### ISSUE TITLE
Subview assign of 1D Strided with stride 1 to LayoutLeft/Right

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1]
I'd like to be able to assign a 1D strided view with stride 1 to LayoutLeft or LayoutRight 1D views. 
This will prevent performance degradation when calling a vector version of a multivector kernel when the number of vectors in the multivector is 1.

**Comment by crtrott** [comment]
I pushed the necessary code and unit tests for it. It is now legal to do stuff like this:
Kokkos::View<double**,LayoutRight> X("X",N,1);
Kokkos::View<double*,LayoutLeft> x_0 = Kokkos::subview(X,Kokkos::ALL(),0);
This will first create a Kokkos::View<double*,LayoutStride> and than assign it to the LayoutLeft.
Using that LayoutLeft view is than much more performant in kernels than using the LayoutStride one which would result from
auto x_0 = Kokkos::subview(X,Kokkos::ALL(),0);
since its indexing is much simpler.

**Comment by mhoemmen** [comment]
Hold on a bit: does 

auto x_0 = subview (X, ALL (), 0);

always result in a LayoutStride View?  If so, I'll have to revisit Tpetra...

**Comment by crtrott** [comment]
No the return type depends on the Layout of X. For LayoutLeft (the tpetra case) this returns LayoutLeft.
For LayoutRight it would return LayoutStride.

**Comment by mhoemmen** [comment]
ok cool thanks!
