### ISSUE TITLE
Make KOKKOS_ALIGN_SIZE a configure-time option

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1004]
Request by @alanw0 .  A user would like to use AVX instructions with explicit SIMD types, with Kokkos::View, with the GCC compiler.  This requires that `KOKKOS_ALIGN_SIZE` be at least 32, for a vector width of 4.  However, `KOKKOS_ALIGN_SIZE` is 64 with the Intel compiler and 16 with all other compilers.  Alan would like one of the following:

  1. `KOKKOS_ALIGN_SIZE` should depend only on the SIMD vector width, not on the compiler.
  2. Users should be able to set `KOKKOS_ALIGN_SIZE` as a configure-time option.

**Comment by alanw0** [comment]
Thanks for lodging this issue Mark. I want to also reference Shreyas @sayerhs, so he can stay updated on this.

**Comment by hcedwar** [comment]
Resolved in PR #1115 
`KOKKOS_MEMORY_ALIGNMENT` is the single configurable memory alignment parameter.
