### ISSUE TITLE
create_mirror should create View with non-const value type

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1005]
The value type of the `View` returned by `create_mirror` should be non-const; however, the current implementation simply copies the input `View` value type.

Reported in #728

**Comment by ibaned** [comment]
I don't think this is true for `create_mirror`. Both `View::HostMirror` and `MirrorType::view_type` are defined as non-const. In pull request #1021 I've added a unit test that confirms this.
It really is only `create_mirror_view` that directly copies the input type when the spaces are the same.

**Comment by hcedwar** [comment]
Test added to verify.
