### ISSUE TITLE
Question: Reasoning behind void type for View.stride

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1009]
I noted that `View.stride()` (see [here](https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_View.hpp#L562)) is `void`, which is inconsistent with `stride_#()`, what is the reasoning behind this choice?

For example, `dimension(#)` and `dimension_#()` are the same type. 

Perhaps there is a newer/better way to get at the strides?

**Comment by hcedwar** [comment]
For LayoutRight and LayoutLeft (the most common) computation of strides requires a computation that must iterate the dimensions.  If strides were computed separately, one rank at a time, then these computations would be repeated for each rank.  Thus most efficient to compute all strides at once.

**Comment by dholladay00** [comment]
That makes sense, so the correct way to use is:

```c++
int strides[View.Rank];
View.stride(strides);
// strides now contains stride for every dimension
```

Or would the intended use look different?

**Comment by crtrott** [comment]
Jup that is right.

**Comment by dholladay00** [comment]
Sounds good to me.

**Comment by mhoemmen** [comment]
Is there still the issue that the `stride` method requires the output array to have at least 8 entries, no matter the rank of the View?

**Comment by dholladay00** [comment]
From my reading of [this](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_ViewMapping.hpp#L975), writes to strides appear to be protected by if statements so that it only needs to be of size `rank`.
