### ISSUE TITLE
OpenMP team_scan hangs with GCC on HSW and maybe others.

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1013]
With high thread count (>8) this test now hangs with some compilers. Looks like a store_fence didn't make it back in the restoration commit which was supposed to restore the previous masters version of team_rendezvous after some performance issues with a new implementation ....

**Comment by hcedwar** [comment]
No longer using a union, no excuse for compiler to emit bad / memory-race code...

**Comment by crtrott** [comment]
Yeah yeah ;-)
