### ISSUE TITLE
Question: Best Way to copy data from file to const device view

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1014]
Currently, I have a number of `const` device views and this is how they are initialized:

```c++
void init_A(Kokkos::View<const double*> A)
{
  Kokkos::DualView<double*> A_h;
  // read from file, fill A_h.h_view;
  deep_copy(A_h.d_view, A_h.hview);
  A = A_h.d_view;
  return;
}
```

What happens when A_h goes out of scope?
More importantly, is there a better/sanctioned way to achieve this (i.e. going back to using views and host mirror views)?

**Comment by ibaned** [comment]
you're passing the parameter `A` by value, so this function cannot change it. What will happen is that the local copy of `A` will be set to `A_h.d_view` and then they will both go out of scope. No effect.

If you start passing `A` by reference, then this will work as expected. `Kokkos::View` is a smart pointer to an allocation, so `A` will increment the reference count of the allocation and the allocation will remain even after `A_h` goes out of scope.

**Comment by dholladay00** [comment]
I should be more explicit:

```c++
struct data {
  View<const double*> A;
  … // lots of other views of various ranks, layouts, etc.
};

void fill_data(data* d)
{
  Kokkos::DualView<double*> A_h;
  // read from file, fill A_h.h_view
  deep_copy(A_h.d_view, A_h.h_view);
  d->A = A_h.d_view;
  return;
}

int main()
{
  data* d = new data;
  fill_data(d);
  delete d;
  d = NULL;
  return 0;
}
```

**Comment by dholladay00** [comment]
Yep, this is a non-issue. I was not actually doing a `delete d;`, so there was lots of "possibly lost" memory. Turns out calling the dtors of the views is helpful. 

Closing
