### ISSUE TITLE
KOKKOS_ENABLE_CUDA_LAMBDA doesn't match KOKKOS_HAVE_CUDA_LAMBDA

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1015]
The CMake option `Kokkos_ENABLE_Cuda_Lambda` is `OFF` by default; it controls the macro `KOKKOS_HAVE_CUDA_LAMBDA`, which thus does not get defined by default.

In contrast, the `KOKKOS_ENABLE_CUDA_LAMBDA` macro is the one that actually controls whether Kokkos supports KOKKOS_LAMBDA with CUDA, and it is defined by default.  (See line 84 of `kokkos/cmake/kokkos.cmake`.)

Are we not supposed to use `Kokkos_ENABLE_Cuda_Lambda` any more?  Just checking :-) .

@tjfulle

**Comment by ibaned** [comment]
I've definitely had cases in the past that broke if I didn't set `-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON` in the Trilinos CMake configure, but I haven't gone through and studied these two systems enough to know how to handle this question.

**Comment by ibaned** [comment]
@mhoemmen `kokkos/cmake/kokkos.cmake` is a separate build system, it doesn't get used by Trilinos (what I call the TriBITS build system, i.e. `kokkos/CMakeLists.txt`). I guess they are inconsistent in what the default behavior is. #1101 is already open to change the default behavior for the TriBITS system, which I think is important for Trilinos.

**Comment by ibaned** [comment]
I think this is the fundamental answer to the question, and the only change we'd like to make is covered by #1101, so I'll close this. Please reopen to discuss further.
