### ISSUE TITLE
View of view initialization

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#102]
Before I dive too deeply into this question, is there a plan to make views of views a standard (non-experimental) feature?

If so, my question involves a view of views:
--

Kokkos::View< Kokkos::View< double*** > ** > B("B", nt, nbr); // num threads x num block rows

--
The outer view dimensions are set above (memory space agnostic). I would now like to set the sizes of the inner views (those that are of `double***'). I would like to be able to initialize those inner views'  sizes without the need for a host mirror (this could be a very large data structure and potentially having a copy that lives both on host and device is not ideal). 

In using a regular for loop to initialize the inner views:

for (int_t i = 0; i < B.dimension_1(); ++i) {
    B(0, i) = Kokkos::View<double***> ("B", 2, h_m(i), h_m(i));
  }

I run into the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::CudaSpace::access_error attempt to execute Cuda function from non-Cuda space
--

How do I go about allocating the memory for these inner views when they live in a non-host memory space? 
host mirror? UVM space? Is there a cleaner way?

**Comment by crtrott** [comment]
The preferred option is to use UVM space or Device/Host pair for the outer view. 

I.e.:
Kokkos::View< Kokkos::View< double*** > ** > B("B", nt, nbr); // num threads x num block 
auto h_B = Kokkos::create_mirror_view(B);
for(int i=0;i<B.dimension_0();i++)
  for(int j=0;j<B.dimension_1();j++)
     h_B(i,j) = Kokkos::View<double***>("B_nested",dims(i,j,0),dims(i,j,1),dims(i,j,2));

Kokkos::deep_copy(B,h_B);
The problem with this approach is that the reference count for the inner parts doesn't go up when you do the deep_copy. Not sure yet how we can fix that.

Another option is to use UVM for the outer view, when you don't need the host mirror. 
There is one more option which is to allocate a large buffer space and then create unmanaged views:

Kokkos::View< Kokkos::View<double**,Kokkos::MemoryTraits<Kokkos::Unmanaged> >*> B();
double* buffer = Kokkos::kokkos_malloc<>("B_buffer",max_size);

Kokkos::parallel_for(N,KOKKOS_LAMBDA(const int& i) {
   B(i) = Kokkos::View<double***,Kokkos::MemoryTraits<Kokkos::Unmanaged> >(&buffer[],dim(i,0),dim(i,1),dim(i,2));
});

I didn't test this but this is roughly how it should work. If I find time I'll test it and update if needed (just wrote this out of my head).

**Comment by dholladay00** [comment]
Suppose that I wanted contiguity of all data in B, can I get that using option 1 (UVM space and having kokkos manage the memory)? Or is the best bet to use unmanaged views? Can I have multidimensional unmanaged views?

**Comment by ndellingwood** [comment]
New view allows this functionality. 
Have consulted with @dholladay00 for proper use.
