### ISSUE TITLE
Problem with dlopen and dlsym in static serial non-cuda build

### ISSUE THREAD

**Issue by gsjaardema** [kokkos/kokkos#1024]
If building kokkos serial with static libraries on a linux system, then the linking of the library may cause undefined symbol references to `dlopen` and `dlsym`:

```
Linking CXX executable KokkosCore_UnitTest_DefaultInit_1.exe
../src/libkokkoscore.so.2.0: undefined reference to `dlsym'
../src/libkokkoscore.so.2.0: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/kokkos/core/unit_test/KokkosCore_UnitTest_DefaultInit_1.exe] Error 1
```

Googling cmake documentation says that this can be fixed by adding `${CMAKE_DL_LIBS}` to the `target_link_libraries()`, but not sure where that goes in a TriBITs based build.   Seems to work OK for a parallel build, but I think in that case the mpi library typically requires libdl, so the error is hidden.

Related to #848.

**Comment by ibaned** [comment]
So, to get this straight, you're building a Kokkos in Trilinos using TriBITS, and you don't have MPI. If I can replicate these undefined references, I'll try to fix the Kokkos TriBITS. Be warned though: I may not get around to this for a while.

**Comment by gsjaardema** [comment]
That's fine.  I just wanted to report so I didn't forget about it.

.. gref

**Comment by crtrott** [comment]
Tribits should enable the DL lib by default. It is a tentatively enabled TPL. Did you explicitly disable it?

**Comment by gsjaardema** [comment]
No, DLlib is enabled and shows up in CMakeCache.txt:  
```
TPL_ENABLE_DLlib:STRING=ON
TPL_TENTATIVE_ENABLE_DLlib:STRING=ON
//ADVANCED property for variable: TPL_TENTATIVE_ENABLE_DLlib
TPL_TENTATIVE_ENABLE_DLlib-ADVANCED:INTERNAL=1
```

Also, this is a build in https://github.com/gsjaardema/seacas (SEACAS) which uses TriBITs.  There may be something that is set up in the top-level of Trilinos which isn't being done in SEACAS but I don't see it yet.  I will try serial build of Trilinos with just SEACAS and Kokkos enabled and see if I can replicate.

**Comment by nmhamster** [comment]
Can you post the actual link line?

**Comment by gsjaardema** [comment]
```cd /scratch/gdsjaar/seacas/build/packages/kokkos/core/unit_test && /projects/sparc/tools/cee-rhel6/cmake-3.5.2/gcc-4.9.3/bin/cmake -E cmake_link_script CMakeFiles/KokkosCore_UnitTest_DefaultInit_6.dir/link.txt --verbose=1
/sierra/sntools/SDK/compilers/gcc/4.9.3-RHEL6/bin/g++    -pedantic -Wall -Wno-long-long -Wwrite-strings   -Wall -Wunused -pedantic -std=c++11 -fopenmp -O3 -DNDEBUG   CMakeFiles/KokkosCore_UnitTest_DefaultInit_6.dir/UnitTestMain.cpp.o CMakeFiles/KokkosCore_UnitTest_DefaultInit_6.dir/default/TestDefaultDeviceTypeInit_6.cpp.o  -o KokkosCore_UnitTest_DefaultInit_6.exe -rdynamic libkokkos_gtest.so.2.0 ../src/libkokkoscore.so.2.0 -Wl,-rpath,/scratch/gdsjaar/seacas/build/packages/kokkos/core/unit_test:/scratch/gdsjaar/seacas/build/packages/kokkos/core/src
../src/libkokkoscore.so.2.0: undefined reference to `dlsym'
../src/libkokkoscore.so.2.0: undefined reference to `dlopen'
```

**Comment by gsjaardema** [comment]
Everything seems to work correctly in Trilinos build so must be something different in the SEACAS setup that I am missing.  You can hold off on looking any on this and I will assume it is an issue on my side.

**Comment by gsjaardema** [comment]
OK, sorry for false alarm. It turns out that SEACAS was missing `DLlib` in the top-level TPLsList.cmake and a `cmake/TPLs/FindTPLDLlib.cmake` at  top-level of the project.   

Everything working now.
