### ISSUE TITLE
seg fault with view of views when copying from CudaSpace

### ISSUE THREAD

**Issue by bfzinser** [kokkos/kokkos#1026]
I get a seg fault running the code below when it tries to copy information back to the host and destroy the view of views at the second to last }. The seg fault does not happen if DefaultExecutionSpace (UVM) is used instead of CudaSpace.

The code below does not demonstrate a lesser (but possibly related) problem, where I do not get a seg fault but I get near-zero values in the host-side mirror inner views. My hope is that this lesser problem will disappear when the seg fault problem is fixed.

```c++
#include <Kokkos_Core.hpp>     

// seg fault if CudaSpace is used. No seg fault if DefaultExecutionSpace (UVM) is used
typedef Kokkos::CudaSpace DeviceSpace;
//typedef Kokkos::DefaultExecutionSpace DeviceSpace;

int main(int narg, char* arg[])
{  

  Kokkos::initialize(narg, arg);
  {

    // Declare view
    const Kokkos::View<Kokkos::View<double*, DeviceSpace>*, DeviceSpace> dd_pointView("dd_pointView", 2);

    // Fill outer view with views
    {
      const Kokkos::View<Kokkos::View<double*, DeviceSpace>*, DeviceSpace>::HostMirror md_pointView = create_mirror_view(dd_pointView);
      md_pointView(0) = Kokkos::View<double*, DeviceSpace>("d_pointView0", 16);
      md_pointView(1) = Kokkos::View<double*, DeviceSpace>("d_pointView1", 7);
      deep_copy(dd_pointView, md_pointView);
    }

    // Fill inner views with data
    {
      Kokkos::parallel_for(16, KOKKOS_LAMBDA( int j) {
        dd_pointView(0)(j) = j;
      });
      Kokkos::parallel_for(7, KOKKOS_LAMBDA( int j) {
        dd_pointView(1)(j) = j;
      });
    }

    // Copy view to host memory; must call deep_copy in order for to get a seg fault
    { 
      Kokkos::View<Kokkos::View<double*, DeviceSpace>*, DeviceSpace>::HostMirror md_pointView = Kokkos::create_mirror_view(dd_pointView);
      deep_copy(md_pointView, dd_pointView);
      printf("seg fault will occur before next print statement\n");
    }
    
    printf("Execution will not reach here because of a seg fault\n");
  }

  Kokkos::finalize();

  return 0;
}
```

**Comment by ibaned** [comment]
May I recommend avoiding Views of Views? Perhaps consider `Crs` or `CrsGraph` to store irregular 2D data?

**Comment by mhoemmen** [comment]
If you want a View of Views, and you're not using UVM, then you'll need to do the following:

  1. Invoke constructors of the inner Views, using "placement new" in a device `parallel_for` loop.
  2. When done with the outer View, invoke destructors of the inner Views, explicitly (`~View`), in a device `parallel_for` loop.

Think really hard about whether you want a View of Views.  You could probably get the effect of a "ragged" 2-D array by using `Kokkos::StaticCrsGraph` (array of offsets, storing start of each inner array in a single 1-D allocation).

**Comment by stanmoore1** [comment]
I've used Views of Views with great success, see https://github.com/lammps/lammps/blob/master/src/KOKKOS/pair_reaxc_kokkos.h#L48 and https://github.com/lammps/lammps/blob/master/src/KOKKOS/pair_reaxc_kokkos.cpp#L369. I didn't have to use placement new or manually invoke the destructor and it works great on GPUs. Not sure what is different in my case.

**Comment by stanmoore1** [comment]
And I'm not using UVM.

**Comment by crtrott** [comment]
Stan you are using a struct of views not a View of Views as far as I can tell. A View of Views is something like this: 

```c++
Kokkos::View<Kokkos::View<double*>*> A("A",N);
```

**Comment by stanmoore1** [comment]
Actually it is a View of a struct of Views, isn't that the same thing?: https://github.com/lammps/lammps/blob/master/src/KOKKOS/pair_reaxc_kokkos.h#L441

**Comment by ibaned** [comment]
https://github.com/lammps/lammps/blob/master/src/KOKKOS/pair_reaxc_kokkos.cpp#L392

I looks like a 2D DualView containing structs containing device Views...    all the initialization takes place using the host part of the DualView and using `modify` and `sync`...   not sure what to think of this

**Comment by stanmoore1** [comment]
@ibaned Right.

**Comment by bfzinser** [comment]
Thank you for all of the prompt responses. It sounds like it would be much safer for someone like me to use a Crs data structure in this instance. It also makes sense because I have some other Kokkos views that might be better as Crs.
