### ISSUE TITLE
Can Kokkos includes detect mismatched versions?

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1031]
If two different Kokkos source trees appear in the `-I` include lists can a means of detection and error generation be inserted?

This was the root cause of #1208

**Comment by mhoemmen** [comment]
Did you mean #1028 ?

**Comment by ibaned** [comment]
I know a way to check when `Kokkos::initialize` runs whether the Kokkos library linked to the program matches the Kokkos headers included in the program. However, I don't know how to detect at compile time that multiple header directories are included. In fact, I don't think it is possible within the C++ code; I would expect that whichever `-I` flag came first would always take precedence, and so it would be indistinguishable from just including that one version of Kokkos. This makes me even more confused about how #1028 ever happened, but I suspect horrible build system setups that move files around have something to do with it....

**Comment by mhoemmen** [comment]
@ibaned wrote:
> However, I don't know how to detect at compile time that multiple header directories are included.

The only way I can imagine, is for Kokkos to generate a header file at installation time, with a version key in it.  All includes would then check that key at compile time.

**Comment by mhoemmen** [comment]
@ibaned might make sense to have a "wontfix" label for issues like this
