### ISSUE TITLE
promotion of 2.04.00 : develop->master 

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1032]
Track progress for integration testing, resulting in 2.03.15

**Comment by ndellingwood** [comment]
Kokkos develop sha 7e60cc223f0100f3bd5b2cc5ede6b1d5be71dbb0 tested
test_all_sandia passed all tests on White and Bowman

**Comment by ndellingwood** [comment]
Trilinos integration tests on shepard with pthreads and serial result in no new build or test failures.
Pristine   sha 7b07aa9c6bac51a8397706e3adb1ea158a7e765c

Tests are building on White for openmp and cuda testing.

**Comment by ndellingwood** [comment]
OpenMP tests on White were successful, no new build or test failures.

**Comment by ndellingwood** [comment]
Issues running Cuda tests on White; accepted PR #1034 and restarted Trilinos integration tests on White (OpenMP, Cuda) and Shepard (Serial, Pthread).

**Comment by ibaned** [comment]
The commit before #1034 was accepted (cadb2d67fab426dbb0cec3f55d9e4c61199179d6) passed `test_all_sandia` on `kokkos-dev`. It includes #1030.

**Comment by ndellingwood** [comment]
The restarted tests failed at configuration due to the `Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA`

Issue tracked in #1035

**Comment by ibaned** [comment]
Change needed to Tpetra example due to meaning change of `KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA`. New Trilinos branch `kokkos-promotion` made to accumulate needed changes to Trilinos, commit added.

**Comment by ndellingwood** [comment]
Restarting tests with kokkos-promotion branch.

**Comment by ndellingwood** [comment]
White + OpenMP test resulted in no new test failures; White + Cuda, Shepard + Pthread and Serial still in progress.

**Comment by ndellingwood** [comment]
Shepard + Pthread completed without any new test failures; no specific build errors are recorded in the *_build.errors files, but both builds reported an error and exited with exit code 2
e.g.
`error: node39: task 0: Exited with exit code 2`

**Comment by ibaned** [comment]
@ndellingwood this is the test that got modified for the lambda macro. Open an issue and paste the output from running just this test?

**Comment by ndellingwood** [comment]
@ibaned Just submitted issue #1040; will assign to you since you are familiar with lambda macro changes.

**Comment by ndellingwood** [comment]
Restarted White + Cuda tests with @ibaned fix in `kokkos-promotion` branch of Trilinos

**Comment by ndellingwood** [comment]
White + Cuda had identical build errors with pristine (Trilinos' develop branch) vs updated (kokkos-promotion branch + Kokkos snapshot) copies of Trilinos;
Updated tests had one failure not seen in the pristine copy - Amesos2_CrsMatrix_Adapter_Consistency_Tests_MPI_4
Manually rerunning the Amesos2 adapter tests showed the test failed for both pristine (pre-snapshot) and updated copies of Trilinos

**Comment by ndellingwood** [comment]
For reference:
Trilinos build issues will be filed for the following (possibly due to a missing ExecutionSpace template parameter):
intrepid2/refactor/unit-test/Orientation/Serial/test_orientationtools_modify_basis_hgrad.cpp
intrepid2/refactor/unit-test/Orientation/Serial/test_orientationtools_coeff_matrix.cpp

**Comment by ndellingwood** [comment]
For reference:
Shepard builds exited with the following message:
`error: node39: task 0: Exited with exit code 2`

`SHARED=ON` for these tests, but the boost module is not compatible
`ld: /home/projects/x86-64-haswell/boost/1.59.0/openmpi/1.10.0/intel/16.1.056/lib/libboost_program_options.a(cmdline.o): relocation R_X86_64_32 against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC`

**Comment by ibaned** [comment]
`checkin-test-sems.sh`: one test failure, known issue introduced into Trilinos develop before us (trilinos/Trilinos#1615). Force pushed snapshot into Trilinos, pushed Kokkos master. Promotion complete.

**Comment by bmpersc** [comment]
@ibaned you have this linked to trilinos/Trilinos#1615, but you made no references in that ticket about this. You did, however, comment in trilinos/Trilinos#1614 about that issue blocking the Kokkos integration. Is this just a small typo of numbers or did 1615 actually impede this?

**Comment by ibaned** [comment]
It is confusing, but I think this is what happened: I though trilinos/Trilinos#1614 would cause trouble, but in the end it didn't, I'm guessing because the checkin script enabled Aprepo. trilinos/Trilinos#1615, however, ended up being the one that actually caused trouble, since that one failing test prevented the checkin script from pushing.
