### ISSUE TITLE
Oversubscribe warning wrong?

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1033]
I'm running on a SandyBridge CPU node which has 16 physical cores. I'm running Kokkos OpenMP with 8 MPI ranks x 2 OpenMP threads per node = 16 processes, which is the same as the number of physical cores on SandyBridge. But I'm still getting this error:

<pre>
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
  process threads available :   1,  requested thread :   2
</pre>

Any ideas?

Thanks

**Comment by stanmoore1** [comment]
Similarly, on KNL if I run 64 MPI x 4 OpenMP threads, which is definitely not oversubscribing the cores, I get this warning:

<pre>
  process threads available :   1,  requested thread :   4
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
</pre>

**Comment by ibaned** [comment]
Although @dsunder is way better suited to answer this question, I would start by asking whether you're using the MPI options to bind each MPI rank to an entire core, e.g. `--bind-to core` ?

**Comment by stanmoore1** [comment]
For SandyBridge, using either `--bind-to socket` or `--bind-to core` both give the same oversubscribe warning. For KNL I'm using SLURM srun.

**Comment by stanmoore1** [comment]
For KNL, it is OK to bind to core since each core has 4 hyperthreads, but the Kokkos warning doesn't seem to take that into account.

**Comment by ibaned** [comment]
I think it does... I think one possibility is that MPI is binding the process to only one hyperthread, in which case Kokkos is warning about a real problem, at least on KNL.

It may also just be the case that its detection is wrong somehow... might be useful to make the printed message more verbose.

**Comment by stanmoore1** [comment]
My personal preference would be not to get these warnings from Kokkos at all, and put the onus on the user to ensure they aren't oversubscribing. But others may feel differently.

**Comment by ibaned** [comment]
Most users aren't experienced enough to know all the details, and its easy for the most experienced user to forget a flag here and there.

Configurability is the way forward here, and again only @dsunder knows the status of the feature set that would both ensure warnings are only printed on one rank and allow users to disable all warnings via an environment variable. I believe the merge of these features is held up for some reason...

**Comment by stanmoore1** [comment]
> I think it does... I think one possibility is that MPI is binding the process to only one hyperthread, in which case Kokkos is warning about a real problem, at least on KNL.

That seems to be the case for KNL, I was using `--cpu_bind=rank`, and it is slower than `--cpu_bind=core`, which doesn't give the warning, so maybe it was oversubscribing.

For SandyBridge, I've tracked it down to whether or not I `export OMP_NUM_THREADS=...` or not. In LAMMPS we can specify the number of threads on the command line without setting `OMP_NUM_THREADS`. That seems to be confusing the Kokkos warning.

**Comment by stanmoore1** [comment]
I'm fine with warnings as long as they are legit. I had a problem with a Kokkos warning in the past that was bogus and I just ended up commenting out that code in the LAMMPS copy of the Kokkos library. I believe that is fixed now though. The other problem with the Kokkos warnings are every single MPI rank prints out the same thing, though I believe that is being worked on.

**Comment by ibaned** [comment]
> That seems to be the case for KNL, I was using `--cpu_bind=rank`, and it is slower than `--cpu_bind=core`, which doesn't give the warning, so maybe it was oversubscribing.

Yep, I think thats the answer there. Stick to `--cpu_bind=core`, it was oversubscribing in a binding sense, your 4 software threads were bound to one hyperthread.

> For SandyBridge, I've tracked it down to whether or not I `export OMP_NUM_THREADS=...` or not. In LAMMPS we can specify the number of threads on the command line without setting `OMP_NUM_THREADS`. That seems to be confusing the Kokkos warning.

I'm not sure which of those takes precendence anymore, though I think we ought to print another warning in the case that they ask for different things. For now be careful to specify only one of them.

> The other problem with the Kokkos warnings are every single MPI rank prints out the same thing, though I believe that is being worked on.

Yea... with any luck that will go into develop after the current promotion. Unfortunately its lumped in with much more serious changes, so I'm guessing they're being evaluated before merging...

**Comment by stanmoore1** [comment]
> I'm not sure which of those takes precendence anymore

The LAMMPS command line takes precedence over the `OMP_NUM_THREADS` variable. But as long as those are consistent I don't get the warning for SandyBridge.
