### ISSUE TITLE
Trilinos configuration fails to recognize Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1035]
Configuring Trilinos with the Kokkos snapshot fails due to the `Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA` variable not being recognized.

Configuration error output:
```
CMake Error at cmake/tribits/core/utils/AssertDefined.cmake:79 (MESSAGE):
  Error, the variable Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA is not defined!
Call Stack (most recent call first):
  packages/tpetra/core/example/Lesson07-Kokkos-Fill/CMakeLists.txt:2 (ASSERT_DEFINED)
```

**Comment by ibaned** [comment]
Change needed to Tpetra example due to meaning change of KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA. New Trilinos branch kokkos-promotion made to accumulate needed changes to Trilinos, commit added.

Spot check on Trilinos running now, but integration testing can be restarted

**Comment by ndellingwood** [comment]
Configuration successful, restarting tests. Thanks for quick fix @ibaned !

**Comment by ibaned** [comment]
So far we think this is resolved. If there is still a piece of this to fix we'll reopen.
