### ISSUE TITLE
Kokkos::Impl::view_verify_operator_bounds not checking number of indices

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#1036]
Today I spent some time tracking down a bug, which ultimately was me using too many indices to access a view. I figured this should be checked in debug mode if KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK is defined. However, it appears it's not. The reason, I think, is that the recursive routine only checks  `size_t(i) < map.extent(R)`, for all dimensions. From my understanding of Kokkos views, I think the problem is that for the "unused" ranks, the dimension is set to ~size_t(0), which is a large number, and therefore the test above will always pass. If one is "unlucky" and the extra index is the last (or at least in a position that does not cause any other dimension index to go out of bounds), then this error will go undetected.

Assuming what I said is correct, I would fix it by either stopping the recursion when R is equal to the view rank, or I would add a check to ensure that map.extent(R) is not equal to ~size_t(0). I know that there are customers of Kokkos that use it in funky ways, so maybe the first check above may break their code, so perhaps the second is safer. However, some sort of check needs to be done for the "simple" use of views, to ensure one does not pass too many indices.

**Comment by mhoemmen** [comment]
The point of this feature is to support `value_type` with a run-time dimension, as found in Trilinos' Stokhos package.

**Comment by bartgol** [comment]
@mhoemmen Are you saying that if the value_type is a vector-like type, then I can do

```
Kokkos::View<SomeVectorLikeType[10]> v("");
v(0,0) = blah;
```
? That seems to make the interface quite confusing... I would much prefer the user to explicitly access the underlying type after extracting it from the view, like `v(0)[0]`, or something like that.

**Comment by bartgol** [comment]
@mhoemmen Are you saying that if the value_type is a vector-like type, then I can do

```
Kokkos::View<SomeVectorLikeType[10]> v("");
v(0,0) = blah;
```
? That seems to make the interface quite confusing. I would much prefer the user to explicitly access the underlying type after extracting it from the view, like `v(0)[0]`, or something like that.

Alternatively, if this check must stay the same to allow this type of views, isn't it possible to detect at compile time whether the view is of this "fancy" type, or just a "normal" view, and check the number of passed indices for the "normal" view case?

**Comment by ibaned** [comment]
For what its worth, I agree philosophically with @bartgol's objection to Views of indexable `value_type` having this special behavior, but Trilinos has so eargerly adopted it (and likely requested it in the first place), that its here to stay. I hope we can still implement a check on the rank for this basic mis-use case being described.

**Comment by bartgol** [comment]
Would it be too much work to add an extra template argument to the view traits that specifies whether the view rank is static or dynamic? That way one could write two specialization of the bounds check, one for the basic/standart case, and one for the advanced/funky one.

Perhaps one could add a template argument to the layout structures. Something along the line of (mimicking MemoryTraits) 

```
enum RankEnforcementFlags
{
  Dynamic = 0;
  Static = 1;
}

template<unsigned T>
struct LayoutTraits
{
   Dynamic = T & (unsigned)Kokkos::Dynamic;
   Static = T & (unsigned)Kokkos::Static;
};

typedef Kokkos::LayoutTraits<Kokkos::Dynamic> DynamicLayout;
typedef Kokkos::LayoutTraits<Kokkos::Static>      StaticLayout;

template<typename LayoutTraits=DynamicLayout>
struct LayoutLeft
{
blah
};
```

So this way the default will stay the same as the current one, while also allowing a compile time check on the type of Layout. One person interested in enforcing a compile time rank (and number of arguments in the () operators) could do so by using a layout tructure with StaticRank traits.

Also, there's probably a more concise way to do so, I just throw there an idea following the traits pattern so vastly used in Kokkos...

**Comment by mhoemmen** [comment]
@bartgol @ibaned Just to clarify, I'm not saying that I _like_ this feature ;-)  There should be a way to distinguish, based on `value_type`, whether the run-time dimension makes sense, as mentioned in @bartgol 's comment above.

**Comment by hcedwar** [comment]
When `rank() <= r` then `1 == extent(r)` , at least it is supposed to be and is a bug if not.  There is no unit test that verifies requirement, so a unit test needs to be added.
When `KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK` all extra indices are supposed to be verified as equal to zero.
The requirement to accept **more** indices than the rank of the array did indeed come from Trilinos packages.  The agreement was that such indices **must be** zero.

**Comment by bartgol** [comment]
@hcedwar You are right. And the extent of the unused ranks is indeed 1. The issue appears to be disappeared now, though very little has changed. I mainly pulled the new master, but I doubt this was the issue. I must have done something else somewhere in my configuration.

I apologize for the false alarm.

**Comment by hcedwar** [comment]
Minor enhancement needed to unit tests to verify correctness of extents beyond rank.

**Comment by hcedwar** [comment]
Need to re-discuss with Intrepid to find a way for Intrepid only to have this relaxation.

**Comment by ibaned** [comment]
Will be done via #1333. Once #1333 is `InDevelop`, this will be too.
