### ISSUE TITLE
Prepare for v3: Update license for NTESS

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1037]
Update all source files' copyright statement as required for upcoming v3 copyright assertion.

Replace:
```
//                           Kokkos v. 2.0
//              Copyright (2014) Sandia Corporation
//
// Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
// the U.S. Government retains certain rights in this software.
```
with:
```
//             Kokkos v. 3.0
//  Copyright 2017 National Technology & Engineering Solutions of Sandia, LLC (NTESS). 
//  Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government 
//  retains certain rights in this software.
```

**Comment by hcedwar** [comment]
After copyright statement updated, create physical CD for v3 copyright assertion process.

**Comment by hcedwar** [comment]
?? 2014 ??

**Comment by dalabre** [comment]
At least 186 files; I'll get it done with sed/awk.

**Comment by crtrott** [comment]
This patch should NOT go into the public repository until after the copyright is actually asserted ...

**Comment by dalabre** [comment]
I will keep it in a branch until that time.

**Comment by dalabre** [comment]
@crtrott  @ibaned  Testing _sed_ and _shell script_ to edit **Copyright statement** for 934 kokkos source files. Both work but _sed_ is 'klunky' without scripting the process, so it then becomes the second method (_shell script_, or _python script_). 

There are also a number of **Trilinos Copyright** statements in the files of the **cmake** directory. Has Trilinos already updated their Copyright statement?

**Comment by ibaned** [comment]
@dalabre I think all Trilinos copyright statements should be replaced with Kokkos copyright statements.

**Comment by dalabre** [comment]
@crtrott @ibaned   I will include the Trilinos statements.

The kokkos/Copyright.txt  and kokkos/LICENSE files differ by this line:

`// Kokkos is licensed under 3-clause BSD terms of use:`

in LICENSE but not Copyright.  Should these files be identical?

**Comment by ibaned** [comment]
I'm not sure why we have both, only one should be necessary. I think LICENSE is the more common name.

**Comment by ndellingwood** [comment]
This is discussed in the more recent issue #1982 and tracked there.

**Comment by ndellingwood** [comment]
Completed by #2752
