### ISSUE TITLE
Error out when the number of threads is modified after kokkos is initialized

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#104]
In openmp, if the calling code changes the number of threads after initializing kokkos, we'd like the next parallel dispatch to throw an error notifying that the number of threads was changed and that this is not allowed by kokkos.

**Comment by nmhamster** [comment]
I think the lightest overhead way to do this is put the error checking into a KokkosP tool and have it do that if s problem exists?

This would mean we don't need constant queries of the runtime that may prevent optimization.

Thoughts?



--
Si Hammond
Scalable Computer Architectures
Sandia National Laboratories, NM
[Sent remotely, please excuse typing errors]
________________________________

**Comment by crtrott** [comment]
Do we have an estimate on what the cost for that call is? We could also have it as a debugging option in Kokkos.

**Comment by nmhamster** [comment]
Will vary by runtime. Its not the call overhead thats the problem, its that there is an external function call in the middle of something we want optimized :-(.

**Comment by nmhamster** [comment]
Plus, I think recompiling for this is nuts and a waste of time when we can literally set an environment variables and run the detect.

**Comment by crtrott** [comment]
Sure it is certainly a viable option. Might actually be a sensible way to push more debugging options into such external tools.

**Comment by crtrott** [comment]
Me or Nathan is gonna check the overhead for doing the test (how is the empty kernel launch rate changed). If it is negligible add the check directly in Kokkos, alternatively add a tool.

**Comment by hcedwar** [comment]
Fixed by adding verification that thread count is unchanged when verifying that OpenMP backend is initialized.
