### ISSUE TITLE
ROCm:  assert in perf_test gramshmidt

### ISSUE THREAD

**Issue by chipfreitag** [kokkos/kokkos#1045]
Test now using parallel reduce with null result_view data pointer.

**Comment by chipfreitag** [comment]
Have to also comment out PerfTest_CustomReduction to get the test to build.

**Comment by hcedwar** [comment]
"InDevelop" label for when the fix has been pushed into develop branch.

**Comment by chipfreitag** [comment]
Got it.  I have created an issue branch with a fix.  I will issue a pull request to develop.

**Comment by masterleinad** [comment]
ROCm is not supported anymore.
