### ISSUE TITLE
reduction_identity<T>::max wrong for floating point numbers

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1048]
It is using DBL_MIN etc. whereas it should use -DBL_MAX since DBL_MIN is the smallest POSITIVE number larger than zero representable by a double (2.2e-308 or so).

**Comment by crtrott** [comment]
I am pushing this fix also directly to trilinos, since it blocks integration of KokkosKernels. This thing made Tpetra tests fail after updating KokkosKernels in Trilinos.

**Comment by mhoemmen** [comment]
happy to help find this :)
