### ISSUE TITLE
kokkos complex operator overloading

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1052]
This separate realtype can be problematic if someone overload the complex operator.
Imagine that someone overload the operator with a SIMD object and perform division with complex 
number. Then, the compiler think the overloading is ambiguous as I provide ``operator / (const complex<RealType1> &x, const RealType2 &y)`` where ``RealType2 is SIMD type``.

```
// in division, you use different real type and this would be confusing if 
// one (like me) want to overload the operator with custom one
template<class RealType1, class RealType2>
KOKKOS_INLINE_FUNCTION
complex<RealType1>
operator / (const complex<RealType1>& x, const RealType2& y) {
  return complex<RealType1> (real (x) / y, imag (x) / y);
}

template<class RealType1, class RealType2>
KOKKOS_INLINE_FUNCTION
complex<RealType1>
operator / (const RealType1& x, const complex<RealType2>& y) {
  return complex<RealType1> (x)/y;
}

// here you use the same real type 
template<class RealType>
KOKKOS_INLINE_FUNCTION
complex<RealType>
operator * (const complex<RealType>& y, const RealType& x) {
  return complex<RealType> (x * y.real (), x * y.imag ());
}
```

**Comment by crtrott** [comment]
Wait I am not sure that we want to change this. There is a purpose to this. For example a=b/2; where a and b are complex<double>. Also if you provide a non overloaded operator that should have precedence shouldn't it?

**Comment by kyungjoo-kim** [comment]
My problem is that I have an operator with SIMD and complex scalar
```
template<typename T>
SIMD<Kokkos::complex<T> > operator / (Kokkos::complex<T> &a, SIMD<Kokkos::complex<T> > &b);

/// this pattern coincide with the following pattern
template<class RealType1, class RealType2>
KOKKOS_INLINE_FUNCTION
complex<RealType1>
operator / (const complex<RealType1>& x, const RealType2& y);

/// with RealType1 is T and RealType2 is SIMD<Kokkos::complex<T> >
```

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> This separate realtype can be problematic if someone overload the complex operator.

I can think of two different ways to fix this.  

1. Force RealType1 and RealType2 to be the same (RealType), and make the compiler deduce conversions from, say, float to double (e.g., `operator/ (const complex<double>&, const float&)`).

2. Use `std::enable_if` in the definition of `operator/`, in order to constrain RealType1 and RealType2 to be real and in the same numerical tower.

For example:
```
template<class RealType1, class RealType2>
KOKKOS_INLINE_FUNCTION
complex<RealType1>
operator / (
  const complex<RealType1>& x,
  const RealType2& y, 
  typename std::enable_if<
    std::is_floating_point<RealType1>::value && 
    std::is_floating_point<RealType2>::value && 
    std::is_convertible<RealType2, RealType1>::value 
  >::type* = 0
);
```

**Comment by kyungjoo-kim** [comment]
Thanks. The second enable_if option seems to be the solution. I guess that kokkos want to do this way not to abuse complex division (more expensive than real division). If all agree with the solution, can we make all complex operator overloading with this enable_if pattern (including multiplication that requires the same real type) ?

**Comment by etphipp** [comment]
I think stylistically it is better to put the enable_if in the return type:

```
template<class RealType1, class RealType2>
KOKKOS_INLINE_FUNCTION
typename std::enable_if<
    std::is_floating_point<RealType1>::value && 
    std::is_floating_point<RealType2>::value && 
    std::is_convertible<RealType2, RealType1>::value,
    complex<RealType1>
  >::type
operator/ (
  const complex<RealType1>& x,
  const RealType2& y, 
);
```

I definitely think Kokkos needs to constrain its overloads like this because otherwise it is impossible to use the code with other user-defined scalar types.  Basically any time you have an unconstrained template parameter in an overload of an arithmetic function, you need to constrain through enable_if.

**Comment by hcedwar** [comment]
@etphipp As soon as we dump gcc 4.7 then yes.  In some cases gcc 4.7 couldn't handle enable_if in the return type.

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> The second enable_if option seems to be the solution.

I would actually prefer the first solution, because it likely would give shorter build times.  Here's why I think so:

  1. It needs fewer template parameters.
  2. It relies on SFINAE; the compiler has to see that "substitution failed" in order to reject that option, and evaluating the potential substitution requires extra lookups for the traits.

What do you think?

**Comment by mhoemmen** [comment]
@kyungjoo-kim wrote:
> The reason that I prefer the second option is because it allows mixed precision computation

This is a good point.  The first option might lose precision, e.g., for the following operation:
```
Kokkos::complex<float> z_f (..., ...);
double d = ...;
Kokkos::complex<float> w_f = z_f / d;
```

**Comment by kyungjoo-kim** [comment]
@hcedwar @mhoemmen @etphipp @crtrott  I put all the names for email notification.

If all of your agree to change the operator for with ``enable_if`` to constrain overloading template parameters, could we also allow different real types for other operators ? complex multiplication, add, minus ? Is this way of overloading also consistent to std complex ?

**Comment by hcedwar** [comment]
@kyungjoo-kim 
Related question: Have you considered the tradeoffs between `SIMD<complex<double>>` versus `complex<SIMD<double>>` ?

**Comment by etphipp** [comment]
A couple of comments:

- It isn't completely obvious to me that the enable_if approach is necessarily slower.  I believe SFINAE throws overloads out of the pool of candidate overloads pretty early in the overload resolution process, which saves the compiler from having to explore all possible conversions of arguments for each overload.  Furthermore, it saves the compiler from having to generate conversion code, and likely results in faster code.  However I really don't have a strong opinion on how you implement this.
- For the enable_if, the is_floating_point<> traits seem overly restrictive.  RealType1 is already constrained to be a valid template parameter for complex, so you don't need to duplicate any of those restrictions here.  Furthermore, RealType2 could be an ordinal type, which is perfectly valid (e.g., a/2 where a is complex).  The is_convertible<> trait is sufficient for what would be valid arguments to this function.

**Comment by etphipp** [comment]
Are there complex-valued SIMD vector instructions?  If so, you want the first one.  If not, the second.

**Comment by kyungjoo-kim** [comment]
@hcedwar 

Yes I consider both. I choose ``SIMD<complex<double> >`` because I can access an individual complex value. In this way ``View<SIMD<complex<double> >** >`` can be reinterpreted as ``View<SIMD<complex<double> >***>`` with appropriate stride layout. However, the other one cannot be inter-operatible with standard Kokkos view.

@etphipp 

There is no complex vector instruction but I wrote one with
```
SIMD<Kokkos::complex<double>,4> operator * (SIMD<Kokkos::complex<double>,4> const &a, SIMD<Kokkos::complex<double>,4> const &b) {
     const __m512d                                                                                                                                                                                  
        as = _mm512_permute_pd(a, 0x55),                                                                                                                                                             
        br = _mm512_permute_pd(b, 0x00),                                                                                                                                                             
        bi = _mm512_permute_pd(b, 0xff);                                                                                                                                                             
      return _mm512_fmaddsub_pd(a, br, _mm512_mul_pd(as, bi));      
}
```

FYI: Testing with std::complex, it does not allow mixed precision arithmetic. 
```
std::complex<double> a, b, c;
int i;
c = a * b; // working
c = a * i; // not working
c = i * a; // not working
c *= b; // working
c *= i; // working
```

**Comment by vbrunini** [comment]
@etphipp

Check out https://www.youtube.com/watch?v=EtU4RDCCsiU 

SFINAE is apparently the most expensive metaprogramming technique in terms of compile time by a significant margin.

**Comment by kyungjoo-kim** [comment]
@hcedwar 

When do we drop gcc 4.7 ? Putting third dummy argument is not valid as operator +,-,*,/ takes two argument only. Putting the second argument with enable_if is not valid as it cannot deduce the type. The way that I figure out is to put  ``enable_if<convertible<Ta,Tb>::value,r_type>`` as its return type. As you mentioned, this option is not allowed until gcc 4.7 is present. 

@mhoemmen @etphipp @crtrott 

It is still needs to restrict division overloading. The first option @mhoemmen suggested (using the same real type) is realistic in this situation. Question: Do you think that mixed precision capability is or will be important in some applications ? A kind of surprising as std::complex does not allow mixed precision either. There should be a reason not to do so in std.

**Comment by mhoemmen** [comment]
@etphipp wrote:
> For the `enable_if`, the `is_floating_point<>` traits seem overly restrictive....

This is a good point.  The only restriction on the denominator type DenomType is that the result of a RealType (template parameter of `Kokkos::complex`) divided by a DenomType, needs to be assignable to a RealType.  We only need `enable_if` to help the compiler disambiguate from a complex divided by a complex, so the `enable_if` just needs to test that DenomType is not complex.

**Comment by etphipp** [comment]
Two comments:

First, have you tried it with gcc 4.7?  I use enable_if<> in the return type all over the place in Sacado, and don't have any issues with gcc 4.7.  I even use a hand-rolled enable_if for non-C++11 builds, and even gcc 4.4 doesn't have a problem with it.

Second, you don't need to disambiguate the case when DenomType is complex.  You have another overload for when both arguments are complex, and that overload will be more specialized than the two versions that take arbitrary template parameters for the numerator/denominator. When the arguments are complex, the overload resolution process chooses the more specialized one that matches the template parameters.  This is exactly how I implement every (binary) arithmetic function in Sacado.

**Comment by kyungjoo-kim** [comment]
@etphipp 

Yes I tried with gcc 4.7. I also confirmed that it does not have an issue about enable_if in the return type. However, as @hcedwar  mentioned, Kokkos would not choose to implement that way.

 I agree with your second comment too.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Care to submit a pull request?  Sounds like we've moved towards consensus on the approach.

**Comment by kyungjoo-kim** [comment]
Okay. I will write a draft and submit pull request.

**Comment by kyungjoo-kim** [comment]
Done. Could one put reviewers for this PR (I cannot assign reviewers) ?

**Comment by ibaned** [comment]
For bookkeeping, the PR is #1059. Unfortunately GitHub doesn't create links for issue numbers that appear in the *title* of a PR, the issue number needs to be in the description. Who do you want as reviewers?

**Comment by mhoemmen** [comment]
@kyungjoo-kim @ibaned I can't actually assign myself as a reviewer, alas.  Please feel free to assign me.  Thanks!

**Comment by hcedwar** [comment]
Not closed until promoted to master branch.

**Comment by crtrott** [comment]
The pull request #1059 broke trillions builds since it disabled stuff like this:
```c++
Kokkos::complex<double> a(1.0,2.0);
std::complex<double> b(2.0,0.5);
a*=b;
```

Opening a new issue to trick the fix for that ...
