### ISSUE TITLE
MDRange policy doesn't support lambda reductions

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1054]

**Comment by hcedwar** [comment]
@ibaned : Need clarification, is this when using a lambda body with a custom reduction?

**Comment by ibaned** [comment]
Correct, lambda body with either custom reducers, Kokkos-provided reducers, or the default reducer which is a sum. In fact, I think these compile with host backends but don't seem to compile with the CUDA backend.

**Comment by ndellingwood** [comment]
See #1379

**Comment by ndellingwood** [comment]
PR #1380 in for this issue.

**Comment by ndellingwood** [comment]
Fix in PR #1380 spot checked with test_all_sandia and should be ready for merge.
