### ISSUE TITLE
MDRange outer iterations produce 'team members'

### ISSUE THREAD

**Issue by bjoo** [kokkos/kokkos#1055]
Further to discussion with @dsunder at the NASA hackathon, I am leaving this here as a placeholder that it may be useful to have a version of MDRange where the outer iteration produces team members. The rationale is that: a) this would allow vectorization/simd-ization and b) use of shared memory in the blocks produced by the MDRange...

**Comment by Char-Aznable** [comment]
I'd like this feature too and one that can allow MDRange to be carried out by members of a team only, i.e., a multidimensional TeamThreadRange

**Comment by ajpowelsnl** [comment]
Reopen if necessary.  We believe the cost of recomputing is small (i.e., multidimensional index from league rank), if you need nested parallelism per iteration.
