### ISSUE TITLE
parallel_for<MDRangePolicy slower than Experimental::md_parallel_for

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1056]
During our hackathon using BoxLib, for kernels that always use `MDRangePolicy`, switching from `Kokkos::parallel_for` to `Kokkos::Experimental::md_parallel_for` speeds up the entire application from 0.3 seconds to 0.2 second (50% speedup).

Our initial interpretation is that the extra layer of abstraction, even though they should be static function calls that in theory can be inlined, do impede compiler optimizations. May be related to "inline depth counter"s in compilers.

More in-depth analysis should be done to determine why this is slower (it can be entirely reproduced using open-source code and Sandia machines).

Edit: naming: `MDRangePolicy`

**Comment by ibaned** [comment]
zronaghi/BoxLib@f0929617

(not that the change of iteration "layout" in this commit was made first and tested separately; it doesn't alter the runtime).

**Comment by ndellingwood** [comment]
@ibaned which compiler/architecture did you notice this for?

**Comment by ibaned** [comment]
This is with the CUDA backend on a single P100 GPU

**Comment by ndellingwood** [comment]
For the `md_parallel_for` I used a stripped down impl of `CudaParallelLaunch` because of problems trying to include `Kokkos_CudaExec.hpp` (which contains `CudaParallelLaunch` definition). 
I traced the discrepancy in performance to the call in `CudaParallelLaunch` to `KOKKOS_ENSURE_CUDA_LOCK_ARRAYS_ON_DEVICE()` [here](https://github.com/kokkos/kokkos/blob/51e7b25a39eab309fb703e8314c3bcbd98c58a8d/core/src/Cuda/Kokkos_CudaExec.hpp#L230) and [here](https://github.com/kokkos/kokkos/blob/51e7b25a39eab309fb703e8314c3bcbd98c58a8d/core/src/Cuda/Kokkos_CudaExec.hpp#L266); the overhead is noticeable for smaller ranges. 

@crtrott pointed out that the call to `KOKKOS_ENSURE_CUDA_LOCK_ARRAYS_ON_DEVICE()` becomes a NOP when relocatable device code (rdc) is enabled, which would resolve the performance issue. Trying to get the BoxLib fork compiled with rdc enabled now.

**Comment by ibaned** [comment]
wow... so a call to `cudaMemcpyToSymbol` (which is what that macro expands to) before each kernel slows down BoxLib by 50%... pretty good to know. I guess part of the reason is that any `cudaMemcpy` operation is a synchronization point...

RDC is okay, but I'm also wondering if we should have a compile-time option to turn off the whole lock arrays feature. There are many applications including BoxLib and my own codes that will never try to use a Kokkos atomic operation on a type bigger than 64 bits.

**Comment by crtrott** [comment]
Its not just atomics larger than 64 bits. It is also the unique token feature, and you may not know whether you ever do atomics on things larger than 64 bit. For example internally reductions of structs may or may not use that (i.e. parallel reduce of a complex<double>), and other operations may use double pointer swaps which require 128bit CAS which on GPUs is implemented using the lock arrays. So no, I don't think that is ever a good idea. That said: some changes about two months ago did insert an additional CUDA_SAFECALL around that memcpy, which probably adds additional overhead.

**Comment by crtrott** [comment]
Also: if this launch overhead adds 50% to your run because launching a kernel went from 30us to 60us, you are completely launch overhead bound and probably don't get good performance on GPUs anyway.

**Comment by ibaned** [comment]
@ndellingwood can you try removing the `CUDA_SAFECALL` wrap that @crtrott mentioned? Its probably helpful to know how much of the overhead that thing is responsible for

**Comment by ndellingwood** [comment]
BoxLib times below are with `DEBUG=false` and `KOKKOS_DEBUG = no` on White with xl/13.4 and cuda/8.0.44

Time using `parallel_for`, no changes to `CudaParallelLaunch`: **0.39**

Time using parallel_for, comment out `KOKKOS_ENSURE_CUDA_LOCK_ARRAYS_ON_DEVICE()`: **0.28**
* The `KOKKOS_ENSURE_CUDA_LOCK_ARRAYS_ON_DEVICE()` call results in the discrepancy in performance between `parallel_for` and `md_parallel_for` calls. 

Time using `parallel_for`, removing `CUDA_SAFE_CALL` from `KOKKOS_COPY_CUDA_LOCK_ARRAYS_TO_DEVICE` (called by `KOKKOS_ENSURE_CUDA_LOCK_ARRAYS_ON_DEVICE()`): **0.38**

**Comment by crtrott** [comment]
What is the time with relocatable device code enabled?

**Comment by ndellingwood** [comment]
I haven't been able to get the code to compile with rdc; linker errors about multiple definitions as well as a compiler error. I used `KOKKOS_CUDA_OPTIONS=enable_lambda,rdc` in the makefile, but no success with compilation.

**Comment by hcedwar** [comment]
Issue has been identified and is not a bug.  The prior mdrange functions were not synchronizing lock arrays for atomics on large types.
