### ISSUE TITLE
ROCm:  example/fixture directory not building

### ISSUE THREAD

**Issue by chipfreitag** [kokkos/kokkos#1058]
The nightly test procedure we use is:

git clone -b develop https://github.com/kokkos/kokkos
mkdir build && cd build
../kokkos/generate_makefile.bash --compiler=/opt/rocm/hcc/bin/clang++ --arch=Fiji --with-rocm
make -j 16 test

right now the performance tests won't build but I can patch them out, and look for the next set of problems.
The next problem is that example/fixture does not build.

The immediate cause is traced back to generate_,makefile.bash:354.  Here KOKKOS_SETTINGS is changed and the KOKKOS_PATH macro is changed to KOKKOS_TEST_INSTALL_PATH.
When building unit_tests and perf_tests, KOKKOS_PATH is set to KOKKOS_PATH, which at build time points to the source directory.  
This all results in the compiler command line missing all the correct include file paths, so the compile fails:
/opt/rocm/hcc/bin/clang++ -O3   -c -o BoxElemPart.o /tmp/kt/kokkos/example/fixture/BoxElemPart.cpp
/tmp/kt/kokkos/example/fixture/TestFixture.cpp:44:10: fatal error:
      'Kokkos_Core.hpp' file not found
#include <Kokkos_Core.hpp>

A working example command line from the previous directory is:
/opt/rocm/hcc/bin/clang++ -I./ -I/tmp/kt/kokkos/core/src -I/tmp/kt/kokkos/containers/src -I/tmp/kt/kokkos/algorithms/src    -hc -std=c++amp -I/opt/rocm/hcc-1.0/include -I/opt/rocm/include  --gcc-toolchain=/usr -I/tmp/kt/kokkos/tpls/gtest -I/tmp/kt/kokkos/algorithms/unit_tests -O3 -c /tmp/kt/kokkos/containers/src/impl/Kokkos_UnorderedMap_impl.cpp
(most of that is from expanding `hcc-config --cxxflags`)

This issue will affect all of the examples.

One solution might be to not build examples with the test target.  There is a KOKKOS_DO_EXAMPLES which would prevent this, but this is set to 1 by default.  But also I will want to include the examples in nightly test coverage.
Another way around is apparently to use --no-examples on the generate_makefile command line.

**Comment by chipfreitag** [comment]
Looking at this further, the install step is happening, but the Makefile.kokkos that is generated does not have everything necessary to compile properly.  For instance it is missing all include paths, so even Kokkos_Core.hpp (which IS in the install directory) is not found by the compiler.

**Comment by crtrott** [comment]
Curious I need to check that.
