### ISSUE TITLE
Kokkos lacks "global" is_initialized

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1060]
Kokkos' execution spaces have an `is_initialized` method, but there is no "global" `Kokkos::is_initialized`.  This makes it hard to prevent double initialization or finalization.  This matters because `Kokkos::initialize` sets up state that is independent of execution spaces, e.g., the Kokkos profiling library.

**Comment by ibaned** [comment]
I believe @dsunder has committed or soon-to-be-committed changes along these lines, including idempotent initialize/finalize. I think we're also moving to have users just call Kokkos::initialize and not the individual spaces, so `Kokkos::is_initialized` makes sense to me.

**Comment by hcedwar** [comment]
Resolve interaction with global initialize vs. to-be-deprecated individual device initialize functions

**Comment by mhoemmen** [comment]
*poke*

**Comment by ibaned** [comment]
@dsunder the world eagerly awaits your many improvements. no pressure though :)

**Comment by mhoemmen** [comment]
This issue, and the fact that `Kokkos::Serial` is always initialized, may be causing memory leaks in Nalu and other apps.  This breaks the "initialize Kokkos if it is not already initialized" pattern in Tpetra.

@DrBooom

**Comment by ibaned** [comment]
As @dsunder commented [here](https://github.com/kokkos/kokkos/issues/1184#issuecomment-339399552), `Kokkos::is_initialized` is apparently in develop right now and will be available in the next snapshot.
