### ISSUE TITLE
Should Kokkos print a warning (on Process 0 only!) if initialized before MPI is initialized?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1061]
See discussion here: https://github.com/trilinos/Trilinos/issues/1653

Rationale: If MPI is enabled, and users call `Kokkos::initialize` before `MPI_Init`, then Kokkos won't have the benefit of correct `mpirun` process and thread binding.

Counterargument: Is this better left to the application?

**Comment by hcedwar** [comment]
Kokkos avoids all direct, and minimizes indirect, dependencies on MPI.

**Comment by mhoemmen** [comment]
@hcedwar So what's going to happen if Kokkos gets initialized before MPI?  Does it actually matter?
