### ISSUE TITLE
Concurrent kernel execution with OMP/PThreads+Cuda

### ISSUE THREAD

**Issue by HBTUM** [kokkos/kokkos#1062]
I have a number of parallel tasks which do not use a lot of resources in terms of memory and computational effort, e.g. each task uses only a fraction of the available computational power of my GPU. Therefore I would like to execute them concurrently on the GPU, e.g. start an outer parallel loop with OpenMP/PThreads and execute for each the inner parallel loop on my GPU.
My first attempts looked like this
```
parallel_for(RangePolicy<Threads/OpenMP>(0,numThreads),KOKKOS_LAMBDA (int thread)
{
    parallel_for(RangePolicy<Cuda>(0,WORKLOAD),KOKKOS_LAMBDA (int index)
    { 
        foo()
    });
});
```
which resulted in the compiling error

```
error: An extended __host__ __device__ lambda must not be defined in a function that is defined within another function

error: An extended __host__ __device__ lambda cannot be defined within a member function of a class that is unnamed
```

Afterwards I used an explicit OpenMP parallel loop
```
#pragma omp parallel
{
    parallel_for(RangePolicy<Cuda>(0,WORKLOAD),KOKKOS_LAMBDA (int index)
    { 
        foo()
    });
}
```
with the compiler flag `--default-stream per-thread`. This compiles and executes, but profiling my GPU revealed that the respective streams for each `parallel_for` get executed sequentially on the GPU. Writing an example with pure CUDA instead of the `parallel_for` enabled concurrent kernel exuction.
Am I missing something in my configuration/implementation or is concurrent kernel execution not available (yet) in the Kokkos framework?

**Comment by ibaned** [comment]
I think that without multiple-CUDA-stream capability (which we don't have yet), these GPU tasks won't execute concurrently. The most reliable way I can think of to do this is to put all the tasks into a single `parallel_for` construct, which loops over all the indices in all the tasks. You can use the experimental `MDRangePolicy` for convenient 2D iteration. This should actually be more performant than using all the additional machinery of OpenMP and CUDA streams.
