### ISSUE TITLE
Document develop->master promotion process

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1063]
To be maintained on the Kokkos github wiki

**Comment by hcedwar** [comment]
Changes for October 2017 promotion:
Updated for develop->promote->master process.
Immediately after promotion merge master back into develop.

**Comment by hcedwar** [comment]
@dalabre : please put it on the Wiki!

**Comment by dalabre** [comment]
I have created a place for this document on the private repo [https://github.com/kokkos/ProgrammingGuide]; see last item on the right side-bar. I have entered text from the introductory section. I have received some review comments from Nathan on this document, in particular gaps that need filling. I will factor these into the document and place the result here for team comment/revision.

**Comment by dalabre** [comment]
I have posted a draft-for-review version of this document to the private repo ( https://github.com/kokkos/ProgrammingGuide/wiki ) under A Guide to Kokkos Testing Processes. Feedback and/or revisions are welcome and necessary to complete this dcoument.
