### ISSUE TITLE
When to use ViewAllocWithoutInitializing?

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#1073]
I have trouble finding documentation about it. The only thing that comes up is #317. But it does not answer the questions:

- When can it be used?
- When should it be used?
- What are the drawbacks of using it?

Looking at the code around it seems to be mostly used as
```c++
Kokkos::View view(Kokkos::AllocateViewWithoutInitializing("name"), size); 
Kokkos::deep_copy(view, value);
// or
Kokkos::deep_copy(v, some_otherview);
```
But is it possible to use it as
```c++
Kokkos::View view(Kokkos::AllocateViewWithoutInitializing("name"), size); 
Kokkos::parallel_for("loop", n, KOKKOS_LAMBDA(const int i) {
  view(i) = /*something here*/;
}
```
If yes, what are the potential issues to be aware of?

**Comment by ibaned** [comment]
I actually use this by default for views in my code, the majority of which looks like your second example (so yes, it is possible). I think it can be used for all managed view constructors which allocate space.

When to use it is a matter of choice. I'm not sure what the original rationale for this was, but without it all Views will be filled with default-initialized values. This is done using a parallel kernel just like `parallel_for`, and so it takes time. I personally made the observation that vast majority of my code requires allocating a view and immediately assigning its values based on complex logic, so running a kernel to set all the values to zero before that was just a waste of time. So I use it everywhere, and if I do happen to want all zero values (which is rare), I'll run my own kernel to do that. Profiling shows this saves significant application runtime.

The obvious drawback is that if your algorithms implicitly assumed that the initial values were all zero, for example if `view(i) += x` is what is in the kernel, then that code will break. Another slightly more subtle drawback is that memory locality is based on first-touch access, and so which thread does the first memory write is important. I think this is okay in my case as long as the kernel that sets the values is a `parallel_for` as you've shown, and using static scheduling would also help there (which I do).

**Comment by ibaned** [comment]
I'm going to label this as a request to put up documentation about it. We are hoping to have something on our Wiki soon, we can add this to that.

**Comment by aprokop** [comment]
@ibaned As a side note, what would you recommend for an uninitialized array with a few initialized values? Lets say you want `view(0) = 0` but initialize all other values in a `parallel_for` loop without `if` statement. As a specific kernel, I'm thinking of constructing compressed rows in a crs matrix of size `numRows+1` where `rows(0) = 0` but all other are first computed to be the number of nonzeros in each row, and then `parallel_scan` with those.

**Comment by ibaned** [comment]
Setting a single value is kindof a missing feature in Kokkos. I suppose you could emulate it by taking a subview of just that value and then doing deep_copy on that. Personally, I implemented a [backend-specific set method](https://github.com/ibaned/omega_h/blob/master/src/Omega_h_array.cpp#L124). As for the row map computation, you can refer to [my implementation here](https://github.com/ibaned/omega_h/blob/master/src/Omega_h_scan.cpp#L8). I know thats not a super concrete answer, but gives some ideas.

**Comment by mhoemmen** [comment]
@aprokop @ibaned Does Kokkos have a "pre-kernel" option, as in, a bit of code that runs on one thread block before anything else happens?  I know reductions have a post-kernel option.

**Comment by crtrott** [comment]
The rational for having initialization by default was first touch. In most of our codes the setup phase is serial, and if you just initialize a chunk of money and then set it all with a single thread the first touch stuff is all wrong. If your setup phase is also parallelized then not initializing is perfectly fine, and probably preferred as Dan said. 

Andrey you can just do it as a parallel_scan algorithm:

```c++
parallel_scan("Scan", N, KOKKOS_LAMBDA (const int& i, int& val, const bool& final) {
  int my_val;
  if(!final) {
    my_val = compute_values(i);
    a(i) = my_val;
  } else {
    my_val = a(i);
    a(i) = val;
  }
  val += my_val;
});
```

P.s. please check my logic, but I think that is what you want. a(0) will be zero after this run.

**Comment by mhoemmen** [comment]
@crtrott Is `! final` ever true for the `Serial` version?  That is, does the `Serial` version only ever do one pass?

**Comment by crtrott** [comment]
Args you are right ... in Serial this breaks shit.

**Comment by mhoemmen** [comment]
Does the functor / lambda know the execution space under which it is running?  If so, you could specialize inside the functor / lambda:
```
if (! final || std::is_same<execution_space, Kokkos::Serial>::value) {
  // ... first-pass initialization code ...
}
```

**Comment by aprokop** [comment]
Does scratched memory view initialized from shared memory zero its memory too?

**Comment by ibaned** [comment]
I feel like we've digressed pretty far from the original question... @mhoemmen @aprokop would you mind opening new question issues so we can keep things organized?

**Comment by mhoemmen** [comment]
@ibaned Sorry! :-) I reissued the question about "pre-kernels" as #1088.

**Comment by ibaned** [comment]
This is now documented here: https://github.com/kokkos/kokkos/wiki/View#642-initialization
