### ISSUE TITLE
Kokkos: Possible issue with kokkos-openmpi/2.0.1/cuda module

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1079]
Module kokkos-openmpi/2.0.1/cuda with CUDA module kokkos-cuda/8.0.44 hangs on exit of Trilinos tests with CUDA enabled. After the Trilinos test passes (with an all-reduce at the end, so I know that all processes passed the test), it prints a bunch of messages (see below). Here is a possible cause (though this relates to 2.1.0, not 2.0.1, I think):

https://github.com/open-mpi/ompi/issues/3244

Here are the messages:

```
93: [artemis.srn.sandia.gov:68935] Sleep on 68935
93: --------------------------------------------------------------------------
93: The call to cuIpcCloseMemHandle failed. This is a warning and the program
93: will continue to run.
93:   cuIpcCloseMemHandle return value:   1
93:   address: 0x20f42000093: Check the cuda.h file for what the return value means. Perhaps a reboot
93: of the node will clear the problem.
93: --------------------------------------------------------------------------
93: [artemis.srn.sandia.gov:68934] Sleep on 68934
93: [artemis.srn.sandia.gov:68933] Sleep on 68933
93: [artemis.srn.sandia.gov:68927] 2 more processes have sent help message help-mpi-common-cuda.txt / cuIpcCloseMemHandle failed
93: [artemis.srn.sandia.gov:68927] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
93: [artemis.srn.sandia.gov:68934] Sleep on 6893493: [artemis.srn.sandia.gov:68927] 1 more process has sent help message help-mpi-common-cuda.txt / cuIpcCloseMemHandle failed
```

Note: This may not actually be an issue, but I'm recording it for posterity.  I had reported it to the SEMS Service Desk on 28 Aug 2017, but Brent mentioned that the Kokkos developers, not SEMS, maintain the `kokkos-*` modules.

**Comment by hcedwar** [comment]
We don't believe the root cause is in Kokkos.
