### ISSUE TITLE
Advance to Version 3

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1084]
Root issue for advancing Kokkos to version 3.
This issues closes when version 3 is released.

Planned Trilinos advance to version 13, in June 2018.  Last version 12.x release in April 2018.
Align schedule with Trilinos version advance.

Schedule estimates:
  Last Kokkos v2.x release in February.
  Need v3 copyright to be approved by February.  Estimate November to submit copyright.
  V3 feature set is well-defined by November.

Selection and planning for deprecation.

**Comment by ndellingwood** [comment]
This is out-of-date, closing in favor of #1982
