### ISSUE TITLE
Update Tutorial material for Supercomputing

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1085]
Update performance data, etc.

**Comment by dalabre** [comment]
Duane and Nathan provided updated performance data ( PDFs ) to Carter for the GT Tutorial. Does this satisfy the requirements for SC17? Are there tweaks or more updates required?

**Comment by ndellingwood** [comment]
I think the data/plots should be done, updated tex (Tutorials with new SC2017 repo) and pdf (in new kokkos-tutorials/SC2017 or something similar to match naming convention) files with the plots are still needed
