### ISSUE TITLE
Can I issue a "pre-kernel" to be executed before the main parallel loop?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1088]
This is useful, for example, if I want to set the first entry of an array to zero before starting the parallel loop.  See #1073 for discussion and examples.

**Comment by crtrott** [comment]
No, you can't and even if you could it would be as slow or slower as a deep_copy on a subview.

**Comment by aprokop** [comment]
> No, you can't and even if you could it would be as slow or slower as a deep_copy on a subview.

@crtrott Can you elaborate on why that would be? If we allocate a large view, and set a single element there, I don't see why that would be slower that zeroing out the full array? Or is this about Kokkos launch overhead?

**Comment by mhoemmen** [comment]
We had already talked about the `parallel_scan` option:
```
if (! final || std::is_same<execution_space, Kokkos::Serial>::value) {
  // ... do a first-pass thing ...
}
```
(We need the second branch of the `if` test because `parallel_scan` only does one pass for the Serial execution space.)

**Comment by mhoemmen** [comment]
Usually, if you want to set the first entry of a vector, you want to follow that with a parallel scan.  Thus, the above pattern should suffice for most use cases.

**Comment by ibaned** [comment]
it also doesn't matter if the first entry of the row map is zeroed before or after the rest, so you can also do
```
if (final) {
  // other final stuff
  if (i == 0) row_map(0) = 0;
}
```
