### ISSUE TITLE
Multiple definitions when RDC is on

### ISSUE THREAD

**Issue by JanRobertE** [kokkos/kokkos#1100]
Hello,

in our project that we are porting to GPUs we are trying to replace the BLAS calls with CuBLAS.
However it seems we ran into a linking issue. The error message is:

nvlink error   : Multiple definition of 'kokkos_impl_cuda_constant_memory_buffer' in 'FileA.cpp.o', first defined in 'FileB.cpp.o'
nvlink error   : Multiple definition of '_ZN6Kokkos4Impl25g_device_cuda_lock_arraysE' in 'FileA.cpp.o', first defined in 'FileB.cpp.o'

We compiled with gcc version 4.8.5 and nvcc version 8.0.26 and the kokkos master branch as of July, 26th 2017.
The flags that we pass through the nvcc wrapper are: '-expt-extended-lambda -rdc true -lcudadevrt -lcublas'.

We have updated the nvcc-wrapper accordingly, so that the '-lcudadevrt -lcublas' flags are added to the list of nvcc flags.

In the relevant header file of our code (FileA.h) we have added: #include "cublas_v2.h" and #include <Kokkos_Core.hpp>.

The issue has arisen when introducing the '-rdc true -lcudadevrt' flags, which became necessary to fix the following error:
ptxas fatal   : Unresolved extern function 'cublasCreate_v2'

We would be very happy if you could shed some light on this issue.

Best wishes,
Jan

**Comment by ibaned** [comment]
It sounds to me like the issue is likely more related to `-rdc true` than to `-lcudadevrt`. I'm going to change the title of this accordingly.

**Comment by crtrott** [comment]
The issue is you enabled RDC without telling Kokkos that you do so. The same might be true for your expt-extended-lambda. Please simply use the appropriate Kokkos settings which will cause those flags to be added automagically in the make build environment, or add the options in addition to the flags in a trilinos build. I think a native CMake build will also add the CXX_FLAGS automatically. 

The options are:
```
# GNU Make:
KOKKOS_CUDA_OPTIONS=enable_lambda,rdc
#CMAKE:
Kokkos_ENABLE_Cuda_Lambda=ON
Kokkos_ENABLE_Cuda_RDC=ON
```

**Comment by JanRobertE** [comment]
Excellent, all working now. Setting the rdc option for KOKKOS_CUDA_OPTIONS has been the key.
