### ISSUE TITLE
Kokkos_ENABLE_Cuda_Lambda should default ON

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1101]
Due to:
 - Increasing use of lambdas in Tpetra
 - Maturity of Kokkos lambda support
 - CUDA 7.5 being on the trailing edge of support this FY

It makes sense to have defaults aimed at the common case, which is CUDA 8.0 and Tpetra using lambdas.

**Comment by ibaned** [comment]
see trilinos/Trilinos#1682

**Comment by mhoemmen** [comment]
Does Kokkos test for `CUDA_VERSION=7.0`?  Trilinos really only needs this for `CUDA_VERSION >= 7.5`.

**Comment by ibaned** [comment]
I was just looking at that... I think our `CUDA_VERSION` checks are only in C++ preprocessor logic, not yet in CMake. Doesn't Trilinos/TriBITS know the CUDA version from its CMake TPL logic?

**Comment by ibaned** [comment]
Yep, CMake's `FindCUDA.cmake` does define `CUDA_VERSION`, which I saw was used in Tpetra's CMake logic already. I'll use that then.

**Comment by ibaned** [comment]
Okay, implemented in PR #1104.

**Comment by hcedwar** [comment]
Must be triggered off of both the CUDA version and having the proper nvcc command line argument.
