### ISSUE TITLE
Memory allocation/free statistics.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1105]
Hello,

This is a feature request. Most of my codes rely on Kokkos. I often need to trace how much memory I use in a certain region. Instead of overriding malloc and free myself, this would be easier if Kokkos provide such statistics. For example,
```
static double total_memory_used, max_memory_used, // track memory usage  
current_memory_used, current_max_memory_used; // track memory usage in a region

Kokkos::resetCurrentMemoryTrace(); // set current_(max)_memory_used = 0

// do something

auto stat = Kokkos::getCurrentMemoryTrace(); // return the stat variables
// so I can see
printf("current memory watermark %f %f\n", stat.current_memory_used, stat.current_max_memory_used);
printf("total memory watermark %f %f\n", stat.total_memory_used, stat.max_memory_used);
```

Or would it be possible to add this kind of functionality into Kokkos profiling tools ?

**Comment by ibaned** [comment]
@kyungjoo-kim Kokkos already has Kokkos profiling hooks for memory allocation and deallocation. If you use the `space-time-stack` tool, it will give you a breakdown if your (Kokkos) memory usage at the high water mark point in time.

**Comment by ibaned** [comment]
I think for now we've answered this question, the existing tool was able to give us some useful information. If you want to request something like `resetCurrentMemoryTrace` in the future, please reopen this issue or create a new one.

**Comment by kyungjoo-kim** [comment]
@ibaned  The profiling report is great but I really appreciate if Kokkos profiling tool provide interface to set region of profiling.

**Comment by kyungjoo-kim** [comment]
Another weird thing is that it reports the following two kernels initialization and memory pool related one. The most important part (numeric factorization) is not included in the profiling. Also, does this trace task-dag ? 
```
BEGIN KOKKOS PROFILING REPORT:
TOTAL TIME: 0 seconds
TOP-DOWN TIME TREE:
<percent of total time> <percent MPI imbalance> <number of calls> <name> [type]
==================
|-> 0.4% -100.0% 33 Kokkos::View::initialization [for]
|-> 0.3% -100.0% 1 ZN5Tacho12Experimental13SupernodeInfoIdN6Kokkos6OpenMPEE23copySparseToSuperpanelsERKNS2_4ViewIPiIS3_EEES9_RKNS5_IPdIS3_EEES9_S9_RNS2_10MemoryPoolIS3_EEEUlRKNS2_4Impl20HostThreadTeamMemberIS3_EEE_ [for]

BOTTOM-UP TIME TREE:
<percent of total time> <percent MPI imbalance> <number of calls> <name> [type]
===================
|-> 0.4% 12.7% 33 Kokkos::View::initialization [for]
|-> 0.3% 12.7% 1 ZN5Tacho12Experimental13SupernodeInfoIdN6Kokkos6OpenMPEE23copySparseToSuperpanelsERKNS2_4ViewIPiIS3_EEES9_RKNS5_IPdIS3_EEES9_S9_RNS2_10MemoryPoolIS3_EEEUlRKNS2_4Impl20HostThreadTeamMemberIS3_EEE_ [for]
```

**Comment by ibaned** [comment]
Yes, if you label a `parallel_for` then it should have a different name.
However, for TaskDAG, I don't think we have explicit profiling support, but you can emulate it by putting `Kokkos::Profiling::pushRegion("name")` before the first `spawn` and `Kokkos::Profiling::popRegion()` after the last `wait`.

@hcedwar may want to comment on the preferred approach for profiling TaskDAG.

**Comment by crtrott** [comment]
You can also use the memory events tool to get more detailed insight into what is going on with allocations/deallocations: https://github.com/kokkos/kokkos-tools/wiki/MemoryEvents

**Comment by crtrott** [comment]
With regards to region stuff: you could modify memory events to include the region information, i.e. put into the timeline points where you enter / exit regions.

**Comment by ibaned** [comment]
Another important point: the current profiling system doesn't measure memory used by `MemoryPool`. I think in general we need a better plan for how the profiling interface should work with TaskDAG.

**Comment by crtrott** [comment]
We should be able to add a tracker to MemoryPool which at least tracks its maximum capacity (even if the app only uses a subset of that).
