### ISSUE TITLE
Implement new WorkGraph push/pop

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1108]
debugging #988 revealed less-than-ideal aspects of the current WorkGraph push/pop implementation. @hcedwar suggested a new design, this issue is to implement that new design and compare to the current one in terms of performance and robustness.

**Comment by hcedwar** [comment]
New algorithm has only a single state for push/pop of the ready queue and uses the ready queue begin/end indices as performance hints.  This entirely avoids the problems with updating a split-state (#988).  Also replaces a compare-and-swap loop with a simple atomic increment.

**Comment by hcedwar** [comment]
Pop function should not spin waiting for work.  Instead return either (a) a valid work index, (b) value indicating that all work is done, or (c) value indicating that no work index is currently available.  The back-end specific scheduler should be handling condition (c), not the pop function.
