### ISSUE TITLE
Question: CMake Standalone build with CUDA (nvcc_wrapper)

### ISSUE THREAD

**Issue by samuelpmish** [kokkos/kokkos#1109]
I'm interested in bundling kokkos into an existing CMake project, and the example/cmake_build was very helpful for getting it working for serial and OpenMP. However, after setting KOKKOS_ENABLE_CUDA on, I get a message about an unsupported compiler:

    Invalid compiler for CUDA.  The compiler must be nvcc_wrapper or Clang.

Is there a way to help CMake find and use the nvcc_wrapper in kokkos/bin?

**Comment by ibaned** [comment]
I usually just define `CMAKE_CXX_COMPILER=kokkos/bin/nvcc_wrapper` at configure time. changing the compiler is one of the few things that really shouldn't be done inside anyone's CMake logic, CMake is quite sensitive to changing the compiler.

**Comment by samuelpmish** [comment]
Thank you, this solved my issue!
