### ISSUE TITLE
Runtime error when compiling for CUDA dynamic parallelism

### ISSUE THREAD

**Issue by JanRobertE** [kokkos/kokkos#1111]
Hello,

we are trying to call some BLAS routines (Dgemm, Dgemv, Dsaxpy) from within a Kokkos::Cuda parallel region.

We attempted to use CuBLAS, which works fine in conjunction with Kokkos when called from the host and using '-lcudart -lcublas' nvcc flags.
But in the case of dynamic parallelism no path has led us to success so far.
I understand that when using CuBLAS with dynamic parallelism we would additionally need the nvcc flags '-lcudadevrt -rdc true'. We compile the Kokkos library using '--with-cuda-options=enable_lambda, rdc'.
Our program (for now without calling any CuBLAS kernels) compiles fine, but a runtime error occurs. While Kokkos is initialising fine, the first time the program hits a Kokkos::View, it crashes with the general error message:
Kokkos::Cuda ERROR: Failed to call Kokkos::Cuda::finalize()
ERROR : Process exiting without calling Kokkos::Threads::terminate()

Any ideas why adding the two flags '-lcudadevrt -rdc true' cause issues during runtime?

Is there maybe another path to implement the BLAS routines? We had a look at the Kokkos-kernels, but it looks like everything we would need is not there yet?
If yes, do you have a minimal example using Kokkos together with direct CuBLAS calls (including compilation flags, C++ source code etc.)?

Thanks a lot in advance for any help you can offer.

Best regards,
Jan

**Comment by crtrott** [comment]
Hi

sorry to here that you ran into issues. I have to admit we never tried CuBLAS in a Kokkos code with dynamic parallelism. Can you post a small reproducer? I will take a look. Assuming I can reproduce it I will mark it as a bug and we will get an estimate of when we can get this fixed. 

Also could you post into this issue what Blas calls you need and at which level of the hierarchy (i.e. global call, something a team would work collaborate on, or a single thread (warp)?

https://github.com/kokkos/kokkos-kernels/issues/9

**Comment by JanRobertE** [comment]
Ok, thanks for the prompt reply. I will have a go at the reproducer.

**Comment by crtrott** [comment]
Great that would be helpful. From the top of my head I don't know a reason why this shouldn't work but you never know ...

**Comment by dholladay00** [comment]
On an example I had working a while ago, I had to additionally (beyond already mentioned) add `-lcublas_device` to my nvcc flags.

**Comment by ibaned** [comment]
Is this still an important issue? If not I'll close it soon.

**Comment by JanRobertE** [comment]
Sorry, I forgot that I have left this thread unresolved.
I have found an efficient Kokkos implementation without using CUDA dynamic parallelism a while ago, so from my side you could close this issue.

Cheers,
Jan

________________________________

**Comment by ibaned** [comment]
Glad to hear you found an efficient approach, I'll close this then.
