### ISSUE TITLE
Synchronic Compile Fails on Mac OS X with Clang

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#112]
Unit tests fail to compile on Mac OS X due to Synchronic code.

../../core/src/impl/Kokkos_Synchronic_Config.hpp:144:3: error: use of undeclared identifier 'native_sleep'
{ native_sleep(time.count()); }
  ^
../../core/src/impl/Kokkos_Synchronic_Config.hpp:152:3: error: use of undeclared identifier 'native_yield'
{ native_yield(); }
  ^
In file included from TestSynchronic.cpp:59:
./TestSynchronic.hpp:233:17: error: use of undeclared identifier 'logf'
        return -logf(1.0f - integer() * 2.3283e-10f) * ooLambda;
                ^
3 errors generated.

**Comment by jgfouca** [comment]
Fixed on develop.

**Comment by crtrott** [comment]
Don't close a bug until its fixed on master. If it is fixed on develop mark it with the appropriate label.

**Comment by jgfouca** [comment]
Got it.

**Comment by crtrott** [comment]
Pushed to master
