### ISSUE TITLE
C++11 memory fence

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1121]
The C++11 standard includes memory fence operation that vendors and compiler-suppliers should optimize for the underlying hardware.
```
std::atomic_thread_fence(memory_order order) noexcept;
```
Our algorithms should start with using the standard supplied memory fence with ``order = std::memory_order_seq_cst``.  Once correctness is confirmed performance may be tuned by using other ``memory_order`` arguments, or even using our own assembly-coded implementations of memory fences if a vendor's memory fences are non-performant.

Related to issue #463 

Note that currently not available in Cuda back-end.

  @nmhamster is our current go-to developer for such assembly coded capabilities.

**Comment by hcedwar** [comment]
Commit 07a09f00c17db83652f69a2e9e44112a9b289769 replaces memory_fence assembly with ``std::atomic_thread_fence``.  This assembly may be retrieved as needed.

**Comment by hcedwar** [comment]
Captured discussion from @nmhamster "I am wondering if we should try to provide a heavyweight and lightweight version then, as you say, start with the heavyweight and slowly back off. My guess is that this will make more of a difference on the POWER and ARM systems where memory ordering is utilized more aggressively by the hardware. The advice you have makes a lot of sense."

**Comment by ibaned** [comment]
I'll call this closed as the C++11 API is now being used. Improving this further can be moved to other issues.
