### ISSUE TITLE
View::operator() to take indices by value instead of reference

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#1122]
I recently experienced a link error, when using a static constexpr int from a class definition to access a view, something like this
```

struct S {
static constexpr int i = 10;
};
Kokkos::View<double[100][100]> v("");
v(S::i,0) = 2.0; // Error. Undefined reference to S::i
```

and the reason is that by taking the reference of a variable, we make it necessary to also have a definition of it, since we `odrused` it. There are a couple of workarounds, of course. The first is to define the variable `i` outside the class, with `constexpr int S::i;`, while the second is to access `v` as `v(int(S::i),0)`. The first is annoying, since it kind of defies the constexpr-ness, while the second seems cumbersome to me.

All of this got me wondering if there is a rationale for which View's operator() takes indices by reference rather than by value. The are_integrals construct already checks that the arguments are indeed of integer type, so I **think** that the scenario where the indices are non-built in types cannot happen. And since the passed arguments are not stored in any reference/pointer, it seems to me that there's no intrinsic need in the arguments being references to variables from the outside world...

**Comment by ibaned** [comment]
I also think this is a question worth asking: "why does `operator()` take indices by reference?" and more importantly "should we switch to indices by value?". I personally would like to switch to indices by value, so lets gather opinions from other Kokkos devs if they disagree and why.

**Comment by crtrott** [comment]
One of the issues is that compilers didn't always optimize the copy away, which for example would cause a higher register utilization on GPUs. Also those guys are taken as `const reference` which means they should be able to accept everything a `by value` argument could take. 

Your example works fine for me with GCC (4.7.2 and 5.3 tested) and Intel (16.2 tested). It does fail with clang 4 though. Not sure if there is an actual reason why it should fail though.
 
```c++
#include<Kokkos_Core.hpp>

struct S {
static constexpr int i = 10;
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  Kokkos::View<double[100][100]> v("");
  v(S::i,0) = 2.0; // Error. Undefined reference to S::i
  printf("%lf %lf\n",v(10,0),v(9,0));
  Kokkos::finalize();
}
```

**Comment by etphipp** [comment]
I just wanted to mention I have seen similar issues in other contexts with GCC (4.9.3 I think).  In Sacado, my implementation of overloaded arithmetic operators take their arguments by const-reference.  If one of those arguments is a compile-time constant implemented through constexpr, I have seen similar undefined symbol linking errors.  It has never been clear to me if this is a compiler bug, or behavior that isn't defined in the standard.

**Comment by etphipp** [comment]
I started reading up on this, and @bartgol is right.  Since "i" is odr-used, a definition is needed if its address is taken (including a const-reference), and initializing it inline with the class declaration is not a definition (technically).  See 

http://en.cppreference.com/w/cpp/language/definition

and

https://stackoverflow.com/questions/3025997/defining-static-const-integer-members-in-class-definition

So what clang is doing is perfectly correct.  The fact that it works with some other compilers is just luck.

So I guess the question is whether Kokkos wants to make it easier to use static-constexpr indices as arguments to view operators by not requiring the user to define the symbol.

**Comment by mhoemmen** [comment]
Could Kokkos overload `operator()` to take `constexpr` integer indices by value?  That would have the benefit of passing `constexpr` indices into Kokkos, but it could cause a combinatorial explosion of overloads.

**Comment by crtrott** [comment]
So adding this: 
```c++
constexpr int S::i;
```
fixes it.

Also doing this
```c++
v(int(S::i),0)
```
fixes it.

**Comment by etphipp** [comment]
Yes.  Changing "i" to an enum should also fix it, which by the way, perfectly explains this comment in the Kokkos_Traits.hpp:
```
template < class T , T v >
struct integral_constant
{
  // Declaration of 'static const' causes an unresolved linker symbol in debug
  // static const T value = v ;
  enum { value = T(v) };
```
which I always wondered about.  That's why I said the question is not whether you can do it, the question is how easy Kokkos should make it for the user.

**Comment by crtrott** [comment]
Does anybody know any good reason why one wouldn't use an enum in that case (or maybe better a typed enum)?

**Comment by ibaned** [comment]
>Does anybody know any good reason why one wouldn't use an enum in that case (or maybe better a typed enum)?

 passing in the result of a `constexpr` function

**Comment by hcedwar** [comment]
This is a known issue in C++11.  For C++17 it is resolved by declaring
inline constexpr int i = ... ;
In the mean time it is best to use
enum : int { i = ... };
To prevent generation of link symbols.

--Carter

Sent from my iPad

On Sep 22, 2017, at 5:00 PM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:


Does anybody know any good reason why one wouldn't use an enum in that case (or maybe better a typed enum)?

passing in the result of a constexpr function

-

**Comment by hcedwar** [comment]
``
