### ISSUE TITLE
Access to team scratch memory pointer and remaining space

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1124]
Giving access to the team scratch memory pointer would allow for folks to implement a stack like behavior. I propose two additions to the `ScratchMemorySpace` class:

```c++
void* get_current_scratch_ptr(int level);
int get_available_scratch_size(int level);
```

This would for example allow utilization of scratch memory in transient function calls such as `team_gemv` for KokkosKernels.

**Comment by hcedwar** [comment]
This is a potentially error prone functionality so we need to be very clear of the usage.
```
void * get_remaining_scratch_ptr();
int get_remaining_scratch_size();
```
Need to clearly document / comment that creating scratch Views after using this memory will alias scratch memory.

**Comment by hcedwar** [comment]
What is really needed is a low-overhead push/pop allocator for scratch memory.
