### ISSUE TITLE
Kokkos::deep_copy ignores its execution space argument

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1127]
See this comment by @etphipp : 

https://github.com/trilinos/Trilinos/issues/1778#issuecomment-332635047

**Comment by crtrott** [comment]
Uhm maybe you misjudge what the argument does? It is an integrated fence argument, not the exec space to actually perform the deep_copy ...

**Comment by mhoemmen** [comment]
@crtrott what's an "integrated fence argument"?   My understanding was that the execution space provides a CUDA stream, which goes into `cudaMemcpyAsync`.  Does it not work that way?

**Comment by crtrott** [comment]
No it doesn't work that way. The first argument says which execution space is synchronous with the deep_copy. Think of it as a ExecSpace::fence(); MagicallyCompletelyAsyncMemCpy(); Hope that makes sense?

**Comment by mhoemmen** [comment]
@crtrott So how do I do an asynchronous memcpy?  Do I need two streams / execution space instances?
