### ISSUE TITLE
 Question: team_size_max usage

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1138]
My project uses lambdas in most cases and I make use of team policies. Is it ok to send in an empty lambda to get a policy with team_max_size?

```c++
team_policy policy(N, team_size_max([=] { }));
```

This is shown commented out in one of the examples [here](https://github.com/kokkos/kokkos/blob/36b92f437de3945b54e67ed8ce015746ae985a34/example/tutorial/Hierarchical_Parallelism/01_thread_teams_lambda/thread_teams_lambda.cpp#L92).

I could foresee potentially doing this differently if preferred (w/o moving to a functor), though I don't know about finer details:

```c++
// not sure if this works with CUDA
auto lambda = KOKKOS_LAMBDA (const member_type& team) {
  …
};
team_policy policy(N, team_size_max(lambda));
parallel_for(name, policy, lambda);
```

**Comment by hcedwar** [comment]
The `auto lambda = ...` should be used.  However, it may only work with CUDA 8 or better.

**Comment by dholladay00** [comment]
I have implemented the following, but have only tested it on my local machine (openmp backend):

```c++
const auto lambda = KOKKOS_LAMBDA (const member_type& team) { … };
const team_policy policy(N, team_policy::team_size_max(lambda));
const std::string name = "kernel";
parallel_for (name, policy.set_scratch_size(…), lambda);
deep_copy(results_h, results);
```

Is that the correct `auto` and placement of `KOKKOS_LAMBDA` macro?

**Comment by crtrott** [comment]
Looks good to me.

**Comment by dholladay00** [comment]
Sounds good, since this is not tied to any code changes, I'll go ahead and close.
