### ISSUE TITLE
DISABLE_PROFILING not working on Power 8

### ISSUE THREAD

**Issue by dalabre** [kokkos/kokkos#1141]

**Comment by dalabre** [comment]
At Georgia Tech Hackathon, adding DISABLE_PROFILING to make command did not turn off profiling. An attendee (being helped by DanS) running on a Power 8 P100 machine was unable to accomplish this.

**Comment by crtrott** [comment]
How did he try to add it? The correct way of doing this is:

```
make KOKKOS_OPTIONS=disable_profiling
```

Also you need to add the other options you want to use for example:
```
make KOKKOS_OPTIONS=disable_profiling,aggressive_vectorization
```

And yes this is case sensitive.
