### ISSUE TITLE
Option to Disable Initialize Warnings

### ISSUE THREAD

**Issue by jrood-nrel** [kokkos/kokkos#1142]
I see one other issue about this involving CUDA warnings, and looking at the code, I don't see any way to disable warnings, but in general I think we need an option to be able to turn off Kokkos warnings in which we can't set something like `OMP_PROC_BIND` to alleviate. I understand that I may be (probably am) naive in running with the wrong configuration, but the main reason I have for this is that I run tests on a two core machine with `mpirun -np 8`, etc, and I'm very aware the processor is oversubscribed, but the warning*8 really gets in the way of the test output.

**Comment by ibaned** [comment]
One of the many things going in with the merge to satisfy #255 will be much nicer options to control Kokkos warnings. I believe there will be three options: (1) print on all ranks, (2) print only on MPI rank 0, (3) don't print at all. @dsunder can correct me on this.

Sorry for the delay on this, but its bundled with a wholesale refactor of the `pthread`->`std::thread` backend which understandably required much code review, regression fixing, and performance testing.

**Comment by ibaned** [comment]
This also addresses #1060

**Comment by jrood-nrel** [comment]
Thanks. Since we use Kokkos through Trilinos, we will probably also have to wait for this to propagate through Trilinos I assume. However, I will close this issue since it seems to have been directly addressed now.

**Comment by ibaned** [comment]
@jrood-nrel, we actually have a policy not to close issues until the fix propagates to Trilinos, so I'll reopen this, and once its closed again that will indicate that the fix is in the Trilinos develop branch.

**Comment by dholladay00** [comment]
If I wanted to do this at initialization, could I do that with `Kokkos::initialize(Kokkos::InitArguments(dw=true));`? I haven't updated to latest master, but when I do, I plan on doing this (or whatever the correct way to do it). Also, did the fix PR include a way to have the warnings printed only from rank 0 if running with MPI?

**Comment by ibaned** [comment]
@dholladay00 I think the rank 0 only feature is still coming up. Both questions are best answered by @dsunder
