### ISSUE TITLE
promotion of : develop->master

### ISSUE THREAD

**Issue by dalabre** [kokkos/kokkos#1156]
Track progress of integration testing; Develop branch sha df8a0a47 is being tested

**Comment by dalabre** [comment]
test_all_sandia passed all tests on Kokkos-dev; Bowman and White testing in-progress

**Comment by dalabre** [comment]
test_all_sandia passed all tests on Bowman (serial, pthread and OpenMP for intel 16.2.181 and 17.0.098)

**Comment by dalabre** [comment]
test_all_sandia on White does not complete cleanly.  Using cuda/8.0.44, all tests PASS except KokkosCore_UnitTest's. I re-ran each of these individually and all produce the messages:

```
./KokkosCore_UnitTest_HWLOC: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./KokkosCore_UnitTest_HWLOC)
./KokkosCore_UnitTest_HWLOC: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./KokkosCore_UnitTest_HWLOC)

```
except  KokkosCore_UnitTest_Serial  which produces output:

```
./KokkosCore_UnitTest_Serial: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./KokkosCore_UnitTest_Serial)
./KokkosCore_UnitTest_Serial: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./KokkosCore_UnitTest_Serial)
./KokkosCore_UnitTest_Serial: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./KokkosCore_UnitTest_Serial)
```
Following a StackOverflow suggestion:

```
strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
.
.
.
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_LDBL_3.4
GLIBCXX_LDBL_3.4.7
GLIBCXX_LDBL_3.4.10
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
and
```
strings /lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
CXXABI_LDBL_1.3
```
Is this a problem with library versions on White? a module issue?  module devpack/openmpi/1.10.4/ibm/xl/13.1.4/cuda/8.0.44 was loaded by the test script.

**Comment by dalabre** [comment]
I confirmed that **test_all_sandia** was setting everything properly. I decided to modify my **bsub** command on White.   I changed my queue from `bsub -Is -q rhel7G bash`   to  `bsub -Is -q rhel7F bash` . The latter echos   `***Forced exclusive execution` ; what does this mean?   All cuda/8.0.44 tests passed.

I am rerunning all of the White tests again in the rhel7F queue for verification.

**Comment by hcedwar** [comment]
Need MemoryPool bug fix:

1. PR https://github.com/kokkos/kokkos/pull/1159

1. Then start from head of develop

**Comment by dalabre** [comment]
test_all_sandia passed all tests on White with a bsub submission to  -q rhel7F.

Following info from Si:
```
LDMS is for internal testing
rhel7T are POWER8 with PCIe attached K40 GPUs
rhel7F are OpenPOWER8 with PCIe attached K80 GPUs
rhel7G are OpenPOWER8+ with NVLINK attached P100 GPUs
```

**Comment by hcedwar** [comment]
@dalabre : Current status with current develop?

**Comment by dalabre** [comment]
This tracker was opened on 10Oct17. Testing commenced on _develop_ branch at sha1 **df8a0a4**.  The test_all_sandia yielded 100% PASSing results on machines kokkos-dev, bowman and white.

Trilinos integration testing in next comment.

**Comment by dalabre** [comment]
Unix issues delayed completion of the trilinos-integration testing. The testing scripts are written in bash; these scripts run within a tcsh shell were being suspended. The desired behavior was achieved by changing my default shell to bash. Thank you @ibaned and @ndellingwood!

Because of the long delay , integration testing begun today used the Kokkos develop branch at 
sha1 7f9bac3. 
The Trilinos commit cloned for integration testing was sha1 73d4c8e; the Trilinos version containing the snapshot of Kokkos was sha1 528d111.
The white integration test scripts were run for the omp and cuda options; results are presented next.
The shepard integration tests have just been started.

**Comment by dalabre** [comment]
The build_updated trilinos **on white using cuda** had configuration errors. See issue #1180.

The configure, build and test of updated and pristine trilinos **on white using omp** backend all completed. Updated and pristine trilinos both produced **identical test results** (72 of 1698 problems failed).

**Comment by ndellingwood** [comment]
@dalabre sounds like good progress, revise the configuration script for the cuda tests (as mentioned in #1180 comment) and that should get those tests up and running, fingers crossed that cuda tests go well also

**Comment by crtrott** [comment]
Where are we with this?

**Comment by dalabre** [comment]
Testing on White for cuda and pthreads cases pass integration testing. See closure in Issue #1180.
Testing on Shepard is not complete yet; see status and request for guidance in Issue #1186 and an email from Duane.

**Comment by ndellingwood** [comment]
See #1196 for build/test result summaries

**Comment by ibaned** [comment]
This was completed by @crtrott
