### ISSUE TITLE
Sort subset of Kokkos::DynamicView

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1160]
I need to be able to get a subview of a dynamic view.  Here is my use case

```
  Kokkos::Experimental::DynamicView<Vector3*> x_;
...
  Sorter.sort(Kokkos::subview(x_, reduced_size));
```

**Comment by hcedwar** [comment]
Subviews are problematic.  However, sorting a subrange was added a while ago.
See https://github.com/kokkos/kokkos/blob/develop/algorithms/unit_tests/TestSort.hpp#L234
where the sort function can be given a [begin,end) range.
Hopefully that is sufficient.

**Comment by bathmatt** [comment]
I'm guessing I'm missing something

```
  KeyViewType local_ielement = Kokkos::subview(element_, reduced_size);

  Kokkos::BinSort<KeyViewType , BinOp > Sorter(local_ielement,binner,false);
  Sorter.create_permute_vector();
  Sorter.sort< KeyViewType >(local_ielement);
  Sorter.sort(x_, 0, reduced_size);
```
and it fails on the sort of x.

```
/home/mbetten/Trilinos/EMPIRE/src/PIC/ParticleContainer.cpp: In member function ‘void empire::pic::ParticleContainer::sort()’:
/home/mbetten/Trilinos/EMPIRE/src/PIC/ParticleContainer.cpp:92:34: error: no matching function for call to ‘Kokkos::BinSort<Kokkos::View<int*, Kokkos::OpenMP>, Kokkos::BinOp1D<Kokkos::View<int*, Kokkos::OpenMP> > >::sort(Kokkos::Experimental::DynamicView<empire::ConstLenVector<double, 3u>*>&, int, Kokkos::pair<long unsigned int, long unsigned int>&)’
   Sorter.sort(x_, 0, reduced_size);
```

**Comment by bathmatt** [comment]
Is it that the KeyViewType needs to be a dynamic view as well?

**Comment by hcedwar** [comment]
Not required.
I had implemented the `sort` function with DynamicView for you:
https://github.com/kokkos/kokkos/blob/master/algorithms/src/Kokkos_Sort.hpp#L524
However, it does not appear to cover your use case of sorting key array and applying permutation to value array.  Perhaps the linked implementation shows enough of the pieces to code your use case?

**Comment by bathmatt** [comment]
Huh, not sure I understand this comment.  

I need to apply the permutation to a lot of views.  Are you saying I can do what I need to with kokkos the way it is or I need to redo my algorithm?

**Comment by hcedwar** [comment]
Can you copy & modify 
https://github.com/kokkos/kokkos/blob/master/algorithms/src/Kokkos_Sort.hpp#L524
to implement what you need?

**Comment by bathmatt** [comment]
So, this code you do this bit of code.

```

  bin_sort.create_permute_vector();
  bin_sort.sort(view);

```

So, I guess I'm not smart enough to figure out what you're asking to do.  Can I grab one of the guys who understands this and help work through all this/?
Now I thought you said that doesn't work.

**Comment by bathmatt** [comment]
Here is my base data class

I need to make all of these dynamic views

```  
  Kokkos::View<LocalOrdinal*> element_;
  Kokkos::View<Vector3*> x_;
  Kokkos::View<Vector3*> x_ref_;
  Kokkos::View<Vector3*> v_;
  Kokkos::View<Vector3*> v_ref_;
  Kokkos::View<Vector3*> E_, B_;
  
```

and then I sort them

```
 typedef Kokkos::View<LocalOrdinal*, PHX::Device> KeyViewType;
  typedef Kokkos::BinOp1D< KeyViewType > BinOp;


  int max_elems = MapContainer::getElementMap()->getNodeNumElements();
  int min_elems = 0, num_elems = max_elems-min_elems+1;
  BinOp binner(num_elems, min_elems, max_elems);

  Kokkos::pair<size_t, size_t> reduced_size(0,size());
  KeyViewType local_ielement = Kokkos::subview(element_, reduced_size);

  Kokkos::BinSort<KeyViewType , BinOp > Sorter(local_ielement,binner,false);
  Sorter.create_permute_vector();
  Sorter.sort< KeyViewType >(local_ielement);

  Sorter.sort(Kokkos::subview(x_, reduced_size));
  Sorter.sort(Kokkos::subview(x_ref_, reduced_size));
  Sorter.sort(Kokkos::subview(v_, reduced_size));
  Sorter.sort(Kokkos::subview(v_ref_, reduced_size));
  Sorter.sort(Kokkos::subview(E_, reduced_size));
  Sorter.sort(Kokkos::subview(B_, reduced_size));
  Sorter.sort(Kokkos::subview(weight_, reduced_size));
```

**Comment by hcedwar** [comment]
Desired API:
```
BinSort<...> Sorter(local_ielement, begin, end, binner, false );
Sorter.sort( x_ , begin , end );
// etc.
```
