### ISSUE TITLE
Kokkos Memory Management Issue

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1163]
When a Kokkos `View` is resized, I understand that it doubles the view's memory allocation since Kokkos allocates an entirely new copy of the resized view and then copies the elements from the old view to the larger new one. 

However, the memory high water mark is much larger than I expect and it looks like the memory from resized old views isn't being freed right away. I'm even getting more than 2 copies of the same view in the memory breakdown using the profiling tools. Is it possible that the old views are hanging around for a while and bloating up the memory use? Why aren't they de-allocated right away?

**Comment by hcedwar** [comment]
If you have another View that references the old memory the reference count > 1 and the memory is not deallocated.

**Comment by stanmoore1** [comment]
Is there a way to get the reference count of a View?

**Comment by stanmoore1** [comment]
When an existing view is reassigned:
`d_view = Kokkos::View(n);`

it looks like the new view is initialized first and then the old view is destroyed. That doubles the memory needed for the view, is there a reason for this?

If instead I use:
`d_view = Kokkos::View();`
`d_view = Kokkos::View(n);`
the old view is destroyed first, which is what I would expect.

**Comment by stanmoore1** [comment]
For the first reassignment case, the view appears multiple times in the `space_time_stack` tool output, but the actual memory high water mark doesn't change when I switch to the second case. @ibaned not sure why the same view is appearing multiple times. I'll open a ticket in the `kokkos-tools` section.

**Comment by stanmoore1** [comment]
Using the `memory-events` tool, it clearly shows that when a view is reassigned, the new view is first allocated and then the old view is deallocated:
<pre>
# Memory Events
# Time     Ptr                  Size        MemSpace      Op         Name
29.283868    0x10596800080     1640890368             Cuda Allocate   particle:sorted
29.373308    0x107a6000080    -1639186432             Cuda DeAllocate particle:sorted
</pre>

However, if the view is first assigned to an empty constructor, the view is destroyed and then reallocated, which is the behavior I would expect:
<pre>
# Memory Events
# Time     Ptr                  Size        MemSpace      Op         Name
29.168586    0x107ec400080    -1639186432             Cuda DeAllocate particle:sorted
29.204098    0x1053c600080     1640890368             Cuda Allocate   particle:sorted
</pre>

**Comment by ibaned** [comment]
This is not really the fault of Kokkos, it is fundamental C++ ordering of operations. The line
```
d_view = Kokkos::View(n);
```
means, in C++, call the function `Kokkos::View(n)` first, then assign the resulting object to `d_view`. Without offering a different API, there is nothing Kokkos can do to reverse these operations. `Kokkos::realloc` or `Kokkos::resize` may be good alternatives. I know one or both of these copy the old data into the new view, so if thats something you don't want to happen then maybe we need a new API to do a resize.

**Comment by stanmoore1** [comment]
I see `Kokkos::realloc` first calls the empty constructor like in my example: https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_View.hpp#L2389. I can use that instead for the large arrays. I wasn't aware of this memory gotcha with view assignment.

**Comment by ibaned** [comment]
> I see `Kokkos::realloc` first calls the empty constructor like in my example

Excellent, then that should be a good solution.

Yea, you'd have the same issue if you used
```cpp
my_vector = std::vector<double>(n);
```
instead of
```cpp
my_vector.resize(n);
```

**Comment by stanmoore1** [comment]
Yes, I understand that. I guess View destruction wasn't on my mind since Kokkos "manages" the View memory under the hood.
