### ISSUE TITLE
{OMPI,MPICH}_CXX hack breaks nvcc_wrapper use case

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1166]
So, this code was added to `Makefile.kokkos` to support the LAMMPS build convention I think:
```
KOKKOS_INTERNAL_COMPILER_NVCC        := $(strip $(shell $(CXX) --version       2>&1 | grep nvcc                | wc -l))
ifneq ($(OMPI_CXX),)
  KOKKOS_INTERNAL_COMPILER_NVCC      := $(strip $(shell $(OMPI_CXX) --version       2>&1 | grep nvcc                | wc -l))
endif
ifneq ($(MPICH_CXX),)
  KOKKOS_INTERNAL_COMPILER_NVCC      := $(strip $(shell $(MPICH_CXX) --version       2>&1 | grep nvcc                | wc -l))
endif
```
However, I now have the following scenario:
```
CXX=nvcc_wrapper
```
The `nvcc_wrapper` file is modified to call `mpicxx` as the host compiler
```
OMPI_CXX=g++
```
The result is that `KOKKOS_INTERNAL_COMPILER_NVCC` starts out being `1`, then becomes `0` due to the `OMPI_CXX` hack.

Is there a way we can alter this logic such that both cases work okay?

**Comment by ibaned** [comment]
@stanmoore1 @crtrott

**Comment by ibaned** [comment]
My understanding is that the `OMPI_CXX` check is only used when the Kokkos compiler `CXX` is set to an MPI compiler wrapper. In PR #1167 I tried to only apply this check if the name of `CXX` has `mpi` in it somewhere.

**Comment by stanmoore1** [comment]
This doesn't break LAMMPS, so I'm fine with it.

**Comment by crtrott** [comment]
OK I got now the right fix:
```
KOKKOS_INTERNAL_COMPILER_NVCC        := $(strip $(shell export OMPI_CXX=$(OMPI_CXX); export MPICH_CXX=$(MPICH_CXX); $(CXX) --version       2>&1 | grep nvcc                | wc -l))
```

That gives the following:

  | CXX | env OMPI_CXX | Makefile OMPI_CXX | KOKKOS_INTERNAL _COMPILER_NVCC | Expected |
  | --- | --- | --- | --- | --- |
  | g++ | NA | NA | 0 | 0 |
  | g++ | g++ | NA | 0 | 0 |
  | g++ | NA | g++ | 0 | 0 |
  | g++ | g++ | g++ | 0 | 0 |
  | g++ | nvcc_wrapper | NA | 0 | 0 |
  | g++ | NA | nvcc_wrapper | 0 | 0 |
  | g++ | nvcc_wrapper | nvcc_wrapper | 0 | 0 |
  | g++ | g++ | nvcc_wrapper | 0 | 0 |
  | g++ | nvcc_wrapper | g++ | 0 | 0 |
  | nvcc_wrapper | NA | NA | 1 | 1 |
  | nvcc_wrapper | g++ | NA | 1 | 1 |
  | nvcc_wrapper | NA | g++ | 1 | 1 |
  | nvcc_wrapper | g++ | g++ | 1 | 1 |
  | nvcc_wrapper | nvcc_wrapper | NA | 1 | 1 |
  | nvcc_wrapper | NA | nvcc_wrapper | 1 | 1 |
  | nvcc_wrapper | nvcc_wrapper | nvcc_wrapper | 1 | 1 |
  | nvcc_wrapper | g++ | nvcc_wrapper | 1 | 1 |
  | nvcc_wrapper | nvcc_wrapper | g++ | 1 | 1 |
  | mpicxx | NA | NA | 0 | 0 |
  | mpicxx | g++ | NA | 0 | 0 |
  | mpicxx | NA | g++ | 0 | 0 |
  | mpicxx | g++ | g++ | 0 | 0 |
  | mpicxx | nvcc_wrapper | NA | 1 | 1 |
  | mpicxx | NA | nvcc_wrapper | 1 | 1 |
  | mpicxx | nvcc_wrapper | nvcc_wrapper | 1 | 1 |
  | mpicxx | g++ | nvcc_wrapper | 1 | 1 |
  | mpicxx | nvcc_wrapper | g++ | 0 | 0 |

I think this is what we want, if you explicitly use nvcc_wrapper as CXX you get a 1, and the Makefile OMPI_CXX is prioritized over the environment OMPI_CXX, but either OMPI_CXX does not factor in if mpicxx is not the compiler.

**Comment by crtrott** [comment]
So if you want to set OMPI_CXX in your Makefile do it like this:

```
export OMPI_CXX=$(KOKKOS_PATH)/bin/nvcc_wrapper
```

**Comment by ndellingwood** [comment]
@crtrott There is also an nvcc_wrapper in kokkos/config, should the version from kokkos/bin be copied over there or should that one be removed? Not sure how common it is for Trilinos config scripts to point to kokkos/config/nvcc_wrapper vs kokkos/bin/nvcc_wrapper.

**Comment by ibaned** [comment]
I think the version in `bin` is the one we want to use moving forward. I'm fine removing the one in `config`, its definitely too confusing.

**Comment by stanmoore1** [comment]
Right now LAMMPS points to `config`, but could switch it to `bin` if necessary. May be good to warn users so they have time to switch, otherwise this could break builds.

**Comment by ibaned** [comment]
Yes, please switch to `bin`, its probably already more up to date.

I think in general we need a better mechanism for announcing release changes to users....
