### ISSUE TITLE
Missing RDC device link step?

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1168]
I'm trying to compile a user application with CUDA + RDC, given that this is the only way to remove lock array overhead from kernel calls. I'm getting these link errors in the final link step, one for each Kokkos `cpp` file:
```
/lustre/atlas/proj-shared/trn001/vpic/kokkos_install_dan/lib/libkokkos.a(Kokkos_Core.o): In function `__sti____cudaRegisterAll_46_tmpxft_0000b9d8_00000000_7_Kokkos_Core_cpp1_ii_8f3cc893()':
tmpxft_0000b9d8_00000000-4_Kokkos_Core.cudafe1.cpp:(.text.startup+0x34): undefined reference to `__cudaRegisterLinkedBinary_46_tmpxft_0000b9d8_00000000_7_Kokkos_Core_cpp1_ii_8f3cc893'
```

I seems fundamentally related to these issues:

https://stackoverflow.com/questions/22076052/cuda-dynamic-parallelism-makefile
http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#examples

Is our `nvcc_wrapper` set up to do this at the final link step? Am I using it wrong somehow? I've configured Kokkos with `rdc` in the CUDA options, which sets up the `--relocatable-device-code=true` flag, but as the links above point out that is only half the required work.
One needs to do:

```
nvcc --gpu-architecture=sm_50 --device-c a.cu b.cu
nvcc --gpu-architecture=sm_50 --device-link a.o b.o --output-file link.o
g++ a.o b.o link.o --library-path=<path> --library=cudart
```

Any clarification or help with this is appreciated. Thanks!

@crtrott ?

**Comment by crtrott** [comment]
I've been compiling stuff with with RDC enabled and it seems to work for my cases. What is your link line? 

Christian
