### ISSUE TITLE
Address gtest issue with TriBITS Kokkos build outside of Trilinos

### ISSUE THREAD

**Issue by bartlettroscoe** [kokkos/kokkos#117]
Teuchos supports a stand-alone TriBITS Project build.  You can just snapshot Teuchos out of Trilinos and configure/build/install it as its own CMake project.  As Teuchos contains an optional dependency on Kokkos, it would be nice if people could just snapshot out Teuchos and Kokkos and then build them under Teuchos.  Or, any TriBITS-based project that wants to pull in Kokkos or Teuchos could just snapshot these dirs out into other project and have these.

Unfortunately, we can't easily do this with Kokkos because Kokkos has a required test dependency on the Gtest TriBITS package under Trilinos.  But Kokkos already has its own version of gtest as shown with:

```
[8vt@u235 Trilinos (master)]$ du -sh packages/kokkos/tpls/gtest/*
1.2M	packages/kokkos/tpls/gtest/gtest
```
To make it easy to build Kokkos as part of any TriBITS project, it would be nice if Kokkos just used its own version of gtest and ignored the one in Trilinos.  That would avoid having to also snapshot out the GTest package.  That poses no problems for Trilinos because the kokkos version of gtest would only be linked into tests/examples for Kokkos and would not interact with the Trilinos version of gtest.
 
Therefore, would Kokkos developers accept a pull-request that made Kokkos use its own version of gtest and ignored the version provided in Trilinos?

Also, note that it would not be hard to allow Kokkos to build as its own CMake TriBITS project as well.  But that is a separate issue that can be addressed later.

**Comment by crtrott** [comment]
I don't think we have an issue with this. Let me ask Brent if he sees any problems, otherwise we can just go ahead.

**Comment by bartlettroscoe** [comment]
Okay, as discussed yesterday in person, I will submit a pull request with the change.

**Comment by bartlettroscoe** [comment]
I tried to build the KokkosExample package and it does not build.  I get build errors like:

```
/home/8vt/localhome/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/kokkos/example/query_device/query_device.cpp:47:29: fatal error: Kokkos_Macros.hpp: No such file or directory
 #include <Kokkos_Macros.hpp>
                             ^
compilation terminated.
```

I see that it is flagged as an EX subpackage and therefore is not under automated testing.  It would seem that none of the examples are even run.  One would think that the examples should important enough to build as part of regular testing and you should test at least something to prove the examples are correct.  As a user, I don't trust examples that are not tested.

I ran the existing tests with a 120s timeout and got:

```
98% tests passed, 2 tests failed out of 130

Label Time Summary:
Kokkos     = 342.70 sec
Teuchos    =  19.37 sec

Total Test time (real) = 122.72 sec

The following tests FAILED:
	  5 - KokkosCore_PerfTest_MPI_1 (Timeout)
	  6 - KokkosContainers_UnitTest_MPI_1 (Timeout)
```

Why is the Kokkos unit-test test suite so expensive?  These are not performance tests are they?  Is this because I am doing a debug-mode build?

Anyway, I am ready to submit the pull request.
