### ISSUE TITLE
Scatter-add parallel pattern

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1171]
Evidence is piling up for scatter-add parallel pattern where a parallel kernel performs scatter-add contributions to a very large array.  On hardware with high concurrency and well performing atomic-add this is implemented with atomic-add to a shared array.  On hardware with low concurrency and poorly performing atomic-add the scatter-add contributions are into a temporary thread-private copy of the array, and when the kernel completes a second _behind the scenes_ parallel pass is performed to join the thread private contributions into the target array.  Allocation, joining, and deallocation of thread private arrays are _hidden_ by the scatter-add parallel pattern.

**Comment by ibaned** [comment]
might be a duplicate of #825, at least in terms of them both addressing the same problem. difference is parallel pattern versus data structure.

**Comment by mhoemmen** [comment]
@hcedwar How specialized will this kernel be?  For example, would it require users to provide an array of the output indices and values, or could those come from some function?  If they could come from a function, then this pattern could replace a lot of code, e.g., for finite-element assembly.  However, that might limit hardware acceleration possibilities in the future.

**Comment by hcedwar** [comment]
My initial guess is the user provides an ordinary `View` and captures it in the functor as a scatter-add _thingy_.
```
struct MyAssemblyFunctor {
  void operator()( int i , ScatterAdd<double*[3]> & a ) const { a[i][0] += ... }
}
View<double*[3]> force = ... ;
parallel_scatter_add( N , MyAssemblyFunctor() , force );
```

The `parallel_scatter_add` has the flexibility of using atomic overloads, data duplication followed by in-parallel reduction, or even setting up a producer-consumer thing.
Composing could get messy:
```
parallel_reduce_and_scatter_add( N , functor , result_scalar , result_array );
```

**Comment by mhoemmen** [comment]
@hcedwar wrote:
> My initial guess is the user provides an ordinary View and captures it in the functor as a scatter-add _thingy_.

This looks reasonable.

> Composing could get messy....

"Parallel reduce and scatter add" is a common pattern for computing counts or detecting errors (reduce over the error code) while doing a scatter-add.  It's hard to compose these patterns in a non-awkward way, at least not in C++.

**Comment by hcedwar** [comment]
Many drivers for separate implementation from parallel pattern.
