### ISSUE TITLE
Add CUDA 9.0 nightly testing

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#1174]
Step one for CUDA 9 back-end; followed by fixing...

**Comment by Rombur** [comment]
Does that mean that Kokkos does not support CUDA 9 right now? I tried to switch my code to CUDA 9 but I get the following kind of error from Intrepid 2:
```
error: expansion pattern 'Kokkos::LayoutStride' contains no argument packs
```

**Comment by hcedwar** [comment]
Until successfully tested CUDA 9 is not supported.

**Comment by Rombur** [comment]
@hcedwar OK thanks.

**Comment by hcedwar** [comment]
Nightly testing on White w/Pascal GPUs.
