### ISSUE TITLE
Excessive calls to a pthread mutex lock

### ISSUE THREAD

**Issue by bfzinser** [kokkos/kokkos#1178]
In the matrix fill for my code, if I use C++ for loops, the entire code runs in 0.2 seconds.

If I use Kokkos parallel for loops (openmp backend) with --kokkos-threads=1 given as a command line argument, the entire code runs in 2.1 seconds. vTune reports two hotspots as being __pthread_mutex_lock (0.6 s) and pthread_mutex_unlock (0.5 s).

If I use --kokkos-threads=12, the entire code runs in 2.2 seconds. vTune adds gomp_barrier_wait_end (0.8 s) to the list of hotspots. I assume this addition is because I call Kokkos::fence() after each Kokkos parallel for. vTune also reports that most of the work is being done by a single thread.

I believe that my code is written such that no locks are required. Is there a way to tell where and why the locks are being added?

**Comment by bfzinser** [comment]
The timing I reported for running the entire code with C++ for loops is incorrect. However, I am still very interested the the rest of my question because this is the current bottleneck.

**Comment by hcedwar** [comment]
Using the OpenMP back-end this would be the native openmp runtime that calls the mutex and barriers.  There are several (sometimes compiler specific) parameters for controlling openmp behavior that you may need to set.

**Comment by crtrott** [comment]
Can you give some more details of the code (in particular length of code etc.) Posting some code may also help, determine what is going. The fact that you don't get any speedup from using more threads is worrisome, and hints at something fundamentally wrong. Possible issues could be: not enough parallelism exposed, thread affinity is screwed up, excessive use of atomic operations.

**Comment by bfzinser** [comment]
For the small problem I was looking at before, I am able to get some speedup in the matrix fill part (the part I'm interested in right now). Going from 1 thread to 12 threads, I see the matrix fill go from taking 0.1s to 0.02s. However, the fundamental problem of vTune showing only one  thread doing most of the work remains.

I ran a larger problem and vTune reported 328s of sping time out of 462s of CPU time. For this problem, the top hotspots were gomp_barrier_wait_end (136.921s), omp_barrier_wait (79.848s), gomp_team_barrier_wait_end (48.925s), gomp_team_barrier_wait_final (19.206s), and __pthread_mutex_lock (17.925s).

I will try to put together a small example of code next week. I wouldn't be surprised if not enough parallelism is exposed.

**Comment by bfzinser** [comment]
I played with the code some to get a better feel for what is happening. You were correct; it amounted to not enough parallelism being exposed. I'm going to rearrange the code to see what the best path forward is. Thank you for the help.
