### ISSUE TITLE
Configuration Errors in Trilinos for White Cuda Promotion Tests 

### ISSUE THREAD

**Issue by dalabre** [kokkos/kokkos#1180]
Reference Promotion #1156. 
```
Trilinos repos versions:
--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
ed9a1aa [Thu Oct 19 16:48:15 2017 -0600] <dalabre@sandia.gov>
Snapshot of kokkos from commit 7f9bac3bd499d8593f52b20ad45e076531ec153d
 --------------------------------------------------------------------------------
.
.
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_C_COMPILER_VERSION='5.4.0'
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /ascldap/users/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpicxx
-- Check for working CXX compiler: /ascldap/users/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
.
.
Processing enabled package: KokkosKernels (Libs, Tests)

=======================
KokkosKernels ETI Types
   Devices:  <Serial,HostSpace>
   Scalars:  double
   Ordinals: int
   Offsets:  int;size_t
=======================

Processing enabled package: RTOp (Libs)
Processing enabled package: Sacado (Libs, Tests, Examples)
-- Performing Test HAS_C99_TR1_CMATH
-- Performing Test HAS_C99_TR1_CMATH - Success
Processing enabled package: Epetra (Libs)
-- Looking for dggsvd3
-- Looking for dggsvd3 - not found
-- Looking for dggsvd3_
-- Looking for dggsvd3_ - not found
-- Looking for DGGSVD3
-- Looking for DGGSVD3 - not found
-- Looking for DGGSVD3_
-- Looking for DGGSVD3_ - not found
Did not find new version of lapack. dggsvd3 is not available.
Processing enabled package: Zoltan (Libs)
Processing enabled package: Shards (Libs)
Processing enabled package: Triutils (Libs)
Processing enabled package: Tpetra (Classic, TSQR, Core, Tests, Examples)
CMake Error at packages/tpetra/CMakeLists.txt:49 (MESSAGE):
  If building with CUDA, Tpetra and downstream packages require, at least
  with CUDA_VERSION >= 7.5 and <= 9.0, that you add "--expt-extended-lambda"
  to either Trilinos_CXX11_FLAGS or CMAKE_CXX_FLAGS.  You must also set
  Kokkos_ENABLE_Cuda_Lambda:BOOL=ON, if it is not already ON by default.


-- Configuring incomplete, errors occurred!
```

**Comment by mhoemmen** [comment]
It's not an error.  Follow the directions in the message :-) .

**Comment by ndellingwood** [comment]
@dalabre add the following to `Trilinos/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all` (the script will need to be updated):

```
-D Trilinos_CXX11_FLAGS:STRING="--expt-extended-lambda -std=c++11" \
-D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON​ \
```

**Comment by dalabre** [comment]
23Oct17 status:   The deficiency in the ```Trilinos_CXX11_FLAGS:STRING``` was remedied in the  ```configure-testbeds-jenkins-all``` test script. A subsequent turning on of flag ```Tpetra_INST_CUDA:BOOL=${CUDA}``` was needed even though it should have already been on.

Running of this white cuda test failed when the disk filled up:

```
/tmp/cci3Vkd8.s: Assembler messages:
/tmp/cci3Vkd8.s: Fatal error: can't close CMakeFiles/Stokhos_recurrence_example.dir/simple/recurrence_example.cpp.o: No space left on device
make[2]: *** [packages/stokhos/example/CMakeFiles/Stokhos_recurrence_example.dir/simple/recurrence_example.cpp.o] Error 1
make[2]: Target `packages/stokhos/example/CMakeFiles/Stokhos_recurrence_example.dir/build' not remade because of errors.
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: *** [packages/stokhos/example/CMakeFiles/Stokhos_recurrence_example.dir/all] Error 2
```

Shepard tests are stalled in the queue at the present time.

**Comment by mhoemmen** [comment]
@dalabre wrote:
> A subsequent turning on of flag `Tpetra_INST_CUDA:BOOL=${CUDA}` was needed even though it should have already been on.

Could you please share Tpetra's CMake output, in particular the list of the enabled Node types, and the ETI output?  Tpetra _should_ enable this by default if `Kokkos_ENABLE_CUDA` is `ON`.  Note that CMake is case sensitive.

**Comment by dalabre** [comment]
White cuda tests completed; some differences between updated and pristine Trilinos. Details on Trilinos github. The Shepard tests had build errors. Details to come ....

**Comment by dalabre** [comment]
Upon further investigation, there are no new failures of updated trilinos. The following problems failed (outright) on the update branch:
```Anasazi_Epetra_ModalSolversTester_MPI_4  and  Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4```
however they also failed on the pristine branch (by timeout).

Shepard builds are still failing; there seems to be a premature timeout by killing a job allocation. Si will be consulted.

**Comment by dalabre** [comment]
With the above results on White, both omp and cuda have passed the integration testing.

**Comment by dalabre** [comment]
With the last posting, White build and test issues have been addressed.

**Comment by ndellingwood** [comment]
@mhoemmen 

> 
> 
>     A subsequent turning on of flag Tpetra_INST_CUDA:BOOL=${CUDA} was needed even though it should have already been on.
> 
> Could you please share Tpetra's CMake output, in particular the list of the enabled Node types, and the ETI output? Tpetra should enable this by default if Kokkos_ENABLE_CUDA is ON. Note that CMake is case sensitive.

`Tpetra_INST_CUDA:BOOL=${CUDA}` was present and `Kokkos_ENABLE_CUDA:BOOL=$CUDA` had to be added to the script, in addition to the configure lines mentioned earlier.

**Comment by mhoemmen** [comment]
@ndellingwood Trilinos' CMake should auto-detect CUDA.  I usually never have to add `Kokkos_ENABLE_CUDA`.
