### ISSUE TITLE
Memory leak in Kokkos::initialize

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1194]
Here is the snippet, the C string `num1_only` never gets freed/deleted:
```cpp
        char* num1 = strchr(arg[iarg],'=')+1;
        char* num2 = strpbrk(num1,",");
        int num1_len = num2==NULL?strlen(num1):num2-num1;
        char* num1_only = new char[num1_len+1];
        strncpy(num1_only,num1,num1_len);
        num1_only[num1_len]=0;

        if(!Impl::is_unsigned_int(num1_only) || (strlen(num1_only)==0)) {
          Impl::throw_runtime_exception("Error: expecting an integer number after command line argument '--kokkos-ndevices'. Raised by Kokkos::initialize(int narg, char* argc[]).");
        }
        if((strncmp(arg[iarg],"--kokkos-ndevices",17) == 0) || !kokkos_ndevices_found)
          ndevices = atoi(num1_only);
```
Why are we, in a modern C++11 code, calling things like `strpbrk` and raw `new` in non-performance-critical code??

I'll submit a PR to just call `delete` in a moment, but the real fix is to get all of this C-style code replaced with `std::string`.

More importantly, we should incorporate Valgrind into Kokkos testing.

**Comment by mhoemmen** [comment]
> but the real fix is to get all of this C-style code replaced with std::string.

+1 (more like +N)
