### ISSUE TITLE
Kokkos-Trilinos Promotion Testing Results for Promotion version 02.04.11

### ISSUE THREAD

**Issue by dalabre** [kokkos/kokkos#1196]
Contained within is a summary of results for the test performed for promotion of Kokkos Master to version 02.04.11. These results are appropriate for the Trilinos PR submission.

**Comment by ndellingwood** [comment]
Related issues: #1156 and #1186

**Comment by dalabre** [comment]
Results from testing on **kokkos-dev, bowman** and **white** ; these results are generated using script
_kokkos/config/test-all-sandia_. 
[kokkos-test-results-for-2.04.11-promotion.txt](https://github.com/kokkos/kokkos/files/1423653/kokkos-test-results-for-2.04.11-promotion.txt)

**Comment by dalabre** [comment]
@crtrott Results from trilinos-integration testing on white are included here.

The white OMP results showed identical test failures, i.e. No New Failures  This file  
[white-omp-results-for-2.04.11-promotion.txt](https://github.com/kokkos/kokkos/files/1423754/white-omp-results-for-2.04.11-promotion.txt) identifies the problems which failed.

The white CUDA results showed three nominal "diffs" in the comparison between Trilinos with Kokkos snapshotted in versus the Trilinos develop branch. These are
```
	797 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Failed)			      |		797 - Anasazi_Epetra_ModalSolversTester_MPI_4 (Timeout)
	809 - Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Failed)		      |		809 - Anasazi_Epetra_OrthoManagerMatTester_4_MPI_4 (Timeout)
	867 - Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Timeout)   |		867 - Anasazi_Tpetra_TraceMinDavidson_largest_standard_test_MPI_4 (Failed)
```
For problem 797 and 809, the tests with Kokkos snappshotted in "Failed" while the Trilinos Develop branch "Timeout" - both are failures. In problem 867, the reverse occurred - again both failures. So effectively "no differences" for the Cuda results either.  The full summary presented side-by-side is presented in this file 
[white-cuda-results-for-2.04.11-promotion.txt](https://github.com/kokkos/kokkos/files/1423765/white-cuda-results-for-2.04.11-promotion.txt) .

The above results thus indicate **No New Failures** when snapshotting Kokkos into Trilinos develop for Cuda Testing on White.

**Comment by ndellingwood** [comment]
**Serial Shepard Results**

**Summary**:
At first glance, it looked like there were 3 'new' test failures in the updated build (after Kokkos snapshot); looking more closely, these tests did not even build/run in the pristine build. 
**Updated branch**: no build failures, all tests ran, 6 test failures
**Pristine branch**:  5 build failures, 131 tests did not run (3 of those are the extra 3 failures above), 3 failures


**Details**
Updated branch
•	Build errors: 0

•	Test failures: 6
```
ML_MLP_Restart_MPI_4 (Failed)
NOX_Thyra_Heq_MPI_1 (Failed)
ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceCVaR_MPI_4 (Failed)
PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Failed)
PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Failed)
PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Failed)
```

•	Tests not run: 0


-----------------------------------------------------
Pristine branch
•	Build errors: 5 errors that begin ‘icpc: error #10106: Fatal error in…’
Pasted errors below

•	Test failures: 3
```
ML_MLP_Restart_MPI_4 (Failed)
NOX_Thyra_Heq_MPI_1 (Failed)
ROL_adapters_tpetra_test_sol_TpetraSimulatedConstraintInterfaceCVaR_MPI_4 (Failed)
```

•	Tests not run: 131
-	This includes the 3 mismatched test failures from the updated branch
```
PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Not Run)
PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Not Run)
PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Not Run)
```

Build errors:
```
icpc: error #10106: Fatal error in /home/projects/x86-64/intel/compilers/2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /ascldap/users/ndellin/IntegrationTests/serial/trilinos-pristine/packages/stokhos/src/sacado/kokkos/vector/muelu/MueLu_ParameterListInterpreter_MP_Vector_Serial.cpp (code 1)
make[2]: *** [packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/build.make:1350: packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/vector/muelu/MueLu_ParameterListInterpreter_MP_Vector_Serial.cpp.o] Error 1

icpc: error #10106: Fatal error in /home/projects/x86-64/intel/compilers/2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /ascldap/users/ndellin/IntegrationTests/serial/trilinos-pristine/packages/stokhos/src/sacado/kokkos/vector/muelu/MueLu_Ifpack2Smoother_MP_Vector_Serial.cpp (code 1)
make[2]: *** [packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/build.make:1028: packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/vector/muelu/MueLu_Ifpack2Smoother_MP_Vector_Serial.cpp.o] Error 1

[ 92%] Building CXX object packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/pce/muelu/MueLu_CoordinatesTransferFactory_kokkos_UQ_PCE_Serial.cpp.o
icpc: error #10106: Fatal error in /home/projects/x86-64/intel/compilers/2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /ascldap/users/ndellin/IntegrationTests/serial/trilinos-pristine/packages/stokhos/src/sacado/kokkos/vector/muelu/MueLu_IntrepidPCoarsenFactory_MP_Vector_Serial.cpp (code 1)
make[2]: *** [packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/build.make:1074: packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/vector/muelu/MueLu_IntrepidPCoarsenFactory_MP_Vector_Serial.cpp.o] Error 1

icpc: error #10106: Fatal error in /home/projects/x86-64/intel/compilers/2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /ascldap/users/ndellin/IntegrationTests/serial/trilinos-pristine/packages/stokhos/src/sacado/kokkos/vector/muelu/MueLu_CoalesceDropFactory_kokkos_MP_Vector_Serial.cpp (code 1)
make[2]: *** [packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/build.make:476: packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/vector/muelu/MueLu_CoalesceDropFactory_kokkos_MP_Vector_Serial.cpp.o] Error 1

[ 92%] Building CXX object packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/pce/muelu/MueLu_DirectSolver_UQ_PCE_Serial.cpp.o
icpc: error #10106: Fatal error in /home/projects/x86-64/intel/compilers/2017/compilers_and_libraries_2017.4.196/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /ascldap/users/ndellin/IntegrationTests/serial/trilinos-pristine/packages/stokhos/src/sacado/kokkos/vector/muelu/MueLu_RefMaxwell_MP_Vector_Serial.cpp (code 1)
make[2]: *** [packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/build.make:1695: packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/sacado/kokkos/vector/muelu/MueLu_RefMaxwell_MP_Vector_Serial.cpp.o] Error 1

make[2]: Target 'packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:110822: packages/stokhos/src/CMakeFiles/stokhos_muelu.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:163: all] Error 2
make: Target 'default_target' not remade because of errors.
srun: error: node70: task 0: Exited with exit code 2
```

---------------------------------------------------------------------------------------
Repo/branch/sha details:
Kokkos
Branch: promotion
Sha: ed36c017e79dadfda2a72ce79bedc7ff65e44bea

Top log message:
commit ed36c017e79dadfda2a72ce79bedc7ff65e44bea
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Wed Oct 25 16:10:29 2017 -0600

    Update module devpack in shepard scripts

---------------------------------------------------------------------------------------
Trilinos-pristine
Branch: kokkos-promotion-test
Sha: 7ff1540150437dd5df07bf63143034b2346f4d4b

Top log message:
commit 7ff1540150437dd5df07bf63143034b2346f4d4b
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Wed Oct 25 16:35:16 2017 -0600

    Modify configure-testbeds-jenkins-all for pthreads again

---------------------------------------------------------------------------------------
Trilinos-updated
Branch: kokkos-promotion-test
Sha:
Top 2 log messages: 507a02409c31ffba7addf4bdc8d009feee4a8173
commit 507a02409c31ffba7addf4bdc8d009feee4a8173
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Fri Oct 27 09:57:13 2017 -0600

    Snapshot of kokkos from commit ed36c017e79dadfda2a72ce79bedc7ff65e44bea

    From repository at https://github.com/kokkos/kokkos

    At commit:
    commit ed36c017e79dadfda2a72ce79bedc7ff65e44bea
    Author: Nathan Ellingwood <ndellin@sandia.gov>
    Date:   Wed Oct 25 16:10:29 2017 -0600

        Update module devpack in shepard scripts

commit 7ff1540150437dd5df07bf63143034b2346f4d4b
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Wed Oct 25 16:35:16 2017 -0600

    Modify configure-testbeds-jenkins-all for pthreads again

**Comment by ndellingwood** [comment]
Rebuilt the pristine branch (without scripts) - 0 errors. 
Reran the Panzer tests:
```
97% tests passed, 3 tests failed out of 113

Label Time Summary:
Panzer    = 121.81 sec (113 tests)

Total Test time (real) = 122.14 sec

The following tests FAILED:
	111 - PanzerAdaptersIOSS_tIOSSConnManager1_MPI_1 (Failed)
	112 - PanzerAdaptersIOSS_tIOSSConnManager2_MPI_2 (Failed)
	113 - PanzerAdaptersIOSS_tIOSSConnManager3_MPI_3 (Failed)
Errors while running CTest
```

The same tests failed; there was no change between the pristine build and updated build, promotion is safe to proceed :)

**Comment by crtrott** [comment]
OK I gonna transfer this info in the actual pull request tonight ( trilinos/trilinos#1916 )

**Comment by dalabre** [comment]
Promotion completed ( Trilinos: Kokkos promotion 2.04.11 #1915 ).  Closed.
