### ISSUE TITLE
TPL_ENABLE_CUDA=ON and building with nvcc_wrapper doesn't enable Kokkos::Cuda by default

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1197]
Hi all!  I configured Kokkos in Trilinos (after this past week's promotion) using the SEMS modules, CUDA 8 and GCC 5.3.0, with the following options:
```
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
-D BUILD_SHARED_LIBS:BOOL=ON
-D Trilinos_ENABLE_OpenMP:BOOL=ON
-D Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL=ON
-D Trilinos_ENABLE_Fortran:BOOL=OFF
-D TPL_ENABLE_CUDA:BOOL=ON
  -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON
  -D Tpetra_INST_CUDA:BOOL=ON
  -D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON
  -D CMAKE_CXX_FLAGS:STRING="-Wall"
  -D Trilinos_CXX11_FLAGS:STRING="-std=c++11 --expt-extended-lambda"
-D Teuchos_ENABLE_COMPLEX:BOOL=ON
-D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON
-D TPL_ENABLE_MKL:BOOL=OFF
-D TPL_ENABLE_Matio:BOOL=OFF
-D TPL_ENABLE_SuperLU:BOOL=OFF
-D TPL_ENABLE_Zlib:BOOL=OFF
-D TPL_ENABLE_Netcdf:BOOL=OFF
-D TPL_ENABLE_HDF5:BOOL=OFF
-D TPL_ENABLE_ParMETIS:BOOL=OFF
-D TPL_ENABLE_Boost:BOOL=OFF
-D TPL_ENABLE_BoostLib:BOOL=OFF
-D TPL_ENABLE_yaml-cpp:BOOL=OFF
-D TPL_ENABLE_MPI:BOOL=ON
-D CMAKE_BUILD_TYPE:STRING=RELEASE
-D Trilinos_ENABLE_OpenMP:BOOL=OFF
-D Kokkos_ENABLE_OpenMP:BOOL=OFF
-D Kokkos_ENABLE_Pthread:BOOL=OFF
-D Tpetra_INST_SERIAL:BOOL=ON
-D MueLu_ENABLE_Tutorial:BOOL=OFF
-D KokkosKernels_INST_MEMSPACE_CUDASPACE:BOOL=OFF
```
CMake stops with the following error:
```
CMake Error at packages/tpetra/CMakeLists.txt:435 (MESSAGE):
  Tpetra: The Kokkos::Cuda execution space is disabled, but you enabled the
  corresponding Tpetra Node type by setting Tpetra_INST_CUDA=ON.  If you want
  to enable instantiation and use of Kokkos::Cuda in Tpetra, you must enable
  the Kokkos::Cuda execution space by setting Kokkos_ENABLE_Cuda=ON.
```
What gives?  Does Kokkos' CMake logic no longer detect CUDA?

**Comment by mhoemmen** [comment]
Work-around: Set CMake option `Kokkos_ENABLE_Cuda:BOOL=ON` explicitly.

**Comment by ndellingwood** [comment]
@mhoemmen I had to add `Kokkos_ENABLE_Cuda:BOOL=ON` explicitly to the configure script during the integration testing as well; I'm not sure why, but thought I should add this info as another data point.

**Comment by crtrott** [comment]
OK something screwed up the cmake logic, this needs to get fixed. Also there is a problem with the Serial initialization fix which was manually put on and thus was not part of the integration testing. While I ran it through checkin-test it only causes issues if OpenMP (or Pthreads) is enabled and someone tries to use the Serial exec space. I will have an emergency fix for that in a few minutes ..

**Comment by ibaned** [comment]
Seems I broke this. Just merged @crtrott 's fix into Kokkos develop. Will do checkin testing to patch Trilinos develop later today.

**Comment by ibaned** [comment]
The patch should be in Trilinos develop now.

**Comment by mhoemmen** [comment]
Thanks @ibaned ! :D
