### ISSUE TITLE
Issue #1184 was incomplete broke builds which use both OpenMP and Serial, or Pthreads and Serial

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1199]
Kokkos initialize was not initializing Serial, and now it correctly reported back that it was not initialized so that all the Serial tests wouldn't run. Fix this by making Kokkos::initialize run initialize for Serial as well if it is configure time enabled. Previously it only ran it for DefaultExecSpace and DefaultHostExecSpace.

**Comment by ibaned** [comment]
Why don't we do this for all the spaces? Is there any point in enabling a space at compile time if it will never be initialized? e.g. enabling both OpenMP and Threads at compile time?
