### ISSUE TITLE
ROCm builds broke with  commit cad2936

### ISSUE THREAD

**Issue by chipfreitag** [kokkos/kokkos#1202]
This was merged on Saturday with pull request 1193.

Issue 1197 added an include file at
https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Traits.hpp#L50

ROCm is defined, but for some reason the hc.hpp file has not been included yet.  So the ROCm
bit op cases blow up (hc namespace not defined)

Not sure how I flag an issue like this.

**Comment by ibaned** [comment]
To be clear, this was pull request #1193, commit cad293691401ec8d7a6427c22142bf30d0ac1bb7 that did this.

@chipfreitag is the fix as easy as including `hc.hpp` from `Kokkos_BitOps.hpp`?

@crtrott

**Comment by chipfreitag** [comment]
Yes, it looks like just including the file fixes the issue.  I'll create an issue, an issue-branch, and a pull request.

**Comment by ibaned** [comment]
@chipfreitag did this actually get fixed already?

**Comment by chipfreitag** [comment]
Yes.  Commit d3a93b9 on November 3.
