### ISSUE TITLE
Clarify policy regarding competing ExecSpaces

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1204]
The recent issues with `Kokkos::Serial` have brought to light a question regarding how `Kokkos::initialize` works. This is best illustrated with the example of users enabling both `OpenMP` and `Threads` (competing ExecSpaces) simultaneously. This issue is for us to state clearly the answers to:
1. Should we allow competing spaces to be enabled together at compile time?
2. If yes, how should they get initialized (by `Kokkos::initialize`, possibly based on a command line flag) ?

@crtrott @dsunder

**Comment by ibaned** [comment]
If we don't allow this at compile time, then we should check at configure time that no competing spaces are enabled together.

**Comment by ibaned** [comment]
@dsunder was pretty clear that OpenMP and Threads will no longer be able to be enabled at compile time together anymore. There will be a compile-time check in Kokkos to prevent this.

**Comment by mhoemmen** [comment]
I'm pretty sure that I agree with this, given that folks have been telling me that OpenMP does not promise interoperability with C++ threads.

**Comment by hcedwar** [comment]
For each type of device there is at most one execution space; however, Serial is a special case where it may be (someday) possible to use Serial within a truly parallel computation.

**Comment by hcedwar** [comment]
Document in the wiki

**Comment by ibaned** [comment]
To elaborate on @hcedwar 's response, going forward, Kokkos will no longer allow compile-time enable of OpenMP and Threads, or CUDA with another GPU backend. The three categories are Serial, Host, and some kind of "attached accelerator", and only one space each is allowed to be configured at compile time.

**Comment by ibaned** [comment]
This is now documented on the Wiki: https://github.com/kokkos/kokkos/wiki/Compiling#44-execution-space-restrictions
