### ISSUE TITLE
stride() is inconsistent with dimension(), extent(), etc.

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1214]
Why does `View::stride()` take an array and fill in all the values while `View::dimension()` and `View::extent()` each take an index and return one value? This seems really inconsistent and less friendly to use. Can we add a `stride()` method that just takes an index and returns one value?

@hcedwar @crtrott

**Comment by dholladay00** [comment]
I had this conversation recently and I recall it dealing with the cost of stride per dimension, but I don’t remember all of the details.

**Comment by ibaned** [comment]
hmm I guess fundamentally stride() is multiplying out all the dimensions, so doing it all at once is more efficient that calling one at a time, so I guess I understand the motivation a bit more. still, in my case I only need one, so for that special case its less efficient.

**Comment by dholladay00** [comment]
I’m not sure it’s a special case. I think it’s fairly common when interfacing views with linear algebra libraries. My comment wasn’t trying to discourage the feature, I was just reiterating the explanation I received when I asked this question.

**Comment by mhoemmen** [comment]
`stride` was really annoying in the past, in that it required an array of 8 entries as output, regardless of the View's rank.  I'm hoping that is no longer the case.

**Comment by ibaned** [comment]
@mhoemmen as far as I know thats still the case, thats why I opened this issue.

**Comment by dholladay00** [comment]
I was able to do the following without issues:

```c++
View<double**> A("A", M, N); // 2D view
int A_stride[A.Rank]; // length 2 array
A.stride(A_stride); // can pass length 2 array int stride call
```

**Comment by ibaned** [comment]
Oh yes, I misspoke there. I think the requirement has shifted to only being sized by the rank, so yes that particular issue has been fixed. I'm only referring to the need to pass an array at all.

**Comment by dholladay00** [comment]
Yep, I would like to be able to do `A.stride(1)`, etc. to be able to get a specific stride as I only need 1 of the strides for linear algebra calls.
