### ISSUE TITLE
Building Doxygen Documentation

### ISSUE THREAD

**Issue by ian-bertolacci** [kokkos/kokkos#1216]
Trying to explore Kokkos some, but cannot build the documentation.
Running the `build_docs` script under the directory `doc/` gives the error: 

    @INCLUDE = ../../common/Doxyfile: not found!

Im assuming this comes from the setting of the variable `TRILINOS_HOME` to `doc/../../..`, which is 2 directories above the kokkos root directory, presumably somewhere in this Trilinos hierachy.
But I don't even have this Trilinos thing.

How is the doxygen documentation for Kokkos built?

**Comment by mhoemmen** [comment]
@ian-bertolacci wrote:
> But I don't even have this Trilinos thing.

Kokkos used to be part of the Trilinos (see https://github.com/trilinos/Trilinos ) repository.  Kokkos' Doxygen builds as part of Trilinos' Doxygen building process.  You can find pre-built Doxygen documentation here:  https://trilinos.org/packages/kokkos/kokkos-doxygen/

However, Kokkos developers prefer that users refer to the Kokkos tutorial and users' guide.  The Doxygen is not up to date.  The nature of the Kokkos library makes it hard to express its documentation in Doxygen.

**Comment by ibaned** [comment]
We've just recently put up the programming guide on our Wiki:
https://github.com/kokkos/kokkos/wiki
This will likely be "the" place for documentation going forward.

**Comment by crtrott** [comment]
You may also find that the wiki has placeholders for an API reference. We are working on that as well. As Mark said, we never managed to convince doxygen to put out sane documentation for Kokkos so we believe that is a better way forward.
