### ISSUE TITLE
Aid vectorization in Kokkos parallel region

### ISSUE THREAD

**Issue by HBTUM** [kokkos/kokkos#1217]
I have a problem concerning auto-vectorization in conjunction with Kokkos. Carrying out simple operations in a parallel for loop, e.g.
```
parallel_for(TeamPolicy<>(YSIZE,AUTO,1),KOKKOS_LAMBDA(member_type thread)
{
  j = thread.league_rank();
  parallel_for(TeamThreadRange<>(thread,XSIZE), [=] (const int i){
    kokkosViewC(i,j) = kokkosViewA(i,j) + kokkosViewB(i,j);
  });
});
```
vectorizes without problem.
In my case I call a high level function, which calls several low level functions. In this case the auto-vectorization does not work anymore. The workaround for the pre-Kokkos code was passing a pointer to the array and implement short loops in the low level functions which can be vectorized, e.g.
```
// Data vector
int a[SIZE], b[SIZE], c[SIZE]
// Helper
int* aP, bP, cP

int vecHelper = 16;


int main()
{
  // Some time loop
  aP = a;
  bP = b;
  cP = c;
  // This outer loop can not be vectorized
  for(int i = 0; i<(SIZE); i=i+vecHelper)
  {
    highLevelFunction(cP,aP,bP);
    aP +=16;
    bP +=16;
    cP +=16;
  }
  // end of time loop

return 0;
}

KOKKOS_FORCEINLINE_FUNCTION
void highLevelFunction(int* cP, int* aP, int* bP)
{
  /* Do Stuff */
  someLowLevelFunc(cP, aP,  bP)
}

KOKKOS_FORCEINLINE_FUNCTION
void someLowLevelFunc(int* cP, int* aP, int* bP)
{
  // low level loop that can be auto vectorized
  for(int ii = 0; ii<vecHelper; ++ii)
     c[ii] = a[ii] + b[ii];
}
```

This does not work with Kokkos, unless using a raw pointer to the data (which seems not the right way concerning data layout etc.). Is it possible to tell the inner loop (e.g. TeamThreadRange), that it should increment by vecHelper and not by 1, so each thread still handles a chunk of the data stored in the view and therefore allows still using the small inner loops. If not is there another way to help the compiler vectorize the stuff happening in the parallel region?

EDIT: added the KOKKOS_FORCEINLINE_FUNCTION attribute

**Comment by ibaned** [comment]
Make sure the compiler can see the definition of both functions when its compiling `parallel_for`, and give them both the `KOKKOS_INLINE_FUNCTION` attribute:
```cpp
// these must be visible when compiling the parallel_for
KOKKOS_INLINE_FUNCTION
void highLevelFunction(int* cP, int* aP, int* bP)
{
  /* Do Stuff */
  someLowLevelFunc(cP, aP,  bP)
}

KOKKOS_INLINE_FUNCTION
void someLowLevelFunc(int* cP, int* aP, int* bP)
{
  // low level loop that can be auto vectorized
  for(int ii = 0; ii<vecHelper; ++ii)
     c[ii] = a[ii] + b[ii];
}
```

You may also want to try `KOKKOS_FORCEINLINE_FUNCTION`.

**Comment by HBTUM** [comment]
Both functions do have the KOKKOS_FORCEINLINE_FUNCTION attribute. I just forgot to add it in the example. Unfortunately this does not resolve the issue.

**Comment by HBTUM** [comment]
UPDATE: What I have gathered after crawling through the full vectorization output, is that the compiler has problems with pointer aliasing (connected to the Kokkos views I am using in the loop) and is doing loop versioning. Increasing the vect-max-version-for-alias-check parameter resolved the issue. Probably not a favorable general approach, but so far I have not found another solution.

**Comment by mhoemmen** [comment]
Some compilers may have trouble proving that a pointer in a struct or class doesn't alias other pointers.  This is exactly the case of a `Kokkos::View`.  Newer compilers seem to do better at this.

**Comment by stanmoore1** [comment]
What is the status of using `restrict` with `Kokkos::View`?

**Comment by ibaned** [comment]
I just thought about this a bit, and one of the issues is that there is no guarantee that two Kokkos Views don't point to overlapping memory, in fact it may happen often.

**Comment by mhoemmen** [comment]
@ibaned Restrict is really a use trait, not a property of a piece of memory throughout its lifetime.  For example, it should be legit to apply `restrict` to two nonoverlapping subviews of the same parent view, as long as the algorithm(s) that use(s) the subviews never alias with the parent view or or with other subviews that overlap them.

**Comment by ibaned** [comment]
@mhoemmen that makes sense, its similar to atomic access. I wonder if someone can hack this by taking a raw pointer from a View, making it restrict, and seeing if the compiler starts optimizing things then. if that works we can try to add it as an official feature.

**Comment by stanmoore1** [comment]
I thought the new compilers were going to make `restrict` a sticky trait, @nmhamster any comments?

**Comment by stanmoore1** [comment]
I talked to @crtrott, he said that there actually is a `restrict` trait on `Kokkos::View` but it doesn't always work. See https://github.com/kokkos/kokkos/issues/517 and https://github.com/kokkos/kokkos/pull/559.
