### ISSUE TITLE
Possible Bug: Kokkos::Single Kokkos::PerTeam compilation warning  

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos#1224]
@crtrott 

I am allocating some memory from memory pool, using Kokkos Single, and I want the allocation to be broadcasted within the team as below.
```c++
Kokkos::single(Kokkos::PerTeam(teamMember),[=] (volatile nnz_lno_t * &memptr) {
  memptr = (volatile nnz_lno_t * )( memory_pool.allocate(tid));
  }, tmp);
```

I am getting warnings as below:
```
......kokkos/install/include/impl/Kokkos_HostThreadTeam.hpp(585): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "void Kokkos::Impl::HostThreadTeamMember<HostExecSpace>::team_broadcast(const Closure &, T &, int) const [with HostExecSpace=Kokkos::OpenMP, Closure=lambda [](volatile int *&)->void, T=volatile int *]" 
(1073): here
            instantiation of "void Kokkos::single(const Kokkos::Impl::ThreadSingleStruct<Kokkos::Impl::HostThreadTeamMember<Space>> &, const FunctorType &, ValueType &) [with Space=Kokkos::OpenMP, FunctorType=lambda [](volatile int *&)->void, ValueType=volatile int *]" 
```

This was okay if I do PerThread instead of PerTeam. Am I using incorrectly or is there a possible bug?

**Comment by crtrott** [comment]
Hm that is funny. Looks like some inconsistent marking of the single function or memory_pool.allocate

**Comment by crtrott** [comment]
Yeah looks like there is some macro protection missing in one of the team_broadcast implementations. It is working correct, but we need to get that warning fixed.

**Comment by mndevec** [comment]
Okay, thanks Christian. 
I won't be worried about the warning in terms of performance/correctness for now then.
