### ISSUE TITLE
Introduce TeamVectorRange policy

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos#1227]
For example given a single dimensional view, I want to increment each value in the view. 
With range policy it is easy to write this as:
```c++
  KOKKOS_INLINE_FUNCTION
  void operator()(const size_t ii) const {
    view(ii) = view(ii) + 1;
  }
```
I am having difficulty to write these simple single dimensional operations with team policy. For example, I want to repeat the same operation within a team on an array that is private to the team. To do this, I am providing the vector size to the functor and using a operator as below. 

```c++
  KOKKOS_INLINE_FUNCTION
  void operator()(const team_member_t & teamMember) const {
  //some code
    	  lno_t num_thread_work =  num_entries_in_private_array / vector_size ;
          if (num_entries_in_private_array % vector_size) num_thread_work++
    	  Kokkos::parallel_for( Kokkos::TeamThreadRange(teamMember,num_thread_work), [&] (lno_t threadind) {

    		  lno_t thread_shift = threadind * vector_size;
    		  lno_t work_to_handle = KOKKOSKERNELS_MACRO_MIN(vector_size, num_entries_in_private_array - thread_shift);
    		  Kokkos::parallel_for( Kokkos::ThreadVectorRange(teamMember, work_to_handle ), [&] (lno_t i) {
    			  team_private_array[thread_shift + i] += 1;
    		  });
    	  });
  //some code
  } 
```
Is there an easy way of doing the same behaviour to distribute all the work to the vectors without going through this partitioning everytime?

**Comment by mndevec** [comment]
Actually, what I need is TeamVectorRange for simplicity. Is there such a mechanism in kokkos that I am missing?

**Comment by dholladay00** [comment]
#713 I have this in as a feature request as well. More demand can't hurt

**Comment by crtrott** [comment]
There is always a chance ;-)

No seriously I want that as well. Just need to find the time to actually implement it.

**Comment by crtrott** [comment]
Need to move this, there is quite a bit of work in this with reductions and scans etc.

**Comment by crtrott** [comment]
Closing this as duplicate.
