### ISSUE TITLE
Implicit barriers in team parallel for

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos#1231]
Are there implicit team_barrier() at the beginning and end of parallel_for's for team thread range?
```c++
member.team_barrier(); //is this duplication?

Kokkos::parallel_for( Kokkos::TeamThreadRange(teamMember, num_threads), FUNCTOR); 
member.team_barrier(); //is this duplication?
```

**Comment by crtrott** [comment]
There are no implicit barriers either at entry or exit. The parallel_reduce though has an implicit barrier at exit since it involves a broadcast.
