### ISSUE TITLE
Threads backend doesn't compile with Clang on OS X

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1232]
It will be great if I can get the latest information of Kokkos support for OS X; in particular Clang compilers.  The information in README is a bit outdated.

**Comment by keitat** [comment]
=== Message from Danny Dunlavy ====
I am using Xcode 8.2:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0

which does not contain cstdalign.h:

/Users/dmdunla/dev/hpda-tensors/tensor/sparten/tpl/kokkos/core/src/Threads/Kokkos_ThreadsExec.hpp:53:10: fatal error: 'cstdalign' file not found
#include 

I looked online and it is not clear whether Xcode 9 has it either. So this dependency means that Apple clang may not be an option for building.

**Comment by ibaned** [comment]
Can confirm this is still an issue with:
```
Apple LLVM version 9.0.0 (clang-900.0.38)
```

**Comment by ibaned** [comment]
It is not an issue with:
```
clang version 5.0.0-svn301099-1~exp1
```
on Ubuntu.
However, on both the OS X and Ubuntu platforms I have, Kokkos Core and its tests still compile with `<cstdalign>` removed, under Clang, suggesting the header may not be needed.

**Comment by ibaned** [comment]
The include was added in ead19d55 and only has to do with `alignas`, but `grep` says that `kokkos/core/` contains no references to `alignas`, we instead use `__attribute__((aligned(N)))` for alignment control. This further suggests it can be removed.

**Comment by ibaned** [comment]
Pull request #1242 should fix this

**Comment by ibaned** [comment]
@keitat  in short, Kokkos needs to be able to build with the latest Clang on OS X, it doesn't, and we're fixing that.
