### ISSUE TITLE
Documentation Hierarchical Parallelism

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1236]
* Add description of custom reductions (or at least correct invalid comments in example code)
  * Add description of implicit barrier semantics (i.e. that there are no implicit barriers for the nested parallel loops)

**Comment by dalabre** [comment]
Made corrections to example code in Nested Parallelism sections (8.4.1 and 8.4.2) and added brief comment regarding using Kokkos-approved reducer functions. @ibaned @crtrott Close this issue if addressed satisfactorily.
Note, implicit barrier semantics documented in #1228.
