### ISSUE TITLE
Kokkos tiled layout

### ISSUE THREAD

**Issue by d-daniel** [kokkos/kokkos#1239]
I'm having trouble using tiled layout and Cuda execution space. The views won't get copied to host space. Here is the code:
````
typedef Kokkos::View<int**, Kokkos::LayoutTileLeft<16,16>> tile_type;
tile_type a("a", 1024, 1024);
tile_type b("b", 1024, 1024);
tile_type::HostMirror h_a = Kokkos::create_mirror_view(a);
tile_type::HostMirror h_b = Kokkos::create_mirror_view(b);

// Initialize "h_a" and "h_b" on host
...

// Copy from host to device
Kokkos::deep_copy(a, h_a);
Kokkos::deep_copy(b, h_b);
````

I get the following runtime error: "deep_copy given views that would require a temporary allocation".
Is there any sample code that deals with tiles?

**Comment by ndellingwood** [comment]
The `LayoutTileLeft` layout lacks a `deep_copy` implementation, causing the error. That code itself is not actively developed, and I believe exists primarily as an example for how users can extend the View layout functionality. Design discussions are underway regarding extending Kokkos' `View` layouts to support tiling.

**Comment by ibaned** [comment]
`LayoutTileLeft` is not fully featured, and we don't currently have plans to make it so. It should've probably been in the `Kokkos::Experimental` namespace. We'll reopen this if we have more reason to fully implement that layout.
