### ISSUE TITLE
parallel_launch_local_memory and cuda 7.5

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#125]
Getting this error
/home/mbetten/Trilinos/cuda-intrepid-install-opt/include/Cuda/Kokkos_CudaExec.hpp(181):
Error: Formal parameter space overflowed (4096 bytes max) in function _ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_11ParallelForI19WeightChargeFunctorNS_10TeamPolicyINS_4CudaEvS5_EEEEEEvT_

Christian said
Ok I found it. It is in the new more accurate function to figure out what the best team size etc is. You find it in this file:
kokkos/core/src/Cuda/Kokkos_Cuda_Internal.hpp

If you for now replace all "cuda_parallel_launch_local" with "cuda_parallel_launch_constant" in that file it should work again.

I need to split the functions and make the "Large" check a template parameter, so that not both branches are instantiated for
each functor. Bummer. We also need to add a functor test larger than 4kB to our test suite to catch this the next time.

Christian

**Comment by crtrott** [comment]
Pushed to master
