### ISSUE TITLE
new simd layout ???

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1256]
Hello,

I am thinking about interoperatibility between scalar view and simd view. Here is an example,
```
constexpr int vl = 4; // vector length
View<SIMD*> A("A", N); // N dimension simd array, it has N*4 doubles. 

// now we have this view, we need to fill the view with some coefficients we compute from physics
// at this moment I would like to treat it as standard view

// case 1
View<double*> AA = A; 
// By overriding the assignment operator, this is possible. 
// - AA(i) = data[i/vl][i%vl] returns a scalar and A(i) returns SIMD type.
// - AA is supposed to have a dimension N*vl (this can be done during assignment), A has dimension N
// For multidimensional array, it restrict which dimension is packed. 
// - layoutleft packs most left dimension and layoutright packs the most right dimension.
// - FE computation usually wants to pack on Cell dimension. Layout right does not allow to do so. 

// case 2
View<double*,SimdLayout<packDim,vl,LayoutParam> > AA = A;
// packDim and vl are used to identify location of scalar by indices. LayoutParam should be inherited from A and not explicitly used(or we always use strided layout). Here I put that to show what is necessary.
// This is similar to 1D tile layout. I believe that tile layout is not maintained well and no one wants to improve it.
// the new layout compute strides according to pack dimension and vector length. 
// the layout is harnessed with specialized view offset so it can compute indicies correctly.

// Now a user can treat AA as a scalar view that can work with other exisiting scalar based library
// and fill the A in a conventional way then interface the A with vectorized kernel libraries. 
```

@hcedwar How do you think ? If you consider a SIMD type as a part of a programming model, View needs to provide an easy inter-operatibility so that it can run with any numeric kernels as long as they use operator().

**Comment by mhoemmen** [comment]
@etphipp Would this mean that Views of FAD, etc. would no longer need methods for the "internal View" of double?  Could one just assign from the View of FAD to the View of double with the appropriate layout?

@mrtupek

**Comment by etphipp** [comment]
I don't understand your comment about AA(i) not matching A(i) regarding case 1.

Regarding Mark's comment, you can already do that with the Sacado and Stokhos views:
```
constexpr int vl = 4;
View<Vector<double,vl> > A("A", N);

View<double*> AA = A; // View of dimension (vl*N,1)
View<double**> AAA = A;  // View of dimension (vl,N) or (N,vl) depending on the layout
```

**Comment by kyungjoo-kim** [comment]
@etphipp 

I am sorry. My description is so so clumbsy. I changed the above description. I just want to say that AA(i) is different from A(i).

Extending Eric's example,
```
View<Vector<double,vl>**> A("A", M,N);
View<double**> AA = A ; // AA dimension is either (vl*M, N) or (M, vl*N);
 ```
Probably more emphasis should go on this multidimensional case that pack dimension is bounded by the layout. However, i believe that pack dimension is users' choice. Most FE application uses a multi dimensional array like (Cell = upto 10k, Point = 8 (hexa), Node = 8 (hexa), SpaceDim = 3) and I would like to pack the array along Cell dimension. Without custom layout, I have to use layout left all the time (we know that this is not feasible for many reasons). 

What I propose is that something it allows like
```
View<Vector<double,vector_length>**> A;
View<double**, SimdLayout<pack_dim,vector_length> > AA = A; 

// internally it behaves like...
int extent(int r) { return simd_view_dimensions[r]*(pack_dim == r ? vector_length : 1); } 
std::enable_if<pack_dim == 0, double&>::type operator()(int i, int j) {
  return reference(i/vector_length * vector_length + i%vector_length,j);
}
std::enable_if<pack_dim == 1, double&>::type operator()(int i, int j) {
  return reference(i,j/vector_length * vector_length + j%vector_length);
}
```
As I explain more, it looks more complicated.

**Comment by etphipp** [comment]
OK, I see.  Conceptually you can think of a view with an array-like scalar type like this as a view of one higher rank.  And if you want the user to be able to choose where that extra dimension appears in the multi-dimensional array, I think you are forced to do something like you've described.  Like I said in my office, we do something similar in Sacado.  Unfortunately I think it means you will need a ViewMapping specialization.  Also, I think you probably need to add the array layout as a template parameter to your SimdLayout, to specify what the layout of the outer array is, e.g., SimdLayout<LayoutLeft,pack_dim,vector_length>.  Like I mentioned to you, you will likely need to specialize is_same<> for SimdLayout to get it to work with Kokkos properly, e.g., so that is_same<SimdLayout<LayoutLeft,pack_dim,vector_length>,LayoutLeft >::value == true.

**Comment by kyungjoo-kim** [comment]
Yes, I agree with you. I can also create custom layout and customize view map(or offset) myself as you suggested. I also know that Kokkos will support SIMD type. Kokkos may provide the layout and formalize it. Then, we may get a better and more elegant and more sustainable solution than my hack.

**Comment by ibaned** [comment]
@crtrott @hcedwar

**Comment by crtrott** [comment]
Uhm we implemented that already with Sierra. Mike Tupek has an implementation available. Kyungjoo you should set a meeting up with him. Also please look at his SIMD implementation.

**Comment by kyungjoo-kim** [comment]
@crtrott 

If you mention about the simd_view type in stk, that is not kokkos view but stk::simd::view which get inherited from kokkos view. I am not quite sure if this can be used on gpu and work seamlessly with kokkos view. 

https://github.com/trilinos/Trilinos/blob/master/packages/stk/stk_simd/stk_simd_view/simd_view.hpp

**Comment by mhoemmen** [comment]
@mrtupek could tell you more :-) .

**Comment by mrtupek** [comment]
It does work on the GPU seamlessly, that is the point.  It is taking a slightly different strategy than others might prefer by deriving off of the view (which I personally like better).   We should talk in person so I can explain.  Perhaps we should have a broader group gather to discuss the preferred simd view strategy.

**Comment by kyungjoo-kim** [comment]
I am going to set up a meeting for discussing SIMD view capability. @etphipp @crtrott @mrtupek Who else need to be in the meeting ?

**Comment by rppawlo** [comment]
I'd like to attend if I can call in over skype.

**Comment by mrtupek** [comment]
I'd add mhoemmen too.  If he is willing!

**Comment by mhoemmen** [comment]
@mrtupek I am very much willing; thanks! :D  I care about this quite a bit for the other application on which I'm working.
