### ISSUE TITLE
Question: use of KOKKOS_FUNCTION

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1258]
Currently, much of my implementation is in header files that get placed in 1 or 2 `.cc` files, which each of which contains a `parallel_for` that makes use of a `TeamPolicy`.

If I try to break up into a much greater number of `.cc` files, put implementations in them and use ETI, replace `KOKKOS_INLINE_FUNCTION` with `KOKKOS_FUNCTION`, will that still work and/or be performant with the CUDA backend?

**Comment by ibaned** [comment]
it should work in theory with RDC. It may be a bit slower, I don't have a good intuition for how much slower though.

**Comment by dholladay00** [comment]
That's a relief. However, there is #1259

**Comment by ibaned** [comment]
@dholladay00 I think this question was answered, even if we're still not sure whats going on with #1259. I'll close this, please comment if theres more to be done.
