### ISSUE TITLE
RDC on cuda backend: compile issues

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1259]
In an attempt improve compilation times by breaking things up into more .cc/.cpp files, I seem to have lost the ability to compile on the cuda backend. 

I get a bunch of errors like these:
```
nvlink error   : Multiple definition of '_ZN6Kokkos4Impl75_GLOBAL__N__51_tmpxft_000017c4_00000000_7_Kokkos_Cuda_Task_cpp1_ii_b2872e7123cuda_task_queue_executeEPNS0_9TaskQueueINS_4CudaEEEi' in '../kokkos/libkokkos.a:Kokkos_Cuda_Task.cpp.o', first defined in '../kokkos/libkokkos.a:Kokkos_Cuda_Task.cpp.o'
nvlink error   : entry function 'really_long_mangled_function_name1' with max regcount of 64 calls function 'really_long_mangled_function_name2' with regcount of 184
ptxas error   : Entry function 'really_long_mangled_function_name3' with max regcount of 64 calls function 'really_long_mangled_function_name4' with regcount of 255
```

Many of these are on my end, and appear to be related to launch bounds issues, but I'm not sure how to resolve those. One of them appears to be on the Kokkos side, and again, I do not know how to resolve it.

**Comment by ibaned** [comment]
is it possible to create an example that reproduces this with just a few C++ files?

**Comment by dholladay00** [comment]
Attempts so far have not yielded a reproducer, could be non-trivial.

**Comment by crtrott** [comment]
I assume you enabled RDC properly, and did not just add the compile time manually right?

**Comment by dholladay00** [comment]
I believe so, it was enabled through cmake.

**Comment by dholladay00** [comment]
Multiple definition was really silly and embarrassing, `libkokkos.a` included twice on compile line.

For the regcount, I needed to go in and explicitly set the launch bounds, currently have a working solution, though I'm open to better ways to do it.

```c++
#ifdef KOKKOS_ENABLE_CUDA
typedef Kokkos::TeamPolicy<schedule, Kokkos::LaunchBounds<64,4> > team_policy;
#else 
typedef Kokkos::TeamPolicy<schedule> team_policy;
#endif
```

**Comment by crtrott** [comment]
The LaunchBounds shouldn't effect anything else, so you can just leave the ifdef off and always specify them.
