### ISSUE TITLE
about cmake and Makefile.generate_build_files

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#1261]
In this issue I describe a small problem related to a standalone cmake build, and provide just after a small fix.

The problem:
Currently with develop branch, if you try to build a kokkos application using cmake standalone (e.g. the one provided in example/cmake_build), one has the following behaviour:

```bash
cd example/cmake_build; mkdir build; cd build
ccmake .. # just use the default serial and generate
make
# everything builds and run ok
```

But later, let assume you want to change anything (e.g. turn on KOKKOS_ENABLE_OPENMP).
So change that variable inside ccmake terminal gui, re-generate, and then build again, one obtains linking errors:
```bash
...
cmake_example.cpp:(.text.startup+0x3f): undefined reference to `Kokkos::OpenMP::print_configuration(std::ostream&, bool)'
...
```

If you look carefully the build log, you can notice that the OpenMP sources are missing (so not built) and explains the undefined references. Again, by carefully looking into the generated file kokkos_generated_settings.cmake, everything seems normal: KOKKOS_SRC contains the OpenMP sources, but the problem is this variable is set in cmake cache without the FORCE option, thus CMakeCache.txt is never updated (but should). 

I suggest to slightly modify core/src/Makefile.generate_build_files, so that the generated output contains variables set in cache with the force option.

**Comment by crtrott** [comment]
Thanks for finding this.
