### ISSUE TITLE
cuda_internal_maximum_warp_count returns 8, but I believe it should return 16 for P100 

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#1269]
I believe the maximum number of threads in a thread block on P100 is 32*16 = 512. I thought that cuda_internal_maximum_warp_count would return 512/Impl::CudaTraits::WarpSize = 512/32 = 16, but it returns 8. Is this a bug, or am I misinterpreting the purpose of the function? Thanks.

**Comment by crtrott** [comment]
Let me check this.

**Comment by crtrott** [comment]
Wow yeat, there is a comment from early 2012 on this. I think this is outdated, and also probably not used anywhere ...

**Comment by crtrott** [comment]
This is now fixed. I also changed the behavior of the normal RangePolicy to use a better heuristic for what the block size should be. Furthermore the old heuristic did NOT take register utilization into account, and could thus fail for very complex kernels. We were just lucky that most really complex kernels were already using Hierarchical Parallelism, which was using the better heuristics already.
