### ISSUE TITLE
Kokkos::resize performs poorly on 1D Views

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#1270]
Since Kokkos::resize is for general views (and for loops over all dimension), its performance on 1D Views is very compiler dependent.

Running on GCC 4.9.3 w/ -O3 and -fopenmp using OMP_NUM_THREADS=1 on my CPU I find that a handcoded 1D resize is ~4 times faster than Kokkos::resize

Source code will be attached...

csiefer@lightsaber> ./02_Exercise.host -N 20 -nrepeat 1000
  User N is 1048576
Kokkos::resize() time = 7.4831e+00 Manual resize time = 1.7968e+00

**Comment by crtrott** [comment]
I will fix that. The kernel which does the resize is written too lazily (i.e. there is only a single resize kernel of all view types of any rank or layout). As a consequence you incur tons of overhead and prevent vectorization. Incidentally if you were to actually run your test with all cores busy (i.e. one MPI rank per core or using 1 thread per core) the performance difference should be going away, because then you don't need vectorization or so to saturate memory bandwidth.

**Comment by csiefer2** [comment]
Does Kokkos::deep_copy have a similar issue?

**Comment by crtrott** [comment]
Under certain situations yet, but it is actually using the same copy kernel.

**Comment by crtrott** [comment]
Here is a Performance Comparison for View Fill, Create, DeepCopy and Resize with different Layouts and Ranks. Maximum Speedup 630x on P100. All the cases are more or less fixed, though there are a couple places where we could write more specializations to get even more performance out. 

  |   |   |   | Shepard |   |   | Bowman |   |   | White K80 |   |   | White P100 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Operation | Rank | Source | Dest | Old | New | Speedup | Old | New | Speedup | Old | New | Speedup | Old | New | Speedup
Fill | Raw |   | Left | 47.821442 | 47.876755 | 1.0011566569 | 191.187596 | 190.991556 | 0.9989746197 | -1 | -1 | 1 | -1 | -1 | 1
Fill | 1 |   | Left | 47.686768 | 48.024885 | 1.0070903736 | 183.150949 | 184.32906 | 1.0064324592 | 172.507076 | 172.747058 | 1.0013911429 | 549.047944 | 550.671145 | 1.0029563921
Fill | 2 |   | Left | 29.328376 | 48.093084 | 1.6398140831 | 20.226905 | 191.580884 | 9.4715866812 | 162.711959 | 173.027882 | 1.0633999066 | 370.491328 | 488.562662 | 1.3186885227
Fill | 3 |   | Left | 4.954338 | 48.255056 | 9.7399604145 | 22.105924 | 188.145975 | 8.511111094 | 65.447827 | 173.916447 | 2.6573295856 | 111.753121 | 488.562662 | 4.3718032895
Fill | 4 |   | Left | 6.85426 | 47.359399 | 6.909483883 | 17.081044 | 192.025273 | 11.2420103244 | 6.694744 | 173.22903 | 25.875377759 | 25.187048 | 488.242503 | 19.3846656027
Fill | 5 |   | Left | 6.852243 | 47.659314 | 6.955286612 | 16.852704 | 189.245126 | 11.2293627183 | 6.433174 | 172.626983 | 26.833874383 | 26.156154 | 488.562662 | 18.678688847
Fill | 6 |   | Left | 6.403538 | 48.06206 | 7.5055477144 | 16.361957 | 189.582203 | 11.5867681965 | 6.1939 | 173.027882 | 27.9352075429 | 27.192892 | 488.562662 | 17.9665576578
Fill | 7 |   | Left | 5.533089 | 47.784637 | 8.6361591147 | 14.646891 | 189.485773 | 12.9369279119 | 5.342565 | 172.747058 | 32.33410506 | 20.618737 | 488.562662 | 23.6950819054
Fill | 8 |   | Left | 2.908736 | 48.220702 | 16.5778888149 | 3.661363 | 191.728785 | 52.3654128258 | 0.641318 | 173.068074 | 269.8631162699 | 2.145861 | 488.562662 | 227.6767516629
Fill | Raw |   | Right | 47.892142 | 47.96614 | 1.0015450969 | 191.482411 | 191.630159 | 1.0007716009 | -1 | -1 | 1 | -1 | -1 | 1
Fill | 1 |   | Right | 47.793833 | 47.778508 | 0.9996793519 | 176.679644 | 185.43008 | 1.0495271317 | 172.8272 | 173.027882 | 1.0011611714 | 486.966052 | 488.562662 | 1.0032786885
Fill | 2 |   | Right | 47.839865 | 47.922947 | 1.0017366688 | 193.672488 | 189.389441 | 0.9778851036 | 11.467018 | 172.907417 | 15.0786732 | 61.000332 | 488.562662 | 8.0091803763
Fill | 3 |   | Right | 48.052761 | 47.772381 | 0.9941651636 | 192.77052 | 188.050999 | 0.9755174131 | 5.216799 | 173.068074 | 33.1751470586 | 21.530981 | 488.242503 | 22.6762776392
Fill | 4 |   | Right | 46.624409 | 47.96614 | 1.0287774372 | 156.426215 | 189.920484 | 1.2141218401 | 1.285421 | 172.78712 | 134.4206450649 | 5.515027 | 488.562662 | 88.5875376494
Fill | 5 |   | Right | 47.278257 | 47.993949 | 1.0151378677 | 154.865529 | 190.503211 | 1.2301201709 | 1.30523 | 173.068074 | 132.5958444106 | 5.514986 | 487.922763 | 88.4721671098
Fill | 6 |   | Right | 46.856051 | 47.975406 | 1.0238892304 | 153.556896 | 187.106494 | 1.2184831738 | 1.295231 | 172.78712 | 133.4025513596 | 5.514945 | 488.562662 | 88.5888548299
Fill | 7 |   | Right | 47.060261 | 48.167705 | 1.0235324662 | 94.863517 | 189.005089 | 1.9923896454 | 1.252689 | 172.907417 | 138.0290056031 | 5.514864 | 488.562662 | 88.5901559857
Fill | 8 |   | Right | 27.738573 | 48.421269 | 1.7456294165 | 16.771521 | 191.334889 | 11.4083206288 | 0.310898 | 172.586996 | 555.1241757747 | 2.438241 | 488.562662 | 200.3750498823
Create | Raw |   | Left | 55.473015 | 53.29838 | 0.9607983269 | 64.574281 | 72.18156 | 1.1178066388 | 10.637456 | 10.637608 | 1.0000142891 | 58.837405 | 58.869948 | 1.0005531005
Create | 1 |   | Left | 61.488657 | 61.025314 | 0.9924645777 | 80.11377 | 75.023468 | 0.9364615846 | 10.647641 | 10.639279 | 0.9992146617 | 59.009826 | 59.047239 | 1.0006340131
Create | 2 |   | Left | 61.907608 | 61.251074 | 0.9893949383 | 75.144535 | 76.463266 | 1.0175492602 | 10.640798 | 10.637 | 0.9996430719 | 58.88856 | 58.883906 | 0.9999209694
Create | 3 |   | Left | 62.191825 | 61.130461 | 0.9829340271 | 84.234942 | 71.833596 | 0.8527767016 | 10.638975 | 10.636241 | 0.9997430204 | 58.855996 | 58.911842 | 1.0009488583
Create | 4 |   | Left | 63.023013 | 64.068971 | 1.0165964455 | 74.076164 | 78.237746 | 1.0561797719 | 10.638519 | 10.63776 | 0.9999286555 | 58.846699 | 58.893215 | 1.0007904607
Create | 5 |   | Left | 64.356747 | 62.181444 | 0.9661993015 | 81.152169 | 71.447838 | 0.8804180946 | 10.637 | 10.637152 | 1.0000142897 | 58.855996 | 58.893215 | 1.000632374
Create | 6 |   | Left | 60.051427 | 63.055015 | 1.0500169297 | 79.651279 | 76.236372 | 0.9571267776 | 10.637 | 10.634723 | 0.9997859359 | 58.8746 | 58.921159 | 1.0007908164
Create | 7 |   | Left | 61.145512 | 61.458225 | 1.0051142429 | 74.113007 | 75.152114 | 1.0140205754 | 10.635938 | 10.638823 | 1.0002712502 | 58.865297 | 58.907184 | 1.0007115737
Create | 8 |   | Left | 61.615784 | 61.969397 | 1.0057390003 | 79.813397 | 72.237547 | 0.9050804716 | 10.638519 | 10.62335 | 0.9985741436 | 58.860646 | 58.907184 | 1.0007906471
Create | Raw |   | Right | 54.787709 | 55.300086 | 1.0093520428 | 69.938802 | 71.653978 | 1.0245239545 | 10.637 | 10.639279 | 1.0002142521 | 58.860646 | 58.902527 | 1.000711528
Create | 1 |   | Right | 63.076368 | 62.964427 | 0.99822531 | 83.283932 | 73.527885 | 0.8828579923 | 10.639279 | 10.638215 | 0.9998999932 | 58.939804 | 58.944467 | 1.0000791146
Create | 2 |   | Right | 62.678393 | 63.593211 | 1.0145954284 | 75.068822 | 75.364967 | 1.00394498 | 10.639127 | 10.637912 | 0.9998857989 | 58.842052 | 58.9165 | 1.0012652176
Create | 3 |   | Right | 63.647536 | 64.251299 | 1.0094860389 | 77.569814 | 72.738266 | 0.9377135544 | 10.638064 | 10.637152 | 0.9999142701 | 58.865297 | 58.907184 | 1.0007115737
Create | 4 |   | Right | 60.682364 | 63.452398 | 1.0456480898 | 79.430497 | 73.54966 | 0.9259624801 | 10.637912 | 10.635178 | 0.9997429947 | 58.842052 | 58.89787 | 1.0009486073
Create | 5 |   | Right | 61.372163 | 61.220876 | 0.9975349248 | 75.09152 | 71.461544 | 0.9516593085 | 10.637456 | 10.635786 | 0.9998430076 | 58.860646 | 58.893215 | 1.0005533239
Create | 6 |   | Right | 62.836979 | 63.017682 | 1.002875743 | 77.83724 | 73.202796 | 0.9404598108 | 10.637456 | 10.635938 | 0.9998572967 | 58.851348 | 58.879252 | 1.0004741438
Create | 7 |   | Right | 61.692313 | 63.339119 | 1.0266938605 | 73.54966 | 75.556035 | 1.027279188 | 10.638215 | 10.638064 | 0.9999858059 | 58.860646 | 58.902527 | 1.000711528
Create | 8 |   | Right | 62.773448 | 61.995179 | 0.9876019396 | 76.889377 | 68.266269 | 0.8878504634 | 10.637912 | 10.638367 | 1.0000427716 | 58.860646 | 58.89787 | 1.000632409
DeepCopy | Raw | Left | Left | 33.860119 | 67.301211 | 1.9876247629 | 29.995493 | 60.235917 | 2.0081655934 | -1 | -1 | 1 | -1 | -1 | 1
DeepCopy | 1 | Left | Left | 7.488096 | 14.91772 | 1.9921913394 | 8.065057 | 16.138325 | 2.0010180957 | 80.512001 | 161.4427 | 2.0052004421 | 241.509906 | 483.019812 | 2
DeepCopy | 2 | Left | Left | 7.48178 | 14.949748 | 1.9981539152 | 8.083257 | 16.119122 | 1.9941370168 | 80.800137 | 161.723043 | 2.0015194157 | 242.059149 | 483.48998 | 1.9974042791
DeepCopy | 3 | Left | Left | 7.47855 | 14.945849 | 1.998495564 | 8.011463 | 16.141996 | 2.014862454 | 80.712605 | 161.390244 | 1.9995667839 | 242.059149 | 483.961065 | 1.9993504356
DeepCopy | 4 | Left | Left | 7.454382 | 14.970474 | 2.0082783522 | 8.086152 | 16.134132 | 1.9952793368 | 80.8089 | 161.635331 | 2.0002169439 | 242.059149 | 483.646907 | 1.9980525793
DeepCopy | 5 | Left | Left | 7.480803 | 14.990655 | 2.0038831393 | 8.076685 | 16.028786 | 1.9845748596 | 80.756347 | 161.460193 | 1.9993498839 | 242.059149 | 483.48998 | 1.9974042791
DeepCopy | 6 | Left | Left | 7.488397 | 14.91772 | 1.9921112623 | 8.077561 | 16.140773 | 1.9982235974 | 80.870298 | 161.58275 | 1.9980481585 | 242.059149 | 484.275632 | 2.0006499816
DeepCopy | 7 | Left | Left | 7.460727 | 12.055858 | 1.6159092807 | 8.083871 | 16.130289 | 1.9953669473 | 80.756347 | 161.547715 | 2.0004336625 | 242.059149 | 484.118297 | 1.9999999959
DeepCopy | 8 | Left | Left | 7.500081 | 14.912793 | 1.9883509258 | 8.084134 | 15.936219 | 1.9712957504 | 80.861522 | 161.81085 | 2.0010858811 | 241.980533 | 483.803935 | 1.9993506461
DeepCopy | Raw | Right | Right | 33.527948 | 68.010777 | 2.0284801504 | 30.07905 | 60.401951 | 2.0081070047 | -1 | -1 | 1 | -1 | -1 | 1
DeepCopy | 1 | Right | Right | 7.478175 | 14.942552 | 1.9981548974 | 8.077211 | 16.014316 | 1.9826541612 | 80.791375 | 161.775716 | 2.002388448 | 242.137816 | 483.961065 | 1.9987008762
DeepCopy | 2 | Right | Right | 5.626519 | 14.935363 | 2.6544588226 | 8.084134 | 15.983226 | 1.9771104734 | 80.695122 | 161.49519 | 2.0013005247 | 241.901967 | 468.148325 | 1.9352811836
DeepCopy | 3 | Right | Right | 7.482907 | 14.936711 | 1.9961107361 | 8.000108 | 16.047429 | 2.0059015453 | 80.782615 | 161.652866 | 2.0010848374 | 241.901967 | 446.543638 | 1.8459694377
DeepCopy | 4 | Right | Right | 7.491861 | 14.910256 | 1.9901938917 | 8.083959 | 15.925148 | 1.9699689224 | 80.782615 | 161.407725 | 1.9980502612 | 242.059149 | 483.961065 | 1.9993504356
DeepCopy | 5 | Right | Right | 7.466335 | 14.961005 | 2.0037950346 | 8.051809 | 16.014661 | 1.9889519237 | 80.870298 | 161.670405 | 1.9991320546 | 241.980533 | 483.803935 | 1.9993506461
DeepCopy | 6 | Right | Right | 7.476974 | 11.216362 | 1.5001205033 | 8.082731 | 15.970036 | 1.975821786 | 80.765101 | 161.56523 | 2.0004337022 | 241.980533 | 468.148325 | 1.9346528384
DeepCopy | 7 | Right | Right | 7.465661 | 14.962658 | 2.004197351 | 8.078086 | 16.069061 | 1.9892163812 | 80.826433 | 161.793281 | 2.0017372411 | 241.901967 | 446.276166 | 1.8448637336
DeepCopy | 8 | Right | Right | 7.474799 | 14.910704 | 1.9947966494 | 8.080715 | 16.141472 | 1.9975301691 | 80.695122 | 161.49519 | 2.0013005247 | 223.204931 | 483.961065 | 2.1682364401
DeepCopy | Raw | Left | Right | 33.355332 | 67.228338 | 2.0155199774 | 30.022084 | 60.64285 | 2.0199413871 | -1 | -1 | 1 | -1 | -1 | 1
DeepCopy | 1 | Left | Right | 7.479526 | 92.284395 | 12.3382678261 | 8.081767 | 87.064921 | 10.7730055816 | 80.712605 | 169.139174 | 2.0955732255 | 241.901967 | 495.549092 | 2.0485533795
DeepCopy | 2 | Left | Right | 6.091804 | 49.067013 | 8.0545948294 | 8.569106 | 30.982766 | 3.6156357501 | 21.889651 | 52.931093 | 2.4180875702 | 70.209014 | 187.43599 | 2.6696855478
DeepCopy | 3 | Left | Right | 1.789061 | 27.315017 | 15.2677952289 | 8.126547 | 32.346013 | 3.9802899066 | 4.160244 | 43.485456 | 10.4526215289 | 9.1361 | 100.894855 | 11.0435366294
DeepCopy | 4 | Left | Right | 1.581747 | 27.586058 | 17.4402467651 | 6.245824 | 49.640753 | 7.9478309027 | 0.4802 | 31.025341 | 64.6092065806 | 1.313091 | 110.150511 | 83.8864259979
DeepCopy | 5 | Left | Right | 1.602899 | 27.702475 | 17.2827327236 | 8.120081 | 50.623955 | 6.2344150262 | 0.512009 | 43.811482 | 85.5677966598 | 1.358588 | 109.398438 | 80.5236304163
DeepCopy | 6 | Left | Right | 1.595249 | 27.760276 | 17.4018451038 | 10.240785 | 45.551191 | 4.4480175104 | 0.534235 | 38.038396 | 71.2016172658 | 1.432115 | 99.413978 | 69.4175942574
DeepCopy | 7 | Left | Right | 5.245927 | 24.980154 | 4.7618188358 | 8.682547 | 29.694827 | 3.4200594595 | 0.543337 | 36.982928 | 68.0662793073 | 1.458376 | 121.167354 | 83.0837548067
DeepCopy | 8 | Left | Right | 2.514149 | 24.974292 | 9.9334971794 | 4.217135 | 28.484624 | 6.7544965954 | 0.152444 | 27.35915 | 179.4701660938 | 0.459705 | 119.505664 | 259.9616362667
DeepCopy | Raw | Right | Left | 33.829371 | 67.917781 | 2.0076572219 | 31.538184 | 60.233482 | 1.909858919 | -1 | -1 | 1 | -1 | -1 | 1
DeepCopy | 1 | Right | Left | 7.390056 | 93.295525 | 12.6244679337 | 8.084924 | 81.703921 | 10.1057129294 | 80.782615 | 169.081598 | 2.0930443759 | 214.899931 | 496.043981 | 2.308255655
DeepCopy | 2 | Right | Left | 9.170961 | 51.634364 | 5.630202113 | 2.59093 | 33.590679 | 12.9647188461 | 10.666849 | 61.92819 | 5.8056685719 | 51.083857 | 309.859871 | 6.0657101714
DeepCopy | 3 | Right | Left | 4.439415 | 27.601899 | 6.2174631117 | 2.661245 | 43.391751 | 16.3050568437 | 3.888429 | 79.804848 | 20.5236736996 | 8.094762 | 206.673526 | 25.531760662
DeepCopy | 4 | Right | Left | 4.10541 | 26.875088 | 6.5462616401 | 2.212529 | 38.035483 | 17.1909534293 | 0.447263 | 65.307276 | 146.0153779767 | 1.000647 | 181.301389 | 181.1841628466
DeepCopy | 5 | Right | Left | 5.212821 | 26.557997 | 5.0947456281 | 3.501229 | 31.03762 | 8.8647786249 | 0.475822 | 56.514435 | 118.7722194434 | 1.048664 | 154.192479 | 147.0370671636
DeepCopy | 6 | Right | Left | 4.436427 | 25.630674 | 5.7773235083 | 3.519821 | 26.192015 | 7.4412917589 | 0.497342 | 40.66134 | 81.7573018165 | 1.106802 | 132.927397 | 120.1004307907
DeepCopy | 7 | Right | Left | 4.720427 | 27.001705 | 5.7201827292 | 3.477728 | 44.681143 | 12.847796895 | 0.504697 | 51.027879 | 101.1059685316 | 1.157201 | 140.431262 | 121.3542521999
DeepCopy | 8 | Right | Left | 4.739947 | 23.072528 | 4.8676763685 | 2.401709 | 21.762733 | 9.0613529782 | 0.106308 | 27.192892 | 255.7934680363 | 0.192975 | 120.316199 | 623.4807565747
Resize | Raw |   | Left | 24.945862 | 52.07647 | 2.0875794951 | 61.463295 | 127.023793 | 2.0666609722 | 67.261719 | 134.402103 | 1.9981960764 | 65.963529 | 131.903702 | 1.9996459256
Resize | 1 |   | Left | 19.668903 | 50.627395 | 2.5739816298 | 14.348459 | 105.756999 | 7.370617221 | 45.502508 | 94.096749 | 2.0679464306 | 59.466682 | 124.404418 | 2.0920020054
Resize | 2 |   | Left | 5.459981 | 42.684506 | 7.817702296 | 2.420969 | 90.94947 | 37.5673831429 | 33.019769 | 55.956294 | 1.6946300866 | 38.532171 | 102.965459 | 2.6721945929
Resize | 3 |   | Left | 1.657416 | 41.854843 | 25.2530704422 | 2.170947 | 74.955539 | 34.5266554181 | 5.03132 | 69.440147 | 13.8015763259 | 7.330002 | 112.546535 | 15.3542297806
Resize | 4 |   | Left | 1.472945 | 41.312931 | 28.0478436058 | 1.818563 | 71.72986 | 39.4431537428 | 0.569305 | 51.76171 | 90.9208772099 | 0.936638 | 86.634658 | 92.4953482562
Resize | 5 |   | Left | 1.465897 | 41.016133 | 27.9802284881 | 2.970892 | 64.787657 | 21.8074763404 | 0.577518 | 37.915476 | 65.6524575857 | 0.949709 | 71.830133 | 75.6338341534
Resize | 6 |   | Left | 1.486504 | 41.237474 | 27.7412465759 | 3.074915 | 65.826572 | 21.4076070395 | 0.595929 | 27.414014 | 46.0021479069 | 0.972833 | 55.26317 | 56.8064302917
Resize | 7 |   | Left | 1.47503 | 38.219866 | 25.9112465509 | 3.02858 | 74.722501 | 24.6724540874 | 0.588122 | 77.489138 | 131.7569109811 | 1.052864 | 103.58099 | 98.3802181478
Resize | 8 |   | Left | 2.128026 | 36.273518 | 17.0456178637 | 1.193674 | 63.049679 | 52.8198477976 | 0.135631 | 56.913762 | 419.6220775486 | 0.195537 | 94.478577 | 483.1749336443
Resize | Raw |   | Right | 26.061916 | 51.835535 | 1.9889379967 | 61.175635 | 123.763797 | 2.023089699 | 66.45777 | 132.797088 | 1.998217635 | 57.404889 | 131.542737 | 2.2914901377
Resize | 1 |   | Right | 17.083002 | 50.121632 | 2.9340060956 | 14.041538 | 105.726984 | 7.5295871435 | 45.204348 | 93.576747 | 2.0700828823 | 62.890019 | 116.899358 | 1.8587903114
Resize | 2 |   | Right | 19.18127 | 41.229487 | 2.1494659634 | 12.524089 | 85.560181 | 6.8316490724 | 4.761119 | 54.643055 | 11.4769353591 | 24.094756 | 103.107952 | 4.2792693979
Resize | 3 |   | Right | 18.277354 | 41.214662 | 2.2549578019 | 13.022531 | 77.83724 | 5.9771207302 | 2.317977 | 61.631075 | 26.5883030763 | 8.108858 | 88.813692 | 10.9526757035
Resize | 4 |   | Right | 17.821797 | 40.703546 | 2.2839192928 | 11.396333 | 72.898396 | 6.3966537306 | 0.39428 | 51.143469 | 129.713576646 | 1.434219 | 85.159225 | 59.376723499
Resize | 5 |   | Right | 18.659105 | 40.734702 | 2.1831005292 | 10.286453 | 72.738266 | 7.0712680066 | 0.426803 | 36.931598 | 86.5307835231 | 1.51397 | 74.502081 | 49.2097472209
Resize | 6 |   | Right | 18.820776 | 41.068132 | 2.1820636939 | 9.726099 | 71.106896 | 7.3109368926 | 0.448811 | 26.825738 | 59.7706785262 | 1.607048 | 53.151993 | 33.0743033189
Resize | 7 |   | Right | 19.043018 | 36.709601 | 1.9277197028 | 9.211895 | 70.364835 | 7.6384755797 | 0.464913 | 49.761767 | 107.0345785125 | 1.638185 | 84.43541 | 51.5420480593
Resize | 8 |   | Right | 13.340341 | 38.431798 | 2.8808707364 | 11.247008 | 55.669896 | 4.9497516139 | 0.115028 | 41.582702 | 361.5006954828 | 0.439993 | 64.212536 | 145.9399035894
