### ISSUE TITLE
Deprecated for Version 3

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1277]
This issue is going to collect all the different things we are going to deprecate for version three.
Please use the checkbox syntax:
```
 - [ ] The foo feature will be replaced with the bar feature
```
The checkbox is only checked when the old feature has deprecation macros around it and the new feature exists and is being used.

 - [x] `View.dimension_0()` and `View.dimension(0)` replaced with `View.extent(0)`
 - [ ] `KOKKOS_HAVE_` replaced by `KOKKOS_ENABLE_`

**Comment by ibaned** [comment]
This is in preparation for #1084

**Comment by ndellingwood** [comment]
- [ ] Deprecate and remove `md_parallel_for`, `md_parallel_reduce`

**Comment by ndellingwood** [comment]
- [ ] Deprecate dimension_* functions in 'View-like' classes (DynRankView, DynamicView, DualView,...)
- [ ] Replace `dimension_i` calls with `extent(i)` in 'View-like' classes (DynRankView, DynamicView, DualView,...)
- [ ] Remove dimension_* functions in 'View-like' classes (DynRankView, DynamicView, DualView,...)

**Comment by ndellingwood** [comment]
- [ ] Add `access(...)` methods to necessary 'View-like' classes which will retain the deprecated behavior of `operator()(...)`; this will also need to be done for Sacado

**Comment by ndellingwood** [comment]
- [ ] Deprecate the following functions in 'View-like' classes: `capacity()`, `is_contiguous()`, `ptr_on_device()`
- [ ] Remove the following functions in 'View-like' classes: `capacity()`, `is_contiguous()`, `ptr_on_device()`

**Comment by mhoemmen** [comment]
FYI @rrdrake @prwolfe @micahahoward

**Comment by ibaned** [comment]
nope, `concurrency` is not being deprecated and should not have been for OpenMP

**Comment by crtrott** [comment]
- [ ] remove sleep from execution spaces
- [ ] remove wake from execution spaces
- [ ] remove thread_pool_size
- [ ] remove thread_pool_rank
- [ ] remove max_hardware_threads
- [ ] remove hardware_thread_id

**Comment by ndellingwood** [comment]
Adding reference to #1531 and PR #1556 
Team policies that will be modified should not be declared `const` - set methods now modify the policies internally rather than returning a newly constructed policy.
