### ISSUE TITLE
View constructor should check arguments

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1286]
The following code compiles and runs with no errors or warnings at all.
```cpp
Kokkos::View<int> my_view("foo", 100);
std::cout << my_view.extent(0) << '\n'; // prints 1
```
Our constructors should check for extra arguments that go beyond the rank of the view.

@csiefer2

**Comment by stanmoore1** [comment]
Yeah, I got bit by this before when I forgot a `*` in the type.

**Comment by ibaned** [comment]
Unfortunately, this is made difficult by the whole "dimensions greater than rank have extent 1 business", see #1263 and #1036.

**Comment by ibaned** [comment]
Remaining piece: constructor should check argument count

**Comment by stanmoore1** [comment]
Just one more data point: I switched some one-dimensional views to two dimensions, but forgot to add an additional argument to constructor. The code compiled without errors and I had to debug at runtime--not a good user experience.

**Comment by ibaned** [comment]
@stanmoore1 this will definitely be fixed in the February Kokkos release.

**Comment by stanmoore1** [comment]
@ibaned awesome, thanks!
