### ISSUE TITLE
For compilation with __INTEL_COMPILER, please #include <immintrin.h> when using an Intel intrinsic

### ISSUE THREAD

**Issue by mibintc** [kokkos/kokkos#1295]
When building kokkos downloaded on 20170724 with an experimental version of the Intel compiler, we are unable to compile because there is a direct reference to the Intel intrinsic __bit_scan_reverse without definition--leading to compilation error This is a request to modify kokkos to #include the intrinsic definition file .  We recommend this modification as good programming practice, and additionally a new version of the Intel compiler may require you to have the include. The intrinsic will be supported through an inline assembly function definition which is part of immintrin.h.

Details:
kokkos-20170724/example/tutorial/../../core/src/impl/Kokkos_ConcurrentBitset.hpp:49:
../kokkos-20170724/example/tutorial/../../core/src/impl/Kokkos_BitOps.hpp:66:22: error: use of undeclared identifier '_bit_scan_forward'
  return full != i ? _bit_scan_forward( ~i ) : -1 ;

Many thanks! --Melanie Blower (I work on the Intel Compiler team)

**Comment by crtrott** [comment]
Thanks for letting us know. I will add that. Should an #include<immintrin.h> work for any Intel compiler 15.x and newer?

**Comment by mibintc** [comment]
Yes it will work for any Intel compiler 15.x and newer.  Thanks a lot.
