### ISSUE TITLE
Interoperability: Do not shut down backend execution space runtimes upon calling finalize.

### ISSUE THREAD

**Issue by u1015163** [kokkos/kokkos#1305]
We are attempting to utilize Kokkos as an external dependency in our project (https://software.crsim.utah.edu:8443/James_Research_Group/SpatialOps.git). In our aim to not have the end user not explicitly call out "Kokkos::Initialize()" in his/her source file, we create a static object which initializes Kokkos, but in having done this, "Kokkos::Finalize()" seems to clear out all of the GPU device memory.

**Comment by crtrott** [comment]
So you are using CUDA or OpenCL in addition to Kokkos? I can see that use case and how this finalize behavior would be problematic. Do you also need to be able to call initialize and finalize multiple times?

**Comment by crtrott** [comment]
Just as a background we had some issues with crashing kernels etc, where an explicit call to GPU reset was helping stability for multi user systems. But I am not opposed to changing that behavior. It is not part of the official "This is how Kokkos must behave" set of stuff.

**Comment by u1015163** [comment]
Yes, we are using CUDA in addition to Kokkos. Currently, our execution would only require one call to initialize and finalize per executable.

**Comment by crtrott** [comment]
Ok I think that I can do for you. I mark this as a feature request and will change the title slightly to better reflect the desired behavior.

**Comment by u1015163** [comment]
Okay, thank you!

**Comment by crtrott** [comment]
This also affects OpenMP and possibly ROCm, where we reset for example the number of openmp threads to 1. In order to allow libraries to use Kokkos which are only active during part of an application we need to change this behavior in case other libraries in the same app are using for example CUDA or OpenMP.

**Comment by crtrott** [comment]
Looks like the CUDA issue is a proper bug, we actually did remove the reset a while ago ...

**Comment by crtrott** [comment]
Ok I think I got this under control.
