### ISSUE TITLE
[Question] Minimum compiler version requirements.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1311]
I have small wondering what problem we have for lower versions of compilers. Do you put the required minimum version because it is not working with Kokkos ? or it is not tested anymore nightly ? 

If the reason is that the lower versions of compilers are not tested anymore, could we just give cmake warning instead of error ? 

```
-- Check for working CXX compiler: /opt/intel/composer_xe_2015.2.164/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMAKE_CXX_COMPILER_ID='Intel'
-- CMAKE_CXX_COMPILER_VERSION='15.0.0.20150121'
CMake Error at packages/kokkos/cmake/kokkos_functions.cmake:72 (message):
  Compiler not supported by Kokkos.  Required compiler versions:

      Clang      3.5.2 or higher
      GCC        4.8.4 or higher
      Intel     15.0.2 or higher
      NVCC      7.0.28 or higher
      PGI         17.1 or higher
```

**Comment by crtrott** [comment]
We don't test and a lot of the lower versions will not work anymore, or at least not reliably. I rather error out and don't deal with all the ignored warnings ...
