### ISSUE TITLE
In Kokkos::initialize(int, char**), change char** to const char** 

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#1317]
I'm thinkin this change:
    `void initialize(int& narg, char* arg[])` to `void initialize(int& narg, const char* arg[])`
would advertise the function's behavior without causing backwards compatibility trouble.

**Comment by ibaned** [comment]
Unfortunately the C++ rules for `const` don't work quite the way we would like them to. In particular, `char**` can't be passed to `const char**`. This reproducer will compile only if the `const` is removed:
```cpp
#include <cstdio>

void foo(const char* arg[]) {
  printf("%s\n", arg[5]);
}

int main() {
  char* a[14] = {nullptr};
  foo(a);
}
```
```
foo.cpp:9:3: error: no matching function for call to 'foo'
  foo(a);
  ^~~
foo.cpp:3:6: note: candidate function not viable: no known conversion from 'char *[14]' to 'const char **' for 1st argument
void foo(const char* arg[]) {
     ^
1 error generated.
```
This has bitten me in the past when trying to do exactly what @ambrad suggests, i.e. enforce const correctness in an API. I think this change would cause trouble for users that declared their `main` as
```cpp
int main(int argc, char* argv[])
```
without a `const`, which I think is the majority.

I do wish the language had been defined differently though, I would like to be able to do this.

**Comment by hcedwar** [comment]
Problem is not the `const` it is the `[14]`

**Comment by ibaned** [comment]
```cpp
#include <cstdio>

void foo(int argc, const char* arg[]) {
  printf("%s\n", arg[argc - 1]);
}

int main(int argc, char** argv) {
  foo(argc, argv);
}
```
```
foo.cpp:8:3: error: no matching function for call to 'foo'
  foo(argc, argv);
  ^~~
foo.cpp:3:6: note: candidate function not viable: no known conversion from 'char **' to 'const char **' for 2nd argument
void foo(int argc, const char* arg[]) {
     ^
1 error generated.
```

**Comment by hcedwar** [comment]
That is a compiler bug.

**Comment by hcedwar** [comment]
C++11 Section 4.4 Qualified Conversions requires addition of `const` at each pointer level:
```
void foo( char const * const * arg ) { }

int main( int argc , char ** argv )
{
  foo( argv );
  return 0 ;
}
```
is a valid implicit conversion.

**Comment by hcedwar** [comment]
So have to either add `const` at every level or don't add at any level.  Language spec provides a motivating example for how, without this requirement, const-ness could be silently violated.

**Comment by crtrott** [comment]
This is actually not at every level. Every level would be
```c++
void foo( char const *const * const arg ) { }

int main( int argc , char ** argv )
{
  foo( argv );
  return 0 ;
}
```

Also we can't have the middle const thing, because we modify the pointer list. 
```c++
void foo( char const ** const arg ) { }

int main( int argc , char ** argv )
{
  foo( argv );
  return 0 ;
}
```

**Comment by ibaned** [comment]
And unfortunately that doesn't compile:
```
foo.cpp:8:3: error: no matching function for call to 'foo'
  foo(argc, argv);
  ^~~
foo.cpp:3:6: note: candidate function not viable: no known conversion from 'char **' to 'const char **const' for 2nd argument
void foo(int argc, char const ** const arg ) {
     ^
1 error generated.
```

**Comment by hcedwar** [comment]
@crtrott : Every is-a-pointer-to level, the last level is the object itself.

**Comment by crtrott** [comment]
Ok I see, but one of the levels needs to be non-const since we modify it ..

**Comment by ambrad** [comment]
I didn't mean to cause trouble. ;) I agree with @crtrott. `char const* const*` won't work since the args array needs to get stripped. What about providing a one-line call-through `init(int, char const**)` that simply `const_cast`s and then calls the non-const one? That insulates the app from having to do exactly that. The difference is the app is _assuming_ that that behavior is intended, whereas Kokkos can _promise_ that it definitely is.

**Comment by ibaned** [comment]
@crtrott : Having `const_cast` in code is immoral, and we'd prefer that users do this prior to calling `Kokkos::initialize` rather than having it hidden under an overload in Kokkos. In other words, we'd prefer that this one-line wrapper be in user code, not in Kokkos.
