### ISSUE TITLE
Travis job errors

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1320]
@nschloe we're seeing various errors related to the package manager in Travis:

https://travis-ci.org/kokkos/kokkos/jobs/325174841

**Comment by nschloe** [comment]
Is this related to my work? Anyways, looking at the failure
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libobjc4_4.8.4-2ubuntu1~14.04.3_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]
```
is seems like a network error on travis's side, probably temporary.

**Comment by ibaned** [comment]
Yea, I don't think anything could affect this except our `.travis.yml` file. Maybe we'll just wait it out, this issue mainly logs the fact that a non-trivial percentage of our jobs are failing with similar ubuntu package management issues.

**Comment by ibaned** [comment]
Whoops, I'm sorry, I meant to mention @jeffhammond . He's the one who committed that file.

**Comment by nschloe** [comment]
I just learned that launchpad shut down many of their services for users outside of Canonical itself in the wake of the Spectre/Meltdown crisis. Will probably a few days before it comes back up.

**Comment by jeffhammond** [comment]
@ibaned Travis CI jobs have been failing frequently due to networking or third-party server issues all week, and I think even before the security hysteria started.  Travis CI reports that their support team is on vacation until next week, so I will not be surprised if these issues persist for a few more days.

**Comment by ibaned** [comment]
@jeffhammond Thanks! we'll wait for their team to come back and put out some fires
