### ISSUE TITLE
Build error in test on some compilers

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1324]
Dup of https://github.com/trilinos/Trilinos/issues/2133 .  My bad.  I'll fix it.

Summary: some compilers implement `operator<<(std::ostream&, const std::ostringstream&)`, and some don't.  Test on multiple compilers before pushing ;-) .

**Comment by crtrott** [comment]
I did test on quite a few compilers (clang3.9/4.0, nvcc 8, gcc 4.8/5.3, intel 16) which compiler failed?

**Comment by mhoemmen** [comment]
@crtrott I'm not sure how to tell, but it's on ride: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=65097

Anyway, it's generally unwise to assume that `operator<<(std::ostream&, const std::ostringstream&)` works :-) .
