### ISSUE TITLE
Check Compile times and runtimes for nightly testing

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1334]
It feels as if those increased significantly. We need to get another break down by compiler and object file, as well as test run times to see if we can improve the situation again. If specific object files stand out, we need to split those.

**Comment by swbova** [comment]
I checked timings for cee blade, shepard, and white.  See attached. Nothing jumps out for blades, but for shepard and white, it appears that something happened between 2.04.00 and 2.03.00.  The bar charts show "pseudo efficiency" (PE), which is (user time + sys time)/(realTime*N).  if the numerator were single processor build times, then this would be the parallel efficiency.  The PE dropped significantly between 2.03.00 and 2.04.00.  For shepard, the gcc build times for serial, openmp, and pthreads used to be about 20% faster.   Also for white CUDA, the build times were about 30% faster.  

The next step is to look at per file build times for gcc on shepard between 2.03.00 and master and see where the anomalies are. 

[kokkosTimingsCeeBlade.pdf](https://github.com/kokkos/kokkos/files/1640484/kokkosTimingsCeeBlade.pdf)
[kokkosTimingsShephard.pdf](https://github.com/kokkos/kokkos/files/1640485/kokkosTimingsShephard.pdf)
[kokkosTimingsWhite.pdf](https://github.com/kokkos/kokkos/files/1640486/kokkosTimingsWhite.pdf)

**Comment by swbova** [comment]
The results are weird.  If you look at the attached pdfs in my comment above from last week, you will see that comparing master builds to 2.03.00 builds, the real (walk clock) time is significantly less for the old version.  However, the sum of the  user and system time (which represents cpu time) is significantly more for the old version.  Also look at the attached plot for gcc pthread build on shepard.  

![changeinbuildtimes](https://user-images.githubusercontent.com/34869966/35355769-940b7dc4-010b-11e8-8af8-b59cb5b2facf.png)

This shows that, generally speaking, the build times per file either stayed the same or decreased in master compared to 2.03.00.    Here are some more stats for this build. 

number of files is different:  master_compute.log = 161 but 2.03.00_compute.log = 143
**average time in master**_compute.log = 2.234771784232366
**average time in  2.03.00**_compute.log = 3.341491228070181
**total time in master_compute.log = 538.5800000000002
total time in 2.03.00_compute.log = 761.8600000000013**
max time in master_compute.log = 18.09
max time in 2.03.00_compute.log = 29.97

**for the files that are new in master, here are the build times:**

core/src/impl/Kokkos_HostBarrier.cpp not found in 2.03.00_compute.log  time = 0.38
core/src/impl/Kokkos_MemoryPool.cpp not found in 2.03.00_compute.log  time = 0.39
core/src/impl/Kokkos_Spinwait.cpp not found in 2.03.00_compute.log  time = 0.29
core/unit_test/UnitTestMainInit.cpp not found in 2.03.00_compute.log  time = 1.21
core/unit_test/threads/TestThreads_SharedAlloc.cpp not found in 2.03.00_compute.log  time = 2.28
core/unit_test/threads/TestThreads_ViewMapping_b.cpp not found in 2.03.00_compute.log  time = 2.4
core/unit_test/threads/TestThreads_Init.cpp not found in 2.03.00_compute.log  time = 3.55
core/unit_test/threads/TestThreads_RangePolicy.cpp not found in 2.03.00_compute.log  time = 3.85
core/unit_test/threads/TestThreads_ViewMapping_subview.cpp not found in 2.03.00_compute.log  time = 2.81
core/unit_test/threads/TestThreads_ViewOfClass.cpp not found in 2.03.00_compute.log  time = 1.92
core/unit_test/threads/TestThreads_ViewMapping_a.cpp not found in 2.03.00_compute.log  time = 10.65
core/unit_test/threads/TestThreads_Scan.cpp not found in 2.03.00_compute.log  time = 2.24
core/unit_test/threads/TestThreads_Complex.cpp not found in 2.03.00_compute.log  time = 2.89
core/unit_test/threads/TestThreads_TeamReductionScan.cpp not found in 2.03.00_compute.log  time = 2.78
core/unit_test/threads/TestThreads_TeamScratch.cpp not found in 2.03.00_compute.log  time = 3.83
core/unit_test/threads/TestThreads_AtomicViews.cpp not found in 2.03.00_compute.log  time = 5.72
core/unit_test/threads/TestThreads_AtomicOperations.cpp not found in 2.03.00_compute.log  time = 7.6
core/unit_test/default/TestDefaultDeviceType.cpp not found in 2.03.00_compute.log  time = 1.1
core/unit_test/default/TestDefaultDeviceType_d.cpp not found in 2.03.00_compute.log  time = 1.18
core/unit_test/default/TestDefaultDeviceTypeInit_1.cpp not found in 2.03.00_compute.log  time = 1.29
core/unit_test/default/TestDefaultDeviceTypeInit_2.cpp not found in 2.03.00_compute.log  time = 1.26
core/unit_test/default/TestDefaultDeviceTypeInit_3.cpp not found in 2.03.00_compute.log  time = 1.27
core/unit_test/default/TestDefaultDeviceTypeInit_4.cpp not found in 2.03.00_compute.log  time = 1.26
core/unit_test/default/TestDefaultDeviceTypeInit_5.cpp not found in 2.03.00_compute.log  time = 1.27
core/unit_test/default/TestDefaultDeviceTypeInit_6.cpp not found in 2.03.00_compute.log  time = 1.27
core/unit_test/default/TestDefaultDeviceTypeInit_7.cpp not found in 2.03.00_compute.log  time = 1.27
core/unit_test/default/TestDefaultDeviceTypeInit_8.cpp not found in 2.03.00_compute.log  time = 1.26
core/unit_test/default/TestDefaultDeviceTypeInit_9.cpp not found in 2.03.00_compute.log  time = 1.25
core/unit_test/default/TestDefaultDeviceTypeInit_10.cpp not found in 2.03.00_compute.log  time = 1.29
core/unit_test/default/TestDefaultDeviceTypeInit_11.cpp not found in 2.03.00_compute.log  time = 1.25
core/unit_test/default/TestDefaultDeviceTypeInit_12.cpp not found in 2.03.00_compute.log  time = 1.26
core/unit_test/default/TestDefaultDeviceTypeInit_13.cpp not found in 2.03.00_compute.log  time = 1.25
core/unit_test/default/TestDefaultDeviceTypeInit_14.cpp not found in 2.03.00_compute.log  time = 1.28
core/unit_test/default/TestDefaultDeviceTypeInit_15.cpp not found in 2.03.00_compute.log  time = 1.29
core/unit_test/default/TestDefaultDeviceTypeInit_16.cpp not found in 2.03.00_compute.log  time = 1.27
core/unit_test/threads/TestThreads_MDRange.cpp not found in 2.03.00_compute.log  time = 14.41
core/unit_test/default/TestDefaultDeviceType_a.cpp not found in 2.03.00_compute.log  time = 13.36
core/unit_test/default/TestDefaultDeviceType_b.cpp not found in 2.03.00_compute.log  time = 13.52
core/unit_test/default/TestDefaultDeviceType_c.cpp not found in 2.03.00_compute.log  time = 13.96
core/perf_test/PerfTestHexGrad.cpp not found in 2.03.00_compute.log  time = 1.85
core/perf_test/PerfTest_CustomReduction.cpp not found in 2.03.00_compute.log  time = 2.36
core/perf_test/PerfTestGramSchmidt.cpp not found in 2.03.00_compute.log  time = 2.51
core/perf_test/test_taskdag.cpp not found in 2.03.00_compute.log  time = 0.69
KokkosCore_PerformanceTest_TaskDAG not found in 2.03.00_compute.log  time = 0.07
core/perf_test/test_mempool.cpp not found in 2.03.00_compute.log  time = 1.41
KokkosCore_PerformanceTest_Mempool not found in 2.03.00_compute.log  time = 0.07

**Files with time differences that exceed the threshold of 2.5:**
core/unit_test/threads/TestThreads_SubView_c01.cpp : -4.1
core/unit_test/threads/TestThreads_SubView_c02.cpp : -3.8400000000000003
core/unit_test/threads/TestThreads_SubView_c03.cpp : -3.7900000000000005
core/unit_test/threads/TestThreads_SubView_b.cpp : -5.53
core/unit_test/threads/TestThreads_ViewAPI_b.cpp : -10.78
core/unit_test/threads/TestThreads_SubView_a.cpp : -6.8500000000000005
core/unit_test/threads/TestThreads_SubView_c05.cpp : -8.7
core/unit_test/threads/TestThreads_SubView_c04.cpp : -6.739999999999998
core/unit_test/threads/TestThreads_SubView_c06.cpp : -8.7
core/unit_test/threads/TestThreads_SubView_c07.cpp : -6.740000000000002
core/unit_test/threads/TestThreads_SubView_c08.cpp : -6.9
core/unit_test/threads/TestThreads_SubView_c09.cpp : -12.419999999999998
core/unit_test/threads/TestThreads_SubView_c10.cpp : -10.219999999999999
core/unit_test/threads/TestThreads_SubView_c11.cpp : -4.640000000000001
core/unit_test/threads/TestThreads_Atomics.cpp : -15.43
core/unit_test/threads/TestThreads_Team.cpp : -8.45
core/unit_test/threads/TestThreads_Reductions.cpp : -8.32
core/unit_test/threads/TestThreads_Other.cpp : -19.200000000000003
core/unit_test/threads/TestThreads_SubView_c12.cpp : -11.760000000000002

**Comment by crtrott** [comment]
XL Compile Times for Object Files:

|File|Front End|IPA|
|----|----|----|
| UnitTestMainInit.cpp	 | 1.000 | 	0.020 |
| gtest-all.cc	 | 2.360 | 	26.310 |
| TestOpenMP_Init.cpp	 | 2.280 | 	24.170 |
| TestOpenMP_SharedAlloc.cpp	 | 1.120 | 	1.410 |
| TestOpenMP_RangePolicy.cpp	 | 1.840 | 	23.540 |
| TestOpenMP_ViewAPI_b.cpp	 | 7.090 | 	1069.490 |
| TestOpenMP_ViewMapping_a.cpp	 | 4.250 | 	209.710 |
| TestOpenMP_ViewMapping_b.cpp	 | 2.110 | 	11.460 |
| TestOpenMP_ViewMapping_subview.cpp	 | 2.260 | 	2.990 |
| TestOpenMP_ViewOfClass.cpp	 | 1.370 | 	4.150 |
| TestOpenMP_SubView_a.cpp	 | 6.210 | 	109.020 |
| TestOpenMP_SubView_b.cpp	 | 2.800 | 	42.830 |
| TestOpenMP_SubView_c01.cpp	 | 1.660 | 	1.500 |
| TestOpenMP_SubView_c02.cpp	 | 1.700 | 	1.250 |
| TestOpenMP_SubView_c03.cpp	 | 1.670 | 	1.170 |
| TestOpenMP_SubView_c04.cpp	 | 7.500 | 	58.840 |
| TestOpenMP_SubView_c05.cpp	 | 7.500 | 	60.640 |
| TestOpenMP_SubView_c06.cpp	 | 7.450 | 	51.370 |
| TestOpenMP_SubView_c07.cpp	 | 4.940 | 	50.130 |
| TestOpenMP_SubView_c08.cpp	 | 4.940 | 	54.210 |
| TestOpenMP_SubView_c09.cpp	 | 4.960 | 	55.150 |
| TestOpenMP_SubView_c10.cpp	 | 4.930 | 	53.850 |
| TestOpenMP_SubView_c11.cpp	 | 5.050 | 	53.560 |
| TestOpenMP_SubView_c12.cpp	 | 5.480 | 	51.050 |
| TestOpenMP_SubView_c13.cpp	 | 1.420 | 	0.560 |
| TestOpenMP_Reductions.cpp	 | 4.760 | 	1069.490 |
| TestOpenMP_Scan.cpp	 | 1.110 | 	0.550 |
| TestOpenMP_Complex.cpp	 | 1.550 | 	6.290 |
| TestOpenMP_AtomicOperations.cpp	 | 3.010 | 	376.520 |
| TestOpenMP_AtomicViews.cpp	 | 3.410 | 	191.060 |
| TestOpenMP_Atomics.cpp	 | 2.120 | 	76.550 |
| TestOpenMP_Team.cpp	 | 2.670 | 	256.430 |
| TestOpenMP_TeamScratch.cpp	 | 1.890 | 	18.320 |
| TestOpenMP_TeamReductionScan.cpp	 | 1.330 | 	3.490 |
| TestOpenMP_Other.cpp	 | 3.630 | 	220.670 |
| TestOpenMP_MDRange.cpp	 | 5.630 | 	1487.210 |
| TestOpenMP_Crs.cpp	 | 1.390 | 	4.200 |
| TestOpenMP_Task.cpp	 | 1.460 | 	4.830 |
| TestOpenMP_WorkGraph.cpp	 | 1.850 | 	23.670 |
| TestOpenMP_UniqueToken.cpp	 | 1.290 | 	3.020 |
| Kokkos_ExecPolicy.cpp	 | 0.700 | 	0.010 |
| Kokkos_HostThreadTeam.cpp	 | 0.290 | 	0.060 |
| Kokkos_SharedAlloc.cpp	 | 0.720 | 	0.100 |
| Kokkos_Spinwait.cpp	 | 0.140 | 	0.000 |
| Kokkos_Profiling_Interface.cpp	 | 0.220 | 	0.080 |
| Kokkos_CPUDiscovery.cpp	 | 0.040 | 	0.010 |
| Kokkos_hwloc.cpp	 | 0.730 | 	0.110 |
| Kokkos_Error.cpp	 | 0.260 | 	0.020 |
| Kokkos_Core.cpp	 | 0.810 | 	0.570 |
| Kokkos_HostBarrier.cpp	 | 0.190 | 	0.060 |
| Kokkos_HostSpace.cpp	 | 0.450 | 	0.080 |
| Kokkos_MemoryPool.cpp	 | 0.210 | 	0.030 |
| Kokkos_UnorderedMap_impl.cpp	 | 0.710 | 	0.010 |
| Kokkos_OpenMP_Task.cpp	 | 0.710 | 	0.280 |
| Kokkos_OpenMP_Exec.cpp	 | 0.730 | 	0.140 |
| UnitTestMain.cpp	 | 0.580 | 	0.010 |
| TestOpenMP_InterOp.cpp	 | 1.010 | 	0.110 |
| TestHWLOC.cpp	 | 0.570 | 	0.030 |
| TestDefaultDeviceType.cpp	 | 1.010 | 	0.030 |
| TestDefaultDeviceType_a.cpp	 | 3.340 | 	426.180 |
| TestDefaultDeviceType_b.cpp	 | 3.320 | 	413.680 |
| TestDefaultDeviceType_c.cpp	 | 3.230 | 	407.670 |
| TestDefaultDeviceType_d.cpp	 | 1.020 | 	0.080 |
| TestDefaultDeviceTypeInit_1.cpp	 | 0.980 | 	0.130 |
| TestDefaultDeviceTypeInit_2.cpp	 | 1.080 | 	0.130 |
| TestDefaultDeviceTypeInit_3.cpp	 | 1.000 | 	0.150 |
| TestDefaultDeviceTypeInit_4.cpp	 | 1.020 | 	0.140 |
| TestDefaultDeviceTypeInit_5.cpp	 | 1.030 | 	0.140 |
| TestDefaultDeviceTypeInit_6.cpp	 | 1.000 | 	0.130 |
| TestDefaultDeviceTypeInit_7.cpp	 | 1.120 | 	0.150 |
| TestDefaultDeviceTypeInit_8.cpp	 | 1.030 | 	0.140 |
| TestDefaultDeviceTypeInit_9.cpp	 | 0.970 | 	0.140 |
| TestDefaultDeviceTypeInit_10.cpp	 | 1.030 | 	0.150 |
| TestDefaultDeviceTypeInit_11.cpp	 | 1.000 | 	0.120 |
| TestDefaultDeviceTypeInit_12.cpp	 | 1.010 | 	0.130 |
| TestDefaultDeviceTypeInit_13.cpp	 | 1.010 | 	0.140 |
| TestDefaultDeviceTypeInit_14.cpp	 | 0.990 | 	0.130 |
| TestDefaultDeviceTypeInit_15.cpp	 | 1.020 | 	0.130 |
| TestDefaultDeviceTypeInit_16.cpp	 | 1.030 | 	0.130 |

**Comment by crtrott** [comment]
Here is the real OOPS PerfTests:

| File | Front | IPA |
| --- | --- | --- |
PerfTestMain.cpp	 | 0.960 | 	0.030
gtest-all.cc	 | 2.120 | 	32.120
PerfTestGramSchmidt.cpp	 | 1.670 | 	11.430
PerfTestHexGrad.cpp	 | 1.250 | 	1.010
PerfTest_CustomReduction.cpp	 | 1.690 | 	16.860
PerfTest_ViewCopy.cpp	 | 11.900 | 	16990.680
Kokkos_ExecPolicy.cpp	 | 0.690 | 	0.000
Kokkos_HostThreadTeam.cpp	 | 0.310 | 	0.160
Kokkos_SharedAlloc.cpp	 | 0.710 | 	0.050
Kokkos_Spinwait.cpp	 | 0.160 | 	0.010
Kokkos_Profiling_Interface.cpp	 | 0.220 | 	0.080
Kokkos_CPUDiscovery.cpp	 | 0.040 | 	0.010
Kokkos_HostBarrier.cpp	 | 0.160 | 	0.030
Kokkos_hwloc.cpp	 | 0.710 | 	0.150
Kokkos_Error.cpp	 | 0.250 | 	0.040
Kokkos_Core.cpp	 | 0.830 | 	0.670
Kokkos_HostSpace.cpp	 | 0.440 | 	0.140
Kokkos_MemoryPool.cpp	 | 0.220 | 	0.050
Kokkos_UnorderedMap_impl.cpp	 | 0.730 | 	0.010
Kokkos_OpenMP_Task.cpp	 | 0.720 | 	0.480
Kokkos_OpenMP_Exec.cpp	 | 0.670 | 	0.210
test_atomic.cpp	 | 1.880 | 	135.340
test_mempool.cpp	 | 0.870 | 	1.160
test_taskdag.cpp	 | 0.740 | 	0.580

**Comment by crtrott** [comment]
After splitting all the files I am down to 155seconds for the PerfTest and 330s for UnitTests (I didn't split the Team UnitTest thing).
