### ISSUE TITLE
Add variant of subview that lets users add traits

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#134]
Add Kokkos::subview variant that lets users add traits (e.g., Atomic, MemoryUnmanaged, RandomRead) to the resulting type.  This is particularly useful for creating an unmanaged subview of a managed View, since it would avoid the intermediate step of assigning from a managed to an unmanaged View (before taking the subview).  It might look something like this:
```
auto X_unmanaged = Kokkos::subview_with_traits<MemoryUnmanaged> (X, std::make_pair (3, 10));
```
The advantage is that users would not need to know the exact return type (which is tricky given different layouts and slices!), yet could still add traits to it.

**Comment by hcedwar** [comment]
Likely do-able simply as: auto x = subview< Traits >( ... );

**Comment by hcedwar** [comment]
The refactored View will allow *compatible* subview construction as
 view_type y( ... );  
 subview_type x( y , ...subview_args... );

**Comment by mhoemmen** [comment]
When you say "likely do-able," does that mean it works now, or that it's easy to make that work?

**Comment by crtrott** [comment]
That means we can add that without too much trouble.

**Comment by hcedwar** [comment]
Putting this feature in the experimental view.

    View<...> primary( ...allocation_arguments... );
    View<...> subview( primary , ...subview_arguments... );

The constructor for subview performs a static_assert on whether the subview type, primary view type, and subview arguments are compatible.

**Comment by crtrott** [comment]
Ok that should be good enough for now. Btw your naming was a bit unfortunate took me a bit to get what you was saying better:

```C++
View<...> a_view(...allocation_arguments...);
View<...> a_sub_view(a_view, ... subview_arguments...);
```
Do we still want 
```C++
auto a_sub_view = subview<Traits>(a_view, ...subview_arguments...);
```
In the first scheme I need to know what the data_type, layout and memory space are, in the second I don't.

**Comment by mhoemmen** [comment]
I've already hacked up a bit of the "add traits" functionality in Tpetra, for ensuring that I get unmanaged Views, no matter what type of input View comes in.  It would be nice if Kokkos provided that :-)

**Comment by hcedwar** [comment]
Nearly trivial addition to experimental view:

  auto a_sub_view = subview< MemoryTraits >( a_view , ...subview_arguments... );

Does a static_assert that MemoryTraits are really memory traits.

**Comment by crtrott** [comment]
Don't close until its in master.

**Comment by crtrott** [comment]
Pushed to master
