### ISSUE TITLE
task scheduler does not include cuda space

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1345]
```
error: no instance of constructor "Kokkos::TaskScheduler<ExecSpace>::TaskScheduler [with ExecSpace=Kokkos::Cuda]" matches the argument list
            argument types are: (Kokkos::Cuda::memory_space, size_t, unsigned int, unsigned int, unsigned int)
```

I attempted to compile Trilinos that uses Kokkos task scheduler with CUDA. I turned on relocatable device is on. It should enable CUDA tasking but it returns the above error. This compiles fine with host execution spaces. 

These are from my CMakeCache.txt
```
//Kokkos Cuda options
KOKKOS_CUDA_OPTIONS:STRING=rdc,enable_lambda

KOKKOS_CXXFLAGS:STRING=--std=c++11;--relocatable-device-code=true;-expt-extended-lambda;-arch=sm_60;-Xcompiler;-fopenmp
``` 

I encountered this problem a few times and this shows up again. Something is changed (probably macros) but not delivered to task scheduler with cuda. What do I need to define additionally in Trilinos configure ?

**Comment by kyungjoo-kim** [comment]
Thanks to @hcedwar we resolve this issue. 

The problem occurs because I did not use scheduler memory space (which is Kokkos::CudaUVMSpace). The constructor does not find out a correct match to the input argument with Kokkos::CudaSpace. Could we have a better error message to improve usability ? or When a user provides Kokkos::CudaSpace, Kokkos redirects it to CudaUVMSpace.

**Comment by ndellingwood** [comment]
@hcedwar @ibaned 

From @kyungjoo-kim previous message:
`... or When a user provides Kokkos::CudaSpace, Kokkos redirects it to CudaUVMSpace.`

Is his question a valid use case for the new AnonymousSpace #1321?

**Comment by hcedwar** [comment]
no
