### ISSUE TITLE
OPenMPI + OpenMP

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1356]
I updated my desktop to RHEL7 and things are acting odd, when I run in MPI+OPENMP I get no threading.
 
dir-unit_test (gcc) 79 $ mpirun -np 1 ./simple_mesh  --kokkos-threads=12
 
yileds a top of only 200%,
 
without mpirun it is 1200% as expected.  I output omp_get_max_threads and it is 12 in both cases.  So, something is stopping the parallel region.  I’m using openmpi 1.10.1 and gcc 6.1.  Here is some outputs and the code
 ```
time ./simple_mesh  --kokkos-threads=12
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name s993289.srn.sandia.gov and rank 0!
12
 
real        0m10.488s
user       0m56.311s
sys          0m0.551s
dir-unit_test (gcc) 86 $ time mpirun -np 1  ./simple_mesh  --kokkos-threads=12
Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name s993289.srn.sandia.gov and rank 0!
12
 
real        0m25.686s
user       0m47.648s
sys          0m0.553s
dir-unit_test (gcc) 87 $
 ```
Here is the source code
 
 ```
int main(int argc, char **argv) {
 
  Teuchos::GlobalMPISession mpiSession(&argc,&argv);
  Teuchos::RCP<Teuchos::MpiComm<int> > comm
    = Teuchos::rcp(new Teuchos::MpiComm<int>(Teuchos::opaqueWrapper(MPI_COMM_WORLD)));
  Kokkos::initialize(argc, argv);
 
  std::cout << omp_get_max_threads()<<std::endl;
  for (int j=0;j<1000;++j)
  Kokkos::parallel_for(1000000, KOKKOS_LAMBDA (int i) {
      double x= 0.001*i;
      double y=sin(x);
    });
 
  Kokkos::finalize();
 
}
```

**Comment by nmhamster** [comment]
@bathmatt - can you try:

mpirun --map-by socket --bind-to socket <put stuff here>

You are binding to a single core with two hyperthreads I think.

**Comment by bathmatt** [comment]
OK, yes, that resolved the issue.

**Comment by mhoemmen** [comment]
@bathmatt FYI you can do this:
```
Teuchos::RCP<Teuchos::MpiComm<int> > comm
   = Teuchos::rcp(new Teuchos::MpiComm<int>(MPI_COMM_WORLD));
 Kokkos::initialize(argc, argv);
```
That is, you don't need the `opaqueWrapper` call.  This has been true for a couple years at least.
