### ISSUE TITLE
Exclusive scan + last value API

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1358]
Brought up by @kyungjoo-kim 

Currently There is this API called `get_crs_row_map_from_counts`, which combines an exclusive scan to form a `row_map` array along with the retrieval of the last value of that array, because that value indicates the size needed to allocate the entries array. This is widely useful functionality, and this issue is to make it more "official".

- [ ] What should the API be? Can we make it an overload of `parallel_scan`
- [ ] We still have the redundancy of `Crs` and `CrsGraph`... how do we make progress on this going forward? (@crtrott )

**Comment by ndellingwood** [comment]
@csiefer2 may be interested in this

**Comment by crtrott** [comment]
Yeah I wanted this for a long time, but always was to lazy to implement it. 

API: 
```c++
parallel_scan(N,functor,return_value);
```

Regarding Crs vs CrsGraph, I am still fully convinced that we should not have higher level data structures in core, I understand why we need something like that as part of the API for the workgraph call, but that should be part of the execution policy and not encouraged to be used as a standalone data structure. Higher level data structures belong into containers, and should be kept separate.

**Comment by hcedwar** [comment]
Be sure is an alternative, not a replacement, as return value forces synchronization.

**Comment by mhoemmen** [comment]
@hcedwar Doesn't `parallel_reduce` already synchronize even if you really just wanted to leave the reduction result on device?

**Comment by stanmoore1** [comment]
I also want this.

**Comment by crtrott** [comment]
Vinh is doing this.

**Comment by mhoemmen** [comment]
Yay!  I want this too :D
