### ISSUE TITLE
KOKKOS_ENABLE_DEPRECATED_CODE

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1359]
`!defined(KOKKOS_DISABLE_DEPRECATED)` -> `defined(KOKKOS_ENABLE_DEPRECATED_CODE)`

`defined(KOKKOS_ENABLE_DEPRECATED_CODE_REMOVAL)` -> `!defined(KOKKOS_ENABLE_DEPRECATED_CODE)`

Makefile option: `disable_deprecated_code`.
CMake option: `Kokkos_ENABLE_Deprecated_Code`/`KOKKOS_ENABLE_DEPRECATED_CODE`.

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe

**Comment by ibaned** [comment]
We strongly recommend turning this on as soon you get the latest version of Kokkos so that you can find out all the places you're using deprecated functionality and prepare for its eventual disappearance in Kokkos version 3.0
