### ISSUE TITLE
Kokkos does not build with -DKOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE as part of Trilinos

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#1362]
Error:

[  3%] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Profiling_Interface.cpp.o
In file included from /home/csiefer/Trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Profiling_Interface.cpp:44:0:
/home/csiefer/Trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
       

Configure:

cmake \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_Kokkos:BOOL=ON \
-DKokkos_ENABLE_Cuda:BOOL=ON \
-DKokkos_ENABLE_Cuda_UVM:BOOL=ON \
-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON \
-DKOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON \
-DTrilinos_ENABLE_CXX11:BOOL=ON \
-DTrilinos_CXX11_FLAGS:STRING='-std=c++11 -expt-extended-lambda' \
-DCMAKE_CXX_FLAGS:STRING='-Wall -DKOKKOS_CUDA_USE_LAMBDA=1 -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-inline -Wshadow' \
-DTPL_ENABLE_CUDA:BOOL=ON \
../Trilinos

**Comment by mhoemmen** [comment]
@csiefer2 This shouldn't affect the issue, but how come you're setting `KOKKOS_CUDA_USE_LAMBDA` manually on the command line?  Does the `Kokkos_ENABLE_Cuda_Lambda` CMake option not work?

**Comment by csiefer2** [comment]
@mhoemmen Because it is a cut down version of artemis' nightly test configure 👅

**Comment by ndellingwood** [comment]
Here's a modified version of the script above I used to configure/build Trilinos with RDC, cuda/8.0.44 and gcc/5.3.0 if you'd like to test

```
#!/bin/bash
 
export TRILINOS_HOME=/home/ndellin/trilinos/Trilinos
export CXX=${TRILINOS_HOME}/packages/kokkos/bin/nvcc_wrapper
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
 
INSTALL_LOCATION=${PWD}/install
 
rm -rf CMakeCache.txt CMakeFiles
 
cmake \
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_COMPILER:FILEPATH="`which ${CXX}`" \
-D CMAKE_CXX_FLAGS:STRING='-Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-inline -Wshadow' \
-D TPL_ENABLE_CUDA:BOOL=ON\
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_CXX11:BOOL=ON \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
-D Kokkos_ENABLE_Cuda:BOOL=ON \
-D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
-D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON \
-D KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON \
-D Kokkos_ENABLE_TESTS:BOOL=ON \
-D KOKKOS_ARCH="Kepler35" \
${TRILINOS_HOME}
```

Lots of warnings like the following:
`nvlink warning : Stack size for entry function '_ZN6Kokkos4Impl75_GLOBAL__N__51_tmpxft_0000798b_00000000_7_Kokkos_Cuda_Task_cpp1_ii_b2872e7123cuda_task_queue_executeEPNS0_9TaskQueueINS_4CudaEEEi' cannot be statically determined`

**Comment by csiefer2** [comment]
Works, thanks!
