### ISSUE TITLE
Algorithms: add inverse permute vector option and multi view sort 

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1373]
@crtrott 
can we look at the performance of the sort, as you know we sort our particles for different reasons.  After the end of the move we sort in the new locations.  This is the dominate cost of the EMPIRE application.  Can we look and tune the sort?

Here are some numbers

```
p=0 |    Main time loop:87.7892 [1] (0)
p=0 |       Particle Update:17.0451 [100] (0)
p=0 |          Pre move work:0.388989 [100] (0)
p=0 |          Inject particles:7.9e-05 [100] (0)
p=0 |          Weight fields:1.4241 [100] (0)
p=0 |          Push particles:15.2313 [100] (0)
p=0 |             Accelerate Particles:0.446598 [100] (0)
p=0 |             Move particles:1.19688 [100] (0)
p=0 |             Sort particles:11.9537 [100] (0)
p=0 |             Weight charge:1.63297 [100] (0)
p=0 |             Remainder: 0.001162
p=0 |          Remainder: 0.000675
p=0 |       Fill RHS:9.78265 [100] (0)
p=0 |       Linear solve:44.3582 [100] (0)
p=0 |       output diagnostics:1.08668 [100] (0)
p=0 |       Dump exodus:15.4976 [100] (0)
p=0 |       Remainder: 0.018979

```

**Comment by crtrott** [comment]
One thing we could consider is sorting multiple views at the same time. That said, if the actual Sorter.sort(...) functions are the ones whcih take the vast majority of time I am not sure that there is much we can do. Basically this is an operation which by its nature has a pretty bad memory access pattern. If it is the "create_permute_vector" we should check for inbalance and if we can do some better parametrizationm i.e. choose a better bin size. But please run the kernel timer so we can see what part of sort is causing all the time consumption. But there is a reason we only sort every couple hundred timesteps in MD. Sorting our particles costs almost an order of magnitude more than doing a typical force calculation.

**Comment by mhoemmen** [comment]
@bathmatt Are all those `Sorter.sort` calls just applying the permutation vector that `create_permute_vector` made?

**Comment by crtrott** [comment]
Yes Mark, all those sort calls just apply the permutation vector. This is where we could maybe gain a bit. In particular for something like this we could potentially create the inverse map, and use that to apply the sorting. That way we can do contiguous writes and gathers instead of contiguous reads and scatters. The scatters will cause a lot of cache line stealing, where in the gather case the cache lines will just be shared.

**Comment by crtrott** [comment]
The reason I didn't think of this before is that creating the inverse map from the permutation vector is basically one sort apply, with the same cost. So this will only bring benefits if there are enough applies which get enough faster to ammortize effectively an additional apply.

**Comment by bathmatt** [comment]
I timed the part in the setup, and the applys, it is roughtly 80% on the apply and 20% on the setup.

I think what @crtrott suggests, creating an inv-scatter would be helpful.  

There are 10 applies in this example, I think I could remove 3 of them which would reduce the cost.

**Comment by crtrott** [comment]
Yeah those numbers make sense. I would expect the sort to create the permute vector to be about 2-3x more costly than an apply. Let us try two things: 
1) have a function to create the inverse permute vector, to be able to do a gather/contiguous apply
2) provide a sort function which takes multiple views, to amortize the cost of reading the permute vector, and the launch overhead. 

We should also check if there is a lot of loadd imbalance in the sort (i.e. if we have some bins which are hit really a lot while other ones are not). That may hint at ways to improve the setup phase of the sort. But I am pretty confident the two issues are orthogonal.

**Comment by crtrott** [comment]
I tentatively schedule this for April delivery. But no promises yet. On the other hand it shouldn't be very hard to do.

**Comment by crtrott** [comment]
Btw. if anybody feel like providing a pull request for this, please to do so ;-)

**Comment by crtrott** [comment]
Actually we have always been doing that. We do not have the permute vector we only ever compute the inverse compute vector i.e. we gather and write not read and scatter.
