### ISSUE TITLE
-mtune=skylake-avx512  with GCC 7.2.0 ?

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1374]
Our tests are failing with:
```
/home/jenkins/blake/workspace/Kokkos_SLURM_inner_test/core/src/impl/Kokkos_Serial.cpp:1:0: error: bad value (skylake-avx512) for -march= switch
```
We need to figure out whether the flag is just plain wrong or if GCC wasn't built right.

**Comment by ibaned** [comment]
According to this page:
https://gcc.gnu.org/gcc-6/changes.html
`-march=skylake-avx512` is supported since GCC 6.
This suggests the SEMS module is built without support for it.

**Comment by nmhamster** [comment]
@ibaned - you shouldn't usually be running hardware optimized builds with SEMS if I recall. They do not support that in their operating requirements. Only the testbeds should be used for optimized builds.

**Comment by nmhamster** [comment]
@ibaned - which machine was used for the build when it errored?

**Comment by rppawlo** [comment]
> you shouldn't usually be running hardware optimized builds with SEMS if I recall. They do not support that in their operating requirements. Only the testbeds should be used for optimized builds.

So how does this square up with the new KOKKOS_ARCH flag? I though that we are eventually going to be forced to use KOKKOS_ARCH in all cmake/Trilinos builds, but if it is injecting all optimization flags, then we will no longer be able to use SEMS modules. Can we somehow override these flags? cc'ing @crtrott

**Comment by nmhamster** [comment]
@rppawlo - I think you will have to rely on testing on genuine hardware builds (e.g. testbeds) on these systems moving forward. Right now, I would argue a quick build without heavy optimization is fine for testing of Trilinos because it is unlikely that developers will be able to test all combination of hardware options anyway. The high-level optimized builds should do sufficient testing to ensure the functionality is good and then the more aggressive optimized builds will be done overnight. Do you think this is a bad plan?

**Comment by rppawlo** [comment]
@nmhamster - I'm thinking about the typical Trilinos developer or external user that doesn't use or have access to the testbeds. Many trilinos packages now have a required dependence on kokkos. If Kokkos requires everyone to use KOKKOS_ARCH in the future, then the sems modules will no longer work if the flag above is always injected - if I understand things correctly. Just wondering if we can override what flags KOKKOS_ARCH injects.

**Comment by ibaned** [comment]
@nmhamster The machine being used was the `blake` Skylake testbed. I think the compiler is at

```
/home/projects/x86-64/gcc/7.2.0/bin
```


@rppawlo 
I don't know how aggressively we'll be requiring `KOKKOS_ARCH`, especially without a clear override mechanism. Its more of a convenience mechanism for those who do know exactly what hardware they're on.

If you do use `KOKKOS_ARCH`, one approach for generic builds is just to target an older generation of Intel CPUs, for example `KOKKOS_ARCH=SNB` (should work for anything Sandy Bridge and later), or even `KOKKOS_ARCH=WSM` which should work on all Kokkos-supported Intel CPUs. I don't know if we officially claim this is the best way, but in practice it should work well.

**Comment by nmhamster** [comment]
@rppawlo - we should probably just enable a generic X86 build for now because many workstations will not be able to run the later ISA anyway. Overriding with `-msse4.2` will get a generic X86 that will run on all modern processors.

**Comment by nmhamster** [comment]
@ibaned - this is not SEMS, its test beds. I will take a look for you but I'm fairly sure we have previously tested this combination of flags and compiler.

**Comment by ibaned** [comment]
This was an automated Jenkins build:

https://jenkins-son.sandia.gov/job/Kokkos_SLURM_inner_test/11157/console

Part of the output says:
```
Compiling with: /home/projects/x86-64/gcc/7.2.0/bin/g++
```
also
```
COMPILERMODULE=gcc/7.2.0
```
And an example compile line is:
```
g++ -I./ -I/home/jenkins/blake/workspace/Kokkos_SLURM_inner_test/core/src -I/home/jenkins/blake/workspace/Kokkos_SLURM_inner_test/containers/src -I/home/jenkins/blake/workspace/Kokkos_SLURM_inner_test/algorithms/src  --std=c++11 -march=skylake-avx512 -mtune=skylake-avx512 -mrtm -fopenmp -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized -c /home/jenkins/blake/workspace/Kokkos_SLURM_inner_test/core/src/impl/Kokkos_Serial.cpp
```
Does it work with `/home/projects/x86-64/gcc/7.2.0/bin/g++` for you?

**Comment by rppawlo** [comment]
I like the idea of a generic X86 target for KOKKOS_ARCH. Asking users to pick an older target architecture is probably going to lead to confusion and lots of emails.

**Comment by mhoemmen** [comment]
Please don't make this hard it's already hard enough to configure Trilinos

**Comment by nmhamster** [comment]
@ibaned / @mhoemmen - I think we need to allow for it *not* to be configured (and this be the default) which means, no architecture optimized flags. This will give a generic Westmere-grade build.

**Comment by ibaned** [comment]
@rppawlo @mhoemmen I think this spiralled a bit out of scope: the long-term role and usability of `KOKKOS_ARCH` is pretty separate from this particular compiler on this particular testbed not accepting this particular flag. I created a different issue to discuss that: #1376

**Comment by nmhamster** [comment]
@ibaned - Looks like g++ is also working.

```
$ g++ -o stream-gpp-720 -fopenmp -O3 -march=skylake-avx512 -mtune=skylake-avx512 stream.c
stream.c:188:33: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     "Add:       ", "Triad:     "};
                                 ^
stream.c:188:33: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
stream.c:188:33: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
stream.c:188:33: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
-bash-4.2$
```

**Comment by nmhamster** [comment]
@ibaned - are you testing `develop` branch?

**Comment by ibaned** [comment]
@nmhamster yes this is a Jenkins test of the `develop` branch I'm not sure what it is about the scripts being used that causes this error.

**Comment by nmhamster** [comment]
@ibaned - let me try a build here first on Blake and see if its just config/env first. Sounds like something is a little weird.

**Comment by nmhamster** [comment]
@ibaned  - `$ ../generate_makefile.bash --arch=SKX --with-openmp --compiler=`which g++` then build is working fine (in that code is compiling and chugging away without any error messages).

**Comment by ibaned** [comment]
@nmhamster I guess there is something wrong with the Jenkins scripts. Unfortunately my knowledge of those is quite limited.

**Comment by nmhamster** [comment]
OK. I'll take a look. Its running fine for me with interactive access.

**Comment by nmhamster** [comment]
@ibaned - the issue is that the node compiling the test is not correctly mounting the projects space, so it does not actually use GCC 7.2.0. Because we cannot specify an exact compiler (see #1377) we aren't detecting that. The effects you are seeing above are not because of the compiler installation or because of anything in Kokkos.

**Comment by ibaned** [comment]
@nmhamster Thanks for figuring this out! Can you let me know (by email if preferrable) if/when the projects mounting issue on this node is resolved?

**Comment by nmhamster** [comment]
@ibaned - all fixed. Build now shows good on Jenkins.

**Comment by ibaned** [comment]
Thanks @nmhamster !
