### ISSUE TITLE
Long-term role and usability of KOKKOS_ARCH

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1376]
#1374 raised questions from users @rppawlo and @mhoemmen , namely:
 - Is the long-term goal to always force Trilinos to use `KOKKOS_ARCH` when configuring?
 - Is there a way to override the flags that `KOKKOS_ARCH` injects?
 - What about users who want to build a "generic" Trilinos version that works on all Intel CPUs?
 - Can we / should we add an "X86" option to `KOKKOS_ARCH` ?

**Comment by mhoemmen** [comment]
Automatic detection would be good, as long as users have an option to override, e.g., for cross-compilation.

**Comment by mhoemmen** [comment]
The "generic" option shouldn't be tied to x86.  It should mean "don't pass any architecture-specific flags to the compiler."

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe

**Comment by nmhamster** [comment]
@mhoemmen - automatic detection is a pain because of the potential for variability in the numerics when vectorization and platform specific optimization are encountered. The code groups get round this by imposing strict FP which all but kills the optimization process. I'm not sure what is best here for Trilinos.

**Comment by ibaned** [comment]
I think an automatically detected hint is a good idea, in particular allowing users to figure out which Intel family their CPU belongs to, for example whether it is Sandy Bridge or Westmere. The same goes for GPUs, non-experts don't necessarily know that the P100 maps to `Pascal60`. This is just to provide suggestions, not forcing anything.

**Comment by nmhamster** [comment]
I'm worried about cross-compile etc in this setting too. Its already a minefield. We would have to be extremely vigorous in testing that the setting/disable of this would work properly and that the tests understand the numerical tolerances of the choices being made.

**Comment by mhoemmen** [comment]
I'll be happy if 
  - not specifying `KOKKOS_ARCH` just picks some sensible works-everywhere default, and
  - Trilinos documents what users need to do in order to optimize for a specific architecture.

**Comment by crtrott** [comment]
There is a KOKKOS_ARCH=None setting (or NONE or none don't know which). That is an accepted architecture, but will not add any flags. That said, it also means you don't get any assembly optimized code from us or any of the other goodies which come with you telling us what you want to optimize for.

**Comment by crtrott** [comment]
Medium term goal (as in by April) is that KOKKOS_ARCH must be set, but defaults to None. I.e. the user does not have to set it explicitly.

**Comment by crtrott** [comment]
It is "None": line 77 or so in https://github.com/kokkos/kokkos/blob/master/cmake/kokkos_options.cmake
