### ISSUE TITLE
New View : Test Compilation Downstream

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#138]
Trilinos all
Nalu
LAMMPS

**Comment by ndellingwood** [comment]
Asynchronous deep copy for LAMMPS still pending

**Comment by hcedwar** [comment]
Asynchronous deep copy of new view in develop.

**Comment by hcedwar** [comment]
Trilinos - good
NALU - good
LAMMPS - pending / debugging

**Comment by crtrott** [comment]
Looks good now.
