### ISSUE TITLE
Using Kokkos on Mutrino/Trinity 

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1387]
I am trying to use the latest Kokkos on Cray XC30 with OpenMP backend (GCC7.2).  Do you have any recommended installation options?  I am trying to use HWLOC, but I am getting link errors (prohibits shared library).

**Comment by dholladay00** [comment]
On Cray systems, I have added `export CRAYPE_LINK_TYPE=dynamic` to my environment and that has been successful. There are probably other options I'm not aware of, but that one has worked for me.

**Comment by mhoemmen** [comment]
@jjellio

**Comment by nmhamster** [comment]
@keitat - what errors are you getting?

`../generate_makefile.bash --with-openmp --compiler=`which CC` --arch=HSW` and then a `make test` work fine for me.

**Comment by keitat** [comment]
It is working for me.  Does it work without bash script?  Say "make -DCMAKE_KOKKOS_ARCH=HSW"

Also, I am working on KNL.  Should I use Intel or GCC (with OpenMP backend)?  Also, do you have any example of running Kokkos code on KNL nodes?

**Comment by jjellio** [comment]
Keita, I've been building Trilinos (w/Kokkos always) on Cray w/OpenMP + Intel/GCC with no issues. Occasionally packages break, but Tpetra/Kokkos have been working. There was an issue last year where building w/out linking pthreads was causing a catastrophic failure, but I believe Cray resolved that issue.

I also have not used the new Cmake Kokkos options. IMO, you are better off managing your modules and compiler options directly.

I have not explicitly tried to link hwloc. I just looked, and do not see a static hwloc lib on the login. They do provide static libnuma (module load numactl)
