### ISSUE TITLE
ScatterView doesn't work with padding

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1392]
Gives the wrong answer, should error out or be fixed.

**Comment by stanmoore1** [comment]
@ibaned shouldn't this be a bug (not enhancement) since the code gives the wrong numerical answer?

**Comment by ibaned** [comment]
I don't think we envisioned scattering to padded views when ScatterView was developed, so this is in some ways expanding the capability of ScatterView.

**Comment by stanmoore1** [comment]
If a developer puts ScatterView into his code and tries to use padding it would be a bug.

**Comment by stanmoore1** [comment]
Thanks!

**Comment by janciesko** [comment]
@stanmoore - Stan, thanks for reporting this. Using the sample below, I was not able to reproduce the error. Would you expect this sample to fail? We might have fixed this in the meantime. 

```
#include <Kokkos_Core.hpp>
#include <Kokkos_ScatterView.hpp>

using DType = int ** [2];

int main(int argc, char *argv[])
{
  int n = 100;
  Kokkos::ScopeGuard kokkos(argc, argv);
  {
    Kokkos::View<DType> view ("myView", n, n);
    Kokkos::deep_copy(view, 0.0);

    auto rangeDim0 = std::pair<int,int>(0+10, n-10);
    auto rangeDim1 = std::pair<int,int>(0+10, n-10);
    auto rangeDim2 = Kokkos::ALL;
    auto sub_view = Kokkos::subview(view, rangeDim0, rangeDim1, rangeDim2);
    
    auto scatter_sub_view = Kokkos::Experimental::create_scatter_view(sub_view);


    Kokkos::parallel_for(32, KOKKOS_LAMBDA(int i) {
    auto scatter_subview_access = scatter_sub_view.access();
    for (int j = 0; j < sub_view.extent(0); ++j) {
      for (int k = 0; k < sub_view.extent(1); ++k) {
        for (int l = 0; l < sub_view.extent(2); ++l) {
          scatter_subview_access(j, k, l) += 1;       
        }   
      }
    }
  });
  Kokkos::Experimental::contribute(sub_view, scatter_sub_view);

  //Check
  Kokkos::parallel_for(view.extent(0), KOKKOS_LAMBDA(int i) {
    for (int k = 0; k < view.extent(1); ++k) {
      for (int l = 0; l < view.extent(2); ++l) {
        if(i >= 10 && i < n-10 && k >= 10 && k < n-10)
          assert(view(i,k,l)==32);
        else
          assert(view(i,k,l)==0);
      }
    }
  });
  }
  return 0;
}
```

**Comment by stanmoore1** [comment]
Hi @janciesko, were you able to reproduce this issue? Eric Phipps (@etphipp) originally reported the issue with padding and ScatterViews. I don't have a reproducer, but may be able to create one.

**Comment by janciesko** [comment]
Hi @stanmoore1 - with the example in the comment above, I was not able to reproduce. The following PR adds coverage for scatter_views with padding and hopefully should detect the issues reported: https://github.com/kokkos/kokkos/pull/4587

**Comment by janciesko** [comment]
We have added coverage for this case with https://github.com/kokkos/kokkos/pull/4587. @etphipp, @stanmoore1, please reopen the issue if issues persist.
