### ISSUE TITLE
Specify ScatterView reduction limits

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1393]
To avoid too frequent reallocation, views are often given extra space to allow room to grow. This makes the reduction in ScatterView more expensive since it is reducing over the empty space. It would be good to allow the user to define a limit on the reduction .

**Comment by ibaned** [comment]
@crtrott is this a good idea? I assume it would be a separate "extent" for the largest-stride dimension only.

**Comment by ibaned** [comment]
I think this is better served by providing better tools for fast reallocation, for example having a subview into a bigger view, not by adding additional size parameters to all the things that might use a View. Views have size information, if that is wrongly reporting capacity and not true extents then that is a View problem.

**Comment by stanmoore1** [comment]
@ibaned see #2276. This is still an issue.
