### ISSUE TITLE
Fix NVIDIA Volta failures

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1395]
The algorithms that make heavy use of atomics and synchronization are failing on Volta, that includes:
 - `MemoryPool`
 - `WorkGraphPolicy`
 - Tasking
 - subwarp reduce and scan

**Comment by hcedwar** [comment]
The work graph and tasking will require CUDA 9.x features to execute properly on Volta

**Comment by ibaned** [comment]
@crtrott will try to fix at least the workhorse Kokkos features like reductions and scans for this promotion.

**Comment by crtrott** [comment]
Bug from LAMMPS:

This is the reax code, according to  Stan if we switch out the parallel_scan for a workaround with parallel_for it works. 

```
LAMMPS/src/KOKKOS/fix_qeq_reax_kokkos.cpp:228
```

Building:
```
make kokkos_cuda_mpi KOKKOS_PATH=/home/crtrott/Kokkos/kokkos -j 48 KOKKOS_CUDA_OPTIONS=enable_lambda
```

Running:
```
cd LAMMPS/examples/reax/HNS/
mpirun -np 1 ../../../src/lmp_kokkos_cuda_mpi -in in.reaxc.hns -k on g 1 -sf kk -pk kokkos newton on neigh half neigh/qeq full -v x 4 -v y 6 -v z 8
```

**Comment by crtrott** [comment]
Also the LAMMPS case works if build for Pascal60 instead of Volta70 ...

**Comment by crtrott** [comment]
Tests were run with Titan V on X86 Rhel6 with CUDA 9.1. Same results apply to AWS instances.

**Comment by hcedwar** [comment]
Task DAG on CUDA has capability to execute a task on a warp or single thread of a warp.  On Volta with CUDA 9 warp synchronizing built-ins must be used with extreme care to insure that the warp mask is correct. Pull request #1431 fixes several improperly called shuffle and warpsync operations.

**Comment by crtrott** [comment]
Pull request #1435 hopefully fixes all of the things for vector level reductions and scans not working for vector lengths < 32 (i.e. sub-warp reductions and scans).
