### ISSUE TITLE
Possible Data Race Condition in Kokkos_HostBarrier

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1398]
I ran my code through Intel Inspector and it reported a data race condition inside Kokkos:

write: Kokkos_HostBarrier.cpp:139
```c++
 bytes[ rank-1 ] = byte_value;
```
read: Kokkos_Spinwait.hpp:99
```c++
while( value != flag ) {
```

I know this part of the code was recently changed. Is this a real issue, or harmless?

Thanks

**Comment by crtrott** [comment]
Most likely false alarm. Barriers have to have potential race conditions since they are supposed to sunchronize.
