### ISSUE TITLE
Possible Data Race Condition in Parallel Scan

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1399]
Intel Inspector is reporting a data race condition in the default `join` method of a parallel_scan:

read: Kokkos_FunctorAdapter.hpp:641
```c++
*((volatile T*)lhs) += *((const volatile T*)rhs);
```
write: incrementing the `update` value (`m_fill`) in my parallel_scan functor
```c++
m_fill++;
```
Is it possible a barrier is missing?

Has anyone ever run the Kokkos unit tests through Intel Inspector? Seems like that would be a good practice.

**Comment by crtrott** [comment]
Yes we did run Intel Inspector, barriers and reductions are prone to false errors because multiple threads explicitly collaborate on the same variables. That said there might still be race conditions which need additional memory fences.
