### ISSUE TITLE
Power8: Fix threads backend

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#140]
This seems completely broken due to memory model. Takes some time.

**Comment by hcedwar** [comment]
The memory model issue may also be a factor in a parallel dispatch bug on X86 when a sequence of parallel_for dispatch are called with no work.  This could have a memory race with setting/clearing the Threads backend closure and starting/stopping the underlying thread pool.

**Comment by hcedwar** [comment]
Si has atomics working on Power 8.  Significantly slows down, probably due to excessive memory_fence.

**Comment by crtrott** [comment]
Marking this as enhancement: currently the pthreads backend is simply not supported on Power.

**Comment by hcedwar** [comment]
The in-development std::threads back-end is being developed with testing on the Power system; issue #255
