### ISSUE TITLE
ThreadVectorRange with a range 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1400]
I found for ``TeamThreadRange(member, ibeg, iend)`` but I could not see ``ThreadVectorRange(member, ibeg, iend)``. Do we have a specifc reason not to have that ? If everything is okay, would it be possible to add a constructor with a range arguments (member, begin, end) ?

**Comment by crtrott** [comment]
OK OK we will do it 👎  ... 

We didn't have that initially because it is better for the compiler and alignment etc. to have vectorized loops which go from 0 to N. But 
  - compilers are getting better
  - too many people ask for this 

So we might as well do it.

**Comment by kyungjoo-kim** [comment]
Oh.... I see why you prefer not to have it. Thanks. 

I meant to use the ``ThreadVectorRange`` on cuda, which can remove unnecessary offset calculation. 

Thank you again.

**Comment by crtrott** [comment]
Kyungjoo I totally get it, and I think we should just do it, but document that if possible use the compile time zero offset variant.

**Comment by bartgol** [comment]
I just thought I'd need this feature too, and I stumbled on this issue. Any rough idea if/when this could end up in master (or at least develop)? To be clear, I'm not trying to put pressure, I'm just trying to understand if I can wait for this, or if I should find a workaround.

Thanks!
