### ISSUE TITLE
Kokkos efficient (no copy) shrinking of a 1D view

### ISSUE THREAD

**Issue by jjellio** [kokkos/kokkos#1417]
I would like to be able to shrink a view in place.

I can see that Kokkos provides a call to realloc().

Supposing I have a 1D view that I wish to shrink, does kokkos provide a means to shrink the view (either by fudging the metadata or by using realloc() ) ?

**Comment by crtrott** [comment]
Uhm do you just want a new view of smaller size (realloc does not guarantee that you keep part of the memory as far as I can tell).

**Comment by jjellio** [comment]
A new view of a smaller size. Effectively, like taking a subview. Having the excess memory freed would be ideal (which is what realloc) would attempt. Currently, I see the ability to resize, which handles the general case of growing or shrinking, and does so for arbitrary dimension views. In the special case that shrink a 1D view, this should be extremely low overhead (no copies necessary).

The use case for this is overallocating something like a CRS matrix, intentionally *not* faulting the memory. Then trimming the sizes back down afterwards. Resizing via copy can produce memory usage spikes, particularly for large matrices. I am not sure taking a subview will work in this case, because I would still have to deal with the parent view - but it could.  I'll probably have more info on that next week.

**Comment by crtrott** [comment]
Updated the title to reflect the issue better.

**Comment by crtrott** [comment]
Idea: specialize resize for 1D Views of trivially copyable/destructable (and these are C++ thingies) types so that it can just realloc with copying.

**Comment by dalabre** [comment]
@crtrott  A few notes; any feedback, comments, guidance?

- we can only resize or realloc managed views
- resize will allow copying old data to new data at corresponding indices; realloc does not (deallocates first)
- do dynamic views only apply in cases of run_time allocation?
- is_trivially_copyable satisfied when storage is contiguous (a trivial memory block), as for scalar types
- is_trivially_destructible uses implicit destructor and not a virtual destructor; includes scalar types

Running 1D view unit tests (Resize and ViewMapping) to instrument and observe; can then begin addressing this issue.

**Comment by mhoemmen** [comment]
This is a special case of reshape (change rank, dimensions, strides, etc., but preserve allocation record), which would also be a useful feature.

**Comment by ajpowelsnl** [comment]
Hello @ibaned and @jjellio -- we believe that you can do this with an in-place subview assignment.  This approach would keep the original allocation, and is explicit about it.
