### ISSUE TITLE
Kokkos dependence on -ldl turn off if DLlib is not enabled by Trilinos

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1422]
Kokkos depends on -ldl in the profiling package but it doesn't have the cmake magic to link it.  

```

-bash-4.2$ /ascldap/users/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpicxx       --std=c++11 -mcpu=power8 -mtune=power8 -fopenmp     -O3 -DNDEBUG   CMakeFiles/PanzerCore_version.dir/version.cpp.o CMakeFiles/PanzerCore_version.dir/__/__/__/teuchos/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o  -o PanzerCore_version.exe -rdynamic ../src/libpanzer-core.a ../../../teuchos/comm/src/libteuchoscomm.a ../../../teuchos/parameterlist/src/libteuchosparameterlist.a ../../../teuchos/parser/src/libteuchosparser.a ../../../teuchos/core/src/libteuchoscore.a ../../../kokkos/core/src/libkokkoscore.a 
/usr/bin/ld: ../../../kokkos/core/src/libkokkoscore.a(Kokkos_Profiling_Interface.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.17'
/usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe

**Comment by nmhamster** [comment]
Note - we have this occurrence more on the POWER8 systems because the MPI library doesn't seem to add -ldl to the link line here. We can investigate more, but I think in the end, this needs to be fixed within Kokkos/Trilinos.

**Comment by ibaned** [comment]
You won't get "magic" linkage unless you use shared libraries. There is no way for a static library (`.a`) to indicate its dependencies.

**Comment by crtrott** [comment]
OK what needs to happen is that profiling gets turned off if the DLlib didn't get enabled in Trilinos.

**Comment by ibaned** [comment]
This actually has to be done in Trilinos since the Kokkos build system is so tightly integrated into Trilinos now. See trilinos/Trilinos#2562 for the fix.
