### ISSUE TITLE
Kokkos_ENABLE_Profiling=OFF does not disable DLLib in Trilinos

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1423]
at least the Kokkos_Profiling_Interface.cpp.o is built and in the library so that seems to be a bug.

I'm trying to work around the kokkos cmake bug with dlopen

I still get this at panzer link time
/usr/bin/ld: ../../../kokkos/core/src/libkokkoscore.a(Kokkos_Profiling_Interface.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.17'

**Comment by nmhamster** [comment]
@bathmatt - can you add “-ldl” to your CMake link flags for now?

**Comment by bathmatt** [comment]
I figured out that I can 
TPL_DLLib_LIBRARY=-ldl
and get past that.  Not sure why it isn't auto finding it...

**Comment by crtrott** [comment]
Yeah Trilinos is supposed to automatically enable/add this ..

**Comment by ibaned** [comment]
I don't think a Trilinos package can tell TriBITS that its dependency on a TPL (`dl`) is dependent on some conditions. You may have to say something like `-DKokkosCore_ENABLE_DLLib:BOOL=OFF` or `-DTPL_ENABLE_DLLib:BOOL=OFF`.

**Comment by ibaned** [comment]
@bathmatt I think profiling is still being "disabled" to the extent Kokkos is capable within TriBITS, you can check by looking at `KokkosCore_config.h` for the absence of `KOKKOS_ENABLE_PROFILING`.

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe @micahahoward just in case you _really_ need to turn off dlopen etc., this may be helpful.
