### ISSUE TITLE
Dynamic resizeable 1dimensional view

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#143]
Dynamically resizeable one dimensional view from within a executing kernel - a replacement for the experimental segmented view.  Likely to use a segmented memory space.

**Comment by hcedwar** [comment]
In containers/src/Kokkos_DynamicView.hpp
Initial unit testing with Serial, OpenMP, Threads, and CUDA.

**Comment by crtrott** [comment]
Merged to master and Trilinos

**Comment by hcedwar** [comment]
In master
