### ISSUE TITLE
Question: portable use of std functions

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1433]
Related to issue #986.

I want to use the `isfinite` function. My understanding from #986 is that I can put `using std::isfinite` in the code and when using the cuda backend which has its own `isfinite`, the compiler should pick the correct thing. 

However (using cuda backend, cuda 8.0, gcc-5.4.0), I get the following error:
```
error: more than one instance of overloaded function "isfinite" matches the argument list:
            function "isfinite(double)"
            function "std::isfinite(double)"
            argument types are: (real_t)
```

I could put guards around the `using` statement and that would probably work for my purposes, but I am curious if someone has thought of better and more robust solution to this problem.

**Comment by mhoemmen** [comment]
A while back we ended up writing a traits class for stuff like this.  I'm hoping that eventually we won't have to worry about it.

**Comment by dholladay00** [comment]
Is this function in said traits class? If not, is the best solution for the time being to put some guards around it?

**Comment by mhoemmen** [comment]
@dholladay00 I was referring to (the perhaps unfortunately named) Kokkos::ArithTraits: 

https://github.com/trilinos/Trilinos/blob/develop/packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp

It has `isInf` that you could use directly.  We were never quite sure where to put this traits class or what to call it, but it's handy.

**Comment by dholladay00** [comment]
Thanks for the info. I think for now I will use `#ifndef KOKKOS_ENABLE_CUDA` guards around my `using` statements. Perhaps when I use kokkos-kernels this will change. 

Closing the issue for now.
