### ISSUE TITLE
Cuda: level 1 scratch memory bug (reported by Stan Moore)

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1434]
Our logic to grep a chunk of level 1 scratch for a team was faulty, and there was a chance that it would grep one chunk over the limit. This was exposed by the SNAP potential in LAMMPS / ExaMiniMD. 

I have a fix.

**Comment by stanmoore1** [comment]
@crtrott Thanks!

**Comment by stanmoore1** [comment]
I confirm #1435 fixes the crash we saw in the SNAP potential in LAMMPS / ExaMiniMD.
