### ISSUE TITLE
[Question] parallel_for for simple nested loops

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1438]
In the past presentations of Kokkos, I saw a new parallel_for API to efficiently parallelize simple nested loops.  Where can I find an example for that?  In my code, I have several nested blocks in which no computation is performed between for statements.
```

for ( i =0;  ...
   // Nothing happens here
    for ( j = 0; ...
         A(i,j) = ... ;
```

**Comment by crtrott** [comment]
This is the MDRangePolicy for which two simple examples are found here:
https://github.com/kokkos/kokkos/tree/master/example/tutorial/06_simple_mdrangepolicy

**Comment by crtrott** [comment]
Closing the issue assuming it answered your question. If not feel free to reopen.

**Comment by crtrott** [comment]
Btw Keitat, think about joining our slack channel for these questions: kokkosteam.slack.com
