### ISSUE TITLE
Tie atomic updates to execution space or even to thread team? (speculation)

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#144]
Would it make sense to tie atomic updates to the execution space in which one plans to execute them?  Right now, the implementation of atomic updates depends only on build options.  Furthermore, it might make sense to tie atomic updates to a particular thread team.

**Comment by crtrott** [comment]
What you are talking about is effectively the concept of contention groups. No hardware really supports that right now and we don't have any such concept in Kokkos at the moment. Also I am not sure that I would want that for now. Using contention groups in any productive way is probably even more complex than using teams as such. So I think any real discussion over this can probably wait for a while.

**Comment by mhoemmen** [comment]
I'm OK with that -- I just want to document the issue.

Would OpenCL's restriction of atomics to within a team be the same thing as "contention groups"?  Just curious.

**Comment by crtrott** [comment]
OK closing this issue, we can discuss contention groups in a few years again ;-)
