### ISSUE TITLE
Any Performance Tuning Document

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1446]
I am just looking for any example and instances for KNL (flat/cache mode) with Kokkos.  My code is written for regular Intel CPUs, but I am looking for examples that use HBW Space and nested parallel for vectorization.  Do you have any documents available?  I saw several tutorial slides, but they are putting more emphasis on GPUs.

**Comment by crtrott** [comment]
Not really sorry. General optimization rules for KNL apply however.

**Comment by keitat** [comment]
That is good to know.  I thought nesting of parallel_for (such as team or vector) would help KNL performance.   It would be great extending the tutorial example to provide multiple platform implementations (HBW, CUDA, CUDA UVM and HOST) ... maybe interns's project?

**Comment by crtrott** [comment]
Oh all the tutorial implementations are multi platform. They work perfectly fine on KNL for example and give pretty decent performance. If you want manually management for memory spaces you need to enable the optional dependency on the memkind library though.

**Comment by keitat** [comment]
Just to make sure.  Is there any examples of memory allocation on HBWSPACE?
  
`Kokkos::View<T **,Kokkos::Host<Kokkos::OpenMP, Kokkos::HBWSpace>>`

**Comment by mhoemmen** [comment]
@keitat Do you mean `Kokkos::View` allocation?  It just works like any other owned `Kokkos::View`.

**Comment by crtrott** [comment]
What you did there is right, but you need to enable the memkind library, which you need first to install.
You need 
MEMKIND_PATH=...
and
KOKKOS_USE_TPLS=experimental_memkind
defined in your Makefile.
