### ISSUE TITLE
Unable to build for Cuda device on Power9/Volta

### ISSUE THREAD

**Issue by dogunter** [kokkos/kokkos#1450]
I cannot get the development branch to build for the Cuda device on a Power9/Volta system.

$ ~/kokkos/generate_makefile.bash --prefix=/home/dog/software/kokkos-power9-gcc640-cuda91 --with-devices=Cuda --arch="Power9,Volta70" --with-cuda-options=force_uvm,enable_lambda --compiler=/usr/local/cuda-9.1/bin/nvcc --with-cuda=/usr/local/cuda-9.1 

$ make
cd core; \
make -f /home/dog/kokkos/core/src/Makefile KOKKOS_SRC_PATH=/home/dog/kokkos CXX=/usr/local/cuda-9.1/bin/nvcc KOKKOS_DEVICES=Cuda,Cuda KOKKOS_ARCH=Power9,Volta70 CUDA_PATH=/usr/local/cuda-9.1 GTEST_PATH=/home/dog/kokkos/tpls/gtest KOKKOS_CUDA_OPTIONS=force_uvm,enable_lambda KOKKOS_PATH=/home/dog/kokkos PREFIX=/home/dog/software/kokkos-power9-gcc640-cuda91 build-lib
make[1]: Entering directory `/home/dog/kokkos-build/core'
/usr/local/cuda-9.1/bin/nvcc -I./ -I/home/dog/kokkos/core/src -I/home/dog/kokkos/containers/src -I/home/dog/kokkos/algorithms/src -I/usr/local/cuda-9.1/include  --std=c++11 -expt-extended-lambda -arch=sm_70 -O3 -c /home/dog/kokkos/core/src/impl/Kokkos_Spinwait.cpp
In file included from /home/dog/kokkos/core/src/impl/Kokkos_Spinwait.cpp:44:0:
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Utilities.hpp:59:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Utilities.hpp:65:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Utilities.hpp:73:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Utilities.hpp:80:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_UniqueToken.hpp:74:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_UniqueToken.hpp:78:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_UniqueToken.hpp:82:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_Core_fwd.hpp:68:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_Core_fwd.hpp:214:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION static void verify(void) {}
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_Core_fwd.hpp:215:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION static void verify(const void *) {}
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_BitOps.hpp:66:1: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
 KOKKOS_FORCEINLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_BitOps.hpp:92:1: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
 KOKKOS_FORCEINLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_BitOps.hpp:116:1: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
 KOKKOS_FORCEINLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_BitOps.hpp:142:1: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
 KOKKOS_FORCEINLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_BitOps.hpp:168:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:157:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION operator T() { return v ; }
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:261:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:264:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:268:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:273:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:277:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:294:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:297:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:301:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:306:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:310:10: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   static KOKKOS_INLINE_FUNCTION
          ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:391:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:396:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:403:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:439:1: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
 KOKKOS_FORCEINLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:459:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION integral_nonzero_constant( const T & ) {}
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Traits.hpp:468:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION integral_nonzero_constant( const T & v ) : value(v) {}
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_Error.hpp:73:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:71:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION static
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:75:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:143:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:147:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:231:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION static
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:323:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:334:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:339:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:349:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:353:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:359:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:364:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:375:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:383:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:389:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:169:40: error: ‘__device__’ does not name a type
   #define KOKKOS_FORCEINLINE_FUNCTION  __device__  __host__  __forceinline__
                                        ^
/home/dog/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:400:3: note: in expansion of macro ‘KOKKOS_FORCEINLINE_FUNCTION’
   KOKKOS_FORCEINLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dog/kokkos/core/src/Kokkos_Macros.hpp:170:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/dog/kokkos/core/src/Kokkos_HostSpace.hpp:248:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION static
   ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dog/kokkos/core/src/Kokkos_Atomic.hpp:71:0,
                 from /home/dog/kokkos/core/src/impl/Kokkos_Spinwait.cpp:47:
/home/dog/kokkos/core/src/Kokkos_HostSpace.hpp: In member function ‘std::__cxx11::string Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::get_label() const’:
/home/dog/kokkos/core/src/Kokkos_HostSpace.hpp:245:25: error: ‘head’ is not a member of ‘Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::RecordBase {aka Kokkos::Impl::SharedAllocationRecord<void, void>}’
     return std::string( RecordBase::head()->m_label );
                         ^~~~~~~~~~
In file included from /home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Locks.hpp:53:0,
                 from /home/dog/kokkos/core/src/Kokkos_Atomic.hpp:123,
                 from /home/dog/kokkos/core/src/impl/Kokkos_Spinwait.cpp:47:
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp: At global scope:
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:54:33: error: variable or field ‘cuda_internal_error_throw’ declared void
 void cuda_internal_error_throw( cudaError e , const char * name, const char * file = NULL, const int line = 0 );
                                 ^~~~~~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:54:33: error: ‘cudaError’ was not declared in this scope
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:54:47: error: expected primary-expression before ‘const’
 void cuda_internal_error_throw( cudaError e , const char * name, const char * file = NULL, const int line = 0 );
                                               ^~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:54:66: error: expected primary-expression before ‘const’
 void cuda_internal_error_throw( cudaError e , const char * name, const char * file = NULL, const int line = 0 );
                                                                  ^~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:54:92: error: expected primary-expression before ‘const’
 void cuda_internal_error_throw( cudaError e , const char * name, const char * file = NULL, const int line = 0 );
                                                                                            ^~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:56:38: error: variable or field ‘cuda_internal_safe_call’ declared void
 inline void cuda_internal_safe_call( cudaError e , const char * name, const char * file = NULL, const int line = 0)
                                      ^~~~~~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:56:38: error: ‘cudaError’ was not declared in this scope
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:56:52: error: expected primary-expression before ‘const’
 inline void cuda_internal_safe_call( cudaError e , const char * name, const char * file = NULL, const int line = 0)
                                                    ^~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:56:71: error: expected primary-expression before ‘const’
 inline void cuda_internal_safe_call( cudaError e , const char * name, const char * file = NULL, const int line = 0)
                                                                       ^~~~~
/home/dog/kokkos/core/src/Cuda/Kokkos_Cuda_Error.hpp:56:97: error: expected primary-expression before ‘const’
 inline void cuda_internal_safe_call( cudaError e , const char * name, const char * file = NULL, const int line = 0)
                                                                                                 ^~~~~
/home/dog/kokkos/core/src/impl/Kokkos_Spinwait.cpp:157:2: error: expected ‘}’ at end of input
 }} // namespace Kokkos::Impl
  ^
/home/dog/kokkos/core/src/impl/Kokkos_Spinwait.cpp:157:2: error: expected ‘}’ at end of input
make[1]: *** [Kokkos_Spinwait.o] Error 1
make[1]: Leaving directory `/home/dog/kokkos-build/core'
make: *** [kokkoslib] Error 2

**Comment by crtrott** [comment]
Note the compiler for Kokkos to build CUDA is nvcc_wrapper or clang 4+ (for Volta only Clang6 works more or less, but only with CUDA 9.0 not 9.1, and there are some bugs, so for Volta its only nvcc_wrapper). If you have nvcc in your path then use --compiler=${KOKKOSPATH}/bin/nvcc_wrapper

**Comment by crtrott** [comment]
You can also use nvcc explicitly if you rewrite some of the Makefiles. You must for example add -x cu to the flags, as well as -Xcompiler etc. in the right places. That is what nvcc_wrapper does. It takes all the input arguments and sorts them into: this is something nvcc knows, this is something I need to prepend with -XCompiler or -XLinker and oh I also need to add the -x cu.

**Comment by dogunter** [comment]
I don't have access to cuda-9.0, so I'll make an admin request for it.  However, your suggestion of setting the compiler to point to kokkos/bin/nvcc_wrapper worked.

**Comment by crtrott** [comment]
Clang 6 for Volta is in any case still buggy. It doesn't pass the whole Kokkos unit test suite.
