### ISSUE TITLE
problem with nvcc_wrapper when using cygwin

### ISSUE THREAD

**Issue by AAUDI** [kokkos/kokkos#1452]
Hello, 
I try to use the nvcc_wrapper in Cygwin to compile an example : 

nvcc_wrapper toto.cpp -arch=sm_35
host_command=g++
nvcc_command=nvcc -arch=sm_35 -ccbin g++ -I/cygdrive/c/cuda_toolkit/v9.1/include/ -x cu toto.cpp

I have this error : 
g++: erreur : cuda_runtime.h: No such file or directory
g++: erreur : unrecognized command line option « -nologo »
g++: erreur : unrecognized command line option « -EHsc »
nvcc warning : nvcc support for Microsoft Visual Studio 2010 and earlier has been deprecated and is no longer being maintained
toto.cpp

"cuda_runtiom.h" exists in /cygdrive/c/cuda_toolkit/v9.1/include/

Do you have any idea about this issue?

**Comment by mhoemmen** [comment]
I'm not sure if Kokkos supports Cygwin.  Microsoft Visual Studio 2010 does not implement C++11 (or even C++98) correctly, so it likely will not work with Kokkos.  You may have better luck with much newer (at least 2015 R3) versions of MS Visual Studio, or with the Intel compiler.  (You can use the Intel compiler through Visual Studio.  It costs money for a commercial license.)

**Comment by AAUDI** [comment]
Thank you for your reply: 
I install the Visual Studio 2015 and Cuda 9.1, So I tried to compile the query device example exists in the example folder in kokkos : 

I still have approximally the same problem : 

../../bin/nvcc_wrapper -I./ -I../../core/src -I../../containers/src -I../../algorithms/src -I/usr/local/cuda-8.0/include  --std=c++11 -O3 -I/home/IS225481/kokkos/example/query_device/  -c query_device.cpp
host_command=g++ -I./ -I../../core/src -I../../containers/src -I../../algorithms/src -I/usr/local/cuda-8.0/include --std=c++11 -O3 -I/home/IS225481/kokkos/example/query_device/ -c
nvcc_command=nvcc -ccbin g++ -arch=sm_35 -I./ -I../../core/src -I../../containers/src -I../../algorithms/src -I/usr/local/cuda-8.0/include --std=c++11 -O3 -I/home/IS225481/kokkos/example/query_device/ -x cu query_device.cpp -c
g++: erreur : cuda_runtime.h: No such file or directory
g++: erreur : unrecognized command line option « -nologo »
g++: erreur : unrecognized command line option « -EHsc »
nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
query_device.cpp

I have the same problem when when I try: make KOKKOS_DEVICES=Cuda
But its works well when I try : make KOKKOS_DEVICES=OpenMP, 

Do you think that the problem comes from the Visual Studio Program while linking?

Thank you,

**Comment by crtrott** [comment]
Hi 

nvcc_wrapper probably doesn't support visual studio as the compiler. You could try adding -ccbin vs++ (or whatever the executable for visual studio is) to your command line arguments. But I am not sure that is going to go great. We may also need to update the Makefile.kokkos to recognize visual studio as the host compiler. We did use cygwin for just OpenMP on windows, and that should work. But Windows with CUDA, I am not sure anybody did that yet ... sorry.

**Comment by crtrott** [comment]
Closing the issue assuming it answered your question. If not feel free to reopen.
If you feel you really want this you can also reopen and tell us this should be a Feature Request, but no guarantee from us we could put it soon on our priority list.
