### ISSUE TITLE
Add RDC to promotion testing

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1469]

**Comment by ibaned** [comment]
Should be a new integration test that turns on RDC in Trilinos and also Tacho

**Comment by crtrott** [comment]
Hm ok do we have any build which gets reasonably far with RDC on in Trilinos?

**Comment by ibaned** [comment]
There are some fundamental issues with TriBITS and CMake allowing static libraries to be repeated on the link line. Its unlikely we'll get that repaired in all of Trilinos in the short term.

**Comment by ndellingwood** [comment]
Added rdc testing to 2.9 promotion, rdc scripts using configurations closely matching those of ATDM automated testing of Trilinos are available in kokkos/scripts/trilinos-integration directory.

**Comment by ndellingwood** [comment]
In master branch already, closing this issue.
