### ISSUE TITLE
Should Kokkos::View::~View() check for whether Kokkos has been finalized, and print a warning in that case?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1477]

**Comment by ibaned** [comment]
@mhoemmen yes, we are considering doing this (its already #1465 , so this is kindof a duplicate). Hopefully it won't be too expensive and the debugging benefit with outweight the small performance loss.

**Comment by mhoemmen** [comment]
Thanks @ibaned !  Is that actually a duplicate or would there be something else involved?  I'm mainly worried about allocations persisting after Kokkos::finalize, so it sounds like the same thing.

**Comment by ibaned** [comment]
yea I think its exactly the same. Basically, `Kokkos::View` is really semantically `std::shared_ptr<SharedAllocationRecord>`, so my suggestion is to only check `~SharedAllocationRecord`. I'll close this on the assumption of it being a duplicate, please comment if you see something missing.
