### ISSUE TITLE
Provide scope guard for initialize/finalize

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1479]
```cpp
namespace Kokkos {
struct Library {
  Library() { Kokkos::initialize(); }
  ~Library() { Kokkos::finalize(); }
};
}

int main() {
  Kokkos::Library lib;
  Kokkos::View<int*> a("a", 10);
  // "a" destructor gets called, then Kokkos::finalize gets called
}
```

**Comment by crtrott** [comment]
Do we really want this? Lets discuss at the meeting.

**Comment by crtrott** [comment]
Rename this thing to ScopeGuard, which makes it also more obvious that we can use this in nested scenarios (i.e. libraries within an application). A scope guard only finalizes if it did the actual initialization (i.e. nobody else had initialized Kokkos before its constructor is called).

**Comment by crtrott** [comment]
Must be not copyable.

**Comment by ibaned** [comment]
- [ ] If `Kokkos::is_initialized()` in the constructor, don't call `Kokkos::initialize` or `Kokkos::finalize`
 - [ ] Not copyable or assignable:
```cpp
ScopeGuard(ScopeGuard const&) = delete;
ScopeGuard& operator=(ScopeGuard const&) = delete;
```
 - [ ] Must have constructor overloads equivalent to `Kokkos::initialize` overloads

**Comment by mhoemmen** [comment]
@ibaned Now might be the time to consider `Kokkos::is_finalized` -- right now, users have no way to tell the difference between "`initialize` and `finalize` were called" and "neither `initialize` nor `finalize` were called."

**Comment by ibaned** [comment]
@mhoemmen I think our goal is to make it so there are only two states, meaning that the two states in your comment are one and the same, and people can re-initialize and re-finalize Kokkos. We're not quite there yet, but we'd rather not introduce an API that suggests we don't have this goal.

**Comment by mhoemmen** [comment]
@ibaned That could make sense if Kokkos did a "lazy finalize of the GPU" thing -- that is, if `Kokkos::finalize` didn't actually finalize specific APIs like CUDA, but just deferred finalizing them to an `atexit` hook.  That might get "interesting" for other APIs :-) .  Never mind then -- I just wanted to point this out.

**Comment by ibaned** [comment]
@mhoemmen I think @crtrott took out the call to `cudaDeviceReset`, I think in general we are going to say that Kokkos doesn't take "ownership" of things like CUDA, OpenMP, etc, at least not in a permanent way. The right and proper thing to do is for `finalize` to put everything back in roughly the state that `initialize` found it. Thats our goal and we're working towards it.

**Comment by crtrott** [comment]
Yeah this "we don't kill the runtime" was done last promotion see #1305

**Comment by dalabre** [comment]
@ibaned Is this close?
'''
namespace Kokkos {
/** \brief  ScopeGuard
 *  Some user scope issues have been identified with some Kokkos::finalize calls;
 *  ScopeGuard aims to correct these issues.
 *
 *  Two requirements for ScopeGuard: 
 *     if Kokkos::is_initialized() in the constructor, don't call Kokkos::initialize or Kokkos::finalize
 *     it is not copyable or assignable
 */
struct ScopeGuard {
  bool scopeguard_init;

  ScopeGuard() {
     if ( ! Kokkos::is_initialized() ) {
         Kokkos::initialize();
         scopeguard_init = true;
     }
     ScopeGuard const& = delete;
     operator=(ScopeGuard const&) = delete;
  }

  ~ScopeGuard() {
     if ( ! Kokkos::is_initialized() && scopeguard_init) {
         Kokkos::finalize();
     }
  }
};
} // namespace Kokkos
'''

**Comment by ndellingwood** [comment]
@dalabre 
Move the deleted copy and copy-assign operators outside of the constructor (if you haven't fixed this yet) and fix the syntax if not done yet. 
Also the constructor will need to take the same runtime arguments as the `Kokkos::initialize()` method and pass them to `Kokkos::initialize()`

**Comment by dalabre** [comment]
Pull Request #1590 submitted, and accepted.
