### ISSUE TITLE
LDFLAGS in core/unit_test/Makefile: potential "undefined reference" to pthread lib

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#148]
Hi,

I just wanted to mention that LDFLAGS should be at the end of build command line.

I noticed that when building the simple "serial" version; the build produces linker error with some pthread routines not found.

g++ -L/home/pkestene/install/kokkos/github/kokkos_develop/build_serial/core/unit_test -lpthread  TestSynchronic.o UnitTestMain.o gtest-all.o -lkokkos   -o KokkosCore_UnitTest_Synchronic
gtest-all.o: dans la fonction « testing::internal::UnitTestImpl::~UnitTestImpl() »:
gtest-all.cc:(.text+0xcf00): référence indéfinie vers « pthread_getspecific »
gtest-all.cc:(.text+0xcf19): référence indéfinie vers « pthread_key_delete »
...

best regards,
Pierre Kestener.

**Comment by crtrott** [comment]
Hi I am looking through old issues which kind of fell over board in the end year hectic. Is this working now for you? Or is it still broken?

**Comment by ibaned** [comment]
I'm having this same issue. Will try to open a PR in a bit.

**Comment by ibaned** [comment]
started PR #740 with fixes for this

**Comment by ibaned** [comment]
configuration to reproduce on Ubuntu machine:
```bash
#!/bin/bash -ex
$HOME/src/kokkos/generate_makefile.bash \
--kokkos-path=$HOME/src/kokkos \
--prefix=$HOME/install/gcc/kokkos \
--with-serial \
--arch=BDW \
--make-j=16 \
2>&1 | tee config_log
```
then `make build-test`
