### ISSUE TITLE
Get rid of deprecated functions inside Kokkos

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1484]
The `concurrency` function is deprecated in favor of `UniqueToken`, see https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_OpenMP.hpp#L179. However, `Kokkos_ExecPolicy.hpp` still uses the `concurrency` function here: https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_ExecPolicy.hpp#L209, which causes a compiler error when using `KOKKOS_OPTIONS ?= "disable_deprecated_code"`.

**Comment by stanmoore1** [comment]
Also, the `Serial` and `Cuda` backends haven't marked `concurrency` as deprecated, only `OpenMP`.

**Comment by crtrott** [comment]
Args, the bug in this case is that concurrency is labeled as deprecated in OpenMP.

**Comment by crtrott** [comment]
At least I am pretty sure that is what we decided right?

**Comment by ibaned** [comment]
@crtrott yes, @stanmoore1 and I looked at it and the comments indicate that the new right thing to do is use `UniqueToken::size()`. We just forgot to deprecate `concurrency` in other backends, and to test an OpenMP build with deprecated code off.

**Comment by ibaned** [comment]
This should be addressed by merged pull request #1553

**Comment by crtrott** [comment]
I am adding more now. Pthreads was not done yet, and there were a small number of other things left in examples.

**Comment by stanmoore1** [comment]
Works now, thanks
