### ISSUE TITLE
View initialization when class member 

### ISSUE THREAD

**Issue by shellshocked2003** [kokkos/kokkos#1486]
I'm experiencing a similar issue to #1254, but I can't seem to fix the issue with the advice given. 

I have a class that has three `Kokkos::View`s as class members (no nested `View`s):
```
typedef Kokkos::HostSpace MemorySpace;
typedef Kokkos::OpenMP AccExecSpace;
typedef Kokkos::OpenMP ExecutionSpace;

Kokkos::View<Kokkos::vector<double>***, MemorySpace> pdf_;
Kokkos::View<lbm::NodeStatus***, MemorySpace> node_status_;
Kokkos::View<Kokkos::vector<double>***, MemorySpace> node_solid_and_velocity_;
```
I'm compiling for OpenMP, but get the following runtime error:

> terminate called after throwing an instance of 'std::runtime_error'
> what():  Constructing View and initializing data with uninitialized execution space
> Traceback functionality not available

In the class constructor, I'm using the default constructor for the `View` members in the initializer list:
```
Lattice(...)
    : ...
      pdf_(),
      node_status_(),
      node_solid_and_velocity_(),
      ...
```
Then I resize and initialize them in a separate function:
```
  Kokkos::resize(pdf_, nodes_x_, nodes_y_, nodes_z_);
  Kokkos::resize(node_status_, nodes_x_, nodes_y_, nodes_z_);
  Kokkos::resize(node_solid_and_velocity_, nodes_x_, nodes_y_, nodes_z_);

  
  // Set initial node status to active fluid
  Kokkos::parallel_for("init_node_status",
                       Kokkos::RangePolicy<AccExecSpace>(0, nodes_x_ * nodes_y_ * nodes_z_),
                       KOKKOS_LAMBDA(const lbm::LatUint& index) {
                         const lbm::LatUint z_index = index / (nodes_x_ * nodes_y_);
                         const lbm::LatUint y_index = (index % (nodes_x_ * nodes_y_)) / nodes_x_;
                         const lbm::LatUint x_index = (index % (nodes_x_ * nodes_y_)) % nodes_x_;
                         node_status_(x_index, y_index, z_index) = lbm::NodeStatus::ACTIVE_FLUID;
                       });

  // Allocate memory for discrete velocities in pdf_
  Kokkos::parallel_for("init_pdfs",
		       Kokkos::RangePolicy<ExecutionSpace>(0, nodes_x_ * nodes_y_ * nodes_z_),
		       KOKKOS_LAMBDA(const lbm::LatUint& index) {
                         const lbm::LatUint z_index = index / (nodes_x_ * nodes_y_);
                         const lbm::LatUint y_index = (index % (nodes_x_ * nodes_y_)) / nodes_x_;
                         const lbm::LatUint x_index = (index % (nodes_x_ * nodes_y_)) % nodes_x_;
			 pdf_(x_index, y_index, z_index) = Kokkos::vector<double>(27, 0.0);
		       });
```

Based on my understanding, this should work--`Kokkos::OpenMP` execution space should have access to `Kokkos::HostSpace` memory space. Am I missing something obvious about why the execution space is uninitialized? Sorry to bother you with simple implementation questions...

**Comment by mhoemmen** [comment]
`Kokkos::resize` fills the Views (for first-touch allocation).  It uses the Views' default memory space to do that.  If `MemorySpace::execution_space` is not the same as `AccExecSpace` or `ExecutionSpace`, which is possible, you may have this problem.

**Comment by shellshocked2003** [comment]
Okay, I tried a few things based on this to see if the `MemorySpace::execution_space` and `AccExecSpace` or `ExecutionSpace` are not the same.

1.) Completely removed `Kokkos::resize` to avoid issues that may be caused due to memory and execution space incompatibility. Instead, just re-assign to member variables in initializer function: 
```
  pdf_ = Kokkos::View<Kokkos::vector<double>***, MemorySpace>("pdf", nodes_x_, nodes_y_, nodes_z_);
  node_status_ =
      Kokkos::View<lbm::NodeStatus***, MemorySpace>("node_status", nodes_x_, nodes_y_, nodes_z_);
  node_solid_and_velocity_ = Kokkos::View<Kokkos::vector<double>***, MemorySpace>(
      "solid_vel", nodes_x_, nodes_y_, nodes_z_);
```
2.) Updated parallel loops to use `RangePolicy<MemorySpace::execution_space>` to make sure compatible execution space is used

I'm still getting the same error when compiling for `OpenMP` (everything works fine when compiling for `Serial`).

**Comment by shellshocked2003** [comment]
I think I've located the source of this error--it looks like having a `Kokkos::View` with type `Kokkos::vector` causes the runtime error. The following code reproduces the error when the class member is `Kokkos::View<Kokkos::vector<double>***>`, but works fine when changing it to `Kokkos::View<double***>`:

Header file:
```
#include <Kokkos_Core.hpp>
#include <Kokkos_Vector.hpp>

class ViewClass {
 public:
  ViewClass(unsigned int x_nodes, unsigned int y_nodes, unsigned int z_nodes);

  void initialize();

 private:
  unsigned int x_nodes_;
  unsigned int y_nodes_;
  unsigned int z_nodes_;
  Kokkos::View<double***> test_view_;
};
```
Implementation file:
```
#include <Kokkos_Core.hpp>
#include <Kokkos_Vector.hpp>
#include "view_class.h"

ViewClass::ViewClass(unsigned int x_nodes, unsigned int y_nodes, unsigned int z_nodes)
  : x_nodes_{x_nodes},
    y_nodes_{y_nodes},
    z_nodes_{z_nodes},
    test_view_()
{}

void ViewClass::initialize() {
  Kokkos::resize(test_view_, x_nodes_, y_nodes_, z_nodes_);
}
```
I'm not sure what the root-cause is within `Kokkos::vector`, but don't get this when using other types that aren't built-in types (for example `Eigen::VectorXd` from [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page)).

**Comment by mhoemmen** [comment]
Before you create the Views (even creating them empty), check whether `MemorySpace::execution_space::is_initialized()` is `true`.

**Comment by shellshocked2003** [comment]
Just checked and `MemorySpace::execution_space::is_initialized()` is `true`; from what I can tell the issue is coming from `Kokkos::vector` being the type of `Kokkos::View`.

**Comment by mhoemmen** [comment]
> it looks like having a Kokkos::View with type Kokkos::vector causes the runtime error.

Oh oops, I missed that bit.  Yes, Views of Views, or Views of things containing Views, takes special treatment.  There is a standard idiom for this that involves placement new.

**Comment by crtrott** [comment]
Are you having somewhere a static instance of your class? `Kokkos::vector` is actually derived from `Kokkos::DualView` which has scalar `Kokkos::View`s in it which get constructed with the default constructor. This has two consequences: (i) you can't construct those guys inside of `parallel_for` and (ii) you cannot construct these things before calling `Kokkos::initialize` and not construct or destruct after `Kokkos::finalize`.

**Comment by shellshocked2003** [comment]
Ah, okay. Didn't realize that. I was just replacing all instances of `std::vector` with `Kokkos::vector`; should probably have looked into that more! Don't have any static instances of the class, but what's strange is that I get the same error with this simple program when compiling to target OpenMP:

```
#include "Kokkos_Core.hpp"
#include "Kokkos_Vector.hpp"

int main(int argc, char *argv[]) {
  Kokkos::initialize();
  Kokkos::View<Kokkos::vector<double>***>test_view("testing", 4, 4, 4);
  Kokkos::finalize();
    
  return 0;
}
```
Seems strange that it fails here, but I'm guessing there's some intricacies to `Kokkos::DualView` that I'm missing here?

**Comment by crtrott** [comment]
Can you scope guard the Kokkos::View. I.e. it should be deallocated before calling Kokkos::finalize. We are actually introducing a thing to allow you to do that in the future: #1479

**Comment by shellshocked2003** [comment]
I can't get it to work that way either--using `new` and `delete` explicitly doesn't seem to fix the issue. Tried creating the `View` in a function call as well to see that would fix it, but no luck.
```c++
int main(int argc, char *argv[]) {

  Kokkos::initialize();
  auto test_view = new Kokkos::View<Kokkos::vector<double>***>("testing", 4, 4, 4);
  delete test_view;  
  Kokkos::finalize();
    
  return 0;
}

```

**Comment by mhoemmen** [comment]
@shellshocked2003 Don't create the Kokkos::View at the same scope as Kokkos::finalize is called.  You want Kokkos::View's destructor to be called before Kokkos::finalize.  Try this:
```
Kokkos::initialize (argc, argv);
{
  Kokkos::View<...> myView (...);
} // View's destructor called at end of scope
Kokkos::finalize ();
```

**Comment by shellshocked2003** [comment]
I tried that as well as creating the `Kokkos::View` as a local variable within a function and get the same error. For now, it works for me to just switch out the type of the `Kokkos::View` to use a container other than `Kokkos::vector`. Everything works fine then. 
Appreciate the time you guys have taken to answer my questions; the work you are doing is fantastic. Will definitely try out the scope guard from #1479 when it gets implemented.

**Comment by mhoemmen** [comment]
@shellshocked2003 Thanks for trying!  The issue is that for a View of Views (or Kokkos::DualView or Kokkos::vector) you need to construct the inner objects explicitly using placement new, then destruct them explicitly before deallocating the outer View.
