### ISSUE TITLE
Built In Reducers (Build Error)

### ISSUE THREAD

**Issue by maguilo11** [kokkos/kokkos#1492]
Hello, I tried using the built in Kokkos reducers and I could not get my code to build. I included  Kokkos_Core.hpp, is there an additional header that needs to be included. The error message that I get is the following: namespace "Kokkos" has no member "Min".

Thank you for your help.

-------- Code Snapshot ---------

const OrdinalType tSize = aInput.size();
const ScalarType* tInputData = aInput.data();

ScalarType tOutput = std::numeric_limits<ScalarType>::max();
Kokkos::Min<ScalarType> tMinReducer(tOutput);
Kokkos::parallel_reduce("KokkosReductionOperations::min",
                                          Kokkos::RangePolicy<OrdinalType>(0, tSize),
                                          KOKKOS_LAMBDA(const OrdinalType & aIndex, ScalarType & aValue){
    tMinReducer.join(aValue, tInputData[aIndex]);
}, tMinReducer);

return (tOutput);

-------- Code Snapshot ---------

**Comment by crtrott** [comment]
Hi

is your error this:
```
main.cpp(15): error: namespace "Kokkos" has no member "Min"
```
That is because the reducers are still in the experimental namespace, since we wanted to gather feedback. But that will change in the next promotion or so. 

Here is some code which compiles for me:

```c++
#include<Kokkos_Core.hpp>
typedef int OrdinalType;
typedef double ScalarType;


int main(int argc, char* argv[]) {

  Kokkos::initialize(argc,argv);
  {
    Kokkos::View<double*> aInput("aINput",100);
    const OrdinalType tSize = aInput.size();
    const ScalarType* tInputData = aInput.data();

    ScalarType tOutput;
    Kokkos::Experimental::Min<double> tMinReducer(tOutput);
    Kokkos::parallel_reduce("KokkosReductionOperations::min",
        Kokkos::RangePolicy<>(0, tSize),
        KOKKOS_LAMBDA(const OrdinalType & aIndex, ScalarType & aValue){
      tMinReducer.join(aValue, tInputData[aIndex]);
    }, tMinReducer);

    printf("%lf\n",tOutput);
  }
  Kokkos::finalize();
}
```

**Comment by crtrott** [comment]
Couple of more comments: 
 * the reducers are templated on the Scalar type
 * you don't need to initialize the value: `parallel_reduce` will initialize with the neutral element
 * `RangePolicy` is templated, but you can let all of the parameters default.

**Comment by maguilo11** [comment]
Hello Christian,

Thank you for your prompt response. I was able to successfully follow your directions and compiled the my code (unit test is also working). Quick question, when do you expect the built in reducer to be part of main Kokkos namespace?    

Thank you,
Miguel

**Comment by ibaned** [comment]
@maguilo11 our next release is planned for mid-April

**Comment by maguilo11** [comment]
Thank you for the information. Looking forward to the release.
