### ISSUE TITLE
Move Reducers out of Experimental namespace

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1494]

**Comment by dalabre** [comment]
@ibaned This means removing them from  ```namespace Experimental {   .... }, thus leaving them in *mostly* namespace Kokkos ?

....and these are all the reducer functions: md_parallel_for(?), md_parallel_reduce, Sum, Prod, Min, ...etc?

**Comment by ibaned** [comment]
Yes. You can also add the following to help ease the transition on applications:
```cpp
namespace Experimental {
  using Kokkos::Min;
  ...
}
```
This allows `Kokkos::Experimental::Min` to still compile.

`md_parallel_for` and `md_parallel_reduce` are unrelated, in fact they should be removed, but thats @ndellingwood 's responsibility. The reducers are `Sum`, `Prod`, `Min`, etc.
