### ISSUE TITLE
Kokkos UnorderedMap doesn't support more than 2 billion entries?

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1495]
Is there a reason why Kokkos::UnorderedMap uses `uint32_t` everywhere and not `size_t` or `uint64_t`? I'm trying to use it for a very large system and it is failing. No warnings or errors, it just returns that the insertion failed.

**Comment by crtrott** [comment]
Hm assuming that means you also need 64 bit keys and values this would mean you exceed 64 GB for the map storage. Basically we thought nobody needs more than that within a single process ...
Are you running a single MPI rank per node to be able to do this kind of stuff?

**Comment by stanmoore1** [comment]
Yes, I misdiagnosed this. The total capacity exceeds 2 billion, but the hash is distributed across many thousand MPI ranks. But there seems to be a bug somewhere. The insertion is failing on a few MPI ranks out of thousands, even though the capacity isn't being exceeded as far as I can tell.

**Comment by stanmoore1** [comment]
Here is my use case: I'm literally copying every entry from a non-Kokkos unordered map into a Kokkos unordered map. The Kokkos map is sized based on the original hash. Yet it is failing.

**Comment by stanmoore1** [comment]
@crtrott who wrote the Kokkos::UnorderedMap implementation? I don't have a small reproducer, it only fails for thousands of nodes (of course...), so I'd like to get some debugging ideas from them.

**Comment by crtrott** [comment]
Dan Sunderland is the main author.

**Comment by stanmoore1** [comment]
OK, I manually increased the max insertion attempts limit from 32 to 1024 in Kokkos::UnorderedMap, and it is inserting successfully now. Is there any documentation on how to set a hint for the max?

**Comment by stanmoore1** [comment]
Or is that not user-settable?

**Comment by stanmoore1** [comment]
@dsunder

**Comment by stanmoore1** [comment]
Closing in favor of #1496.
