### ISSUE TITLE
Tuning for Kokkos::UnorderedMap?

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1496]
I'm running into the max insertion attempt limit in `Kokkos::UnorderedMap` for very large systems, which causes the insertion to fail. Can this limit or other parameters be set or tuned in `Kokkos::UnorderedMap`? @dsunder

**Comment by stanmoore1** [comment]
If I double the capacity of the map then insertion is successful.

**Comment by dsunder** [comment]
The problem seems to be that we use a bounded insert, so inserts could fail there is not space nearby even if there is still remaining capacity in the pool.  If you increase the capacity of the map to it should avoid this problem (assuming a well distributed hash).
