### ISSUE TITLE
Question about kokkos's random number generators in Kokkos_Random.hpp

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1498]
What's the current status of kokkos's random number generator? Can anyone provide some example of how to use it in CUDA? I'm hoping to use it for some Monte Carlo simulation.

**Comment by mhoemmen** [comment]
It works fine.  Here is an example (not a particularly good one, but it's what I have on hand) of code that is generic on the execution space:

https://github.com/trilinos/Trilinos/blob/a68547f3d80812559a2a5821b0fb714cbf5bc1ed/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp#L2602

In the following line, `thisView` is just a `Kokkos::View<impl_scalar_type**, device_type>`:

https://github.com/trilinos/Trilinos/blob/a68547f3d80812559a2a5821b0fb714cbf5bc1ed/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp#L2632

**Comment by stanmoore1** [comment]
Also see https://github.com/kokkos/kokkos/blob/master/example/tutorial/Algorithms/01_random_numbers/random_numbers.cpp. It works great in the LAMMPS and SPARTA codes.

**Comment by Char-Aznable** [comment]
Thank you guys! Those are very good examples!
Now I have another related question. I have a functor class sample a discrete distribution according to its member array ```probabilities_```, as illustrated in this pseudo code:
```
struct Sampler {
  std::vector<double> probabilities_; //this is the data to be used
  OtherDataType others_; //this helps with generating probabilities_
  void otherMethods() {}; //this helps with generating probabilities_
  Sampler() {
     //Generate probabilities_
     ...
  }
  template < class PRNG >
  unsigned int operator()(PRNG&& prng) const {
     //Sample according to probabilities_ using inverse-transform sampling
     ...
  }
};
```
but I only have the CPU implementation now because the generation of ```probabilities_``` is rather complicated. I'm thinking about porting this to CUDA using kokkos so that it behaves something like the ```template<class GeneratorPool> struct generate_random{};``` in the example of https://github.com/kokkos/kokkos/blob/master/example/tutorial/Algorithms/01_random_numbers/random_numbers.cpp. I only need the ```operator()``` to be run on the GPU. Here are the steps I'm thinking to take:
1) make ```probabilities_``` a kokkos::DualView<double*> and 
2) populate ```probabilities_``` on the host and copying it to the device 
3) decorate the ```operator()``` with ```KOKKOS_INLINE_FUNCTION``` and use it on the device
Is this a valid way of doing it? Do I need to port the ancillary member functions (```otherMethods()```) and member variables (```others_```) to GPU too? I'm totally new to CUDA and kokkos so I'd really appreciate your help here.

**Comment by crtrott** [comment]
Hi you only need to do something to the functions you actually want to use on the gpu, i.e. things which get called in the operator. That said you need to also touch the functions which use the data structures you change, but I guess that is relatively obvious.

**Comment by Char-Aznable** [comment]
@crtrott Thanks for your suggestion! I manage to come up with a minimal working example following tutorial/Advanced_Views/04_dualview/dual_view.cpp and tutorial/Algorithms/01_random_numbers/random_numbers.cpp and it gives the results I expect. However, there are a few things I don't quite understand:
1) Does Kokkos::DualView<>::sync() involve calling device function? If not, as in the following code, ```genProbabilities()``` is not marked ```KOKKOS_INLINE_FUNCTION``` but how can it do the sync?
2) Intuitively, wouldn't ```Kokkos::Random_XorShift64_Pool<>::get_state``` and ```Kokkos::Random_XorShift64_Pool<>::free_state``` modify ```*this``` object because a random number generation with propagate the state? I manage to set up a functor with a ```void operator()() const``` that call get_state and free_state.

Here is the code:
```
#include <Kokkos_Core.hpp>
#include <Kokkos_Random.hpp>
#include <Kokkos_DualView.hpp>
#include <iostream>
#include <vector>
#include <numeric>
#include <string>
#include <algorithm>

template < class Real, template<class ExecutionSpace> class GeneratorPool, 
           class ExecutionSpace = Kokkos::DefaultExecutionSpace>
struct Sampler {
  // If the functor has a public 'execution_space' typedef, that defines
  // the functor's execution space (where it runs in parallel).  This
  // overrides Kokkos' default execution space.
  typedef ExecutionSpace execution_space;
  using GeneratorPoolType = GeneratorPool<ExecutionSpace>;

  using DVType = Kokkos::DualView<Real*, ExecutionSpace>;
  using DVHistType = 
    Kokkos::DualView<unsigned long long*, ExecutionSpace, 
      Kokkos::MemoryTraits<Kokkos::Atomic>>;

  using HostMirrorSpace = typename DVType::host_mirror_space;
  using MemorySpace = typename DVType::memory_space;

  std::vector<Real> p_;
  DVType probs_;
  DVType cumProbs_;
  GeneratorPoolType rand_pool_;
  DVHistType hist_;

  Sampler(const std::vector<Real>& p, const GeneratorPoolType& rand_pool) 
    :p_(p)
    ,probs_("prob",p.size())
    ,cumProbs_("cumProb",p.size())
    ,rand_pool_(rand_pool)
    ,hist_("hist",p.size())
  {
    genProbabilities();
  } 

  //Populate the probs_, cumProbs_ and hist_ on the host
  void genProbabilities() {
    const Real total = std::accumulate(p_.begin(),p_.end(),Real(0.0));
    probs_.h_view(0) = p_[0] / total;
    cumProbs_.h_view(0) = probs_.h_view(0);
    hist_.h_view(0) = 0;
    for(int i = 1; i < p_.size(); ++i) {
      const Real pi = p_[i] / total;
      probs_.h_view(i) = pi;
      cumProbs_.h_view(i) = cumProbs_.h_view(i-1) + pi; 
      hist_.h_view(i) = 0;
    }
    probs_.template modify<HostMirrorSpace>();
    probs_.template sync<MemorySpace>();
    cumProbs_.template modify<HostMirrorSpace>();
    cumProbs_.template sync<MemorySpace>();
    hist_.template modify<HostMirrorSpace>();
    hist_.template sync<MemorySpace>();
    //Mark update on device's memory space that's going to 
    //happen in operator()
    hist_.template modify<MemorySpace>();
  }

  KOKKOS_INLINE_FUNCTION
  void operator() (int i) const {
    // Get a random number state from the pool for the active thread
    typename GeneratorPoolType::generator_type rand_gen = rand_pool_.get_state();

    // Draw samples numbers from the pool as Real between 0 and 1
    const Real u = rand_gen.drand();
    int n = 0;
    while( cumProbs_.d_view(n) < u && n < cumProbs_.d_view.extent(0)) { ++n; }

    // Do atomic addition
    hist_.d_view(n) += 1;

    // Give the state back, which will allow another thread to aquire it
    rand_pool_.free_state(rand_gen);
  }

};

template <class Tp> 
std::vector<Tp> split(const std::string& str) {
  std::vector<Tp> ans;
  std::istringstream iss(str);
  Tp val;
  while (iss >> val) {
    ans.emplace_back(val);
  }
  return ans;
}

int main(int argc, char* argv[])
{
  const std::string usage = "testrnd nSamples";
  if (uint(argc) != split<std::string>(usage).size()) {
    std::cerr << "Usage: " << usage << std::endl;
    exit(-1);
  }
  std::cout << "# " << usage << std::endl;;
  std::cout << "# ";
  std::for_each(argv, argv+argc, [] (char* arg) { std::cout << "'" << arg << "' "; });
  std::cout << std::endl;

  // Initialize Kokkos
  Kokkos::initialize(argc,argv);

  uint n = 1;
  const ulong nSamples = std::stoul(argv[n++]);

  //Initialize random number engine
  Kokkos::Random_XorShift64_Pool<> drand_pool64(5374857);
  Kokkos::Random_XorShift64_Pool<Kokkos::HostSpace::execution_space> hrand_pool64(5374857);

  //Initialize functor
  std::vector<double> p{0.1,0.2,0.3,0.4};
  std::cout << "# Sampling PDF: \n";
  std::cout.precision(8);
  std::cout.flags(std::ios::scientific | std::ios::right);
  std::cout << "# ";
  std::for_each(p.begin(), p.end(), 
    [](const double& sp) { std::cout.width(15); std::cout << sp << " "; });
  std::cout << "\n"; 

  //Sample the distribution from p on device
  using DeviceSampler = Sampler<double, Kokkos::Random_XorShift64_Pool>;
  DeviceSampler ds(p, drand_pool64);
  Kokkos::Timer timer;
  Kokkos::parallel_for(nSamples, ds);
  Kokkos::fence();
  const double dt = timer.seconds();
  //Check the histogram on the host
  ds.hist_.template sync<DeviceSampler::HostMirrorSpace>();
  std::vector<double> hist;
  for(int i = 0; i < ds.hist_.h_view.extent(0); ++i) {
    hist.emplace_back(double(ds.hist_.h_view(i)) / double(nSamples));
  }
  std::cout << "# Total time on device: " << dt << " sec\n";
  std::cout << "# Sampled histogram on device: \n";
  std::for_each(hist.begin(), hist.end(), [](const double& h) { std::cout.width(15); std::cout << h << " "; });
  std::cout << "\n"; 

  //Sample the distribution from p on host 
  using HostSampler = 
    Sampler<double, Kokkos::Random_XorShift64_Pool, Kokkos::HostSpace::execution_space>;
  HostSampler hs(p, hrand_pool64);
  timer.reset();
  Kokkos::parallel_for(nSamples, hs);
  Kokkos::fence();
  const double ht = timer.seconds();
  hs.hist_.template sync<HostSampler::HostMirrorSpace>();
  hist.clear();
  for(int i = 0; i < hs.hist_.h_view.extent(0); ++i) {
    hist.emplace_back(double(hs.hist_.h_view(i)) / double(nSamples));
  }
  std::cout << "# Total time on host: " << ht << " sec\n";
  std::cout << "# Sampled histogram on host: \n";
  std::for_each(hist.begin(), hist.end(), [](const double& h) { std::cout.width(15); std::cout << h << " "; });
  std::cout << "\n"; 
  
  Kokkos::finalize();
}

```

**Comment by mhoemmen** [comment]
> Does Kokkos::DualView<>::sync() involve calling device function?

`sync` must be called on host.  It may call cudaMemcpy and perhaps other CUDA run-time API functions.  As you can see here http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html , `cudaMemcpy` is a `__host__` function.
