### ISSUE TITLE
Does UniqueToken< Cuda, * > actually work?

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#1499]
I hate to ask what is likely a stupid question, but does UniqueToken< Cuda, * > (where * = Global or Instance) actually work?  I am trying to use it in an application (through ScatterView<>), and I am finding size() always returns 0.  Examining the source code here:

https://github.com/kokkos/kokkos/blob/develop/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp

I see
```
KOKKOS_INLINE_FUNCTION int32_t size() const noexcept { return m_count ; }
```
`m_count` is initialized in the constructor:
```
KOKKOS_INLINE_FUNCTION UniqueToken() : m_buffer(0), m_count(0) {}
```
but I don't see where `m_count` is ever set to anything else.  It is passed to concurrent_bitset::acquire_bounded() in acquire():
```
KOKKOS_INLINE_FUNCTION int32_t acquire() const
  {
    const Kokkos::pair<int,int> result =
      Kokkos::Impl::concurrent_bitset::
        acquire_bounded( m_buffer
                       , m_count
                       , Kokkos::Impl::clock_tic() % m_count
                       );
```
but that argument is passed by value:
```
KOKKOS_INLINE_FUNCTION static
  Kokkos::pair<int,int>
  acquire_bounded( uint32_t volatile * const buffer
                 , uint32_t const bit_bound
                 , uint32_t bit = 0                /* optional hint */
                 , uint32_t const state_header = 0 /* optional header */
                 ) noexcept
```
What am I missing?

**Comment by mhoemmen** [comment]
@tjfulle has some experience using this in Tpetra; it seemed to work just fine there, though perhaps it was passing tests despite not working ;-) .

**Comment by ibaned** [comment]
It seems like one has to use the constructor that takes an execution space instance in order for it to work correctly, even though it uses nothing from said instance:
```cpp
UniqueToken< Kokkos::Cuda , Kokkos::Experimental::UniqueTokenScope::Global >::
UniqueToken( Kokkos::Cuda const & )
  : m_buffer( Kokkos::Impl::CudaInternal::singleton().m_scratchConcurrentBitset )
  , m_count(  Kokkos::Impl::CudaInternal::singleton().m_maxConcurrency )
  {}
```

**Comment by etphipp** [comment]
Ah, OK.  See I knew it was a stupid question :)

**Comment by etphipp** [comment]
All of the other implementations of UniqueToken<> have a default constructor of the form
```
UniqueToken( execution_space const& = execution_space() )
```
except the Cuda one.  Is there a reason the Cuda one has a separate default constructor without an execution space argument (resulting in a UniqueToken that is basically useless)?

**Comment by etphipp** [comment]
Btw, the Cuda specialization is missing the definition of size_type to be consistent with all of the others, e.g.,
```
using size_type       = int32_t;
```

**Comment by ibaned** [comment]
@etphipp I think we can make both of those changes, they seem reasonable and what is there now is definitely confusing.

**Comment by ibaned** [comment]
@etphipp I just opened #1505 to make those improvements to the CUDA UniqueToken. Let me know if we can move to that one and close this one as a question about how to use whats there now.

**Comment by etphipp** [comment]
Yes, thank you.
