### ISSUE TITLE
Issue with HWLOC and Intel OpenMP

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#15]
That would address my issue, as it is basically the same thing that i am
doing when I call this which I stumbled across as I was hoping to figure
something out.

int omp_thread_count() {
       int n = 0;
       #pragma omp parallel reduction(+:n)
       n += 1;
       return n;
}

On 05/08/2015 09:51 AM, Hammond, Simon David (-EXP) wrote:
Matt,

I gave Christian the patch a few weeks ago. The trick is to do

int threads = 0;
#pragma omp parallel
{
#pragma omp atomic
threads++
}

Instead of omp_get_max_threads() in the Kokkos::initialize() routine.
There are some interesting but actually kind of smart/kind of stupid
reasons why the OpenMP runtime behaves in this way. Can you see if that
addresses your issue?

S.

**Comment by crtrott** [comment]
Nobody complained any more and to me it seems to work now. Closing now, if you encounter this again feel free to make a new ticket or reopen.
