### ISSUE TITLE
Harmonize Macro names

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#150]
We are currently using a mixture of 
KOKKOS_USE_....
KOKKOS_USING_....
KOKKOS_ENABLE_....
KOKKOS_HAVE_....

We should harmonize this. My current thinking is to harmonize around two variants:

KOKKOS_HAVE_ for capabilities which are available (such as KOKKOS_HAVE_OPENMP etc) 
and 
KOKKOS_ENABLE_[CATEGORY]_[FEATURE]
for features which are user defined settings to change behavior of Kokkos:

For example:
KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK
KOKKOS_ENABLE_CUDA_DEFAULT_UVM

Thoughts?

**Comment by mhoemmen** [comment]
I like that.  Trilinos could also use a similar refactoring of macros.

**Comment by gmackey** [comment]
The first step is to look over all code and do a survey of all the macro names and how they are used.

**Comment by hcedwar** [comment]
Keep Mark Hoemmen in the loop

**Comment by dsunder** [comment]
The following patterns have been used to harmonize the macros

KOKKOS_HAVE_DEBUG -> KOKKOS_DEBUG

KOKKOS_HAVE_XXX -> KOKKOS_ENABLE_XXX
KOKKOS_USE_XXX -> KOKKOS_ENABLE_XXX

all impl macros have been renamed to 
KOKKOS_XXX -> KOKKOS_IMPL_XXX

**Comment by mhoemmen** [comment]
don't forget to fix the CMake autogenerated header file :)
