### ISSUE TITLE
Can't include Kokkos built with Cuda relocatable device code

### ISSUE THREAD

**Issue by mfdeakin-sandia** [kokkos/kokkos#1500]
I get the following error if I try to include a version of Kokkos built with KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE.
```
/ascldap/users/mdeakin/white/kokkos-release/include/Cuda/Kokkos_CudaExec.hpp:120:62: error: storage size of ‘kokkos_impl_cuda_constant_memory_buffer’ isn’t known
 extern unsigned long kokkos_impl_cuda_constant_memory_buffer[] ;
```
This is with nvcc_wrapper, g++ 5.4, cuda 8.0.44

**Comment by crtrott** [comment]
Are you linking with nvccwrapper, and are you adding kokkos linkflags to your linkline? You could post your linkline here.

**Comment by mfdeakin-sandia** [comment]
I wasn't linking, I was just trying to compile. My minimal reproducer consists only of `#include <Kokkos_core.hpp>`
My compile command was `~/tpl-sources/kokkos/bin/nvcc_wrapper -std=c++11 -I${HOME}/white/kokkos-release/include -c test.cpp -o test.o`, where kokkos-release was where I installed it. I'll try this again and verify it still happens to me.

**Comment by mfdeakin-sandia** [comment]
I can confirm I'm still getting this error

**Comment by mfdeakin-sandia** [comment]
For completeness, here's my CMake command:
```
cmake -D CMAKE_CXX_COMPILER=${PWD}/../bin/nvcc_wrapper -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=${HOME}/white/kokkos-relocatable -D KOKKOS_ARCH="Power8;Pascal60" -D KOKKOS_ENABLE_DEBUG=OFF -D KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION=ON -D KOKKOS_ENABLE_CUDA=ON -D KOKKOS_CUDA_DIR=${CUDA_ROOT} -D LIB_cuda=${CUDA_ROOT}/cuda/8.0.44/targets/ppc64le-linux/lib/stubs/libcuda.so -D KOKKOS_ENABLE_CUDA_LAMBDA=ON -D KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON -D KOKKOS_ENABLE_PROFILING=OFF -D KOKKOS_ENABLE_SERIAL=OFF -D KOKKOS_ENABLE_DEPRECATED_CODE=OFF ..
```

**Comment by crtrott** [comment]
Sorry lost track of this thing. You are not actually adding all the flags to your compile line you need to add. Kokkos should have installed a file called:
kokkos_generated_settings.cmake
In that you find defines for stuff like KOKKOS_CXXFLAGS. And you need to add those to your build and link flags etc.

**Comment by mfdeakin-sandia** [comment]
Ah, CMake's assumption you're using CMake to configure strikes again!
Adding the ` --relocatable-device-code=true` flag did fix this issue, thanks
