### ISSUE TITLE
Cuda UniqueToken interface not consistent with other backends

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1505]
@etphipp wrote:

All of the other implementations of UniqueToken<> have a default constructor of the form
```
UniqueToken( execution_space const& = execution_space() )
```
except the Cuda one.  Is there a reason the Cuda one has a separate default constructor without an execution space argument (resulting in a UniqueToken that is basically useless)?

Btw, the Cuda specialization is missing the definition of size_type to be consistent with all of the others, e.g.,
```
using size_type       = int32_t;
```

**Comment by mhoemmen** [comment]
@tjfulle may be interested in this.

**Comment by ndellingwood** [comment]
It looks like `concurrency()` is to be deprecated in favor of `UniqueToken`, consistent default constructors will help with consistency and avoiding if-guards based on enabled backends when replacing `concurrency()` within Kokkos (and other codes).

**Comment by william76** [comment]
Ahhh, I got it working.  Using `unique_token_t( ExecutionSpace() )`
