### ISSUE TITLE
Intel 16 compile error

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1507]
A Jenkins error popped up in Melvin jobs. 

First issue: Unable to load sems-git: `11:10:24 ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'sems-git'`

This error has popped up in a couple Jenkins jobs today, this one specifically with intel/16.0.1 and debug enabled:
```
11:10:35 In file included from /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/Kokkos_Atomic.hpp(71),
11:10:35                  from /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/impl/Kokkos_Spinwait.cpp(47):
11:10:35 /home/jenkins/slave/workspace/kokkos_melvin_debug/kokkos/core/src/Kokkos_HostSpace.hpp(233): error #809: exception specification for virtual function "Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::~SharedAllocationRecord" is incompatible with that of overridden function "Kokkos::Impl::SharedAllocationRecord<void, void>::~SharedAllocationRecord"
11:10:35     ~SharedAllocationRecord();
```

Edit: Adding SHA for the build
`Repository Status:  2b1c8cfcb087532ca5c4619d59cddbb117345815 Merge pull request #1485 from swbova/checkViewConstructors`

**Comment by ndellingwood** [comment]
@ibaned could this be related to changes in PR #1483?

**Comment by ibaned** [comment]
@ndellingwood probably, I'll look into it

**Comment by ndellingwood** [comment]
@ibaned thanks and for adding labels, I didn't want to assign without digging a bit further.
