### ISSUE TITLE
HIP: list initializer doesn't work for host/device classes

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1515]
List initialization doesn't work if the class has a host/device function in it. 
Example code:
```c++
struct S {
  int x,y;
#ifdef ATTR
  __attribute__((amp,cpu)) inline
#endif
  int operator() () const {
    return x;
  }
};

int main(int argc, char* argv[]) {
  S s({0,0});
}
```

Working compile line:
```
clang++ main_simple.cpp  -mavx  -hc -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -lunwind -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -lhc_am -lm  --amdgpu-target=gfx803 --gcc-toolchain=/usr -I./
```

Non-Working compile line (just added a -DATTR):
```
clang++ main_simple.cpp  -mavx  -hc -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -lunwind -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -lhc_am -lm  --amdgpu-target=gfx803 --gcc-toolchain=/usr -I./ -DATTR
```

Error:
```
main_simple.cpp:12:5: error: no matching constructor for initialization of 'S'
  S s({0,0});
    ^ ~~~~~
main_simple.cpp:1:8: note: candidate constructor (the implicit copy constructor) not viable: cannot convert initializer list argument to 'const S'
struct S {
       ^
main_simple.cpp:1:8: note: candidate constructor (the implicit move constructor) not viable: cannot convert initializer list argument to 'S'
struct S {
       ^
main_simple.cpp:1:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
1 error generated.
```

**Comment by crtrott** [comment]
We added explicit constructors to work around this issue in Kokkos.

**Comment by chipfreitag** [comment]
We had developed a fix for this.  I was about to push, but I noticed that you have already pushed a very similar fix to develop.
The fix we applied in Kokkos_Array:

--- a/core/src/Kokkos_Array.hpp
+++ b/core/src/Kokkos_Array.hpp
@@ -105,6 +105,16 @@ public:
       return & m_internal_implementation_private_member_data[0];
     }

+#if defined(KOKKOS_ENABLE_ROCM)
+  KOKKOS_INLINE_FUNCTION
+  Array( std::initializer_list<T> const& list)
+    {
+      std::copy_n(list.begin(), list.size(), m_internal_implementation_private_member_data);
+    }
+
+  Array() = default ;
+#endif
+
I think this is close to the same thing you added.  
Do we need to close this issue, or are you leaving it open to drive the compiler fix?

**Comment by masterleinad** [comment]
```C++
#include <hip_runtime.h>

struct S {
  int x,y;
#ifdef ATTR
  __host__ __device__ inline
#endif
  int operator() () const {
    return x;
  }
};

int main(int argc, char* argv[]) {
  S s({0,0});
}
```
still doesn't work with `hipcc` version 3.0.

**Comment by arghdos** [comment]
@masterleinad -- just tested this with one of our internal HIP-Clang builds, and I can get it to compile w/ ATTR defined.

**Comment by ajpowelsnl** [comment]
Assumed this issue is fixed in compiler
