### ISSUE TITLE
[Question] range policy with device_type fails to deduce correct functor interface and returns ambiguous error message.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1517]
```
using node_type = typename tpetra_multivector_type::node_type;
using device_type = typename node_type::device_type; // e.g., Kokkos::Device<OpenMP,HostSpace>
Kokkos::RangePolicy<device_type> policy(0, 10);
Kokkos::parallel_for(policy, functor);
```
The above code returns the following error: 
```
/home/kyukim/Work/lib/trilinos/kyukim/packages/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:109:28: error: no match for call to  functor( t , iwork ); 
```
As I use tpetra node type and its associated device type, it is quite easy to use the device type in the policy template parameter (it should be execution space). However, when I do this mistake, the device template parameter is mistaken as a "tag" and returns functor interface mismatch. This error message does not seem to be correct and confuse users. 

Another solution is to put another template deduction step taking execution space from the device type. This also prevents such an error and it would simplify the interface when people use deduced device type from tpetra.

**Comment by crtrott** [comment]
Hm yeah, it would complicate things a bit though, basically we would need yet another meta class for argument deduction ...
