### ISSUE TITLE
Compiling with Clang 6.0 and CUDA 9.1

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#1518]
`Clang 6.0.0 for CUDA (CUDA Toolkit 9.1)` is listed in README, among primary tested compilers for X86. 

The LLVM docs note that CUDA 7.0, 7.5, or 8.0 is required to compile with Clang (http://releases.llvm.org/6.0.0/docs/CompileCudaWithLLVM.html), and the following error is thrown (as expected):
`clang-6.0: error: cannot find libdevice for sm_52. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.`

Clang 7 from SVN works fine, but how do you manage to compile with Clang 6 and CUDA 9?

**Comment by crtrott** [comment]
Args that is a typo. It is CUDA 9.0 (9.0.69 to be exact) which we use for the Clang 6. Clang 6 does not support CUDA 9.1 you are right. And its support for 9.0 is only semi official.
