### ISSUE TITLE
Fix View assignment (of managed to unmanaged)

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#153]
@crtrott 

Assignment of a managed View to an unmanaged View, not with CUDA, updates the unmanaged View's reference count.  This causes a thread scalability bottleneck that we observed with ~4 threads in Nalu.  Christian knows how to fix this already. 

This affects old View, not experimental, but preliminary tests with experimental suggests that it's broken there too.

**Comment by crtrott** [comment]
fixed it for the old view implementation. There are some questions how to do correctly for the new view implementation.

**Comment by crtrott** [comment]
Pushed to master

**Comment by mhoemmen** [comment]
Sweet, thanks Christian!!!

On 12/3/15, 11:22 AM, "Christian Trott" <notifications@github.com<mailto:notifications@github.com>> wrote:


Pushed to master

-

**Comment by hcedwar** [comment]
Also fixed and unit tested in Experimental::View, on the develop branch.

**Comment by crtrott** [comment]
Is now in master and in Trilinos.
