### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1533]
We have now Sandia internal customers in addition to external folks who want to run Kokkos based apps on Windows including GPU support. To make this work we need to do a couple things starting with buying a Windows Server with a GPU (preferably a TitanV). 

One big advantage is that this will remove an obstacle for commercial customers to use Kokkos.

**Comment by j8asic** [comment]
Does this mean compiling with Clang on Windows without Cygwin?

**Comment by ibaned** [comment]
@j8asic I'm not sure about Clang on Windows. Our initial target was MSVC 2017. If you can point us to a Clang workflow we may look into that as well.

**Comment by j8asic** [comment]
If you're going with MSVC, probably no need for a specific Clang workflow -- seems that `clang-cl` has matured, and is mostly compatible with MSVC's `cl.exe`. Good luck with adapting GNU makefiles.

**Comment by ibaned** [comment]
@j8asic yes, the build system will be tricky. I'm thinking of focusing on our CMake build system, although even that makes some use of the Makefile system...

**Comment by mhoemmen** [comment]
CMake is _supposed_ to be able to dump MS project files.  That was the whole justification for Trilinos adopting it circa 2009.  CMake dumps Ninja just fine (yay!) so I'm a bit hopeful perhaps?

**Comment by ibaned** [comment]
In particular, on Windows we'll just avoid calling our Makefile system to determine things like compiler flags, and instead just determine things like compilers flags with some pure-CMake logic that only covers the Windows case.

**Comment by crtrott** [comment]
We discussed this shortly today. The vast majority of all our Makefile logic is compiler and architecture detection and the combinatorial issues with all possible combinations. 

It looks to me like the non-cygwin (i.e. non-gnu-make compatible) ecosystem on Windows should be quite bit simpler. We don't have to deal necessarily with gcc, clang, pgi, cray, XL and intel, and we don't have to support ARM, Power, BGQ, Xeon Phi etc. 

We probably can get away initially with some simple logic and just assume we have an AVX compatible CPU and are using MSVC.

**Comment by ndellingwood** [comment]
Here is a helpful comment posted on Trilinos github.io site

https://github.com/trilinos/trilinos.github.io/issues/24#issue-559640535

@alessiocacciatori this is a good place for discussion regarding the fixes you've worked on for MSVC, thanks for posting!

Thanks @william76 for helping direct the comment this way!

**Comment by crtrott** [comment]
Here we go: we got Windows support with MSVC in develop! For now only the Serial backend is supported. CUDA comes next. Not sure yet about OpenMP since MSVC only promises OpenMP 2.0.

**Comment by alessiocacciatori** [comment]
Wonderful! Eager to try it! Thank you!

**Comment by j8asic** [comment]
I've tried to test compile with Clang 9, i.e. clang-cl, from VS and it almost goes through :)

1st problem is that Kokkos_Macros.hpp defines STACKTRACE and CXXABI, which I guess, are not available on Windows:
```
#if defined(KOKKOS_COMPILER_GNU) || defined(KOKKOS_COMPILER_CLANG) || \
    defined(KOKKOS_COMPILER_INTEL) || defined(KOKKOS_COMPILER_PGI)
#define KOKKOS_IMPL_ENABLE_STACKTRACE
#define KOKKOS_IMPL_ENABLE_CXXABI
#endif
```
```
impl\Kokkos_Stacktrace.cpp(6): fatal error : 'execinfo.h' file not found
impl\Kokkos_Stacktrace.cpp(9): fatal error : 'cxxabi.h' file not found
```

2nd problem arises in `atomic_compare_exchange` in Kokkos_Atomic_Windows.hpp:  
```
impl/Kokkos_Atomic_Windows.hpp(149): error : '_InterlockedCompareExchange128' needs target feature cx16
```
The solution was to add `-mcx16` compiler option to C++ command line options in the VS project properties.

**Comment by hph73** [comment]
Any progress on building Kokkos on windows? Is it available now?

**Comment by masterleinad** [comment]
> Any progress on building Kokkos on windows? Is it available now?

We have CI for Windows. Which backends are you interested in, though?

**Comment by hph73** [comment]
Hi, I am especially interested in GPU acceleration with Nvidia.

**Comment by masterleinad** [comment]
> Hi, I am especially interested in GPU acceleration with Nvidia.

This should in general work. Have a look at https://github.com/kokkos/kokkos/issues/3062, https://github.com/kokkos/kokkos/pull/3018, and https://github.com/kokkos/kokkos/pull/3345.
