### ISSUE TITLE
cudaErrorInvalidDeviceFunction in CudaGetOptBlockSize::get_block_size (anonymous namespace issue)

### ISSUE THREAD

**Issue by timrlaw** [kokkos/kokkos#1547]
Hi there,

I'm having trouble with the aforementioned occuring at [line 182 in Kokkos_Cuda_Internal.hpp](https://github.com/kokkos/kokkos/blob/e01945d0947f47e579468f325e4d97446453ad40/core/src/Cuda/Kokkos_Cuda_Internal.hpp#L182).

My application is structured as a static library of code, linked into an executable consisting solely of `main()`. I've reduced `main()` down to the following:

```
#include <Kokkos_Core.hpp>
#include "test.h"
int main(int argc, char *argv[]) {
    using namespace test;
    Kokkos::initialize(argc, argv);
    Kokkos::parallel_for(1, KOKKOS_LAMBDA (int const i) {});
    test();
    Kokkos::finalize();
    return 0;
}
```

`test()` is a function within the static library, defined as follows:

```
#include <Kokkos_Core.hpp>
// other code here, not called anywhere in this reduced verison
namespace test {
// other code here
void test() {
    Kokkos::parallel_for(1, KOKKOS_LAMBDA (int const i) {});
}
}
```

The first `parallel_for` works, the second produces the `cudaErrorInvalidDeviceFunction` (which manifests as a divide-by-zero [here](https://github.com/kokkos/kokkos/blob/e01945d0947f47e579468f325e4d97446453ad40/core/src/Cuda/Kokkos_Cuda_Parallel.hpp#L395)).

There are lots of other files in the static library, but if I remove them from the build the error goes away. If I put `test()` in its own file separate from the other code that it currently resides alongside, the error goes away. *Before I started removing code to produce this minimal broken example, there were many other instances of Kokkos parallel dispatch, all of which worked fine.* I'm baffled, and am struggling to debug the issue further as I'm no CUDA expert. As I understand it, this error shows up when the kernel isn't compiled for the right architecture, but it definitely is in this case (as other kernels defined in the same way work).

I'm developing this on an old Geforce GTX 670 (CC 3.0, perhaps an issue), using CUDA 8.0.44 and building with Clang 6.0. I've attached the top-level CMakeLists.txt.

Perhaps this is a longshot, but if anyone has any ideas I'd love to hear them!

Thanks,
Tim

[CMakeLists.txt](https://github.com/kokkos/kokkos/files/1891963/CMakeLists.txt)

**Comment by timrlaw** [comment]
Update:

I've narrowed this down to an issue with anonymous namespaces, minimal broken example [here](https://github.com/timrlaw/kokkos_namespace_err). In short, even defining a Kokkos lambda inside the anonymous namespace breaks the other ones in the file. This seems like a compiler bug to me. Has anyone else tried and succeeded/failed to use anonymous namespaces in this way?

**Comment by ibaned** [comment]
Is the compiler flag `--expt-extended-lambda` being used for all files in your build?

**Comment by crtrott** [comment]
I believe this is a known issue in the CUDA compiler. Can you try this with the clang compiler 4.0 or higher? 4.0 works with CUDA 8, 6.0 could use CUDA 9.0 but not 9.1. You then don't need to use nvcc_wrapper as compiler but simply clang++.

**Comment by timrlaw** [comment]
I'm using Clang 6.0 which doesn't recognise `--expt-extended-lambda`. Here's the invocations:

```
/home/timrlaw/bin/clang++  -D__STRICT_ANSI__ -I/home/timrlaw/repos/kokkostest/kokkos/core/src -I/home/timrlaw/repos/kokkostest/kokkos/containers/src -I/home/timrlaw/repos/kokkostest/kokkos/algorithms/src -I/home/timrlaw/repos/kokkostest/build/kokkos  --std=c++11 -x cuda -fopenmp=libomp --gcc-toolchain=/usr --cuda-gpu-arch=sm_30 -std=gnu++11 -o CMakeFiles/kokkostest.dir/other.cpp.o -c /home/timrlaw/repos/kokkostest/other.cpp
/home/timrlaw/bin/clang++  -D__STRICT_ANSI__ -I/home/timrlaw/repos/kokkostest/kokkos/core/src -I/home/timrlaw/repos/kokkostest/kokkos/containers/src -I/home/timrlaw/repos/kokkostest/kokkos/algorithms/src -I/home/timrlaw/repos/kokkostest/build/kokkos  --std=c++11 -x cuda -fopenmp=libomp --gcc-toolchain=/usr --cuda-gpu-arch=sm_30 -std=gnu++11 -o CMakeFiles/kokkostest.dir/kokkostest.cpp.o -c /home/timrlaw/repos/kokkostest/kokkostest.cpp
```

I can work around it by removing the anonymous namespaces, so it's not an immediate problem.

**Comment by ibaned** [comment]
Is `__STRICT_ANSI__` really needed? This [documentation](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html) makes it sound like that macro forces C++98 behavior.

**Comment by timrlaw** [comment]
If I don't supply `__STRICT_ANSI__` I get the following error:

```
In file included from /home/timrlaw/repos/kokkostest/kokkos/core/src/Kokkos_Core.hpp:50:
In file included from /home/timrlaw/repos/kokkostest/kokkos/core/src/Kokkos_Core_fwd.hpp:52:
In file included from /home/timrlaw/repos/kokkostest/kokkos/core/src/impl/Kokkos_Utilities.hpp:49:
/usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/type_traits:344:39: In file included from /home/timrlaw/repos/kokkostest/kokkostest.cpperror:: 1:
In file included from __float128/home/timrlaw/repos/kokkostest/kokkos/core/src/Kokkos_Core.hpp :is50 :
notIn file included from  /home/timrlaw/repos/kokkostest/kokkos/core/src/Kokkos_Core_fwd.hppsupported: 52on:
 In file included from this/home/timrlaw/repos/kokkostest/kokkos/core/src/impl/Kokkos_Utilities.hpp :target49:

/usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/type_traits:344:39: error: __float128 is not supported on this target    struct __is_floating_point_helper<__float128>

                                      ^
    struct __is_floating_point_helper<__float128>
```

I imagine this has more to do with Debian than Kokkos though.

**Comment by ibaned** [comment]
I'm having similar issues with Clang 6 and CUDA 9.1. I'm not sure what the cause is, but I'll investigate as time allows.

**Comment by mhoemmen** [comment]
@vbrunini found a similar issue.  Is this still a thing?

**Comment by ajpowelsnl** [comment]
Nov. 5, 2021 -- NVIDIA documented (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#extended-lambda-restrictions) that you cannot use Lambda in an anonymous namespace with Cuda.
