### ISSUE TITLE
Question: how to declare and initialize a scalar (zero-dimensional) DualView?

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1552]
As in the subject, I can't find this in the documentation. Can anyone provide an example? I know I can do DualView<int[1]> but that's kinda clumsy to be used as a scalar.

**Comment by ibaned** [comment]
@Char-Aznable does something go wrong if you just try `DualView<int>` ?

**Comment by stanmoore1** [comment]
Yes, use `DualView<int>` as @ibaned suggested, and remember that you still have to use `()` for accessing the value, even though the parentheses are empty.

**Comment by Char-Aznable** [comment]
@stanmoore1 I didn't know I can call ```()``` without argument. I guess it's something like this?
```
DualView<int> a("a");
a.h_view() = 1;
```
