### ISSUE TITLE
KOKKOS_ARCH HSW / assembler issues

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#1558]
On RHEL6 at least, the system assembler does not play well with the HSW avx flags, leading to an assembler error trying to build kokkos through Trilinos (on Kokkos_HostBarrier, iirc).  This can be worked around by setting KOKKOS_ARCH to SNB which uses a different avx flag set.

It would be nice if we caught "Assembler does not like your AVX flags" at configure time.

**Comment by nmhamster** [comment]
@csiefer2 - its virtually impossible to know for all inputs/outputs because different assembly is generated with different code. Thus, its possible the assembler would work in many cases. I realize this is frustrating.

**Comment by csiefer2** [comment]
Two ideas:

1) Test the assembler directly using known problematic code (rather than going through the compiler)?  I can redo the failing build and post the instructions the assembler woofed on.

2) Get the assembler version and then drop from HSW to SNB avx flags if we're using an assembler as old as the RHEL6 one (2.20.51.0.2-5.47.el6_9.1) or older.

Either of those sound tenable?

**Comment by nmhamster** [comment]
@csiefer2 - both sound possible.

**Comment by ibaned** [comment]
@csiefer2 I'm strongly inclined to say "don't have a terrible environment". If we want to attempt automatic detection of this terribleness, I suspect CMake is maaaybe the place to do it. Closing, please comment if we really should detect the terribleness ourselves.
