### ISSUE TITLE
Scan with Total: add support for providing Kokkos::View as return place

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1561]

**Comment by jeffmiles63** [comment]
Should this issue include changes to support and test Scan with Total using a Rank(1) view or is a Rank(0) view sufficient?

**Comment by ndellingwood** [comment]
@crtrott quick ping to confirm Jeff's question above.

**Comment by jeffmiles63** [comment]
@crtrott I forgot to mention, that this issue needs to unit test a change in the ROCm backend, can I will need a logon to the Fiji AMD system to do the unit test

**Comment by ajpowelsnl** [comment]
@ajpowelsnl, @crtrott , @dalg24  -- Add to Release 3.7, and assign to someone new in Wed. meeting
