### ISSUE TITLE
Guidance/documentation on multidimensional range policy

### ISSUE THREAD

**Issue by shellshocked2003** [kokkos/kokkos#1562]
I'm iterating over a three-dimensional Cartesian grid using `parallel_for` with functors and function name tags. Right now I only have the outer loop parallelized with a single dimension range policy, but would like to maximize parallelism within the two inner loops as well. 
Do you have any documentation or guidance on how best to specify a multidimensional `RangePolicy`? The loops are tightly nested, so it seems that this would be a better approach then trying to use `ThreadPolicy` with `TeamThreadRange` and `TeamVectorRange`?

**Comment by mhoemmen** [comment]
Do you mean MDRangePolicy, that already exists in Kokkos?

**Comment by mhoemmen** [comment]
https://github.com/kokkos/kokkos/blob/master/core/unit_test/TestMDRange.hpp shows unit tests for MDRangePolicy.

**Comment by mhoemmen** [comment]
Here is a tutorial example: https://github.com/kokkos/kokkos/blob/master/example/tutorial/06_simple_mdrangepolicy/simple_mdrangepolicy.cpp

**Comment by shellshocked2003** [comment]
Great, thanks. Exactly what I was looking for and probably should have found on my own...

Appreciate the help!

**Comment by mhoemmen** [comment]
@shellshocked2003 Gladly, no worries!
