### ISSUE TITLE
What does Kokkos::CudaUVMSpace::size_type ??

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1565]
I tried to assign as follows
```
typedef size_t size_type;
Teuchos::RCP<const tpetra_block_crs_matrix_type> A;
Kokkos::View<const size_type*> A_rowptr(A->getCrsGraph().getLocalGraph().row_map);
```
Then I see the following. How could I typedef size_type consistently ?

```
/home/kyukim/Work/lib/trilinos/kyukim/packages/kokkos/core/src/Kokkos_View.hpp(1851):
error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &)
[with
DataType=const size_t *, Properties=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>>,
RT=const Kokkos::CudaUVMSpace::size_type *, RP=<Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]"
```

**Comment by mhoemmen** [comment]
It's not `size_t`, it's `int`.  The `size_type` typedef may differ for different spaces.

**Comment by mhoemmen** [comment]
@kyungjoo-kim You can get the right type from the typedefs in `Tpetra::CrsGraph`.

**Comment by kyungjoo-kim** [comment]
@mhoemmen When I compile the code on host architecture, it is ``size_t`` (I have not experienced the similar problem). In Tpetra, we mostly define size_type with size_t. Why do we use different size type for CudaUVMSpace ?

**Comment by mhoemmen** [comment]
I'm not saying I _like_ it, just that I don't have evidence that it's safe to use a larger size type with Kokkos than what it claims to support on GPU.

**Comment by mhoemmen** [comment]
@crtrott wrote:
> It should usually be safe.

Hi Christian -- I don't mean to criticize Kokkos here.  Does "usually" mean "always"?

I would be happy to change Tpetra to use `int64_t` for row offsets, but that would break backwards compatibility.  I would be happy to add new functions for fixing that.

**Comment by crtrott** [comment]
"usually" is my way of hedging ;-). 
It is supposed to work, but I wouldn't bet my next biweekly salary check on it always doing so ...

**Comment by crtrott** [comment]
Also there are benefits to using 32bit int if you can performance wise. Sometimes quite a bit so.

**Comment by mhoemmen** [comment]
@crtrott ha! ;-P

It seems reasonable to me that different programming models might have different `size_type`.  Kokkos doesn't have control over the C++ Standard Library's `size_t`, so it has to set this `size_type` typedef instead.

**Comment by ibaned** [comment]
There was a lot of discussion a long time ago, so I assume this has been answered. please comment if not.
