### ISSUE TITLE
Feature request: make Kokkos pseudo random number generator compatible with std::*_distribution

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1574]
The idea is to be able to do the following:
```
Kokkos::Random_XorShift64<ExecutionSpace> engine;
std::uniform_int_distribution<> d;
auto iRandom = d(engine); 
```
or any other ```std::*_distribution```. 

One thing to note is that the ```std::*_distribution``` is that its ```::operator()(EngineType)``` is not declared ```const```, which can potentially have thread-safety issue. I believe that this is not a big issue for ```std::uniform_int_distribution<>::operator()``` because it's not actually mutating object but this is not true for ```std::normal_distribution<>```.

**Comment by ndellingwood** [comment]
Other Sandia groups, particularly involved in data analytics and ML will be interested in this as well.

**Comment by dhollman** [comment]
So it's not much trouble to make this work, but the biggest problem is that `uniform_int_distribution` and friends don't have `__device__` markings on their methods as implemented in the standard library, so you won't be able to use them in portable code.  You're also correct that `std::normal_distribution` is not guaranteed to be thread-safe (and indeed, it isn't; see [libcxx's implementation](https://github.com/llvm-mirror/libcxx/blob/master/include/random#L4336) for instance).

**Comment by Char-Aznable** [comment]
@dhollman Yeah, you are right about the std::*distribution. I think the big-picture idea is to separate the random number engine from sampling distributions. We can then add portable implementations for various distributions -- I can surely help with that because I have written some in my own projects. I'm not familiar enough with the Kokkos random number engine code to tell if the code factorization would be easy or not.
