### ISSUE TITLE
Question: How to disable warnings in the future

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1577]
I currently initialize Kokkos in the following way:

```c++
Kokkos::initialize(Kokkos::InitArguments(-1,-1,-1,true));
```

To obtain the defaults for threads, numa, etc, but still disable warning output. When I built kokkos with `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`, I obtain the following compile time error:

```
kokkos/core/src/impl/Kokkos_Core.cpp(100): error #140: too many arguments in function call
        Kokkos::OpenMP::initialize(num_threads,use_numa);
                                               ^

compilation aborted for /.../kokkos/core/src/impl/Kokkos_Core.cpp (code 2)
gmake[2]: *** [kokkos/CMakeFiles/kokkos.dir/core/src/impl/Kokkos_Core.cpp.o] Error 2
gmake[1]: *** [kokkos/CMakeFiles/kokkos.dir/all] Error 2
gmake: *** [all] Error 2
```

What is the recommended way to disable warnings and still obtain default performance parameters?

**Comment by crtrott** [comment]
Can you check again, I can't reproduce it on develop. But we just the last couple days fixed a few things with deprecated code off, and have now our nightly tests run with deprecated off and on.

**Comment by crtrott** [comment]
This code works for me:
```c++
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(Kokkos::InitArguments(-1,-1,-1,true));
  {
     int N = (argc>1) ? atoi(argv[1]) : 10000;
     int M = (argc>2) ? atoi(argv[2]) : 10000;
     int R = (argc>3) ? atoi(argv[3]) : 10;


  }
  Kokkos::finalize();
}
```

**Comment by dholladay00** [comment]
I am running master.

**Comment by crtrott** [comment]
Yeah I see the issue in master. We only did limited testing with deprecated code off at the last promotion so this slipped through. The next promotion probable like next week, is the official "Now you should start testing with deprecated code off" point. 

Your code as above is totally fine, and supposed to go on working.

**Comment by dholladay00** [comment]
Works for me. I’ll hold off on futher deprecated code testing until the next promotion. I’m ok with closing this issue.
