### ISSUE TITLE
Kokkos::StaticCrsGraph does not propagate memory traits (e.g., Unmanaged)

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1581]
@rppawlo has been working on a "View of StaticCrsGraph" pattern.  It's been crashing unexpectedly.  I investigated and noticed that `Kokkos::StaticCrsGraph` does not propagate memory traits (e.g., Unmanaged, which is what matters here) to its Views.  The `row_map_type`, `entries_type`, and `row_block_type` typedefs only use the layout and device type.

We could fix this by using the `traits` typedef in StaticCrsGraph.  The `traits` typedef takes into account the `Arg1Type` and `Arg2Type` template parameters of StaticCrsGraph.

**Comment by ndellingwood** [comment]
@mhoemmen An extra defaulted template parameter like `Arg3=void` may be necessary to inject and propogate MemoryTraits info into the `StaticCrsGraph`, it looks like `Arg1Type` is reserved for either a Device type or Layout type, and if a Layout type is given then `Arg2Type` is reserved for the Device type (if given). I can add this, is this trivial enough of a change to not effect compile times with an extra template parameter? Adding @crtrott

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Uhm, why do you need Unmanaged at compile time for this?

I think what's happening is that @rppawlo is doing something like this:
```
using local_matrix_type = KokkosSparse::CrsMatrix<double, int, inner_device_type, Kokkos::MemoryUnmanaged, size_type>;
Kokkos::View<local_matrix_type**, outer_device_type> localMatrices ("matrices", M, N);
// ...
for (int i = 0; i < M; ++i) {
  for (int j = 0; j < N; ++j) {
    new (localMatrices(i,j)) local_matrix_type (getTpetraGlobalMatrix(i,j)->getLocalMatrix ());
  }
}
```
This invokes the `KokkosSparse::CrsMatrix` copy constructor, but since `local_matrix_type` "loses" the unmanaged property, the result still has ownership.

**Comment by mhoemmen** [comment]
Roger could still work around by creating unowned Views manually, but the above behavior is surprising.

**Comment by rppawlo** [comment]
It also seems like quite a bit of extra work to do this. Mark's example is exactly what I am doing. Maybe I am wrong, but doesn't rebuilding the runtime unmanaged CrsMatrix require rebuilding all the views used in the graph, then rebuild the graph, then rebuild all views in the CrsMatrix to make sure everything is unmanaged? The code above jumps from a few lines to quite a lot.

**Comment by mhoemmen** [comment]
@rppawlo That's correct, the above example would expand quite a bit.  The sensible thing to do for now would be to write a "getUnmanagedLocalMatrix" function that encapsulates all that code.

**Comment by rppawlo** [comment]
Just to follow up, here's the difference in the code. If the unmanaged template parameter worked through all objects, the inner loop looks like this:

```
const auto crsMatrix = rcp_dynamic_cast<Tpetra::CrsMatrix<double,LO,GO,NodeT>>(thyraTpetraOperator->getTpetraOperator(),true);                                                                                                                         
new (&hostJacTpetraBlocks(row,col)) KokkosSparse::CrsMatrix<double,LO,PHX::Device,Kokkos::MemoryTraits<Kokkos::Unmanaged>> (crsMatrix->getLocalMatrix());                                                                                              
```

Instead, with the runtime interface the inner loop looks like:

```
// Grab the local managed matrix and graph                                                                                                                                                                                                              
const auto tpetraCrsMatrix = rcp_dynamic_cast<Tpetra::CrsMatrix<double,LO,GO,NodeT>>(thyraTpetraOperator->getTpetraOperator(),true);
const auto managedMatrix = tpetraCrsMatrix->getLocalMatrix();
const auto managedGraph = managedMatrix.graph;

// Create runtime unmanaged versions                                                                                                                                                                                                                    
using StaticCrsGraphType = typename LocalMatrixType::StaticCrsGraphType;
StaticCrsGraphType unmanagedGraph;
unmanagedGraph.entries = typename StaticCrsGraphType::entries_type(managedGraph.entries.data(),managedGraph.entries.extent(0));
unmanagedGraph.row_map = typename StaticCrsGraphType::row_map_type(managedGraph.row_map.data(),managedGraph.row_map.extent(0));
unmanagedGraph.row_block_offsets = typename StaticCrsGraphType::row_block_type(managedGraph.row_block_offsets.data(),managedGraph.row_block_offsets.extent(0));

typename LocalMatrixType::values_type unmanagedValues(managedMatrix.values.data(),managedMatrix.values.extent(0));
LocalMatrixType unmanagedMatrix(managedMatrix.values.label(), managedMatrix.numCols(), unmanagedValues, unmanagedGraph);
new (&hostJacTpetraBlocks(row,col)) LocalMatrixType(unmanagedMatrix);
```

**Comment by crtrott** [comment]
I see. Nathan if you want to take this, give it a shot. It shouldn't be all that hard (I hope ;-) ).

**Comment by ndellingwood** [comment]
I'll work on it, the KokkosKernels changes will need to be synced/follow the Kokkos changes though. It looks like the the `StaticCrsGraph` needs an extra template parameter for the memory traits, then the `KokkosSparse::CrsMatrix` can pass the info along properly.

**Comment by rppawlo** [comment]
The use case above didn't work on cuda. Had to go through and mark a bunch of functions in the CrsMatrix and CrsGraph and sub-structs with KOKKOS_INLINE_FUNCTION. 

PRs for kokkos:

https://github.com/kokkos/kokkos/pull/1587

PR for kokkos-kernels:

https://github.com/kokkos/kokkos-kernels/pull/220

The kokkos-kernels PR will probably require the kokkos PR to be accepted first. If these are both accepted in the kokkos repos, can I push the corresponding changes to the current Trilinos snapshot?

**Comment by ndellingwood** [comment]
I put in PR #1587 with first go at adding support for unmanaged memory traits, KokkosKernels CrsMatrix and BlockCrsMatrix changes will follow once this issue is resolved. 
@rppawlo, @mhoemmen can you take a look and see if this is on track for what you need?

**Comment by mhoemmen** [comment]
@ndellingwood I reviewed #1595.  Short answer: this will break backwards compatibility; I'm OK with that, but if it's a problem, we could use a variadic type alias (see review for details).

**Comment by rppawlo** [comment]
Thanks @ndellingwood ! I will change over on the next snapshot into Trilinos.
