### ISSUE TITLE
question regarding to team barrier 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1596]
@crtrott 

I am wondering if the following code is dead lock or not. 

```
TeamPolicy<Cuda> policy(league_size, AUTO, 2);

operator(const member_type &member) {
  Kokkos::parallel_for(Kokkos::TeamThreadRange(member, 10), [&](int i) {
    Kokkos::parallel_for(Kokkos::ThreadVectorRange(member, 3), [&](int j) {
      // do something
      member.team_barrier();
    }
  }
}
```

Let's say 2 vector threads are active and it is called inside of ``parallel_for(ThreadVectorRange(3))``. In the first iteration, 2 vector threads would call the team barrier. In the second iteration, 1 vector thread will be masked out and the thread does not call the team_barrier. Then, is the barrier still okay without causing a deadlock ?

**Comment by dsunder** [comment]
It depends.  If the vector range is guaranteed to be the same for all members of the team it should work and shouldn't deadlock.  However, it WILL deadlock if the team_barrier is not called the same number of times by all threads in the team.  

Conceptually, the team_barrier is very similar to an atomic counter that starts at zero and is incremented by each thread when it calls team_barrier and blocks (spins) until the value of the counter equals the number of threads in the team.

**Comment by dsunder** [comment]
Though you probably want to put the barrier call inside a `Kokkos::single( Kokkos::PerThread(team), ...)` block

**Comment by crtrott** [comment]
This is more likely than not a deadlock. Actually this is already a potential deadlock:
```c++
TeamPolicy<Cuda> policy(league_size, AUTO, 2);

operator(const member_type &member) {
  Kokkos::parallel_for(Kokkos::TeamThreadRange(member, 10), [&](int i) {
      // do something
      member.team_barrier();
  }
}
```

If for example you run this on KNL with topology recognition (i.e. hwloc) the auto team size will be 4 and it will deadlock, because 2 of the teams threads will do 3 iterations while the other 2 will only 2. 

So no this is not safe in the same way that this is not safe:

```
#pragma omp parallel 
{
  #pragma omp for
  for(int i=0; i<N; i++) {
    #pragma omp barrier
  }
}
```

**Comment by kyungjoo-kim** [comment]
@dsunder @crtrott Thanks. I do not use barrier on host architecture but on cuda. Thus, as long as I make sure every threads calls the barrier, it is safe. Do we have an access querying functions the team/vector size in the team policy (not from the member).
