### ISSUE TITLE
parallel_scan init value

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#1600]
From @bartgol 
    So, we were having a problem in Hommexx, where parallel_scan was not
    bif-for-bit on GPU with F90, and the core problem is that we cannot
    init the accummulation variable to a given value.
    
    In short:
    
    - F90 does:  result_N = (...(init_val+v_0) + v_1) + v_2) + .... ) + v_N
    - Kokkos can only do result_N = init_val + sum(v_0,...,v_N)
    
    It seems to me that the solution should be easy to implement: add an
    additional argument to parallel_scan, like
    
    parallel_scan(..., value_type init_val = 0);
    
    So that other codes are not broken, but now one can init the
    accummulation to init_val.
    
    If this is not yet under development, I can add an issue in kokkos..
    
    Thanks!

**Comment by dsunder** [comment]
The 'init' value for scan and reduce **must** be the identity value for the operation, since it can/will be applied multiple times.  However, you can easily achieve the result you want with the current scan interface

```c++
value_type offset;
View<value_type*> results;
...
KOKKOS_LAMBDA( int i, value_type & update, bool final_pass ) {
  update += ...
  if( final ) {
    results[i] = update + offset;
  } 
}
```

**Comment by bartgol** [comment]
Thanks @dsunder !

I now realize that this solution would not be viable to us for another set of reasons, but it is in general the right way to achieve the result.

I think this can be closed.
