### ISSUE TITLE
Add KOKKOS_ENABLE_CXX14 and KOKKOS_ENABLE_CXX17

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1602]

**Comment by crtrott** [comment]
Doing that in pull request #1677 
Adds: c++1y, c++14, c++17, c++2a

**Comment by j8asic** [comment]
The options rely on `CMAKE_CXX_STANDARD`, and some CMake GUIs don't add the option by default. In such cases, modifying `KOKKOS_CXX_STANDARD` doesn't result in changing the C++ standard, i.e. `c++11` value stays unmodified.
