### ISSUE TITLE
App Info Request from Users

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1604]
We are trying to put together a list of Kokkos usage in applications, libraries and maybe training with some basic information. We are planning to have both a non-public list and a public list (which ideally would be identical). Besides helping us to justify our existence we also would like to use it to point prospective users to other Kokkos users who might have already done something similar.

If you are willing to provide some information you can post that either here or send an email to me directly at crtrott@sandia.gov. 

The information we like to get would be this:

Project Name: Name of the application or library etc.
Area: What type of code is this (e.g. PIC in Plasma Physics, High Mach CFD)
Institution: Who works on this / owns the code.
Website: app website if one exists
Status: Production; Porting; Evaluation; Training/Education (see below)
Uses KokkosKernels: Does it make direct or indirect use of KokkosKernels
Contact Name:
Contact Email:
Can we make non-contact info public: (i.e. can we put the above info minus contact information on a public wiki)
Can we make contact info public: (i.e. can we put the contact name and maybe email on a public wiki)

Status:
 * Production (i.e. runs science/engineering problems)
 * Porting (app decided to use Kokkos and is working on porting, but not yet ready for actual runs)
 * Evaluation (looking at using Kokkos but no firm decision to do so)
 * Training/Education (for example Kokkos use in University classes for parallel programming)

Thanks for your help
Christian

**Comment by crtrott** [comment]
Template table entry:
```
 | AppName | Area | Institution | Website | Status | Uses KokkosKernels | Contact Name | Contact Email | Can we make non-contact info public | Can we make contact info public |
|---|---|---|---|---|---|---|---|---|---|
```

**Comment by grahamlopez** [comment]
There are several at ORNL, but they will be present at the training in July. Is it acceptable to wait and collect it then in person rather than try to chase emails for a few weeks, or do you need it sooner?

**Comment by ibaned** [comment]
@grahamlopez could you post here the results of your survey?

**Comment by grahamlopez** [comment]
Here is a CSV (but github will only let me attach it with a .txt extension)
[Kokkos Application Survey (Responses) - Form Responses 1.txt](https://github.com/kokkos/kokkos/files/2266824/Kokkos.Application.Survey.Responses.-.Form.Responses.1.txt)

**Comment by grahamlopez** [comment]
I will email it, since it has email addresses, etc.

**Comment by ibaned** [comment]
List of applications at the July tutorial who agreed to be listed:
 - [MPACT](https://ornl.gov/division/rnsd/projects/mpact)
 - [DTK](https://github.com/ORNL-CEES/DataTransferKit)
 - [NUFEB](https://github.com/nufeb/NUFEB)
 - Grit @ Oak Ridge
 - SGBench @ Georgia Tech
 - [LSMS](https://www.olcf.ornl.gov/tag/lsms/)
