### ISSUE TITLE
Include non-CUDA Kokkos headers in CUDA build of app

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#1607]
The bug refers to this issue https://github.com/dealii/dealii/issues/6423 The bug happens when Trilinos is built with kokkos but without cuda and then `sacado.hpp` is included in a file that is compiled by nvcc. The problem is that in kokkos/core/src/impl/Kokkos_Error.hpp, `Cuda/Kokkos_Cuda_abort.hpp` is guarded by `KOKKOS_ENABLE_CUDA` (see [here](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Error.hpp#L51)) but the call to `Kokkos::Impl::cuda_abort(message)` is guarded by `__CUDA_ARCH__` (see [here](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Error.hpp#L76)). Because of that the include is missing when the file is compiled by nvcc and Kokkos was compiled without CUDA support. You should use the same macro in both places.

**Comment by davydden** [comment]
> Is there a good reason why deal.II doesn't just require the Kokkos CUDA backend be enabled in Trilinos?

We don’t currently use Tpetra or Kokkos, so there is no requirement on this part of Trilinos.

**Comment by davydden** [comment]
>  its a matter of ensuring that enabling Tpetra/Kokkos doesn't break the usage of Sacado in deal.II

correct.

**Comment by ibaned** [comment]
I've fixed the original issue pointed out in dealii/dealii#6423, but as expected there are other issues. One of them has to do with our atomic functions, which are currently being refactored by @dsunder. I'll work with him to see if we can resolve that for your scenario.

**Comment by davydden** [comment]
>  I'll work with him to see if we can resolve that for your scenario.

thank you !

**Comment by ajpowelsnl** [comment]
@Rombur -- do you think this Enhancement is still worthwhile?
