### ISSUE TITLE
Bug: use of ballot on Volta

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1612]
Atomic operations on arbitrarily large scalar types can deadlock on Volta if called inside a branching parallel reduce kernel ...

This is caused by use of __ballot(0xFFFFFFF,val) inside the atomic function.

**Comment by mhoemmen** [comment]
@crtrott Is this why `complex<double>` `sumInto` was broken?

**Comment by crtrott** [comment]
Yes that is the reason.

**Comment by mhoemmen** [comment]
Thanks @crtrott ! :D
