### ISSUE TITLE
architecture macro flag. 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1614]
KokkosKernels, issue 231 (how to cross reference it ?), is machine and compiler specific. As kokkos and each compiler provides its identification macro, we can disable the compiler. However, if we know architecture in the macro, we can surgically limit the fix for only Sandybridge. 

As now Kokkos have "--arch" flags, it would be better to provide such information of machine configuration to a macro in kokkos. 

@nmhamster @crtrott @ndellingwood

**Comment by ibaned** [comment]
@kyungjoo-kim The cross-reference is done like this:
```
kokkos/kokkos-kernels#231
```
kokkos/kokkos-kernels#231

**Comment by crtrott** [comment]
Hi Kyungjoo that exists already. Check for stuff like 
`KOKKOS_ARCH_AVX` 
`KOKKOS_ARCH_AVX2`
`KOKKOS_ARCH_AVX512XEON`
`KOKKOS_ARCH_AVX512MIC`
