### ISSUE TITLE
Overhead on parallel launch with big member vector

### ISSUE THREAD

**Issue by ArVictor** [kokkos/kokkos#1615]
I ran into this issue that if I call a parallel_for on a class operator and this class contains a big vector (7*10^7 elements), there is a 0.5-1 second overhead at the beginning of the computation.

In the original code, I work with Views. But just having this vector as a member of my class causes the over.

Would you have an explanation ? Any solution to solve this ?

Here is a reproducer. Try commenting out the vector initialization in the constructor to remove the overhead.

```C++
#include <Kokkos_Core.hpp>

typedef Kokkos::DefaultExecutionSpace   ExecSpace;

class hamiltonian_splitting {
  public :
  std::vector<double> particle_array;
  hamiltonian_splitting() {
    this->particle_array = std::vector<double>(70000000);
  }

  KOKKOS_INLINE_FUNCTION
  void operator() (const Kokkos::TeamPolicy<>::member_type &) const{}
};

int main( int argc, char* argv[] )
{
  Kokkos::initialize( argc, argv );
  auto policy = Kokkos::TeamPolicy<ExecSpace>(1, 1);

  hamiltonian_splitting hamiltonian;
  Kokkos::Timer timer;
  timer.reset();

  Kokkos::parallel_for(policy, hamiltonian);
  Kokkos::parallel_for(policy, hamiltonian);

  auto elapsed_secs = timer.seconds();
  std::cout << "Elapsed time " << elapsed_secs << " seconds" << std::endl;

  Kokkos::finalize();
  return 0;
}
```
Thanks.

**Comment by ibaned** [comment]
Your class will get copied when it is used in `parallel_for`. That means the big vector is being fully copied, which explains the slowdown. This will be even worse if you try to use GPUs, because then the vector won't even be able to copy onto the GPU. Changing that vector a View should remove the overhead, because View behaves more like `std::shared_ptr<std::vector<double>>`, and using that would also remove the overhead.

**Comment by ArVictor** [comment]
Thanks ! That answers my question.
There is no overhead with a shared_ptr indeed.

**Comment by mhoemmen** [comment]
@ArVictor Just use a Kokkos::View!  It works great!

**Comment by ArVictor** [comment]
@mhoemmen I am using Views too. But I started with vectors (serial/OpenMP implementation) and wanted to keep them to do a performance test.
