### ISSUE TITLE
Replacement for deprecated APIs

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1621]
Hi,

I have a quick question on Kokkos::View.  I found the latest version no longer support the following methods.  Could you tell me the new methods for them?
(1) ptr_on_device()
(2) dimension_0() , dimension_1()....

**Comment by ndellingwood** [comment]
Replace `ptr_on_device()` with `data()`
Replace `dimension_0()` with `extent(0)` etc.

**Comment by mhoemmen** [comment]
Kokkos has an option you can set that enables deprecated things like these.  Search for `DEPRECATED`.

**Comment by crtrott** [comment]
We will pin up a wiki page with deprecated code and the replacements next week. Besides the ones Nathan already mentioned one major change is that all the KOKKOS_HAVE macros are replaced by KOKKOS_ENABLE ones. For the vast majority of the Macros this is all done by literal replacements of those strings. There are a very few there this is not true. Most notably KOKKOS_HAVE_PTHREAD becomes KOKKOS_ENABLE_THREADS. The kokkos-promotion branch in Trilinos is where we work on doing all of that.

**Comment by crtrott** [comment]
Another big change is that View::operator() doesn't allow you to provide more indicies than the rank is anymore. If you relied on that behavior (as for example Intrepid2 does) you need to use the .access function.

**Comment by crtrott** [comment]
Also a lot of the special ExecutionSpace::... functions are gone or renamied to impl_...
For example max_hardware_threads or is_initialized.

**Comment by crtrott** [comment]
https://github.com/kokkos/kokkos/wiki/DeprecationPage

**Comment by ibaned** [comment]
I'm going to assume this was resolved, please comment if otherwise.
