### ISSUE TITLE
CUDA atomic_fetch_sub for doubles is hitting CAS instead of intrinsic

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1624]
This manifested in LAMMPS and ExaMiniMD where atomic_fetch_sub was exercised via the -= operator of an atomic view.

**Comment by mhoemmen** [comment]
woah

**Comment by stanmoore1** [comment]
This caused a huge performance regression in LAMMPS.

**Comment by stanmoore1** [comment]
I confirm that #1624 fixes the performance regression in LAMMPS. Thanks.
