### ISSUE TITLE
Loosen dyn_rank check during View construction for non-void specialized types

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1625]
The current check for `dyn_rank == num_passed_args` in `runtime_check_rank_*` (when deprecated code is disabled) causes runtime failures in Sacado View's of DFad type. In these cases, an additional arg can be passed to the constructor for the runtime Fad dimension. 
Spoke to @crtrott, he suggested loosening this check when the `traits::specialized` type is non-void. 
To fix, I'll modify the `runtime_check_rank_*` routines to take an extra boolean argument which will be passed in to each call as `std::is_same<typename traits::specialize,void>::value` and will disable test for `dyn_rank == num_passed_args` for non-void specialization.

**Comment by stanmoore1** [comment]
I confirm that #1624 fixes the performance regression in LAMMPS. Thanks.
