### ISSUE TITLE
Question: Kokkos::deep_copy of Kokkos::DualView

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1630]
I'm looking at the specialization of Kokkos::deep_copy for Kokkos::DualView:
```
template< class DT , class DL , class DD , class DM ,
          class ST , class SL , class SD , class SM >
void
deep_copy (DualView<DT,DL,DD,DM> dst, // trust me, this must not be a reference
           const DualView<ST,SL,SD,SM>& src )
{
  if (src.modified_device () >= src.modified_host ()) {
    deep_copy (dst.d_view, src.d_view);
    dst.template modify<typename DualView<DT,DL,DD,DM>::device_type> ();
  } else {
    deep_copy (dst.h_view, src.h_view);
    dst.template modify<typename DualView<DT,DL,DD,DM>::host_mirror_space> ();
  }
}
```
If my guess is right, deep copying DualView only copy the device view when neither the source device or host view is marked modified. This seems a bit counter-intuitive because one would manually perform deep_copy on the member d_view if that's what needs to be done. Why not perform deep_copy on both host and device view unconditionally?

**Comment by crtrott** [comment]
because in the else branch the device data is stale. Actually it should probably be a triple thing.
==
>
<
