### ISSUE TITLE
Over-fencing in profiling system

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1631]
Currently, both the "begin" and "end" APIs in the Kokkos profiling interface will call `Kokkos::fence()`. For a program running with `CUDA_LAUCH_BLOCKING=1` in the environment, that means that a Kokkos CUDA kernel is surrounded by 3 synchronizations: begin, `CUDA_LAUNCH_BLOCKING`, and end.

We are thinking of:
1) not doing the "end" fence if `CUDA_LAUNCH_BLOCKING=1`
2) not doing the "begin" fence *ever*

**Comment by ibaned** [comment]
@crtrott thoughts?

**Comment by crtrott** [comment]
Might be both possible assuming we don't have a mix of Kokkos and native stuff. Not sure how important that mix use case is. Btw. just as info for occasional users: these fences are only there if you actually use a profiling tool (i.e. if KOKKOS_PROFILE_LIBRARY environment variable is set and points somewhere).

**Comment by nmhamster** [comment]
Hmmm, we need to give this some thought. We want accurate timing/profiling. Why are you asking about this? Is overhead too high?

**Comment by mhoemmen** [comment]
@csiefer2 and @ibaned noticed the overhead of double sync's.

**Comment by ibaned** [comment]
It was @csiefer2 and @dsunder who uncovered this. I don't know what the overhead is myself. We should still get accurate timing/profiling info assuming all CUDA kernels are launched through Kokkos. We can also just require that if users launch their own CUDA stuff they have to call Kokkos::fence after, or put a profiling region around it (that way fence is not called if not profiling).

**Comment by mhoemmen** [comment]
My bad -- not to neglect @dsunder :D

**Comment by crtrott** [comment]
Wait Dan: the fence should not be called if you do not do profiling even now.

**Comment by crtrott** [comment]
Yeah just checked: the fences are only called if you use a profiling tool. One reason why we would still need both a fence before and after is that a tool only provides some of the hooks. Say it only provides something for reductions: then we would still need to fence at the beginning to get good timings, because otherwise a previous parallel for loop may still be executing and thus the time for the reduce would include everything.

**Comment by ibaned** [comment]
I think the common use case is for users to profile all things: regions, reductions, loops, etc. We should optimize for performance in that case. In particular, when any profiling is enabled lets just put fences at the end of all things.

**Comment by crtrott** [comment]
Another potential issue is interoperability with native code. (i.e. you call a CUDA library). In that case a kernel from that may still be running by the time we enter a paralle_for. Without the begin fence we gonna get spurious timing.

**Comment by ibaned** [comment]
We could require that if users mix CUDA and Kokkos they should call `fence` between them to get accurate timings.

**Comment by crtrott** [comment]
But that requirement would mean they have to put a conditional fence in based on whether profiling tools are loaded.

**Comment by ibaned** [comment]
Or it could just be a permanent fence. Transitions between other CUDA code and Kokkos are typically not high-frequency (e.g. we call a pure CUDA linear solver). Another trick they could use to get a conditional fence is to put a Kokkos profiling region around the CUDA code. The point is to not slow down all high-frequency vector loops in pure Kokkos code (e.g. Belos/MueLu) just to get this mixed edge case to be convenient.

**Comment by mhoemmen** [comment]
@ibaned Why can't it be the profiling library's choice whether to fence?  That way, if Kokkos profiling is enabled but the user didn't load a profiling library, it's zero overhead.

**Comment by ibaned** [comment]
@mhoemmen the fence is already conditional on whether a profiling library is loaded and it has a hook for the particular construct being measured. So if no library is loaded there should be no fences from Kokkos. As for the library's choice, currently profiling libraries don't actually have access to Kokkos functions, which is kindof ironic, but it prevents them from calling things like `Kokkos::fence`.

**Comment by csiefer2** [comment]
As a point of anecdata, disabling syncs in Kokkos profiling increases time "Spent in Kokkos" for Chebyshev smoothing by 20% on my small test case!

**Comment by nmhamster** [comment]
@csiefer2 - you are running CUDA_LAUNCH_BLOCKING in your small test case?

**Comment by nmhamster** [comment]
@mhoemmen 

> Why can't it be the profiling library's choice whether to fence? That way, if Kokkos profiling is enabled but the user didn't load a profiling library, it's zero overhead.

We are trying to keep the tools as extremely basic C/C++ in order to make them much simpler to write and potentially work with other programming models/tool chains. For instance, some low-level performance tools was a C-only interface. We might also be able to unify our tools work with RAJA and so don't want to force Kokkos into the equation if we can avoid it. Not sure what is best to do here but my inclination is Kokkos should do the house keeping.

**Comment by csiefer2** [comment]
@nmhamster Tpetra requires CUDA_LAUNCH_BLOCKING

**Comment by mhoemmen** [comment]
I really wish Tpetra didn't need `CUDA_LAUNCH_BLOCKING=1`.  The main issue is downstream code.  It's impossible to tell a priori whether it will work, because errors depend on downstream interactions.

**Comment by stanmoore1** [comment]
If I recall correctly, when running on Pascal or later GPUs, you don't need `CUDA_LAUNCH_BLOCKING=1` for UVM to not segfault.

**Comment by csiefer2** [comment]
@mhoemmen

**Comment by ibaned** [comment]
We need to talk to @crtrott who was the main person in opposition of removing these. A meeting might make sense.

**Comment by nmhamster** [comment]
Folks, before we go round butchering a working solution, it would be really good to get some real benchmark data (not just anecdotal). The system does not fence if no tools are loaded, so if you’re getting changes without a tool loaded then it’s something else (possibly reduced optimisation?). I’m seriously against changing the fencing today because it provides us with the most accurate per-kernel timing mechanism.

**Comment by nmhamster** [comment]
I guess I’m confused, if you don’t use the tool, we don’t fence, then it’s just whatever the environment specifies. So that’s good? Maybe we should meet up?

**Comment by mhoemmen** [comment]
@nmhamster If Kokkos profiling is enabled at configure time, but you don't use the tool at run time, does Kokkos still fence?

The issue is that we (Sierra) would like to enable profiling at configure time by default.  However, if there's an overhead to enabling this at configure time (even if not using profiling), then Sierra would likely not want to enable profiling.

**Comment by nmhamster** [comment]
If you configure but don’t run a actively run a tool then no fences. The only time you get fencing (and essentially serial kernel timing) is if you configure and run the binary with a tool loaded. So you should be able to configure and run in usual mode without overhead. We designed the system for “always compile in” so we wouldn’t need a reconfigure to profile. Are you at the ECP?

**Comment by mhoemmen** [comment]
@nmhamster I'm not at the ECP.  OK, this is good news, thank you :-)

**Comment by mhoemmen** [comment]
@csiefer2 take note, you only pay for fences if actually using a profiling library.  you don't pay fences when enabling profiling at configure time.

**Comment by dsunder** [comment]
I should point out that there is overfencing when **both** CUDA_LAUNCH_BLOCKING=1 and a profiling library is loaded since the profiling library will *explicitly* fence and the kernel will then *implicitly* fence, though I’m not sure if this is an edge case that we care about optimizing.

**Comment by vbrunini** [comment]
Is that even expensive? I'd hope that in the fence -> don't run any kernels -> fence case that the runtime realizes the second fence is a no-op.

**Comment by ibaned** [comment]
@vbrunini At least with CUDA, we definitely see the second fence as equally expensive.

**Comment by dsunder** [comment]
The second fence is not as expensive as waiting for a kernel to finish, but it does need to poll the device since CUDA_LAUNCH_BLOCKING will serialize over all streams (a fence will only serialize a single stream and can avoid polling the device).

**Comment by mhoemmen** [comment]
I see the need to run with `CUDA_LAUNCH_BLOCKING=1` as a Trilinos bug that the Trilinos team needs to fix gradually over time.  @crtrott 's proposal to add an "opt out of launch blocking for specific phases of code" feature to Kokkos would help with that.

**Comment by ibaned** [comment]
It sounds like this should be revisited after either Tpetra no longer needs `CUDA_LAUNCH_BLOCKING` or has admitted it will need it forever.

**Comment by mhoemmen** [comment]
@ibaned just to remind readers -- this is mostly not a Tpetra issue, it's an issue with downstream packages.  SPARC runs with Tpetra and the Ifpack2 line solver fine with `CUDA_LAUNCH_BLOCKING` unset.

**Comment by ibaned** [comment]
@mhoemmen good point! Some use cases of Belos+MueLu+Tpetra still requires UVM and `CUDA_LAUNCH_BLOCKING`, that's what I assume we're all dealing with.

**Comment by mhoemmen** [comment]
@ibaned It's really hard to tell if Tpetra or anything is truly UVM-clean.  Sometimes the test itself is not clean but the library is.  Sometimes the tests don't have adequate coverage, since UVM issues often only show up in a larger context.

**Comment by csiefer2** [comment]
Can we just remove fencing for the regions?  I can see an argument keeping fencing for the parallel for / scan / reduce, especially if CUDA_LAUNCH_BLOCKING is disabled. But regions?  I can't see why those need to fence if all of the kernels are...

@dsunder @crtrott @ibaned

**Comment by ibaned** [comment]
if the data parallel dispatch functions are made blocking, then I guess I agree that I can't see a reason to synchronize the device on region start/stop.

**Comment by csiefer2** [comment]
@ibaned That's pretty much what I figured.  @crtrott Any argument?

**Comment by vbrunini** [comment]
I would very strongly like to see this happen. Right now I see a > 2x overhead on solve times on vortex when I turn on the space time stack tool. That is also much larger than the difference between turning on launch blocking or not.

Solve time w/space time stack: 16:27.707
Solve time w/o space time stack: 7:31.860
Solve time w/o space time stack, w/o CUDA_LAUNCH_BLOCKING: 6:22.425

**Comment by mhoemmen** [comment]
Even the Kokkos profiling regions fence, according to @csiefer2 .

**Comment by DavidPoliakoff** [comment]
Chris,

Somehow I missed this when it was filed. I took today off, but we'll at
least tackle the region fencing next week. Hopefully after we merge and
implement sync profiling we can do a better job with the rest. Thanks for
the patience

>

**Comment by ajpowelsnl** [comment]
@ibaned -- we now have the new callback (in Kokkos Tools).  You can add this callback to turn off fencing:

```
extern "C" void kokkosp_request_tool_settings(const uint32_t, Kokkos_Tools_ToolSettings* settings) {
  settings->requires_global_fencing = false;
}

```
