### ISSUE TITLE
Struct size difference with PGI 18.4

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#1635]
I get the following error when trying to compile [DTK](https://github.com/ORNL-CEES/DataTransferKit) with PGI 18.4 (with llvm backend) and 17.10. 
```
Building CXX object DataTransferKit/packages/Utils/src/CMakeFiles/dtk_utils.dir/DTK_Core.cpp.o
"/home/trilinos/packages/kokkos/core/src/impl/Kokkos_TaskQueue.hpp", line 245:
          error: static assertion failed with "Verifying expected
          sizeof(TaskBase<void,void,void>)"
  static_assert( sizeof(TaskBase<void,void,void>) == 48
  ^
```
`DTK_Core.cpp` is the first file that include Kokkos. There is virtually nothing in `DTK_Core.cpp`, it only initializes and finalizes Kokkos. I have no problem with `gcc` or `clang`. Any idea what could be wrong?

**Comment by mhoemmen** [comment]
@ibaned Time for `alignas`? :D

**Comment by Rombur** [comment]
@ibaned Thanks for your help! I just realized that the problem only appears when I compile with this [flag](https://www.pgroup.com/resources/docs/18.4/x86/pgi-ref-guide/index.htm#a). I think it's a bug in the compiler because I couldn't find a size that would work with the simple test you created. Thanks again.

**Comment by ibaned** [comment]
@Rombur huh, thats strange. That flag is documented as enabling ISO-conforming C++. As far as I know that snippet is fully ISO compliant.

**Comment by Rombur** [comment]
This flag is supposed to only issue warnings, so even if the code was not ISO-conforming, it should still compile. So it's probably a bug in the compiler.
