### ISSUE TITLE
Kokkos::fence a no-op w/ cuda lauch blocking enabled?

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#1639]
Anecdata % time in Kokkos P100:

Smoother | Code w/o Profiling syncs | Code w/ @dsunder 's mods
----| --- | ---
mtsgs | 80.9% | 96.1%
fastilu | 74.7% | 94.8%

@dsunder 's modifications involved swapping all DeepCopyAsyncs for DeepCopy and removing cuda device sync in fence.  Launch blocking enabled :)

Talk amongst yourselves...

**Comment by ndellingwood** [comment]
Cross-ref #1631

**Comment by nmhamster** [comment]
Do we know if the improvement is the DeepCopyAsync or the Fences? :)

**Comment by ndellingwood** [comment]
Per @dsunder - the fences.

**Comment by stanmoore1** [comment]
If you have load imbalance where some threads are waiting on others then a fence can shift that from one kernel to another.

**Comment by stanmoore1** [comment]
In other words, is the profiling timing accurate without the fences?

**Comment by nmhamster** [comment]
@stanmoore1 - this is my worry, same thing with counters etc. Taking the fences out is potentially problematic. We only pay the cost when profiling though so this doesn't affect "production" runs.

**Comment by crtrott** [comment]
here is my two cents: I had an option in to make Kokkos::fence for everything a no op with CUDA_LAUNCH_BLOCKING enabled. That caused all kinds of Trilinos codes to crash all over the place on Kepler systems. Also at least on the volta systems you shouldn't need CudaLaunchBlocking anymore.

**Comment by csiefer2** [comment]
@nmhamster FYI Empire wants profiling on by default...

**Comment by stanmoore1** [comment]
>Also at least on the volta systems you shouldn't need CudaLaunchBlocking anymore

I thought this was true on Pascal as well?

**Comment by crtrott** [comment]
BTW: what most likely happened in your experiment is that you are now measuring the deepcopies inside your kernel times. So the 96% now includes the data transfer, because you are not fencing to make those finish before you start measuring your kernel. CUDA_LAUNCH_BLOCKING does not fence deep_copies, allocations and so on and so on. It only fences CUDA kernel launches.

**Comment by csiefer2** [comment]
Tpetra does not call the Async memcopies, Tpetra is probably OK...
