### ISSUE TITLE
Kokkos Cuda: Can get_block_size() stuff be cached or something?

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#1641]
At the start of the kernel launch, the heuristics for the block size (see Kokkos_Cuda_Internal.hpp) call cudaOccupancyMaxActiveBlocksPerMultiprocessor() multiple times until the ideal block size is calculated.

Would it be possible to precompute or cache these guys somehow?

**Comment by crtrott** [comment]
But we could at least cut it short if it doesn't fit anymore.

**Comment by csiefer2** [comment]
As per the cuda cods:
dynamicSMemSize = " Per-block dynamic shared memory usage intended, in bytes"

Is "no dynamic shared memory usage intended" a common enough use case to optimize for?

**Comment by crtrott** [comment]
Yes and no. We use dynamic shared memory for some internal purposes. Also one of the harder to deal with things is actually the register pressure. That is what more often than not defines the step functions in occupancy based on block size.

**Comment by csiefer2** [comment]
Does cudaOccupancyMaxActiveBlocksPerMultiprocessor take register pressure into account?  The cuda documentation makes no mention of that...

**Comment by crtrott** [comment]
Yes it does.

**Comment by csiefer2** [comment]
Notes from in-person discussion:  If this information were to be cached, it should *not* be cached by Kokkos (it should happen upstream).  Kokkos would provide an API by which the block size can be sent into Kokkos during the kernel launch, bypassing the calculation.

It isn't clear this is worth doing.  But if we did want to do it, this is how we would do it.
