### ISSUE TITLE
missing libkokkos.a during Trilinos 12.4.2 build, yet other libkokkos*.a libs are there

### ISSUE THREAD

**Issue by boegel** [kokkos/kokkos#165]
While building/installing Trilinos 12.4.2 with Kokkos enabled, our build system detected that `lib/libkokkos.a` is missing, which seems to indicate a problem with the build.

Other `libkokkos*.a` libraries are there in the installation, however:

```
lib/libkokkosalgorithms.a
lib/libkokkoscontainers.a
lib/libkokkoscore.a
lib/libkokkostsqr.a
```

The build was configured to also do Kokkos, i.e. CMake output includes this:

```
-- Setting Trilinos_ENABLE_KokkosCore=ON                                                                                                                                      
-- Setting Trilinos_ENABLE_KokkosContainers=ON                                                                                                                                
-- Setting Trilinos_ENABLE_KokkosAlgorithms=ON                                                                                                                                
-- Setting Trilinos_ENABLE_Kokkos=ON  
```

I spent some time checking the build log, but couldn't find an error that explains this, so I'm wondering whether there was a recent change in Kokkos that could explain why `libkokkos.a` is not being built.

Any other pointers to something that could help me figuring this out are welcome!

**Comment by crtrott** [comment]
Hi

sorry I must have overlooked this. Was this solved for you? There actually is not supposed to be a libkokkos.a but only the ones you actually got.

**Comment by boegel** [comment]
That's what I figured, the build of Trilinos (an DOLFIN) eventually worked, thanks for the confirmation!

**Comment by crtrott** [comment]
Ah great in that case I close the issue.
