### ISSUE TITLE
std::is_convertible<Kokkos::complex<T1>, T2> is not defined. 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1658]
In STD, is_convertible is not defined with Kokkos::complex nor std::complex. In practice, these should behave like
```
namespace std {
  template<typename T1, typename T2>
  struct is_convertible<T1,Kokkos::complex<T2> >, { static constexpr value = std::is_convertible<T1,T2>::value; };
  struct is_convertible<T1,std::complex<T2> >, { static constexpr value = std::is_convertible<T1,T2>::value; };

}
```

Can we put this in the Kokkos_Complex.hpp ?

**Comment by mhoemmen** [comment]
https://en.cppreference.com/w/cpp/language/extending_std

> None of the templates defined in `<type_traits>` may be specialized for a user-defined type, except for `std::common_type`. This includes the type traits and the class template `std::integral_constant`.

**Comment by mhoemmen** [comment]
Also, `std::is_convertible` implementations should not need an implementation for custom types.  They use SFINAE to check whether an implicit assignment actually compiles.  Thus, if `std::is_convertible` doesn't work, that suggests that implicit assignment doesn't compile.

**Comment by crtrott** [comment]
Agreed.
