### ISSUE TITLE
KokkosExp_SharedAlloc, m_team_work_index inaccessible

### ISSUE THREAD

**Issue by jdbooth** [kokkos/kokkos#166]
Pulled Trilinos with fresh Kokkos Snapshot (Jan 14).  
Get error while compiling Kokkos:

/home/jdbooth/workspace/Trilinos_Basker/Trilinos/packages/kokkos/core/src/OpenMP/Kokkos_OpenMPexec.hpp(638): error #308: member "Kokkos::Impl::OpenMPexec::m_team_work_index" (declared at line 117) is inaccessible
      long work_index = m_team_lead_exec.m_team_work_index;
                               

 Error was not there last night before the snapshot.  
Compiling with Experimental View and Bounds Check on.

**Comment by crtrott** [comment]
I'll look into it and try to get an emergency fix in. Does this happen without Experimental View? Because it didn't for me. And where is the error? Can you send more output?

Christian

**Comment by jdbooth** [comment]
Hi,

It only happens with Experimental View.  I have tested it with gcc 4.9 and Intel 15.2.
I have sent you the make file and make log.

**Comment by crtrott** [comment]
Should be a few days ago.
