### ISSUE TITLE
Scratch-free implementation of ParallelFor with TeamPolicy under CUDA

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#1660]
I see that the `ParallelFor` class (`Cuda` + `TeamPolicy`) in its `operator()` device function processes some conditions based on the scratch size. 
I'm just wondering how does this overhead affect the performance if shared memory isn't used? Is it possible to use a different implementation of the function for scratch-free kernels?

**Comment by crtrott** [comment]
That overhead should be minimal. It basically does one comparison operation     
```c++
    if ( m_scratch_size[1]>0 ) {
```
which conditions all the other stuff. That comparison at worst loads a value from global memory which very likely is cached already.

**Comment by j8asic** [comment]
I'd like to revisit this. I've made an extremely quick experiment, i.e. commented out the two conditions in the `operator()` of `ParallelFor` @crtrott mentioned above, recompiled, run my personal solver that doesn't use scratch space, and then compared results.  The summary is this:

- `With-scratch-condition` in _best case takes 1.7% more time_ than the worst case of `no-scratch-condition` inside the kernel.
- `With-scratch-condition` in _average takes 3.1% more time_ than `no-scratch-condition` inside the kernel.

I believe that kernels not using scratch space should not even make these checks in runtime.

**Comment by ibaned** [comment]
@crtrott

**Comment by crtrott** [comment]
If you don't want the check, then we either can compile everything twice, or need to make scratch a compile time option on the policy. I don't believe that either option is acceptable. We could potentially make the check go through an argument instead of a dereference maybe...

**Comment by crtrott** [comment]
What hardware and what do your team kernels look like? I see only <1% changes unless your kernel runs faster than 20us at which point the overhead grows since it floors out at 1 or 2 HBM memory latencies (200-500us). So if your kernel only runs like 20us you could see 3% overhead.

**Comment by j8asic** [comment]
Thanks for checking this out. Exactly, I've timed it on multiple modern GPUs for a real-time application where kernels run for less than 20 millisecs.

Why is e.g. `if constexpr` inside `operator()` not acceptable? Having somewhere a bool compile-time option about scratch space seems like valuable info.

**Comment by crtrott** [comment]
We do not believe that adding a compile time parameter to the policy for this is a good design point. Note also that I said us not ms. Closing this for now.
