### ISSUE TITLE
Error constructing view inside parallel regions

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1664]
The following code will throw at run tme `what():  Constructing View and initializing data with uninitialized execution space`:
```
int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  Kokkos::View<int[3],ExecutionSpace> b("b");
  Kokkos::parallel_for(Kokkos::RangePolicy<ExecutionSpace>(0,10), 
    KOKKOS_LAMBDA (const int i) {
    Kokkos::View<int[3], ExecutionSpace> a("a"); //throw here
    a(0) = 1;
    a(1) = 1;
    a(2) = 1;
    b(0) = a(0);
    b(1) = a(1);
    b(2) = a(2);
    });

  } Kokkos::finalize();
}
```
where `ExecutionSpace` is OpenMP. What are the rules about constructing view inside parallel region?

**Comment by mhoemmen** [comment]
> What are the rules about constructing view inside parallel region?

Don't :-)  (Nonowning Views and subviews are OK.)

**Comment by mhoemmen** [comment]
That's a bit of an overgeneralization, but Kokkos offers ways to manage per-team and per-thread scratch space that you should use, rather than trying to create Views arbitrarily.

**Comment by Char-Aznable** [comment]
Also, I thought scratch memory is only available to team policy. How do I use scratch space in range policy?

**Comment by mhoemmen** [comment]
> OK. But what does it mean by uninitialized execution space in the error?

Delete everything but the first View creation (outside the parallel region).  Does it still throw?  If so, Kokkos was not configured with OpenMP enabled.

> Also, I thought scratch memory is only available to team policy. How do I use scratch space in range policy?

  1. UniqueToken: Use when all threads need the same amount of scratch space, and when you only need as much scratch as the amount of hardware concurrency, not the number of parallel loop iterations
  2. MemoryPool: Use when you can bound the total amount of scratch space, but different threads may need different amounts

You can search Trilinos' Tpetra package for code using UniqueToken.  Also, maybe there's a way to use team scratch in the RangePolicy case now.

**Comment by Char-Aznable** [comment]
@mhoemmen OpenMP is enabled. It doesn't throw without the creation of the view inside the parallel region. Can you give a minimal example of using UniqueToken to create view inside a parallel region? I don't see how the Tpetra example I found (core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp) is irrelevant to what I'm trying to do here. In any case, is it always safe to use POD c-array in simple cases like the one I post, i.e., replace `Kokkos::View<int[3], ExecutionSpace> a("a")` with `int a[3]`?

**Comment by mhoemmen** [comment]
> In any case, is it always safe to use POD c-array in simple cases like the one I post

Yes.  You may also use unmanaged Kokkos::View, and subviews of existing Kokkos::View.
