### ISSUE TITLE
Support for additional reductions in ScatterView

### ISSUE THREAD

**Issue by rspavel** [kokkos/kokkos#1674]
Currently it appears ScatterView only supports reductions as sums. Many of our loops actually use a min or a max for the reduction. Is there a comparatively simple way to use the existing kokkos atomics or a rough timeline on support for a wider range of reduction operators?

**Comment by crtrott** [comment]
This came out of our LANL meeting: we just gonna add this. Might be possible with the next release

**Comment by crtrott** [comment]
Fix in #1677
