### ISSUE TITLE
Illegal memory access to shared-memory view

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1695]
I have the following code that triggers a `terminating with uncaught exception of type std::runtime_error: cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/aznb/mycodes/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119` in Cuda:

```
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
#include <Kokkos_Random.hpp>

using namespace std;

using ExecutionSpace = Kokkos::DefaultExecutionSpace;

struct Foo {

  Foo(uint64_t rndSeed) : rndPool_(rndSeed) {};

  template < class E >
  KOKKOS_INLINE_FUNCTION void move() {
    
    using TeamPolicy = Kokkos::TeamPolicy<E>;
    using Team = typename TeamPolicy::member_type;
    TeamPolicy policy(100, 256);

    auto rndPool = rndPool_; //avoid capture this by pointer

    Kokkos::parallel_for(policy.set_scratch_size(0,Kokkos::PerTeam(sizeof(int))), KOKKOS_LAMBDA (Team team) {

      Kokkos::View<int, typename E::scratch_memory_space, Kokkos::MemoryTraits<Kokkos::Unmanaged>> 
        sharedInt(team.team_scratch(0));
      sharedInt() = 10889;
      }); 
  }

  Kokkos::Random_XorShift64_Pool<ExecutionSpace> rndPool_;
};


int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  Foo d(829819);

  d.move<ExecutionSpace>();

  Kokkos::fence();

  } Kokkos::finalize();
}

```
I couldn't figure out a way to debug this. Any suggestion?

**Comment by dholladay00** [comment]
I am having an issue related to this as well. I sadly don't have nice self contained example like @Char-Aznable

I can say that my issue appears to occur during finalization of the cuda and might be related to the use of scratch memory. The evidence is not strong (totalviewing a core file), but that's all I have for now.

**Comment by crtrott** [comment]
Looking into it now.

**Comment by crtrott** [comment]
Can you give more info (SHA of Kokkos, post the KokkosCore_config.h, compiler versions, hardware)? I can't reproduce it. The example you gave runs fine even when checking with cuda-memcheck.

**Comment by crtrott** [comment]
My config: Titan V, CUDA 9.0, gcc 5.3, current Kokkos develop.

**Comment by dholladay00** [comment]
I’m currently away from my desk so I don’t have all of the details, but I was using the current master, gcc 5.4.0, and cuda 9.1. I was running on a titan X (Maxwell52). Although I was also seeing this on a K40 (kepler35).

**Comment by crtrott** [comment]
Ah I see the issue. And actually Kokkos develop is actually printing a good error message now. 
```
ScratchMemorySpace<...>::get_shmem: Failed to allocate 8 byte(s); remaining capacity is 4 byte(s)
```
You didn't request enough scratch space. There is somewhere in the documentation something about you needing to use the 
```c++
view_type::shmem_size(sizes...);
```
functions to figure out how much scratch you need. One particular thing we do is aligning memory by 8 bytes, since we use the 8byte access mode to CUDA shared memory by default. 

Here is the fixed code:
```c++
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
#include <Kokkos_Random.hpp>

using namespace std;

using ExecutionSpace = Kokkos::DefaultExecutionSpace;

struct Foo {

  Foo(uint64_t rndSeed) : rndPool_(rndSeed) {};

  template < class E >
  KOKKOS_INLINE_FUNCTION
  void move() {

    using TeamPolicy = Kokkos::TeamPolicy<E>;
    using Team = typename TeamPolicy::member_type;
    TeamPolicy policy(100, 256);

    auto rndPool = rndPool_; //avoid capture this by pointer

    int shmem_size = Kokkos::View<int, typename E::scratch_memory_space, Kokkos::MemoryTraits<Kokkos::Unmanaged>>::
                     shmem_size();
    Kokkos::parallel_for(policy.set_scratch_size(0,Kokkos::PerTeam(shmem_size)), KOKKOS_LAMBDA (Team team) {

      Kokkos::View<int, typename E::scratch_memory_space, Kokkos::MemoryTraits<Kokkos::Unmanaged>>
        sharedInt(team.team_scratch(0));
      sharedInt() = 10889;
      });
  }

  Kokkos::Random_XorShift64_Pool<ExecutionSpace> rndPool_;
};


int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {

    Foo d(829819);

    d.move<ExecutionSpace>();

    Kokkos::fence();

  }
  Kokkos::finalize();
}
```

Note that shmem_size doesn't take an argument in this case since it is a 0-dim view. Normally it would take the runtime dimensions like the view constructor.

**Comment by crtrott** [comment]
Actually its a bit weird. That error message should always have been printed. Not sure why it now in develop does while it doesn't in master.

**Comment by Char-Aznable** [comment]
Yes, using `View::shmem_size()` instead of `sizeof(int)` fixes the problem for me.
