### ISSUE TITLE
Kokkos::critical

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos#1702]
Is there a Kokkos::critical available or in the works similar to Kokkos::single ? (#omp critical vs omp single)

**Comment by ndellingwood** [comment]
There is no `Kokkos::critical`, as far as I know nothing is in the works (GPU would be tricky),
@crtrott would you comment if there is some capability like this planned?

**Comment by ibaned** [comment]
Yea this would be super slow on GPUs, as the construct is inherently non-scalable. Its probably not the best parallel algorithm if it requires a critical region. It is implementable though, we could do it if required.

**Comment by crtrott** [comment]
This is basically not possible on all on hardware, and even if it were I would probably name it something like `Kokkos::measure_of_very_last_resort_because_it_is_a_terrible_idea_and_very_slow_critical` ;-)

**Comment by srajama1** [comment]
Apps request, not mine :)
