### ISSUE TITLE
Kokkos::resize accepts extra dimension arguments & passes them to View constructor, even though View constructor 

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1714]
Kokkos::resize accepts extra (greater than the run-time rank) dimension arguments without complaint, and passes them to View's constructor:

https://github.com/kokkos/kokkos/blob/64e1f315716a6d1e096d12519e5305200cae183a/core/src/Kokkos_CopyViews.hpp#L1850

but View's constructor throws if it gets extra arguments:

https://github.com/kokkos/kokkos/blob/d3a941925cbfb71785d8ea68259123ed52d3f9da/core/src/Kokkos_View.hpp#L120

@vbrunini

**Comment by mhoemmen** [comment]
@ibaned wrote:
> What exactly was the usage of resize that behaved wrongly and what is the desired outcome?

Some applications want to write code that's generic on the "Scalar" type.  Scalar could either be `double`, or one of those Sacado dynamic FAD types (for automatic differentiation).  `Kokkos::View` construction and resize with the latter requires an extra run-time dimension.  This is why `Kokkos::View`'s constructor used to let users supply an extra run-time dimension, that it would ignore in the default specialization.  This feature has been deprecated, but `Kokkos::resize` does not check whether the number of arguments correctly matches the View's rank.

**Comment by ibaned** [comment]
@mhoemmen so we just need to make `resize` stricter? Is there functionality that is now missing for FAD types with the stricter API though?

**Comment by mhoemmen** [comment]
Hi @ibaned !  Sorry for the late reply!  Mainly what I would like is for `resize` to follow the same rules that Kokkos::View's constructor follows.  This isn't a huge deal, though.

**Comment by PhilMiller** [comment]
Fix released in 3.6
