### ISSUE TITLE
Problem with returning team-shared view from function

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1730]
Consider the following:

```
#include <cstdio>
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>

using namespace std;

using ExecutionSpace = Kokkos::DefaultExecutionSpace;

static constexpr std::size_t nTeams = 1;
static constexpr std::size_t teamSize = 1;

using UnmanagedTraits = Kokkos::MemoryTraits<Kokkos::Unmanaged>;
template < class E >
using SharedSpace = typename E::scratch_memory_space;

template < class T, class E >
using SharedView = Kokkos::View<T,SharedSpace<E>,UnmanagedTraits>;


using TeamPolicy = Kokkos::TeamPolicy<ExecutionSpace>;
using Team = TeamPolicy::member_type;

decltype(auto) foo(Team team) {
  return SharedView<int***[3][2],ExecutionSpace>{team.team_scratch(1),3,3,3};
}

decltype(auto) bar(Team team) {
  return SharedView<int***,ExecutionSpace>{team.team_scratch(1),3,3,3};
}

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  auto policy = TeamPolicy(nTeams,teamSize).
    set_scratch_size(1,Kokkos::PerTeam(
      SharedView<int***[3][2],ExecutionSpace>::shmem_size(3,3,3) +
      SharedView<int***,ExecutionSpace>::shmem_size(3,3,3)
    ));

  Kokkos::parallel_for(policy, KOKKOS_LAMBDA (Team team) {
    auto f = foo(team);
    auto b = bar(team);


/*     //The following would work 
 *     SharedView<int***[3][2],ExecutionSpace> f(team.team_scratch(1),3,3,3);
 *     SharedView<int***,ExecutionSpace> b(team.team_scratch(1),3,3,3);
 */

    Kokkos::single(Kokkos::PerTeam(team), [&]() {
      printf("%20p%20p\n",f.data(),b.data());
    });
    });

  } Kokkos::finalize();
}
```
which runs with output:
```
      0x62a000008db0      0x62a000008db0
```
i.e., the two team-shared views have overlapping memory address. It seems that the move construction from the return of functions `foo()` and `bar()` doesn't work as expected. Can someone tell me if this is a limitation of constructing team-shared view? The reason why I have to do this is because in the actual use case `foo()` and `bar()` depends on some compile-time constants that specified the size of the view through pack expansion and I really want to keep it that way.

**Comment by Char-Aznable** [comment]
One work around I can see is to use the ctor 
```
Kokkos::View(const typename traits::execution_space::scratch_memory_space & arg_space, const typename traits::array_layout & arg_layout)
```
so that `foo()` and `bar()` can return a array_layout object and feed that to the View ctor but I'm not sure how to proceed with that. Can someone give an example if possible?

**Comment by ibaned** [comment]
Have you tried passing the `team` to `foo()` and `bar()` by reference instead of by value?

**Comment by Char-Aznable** [comment]
Using reference to `team` works! Should I always pass `team` by reference then? I see it passed as value and reference in different places on the wiki.

**Comment by ibaned** [comment]
Yes, always pass the team by reference. If there are parts of the wiki that have it passed by value, they should be changed.

**Comment by Char-Aznable** [comment]
For future reference, the wiki page https://github.com/kokkos/kokkos/wiki/HierarchicalParallelism has examples of passing `team` by value and by reference here and there if someone wants to correct them.
