### ISSUE TITLE
Implement and test no-constant-memory dispatch

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1732]
Essentially create a branch which doesn't send functors to constant memory, then test performance with key apps on Volta/Pascal and if it looks good then accept the branch.

**Comment by crtrott** [comment]
We have confirmation that this doesn't work. Worst case scenario with some NVSHMEM related stuff is 5x slow down. We can now effect what happens with the `WorkItemProperty`. 
For example:
```c++
  Kokkos::parallel_for(
      "default_exec::overlap_range_policy::kernel2",
      Kokkos::Experimental::require(
          Kokkos::RangePolicy<TEST_EXECSPACE>(space2, 0, N),
          Kokkos::Experimental::WorkItemProperty::HintLightWeight),
      f);
```
Will prefer kernel argument dispatch while:
```c++
  Kokkos::parallel_for(
      "default_exec::overlap_range_policy::kernel2",
      Kokkos::Experimental::require(
          Kokkos::RangePolicy<TEST_EXECSPACE>(space2, 0, N),
          Kokkos::Experimental::WorkItemProperty::HintHeavyWeight),
      f);
```
will prefer constant cache (if `f` fits).
