### ISSUE TITLE
Harmonize implementation structure of backends

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#174]
Currently the backends have very different file structure, different naming schemes etc for the internal details. For example both threads and openmp have a Kokkos_***exec.hpp and cpp. In OpenMP that contains the TeamPolicyInternal implementation as well as the TeamMemberType. In Pthreads those are in there own ThreadTeam.hpp file. Also the opening and closing of namespaces is very different which in IDEs makes it confusing to navigate the code, since the grouping and collapsing of functionality is very different. We should try and harmonize that to get the same type of file structure etc as much as possible.

**Comment by dsunder** [comment]
OpenMP cleanup already did most of this.  Environment cleanup will capture the rest
