### ISSUE TITLE
gcc-7.2.0 build error

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#1740]
We get the following build error with openmp, gcc-7.2.0:
```
/impl/Kokkos_FunctorAdapter.hpp:1219:7: error: implicit dereference will not access object of type ‘volatile Ifpack2::BlockTriDiContainerDetails::ArrayValueType<long unsigned int, 2>’ in statement [-Werror]
       *((volatile T*)lhs) += *((const volatile T*)rhs);
```

**Comment by mhoemmen** [comment]
@mrtupek FYI, best practice is to enclose build error blocks in triple backticks.  For example:
```
funky build error
T* totally_not_italics = function_returning_a_pointer ();
```

**Comment by stanmoore1** [comment]
Also good to link to the line of code on GitHub like this: https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_FunctorAdapter.hpp#L1219

**Comment by mrtupek** [comment]
OK, that hint helped us fix it locally!

**Comment by mrtupek** [comment]
Moved to Trilinos: https://github.com/trilinos/Trilinos/issues/3304
