### ISSUE TITLE
parallel_reduce of size 0, not calling init/join

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#175]
I would assume that if you call a parallel_reduce(0, functor) it would call init and then join for the result, or at least call init for the result.  However, this call does nothing.

Therefore, for a reduction of an array has to do the convoluted code listed below with the if statement.

if ( particles_.migrate_count_() == 0 )
      for (size_t i=0; i<n_remote_procs_; ++i)
	count[i] = 0;
    else
      //  This is the only thing that should be needed
      Kokkos::parallel_reduce(particles_.migrate_count_(), counter, &count[0]);

**Comment by crtrott** [comment]
That was supposed to get fixed with a commit about 5 days ago, which should have made it into Trilinos with the last integration I believe. Is this an issue in the current Head Trilinos? 

Here is the commit: https://github.com/kokkos/kokkos/commit/432e294758e68de41d20eb73cb9c9281ba933057

**Comment by bathmatt** [comment]
After an update, this seems to work,

**Comment by crtrott** [comment]
OK great. And its not an accident but was explicitly fixed ! ;-) Closing the issue.

**Comment by bathmatt** [comment]
Did you add a test because this was fixed previously (I reported it a long while ago) and broken since then.

**Comment by hcedwar** [comment]
Yes - unit tests were added.
