### ISSUE TITLE
View<>::shmem_size should runtime check for number of arguments equal to rank

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#176]
The shmem_size function should do a runtime check that the number of dimension arguments provided matches the rank of the view. This would catch user errors, which can lead to segfaults. An example is if you want a 3D shared view but forget one "*" in the shmem_size call, your third argument is silently ignored and later the code can segfault.

**Comment by crtrott** [comment]
This is neither checked in the old view implementation nor in the new one.

**Comment by hcedwar** [comment]
Default argument becomes ~size_t(0) and require `rank` arguments that are not ~size_t(0).
