### ISSUE TITLE
Team scratch memory view on CPU inherits values from previous work item assigned to the team

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1768]
Consider the following:
```
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
#include <iostream>
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using SharedSpace = typename ExecutionSpace::scratch_memory_space;
using UnmanagedTraits = Kokkos::MemoryTraits<Kokkos::Unmanaged>;

template < class T > 
using SharedView = Kokkos::View<T,SharedSpace,UnmanagedTraits>;

using TeamPolicy = Kokkos::TeamPolicy<ExecutionSpace>;
using Team = typename TeamPolicy::member_type;

struct Foo {

  SharedView<int> i_;

  KOKKOS_FUNCTION
  Foo(const Team& team) : i_(team.team_scratch(0)) {
    Kokkos::single(Kokkos::PerTeam(team), [&]() { 
      printf("%10d\n",i_());
      i_() += 1; 
    });
  };

};



int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  TeamPolicy policy = TeamPolicy(10,1).set_scratch_size(0,
    Kokkos::PerTeam(SharedView<int>::shmem_size()));
  Kokkos::parallel_for(policy, KOKKOS_LAMBDA (const Team& team) {
      Foo foo(team);
    });

  Kokkos::fence();

  } Kokkos::finalize();
}

```
When compiled with CUDA and run on GPU, I get the expected output of 
```
         0
         0
         0
         0
         0
         0
         0
         0
         0
         0

```
But on CPU with OpenMP backend, I get
```
         0
         1
         2
         3
         4
         5
         6
         7
         8
         9
```
for running with 1 thread and 
```
         0
         1
         2
         3
         4
         0
         1
         2
         3
         4

```
with 2 threads and so on. I can't find any documentation on this topic. This behavior is really odd in that the  team-shared view appears to be default initialized by calling its constructor with the scratch pad memory handle but it's actually carrying over values from previous state.

**Comment by crtrott** [comment]
This is as expected. If you run say 10000 teams on CUDA you will start to see the same thing. On Volta you have about 5000 teams running concurrently, so you need more than that to reuse any scratch memory. On Kepler it would be significantly less (more like 500). Initializing scratch memory for each team is a performance issue we want to avoid.

**Comment by Char-Aznable** [comment]
@crtrott Would reallocation of the scratch memory happen if the argument to the view ctor is dependent on the loop index? For example, if `Foo::i_` is `SharedView<int*>`, requesting a maximum of `SharedView<int*>::shmem_size(10)` during the team policy loop but each work item construct the view via the loop index such as `SharedView<int*>(team.team_scratch(0),i)` where `i = 0,1,...,9`. Does Kokkos reallocate `Foo::i_` for a team when switching over to new loop index?
