### ISSUE TITLE
environment var for ndevices...

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#1773]
Right now you need to supply --kokkos-ndevice=N to set the number of devices.  This can be problematic with cmake and testing, It would be awesome to have an environment var where you can set this.

cmake doesn't have a post exec flag option as far as I can tell, therefore, it isn't easy to set this up.  

Thanks
Matt

**Comment by crtrott** [comment]
OK we can look into this. But there is a bigger question to be had. Namely: should we use more environment variables to control runtime behaviour. Prior members of the Kokkos team were very much against it for various reasons, while current folks were generally in favour - we need to go carefully over the reasons why we didn't end up using environment variables before.

**Comment by bathmatt** [comment]
I get that, but maybe default to kokkos-ndevices to cuda number devices at least?  ctest is a pain w/o this since cmake doesn't really support this use case.

**Comment by bathmatt** [comment]
Any more thoughts on this?

**Comment by ibaned** [comment]
Yesterday's meeting concluded that we should make this available, and basically anything that can be set by an argument should also have an environment variable to control it. We'll throw an error if you try to set it both ways.

**Comment by bathmatt** [comment]
Ok. Think command line should override is the community standard though.
But I'm fine with this

**Comment by crtrott** [comment]
Tracked in larger #1798
