### ISSUE TITLE
Allow execution space for 1st arg of VerifyExecutionCanAccessMemorySpace

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#178]
Contrary to expectations, the first argument of `Kokkos::Impl::VerifyExecutionCanAccessMemorySpace<ActiveSpace, MemorySpace>` must be a memory space, not an execution space.  For example, the following Trilinos build failure:

http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2320055

shows that `VerifyExecutionCanAccessMemorySpace<device_type::execution_space, device_type::memory_space>::value == false`, for `device_type = Device<Serial, HostSpace>`.

**Comment by hcedwar** [comment]
This Kokkos::Impl (internal implementation) meta function should be used as
  'VerifyExecutionCanAccessMemorySpace< ESpace::memory_space , MSpace >::value'

**Comment by mhoemmen** [comment]
> This Kokkos::Impl (internal implementation) meta function should be used as
> 'VerifyExecutionCanAccessMemorySpace< ESpace::memory_space , MSpace >::value'

Is the eventual goal to assume "everything can access everything," so that this function won't be needed anymore?

**Comment by crtrott** [comment]
Nope, this is architecture dependant and we will not assume universal access. We do potentially assume a unified address space, (i.e. virtual addresses are unique) but that is not the same.

**Comment by mhoemmen** [comment]
I'm reopening this because -- it's wrong!  The name is wrong!  Let me fix it! ;-P

**Comment by hcedwar** [comment]
See https://github.com/kokkos/kokkos/issues/1192
