### ISSUE TITLE
circular dependency with team size functions 

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1782]
@kyungjoo-kim pointed out that you have to create a team policy to use its `team_size_max` member function, but users are usually using that function to determine the team size they want, which can't be set after the team policy is created. Is there an API to change the team size after the policy is created?

**Comment by ibaned** [comment]
@crtrott

**Comment by crtrott** [comment]
You have to create another policy. We can check whether we could add something to reset the team size. I understand this is awkward, but there is basically no other way. We need all the information from the policy object to determine maximum and optimal team size (and that includes the compile time template parameters as well as all runtime settings). There is no way to do it without less. We could have added static functions which take all the information, but that would basically have recreated the complete policy interface.

**Comment by ibaned** [comment]
Well, I think the exception is that user-requested team size should not affect maximum or optimal team size, otherwise we'd need an iterative solver. We should consider adding an API to change team size, but I guess users can work around it by creating two policies for now...

**Comment by kyungjoo-kim** [comment]
@ibaned @crtrott One question. How do we know that the determining a teamsize is not biased by the dummy policy I create to determine team size ? Suppose that I request a rough estimate of my team hierarchy size, say that vector size 5 and team size is auto. How do I know the team size given from the dummy policy is still good if I request a vector size 8 this time ?

**Comment by ibaned** [comment]
@kyungjoo-kim I think the optimal team size does depend on the vector length, so it will be different if you change vector length. Ideally you would first choose a vector length and then ask for a team size.

**Comment by crtrott** [comment]
If you want all that you just have to write your own heuristic and not use our functions. I believe the current solution is the best we can do in a generic scenario based on the information available to us. Everything beyond that will require kernel knowledge we don't have. Like for the SPMV we have a heuristic which determines those numbers.

**Comment by kyungjoo-kim** [comment]
Okay. I got it but I cannot close this issue.
