### ISSUE TITLE
spotcheck warning in Kokkos Kernels

### ISSUE THREAD

**Issue by srajama1** [kokkos/kokkos#1785]
@kyungjoo-kim reported this in Kokkos Kernels. Adding @crtrott ..

See the duplicate as well https://github.com/kokkos/kokkos-kernels/issues/284

Warnings from kokkos

/home/kyukim/Work/lib/kokkos/master/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp(645): 
warning: variable "mask" was declared but never referenced    
/home/kyukim/Work/lib/kokkoskernels/build/spotcheck/TestAll_2018-09-05_15.24.03/cuda/9.0.103/Cuda_OpenMP-release/kokkos/install/include/Cuda/Kokkos_Cuda_ReduceScan.hpp(871): 
warning: dynamic initialization in unreachable code

**Comment by crtrott** [comment]
duplicates #1767
