### ISSUE TITLE
Kokkos stride() array out-of-bounds write

### ISSUE THREAD

**Issue by kddevin** [kokkos/kokkos#1793]
In this bug report, I refer to the Kokkos that is in Trilinos.

I suspect that in Kokkos_ViewMapping.hpp, some implementations of stride() have array out-of-bounds accesses.

[https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L1463](https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L1463)

[https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L1700](https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L1700)

[https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L2152](https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L2152)

These implementations access input array elements s[0] to s[rank], while [other array-based implementations](https://github.com/trilinos/Trilinos/blob/master/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp#L976) accesses only s[0] to s[rank-1].  

The latter seems more natural from a user perspective.  Should the user always allocate his input array to be rank+1?  

Related to 
[https://github.com/trilinos/Trilinos/pull/3420](https://github.com/trilinos/Trilinos/pull/3420)
and
[https://github.com/trilinos/Trilinos/issues/3417](https://github.com/trilinos/Trilinos/issues/3417)

**Comment by mhoemmen** [comment]
I would recommend using `stride_0()`, `stride_1()`, etc. in favor of `stride()`, but yes, I've seen issues like this before.

**Comment by crtrott** [comment]
Yes the strides() interface intentionally requires a rank+1 size array. It returns tge span of the view in the last entry. Now whether that was a good design decision is another question. Maybe we should deprecate that interface and use the one from mdspan, which uses a std::array. That is in many ways a safer interface.

**Comment by kddevin** [comment]
Note that two implementations of stride() do not write anything to s[rank], so they would have uninitialized memory reads for that entry.  That is, some implementations write rank entries, and some write rank+1.

**Comment by crtrott** [comment]
Karen you are wrong they do. I guess you mean this one: 
```
  template< typename iType >
  KOKKOS_INLINE_FUNCTION
  void stride( iType * const s ) const
    {
      s[0] = 1 ;
      if ( 0 < dimension_type::rank ) { s[1] = m_dim.N0 ; }
      if ( 1 < dimension_type::rank ) { s[2] = s[1] * m_dim.N1 ; }
      if ( 2 < dimension_type::rank ) { s[3] = s[2] * m_dim.N2 ; }
      if ( 3 < dimension_type::rank ) { s[4] = s[3] * m_dim.N3 ; }
      if ( 4 < dimension_type::rank ) { s[5] = s[4] * m_dim.N4 ; }
      if ( 5 < dimension_type::rank ) { s[6] = s[5] * m_dim.N5 ; }
      if ( 6 < dimension_type::rank ) { s[7] = s[6] * m_dim.N6 ; }
      if ( 7 < dimension_type::rank ) { s[8] = s[7] * m_dim.N7 ; }
    }
```

If rank==6 than it will write into s[6]. It just looks different than the other implementation because this is for the case where we don't have a leading dimension.

**Comment by kddevin** [comment]
I agree, @crtrott   Thanks for the clarification.
The issue was resolved in a Kokkos-Kernels hot-fix to Trilinos.  Feel free to close this issue if appropriate.

**Comment by crtrott** [comment]
Ok closing this issue. We gonna discuss tomorrow whether or not to change the interface into not being so awkward.
