### ISSUE TITLE
Kokkos complains when attaching a large Kokkos::View to texture cache

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#1794]
On Volta70 (CUDA 9.2.88), I am getting the following error when dealing with large Kokkos::View object.  Is there any way to avoid this situation?
```
Kokkos::CudaSpace ERROR: Cannot attach texture object to alloc_ptr(0x7ffc00000000) alloc_size(2556948864) max_size(1073741824)
Kokkos::CudaSpace ERROR: Cannot attach texture object to alloc_ptr(0x7ffc00000000) alloc_size(2556948864) max_size(1073741824)
```

**Comment by crtrott** [comment]
You can compile with the option to use "ldg" instead of texture objects.

**Comment by keitat** [comment]
Is it nvcc option?

**Comment by crtrott** [comment]
No a Kokkos option `KOKKOS_ENABLE_CUDA_LDG_INTRINSIC` in cmake. It is probably not well tested.

**Comment by keitat** [comment]
Thanks!  Interestingly, I did not see any performance change with my code.
