### ISSUE TITLE
Warning error.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1796]
I am not sure if I need to put this issue on kokkos or kokkoskernels. I decided to post for both. 

gcc 7.2.0 and cuda 9.2.88. While compiling kokkoskernels with ``-Werror``,  I got the following warning error. Removing compiler warnings is quite annoying and I am wondering if kokkos wants to remove these warnings or not. 

```
/home/kyukim/Work/lib/kokkoskernels/master/src/impl/generated_specializations_cpp/spgemm_numeric/KokkosSparse_spgemm_numeric_eti_spec_inst_doub$
/ascldap/users/kyukim/Work/lib/kokkoskernels/build/white/release/kokkos/install/include/Cuda/Kokkos_CudaExec.hpp:267:42:                        
error: ‘*’ in boolean context, suggest ‘&&’ instead [-Werror=int-in-bool-context]                                                               
     if ( grid.x && ( block.x * block.y * block.z ) ) {   
```

**Comment by kyungjoo-kim** [comment]
I don't find any PR related to this kind of warnings.

**Comment by ndellingwood** [comment]
@kyungjoo-kim looks like PR #1739 should have addressed this, can you confirm you have that SHA in your kokkos branch?

**Comment by ndellingwood** [comment]
Here's is the SHA from the merge commit - 5fe980f4b6d672cd58aab0e8685d8e1dfc9f809e

Made Aug 16.

**Comment by kyungjoo-kim** [comment]
Thank you. My kokkos was outdated. I updates kokkos and see if the problem still exist or not in kokkos kernels compiling.

**Comment by kyungjoo-kim** [comment]
There are others in the code 
Line 211, 267, 324 and (373 is fixed). 
```
https://github.com/kokkos/kokkos/blob/a1ed6a8ae192236c7acd88ecfd1bfe7a1d83a5b4/core/src/Cuda/Kokkos_CudaExec.hpp#L211
```

**Comment by ndellingwood** [comment]
@kyungjoo-kim thanks for the catch, will work on a fix

**Comment by kyungjoo-kim** [comment]
I don't know if this is really worth for fixing that kind of warnings. Compilers are getting picky. I think that generating warnings for totally legal statement in C++ does not make sense. BTW, C++ does not allow integer in conditional statement ?

**Comment by ndellingwood** [comment]
It's a straightforward and fast fix (replace offending lines by something like 373 basically) and removes annoying warnings, important sicne others will be annoyed by as well ;)

**Comment by kyungjoo-kim** [comment]
I do not worry Kokkos but Trilinos. Whenever Sierra integration happens, Sierra requests warning free trilions but this would consume quite a lot of time of Trilinos developers.

**Comment by ndellingwood** [comment]
PR #1799 in, running spot-check
