### ISSUE TITLE
Experimental::UniqueToken interface

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#1806]
Starting to use UniqueToken and had a couple interface suggestions/feature requests that @crtrott wanted an issue for:

1) Rather than returning the size_type unique value acquire() could return an RAII helper that automatically calls release() when it goes out of scope.
2) I would find it useful to be able to get a per-team unique value in the range [0, concurrency() / team_size) in addition to the existing per-thread unique value in [0, concurrency()). An overload of acquire() that accepts the team member struct as an argument is one possible interface for this that would be convenient.

**Comment by crtrott** [comment]
I talked with victor about this earlier: we should discuss this next week at the meeting.
