### ISSUE TITLE
Kokkos::deep_copy broken for custom stk::simd layouts

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1810]
@alanw0 showed me some build errors yesterday with an updated Trilinos.  It looks like the recent Kokkos::deep_copy changes now require that users specialize Kokkos::Impl::ViewRemap (and possibly other things) for custom layouts.  Is that correct?

**Comment by crtrott** [comment]
Not sure why that would be needed. We must have overlooked something. First: post the full error. Second: we need a unit test which tests a custom Layout. I think we can fake that by putting a wrapper around LayoutRight or so (e.g. just derive things or so).

**Comment by mhoemmen** [comment]
Here is an example, involving `stk_simd/stk_simd_view/simd_view.hpp` in a unit test:
```
In substitution of 'template<class V, class ... Args> using Subview = typename Kokkos::Impl::ViewMapping<void, typename V::traits, Args ...>::type [with V = Kokkos::View<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0> >; Args = {Kokkos::Impl::ALL_t, Kokkos::pair<long int, long int>, Kokkos::Impl::ALL_t}]':
    .../Kokkos_CopyViews.hpp:723:60:   required from 'struct Kokkos::Impl::CommonSubview<Kokkos::View<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0> >, Kokkos::View<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0> >, 3, Kokkos::Impl::ALL_t, Kokkos::pair<long int, long int>, Kokkos::Impl::ALL_t>'
    .../Kokkos_CopyViews.hpp:857:25:   required from 'Kokkos::Impl::ViewRemap<DstType, SrcType, ExecSpace, 3>::ViewRemap(const DstType&, const SrcType&) [with DstType = Kokkos::View<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0> >; SrcType = Kokkos::View<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0> >; ExecSpace = Kokkos::Serial]'
    .../Kokkos_CopyViews.hpp:1439:21:   required from 'void Kokkos::deep_copy(const Kokkos::View<D, P ...>&, const Kokkos::View<RT, RP ...>&, typename std::enable_if<((std::is_same<typename Kokkos::ViewTraits<DataType, Properties ...>::specialize, void>::value && std::is_same<typename Kokkos::ViewTraits<RT, RP ...>::specialize, void>::value) && (((unsigned int)(Kokkos::ViewTraits<DataType, Properties ...>::rank) != 0) || ((unsigned int)(Kokkos::ViewTraits<RT, RP ...>::rank) != 0)))>::type*) [with DT = double* [3][4]; DP = {stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0>}; ST = double* [3][4]; SP = {stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0>}; typename std::enable_if<((std::is_same<typename Kokkos::ViewTraits<DataType, Properties ...>::specialize, void>::value && std::is_same<typename Kokkos::ViewTraits<RT, RP ...>::specialize, void>::value) && (((unsigned int)(Kokkos::ViewTraits<DataType, Properties ...>::rank) != 0) || ((unsigned int)(Kokkos::ViewTraits<RT, RP ...>::rank) != 0)))>::type = void]'
    .../stk_simd/stk_simd_view/simd_view.hpp:388:20:   required from 'void stk::simd::deep_copy(A, B) [with A = stk::simd::View<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial>; B = stk::simd::View<double* [3][4], void>]'
    .../stk/stk_simd/unit_tests/UnitTestStkSimdView3d.cpp:72:25:   required from 'void StkSimdView3dTester<ArrayStyle, Real, dim1, dim2, Layout>::host_mirror_test() const [with ArrayStyle = double* [3][4]; Real = double; int dim1 = 3; int dim2 = 4; Layout = void]'
    .../stk/stk_simd/unit_tests/UnitTestStkSimdView3d.cpp:248:27:   required from here
    .../Kokkos_View.hpp:2413:13: error: no type named 'type' in 'class Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<double* [3][4], stk::simd::LayoutRight<double>, Kokkos::Serial, Kokkos::MemoryTraits<0> >, Kokkos::Impl::ALL_t, Kokkos::pair<long int, long int>, Kokkos::Impl::ALL_t>'
         >::type ;
                 ^
```

**Comment by mhoemmen** [comment]
@crtrott btw this is not urgent -- it's a Sierra build with current master Trilinos, not the regular Sierra build.

**Comment by crtrott** [comment]
It might be as simple as that your specialization of VIewMapping needs to add a typedef (i.e. the `type` typedef. See https://github.com/kokkos/kokkos/blob/d3a941925cbfb71785d8ea68259123ed52d3f9da/core/src/impl/Kokkos_ViewMapping.hpp#L3072

That was added in 2016 but maybe we didn't use it anywhere critical before, and now it is used inside of deep_copy indirectly.

**Comment by ndellingwood** [comment]
Is this occurring when deprecated code is enabled? For that case we had to deal with similar issues with Sacado during the 2.6.00 promotion when using a custom `LayoutContiguous`, the problem occurred with the `CommonSubview` adapters in the `ViewRemap` trying to create a subview that led to calling an `assign` method in Kokkos' `ViewMapping` that only recognizes `LayoutRight`, `LayoutLeft`, or `LayoutStride`. For this case I think we reworked Sacado's `deep_copy` to create a new View with a compatible layout (i.e. Left, Right, or Stride) used as a wrapper prior to calling Kokkos' `deep_copy`. 
For reference, this was in PR trilinos/Trilinos#2297 and discussion in issue trilinos/Trilinos#1413

**Comment by ndellingwood** [comment]
Also, this issue shouldn't occur when deprecated code is disabled, as that code path that causes the compilation issue will no longer exist, so extra effort to make this work with deprecated code will be short lived.

**Comment by crtrott** [comment]
Regarding what Nathan just said: the reason that code path doesn't get exercised anymore is that we deprecated the behavior of deep_copy to accept two views of different dimensions, and simply copying elements up the min of the extents. We decided the cleaner interface is for folks to give subviews to deep_copy if they really want that.

**Comment by mhoemmen** [comment]
@mrtupek @alanw0

**Comment by mhoemmen** [comment]
Thanks @crtrott and @ndellingwood ! :D

**Comment by crtrott** [comment]
Are we ok to not fix this and just rely on deprecated code being disabled?

**Comment by ndellingwood** [comment]
@mhoemmen I'm labeling as a question based on the previous comment for resolution, let me know if I should recategorize if the label seems unfitting. Thanks!

**Comment by theguruat12** [comment]
@alanw0

**Comment by theguruat12** [comment]
@mhoemmen Note that we started to look at possible fixes today.  However, it looks more involved and we may need some help.  Therefore, @ndellingwood and @crtrott , we Sierra developers would like to reopen this issue, because this blocks Trilinos promotion in Sierra.  @alanw0 depends on promotion (and on disabling deprecated code) for getting good GPU performance with STK (relating to DualView).
