### ISSUE TITLE
pthread back end hangs if used uninitialized

### ISSUE THREAD

**Issue by rppawlo** [kokkos/kokkos#182]
The other execution spaces seem to exit with an exception reported for attempting to use an execution space that is not yet initialized. However the pthread back end just hangs with no message. Can this be fixed to throw an exception?

**Comment by hcedwar** [comment]
This is a new bug in Kokkos_RangePolicy::set_auto_chunk_size() where the Threads::concurrency() has a value of zero before Threads is initialized().  This function needs to be fixed and reviewed.

**Comment by crtrott** [comment]
Args. I wondered why I was assigned this stuff - I don't like the threads backend ;-)

**Comment by crtrott** [comment]
got it fixed on my machine, will push later. I am trying to get through a number of issues in one go.

**Comment by rppawlo** [comment]
Thanks Christian!

**Comment by crtrott** [comment]
I believe this was merged into master and Trilinos.
