### ISSUE TITLE
When to use Kokkos::fence()?

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1821]
I know on CUDA backend `Kokkos::fence()` is just `cudaDeviceSynchronize()`. The only relevant situation I've encountered is to sync from device to host. I know also that syncing kernels in different CUDA streams also require `cudaDeviceSynchronize()` -- but is this relevant to Kokkos? Is there any other situation where one wants to call `Kokkos::fence()`?

**Comment by mhoemmen** [comment]
It's not currently legal to modify entries of a UVM allocation concurrently on device and on host.  `Kokkos::fence()` ensures that any device kernels that modify the entries of a UVM allocation have finished running, so that it's safe to access those entries on host.
