### ISSUE TITLE
API Documentation/Wiki: Impl typedef  

### ISSUE THREAD

**Issue by dalabre** [kokkos/kokkos#1832]
@crtrott @ibaned  The API documentation is *not* intended to cover *namespace Impl* templates; what about Impl constructions within functions? See example below: 

the template function *copy_functor* includes a typedef from the *Impl namespace* used in the arguments and copy constructor. This definition is a *public member* in the Kokkos namespace *(algorithms/src/Kokkos_Sort.hpp)*. Is this an acceptable entry for the API? Or __No Impl definitions__ at all!

```c++
  template< class DstViewType , class SrcViewType >
  struct copy_functor {

    typedef typename SrcViewType::const_type  src_view_type ;

    typedef Impl::CopyOp< DstViewType , src_view_type > copy_op ;

    DstViewType     dst_values ;
    src_view_type   src_values ;
    int             dst_offset ;

    copy_functor( DstViewType  const & dst_values_
                , int          const & dst_offset_
                , SrcViewType  const & src_values_
                )
      : dst_values( dst_values_ )
      , src_values( src_values_ )
      , dst_offset( dst_offset_ )
      {}

    KOKKOS_INLINE_FUNCTION
    void operator() (const int& i) const {
      copy_op::copy(dst_values,i+dst_offset,src_values,i);
    }
  };
```

**Comment by ibaned** [comment]
@dalabre I don't think `BinSort::copy_functor` was meant to be part of of the public API of `BinSort` itself. It may be that the code will compile fine if it is moved to the `private` section, or it may be that some deficiency in CUDA prevents us from doing that, I'm not sure. Either way, I would just not document `BinSort::copy_functor` or `BinSort::copy_permute_functor` at all. Sometimes the rules are subjective, I would say if there is one good rule of thumb it is to look in Kokkos examples and parts of Trilinos that use Kokkos, and document Kokkos features in order of how often they appear outside of Kokkos itself.

**Comment by dalabre** [comment]
@ibaned Thanks for that input. That seems to be a more valuable approach as documenting "all public template/class functions" according to the style of the **Views API** is going to take a looooong time!

**Comment by dalabre** [comment]
I have searched the Kokkos function calls and classes in Tpetra, created a list. I will focus on folding this into the private wiki API.

Closing this question.
