### ISSUE TITLE
OpenMP: Be aware of cost of num_threads cost

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1844]
Stephen Olivier says: Be aware that there is a run-time cost to use the `num_threads` clause.  We are working with vendors to eliminate that cost.

@csiefer2 @jjellio @olivier-snl

**Comment by olivier-snl** [comment]
Related LLVM bugzilla ticket: https://bugs.llvm.org/show_bug.cgi?id=39137

**Comment by crtrott** [comment]
Yeah we know that is one of the issues which delayed our move to doing more native OpenMP 4 constructs.

**Comment by olivier-snl** [comment]
@crtrott Please let me know if there are similar OpenMP issues we should be pushing on.
