### ISSUE TITLE
cuda.scatterview unit test causes "Bus error" when force_uvm and enable_lambda are enabled

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1852]
Tested with SHAs 21e5f5ba2d603f2420403ec6b126bcbb09f708fe and a76b5c1cb9f65e4a7dca8ddb3495d5aa53a9757e

Tested on White on the Kepler queue.

Sample error output:
```
[ RUN      ] cuda.scatterview
Bus error (core dumped)
bash-4.2$ 
```

generate_makefile reproducer:
`../../generate_makefile.bash --with-cuda --with-serial --compiler=${HOME}/kokkos/bin/nvcc_wrapper --with-cuda-options="force_uvm,enable_lambda" --arch="Power8,Kepler37"`

**Comment by ndellingwood** [comment]
Running the scatterview test with uvm and lambda require setting `CUDA_LAUNCH_BLOCKING=1` and `CUDA_MANAGED_FORCE_DEVICE_ALLOC=1` allows the test to pass. 
@ibaned @crtrott are these environment variables supposed to be required, or does needing these to make the test pass an indication of an issue?

**Comment by crtrott** [comment]
This is a bug basically there is a missing Kokkos::fence()

**Comment by crtrott** [comment]
Bug is in the test not in the code.

**Comment by crtrott** [comment]
PR #1854

**Comment by ndellingwood** [comment]
See PR #1854.
