### ISSUE TITLE
subview return type and static dimensions

### ISSUE THREAD

**Issue by gregvw** [kokkos/kokkos#1862]
I have some code that creates compile time ''strings'' for multidimensional data types
that I have tested with `Kokkos::subview` as follow:

```c++
Kokkos::View<double*[5][10],Kokkos::LayoutRight>  A("A",3,5,10);
using A_type = decltype(A);
using A_data_type = my_traits::data_t<A_type>; // is double*[5][10]
cout << DataTypeString<A_data_type>() << endl; // prints double*[5][10]

using all_type = decltype( Kokkos::ALL() );
using subview_type = decltype( Kokkos::subview( declval<A_type>(), declval<size_t>(), declval<all_type>(),declval<all_type>() ) );
using subview_data_type = typename subview_type::traits::data_type;
cout << DataTypeString<subview_data_type>() << endl; // prints double**
```

The data type for the `Kokkos::subview` loses the static dimensions. Is this due to how subview is
implemented or is there some fundamental limitation to slicing multidimensional arrays 
in C++ which precludes preserving static dimensions?

**Comment by crtrott** [comment]
It is not a fundamental thing. Actually our reference implementation for MDSpan (i.e. what will be the C++ standard version of Kokkos::View) does the right thing. I mark this as an enhancement request.

**Comment by dhollman** [comment]
#2007 should address this, once it's merged

**Comment by dhollman** [comment]
This is now in master. Closing.

**Comment by Char-Aznable** [comment]
@dhollman I have a similar question. As in the OP, is it expected that the type of
```c++
subview(A, ALL(), ALL(), 0) 
```
is `View<double**>`? i.e., all the static dimension preceding the one sliced by a single index is converted to dynamic dimension.
