### ISSUE TITLE
Compiling Kokkos library with CUDA support

### ISSUE THREAD

**Issue by minitu** [kokkos/kokkos#1867]
Hi,

I'm having trouble trying to compile Kokkos with CUDA support.

I created a separate build folder and then ran
`../generate_makefile.bash --prefix=/home/jchoi157/kokkos/build-cuda --with-cuda=/opt/packages/cuda/8.0`

Running `make kokkoslib` after throws the following error:
```
Makefile.kokkos: CUDA is enabled but the compiler is neither NVCC nor Clang.  Stop.
```

So I tried setting the compiler to NVCC with
` ../generate_makefile.bash --prefix=/home/jchoi157/kokkos/build-cuda --with-cuda=/opt/packages/cuda/8.0 --compiler=/opt/packages/cuda/8.0/bin/nvcc`,
but running `make kokkoslib` throws a bunch of errors starting with
```
In file included from /home/jchoi157/kokkos/core/src/impl/Kokkos_HostBarrier.cpp:44:0:
/home/jchoi157/kokkos/core/src/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/jchoi157/kokkos/core/src/impl/Kokkos_Utilities.hpp:59:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
```

FYI, this was done on PSC Bridges with CUDA Toolkit 8.0.
I must be doing something wrong here, and I would really appreciate some help.
Thanks!

**Comment by mhoemmen** [comment]
Do you need to use the makefile generator?  If not, try this:
```
make CXX=${KOKKOS_SOURCE_DIRECTORY}/bin/nvcc_wrapper KOKKOS_DEVICES=Cuda KOKKOS_ARCH=Volta70,Power9
```
Replace `${KOKKOS_SOURCE_DIRECTORY}` with your Kokkos source directory, and replace the arguments to `KOKKOS_ARCH` with your architectures.

**Comment by minitu** [comment]
@mhoemmen How do I create a Makefile to build Kokkos as a standalone library without the makefile generator? The top level folder does not have a Makefile and the README tells me to use the generator in a separate build folder to create the Makefile.

**Comment by crtrott** [comment]
Your second attempt was almost correct. But you need to use either Kokkos's nvcc_wrapper or clang with CUDA support as compiler. nvcc_wrapper is using nvcc underneath but sorts arguments correctly etc. 

So this should work: 
```
../generate_makefile.bash --prefix=/home/jchoi157/kokkos/build-cuda --with-cuda=/opt/packages/cuda/8.0 --compiler=/home/jchoi157/kokkos/bin/nvcc_wrapper
```

**Comment by minitu** [comment]
@crtrott That does the trick. Thank you!
