### ISSUE TITLE
Degenerate View behavior changes with deprecated code disabled

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1870]
Reported by @vqd8a 

The following code compiles and executes without failure when deprecated code is disabled and debugging is off:

```cpp
#include <Kokkos_Core.hpp>
#include <cstdio>
#include <iostream>

int main (int narg, char* arg[]) {
  Kokkos::initialize(narg , arg);
  {
    Kokkos::View<double***, Kokkos::HostSpace> v("v",0,2,2);
    std::cout << " span" << v.span() << std::endl;
    std::cout << "v(0,0,0) = " << v(0,0,0) << std::endl;
    v(0,0,0) = 1;
    v(0,1,1) = 2;
    std::cout << "v(0,0,0) = " << v(0,0,0) << std::endl;
    std::cout << "v(0,1,1) = " << v(0,1,1) << std::endl;
  }
  Kokkos::finalize();

return 0;
}
```

If deprecated code is enabled, this seg faults at execution.

If debugging is on, then an error is thrown as expected:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: View bounds error of view v ( 0 < 0 , 0 < 2 , 0 < 2 )
Traceback functionality not available
```

**Comment by ndellingwood** [comment]
Question - what is the proper behavior when accessing a View with a zero extent in a rank?

Assuming the above is a bug when deprecated code is disabled so marking as bug.

**Comment by ndellingwood** [comment]
When deprecated code is enabled, there is no memory allocation for `v("v",0,2,2);` (`v.data()` is `null`).
When deprecated code is disabled, there is a memory allocated (or else it would have seg faulted as well).

**Comment by ndellingwood** [comment]
Adding @crtrott @ibaned

**Comment by crtrott** [comment]
Deprecated behavior is correct. Not sure why it actually not crashed before. The view should have a name (i.e. v.label() should work), but v.data() should be NULL and data accesses are violating bounds.

**Comment by ndellingwood** [comment]
Thanks for the info, I'll close this then since there is no code to address.
