### ISSUE TITLE
Support creation of managed views of classes without a device default constructor when asking for no-initialization

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#1873]
In particular this is coming up for UniqueToken, but the issue should apply to any type whose default constructor is host-only that is being stored in a View. Code like:
```cpp
// Allocate space for unique tokens, do not initialize because the default constructor is not GPU-safe
View<UniqueToken<Cuda>*, CudaSpace> unique_tokens(view_alloc("unique_tokens", Kokkos::WithoutInitializing), size); // Warning here
auto host_mirror = create_mirror_view(unique_tokens);
// Code to create the tokens in the host_mirror and deep_copy them over to the GPU follows here
```
causes warnings about calling a host function from a host device function with nvcc. The warnings show up on the marked line from the functor call that would initialize the values in unique_tokens if we weren’t using Kokkos::WithoutInitializing. Looking at Kokkos_ViewMapping.hpp I see that that functor call is just protected by a regular if statement that checks the (compile time known) value of alloc_prop::initialize, thus the warning.
 
How much would it hurt compile times, maintenance for you guys, etc to move that initialization functor call so that it does not get compiled when we use WithoutInitializing to get rid of the warning?

**Comment by crtrott** [comment]
Renamed title. Basically we need to find a way of making the constructor which requests WithoutInitializing not instantiate the initialization kernel.

**Comment by dhollman** [comment]
@ibaned Have you made any progress on this? I already handled this exact thing for something similar in Kokkos tasking; should be a 15 minute fix or so.

**Comment by ibaned** [comment]
I haven't done any work towards this, if you have an approach please go ahead, thanks!

**Comment by mhoemmen** [comment]
I think @alanw0 may want a fix for this too.

**Comment by dalg24** [comment]
Tentative solution #2024 stalled because of compiler bug

**Comment by clellsolomon** [comment]
@dhollman and @crtrott: is there an ETA on this issue and/or associated compiler bug that has been identified.  I'd like to be able to construct uninitialized managed views with non default constructible types.  If you have any other means of doing so, please let me know.

**Comment by crtrott** [comment]
Here is a workaround:

```c++
#include <Kokkos_Core.hpp>
#include <cmath>

struct Foo {
  double a;
  KOKKOS_FUNCTION
  Foo(double a_) { a=a_;}
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  {
    int N = argc > 1 ? atoi(argv[1]) : 1000000;
   using view_t = Kokkos::View<Foo*,Kokkos::MemoryTraits<Kokkos::Unmanaged>>;
    int64_t bytes = view_t::required_allocation_size(N);
    Foo* ptr = (Foo*)Kokkos::kokkos_malloc<typename view_t::memory_space>(bytes);
    view_t a(ptr,N);
    Kokkos::kokkos_free(ptr);
  }
  Kokkos::finalize();
}
```

This uses a truly unmanaged view, note that means no reference counting, and you are responsible for destroying the allocation. 
In some sense this is semantically safer since we don't know how to create valid instances of your objects or how to delete them correctly again.

**Comment by clellsolomon** [comment]
@crtrott : Thanks for getting back to me.  In you example you never actually construct `Foo`s though, do you?  You create a buffer that can store them.

Wouldn't this require some sort of placement construction like the following inserted under
`view_t a(ptr,N);`:
```
kokkos::parallel_for(N, KOKKOS_LAMBDA(int64_t i){
  new (&a[i]) Foo{construct_a_Foo(i)};
});
```
It didn't seem that `deep_copy` could be utilized unless the type is also trivially copyable, which if my type is holding other Kokkos::Views I don't think is the case, correct?

I think I could use what you propose if I wrap your proposal in some sort of "`UniqueView`" that would behave as a sort of blend of unmanaged view and unique_ptr...but I've only given this a few moments thought.  I bet you've considered this already, what are your thoughts.

**Comment by crtrott** [comment]
Yes you are right you need to do the placement new. But that is exactly my point: how would I give you initialized memory if I don't know what consturctor works for you? In that case I can only give you uninitialized memory and I hope you know what you are doing.
