### ISSUE TITLE
FY19 Big Ticket Items

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1874]
This is a list of big-ticket items for FY19 for book keeping
* HIP Backend for AMD GPUs
  * We already have the ROCm backend, but per guidance from AMD the HIP frontend from their compiler is more robust at this point
* Cilk+ Backend Support for EMU 
  * Collaboration with Georgia Tech
* OpenMP Native Constructs
  * Originally our own scheduling in OpenMP was better than the runtimes, and OpenMP 3 didn't support flexible enough custom reductions. This is not longer true.
  *  Biggest issue: Hierarchical Parallelism can be implemented via OpenMP teams or nested parallelism, both of which are not necessarily well supported with all compilers and may need a host of environment variables to be set correctly.
* OpenMP Target For GPUs
  * Not super high priority but we should make this work
* Execution Spaces Instances: GPUs
  * We have long standing requests for supporting CUDA streams. We need to get this finally done. 
* Resilient Memory Spaces
  * Collaboration with Sandia CA
* Remote Memory Space
  * Initial versions working need to be made more robust and performant.
  * Need to explore more proxy apps, in particular something in the graph space
* Auto Tuning
  * Register internal and user provided runtime parameters with a auto tuning library
  * Current thought make this software engineering wise work like the profiling interface
* C++ Standard More Asynchronous Behavior like Executors

**Comment by mhoemmen** [comment]
Does "resilient memory spaces" mean something like arrays with global versioning?

**Comment by crtrott** [comment]
Resilient Memory Spaces is something we want to explore together with Keita. There are numerous approaches one can take, from fairly simple things such as simply supporting snapshotting by putting one of those IO libraries underneath, semi automatic snapshotting where we register the views and a space::snapshot or so would create a snapshot of all the registered views, automatic saving of modifiable views at kernel launches to make them idempotent and so on. All those could be combined with global versioning, and various approaches to snapshotting in either non-volatile memory or via MPI to other nodes. We need to explore what is most practical and useful in various application scenarios. 

In either case this would be an add-on library not part of Kokkos core.

**Comment by pguthrey** [comment]
Is there any plan to make the following work (or do these currently work) with Kokkos?
I did not yet see options for these GPUs in the documentation

Radeon Pro 560X with 4GB of GDDR5 memory
Radeon Pro Vega 16 with 4GB of HBM2 memory
Radeon Pro Vega 20 with 4GB of HBM2 memory

[FIY these are the GPU options for the 2019 Macbook pros]

**Comment by PhilMiller** [comment]
Several of these things actually got implemented, and a few more are work-in-progress. We're now 4 years past the expiration date on this issue, though, so closing it.
