### ISSUE TITLE
Kokkos::Crs constructor/destructor should not be host-only

### ISSUE THREAD

**Issue by alanw0** [kokkos/kokkos#1876]
Since Kokkos::Crs basically just holds two Views, and Views can be constructed/destructed on device, Kokkos::Crs should also be constructed/destructed on device.

Can KOKKOS_FUNCTION be added to the constructor and destructor?

**Comment by crtrott** [comment]
Sure.

**Comment by crtrott** [comment]
Need to:
* add KOKKOS_INLINE_FUNCTION to appropriate constructors
* extend Kokkos::Crs UnitTests to test constructions inside a parallel_for
