### ISSUE TITLE
0d View usage

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#188]
I am having difficulty using 0d views (specifically with cuda). 2 small examples below to show what is happening.
1. Copying const view back to host
---
```c++
    View <const int> a; // read only variable on device
    {
      View <int> b("b"); // not const, set by some function
      // b is set to some value
      ...
      a = b; // set a = b
    } // b now out of scope
    int c = 0; // get value of a host-side
    deep_copy(c, a); // this line fails with: "error: no instance of overloaded function "deep_copy" matches the argument list ..."
```
---
2. atomics
---
```c++
    View <int, MemoryTraits<Atomic> > a("a"); 
    parallel_for(N, ... 
    {
      a += 1; // this line fails: "no operator "+=" matches these operands ... "
    });
```
---
2 is less of an issue b/c one can use `Kokkos::atomic_add(&a(), 1)` ? I have not verified that using this gives the desired results, but it does not throw a compile error. 

If there is a resource to help with this that I am unaware of, that would be good to know of as well.

**Comment by ndellingwood** [comment]
1. Fix for copying const view back to host committed and merged to develop branch f93cd23
2. For the atomics issue try replacing a += 1; with  a() += 1;

**Comment by dholladay00** [comment]
1. I switched to develop branch and rebuilt and it works!
2. That worked, for some reason I thought I had tried it before and it failed. In one of my tests I had ```c++ *(&a())``` to get at the 0d views, but I was able to remove all of that with just empty parentheses. 

Thanks for the quick turnaround!!

**Comment by crtrott** [comment]
Yeah the atomic stuff was broken at some point for 0d views, but I fixed that a while ago.
