### ISSUE TITLE
get rid of uvm_num_allocs test

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1880]
I know this tests something legitimate, but its excessive runtime seems to be too high a cost for the slightly improved error message that it is ensuring the correctness of.

**Comment by crtrott** [comment]
Actually looks like the limitation is gone in the drivers now. Not sure which driver version removed that. But effectively that means we can get rid of the error thingy altogether.

**Comment by crtrott** [comment]
We should hot-fix remove that error check inside of Trilinos too ...
