### ISSUE TITLE
Kokkos nvcc compiler error for C++14 constructs

### ISSUE THREAD

**Issue by huttered40** [kokkos/kokkos#1882]
I am trying to build a library that uses Kokkos on the White machine, 7G queue. In my Makefile, I have set CXXFLAGS = -O3 --expt-extended-lambda --expt-relaxed-constexpr -std=c++14. When I go to build, I get warnings "nvcc_wrapper - *warning* you have set multiple optimization flags (-std=c++1* or --std=c++1*), only the first is used because nvcc can only accept a single std setting", telling me that the '-std=c++14' flag is being removed. Then, I get a number of compiler errors related to C++14 constructs like 'error: "auto" function requires a trailing return type'.

I have successfully built this library on Bowman machine. Is there something special I need to do in my Makefile or Kokkos build in order to have the compiler recognize the '-std=c++14' flag?

I tried compiling with module 'devpack/20180521/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88'

@srajama1

**Comment by mhoemmen** [comment]
https://github.com/kokkos/kokkos/wiki/Compiling

**Comment by huttered40** [comment]
Thanks. Looks like I will need to modify the bin/nvcc_compiler script to accept -std=c++14 only.

**Comment by ibaned** [comment]
I think you actually need to set `KOKKOS_CXX_STANDARD=c++14`

**Comment by huttered40** [comment]
Ok thanks. I'll try that first.

**Comment by crtrott** [comment]
Also KOKKOS_CXX_STANDARD=c++14 will only work on the develop branch. We didn't actually fully support higher standards than c++11 before (mostly an issue of not testing it). The develop branch (next week master) does support that.

**Comment by huttered40** [comment]
Thanks. This issue has been resolved.
