### ISSUE TITLE
Runtime rank wrapper for View

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#189]
Provide a thin wrapper over a rank eight View that supports a runtime rank between zero and eight.  The member access operator overloads simply fill in the missing arguments to the underlying View operator with the literal value 0.  It is assumed that compilers' optimization will eliminate the integer index operations with hard-coded zero values.

**Comment by nmhamster** [comment]
Should we test out the compiler inling/optimization etc?

**Comment by hcedwar** [comment]
Would be good, but not necessary as this Kokkos feature will replace an already non-performing application specific feature.

**Comment by crtrott** [comment]
I just merged the pull request. I think there are a couple more corner cases to be worked on in addition to subviews, but the basic capability seems to be there and the implementation looks fundamentally sound.

**Comment by crtrott** [comment]
First issue I currently see as outstanding: creating degenerated Views. E.g. a 2D view with second dimension==0 would come out as a 1D view right now. We should fix that by having explicit constructors with different number of arguments. 
Second outstanding issue: subviews must be correctly implemented.

**Comment by hcedwar** [comment]
other option based upon related discussion at ISO/C++ meeting is to change the dimension argument types to ptrdiff_t = -1, then deduce rank by the first non-negative input.

**Comment by ndellingwood** [comment]
The dynamic rank view with subview functionality is now available in the kokkos develop branch. 

The DynRankView code is located in kokkos/containers/src/Kokkos_DynRankView.hpp
Sample usage available in the unit tests kokkos/containers/src/TestDynViewAPI.hpp

A couple comments, including changes from Kokkos::View:

 1. Max rank of a DynRankView is 7
 2. The rank of the DynRankView is returned by the function rank()
 3. subdynrankview is the name for the function to create 'subviews' of dynamic rank views. 
 4. Every subdynrankview is returned with LayoutStride

**Comment by hcedwar** [comment]
Fine tune `subdynrankview` for Trilinos/Intrepid to allow and ignore excess `ALL` subview arguments.

**Comment by ndellingwood** [comment]
Modifications to DynRankView and subdynrankview:

1. Enhancement for subdynrankview

Relaxed assumption that number of arguments to a subdynrankview must equal
the rank of the source DynRankView - a subdynrankview can now accept 
greater number of arguments than the source dynrankview rank, the 
additional are ignored.

2. LayoutStride fix for DynRankView

Added createLayout code for LayoutStride input case for construction of DynRankView

3. Additional unit tests added to check LayoutStride DynRankView input to 
subdynrankview, that subdynrankview ranks contract as expected, and that
subdynrankview acts properly when given more arguments than source rank.

**Comment by crtrott** [comment]
Merged into master again. Can this be closed now?
