### ISSUE TITLE
Wrong OpenMP flag for Apple Clang

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#1898]
Recently I have started building Kokkos on Mac OS 10.13 (High Sierra).  The system supplied Apple-Clang parser now supports OpenMP, however the flag Kokkos sets to turn it on appears to be incorrect (from Makefile.kokkos, line 190):
```
KOKKOS_INTERNAL_OPENMP_FLAG := -fopenmp=libomp
```
It should be
```
KOKKOS_INTERNAL_OPENMP_FLAG := -Xpreprocessor -fopenmp
```
Note that while the compiler supports parsing OpenMP, Apple doesn't provide an OpenMP runtime library.  It is simple enough to install that though using one of the various package managers, and then you just add the OpenMP include/library paths to the compile/link like any other library.  With the above change I have successfully built and run Kokkos on High Sierra with OpenMP.

**Comment by etphipp** [comment]
As of now, Kokkos just errors out if you try to build with OpenMP enabled with Apple-Clang:
```
CMake Error at kokkos/cmake/kokkos_arch.cmake:181 (MESSAGE):
  Apple Clang does not support OpenMP.  Use native Clang instead
Call Stack (most recent call first):
  kokkos/cmake/kokkos_tribits.cmake:173 (INCLUDE)
  kokkos/CMakeLists.txt:146 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```
This is fixed rather simply with:
```
diff --git a/cmake/kokkos_arch.cmake b/cmake/kokkos_arch.cmake
index c33247c9..92d1f0bd 100644
--- a/cmake/kokkos_arch.cmake
+++ b/cmake/kokkos_arch.cmake
@@ -177,11 +177,12 @@ IF (KOKKOS_CXX_COMPILER_ID STREQUAL NVIDIA)
 ENDIF()
 
 IF(KOKKOS_ENABLE_OPENMP)
-  IF (KOKKOS_CXX_COMPILER_ID STREQUAL AppleClang)
-    MESSAGE(FATAL_ERROR "Apple Clang does not support OpenMP. Use native Clang instead")
-  ENDIF()
+  #  IF (KOKKOS_CXX_COMPILER_ID STREQUAL AppleClang)
+  #  MESSAGE(FATAL_ERROR "Apple Clang does not support OpenMP. Use native Clang instead")
+  #ENDIF()
   ARCH_FLAGS(
     Clang      -fopenmp=libomp
+    AppleClang -Xpreprocessor -fopenmp
     PGI        -mp
     NVIDIA     -Xcompiler -fopenmp
     Cray       NO-VALUE-SPECIFIED
```

**Comment by dalg24** [comment]
Would you like to open a pull request?

**Comment by dalg24** [comment]
Feel free to reopen if you still have issues with Apple Clang and the OpenMP backend.
