### ISSUE TITLE
deep_copy of stateful data types is unsupportable, document restriction

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#191]
deep_copy of non-trivial data types is dangerous when the non-trivial data type has state data.
This was encountered in the 'ichol' mini-application where a View of managed and allocated Views was given to deep_copy and the byte-wise copy corrupted the reference counting.
This error may be impossible to catch or manage.  
This restriction for not using View of stateful objects must be documented.
An unmanaged View is not stateful so a View of unmanaged Views is OK.

**Comment by crtrott** [comment]
So that means I can't have a view of managed views right?

**Comment by hcedwar** [comment]
Problem is raw memory copying across the CPU/GPU boundary cannot invoke copy constructor so state data cannot be properly updated for the copy operation.

**Comment by hcedwar** [comment]
Requires a discussion in programming guide.
Should be comprehensive discussion of issues associated with using views of non-POD types.
