### ISSUE TITLE
Illegal Address on cuda backend

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#1911]
This issue appears to be related to the combination of relocatable device code and const random access views on the cuda backend. I have attached code that reproduces this issue (just put in the kokkos path in the makefile). 

I won't rule out user error either. I noticed these issues when going from lambdas to functors and my usage of const & for certain members, etc. could be the culprit.

This code runs without error on the openmp backend but fails with tho following on the cuda backend:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaMemcpy( dst , src , n , cudaMemcpyDefault ) error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/dholladay00/repos/inlinlte/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:89
Traceback functionality not available

Aborted (core dumped)
```

[reproducer.zip](https://github.com/kokkos/kokkos/files/2597471/reproducer.zip)

main.cpp:
```c++
#include "extra_data.hh"

// set schedule type
typedef Kokkos::Schedule< Kokkos::Dynamic > schedule;

// team policy (takes a scheduling parameter)
#ifdef KOKKOS_ENABLE_CUDA
typedef Kokkos::TeamPolicy<schedule, Kokkos::LaunchBounds<64,4> > team_policy;
#else 
typedef Kokkos::TeamPolicy<schedule> team_policy;
#endif

typedef team_policy::member_type member_type;

class test_functor {
public:
  const data_t& data;

  test_functor (const data_t& dat)
    : data(dat)
  { }
  
  KOKKOS_INLINE_FUNCTION
  void operator () (const member_type& team) const
  {
    printf("thing: %i \n", data.dat());
  }
};

template <class T>
void do_parallel(T& f, const int size)
{
  team_policy policy(size, Kokkos::AUTO);
  int mem_size = View<int**>::shmem_size(5, 5);
  policy.set_scratch_size(1, Kokkos::PerTeam(mem_size));
  Kokkos::parallel_for ("test functor", policy, f);
  return;
}

int main(int argc, char** argv) {
  Kokkos::initialize();
  {
    data_t dat;
    set_data(dat);
    test_functor f(dat);
    do_parallel(f, 100);
  }
  Kokkos::finalize();
  return 0;
}
```

extra_data.hh:
```c++
#ifndef EXTRA_DATA_HH
#define EXTRA_DATA_HH

#include <Kokkos_Core.hpp>

template <class D, class ... Q>
using View = Kokkos::View<D, Q ... >;
using Kokkos::LayoutLeft;

struct data_t {

  View<const int, Kokkos::MemoryTraits<Kokkos::RandomAccess> > dat;
};

void set_data(data_t& dat);

#endif // EXTRA_DATA_HH
```

extra_data.cpp
```c++
#include "extra_data.hh"

void set_data(data_t& data)
{
  View<int> dat_("dat");

  const int d = 5;

  Kokkos::deep_copy(dat_, d);

  data.dat = dat_;
  return;
}
```

**Comment by mhoemmen** [comment]
It's safer for the functor to capture by value, even on CPU, because that ensures that the View won't fall out of scope and get deallocated.  If you plan on reusing that functor a lot, you could just save the functor somewhere; that would avoid whatever Kokkos::View (shallow) copy overhead there might be.

**Comment by crtrott** [comment]
The overhead should be minimal. I mean its an atomic increment per view + a couple of assignments. If you want to get rid of the atomic you can make the view-member of the functor an unmanaged view.

**Comment by dholladay00** [comment]
@mhoemmen great idea!

Feel free to close this.
