### ISSUE TITLE
UVMSpace without setting CUDA_LAUNCH_BLOCKING warning

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1912]
I believe the following warning is bogus for P100 and V100 GPUs:

```
Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_LAUNCH_BLOCKING=1.
                                  The code must call Cuda::fence() after each kernel
                                  or will likely crash when accessing data on the host.
```

In other words, if I recall correctly P100 and later GPUs will NOT crash when accessing data on the host. Can someone confirm this?

**Comment by crtrott** [comment]
V100 should not. P100 has still some issues I believe. Someone probably should check ...
