### ISSUE TITLE
CMake namespaces (and other modern cmake cleanup)

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#1924]
Best practice (AFAIK) is to namespace targets so that CMake knows the name is intended to be a CMake target, generating getter error messages:

````
target_link_libraries(mylib Kokkos::kokkos)
````

This seems easy enough to add - but I suppose could break a lot of code that expect the target `kokkos` with no namespace. Is it worth exporting both the current un-namspaced target for (compatibility) and a namespaced-target (for good practice)?

**Comment by jjwilke** [comment]
Related to #674

**Comment by jjwilke** [comment]
Separate libs builds did not. 
````
LINK_TARGETS=kokkoscore
````
was the only thing set, leading to a bunch of undefined references on kokkos containers

**Comment by Char-Aznable** [comment]
@jjwilke Is your branch cmake-1924 supposed to tackle the issue mentioned here and those in #674? If so, can you give a big picture of how it works?

**Comment by dalg24** [comment]
> Separate libs builds did not work

@jjwilke Is that still an issue?

**Comment by jjwilke** [comment]
Not still an issue. Separate libs and single lib should still be working.
