### ISSUE TITLE
Question: operator* for Rank-0 views

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#1929]
This got removed in 2016 in favor of just using `v()` for a rank-0 view `v`.
All of the examples were written with `*dt` to access the single element in a rank-0 view.

What was the rationale for removal? It makes sense to me to enable_if an `operator*` function on Rank-0.

**Comment by crtrott** [comment]
It makes view look much more like a pointer than it actually is and was confusing to a lot of people. mdspan doesn't have it either.

**Comment by jjwilke** [comment]
Sounds good. Examples are fixed to use `X()`
