### ISSUE TITLE
Utilizing team shared/scratch memory

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#193]
I am attempting to use team scratch memory. I have a 1D view called `buffer` that uses the scratch memory directly~~, and I want a view of unmanaged views (called `data`) "pointing to" the memory allocated for `buffer`~~. I have attempted but have not been successful. 
```c++
const TeamPolicy<> policy(N, AUTO);
//policy.set_scratch_size(2, PerTeam(size), PerThread(0));
parallel_for(policy.set_scratch_size(2, PerTeam(size), PerThread(0)), ...
{
  View<double*> buffer(team.team_scratch(2), size);
  //View< View<double*, MemoryUnmanaged>** > data(??); // not sure what to put in ??

  // point data at buffer
  //int sum = 0;
  //for (i < a)
  //  for (j < b)
  //    data(i,j) = subview(buffer, pair<int, int>(sum, sum+x(i))
  //    sum += x(i);
});
```

* I have the following runtime error:
  * `ScratchMemorySpace<...>::get_shmem: Failed to allocate 23200 byte(s); remaining capacity is 2900 byte(s)`
* I am using a cuda build of kokkos (develop branch) with cuda 7.5.

**Comment by hcedwar** [comment]
View<...> data is a local variable within a kernel so it should also be unmanaged and constructed with scratch memory.
data( team.team_scratch(2) , NI , NJ );
Assuming View<...> data is team-shared then one of the loops should be an internal parallel_for so the data(i,j) only happens once.

**Comment by dholladay00** [comment]
Thanks, unfortunately I spoke too soon on what the problem actually was. **Please see the revised comment.** 

The problem could be that the 'LEVEL' argument (currently 2) is wrong, or that the team scratch memory space is too small for my use case.

**Comment by crtrott** [comment]
The level argument is currently completely ignored. so it can't be that. But the arguments to set_scratch_size must be in bytes. So you need to multiply that by sizeof(double).

**Comment by dholladay00** [comment]
Oh wow, yes, that did indeed fix that problem. When I add in the `data` view, however:

```c++
const TeamPolicy<> policy(N, AUTO);
//policy.set_scratch_size(2, PerTeam(size), PerThread(0));
parallel_for(policy.set_scratch_size(2, PerTeam(size), PerThread(0)), ...
{
  View<double*> buffer(team.team_scratch(2), size);
  View< View<double*, MemoryUnmanaged>** > data(team.team_scratch(2), size2, size3);
});
```

Fails at runtime with: `ScratchMemorySpace<...>::get_shmem: Failed to allocate 4800 byte(s); remaining capacity is 0 byte(s)`, Is there some amount of padding I need to add to the scratch memory?

If so, is/does it:
* a constant value related to some metadata
* scale with size2*size3

This isn't a guaranteed correlation, but it is potentially worth noting that in this case 4800 = 3*size2*size3*sizeof(double).

**Comment by crtrott** [comment]
Ok first of all it looks like you didn't actually allocate enough in the first case again (i.e. you need to give a size of bytes). Furthermore you only seem to allocate space for the first view not for the others. And third we are doing padding so the way to do this is:
```C++
bytes_per_team = SharedMemViewType<double **>::shmem_size(N1,N2)
```
where SharedMemViewType is a typedef of the view type you want.

**Comment by dholladay00** [comment]
Ah, I see, so rather than me calculating directly, I can let Kokkos do it, that sounds like the right way. 

In terms of not allocating enough memory, my goal in this example is to allow `buffer` be a regular 1D view that stores everything (hopefully 1 large contiguous chunk of memory), but `data` is a view (of views) on `buffer`. This should work out such that `data` should not need any memory allocated to it b/c all of it will be pointing to `buffer`. I apologize for not making that point clear, but essentially my goal is to only allocate memory for the first view, the question is how to accomplish that (perhaps some amount of padding is necessary, but I am not sure).

**Comment by crtrott** [comment]
You still need memory for the second view, in order to allocate space for all the metadata. I.e. the second one would allocate something like size2*size3*sizeof(Kokkos::View<double*,Kokkos::MemoryUnmanaged>).

**Comment by dholladay00** [comment]
Yep, that worked! Thanks for your patience.

```c++
  const Kokkos::TeamPolicy<> policy(10, Kokkos::AUTO());
  int_t byte_size = Kokkos::View<real_t*>::shmem_size(size); // first view
  byte_size += bs*nbr*sizeof(Kokkos::View<real_t*, Kokkos::MemoryUnmanaged>); // 2nd view
  
  Kokkos::parallel_for(policy.set_scratch_size(2, Kokkos::PerTeam(byte_size),
    Kokkos::PerThread(0)), KOKKOS_LAMBDA (const member_type & team)
  {
    Kokkos::View<real_t*> buffer(team.team_scratch(2), size);
    Kokkos::View< Kokkos::View<real_t*, Kokkos::MemoryUnmanaged>**, outer_layout > data(team.team_scratch(2), bs, nbr);
    int_t sum = 0;
    Kokkos::parallel_scan(Kokkos::TeamThreadRange(team, bs),
      [&] (const int_t e, int_t & isum, bool final)
    {
      for (int_t br = 0; br < nbr; ++br) {
        data(e, br) =
          Kokkos::subview(buffer,
                          Kokkos::pair<int_t, int_t>(isum, isum + m(br)));
        isum += m(br);
      }
    }, sum);
  });
```

That use case is solved. Unfortunately there is another use case that is not working at the moment, but now that the other silly mistakes are no longer present, hopefully this can be resolved more quickly. I'll put in a new comment.

**Comment by dholladay00** [comment]
The new use case is almost identical, but the inner view is a 2D view and is not set with a subview. It is as follows:

```c++
  const Kokkos::TeamPolicy<> policy(10, Kokkos::AUTO());
  int_t byte_size = Kokkos::View<real_t*>::shmem_size(size);
  byte_size += bs*nbr*sizeof(Kokkos::View<real_t**, Kokkos::LayoutLeft, Kokkos::MemoryUnmanaged>);
  
  Kokkos::parallel_for(policy.set_scratch_size(2, Kokkos::PerTeam(byte_size),
    Kokkos::PerThread(0)), KOKKOS_LAMBDA (const member_type & team)
  {
    Kokkos::View<real_t*> buffer(team.team_scratch(2), size);
    Kokkos::View< Kokkos::View<real_t**, Kokkos::LayoutLeft, Kokkos::MemoryUnmanaged>**, outer_layout > data(team.team_scratch(2), bs, nbr);
  });
```

Fails at runtime with `C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > insufficient shared memory`
