### ISSUE TITLE
Trouble with scratch space on cuda

### ISSUE THREAD

**Issue by alanw0** [kokkos/kokkos#1932]
Gents,
in the exawind application (nalu-wind) we have been using kokkos' scratch-space mechanism. We're now working on using GPUs, and getting some errors. I've created a pure-kokkos unit-test (self contained, no nalu or stk code) which is shown here:

```
150 using DeviceSpace = Kokkos::Cuda;
151 using DeviceShmem = DeviceSpace::scratch_memory_space;
152 using DynamicScheduleType = Kokkos::Schedule<Kokkos::Dynamic>;
153 using DeviceTeamHandleType = Kokkos::TeamPolicy<DeviceSpace, DynamicScheduleType>::member_type;
154 template <typename T, typename SHMEM>
155 using SharedMemView = Kokkos::View<T, Kokkos::LayoutRight, SHMEM, Kokkos::MemoryUnmanaged>;
156 
157 void do_kokkos_test()
158 {
159 
160   const int bytes_per_team = 0;
161   const int bytes_per_thread = 2048;
162 //  int threads_per_team = 1;
163   unsigned N = 1;
164 
165   Kokkos::TeamPolicy<DeviceSpace> team_exec(N, Kokkos::AUTO);
166 //  team_exec = team_exec.set_scratch_size(0, Kokkos::PerTeam(bytes_per_team), Kokkos::PerThread(bytes_per_thread));
167 
168 std::cout << "entering outer parallel_for, team_size = "<<team_exec.team_size()<<", N = "<< N << ", bytes_per_thread = "<<byt    es_per_thread<<std::endl;
169 
170   Kokkos::parallel_for(team_exec.set_scratch_size(0, Kokkos::PerTeam(bytes_per_team), Kokkos::PerThread(bytes_per_thread)), K    OKKOS_LAMBDA(const DeviceTeamHandleType& team)
171   {
172     printf("outer parallel_for getting shmem view.\n");
173 
174     int len = 50;
175     SharedMemView<double*,DeviceShmem> shview =
176        Kokkos::subview(SharedMemView<double**,DeviceShmem>(team.team_shmem(), team.team_size(), len),
177                        team.team_rank(), Kokkos::ALL());
178 
179     printf("outer parallel_for got shmem view, size = %lu.\n", shview.size());
180   });
181 }
182 
183 TEST_F(Hex8MeshWithNSOFields, teamSize)
184 {
185   do_kokkos_test();
186 }
```

This produces the following error:
ascicgpu10>mpirun -np 1 unittestX --gtest_filter=*teamSize
Note: Google Test filter = *teamSize
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Hex8MeshWithNSOFields
[ RUN      ] Hex8MeshWithNSOFields.teamSize
entering outer parallel_for, team_size = -1, N = 1, bytes_per_thread = 2048
[ascicgpu10:20674] *** Process received signal ***
[ascicgpu10:20674] Signal: Floating point exception (8)
[ascicgpu10:20674] Signal code: Integer divide-by-zero (1)
[ascicgpu10:20674] Failing at address: 0x7bf84d8
[ascicgpu10:20674] [ 0] /lib64/libpthread.so.0[0x305d40f7e0]

If I change line 165 to use threads_per_team=1 instead of Kokkos::AUTO, then it produces this error:

unknown file: Failure
C++ exception with description "Kokkos::Impl::ParallelFor< Cuda > requested too large team size

Help!

**Comment by alanw0** [comment]
FYI to fellow nalu-wind guys @overfelt @sayerhs

**Comment by crtrott** [comment]
Ok the thing is that you ask for so much per_thread storage that Kokkos can't find a legal team_size. It assumes that the minimum team_size*vector_size needs to be 32 (a full warp), but 32*2kB doesn't fit into shared memory, so the team_size comes back as zero. It should throw an error now, but unfortunately just fails.

**Comment by crtrott** [comment]
Two possible solutions: 
 * allow team_sizes < 32, but that would give you horrendous performance
 * throw so you know what went wrong.

I am tending to solution 2, any thoughts? 

The reason that asking explicitly for team_size 1 also throws is that the max_team_size check also starts with a minimum guess of 32, and because that doesn't fit returns a zero indicating nothing fits.

**Comment by mhoemmen** [comment]
@alanw0 Oh wow, when you were explaining this to me today, I didn't realize you wanted 2k per _thread_.  That's way too much.

**Comment by alanw0** [comment]
@crtrott in 'team_size*vector_size'  is vector_size the bytes of per_thread storage? When we call 'set_scratch-size' we're passing '0' as the first argument. Would it help to pass a different value there?
@mhoemmen we've been using a model where each thread computes the linear-system contribution for an element of the mesh. In that model, scratch space needs to hold the lhs and rhs contributions, as well as element data used in the calculation (gathered nodal coords, grad-op, etc.). 2k doesn't seem unreasonable. When we do the momentum equation (3 dof per mesh node) we might actually need more like 5kb or 6kb. Do you propose splitting an element calculation among multiple threads? Or just don't use scratch space? Or (if possible) have scratch space use a higher-level (larger) cache or memory area?

**Comment by alanw0** [comment]
When I use '1' for the level parameter, it runs but it is printing out a bunch of messages like this:

```
ScratchMemorySpace<...>::get_shmem: Failed to allocate 25600 byte(s); remaining capacity is 0 byte(s)
```
It prints this the first time, i.e., it appears as though it starts out with 0 bytes capacity.
I haven't tried accessing the view I get from that call, but this doesn't look good.

**Comment by crtrott** [comment]
use team_scratch(1) instead of team_shmem (which is equivalent to team_scratch(0)
