### ISSUE TITLE
profiling label

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1935]
random functor does not have labels.
```
N6Kokkos4Impl25fill_random_functor_rangeINS_4ViewIPPPNS_7complexIdEEJNS_10LayoutLeftENS_6OpenMPEEEENS_22Random_XorShift64_PoolIS9_EELi128ELi3ElEE (ParFor)           1.17556         2964         0.00040   0.818   0.573 
```

**Comment by DavidPoliakoff** [comment]
@dhollman it gives some false positives, but `match callExpr(callee(unresolvedLookupExpr(hasAnyDeclaration(namedDecl(matchesName("Kokkos::parallel_"))))),unless(anyOf(hasDescendant(stringLiteral()),hasAnyArgument(hasDescendant(declRefExpr(hasType(asString("const char*"))))))))` gets us what we want. 

I think the rule should be "if we're in Kokkos, unless we're in a forwarding layer which calls another Kokkos::parallel_* construct, calls to Kokkos::parallel_* must name their kernels." Does that sound like the semantics we want?

**Comment by dhollman** [comment]
Seems reasonable :-)

**Comment by dalg24** [comment]
@DavidPoliakoff will look into this
