### ISSUE TITLE
Add a way to disable memory leak output

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#194]
If Sierra crashes, Kokkos outputs a bunch of error messages relating to memory leaks (because the application terminated before Trilinos or Sierra could let go of its Kokkos::View instances).  The crash is not Kokkos' fault, but Sierra would still like a way to shut off this output.  See Sierra Issue 14037.

https://prod.sandia.gov/sierra-trac/ticket/14037

**Comment by hcedwar** [comment]
Wait for conversion to new View and see if the revised behavior is sufficient.

**Comment by mhoemmen** [comment]
Any ETI on new View completion?

**Comment by hcedwar** [comment]
Just waiting for Trilinos to convert to new View.  The View is ready on the master branch and in the Trilinos snapshot.  As soon as Trilinos converts will will delete the old View.

**Comment by mhoemmen** [comment]
Thanks Carter!  What does "Trilinos converts" mean?

**Comment by crtrott** [comment]
We are pretty close to getting there. Might go in tomorrow.

**Comment by mhoemmen** [comment]
@crtrott YAY :-D

**Comment by crtrott** [comment]
Closing this issue, tested that new view does indeed not print any warnings or errors.
