### ISSUE TITLE
tuple of scratch memory view on CUDA backend causes memory error

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#1941]
This might be related to #1774. This only happens with nvcc 9.2 but not with clang 7 + cuda 9.2:
```c++
#include <Kokkos_Core.hpp>

using ExecutionSpace = Kokkos::DefaultExecutionSpace;

template < class E > struct Foo {

  using UT = Kokkos::MemoryTraits<Kokkos::Unmanaged>;
  using Space = typename E::scratch_memory_space;
  using Sview = Kokkos::View<int,Space,UT>;
  std::tuple<Sview> data_;

  template < class Team > KOKKOS_FUNCTION Foo(const Team& team) 
    :data_(std::tuple_element_t<0,decltype(data_)>(team.team_scratch(1)))
  {
    std::get<0>(data_)() = 33;
    printf("%10d\n", std::get<0>(data_)());
  }
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  using TeamPolicy = Kokkos::TeamPolicy<ExecutionSpace>;
  using Team = TeamPolicy::member_type;
  auto policy = TeamPolicy(8,8).
    set_scratch_size(0,Kokkos::PerTeam(10000)).
    set_scratch_size(1,Kokkos::PerTeam(100000));
  Kokkos::parallel_for(policy, KOKKOS_LAMBDA(const Team& team) {
    auto f = Foo<ExecutionSpace>(team);
  });

  Kokkos::fence();


  } Kokkos::finalize();
}

```
cuda-gdb gives `Thread 1 "testTuple" received signal SIGTRAP, Trace/breakpoint trap.` and traces back to the TeamPolicy parallel_for launch but no further. 

This does look like a compiler bug. If so, I'd like to report it to nvidia but I don't know how to remove all the kokkos stuff to produce a native cuda example. Any help is appreciated.

**Comment by crtrott** [comment]
doesn't look like this works with CUDA 10 either ...

**Comment by Char-Aznable** [comment]
@crtrott Can you suggest a way to make a native cuda example of this so that I can file a bug report to nvidia? Thanks!

**Comment by Char-Aznable** [comment]
I just found that using `thrust::tuple` instead of `std::tuple` can get nvcc to work with the example

**Comment by dhollman** [comment]
@Char-Aznable I'm having trouble finding anywhere that guarantees `std::tuple` will work with `nvcc` or Cuda in general.  Can you point me to where you found this?

I don't think the `--expt-relaxed-constexpr` flag applies here, since the `Kokkos::View` constructor that takes a scratch space isn't `constexpr` (nor can it be) and thus the template instantiation of the `std::tuple` constructor can't be `constexpr` either.

**Comment by Char-Aznable** [comment]
https://docs.nvidia.com/cuda/archive/9.2/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features

**Comment by dhollman** [comment]
Oh! That's excellent; I wasn't aware of that.  I'll try to see if I can figure out what's going on here.  I suspect there's a subtle layout bug or something relating to empty base class optimization; shouldn't be too hard to come up with a reproducer.

**Comment by dalg24** [comment]
Need to test with CUDA 11

**Comment by ajpowelsnl** [comment]
### Reproducing the failure with different versions of Cuda and gcc, and std::tuple 


_**Reproducer with sems-cuda/11.1, sems-gcc/9.2.0, & std::tuple:**_

`./reproducer_1941.cuda
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorLaunchFailure): unspecified launch failure /ascldap/users/ajpowel/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:140
Traceback functionality not available`

_**Reproducer with sems-cuda/10.1, sems-gcc/7.2.0, & std::tuple:**_


`./reproducer_1941.cuda 
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorLaunchFailure): unspecified launch failure /ascldap/users/ajpowel/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:140
Traceback functionality not available

Aborted (core dumped)`


**BUILD WARNING:**

reproducer_1941.cpp(18): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during instantiation of "Foo<E>::Foo(const Team &) [with E=ExecutionSpace, Team=Kokkos::Impl::CudaTeamMember]" 
(35): here

_**Reproducer with sems-cuda/9.2, sems-gcc/7.2.0, & std::tuple:**_

./reproducer_1941.cuda 
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorLaunchFailure): unspecified launch failure /ascldap/users/ajpowel/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:140
Traceback functionality not available

Aborted (core dumped)




**BUILD WARNING:**

reproducer_1941.cpp(18): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during instantiation of "Foo<E>::Foo(const Team &) [with E=ExecutionSpace, Team=Kokkos::Impl::CudaTeamMember]" 
(35): here

**Comment by ajpowelsnl** [comment]
```thrust::tuple``` (implementing with #include <thrust/tuple.h> and #include <thrust/pair.h>) and ```cuda::std::tuple``` (implementing with #include <cuda/std/tuple>) are drop-in replacements for ```std::tuple```.
