### ISSUE TITLE
CUDA Team Scan gives wrong values on Volta with -G compile flag

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1942]
CUDA Team Scan gives wrong values on Volta. Here are the results for a simple team scan where all the values are 1. Notice how the V100 results have a bunch of 3's instead of 7, 11, 15, 19, 23 etc. while P100 is completely sequential:

Pascal| Volta
-- | --
0 | 0
1 | 1
2 | 2
3 | 3
4 | 4
5 | 5
6 | 6
7 | 3
8 | 8
9 | 9
10 | 10
11 | 3
12 | 12
13 | 13
14 | 14
15 | 3
16 | 16
17 | 17
18 | 18
19 | 3
20 | 20
21 | 21
22 | 22
23 | 3
24 | 24
25 | 25
26 | 26
27 | 3
28 | 12
29 | 13
30 | 14
31 | 3

This shows up in LAMMPS even for the simple Lennard Jones benchmark, where it gives the wrong number of ghost atoms:

https://github.com/lammps/lammps/blob/1c795a6be3c590eb83666c94f6553f02a07f66e1/src/KOKKOS/comm_kokkos.cpp#L791

**Comment by stanmoore1** [comment]
This bug seems to only show up when compiling with the "-G" flag. Here is a tiny reproducer:
[scan_wrong.cpp.txt](https://github.com/kokkos/kokkos/files/2681931/scan_wrong.cpp.txt)

**Comment by stanmoore1** [comment]
See https://github.com/kokkos/kokkos/issues/1410 for an explanation of why I need to use the `-G` flag.

**Comment by crtrott** [comment]
We can look into it. But -G is not officially supported for Kokkos, since it most of the time doesn't work ...

**Comment by crtrott** [comment]
Ok I got a fix for this.

**Comment by crtrott** [comment]
Actually we were just lucky that it generally worked on Volta without -G. There were still warp syncs missing in the scan.

**Comment by stanmoore1** [comment]
@crtrott glad you fixed this!!

**Comment by stanmoore1** [comment]
@crtrott can you post your code that fixes this? I'd like to see if it also fixes #1949.

**Comment by crtrott** [comment]
Jup will issue a pull request latest tomorrow.

**Comment by crtrott** [comment]
Should be fixed now.
