### ISSUE TITLE
Non-deterministic behavior on Volta, runs fine on Pascal

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1949]
When running the SNAP potential in LAMMPS, I'm seeing non-deterministic behavior on Volta GPUs, as well as `NaNs` crashing the run in some cases. On Pascal, it is 100% deterministic and gives the same numerics as the CPU version of the code. Here is a reproducer for V100:

[snap.zip](https://github.com/kokkos/kokkos/files/2695815/snap.zip)
```
bsub -I -n 40 -q rhel7W ~/lammps/src/lmp_kokkos_cuda_mpi -in in.snap -k on g 1 -sf kk -pk kokkos newton on neigh half
```

This has been difficult to debug due to a partially broken debugging toolchain, see:

#1948 Invalid Configuration when resizing views with KOKKOS_DEBUG=yes 
#1942 CUDA Team Scan gives wrong values on Volta with -G compile flag
#1461 cuda-gdb internal error when trying to debug
#1410 Compiler internal error with -G flag

**Comment by stanmoore1** [comment]
This issue is probably related to #1461.

**Comment by stanmoore1** [comment]
Just to clarify, the attached reproducer is a different input deck than the standard SNAP examples in LAMMPS and ExaMiniMD and has a larger number of bispectrum coefficients. The standard SNAP examples run fine on Volta.

**Comment by crtrott** [comment]
Should now be fixed in develop. Please confirm.

**Comment by stanmoore1** [comment]
@crtrott Now I am getting a view bounds error, so there may also be an issue in the LAMMPS SNAP code. I will investigate more.

```
:0: : block: [690,0,0], thread: [0,4,0] Assertion `View bounds error of view atom:f` failed.
:0: : block: [690,0,0], thread: [0,5,0] Assertion `View bounds error of view atom:f` failed.
:0: : block: [690,0,0], thread: [0,6,0] Assertion `View bounds error of view atom:f` failed.
:0: : block: [690,0,0], thread: [0,7,0] Assertion `View bounds error of view atom:f` failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available
```

**Comment by stanmoore1** [comment]
For whatever reason, this seems to make the issue go away, at least for the test case I ran:

```diff
$ git diff KOKKOS/
diff --git a/src/KOKKOS/sna_kokkos_impl.h b/src/KOKKOS/sna_kokkos_impl.h
index 6a19c57..0588999 100644
--- a/src/KOKKOS/sna_kokkos_impl.h
+++ b/src/KOKKOS/sna_kokkos_impl.h
@@ -1059,7 +1059,7 @@ T_INT SNAKokkos<DeviceType>::size_team_scratch_arrays() {

   size += t_sna_3d::shmem_size(jdim,jdim,jdim); // uarraytot_r_a
   size += t_sna_3d::shmem_size(jdim,jdim,jdim); // uarraytot_i_a
-  size += t_sna_5d::shmem_size(jdim,jdim,jdim,jdim,jdim); // zarray_r
+  size += t_sna_5d::shmem_size(jdim+1,jdim+1,jdim+1,jdim+1,jdim+1); // zarray_r
   size += t_sna_5d::shmem_size(jdim,jdim,jdim,jdim,jdim); // zarray_i
   size += Kokkos::View<double*, Kokkos::LayoutRight, DeviceType>::shmem_size(nc
   size += t_sna_3d::shmem_size(jdim,jdim,jdim); // barray
```

However, there should be a view bounds error if the memory isn't large enough. Perhaps the size of the allocation from `::shmem` is incorrect?

**Comment by stanmoore1** [comment]
Using bisection, I've found that if I increase the size of the allocation by more than about 1 MB, it is deterministic, any less and it is non-deterministic.

**Comment by crtrott** [comment]
The particular change of increasing zarray didn't didn't fix it for me.

**Comment by crtrott** [comment]
I still don't know where the problem is, but we need to track this down. My gut feeling is there is a 50/50 chance that something is wrong with Kokkos's scratch memory allocation in extreme cases.

**Comment by crtrott** [comment]
Ok found it. Its an integer overflow in part of the scratch offset calculations. This only happens if the total amount of required scratch space goes beyond a certain limit, something which may not be triggered on Pascal.

**Comment by stanmoore1** [comment]
@crtrott Thanks!!!!

**Comment by stanmoore1** [comment]
I noticed I actually do see similar non-determinism on Pascal in some cases. The fix provided by @crtrott fixes Pascal as well.
