### ISSUE TITLE
Rename team policy set_scratch_size.

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#195]
The fact that:

Kokkos::TeamPolicy<DeviceSpace> policy(size, Kokkos::AUTO);
policy.set_scratch_size(0, Kokkos::PerTeam(bytes_per_team), Kokkos::PerThread(bytes_per_thread));
Kokkos::parallel_for(policy, /* lambda omitted */);

will not have the scratch space allocated inside the lambda is quite confusing as a user. If the requirement that the return value of the set_scratch_size() call is used for the policy passed to the parallel_for remains I think it would be more clear to name it get_policy_with_scratch_size() or something that makes it clear it is not setting member data on the existing policy.

**Comment by hcedwar** [comment]
Agreed.  Policy parameters should be defined at construction.

**Comment by hcedwar** [comment]
Issue will be resolved with refactored API to move all options in constructor.

**Comment by crtrott** [comment]
Replaced by #453
