### ISSUE TITLE
atomic_fetch_oper has no case for Kokkos::complex<double> or other 16-byte types

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1951]
`Kokkos::atomic_fetch_oper` used to build for `Kokkos::complex<double>`, but does not any more.  See https://github.com/trilinos/Trilinos/issues/4094 .

[The implementation of](https://github.com/kokkos/kokkos/blob/43701557e655e3c80fa8f5fda16e7f0df4a5be67/core/src/impl/Kokkos_Atomic_Generic.hpp#L233)`atomic_fetch_oper` has three cases:
  1. `sizeof(T) != sizeof(int) && sizeof(T) == sizeof(unsigned long long int)` (i.e., `sizeof(T) == 8`)
  2. `sizeof(T) == sizeof(int)` (usually `sizeof(T) == 4`)
  3. `sizeof(T) != 4 && sizeof(T) != 8 && sizeof(T) != 16` (the last case is protected by macros, which I verified are all defined, for GCC 4.9.3 and OpenMP in a debug build at least)

This means that, as long as the aforementioned macros are all defined, types of size 16 bytes are not covered.  I was able to get Tpetra to build just fine with `Scalar=complex<double>` by deleting the `sizeof(T) != 16` case in Kokkos.  I am planning to do just that and to patch the version of Kokkos in Trilinos.  If you have any objections, please let me know.  Thanks!

**Comment by crtrott** [comment]
No sounds good. Seems there is a specialization for 128 bit missing which was supposed to be there.

**Comment by mhoemmen** [comment]
@crtrott Was the plan to use 128-bit CAS with that or what?

**Comment by ndellingwood** [comment]
Also see trilinos/Trilinos#4095

**Comment by mhoemmen** [comment]
@ndellingwood @crtrott https://github.com/kokkos/kokkos/pull/1953

**Comment by ndellingwood** [comment]
I'm looking at the testing scripts to see how this slipped through integration testing. We test Complex with the Serial backend using an Intel compiler (gcc is skipped) with these settings:

`-D Teuchos_ENABLE_COMPLEX=${COMPLEX} `
`  -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=${COMPLEX}`

 From Mark's comment in the issue this must occur due to some of the macros guarding the `sizeof(T) != 16` not being defined for the Intel compiler.

Though this issue is addressed by #1953 we will add an extra gcc complex build to promotion testing.

**Comment by mhoemmen** [comment]
@ndellingwood Please don't use these flags any more.  Use `Trilinos_ENABLE_COMPLEX_DOUBLE` to control whether `Scalar=complex<double>` is enabled.  Thanks!

**Comment by ndellingwood** [comment]
@mhoemmen thanks for suggestion, put in PR trilinos/Trilinos#4097 to update the scripts and kokkos/kokkos-kernels#363 with an extra script for extra complex testing with gcc + cuda compilers.

**Comment by mhoemmen** [comment]
Awesome, thanks @ndellingwood ! :D

**Comment by mhoemmen** [comment]
btw here is some context: https://github.com/trilinos/Trilinos/issues/4059 .  We've had this issue or others like it pop up before.  @bartlettroscoe and I have been working for a while on consolidating those CMake options and adding error checks so as to prevent untested combinations of options that lead to post-configuration build errors.

**Comment by crtrott** [comment]
We need a Kokkos level test making sure this works. I.e. testing the atomic_fetch_oper stuff. We probably test atomic_add etc, but those will take a different path.
