### ISSUE TITLE
deep_copy of DualView will not compile with deprecated code disabled

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#1952]
@crtrott 

When deprecated code is disabled DualView::modified_flags is a protected member variable but both specializations of deep_copy at the end of Kokkos_DualView.hpp attempt to directly access src.modified_flags. This fails to compile. It can be worked around by making the two specializations of deep_copy friend functions, not sure if that is the desired fix though.

**Comment by crtrott** [comment]
args....

**Comment by mhoemmen** [comment]
I'm starting on a fix for some Tpetra BlockCrs stuff that doesn't build with deprecated code disabled.  Maybe we can just fix this in Trilinos and disable deprecated Kokkos code there by default.

**Comment by mhoemmen** [comment]
@micahahoward

**Comment by ndellingwood** [comment]
I'll add a PR with potential fix in a moment.

**Comment by ndellingwood** [comment]
Added #1954 with possible fix. Added a unit test to check the `dual_view`'s `deep_copy` and it passed with deprecated code disabled.
