### ISSUE TITLE
ROCm/hc_math_std.hpp does not do what it should do?

### ISSUE THREAD

**Issue by finkandreas** [kokkos/kokkos#1955]
Simple test program:
```
#include <ROCm/hc_math_std.hpp>

int main() {
  long double v=0; // does not compile
  //double v=0;  // compiles but does NOT call the "overridden" std::isinf from hc_math_std.hpp!!!
  auto inf = std::isinf(v);
  return 0;
}
```
The error message when trying to compile it with `long double`:
```
In file included from test_rocm.cpp:1:
/scratch/anfink/build/20181213_cpu/trilinos/src/packages/kokkos/core/src/ROCm/hc_math_std.hpp:244:1: error: call to 'isinf' is ambiguous
HC_MATH_WRAPPER_FP_OVERLOAD_TQ(isinf, bool, x)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/anfink/build/20181213_cpu/trilinos/src/packages/kokkos/core/src/ROCm/hc_math_std.hpp:71:10: note: expanded from macro 'HC_MATH_WRAPPER_FP_OVERLOAD_TQ'
  return hc::precise_math::function(arg1); \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
test_rocm.cpp:6:19: note: in instantiation of function template specialization 'std::isinf<long double>' requested here
  auto inf = std::isinf(v);
                  ^
/opt/rocm/bin/../hcc/include/kalmar_math.h:1203:13: note: candidate function
        int isinf(__fp16 x) { return __hc_isinf_half(x); }
            ^
/opt/rocm/bin/../hcc/include/kalmar_math.h:1206:13: note: candidate function
        int isinf(float x) { return __hc_isinf(x); }
            ^
/opt/rocm/bin/../hcc/include/kalmar_math.h:1209:13: note: candidate function
        int isinf(double x) { return __hc_isinf_double(x); }
            ^
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/cmath:604:3: note: candidate function
  isinf(long double __x)
  ^
/usr/include/bits/mathcalls.h:202:19: note: candidate function
__MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
                  ^
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/cmath:591:3: note: candidate function
  isinf(float __x)
  ^
1 error generated.
```

Compiling it with the `long double` line commented, and enable the line with `double` will compile, however it is NOT picking up the template implementation, but use the normal `std::isinf` from `<cmath>`.

In general I have trouble compiling kokkos-kernels, which are exactly the same as in the test program (basically kokkos-kernel source files include `kokkos-kernels/src/Kokkos_ArithTraits.hpp` which in turn has an explicit instantion for `long double`, which would fail with the above error message.)

In my understanding of the C++-standard, it is also forbidden to mess with the std namespace...

**Comment by crtrott** [comment]
The ROCm backend is highly experimental, and we are still fighting with serious compiler issues. I highly doubt that we can make KokkosKernels work right now currently. Sorry. 
Based on extensive discussions with AMD we will start a new backend using the HIP compiler front end. That front end is more mature and less buggy as of now.

**Comment by ndellingwood** [comment]
@crtrott I'm marking this as compiler issue, should we also mark this as won't fix as the plan is to start the backend using HIP since it is less buggy?

**Comment by finkandreas** [comment]
Although you have flagged it as a compiler issue I want to add that it is not a compiler issue. The compiler is behaving correctly by throwing the error message.
The approach that you are taking by overriding math functions in the std namespace is neither allowed by the standard nor is it easily possible to do so.
When you look into the file `hc_math_std.hpp` you can see that you try to override math functions in the std namespace with your own implementations. This is not valid C++ code (which gets discarded by SFINAE  for `v==double` but does not get discarded for `v==long double`, hence leads to the error).

**Comment by masterleinad** [comment]
ROCm is not supported anymore and this file is not used anywhere.
