### ISSUE TITLE
incompatible assignment between scratch space and its main memory space

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1960]
I have assignment error when I do 
```
Kokkos::View<double*,Kokkos::OpenMP> A;
Kokkos::View<double*,typename Kokkos::OpenMP::scratch_memory_space>B; 
// B is correctly constructed within a team policy and it is unmanaged.
A = B; // this does not work in the functor. 
```

**Comment by crtrott** [comment]
It is not supposed to work.

**Comment by mhoemmen** [comment]
@kyungjoo-kim Would it make sense to use AnonymousSpace for A here?

**Comment by kyungjoo-kim** [comment]
Do we have AnonymousSpace in Kokkos ? I had this question while modifying Tpetra BlockCrs in            
https://github.com/trilinos/Trilinos/blob/a330c2ab9dcdb192f97cb3d189a14bc842464300/packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp#L3056

From that code, 
```
/// packRowForBlockCrs has template arguments of execution space.
 const size_t numBytes = packRowForBlockCrs<impl_scalar_type,LO,GO,host_exec> 
              (exportsByteHost, // this view has host_exec and its interface asked a view with host exec space
               offset(i), 
               numEnt, 
               // gblColInds has host_exec::scratch_space but the interface requires host_exec;
               // so here I wrap the view with host_exec. 
               Kokkos::View<const GO*,host_exec>(gblColInds.data(), maxRowLength), 
               Kokkos::View<const impl_scalar_type*,host_exec>(valsRaw, numEnt*blockSize*blockSize),
               numBytesPerValue, 
               blockSize);
```
I just thoguht exec_space::scratch_space is compatible to exec_space::memory_space. As the original view with scratch space is unmanaged, the assignment is supposed to be okay. That was my thought. If Kokkos provides a compatible assignment for "unmanaged" views of these memory space, the above code can reduce unnecessary wrapping and it is easier to understand the code.

**Comment by crtrott** [comment]
You can use `Kokkos::AnonymousSpace`
