### ISSUE TITLE
Add systemtap markers to Kokkos

### ISSUE THREAD

**Issue by wcohen** [kokkos/kokkos#1961]
The kokkos profiling and instrumentation mechanism seems like it really helpful in diagnosing performance issues.  It would be nice to extend that instrumentation to allow SystemTap to hook into those same locations.  There are several advantages with the SystemTap instrumentation:

  -can instrument places outside the kokkkos library, such as other software libraries and the kernel
  -can instrument already running application
  -can export data via prometheus for monitoring purposes (for example track amount of time required for iterations of a particular phases of a computation)

I have a WIP on a github branch: https://github.com/wcohen/kokkos/tree/wcohen/systemtap

However, I don't have experience with cmake and the code doesn't have the logic implemented to trigger the machine generation of probes.h and probes.o files and linking them in properly.

**Comment by crtrott** [comment]
Hi

thanks for your work on this. Here is a question though:
would it be enough to write a tool in Kokkos tools for the meta instrumentation similar, to how we use it to map our instrumentation to vtunes instrumentation? The reason I ask is because that was exactly one of the purposes of those things. Our user base has at least 5 or 6 different prefered instrumentation mechanism. This includes vtune, NVIDIAs thingy, TAU, some Cray stuff, vampire, HPCToolkit and some other ones. Instead of littering Kokkos core with all those different ones we can just write meta instrumentation in those tools. 

There is an argument to be made that systemtap may fall into a different category due to its close ties to Linux distributions, but I'd like us to discuss the pros and cons of doing this in Kokkos core proper vs. doing a meta tool.

**Comment by wcohen** [comment]
Yes, kokkos-tools shared libraries give a flexible way to plug the various consumers of the information into the same instrumentation points that works across a variety of environments.

The kokkos-tools have functions defined for the instrument information required. For those tools there is an idea of the subset of instrumentation points needed.  However, for the systemtap instrumentation it would end up have a stub function for systemtap instrumentation for every possible instrumentation point whether it is actively used or not.

Using the shared library approach requires that any application that might need to be instrumented would need to be started with the instrumentation shared library.  Normal systemtap user-space instrumentation doesn't have that requirement allowing systemtap to instrument a executable  after it has already started execution. Also systemtap instrumentation can also monitor an executable everytime it starts up.

If things are properly implemented with the systemtap userspace markers probes, then equivalent dtrace probes would also be available from the same code changes.

**Comment by crtrott** [comment]
What do you mean needing to be started with the shared library? Just the "you need to set the environment variable" part? Is that the only real drawback?

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Instead of littering Kokkos core with all those different ones we can just write meta instrumentation in those tools.

See also https://github.com/kokkos/kokkos-tools/pull/46 .  Would we want to handle Caliper in the same way?

**Comment by wcohen** [comment]
Hi,

This morning I made a fork of kokkos-tools and have the wcohen/systemtap branch with the systemtap support added (https://github.com/wcohen/kokkos-tools/tree/wcohen/systemtap).  The instrumentation points are visible to systemtap:

$ stap -L 'process("./kp_systemtap_connector.so").mark("*")' 
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("allocate_data") $arg1:long $arg2:long $arg3:long $arg4:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("begin_deep_copy") $arg1:long $arg2:long $arg3:long $arg4:long $arg5:long $arg6:long $arg7:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("begin_parallel_for") $arg1:long $arg2:long $arg3:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("begin_parallel_reduce") $arg1:long $arg2:long $arg3:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("begin_parallel_scan") $arg1:long $arg2:long $arg3:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("create_profile_section") $arg1:long $arg2:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("deallocate_data") $arg1:long $arg2:long $arg3:long $arg4:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("destroy_profile_section") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("end_deep_copy")
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("end_parallel_for") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("end_parallel_reduce") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("end_parallel_scan") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("finalize_library")
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("init_library") $arg1:long $arg2:long $arg3:long $arg4:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("pop_profile_region")
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("profile_event") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("push_profile_region") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("start_profile_section") $arg1:long
process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("stop_profile_section") $arg1:long


One can write a toy systemtap script to tally the number of times that each probe point is encountered and have that running in one window:

sudo stap -e 'global counts; probe process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("*"){ counts[pn()] <<< 1}'

In another window set the KOKKOS_PROFILE_LIBRARY and run an example:

$ export KOKKOS_PROFILE_LIBRARY=/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so
$ ./07_Exercise.cuda 
  Total size S = 262144 N = 256 M = 1024 E = 1024
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
  Computed result for 256 x 1024 x 1024 is 268435456.000000
  N( 256 ) M( 1024 ) E( 1024 ) nrepeat ( 100 ) problem( 2157.97 MB ) time( 3.22651 s ) bandwidth( 66.8824 GB/s )

Go back to the window running the systemtap script hit control-c and get the following output:


$ sudo stap -e 'global counts; probe process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("*"){ counts[pn()] <<< 1}'
[sudo] password for wcohen: 
^Ccounts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("begin_parallel_reduce")"] @count=100 @min=1 @max=1 @sum=100 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("end_parallel_reduce")"] @count=100 @min=1 @max=1 @sum=100 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("allocate_data")"] @count=10 @min=1 @max=1 @sum=10 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("begin_parallel_for")"] @count=6 @min=1 @max=1 @sum=6 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("end_parallel_for")"] @count=6 @min=1 @max=1 @sum=6 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("deallocate_data")"] @count=6 @min=1 @max=1 @sum=6 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("init_library")"] @count=1 @min=1 @max=1 @sum=1 @avg=1
counts["process("/home/wcohen/hpc/kokkos-tools/src/tools/systemtap-connector/kp_systemtap_connector.so").mark("finalize_library")"] @count=1 @min=1 @max=1 @sum=1 @avg=1

**Comment by DavidPoliakoff** [comment]
I'm closing this, if people want further work in Kokkos for this they're free to ask
