### ISSUE TITLE
1st Kokkos Usergroup Meeting April 23rd-25th ABQ NM

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#1962]
|||
|---|---| 
|Announcement: 	|**First Kokkos Usergroup Meeting**|
|Date: 			|**23rd-25th of April 2019**|
|Location: 		|**Sandia National Laboratories, Albuquerque NM, USA**|
|Registration:		| CLOSED |
||Alternative send email to celmont@sandia.gov|
|Address:  | 1450 Innovation Pkwy SE Albuquerque, NM 87123 (https://goo.gl/maps/n3vGtMBFSRk)|
|Webmeeting: | https://meeting.sandia.gov/celmont/G8TFB38V | 

The Kokkos team is announcing the first Kokkos Usergroup Meeting to be held in Albuquerque New Mexico, USA April 23rd through 25th. The meeting will give the growing Kokkos community a chance to present progress in adopting Kokkos, exchange experiences, discuss challenges and help set priorities for the future roadmap of Kokkos. Projects are invited to give a 20 minute presentation. Application talks are encouraged to focus on technical and algorithmic challenges in adopting Kokkos and how Kokkos’s capabilities were used to overcome those. 
The tentative schedule is as follows:

**Tuesday 23rd**

Time | Activity | Presenter
-- | -- | --
8:30 | Registration / Arriving | 
9:00 | Welcome | Christian Trott
9:15 | Keynote: AMTPPL  - Evaluating a Possible Exascale Abstraction Using Uintah | Martin Berzins
10:00 | Evacuation Drill | --
10:15 | Break |  --
10:30 | Kokkos Status | Christian Trott
11:15 | Kokkos Kernels Status | Siva Rajamanickam
12:00 | Lunch | --
1:15 | Kokkos Tasking | David Hollman
1:50 | Kokkos Resilience | Jeff Miles
2:15 | Tpetra: Distributed Linear Algebra | Mark Hoemmen
2:40 | Break |  --
3:00 | MueLu: Multigrid PreConditioners | Chris Siefert
3:25 | Panzer: | Roger Pawloski
3:55 | Sparten: | Keita Teranishi
4:20 | Cabana:  | Stuart Slattery
4:45 | Discussion |  --

**Wednesday 24th**

Time | Activity | Presenter
-- | -- | --
8:30 | Registration
9:00 | Welcome |  --
9:10 | Exawind: Computational Fluid Dynamics | Luc Berger-Vergiat
9:35 | Albany: Implicit Unstructured FE | Jerry Watkins
10:00 | Empire | Nathan Roberts
10:25 | Break |  --
10:45 | LAMMPS: Molecular Dynamics | Steve Plimpton
11:10 | K-Athena: astrophysical magnetohydrodynamics | Philipp Grete
11:35 | ARK and ppkMHD | Pierre Kestner
12:00 | Lunch |  --
13:15 | C++ Future | David Hollman
14:00 | Kokkos Roadmap | Christian Trott
14:45 | Break |  --
15:00 | Kokkos Kernels Roadmap | Siva Rajamanickam
16:00 | Kokkos Tools |  Christian Trott
16:40 | Discussion |  --

**Thursday 25th**

Time | Activity | Presenter
-- | -- | --
9:00 | Welcome/Day | --
9:10 | Zoltan2 | Michel de Messieres
9:35 | ROL | Greg van Winkel
10:00 | MTGL Kokkos | Jonathan Berry
10:25 | Break |  --
10:30 | GEMMA  | --  
10:55 | Cmake Issues | Damien Lebrun-Grandie
11:45 | Lunch | --  
13:10 | Build System Updates | Jeremiah Wilke
13:35 | User Discussion Biggest Issues
14:10 | User  Issues/Roadmap alignment
14:45 | Break |  --
15:00 | Issue Focus Groups?? | --

The Kokkos Team will also be available on the 22nd and 26th for project specific meetings. Please request such a meeting if you are interested.

Since this is the first Usergroup meeting we are not sure what attendance level to expect. 

For questions please send an email to crtrott@sandia.gov 

We are looking forward to seeing you in Albuquerque

Christian Trott		
PI Kokkos Core			

Siva Rajamanickam
PI Kokkos Kernels

Si Hammond
PI Kokkos Tools

**Comment by crtrott** [comment]
# Registration Information 

Each team member has to register separately. Only one member per team should indicate they want to present. Until we have a website set up you can send an email to celmont@sandia.gov to register. We would kindly ask to register soon. If the registration rate is high, we may need to book alternative facilities, to the one we currently have planned - which would be limited to about 50 participants. 

•	Name
•	Address
•	Email address
•	Institution
•	Nationality
•	Project/Code
•	Project Website
•	Want to give a talk
•	Could attend on the 25th
•	Interested in project specific meeting on the 25th or 26th

**Comment by crtrott** [comment]
[UsergroupMeeting-Announcement.pdf](https://github.com/kokkos/kokkos/files/2783891/UsergroupMeeting-Announcement.pdf)

**Comment by crtrott** [comment]
We had enough registrations and interest in providing talks that the hinted at extension for a day seemed wise, so I did that. It also gives us more time to discuss Kokkos priorities and directions with users with feedback opportunities.

**Comment by crtrott** [comment]
Hi all,

It is not quite 3 weeks until our first Kokkos usergroup meeting and we have about 60 people registered. At the end of the email there is a little template questionnaire to help with planning. First, in order to firm up the schedule I’d like to ask everybody who said “maybe I would give a talk” to write me back whether or not they want to do that. You can also say “only if you need some more”. We won’t have quite enough time to accommodate everyone who said “maybe”. If we get to many desires to talks I will prioritize – with strong emphasis on letting folks present the Kokkos team doesn’t speak with on a weekly basis.

If you want some pointers for talks we had a set of them which worked really well at the recent ECP all hands meeting. The layout of the talks was something along the lines of:
  * What is your application/library about?
  * What are the biggest or maybe particularly special challenges with adopting Kokkos or making it generally work on modern hardware?
  * How did you address those challenges? What Kokkos capabilities did you use? Some (pseudo) code examples of what you did.
  * Some performance results if you got any.
 
The audience will be other people using Kokkos, but maybe in completely different application fields. So they may not learn much from the details of the physics/engineering problem you face, but they may be able to learn something from the particular computational/implementation challenges you encountered. So things like algorithmic ideas, data structure approaches, coding tricks and patterns are generally useful. Think about what would be useful for you if you listened to a talk from some other Kokkos user from a completely different science domain.

Some more logistic things, as you hopefully noticed (if not I apologize that I didn’t manage to update all channels – some of which were a bit out of my control) we have a extension to the third day for some more discussion etc. If you can’t make that Thursday please let me know – I will prioritize scheduling of talks and discussions according to expected attendance on the various days. Those of you without proper DOE badges, have to get their badges at the Sandia badge office:
1611 Innovation Pkwy SE, Albuquerque, NM 87123
Please bring proper identification (passport, RealID complient driver license).

The meeting is in CSRI 90:
1450 Innovation Pkwy SE, Albuquerque, NM 87123

Due to all kinds of rules we cannot provide refreshments via our available funding. We will organize coffee and tea nevertheless (since we don’t want this meeting to be hampered by widespread withdrawal syndroms) and might put out a little donation pot.  For those of you who do not want to go out for lunch during the lunch break we will collect cash in the morning and order pizzas and some salad ($10 per person per day).

**Comment by ikalash** [comment]
Will it be possible to view parts of the Kokkos Usergroup Meeting via Skype (e.g., by those of us out in SNL/CA)?  If so, would it be possible to send out the Skype link?

**Comment by crtrott** [comment]
I can try organize that.

**Comment by ikalash** [comment]
That would be great!  I think a lot of folks out here would be interested.  If you send me the link, I can circulate it among orgs that may be interested.

**Comment by crtrott** [comment]
I put in a link at the top to the meeting. We will have one open for the whole meeting.

**Comment by ikalash** [comment]
Thanks @crtrott !  I'll circulate it in SNL/CA.

**Comment by AndrewGaspar** [comment]
Is this web meeting open to non-SNL employees? I'm not planning to attend Thursday, but I'd like to at least view the "Cmake Issues" and "Build System Updates" talks.

**Comment by crtrott** [comment]
Yeah the web meeting should be completely open. We can only discuss non-export controlled matters anyway.

**Comment by csiefer2** [comment]
Are we using our own laptops or are you collecting PDFs for the slides?

**Comment by crtrott** [comment]
Either way is fine. I'd like to collect PDFs in the end though, and put them on the new Kokkos webpage.

**Comment by weinbe2** [comment]
Beyond the sessions being broadcast over Skype, will they also be recorded?

**Comment by pguthrey** [comment]
Is anyone else having trouble connecting to the webmeeting?

Is guest login enabled?

**Comment by AndrewGaspar** [comment]
I'm having issues too, but I wasn't sure if it was just a SfB on Mac issue. What I'm seeing is that when I try to log in as a guest, the UI doesn't react in any way.

**Comment by dholladay00** [comment]
Having the same issue as @AndrewGaspar

**Comment by csiefer2** [comment]
Slides should be broadcast now.  We took a break for an evacuation drill :)

**Comment by jgfouca** [comment]
Is there any way to download the slides for the various presentations?

**Comment by AndrewGaspar** [comment]
@dholladay00 @pguthrey I was able to get it working just now on macOS. First launch SfB in a logged out state (not sure how to do it when logged in - SfB on macOS doesn't work with LANL's site deployment).

<img width="517" alt="image" src="https://user-images.githubusercontent.com/2292643/56702916-bd2cda80-66c3-11e9-8b33-3b0d8ac28762.png">

Click "Join Meeting As Guest". Paste "https://meeting.sandia.gov/celmont/G8TFB38V" into the "Enter Meeting URL" box.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/2292643/56702949-e0f02080-66c3-11e9-9ef5-d431506ba32b.png">

You should now be logged in.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2292643/56702966-f5ccb400-66c3-11e9-8613-6cfb9009f200.png">

**Comment by AndrewGaspar** [comment]
Nvm - I can only join for a few seconds at a time and then SfB disconnects me. Oh well...

**Comment by aprokop** [comment]
@AndrewGaspar The (only) thing that works for me was the following:
Add `?sl=1&UseCdn=false` to the link:
`https://meeting.sandia.gov/celmont/G8TFB38V?sl=1&UseCdn=false`
The first time running it in Chrome on Mac it will prompt to install
Skype Meetings App. Once installed, going to the same link and using second option would launch the installed app and work correctly. This approach does not require any accounts.

**Comment by crtrott** [comment]
* SIMD Types
  * We just need to do it ...
  * What does CABANA have?
  * SIMD Execution Policy to work on non-SIMD types layed out in a SIMD way
  * Align with C++20 SIMD
  * Working Group: Stuart (ORNL), Si, Siva, Nevin (ANL), Damodar (Utah), Eric, Kyungjoo, David   
* Vectorization Enforcer
  * Only K-Athena wants this in the room
  * `prefer(RangePolicy<>(0,N),SIMD)`
* C++ Standard Progression
  * Early CY 20 -> C++14
  * Late CY21 -> C++17
* MDRangePolicy Improvement
  * Vectorization issues need to be resolved ...
  * MDRange on each level
    * Maybe Sparten but maybe not
    * Maybe OtherThing
    * Maybe MHD
* Latency Limited Runs 
  * Many kernels per second
  * CUDA Graphs
* Pipelining
  * Need Kernel Fusion at the KokkosKernels level: maybe just a couple things
  * Kernel Fusion
  * Not Super Important
* Coarse Grained Tasking
  * Nobody has an opinion
  * `auto fut = parallel_for("A",policy,f1);`
  * `Constructing graph` interface?
* Properties
  * `auto view_atomic = require(a,MemoryTrait<Atomic>);`
  * `require(Thing,Option)`
  * `prefer(Thing,Option)`
  * `RangePolicy<Cuda,IndexType<int>,Schedule<Dynamic>>` => require(RangePolicy(0,N),Cuda,IndexType<Int>,Schedule<Dynamic>)`
* Compile Times vs Readable Error vs Performance
  * Want regression tests so we have reasons for whatever happens
  * Mostly just the usual suspects
* Clang Static Analysis
  * Find anti patterns?
  * capturing views of memory space not compatible with execution space
  * forgetting reference on output parameter for parallel_reduce functor
  * Cheetah/Gemma/Aria want this
* Autotuning
  * Choosing TeamSize, VectorLength, Chunksize, tile sizes etc. 
  * Generally useful to the crowd
* Documentation
  * API Reference
  * User Guide -> keep up to date
  * Use Cases
* Large Memory Footprint
  * Auto staging via a special out-of-core parallel dispatch
  * Problem: need a list of all the things which needs to stage
  * ORNL Cabana will prototype
* PGAS Support
  * Worry about making constructor/destructor synchronous
    * Construct / Destruct via functions better
  * Limited to a number of folks (graph stuff for example)
* IO / Checkpointing / Resilience
  * IO/Checkpointing 
  * Parallel HDF5, restart with different number of MPI ranks
  * In-Situ analysis, using this kind of IO for data staging
* Memory Pool on host to replace CUDA/CUDA-UVM
  * Mark wants the thing
  * Benchmark: MPI call like AllReduce 
* Performance Regression Test Suite
  * Useable for Apps?
  * Compilation Time Testing
