### ISSUE TITLE
atomic_fetch_oper & atomic_oper_fetch don't build for complex<float>

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1964]
Tpetra is no longer able to build with `Scalar=complex<float>`.  I get error messages that look like this:
```
.../Trilinos/packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp:70:87: error: use of deleted function ‘Kokkos::Impl::atomic_fetch_oper(const Oper&, volatile Kokkos::complex<float>*, Kokkos::complex<float>) [with Oper = Tpetra::KokkosRefactor::Details::AbsMaxOper<Kokkos::complex<float>, Kokkos::complex<float> >]::<anonymous union>::<constructor>()’
   union { unsigned long long int i ; ::Kokkos::complex<float> t ; } oldval , assume , newval ;
```
I'm building with GCC 4.9.3.  It looks like the compiler doesn't want to make a union with `Kokkos::complex<float>`, probably because the class has a user-defined constructor: https://en.cppreference.com/w/cpp/language/union

I am trying out a work-around now.

**Comment by ndellingwood** [comment]
Cross-reference #1951 in case that is relevant.

**Comment by dsunder** [comment]
I’ve run into this problem with other compilers.  The fix is to remove the volatile overloads  the default constructor and copy constructor and set both of them to `= default;`.  I have this fix as part of a larger patch that I’ve been working on, I’ll pull it out and issue a pull request.

**Comment by mhoemmen** [comment]
@dsunder I have an alternate work-around that eschews `union` in favor of keeping separate `T` and `unsigned long long` values, and using `memcpy` to copy between them.  That would make the functions work for custom types `T` with `sizeof(T)==sizeof(unsigned long long)`, as long as the `T` are default constructible and whatever it is you call "can `memcpy` into them and get a valid `T`."  Would your work-around address this?

This may block Sierra promotion, but it's not clear whether Sierra actually needs `complex<float>`, so perhaps it's not so urgent.

**Comment by mhoemmen** [comment]
@dsunder @ndellingwood I just e-mailed you two a patch that makes Tpetra build with `Scalar=complex<float>` enabled.  I have no idea if it's correct :-)

**Comment by mhoemmen** [comment]
Nothing in Tpetra cares about that assumption.  I don’t think the interface in Kokkos cares either.

**Comment by dsunder** [comment]
Technically, without my changes to Kokkos complex our complex number is not allowed to be used as the parameter to std::atomic.

**Comment by mhoemmen** [comment]
@dsunder I am totally ok with those changes :-)

**Comment by masterleinad** [comment]
So what is the idea for fixing this issue?

**Comment by masterleinad** [comment]
Is there a reason to not just use
```
template < class Oper, typename T >
KOKKOS_INLINE_FUNCTION
T atomic_fetch_oper( const Oper& op, volatile T * const dest ,
  typename Kokkos::Impl::enable_if< sizeof(T) != sizeof(int) &&
                                    sizeof(T) == sizeof(unsigned long long int) , const T >::type val )
{
  union Dummy {
   Dummy () {};
   unsigned long long int i ;
   T t ;
  } oldval , assume , newval ;
 
  oldval.t = *dest ;
 
  do {
    assume.i = oldval.i ;
    newval.t = Oper::apply(assume.t, val) ;
    oldval.i = Kokkos::atomic_compare_exchange( (unsigned long long int*)dest , assume.i , newval.i );
  } while ( assume.i != oldval.i );
 
  return oldval.t ;
}
```
?

**Comment by masterleinad** [comment]
There are already constructors defined for unions, e.g. in `Kokkos::atomic_fetch_add()` in `Kokkos_Atomic_Fetch_Add.hpp`. I will just create a pull request.

**Comment by crtrott** [comment]
Before we close this: we need a unit test.
