### ISSUE TITLE
Kokkos::Array subscript vs call operator

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#1965]
Following the Kokkos standard, wouldn't it be consistent that the `operator[]` in `Array` is accessible only from the host, and that the `operator()` is introduced and accessible from the device?

**Comment by j8asic** [comment]
Well exactly, the suggestion is complementing it. `[]` is to mimic std::array for host operations, and `()` for Kokkos' extended functionality? Seems strange to access with `[]` within the device code...

**Comment by ibaned** [comment]
I don't think `()` was ever intended to be the "special on-device access" operator. Both `[]` and `()` are available from the space where the `View` is allocated, similarly for `Array`. Furthermore, trying to introduce such a distinction would break Kokkos' single-source goal, which is that the user source shouldn't change if its running on host threads versus GPU threads.
