### ISSUE TITLE
Assign a 1D view with a single element to a scalar view

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1970]
Is there a reason I can't directly assign a 1D view with a single element to a scalar view?  My use case is I am taking a subview with a single element out of a larger array and want to assign it to a scalar view and use `view()`. I don't want to have to use `view(0)` everywhere if possible. When I try to take the subview and assign to a scalar view, I get:

```
error: static assertion failed: Incompatible View copy assignment
```

**Comment by stanmoore1** [comment]
For example:

```
  d_scalar_view = Kokkos::subview(d_1D_view,std::make_pair(4,4));
```

**Comment by mhoemmen** [comment]
Do this:
```c++
d_scalar_view = Kokkos::subview(d_1d_view, 4);
```

**Comment by crtrott** [comment]
```c++
subview(d_1D_view,std::make_pair(4,4));
```
returns a rank 1 view (because you gave a range) of length zero (because the range is 0 long). 

Mark is correct. You need to reduce the rank of the original view (which happens by using subview with a n integer argument).

**Comment by stanmoore1** [comment]
Got it, thanks!
