### ISSUE TITLE
Pthreads backend does not handle RangePolicy with offset correctly

### ISSUE THREAD

**Issue by msimberg** [kokkos/kokkos#1976]
It seems like the Pthreads backend does not handle `RangePolicy(a, b)` with `a != 0` correctly. I added a test for the HPX backend because I handled it incorrectly there, and it seems to fail for Pthreads but not OpenMP (or HPX): https://travis-ci.com/msimberg/kokkos/builds/99084238, and https://travis-ci.com/msimberg/kokkos/jobs/173993017#L1624. The added test is here: https://github.com/kokkos/kokkos/commit/e97b9d4486a259643bcb7b1e52f331abe486cf86.

This is not important for me but thought it might affect someone else.

**Comment by crtrott** [comment]
Do you have a reproducer? This seems to work fine:
```
[crtrott@apollo 1976-PthreadRangePolicy]$ ./test.host 
5
6
7
8
9
[crtrott@apollo 1976-PthreadRangePolicy]$ cat main.cpp 
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = (argc>1) ? atoi(argv[1]) : 10000;
     int M = (argc>2) ? atoi(argv[2]) : 10000;
     int R = (argc>3) ? atoi(argv[3]) : 10;
    
     Kokkos::parallel_for(Kokkos::RangePolicy<>(5,10), [=] (const int i) {
       printf("%i\n",i);
     });
  }
  Kokkos::finalize();
}
```

**Comment by msimberg** [comment]
Yes, the test on the HPX branch with the results on Travis. However, it does seem to be something different than e.g. `RangePolicy(5, 10)` iterating from 0 to 5 or something like that. I didn't look into the cause of it though.

**Comment by crtrott** [comment]
I confirmed it has something to do with Dynamic Scheduling and you need to run a larger count. 
```c++
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = atoi(argv[1]);
     Kokkos::parallel_for(Kokkos::RangePolicy<Kokkos::Schedule<Kokkos::Dynamic> >(13,N+13), [=] (const int i) {
       printf("RUN %i A\n",i);
     });
  }
  Kokkos::finalize();
}
```

```
[crtrott@apollo 1976-PthreadRangePolicy]$ ./test.host 101
RUN 16 A
RUN 17 A
RUN 18 A
RUN 19 A
...
RUN 113 A
```

Note this is running a single thread.

**Comment by crtrott** [comment]
I am cherry picking the test onto develop, fix the issue and then issue a pull request with that fix and the test against develop. After that we can merge develop back into the HPX branch.

**Comment by ndellingwood** [comment]
PR #1978 contained partial fix; @crtrott will issue a follow on to complete the fix.

**Comment by crtrott** [comment]
I couldn't actually reproduce the Jenkins error yet ...
