### ISSUE TITLE
nvcc_wrapper Does Not Support  -Xcompiler <compiler option>

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#198]
Would like to be able to provide arguments as:

`OMPI_CXX=$PWD/nvcc_wrapper mpicxx .. -Xcompiler <compiler option>`

This is slightly messy because of C++11 pass through on POWER.

**Comment by crtrott** [comment]
We can change that, and it would work for the method: 
-Xcompiler arg1,arg2,arg3
There would be no spaces allowed in any of those things. Would that fit your need?

**Comment by nmhamster** [comment]
Yeah, I need this for the POWER8 work because the C++11 pass through is turning into a bit of a mess.

**Comment by crtrott** [comment]
Does this patch work for you:

```C++
diff --git a/config/nvcc_wrapper b/config/nvcc_wrapper
index 0589119..ce82f2b 100755
--- a/config/nvcc_wrapper
+++ b/config/nvcc_wrapper
@@ -127,6 +127,8 @@ do
     ;;
   #strip -Xcompiler because we add it
   -Xcompiler)
+    xcompiler_args="$xcompiler_args,$2"
+    shift
     ;;
   #strip of "-x cu" because we add that
   -x)
```

**Comment by crtrott** [comment]
New try: 

```C++
diff --git a/config/nvcc_wrapper b/config/nvcc_wrapper
index 0589119..5b56832 100755
--- a/config/nvcc_wrapper
+++ b/config/nvcc_wrapper
@@ -127,6 +127,13 @@ do
     ;;
   #strip -Xcompiler because we add it
   -Xcompiler)
+    if [ $first_xcompiler_arg -eq 1 ]; then
+      xcompiler_args="$2"
+      first_xcompiler_arg=0
+    else
+      xcompiler_args="$xcompiler_args,$2"
+    fi
+    shift
     ;;
   #strip of "-x cu" because we add that
   -x)
```

**Comment by nmhamster** [comment]
Its still not working correctly with XL and NVCC but I don't think this is because of the `nvcc_wrapper` script. Its something to do with `nvcc`.

**Comment by nmhamster** [comment]
It looks like this is a bug in CUDA 7.5 toolkit when using IBM XL series

`nvcc warning : The -c++11 flag is not supported with the configured host compiler. Flag will be ignored.`

Even though the IBM compiler does support C++11. I am raising a bug to see if we can get this fixed.

**Comment by crtrott** [comment]
Merged into Master
