### ISSUE TITLE
Kokkos Ecosystem Promotion to 3.0.00

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1982]
The next promotion of the Kokkos Ecosystem will see a new major version, including official deprecation of various functionality as documented here: [Deprecation Page](https://github.com/kokkos/kokkos/wiki/DeprecationPage). This issue is posted in advance of promotion testing to help announce the timeframe for deprecation as well as track key issues requiring completion in this promotion.

### Timeframe

Mid-April 2019 Release prior to the Kokkos User Group meeting, see #1962 

### Required for this release

- [x] Set `KOKKOS_ENABLE_DEPRECATED_CODE=OFF` as the default

- [ ] Copyright assertion for version 3.0
       Primary issues: #1335 #1084 #1037

- [ ] Updated CMake support (standalone) in kokkos and kokkos-kernels
       Primary issues: #1924 (kokkos) and kokkos/kokkos-kernels#120
       Related issues: #1930 #1902 #1928 #1966 kokkos/kokkos-kernels#361

- [x] Updates to tasking backend
       Primary issue: PR #1971
        Related issues: #1412 #565 #550 

- [x] Cuda Stream support
       Primary issue: #1723 

- [ ] Structured spmv
       Primary issue: kokkos/kokkos-kernels#365

This is a subset of required capabilities to add to this release; other bug fixes, enhancements etc. within this milestone are currently excluded. 

@crtrott @srajama1 @ibaned @dsunder @dhollman @jeffmiles63 @jjwilke @vqd8a @kyungjoo-kim @swbova @lucbv @mhoemmen @william76 @ndellingwood 

Please update the issue as necessary to add anything I missed.

**Comment by ndellingwood** [comment]
@crtrott Will cuda/7.5 support be discontinued with Kokkos v 3.0 release?

**Comment by stanmoore1** [comment]
Isn't cuda/7.5 the highest version of CUDA on the ORNL Titan supercomputer? If so, can we wait until Titan goes away to discontinue support for cuda/7.5?

**Comment by ndellingwood** [comment]
> Isn't cuda/7.5 the highest version of CUDA on the ORNL Titan supercomputer? If so, can we wait until Titan goes away to discontinue support for cuda/7.5?

@stanmoore1 yes thanks for info, I thought it was discontinued already, my mistake.

**Comment by nmhamster** [comment]
@ndellingwood - will be around for a while yet.

**Comment by Rombur** [comment]
> Isn't cuda/7.5 the highest version of CUDA on the ORNL Titan supercomputer?

No, there is cuda 9.1 on Titan

**Comment by stanmoore1** [comment]
@Rombur thanks for the update

**Comment by stanmoore1** [comment]
ORNL should update their website: https://www.olcf.ornl.gov/software_package/cudatoolkit/

**Comment by crtrott** [comment]
With Titan being updated to 9.1 we can probably discountinue CUDA 7.5 support.

**Comment by ndellingwood** [comment]
I created the kokkos-promotion branch in Trilinos to begin accumulating any necessary fixes for the next promotion.

kokkos-promotion branch of Trilinos created from SHA trilinos/Trilinos@33fbe89c6eea347aad62e2864b039b67db0ebd7a

One update needed in Trilinos in Stokhos to an internal specialization of `ParallelFor` to account for changes in Kokkos for the new Cuda stream support.

Still need to address #2071 in Kokkos (I haven't looked into this) to get all Kokkos unit tests building in Trilinos, along with several issues blocking promotion until we're ready for further testing.

**Comment by ndellingwood** [comment]
Updated integration testing results on Waterman:

### ATDM testing env
Waterman Cuda/9.2 build (Volta70 + Power9), deprecated code disabled

Trilinos kokkos-promotion branch SHA: trilinos/Trilinos@be47e609401cddc1fa1c2dd4ad8408530be4d7df
Kokkos develop branch SHA: kokkos/kokkos@8917524c60e4c4d5e361d4412194c89dc6c6ef06
KokkosKernels develop branch SHA: kokkos/kokkos-kernels@683e5b3b49d823ddabbaefb9d6d4f8fe43613353

### Enabled packages
```
PACKAGE1=Kokkos
PACKAGE2=KokkosKernels
PACKAGE3=Sacado
PACKAGE4=Tpetra
PACKAGE5=Intrepid2
PACKAGE6=Ifpack2
PACKAGE7=Panzer
PACKAGE8=Phalanx
PACKAGE9=Stratimikos
PACKAGE10=Belos
PACKAGE11=Stokhos
PACKAGE12=MueLu
```

### Build: 
100%

### Failed tests:

```
99% tests passed, 14 tests failed out of 1386

Subproject Time Summary:
Belos            = 1131.91 sec*proc (100 tests)
Ifpack2          = 1426.38 sec*proc (45 tests)
Intrepid2        = 1951.01 sec*proc (267 tests)
Kokkos           = 515.65 sec*proc (28 tests)
KokkosKernels    = 304.67 sec*proc (8 tests)
MueLu            = 26396.52 sec*proc (112 tests)
Panzer           = 10402.44 sec*proc (166 tests)
Phalanx          = 121.98 sec*proc (27 tests)
Sacado           = 453.22 sec*proc (300 tests)
Stokhos          = 369.14 sec*proc (84 tests)
Stratimikos      =  61.67 sec*proc (39 tests)
Tpetra           = 4761.22 sec*proc (210 tests)

Total Test time (real) = 3049.84 sec

The following tests FAILED:
	690 - Ifpack2_SGSMT_compare_with_Jacobi_MPI_4 (Failed)
	1054 - MueLu_UnitTestsIntrepid2Tpetra_MPI_4 (Timeout)
	1056 - MueLu_UnitTestsCreatePreconditionerTpetra_MPI_4 (Timeout)
	1064 - MueLu_DriverTpetra_MPI_4 (Failed)
	1066 - MueLu_DriverTpetra_WithGlobalConstants_MPI_4 (Failed)
	1067 - MueLu_DriverTpetraTripleMatrixProduct_MPI_4 (Failed)
	1069 - MueLu_DriverTpetraIfpack2LinePartitioner_MPI_4 (Failed)
	1081 - MueLu_ParameterListInterpreterTpetra_MPI_4 (Timeout)
	1083 - MueLu_CreateOperatorTpetra_MPI_4 (Failed)
	1090 - MueLu_Maxwell3D-Tpetra-Stratimikos_MPI_4 (Timeout)
	1117 - MueLu_Driver_TogglePFactory_tent_tent_Tpetra_MPI_4 (Timeout)
	1118 - MueLu_Driver_TogglePFactory_sa_tent_Tpetra_MPI_4 (Failed)
	1119 - MueLu_Driver_TogglePFactory_semi_tent_Tpetra_MPI_4 (Failed)
	1129 - MueLu_Structured_Elasticity3D_Tpetra_MPI_4 (Timeout)
```

**Comment by ndellingwood** [comment]
Closing in favor of #2614
