### ISSUE TITLE
Problem compiling with CUDA support

### ISSUE THREAD

**Issue by pgambron** [kokkos/kokkos#1983]
Hello,

If I compile Kokkos with the support for CUDA enabled, I obtain the following errors when I try to compile my code.

 Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline

However, if Kokkos has been compiled without support for CUDA, it works fine,

Thanks!

**Comment by crtrott** [comment]
Hm somehow you must have managed to evade our compiler detection warning/error. This usually means you are not using a CUDA capable compiler. With Kokkos you need to compiler everything with a CUDA aware compiler if you enable the CUDA backend. The two easiest things to do are using Clang (6.0 or newer) or use our nvcc_wrapper (which calls nvcc, but sorts arguments appropriately).

**Comment by pgambron** [comment]
Thank you for your reply.

I have set the variables CMAKE_CXX_COMPILER and NVCC_WRAPPER  accordignly (KOKKOS_PATH is also set correctly) but, now, I obtain the following error message:

Building CXX object CMakeFiles/kokkos.dir/core/src/impl/Kokkos_HostBarrier.cpp.o
/home/pgambron/kokkos/core/src/impl/Kokkos_HostBarrier.hpp(110): error: namespace "Kokkos" has no member "atomic_fetch_add"

Thanks!

**Comment by crtrott** [comment]
Uhm that is rather weird. I am not sure how you can get into that state. Can you post your KokkosCore_config.h file which should have been generated somewhere in your build directory?

**Comment by pgambron** [comment]
Thank you for your reply.

I have managed to sort out the problem. Now, I am trying to go further so I will probably come back... :-)

Thanks!

**Comment by crtrott** [comment]
What was it? It helps us to know what happened so we can help other people who may run into the same issue.

**Comment by pgambron** [comment]
Hello, it was not sorted out in fact. I had a doubt. It's the reason why I had remained vague.

If I complie kokkos without CUDA support, everything works fine.

But, if I enable CUDA support, I am able to compile kokkos but I can't compile my code anymore.

I enabled CUDA by setting the following variables:

`
CMAKE_CXX_COMPILER   /home/pgambron/kokkos/bin/nvcc_wrapper  
KOKKOS_ENABLE_CUDA   ON                                                                                                                                                                                                        
KOKKOS_ENABLE_CUDA_INTERNAL   ON 
NVCC_WRAPPER   /home/pgambron/kokkos/bin/nvcc_wrapper  
`

When I try to compile my code, I obtain errors like: 
`
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/impl/Kokkos_Utilities.hpp:59:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/impl/Kokkos_Utilities.hpp:65:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/impl/Kokkos_Utilities.hpp:73:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/impl/Kokkos_Utilities.hpp:80:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/Kokkos_UniqueToken.hpp:74:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/Kokkos_UniqueToken.hpp:78:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/Kokkos_UniqueToken.hpp:82:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
/home/pgambron/opt/include/Kokkos_Macros.hpp:182:40: error: ‘__device__’ does not name a type; did you mean ‘__dev_t’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^
/home/pgambron/opt/include/Kokkos_Core_fwd.hpp:68:3: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
   KOKKOS_INLINE_FUNCTION
   ^~~~~~~~~~~~~~~~~~~~~~
`


Here is my KokkosCore_config.h. The section about CUDA settings is empty.

` /* ---------------------------------------------
Makefile constructed configuration:
Mon 18 Feb 10:49:43 GMT 2019
----------------------------------------------*/
#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
#error "Do not include KokkosCore_config.h directly; include Kokkos_Macros.hpp instead."
#else
#define KOKKOS_CORE_CONFIG_H
#endif
/* Execution Spaces */
#define KOKKOS_ENABLE_CUDA
#define KOKKOS_COMPILER_CUDA_VERSION 100
#define KOKKOS_ENABLE_SERIAL
/* General Settings */
#define KOKKOS_ENABLE_CXX11
#define KOKKOS_USE_LIBRT
#define KOKKOS_ENABLE_PROFILING
#define KOKKOS_ENABLE_DEPRECATED_CODE
/* Optimization Settings */
/* Cuda Settings */
'

Thanks!

**Comment by crtrott** [comment]
Can you post a full compile line from the output? (I.e. in a verbose build?) It seems like it is not using nvcc_wrapper for those objects for some reason.

**Comment by pgambron** [comment]
Thank you for your reply.

This was my mistake. I had not compiled my code with the wrapper.

I had assumed that, if the header files and the libraries where in places contained in the relevant environment variables, I could compile it the classical way.

Now, it's still does not work but this time, it's my fault. My codes used to work in a multithreaded way but using the GPU has revealed some things I have done wrong.

Thanks!
