### ISSUE TITLE
Jenkins failures - Cuda

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1984]
Following merge of PR #1971 the following failures are occurring in the nightly Jenkins tests:

### cuda_92_gcc_720_kepler_rdc_deprecated_off

Sign comparison error

`Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off/ws/kokkos/core/src/Cuda/Kokkos_Cuda_Task.hpp>:235:93: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]`

### kokkos-dev_cuda_80_rdc_large_mem

```
Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem/ws/kokkos/core/src/Kokkos_ExecPolicy.hpp>:810:63: error: ‘device’ attribute directive ignored [-Werror=attributes]
TeamThreadRange( const TeamMemberType&, const iType& count ) = delete;
```

### kokkos-dev_cuda_75

```
kokkos-dev_cuda_75/ws/kokkos/core/src/Kokkos_ExecPolicy.hpp>:810:63: error: ‘host’ attribute directive ignored [-Werror=attributes]
<https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_cuda_75/ws/kokkos/core/src/Kokkos_ExecPolicy.hpp>:821:84: error: ‘device’ attribute directive ignored [-Werror=attributes]
TeamThreadRange( const TeamMemberType&, const iType1& begin, const iType2& end ) = delete;
```

@dhollman do you have time to look into these? Are the tasking changes intended to work with cuda 7.5 and 8.0 or should there be guards in these cases?

**Comment by mhoemmen** [comment]
@ndellingwood Are y'all trying to build CUDA with warnings as errors?  That's ... exciting ;-)

**Comment by crtrott** [comment]
Yeah we do :-).

**Comment by ndellingwood** [comment]
@crtrott Some of the Jenkins build errors still remain so I removed the InDevelop tags for now.

## Jenkins Build Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem

[Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem/185/display/redirect)

### Sample errors:
1. signed and unsigned comparison
`<https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem/ws/kokkos/core/src/Cuda/Kokkos_Cuda_Task.hpp>:235:93: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]`

2. -Werror=reorder
<https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem/ws/kokkos/core/src/impl/Kokkos_TaskNode.hpp>:622:83: error: base `
‘TestTaskScheduler::TestFib<Kokkos::SimpleTaskScheduler<Kokkos::Cuda, Kokkos::Impl::SingleTaskQueue<Kokkos::Cuda, Kokkos::CudaSpace, Kokkos::Impl::TaskQueueTraitsLockBased> > >’ will be initialized after [-Werror=reorder]`

## Jenkins Builds Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off and  Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc

[Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off](https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off/186/display/redirect)

### Sample errors
Same as above

@dhollman these -Werror followed from the merge of the tasking updates, do you have time to look at these?

## Jenkins Build Kokkos_apollo_debug

[Kokkos_apollo_debug](https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/757/display/redirect)

### Sample errors:
```
<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_HostSpace.cpp(438)>: error: expected a declaration

At end of source: warning: parsing restarts here after previous syntax error

1 error detected in the compilation of "/tmp/tmpxft_0000abae_00000000-6_Kokkos_HostSpace.cpp1.ii".
make[1]: *** [Kokkos_HostSpace.o] Error 1
make[1]: *** Waiting for unfinished jobs....
<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(154)>: error: SharedAllocationRecord is not a template

<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(157)>: error: identifier "SharedAllocationRecord" is undefined

<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(157)>: error: type name is not allowed

<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(157)>: error: expected a ")"

<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(162)>: warning: parsing restarts here after previous syntax error

<https://jenkins-son.sandia.gov/job/Kokkos_apollo_debug/ws/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp(163)>: error: expected a ";"

...
```

**Comment by crtrott** [comment]
Working on this to get another fix in.

**Comment by ndellingwood** [comment]
Most of the issues here have been fixed, the cuda rdc builds are still failing so I'm going to open a new issue specifically for that.

**Comment by ndellingwood** [comment]
#2008 is followup reporting the cuda rdc issues in Kokkos_TaskNode.

**Comment by ndellingwood** [comment]
cuda rdc issues tracked in #2006. Won't fix for old Cuda compilers that are no longer supported.
