### ISSUE TITLE
performance difference between range policy and team policy in openmp

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1994]
I usually use range policy for openmp and team policy for cuda. I would like to maintain a single version of the code and I consider the following situation.
```
num_leagues = some number;
team_size = 1; vector_size =1;
Kokkos::parallel_for(TeamPolicy<>(num_leagues, team_size, vector_size), 
  KOKKOS_LAMBDA(const member_type member) {
    const int i = member.league_rank();
    doSomethingWithView(i);
  });

Kokkos::parallel_for(RangePolicy<>(0, num_leagues), 
  KOKKOS_LAMBDA(const int i) {
    doSomethingWithView(i);
  });
```

In my code, timing results are quite different and range policy is almost twice faster than team policy on openmp. Besides overhead of team policy, is there any way I can enforce the same parallel work scheduling as behaving like range policy ? 

@crtrott @ndellingwood @dsunder @ibaned

**Comment by kyungjoo-kim** [comment]
Oh... sorry... my test includes some mistakes.. closing this issue.

**Comment by ndellingwood** [comment]
@kyungjoo-kim just to followup, does this mean times were nearly identical minus possible extra overhead with team policy use?

**Comment by kyungjoo-kim** [comment]
Yes. I would say so.
