### ISSUE TITLE
local deep copy tests breaking non-lambda CUDA builds

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#1995]
Merge of PR #1939 has broken several Jenkins Cuda builds, from this error message it is due to unguarded tests using lambda:

`<https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_pascal/ws/kokkos/core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp(75)>: error: The closure type for a lambda ("lambda [](const member_type &)->void", defined at <https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_pascal/ws/kokkos/core/unit_test/TestLocalDeepCopy.hpp>:423) cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is an 'extended lambda' and the flag --expt-extended-lambda is specified`

@vqd8a can you look into this? Lambda support is not enabled during testing by default with Cuda since it is still considered an experimental feature, so any tests using lambdas (like the one at TestLocalDeepCopy.hpp:423) must be guarded so they do not build/run unless lambdas explicitly enabled.

**Comment by ibaned** [comment]
@ndellingwood can you post the full error output? The last file  isn't useful, we need the first one

**Comment by ndellingwood** [comment]
@ibaned here is additional info pasted, all the unit tests in `TestLocalDeepCopy.hpp` use lambdas (line 423 specified in the one error snip above). The quick bandaid fix is to disable the tests when cuda lambdas are not enabled (which is the default setting in test_all_sandia script and in the Jenkins builds), longer term some/all the lambdas should be rewritten as functors to ensure testing coverage. 

My suggested short term fix, if you agree I can put in a quick PR:

Bottom of `TestLocalDeepCopy.hpp`
```

#if defined( KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA )
#if !defined(KOKKOS_ENABLE_CUDA) || ( 8000 <= CUDA_VERSION )
  { //Rank-1
    impl_test_local_deepcopy_rangepolicy_rank_1<ExecSpace,ViewType>(8);
  }
  { //Rank-2
    impl_test_local_deepcopy_rangepolicy_rank_2<ExecSpace,ViewType>(8);
  }
  { //Rank-3
    impl_test_local_deepcopy_rangepolicy_rank_3<ExecSpace,ViewType>(8);
  }
  { //Rank-4
    impl_test_local_deepcopy_rangepolicy_rank_4<ExecSpace,ViewType>(8);
  }
  { //Rank-5
    impl_test_local_deepcopy_rangepolicy_rank_5<ExecSpace,ViewType>(8);
  }
  { //Rank-6
    impl_test_local_deepcopy_rangepolicy_rank_6<ExecSpace,ViewType>(8);
  }
  { //Rank-7
    impl_test_local_deepcopy_rangepolicy_rank_7<ExecSpace,ViewType>(8);
  }
#endif
#endif
```


Additional error message detail:
```
07:39:31 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/bin/nvcc_wrapper  -I./ -I/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/core/src -I/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/containers/src -I/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/algorithms/src -I/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/core/src/eti --std=c++11 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -arch=sm_60 -I/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/include -I/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/tpls/gtest -I/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/core/unit_test -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  -c /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/core/src/Cuda/Kokkos_Cuda_Locks.cpp
07:39:31 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp(300): error: The closure type for a lambda ("lambda [](const member_type &)->void", defined at /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_pascal/kokkos/core/unit_test/TestLocalDeepCopy.hpp:74) cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is an 'extended lambda' and the flag --expt-extended-lambda is specified
```

**Comment by ndellingwood** [comment]
I just put in PR #1998
