### ISSUE TITLE
Support PGI

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2]
We need to make sure PGI 15.x compilers are supported both for host only and host+cuda compilation. This will probably be an important compiler on machines with NVIDIA GPUs.

**Comment by crtrott** [comment]
I get through the compilation with PGI 15.4 but fail at link time with:
/usr/bin/ld: cannot find -lgcc_s

**Comment by nmhamster** [comment]
What system are you using for this compile?



--
Si Hammond
Scalable Computer Architectures
Sandia National Laboratories, NM
[Sent remotely, please excuse typing errors]
________________________________

**Comment by hcedwar** [comment]
Duplicate of issue #289
