### ISSUE TITLE
Using Kokkos in a distributed memory environment

### ISSUE THREAD

**Issue by minitu** [kokkos/kokkos#2003]
Dear Kokkos developers,

Is there a canonical method of using Kokkos in a distributed memory setting?
I would like to have Kokkos manage the shared-memory execution on each physical node and use MPI or something to move data around between nodes.

**Comment by mhoemmen** [comment]
@minitu wrote:
> I would like to have Kokkos manage the shared-memory execution on each physical node and use MPI or something to move data around between nodes.

Most MPI codes that use Kokkos do this.  Current best practice for multiple GPUs is to use 1 GPU per MPI process (or multiple MPI processes per GPU if you're running MPS), and use host-pinned memory for communication buffers.

@crtrott has done some interesting experiments using PGAS (e.g., MPI one-sided) through a Kokkos::View, but that is not in the main Kokkos repository yet, as far as I know.  That may end up being an alternative to users managing MPI.

**Comment by stanmoore1** [comment]
If using a CUDA-aware version of MPI, you can directly use GPU device buffers in MPI Send/Recv calls (i.e. GPU-direct) and you may get speedup that way.

**Comment by minitu** [comment]
My main concern was actually how the View abstraction would work with MPI calls.
If you could point me to some (simple) Kokkos + MPI code that would be great.

**Comment by stanmoore1** [comment]
https://github.com/lammps/lammps/blob/master/src/KOKKOS/comm_kokkos.cpp#L203

**Comment by mhoemmen** [comment]
`MPI_Send`, `MPI_Recv`, etc. just take the pointer and the length.  You'll want to check whether the MPI implementation is CUDA aware before giving MPI functions pointers to device memory.  That's a configure-time option for OpenMPI, for example, and you can use `ompi_info` to check.

**Comment by nmhamster** [comment]
From OpenMPI 2.0 onwards, the distribution reports that you can do compile time checking with the following:

```
#include <stdio.h>
#include "mpi.h"
 
#ifdef
#include "mpi-ext.h" /* Needed for CUDA-aware check */
#endif
 
int main(int argc, char *argv[])
{
    printf("Compile time check:\n");
#if defined(MPIX_CUDA_AWARE_SUPPORT) && MPIX_CUDA_AWARE_SUPPORT
    printf("This MPI library has CUDA-aware support.\n", MPIX_CUDA_AWARE_SUPPORT);
#elif defined(MPIX_CUDA_AWARE_SUPPORT) && !MPIX_CUDA_AWARE_SUPPORT
    printf("This MPI library does not have CUDA-aware support.\n");
#else
    printf("This MPI library cannot determine if there is CUDA-aware support.\n");
#endif /* MPIX_CUDA_AWARE_SUPPORT */
 
    printf("Run time check:\n");
#if defined(MPIX_CUDA_AWARE_SUPPORT)
    if (1 == MPIX_Query_cuda_support()) {
        printf("This MPI library has CUDA-aware support.\n");
    } else {
        printf("This MPI library does not have CUDA-aware support.\n");
    }
#else /* !defined(MPIX_CUDA_AWARE_SUPPORT) */
    printf("This MPI library cannot determine if there is CUDA-aware support.\n");
#endif /* MPIX_CUDA_AWARE_SUPPORT */
 
    return 0;
}
```

**Comment by minitu** [comment]
Thank you all for your help, seems like I have a good starting point.
