### ISSUE TITLE
Allow parallel_*() to forward additional arguments to functor

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#2005]
For example, 
```c++
parallel_for(policy, f, args...);
```
and `f`:
```c++
operator()(const DispatchTag, args...) { ... };
```
Currently, there's no way of doing this and the user has to wrap all the `args...` into the functor, which is very inconvenient. Also, there are situations where wrapping `args...` into the functor doesn't make sense or it incurs significant copying overhead.

**Comment by mhoemmen** [comment]
Counterarguments:

1. `Kokkos::parallel_for`'s current behavior is more consistent with `std::for_each`. 
2. Lambdas let users automate the capture process.  If you choose to write a functor instead, it means that you want to make capture explicit or control the capture process explicitly.
3. Forwarding the arguments will need to incur copy overhead for device kernel launches anyway.  In that case, the notation `operator() (Tag, args...)` is definitely _not_ what you want.
4. You always have the freedom to capture by reference on host.

**Comment by Char-Aznable** [comment]
Thanks for the input. I think you are right about lambda and this should not involve lambda in the discussion -- I change the title.
>1. `Kokkos::parallel_for`'s current behavior is more consistent with `std::for_each`
I think the difference here is that the user can easily access the state of the object on the host but can't do that for device code so the restriction is not very useful.

>2. If you choose to write a functor instead, it means that you want to make capture explicit or control the capture process explicitly.

This makes sense but not entirely true. For example, `args...` are other functors that take the state of the current functor as input, in which case I can't afford implementing for each expansion of `args...` one functor to do parallel_*(). But forwarding them as callbacks provides a way for this to work.

>3. Forwarding the arguments will need to incur copy overhead for device kernel launches anyway.  In that case, the notation `operator() (Tag, args...)` is definitely _not_ what you want.

That's true for kernel launches but not necessarily for nested parallel loop.

**Comment by dhollman** [comment]
> For example, `args...` are other functors that take the state of the current functor as input, in which case I can't afford implementing for each expansion of `args...` one functor to do parallel_*(). But forwarding them as callbacks provides a way for this to work.

I'd need to understand your use case a bit more carefully, but basically my answer for this is that you can always just pass the arguments to the functor's constructor instead.  I think it's a mistake to think of the functors you pass to `Kokkos::parallel_for` and friends as anything more than transient function objects that carry along their "arguments" in data members.  (I also dislike the `Tag` stuff for the same reason; it encourages an anti-pattern of persistent functors.)

> That's true for kernel launches but not necessarily for nested parallel loop.

In the nested case, you can always trivially capture by reference in a lambda and forward the arguments yourself.  If you still really want to avoid lambdas, you can use reference data members in the (hopefully transient) functor you create and bind those references at construction time, thus avoiding copy overhead.

**Comment by mhoemmen** [comment]
What David said -- for inner parallel loops, you can capture by reference.

**Comment by Char-Aznable** [comment]
> > For example, `args...` are other functors that take the state of the current functor as input, in which case I can't afford implementing for each expansion of `args...` one functor to do parallel_*(). But forwarding them as callbacks provides a way for this to work.
> 
> I'd need to understand your use case a bit more carefully, but basically my answer for this is that you can always just pass the arguments to the functor's constructor instead. I think it's a mistake to think of the functors you pass to `Kokkos::parallel_for` and friends as anything more than transient function objects that carry along their "arguments" in data members. (I also dislike the `Tag` stuff for the same reason; it encourages an anti-pattern of persistent functors.)

Passing `args...` in the functor's ctor will add unnecessary dependence on the `args...` -- like I said, I can't take care of all the possible `args...` expansions in my functor. A typical use case would be I implement a functor and I expect the users to implement their own `args...`, which are potentially functors themselves (or something else, whose details is not important to me), to take the state of my functor and do whatever with it.  
 
> 
> > That's true for kernel launches but not necessarily for nested parallel loop.
> 
> In the nested case, you can always trivially capture by reference in a lambda and forward the arguments yourself. If you still really want to avoid lambdas, you can use reference data members in the (hopefully transient) functor you create and bind those references at construction time, thus avoiding copy overhead.

Like I said, I agree you can avoid the issue here by using lambda. However, lambda capture doesn't yet always support capturing `*this` in class scope on CUDA backend until someday nvidia decides to support c++17 -- and yes, I'm aware of some workarounds for this but none of them always work.

**Comment by dhollman** [comment]
> However, lambda capture doesn't yet always support capturing *this in class scope on CUDA backend until someday nvidia decides to support c++17 -- and yes, I'm aware of some workarounds for this but none of them always work.

For nested parallelism, you should *not* be capturing `*this` anyway; rather you should be capturing by reference, which works fine even in C++11.

> Passing `args...` in the functor's ctor will add unnecessary dependence on the `args...` 

I still don't really understand this.  Are you talking specifically about the case where you need to expose variadic arguments to your users, and the absence of a device-safe `std::tuple` implementation prevents you from doing so?  If that's the case, we can work on providing a `tuple` type (and a `std::apply` analog) that will allow you to do this on a device; otherwise, I don't see the problem.  Generically, this is what I'm picturing:

```c++
template <class MyFunctor, class... UserArgs>
struct FunctorWithArgs {
  MyFunctor f;
  std::tuple<UserArgs...> args_tuple;
  KOKKOS_INLINE_FUNCTION
  void operator()(int val) const {
    std::apply(
      [&](UserArgs&... args) { f(val, args...); },
      args_tuple
    );
  }
};

// usage, which can be wrapped in whatever interface you want to present to the user:
Kokkos::parallel_for(n, FunctorWithArgs<MyFunctor, UserArgs...>{f, std::make_tuple(user_args...)});

```

So if you need to be that generic, we can talk about a `tuple` and `apply` implementation for Kokkos, but this still doesn't necessitate forwarding arguments at the function call site.

---

Philosophically, the issue with forwarding arguments transparently to the functor is that either you incur hidden copy overheads that are not apparent to the user, or (worse) you risk dangling references, since the Kokkos `parallel_*` functions are asynchronous.  Requiring the user to do their own capture into data members makes this cost/danger much clearer, in my book.

**Comment by Char-Aznable** [comment]
Thanks for the suggestion. I really appreciate it. Yes, I've considered the tuple approach. Even one can have a device-side tuple, there are other issues. The major issue is that it breaks the encapsulation and makes extension and modification difficult. For example, what if I have some other `MyFunctor` that does some other things and the user only want some other `args...` for it? In addition, the users have to carry the whole `FunctorWithArgs` around even if they want to update some `args...` in it between different `parallell_*()` calls for consistence.

>the issue with forwarding arguments transparently to the functor is that either you incur hidden copy overheads that are not apparent to the user, or (worse) you risk dangling references, since the Kokkos parallel_* functions are asynchronous.
Yes, this makes sense. I think the users have to be aware of these catches in any case and they are responsible of doing it right with their implementation.

**Comment by dhollman** [comment]
> In addition, the users have to carry the whole FunctorWithArgs around even if they want to update some args... in it between different parallell_*() calls for consistence.

Ah, but see, that's exactly what I'm getting at.  In my opinion, users shouldn't be carrying around instances of a functor between different `parallel_*()` calls.  I think you should just construct a new one for each call.  That way, the transience of the function object used by the `parallel_*` implementation is clearly represented in the user-side object instance lifetimes.  I'm not saying people won't ignore this advice and use long-lived function objects anyway, but I don't think we should make it easier for them to do this.

**Comment by Char-Aznable** [comment]
That's going to impose a huge limitation on the application, let alone the multiplied copying overhead of the `args...`. By your argument, there shouldn't be functor calling `parallel_*` inside its member functions, which I consider as one of the major use cases of Kokkos. Beside, If you were to define the concept of transient functor, I think it should be done explicitly instead of imposing implicit restraints.

**Comment by dhollman** [comment]
> let alone the multiplied copying overhead of the `args...`.

That's kind of my point.  That overhead exists no matter how we do this—whether we hide it inside Kokkos or make the application do the copying—so I'd rather it be explicit in the application.  The overhead of copying the arguments is exactly the same with a temporary functor as it is if we hide it in Kokkos.

I agree that there's a lot of Kokkos code in the wild that doesn't use temporaries for the functors passed to parallel patterns, but I think it frequently causes problems, and that's why I don't think we should continue to recommend it.

Is there any concrete code you can share with us that illustrates your use case? I'm definitely willing to talk about it, and we're willing to be convinced we're wrong on this, but I think right now we're talking past each other a bit.

**Comment by crtrott** [comment]
The team came to a consensus that we don't want to do this. The amount of work and stuff we need to maintain on our side compared to the benefit for the few users who want to do this is probably not worth it. The C++ standard committee also decided to not to do this for the std parallel algorithms (this was discussed).
