### ISSUE TITLE
cuda rdc build failures occur in Kokkos_TaskNode.hpp

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2006]
Jenkins cuda builds with rdc are failing due to `-Werror=reorder` triggered in `Kokkos_TaskNode.hpp`

Failing Builds:

[Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc](https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/)
[Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off](https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off/)
[Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem](https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_cuda_80_rdc_large_mem/)

Error snip:

`17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/src/Kokkos_TaskScheduler.hpp:705:140:   required from ���typename Scheduler::future_type_for_functor<typename std::decay<FunctorType>::type> Kokkos::host_spawn(Kokkos::Impl::TaskPolicyWithScheduler<TaskEnum, Scheduler, DepFutureType>, FunctorType&&) [with int TaskEnum = 1; Scheduler = Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased> >; DepFutureType = std::nullptr_t; FunctorType = TestTaskScheduler::TestMultipleDependence<Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased> > >; typename Scheduler::future_type_for_functor<typename std::decay<FunctorType>::type> = Kokkos::BasicFuture<bool, Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased> > >]���
17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/unit_test/TestTaskScheduler.hpp:778:28:   required from ���static void TestTaskScheduler::TestMultipleDependence<Scheduler>::run(int) [with Scheduler = Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased> >]���
17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/unit_test/TestTaskScheduler.hpp:925:203:   required from here
17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/src/impl/Kokkos_TaskNode.hpp:622:79: error: base ���TestTaskScheduler::TestMultipleDependence<Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased> > >::TestComputeValue��� will be initialized after [-Werror=reorder]
17:26:52      Args&&... args
17:26:52                                                                                ^
17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/src/impl/Kokkos_TaskNode.hpp:622:79: error:   base ���Kokkos::Impl::TaskResultStorage<int, Kokkos::Impl::SchedulingInfoStorage<Kokkos::Impl::RunnableTaskBase<Kokkos::Impl::TaskQueueTraitsLockBased>, Kokkos::Impl::EmptyTaskSchedulingInfo> >��� [-Werror=reorder]
17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/src/impl/Kokkos_TaskNode.hpp:620:1: error:   when initialized here [-Werror=reorder]
17:26:52    RunnableTask(
17:26:52  ^ ~~~~~~~~~~
17:26:52 /home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/kokkos/core/src/impl/Kokkos_TaskNode.hpp: In instantiation of ���constexpr Kokkos::Impl::RunnableTask<TaskQueueTraits, Scheduler, ResultType, FunctorType>::RunnableTask(FunctorType&&, Args&& ...) [with Args = {void (*&)(Kokkos::Impl::TaskNode<Kokkos::Impl::TaskQueueTraitsChaseLev<64> >*, void*), Kokkos::Impl::TaskType, Kokkos::TaskPriority&, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsChaseLev<64> >*&, int, long unsigned int&}; TaskQueueTraits = Kokkos::Impl::TaskQueueTraitsChaseLev<>; Scheduler = Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsChaseLev<> > >; ResultType = int; FunctorType = TestTaskScheduler::TestMultipleDependence<Kokkos::SimpleTaskScheduler<Kokkos::Serial, Kokkos::Impl::MultipleTaskQueue<Kokkos::Serial, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsChaseLev<> > > >::TestComputeValue]`

Edit: removed code markup around the Jenkins links

**Comment by ndellingwood** [comment]
Followup of remaining build failure reported in #1984

**Comment by dhollman** [comment]
This is a bug in the compiler warning implementation. You can see in the code that these are properly ordered, and switching them leads to the same warning being raised

**Comment by ndellingwood** [comment]
@dhollman yeah, I'll switch the labeling. To get around this in the builds should I add `-Wno-reorder` to the cxxflags?

**Comment by ndellingwood** [comment]
@dhollman @crtrott for now I added `-Wno-reorder` to the Jenkins jobs so we can get the testing coverage. Ross has set up Cuda RDC testing with the ATDM environment, so this may come back up sooner than later depending on what warnings they test with.
