### ISSUE TITLE
cuda.task_fib seg fault on Kepler GPU with rdc enabled

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2008]
The task_fib unit test is seg faulting in the following Jenkins builds:

[Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc](https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc/)

[Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off](https://jenkins-son.sandia.gov/job/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off/)

Test failure output:
```
02:44:33 [ RUN      ] cuda.task_fib
02:44:33 make[2]: *** [test-cuda] Segmentation fault (core dumped)
02:44:33 make[2]: Leaving directory `/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off/TestAll_2019-02-28_02.29.46/cuda/9.2.88/Cuda_Serial-release/core/unit_test'
02:44:33 make[1]: *** [test] Error 2
02:44:33 make[1]: Leaving directory `/home/jenkins/white/workspace/Kokkos_develop_white_cuda_92_gcc_720_kepler_rdc_deprecated_off/TestAll_2019-02-28_02.29.46/cuda/9.2.88/Cuda_Serial-release/core/unit_test'
02:44:33 make: *** [test] Error 2
```

The failures showed up after adding `-Wno-reorder` to get these tests running again, discussed in #2006

**Comment by ndellingwood** [comment]
Here are reproducer instructions running via `test_all_sandia` script on white:

```
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
bsub -J Kokkos-Kepler-rdc -W 01:00 -Is -q rhel7F ./kokkos/scripts/testing_scripts/test_all_sandia cuda/9.2.88 --arch=Power8,Kepler37 --with-cuda-options=rdc --cxxflags-extra="-Wno-reorder"
```

**Comment by dhollman** [comment]
I thought tasking was supposed to be disabled on Kepler, so I hadn't taken into account.  IIRC @crtrott told me at one point that tasking was something like a Volta and later feature, so I hadn't tested that.  Do we need to try and fix this, or should we just disable tasking on Kepler?

**Comment by ndellingwood** [comment]
@dhollman if it's a Volta and later feature than we just need to disable for Kepler, don't want you to waste time on a fix. Just clarify, this should only work on Volta and later, not Pascal?

**Comment by crtrott** [comment]
At least we should understand why it doesn't work on Kepler. If there is a good reason I am fine with not supporting it on Kepler. But lets understand this.

**Comment by lucbv** [comment]
@ndellingwood is this failure related to [this](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4648229) ?
My guess is that it is not but I thought I would mention it just in case...

**Comment by dhollman** [comment]
@ndellingwood does #2042 address this issue?

**Comment by ndellingwood** [comment]
@dhollman I'll get a run going on a Kepler GPU to check.

**Comment by ndellingwood** [comment]
@dhollman I tested on White's Kepler queue, things look good! I'll label as InDevelop


task_fib-related test results:
```
...
[ RUN      ] cuda.task_fib
[       OK ] cuda.task_fib (2303 ms)
[ RUN      ] cuda.task_fib_multiple
[       OK ] cuda.task_fib_multiple (1857 ms)
[ RUN      ] cuda.task_fib_new
[       OK ] cuda.task_fib_new (2246 ms)
[ RUN      ] cuda.task_fib_new_multiple
[       OK ] cuda.task_fib_new_multiple (1990 ms)
[ RUN      ] cuda.task_fib_chase_lev
[       OK ] cuda.task_fib_chase_lev (2963 ms)
...
```

Testing reproducer instructions:
```
module load cuda/9.2.88 gcc/7.2.0
generate_makefile.bash --with-cuda --arch="Power8,Kepler37" --compiler=${HOME}/kokkos/bin/nvcc_wrapper --with-cuda-options=rdc
bsub -Is -n 1 -q rhel7F bash
make unit-tests-only -j16 2>&1 | tee make.output
```
