### ISSUE TITLE
Need to default-construct DualView on GPU device

### ISSUE THREAD

**Issue by alanw0** [kokkos/kokkos#2010]
In STK we have a scenario where we have objects 'Field' that contain a Kokkos::DualView, and we want to store Fields in a view: Kokkos::View<Field*, …>. But this seg-faults because DualView's default constructor can't work on a GPU/Cuda device.

DualView's default constructor could work on device if it is decorated with KOKKOS_FUNCTION and if its initializer list uses the default constructor for t_modified_flags (i.e., don't pass a string to t_modified_flags).

In a local project I have verified that modifying DualView's default constructor like this allows our Field to be held in a device view.
Are kokkos developers agreeable to this?

**Comment by stanmoore1** [comment]
Why not make the inner `Field` view a device view and the outer view that stores Fields a dual view? This is what we did in LAMMPS, and it works well. BTW, view of views have certain pitfalls, like you need to deallocate them in serial to prevent race conditions.

**Comment by alanw0** [comment]
The Field class has an API for syncing its data to/from device and host, we just thought using DualView would be a good way to implement it. If DualView can't be default-constructed on device, we'll stop using DualView.

**Comment by mhoemmen** [comment]
I feel like there's something fundamentally wrong if you find yourself wanting to create DualViews on device.  Maybe UVM is really the right model for you, in which case, a single View is perfectly fine.

**Comment by alanw0** [comment]
Mark, you were there when we put the sync/modify API on Field, and you agreed that DualView was a good way to implement it. Also, you talked to Dave and JVo when they discovered that Sierra's copy of DualView wouldn't default-construct on device, which is why you were trying to pull in a newer version for us. But I've now discovered that the current version doesn't default-construct on device either. If it never will, then we'll stop using it.

**Comment by mhoemmen** [comment]
> Mark, you were there when we put the sync/modify API on Field, and you agreed that DualView was a good way to implement it.

oh oops ;-P sorry about that.  I had thought the Trilinos update would fix this.  With the new Trilinos, does this work if you just mark the default constructor with `KOKKOS_INLINE_FUNCTION`?

**Comment by alanw0** [comment]
Almost. Like I said above, you have to mark it, and also remove the string from the initializer list (the string that's being passed to t_modified_flags).

**Comment by mhoemmen** [comment]
hm, had thought that default DualView constructor doesn't initialize that View.

**Comment by crtrott** [comment]
This is the behavior when turning off deprecated view I talked to Alan in person.
