### ISSUE TITLE
Problem with parallel_reudce to get Maximum value 

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#2011]
I am trying to get the maximum nonzero count of sparse matrix rows using the code on GPU below.  
However, I am seeing that it returns maxNonzPerRow=95 on GPU and 87 on CPU.

> AINDEX ( 0 ) 0
> AINDEX ( 1 ) 83
> AINDEX ( 2 ) 168
> AINDEX ( 3 ) 253
> AINDEX ( 4 ) 348
> AINDEX ( 5 ) 434
> AINDEX ( 6 ) 527
> AINDEX ( 7 ) 617
> AINDEX ( 8 ) 711
> AINDEX ( 9 ) 805
> AINDEX ( 10 ) 892

```
  SubIdx maxNonzPerRow;
  const auto reduceTeamSize = Kokkos::AUTO;
  Kokkos::parallel_reduce (Kokkos::TeamPolicy<>(nRows, reduceTeamSize), KOKKOS_LAMBDA (Kokkos::TeamPolicy<>::member_type team, SubIdx &ldMyMax)
  {
    const auto i = team.league_rank();
    ldMyMax = static_cast<SubIdx>( Aindex(i+1) - Aindex(i) ) ;
  }, Kokkos::Max<SubIdx>(maxNonzPerRow) );
```

**Comment by keitat** [comment]
Never mind. I found the solution..

**Comment by keitat** [comment]
I am using OpenMP for CPUs.

**Comment by vbrunini** [comment]
You're unconditionally updating ldMyMax in your lambda, you should only be updating it if the new value is larger than the current value.

**Comment by keitat** [comment]
Thanks!  I will do that.
