### ISSUE TITLE
unit_test Makefile is Broken - Recursively Calls itself until Machine Apocalypse.

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#202]
Seem to be having a problem with the Makefile in unit_test after I run ./generate_makefile.

I clone the Kokkos repo, create a directory for an out of source build, run `../generate_makefile.bash --with-openmp --arch=HSW --compiler=icpc` and then run make in unit_test causes infinite recursion.

**Comment by crtrott** [comment]
I can't reproduce that, can you post the output?

**Comment by crtrott** [comment]
Still can't reproduce it. Lets sit down again.

**Comment by crtrott** [comment]
This was tracked down to previously calling generate_makefile in the Kokkos root directory. That will overwrite the sub makefiles which will end up recursively calling itself if you try to build. 

To prevent that generate_makefile should check whether it is called inside of the kokkos root directory.

**Comment by nmhamster** [comment]
I thought we agreed we would modify the `generate_makefile.sh` to error on this case?

**Comment by crtrott** [comment]
Thats what I meant.
