### ISSUE TITLE
What is the expected way of setting the C++ standard with Kokkos in a CMake build?

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#2025]
What is the proper way of telling Kokkos the C++ standard you want when using a CMake (non-Tribits) build?  Currently I do it like this:
```
#---- Require C++14 without GNU extensions
SET(CMAKE_CXX_STANDARD 14)
SET(CMAKE_CXX_EXTENSIONS OFF)
```
because of this from kokkos_settings.cmake:
```
if (CMAKE_CXX_STANDARD)
  if (CMAKE_CXX_STANDARD STREQUAL "98")
    message(FATAL_ERROR "Kokkos requires C++11 or newer!")
  endif()
  set(KOKKOS_CXX_STANDARD "c++${CMAKE_CXX_STANDARD}")
  if (CMAKE_CXX_EXTENSIONS)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
      set(KOKKOS_CXX_STANDARD "gnu++${CMAKE_CXX_STANDARD}")
    endif()
  endif()
  set(KOKKOS_SETTINGS ${KOKKOS_SETTINGS} "KOKKOS_CXX_STANDARD=\"${KOKKOS_CXX_STANDARD}\"")
endif()
```
However this results in `-std=c++14` being put in CXX_FLAGS multiple times (presumably once by CMake and once by Kokkos), resulting in copious Kokkos warnings of the form
```
nvcc_wrapper - *warning* you have set multiple optimization flags (-std=c++1* or --std=c++1*), only the first is used because nvcc can only accept a single std setting
```
when building for CUDA.  However setting KOKKOS_CXX_STANDARD directly does not work.  

So how are you supposed to do this and not get tons of warnings?

**Comment by Char-Aznable** [comment]
I have to same issue here

**Comment by dholladay00** [comment]
I see this as well

**Comment by jjwilke** [comment]
We already have things of the form
````
ifneq ($(KOKKOS_CMAKE), yes)
  KOKKOS_CXXFLAGS = -I./ -I$(KOKKOS_PATH)/core/src -I$(KOKKOS_PATH)/containers/src -I$(KOKKOS_PATH)/algorithms/src -I$(KOKKOS_ETI_PATH)
endif
````
I suspect we can avoid putting the -std flag for CMake builds. 

Weird to me that CMake doesn't deduplicate this.

**Comment by jjwilke** [comment]
Related to #2035

**Comment by masterleinad** [comment]
I don't see this anymore.
