### ISSUE TITLE
resize without initializing

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#2028]
Right now `resize` does this:

```
  view_type v_resized( v.label(), n0, n1, n2, n3, n4, n5, n6, n7 );

  Kokkos::Impl::ViewRemap< view_type , view_type >( v_resized , v );

  v = v_resized ;
```

The `v_resized` constructor executes the `ViewValueFunctor` to fill the View with default initialied values prior to the `ViewRemap`. We should have a `resize` variant where `v_resized` is constructed without initializing.

**Comment by dhollman** [comment]
This is somewhat tangentially connected to #1873, so I'll assign myself to it for now and I can check in both fixes at the same time.

**Comment by ibaned** [comment]
closing in favor of more recent duplicate #2048
