### ISSUE TITLE
Don't keep labels in device allocation

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#2029]
We would save a lot of `cudaMemcpy` if the View label was stored as a `std::string` in `SharedAllocationRecord` instead of putting it in the allocation header.

**Comment by dhollman** [comment]
We need to be able to get to the label on the device for the purposes of things like bounds checking, etc.  A couple of options come to mind:

- We could put the label in the header only if features that need it are enabled
- We could provide a `View` trait that allows the user to control the accessibility of the label and enables/disables features that access it accordingly.

Thoughts?

**Comment by ibaned** [comment]
I guess we could store it in both places since it never changes. That way host queries could return the host copy instead of calling `cudaMemcpy`.
