### ISSUE TITLE
OpenMP 4.5 capability

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#2032]
xSDK-ECP team is asking OpenMP4.5+ capability with Kokkos.  I'd like to know what OpenMP4.5+ specific features reflected in the current Kokkos APIs and capability (tasking, threads, parallel loops, critical sections, barriers).

**Comment by ibaned** [comment]
I'd say parallel loops, critical sections, and barriers are all part of our current backends, as well as thread ID functions. There is work that could be done to make their use more canonical. Overall, a code can use OpenMP and Kokkos together effectively.

**Comment by keitat** [comment]
Thanks a lot!
