### ISSUE TITLE
How to suppress "Stack size for entry function XXX cannot be statically determined"?

### ISSUE THREAD

**Issue by bartlettroscoe** [kokkos/kokkos#2039]
Hello,

When we build Trilinos with Kokkos and CUDA disabled we get a flood of warnings of the form:

```
nvlink warning : Stack size for entry function '_ZN6Kokkos4Impl75_GLOBAL__N__51_tmpxft_00000fea_00000000_6_Kokkos_Cuda_Task_cpp1_ii_b2872e7123cuda_task_queue_executeEPNS0_9TaskQueueINS_4CudaEEEi' cannot be statically determined
```

According to:

* https://devtalk.nvidia.com/default/topic/524712/a-meaning-of-nvlink-warning-stack-size-for-entry-function-cannot-be-statically-determined/

This is benign warning that occurs with recursive code.  The make output for 'ninja' is over 1.5G due in part to these warnings.

Is there a way to suppress these warnings?

**Comment by ibaned** [comment]
This warning will always show up when RDC is being used, since the stack size required for virtual calls can't be determined. We might have to look for a secret warning silencing flag in NVCC, but to me this is more and more evidence of RDC's immaturity.

**Comment by bartlettroscoe** [comment]
@ibaned said:

> This warning will always show up when RDC is being used, since the stack size required for virtual calls can't be determined. We might have to look for a secret warning silencing flag in NVCC, but to me this is more and more evidence of RDC's immaturity.

Thanks for the FYI.  CTest and CDash can handle the flood of warnings but it will obscure other build warnings that might be more troubling so it would be good to find a way to silence them.   But RDC is not getting turned on the ATDM Trilinos CUDA builds by default just yet so we have some time to address this.

**Comment by sethrj** [comment]
Our [Celeritas project](https://github.com/celeritas-project/celeritas) has this same issue with [VecGeom](https://gitlab.cern.ch/VecGeom/VecGeom) which requires RDC :( and results in all sorts of complications as well as warnings.

As of CUDA 10.4 at least, you can pass an option directly to the linker to suppress these warnings by appending `-Xnvlink --suppress-stack-size-warning` to `CUDA_FLAGS`: see https://github.com/celeritas-project/celeritas/pull/334 .

**Comment by crtrott** [comment]
We are discussing what to do: but my gut feeling is that we should turn the warning off in our Kokkos tests build, but downstream projects should add the warning suppression on their own. Alternatively we could do something like "KOKKOS_ENABLE_MOSTLY_USELESS_WARNINGS_SUPRRESION"?

**Comment by stanmoore1** [comment]
This issue is also somewhat related: https://github.com/kokkos/kokkos/issues/2214

**Comment by sethrj** [comment]
I would suggest it be defined in a PUBLIC target compile options to apply internally (if the warnings show up when compiling) and downstream (if the warning always shows up when linking code)
```cmake
   # Suppress warnings from virtual function calls in RDC
   target_compile_options(kokkos
     PUBLIC "$<$<COMPILE_LANGUAGE:CUDA>:SHELL: -Xnvlink --suppress-stack-size-warning>"
   )
```
