### ISSUE TITLE
DualView lazy allocation

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#204]
This started as Trilinos Bugzilla Bug 6294 ("Be able to allocate Kokkos DualView initially only on one side (either one?)"): 

https://software.sandia.gov/bugzilla/show_bug.cgi?id=6294

I posted it on 25 Feb 2015.  Original test:

Currently, allocating a Kokkos::DualView requires allocation in both memory spaces (i.e., on host and device).  Applications might like to save limited device memory by starting with an allocation only on the host, and only moving to device on demand.  They might also like to avoid initializing on host if they never plan to use that side.

Thus, I would like it to be possible to create a DualView such that it is allocated only on one side.  modify() on memory space M0, or sync() to M0, would allocate in M0, if it hasn't already been allocated.

Allocation on only one memory space M0 should mean that the DualView is marked modified on M0, at creation of the DualView.  That way,
1. It is incorrect to read or modify on the other (unallocated) memory space M1, until the user sync()s to M1.
2. The user's sync() to M1 signals that they want to allocate on M1.

This change will mean that we will need to go through Tpetra to ensure that no methods attempt to read from an unallocated memory space.  We can do this by checking the modified flags, and only reading from the most recently modified

**Comment by ibaned** [comment]
Reasonable feature, but without some driving need we likely won't implement this.
