### ISSUE TITLE
Construct DualView without initialization

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#2046]
There should be a way of doing this because we can do it for either side of the DualView

**Comment by crtrott** [comment]
You can currently work around that by constructing a DualView from its two nested views. But yes the more advanced constructors of view should be added.

Workaround:
```c++
typedef DualView<double*> view_type;
view_type a(view_type::t_dev(ViewAllocateWithoutInitializing("Label"),N),
            view_type::t_host(ViewAllocateWithoutInitializing("Label"),N));
```

**Comment by mhoemmen** [comment]
@Char-Aznable You may find this Tpetra example helpful.  It creates a DualView, optionally without initialization.

https://github.com/trilinos/Trilinos/blob/a04a0956dd4354e0bdae2317f538c411e9a49c23/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp#L142

**Comment by crtrott** [comment]
Done through #2842
