### ISSUE TITLE
Add Method to Resize View without Initialization

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2048]
Can a way to resize a view without any initialization please be added? The values are just going to be overwritten in the next parallel region.

**Comment by stanmoore1** [comment]
See also #1877.

**Comment by stanmoore1** [comment]
Actually looking at this more, I think the initialization is only on the "new" part of the view. I'd still like a way to resize without any initialization though, since the values are just going to be overwritten in the next parallel region.

**Comment by Char-Aznable** [comment]
I asked the same question on the Slack channel. It seems the answer for now is to use unmanaged view

**Comment by mhoemmen** [comment]
You don't have to use an unmanaged View.  Just create a new View, uninitialized, and assign to the old one.  That's what `Kokkos::resize` does anyway.

**Comment by stanmoore1** [comment]
Can only resize managed views, so can't use unmanaged in this case. A static assert prevents this, see https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_CopyViews.hpp#L1839.

>That's what Kokkos::resize does anyway

No, I don't think that is true, for example see https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_CopyViews.hpp#L470.

**Comment by stanmoore1** [comment]
@mhoemmen unless by "assign" you mean copy element by element...

**Comment by stanmoore1** [comment]
Maybe I need to explain what I need a little better. When I call `Kokkos::resize` on a view, I want to preserve the existing values, *without* initializing the extra empty space, since the new space will just be overwritten in the next parallel region. So the existing values in the old view have to be copied element by element in the new view.

**Comment by stanmoore1** [comment]
@mhoemmen pretty sure you are thinking of `realloc`, not `resize`.

**Comment by Char-Aznable** [comment]
@stanmoore1 I didn't mean resizing the unmanaged directly. Can you create an unmanaged view with the desired dimension by wrapping the pointer from the old view?

**Comment by stanmoore1** [comment]
>Can you create an unmanaged view with the desired dimension by wrapping the pointer from the old view?

I could create a new larger view that is uninitialized and copy element by element manually, but then I'm recreating the `Kokkos::resize` method on my own, which is not convenient. I'm not trying to get around the element by element copy, I don't think that is possible except for really special cases. I am trying to get around the initialization that wastes another CUDA kernel launch, the overhead of which can be significant when you are launch latency bound.

**Comment by stanmoore1** [comment]
Just to be 100% clear, `Kokkos::resize` preserves old values, while `Kokkos::realloc` does not. `Kokkos::resize` copies all the values from the old view into the new view element-by-element by launching a `parallel_for` on the device. It also initializes the new values in the new view by launching another `parallel_for` on the device, which is what I want to avoid.

**Comment by stanmoore1** [comment]
Actually, it is worse that I thought. Kokkos isn't just initializing the "extra" in the new view, it is initializing the entire new view, even though most of the values will just be copied over in the next operation. You can see that using this code. 

```c++
#include <Kokkos_Core.hpp>
#include <cstdio>

typedef Kokkos::View<int*> view_type;

int main (int argc, char* argv[]) {
  Kokkos::initialize (argc, argv);
  {
    const int N = 10;
    view_type a (Kokkos::view_alloc("A",Kokkos::WithoutInitializing), N);
    Kokkos::resize(a,2*N);
  }
  Kokkos::finalize ();
}
```
I used `kernel_logger` and also put a `printf` statement in the view initialization function:

```
KokkosP: Allocate<Cuda> name: A pointer: 0x7fff5a200080 size: 40
KokkosP: Allocate<Cuda> name: A pointer: 0x7fff5a200280 size: 80
KokkosP: Executing parallel-for kernel on device 0 with unique execution identifier 0
KokkosP: Kokkos::View::initialization
Initialized 80
KokkosP: Execution of kernel 0 is completed.
KokkosP: Executing parallel-for kernel on device 0 with unique execution identifier 1
KokkosP: Kokkos::ViewCopy-1D
KokkosP: Execution of kernel 1 is completed.
KokkosP: Deallocate<Cuda> name: A pointer: 0x7fff5a200080 size: 40
KokkosP: Deallocate<Cuda> name: A pointer: 0x7fff5a200280 size: 80
```

**Comment by mhoemmen** [comment]
> pretty sure you are thinking of `Kokkos::realloc` instead of `Kokkos::resize`

my bad; thanks!

**Comment by ibaned** [comment]
I opened a duplicate earlier, (#2028), but I'll close that one in favor of this one because this one has user data showing why this is expensive.

**Comment by ibaned** [comment]
@dhollman volunteered on #2028, so I'll assign him to this one

**Comment by ibaned** [comment]
The CoPA/Cabana team also needs this feature.

**Comment by vqd8a** [comment]
Is adding something like ```Kokkos::resize( Kokkos::view_resize (WithoutInitializing), A, 2*N )``` okay?

**Comment by stanmoore1** [comment]
>Is adding something like Kokkos::resize( Kokkos::view_resize (WithoutInitializing), A, 2*N ) okay?

Yes, seems fine to me.
