### ISSUE TITLE
Kokkos::deep_copy from 2-D HostSpace to (Cuda, CudaSpace) View throws

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#2051]
`Kokkos::deep_copy` from a `Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<0u> >` to `Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::HostSpace>` throws the following exception:

```
Error: Kokkos::deep_copy with no available copy mechanism: Reference View to Reference View_mirror
```

I don't get this with rank-1 Views, or with a rank-2 `(Cuda, CudaUVMSpace)` View.

This means that I can't sync a `DualView<double**, Device<Cuda, CudaSpace>>`; that's how I found this error.

**Comment by mhoemmen** [comment]
It looks like the problem is that, for Views with rank > 1, `view_copy` [expects to be able to run a kernel that can access both input and output Views](https://github.com/kokkos/kokkos/blob/5d6e7fb38e96aec88d2c514e1f9be1cf2b549b57/core/src/Kokkos_CopyViews.hpp#L641).  It prefers the output View's execution space, but can also run on the input View's execution space.  However, in this case, neither execution space can access the opposite's memory space.  That's why `cudaMemcpy` exists.

**Comment by mhoemmen** [comment]
CUDA has [cudaMemcpy2D](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g3a58270f6775efe56c65ac47843e7cee); we could try using that for rank 2, LayoutLeft Views.

**Comment by ibaned** [comment]
There must be something more subtle going on, I think there is tons of production code that does device to host `deep_copy` of higher-dimensional Views.

**Comment by ibaned** [comment]
For now, seems like a bug in our determination of copy mechanism based on traits

**Comment by mhoemmen** [comment]
@ibaned this code path _should_ only be reached if Kokkos determines that one of the Views isn't contiguous, no?

**Comment by jeffmiles63** [comment]
I believe I can confirm this theory, but if you have a case where the views aren't contiguous, then there is reason for it to fail...there are about 15 different code paths within the internal view_copy that are possible if the view/s aren't contiguous, none of which use the DeepCopy struct (which invokes cudaMemcpy).  @mhoemmen, do you have a code snippet of the DualView usage that is failing?

**Comment by ibaned** [comment]
@mhoemmen no, using different layouts in different memory spaces should also be an error. But your types should *not* hit this error case, so our plan is to have @jeffmiles63 add a unit test that `deep_copies` between these types to see if the same thing happens and figure out why.

**Comment by mhoemmen** [comment]
@jeffmiles63 something like this:
```c++
using device_type = Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>;
using array_layout = Kokkos::LayoutLeft;
using dual_view_type = Kokkos::DualView<double**, array_layout, device_type>;
using dev_view_type = dual_view_type::t_dev;
using host_view_type = dual_view_type::t_host;

const size_t num_rows = 1;
const size_t num_cols = 1;
dev_view_type d_view ("d_view", num_rows, num_cols);
host_view_type h_view ("h_view", num_rows, num_cols);
Kokkos::deep_copy (h_view, 418.0);

dual_view_type dual_view (d_view, h_view);
dual_view.modify_host ();
dual_view.sync_device (); // throws
```

**Comment by crtrott** [comment]
This works for me both on develop and master.

**Comment by crtrott** [comment]
I extended the test to include what you said earlier was the issue and I still can't make it fail with either UVM on or off. 

```c++
#include<Kokkos_Core.hpp>
#include<Kokkos_DualView.hpp>
#include<cmath>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
    int N = argc>1?atoi(argv[1]):10000;
    int M = argc>2?atoi(argv[2]):10000;

    using device_memory_space = Kokkos::CudaSpace;
    using device_type = Kokkos::Device<Kokkos::Cuda, device_memory_space>;
    using array_layout = Kokkos::LayoutLeft;
    using dual_view_type = Kokkos::DualView<double**, array_layout, device_type>;
    using dev_view_type = dual_view_type::t_dev;
    using host_view_type = dual_view_type::t_host;

    const size_t num_rows = N;
    const size_t num_cols = M;
    dev_view_type d_view ("d_view", num_rows, num_cols);
    host_view_type h_view = Kokkos::create_mirror_view (d_view);
    Kokkos::deep_copy (h_view, 418.0);

    dual_view_type dual_view (d_view, h_view);
    dual_view.modify_host ();
    dual_view.sync_device (); // throws

    Kokkos::View<double**,array_layout,
         device_type,Kokkos::MemoryTraits<Kokkos::Unmanaged>> 
      d_view_um(d_view.data(),d_view.extent(0),d_view.extent(1));
    Kokkos::View<double**,array_layout,Kokkos::HostSpace> 
      h_view_raw("h_view",d_view.extent(0),d_view.extent(1));

    Kokkos::deep_copy(h_view_raw,d_view_um);
    Kokkos::deep_copy(d_view_um,h_view_raw);
  }
  Kokkos::finalize();
}
```

**Comment by mhoemmen** [comment]
I'll try this again once I get the chance.

**Comment by crtrott** [comment]
@mhoemmen is this still a problem?

**Comment by mhoemmen** [comment]
@crtrott I'll close this and reopen if it becomes a problem again.  Thanks!
