### ISSUE TITLE
Question: view element access operator() member functions

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2057]
Why are these templated on the integral types?
Why are the indices passed by const reference?
Do we have a benchmark that shows that this is more performant than passing them by values and using the view member type `size_type`.

**Comment by ibaned** [comment]
I do know that the templating on integral type is necessary to prevent tons of warnings about signed/unsigned conversion if users pass in signed integers.

I think changing them to pass by value would be a positive change though, although I don't think we're losing performance in the common case by using `const&`.

**Comment by dalg24** [comment]
> I do know that the templating on integral type is necessary to prevent tons of warnings about signed/unsigned conversion if users pass in signed integers.

You would get the same sign conversion warnings with `std::vector::operator[]`.  Is there another rational besides suppressing the warnings?

**Comment by ibaned** [comment]
I think there is some user with actually negative indices that are valid

**Comment by dhollman** [comment]
We should actually remove SFINAE entirely from the `View` call operator.  We should get massive compilation time improvements from that.  We talked about how to do this in a side conversation at the Oakland bootcamp, and I'm going to give it a shot at some point.

**Comment by ibaned** [comment]
@dhollman I guess this is somewhat orthogonal, if there is no `enable_if` on the Integral type itself would it still be okay to template on the Integral type?

**Comment by dalg24** [comment]
> @dhollman I guess this is somewhat orthogonal, if there is no `enable_if` on the Integral type itself would it still be okay to template on the Integral type?

Yes, it would be fine.

But if the only goal was to suppress the warning we could also look into using diagnostic pragmas instead of templating.

**Comment by dalg24** [comment]
We also discussed the possibility of using variadic templates and perfect forwarding arguments to `Impl::ViewMapping::reference()`.

**Comment by dhollman** [comment]
I tried ripping all of the SFINAE out and using partial specializations and the compilation time did not appear to decrease in a few cursory tests.  However, I've run some code through the templight profiler, and it looks like the majority of our compile time is spent in `View::operator()`, so it's worth thinking about very carefully.

**Comment by crtrott** [comment]
Actually the reason that we do the templating is so that we do get 32 bit integer index calculations when possible. I.e. if the user asked for IndexType<int32_t> in their execution policy, and uses int32_t all throughout his code, we don't want it to convert to int64_t or size_t for the index calculation. 1) conversion can take cycles, and 2) vectorization length will be halved.

**Comment by PhilMiller** [comment]
#4800 addressed the pass-by-reference concern, and was released in 3.7.

Christian answered the templating concern.
