### ISSUE TITLE
CMake install not including path in Makefile.kokkos

### ISSUE THREAD

**Issue by attom** [kokkos/kokkos#2058]
When CMake is used to make Kokkos, the Makefile.kokkos does not include the path to Kokkos in either KOKKOS_CPPFLAGS or KOKKOS_CXXFLAGS

**Comment by jjwilke** [comment]
Could you be more specific about what you mean by "does not include" and "path to Kokkos"? 

* Errors occur while building Kokkos?
* Errors occur building a project that depends on Kokkos?
* What are you doing to link your cmake project against kokkos? Just `target_link_libraries(...)`?

**Comment by jjwilke** [comment]
Makefile.kokkos is no longer part of the CMake. I believe it is okay to close this?

**Comment by mhoemmen** [comment]
Kokkos normally only closes issues once the fix merges into master.  You can label issues fixed in develop with the "inDevelop" tag.

**Comment by jjwilke** [comment]
I think we are good to clear this.
