### ISSUE TITLE
Team reduction for array type

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#206]
Moved from Trilinos issue. 

Currently team reduction is designed for scalar type and I need team reduction for array and the array should be thread specific. The input array may have initial values.

template< typename iType, class Lambda, typename ValueType, class JoinType >
KOKKOS_INLINE_FUNCTION
void parallel_reduce(const Impl::TeamThreadRangeBoundariesStruct& loop_boundaries,
const Lambda & lambda, const JoinType& join, ValueType& init_result) {

ValueType result = init_result;

for( iType i = loop_boundaries.start; i < loop_boundaries.end; i+=loop_boundaries.increment) {
ValueType tmp = ValueType();

/// this tmp initialization should be reconsider to use thread local array.

lambda(i,tmp);
join(result,tmp);
}

init_result = loop_boundaries.thread.team_reduce(result,Impl::JoinLambdaAdapter(join));
}

**Comment by crtrott** [comment]
This doesn't quiet make sense to me. Could you post a full little reproducer (i.e. main and so on?)

Thanks

**Comment by dsunder** [comment]
This might have been done with Christian's reduction refactor.  @kyungjoo-kim is this still an issue or can we close it?

**Comment by ibaned** [comment]
Closing for lack of response, please comment if its still an issue.
