### ISSUE TITLE
Kokkos::ALL for first dimension breaks on GPU

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2060]
The problem is that we have a `const Arg1&` in the subview constructor.  We need:

- A test that does this inside a kernel so that `nvcc` has to use it
- The small fix that removes the reference on this parameter

**Comment by ndellingwood** [comment]
Fixed by @crtrott with SHA 2bee6b816, removing the BLOCKS PROMOTION tag

**Comment by ndellingwood** [comment]
Will add a unit test
