### ISSUE TITLE
View::host_mirror_space can be a memory space and an execution space

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#2062]
if
```c++
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using T = Kokkos::View<int**,ExecutionSpace>;
``` 
then `T::host_mirror_space` is `Kokkos::OpenMP`, which is an execution space, when `ExecutionSpace` is `OpenMP`;  
or `T::host_mirror_space` is `Kokkos::HostSpace`, which is a memory space, when `ExecutionSpace` is `Kokkos::Cuda`

This gives troubles doing metaprogramming when one want to figure out the execution space for things like `RangePolicy<>` because a memory space can't be used directly as an execution space

**Comment by mhoemmen** [comment]
@Char-Aznable I like to be specific about whether I want an execution space or a memory space.  That's avoided pain in the past with DualViews.  Just ask for `T::host_mirror_space::execution_space` and you should always get an execution space.

**Comment by Char-Aznable** [comment]
There is an easier way and cleaner way for that, just define and use `T::HostMemorySpace` and `T::ExecutionSpace`. I simply don't see why these concepts have to be mingled

**Comment by dhollman** [comment]
We're in the process of cleaning up the Concept structure of Kokkos, but one of the things on the list is to be a bit more specific about places you expect to get an execution space, places you expect to get a memory space, and places where you expect that passing an execution space is a shortcut for passing `ExecSpace::memory_space`.  The confusion currently arises from the third case, and AFAICT what you've pointed out is (essentially) a bug in Kokkos where we have propagated this "shortcut" to a nested type alias.  Thanks for pointing this out; we'll add this to the list of things that needs to be addressed as we do the concept structure cleanup.

**Comment by crtrott** [comment]
Make this a memory space.

**Comment by Char-Aznable** [comment]
@ndellingwood What is the conclusion on this now? Is View::host_mirror_space consistently a memory space?

**Comment by masterleinad** [comment]
Yes, #2158 addressed this.
