### ISSUE TITLE
TestScatterView Failure on Bowman (KNL)

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2068]
Build info:
```
Compiler:         icpc
C++ Flags:        -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized
Kokkos-Arch:      KNL
Kokkos-Options:   
Compiler-Module:  intel/compilers/17.1.132
HWLOC:            hwloc/1.11.3
Backend:          OpenMP,Serial
```

Failure message:
```
/home/jenkins/bowman/workspace/Kokkos_SLURM_inner_test/containers/unit_tests/TestScatterView.hpp:326: Failure
Value of: std::fabs((val0 - 16.0) / 16.0) < 1e-15
  Actual: false
Expected: true
[  FAILED  ] openmp.scatterview (124756 ms)
```

Maybe the tolerance needs to be a bit more forgiving to handle non-determinism when running in parallel? This test has failed on Bowman in the past week, appears to be random.

[Link to full error log](https://jenkins-son.sandia.gov/job/Kokkos_SLURM_inner_test/24454/consoleFull)

**Comment by crtrott** [comment]
Yeah 1e-15 may be to tight. Probably needs 1e-14 or so depending on how many contribution we combine.

**Comment by ndellingwood** [comment]
PR #2081 issued with loosened tolerances.
