### ISSUE TITLE
Trilinos develop branch fails to configure with VOTD Kokkos

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2069]
This occurred with an attempted Cuda build on White (Kepler node)

CMake configure error message:

```
Processing enabled package: Gtest (Libs)
Processing enabled package: Kokkos (Core, Containers, Algorithms, Tests)
CMake Error at kokkos/core/unit_test/CMakeLists.txt:28 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "kokkos_gtest".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * cmake/tribits/core/package_arch/TribitsLibraryMacros.cmake:860 (TARGET_LINK_LIBRARIES)

...
-- Configuring incomplete, errors occurred!
```

**Comment by ndellingwood** [comment]
@dhollman it looks like one of your PRs added the following lines to `kokkos/core/unit_tests/CMakeLists.txt`:

```
target_compile_options(
  kokkos_gtest
  PUBLIC $<$<COMPILE_LANGUAGE:CXX>:${KOKKOS_CXX_FLAGS}>
)
target_link_libraries(
  kokkos_gtest
  PUBLIC ${KOKKOS_LD_FLAGS}
)
```

In particular, the `target_link_libraries` is causing the problem above in Trilinos. What was the reason for the addition, and Is it safe to pull this out? Or would you suggest an alternative way to resolve the issue above?

**Comment by ndellingwood** [comment]
@dhollman I put in PR #2070 that removes the lines above and the added function to the CMakeLists.txt file which allows Trilinos to configure with VOTD Kokkos for testing. If you have time to look into this soon and get those changes working with Trilinos then #2070 can be closed, otherwise we can merge that PR temporarily until you can revisit if you think that is acceptable.

**Comment by kyungjoo-kim** [comment]
Thanks for the fix.

**Comment by dhollman** [comment]
In non-trilinos mode, Kokkos doesn't put the correct flags on the `kokkos_gtest` target.  These lines add those flags and link to the correct libraries.

You can reproduce this problem by compiling Kokkos with non-Trilinos CMake and with something like `gcc-4.9`.  The compilation will complain about missing C++11 functionality while compiling google test, even if the Kokkos C++ standard is set correctly.

**Comment by dhollman** [comment]
So I basically can't compile Kokkos tests (in my non-Trilinos CMake workflow) without these lines.

I chalk this one up to another example of how our CMake *really*, **seriously** needs to be overhauled.

**Comment by ndellingwood** [comment]
@dhollman 

> I chalk this one up to another example of how our CMake _really_, **seriously** needs to be overhauled.

Indeed, I also ran into issues trying to build tests with stand-alone CMake awhile back but wasn't sure if it was ever supported outside of Trilinos. Are you able to work on a fix for this issue that satisfies your workflow and getting Trilinos to compile? I can use the branch for PR #2070 to begin Trilinos integration testing, but a fix will need to go in for the next promotion, I'll leave #2070 as a backup for now.

**Comment by dhollman** [comment]
@jjwilke What should I be doing here? Do you have this fixed in your branch?

**Comment by jjwilke** [comment]
I should be working on this next week (should). This sounds familiar? What was going in `KOKKOS_LD_FLAGS`? That should usually just be CMake target names (or possibly name X to link a system lib -lX).  I believe the default behavior of `target_link_libraries` is public, so you could try omitting it - or conditionally calling it when you're not in Trilinos mode (subideal, but will work for time being)

**Comment by ndellingwood** [comment]
@jjwilke is this as simple as adding guards around the lines causing Trilinos issues, something like:

```
IF(KOKKOS_HAS_TRILINOS)
...
ENDIF()
```

Maybe this should be obvious, but I'm not very confident when making CMake changes, especially when Trilinos + Tribits come into play.

**Comment by ndellingwood** [comment]
Alright, that change seemed to work so I'm going to put in a new PR with that fix.

**Comment by jjwilke** [comment]
That should be a good stop gap. @dhollman: What is the exact set of flags that go in `KOKKOS_LD_FLAGS`?

**Comment by ndellingwood** [comment]
PR #2073 issued with the stop-gap.

**Comment by dhollman** [comment]
I have no idea on exact flags, but I know the C++11 flag was missing from the GTest build at the very least. Thanks for helping with this, everyone!
