### ISSUE TITLE
md range policy behavior....

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#2076]
MDRangePolicy will determine the iteration space wisely. Does this mean that I am going to have the same performance for the following case ?
```
MDRangePolicy<space,Rank<2>, IndexType<int> > policy_a({0,0}, {m, 1});
MDRangePolicy<space,Rank<2>, IndexType<int> > policy_b({0,0}, {1, m});
```

Can I expect that the both in the above perform like a range policy ? 
```
RangePolicy<space> policy_c(0, m);
```

As the md policy considers multiple aspects of the iteration spaces, I kind of feel it difficult to expect how it works. Could someone explain how the iteration space is determined ?

**Comment by crtrott** [comment]
It is probably not as wise as you would hope ;-)

We are planning a major optimization effort for MDRange soon ...
