### ISSUE TITLE
threads.team_vector failure

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2085]
@crtrott following the fixes that went in today the team_vector unit test is failing with the threads backend, gcc/7.3.0 and clang 3.8 and 4.0 builds

```
[ RUN      ] threads.team_vector
<https://jenkins-son.sandia.gov/job/Kokkos_develop_kokkos-dev_gcc_730_deprecated_off/ws/kokkos/core/unit_test/TestTeamVector.hpp>:976: Failure
Value of: ( TestTeamVector::Test< TEST_EXECSPACE >( 6 ) )
  Actual: false
Expected: true
```

**Comment by ndellingwood** [comment]
This is failing many jobs on Blake and Bowman, added BLOCKS PROMOTION tag.

**Comment by crtrott** [comment]
This is basically #1905 not yet fixed for threads. The unit test is catching that.
