### ISSUE TITLE
parallel_reduce with const return value reference doesn't fail like it should

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2090]
The following snippet compiles, runs, and prints `0`:

```c++
    const int value = 0;

    Kokkos::parallel_reduce(42,
      KOKKOS_LAMBDA (int i, int& result) {
        result += 1;
      },
      value
    );

    Kokkos::fence();
    std::cout << value << std::endl;
```

This feels like a bug...

**Comment by dhollman** [comment]
I'll clean this up along with #2034 and #2088, but for now I thought it should be documented as a known bug.

**Comment by crtrott** [comment]
Its not a bug. Its user error, but we can help the user.

**Comment by crtrott** [comment]
I.e. bugs are generally things which are expected to work, but don't.

**Comment by crtrott** [comment]
Oh I see where this is coming from ...

**Comment by ajpowelsnl** [comment]
@dalg24 and @masterleinad -- can we close this issue?

**Comment by masterleinad** [comment]
@ajpowelsnl It has the `InDevelop` tag.
