### ISSUE TITLE
Modify CMake to find hwloc, memkind, and librt

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2098]
Kokkos has a limited number of TPLs. We should be creating imported CMake targets for them directly rather than relying on Makefile to append CXXFLAGS, etc.

All TPL operations should be guarded in the Makefile by:

````
ifneq ($(KOKKOS_CMAKE), yes)
````

**Comment by jjwilke** [comment]
Include `-ldl` in this.

**Comment by masterleinad** [comment]
Addressed in #2104.
