### ISSUE TITLE
Universal Kokkos find_package

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2099]
Kokkos currently gets installed with a bunch of different names - both at the library level (Tribits names, single lib, multiple libs) and even the package name level.

We really need to make this easier for people. I recommend always installing a kokkosConfig.cmake so the following is valid no matter what kokkos installation is done
````
FIND_PACKAGE(kokkos)
````
and probably extending this to add a function like
````
TARGET_LINK_KOKKOS(myTarget)
````

**Comment by jjwilke** [comment]
Assertions have been added to the `target_link_kokkos` function. Users can now call:

target_link_kokkos(myTarget
   TPLS ...
   DEVICES ...
   ARCH ...
   OPTIONS
)

**Comment by masterleinad** [comment]
Addressed in #2104.
