### ISSUE TITLE
Simplify teams + shared memory histogram example to remove vectorization

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#21]
kokkos/example/tutorial/Hierarchical_Parallelism/03_vectorization/vectorization.cpp

It would be helpful for the Kokkos tutorial to have a histogram example that uses shared memory, but doesn't have three levels of parallelism.

**Comment by crtrott** [comment]
This will be addressed in the formal tutorial development project to be done by the end of this summer.
