### ISSUE TITLE
Custom init() function for parallel_reduce with array value_type

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#210]
I have a functor that does reduction on an array that requires a non-trivial init() function, however I am finding that my functor's init function is not getting called.  Here are the relevant parts of the declaration:

```
struct MaxMinFunctor {
  typedef double value_type[];

   KOKKOS_INLINE_FUNCTION
   void init (value_type dst) const { ... }

```
By adding print and assert statements I can verify init() is not getting called.  Looking at the Kokkos source code, I see this:

```
template< class FunctorType , class ArgTag >
struct FunctorValueTraits< FunctorType , ArgTag , true /* == exists FunctorType::value_type */ >
{
  typedef typename Impl::remove_extent< typename FunctorType::value_type >::type  value_type ;

  // If not an array then what is the sizeof(value_type)
  enum { StaticValueSize = Impl::is_array< typename FunctorType::value_type >::value ? 0 : sizeof(value_type) };

  typedef value_type                 * pointer_type ;

  // The reference_type for an array is 'value_type *'
  // The reference_type for a single value is 'value_type &'

  typedef typename Impl::if_c< ! StaticValueSize , value_type *
                                                 , value_type & >::type  reference_type ;
```

and this

```
// Function signatures for FunctorType::init function without a tag and is an array
template< class FunctorType >
struct FunctorValueInitFunction< FunctorType , void , true > {

  typedef typename FunctorValueTraits<FunctorType,void>::reference_type value_type ;

  KOKKOS_INLINE_FUNCTION static void enable_if( void (FunctorType::*)( value_type * ) const );
```

Shouldn't that be:
 
`  KOKKOS_INLINE_FUNCTION static void enable_if( void (FunctorType::*)( value_type ) const );`

given that reference_type for an array is value_type *?

If I add an empty overload of "void init(double**) const {}"  to my functor it works and the correct init function is called.  This seems like a bug, or am I just doing something stupid?

**Comment by crtrott** [comment]
Can you try init(value_type& dat), I believe we expect a reference to the value_type.

**Comment by hcedwar** [comment]
The value_type is a dynamic length array, so appears to be a bug in the 'is there an init function' introspection.

**Comment by etphipp** [comment]
Changing it to a reference doesn't work, and in fact introduces a compiler error:

> /home/etphipp/Trilinos/Trilinos/packages/trilinoscouplings/examples/fenl/SampleGrouping.hpp:260:33: error: parameter âdstâ includes reference to array of unknown bound âKokkos::Example::FENL::MaxAnisotropyGrouping<Scalar, MeshType, CoeffFunctionType>::MaxMinFunctor::value_typeâ
>      void init (value_type& dst) const

**Comment by etphipp** [comment]
My belief is the introspection is wrong and it should be

`KOKKOS_INLINE_FUNCTION static void enable_if( void (FunctorType::*)( value_type ) const );`

instead of

`KOKKOS_INLINE_FUNCTION static void enable_if( void (FunctorType::*)( value_type* ) const );`

since value_type is already a pointer.

**Comment by crtrott** [comment]
Not so sure. It looks like we need to test for both. If your value_type is a "double" then the signature is
value_type& not value_type for the init thing.

**Comment by crtrott** [comment]
Carter can you do this?

**Comment by etphipp** [comment]
Btw, changing it to a static-length array doesn't make it work either.

**Comment by crtrott** [comment]
Yeah I wouldn't expect it too.

**Comment by etphipp** [comment]
You actually do all of that stuff already.  My point was the test for when value_type is an array is wrong.  The separate test for when value_type is not an array is correct.

**Comment by crtrott** [comment]
Oh ok. So it should be easy to fix :+1:

**Comment by etphipp** [comment]
Yes, I think I told you how to fix it :smiley:

**Comment by crtrott** [comment]
Pushed to master, closing the issue
