### ISSUE TITLE
Link/Compiler flag propagation for Clang CUDA

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2100]
Standalone will correctly pass along PUBLIC flags for Clang CUDA. Tribits does not.

Now that CMake 3 is used under the hood, we should change the Tribits Kokkos build to call
````
TARGET_COMPILE_FLAGS(...)
````
Downstream projects like SPARC are not receiving the necessary compiler flags from Trilinos.
This happens to work right now with nvcc_wrapper, but does not work Clang.

**Comment by masterleinad** [comment]
In #2104.
