### ISSUE TITLE
Warning in Kokkos_Cuda_UniqueToken

### ISSUE THREAD

**Issue by jhux2** [kokkos/kokkos#2102]
On waterman, I'm seeing a number of Kokkos warnings of this type from within Trilinos develop:
```
/ascldap/users/jhu/software/trilinos/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp(88): warning: calling a __host__ function("Teuchos::RCP<const  ::Tpetra::Map<int, int,  ::Kokkos::Compat::KokkosDeviceWrapperNode< ::Kokkos::Serial,  ::Kokkos::HostSpace> > > ::RCP") from a __host__ __device__ function("Tpetra::CrsGraph<int, int,  ::Kokkos::Compat::KokkosDeviceWrapperNode< ::Kokkos::Serial,  ::Kokkos::HostSpace> > ::CrsGraph [subobject]") is not allowed
```

This is cuda 9.2.88 and gcc 7.2.0.

I'm compiling on waterman in the ATDM way:

source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-opt

args=(
  -GNinja
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON
)

cmake "${args[@]}" $TRILINOS_DIR

**Comment by mhoemmen** [comment]
If I remember right, these are harmless.  @crtrott explained (if I remember right) that it may be impossible to fix these for both nvcc and Clang builds of CUDA.

**Comment by crtrott** [comment]
Uhm not sure if that one is harmless. Also I am not sure how you got to that point.

**Comment by mhoemmen** [comment]
We definitely have seen these before.  `Tpetra::Map` doesn't actually keep a `UniqueToken` instance, so there's no reason that CrsGraph's destructor should need to invoke `UniqueToken`'s destructor.

**Comment by crtrott** [comment]
It looks more like the CrsGraphs stuff called inside UniqueToken?

**Comment by mhoemmen** [comment]
I think what's happening is that a functor or lambda happens inside CrsGraph (though it does _not_ capture `this` or `*this` for device execution), and the compiler is being too conservative about what it thinks the functor actually calls.

**Comment by crtrott** [comment]
Is this still an issue?

**Comment by crtrott** [comment]
@jhux2 if this is still an issue you probably want to open it on the Trilinos side ...
