### ISSUE TITLE
Layout documentation request

### ISSUE THREAD

**Issue by lshulen** [kokkos/kokkos#2106]
I would like to use a custom layout for a view in an application in order to mimic previous work done on the project that improves cache blocking by tiling one of the dimensions of the view.  I've done a fair amount of googling / reading the source code and the best I have found so far is an admonition on the wiki to read the source and discussions on GitHub about other layouts people have implemented or are thinking about.

It would be very useful to have documentation about what one needs to do make your own customized layout and also to have more documentation / examples of other layouts that have already been created.

**Comment by PhilMiller** [comment]
https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/View.html#other-layouts somewhat addresses this - it says to specialize `ViewMapping`, and what to take as a starting point. Always room for improvement, but I think we can close this for now.
