### ISSUE TITLE
User-level atomics on the CPU should not imply a full barrier

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2107]
According to the [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/_005f_005fsync-Builtins.html#g_t_005f_005fsync-Builtins), the intrinsics we're using to implement CPU-side atomics (e.g., `Kokkos::atomic_fetch_add` is implemented with `__sync_fetch_and_add`) imply a full barrier (see fifth paragraph of the page linked here).  We should instead be using the [memory-model aware intrinsics](https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/_005f_005fatomic-Builtins.html#g_t_005f_005fatomic-Builtins).  These are available in every version of GCC that we support (see [4.8.4 docs here](https://gcc.gnu.org/onlinedocs/gcc-4.8.4/gcc/_005f_005fatomic-Builtins.html#_005f_005fatomic-Builtins)).

**Comment by masterleinad** [comment]
`Desul` uses the memory-model aware intrinsics.

**Comment by ajpowelsnl** [comment]
@dalg24 and @masterleinad  -- can we close this issue?

**Comment by masterleinad** [comment]
> @dalg24 and @masterleinad -- can we close this issue?

Likely. `desul` should be mandatory soon anyway.

**Comment by ajpowelsnl** [comment]
> > @dalg24 and @masterleinad -- can we close this issue?
> 
> Likely. `desul` should be mandatory soon anyway.

If / when `desul` becomes the law of the land, @masterleinad would you please close this issue with a comment?

**Comment by dalg24** [comment]
We are using them in Desul
