### ISSUE TITLE
Errors -DKOKKOS vs -DKokkos for certain options

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2108]
We need to pick a "case" for Kokkos options for the standalone CMake. Since Trilinos uses lowercase (and the package is named Kokkos), the most sensible thing seems to be to have users use `-DKokkos_...`

This is currently breaking CMake because some (but not all) Kokkos options are given default values as `Kokkos_....`.  For example, if you give:
````
-DKOKKOS_ENABLE_OPENMP=ON
````
configure crashes because a default value `Kokkos_ENABLE_OpenMP=OFF` was given.

**Comment by jjwilke** [comment]
The variables get 'case-insensitized' anyway internally. For now,  in standalone, I am turning off all defaults for enable variables (this defaults to OFF anyway for undefined variables) so no Kokkos_ENABLE or KOKKOS_ENABLE variables are in the cache.

This will allow us to delay a decision on 'canonical' variable names. The allowed ways to specify enable options will now be, e.g.
````
-DKOKKOS_ENABLE_OPENMP=X
````
OR
````
-DKokkos_ENABLE_OpenMP=X
````

**Comment by jjwilke** [comment]
Okay, I lied. I'm not going to touch the `set_kokkos_default_default` functions.

This is fragile, but working as long as no defaults are set BEFORE the 'case-insensitive' loop in kokkos_options.cmake.

**Comment by masterleinad** [comment]
Let's discuss all this at the Usergroup Meeting.

**Comment by jjwilke** [comment]
We missed discussing this at the meeting.  I'll start by proposing this and get feedback:

1. No -DKokkos variables are allowed to be CACHE variables. If CMake gets re-run, this avoids stale -DKokkos values complicating things
2. Only -DKOKKOS (the cmake preferred) variables are allowed to be CACHE variables with global scope that carry over if you re-run cmake in the same folder
3. Because Tribits... we keep the existing system of converting all -DKokkos variables to -DKOKKOS variables.
4. We must unfortunately keep the logic as it exists checking values because CMake has no way to distinguish a variable that is explicitly set or just cached from a previous configure
5. No `SET(... CACHE...)` calls can happen BEFORE the Kokkos->KOKKOS conversion 

I think the previous system before I messed with it was basically working, except that some `SET(...CACHE...)` calls occurred too early, which made it illegal to use `-DKokkos...` for certain flags.

**Comment by jjwilke** [comment]
@dalg24 @crtrott

**Comment by masterleinad** [comment]
We use `Kokkos_*` everywhere.
