### ISSUE TITLE
Shannon build problems

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#211]
User Help Request via mailing list:

Hello,

I am starting to adopt Kokkos in my library

https://github.com/ibaned/omega_h/tree/kokkos

and am trying to run performance tests
on the Shannon testbed.
So far I've built Kokkos on its own using
the Makefile system, but its unclear how to
do that in a CUDA environment.

I am currently trying the following:

./generate_makefile.bash \
--prefix=$HOME/kokkos-install \
--with-cuda=/home/projects/x86-64-sandybridge-nvidia/cuda/7.5.7 \
--arch=Kepler37 \
--with-cuda-options="enable_lambda,rdc" \
--compiler=$PWD/config/nvcc_wrapper

Many errors related to not using C++11 ensue.
Can someone explain how to compile Kokkos via
Makefile on Shannon ?

Thank you,

Dan Ibanez

**Comment by crtrott** [comment]
Did you load the modules for cuda and gcc etc.?

Which modules are available:
module avail

Load Modules:
module load ....

If yes please post your errors as well as 
which nvcc
which g++

**Comment by ibaned** [comment]
loading the gcc/4.9.0 module alongside the cuda module solved my current problem.
Kokkos is built and installed, I'll open a different issue if something else comes up.

Thanks

**Comment by crtrott** [comment]
Great.
