### ISSUE TITLE
Is it possible to call a Kokkos::parallel_reduce on an array at thread level?

### ISSUE THREAD

**Issue by d-daniel** [kokkos/kokkos#2111]
I have two nested layers of parallelism. The second layer (thread level) needs to perform a reduction with an array of results. As stated in the reference guide, this only works with functors. But is it possible to do this from inside a kernel?

**Comment by crtrott** [comment]
Not currently. How much do you need this?

**Comment by crtrott** [comment]
Also can you show an example of what you try to do?

**Comment by d-daniel** [comment]
This is a simple kernel. It is the MRIQ benchmark from Parboil. I want to sum of the real and imaginary parts of Q.
 
`typedef Kokkos::View<float*> view_type;
 struct computeQ {

  view_type x, y, z, kx, ky, kz, Qr, Qi, phiR, phiI;

  computeQ (const view_type& x_, const view_type& y_, const view_type& z_,
            const view_type& kx_, const view_type& ky_, const view_type& kz_,
            const view_type& Qr_, const view_type& Qi_, 
            const view_type& phiR_, const view_type& phiI_) : 
    x (x_), y (y_), z (z_), kx (kx_), ky (ky_), kz (kz_), 
    Qr (Qr_), Qi (Qi_), phiR (phiR_), phiI (phiI_)  
  {}

  KOKKOS_INLINE_FUNCTION
  void operator() (const member_type &team_member) const {
    
    float QrSum, QiSum;    

    int indexX = team_member.league_rank();
    float xX = x(indexX);
    float yX = y(indexX);
    float zX = z(indexX);

    Kokkos::parallel_reduce(Kokkos::TeamThreadRange(team_member, kx.extent(0)), [&] (const int& indexK, float& update) {
      float expArg = PIx2 * (kx(indexK) *  xX +
                             ky(indexK) *  yX +                      
                             kz(indexK) *  zX);
      float cosArg = cosf(expArg);
      float real = phiR(indexK);
      float imag = phiI(indexK);
      update += (real*real + imag*imag)*cosArg;
    
    }, QrSum);

    Kokkos::parallel_reduce(Kokkos::TeamThreadRange(team_member, kx.extent(0)), [&] (const int& indexK, float& update) {
      float expArg = PIx2 * (kx(indexK) *  xX +
                             ky(indexK) *  yX +                      
                             kz(indexK) *  zX);
      float sinArg = sinf(expArg);
      float real = phiR(indexK);
      float imag = phiI(indexK);
      update += (real*real + imag*imag)*sinArg;
    
    }, QiSum);

    if (team_member.team_rank() == 0) {
      Qr(indexX) += QrSum;
      Qi(indexX) += QiSum;
    }
  }
};`

**Comment by crtrott** [comment]
I would use Kokkos::complex<float> instead and then it would work. Even if we added support for array type reductions, it would still be slower than doing on a struct type such as Kokkos::complex.

**Comment by d-daniel** [comment]
Kokkos::complex did the trick. Thank you.
