### ISSUE TITLE
Missing #include <typeinfo> in Kokkos_ExecPolicy.hpp

### ISSUE THREAD

**Issue by mdmosby** [kokkos/kokkos#2115]
MWE:
```
#include <Kokkos_ExecPolicy.hpp>
```

Using clang-5.0 in the SIERRA environment results in the following error:
```
Kokkos_ExecPolicy.hpp:842:53: error: member access into incomplete type 'const std::type_info'
      default_name = std::string(typeid(FunctorType).name()) + "/" +
                                                    ^
/sierra/sntools/SDK/compilers/gcc/4.9.3-RHEL6/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../include/c++/4.9.3/bits/exception_ptr.h:47:9: note: forward declaration of 'std::type_info'
  class type_info;
        ^
```

**Comment by mhoemmen** [comment]
@mdmosby Are you including `Kokkos_ExecPolicy.hpp` directly, without just including `Kokkos_Core.hpp`?  Kokkos developers recommend just including `Kokkos_Core.hpp`.

**Comment by mhoemmen** [comment]
PR https://github.com/kokkos/kokkos/pull/2116 proposes a fix.

**Comment by mhoemmen** [comment]
@mdmosby Fixed in Kokkos:develop.  Would you like us to cherry-pick the fix into Trilinos or just wait until the next (Kokkos develop-to-master and Trilinos develop-to-master and Sierra/Trilinos) promotion?

**Comment by mdmosby** [comment]
I think we can wait for the next integration. Thanks Mark!
