### ISSUE TITLE
Thread scalable memory pool

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#212]
Thread scalable memory pool for CPU and GPU.
Required by task policy and dynamically resizable view. 
See issue #142 and issue #143

**Comment by ndellingwood** [comment]
More performant version under development.

**Comment by crtrott** [comment]
Can this be closed or is this undoing development?

**Comment by gmackey** [comment]
There's a version in master that works, but it is not as thread scalable as we would like.  I'm currently working on a new version that should be more scalable.

**Comment by gmackey** [comment]
Forgot to say that this needs to remain open for now.

**Comment by hcedwar** [comment]
Current implementation has a race condition with extremely low probability, as exposed by very infrequent failures of the unit test.  A new more performant and flexible implementation is in progress so this current race condition may not need to be addressed.

**Comment by hcedwar** [comment]
New superblock based implementation is ~ 100x improved performance on GPU.
Need "get cycle register pull" on Power 8 for pseudo random number in search for available memory block.
