### ISSUE TITLE
Ryzen, Fiji, etc missing from CMake

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2120]
These do not show up in the KOKKOS_ARCH option list and will not be recognzied

**Comment by jjwilke** [comment]
@crtrott Can someone more familiar on the AMD side confirm that flags are correct - if we need to have them?

**Comment by masterleinad** [comment]
Can anyone confirm that the flags for `Ryzen` and `Fiji` are working correctly?

**Comment by dalg24** [comment]
> @crtrott Can someone more familiar on the AMD side confirm that flags are correct - if we need to have them?

cc @nmhamster

**Comment by jjwilke** [comment]
Ryzen currently does not set any flags (this is consistent with Makefile.kokkos).

For Fiji (and all AMD GPUs) the only flags that get set are linker-only flags (--amdgpu-target=...). These are NOT currently getting in CMake.

**Comment by masterleinad** [comment]
We decided to remove these architectures from the release in #2470. We will add them back in after the release in case we actually provide special flags for them.
