### ISSUE TITLE
Deprecate: ExecSpace::is_initialized

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2124]
In concept Kokkos is either initialized or not.  An execution space instance is implicitly initialized via construction; thus ExecSpace::is_initialized is meaningly.

Deprecating ExecSpace::is_initialized, should be removed or replaced with Kokkos::is_initialized().

referenced in Kokkos 2.9 #2123

**Comment by ndellingwood** [comment]
@jeffmiles63 I think you mentioned this was already done, just a quick message to confirm.

**Comment by jeffmiles63** [comment]
Correct, with the exception of ROCm and sort_array.cpp in the examples, this is effort already complete
