### ISSUE TITLE
Kokkos kernel on multiple GPU

### ISSUE THREAD

**Issue by jacobmerson** [kokkos/kokkos#2128]
Is it possible to spread a Kokkos kernel across multiple GPUs in Kokkos?

i.e. if I am running on a system with multiple GPU's per node and I would like to utilize multiple of these GPUs at a time for a single parallel for loop is it possible?

**Comment by crtrott** [comment]
No it is not. We thought about this on and off, but there is almost no good way to really do this except for a couple of very compute heavy stuff. People tend to do DGEMM, and sure it works for that, but for the vast majority of things you need the locality of data and compute to make it work.

There are more detailed reasons why this is generally not a great idea, if you really want to know we can detail them somewhere at some point ...

Another reason why we never needed this much is that the vast majority of Kokkos users are already using MPI anyway and need to go beyond a single node. At that point the benefit of such a mechanism is really small.
