### ISSUE TITLE
Build only one version of Kokkos library for tests

### ISSUE THREAD

**Issue by gmackey** [kokkos/kokkos#213]
Currently, each of the testing subdirectories in the build directory has a separate copy of the Kokkos library compiled for it.  Instead, there should be a single copy of the Kokkos library that is compiled and used by all of the testing subdirectories.  This will reduce compile time for the tests.

The solution would need to work if doing a 'make build-test' from the top level directory or if doing a make in one of the subdirectories.

**Comment by crtrott** [comment]
Actually I fixed this a while ago in the way I think it should be fixed. We still build extra libraries for the unit and performance tests, but all examples etc. are build against an installed one).  This guarantees that we still test inline builds but cut the total number of library builds from over 30 to 6. Also the library build on the unit and performance tests is only about 10% of the total build time for each of those tests. Total build time would only be reduced by <3% if we were to eliminate those.
