### ISSUE TITLE
Kokkos for utilization of CUDA registers

### ISSUE THREAD

**Issue by wuziyou199217** [kokkos/kokkos#2131]
Hi,

I've recently rewrite a CUDA kernel using Kokkos, but the performance is very bad

i profiled it with nvprof, and found that **Registers/Thread** is only **8**, while this value equals to **64** for CUDA version

I wonder how could this happen?

I have no right to upload source code.

**_Is there anyone who can give me some suggestions, for what may prohibit the use of CUDA registers?_**

Thanks in advance

**Comment by crtrott** [comment]
I don't know of anything which would reduce the register count vis a vis raw CUDA can you post some code? Generally I have not seen any performance degradation vs CUDA code if implemented nin Kokkos either.

**Comment by mhoemmen** [comment]
> I have no right to upload source code.

You are literally using GitHub right now, a site that allows you to maintain a public repository of source code.  Thus, you could either post a link to some code in a branch of your public repository, or comment with a shorter code (in which case, please use Markdown formatting with triple back quotes).

**Comment by stanmoore1** [comment]
@mhoemmen I think this means that their code may not be open source...

**Comment by j8asic** [comment]
I believe this is because Kokkos kernel data are copied to CUDA _constant_ or _shared_ device memory before the kernel execution, therefore the kernel is accessing this memory and avoiding usage of registers for kernel parameters...
