### ISSUE TITLE
Deprecate ExecutionSpace::fence() as static function and make it non-static

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2140]
As part of the revamp to supporting execution space instances we need fences which are specific to the instance. So we deprecate the execution space specific fence functions as static and have them being non-static. 

```c++
// Deprecated
Cuda::fence()
// Now
Cuda().fence()
```

`Kokkos::fence()` is still available as a static function.

As an internal implementation in order to fence all instances of a type we will have
```c++
Cuda::impl_static_fence()
```

Note we may change the function name for that impl thing later, or move it elsewhere.

**Comment by crtrott** [comment]
Note if you have something like 
```c++
traits::execution_space::fence()
```
You need to add typename
```c++
typename traits::execution_space().fence();
```

**Comment by crtrott** [comment]
Sed lines:
```
find * -type f -name "*.hpp" | xargs sed -i 's|::fence()|().fence()|g'
find * -type f -name "*.hpp" | xargs sed -i 's|Kokkos().fence()|Kokkos::fence()|g'
```

Find all the ones needing a `typename` in front:
```
grep -R "::execution_space().fence()"
```

**Comment by mhoemmen** [comment]
How long have Kokkos execution spaces had `fence()` as an instance method?  I'm thinking about how to manage the interface change in Trilinos etc.

**Comment by crtrott** [comment]
they had it as a static function for forever. But since you can call the static function like an instance method you can do the change now.

**Comment by crtrott** [comment]
Nathan will do this on the Kokkos Promotion branch of Trilinos btw.

**Comment by ndellingwood** [comment]
@crtrott 

> Nathan will do this on the Kokkos Promotion branch of Trilinos btw.

Yes I'll work on this, probably in kokkos-kernels first then Trilinos.

**Comment by ndellingwood** [comment]
Packages likely impacted (aside from Kokkos + KokkosKernels of course):
ifpack2, intrepid2, moertel, panzer, phalanx, sacado, shylu fastilu, shylu tacho (mostly deprecated code), stokhos, teuchos, tpetra, trilinoscouplings (examples)

**Comment by ndellingwood** [comment]
Updated in kokkos-kernels and on kokkos-promotion branch of Trilinos.
