### ISSUE TITLE
Unconstrained Kokkos::swap makes anything in standard library that requires swappable not work with Kokkos

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2144]
For instance, `std::unique_ptr<Kokkos::View<double>>` assignment operator calls an unqualified `swap()` (in `libstdc++`, anyway; I can't figure out if this is a bug on their part or not), which finds the unconstrained overload in namespace Kokkos and results in an ambiguity.  There is no reason our version should participate in ADL; we should make it a function object instead.

**Comment by crtrott** [comment]
This is not a current thing in Kokkos right? It is something if we were to add swap?

**Comment by dhollman** [comment]
It was in `master`, but looks like someone removed it in `develop`.  It would be a problem if we ever add an unconstrained `swap` function template, so let's not do that.
