### ISSUE TITLE
Provide mechanism for detecting "in-tree" Kokkos

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2148]
With the new CMake updates, projects still using in-tree Kokkos CMake builds will want to avoid calling `find_package` and also want to avoid using the `target_link_kokkos` function.

We can:
* Require Kokkos to receive a CMake cache variable `-DKOKKOS_IN_TREE` or
* Have Kokkos auto-detect and define an internal variable `KOKKOS_IN_TREE` that other projects can see

**Comment by jjwilke** [comment]
@kyungjoo-kim

**Comment by dalg24** [comment]
@jjwilke Do we still need this?

**Comment by jjwilke** [comment]
Yes. We define a `HAS_PARENT` variable instead that tweaks logic a bit for in-tree.
