### ISSUE TITLE
question about linking kokkos into existing CMake application

### ISSUE THREAD

**Issue by amklinv** [kokkos/kokkos#2159]
@mhoemmen 

I have an application which uses CMake for its build system.  I would like to link in Kokkos, but I am unsure of how to do so.  It does not appear that I can import Kokkos in as a CMake package.  Does anyone have advice for how to add Kokkos to my build system?

**Comment by mhoemmen** [comment]
@jjwilke has been working on Spack integration -- he might know more details of how to do this without bringing in Trilinos' machinery.  I think you can always install Kokkos as a TPL and use the TriBITS-generated files with `FIND_PACKAGE`.

**Comment by crtrott** [comment]
Proper CMake is upcoming including fund package and all the other stuff. We are completely overhauling our build system. You could try @jjwilke branch in the mean time or muddle through with some hints from Jeremiah how this works right now.

**Comment by crtrott** [comment]
The branch: https://github.com/kokkos/kokkos/pull/2104

**Comment by masterleinad** [comment]
You might want to have a look at https://github.com/arborx/ArborX/blob/master/cmake/FindKokkos.cmake.

**Comment by jjwilke** [comment]
I'm pushing for kokkos_generating_settings.cmake to disappear, basically forbidding anyone from creating Kokkos as an imported target.  

There are two branches each with different snapshots.

#2104: Is an initial CMake package export 
#2160: Is close the final version of the new CMake export

Ideally you would install kokkos and then use `FindPackage(Kokkos)` in your project.
You can then use:
`target_link_libraries(target Kokkos::kokkos)`
or
`target_link_kokkos(target)`

We are happen for anyone willing to test #2160 with their project.

**Comment by jjwilke** [comment]
@mhoemmen, @amklinv:

This is demonstrated for Kokkos kernels at:
https://github.com/jjwilke/kokkos-spack

**Comment by AndrewGaspar** [comment]
> We are happen for anyone willing to test #2160 with their project.

I tested it out. I didn't use Spack - just installed directly via CMake.

A behavior I found surprising is that I had to manually add links for `OpenMP::OpenMP_CXX`. I would have expected `Kokkos::kokkos` to add it as a link dependency, and therefore been inherited transitively. Same with Cuda, etc.

Otherwise my code compiled and tests passed.

**Comment by Char-Aznable** [comment]
@jjwilke Is the upcoming cmake change going to support building app in place with Kokkos by fetchcontent so that the user doesn't have to install Kokkos for my app?

**Comment by jjwilke** [comment]
Yes, this will still be allowed.
