### ISSUE TITLE
Install Kokkos config files and target files to correct folders

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2162]
Current installing to `lib/CMake/Kokkos` which accidentally works on a Mac. We should be installing to `lib/cmake/Kokkos`.

I don't see a reason for the 3.0 release keep the old location since we are making a somewhat clean break from old bad practices?

**Comment by jjwilke** [comment]
I just install everything everywhere - both old locations and the CMake "correct" locations

**Comment by mhoemmen** [comment]
Is this done in Kokkos:master?  The usual Kokkos policy is to leave issues open until they merge into master.

**Comment by masterleinad** [comment]
We only install to `lib/cmake/Kokkos`.

**Comment by masterleinad** [comment]
> Is this done in Kokkos:master? The usual Kokkos policy is to leave issues open until they merge into master.

How do you want to track release progress if you can't close related issues?
