### ISSUE TITLE
Cryptic Error When Malloc Fails

### ISSUE THREAD

**Issue by sswan** [kokkos/kokkos#2164]
As a user of a program that uses kokkos, I ran into this error message this morning and had no idea what it was or what it meant:

```
Kokkos::HostSpace::allocate[ INTEL_MM_ALLOC ]( 18446743565090964400 ) FAILED NULL
```

We figured out it was because the requested array was too large. Can you please make this error message more useful? Maybe the name of the array that is trying to be malloc'ed?

**Comment by crtrott** [comment]
We will look into doing this.

**Comment by sswan** [comment]
What is the status of this issue?

**Comment by crtrott** [comment]
This is a request for a better warning.

**Comment by sswan** [comment]
Do we have an ETA for when a fix for this will get in?

**Comment by crtrott** [comment]
We are in the process of prioritizing everything. We should have an idea by next Wednesday.

**Comment by dhollman** [comment]
Hopefully #2409 should address this.  We probably still need Cuda versions of this same kind of thing, so I'm leaving the tag [WIP] on here for now.
