### ISSUE TITLE
Kokkos_LIBRARIES not defined in KokkosConfig.cmake

### ISSUE THREAD

**Issue by tuxfan** [kokkos/kokkos#2166]
It would be nice if the new cmake support defined Kokkos_LIBRARIES. I am working off of the 'cmake-overhaul' branch.

**Comment by jjwilke** [comment]
What's the use case for needing the `Kokkos_LIBRARIES` variable?  I am hoping for a clean break from the old CMake and forcing modern CMake usage downstream.  If there's a valid use case, though, it would be good to understand.

Also - are you wanted it defined automatically after `find_package(Kokkos)` or are you wanting a `generating_settings.cmake` file?

**Comment by crtrott** [comment]
The use-case is an existing largish build system written in pre CMake 3 cmake style. That said it looked like it kinda worked after we fixed the libkokkos.a thingy ...

**Comment by jjwilke** [comment]
I can restore this fairly easily. @tuxfan: Is it just a matter of having code like

````
foreach(lib ${Kokkos_LIBRARIES})
  target_link_libraries(target lib)
endforeach()
```

?

**Comment by jjwilke** [comment]
@tuxfan: Pinging again. How do you need this to work? It it just a matter of you need
````
Kokkos_LIBRARIES = kokkos
````
or 
````
Kokkos_LIBRARY = kokkoscore kokkosalgorithms kokkoscontainers
````
depending on `KOKKOS_SEPARATE_LIBS`
?

**Comment by dalg24** [comment]
Closing for lack of response.
@tuxfan Feel free to re-open if you still need this.
