### ISSUE TITLE
KOKKOS_SEPARATE_LIBS needs to return...

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2167]
CMake does not provide a robust way of combining static subdirectory libraries into a single global library.  As such, my original plan of installing ALL the kokkos libraries as both valid CMake targets and valid libraries is not viable.

The best thing to do is bring back the separate libraries flag. If present, libkokkos does not get installed and the sub-libraries get built as full libraries.

If not present, the sub-libraries get build as object libraries.

We can still mitigate the complexity of these different variations by having the `TARGET_LINK_KOKKOS` function.

**Comment by jjwilke** [comment]
Working (as well as it can) with object libraries

**Comment by dalg24** [comment]
Closing as multiple duplicate are still open.
Also related to #1902
