### ISSUE TITLE
Shorten or partition long running nightly tests

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#217]
These nightly tests consistently time out in the Jenkins queues.  Tests need to be shortened or partitioned into separate tests to reduce the runtime.

KokkosCore_PerfTest_MPI_1 (http://testing.sandia.gov/cdash/testDetails.php?test=33084164&build=2381234)
KokkosContainers_UnitTest_MPI_1 (http://testing.sandia.gov/cdash/testDetails.php?test=33084165&build=2381234)

**Comment by hcedwar** [comment]
Timeouts on Trilinos 12.6.1 release branch on hansel test platform.
Could simply be an issue with hansel.

**Comment by crtrott** [comment]
I tested on my machine with the same settings and the tests finished in about 20s each. On Hansen they time out with 600s. This was the 12.6 Release.

**Comment by hcedwar** [comment]
Has been confirmed that issue is with platform.
