### ISSUE TITLE
Add non-member Kokkos::resize/realloc for DualView

### ISSUE THREAD

**Issue by AndrewGaspar** [kokkos/kokkos#2170]
It would be nice if there were non-member `Kokkos::resize` and `realloc` functions to match `Kokkos::View`.

Slack discussion:

> 
> Andrew Gaspar [10:50 AM]
> Could we get an overload of `Kokkos::resize` for `DualView`?
> 
> 
> crtrott [10:54 AM]
> It doesnt exist?
> 
> Andrew Gaspar [10:54 AM]
> There’s member `resize`
> 
> crtrott [10:54 AM]
> Oh maybe it got a member functiin
> Yeah
> 
> Andrew Gaspar [10:55 AM]
> but it would be nice for a couple reasons if it was non-member `resize` like `View`:
> 1) If you change a `View` to a `DualView`, you don’t have to change any resizes
> 2) Visually consistent in the code
> 
> crtrott [10:56 AM]
> Agreed
> 
> Andrew Gaspar [10:56 AM]
> I can file an issue
> 
> crtrott [10:56 AM]
> Jup do that
> 
> Andrew Gaspar [10:57 AM]
> I can see about providing the change myself
> 
> crtrott [10:57 AM]
> Also realloc

**Comment by dsunder** [comment]
There are kokkos_malloc, kokkos_free, and kokkos_realloc available as free functions in the Kokkos namespace, though they work on raw allocations and not Kokkos data structures.  Kokkos::resize is possible for View, DualView, and UnorderedMap, not sure how realloc would be different from resize (unless realloc does not copy the data).

Cheers,

--Dan S

**Comment by stanmoore1** [comment]
Yes resize preserves the existing data of the view while realloc does not.

**Comment by dhollman** [comment]
@AndrewGaspar does PR #2408 address this?

**Comment by AndrewGaspar** [comment]
Looks right.
