### ISSUE TITLE
Should environment variables be translated into CMake cache variables?

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2174]
Some users or tests are expecting environment variables to translate into particular configuration features. This does not work in the CMake.

Question for the 3.0 CMake: Should certain environment variables be recognized by CMake and translated into cache variables?

**Comment by masterleinad** [comment]
Can you be more specific? What kind of environment variables are people expecting to be reflected in `CMake` variables?

**Comment by jjwilke** [comment]
KOKKOS_DEVICES, KOKKOS_ARCH, e.g.

**Comment by crtrott** [comment]
Does this work with Trilinos right now> Or is this just the GNU Makefiles? I am ok if it doesn't work. Even for GNU Makefiles I override arguments on the command line not via environment variables.

**Comment by masterleinad** [comment]
Is there still a demand for addressing this?

**Comment by crtrott** [comment]
Answer: No
