### ISSUE TITLE
-DKOKKOS_DEVICES for new CMake

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2175]
Rather than requiring `-DKOKKOS_ENABLE_X` allow multiple devices to be specified as a list of devices like `KOKKOS_ARCH`

**Comment by dalg24** [comment]
On a related note, we need to make sure downstream code that do `find_package(Kokkos)` will be able to deduce the list of devices that where enabled at the time Kokkos was built.
c.f. https://github.com/arborx/ArborX/pull/73#discussion_r290908516

**Comment by jjwilke** [comment]
No longer needed. Less verbose input is not worth extra cmake complexity and cache inconsistencies.
