### ISSUE TITLE
kokkos parallel for with openmp

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#2178]
Can we create a range policy that can be exactly mapped to something like ``pragma omp for schedule(dynamic,chunk)`` ? Kokkos dynamic scheduling is not exactly same as openmp dynamic scheduling. Also, a user does not have a control over the chunksize which should be a runtime parameter. For some situations, I found that omp dynamic schedule is better but I do not want to hard code it.

**Comment by dhollman** [comment]
We've talked about this.  This will probably come shortly after the update of the OpenMP backend that uses actual OpenMP constructs directly.  Right now, we don't even use `pragma omp for`, so that wouldn't be possible

**Comment by kyungjoo-kim** [comment]
Thanks. Would you mind if I ask to let me know roughly when this feature could be included ?

**Comment by dhollman** [comment]
Pinging @dsunder for that, but also the priority for this can be moved up or down based on interest.

**Comment by kyungjoo-kim** [comment]
Okay. I first my thumbs up.

**Comment by nmhamster** [comment]
I'd like to see the true OpenMP constructs get used. For one, this may give better performance as a number of compilers seem to understand how to handle these constructs in optimization phases.

**Comment by crtrott** [comment]
‘RangePolicy<Schedule<Dynamic>>(0,N).set(ChunkSize(K))’ should do what you want

**Comment by ibaned** [comment]
Despite not giving users guarantees on direct mapping to some backend construct, we do think in the case of OpenMP that it is the right direction for our implementation to map more directly to their constructs, for the performance reasons @nmhamster gave and reasons of code quality.

**Comment by PhilMiller** [comment]
#4369 is addressing much of the direct mapping to underlying OpenMP constructors. Besides that, as said, there's no much to be done here, so closing.
