### ISSUE TITLE
hwloc dependence on libnuma

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2186]
hwloc, depending on how built, depends on libnuma.  At the very least, we need another find module for libnuma to enable this.  I'm not sure on the best course for auto-detecting hwloc dependence on libnuma and forcing an enable libnuma.

Related to #2098

**Comment by jjwilke** [comment]
This appears to be working downstream in #2167

**Comment by dalg24** [comment]
@jjwilke What is the status of this?

**Comment by jjwilke** [comment]
Done. We have a `FindLIBNUMA.cmake` that can be activated.
