### ISSUE TITLE
Set Kokkos_DEVICES and Kokkos_ARCH variables in exported CMake configuration

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2193]
On a related note, we need to make sure downstream code that do `find_package(Kokkos)` will be able to deduce the list of devices that where enabled at the time Kokkos was built.
c.f. https://github.com/arborx/ArborX/pull/73#discussion_r290908516

_Originally posted by @dalg24 in https://github.com/kokkos/kokkos/issues/2175#issuecomment-501409585_

**Comment by dalg24** [comment]
Current version of #2104 would break Cabana and ArborX.  Both projects have some logic to instantiate code or enable examples/tests that rely on knowing at configuration time what devices were enabled at the time Kokkos was built.
See:
https://github.com/ECP-copa/Cabana/blob/b27a54c8c2df2f8b46d93f15d3e6992ee05041d3/CMakeLists.txt#L47-L49
and
https://github.com/arborx/ArborX/blob/857bcb6e06a984ca2363174ed7c989cdfb90f0e8/cmake/FindKokkos.cmake#L81-L82

CC: @junghans

**Comment by dalg24** [comment]
Adding a reference to the [helper function](https://dalg24.github.io/kokkos/#/12/1) I had proposed at the user meeting (see also #2064) which let the user code assert that a backend has been enabled.

https://github.com/kokkos/kokkos/blob/839229df4f6eaff3b8a8f3bf6e8d933234a48a82/core/cmake/kokkos-config.cmake.in#L60-L92

**Comment by junghans** [comment]
I agree, exporting devices would be very useful.

**Comment by ipdemes** [comment]
We need this for FLeCSI too

**Comment by junghans** [comment]
@crtrott

**Comment by junghans** [comment]
Another option would be to set the these as properties in `kokkos-config.cmake`, e.g.:
```
set_target_properties(Kokkos::kokkos PROPERTIES ARCH "@KOKKOS_ARCH@")
```
then we could process them in Cabana and FleCSI with:
```
get_target_property(KOKKOS_ARCH Kokkos::kokkos ARCH)
```
and everything is transparently attached to the `Kokkos::kokkos` target.

**Comment by ipdemes** [comment]
@crtrott : any update on this?

**Comment by dalg24** [comment]
@jjwilke has added `Kokkos_ARCH` and `Kokkos_DEVICES` in the latest revision of #2104.
The plan is to address the current issue before we merge into `develop`.

**Comment by ipdemes** [comment]
@dalg24 : Great! Thank you
