### ISSUE TITLE
Kokkos::Impl::CudaTraits::SharedMemoryCapacity went away; equivalent functionality?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#2203]
I know it's in the `Impl` namespace so this is not a bug, but I'm wondering how to get equivalent functionality.

**Comment by ndellingwood** [comment]
@mhoemmen you can try something like this:

Change
`auto shcap = Kokkos::Impl::CudaTraits::SharedMemoryCapacity;`

to

`auto shcap = Kokkos::Cuda().impl_internal_space_instance()->m_maxShmemPerBlock;`

**Comment by ndellingwood** [comment]
@mhoemmen I had to make similar changes in Stokhos during the 2.9 promotion, see e.g. `packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CooProductTensor.hpp` line 282

**Comment by mhoemmen** [comment]
Thanks @ndellingwood !  Is there a non-"impl" way to get this information or do I just have to close my eyes and reach into the innards of Kokkos?

**Comment by ndellingwood** [comment]
@mhoemmen it's not exposed through any public API in Kokkos, only way is with innards-digging.

**Comment by mhoemmen** [comment]
Thanks @ndellingwood !

**Comment by crtrott** [comment]
This is not actually correct. It is part of the TeamPolicy concept: 

```c++
TeamPolicy<> p(N,AUTO);
int max_l0_scratch = p.scratch_size_max(0);
int max_l1_scratch = p.scratch_size_max(1);
```

**Comment by mhoemmen** [comment]
Thanks @crtrott and @ndellingwood !
