### ISSUE TITLE
Warnings with Cuda 10.1

### ISSUE THREAD

**Issue by berselius** [kokkos/kokkos#2206]
I am building an application off of a cuda-enabled trilinos and getting a zillion kokkos-related warnings similar to

```/projects/draco/vendors/trilinos-12.14.1/power9-gcc-7.3.0-openmpi-3.1.3-cuda-10.1-b/include/Kokkos_MemoryPool.hpp(314): warning: __device__ annotation is ignored on a function("MemoryPool") that is explicitly defaulted on its first declaration```

I mentioned this in the kokkos slack and Christian suggested this is a Cuda 10.1 thing. 

Looks like someone was seeing similar warnings in #1985

**Comment by crtrott** [comment]
OK it is not fixed: we need to use the "DEFAULTED" macro.

**Comment by berselius** [comment]
After some discussion on slack, it looks like the issue was that my app does not pick up the trilinos CXX flags

We don't want all of them anyway, so I added the following to my build system.

```if (ENABLE_KOKKOS)
   string(APPEND CMAKE_CXX_FLAGS "-Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-lambda")
endif()```

The warning suppression flag takes care of this.

**Comment by ibaned** [comment]
@crtrott I think the latest CUDA versions (10.1) do generate the right device code for defaulted member functions, so I think when CUDA is new enough we should just not mark defaulted functions with `__host__ __device__`. Then we can also omit the diagnostic suppression flag.

**Comment by jeffmiles63** [comment]
@ibaned @crtrott @berselius The current version (develop - Release 3.0) of Makefile.kokkos and cmake/kokkos_arch.cmake automatically add the `--diag_suppress=esa_on_defaulted_function_ignored` if the compiler version is greater than 9.0
