### ISSUE TITLE
Slack inaccessible?

### ISSUE THREAD

**Issue by ian-bertolacci** [kokkos/kokkos#2208]
The readme states that we can use [kokkosteam.slack.com](https://kokkosteam.slack.com) for Kokkos questions, but that it looks like an invite only slack (unless your email is under some specific DOE/military/industry domains).

Can you open that up to the public?
Slack is a lot better than filing issues if we have questions.

**Comment by crtrott** [comment]
Hi, we can add new domains, but we cannot open it to the public for various reasons. One of the reasons is that Slack doesn't actually give you that option - and while I read that there is some backdoor way to do it anyway that is against the user agreement. What we can do is adding your university domain.

**Comment by ian-bertolacci** [comment]
Sure. The university of arizona uses the @email.arizona.edu domain

**Comment by crtrott** [comment]
email.arizona.edu was added as a pre-approved domain for joining.
