### ISSUE TITLE
DualView use and documentation?

### ISSUE THREAD

**Issue by ian-bertolacci** [kokkos/kokkos#2209]
I'm having trouble understating the purpose of DualView.
It feels like the same is accomplished using a View on a device memory space, and then using a HostMirror as necessary on the host end.
Is the purpose of DualView to make a more explicit interface for synchronizing a view between two memory spaces? or is there something more?

Also, is there any documentation or examples beyond [this DualView tutorial](https://github.com/kokkos/kokkos-tutorials/tree/master/Intro-Full/Exercises/dualview/Solution)?
There is not yet an entry in the wiki about it or its API, and it does not show up in the Kokkos Programming Guide PDF.

**Comment by pguthrey** [comment]
I have understood DualViews as an abstraction that handles mirroring for you. 
As far as I know, if your host and device views are in the same memory space then Kokkos ignores deep copy operations because they would be a waste of time. 

We are experimenting with DualViews in our own codes. They seem very convenient.

**Comment by ian-bertolacci** [comment]
I see. Unfortunately, we were hoping that DualViews would allow access to arrays without adding synchronization or unwrapping steps to our code.

**Comment by pguthrey** [comment]
I know that you must explicitly tell the dualviews when to synchronize, but they do not synchronize unless the variables you are synchronizing are marked as modified [again by you]. 

Btw, you can't access device views from the host.  They must be copied.

**Comment by mhoemmen** [comment]
@ian-bertolacci wrote:
> It feels like the same is accomplished using a View on a device memory space, and then using a HostMirror as necessary on the host end.

That's correct -- you could just create a host mirror and manage copying back and forth yourself.  DualView does exactly that, and also maintains flags that avoid unnecessary copying.  However, you, the user, must maintain those flags by calling `modify_*` as needed.
