### ISSUE TITLE
Allow View<...,CudaSpace> = View<...,CudaUVMSpace>

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#221]
A View type in the CudaUVMSpace can be safely assigned to a View type with the CudaSpace.
Allowing this assignment can allow libraries written for CudaSpace Views to accept both CudaSpace and CudaUVMSpace Views.

**Comment by mhoemmen** [comment]
Could also be useful to reduce the number of KokkosKernels instantiations.

**Comment by crtrott** [comment]
That is the original use case driver ;-)

**Comment by hcedwar** [comment]
redundant with issue #290
