### ISSUE TITLE
Kokkos::View<> under CUDA_ENABLE

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#2211]
When KOKKOS_CUDA_ENABLE (UVM is off) is on, is it safe to assume Kokkos::View<double **>  are Kokkos::View<double **, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>> > equivalent?  

Recently, I changed my code to use Kokkos::View<double **> for portability, but I found that I am getting different results from the same computation.

**Comment by crtrott** [comment]
Yeah it is.
