### ISSUE TITLE
Does Kokkos currently (or soon will) support AMD Radeon Pro Vegas?

### ISSUE THREAD

**Issue by pguthrey** [kokkos/kokkos#2212]
Is there any plan to make the following work (or do these currently work) with Kokkos?
I did not yet see options for these GPUs in the documentation

Radeon Pro 560X with 4GB of GDDR5 memory
Radeon Pro Vega 16 with 4GB of HBM2 memory
Radeon Pro Vega 20 with 4GB of HBM2 memory

The reason I ask is that these are the GPU options for the 2019 Macbook pros.

Further, can I use Kokkos to run my code on the GPU in a MacbookPro? 

_Originally posted by @pguthrey in https://github.com/kokkos/kokkos/issues/1874#issuecomment-511928047_

**Comment by Rombur** [comment]
We are working to support AMD GPUs but a complete port is still months away.

**Comment by crtrott** [comment]
We had a reasonably complete thing, but AMD deprecated the programming model (ROCm HCC compiler based on C++ AMP). We are now working on the HIP backend.

**Comment by jeffhammond** [comment]
Is there actually a hope that HIP/ROCm works on Mac OSX?  https://github.com/RadeonOpenCompute/ROCm/issues/262 did not make me optimistic.
