### ISSUE TITLE
illegal instruction core dumped

### ISSUE THREAD

**Issue by huilinye** [kokkos/kokkos#2213]
Dear all,

I tried to reproduce the same results in the examples. I found if I compiled using 
KOKKOS_PATH/generate_makefile.bash
make build-test
make test
, everything goes well for the exe file in build/example folder. While when I tried to compile the source code using the makefile provided by you guys inside the folder ${HOME}/example/tutorial/01....., the files can be compiled, but if I run exe file, following results prints on the screen
" illegal instruction, core dumped". 
So, how can I generate general makefile like the KOKKOS_PATH/generate_makefile.bash.

**Comment by crtrott** [comment]
Most likely you compiled for the wrong architecture. By default I believe it compiles for AVX or AVX2. You most likely need to change KOKKOS_ARCH to something which matches your architecture. Or set it to "none" and use whatever your compiler natively does.
