### ISSUE TITLE
DualView with CudaHostPinned memory_space

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2217]
Is there any way to get a `Kokkos::DualView` with `CudaHostPinnedSpace` memory_space for the host copy? I.e. to improve data transfer bandwidth.

**Comment by mhoemmen** [comment]
Yes; the following works fine:
```c++
using device_type = Kokkos::Device<Kokkos::Cuda, Kokkos::CudaHostPinnedSpace>;
Kokkos::DualView<double*, device_type> dv;
```

**Comment by stanmoore1** [comment]
@mhoemmen thanks I'll give that a try
