### ISSUE TITLE
How to get unmanaged subview without using view constructor

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2218]
Is there any way I can get an *unmanaged* subview using the `auto` keyword like this:

```
auto A_sub = subview (A, make_pair (2, 4), make_pair (3, 7));
```

without using the view constructor (which requires knowing the subview type)?

**Comment by dhollman** [comment]
I don't think there is currently, but the syntax we're exploring for this would look something like:

```c++
auto A_unmanaged = Kokkos::require(A, Kokkos::Properties::MemoryTraits.Unmanaged);
auto A_sub = subview (A_unmanaged, make_pair (2, 4), make_pair (3, 7));
```

Would that be an acceptable approach to this problem?

**Comment by stanmoore1** [comment]
Yes, that would be great!

**Comment by dhollman** [comment]
For now, you should always be able to do something cheesy like (untested, but should work):

```c++
template <class> struct my_add_unmanaged;
template <unsigned Val>
struct my_add_unmanaged<Kokkos::MemoryTraits<Val>> {
  using type = Kokkos::MemoryTraits<Val | Kokkos::MemoryTraitsFlags::Unmanaged>;
};
template <class ViewLike>
struct my_make_unmanaged {
  using type = Kokkos::View<
    typename ViewLike::data_type,
    typename ViewLike::array_layout,
    typename ViewLike::device_type,
    typename my_add_unmanaged<typename ViewLike::memory_traits>::type
  >;
};
/* ... */
auto A_unmanaged = typename my_make_unmanaged<decltype(A)>::type{A};
auto A_sub = subview (A_unmanaged, make_pair (2, 4), make_pair (3, 7));
```

**Comment by stanmoore1** [comment]
If I take a subview of an unmanaged view, is the subview also unmanaged by default?

**Comment by dhollman** [comment]
Yes.  Especially for something that starts life as an unmanaged `View`, there's no real way for us to reference count the thing or anything derived from it, so once it's unmanaged, it's always unmanaged.

**Comment by stanmoore1** [comment]
OK that is helpful, thanks.
