### ISSUE TITLE
Is there any way to figure out scrtach space allocation failure?

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#2219]
I am trying to create scratch space in GPU main memory (Option "1") for each team.  It appears that the allocation fails when requesting a large size.  The problem is Kokkos::View<*,scratch> does not give any notification if the allocation is successful.  Should I use extent() method to check the size?

**Comment by stanmoore1** [comment]
Try turning on `KOKKOS_DEBUG = yes`, it gives more output then.

**Comment by keitat** [comment]
-DKOKKOS_ENABLE_DEBUG=ON in CMAKE script?

**Comment by stanmoore1** [comment]
Yes, see https://github.com/kokkos/kokkos/blob/master/cmake/kokkos_options.cmake#L284
