### ISSUE TITLE
Deep copy with type cast

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2224]
I need a way to deep copy between an FP64 (double-precision) LayoutRight view and a FP32 (single-precision) LayoutLeft view. I can use `Kokkos::deep_copy` to convert between `LayoutRight` and `LayoutLeft`, but I believe there is a static assert that prevents deep copying between views of different type, even when the implicit conversion can be done with `static_cast`. Can this restriction be relaxed, or a new type of deep_copy that allows this (i.e. `deep_cast`) be added?

**Comment by stanmoore1** [comment]
I need this for LAMMPS to allow FP32 LayoutLeft on the device while still maintaining interoperability with FP64 LayoutRight legacy (non-Kokkos) data-structures on the host.

**Comment by mhoemmen** [comment]
@stanmoore1 I wrote [something like this in Tpetra](https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp), called `copyConvert`.  It only works for rank-one Views, but you could easily adapt it for general Views.

**Comment by stanmoore1** [comment]
Thanks @mhoemmen, but the machinery is already in Kokkos, it just needs to allow a static_cast. I'd like to keep code that belongs in Kokkos out of LAMMPS if possible.

**Comment by stanmoore1** [comment]
i.e. I don't want to re-implement `Kokkos::deep_copy` in LAMMPS just for the cast.

**Comment by mhoemmen** [comment]
Last time `Kokkos::deep_copy` got refactored it increased SPARC's build time a lot.  We'll need to be careful about how we do this.

**Comment by stanmoore1** [comment]
@mhoemmen I don't think this will require much of a refactor and can be done in a way that won't affect performance.

**Comment by stanmoore1** [comment]
Can the Kokkos core developers @crtrott @ibaned @dsunder etc. comment on the feasibility of this request?

**Comment by dhollman** [comment]
`deep_copy` between different layouts has a number of known issues anyway, particularly when it comes to construction of non-trivially-copyable types (the behavior is, incorrectly, different depending on whether the layout changes or not, which is definitely a bug).  When we fix this problem, we could also probably relax the restriction of same type to just be convertible type, which can effectively follow the same code pathway (well, through templates, anyway) that the non-trivially-copyable types follow.

**Comment by crtrott** [comment]
Ok turns out this always worked ...

```c++
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = (argc>1) ? atoi(argv[1]) : 10000;
     int M = (argc>2) ? atoi(argv[2]) : 10;
     int R = (argc>3) ? atoi(argv[3]) : 10;

     Kokkos::View<double**> a("A",N,M);
     Kokkos::View<float**> b("B",N,M);

     Kokkos::parallel_for(N,KOKKOS_LAMBDA(const int i) {
       for(int j=0;j<b.extent(1);j++) b(i,j) = (i!=5 || j!=3)? i*100+j:0;
     });

     Kokkos::deep_copy(a,b);
     Kokkos::parallel_for(N,KOKKOS_LAMBDA(const int i) {
       for(int j=0;j<b.extent(1);j++)
         if(a(i,j) != double(float(i*100+j))) printf("Error: %i %i\n",i,j);
     });

  }
  Kokkos::finalize();
}
```

Output (note I explicitly don't assign b(5,3)) so I expect exactly one error:
```
./test.cuda 
Error: 5 3
```

I tested all the way back to Kokkos 2.01.00 , had to go to a Kepler machine for that ...

**Comment by crtrott** [comment]
Oh what you can't do is conversion and copying from host to device at the same time. But thats the same with layout change. We won't support it since we would need to internally allocate an extra buffer for that. So you need to do the extra buffer and then two deep copies. (host to buffer, buffer to device). The buffer can be on host or device, if its on the host it needs to have the same scalar type/layout as the device view if its on the device it needs to be compatible with the host view.

**Comment by mhoemmen** [comment]
Tpetra provides a special case of this; see `Trilinos/packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp`.  As Christian said, you can't convert and copy between different memory spaces without an intermediate step.

**Comment by stanmoore1** [comment]
Sweet! Thanks @crtrott
