### ISSUE TITLE
Kokkos::HBWSpace appears to have a namespace mismatch

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2225]
Hey folks,

I'm working on something with @dsunder in which I'm playing with the HBW memory space. In Kokkos_HBWSpace.hpp, the DeepCopy templates refer to

`Experimental::HBWSpace`

But the DeepCopy templates are in `Kokkos::Impl`, so it's looking for HBWSpace in `Kokkos::Impl::Experimental::HBWSpace`, when it's actually in `Kokkos::Experimental::HBWSpace`.

Am I misconfiguring something, or is this an actual defect? If it's an actual defect, do we want to move "HBWSpace" to "Impl::Experimental" or do we want to just fully specify that it's in `Kokkos::Experimental::HBWSpace`?

**Comment by dsunder** [comment]
Hi David,

For a class Foo in Kokkos::Experimental you need to specify that it is Kokkos::Experimental::Foo whenever you want specialize a class in Kokkos::Impl.

Cheers,

—Dan S

**Comment by DavidPoliakoff** [comment]
Cool, any objection to me putting in a PR that fixes this in develop?

**Comment by crtrott** [comment]
Sure go ahead.
