### ISSUE TITLE
Meet with Kitware staff about suggested changes to Kokkos for selecting GPUs to run on for ctest?

### ISSUE THREAD

**Issue by bartlettroscoe** [kokkos/kokkos#2227]
Hello Kokkos team (@crtrott, @ibaned, @jjellio, @dsunder ...),

Can a member of the Kokkos team knowledgeable with running Kokkos on GPUs attend a meeting with myself and @KyleFromKitware to discuss the proposed changes to Kokkos for selecting GPUs in the WIP PR https://github.com/trilinos/Trilinos/pull/5598?  Can someone volunteer to try to meet this week and then we can set up a meeting over email?

Please let me know.

**Comment by jjellio** [comment]
I'd like to be a part of this discussion. (the more general problem of testing on batch systems is important to me)

**Comment by dhollman** [comment]
I can be there if you have telecon details.  Email me :-)

**Comment by ibaned** [comment]
I can also be there!

**Comment by bartlettroscoe** [comment]
We just met at the Kitware developers meeting.  We can close this.

**Comment by nmhamster** [comment]
@bartlettroscoe - might you be able to provide some details to the interested parties on this list so we can understand what was discussed? Thanks!

**Comment by bartlettroscoe** [comment]
@nmhamster asked:

> might you be able to provide some details to the interested parties on this list so we can understand what was discussed? Thanks!

Just debated if Kokkos should contain logic that is CTest-specific, if a command-line arg should be used in order to look for CTest env vars or if some other env var should be used.  I think the Kokkos team is going to discuss this among themselves for how they want to deal with this.

Since Kokkos already has some knowledge of what MPI rank it is running on, it would be pretty convenient if CTest and Kokkos could just shake hands using env vars and not require any changes to TriBITS or Trilinos to make this work.  Then every project that uses Kokkos and CTest could take advantage of this, not just projects that use TriBITS.

**Comment by mhoemmen** [comment]
I find it a bit silly to use a command-line argument to tell Kokkos merely that it's using GPUs (nothing more specific), when Kokkos perfectly well knows that it's using GPUs.  Perhaps I don't quite understand what's going on, though.

**Comment by KyleFromKitware** [comment]
> I find it a bit silly to use a command-line argument to tell Kokkos merely that it's using GPUs (nothing more specific), when Kokkos perfectly well knows that it's using GPUs.

The command line argument doesn't mean "Kokkos is using GPUs", but "Kokkos is using the GPUs specified by CTest and should follow the CTest allocation protocol."

**Comment by bartlettroscoe** [comment]
> The command line argument doesn't mean "Kokkos is using GPUs", but "Kokkos is using the GPUs specified by CTest and should follow the CTest allocation protocol."

Then it should say that explicitly:

```
--kokkos-use-ctest-gpu-allocation-protocol=1
```

No reason to be shy about the length of the command-line argument.  Regular users are not typing this stuff in.

**Comment by bartlettroscoe** [comment]
Reopening issue because we need another meeting on this.  I sent out the following email but no responses yet.

----

From: Bartlett, Roscoe A 
Sent: Thursday, August 01, 2019 10:52 AM
To: Elliott, James John <jjellio@sandia.gov>; Ibanez, Daniel Alejandro <daibane@sandia.gov>; Hollman, David S <dshollm@sandia.gov>
Cc: Kyle Edwards <kyle.edwards@kitware.com>
Subject: RE: CTest+Kokkos changes

Hello guys,

Looks like we still need some more information about how kernels from multiple processes/rank run on a GPU in order to adjust what is in:

https://github.com/trilinos/Trilinos/pull/5598

to do fuller experimentation on al of Trilinos.

If multiple MPI ranks are trying to run kernels on the same GPU device, do they all run at once and the GPU or does the GPU run only one at a time (i.e. giving each kernel all of the threads)? Also, you can’t control how many threads that a kernel uses to run on a GPU, right?

What about memory on the GPU? Does the memory from each MPI rank’s kernel all exist at the same time on the GPU even when a kernel is not running? Does memory for a given MPI process/rank persist on the GPU between parallel_for() runs?

Also, it seems that some GPUs limit the number of Kernels that can be run at one time but are the other constraints (I heard the number 20 from Robert M. at Kitware). Is this true?

We need to understand how this works in order for ctest to implement a good strategy for deciding how to spread out and limit the work running on the GPUs by the various tests and not have tests crashing due to running out of memory or breaking other constraints.

Can we set up a meeting with Kyle to discuss this? In general, what days/times are good or bad for setting up another meeting? Should we just use doodle.com to schedule a meeting?

Please let us know,

-Ross

**Comment by mhoemmen** [comment]
> If multiple MPI ranks are trying to run kernels on the same GPU device, do they all run at once and the GPU or does the GPU run only one at a time (i.e. giving each kernel all of the threads)?

It depends on whether an MPS server is running.  The MPS server lets multiple (MPI or OS) processes multiplex a single GPU concurrently.  If an MPS server is not running, then the GPU will serialize the MPI processes' requests to run kernels.

**Comment by mhoemmen** [comment]
> Also, you can’t control how many threads that a kernel uses to run on a GPU, right?

That's not really a thing.  You can control the number of blocks and the number of threads per block, but controlling the number of blocks really does not mean something analogous to `OMP_NUM_THREADS`.

**Comment by bartlettroscoe** [comment]
> It depends on whether an MPS server is running.

Is an MPS server running on production ATS-2 machines like Sierra and Summit?

**Comment by mhoemmen** [comment]
@nmhamster would know -- I haven't tried multiplexing GPUs there.

**Comment by nmhamster** [comment]
@mhoemmen / @bartlettroscoe - my understanding is that, yes, MPS is supported in the environment.

**Comment by bartlettroscoe** [comment]
@nmhamster said:

> my understanding is that, yes, MPS is supported in the environment.

Is it installed on 'ride', 'waterman' or 'vortex' where we can experiment with this?

**Comment by jjellio** [comment]
It seems like Kitware is working to implement a resource manager.  LSF's (jsrun) tool may be a model to learn from.  They define a 'resource set' (**rs**), and an rs has attached to it some number of Cores and Devices.  You then specify how many 'tasks' (processes) can share a rs.

I am not saying LSF is the holy land, it is buggy and rather a pain to use at times.  But the problem of scheduling onto HPC resources is non-trivial, and Kitware is trying to fill in the blank for the case where you just have 'mpirun'.  I suspect SLURM and ALPS will start showing off their approaches soon enough (NERSC's Perlmutter is in early access).

I would just create pools of 'cores and devices' that should run using them, then give a 'task' one core, and 1 device that matches that core.  Assuming the node has around 16-20 cores per socket, then you would get about 16-20 concurrent MPI tasks per socket. The cards *will* serialize the utilization. Data you lack, is an expected runtime and estimated max memory usage. 

With the latter data points, you can schedule MPI jobs onto core/gpu pairs  until the memory utilization would be exhausted.

Another attribute that is forward looking, is tests that want *multiple* GPUs. That isn't a use case I've seen, but the machine learning crowd generally doesn't worry with MPI, and can run single monolithic processes that use all GPUs within a single process.  If a test wanted 2 GPUs, you would want to grab two in the same 'pool' of cores, so they share the same memory backing.


As for MPS on Sierra. Lassen does not run MPS.
Moreover, most of our platforms have avoided it, because it requires root to start/stop (I think waterman admins let me play with it a while back)

**Comment by bartlettroscoe** [comment]
Kitware is trying hard **NOT** to implement a resource manager given the existence of SLURM and LSF.  So for host utilization, they want us to just rely on those systems (or the OS to move things around and spread out).   CTest just needs to know how many tests it can run at the same time as to not overload the machine.  (But I think we can do that with OpenMP given what we currently know.) 
 The question is if these systems can effectively spread out and manage work on a set of GPUs.  It sounds like we are not too sure about that.

I guess on people's own workstations, they will generally just have a single GPU so GPU allocation is not a problem (and therefore your tests will all use the GPU in a serial fashion and will not parallellize  really).

**Comment by KyleFromKitware** [comment]
@bartlettroscoe 

> CTest just needs to know how many tests it can run at the same time as to not overload the machine.

CTest is also keeping track of which test has which GPU. To do this, it assigns a GPU to each test (more accurately, each process of each test.)

**Comment by bartlettroscoe** [comment]
> CTest is also keeping track of which test has which GPU. To do this, it assigns a GPU to each test (more accurately, each process of each test.)

@KyleFromKitware, right that is true for GPUs but not for cores on the host node.  On the host using OpenMP, for example, CTest has no idea how processes and threads are assigned to each MPI rank for each test it runs.  CTest just knows of an abstract "Processor" (which we will define as a core that can run a thread) and how many "Processors" each test consumes when it runs.  Then ctest just makes sure that it does not run any more tests than there are processors on the machine.  Brad argued that other systems (or just the OS) can do a good enough job of spreading out assigning MPI ranks and threads to sockets and cores on a host node.

**Comment by KyleFromKitware** [comment]
> right that is true for GPUs but not for cores on the host node.

Right, I see what you're saying. Yes, your understanding is correct.

> Brad argued that other systems (or just the OS) can do a good enough job of spreading out assigning MPI ranks and threads to sockets and cores on a host node.

Yes, and I agree with this conclusion.

**Comment by stanmoore1** [comment]
MPS is available on Summit, you simply add the `-gpumps` flag to the `bsub` line. MPS is also available on Sierra but it is a few more steps to enable.

**Comment by jjellio** [comment]
@stanmoore1 I assume this reboots the nodes?  I know the default Lassen node does not MPS for you.

**Comment by stanmoore1** [comment]
Not sure about rebooting the nodes but you can start and kill the MPS server manually by using `nvidia-cuda-mps-control`.

**Comment by jjellio** [comment]
The -gpumps flag does not seem to work on Lassen (SON Sierra test bed)
The last I tried MPS on SNL machines, it required root to start/stop.

**Comment by jjellio** [comment]
So, I just messed with Lassen more - you can manually start/stop the server as regular user.
So MPS is available on the Sierra testbeds most likely (Vortex, Anzel, Sierra)

**Comment by stanmoore1** [comment]
`-gpumps` is only for Summit, not Sierra.

**Comment by bartlettroscoe** [comment]
@jjellio said:

> So, I just messed with Lassen more - you can manually start/stop the server as regular user.
So MPS is available on the Sierra testbeds most likely (Vortex, Anzel, Sierra)

Can you provide details so we can reproduce?  Any chance that using the MPS server will help improve GPU utilization without any changes to CTest, TriBITS or Kokkos?  What is needed on our end to try this on 'ride', 'waterman', etc.?

**Comment by bartlettroscoe** [comment]
I just tried this on 'waterman':

```
$ nvidia-cuda-mps-control
Cannot find MPS control daemon process
```

**Comment by nmhamster** [comment]
Try Vortex. This isn’t something we have enabled on the test beds generally.

**Comment by bartlettroscoe** [comment]
On 'vortex':

```
$ nvidia-cuda-mps-control
Cannot find MPS control daemon process
```

**Comment by bartlettroscoe** [comment]
After reading manpage on 'vortex':

```
$ nvidia-cuda-mps-control -d
Warning: Failed writing log files to directory [/var/log/nvidia-mps]. No logs will be available.
```
