### ISSUE TITLE
README.md with updated CMake documentation

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2234]
Complete with logo and license fanciness?

**Comment by masterleinad** [comment]
@jjwilke Is there anything else you want to address here?

**Comment by jjwilke** [comment]
I believe this is ready to go. It would be helpful if someone else also did a proofread pass just in case my brain is overlooking any obvious mistakes.

**Comment by jjwilke** [comment]
Merged a while ago. This should be pretty clean now with even more details in the BUILD.md  and Spack.md.
