### ISSUE TITLE
Error: Multiple definition of [cuda stuff] when using --relocatable-device-code

### ISSUE THREAD

**Issue by ascheinb** [kokkos/kokkos#2237]
Hi all,

I am getting this compiler error on Summit and Princeton's local GPU cluster. I tried with gcc/4.8.5, gcc/8.1.1 and pgi/19.4 and get the same result.

Below is a minimum example of the problem. Removing -rdc=true removes the problem, however I'm pretty sure we need that for optimization.

**build.sh**
```
$KOKKOS_DIR/bin/nvcc_wrapper -C -std=c++11 -fopenmp --expt-extended-lambda -rdc=true -arch=sm_70 -I$KOKKOS_DIR/install/include -c -o source.o source.cpp
$KOKKOS_DIR/bin/nvcc_wrapper -C -std=c++11 -fopenmp --expt-extended-lambda -rdc=true -arch=sm_70 -I$KOKKOS_DIR/install/include -c -o main.o main.cpp
$KOKKOS_DIR/bin/nvcc_wrapper    -std=c++11 -fopenmp --expt-extended-lambda -rdc=true -arch=sm_70 -L$KOKKOS_DIR/install/lib -o example *.o
```

**main.cpp:**
```
#include <Kokkos_Core.hpp>

int main()
{
}
```

**source.cpp:**
`#include <Kokkos_Core.hpp>`

**Output:**
```
nvlink error   : Multiple definition of 'kokkos_impl_cuda_constant_memory_buffer' in 'source.o', first defined in 'main.o'
nvlink error   : Multiple definition of '_ZN6Kokkos4Impl25g_device_cuda_lock_arraysE' in 'source.o', first defined in 'main.o'
nvlink fatal   : merge_elf failed
```

Thanks for any suggestions!

**Comment by dalg24** [comment]
Please post your Kokkos configuration script.  I could not reproduce the issue with `../generate_makefile.bash --with-serial --with-openmp --with-cuda --with-cuda-options=enable_lambda,rdc --arch=Pascal70,BDW`

**Comment by ascheinb** [comment]
Adding rdc to --with-cuda-options resolved the problem. Thank you!
