### ISSUE TITLE
list of clang format complaints

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2238]
If we ever do another clang-format change, here's a list of some lines/sections that look *horrible* as a result of the last clang-format change and should look reasonable after any changes we make (because at least having an organized place to complain makes me feel better :-P)

**Comment by dhollman** [comment]
https://github.com/kokkos/kokkos/blob/83799feaae8c4ac32db83044fafd139732493911/core/src/Cuda/Kokkos_Cuda_Parallel.hpp#L885

**Comment by dhollman** [comment]
https://github.com/kokkos/kokkos/blob/83799feaae8c4ac32db83044fafd139732493911/core/src/Cuda/Kokkos_Cuda_Parallel.hpp#L1579-L1583

**Comment by dalg24** [comment]
@dhollman Please suggest configuration options that would resolve the issues you report.

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/83799feaae8c4ac32db83044fafd139732493911/core/src/Kokkos_MemoryTraits.hpp#L70-L96
Here is another example where the formatting is not great but the cure for that one is putting the code between a comment `// clang-format off` and `// clang-format on`

**Comment by dhollman** [comment]
@dalg24 Unfortunately, the biggest one is not yet an option in mainline `clang-format`, so I'm waiting on that one at the very least.  I will try to suggest changes when possible, but even in the absence of that, I think it's good to collect and document these issues.

**Comment by dhollman** [comment]
https://github.com/kokkos/kokkos/blob/9247188bbce68d947d7b6d90f32fe337b9d391b7/core/src/impl/Kokkos_ViewMapping.hpp#L1989-L2017

**Comment by ajpowelsnl** [comment]
@dalg24 -- can we close this issue?
