### ISSUE TITLE
Removing "NONE" from the list of Kokkos_ARCH in KokkosConfig.cmake

### ISSUE THREAD

**Issue by ipdemes** [kokkos/kokkos#2241]
I get "NONE"  in the list of Kokkos_ARCH in KokkosConfig.cmake even if I explicitly specify architecture.
my cnfigure script:
`CC=clang CXX=clang++ cmake -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} --gcc-toolchain=/projects/opt/ppc64le/gcc/7.4.0 -static-libstdc++ -D__STRICT_ANSI__" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} --gcc-toolchain=/projects/opt/ppc64le/gcc/7.4.0 -static-libstdc++ -D__STRICT_ANSI__" -DCMAKE_INSTALL_PREFIX=/home/irina/install_dir/kokkos_cuda_power -DCMAKE_BUILD_TYPE=Debug  -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON  -DKokkos_ENABLE_DEBUG=ON  -DKokkos_ENABLE_SERIAL=ON -DKOKKOS_CXX_COMPILER_ID=Clang -D-DKokkos_ARCH=Power9 -DKokkos_ARCH_VOLTA70=ON ..` 

The Kokkos_ARCH in KokkosConfig.cmake  I get:
`SET(Kokkos_ARCH                         NONE;VOLTA70)`

**Comment by ipdemes** [comment]
@jjwilke

**Comment by jjwilke** [comment]
Got it. Yes, I see now that `Kokkos_ARCH` still defaults to `None` (legacy CMake that I missed cleaning up). I will try to fix this today.

As an aside: I think you have `-D-DKokkos_ARCH=Power9` instead of `-DKokkos_ARCH=Power9`

**Comment by ipdemes** [comment]
@jjwilke : thank you for finding the typo. You;ll get the same output if you remove  -D-DKokkos_ARCH=Power9
