### ISSUE TITLE
Document Jenkins nightly testing coverage, add jobs for any gaps in coverage

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2242]

**Comment by dalg24** [comment]
I suppose you are referring to your internal Jenkins server at Sandia and not the ORNL server that is running CUDA tests on pull requests and reporting back on GitHub.

**Comment by ndellingwood** [comment]
> I suppose you are referring to your internal Jenkins server at Sandia and not the ORNL server that is running CUDA tests on pull requests and reporting back on GitHub.

Yes that's correct.

**Comment by jeffmiles63** [comment]
Test coverage is documented in https://github.com/kokkos/internal-documents/blob/master/testing/KokkosAutomatedTesting.md

**Comment by jeffmiles63** [comment]
The full matrix is in https://github.com/kokkos/internal-documents/blob/master/testing/Kokkos_Test_Coverage_Matrix.xlsx

**Comment by PhilMiller** [comment]
@ndellingwood That internal document is pretty badly out of date. Want to update it to current and then close this?

**Comment by ndellingwood** [comment]
> @ndellingwood That internal document is pretty badly out of date. Want to update it to current and then close this?

@PhilMiller yes, very badly out of date. i have this on my list, will self-assign this issue

**Comment by ndellingwood** [comment]
@PhilMiller here is the current link with updated job list https://github.com/kokkos/internal-documents/blob/master/testing/Kokkos_Nightly_Testing.md
