### ISSUE TITLE
What is the overhead associated with Scratch space

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#2243]
I want to have a rough idea to "allocate" scratch space at parallel_for/parallel_reduce.  If "0" is selected for NVIDIA GPUs, the cost is initialization of shared-memory that is considered negligible.  How about main memory ("1") on GPUs and CPUs, respectively?   Does Kokkos backend call cudaMalloc/malloc every time parallel_for/parallel_reduce is called?  Or does it use other mechanism to reduce the overhead?

**Comment by crtrott** [comment]
It uses other mechanism. There is a persistent buffer for this stuff.
