### ISSUE TITLE
boolean reduction value_type changes answer

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#225]
I'm trying to write some custom parallel_reduce functors which will compute whether a condition is true for all items in an array. I tried to use "bool" as the value_type and implement methods based on the && operator. Strangely, it gives the wrong output when value_type is bool but I can fix it by using an integer value_type:

    struct SameContent {
    #if 0
      typedef int value_type;
    #else
      typedef bool value_type;
    #endif
      Kokkos::View<int*> a_;
      Kokkos::View<int*> b_;
      SameContent(Kokkos::View<int*> a, Kokkos::View<int*> b):a_(a),b_(b) {}
      KOKKOS_INLINE_FUNCTION
      void init(value_type& update) const
      {
        update = 1;
      }
      KOKKOS_INLINE_FUNCTION
      void join(volatile value_type& update,
          const volatile value_type& input) const
      {
        update = update && input;
      }
      KOKKOS_INLINE_FUNCTION
      void operator()(int i, value_type& update) const
      {
        update = update && (a_[i] == b_[i]);
      }
    };

Am I misusing Kokkos here ?
If this is something that should work, I have a two-file standalone example that replicates the issue. All the above is using Kokkos with CUDA on Shannon.

**Comment by hcedwar** [comment]
Reduction value_type needs to be a word-aligned plain-old-data types.  Unfortunately 'bool' can be compiled to a fraction of a word, which is probably the source of the error.  We should introduce a static_assert to catch / enforce this requirement.

**Comment by ibaned** [comment]
Thank you for the explanation. I'll switch to word-sized value_types in my code. A compile-time check would be much appreciated.

**Comment by hcedwar** [comment]
The types can be larger than a word (i.e., int) just not smaller.  Re-opening until we get the static_assert into the code, then will close.

**Comment by crtrott** [comment]
Pushed to Master and Trilinos: you can not do reductions with types smaller than 32bit now

**Comment by ibaned** [comment]
Just FYI, I had to increase this further from `int32_t` to `int64_t` to use an NVidia GTX 980 Ti with the CUDA 8.0 RC.

https://github.com/ibaned/omega_h2/commit/18110dbfd1fbe6e55cfabd9a54ba3e866fe8581b
