### ISSUE TITLE
Compile kokkos with fortran code

### ISSUE THREAD

**Issue by huilinye** [kokkos/kokkos#2253]
Dear kokkos users,

I want to couple kokkos code and fortran code. I have finished the interface writing, but I don't know how to compile them. Below is my compile file, but it doesn't work. Please advise me about the compiling process.

kokkos_f_interface.f90, kokkos_c_interface.cpp are two interfaces. The main file is main.f90.

#!/bin/bash
export KOKKOS_ROOT_DIR=${HOME}/Kokkos/kokkos

gfortran -c -std=f2008 kokkos_f_interface.f90
g++ -fopenmp -O3 -c -I./ -I$KOKKOS_ROOT_DIR/core/src kokkos_c_interface.cpp
gfortran -c -g -std=f2008 main.f90
gfortran -std=f2008 -o  kokkos_f_interface.o kokkos_c_interface.o main.o -L$KOKKOS_ROOT_DIR/lib -lkokkos -lstdc++ -fopenmp

**Comment by huilinye** [comment]
> Uhm that in itself isn't quite enough information. We have an example of building a combined kokkos/fortran code. If you got to the develop branch (which has now new and shiny updated cmake support) you can find it here: example/build_cmake_in_tree/. So basically this works:
> 
> ```
> mkdir build
> cd build
> cmake -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH=Power8 ../
> make -j
> ```
> 
> So in principle that works. What are your concrete issues?

@crtrott It works now for that I call fortran function in Kokkos program. While I still don't know how to compile the program that the fortran is the main program while kokkos function is called.

**Comment by huilinye** [comment]
> @huilinye My comment here is irrelevant to the kokkos software. But since you are using Fortran, in case you were unaware, I wanted to inform you that Fortran already has a native one-sided-communication parallelism known as Coarray Fortran as part of the F2008/F2018 standards, resolving much of the explicit need for external packages or communication libraries. Hope that is helpful in your special application.

@shahmoradi Many thanks for the references that are useful for me!

**Comment by huilinye** [comment]
> Uhm that in itself isn't quite enough information. We have an example of building a combined kokkos/fortran code. If you got to the develop branch (which has now new and shiny updated cmake support) you can find it here: example/build_cmake_in_tree/. So basically this works:
> 
> ```
> mkdir build
> cd build
> cmake -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH=Power8 ../
> make -j
> ```
> 
> So in principle that works. What are your concrete issues?

@crtrott  Compiling the example in example/build_cmake_in_tree/ only works for Openmp and serial. I try to compile using CUDA option. It tells no nvcc compiler. And then I set the cmake compiler as:
set(CMAKE_CXX_COMPILER ${KOKKOS_PATH}/bin/nvcc_wrapper)

It can compile, but the compiling process is continuing without idling and tells 

You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++

Please advice me about this?

**Comment by masterleinad** [comment]
> It can compile, but the compiling process is continuing without idling and tells
> 
> You have changed variables that require your cache to be deleted.
> Configure will be re-run and you may have to reset some variables.
> The following variables have changed:
> CMAKE_CXX_COMPILER= /usr/bin/c++
> 
> Please advice me about this?

It is best to just start from a clean build directory when you change the compiler.

**Comment by huilinye** [comment]
> > It can compile, but the compiling process is continuing without idling and tells
> > You have changed variables that require your cache to be deleted.
> > Configure will be re-run and you may have to reset some variables.
> > The following variables have changed:
> > CMAKE_CXX_COMPILER= /usr/bin/c++
> > Please advice me about this?
> 
> It is best to just start from a clean build directory when you change the compiler.

Yeah, I re-create the build directory and it doesn't work!

**Comment by masterleinad** [comment]
What kind of problems do you see starting from an empty build directory again?

**Comment by huilinye** [comment]
The same results!
Following is the cmake file:

cmake_minimum_required(VERSION 3.1)
project(Example CXX C Fortran)

set(CMAKE_CXX_COMPILER ${HOME}/Kokkos/kokkos/bin/nvcc_wrapper)
list(APPEND CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} -O3)

add_subdirectory(${Example_SOURCE_DIR}/../.. ${Example_BINARY_DIR}/kokkos)

include_directories(${Kokkos_INCLUDE_DIRS_RET})

add_executable(example cmake_example.cpp foo.f)
target_link_libraries(example kokkos)

I use the command: cmake -DKOKKOS_ENABLE_CUDA=ON -DKOKKOS_ARCH=Pascal61 to compile the example

**Comment by crtrott** [comment]
In the example you need to set -DKokkos_ENABLE_CUDA_LAMBDA=ON too for building with CUDA. This here worked for me on develop branch:
```
cd example/build_cmake_in_tree
mkdir build
cd build
cmake -DKokkos_ENABLE_CUDA=ON -DCMAKE_CXX_COMPILER=/home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper -DKokkos_ARCH=Pascal60 -DKokkos_ENABLE_CUDA_LAMBDA=ON ../
make -j
./example 10
macro  KOKKOS_ENABLE_CUDA      : defined
macro  CUDA_VERSION          = 10010 = version 10.1
Kokkos::Cuda[ 0 ] Tesla P100-SXM2-16GB capability 6.0, Total Global Memory: 15.9 G, Shared Memory per Block: 48 K : Selected
Kokkos::Cuda[ 1 ] Tesla P100-SXM2-16GB capability 6.0, Total Global Memory: 15.9 G, Shared Memory per Block: 48 K
Kokkos::Cuda[ 2 ] Tesla P100-SXM2-16GB capability 6.0, Total Global Memory: 15.9 G, Shared Memory per Block: 48 K
Kokkos::Cuda[ 3 ] Tesla P100-SXM2-16GB capability 6.0, Total Global Memory: 15.9 G, Shared Memory per Block: 48 K
Number of even integers from 0 to 9
  Parallel: 5      0.000034
Sequential: 5      0.000000
 Hello World from Fortran
```

**Comment by huilinye** [comment]
It works now as the same setting with @crtrott . Feel free to close this. Thanks.
