### ISSUE TITLE
Fix alignment for Kokkos::complex

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2255]
Reported at hackathon, in order to get proper 8 byte and 16 byte loads for `complex<float>` and `complex<double>` the user derived his own classes from CUDA's `float2` and `double2`. 

But it is enough to tell the type that it is aligned: `alignas ( 2*sizeof(RealType))`

**Comment by crtrott** [comment]
We can partially specialize for `pair<T,T>`.

**Comment by dhollman** [comment]
I don't know if we really want to support use cases that abuse `pair` in this way, but if we do, we should go all in on it:

```
template <class T, class U>
struct alignas((alignof(T) > alignof(U)) ? 2 * alignof(T) : 2 * alignof(U)) pair;
```

That should do the trick, and should support whatever use cases we would have wanted to support for the `pair<T, T>` case

**Comment by nliber** [comment]
There look to be a fair number of uses of pair<T, T> inside Kokkos, so we probably should do this (the full general one @dhollman wrote above).

**Comment by crtrott** [comment]
I am fine with that.

**Comment by ndellingwood** [comment]
Related PR #2259
