### ISSUE TITLE
target_link_libraries flag propagation issues

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2264]
@ipdemes Troubles with CXXFLAGS not propagating

**Comment by jjwilke** [comment]
In `CMakeFiles/Export/lib/cmake/Kokkos/KokkosTargets.cmake` there should be a section that looks like:

````
set_target_properties(Kokkos::kokkoscore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-fopenmp;-mavx;-march=core-avx2;-mtune=core-avx2>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-fopenmp;-mavx;-march=core-avx2;-mtune=core-avx2;Kokkos::libdl"
)
````

This defines all the the compiler and linker flags that Kokkos should propagate to your project.  We should validate that 1) The expected flags are showing up in your `KokkosTargets.cmake` file and 2) what flags appear in a `make VERBOSE=1` output

**Comment by masterleinad** [comment]
What is the status? Do we still expect something to be done here?

**Comment by ipdemes** [comment]
@masterleinad : you can close this issue. I get all necessary flags from Kokkos target
