### ISSUE TITLE
How to control texture memory binding

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#2275]
I am having the following error when I create large Kokkos:View objects.

`Kokkos::CudaSpace ERROR: Cannot attach texture object to alloc_ptr(0x7ffea0000000) alloc_size(2397139568) max_size(1073741824) `

Is there any way to control texture memory binding or do I have to reduce the size of Kokkos::View?

**Comment by crtrott** [comment]
You can reduce the size of the view or switch to develop branch where this problem is sidestepped.

**Comment by crtrott** [comment]
Also for questions like this you may want to simply ask on the slack channel: kokkosteam.slack.com, you usually get an answer faster there.
