### ISSUE TITLE
Do ScatterViews support subviews?

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2276]
Simple question: Do ScatterViews support subviews? If not, consider this a feature request. See #1393.

**Comment by janciesko** [comment]
@stanmoore1: the Kokkos::subview API does not support ScatterView so you cannot create a subview of a ScatterView.
But, you can create a subview of a view and then create a ScatterView of that subview.
Something like:

```
view_t original_view("original_view", n);
auto original_sub_view = Kokkos::subview(original_view, rangeDim0);
scatter_view_t scatter_sub_view = Kokkos::Experimental::create_scatter_view(Op{}, original_sub_view);
```

Would this work for you?

**Comment by janciesko** [comment]
We did add subview unit-test coverage a while back. See if this covers the use-case: 
https://github.com/kokkos/kokkos/pull/4587

**Comment by PhilMiller** [comment]
@stanmoore1 Did Jan's PR address your needs?

**Comment by stanmoore1** [comment]
Unfortunately taking a subview of a view and then creating a `ScatterView` out of that won't work to prevent expensive memory allocations. As described in https://github.com/kokkos/kokkos/issues/1393, we need a way to keep a persistent copy of a ScatterView that has extra space but doesn't require summing over the entire view, otherwise there is an overhead of the extra reductions. If we don't overallocate then there is an overhead of having to realloc every timestep which can be expensive too.
