### ISSUE TITLE
Random issues after CMake overhaul

### ISSUE THREAD

**Issue by junghans** [kokkos/kokkos#2283]
- `BUILD_SHARED_LIBS=ON` option is broken
```
[ 94%] Linking CXX shared library libkokkos.so
/usr/bin/ld: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
```
- shared library misses a so version number, use `set_target_properties(kokkoscore PROPERTIES 3)` to fix that.
- library should be installed into `lib64` on 64-bit systems, there is a `INSTALL_LIB_DIR` option, but it gets ignored(?)
- all headers get installed independently, which backends are enabled
- `KokkosConfig.cmake` etc. get installed twice, once in `lib/cmake/Kokkos` and once in `lib/CMake/Kokkos`
- pkgconfig files (`kokkos.pc`) misses version information

**Comment by crtrott** [comment]
1) ??
2) hm is that generally true? I have seen tons of projects which just install into lib
3) This is how Kokkos internally works now. Cleaning this up would take a bit of work and is not in scope for the 3.0 release.
4) @jjwilke did we still want to do this or what did we decide on cmake vs CMake directory?
5) We probably need to first introduce a proper version number in the code ...

**Comment by dalg24** [comment]
1. I think Christoph meant `BUILD_SHARED_LIBS=OFF`

4. We are still installing the legacy `kokkos` target (without the `Kokkos::` namespace) but I think we should just get rid of it even if we might break temporarily code downstream.

**Comment by junghans** [comment]
1. I meant to say support for shared libraries is broken, for some reason the `-fPIC` get stripped from the object compiles, which leads to that error above. Not sure where in the tribit salat that happens. 
2. If 1. gets fixed just please add a soversion number, as this is the standard for shared libraries.
3. There are two points here, first most distributions use `lib64` (Suse and Fedora-based ones) or `lib/<multiarch-tuple>` (Debian-based ones) already so it would be good to support that. Moving stuff isn't an option as the library directory get hard-coded in multiple places e.g. rpath and pkg-config. Secondly, it is confusing if there is an option like `INSTALL_LIB_DIR` provided by Kokkos' buildsystem, which is then ignored. CMake already provided a mechanism to configure install directories via the `GNUInstallDirs` macro.
4. Nitpick
5. Nitpick
6. Nitpick

**Comment by jjwilke** [comment]
1. I suspect this has to do with the way object libraries are used, but I'm not sure.
2. Yeah, we can definitely add the SOVERSION number easily enough. We'll need to selectively do this only outside of TriBITS.
3. We are gradually cleaning up relics like `INSTALL_LIB_DIR` that we missed. This can just get deleted. As far as the install dir being lib vs lib64 goes? I don't love the idea that the Kokkos config would live in different places on different systems (even if non-standard), unless we rely on `Kokkos_ROOT` install of `Kokkos_DIR` for downstream projects to find it. 
4. I had been trying to preserve as much as possible - but we're already breaking so much backwards compatibility we might as well just delete it. If @crtrott is comfortable people won't be too upset, I say just install the single location. 
5. I can add the version numbers to KokkosCore_config.h. I haven't looked at the xSDK requirements in a while. We may want to open this as another project.

**Comment by dalg24** [comment]
> * `BUILD_SHARED_LIBS=ON` option is broken
> 
> ```
> [ 94%] Linking CXX shared library libkokkos.so
> /usr/bin/ld: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
> ```

Fixed in #2288
> 
> * shared library misses a so version number, use `set_target_properties(kokkoscore PROPERTIES 3)` to fix that.

Fixed in #2291 

> * library should be installed into `lib64` on 64-bit systems, there is a `INSTALL_LIB_DIR` option, but it gets ignored(?)

Won't fix yet.  This is more controversial.  See https://github.com/kokkos/kokkos/pull/2287#pullrequestreview-285067434.  Would you open a separate issue for it.

> * all headers get installed independently, which backends are enabled

Won't fix.  This is not a defect.  The headers get installed the same way with the generated makefiles and then the preprocessor macros do the right thing.

> * `KokkosConfig.cmake` etc. get installed twice, once in `lib/cmake/Kokkos` and once in `lib/CMake/Kokkos`

Resolved in #2287 

> * pkgconfig files (`kokkos.pc`) misses version information

Fixed in #2286

**Comment by junghans** [comment]
> > * library should be installed into `lib64` on 64-bit systems, there is a `INSTALL_LIB_DIR` option, but it gets ignored(?)
> 
> Won't fix yet. This is more controversial. See [#2287 (review)](https://github.com/kokkos/kokkos/pull/2287#pullrequestreview-285067434). Would you open a separate issue for it.
See #2296

**Comment by dalg24** [comment]
Closing as all issues reported have been resolved
