### ISSUE TITLE
Rename FORCE_UVM in CUDA_DEFAULT_UM

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2289]
Our UVM settings have two issues:
- we are not actually forcing: we just change the default, and even if you don't set it UM it still enabled
- It is not "virtual" anymore, since there is actual hardware support. NVIDIA now calls it unified memory. 

So two things: we can/need to rename the options users set, and we could rename all the macros.

**Comment by dalg24** [comment]
`FORCE_UVM` is not used anywhere.  We decided to keep the `CUDA_UVM` option name for now but updated the documentation in #2473.

**Comment by PhilMiller** [comment]
Renaming happened a while ago. With #5608, this is going away.
