### ISSUE TITLE
Validate options passed to CMake

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2293]
Motivation for this is avoid deceptions like #2292 

This involves building a list of valid options and checking all options enabled by the user against that list.

**Comment by jjwilke** [comment]
Probably the easiest way is 

````
foreach(OPT ${Kokkos_OPTIONS})
if (NOT DEFINED Kokkos_ENABLE_${OPT})
message(FATAL_ERROR "Given ${OPT} to Kokkos_OPTIONS, but it does not appear to be a valid options")
endif()
endforeach()
````

All valid options should be cache variables with a defined default.

**Comment by dalg24** [comment]
We do not accept `-DKokkos_OPTIONS=...` any more so this is not relevant.
