### ISSUE TITLE
Update / Finalize Spot Check and Nightly test scripts to work with cmake

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2299]
CMake version of test_all_sandia is cm_test_all_sandia uses the cmake equivalent of generate_makefile.bash (cm_generate_makefile.bash).  

When tests are complete and issues resolved, test_all_sandia and generate_makefile.bash will be replaced with the cm versions which should drastically simplify updating the jenkins jobs.

**Comment by ndellingwood** [comment]
Update as of 10/24/2019:

kokkos-dev-2: spot-check fails with clang8; @jeffmiles63 has a fix in PR #2501 and #2502 
bowman: several issues like:
`/home/projects/x86-64-knl/gcc/4.7.4/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by cmake)`; @jeffmiles63 has a fix in PR #2505, retesting with that PR
apollo: issues with older version of hpx/1.2.1, discussion in #2500 
white: in-progress, no fails so far - I'll edit+update this comment with results

**Comment by ndellingwood** [comment]
Based on discussion during 10/31/2019 meeting, hpx/1.3.0 will be installed on apollo. Once confirmed that all tests pass on apollo following the tpl update the blockers to begin using the new scripts in nightly testing that utilize the cmake build system will be resolved.

Items to complete this issue:
- [ ] Install hpx/1.3.0 on apollo
- [ ] confirm scripted testing passes on apollo
- [ ] issue PR to rename currently named `generate_makefile.bash` and `test_all_sandia`; remove `cm_` prefix from the new replacement scripts
- [ ] add new nightly tests to continue exercising the makefile build system

**Comment by ndellingwood** [comment]
PR #2551 contains more updates to `*_test_all_sandia` scripts:
- arm testing (compiler list updates, mayer testbed)
- pgi testing (compiler list updates, blake testbed)
- fixes for module lists

**Comment by ndellingwood** [comment]
Another PR issued #2562 with a few more minor updates and fixes.

**Comment by jeffmiles63** [comment]
this is resolved as 3.0 is released and nightly testing is now using cmake
