### ISSUE TITLE
Scratch space for range policy ..

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#231]
Currently team policy has scratch spaces for per team and per thread. Can we extend this to other parallel policies such as range policy (without team scratch in this case )?

**Comment by crtrott** [comment]
You mean something like a generic per_iteration scratch or so?

**Comment by kyungjoo-kim** [comment]
Yes, that might be the better name.

**Comment by dsunder** [comment]
This is a duplicate of #428
