### ISSUE TITLE
Get nvcc_wrapper to pass CMake feature tests

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2317]
`nvcc_wrapper` fails feature tests for CMake because `nvcc` does not accept intermediate standards like `std=c++1y`.  This wreaks havoc on the build system because we can't just declare `cxx_std_14` as a valid feature to CMake.

What we really want is for c++11, etc to be valid features for `nvcc_wrapper`

**Comment by jjwilke** [comment]
I believe we can do the following.

In `nvcc_wrapper`
````
       if [ ! -z "${KOKKOS_CMAKE_CXX_STANDARD}" ]; then
         echo "nvcc_wrapper does not accept intermediate standard flag $1, but I will use -std=c++${KOKKOS_CMAKE_CXX_STANDARD} instead"
         shared_args="$shared_args -std=c++${KOKKOS_CMAKE_CXX_STANDARD}"
       else
        echo "nvcc_wrapper has been given intermediate standard flag $1 - nvcc only accepts full standard flags like -std=c++11"
        exit 1
       fi
````

Then in the CMake, we set the environment variable:
````
SET(ENV{KOKKOS_CMAKE_CXX_STANDARD} ${KOKKOS_CXX_STANDARD})
````

This tells `nvcc_wrapper` that we are inside a CMake configure. It can then happily change the flags so that `nvcc_wrapper` doesn't fail during CMake feature tests.  After making this change, we can now use c++14 as a compiler feature.

**Comment by jjwilke** [comment]
Related to #2305 and #2035

**Comment by jjwilke** [comment]
This will be a temporary fix until we bump the CMake version. CMake will no longer test levels of the standard that are not explicitly requested in 3.16. Then we can get rid of this annoying logic in `nvcc_wrapper`

**Comment by berselius** [comment]
To be clear, is this supposed to work if you are using c++14, or is this fix just for the intermediate ones? I have a cmake application that is trying to do e.g.

`target_compile_features(graph PUBLIC cxx_std_14)`

And it is barfing ala

```
CMake Error at src/graph/CMakeLists.txt:12 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 7.3.0.
```

**Comment by jjwilke** [comment]
This fixes if you request 11, 14, or 17. Due to some subtleties in the way CMake determines compiler features, this didn't work.  `cxx_std_14` *should* now be in the list of supported features when the PR goes in.

**Comment by berselius** [comment]
Ok, I built off develop with this fix, but am still getting the same error when I request cxx_std_14 in my application. Is there something kokkos-related I need to add on my end?

**Comment by jjwilke** [comment]
No, I forgot to add a necessary env variable to the Kokkos import. To continue for now, please try setting `KOKKOS_CMAKE_CXX_STANDARD=14` in your environment. The Kokkos import *should* do this automatically.

**Comment by jjwilke** [comment]
Er, never mind. I can't move the Kokkos import BEFORE the C++ language declaration.
So, yes, when you configure set the env `KOKKOS_CMAKE_CXX_STANDARD=14` and you should be good.

I don't why I gave it a weird name. I will probably change it to `KOKKOS_CXX_STANDARD` when I update the build documentation for how to do this correctly.

**Comment by berselius** [comment]
Thanks, that seemed to do the trick!
