### ISSUE TITLE
View::memory_span concerns

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#233]
The purpose of the `View::memory_span(N0,N1,...)` static function is to compute how much memory, in bytes, that must be allocated for a `View` of the given dimensions.

Concerns:
1. The name of this function is non-intuitive.  Possible alternative is `required_allocation_size`.
2. An overload that accepts an `array_layout` object is required to support allocation of views with strided layout.
3. If memory allocation requirements are effected by runtime construction arguments, such as allowing padding, then an additional constructor-options argument is needed.

**Comment by crtrott** [comment]
This got fixed.
