### ISSUE TITLE
Kokkos::Timer

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#234]
"Expose" and commit to supporting the Kokkos timer by making it available in the Kokkos namespace.
Review interface and implementation prior to this update.

**Comment by crtrott** [comment]
We should probably make it use std::chrono features internally.

**Comment by dsunder** [comment]
Here is the simple timer that I created for Uintah using c++11.



—Dan

**Comment by bartlettroscoe** [comment]
Related to trilinos/Trilinos#253.

**Comment by ndellingwood** [comment]
Pull request issued #274 

Timer available in Kokkos namespace. 

Updated unit tests, performance tests, and examples using
Kokkos::Impl::Timer to use Kokkos::Timer
