### ISSUE TITLE
Performance Test are failing for kokkos/containers when built with CMake

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2347]
The CMakelists.txt version of the containers performance tests is currently configured to build a single test executable for all backends.  Then GNU make is configured to build a separate test executable for each of the configured backends.  It appears that the problem with a single executable is that the test application calls Kokkos::initialize and Kokkos::finalize before and after each test.  The Cuda instance doesn't appear to like calling Kokkos::initialize a second time with a different backend selected.

Solution is to configure and enable different test EXEs for each of the enabled backends.

**Comment by jjwilke** [comment]
Does this need CMake modifications? Or test script modifications?

**Comment by jeffmiles63** [comment]
I believe it does.  The GNU make is driving this in that configuration, so I would expect a CMake equivalent ...see PR #2348

**Comment by jjwilke** [comment]
Sorry, I was looking at `core/perf_tests`. Yes, you are correct.
