### ISSUE TITLE
CMake Kokkos_ARCH_XXX isn't setting some of the arch dependent defines properly.

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2349]
Two specific issue here.  

-- Both the Kokkos_ARCH_VOLTA## and the Kokkos_ARCH_PASCAL## need to have a KOKKOS_ARCH_VOLTA and KOKKOS_ARCH_PASCAL defined in the C++ headers.  I believe this is also true for all of the other 2 digit CUDA architectures, but it won't hurt if it is added as such

-- AMDAVX and SNB should also set KOKKOS_ARCH_AVX

**Comment by jjwilke** [comment]
See PR #2346: I believe this is redundant.

**Comment by jeffmiles63** [comment]
this is handled with PR #2346
