### ISSUE TITLE
Can Host and Cuda run simultaneously?

### ISSUE THREAD

**Issue by huilinye** [kokkos/kokkos#2352]
I found the Host is always remaining idling and waiting for Cuda result when Kokkos function is called. Like below code:

      
      Kokkos::parallel_reduce( range_policy( 0, N ), KOKKOS_LAMBDA ( int j, double &update ) {
      double temp2 = 0;

      for ( int i = 0; i < M; ++i ) {
        temp2 += A( j, i ) * x( i );
      }

      update += y( j ) * temp2;
    }, result );
    
    for (int kk=0; kk< 10000; ++kk){
		....
	}

When the Kokkos::parallel_reduce is called and run in Cuda space, the subsequent for loop cannot execute until Cuda work is finished. Could I make the Host and Cuda run simultaneously?

**Comment by mhoemmen** [comment]
If `result` is a reference to a value on host, then the `parallel_reduce` must finish on device and return the result synchronously to host.

**Comment by ndellingwood** [comment]
If you pass a View or Reducer as a result then you should get the behavior you'd like, see this section of the wiki for reference ["The call is potentially asynchronous if the ReducerArgument is not a scalar type."](https://github.com/kokkos/kokkos/wiki/Kokkos%3A%3Aparallel_reduce#semantics)

**Comment by huilinye** [comment]
> ```c++
> Kokkos::View<double,Kokkos::CudaHostPinnedSpace> result("R");
> Kokkos::parallel_reduce( range_policy( 0, N ), KOKKOS_LAMBDA ( int j, double &update ) {
>   double temp2 = 0;
> 
>   for ( int i = 0; i < M; ++i ) {
>     temp2 += A( j, i ) * x( i );
>   }
> 
>   update += y( j ) * temp2;
> }, result );
> 
> for (int kk=0; kk< 10000; ++kk){
> 	....
> }
> ```
> 
> This will be asynchronous.

@crtrott Many thank. Now it works when I define all the variables using in Cuda in CudaHostPinnedSpace. If this will affect the efficiency?

**Comment by crtrott** [comment]
Not this is fine from a performance perspective.

**Comment by PhilMiller** [comment]
This question seems to have been answered.
