### ISSUE TITLE
FAILED NIGHTLY: CUDA compile options not set for test libs

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2362]
Need something like this for test libs...

  IF (KOKKOS_ENABLE_CUDA)
    TARGET_COMPILE_OPTIONS(
      ${NAME}
      PUBLIC $<$<COMPILE_LANGUAGE:CXX>:${KOKKOS_CUDA_OPTIONS}>
    )
    SET(TEST_NODEDUP_CUDAFE_OPTIONS)
    FOREACH(OPT ${KOKKOS_CUDAFE_OPTIONS})
      LIST(APPEND TEST_NODEDUP_CUDAFE_OPTIONS -Xcudafe ${OPT})
    ENDFOREACH()
    TARGET_COMPILE_OPTIONS(
      ${NAME} 
      PUBLIC $<$<COMPILE_LANGUAGE:CXX>:${TEST_NODEDUP_CUDAFE_OPTIONS}>
    )
  ENDIF()

**Comment by jjwilke** [comment]
Ah. gtest, e.g. needs these when building with `nvcc` or `Clang CUDA`?

**Comment by dalg24** [comment]
You are sketching a solution to a problem that you don't describe enough for us to reproduce.
How did you configure?  What was the error?  What was the compile line like?

**Comment by jeffmiles63** [comment]
############# BAD (without fixes to fake-tribits.cmake

cd /home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.02.16/clang/3.9.0/Pthread_Serial-release/algorithms/unit_tests && /projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.9.0/base/bin/clang++  -DGTEST_HAS_PTHREAD=0 -I/home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.02.16/clang/3.9.0/Pthread_Serial-release/algorithms/unit_tests -I/home/jsmiles/Development/test-build/kokkos/algorithms/unit_tests -I/home/jsmiles/Development/test-build/kokkos/algorithms/unit_tests/../src -I/home/jsmiles/Development/test-build/kokkos/tpls/gtest  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base   -o CMakeFiles/kokkosalgorithms_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o -c /home/jsmiles/Development/test-build/kokkos/tpls/gtest/gtest/gtest-all.cc
cd /home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.02.16/clang/3.9.0/Pthread_Serial-release/core/unit_test && /projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.9.0/base/bin/clang++  -DGTEST_HAS_PTHREAD=0 -I/home/jsmiles/Development/test-build/kokkos/tpls/gtest -I/home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.02.16/clang/3.9.0/Pthread_Serial-release/core/unit_test -I/home/jsmiles/Development/test-build/kokkos/core/unit_test  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base   -o CMakeFiles/kokkos_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o -c /home/jsmiles/Development/test-build/kokkos/tpls/gtest/gtest/gtest-all.cc

############# Error ########

/home/jsmiles/Development/test-build/kokkos/tpls/gtest/gtest/gtest-all.cc:1424:20: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
  typedef unsigned long long BiggestConvertible;  // NOLINT
                   ^
/home/jsmiles/Development/test-build/kokkos/tpls/gtest/gtest/gtest-all.cc:1424:20: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
  typedef unsigned long long BiggestConvertible;  // NOLINT
                   ^
1 error generated.
1 error generated.
make[2]: make[2]: *** [algorithms/unit_tests/CMakeFiles/kokkosalgorithms_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o] Error 1*** [core/unit_test/CMakeFiles/kokkos_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o] Error 1



#############.Good (with fixes to fake-tribits.cmake 

cd /home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.14.31/clang/3.9.0/Pthread_Serial-release/core/unit_test && /projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.9.0/base/bin/clang++  -DGTEST_HAS_PTHREAD=0 -I/home/jsmiles/Development/test-build/kokkos/tpls/gtest -I/home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.14.31/clang/3.9.0/Pthread_Serial-release/core/unit_test -I/home/jsmiles/Development/test-build/kokkos/core/unit_test  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base   -mavx -pthread -std=c++11 -o CMakeFiles/kokkos_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o -c /home/jsmiles/Development/test-build/kokkos/tpls/gtest/gtest/gtest-all.cc
cd /home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.14.31/clang/3.9.0/Pthread_Serial-release/algorithms/unit_tests && /projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.9.0/base/bin/clang++  -DGTEST_HAS_PTHREAD=0 -I/home/jsmiles/Development/test-build/kokkos/scripts/testing_scripts/TestAll_2019-09-27_11.14.31/clang/3.9.0/Pthread_Serial-release/algorithms/unit_tests -I/home/jsmiles/Development/test-build/kokkos/algorithms/unit_tests -I/home/jsmiles/Development/test-build/kokkos/algorithms/unit_tests/../src -I/home/jsmiles/Development/test-build/kokkos/tpls/gtest  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base   -mavx -pthread -std=c++11 -o CMakeFiles/kokkosalgorithms_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o -c /home/jsmiles/Development/test-build/kokkos/tpls/gtest/gtest/gtest-all.cc

###### Note the addition of ‘ -mavx -pthread -std=c++11   ‘

**Comment by jeffmiles63** [comment]
This is just a sample....there are many others that fail too...I think what it is is that the newer compilers are more tolerant and thus it just works

**Comment by jeffmiles63** [comment]
note the -pthread is the result of another change...but it is included with the -mavx in the compile_options

**Comment by jjwilke** [comment]
Did we come up with a fix for this? We should set a `target_compile_features` for gtest based on that chosen for Kokkos.

**Comment by jeffmiles63** [comment]
my proposed fix for this is in PR #2384

**Comment by jeffmiles63** [comment]
I have added comments to #2396 and updated #2384 ... I think the simplest solution is to link the test libs to kokkos lib
