### ISSUE TITLE
FAILED NIGHTLY: Clang needs to set the gcc-toolchain

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2364]
Need to add something like this to kokkos_cxx_std.cmake

IF(KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
    execute_process(
      COMMAND "which"
      g++
      OUTPUT_VARIABLE gcc_exec_path ERROR_VARIABLE gcc_exec_path
      RESULT_VARIABLE gcc_result
      TIMEOUT 10
      )
    if (gcc_exec_path MATCHES "/bin/g")
      STRING(REPLACE "/bin/g++\n" "" GCC_PATH "${gcc_exec_path}")
      MESSAGE(STATUS "Clang using gcc toolchain ${GCC_PATH}")
      GLOBAL_APPEND(KOKKOS_COMPILE_OPTIONS --gcc-toolchain=${GCC_PATH})

      LIST(APPEND CLANG_LINK_OPTIONS ${KOKKOS_LINK_OPTIONS})
      LIST(APPEND CLANG_LINK_OPTIONS --gcc-toolchain=${GCC_PATH})
      GLOBAL_SET(KOKKOS_LINK_OPTIONS ${CLANG_LINK_OPTIONS})
    endif()
ENDIF()

**Comment by crtrott** [comment]
We should have a check in there if gcc-toolchain is already set by the user.

**Comment by jjwilke** [comment]
out of curiosity, what is the output of `clang++ -v -print-search-dirs' on the systems where this fails without the `gcc-toolchain`?

**Comment by jeffmiles63** [comment]
clang version 6.0.0 (git@github.com:llvm-mirror/clang bb8d45f8ab88237f1fa0530b8ad9b96bf4a5e6cc) (git@github.com:llvm-mirror/llvm 16ebb58ea40d384e8daa4c48d2bf7dd1ccfa5fcd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/projects/x86-64/clang/6.0/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.4.7
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.4.7
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 7.5
programs: =/home/projects/x86-64/clang/6.0/bin:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../x86_64-redhat-linux/bin
libraries: =/home/projects/x86-64/clang/6.0/lib/clang/6.0.0:/usr/lib/gcc/x86_64-redhat-linux/4.4.7:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64:/lib/../lib64:/usr/lib/../lib64:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../..:/home/projects/x86-64/clang/6.0/bin/../lib:/lib:/usr/lib

**Comment by jeffmiles63** [comment]
FYI, this is found in the Makefile.kokkos

# Explicitly set the GCC Toolchain for Clang.
ifeq ($(KOKKOS_INTERNAL_COMPILER_CLANG), 1)
  KOKKOS_INTERNAL_GCC_PATH = $(shell which g++)
  KOKKOS_INTERNAL_GCC_TOOLCHAIN = $(KOKKOS_INTERNAL_GCC_PATH:/bin/g++=)
  KOKKOS_CXXFLAGS += --gcc-toolchain=$(KOKKOS_INTERNAL_GCC_TOOLCHAIN)
  KOKKOS_LDFLAGS += --gcc-toolchain=$(KOKKOS_INTERNAL_GCC_TOOLCHAIN)
endif

**Comment by jeffmiles63** [comment]
looks like this can be set with the CMAKE_CXX_FLAGS, so I am moving the gcc-toolchain logic to the cm_generate_makefile script
