### ISSUE TITLE
kokkos_gtest lib shows up twice when compiling test exes 

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2365]
I had to comment out the target link libraries entry when not trilinos in kokkos_tribits.cmake
```
IF (NOT KOKKOS_HAS_TRILINOS)
##    TARGET_LINK_LIBRARIES(${EXE_NAME} kokkos_gtest)
    ADD_DEPENDENCIES(check ${EXE_NAME})
  ENDIF()
```

**Comment by mhoemmen** [comment]
I edited your post just to protect the code snippet with triple backquotes.

**Comment by jjwilke** [comment]
Yes, wires got crossed doing the Trilinos wrappers.
You can safely delete that line.
The `TESTONLYLIBS` flag causes it to get linked later.
