### ISSUE TITLE
FAILED NIGHTLY: Cuda path needs to be set for clang when compiling cuda

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2366]
need to add something like this to kokkos library, exes and test libraries and exes

  IF (KOKKOS_ENABLE_CUDA)
    IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
       IF (DEFINED KOKKOS_CUDA_DIR)
          IF (EXISTS ${KOKKOS_CUDA_DIR})        
             TARGET_COMPILE_OPTIONS(
                ${NAME}
                PUBLIC $<$<COMPILE_LANGUAGE:CXX>:--cuda-path=${KOKKOS_CUDA_DIR}>
              )
          ENDIF()
       ENDIF()
    ENDIF()
  ENDIF()

may also need the equivalent of 

TARGET_LINK_LIBRARIES(${LIBRARY_NAME} PUBLIC --cuda-path=${KOKKOS_CUDA_DIR})

**Comment by jjwilke** [comment]
Related to issue #2370
