### ISSUE TITLE
Memset equivalent?

### ISSUE THREAD

**Issue by ascheinb** [kokkos/kokkos#2369]
Is there a Kokkos equivalent to std::memset/cudaMemset? If I have a Kokkos View, how do I initialize/reinitialize to a (zero or non-zero) value?

**Comment by stanmoore1** [comment]
By default Kokkos views are initialized to zero. To reinitialize, you can use something like `Kokkos::deep_copy(d_view,0.0);`

**Comment by ascheinb** [comment]
Cool, thanks. By the way, is there a way to allocate a view but not initialize it?

**Comment by stanmoore1** [comment]
d_view = t_view_type(Kokkos::view_alloc("name",Kokkos::WithoutInitializing),size);

**Comment by ascheinb** [comment]
Thanks!
