### ISSUE TITLE
Large register usage from Kokkos::UnorderedMap

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2371]
Adding `Kokkos::UnorderedMap` to my code increased the kernel register usage on a V100 GPU from 184 to 255 (i.e. maximum). Any ideas on why `Kokkos::UnorderedMap` would blow up my register count?

**Comment by stanmoore1** [comment]
I did more digging and it is only the `insert` method in device code from `Kokkos::UnorderedMap` that blows up the register count. Using the `find` method does *not* blow up register count.

**Comment by crtrott** [comment]
The thread safe insert is a pretty complicated thing. It uses stuff like bit sets etc. and is likely to increase register count substantially. That said we could see if we can reduce it somehow if that seems important to you.

**Comment by stanmoore1** [comment]
@crtrott maybe other codes can take a huge hit in register pressure but this kernel already uses a lot of registers and just compiling the `UnorderedMap::insert` method into the code made a noticeable slowdown in the overall benchmark performance, even when it is never used.

**Comment by mhoemmen** [comment]
Note also that invoking `printf` can increase register use a lot, even if it never gets called.  In general, if you utter the invocation of a complicated thing, it will eat registers.  Hopefully `if constexpr` will make it easier to avoid that.

**Comment by stanmoore1** [comment]
I only invoke `printf` in device code for debugging...

**Comment by mhoemmen** [comment]
It's best to comment or ifdef it out if you don't need it, because you'll pay for it as long as it gets compiled (even if it is never called).

**Comment by stanmoore1** [comment]
I was able to remove the `Kokkos::UnorderedMap` from my code and use a 1D view instead, to avoid the performance hit.
