### ISSUE TITLE
Weird Preprocessor Macro definition

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2381]
Hey folks,

In #2307 I'm imitating HostSpace.cpp for my logical spaces. I copied over the use of a preprocessor macro here

https://github.com/kokkos/kokkos/blob/develop/core/src/Kokkos_HostSpace.hpp#L301

And @dhollman wanted to know why it was there. Should this be here? If so, feel free to close the issue (maybe comment the line), if not, maybe we should remove it

**Comment by DavidPoliakoff** [comment]
Apparently added here (https://github.com/kokkos/kokkos/commit/a74ec6d236315e7865781a24a472954c12727cd7 , and the other piece of code it informs has been moved or removed)

**Comment by dalg24** [comment]
```
$ git log --oneline -n1
f09736b0 (HEAD -> develop, upstream/develop) Merge pull request #2158 from kokkos/host_mirror_space
$ git grep PAR_DEEP_COPY_USE_MEMCPY
core/src/Kokkos_HostSpace.hpp:#define PAR_DEEP_COPY_USE_MEMCPY
```
I suspect this can be deleted.

**Comment by crtrott** [comment]
Agreed.

**Comment by DavidPoliakoff** [comment]
I'll grab this tomorrow
