### ISSUE TITLE
Remove skip validation for spot checks

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2388]
When the spot checks are run, the options and arch are generally a supported list for the machine type or the test selected.  Depending on the type of spot check, the options and/or arch may or may not be needed for the devices / compiler selected.  As a result, the places where CMake validates that the options and arch are consistent with the devices and compilers must disable the option/arch and print a warning rather than error out -- as this will cause the test to fail.

Adding an option to skip validation and enabling that option when spot check is selected.  Other scenarios are expected to be a 1 to 1 mapping so the skip validation shouldn't be necessary (I hope)

**Comment by jeffmiles63** [comment]
This appears to already be resolved, so using this issue to track cleanup of the cm_ test scripts

**Comment by dalg24** [comment]
What place specifically is causing the error?  We changed the behavior last week.

**Comment by jeffmiles63** [comment]
see previous comment...

**Comment by dalg24** [comment]
> This appears to already be resolved, so using this issue to track cleanup of the cm_ test scripts

Close then?

**Comment by jeffmiles63** [comment]
well, I still have to clean up the scripts to remove the unnecessary validation options
