### ISSUE TITLE
Update Travis CI testing

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2395]
- inject -O3 -Werror again?
  - Yes.
- build with the legacy build system? (one build maybe)
  - One build would be good: note use the generate_makefile_bash inside the scripts testing directory
- enable OPENMP for Device Parallel?
  - Yeah for a couple builds
- test more or less compilers?
  - I think this is fine for now
- run travis only for the develop and master branch? (Will only work for branches with the new ci file)
  - were you running it for anything else?
- test different CMake build types?
  - probably should have one OpenMP debug build
- turn one build in a canary build? (as a sniff test before the other builds)
  - yeah that sounds like a good idea: like some GCC / OpenMP / Release build

Do you want to first merge this and then do all the other things?

_Originally posted by @crtrott in https://github.com/kokkos/kokkos/pull/2392#issuecomment-536030644_

**Comment by jeffmiles63** [comment]
If it is possible, I think that the team would be more efficient if failed checks sent notifications to the author/s of the PR as well.

**Comment by dalg24** [comment]
Note that the build with the legacy build system (generated makefile) was not added.
Everything else has been addressed.
