### ISSUE TITLE
Makefile.kokkos lacks bounds checking option that CMake has

### ISSUE THREAD

**Issue by reberhardt7** [kokkos/kokkos#24]
Kokkos' CMake build system has an option for enabling bounds checking, but the Makefile-based build system doesn't look like it has a way to enable bounds checking.  Does it?

**Comment by reberhardt7** [comment]
Adding `-DKOKKOS_EXPRESSION_CHECK` to `CXXFLAGS` in my Makefile made bounds checking work:

```
CXXFLAGS = -O3 -DKOKKOS_EXPRESSION_CHECK
```

**Comment by crtrott** [comment]
I am actually working on that option right now to get a more extensible and systematic naming of debug and profiling options.
