### ISSUE TITLE
Simple parallel_for does not vectorize over threads

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#240]
Hello Kokkos Team,

My name is Michael Carilli.  We met at the GTC this year and you advised me that vectorization of simple parallel_for kernels on the CPU could be encouraged by compiling with the flag
-DKOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION.

I tried that and it doesn't seem to work.  I have attached a minimal working sample:  code, makefile, and the optimization report given by icpc version 16.0.1.  I have highlighted (with @@@@@) the section of vectorization.optrpt that concerns me:  my parallel_for at line 15 of vectorization.cpp is not vectorizing because "loop control variable was not identified."

[vectorization.cpp.txt](https://github.com/kokkos/kokkos/files/218114/vectorization.cpp.txt)
[Makefile.txt](https://github.com/kokkos/kokkos/files/218115/Makefile.txt)
[vectorization.optrpt.txt](https://github.com/kokkos/kokkos/files/218116/vectorization.optrpt.txt)

(.txt appended to filenames because github won't let me upload otherwise)

Please let me know if there's anything I'm missing!

Much appreciated,
Michael

**Comment by crtrott** [comment]
Hi

you are worried about the wrong loop. That loop you highlight is in line 320 of Kokkos_ExecPolicy.hpp.
That loop is a while loop which tries to deduct optimal chunk size. I.e. its part of the setup phase for launching a parallel kernel. What you are interested in is a couple lines below that. 

```
LOOP BEGIN at /home/mcarilli/Desktop/afrl/kokkos/git/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization.cpp(15,3)
<Peeled loop for vectorization>
LOOP END

LOOP BEGIN at /home/mcarilli/Desktop/afrl/kokkos/git/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization.cpp(15,3)
   remark #15300: LOOP WAS VECTORIZED
LOOP END

LOOP BEGIN at /home/mcarilli/Desktop/afrl/kokkos/git/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization.cpp(15,3)
<Remainder loop for vectorization>
LOOP END
```

That line 86 in Kokkos_OpenMP_Parallel.hpp is the loop which calls the operator of lambda. That is what needs to be vectorized and it got.

**Comment by jeffamelang** [comment]
I think the ultimate concern was some lacking performance, right?  Michael, can you perhaps tell us about the wider problem?  Perhaps this particular loop is being vectorized, but that just means there's a discrepancy in the performance somewhere else, right?

**Comment by crtrott** [comment]
Btw. such a code like the above one will not necessarily benefit from vectorization since it is bandwidth bound. So for this particular example (at least if it was more than the 100 long) vectorization or no vectorization wouldn't be expected to make a difference. Also for a loop of 100 like this I would expect threading to typically hurt, because the parallel launch and end of loop synchronization costs you something. In this particular case its even worse since all your threads will try to write to the same cache line. So if you have a particular performance issue and you can share the full code that might be the best thing to do.

**Comment by mcarilli** [comment]
Hi Jeff and Christian,

Thank you for your prompt and helpful replies.  

Christian, I know the code I sent is bandwidth bound; I sent it as the simplest example I could think of to test whether vectorization was actually taking place.  The value of 100 is arbitrary and has nothing to do with my application.  However, I've encountered another problem:  The simple change of adding an additional View object in vectorization.cpp appears to prevent vectorization.  I thought it might have something to do with aliasing, but including -fno-alias in my compiler flags does not fix it.  My background is mostly Cuda so I'm new to the CPU vectorization world, admittedly.

Simple parallel_for with only one view declared (same as my previous post):
[vectorization_oneview.cpp.txt](https://github.com/kokkos/kokkos/files/219383/vectorization_oneview.cpp.txt)
Corresponding optrpt (vectorization succeeds):
[vectorization_oneview.optrpt.txt](https://github.com/kokkos/kokkos/files/219385/vectorization_oneview.optrpt.txt)

Simple parallel_for with two views declared:
[vectorization_twoviews.cpp.txt](https://github.com/kokkos/kokkos/files/219422/vectorization_twoviews.cpp.txt)
Corresponding optrpt:
[vectorization_twoviews.optrpt.txt](https://github.com/kokkos/kokkos/files/219425/vectorization_twoviews.optrpt.txt)
Vectorization fails...I think.  At least, there's nothing in the optrpt that says any vectorization is taking place at line 20 of vectorization_twoviews.cpp.  Even more confusingly, there is no line in the "twoviews" optrpt that looks like this 
"...../OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_oneview.cpp(20,3)," 
as there was in the "oneview" optrpt above.

Makefile used for both:
[Makefile.txt](https://github.com/kokkos/kokkos/files/219426/Makefile.txt)

Jeff, I plan to post a functor that more closely resembles the actual rate limiting computation in my code.  I need to rewrite a sanitized representative version, because I'm not allowed to post the actual code (i'm sure you know the drill).  If you could look it over and offer advice, that would be fantastic.  However, I want to get my minimal sample behaving sensibly first.  No sense jumping to the difficult case when the simple one is still failing.

Thanks very much for your help,
Michael

**Comment by crtrott** [comment]
Oh you must have just overlooked it. Starting line 31 of your vectorization_twoviews.optrpt.txt it says it vectorized:
```
LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(15,19)
   remark #15542: loop was not vectorized: inner loop was already vectorized

   LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(15,19)
   <Peeled>
   LOOP END

   LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(15,19)
      remark #15300: LOOP WAS VECTORIZED
   LOOP END

   LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(15,19)
   <Remainder>
   LOOP END
LOOP END

LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(16,19)
   remark #15542: loop was not vectorized: inner loop was already vectorized

   LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(16,19)
   <Peeled>
   LOOP END

   LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(16,19)
      remark #15300: LOOP WAS VECTORIZED
   LOOP END

   LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(16,19)
   <Remainder>
   LOOP END
LOOP END
```

And also I just wanted to make sure that this is a toy example. People not familiar with parallelization sometimes don't realize that small loops don't benefit from it due to overheads. 

Feel free to get to more realistic examples, and I have a look. Btw. if it is not a classification and/or export control issue we could probably work something out for you to send some code snipped privately, under NDA.

**Comment by crtrott** [comment]
And just to make sure I recompiled the two vector example, and got the same optrpt.

**Comment by mcarilli** [comment]
Hi Christian,

Thank you for replying so quickly once again!  However, I did notice those vectorizations.  They indicate loops are being inlined and vectorized at lines 15 and 16 of vectorization_twoviews.cpp.  Those are the two lines where a and b are declared.  Therefore, I believe that those two (vectorized) loops are the internal loops associated with initializing all elements of a and b to zero.

My actual parallel_for is at line 20.

**Comment by crtrott** [comment]
Oh my bet. Sorry I'll check again.

**Comment by crtrott** [comment]
Hm when I compile your source code it vectorizes:
```
LOOP BEGIN at /home/crtrott/kokkos/core/src/Kokkos_ExecPolicy.hpp(316,8) inlined into main.cpp(20,56)
   remark #15521: loop was not vectorized: loop control variable was not identified. Explicitly compute the iteration count before executing the loop or try using canonical loop form
LOOP END

LOOP BEGIN at /home/crtrott/kokkos/core/src/Kokkos_ExecPolicy.hpp(320,10) inlined into main.cpp(20,56)
   remark #15521: loop was not vectorized: loop control variable was not identified. Explicitly compute the iteration count before executing the loop or try using canonical loop form
LOOP END

LOOP BEGIN at /home/crtrott/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into main.cpp(20,3)
<Peeled loop for vectorization>
LOOP END

LOOP BEGIN at /home/crtrott/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into main.cpp(20,3)
   remark #15300: LOOP WAS VECTORIZED
LOOP END

LOOP BEGIN at /home/crtrott/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into main.cpp(20,3)
<Remainder loop for vectorization>
LOOP END
```

This is with 
```
[crtrott@apollo 2]$ icpc --version
icpc (ICC) 16.0.1 20151021
```

**Comment by mcarilli** [comment]
Hmm, I am able to duplicate that (vectorization succeeds) on my laptop (icpc 16.0.1), but not on my desktop (icpc 15.0.3).  It is also possible that the version of Kokkos on my desktop is out of date, since I didn't clone the repo directly.  I'll pull the latest version and retry

**Comment by crtrott** [comment]
I just checked with intel 15.2 (15.0.2) and it did vectorize as well. Maybe the Kokkos version was just quite a bit out of date and it didn't know that option?

**Comment by mcarilli** [comment]
Good news!  After pulling the latest version of Kokkos on my desktop, and compiling with icpc 15.0.3, vectorization succeeds:
```
LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master2/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(20,3)                                                                                                                                 
<Peeled>
LOOP END
  
LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master2/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(20,3)                                                                                                                                 
   remark #15300: LOOP WAS VECTORIZED
LOOP END

LOOP BEGIN at /home/mcarilli/Desktop/kokkos-master2/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp(86,7) inlined into vectorization_twoviews.cpp(20,3)                                                                                                                                 
<Remainder>
LOOP END
```
I will now write a toy example that is more representative of my application, and you can take a look.
Thanks very much for your help with all of this!

**Comment by mcarilli** [comment]
Hi Jeff and Christian,

I have prepared an example that is more representative of the performance-limiting kernels in my application.  I have experimented with various #pragmas and noted their effects in the cpp file at line 63 and below.  It seems that vectorization over threads is not a huge issue for this kernel; rather, optimizing the inner loops computed by each thread is a higher priority.  I could be wrong though.

[representative.cpp.txt](https://github.com/kokkos/kokkos/files/221849/representative.cpp.txt)
[Makefile.txt](https://github.com/kokkos/kokkos/files/221850/Makefile.txt)

If you are still willing, I'd greatly appreciate you taking a look.

Regards,
Michael

**Comment by crtrott** [comment]
Hi

yeah the aggressive vectorization thing will only effect non-nested loops. For nested loops you typically want the innermost to vectorize. I am glad in this case it happend on its own. That is what I would hope for since all the data is accessed read-only in the loop. One thing I would try is to manually hoist the loads not affected by "j" out of the inner loop. But a good compiler might do that automatically. Otherwise does this mean you are so far happy with what it is doing?

Christian

**Comment by mcarilli** [comment]
Well, I don't know if I should be happy with it or not, that's why I wanted to consult the Kokkos professionals.  It looks like there are several variables for which the load could be hoisted, so I'll try that, but I expect those were already at least hitting in cache, so I may not see a big jump in performance.  I'll try on Monday and tell you how it works.

Anyway, thanks again for your help, you've been great.  Please tell me if there are any other optimizations that occur to you.

**Comment by crtrott** [comment]
I just wrote a little version using Hierarchical Parlallelism. It doesn't help or hurt the CPU (which is what one would hope), but it does speed up the code for the GPU quite a bit. 

[representative.cpp.team.txt](https://github.com/kokkos/kokkos/files/221932/representative.cpp.team.txt)
[Makefile.txt](https://github.com/kokkos/kokkos/files/221934/Makefile.txt)

**Comment by mcarilli** [comment]
I skimmed the code.  Very cool!  I'll take a more in depth look monday,  busy with other things this weekend.

**Comment by mcarilli** [comment]
Hi Christian,

On my desktop, I observe that the hierarchical version is about 10% faster than the non-hierarchical version (with the same loads hoisted).

I am honestly surprised that the reduce version performs better, because the parallel reduce pattern is inherently cost-inefficient:  Near the end, half the threads are idle.  A cooperative pattern is not necessary in this case, since each grid point is independent.  I would expect that letting each thread carry out its own running sum to completion would be faster, since this way, no threads are ever idle.  

Any ideas on why the hierarchical version is faster?

Regards,
Michael

**Comment by crtrott** [comment]
That would need a really careful profiling to answer. I am closing this discussion for now, since we have not written anything in 2 weeks. If you are interested in more analysis feel free to reopen.
