### ISSUE TITLE
atomicMax equivalent (and other atomics)

### ISSUE THREAD

**Issue by ascheinb** [kokkos/kokkos#2401]
Hi all, I'm trying to convert a cuda atomicMax to Kokkos. In general, I see that there are a number of cuda atomics that do not have kokkos equivalents. I think that there is a way to effectively do an atomic max with the available kokkos atomics? In general, it would be nice to have guidance/documentation for the most efficient kokkos equivalent to the various cuda atomics.

**Comment by crtrott** [comment]
Which other ones are you looking for? AtomicMax and Min is certainly one we should add. Probably we should have all of the ones we also support for reducers.

**Comment by ascheinb** [comment]
Those are the only ones I need, and it looks like I can use the atomic CAS to get around it. I also had to convert an atomicInc before, which I replaced with a fetch add. It works fine, I was just thinking it might be nice to have a conversion chart in the docs.

**Comment by crtrott** [comment]
atomic increment should actually be there, but lets make this into a request for min and max.

**Comment by DavidPoliakoff** [comment]
@crtrott, I actually think this is a good idea more generally, cheat sheets for

"I use `Programming Model` and am looking to switch to Kokkos, how do I translate `Feature` into it"

Where `Feature` might be Parallelism Patterns, Data Placement, Atomics... anything else?

**Comment by ascheinb** [comment]
Hello all - Did atomic max and min ever get implemented? I was looking through https://github.com/kokkos/kokkos/wiki/Atomic-Operations and didn't see a way to construct an equivalent to atomic max from the existing listed operations.

**Comment by mhoemmen** [comment]
@ascheinb Here's how Tpetra does atomic `max(abs(x), abs(y))` using `Kokkos::Impl::atomic_fetch_oper`.

**Comment by crtrott** [comment]
@janciesko You wanna do this? Or maybe @jrmadsen ?

**Comment by dalg24** [comment]
@janciesko will look into this
