### ISSUE TITLE
Issue with Makefile.kokkos logic for detecting CUDA

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#2403]
I'm having an issue when building kokkos on gpu with mpicxx compiler. I followed the kokkos guidelines, and kept mpicxx as compiler for my application, declaring `OMPI_CXX=/path/to/nvcc_wrapper`. The problem is now in Makefile.kokkos, when trying to detect if the internal compiler is nvcc. In particular, the makefile uses the following

`KOKKOS_INTERNAL_COMPILER_NVCC        := $(strip $(shell export OMPI_CXX=$(OMPI_CXX); export MPICH_CXX=$(MPICH_CXX); $(CXX) --version 2>&1 | grep nvcc | wc -l))`

to test whether the internal compiler is nvcc:
`
ifeq ($(KOKKOS_INTERNAL_COMPILER_NVCC), 1)
...
endif
`

Unfortunately, when I run `mpicxx --version | grep nvcc`, I get the following:

```
lbertag@waterman11:[kokkos]$ mpicxx --version | grep nvcc
nvcc  -ccbin g++ -arch=sm_35  --version     
nvcc: NVIDIA (R) Cuda compiler driver
```

So `wc -l` returns 2, and the makefile tests fail. A possible fix for me (and it works) would be to test that `wc -l` returns a number greater than 0. E.g., replacing the line above with 

`KOKKOS_INTERNAL_COMPILER_NVCC := $(strip $(shell export OMPI_CXX=$(OMPI_CXX); export MPICH_CXX=$(MPICH_CXX); echo "$(shell $(CXX) --version 2>&1 | grep nvcc | wc -l)  >0" | bc))
`

seems to work in my case.

**Comment by bartgol** [comment]
Update: it appears it was my fault (partly). I set `NVCC_WRAPPER_SHOW_COMMANDS_BEING_RUN=1` earlier while debugging something else, and forgot to disable it. Without that env var defined, everything worked, since 

```
lbertag@waterman11:[kokkos]$ mpicxx --version | grep nvcc
nvcc: NVIDIA (R) Cuda compiler driver
```

However, I wonder if the logic in the makefile should still be modified, so that nobody falls into this (admittedly, corner) scenario in the future.

**Comment by crtrott** [comment]
Hm interesting corner case. We probably should get that fixed since that environment variable exists.

**Comment by bartgol** [comment]
Update: it appears this is gone with the cmake mods in the develop branch. I may be missing something, but I think that Makefile.kokkos is no longer used in the cmake build. Therefore the problem is gone for cmake users. It seems to be still an issue for users relying on generate_makefile.bash though.

I'm personally a cmake user, so I guess I will just use the develop branch (or wait for a promotion). Still, I issues a PR just in case you want to fix it.
