### ISSUE TITLE
error in wrapping user data with Kokkos view...

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#242]
When I wrap 2d array with Kokkos view, I got the following error. Am I doing wrong ? or Kokkos view bug ? 
```
/home/kyukim/Work/lib/trilinos/trunk/packages/intrepid2/src-kokkos/Discretization/Integration/Intrepid2_CubatureDirectLineGaussDef.hpp:72:76: error: no matching function for call to Kokkos::Experimental::View<const double [1001][3], Kokkos::HostSpace>::View(const double [1001][3])
```

**Comment by kyungjoo-kim** [comment]
Adding one more comment with a simple example

i can compile
```
double testData[10];
View<double[10]> testView(testData);
```

I cannot compile
```
double testData[10][3];
View<double[10][3]> testView(testData);
```

Any clue ?

**Comment by hcedwar** [comment]
Because

    double[10] decays to double*

    double[10][3] decays to (double[3])*


________________________________

**Comment by kyungjoo-kim** [comment]
Hi Carter,

Then, how should I change to wrap the 2D data 

Kyungjoo

**Comment by hcedwar** [comment]
double testData[10][3];
    View<double[10][3]> testView( testData[0] );

**Comment by kyungjoo-kim** [comment]
Thank you. I thought that I tried that but apparently I did not. It compiles.

**Comment by crtrott** [comment]
Can I close this?
