### ISSUE TITLE
Incremental Unit test required to validate New Backend Development 

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2424]
Unit tests are currently an "all or nothing" process to confirm that changing integrated into Kokkos do not break or alter current functionality.   Backends that are currently being developed require unit tests that validate each stage as they are complete, but because all of the concepts and policies aren't implemented, they will not be able to run the entire unit test suite.

This issue is intended to address to the need to turn on / run unit tests based on what level of completion a target backend had reached.  It should result in CMake and Make changes that accept options related to staged backend development. 

Additional issues will be opened for each of the incremental tests themselves.

**Comment by jeffmiles63** [comment]
I think maybe we can have an incremental test option where we set a test level to specify how far to go.

e.g. -DKokkos_INCREMENTAL_TEST_LEVEL=100

then each of the tests can be enabled if the test level is greater than the implementation level

#if defined KOKKOS_INCREMENTAL_TEST_LEVEL && KOKKOS_INCREMENTAL_TEST_LEVEL >= KOKKOS_INC_TEST_MEMORY_SPACE_ALLOC
   TEST( TEST_CATEGORY, test_memory_space_allocate ) {
         // test_code
    }
#endif

CMake would only add the test exe for incremental test if level is set, and like wise not create the other tests.

**Comment by DavidPoliakoff** [comment]
I think this is likely the right answer, my only question is whether we can say going forward that capability in Kokkos is strictly ordered. If it will always be `parallel_for` -> `kokkos_malloc` -> `View` (or whatever it might be) then a numbering system makes sense. If instead it's more of a tree shape, things get a little more complicated. Is task support "less than" MDRange? Can we find some ordering that maximally offends people from certain fields of study?

**Comment by janciesko** [comment]
We could do it like this: the modular unit tests (*.hpp) go into a new directory. Cmake finds all hpp files, filters those defined by the implementation level (-DKokkos_OPENMP_ILEVEL=[1…100] maybe) and generates the corresponding cpp file. Make then generates the corresponding binary for the backend. Would that work?

**Comment by janciesko** [comment]
If the unit test files have leading numbers in their file names, with increasing numbers corresponding to increasing dependency level, we could use those numbers to identify which unit tests to run for a given implementation level.

**Comment by Rombur** [comment]
> I think this is likely the right answer, my only question is whether we can say going forward that capability in Kokkos is strictly ordered.

I don't think we can really ordered all the capabilities in Kokkos. For example, we plan to support `parallel_scan` much earlier than in the roadmap because ArborX requires `parallel_scan` but it does not use `Teams`.

**Comment by jeffmiles63** [comment]
So, after some further analysis and some prototyping, I think a good alternative would be to require some type of feature dependency list in the test source (hpp) files.   Here is an example:

```
/// @Kokkos_Feature_Required:ParallelForRangePolicy;KokkosAtomics
```

Through scripts and CMake logic, the source files can be parsed and interrogated to create a list of  tests with a corresponding list of required features.  

Then when the project is configured we can use a backend feature list option to articulate which features are completed.  Here is an example:

```
-DKokkos_HIP_FEATURE_LIST="ExecSpaceInit;MemorySpaceAlloc;ParallelForRangePolicy; KokkosAtomics"
```
With the list of tests and required features, the CMake logic can then filter and build a test executable that matches the features that are completed for the target backend.

Note: We will probably need some additional logic or names for backends that support additional memory spaces.
