### ISSUE TITLE
Add TriBITS/CMake configure information about node types

### ISSUE THREAD

**Issue by rppawlo** [kokkos/kokkos#243]
During a Trilinos tribits/cmake configure, Tpetra prints some very useful information about enabled nodes types and which one is the default:

-- Tpetra execution space availability (ON means available): 
--   - Serial:  OFF
--   - Threads: OFF
--   - OpenMP:  ON
--   - Cuda:    OFF
-- Setting default Node to Kokkos::Compat::KokkosOpenMPWrapperNode.

This exact information would be great to have from the kokkos configure as well for cases where tpetra is not enabled. Could you add message statements to print this information for kokkos during a tribits configure?

**Comment by mhoemmen** [comment]
Per discussion today with @rppawlo, add CMake variable to Kokkos that chooses the default execution space.  Make logic for choosing the default execution space happen in CMake, not in the header file ifdefs.  Make Tpetra use that choice and be consistent with that choice.

**Comment by mhoemmen** [comment]
Per @ambrad 's suggestion, consider memory spaces too.  The default memory space could be set separately from the default execution space.

**Comment by gmackey** [comment]
The original request of printing the configure information is addressed in the pure cmake (but not Tribits) build.  It is currently in my cmake branch and will be pulled in with it.

**Comment by ibaned** [comment]
I think the most recent TriBITS integration with Kokkos CMake seems to satisfy this:
```
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: Cuda
--     Host Parallel: None
--       Host Serial: Serial
--     
-- Architectures:
--     HSW,Pascal61
-- 
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_CUDA
--   KOKKOS_ENABLE_CUDA_LAMBDA
--   KOKKOS_ENABLE_PROFILING
--   
-- Final kokkos settings variable:
--   env;KOKKOS_SRC_PATH=/home/daibane/src/Trilinos/kokkos;KOKKOS_PATH=/home/daibane/src/Trilinos/kokkos;KOKKOS_INSTALL_PATH=/home/daibane/install/nvcc/Trilinos;KOKKOS_ARCH=HSW,Pascal61;KOKKOS_DEVICES=Cuda,Serial;KOKKOS_DEBUG=no;KOKKOS_OPTIONS=disable_deprecated_code,disable_dualview_modify_check;KOKKOS_CUDA_OPTIONS=enable_lambda;CUDA_PATH=;PATH="/bin:/home/daibane/bin:/home/daibane/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daibane/install/gmsh-3.0.4-Linux/bin:/home/daibane/install/ParaView-5.3.0-Qt5-OpenGL2-MPI-Linux-64bit/bin:/usr/local/cuda-9.0/bin:/home/daibane/install/texlive/bin/x86_64-linux"
-- *****************************************************
```
