### ISSUE TITLE
Add PMem Support

### ISSUE THREAD

**Issue by nealepetrillo** [kokkos/kokkos#2434]
With Intel Optane DC Persistent memory becoming more popular, support for running in the "app direct" mode would be nice. Support for libpmemobj, libpmemblk, and libvmemcache would be nice to have in Kokkos. 

More information on this technology can be found here:

https://pmem.io/pmdk/

https://www.intel.com/content/www/us/en/architecture-and-technology/optane-dc-persistent-memory.html

**Comment by crtrott** [comment]
Generally this is in scope to be added as another memory space. To get it correctly prioritized we would need to see a) who is a concrete user interested in this. b) are there systems we want to support which could actually use this. 

External contributions for this could be a way to get it done faster, with us taking over support when its properly done.

**Comment by crtrott** [comment]
@jeffhammond Jeff do you have any thoughts on this, and its usefulness in an Intel OneAPI world?

**Comment by jeffhammond** [comment]
I agree 100% regarding the need for a concrete use case to prioritize.

**Comment by nealepetrillo** [comment]
The technology is going to be available on Aurora (see link below). That seems like a good reference platform. 

I think our target use case is going to revolve around meshing large models and doing in memory data lookups of material databases.

https://newsroom.intel.com/news-releases/u-s-department-energy-intel-deliver-first-exascale-supercomputer/#gs.91qvnf

**Comment by jeffhammond** [comment]
@nealepetrillo Use cases should be outlined in terms of access patterns.  Because Optane memory supports cache mode (to use the KNL language - marketing calls it "memory mode"), it can be used without any code changes.  The usage where you need code changes in Kokkos or wherever is if cache mode isn't going to do what you need.

https://itpeernetwork.intel.com/intel-optane-dc-persistent-memory-operating-modes/

**Comment by nealepetrillo** [comment]
Our rep is saying that version two of the technology is going to operate at DDR speed making the distinction between cache and app direct modes moot. So I'm going to close the request.
