### ISSUE TITLE
Inconsistencies in Kokkos::complex

### ISSUE THREAD

**Issue by dhollman** [kokkos/kokkos#2438]
`Kokkos::complex` is more permissive than `std::complex` in quite a few different ways, though it's not consistent about it. It's also missing some functionality of `std::complex` for no apparent reason.

* `operator==()`, for instance, on `Kokkos::complex` permits implicit conversions, whereas `std::complex` requires the exact same type to be deduced for LHS and RHS. (So Kokkos is more permissive).
* Kokkos doesn't provide `operator+`, etc., between `Kokkos::complex` and a scalar type, even though `std::complex` does (so Kokkos is less permissive).
* `volatile` overloads of `+=` and `*=` are provided, but others are missing (the reason for this is understandable, but AFAICT not documented).

**Comment by mhoemmen** [comment]
I wrote `Kokkos::complex` merely to get Trilinos code to compile way back when.  I didn't want to do it but it's what we had to do.  Please feel welcome to fix what's broken and then to purge it with fire once CUDA gets unbroken ;-) .

**Comment by PhilMiller** [comment]
* Comparisons are allowing implicit conversions, as noted.
* Binary operators between `Kokkos::complex` and scalar types were and are available
* `volatile` overloads are now deprecated.

At this point, I don't feel like there's much to say is broken/deficient, though the allowed conversions is a point of divergence from the current practice that `Kokkos::foo` where there's a C++ `std::foo` should follow the standard specification. Any code that directly uses the standard functionality would behave the same. Code that tries to detect the presence or absence of this functionality would be confused, but that's a pretty universal point of "not a compatibility bug" in C++ libraries.
