### ISSUE TITLE
view.empty ??

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#244]
A interface to see that a view is not initialized might be necessary. For example,
```
Kokkos::View<double*> a;  // this is declared but not yet initialized
a.size(); // this returns 1
a.span(); // this returns 1
```

I need to compare an input view is initialized or not. I can do ....
```
if (a.data() == NULL) { 
   a = View<double*>("i need", 1);
} else {
  do_something(a);
}
```
can I assume that the view always have null pointer ? or can you provide a function to determine the state of a view ? like a.empty() ?

**Comment by crtrott** [comment]
a.data()==NULL is the way to check whether you have an initialized view. (not the deprecated view requires a.ptr_on_device().

**Comment by kyungjoo-kim** [comment]
okay. thanks.

**Comment by hcedwar** [comment]
With

    Kokkos::view<double*> a ;
    assert( a.size() == 0 );
    assert( a.span() == 0 );
    assert( a.data() == NULL );

should all hold.

**Comment by kyungjoo-kim** [comment]
I presumed that the dimension is always initialized with 1 and I did not check the default constructor but I checked the following with Nathan.
```
Kokkos::view<double*> a("a"); // this returns span() = 1
```

**Comment by crtrott** [comment]
Uhm I can't replicate that, for me that returns span() = 0/

**Comment by kyungjoo-kim** [comment]
When I run the following code,
```
      {
        Kokkos::DynRankView<double,DeviceSpaceType> A("A"), B;
        std::cout << " DynRankView testing " << std::endl;
        std::cout << " A.span() = " << A.span() << "  B.span() = " << B.span() << std::endl;
        std::cout << " A.data() = " << A.data() << "  B.data() = " << B.data() << std::endl;
      }
      {
        Kokkos::View<double,DeviceSpaceType> A("A"), B;
        std::cout << " View testing " << std::endl;
        std::cout << " A.span() = " << A.span() << "  B.span() = " << B.span() << std::endl;
        std::cout << " A.data() = " << A.data() << "  B.data() = " << B.data() << std::endl;
        Kokkos::View<double*,DeviceSpaceType> C("C"), D;
        std::cout << " C.span() = " << C.span() << "  D.span() = " << D.span() << std::endl;
        std::cout << " C.data() = " << C.data() << "  D.data() = " << D.data() << std::endl;
      }
```
I got this.
```
 DynRankView testing                                                                                                
 A.span() = 1  B.span() = 0                                                                                         
 A.data() = 0x1a72580  B.data() = 0                                                                                 
 View testing                                                                                                       
 A.span() = 1  B.span() = 1                                                                                         
 A.data() = 0x1a72580  B.data() = 0                                                                                 
 C.span() = 0  D.span() = 0                                                                                         
 C.data() = 0  D.data() = 0  
```

So, when I give a name for the container, it initialize dimensions and the default constructor does nothing. 

For Kokkos::View, it seems to be okay. When the view goes with "double", it allocate for a single value. When the view goes with "double*", data is initialized with null. It seems to be natural. 

For DynRankView, is this expected behavior when the container has a label ? Isn't the behavior similar to when a view with "double*" as DynRankView has base with "double******" ?

**Comment by crtrott** [comment]
This is different. You have a scalar view. That one is expected to have size 1 if you initialize, and 0 if you don't call the constructor. A runtime_rank 1 or higher view would have span 0 if you only give it a name but no length arguments.

**Comment by hcedwar** [comment]
A View type with fully compile-time dimensions will report the compile-time dimensions and span whether it is allocated or not.  To prevent this an `if` test would have to be introduced into each and every dimension and span query, which would hurt performance.  As such the `data() == NULL` should always be used to determine if a `View` views non-null data.

**Comment by ibaned** [comment]
This doesn't seem to hold for zero-sized Views:

```
Kokkos::View<double*> view("name", 0);
view.data() == NULL;
```

Is there any way to reliably distinguish zero-size views from non-allocated ones ? This is useful for algorithms that temporarily have no data on one processor out of many during normal operation.

**Comment by hcedwar** [comment]
Only Views with dynamic dimensions are potentially allocated with zero size.  What is allocated is a header which holds the label but no memory for the zero-size contents.

    Kokkos::View<double*> view("name",0);
    assert( view.size() == 0 && view.data() != NULL );
    // it is invalid to dereference the data() pointer

This will hold true for non-allocated views with dynamic dimensions as well.  However, if you have all static dimensions the story is different:

    Kokkos::View<double[10]> view ;
    assert( view.size() == 10 && view.data() == NULL );

**Comment by ibaned** [comment]
Your code seems to indicate that `view.data() != NULL` for a zero-size view, but that is not what happens in practice (using Kokkos bcaa9c9 Serial). Zero-size views behave as:
```
Kokkos::View<double*> view("name",0);
assert( view.size() == 0 && view.data() == NULL );
```
So to be clear do we expect `view.data()` to be null in this case or not ? If we do expect it to be null in this case, is there any other call I could make, maybe down to the allocation tracker, to tell zero-size views apart from non-allocated ones ?
