### ISSUE TITLE
Cannot access data in another class

### ISSUE THREAD

**Issue by huilinye** [kokkos/kokkos#2440]
I simplify my problem as follows: I have two class, class A and Class B

```c++
Class A{

  typedef Kokkos::View<int*>   View_idx_1d;
  
  View_idx_1d ind;
  
  }
  
  Class B{
  
  typedef Kokkos::View<int**>   View_idx_2d;
  
  View_idx_2d ind2;
  
  void catch();
  
  KOKKOS_INLINE_FUNCTION
  void operator()( const int& i) const{
  
  A->ind(i) = 2;
  
  }
  
  }
```
  
  The catch() function is like:
  
```c++
  {
  ...
  Kokkos::parallel_for(Kokkos::RangePolicy( 0, nmax ),*this);
   execution_space().fence();
   }
```
   
   This works for OpenMP, but when I run this with Cuda, the error happens as:
   
```
   terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/huilin/Kokkos/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:120
Traceback functionality not available
```

I find it is caused by the reference to ind in class A, but I don't know why. Both ind and ind2 are stored in Cuda space, but I cannot access ind?

**Comment by dhollman** [comment]
I'm going to need a little bit more complete example to diagnose the problem here, but there are a few things that could be going wrong.  Is `A` a data member of `B`? (Presumably the data member has a name other than `A`, the name of the type itself?). Are you copying the `ind` member in the copy constructor of `A`? What is the size of `A->ind`? Less than `nmax`?

**Comment by stanmoore1** [comment]
Either A is allocated in CPU host memory that not accessible on the device, or A is not initialized at all. With A as a pointer, I think you would need to do a `placement new` to get the vtable on the device. This can easily work if A is not a pointer and is declared as a data member of class B--then it is automatically captured as part of the `*this` pointer of class B.

**Comment by huilinye** [comment]
> Either A is allocated in CPU host memory that not accessible on the device, or A is not initialized at all. With A as a pointer, I think you would need to do a `placement new` to get the vtable on the device. This can easily work if A is not a pointer and is declared as a data member of class B--then it is automatically captured as part of the `*this` pointer of class B.

A is a pointer, and I have ran successfully in Cuda space without initializing class B. After I add class B and want to manipulate data in class A, the error happens.

**Comment by stanmoore1** [comment]
We are going to need a full example with more details.

**Comment by dhollman** [comment]
If `A` is a pointer, you can't access it on the GPU unless you allocate it on the GPU (e.g., by creating a `Kokkos::View<A>`). Can you give us a more detailed example (i.e., one that actually compiles, or comes close) so we can help you better?

**Comment by huilinye** [comment]
> If `A` is a pointer, you can't access it on the GPU unless you allocate it on the GPU (e.g., by creating a `Kokkos::View<A>`). Can you give us a more detailed example (i.e., one that actually compiles, or comes close) so we can help you better?

The detailed code is too large, I don't think uploading the whole file is a good idea. I find if I create same data ind in class B and use this to accept the data in class A through deep_copy, this problem can be overcome. But Im still confused why I cannot directly use the data...

**Comment by masterleinad** [comment]
@huilinye Can you reduce your code to a minimal example showing the problem? It is really much easier to help you if we have some code to work with.

**Comment by crtrott** [comment]
The example you show can't work since `A->` is not a valid expression (A is your class name) and A is not a member of B. Furthermore in your definition `ind` is a private member of A and thus not accessible outside?

Is the somewhat fixed example this:

```c++
class A {
  public:
    typedef Kokkos::View<int*>   View_idx_1d;
    View_idx_1d ind;
};
  
class B {
  public:
  typedef Kokkos::View<int**>   View_idx_2d;
  View_idx_2d ind2;
  
  void catch();
  
  A* a;
  KOKKOS_INLINE_FUNCTION
  void operator()( const int& i) const {
    a->ind(i) = 2;
  }
};
```

Also what is your error message?
In this case you would need to allocate the storage for `a` in a memory space which is accessible from wherever you want to run the problem.

Or (if `A` isn't large, and mostly just contains Kokkos View you can just store a copy of A in B instead of a pointer.

```c++
class B {
  public:
  typedef Kokkos::View<int**>   View_idx_2d;
  View_idx_2d ind2;
  
  void catch();
  
  A a;
  KOKKOS_INLINE_FUNCTION
  void operator()( const int& i) const {
    a.ind(i) = 2;
  }
};
```

**Comment by huilinye** [comment]
> The example you show can't work since `A->` is not a valid expression (A is your class name) and A is not a member of B. Furthermore in your definition `ind` is a private member of A and thus not accessible outside?
> 
> Is the somewhat fixed example this:
> 
> ```c++
> class A {
>   public:
>     typedef Kokkos::View<int*>   View_idx_1d;
>     View_idx_1d ind;
> };
>   
> class B {
>   public:
>   typedef Kokkos::View<int**>   View_idx_2d;
>   View_idx_2d ind2;
>   
>   void catch();
>   
>   A* a;
>   KOKKOS_INLINE_FUNCTION
>   void operator()( const int& i) const {
>     a->ind(i) = 2;
>   }
> };
> ```
> 
> Also what is your error message?
> In this case you would need to allocate the storage for `a` in a memory space which is accessible from wherever you want to run the problem.
> 
> Or (if `A` isn't large, and mostly just contains Kokkos View you can just store a copy of A in B instead of a pointer.
> 
> ```c++
> class B {
>   public:
>   typedef Kokkos::View<int**>   View_idx_2d;
>   View_idx_2d ind2;
>   
>   void catch();
>   
>   A a;
>   KOKKOS_INLINE_FUNCTION
>   void operator()( const int& i) const {
>     a.ind(i) = 2;
>   }
> };
> ```

Storing a copy of a in B should be a good choice, and it works well. Many thanks for the suggestion. Please feel free to close this issue.
