### ISSUE TITLE
cmake problem: serial space is not enabled even though I set it on.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#2445]
My first attempt was to use ``KOKKOS_ENABLE_SERIAL=ON``. It is so kind that kokkos telss me its cmake changes.
```
  Matching option found for Kokkos_ENABLE_SERIAL with the wrong case
  KOKKOS_ENABLE_SERIAL.  Please delete your CMakeCache.txt and change option
  to -DKokkos_ENABLE_SERIAL=ON.  This is now enforced to avoid hard-to-debug
  CMake cache inconsistencies.
```

So, I configure with ``SET(Kokkos_ENABLE_SERIAL ON)``.  Then,  configuration is done with output
```
-- Execution Spaces:
--   Device Parallel: NONE
--     Host Parallel: OPENMP
--       Host Serial: NONE
```
This does not enable serial host execution space. I double-checked ``KokkosCore_config.h`` and found ``/* #undef KOKKOS_ENABLE_SERIAL */ ``. 

I use kokkos develop branch and something is not correctly harnessed in cmake. 

update
--------
The serial space is enabled if I enable serial space ``-D Kokkos_ENABLE_SERIAL=ON``. What is the difference between ``SET`` and ``-D`` option ? 

@jjwilke

**Comment by dalg24** [comment]
> The serial space is enabled if I enable serial space -D Kokkos_ENABLE_SERIAL=ON. What is the difference between SET and -D option ?

Not sure what you mean by I configure with `SET(Kokkos_ENABLE_SERIAL ON)`.

Passing `-D Kokkos_ENABLE_SERIAL=ON` to cmake is the way to go.

**Comment by dalg24** [comment]
Also if you don't explicitly enable any backend it will enable the Serial backend by default.

**Comment by kyungjoo-kim** [comment]
I am configure kokkos as a submodule of another cmake application. So, I want to set some necessary things by default. The code requires that the serial space needs to be enabled and I often use openmp (optional) together. So, I put SET(Kokkos_ENABLE_SERIAL ON) in the application cmake file. Somehow this does not transfer to kokkos cmake setup. I am wondering if this is intended by kokkos cmake design.

**Comment by jjwilke** [comment]
If you were going to do it this way, you'd have to set it as a cache variable (and possibly force it).
````
SET(Kokkos_ENABLE_SERIAL ON CACHE "" FORCE)
````
It's not recommend to interact with the CMake system this way, though.

**Comment by jjwilke** [comment]
If you MUST have serial backend enable, it's probably better to make sure the configuration is correct.

````
IF (NOT Kokkos_ENABLE_SERIAL)
  MESSAGE(FATAL_ERROR "Project X requires you to configure with -DKokkos_ENABLE_SERIAL=ON)
ENDIF()
````

**Comment by kyungjoo-kim** [comment]
I can add the error message. It might be more clear. FYI: the first option  ``SET(Kokkos_ENABLE_SERIAL ON CACHE "" FORCE)`` does not work.

**Comment by jjwilke** [comment]
Sorry, type-o.
````
SET(Kokkos_ENABLE_SERIAL ON CACHE BOOL "" FORCE)
````

**Comment by kyungjoo-kim** [comment]
Oh... That works~~ Thanks.

**Comment by jjwilke** [comment]
Just for reference in case someone looks at this.  Using `SET` without `CACHE` creates a regular variable. In the function that processes options, it calls `SET(Kokkos_X DEFAULT CACHE BOOL "")`. This sets a default value if none is set. Otherwise it keeps the previously assigned value from `-DKokkos_X`. This nukes any values from pre-existing regular variables.
