### ISSUE TITLE
Add CMake option to select Cuda ARCH automatically

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2455]
When using FIND_PACKAGE(CUDA) CMake will try to detect the arch compile option when the CUDA_SELECT_NVCC_ARCH_FLAGS(CUDA_ARCH) command is invoked.

This request is to add a Kokkos /CMake option to invoke this command to select the ARCH needed for the active execution environment.  i.e. set Kokkos_ENABLE_${CUDA_ARCH} from command above.

Important note: This is not expected to work if the execution node has a different configuration than the compilation node.

**Comment by jjwilke** [comment]
I think the main problem is going to be login nodes. Cross-compiling would break this. In general, you're much safer if people assert the configuration you want. 

In a few cases, we could at the very least warn. I would guess, though, we don't want customers in the habit of relying on Kokkos to automatically select how to build?

@crtrott @dalg24

**Comment by lkersting** [comment]
The [CUDA_SELECT_NVCC_ARCH_FLAGS](https://cmake.org/cmake/help/v3.7/module/FindCUDA.html) function also allows you to specify the desired arch:

> CUDA_SELECT_NVCC_ARCH_FLAGS(out_variable [target_CUDA_architectures])
-- Selects GPU arch flags for nvcc based on target_CUDA_architectures
   target_CUDA_architectures : Auto | Common | All | LIST(ARCH_AND_PTX ...)
    - "Auto" detects local machine GPU compute arch at runtime.
    - "Common" and "All" cover common and entire subsets of architectures
   ARCH_AND_PTX : NAME | NUM.NUM | NUM.NUM(NUM.NUM) | NUM.NUM+PTX
   NAME: Fermi Kepler Maxwell Kepler+Tegra Kepler+Tesla Maxwell+Tegra Pascal
   NUM: Any number. Only those pairs are currently accepted by NVCC though:
         2.0 2.1 3.0 3.2 3.5 3.7 5.0 5.2 5.3 6.0 6.2
   Returns LIST of flags to be added to CUDA_NVCC_FLAGS in ${out_variable}
   Additionally, sets ${out_variable}_readable to the resulting numeric list
   Example:
    CUDA_SELECT_NVCC_ARCH_FLAGS(ARCH_FLAGS 3.0 3.5+PTX 5.2(5.0) Maxwell)
     LIST(APPEND CUDA_NVCC_FLAGS ${ARCH_FLAGS})

If no arch is specified than it will try and auto detect the arch. Kokkos could still allow the customer to manually set the Kokkos arch and add the capability to auto-detect the arch if none is specified (and cuda is enabled).

**Comment by jjwilke** [comment]
Sorry, I didn't read this carefully enough. You meant only for CUDA. For CUDA, this is probably okay.  I could use the function to find the highest supported ARCH and use that as the default.

**Comment by jjwilke** [comment]
I might have been convinced to put this in sooner than later. It is pretty easy to forget to add a CUDA architecture.  For the Clang build, this leads to compiler errors, not configure errors. We should definitely never have configure errors show up as compiler errors. Something needs to get added.

**Comment by jjwilke** [comment]
Adding to my monologue: another possibility for us is to embed build information and check it during `Kokkos::initialize()`. During initialize, there are no cross-compiling or architecture detection issues. We could then check the build flags against the architecture actually being run on and issue warnings about potentially sub-optimal build configurations.

**Comment by masterleinad** [comment]
Do we want this for the release? I would be rather hesitant to include even more things last minute we need to verify to work correctly unless it's absolutely crucial.

**Comment by jjwilke** [comment]
I think this should probably be post-release. And we should discuss exactly how this should work. I think this is generally going to be important, though. It is probably unrealistic for us to expect average users to know what architecture they're running on.

**Comment by crtrott** [comment]
Note: we are still doing cross compile fairly frequently (i.e. we compile on head nodes without GPUs and then run on the GPU nodes). That said using the auto detecting mechanism if the architecture was not set is probably ok. And if that fails we should error out of the configure.

**Comment by dalg24** [comment]
Cross-referencing #2639

**Comment by masterleinad** [comment]
Fixed in #2980.
