### ISSUE TITLE
Disabling/controlling padding?

### ISSUE THREAD

**Issue by ascheinb** [kokkos/kokkos#2456]
Hello,

I'm trying to send a multi-dimensional Fortran array on the host to a Kokkos view on device.

For single-dimensional arrays, I wrap my fortran array in an unmanaged kokkos view and do a deep copy from it, like so:

```
extern "C" void update_E(int E_size, double *E_from_fortran_code)
{
    typedef Kokkos::View<double*,Kokkos::LayoutLeft, ExSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> double_view;
    double_view E_from_fortran_view(E_from_fortran_code, E_size);
    Kokkos::deep_copy(E_on_device, E_from_fortran_view);
}
```

where E_on_device is a Kokkos view defined elsewhere: `Kokkos::View<double*,Device> E_on_device;`

Let's say the array is 2D. The iso c binding will reshape the array to be 1D, but I should still be able to wrap the appropriate unmanaged kokkos view. I can figure out later whether to force layout left or right, but what I understand less is the padding. I know that padding has to be the same for a deep copy to work. So I'm worried that this will not necessarily work:

```
extern "C" void update_E(int E_size_dim1, int E_size_dim2, double *E_from_fortran_code)
{
    typedef Kokkos::View<double**,Kokkos::LayoutLeft, ExSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> double_view_2D;
    double_view_2D E_from_fortran_view(E_from_fortran_code, E_size_dim1, E_size_dim2);
    Kokkos::deep_copy(E_on_device, E_from_fortran_view);
}
```

where E_on_device is now 2D: `Kokkos::View<double**,Device> E_on_device;`

At least in the short term, the easy solution would be to ensure that both the unmanaged host View and the managed device View are not padded. Is there an option for that? Is there an easier/more correct way?

**Comment by crtrott** [comment]
Padding is by default off. But the correct way to do this is to create a mirror_view in a specific space:

https://github.com/kokkos/kokkos/wiki/Kokkos%3A%3Acreate_mirror

```c++
extern "C" void update_E(int E_size_dim1, int E_size_dim2, double *E_from_fortran_code)
{
    typedef Kokkos::View<double**,Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> double_view_2D;
    double_view_2D E_from_fortran_view(E_from_fortran_code, E_size_dim1, E_size_dim2);
    auto E_on_device = Kokkos::create_mirror_view(Device(),E_from_fortran_view);
    Kokkos::deep_copy(E_on_device, E_from_fortran_view);
}
```

Also you should check out the fortran interop library we are introducing: https://github.com/kokkos/kokkos-fortran-interop

It actually provides officially supported capabilities to do all of this stuff. 
@womeld Geoff could help you further, he is in charge of that.

**Comment by ascheinb** [comment]
Thanks!

**Comment by PhilMiller** [comment]
Question was answered.
