### ISSUE TITLE
Add GCC 4.8.4 testing to Pull Requests testing. 

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2461]

**Comment by dhollman** [comment]
This is a start, but I think we really need a staged approach: as much as we can reasonably do in CI tests, and then an automated process that promotes to the working copy when nightlies pass.  I'd suggest using `develop` for the former and `master` for the latter (and just doing releases as tarballs like everyone else does), but I suppose if that's a problem we could do something like `develop` and `stable` or `predevelop` and `develop`.

**Comment by ndellingwood** [comment]
Should automated Trilinos testing be considered part of the staged approach?

**Comment by dhollman** [comment]
I don't know, maybe. Possibly in a separate stage, since it's more extensive than our nightlies (correct?).

**Comment by masterleinad** [comment]
Is there any chance to make the results of the nightlies public?

**Comment by dalg24** [comment]
No backend explicitly enabled ok?

**Comment by crtrott** [comment]
OpenMP would be good.

**Comment by ndellingwood** [comment]
@masterleinad 

> Is there any chance to make the results of the nightlies public?

The dashboard that our Jenkins nightlies report to requires permissions for access and I'm not certain what availability there is for non-Sandians, I'll look into this and get back to you if there is a way to access.
