### ISSUE TITLE
query MPI context better

### ISSUE THREAD

**Issue by jeffhammond** [kokkos/kokkos#2478]
You have three instances of the same pattern:
* https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Core.cpp#L101
* https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_CPUDiscovery.cpp#L88
* https://github.com/kokkos/kokkos/blob/develop/example/multi_fem/ParallelMachine.cpp#L82

I don't care what you do in examples but [Kokkos_Core.cpp](https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Core.cpp#L101) should use `Kokkos::Impl:: mpi_ranks_per_node()` and/or `Kokkos::Impl::mpi_local_rank_on_node` instead of reinventing the wheel.

Regardless of how many times or where you do it, the right way to query the local MPI environment is `MPI_Comm_split_type` but that means you have a dependency on MPI that you don't want.  At the very least, you should support other MPI libraries.

I will try to work on this, but would like feedback from @crtrott or other authority on the MPI library aspect before proceeding with refactoring the implementation.

**Comment by crtrott** [comment]
I really don't want a dependency on MPI. Technically this is more of a convenience thing anyway. It would be better for people to explicitly tell Kokkos initialize which device to use after they initialized MPI. That said,  I know how convenience crutches become often the defacto standard. I put it on the agenda for our next meeting and see what other people think.

**Comment by PhilMiller** [comment]
@dalg24 @crtrott This hole was dug deeper in #5525

**Comment by jeffhammond** [comment]
> I really don't want a dependency on MPI.

There is `dlopen` if you want to make MPI optional.

**Comment by jeffhammond** [comment]
Have you tried this with MPI_Comm_spawn?

How about MPI-4 sessions, which was driven into MPI by LANL, among others?

What happens when someone uses Kokkos Remote Spaces and the NVSHMEM back end?

**Comment by jeffhammond** [comment]
My point was that this method will be incorrect in the context dynamic process management, and anything like it.  Your users might not care, but it's not portable.

**Comment by dalg24** [comment]
Were you willing to explore the dlopen route?

**Comment by jeffhammond** [comment]
well, i just spent a month writing a dlopen wrapper for everything in MPI so i certainly know how to do it (https://github.com/jeffhammond/mukautuva/blob/main/libinit.c).

if you are interested in going the dlopen route here, i can work on it later.  probably April.
