### ISSUE TITLE
Documentation on View passing

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2482]
On the Slack somebody was asking whether passing a View by value (like a pointer) was the right thing to do, he'd heard somewhere that it was the standard practice. I looked through our docs here (https://github.com/kokkos/kokkos/wiki/View ) and didn't really see a mention, other than an oblique callout that it's a reference counted object.

It would be nice to get some consensus on the team as to best practices, and then update the docs. Once a consensus is reached I'd be happy to update the docs, I just don't want to write it down before we know all the caveats

**Comment by DavidPoliakoff** [comment]
From @crtrott it sounds rather like the guidance is "when it's first captured by Kokkos, capture it by value. Once it's inside Kokkos both capture semantics and how they're passed is difficult to give consistently good advice for, we 've seen either be more performant."

**Comment by mhoemmen** [comment]
Other than "capture by value in a kernel," we could just say it behaves like `std::shared_ptr` and refer users to advice about how to pass that around.

**Comment by crtrott** [comment]
Btw. on CUDA inside the kernel forwarding via references is usually as good and sometimes better than by value. There are almost no cases where in CUDA forwarding by value helps. On CPU builds that is not true, because passing stuff on by reference can in effect create more "pointer like" objects which confuse vectorizers regarding aliasing.

**Comment by ajpowelsnl** [comment]
@crtrott , @dalg24 - we will review the documentation for a Kokkos::View to make sure that it conforms to key concepts and correct usage.  We decided to close this issue, because we're not entirely certain this issue is still a question.
