### ISSUE TITLE
find_package(CUDA) ignoring CUDA_ROOT

### ISSUE THREAD

**Issue by bartlettroscoe** [kokkos/kokkos#2483]
While doing a configure of Trilinos I just noticed the warning:

```
CMake Warning (dev) at packages/kokkos/cmake/kokkos_options.cmake:353 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable CUDA_ROOT is set to:

    /home/projects/ppc64le-pwr9-nvidia/cuda/9.2.88

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/ProjectCompilerPostConfig.cmake:40 (include)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1952 (INCLUDE)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:192 (TRIBITS_SETUP_ENV)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

I think you can fix this by calling:

```
CMAKE_POLICY(SET CMP0003 NEW)
```

or

```
CMAKE_POLICY(SET CMP0003 OLD)
```

in the file `kokkos/cmake/kokkos_options.cmake` before this command.

The question is, do we want `find_package(<PackageName>)` to respond to `<PackageName>_ROOT` env vars?

**Comment by bartlettroscoe** [comment]
FYI: This was the ATDM Trilinos build `cuda-9.2-rdc-opt-dbg` on waterman.  One can reproduce as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

**Comment by masterleinad** [comment]
There is no file `kokkos_options.cmake` in the `develop` branch. Are you referring to `master`?

There is currently a pull request (https://github.com/kokkos/kokkos/pull/2467) that overhauls TPL detection. Does your comment also apply after that patch is applied?

**Comment by jjwilke** [comment]
This is fixed in develop. We explicitly set that policy.

**Comment by bartlettroscoe** [comment]
> This is fixed in develop. We explicitly set that policy.

Okay, I will close.  Thanks!
