### ISSUE TITLE
documentation of case-sensitive CMake options need fixing

### ISSUE THREAD

**Issue by jeffhammond** [kokkos/kokkos#2486]
https://github.com/kokkos/kokkos/wiki/Compiling#table-41-configuration-macros shows e.g. `KOKKOS_ENABLE_CUDA` but when I use it, it fails like this:
```
$ cmake .. -DKOKKOS_ENABLE_CUDA=True
-- Setting default Kokkos CXX standard to 11
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
CMake Error at cmake/kokkos_functions.cmake:49 (MESSAGE):
  Matching option found for Kokkos_ENABLE_CUDA with the wrong case
  KOKKOS_ENABLE_CUDA.  Please delete your CMakeCache.txt and change option to
  -DKokkos_ENABLE_CUDA=True.  This is now enforced to avoid hard-to-debug
  CMake cache inconsistencies.
```

Please make the documentation consistent with what the build system requires.

**Comment by crtrott** [comment]
Was this on develop?

Christian

**Comment by jeffhammond** [comment]
Yes

**Comment by crtrott** [comment]
The build system changes with the next release. The updated documentation for develop is found in the develop branch as BUILD.md. The wiki will be updated with the release.

**Comment by jjwilke** [comment]
@crtrott Do you want me to update the wiki? And if so, when? And if so, should I make separate pages for 2.9 and 3.0?

**Comment by crtrott** [comment]
@jjwilke You can make the updates on the private wiki (ProgrammingGuide repo) and then we merge it with the release.

**Comment by janciesko** [comment]
Changes made accordingly.

**Comment by masterleinad** [comment]
> Changes made accordingly.

Hmm... On that page, there are still a number of places that are not up-to-date with the new build system. In particular, we don't mention the overhauled `CMake` build system at all (only building `Kokkos` as part of `Trilinos`). Also the list of execution spaces changed.

**Comment by dalg24** [comment]
@masterleinad You probably didn't look at the right place.  The changes are staged [here](https://github.com/kokkos/ProgrammingGuide/wiki/BUILD) before it is synched with the wiki on the main repo.

**Comment by masterleinad** [comment]
I was looking [here](https://github.com/kokkos/ProgrammingGuide/wiki/Compiling) since this is the page this pull request initially linked to. I think we should just merge the two pages.

**Comment by masterleinad** [comment]
But the `BUILD` page looks pretty nice indeed.
