### ISSUE TITLE
Drop support for CUDA 7 and CUDA 8

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#2489]
We decided to drop support for CUDA 7 and CUDA 8. This requires changes to 
- `cmake/kokkos_compiler_id.cmake`, 
- `README.md`, 
- `scripts/testing_scripts/test_all_sandia`
- `scripts/testing_scripts/cm_test_all_sandia`

**Comment by ndellingwood** [comment]
I put in PR #2490 for the first 3 items - @jeffmiles63 can you update the `cm_test_all_sandia` script? I didn't want to alter it in case you are actively making changes.

**Comment by ndellingwood** [comment]
PR #2495 completed the `cm_test_all_sandia` changes, all 4 items now addressed.
