### ISSUE TITLE
Trilinos interaction with C++ standard

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2496]
Trilinos only has options for C++11. In addition, it does this by explicitly setting flags. This is not going to mix well with `target_compile_features`, which is the way C++ standard flags are supposed to be chosen. The main effect is that the compiler gets multiple C++ standard flags. One comes from `target_compile_features` and the other comes from Trilinos explicitly setting `-std=c++11`. In most cases this does nothing. For `nvcc_wrapper`, this produces a warning about multiple flags.

There are no good options here without changing Trilinos. This mainly has to do with feature macros. If we define, e.g. `KOKKOS_ENABLE_CXX14` in the config header then we need to make sure that `-std=c++14` is forced on downstream projects by using `target_compile_features`. If we force `-std` flags via `target_compile_features`, we will get warnings about multiple `-std` flags. And should Trilinos builds of Kokkos even allow C++14 and above?

**Comment by DavidPoliakoff** [comment]
@jjwilke, can we allow an external builder to either

1) Force the use of a standard
2) Force Kokkos not to set a standard flag, and rely on the external building project to specify it

I honestly am more of a fan of (2), I don't like Kokkos being in the business of supporting a weird build configuration any more than it has to be, letting external packages say "I'll handle it" seems a little less odious. (Note: I assume Trilinos does some variant of the `add_subdirectory(kokkos)` idiom, otherwise we need (1))

**Comment by jjwilke** [comment]
Either option is *possible* in CMake.  The problem here is that if you configure with `Kokkos_CXX_STANDARD=X` then the code (config header) is hardwired.  Any Kokkos project MUST at least have the `-std=c++X` flag or it will fail to compile. We want to keep the simple rule that `target_link_libraries(lib Kokkos::kokkos)` provides all the flags needed for both a *correct* and *performant* build.  

I think (1) has to be the way we do things. The question is whether we build in a special exception for Trilinos to allow (2) for that one case? Or we make Trilinos change if it wants to get rid of all the `nvcc_wrapper` warnings?

**Comment by jjwilke** [comment]
@bartlettroscoe 
Related to: https://github.com/TriBITSPub/TriBITS/issues/127

Right now, TriBITS does:
````
IF (${PROJECT_NAME}_ENABLE_CXX AND ${PROJECT_NAME}_ENABLE_CXX11)
   SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${${PROJECT_NAME}_CXX11_FLAGS}")
````
and globally sets `CMAKE_CXX_FLAGS` in TribitsGlobalMacros. I am wondering if it would make more sense for us to rip this out and just put in `TribitsLibraryMacros` the following:
````
ADD_LIBRARY(${LIBRARY_NAME} ...)
...
IF (${PROJECT_NAME}_ENABLE_CXX)
  IF (${PROJECT_NAME}_ENABLE_CXX11)
    TARGET_COMPILE_FEATURES(${LIBRARY_NAME} cxx_std_11)
  ELSEIF(${PROJECT_NAME}_ENABLE_CXX14)
  ....
  ENDIF()
ENDIF()
````

**Comment by bartlettroscoe** [comment]
@jjwilke and @DavidPoliakoff, I believe that the Trilinos build completely bypasses this and just uses whatever compiler flags that Kokkos provides.   See:

* https://github.com/trilinos/Trilinos/blob/bad567f3ff8531134b0fbbdc1dafff594567cd00/cmake/ProjectCompilerPostConfig.cmake#L103
* https://tribits.org/doc/TribitsBuildReference.html#enabling-support-for-c-11

Therefore, I don't think there is a problem here, is there?

And yes, TriBITS needs to get out of the business of dealing with compiler settings and  TriBITSPub/TriBITS#127 is part of that.

**Comment by jjwilke** [comment]
@bartlettroscoe Thanks for the response.  There is a line:
````
  IF (NOT KOKKOS_ARCH STREQUAL "None")
````
and a comment
````
  # Above, It is important not to distrube the default configuraiton of
  # Trilinos if KOKKOS_ARCH is not set.
````
both attributed to you that makes it NOT clear `Trilinos_CXX11_FLAGS` unless `KOKKOS_ARCH` is set. Do you remember the rationale for this?

@ibaned A lot of the `ProjectCompilerPostConfig.cmake` is also attributed to you. Possibly you remember why there is the `IF (KOKKOS_ARCH)`?

**Comment by bartlettroscoe** [comment]
> Do you remember the rationale for this?

@jjwilke, it was to avoid breaking existing configurations that were not using `KOKKOS_ARCH`.  This logic basically guaranteed we would not break existing configurations.

I fear that if we remove this if logic then it will break some existing configurations. However, if you think the risk is low (or that changes will be easy for users to absorb) then let's try removing that IF() statement and just always using the Kokkos configuration stuff if that makes you job easier.

**Comment by jjwilke** [comment]
@bartlettroscoe Sounds good. I will just remove it. I'm already prepared for 3 months of hate mail once we promote!
