### ISSUE TITLE
Configure and install nvcc_wrapper

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2497]
Based on #2474, @jjwilke mentioned

```
This is probably as much as we want to change for 3.0.

I believe the right way to do this for 3.1 is to have nvcc_wrapper be different when installed. Have an nvcc_wrapper.in that during configure writes the underlying gcc, nvcc, and valid flags/features into the compiler script. All downstream projects MUST use an installed nvcc_wrapper.

The way this works is then:

    If building Kokkos, Kokkos sets environment variables during CMake configure time that tells the nvcc_wrapper to accept and translate certain flags
    If building downstream, an installed nvcc_wrapper has the information on what flags to accept and translate embedded into it.

```

@crtrott disagreed, saying

```
I don't like the idea of installing a different nvcc_wrapper. Generally I would love to get rid of nvcc_wrapper at some point, but until then I want it to be the minimal logic to fix deficiencies in NVCC and its interaction with CMake.
```

I think Jeremy has a great point here, we insulate ourselves from the environment, which is something I approve of, though I don't know if it's in line with the Sandia mentality about how to use a system

**Comment by crtrott** [comment]
@DavidPoliakoff Sandia as far as I can tell usually doesn't want to build huge constructs of "we isolate ourselves from the system". Basically in the minds of loads of folks here this tends to lead to writing stacks of fragile scripts which works as long as you are in on the tribal knowledge of how to use them, but which don't align with any other peoples machines and then break if your use case doesn't look like what is typically done at the institution.

**Comment by PhilMiller** [comment]
I think we can close this as WontFix?
