### ISSUE TITLE
Taking a subview of non-zero length from a zero-length view should fail

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#250]
The following code runs right now:
```C++
Kokkos::View<double*> a;
auto b = Kokkos::subview(a,std::make_pair(0,10));
```
It also returns 10 as both the span and the dimension_0, while returning 0 for the memory_span. 
I believe this should fail at runtime (or alternatively return a view of length 0).

**Comment by hcedwar** [comment]
This code should fail when bounds checking is configured.  The only way to fail or return length zero is to always perform bounds checking for all subview operations, which was removed to improve performance of subview operations within parallel kernels.
