### ISSUE TITLE
HPX tests fail for view_layoutstride_right_to_layoutleft_assignment

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2500]
The issue appears to be where abort is called in Kokkos_ViewMapping: 
```C++
    if (!assignable_layout)
      Kokkos::abort("View assignment must have compatible layouts\n"); 
```
Test Error is here.

```C++
[ RUN      ] hpx.view_layoutstride_right_to_layoutleft_assignment
view_layoutstride_right_to_layoutleft_assignment: srand(1571874330)
/home/jsmiles/Development/spot-check-apollo/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:676: Failure
Death test: { dst = src; }
    Result: died but not with expected error.
  Expected: View assignment must have compatible layouts
Actual msg:
[  DEATH   ] terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
[  DEATH   ]   what():  <unknown>: HPX(network_error)
[  DEATH   ] 
[  FAILED  ] hpx.view_layoutstride_right_to_layoutleft_assignment (648 ms)
[ RUN      ] hpx.view_layoutstride_left_to_layoutright_assignment
view_layoutstride_left_to_layoutright_assignment: srand(1571874330)
/home/jsmiles/Development/spot-check-apollo/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:827: Failure
Death test: { dst = src; } 
    Result: died but not with expected error.
  Expected: View assignment must have compatible layouts
Actual msg:
[  DEATH   ] terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
[  DEATH   ]   what():  <unknown>: HPX(network_error)
[  DEATH   ] 
[  FAILED  ] hpx.view_layoutstride_left_to_layoutright_assignment (127 ms)
```

**Comment by DavidPoliakoff** [comment]
@jeffmiles63 does any other test pass, or do all/most fail with that same networking exception? I know HPX used to be a little picky about how jobs launch and such

**Comment by masterleinad** [comment]
Hmm... for me all the HPX tests pass. In particular, `UnitTest` `view_layoutstride_right_to_layoutleft_assignment` is part of succeeds.

**Comment by msimberg** [comment]
What version of HPX is this using? Have you changed the way tests are launched? HPX used to not like having multiple instances running on the same node, which means that `make -jN test` didn't work and typically lead to an error message like that. That has changed on master (I'll have to go digging to see if it was before or after 1.3.0 was released) and *should* work but you never know... I'd be happy to have a look at this with some more details.

**Comment by jeffmiles63** [comment]
apollo is using hpx/1.2.1 with gcc/6.1.0

These tests were working about a month ago.

**Comment by masterleinad** [comment]
I am using hpx/1.3.0 and gcc/7.4.0.

**Comment by jeffmiles63** [comment]
I'm guessing the multiple instances are because the gtest ASSERT_DEATH has to use a fork?

**Comment by masterleinad** [comment]
Likely, we were having a similar problem in #2471 with `CUDA`.

**Comment by masterleinad** [comment]
Of course, it would be good to see if we can get the tests pass for 1.2.1 as well. Since `HPX` support is still experimental, I would not let this block the release (in particular if version 1.3.0 also works for you), though.

**Comment by msimberg** [comment]
If you can't change the test, the only way to get this working with 1.2.1 is to configure HPX with `HPX_WITH_NETWORKING=OFF`, unfortunately. From our side requiring 1.3.0 for the HPX backend would be perfectly fine as well.

**Comment by jeffmiles63** [comment]
As stated above, this appears to only be an issue with the 1.2.1 version.  We have since updated the spot checks to use the 1.3.0 version, so this is no longer an issue of concern
