### ISSUE TITLE
Revise test-pass criteria for TestCuda_DebugSerialExecution and TestCuda_DebugPinUVMSpace

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2506]
New unit tests added in `TestCuda_DebugPinUVMSpace.cpp` by #2481 and `TestCuda_DebugSerialExecution.cpp` in #2479 rely on timing results to establish PASS/FAIL of the unit test.
The CI test failure in PR #2502 of the `TestCuda_DebugSerialExecution` indicates that there is potentially enough noise in the timing results that the existing time-comparison is not a reliable measure for PASS/FAIL. At a minimum there should output of the times upon failure.

**Comment by bartlettroscoe** [comment]
Yea, it is unreliable to use timings on a loading machine as a basis for pass/fail.

**Comment by ndellingwood** [comment]
This is preventing clang+cuda debug builds passing and has been randomly occurred in Trilinos tests.

**Comment by ndellingwood** [comment]
@crtrott this one fell off the radar, for the 3.1 release could the `ASSERT_TRUE` check based on timing results be removed and simply print the results, until a more robust test can be added not relying on timing results?

**Comment by ndellingwood** [comment]
Cross-referencing https://github.com/trilinos/Trilinos/issues/6799#issuecomment-603921412

**Comment by ndellingwood** [comment]
I'll add the 3.1 milestone for now, others will readjust if necessary.

**Comment by dalg24** [comment]
Feel free to re-open if that is still an issue.
