### ISSUE TITLE
HostMirror behavior for CudaUVM space

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2512]
In numerous places downstream, code like the following is used to get the host execution space:

````
typedef typename Kokkos::View<int*, device_type>::HostMirror::execution_space host_exec;
````
Under recent typedef changes, if the input `device_type` gives a view with `CudaUVM` space then `HostMirror` is also `CudaUVM` and `host_exec` typedefs to the default execution space for `CudaUVM`, which is `Cuda`.

Code expecting to have a host exec space now fails to build with difficult to parse lambda or other errors.

**Comment by jjwilke** [comment]
Related to issue #2062

**Comment by mhoemmen** [comment]
I'll register my objection here that it's a reasonable expectation for the HostMirror's execution space to be a host execution space.

**Comment by jjwilke** [comment]
@mhoemmen Objection sustained. We are reverting to `HostMirror::execution_space` being a host execution space.

**Comment by mhoemmen** [comment]
@kddevin @trilinos/tpetra @csiefer2 FYI
