### ISSUE TITLE
Cuda::fence on default stream does cudaStreamSynchronize (not cudaDeviceSynchronize) when deprecated code is disabled; this may be bad

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#2517]
When deprecated code is enabled in Kokkos, `Kokkos::Cuda::fence` calls `cudaDeviceSynchronize` (via `impl_static_fence`).  When deprecated code is disabled, `Kokkos::Cuda::fence` calls `m_space_instance->fence()`, which calls `cudaStreamSynchronize` on Kokkos' CUDA singleton's stream.  The latter behavior can cause the following issues when deprecated code is disabled:

1. If users are using multiple streams, `Kokkos::fence()` no longer synchronizes all the streams.
2. @jewatkins observes that the implementation of UVM itself (even when not using `nvprof`) appears to use multiple streams.  See https://github.com/trilinos/Trilinos/issues/6079 .  This might also explain why `Kokkos::fence` and `CUDA_LAUNCH_BLOCKING` have been observed to have different behavior.

Users have been expecting `Kokkos::fence()` to fence everything.  (2) above means that even when using Kokkos' default CUDA stream, UVM might be subverting this expectation.

@vbrunini

**Comment by mhoemmen** [comment]
To quote @jewatkins : "Not sure how UVM works but I'm pretty sure I've seen multiple streams being used for memory transfer in the profiler."

**Comment by jewatkins** [comment]
I noticed UVM uses multiple streams with the profiler and we've been disabling deprecated code

**Comment by mhoemmen** [comment]
@kddevin @csiefer2 @jhux2 may be interested in this too.

**Comment by crtrott** [comment]
Cuda::fence doesn't exist anymore ... Cuda().fence() does exist and fences the default stream. But the default stream (if you don't ask CUDA not do that) is synchronized with all other streams. Thus Cuda().fence() will synchronize all outstanding streams ...

Test code: 
```c++
#include<Kokkos_Core.hpp>
#include<cmath>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
    int N = argc>1?atoi(argv[1]):1000000;
    int R = argc>2?atoi(argv[2]):10;
    cudaStream_t stream1,stream2;
    cudaStreamCreate(&stream1);
    cudaStreamCreate(&stream2);

    Kokkos::Cuda cuda1(stream1);
    Kokkos::Cuda cuda2(stream2);
    Kokkos::View<double**> a("A",N,R);
    Kokkos::fence();
    {
    Kokkos::Timer timer;
    Kokkos::parallel_for(Kokkos::RangePolicy<>(cuda1,0,N), KOKKOS_LAMBDA(const int i) {
      for(int j=0;j<R;j++)
        a(i,j) = i*100+j;
    });
    double time1 = timer.seconds();
    cuda1.fence();
    double time2 = timer.seconds();

    printf("cuda1.fence(): %e %e\n",time1,time2);
    }
    {
    Kokkos::Timer timer;
    Kokkos::parallel_for(Kokkos::RangePolicy<>(cuda1,0,N), KOKKOS_LAMBDA(const int i) {
      for(int j=0;j<R;j++)
        a(i,j) = i*100+j;
    });
    double time1 = timer.seconds();
    Kokkos::Cuda().fence();
    double time2 = timer.seconds();

    printf("Cuda().fence(): %e %e\n",time1,time2);
    }
    {
    Kokkos::Timer timer;
    Kokkos::parallel_for(Kokkos::RangePolicy<>(cuda1,0,N), KOKKOS_LAMBDA(const int i) {
      for(int j=0;j<R;j++)
        a(i,j) = i*100+j;
    });
    double time1 = timer.seconds();
    Kokkos::fence();
    double time2 = timer.seconds();

    printf("Kokkos::fence(): %e %e\n",time1,time2);
    }
    {
    Kokkos::Timer timer;
    Kokkos::parallel_for(Kokkos::RangePolicy<>(cuda1,0,N), KOKKOS_LAMBDA(const int i) {
      for(int j=0;j<R;j++)
        a(i,j) = i*100+j;
    });
    double time1 = timer.seconds();
    cuda2.fence();
    double time2 = timer.seconds();

    printf("cuda2.fence(): %e %e\n",time1,time2);
    }
  }
  Kokkos::finalize();
}
```

output:
```
cuda1.fence(): 1.169400e-05 1.081140e-04
Cuda().fence(): 7.502000e-06 1.046280e-04
Kokkos::fence(): 6.420000e-06 1.033210e-04
cuda2.fence(): 6.606000e-06 8.326000e-06
```

**Comment by brian-kelley** [comment]
@crtrott Assuming user streams aren't used, is there a definitive guide for when exec_space().fence() is necessary (generally, not just Cuda)? I know it prevents host and device from accessing the same UVM view simultaneously. My understanding is that it's otherwise not necessary to fence between any two kernel launches/deep_copies since every backend guarantees those are sequenced, is that correct?

**Comment by crtrott** [comment]
That is correct. Kernels, allocations, deallocations and deep_copies submitted into the same execution space instance are sequenced. They work like CUDA streams.

**Comment by crtrott** [comment]
deep_copy, allocations and deallocations also fence with the host, unless you use the asynchronous overloads which take an execution space instance.

**Comment by mhoemmen** [comment]
One of the things we're trying to understand is why `CUDA_LAUNCH_BLOCKING` seems to do something different than `Cuda().fence()`.  Is it because `CUDA_LAUNCH_BLOCKING` calls `cudaDeviceSynchronize` (does it?), but `Cuda().fence()` calls `cudaStreamSynchronize`?

**Comment by crtrott** [comment]
But Trilinos didn't turn deprecated code off by default so you always had cudaDeviceSynchronize in those experiments.

**Comment by mhoemmen** [comment]
Right, but EMPIRE or SPARC may turn off deprecated code by default.  Anyway, I'm not saying this is bad or the cause of the issue, just that it's a thing.

**Comment by crtrott** [comment]
EMPIRE doesn't build yet with deprecated code off since Panzer doesn't work I believe.
