### ISSUE TITLE
clang-cuda -std flags incorrect for newer clang

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2520]
Clang 9 default is c++14. If you request:
````
target_compile_features(target PUBLIC cxx_std_14)
````
CMake does NOT add the `-std=c++14` flag because it is "redundant".

Clang 9 CUDA default is c++98 (-x cuda changes the default C++ standard).
Because we configure everything as a CXX project and not a CUDA project, 
CMake thinks it doesn't need to add the flags.

This now creates the error where even though we want C++14, CMake is not adding `-std=c++14` and the whole `-x cuda` compile crashes.

**Comment by dalg24** [comment]
Just out of curiosity, are you using the LLVM 9.0.0 release?  What CUDA version?

**Comment by jjwilke** [comment]
It's not specific to a compiler or CUDA version. LLVM 9 release. I'm not sure on the exact CUDA. This was an issue someone else was having. 

This is an issue entirely with CMake (and our particular use of CMake in which we build CUDA projects as C++). Any compiler (Clang 8,9,10 or GCC 7,8,9) for which the default C++ is higher than 98 will break on CMake >= 3.14.
