### ISSUE TITLE
Missing DeepCopy instrumentation in Kokkos

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2522]
Turns out we never call the instrumentation hooks for DeepCopy inside of our deep_copy function ...

**Comment by stanmoore1** [comment]
https://github.com/kokkos/kokkos-tools/issues/49

**Comment by crtrott** [comment]
Turns out someone did notice it but we ignored the tools issue :-(

**Comment by crtrott** [comment]
Anyway PR for fix is issued.
