### ISSUE TITLE
Kokkos_INCLUDE_DIRS Not Properly Set in KokkosConfig.cmake

### ISSUE THREAD

**Issue by lkersting** [kokkos/kokkos#2524]
Currently `Kokkos_INCLUDE_DIRS` is set to `@CONF_INCLUDE_DIRS@` in the KokkosConfig.cmake.in file. However `CONF_INCLUDE_DIRS` is never set. 

Anyone trying to use find_package(Kokkos) will be given an empty list for `Kokkos_INCLUDE_DIRS`. This variable should either be eliminated is not needed or properly set.

**Comment by lkersting** [comment]
Looks like you have a similar problem for `Kokkos_LIBRARY_DIRS` being set to `@INSTALL_LIB_DIR@` which is never set.

**Comment by dalg24** [comment]
@lkersting we decided to drop these variables rather than fix them (cf #2535).  Users are expected to use the `Kokkos::kokkos` target instead.

**Comment by jjwilke** [comment]
These are deleted.  If the user really wants them in CMake land, then they should grab target properties from `kokkoscore`.
