### ISSUE TITLE
Add Alias with Namespace Kokkos:: to Interal Libraries

### ISSUE THREAD

**Issue by lkersting** [kokkos/kokkos#2530]
Current the internal libraries (e.g. `kokkos`,  `kokkoscore`, `kokkoscontainers`, etc.) do not have an alias with the Kokkos namespace (e.g. `Kokkos::kokkos`, `Kokkos::kokkoscore`, `Kokkos::kokkoscontainers`, etc.), but the installed libraries do have the Kokkos namespace.

CMake best practices would be to add an alias to the internal libraries so that all codes reference the Kokkos libraries in the same way (e.g. `Kokkos::kokkos`) independent on if they are linking to an installed version of Kokkos via `find_package(Kokkos)` or including Kokkos as a sub directory in their build.

**Comment by masterleinad** [comment]
@lkersting Can you confirm that #2550 works for you?

**Comment by lkersting** [comment]
Yes, these changes fixed the problem. Thanks
