### ISSUE TITLE
Compressed storage Layout via ZFP

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#254]
From: <Miller>, Mark Miller miller86@llnl.gov
Date: Tuesday, April 19, 2016 at 5:57 PM
Subject: Possibility of Compressed Array Storage in Kokkos

I am writing because I have been using a new compression capability, ZFP, in Silo (think of Silo as sort of Livermore's Exodus) and getting some great results with it.

http://computation.llnl.gov/projects/floating-point-compression/zfp-compression-ratio-and-quality

I have cc'd the researcher who developed ZFP, Peter Lindstrom, here.

Among many great features, ZFP supports high-performance, random access to compressed arrays in memory.

It occurred to me that the marriage of ZFP and Kokkos Array classes could really be something very powerful.

I know that Peter has looked at supporting ZFP compressed arrays on GPUs too.

Anyways, I wanted to introduce you to Peter and suggest that it might be worth having a short dialog with him about integrating ZFP with Kokkos.

If it winds up looking promising, I would love to hear about where it finally leads.

Mark

**Comment by ibaned** [comment]
I just found out `zfp` is a lossy compression system...

**Comment by mhoemmen** [comment]
@ibaned Right, but ZFP is more or less still a block random access layout, in principle not much different than Kokkos::DynamicView.

**Comment by ajpowelsnl** [comment]
Reopen if there's interest.

**Comment by Char-Aznable** [comment]
I am interested in something like this as well. It looks like ZFP already has OpenMP and CUDA support

**Comment by ajpowelsnl** [comment]
Morning @crtrott and @dalg24 -- Would there be interest in integrating ZFP functionality into Kokkos?
