### ISSUE TITLE
StdThread execution space with intances

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#255]
A new execution space for CPU architectures is required to support distributed asynchronous many-tasking (AMT) functionality use of Kokkos.  The new  execution space will provide execution space instances that map to non-overlapping subsets of the hardware threads.  An AMT layer will dispatch tasks to execution space instances such that those tasks have internal parallelism over the associated hardware threads.
The new `StdThread` execution space will use C++11 `std::thread` for hardware threads in contrast to the current `Threads` execution space use of `pthreads`.

**Comment by hcedwar** [comment]
- This will require a minimum of gcc v4.8 for complete std::thread functionality, other compiler versions TBD.
- Internal design separates and layers the instance information (size, which hardware threads, synchronization support) from the hardware thread information.
- At initialization a "whole node" instance is created and then the application or AMT layer can partition this "whole node" instance into smaller instances.  Analogous to initializing and splitting MPI_COMM_WORLD.

**Comment by hcedwar** [comment]
Concern that split functionality is currently incompatible with OpenMP capability.

**Comment by hcedwar** [comment]
Minimal implementation conforming to design (issue #457 and [rough design notes](https://github.com/kokkos/kokkos/blob/develop/doc/design_notes_space_instances.md)) 

Unit test:

- Request threads > 1  instance of which the `main` control thread is a member
- `parallel_for` on that instance
- Request default instance from the `main` control thread, must be the same instance
- Relinquish instances
- Request default instance form the `main` control thread, should contain only the instance

**Comment by hcedwar** [comment]
DARMA needs the abstraction and API to be mappable onto other lightweight threading packages such as Charm++ CTH-threads, Qthreads, etc.

**Comment by dsunder** [comment]
We need to expose the  "control thread" concept

- The thread running main is a control thread
- A control thread has ownership over resources and can launch parallel algorithms
- Control threads interact with the resource manager to acquire resources
- Kokkos::initialize/finalize must be called from each control thread
- To change the control thread resources, Kokkos must be finalized and re-initalized on the control thread
- Kokkos::fence will only fence resources initialized by the calling control thread (i.e. other control threads and their resources are unaffected)

Cuda specific:
- A control thread will interact with a (singular) device
- Multi-GPU support requires multiple control threads
- We need to adjust how we use constant memory when using streams and/or multi-gpis
- Constant memory symbols are global, but each context manages their own constant memory  ( cudaGetSymbolAddress )

**Comment by hcedwar** [comment]
When release to master branch will be named `Kokkos::Threads` in source code.
Must also address build system references to `pthread`.

**Comment by dsunder** [comment]
std thread backend work moved to new issue
