### ISSUE TITLE
nvcc_wrapper taking first -std option is counterintuitive

### ISSUE THREAD

**Issue by mdmosby** [kokkos/kokkos#2553]
The nvcc_wrapper script only uses the first specified `-std` option which is counter to most compiler behavior of 'last one wins' with duplicate options.

**Comment by dalg24** [comment]
This was brought up at the developer meeting.  We agree that this is counterintuitive and are open to change the behavior.

**Comment by mdmosby** [comment]
Great! Please let me know if I need to provide any additional information.

**Comment by jjwilke** [comment]
We are working to address this. For reference, can you give a bit more detail on how you configured such that you ended up with two `-std` flags?

**Comment by mdmosby** [comment]
I am experimenting with a new library in SNL’s Sierra engineering code and it needed to compile certain files with –std=c++14. The build system just appended it to the build line for the relevant objects. As every other compiler we use takes the last conflicting option, this is not an issue.

**Comment by jjwilke** [comment]
Is this CMake? Or Makefiles?

**Comment by mdmosby** [comment]
The Sierra build system uses bjam to construct make/ninja files. The behavior of the build system is to append compiler options whenever they are different from the defaults, e.g., specified on the command line.

**Comment by ndellingwood** [comment]
Looks like this was addressed by PR #2580
