### ISSUE TITLE
Missing memory fence for scatter view contribute

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2565]
On Blake (SKX cluster) we had scatter view tests fail with Intel 19 compiler. The failure was due to the result not being in the expected precision. Adding a printf in there seemed to fix the issue. I believe the issue is that we use now proper relaxed atomics in the scatter view using atomic mode. Which means that before we do the contribute step we need a memory fence. I am adding the memory_fence to Kokkos::fence() and then call Kokkos::fence() for now. We may consider calling the ExecSpace().fence(), but currently that is not safe, in case the scatter view was filled in a different execution space instance. So we need to do a full fence for the contribute.

**Comment by crtrott** [comment]
Note the likelyhood of this surfacing is only large with high number of threads.

**Comment by dhollman** [comment]
> Note the likelyhood of this surfacing is only large with high number of threads.

Or with a highly relaxed memory model, like on Power or ARM. Note that this bug should never show up on X86 AFAICT, so if SKX is the issue this solution doesn't make a whole lot of sense.

**Comment by crtrott** [comment]
@dhollman You are right it doesn't make much sense :-(

**Comment by ndellingwood** [comment]
Removing the BLOCKSPROMOTION label as this has been moved to 3.1 release.

**Comment by crtrott** [comment]
Also it relates to a change which was reverted ...
