### ISSUE TITLE
List of Catchable Antipatterns in Kokkos

### ISSUE THREAD

**Issue by calewis** [kokkos/kokkos#2579]
This is an initial list of things we want a compiler tool to at least check for and maybe fix automatically in projects using Kokkos. 

- [ ] Implicit ```this``` capture in ```parallel_for```
  - [X] Detected when parallel_for takes a lambda using implicit this capture
  - [X] Avoid detection when one of the arguments to the parellel_for is a ```TeamThreadRange```
  - [ ] Other exceptions? @dhollman? 
  - [ ] Harden for general use, for example ensure that ```parallel_for```  is located in the ```Kokkos``` namespace and is not a different ```parallel_for```, also ensure that it works with named lambda instead of temporary ones. 
- [ ] User configurable warning on capture by value or capture by reference for specific types
- [ ] Ensure that functor in ```parallel_{scan,reduce}``` takes the reduction argument by reference.

**Comment by crtrott** [comment]
Hierarchical parallelism:
- catch writeback to local variable captured by reference in the inner scope. 
```c++
auto a = KOKKOS_LAMBDA (const TeamPolicy<>::member_type& team) {
  int a;
  Kokkos::parallel_for(Kokkos::TeamThreadRange(team,N), [&] (const int i) {
     a += i; // would compile but our semantics don't allow it
  });
}
```

**Comment by crtrott** [comment]
Hierarchical parallelism:
* catch non-collective allocation of scratch views:

```c++
auto team_lambda = KOKKOS_LAMBDA (const TeamPolicy<>::member_type& team) {
  shared_view_type a;
  if(team.team_rank()<5) {
    // This is not allowed since all team_members must have 
    // agree on state of the scratch memory ptr.
    a = shared_view_type(team.thread_scratch(0),K);
  } 
};

**Comment by calewis** [comment]
> Hierarchical parallelism:
> 
>     * catch writeback to local variable captured by reference in the inner scope.
> 
> 
> ```c++
> auto team_lambda = KOKKOS_LAMBDA (const TeamPolicy<>::member_type& team) {
>   int a;
>   Kokkos::parallel_for(Kokkos::TeamThreadRange(team,N), [&] (const int i) {
>      a += i; // would compile but our semantics don't allow it
>   });
> }
> ```

```cpp
#include <Kokkos_Core.hpp>
#include <cstdio>

using TeamMember = Kokkos::TeamPolicy<>::member_type;

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  printf("Hello World on Kokkos execution space %s\n",
         typeid(Kokkos::DefaultExecutionSpace).name());

  Kokkos::parallel_for(
      Kokkos::TeamPolicy<>(3, 45), KOKKOS_LAMBDA(TeamMember const& team) {
        int a = 0;
        Kokkos::parallel_for(Kokkos::TeamThreadRange(team, 30), [&](int i) {
          a += i;
          printf("a = %i, i = %i\n", a, i);
        });
      });

  // You must call finalize() after you are done using Kokkos.
  Kokkos::finalize();
}
```
@crtrott @DavidPoliakoff @dhollman, is this a suitable example for the quoted test?  Under what circumstances would the inner ```parallel_for``` be allowed to modify ```a```?

**Comment by calewis** [comment]
I have made some progress on the nested parallelism reference capture issue. Given the following code we expect 4 warnings:
```cpp
#include <Kokkos_Core.hpp>

using TeamMember = Kokkos::TeamPolicy<>::member_type;

auto TTR(TeamMember const& t, int size)
    -> decltype(Kokkos::TeamThreadRange(t, size)) {
  return Kokkos::TeamThreadRange(t, size);
}

KOKKOS_FUNCTION void modify_int(int&);
KOKKOS_FUNCTION void do_not_modify_int(int const&);

auto TPolicy = Kokkos::TeamPolicy<>(3, 45);

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);

  {
    Kokkos::View<int> cv("Hi");

    // Base case
    Kokkos::parallel_for(
        TPolicy, KOKKOS_LAMBDA(TeamMember const& t) {
          int a = 0;

          Kokkos::parallel_for(TTR(t, 30), [&](int i) {
            a += 1;
            cv() += 1;
          });
        });

    // One with variable Lambda
    Kokkos::parallel_for(
        TPolicy, KOKKOS_LAMBDA(TeamMember const& t) {
          int b       = 0;
          auto lambda = [&](int i) {
            b += 1;
            cv() += 1;
          };
          Kokkos::parallel_for(TTR(t, 30), lambda);
        });

    // One with variable TeamThreadRange
    Kokkos::parallel_for(
        TPolicy, KOKKOS_LAMBDA(TeamMember const& t) {
          int c             = 0;
          auto thread_range = TTR(t, 30);
          Kokkos::parallel_for(thread_range, [&](int i) {
            c += 1;
            cv() += 1;
          });
        });

    // One with bad opaque function call
    Kokkos::parallel_for(
        TPolicy, KOKKOS_LAMBDA(TeamMember const& t) {
          int d = 0;
          Kokkos::parallel_for(TTR(t, 30), [&](int i) {
            modify_int(d);
            cv() += 1;
          });
        });

    // One with okay opaque function call
    Kokkos::parallel_for(
        TPolicy, KOKKOS_LAMBDA(TeamMember const& t) {
          int e = 0;
          Kokkos::parallel_for(TTR(t, 30), [&](int i) {
            do_not_modify_int(e);
            cv() += 1;
          });
        });
  }

  Kokkos::finalize();
}
```
And the results that I now get are: 
```sh
4 warnings generated.
hello_world_lambda.cpp:26:44: warning: Lambda capture modifies reference capture variable 'a' that is a local [kokkos-KokkosNestedParallelWriteToLocalCheck]
          Kokkos::parallel_for(TTR(t, 30), [&](int i) {
                                           ^
hello_world_lambda.cpp:36:25: warning: Lambda capture modifies reference capture variable 'b' that is a local [kokkos-KokkosNestedParallelWriteToLocalCheck]
          auto lambda = [&](int i) {
                        ^
hello_world_lambda.cpp:48:46: warning: Lambda capture modifies reference capture variable 'c' that is a local [kokkos-KokkosNestedParallelWriteToLocalCheck]
          Kokkos::parallel_for(thread_range, [&](int i) {
                                             ^
hello_world_lambda.cpp:58:44: warning: Lambda capture modifies reference capture variable 'd' that is a local [kokkos-KokkosNestedParallelWriteToLocalCheck]
          Kokkos::parallel_for(TTR(t, 30), [&](int i) {
```
None of the writes to `cv` are warnings.  @crtrott @DavidPoliakoff does this look good to y'all, or am I missing some important examples?

**Comment by DavidPoliakoff** [comment]
Another antipattern, via Matt Bettencourt: apparently it's possible for a View to be constructed with a bad number of arguments. Like, you could initialize a `View<double**>` with just one size argument. If this is still true, it's an antipattern, perhaps best phrased by "the number of dimensions of the view must be equal to the number of size arguments passed to its constructor"

**Comment by stanmoore1** [comment]
>it's possible for a View to be constructed with a bad number of arguments. Like, you could initialize a View<double**> with just one size argument

This has bit me as well.

**Comment by calewis** [comment]
@DavidPoliakoff and @stanmoore1 according to @dhollman this will be a compiler error in future versions of `View` that depend on mdspan, but we might still want a check for it to 1. make the error more human readable and 2. catch it in older versions of Kokkos.

**Comment by DavidPoliakoff** [comment]
I think it's worth putting the check together, if nothing else it will be a template for future checks on View construction

**Comment by ndellingwood** [comment]
> Another antipattern, via Matt Bettencourt: apparently it's possible for a View to be constructed with a bad number of arguments. Like, you could initialize a `View<double**>` with just one size argument. If this is still true, it's an antipattern, perhaps best phrased by "the number of dimensions of the view must be equal to the number of size arguments passed to its constructor"

@DavidPoliakoff not sure if this is a useful addition to the conversation since it sounds like the goal is to make this a compile-time check, but this is checked at runtime when deprecated code is disabled by `runtime_check_rank_host` and `runtime_check_rank_device` routines in View ctors, function definitions are here for these routines https://github.com/kokkos/kokkos/blob/a1997613cf05a8a35c32224293a24df0c59f2e6d/core/src/Kokkos_View.hpp#L95-L150  (they do nothing when deprecated code is enabled)

**Comment by ndellingwood** [comment]
Adding @etphipp in case he's interested in following this thread.

**Comment by etphipp** [comment]
Can I ask what "Avoid detection when one of the arguments to the parellel_for is a TeamThreadRange" means with regards to implict this capture in the opening post?  Is capturing this allowed for a TeamThreadRange parallel_for?

**Comment by calewis** [comment]
@etphipp, my understanding is that yes capturing this is allowed in that context, but other more knowledgeable people should provide a proper answer, such as @dhollman.

**Comment by dhollman** [comment]
@etphipp Yes, that's fine. In fact, a `parallel_for` (e.g.) over a `TeamThreadRange` kernel can capture everything by reference if you want, not just data members.

**Comment by dhollman** [comment]
Here's one that's not on the list yet, but we've talked about several times:

This should be flagged, since the second parameter is not a reference:

```c++
Kokkos::parallel_reduce(n,
  KOKKOS_LAMBDA (int i, double out) {
    out += i;
  },
  result
);
```

Common false positive (though even in this case it doesn't hurt the user to make the parameter a reference, so maybe there's no need to try and exclude this case):

```c++
struct MyRefType {
  double* value_ptr;
  // ...
};
// ...
Kokkos::parallel_reduce(n,
  KOKKOS_LAMBDA (int i, MyRefType out) {
    *out.value_ptr += i;
  },
  result
);
```

(Maybe we want to explicitly exclude the case where the reduction is over an array, which results in a pointer parameter—see wiki for how this is done.)

**Comment by etphipp** [comment]
> @etphipp Yes, that's fine. In fact, a `parallel_for` (e.g.) over a `TeamThreadRange` kernel can capture everything by reference if you want, not just data members.

Is this because it is a capture by reference, i.e., capturing *this by reference is not an issue?

**Comment by mhoemmen** [comment]
@dhollman wrote:
> This should be flagged, since the second parameter is not a reference:

Why does Kokkos even let this compile?  Is it because `parallel_reduce` could, in theory, take a proxy reference type there instead of an actual reference type `T&`?

**Comment by dhollman** [comment]
Yes. Also, making this not compile is...complicated, messy, and ill-advised. There are a few tricks you can do to make this into a (horribly unreadable) compilation error, but (at least until we have static reflection) most of those tricks are a really bad idea because they make things like generic lambdas and function templates not work with `parallel_reduce`.  Even with concepts in C++20, it's very hard to constrain the *signature* of a callable—you can only really constrain what you're allowed to call it with.  `void foo(double)` and `void bar(double&)` can both be called with a `double` lvalue, so for the most part they both meet the requirements of the same concepts.  You have to do something like assert that the callable *can't* be called with an rvalue, which is doable (but messy) in C++20, and doable but _really_ not a great idea in pre-C++20.

That said, once we merge the detection idiom stuff, I should be able to add a static assertion that checks this without too much gross metaprogramming (and hopefully without any additional constraints on the user).

**Comment by vbrunini** [comment]
To start with, thanks for working on this and sharing the current version, it's got a ton of potential. Now for the bug reports/feature requests :)

1. The warning about calling things not marked with `KOKKOS_FUNCTION` inside a `KOKKOS_FUNCTION` seems to only work when the function is called from a parallel region in the current translation unit. For example:
```
double not_a_kokkos_function() { return 5.; }
KOKKOS_FUNCTION double is_a_kokkos_function()
{
  return 2.*not_a_kokkos_function(); // I'd like a warning here no matter what
}
```
does not give the warning right now, but adding:
```
void test()
{
  Kokkos::View<double *> a("a", 10000);
  Kokkos::parallel_for(10000,
    KOKKOS_LAMBDA(int i)
    {
      a(i) = is_a_kokkos_function();
    });
}
```
makes the warning appear.

2. Catching improperly marked lambdas and/or functors being passed to parallel regions would be nice.
```
struct MyFunctor
{
  void operator()(int i) const
  {
    printf("test");
  }
}
void test()
{
  Kokkos::parallel_for(100, [&](int i) { return 0.; });
  Kokkos::parallel_for(100, MyFunctor{});
}
```
does not warn on either right now.

3. The nested parallelism reference capture warning doesn't work when inside an uninstantiated template.
```
template <typename F>
void test(F f)
{
  Kokkos::View<double **> a("a", 10000);
  Kokkos::parallel_for(Kokkos::TeamPolicy<>(10000, 32),
    KOKKOS_LAMBDA(Kokkos::TeamPolicy<>::member_type team)
    {
      int i = team.league_rank();
      Kokkos::parallel_for(Kokkos::TeamThreadRange(team, 0, 64),
        [&](const int j)
      {
        i++; // no warning here
        f(i, j);
      });
  });
}
```
Adding a call to the function template gets the warning to appear, but for using clangd to get the warnings while editing code in a header file there often isn't an instantiation present. I suspect this issue applies to several of the other warnings as well, I only tested the reference capture one.

4. There isn't a warning when declaring a vector inside a parallel region, this (or more generally declaring any type that does memory allocation/isn't allowed on the GPU) would be really useful to detect for porting existing code in particular.

```
void test3()
{
  Kokkos::View<double *> a("a", 10000);
  Kokkos::parallel_for(10000,
    KOKKOS_LAMBDA(int i)
    {
      std::vector<double> vec(5, 0.); // no warning here
      a(i) = vec[3]; // or here for calling a non-KOKKOS_FUNCTION
    });
}
```

**Comment by mhoemmen** [comment]
@vbrunini Regarding the first issue, I'm wondering if the inlining pass is taking care of the unmarked function for you.  I have a vague recollection that device lambdas somehow don't partake of the full inlining pass goodness, but I haven't studied this problem seriously.

**Comment by DavidPoliakoff** [comment]
@mhoemmen , we should be coming in before any inlining happens. Not 100% sure, but it definitely happens later in Clang's pipeline than where we are here

**Comment by DavidPoliakoff** [comment]
Oh, yeah, looking at it, the issue is really that we look inside Kokkos parallel for's for something that is called but isn't marked KOKKOS_FUNCTION. Victor is asking for anything inside a KOKKOS_FUNCTION that isn't marked KOKKOS_FUNCTION to be picked up.

**Comment by vbrunini** [comment]
@mhoemmen I have definitely seen inlining make the code work in cuda when you call a function that isn't marked before, but I think that's a separate issue from wanting the tool to warn me when I've done that and it just happens to work because of inlining.

**Comment by DavidPoliakoff** [comment]
On 3, I remember this being a huge problem, and the easiest way to solve it being "have a test that instantiates that template included in the build clangd is doing," but I remember there being ways of handling it otherwise... Drew and I will discuss it

**Comment by DavidPoliakoff** [comment]
On 4, good catch. We're looking for _captures_ of `std` namespaced objects, when we should just be looking for uses and/or constructions of those objects

**Comment by vbrunini** [comment]
> On 3, I remember this being a huge problem, and the easiest way to solve it being "have a test that instantiates that template included in the build clangd is doing," but I remember there being ways of handling it otherwise... Drew and I will discuss it

Yeah, I can totally understand this being hard, but it would be a big win for at least my use case. We have most of our actually parallel_for/reduce/etc calls implemented in function templates to handle different mesh iteration patterns, with the actual work to be done as a template parameter. So they're basically all in header files and the instantiations are in the various translation units that call the function. I would really love for clangd to show me the warnings when I'm editing the header file, and that is basically guaranteed not to have an instantiation of the template function in it.

**Comment by DavidPoliakoff** [comment]
@vbrunini : definitely, that comment wasn't "hahano," it was "Drew and I will talk about what needs to happen."

**Comment by calewis** [comment]
@vbrunini we will be able to do some of the things that you want, but are actually moving away from one of the things you have requested in the following snippet:

```c++
void test3()
{
  Kokkos::View<double *> a("a", 10000);
  Kokkos::parallel_for(10000,
    KOKKOS_LAMBDA(int i)
    {
      std::vector<double> vec(5, 0.); // no warning here
      a(i) = vec[3]; // or here for calling a non-KOKKOS_FUNCTION
    });
}
```
The check to detect `std` containers needs to polished and then we will detect the first issue in this code.  

Going forward I think we have decided not to warn on the second issue.  We had a discussion on slack about this, but there are too many functions that are legal but are not annotated such as `printf` or `std::abs` we still intend to catch calls to functions that are not annotated, but only when they don't come from system headers.  This is still open to discussion, but the amount of functions that are not annotated, but are still legal seemed too large to maintain a list of exceptions. So `vector::operator[]` will get caught up in this.

**Comment by calewis** [comment]
```cpp
template <typename F>
void test(F f)
{
  Kokkos::View<double **> a("a", 10000);
  Kokkos::parallel_for(Kokkos::TeamPolicy<>(10000, 32),
    KOKKOS_LAMBDA(Kokkos::TeamPolicy<>::member_type team)
    {
      int i = team.league_rank();
      Kokkos::parallel_for(Kokkos::TeamThreadRange(team, 0, 64),
        [&](const int j)
      {
        i++; // no warning here
        f(i, j);
      });
  });
}
```
This comment is mostly for me to document how to fix this at a later date, but I'll try to explain why this fails based on https://godbolt.org/z/vJB3fj

The current check recursively steps through the bodies of functions that are arguments to call expressions (which in this case means we would recurse through the `parallel_for` looking for declrefexpressions to local variables) if we hit a call expression with no body, which happens when the call to `parallel_for` is type dependent, we stop recursing.  In the example from godbolt we hit the following:
```
`-CallExpr <line:23:7, line:26:8> '<dependent type>'
        -UnresolvedLookupExpr <line:23:7> '<overloaded function type>' lvalue (ADL) = 'do_a_kokkos'
```
Given that we have special knowledge of what the `::Kokkos::parallel_x` functions do I think we can just specialize the check for these cases to avoid recursion and to look into the callable directly.

**Comment by calewis** [comment]
```cpp
double not_a_kokkos_function() { return 5.; }
KOKKOS_FUNCTION double is_a_kokkos_function()
{
  return 2.*not_a_kokkos_function(); // I'd like a warning here no matter what
}
```

This currently can't happen, but with some modifications to Kokkos we could do this.  At the moment we don't have a way to match on functions that are annotated with `KOKKOS_FUNCTION`, but I think this use case is a good argument for that (given the caveat I mentioned above about system headers).  It requires that we modify the definition of `KOKKOS_FUNCTION` to be detectable when running clang-tidy though so will require users to get a newer version of Kokkos.

**Comment by vbrunini** [comment]
> Going forward I think we have decided not to warn on the second issue. We had a discussion on slack about this, but there are too many functions that are legal but are not annotated such as `printf` or `std::abs` we still intend to catch calls to functions that are not annotated, but only when they don't come from system headers. This is still open to discussion, but the amount of functions that are not annotated, but are still legal seemed too large to maintain a list of exceptions. So `vector::operator[]` will get caught up in this.

I can live with that tradeoff. Use of the standard containers is the most common place we run into issues so as long as the tool can catch both lambda capture of those, as well as construction inside the body or a KOKKOS_FUNCTION that's probably good enough.

**Comment by vbrunini** [comment]
Another false positive I just ran into, a parallel for with an explicit host execution space shouldn't warn about implicit this capture or use of non-KOKKOS_FUNCTIONS.

**Comment by calewis** [comment]
@vbrunini and @DavidPoliakoff I have just pushed an update to the beta branch of kokkos clang  that fixes warnings for the following two situations: 
```cpp
KOKKOS_FUNCTION void do_something(int i, int j) {
  // You should no longer get a warning for functions declared in headers that 
  // were marked system headers at compile time. 
  printf("Hello{%i} from j = %i\n", i, j); 
}
```
and 
```cpp
struct GoodClass {
  int foo;

  KOKKOS_INLINE_FUNCTION GoodClass(int f) : foo(f) {}
  KOKKOS_INLINE_FUNCTION void method() {
    Kokkos::parallel_for(
        // We now detect when Kokkos::DefaultHostExecutionSpace is explicitly used and 
        // don't warn about implicit this in this specific case.  Eventually though I plan to make this
        // a run time option only for Kokkos::DefaultHostExecutionSpace
        Kokkos::RangePolicy<Kokkos::DefaultHostExecutionSpace>(0, 42),
        KOKKOS_LAMBDA(int i) { do_something(foo, i); });
  }
};
```
But unfortunately this one is harder so isn't currently handled
```cpp
struct GoodClass2 {
  int foo;

  KOKKOS_INLINE_FUNCTION GoodClass2(int f) : foo(f) {}
  KOKKOS_INLINE_FUNCTION void method() {
    auto RP = Kokkos::RangePolicy<Kokkos::DefaultHostExecutionSpace>(0, 42);
    Kokkos::parallel_for( Call to parallel_for implicitly captures this.
        // At this point we no longer have the sugared type of the template parameter to
        // Kokkos::RangePolicy.  Instead we only have things like Kokkos::Serial or Kokkos::Cuda
        // So the detection can't be done at the parallel_for call site. 
        RP, 
        KOKKOS_LAMBDA(int i) { do_something(foo, i); });
  }
};
```
I think this failing case can eventually be fixed by finding where RP gets constructed and inspecting that expression, but that will take some more work.

**Comment by calewis** [comment]
@vbrunini when you say explicit host space how explicit are you being.  Like don't warn if `Kokkos::OpenMP` is used or don't warn if `Kokkos::DefaultHostExecutionSpace`? The second one is actually easier in some sense than the first, which is why I ask.

**Comment by vbrunini** [comment]
I think the most common usage for us is:
```
// In some header
namespace MyNS
{
using HostSpace = Kokkos::HostSpace;
}

// Wherever the parallel_for is (another header or .cpp file)
Kokkos::parallel_for(Kokkos::RangePolicy<MyNS::HostSpace>(...), ...);
```
so I'd find the tool being able to both look through typedefs and handle the mapping from memory space or device to execution space. I do also think not warning on any of the specific host execution space variants in addition to the defaults would be useful.

**Comment by calewis** [comment]
This is pretty hard to do if the Policy isn't a temporary passed into the `parallel_x` function.  The reason being that if you stored the policy in a variable, then at the call site we will only be able to see something like (for `auto RP = Kokkos::RangePolicy<Kokkos::DefaultHostExecutionSpace>`) :
```
`-DeclRefExpr 0x89102a0 'class Kokkos::RangePolicy<class Kokkos::Serial>':'class 
    Kokkos::RangePolicy<class Kokkos::Serial>' lvalue Var 0x88f1b78 'RP' 'class
    Kokkos::RangePolicy<class Kokkos::Serial>':'class Kokkos::RangePolicy<class Kokkos::Serial>'
```

If you promise to only pass in temporaries we could potentially detect the typedef though, or if you are very careful to always give us a nearby initialization.  But in general we can't always see that something like `Kokkos::Serial` came from the host space typedef.

**Comment by vbrunini** [comment]
The policy being a temporary in the parallel_for call is the 90% case where this comes up so if you can handle that I can definitely live with using nolint on the remaining false positives.

**Comment by calewis** [comment]
@vbrunini 
> I do also think not warning on any of the specific host execution space variants in addition to the defaults would be useful.

Unless we can consistently detect that the user intentionally specified a host space then we can't do this. Because it might not be possible to tell the difference between a host space and the default execution space.  It might help to know that this check was originally requested by people who develop mostly on OpenMP and only sometimes test on devices.  They wanted the warnings so that they didn't find out their device code was broken a week after writing it.

**Comment by vbrunini** [comment]
> They wanted the warnings so that they didn't find out their device code was broken a week after writing it.

Yeah that's the same reason I want the warning. Warning by default if you can't tell it is an explicit host space sounds like the right behavior to me.

**Comment by DavidPoliakoff** [comment]
One check that might be useful, just in case we ever added a scatterbrained member of the team, might be to check _within_ Kokkos for files which fail to include `Kokkos_Macros.hpp`. Supposing somebody had done that, they would run into lots of little issues where they didn't have access to any of the Kokkos configuration data while defining their functionality. Purely an interesting hypothetical, but perhaps useful if we ever did add such a member to the team.

**Comment by calewis** [comment]
@vbrunini @DavidPoliakoff  The latest push to the kokkos clang-tidy work has some progress.  

We can now turn off the implicit this warning if the user requests it and the policy to the parallel function is a temporary (I have inquired with the llvm mailing list about removing this restriction). I have also improved the error reporting that gives the variable, the lambda, and the Kokkos call. 

We can detect the following two cases depending on how you configure the tool:
```cpp
struct GoodClass {
  int foo;

  KOKKOS_INLINE_FUNCTION GoodClass(int f) : foo(f) {}
  KOKKOS_INLINE_FUNCTION void method() {
    Kokkos::parallel_for(
        Kokkos::RangePolicy<Kokkos::DefaultHostExecutionSpace>(0, 42),
        KOKKOS_LAMBDA(int i) { do_something(foo, i); });
  }
};

using MyTypeDef = Kokkos::DefaultHostExecutionSpace;
struct GoodClass3 {
  int foo;

  KOKKOS_INLINE_FUNCTION GoodClass3(int f) : foo(f) {}
  KOKKOS_INLINE_FUNCTION void method() {
    Kokkos::parallel_for(
        Kokkos::RangePolicy<MyTypeDef>(0, 42),
        KOKKOS_LAMBDA(int i) { do_something(foo, i); });
  }
};
```
`MyTypeDef` can actually be a typedef to anything, not just `DefaultHostExecutionSpace`, since it is just matched by a regex (the regex string is passed to an `llvm::Regex` if you need documentation on the syntax). 

To configure the tool you should set the CheckIfExplicitHost argument to anything that isn't 0 and you can set the HostTypeDefRegex to match what ever you want. 

Here is a dump of the `.clang-tidy` file with the default arguments. 
```txt
---
Checks:          '-*,kokkos-*'
User:            me
CheckOptions:
  - key:             kokkos-KokkosImplicitThisCapture.CheckIfExplicitHost
    value:           '0'
  - key:             kokkos-KokkosImplicitThisCapture.HostTypeDefRegex
    value:           'Kokkos::DefaultHostExecutionSpace'
...
```

**Comment by vbrunini** [comment]
That works great for me. Could it also be applied to the check for calling non-KOKKOS_FUNCTIONs ?

**Comment by calewis** [comment]
@vbrunini in what way? Provide a regex for allowed but not annotated functions? Or just turn off the check if `Kokkos::DefaultHostExecutionSpace` or your regex of choice is the execution space?

**Comment by vbrunini** [comment]
Turn off the check for host execution spaces using the same regex as for the implicit this capture.

**Comment by DavidPoliakoff** [comment]
Trilinos is soon going to look to eliminate their calls to `deep_copy` that don't take in an ExecutionSpace as an argument. So just look for such calls (`callExpr(unless(hasAnyArgument(recordDecl(isAnExecutionSpace))))`), where isAnExecutionSpace could just check for arguments which have the typedef calling themselves an execution space, I guess

**Comment by calewis** [comment]
@DavidPoliakoff, i'm sure we can figure out how to detect execution spaces.

**Comment by DavidPoliakoff** [comment]
Yeah, shouldn't be too bad

**Comment by calewis** [comment]
@vbrunini @mhoemmen @stanmoore1  We have a new repo for this https://github.com/kokkos/llvm-project, but it is not yet as feature complete as the temp version on our internal gitlab.  I have started the process of doing a proper publicly facing release, which involves some clean up and hopefully some testing.  But if you have any new feature requests or issues please make them issues at the new repo.  Also @vbrunini I recall that people wanted newer versions of clangd.  So you'll be happy to hear that our goal is to track the llvm master branch, but we don't yet have a good idea of how often we will rebase on master since it moves at the pace of 100s of commits per day.
