### ISSUE TITLE
Relax restrictions on View Assignments

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#258]
Generally we have been more restrictive than necessary in allowing view assignments. This includes going from runtime dimensions to compile dimensions, but also assigning Views of nominal different Layout which happen to have the same runtime physical Layout (think degenerated 2D views, where LayoutLeft and LayoutRight might have the same physical layout). 

We will not ad-hoc fix all those things, since it is a combinatorial issue. So please post use cases which are not currently supported in this issue, and we will look at relaxing them.

We also need ways to test for compile time and runtime errors, for cases where we expect failures.

**Comment by hcedwar** [comment]
This is a category / topic as opposed to an actionable issue.
