### ISSUE TITLE
PGI Test failures in tasking

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2582]
The merge of PR #2578 addressed test failures in the task_single_fib test.
 The test `serial.task_fib_chase_lev` now fails with a segfault:

```
[ RUN      ] serial.task_fib_chase_lev
make[2]: *** [test-serial] Segmentation fault (core dumped)
```

This occurred on the Blake testbed (Skylake arch) with OpenMP_Serial backends enabled and the pgi/18.7.0 compiler.

@dhollman

**Comment by ndellingwood** [comment]
pgi/19.4 seg-fault on kokkos-dev-2 in OpenMP build:

```
[ RUN      ] openmp.task_fib_single
Segmentation fault (core dumped)
```

**Comment by ndellingwood** [comment]
Updated the title since test failures are not unique to pgi/18.7

**Comment by dalg24** [comment]
Try with current NVHPC compiler

**Comment by ajpowelsnl** [comment]
@ndellingwood -- have you had the chance get to look at this error with the NVHPC compiler?

**Comment by ajpowelsnl** [comment]
Hi @PhilMiller, @ndellingwood and @dalg24 -- I see the same seg faulting behavior (w/ `clang-16`) in #5315 (details updated today).  Would you like for me to try the build and test run with another compiler (besides `clang-16`)?

**Comment by masterleinad** [comment]
We don't support PGI anymore.
