### ISSUE TITLE
Can we add the `check` target only if KOKKOS_ENABLE_TESTS is ON?

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#2583]
We are using Kokkos inside a larger project, building it alongside the rest of the code (i.e., we `add_subdirectory(path/to/kokkos-src)`). We also have other libraries that we build. All these TPLs are snapshotted as submodules in our project, to make it easy for the user to build the project (they are all relatively fast to build anyways).

The issue is that another TPL has the target `check`, which Kokkos also have. I understand that Kokkos "check" whether `check` is already defined, but unfortunately the other project doesn't, and I am not 100% sure that I am in full control of parsing Kokkos _after_ the other project. Besides, I'm not interested in the `check` target.

It appears to me that `check` is only used to somewhat group all tests, by means of adding tests as dependencies of `check`. If this is correct, and since tests, I presume, are only built if `KOKKOS_ENABLE_TESTS` is on, would it be possible to define the `check` target only if `KOKKOS_ENABLE_TESTS` is ON? It seems superfluous otherwise.

**Comment by crtrott** [comment]
Maybe we should just rename the target to "kokkos-check". I believe it is bad form to have this generic target name.

**Comment by crtrott** [comment]
We will remove this.
