### ISSUE TITLE
"Non-idempotent" find_package behavior

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2587]
Certain downstream users have configurations that end up repeating the include of `KokkosConfig.cmake`, which causes issues. `find_package` is supposed to short-circuit if the package is already found, but this behavior is more fragile than expected.

if-statements are needed to make the KokkosConfig.cmake file "idempotent" since we can't rely on CMake `find_package` doing that for us.

**Comment by jjwilke** [comment]
`add_library` calls are the main culprit.

**Comment by jjwilke** [comment]
From CMake docs:

"Once one of the calls succeeds the result variable will be set and stored in the cache so that no call will search again."

**Comment by ndellingwood** [comment]
@jjwilke looks like this was addressed by PR #522? I marked as InDevelop, please change if more work is needed.
