### ISSUE TITLE
Remove old View and its infrastructure

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#259]
Given a sufficient period of use for the new View, remove the old Kokkos::View and its implementation infrastructure and move the new Kokkos::Experimental::View and its implementation infrastructure into the appropriate Kokkos and Kokkos::Impl namespaces.

**Comment by dsunder** [comment]
Great job!

**Comment by hcedwar** [comment]
Old View removed in commit:  
https://github.com/kokkos/kokkos/commit/e17ea00f4ad302073e73fc5b7624f4fda560cf54

Pending to move from Kokkos::Experimental to Kokkos namespace.  Must schedule with downstream users to avoid potential breakage.

**Comment by hcedwar** [comment]
Postpone namespace move until Trilinos packages update to use non-experimental namespace.

**Comment by rppawlo** [comment]
Do you know which packages are still using the experimental namespace?

**Comment by hcedwar** [comment]
Removed dead code.
Moved all but `ViewMapping`, `ViewArrayAnalysis`, and `ViewDataAnalysis` from `namespace Kokkos::Experimental::Impl` to `Kokkos::Impl`.  Moving these requires coordination with downstream code that specializes `ViewMapping` for non-trival _scalar_ types.

**Comment by hcedwar** [comment]
Remove use of 
`KOKKOS_USING_DEPRECATED_VIEW`
`KOKKOS_USING_EXPERIMENTAL_VIEW`
`KOKKOS_USING_EXP_VIEW`
