### ISSUE TITLE
Kokkos_DEVICES not defined in Trilinos/TriBITS install

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#2600]
TriBITS writes its own `KokkosConfig.cmake` and we lose all the information we record in a non-`TriBITS` configuration in `KokkosConfig.cmake.in` resp. `KokkosConfig.cmake`. In particular, this includes `Kokkos_DEVICES` and `Kokkos_ARCH` some downstream projects need.

https://github.com/kokkos/kokkos/blob/7212d7478dd47f77b287b5813f10c277b5352bd2/cmake/kokkos_install.cmake#L2-L28

**Comment by ndellingwood** [comment]
@masterleinad I marked this blocking promotion

**Comment by jjwilke** [comment]
I agree we need to fix this. Is this really a 3.0 issue though? Kokkos_DEVICES was never available downstream to projects depending on Trilinos.

**Comment by jjwilke** [comment]
This is also requires pretty significant changes to Tribits, not just Kokkos.

**Comment by ndellingwood** [comment]
> Kokkos_DEVICES was never available downstream to projects depending on Trilinos.

@jjwilke my mistake, I marked as BLOCKS PROMOTION because I had assumed behavior had changed from 2.9. Please relabel as appropriate.

**Comment by jjwilke** [comment]
@masterleinad Is this breaking something that used to work that you know of? It's totally possible. If so, we can keep the 3.0 and BLOCKS PROMOTION labels.

**Comment by masterleinad** [comment]
Previously, `KOKKOS_GMAKE_DEVICES` was defined in `cmake/kokkos_settings.cmake` and this file would also be installed. 

I would be fine if we just mirror this behavior and duplicate the enabled devices into a separate file (or ideally just appending to the file created by `TriBITS`).

**Comment by jjwilke** [comment]
Touche. 

I had been trying to limit the files that got installed as a Hyrum's law defense (@dhollman). The more garbage that exists in the install folder, the higher the probability that a downstream user will depend on it, which means we have to keep maintaining it.  I'm okay if it gets installed ONLY for Trilinos builds.  

Do we have use cases though of Trilinos-dependent apps in the wild that were relying on `kokkos_settings.cmake`?

**Comment by jjwilke** [comment]
The relevant bit of Tribits code is in `TribitsWriteClientExportFiles.cmake `:

````
  IF (${PROJECT_NAME}_ENABLE_INSTALL_CMAKE_CONFIG_FILES)
    CONFIGURE_FILE(
      ${${PROJECT_NAME}_TRIBITS_DIR}/${TRIBITS_CMAKE_INSTALLATION_FILES_DIR}/TribitsProjectConfigTemplate.cmake.in
      ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config_install.cmake )

    INSTALL(
      FILES ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config_install.cmake
      DESTINATION "${${PROJECT_NAME}_INSTALL_LIB_DIR}/cmake/${PROJECT_NAME}"
      RENAME ${PROJECT_NAME}Config.cmake
      )
  ENDIF()
````

**Comment by jjwilke** [comment]
The default value here is `${PROJECT_NAME}_ENABLE_INSTALL_CMAKE_CONFIG_FILES=ON`. I don't think we would want users to command-line override globally with:
````
-DTrilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=OFF
````
Possibly we could short-circuit this at the the package level:
````
-DKokkos_ENABLE_INSTALL_TRIBITS_CONFIG_FILES:BOOL=OFF
````

**Comment by masterleinad** [comment]
Trying that we are currently getting
```
   INCLUDE could not find load file:

    ${TRILINOS_INSTALL_DIR}/cmake/Kokkos/KokkosTargets.cmake
```

**Comment by jjwilke** [comment]
What is the "that" in "trying that"?

**Comment by masterleinad** [comment]
Oh, sorry. I wanted to say, trying to configure `Trilinos` with `-DTrilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=OFF`,
I get the above error when trying to find `Kokkos` downstream.

**Comment by jjwilke** [comment]
Interesting. I would have thought no `KokkosConfig.cmake` at all would have gotten installed.

**Comment by masterleinad** [comment]
You are right. I forgot to remove the install dircetory before trying.

**Comment by masterleinad** [comment]
Something like
```CMake
diff --git a/packages/kokkos/cmake/kokkos_install.cmake b/packages/kokkos/cmake/kokkos_install.cmake
index 7ba15bee02..67ea498c9a 100644
--- a/packages/kokkos/cmake/kokkos_install.cmake
+++ b/packages/kokkos/cmake/kokkos_install.cmake
@@ -21,11 +21,14 @@ IF (NOT KOKKOS_HAS_TRILINOS)
     "${Kokkos_BINARY_DIR}/KokkosConfigVersion.cmake"
     DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Kokkos)
   install(EXPORT KokkosTargets NAMESPACE Kokkos:: DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Kokkos)
-
-  # build and install pkgconfig file
-  CONFIGURE_FILE(core/src/kokkos.pc.in kokkos.pc @ONLY)
-  INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/kokkos.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
+ELSE()
+  file(APPEND "${Kokkos_BINARY_DIR}/KokkosConfig.cmake" "SET(Kokkos_DEVICES ${KOKKOS_ENABLED_DEVICES})")
+  file(APPEND "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/KokkosConfig_install.cmake" "SET(Kokkos_DEVICES ${KOKKOS_ENABLED_DEVICES})")
 ENDIF()
```
would probably already help.

**Comment by jjwilke** [comment]
That would work - but I'd need to check again what order these things happen in Tribits. The APPEND might get completely overwritten depending on when Tribits does its `CONFIGURE_FILE`

**Comment by masterleinad** [comment]
I checked that this indeed appends to the file in the installed `Trilinos`. Of course, it looks a bit hacky and there might be a better way.

**Comment by jjwilke** [comment]
@masterleinad The whole Tribits + standalone CMake is the embodiment of hacky. I think your approach is probably the simplest way to accomplish things if it works - particularly since it avoids bringing a non-standard file into the mix.

If the append works, we could actually put all of the stuff including the KOKKOS_CHECK function into a common file.

````
FILE(READ KokkosConfigCommon.cmake KOKKOS_CONFIG_COMMON)
FILE(APPEND ${Kokkos_BINARY_DIR}/KokkosConfig.cmake ${KOKKOS_CONFIG_COMMON})
````
and use the same logic for standalone and Tribits. Then KokkosConfig.cmake would essentially be the same for both.

**Comment by ndellingwood** [comment]
Does merge of PR #2604 resolve this?

**Comment by masterleinad** [comment]
Yes.
