### ISSUE TITLE
Travis CI build failures with death tests

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2617]
We have been seeing failures on Travis in several PRs.

The snippets below are taken from PR #2615 and the full log is available [here](https://travis-ci.org/kokkos/kokkos/jobs/628879863#L1130-L1148)
```
Running tests...
Test project /home/travis/build/kokkos/kokkos/build
      Start  1: UnitTest_OpenMP
1/29 Test  #1: KokkosCore_UnitTest_OpenMP ........................***Failed  Error regular expression found in output. Regex=[  FAILED  ]344.52 sec
[==========] Running 169 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from TEST_CATEGORYDeathTest
[ RUN      ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment
view_layoutstride_right_to_layoutleft_assignment: srand(1577125550)
/home/travis/build/kokkos/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:678: Failure
Death test: { dst = src; }
    Result: died but not with expected error.
  Expected: View assignment must have compatible layouts
Actual msg:
[  DEATH   ] 
[  FAILED  ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment (163 ms)
[----------] 1 test from TEST_CATEGORYDeathTest (163 ms total)
[----------] 168 tests from openmp
```
```
[ RUN      ] openmp.view_layoutstride_left_to_layoutright_assignment
view_layoutstride_left_to_layoutright_assignment: srand(1577125883)
/home/travis/build/kokkos/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:829: Failure
Death test: { dst = src; }
    Result: died but not with expected error.
  Expected: View assignment must have compatible layouts
Actual msg:
[  DEATH   ] 
[  FAILED  ] openmp.view_layoutstride_left_to_layoutright_assignment (150 ms)
```

These failures also show in [serial](https://travis-ci.org/kokkos/kokkos/jobs/628879862#L1092-L1108).

Both failing builds are with Clang version 7.0.0 in debug mode.

When skimming through the build history, I saw these failures in `develop` for 
builds [#2960](https://travis-ci.org/kokkos/kokkos/builds/627705820), [#2958](https://travis-ci.org/kokkos/kokkos/builds/626857747), [#2930](https://travis-ci.org/kokkos/kokkos/builds/624300521).  [#2909](https://travis-ci.org/kokkos/kokkos/builds/620770702) was the first occurence but it looks unrelated to the changes merged in PR #2578.

**Comment by crtrott** [comment]
I can't reproduce this yet with clang 7 on apollo.

**Comment by crtrott** [comment]
I have an attempt at a fix: https://github.com/kokkos/kokkos/pull/2671
