### ISSUE TITLE
deep_copy with LayoutStride should not memcpy

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#262]
The current deep_copy implementation will memcpy if the Views are contiguous, have the same span, and same layout.  The layout should be constrained to LayoutLeft or LayoutRight as well.

**Comment by crtrott** [comment]
It could do a runtime check for LayoutStride whether the view spans a contigous space of memory.

**Comment by hcedwar** [comment]
Yep - we just discussed.

**Comment by ndellingwood** [comment]
Issued pull request with a fix. 
Tested using test_all_sandia script for 1. cuda/7.5 with Cuda_Serial build  2. intel/16.0.1 with OpenMP  3. clang/3.6.1 with Pthread_Serial
