### ISSUE TITLE
3.0rc Build Instructions: Feedback

### ISSUE THREAD

**Issue by flying-tiger** [kokkos/kokkos#2624]
I've been playing around with the new CMake support in the release candidate for 3.0. Above all, thank you for putting a modern CMake interface in place. This is a huge help and I was able to get a test project up and running on CPU very quickly and painlessly as a result. 

One piece of feedback: getting from CPU to GPU was rough. A few suggestions to help new users along, especially those just getting started with accelerators (me):

- A cmake example in README.md/BUILD.md using nvcc_wrapper and a custom host compiler would be greatly appreciated. It took me awhile to realize the purpose/need for nvcc_wrapper and its not mentioned anywhere in the top-level docs. I also suspect many of your users will want to use the Intel compilers is possible, so an example of how to specify that to nvcc_wrapper would be helpful.

- If you don't specify Kokkos_ARCH_XX for the GPU, it defaults to the lowest possible value, which is too old for the recent CUDA toolkits. It would be nice to have a better default, or a call out in the docs that this is more of a requirement than an option in most cases.

- Finding a combination of toolkit/compiler/compute capability took some searching. It would be nice to have the appropriate NVIDIA docs linked in the README/BUILD docs.

Thanks again for the great software.

**Comment by ndellingwood** [comment]
Looks like #2639 should have addressed this
