### ISSUE TITLE
subview from Scalar*[2] to Scalar* aborts

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#263]
Hello, I have code that should boil down to this:
```
typedef Kokkos::View< Scalar*, execution_space > array_type ;
typedef Kokkos::View< Scalar*[NumStates], execution_space > state_array_type ;
static array_type getFromSA(const state_array_type &a, const int state){
  return Kokkos::subview(a, Kokkos::ALL (), state);
}
```
As far as I can tell, executing this code results in a `host_abort`:
```
Kokkos::Experimental::ViewOffset assignment of LayoutLeft/Right from LayoutStride  requires stride == 1
```
`execution_space` is `Serial`, so the types ought to be `LayoutRight`.
Should this work and if not what should I do differently ?
Thanks.

**Comment by hcedwar** [comment]
With LayoutRight the NumStates dimension is contiguous.
I suspect you want the leading dimension to be contiguous so explicitly force LayoutLeft.

**Comment by ibaned** [comment]
Thank you, I'll try that.

**Comment by ibaned** [comment]
That fixed it, and probably improved performance.
Feel free to close this issue.
