### ISSUE TITLE
ThreadVector with arbitrary index range

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#264]
It appears that I cannot have a `ThreadVectorRange` over an index space [begin, end) if begin != 0.

I would like to have `ThreadVectorRange(team, begin, end), [=] (...)`, it is easy to get around this by shifting the iteration indices, but having this natively supported would be nice.

**Comment by crtrott** [comment]
I thought about this long and hard a few times already. On one hand I get annoyed myself with the same issue, on the other hand I really like to encourage people to write vector loops which start at 0, since that can help optimization. But since you get annoyed with it as well, I might as well add that overload.

**Comment by dholladay00** [comment]
If there is a performance related reason, then I will stick with starting at 0.

Is there an inherent issue with loops that don't start at 0, or is it related to compiler limitations?

**Comment by nmhamster** [comment]
Zero is better for pattern and alignment detection. At least the compilers seem to like it and actually vectorize from zero more happily.

**Comment by crtrott** [comment]
The question is whether there is a difference between

```C++
for(int i = 0; i<N; i++)
  do_something(i+offset);
```

and
```C++
for(int i = offset; i<N; i++) 
  do_something(i);
```

**Comment by nmhamster** [comment]
In the example you give yes there is a difference, you're doing N-offset iterations on the lower and N on the upper. If you can get offset to be properly aligned then the code should be good, if not then it's a hassle of a pre-vector loop to get it to an aligned state (assuming the data is aligned in the first place). In the past we have had compilers that preferred zero but there isn't a good fundamental reason for it.

**Comment by mhoemmen** [comment]
@jjellio was this of interest to you?

**Comment by dholladay00** [comment]
I am curious as to why this was labeled `wontfix`. I don't have a strong preference unless it is performance related. However, given that team-thread-ranges can support index ranges that do not start with 0, it seems odd (at least to me) to not extend that to thread-vector-ranges. 

Note: I'm not necessarily pushing for this issue to be reopened, but it would be nice to know more about why it was closed.

**Comment by hcedwar** [comment]
Compiler generation of vectorized code is so fragile, as @nmhamster noted, that there is high risk of non-zero based loops not yielding vectorization performance as desired.

**Comment by jjellio** [comment]
@mhoemmen I was able to rewrite the loops so that the inner loop could be zero indexed. The downside is that it means you have to compute the offset inside the loop (nmhamster's point).
