### ISSUE TITLE
Parallel_for rookie mistake that prevents threadparallel execution?

### ISSUE THREAD

**Issue by andyroydz** [kokkos/kokkos#2646]
Hello everyone,

I am very new to Kokkos and wanted to compare parallel_for with a regular for loop.
Unfortunately, there is something I am doing wrong, as I do not notice a speedup when launching multiple threads.

Also I wonder if there is a better way to code this without initialising the vectors `x_1`, `x_2` and `xi` inside of the parallel_for.

Here is the code snippet I used.
````cpp
#include <cmath>
#include "Tpetra_Core.hpp"
#include "Kokkos_Core.hpp"

int main(int argc, char *argv[]) {
   Tpetra::ScopeGuard tpetraScope (&argc, &argv);
   {
	std::clock_t start_t_test;
	double duration_t_test;
	start_t_test = std::clock();
	int numval = 1000000;
	Kokkos::View<double *> xi_kokkos("v", numval);

	// Parallel
	Kokkos::parallel_for("Compute Dilatation", numval, KOKKOS_LAMBDA(const int k) {
		std::vector<double> x_1(3);
		std::vector<double> x_2(3);
		std::vector<double> xi(3);
		double xi_norm = 0;
		for (int i = 0; i < 3; i++) {
			x_1[i] = 3 * k + i;
			x_2[i] = 30 * k + i;
			xi[i] = x_2[i] - x_1[i];
			xi_norm += xi[i] * xi[i];
		}
		xi_norm = sqrt(xi_norm);
		xi_kokkos(k) = xi_norm;
	});
	duration_t_test = (std::clock() - start_t_test) / (double)CLOCKS_PER_SEC;
	std::cout << "Test Parallel: " << duration_t_test << std::endl;
	
	// Serial
	std::vector<double> x_1(3);
	std::vector<double> x_2(3);
	std::vector<double> xi(3);
	start_t_test = std::clock();
	for (int k = 0; k < numval; k++) {
		double xi_norm = 0;
		for (int i = 0; i < 3; i++) {
			x_1[i] = 3 * k + i;
			x_2[i] = 30 * k + i;
			xi[i] = x_2[i] - x_1[i];
			xi_norm += xi[i] * xi[i];
		}
		xi_norm = sqrt(xi_norm);
		xi_kokkos(k) = xi_norm;
	}
	duration_t_test = (std::clock() - start_t_test) / (double)CLOCKS_PER_SEC;
	std::cout << "Test Seriell: " << duration_t_test << std::endl;
   }
   return 0;
}
````

**Comment by dalg24** [comment]
I don't understand why you used a vector in the first place.
```C++
	Kokkos::parallel_for("Compute Dilatation", numval, KOKKOS_LAMBDA(const int k) {
		double xi_norm = 0;
		for (int i = 0; i < 3; i++) {
			double const x_1 = 3 * k + i;
			double const x_2 = 30 * k + i;
			double const xi = x_2 - x_1;
			xi_norm += xi * xi;
		}
		xi_norm = sqrt(xi_norm);
		xi_kokkos(k) = xi_norm;
	});
```
And yes constructing a `std::vector` within the body of your loop kills performance.

**Comment by calewis** [comment]
Specifically why it kills your performance is that allocating in KOKKOS_LAMBDA is usually something you want to avoid.  

For the following code 
```cpp
#include <vector>
#include <cmath>
double dilatation(int k) {  
  std::vector<double> x_1(3);
  std::vector<double> x_2(3);
  std::vector<double> xi(3);
  double xi_norm = 0;
  for (auto i = 0; i < 3; ++i) {
    x_1[i] = 3 * k + i;
    x_2[i] = 30 * k + i;
    xi[i] = x_2[i] - x_1[i];
    xi_norm += xi[i] * xi[i];
  }

  return std::sqrt(xi_norm);
}
```
You can compile (https://godbolt.org/z/qC2DGm) it and see that there are calls to `operator new(unsigned long)` in your kernel.  

While @dalg24's code doesn't have those allocations which you can see here https://godbolt.org/z/7CDHYZ.

**Comment by andyroydz** [comment]
I see, thank you both!
So I need to avoid the allocation inside the loop.
In another case though, I will have to save the values of x_1 and x_2 not only for xi_norm, but also for further computations. So if I need to do that, is there a way that the vector is not initialised in every step? Maybe a Kokkos specific data structure that automatically creates as many vectors as there are threads assigned to the parallel_for and then overwrites them. Because as far as I have tried it, a Kokkos::View will not do that automatically.

**Comment by calewis** [comment]
Can you give an example.  A std::array might be what you need.

**Comment by janciesko** [comment]
Also note that you are measuring CPU time. Std::clock provides CPU time. For OMP_NUM_THREADS = 4, your CPU time will be 4x higher, thus not showing a speedup.
Kokkos_Core provides a timing routine for convenience:

Kokkos::Timer timer;
//body
double time = timer.seconds();
std::cout << "Test Parallel: " << time << std::endl;

Your code:
OMP_NUM_THREADS=1 ./code  34.46s user 0.35s system 99% cpu 34.845 total
Test Parallel: 34.8379
OMP_NUM_THREADS=4 ./code  37.59s user 0.50s system 386% cpu 9.847 total
Test Parallel: 9.66779

Removing std::vector<> allocation:
OMP_NUM_THREADS=1 ./code  0.61s user 0.22s system 82% cpu 1.003 total
Test Parallel: 0.823801
OMP_NUM_THREADS=4 ./code  0.71s user 0.38s system 343% cpu 0.318 total
Test Parallel: 0.310278

**Comment by andyroydz** [comment]
@calewis 
For example if I just take my crappy code from above and add to it some function that uses the vectors, rewrite the formula for the View xi_kokkos and use xi_1 and xi_2 several times afterwards in the loop
```` cpp
Kokkos::View<double *> xi_kokkos("v", numval);
Kokkos::parallel_for("Compute Dilatation", numval, KOKKOS_LAMBDA(const int k) {
	std::vector<double> x_1(3);
	std::vector<double> x_2(3);
	std::vector<double> xi(3);
	double xi_norm = 0;
	for (int i = 0; i < 3; i++) {
		x_1[i] = 3 * k + i;
		x_2[i] = 30 * k + i;
		xi[i] = x_2[i] - x_1[i];
		xi_norm += xi[i] * xi[i];
	}
	xi_norm = sqrt(xi_norm);
	// This variable func_out e.g. also cannot be allocated outside of the parallel_for loop as far as I understand
	// At least I get a compiler error if I try to do it, because it is rewritten in the loop
	double func_out = some_function_that_uses_the_vectors(xi_1, xi_2);
	xi_kokkos(k) = xi_norm*xi_1[0]*xi_2[1];
	// Same for other_var as for func_out
	double other_var = 0;
	for(int j = 0; j < 10; j++) {
		other_var += xi_kokkos(k)*xi_1[2]*xi_2[2];
	} 
});
````

@janciesko 
Thank you for clearing that up for me!

**Comment by masterleinad** [comment]
You want to look into scratch memory, e.g. at https://github.com/kokkos/kokkos/wiki/HierarchicalParallelism or in the tutorial.
