### ISSUE TITLE
Question: how can I know one view data regions does not overlap with another ? 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#265]
Question: how can I know one view data regions does not overlap with another ? 

Let's say I do something supid like this
```
View<double**> a("a", 10,10);
auto part_a = subview(a, range(0,5), range(0,5));
auto part_b = subview(a, range(3,7), range(3,7));
SomeFunction(part_a, part_b);
```
Now I need to abort if part_a has overlap with part_b. Is there a kokkos utility function ?

**Comment by hcedwar** [comment]
No such utility function.  For LayoutStride Views, which you will have in the example, such a function would be non-trivial.  Please feel free to develop such a function and submit a pull request.

**Comment by kyungjoo-kim** [comment]
Okay. I will write a function for that.
