### ISSUE TITLE
Environment variables question

### ISSUE THREAD

**Issue by kddevin** [kokkos/kokkos#2653]
Why do the environment variables have different names than the command-line arguments (e.g., KOKKOS_NUM_DEVICES vs --kokkos-ndevices, KOKKOS_DEVICE_ID vs --kokkos-device)?  Wouldn't it be easier to maintain and for users to guess the right environment variable names if the arguments and environment variables shared the same names?

https://github.com/kokkos/kokkos/wiki/Initialization#53-initialization-by-environment-variables

Kokkos' environment variables are insufficiently documented.  I'm told @mhoemmen added the section above just yesterday, with just enough info to get me past a problem I was having.  (Thanks, @mhoemmen !)  But there are other initialization variables that are not documented, and users can't guess their names because the naming convention differs.

https://github.com/trilinos/Trilinos/pull/6590

**Comment by mhoemmen** [comment]
@kddevin Just curious -- do you prefer the environment variable names, the command-line argument names, or neither?

**Comment by kddevin** [comment]
@mhoemmen No preference, as long as they match each other and are documented.  Thanks!

**Comment by jeffmiles63** [comment]
We will add --kokkos-num-devices to match KOKKOS_NUM_DEVICES and deprecate --kokkos-ndevices.  --kokkos-ndevices will generate a warning, but will still work for first adopted release, then it will be removed for subsequent release.

**Comment by mhoemmen** [comment]
@jeffmiles63 Thanks!  I prefer `kokkos-num-devices` over `kokkos-ndevices`.

**Comment by mhoemmen** [comment]
@jeffmiles63 What about `kokkos-device-id`?

**Comment by crtrott** [comment]
All of them.

**Comment by dalg24** [comment]
Closed in #2732
`--[kokkos-]ndevices -> --[kokkos-]num-devices`
`--[kokkos-]device -> --[kokkos-]device-id`
A warning is raised when the old argument is used.

**Comment by mhoemmen** [comment]
@dalg24 Thanks! :-D
