### ISSUE TITLE
Kokkos::fence behavior with multiple execution spaces

### ISSUE THREAD

**Issue by streichler** [kokkos/kokkos#2659]
When Kokkos is built with two or more execution spaces, the behavior of `Kokkos::fence` seems wrong to me.  No matter which execution space has performed an operation that needs fencing, a call to `Kokkos::fence` always performs fences on the following execution spaces:
1. the default execution space
2. the `HostSpace`'s execution space, if different from (1)
3. the HPX execution space, if different from (1) and (2) 

If the operation performed is on one of these spaces, then things are functionally correct, but may have undesirable performance impact (e.g. waiting for a CUDA fence even though you were just doing an OpenMP reduction).  The current Legion+Kokkos interop (#2651) is in a worse situation here, because trying to talk to multiple execution spaces from a single thread becomes a fatal error.

Worse, if your operation was performed on a space that's not in the above list, you're not getting the synchronization that may be critical for correct execution.  (The least-contrived way to have this happen that I can see right now is to build with OpenMP+Cuda, but then compile with
`-DKOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_OPENMP` and have all the CUDA fences go away.)

With the certainty that comes from having not worked with the Kokkos codebase much at all, the obviously (to me) right answer is that the generic `Kokkos::fence` should go away, each execution space (or instance thereof) should get a public `fence` method, and then all Kokkos operations that require fences should be expected to know which execution space(s) they require fences for.

On the Legion side, I'll probably need to hack things so that the "rogue" CUDA fence that is issued by the thread(s) that are using OpenMP execution space is silently ignored rather than causing a runtime assert.  I'd love that to be temporary though.

**Comment by masterleinad** [comment]
Each execution space already has a public `fence` method. Before https://github.com/kokkos/kokkos/pull/2141 it was a static class function and is now non-static, also see https://github.com/kokkos/kokkos/issues/2140.

**Comment by masterleinad** [comment]
Did you try to replace `Kokkos::fence` by `ExecutionSpace().fence()`?

**Comment by streichler** [comment]
@masterleinad if I were calling `Kokkos::fence()` directly, then yes, I would switch to that.  My problem is that I'm calling `Kokkos::parallel_reduce` (with a range policy that specifies my desired execution space), which then in turns calls `Kokkos::Impl::ParallelReduceFence`, and there's no way to tell the latter which execution space needs the fence.

I guess I technically am raising two issues here:
1. `Kokkos::fence` has behavior that is not what the naive user of Kokkos would expect (i.e. it does not actually fence all execution spaces for some configurations).
2. Any fences initiated by Kokkos internally should be performed on specific execution space instances.

**Comment by crtrott** [comment]
In which configs does `Kokkos::fence()` not all exec spaces? And 2: yes we should fix that.

**Comment by streichler** [comment]
> In which configs does Kokkos::fence() not all exec spaces?

It looks like any config that has two or more accelerator spaces (e.g. Cuda+ROCm), or two host spaces (e.g. Serial+OpenMP), or one that messes with the `KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_...` defines.  I guess I don't understand why there's any conditions beyond the `#ifdef KOKKOS_ENABLE_...` tests in this code: https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Core.cpp#L380-L419

**Comment by masterleinad** [comment]
You cannot have more than one device execution space and we are always fencing the host space and the default execution space (and HPX if available). For me, it looks like we do enough fencing there.

**Comment by streichler** [comment]
> You cannot have more than one device execution space and we are always fencing the host space and the default execution space (and HPX if available). For me, it looks like we do enough fencing there.

Well, with PR #2672 or something like it (thanks for getting the ball started on that!), I'll stop caring personally about the semantics of `Kokkos::fence`, but I doubt I'd be the only user of Kokkos to be surprised that the semantics aren't "fence all the spaces".  The only documentation I can find regarding Kokkos::fence does imply that it's a sufficient replacement for any other fence you might issue.  So if there's a good reason for `Kokkos::fence` to only "fence some of the spaces", I guess I'd push for that to be documented a little more obviously.

**Comment by crtrott** [comment]
`Kokkos::fence()` should fence everything. In practice it does, the way it is implemented that is only true though because you can't have multiple asynchronous backends enabled right now. So we should ensure that it does ...

**Comment by streichler** [comment]
@masterleinad I believe it will, but will try to test it out today.  I'll need to hack some workarounds for #2652 or #2658, but I ought to at least be able to verify that fences have enough precision for my needs.

**Comment by streichler** [comment]
Yes, I am able to run a Legion test that sends work to both the Cuda and Serial execution spaces, with each fencing only its own space.  I can't check OpenMP+Cuda yet, but based on the structure of the changes in #2724 and #2672, I would not expect any fence-related issues there.

**Comment by masterleinad** [comment]
OK, great! I'll mark this as fixed.
