### ISSUE TITLE
DualView::sync_host doesn't sync with CudaUVMSpace views

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#2665]
@kddevin @trilinos/tpetra

My understanding of the meaning of `Kokkos::DualView::sync_to_host` is that if you call it, you may then safely access the DualView's host View on host.  This is not the case for a CudaUVMSpace DualView.  In that case, `sync_to_host` does nothing.  It used to fence, but now it does nothing.

We discovered this while working on [Trilinos PR 6617](https://github.com/trilinos/Trilinos/pull/6617#discussion_r368773560).  We can work around in Trilinos to some extent, but it's annoying that `DualView::sync_to_host` "lies" about its core semantics with CudaUVMSpace.  Working around that means we need two separate code branches based on the memory space.  That defeats the purpose of DualView.

**Comment by stanmoore1** [comment]
@mhoemmen Are you saying you want CudaUVMSpace DualView `sync_to_host` to fence?

**Comment by mhoemmen** [comment]
@stanmoore1 wrote:
> Are you saying you want CudaUVMSpace DualView `sync_to_host` to fence?

The only sensible postcondition of `sync_to_host` is that I can safely access the host View on host.  If `sync_to_host` has no postcondition, then there's no point to calling it, or to using DualView with `Device<Cuda, CudaUVMSpace>`.  The only way to guarantee this postcondition with `Device<Cuda, CudaUVMSpace>` is to fence.

`Device<Cuda, CudaSpace>` DualViews don't need to fence, because `cudaMemcpy` is synchronous.

**Comment by dalg24** [comment]
> This is not the case for a CudaUVMSpace DualView. In that case, sync_to_host does nothing. It used to fence, but now it does nothing.

Are you sure?  `DualView` has no specialization on memory nor execution spaces and `DualView::sync_host()` calls `deep_copy()` which seems to have fences.
https://github.com/kokkos/kokkos/blob/f60f11eb9a016a271cba594bf799608b197f8dcf/containers/src/Kokkos_DualView.hpp#L530-L533

**Comment by masterleinad** [comment]
in contrast to, `DualView::sync()` to `DualView::sync_to_host` does not fence if host and device memory space are equal which looks inconsistent. Other than that, I agree with @dalg24 that `deep_copy()` is called if the data is marked as modified and that call always fences.

Do you have a minimal example that shows the problem?  Do you also observe it with the release candidate or a recent version of the `develop` branch?

I tried replacing all `template sync<typename ViewType::host_mirror_space>()` with `sync_host()`  in the unit test and didn't observe any issues.

**Comment by mhoemmen** [comment]
@masterleinad wrote:
> Do you have a minimal example that shows the problem?

See the Trilinos issue quoted above.

@dalg24 wrote:
> Are you sure? `DualView` has no specialization on memory nor execution spaces and `DualView::sync_host()` calls `deep_copy()` which seems to have fences.

Does `deep_copy` do anything at all if the two pointers are the same, as they would be in this case?

**Comment by masterleinad** [comment]
> > Do you have a minimal example that shows the problem?
> 
> See the Trilinos issue quoted above.

I meant something free-standing not requiring `Trilinos`.

> Does `deep_copy` do anything at all if the two pointers are the same, as they would be in this case?

Yes, it should fence:
https://github.com/kokkos/kokkos/blob/2983b80d9aeafabb81f2c8c1c5a49b40cc0856cb/core/src/Kokkos_CopyViews.hpp#L1441-L1451

**Comment by mhoemmen** [comment]
> Does `deep_copy` do anything at all if the two pointers are the same, as they would be in this case?

For `deep_copy` between two Views of nonzero rank, `deep_copy` [does *nothing* (not even a fence)](https://github.com/kokkos/kokkos/blob/c5f6aa0e2f883c3ada160112bdeea847edb8fc8d/core/src/Kokkos_CopyViews.hpp#L1672) if the pointers are the same.

That behavior is fine.  The problem is with `DualView::sync*`.  `deep_copy`'s postcondition is "the two Views have the same data."  `DualView::sync*`'s postcondition is (or at least should be) "you may now safely access the data in the desired space."

**Comment by mhoemmen** [comment]
> Yes, it should fence

That's a bit weird.  `deep_copy`'s postcondition should be "the two Views have the same data"; `sync*`'s postcondition should be "it is now safe to access the View in the desired space."

**Comment by masterleinad** [comment]
> For `deep_copy` between two Views of nonzero rank, `deep_copy` [does _nothing_ (not even a fence)](https://github.com/kokkos/kokkos/blob/c5f6aa0e2f883c3ada160112bdeea847edb8fc8d/core/src/Kokkos_CopyViews.hpp#L1672) if the pointers are the same.

The line you are referencing is for the case that either of the pointers is a `nullptr`, isn't it? Even in this case, line 1704 has a fence if I see correctly.

**Comment by mhoemmen** [comment]
@masterleinad Sorry, that was incorrect of me.  Could it be possible that `Kokkos::fence()` does the wrong thing, compared to `execution_space().fence()` ?

**Comment by masterleinad** [comment]
`Kokkos::fence()` calls `Kokkos::fence_internal()` which fences the default execution space and the host space. In particular, it calls `Kokkos::Cuda::impl_static_fence()`:
https://github.com/kokkos/kokkos/blob/2983b80d9aeafabb81f2c8c1c5a49b40cc0856cb/core/src/impl/Kokkos_Core.cpp#L356-L396

`Kokkos::Cuda::fence()` calls `impl_static_fence()` if deprecated code is enabled and `m_space_instance->fence()` otherwise:
https://github.com/kokkos/kokkos/blob/2983b80d9aeafabb81f2c8c1c5a49b40cc0856cb/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L797-L805

The latter calls `cudaStreamSynchronize()` and `impl_static_fence()` calls `cuda_device_synchronize()` which calls `cudaDeviceSynchronize()`.

**Comment by crtrott** [comment]
Maybe there is a modify call missing somewhere? sync_host does not fence if the data was not last modified on the device. But in that case it should be not necessary to fence in the first place.

**Comment by mhoemmen** [comment]
Thanks everyone!  We will look more closely at this.  I'll close this issue for now, but reopen if needed.
