### ISSUE TITLE
deep_copy using remap with source execution space

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#267]
deep_copy with incompatible layout uses the Impl::ViewRemap functor running in the destination View's execution space.  If the destination execution space cannot access the source memory space, but the source execution space can access the destination memory space then should use ViewRemap with source execution space.
Impl::ViewRemap will need to accept an execution space which will be set by the deep_copy function.

**Comment by ndellingwood** [comment]
@hcedwar @crtrott 
Pull request issued #270 containing this feature and adding the recent View create_mirror_view enhancement to DynRankView and corresponding unit tests. 

Tested with test_all_sandia script for clang 3.6.1 Pthread_Serial, gcc 4.8.4 Serial, intel 16.0.1 and 14.0.4 OpenMP_Serial, cuda 7.5.18 Cuda_Serial

**Comment by ndellingwood** [comment]
Updated #270  to include create_mirror unit tests
