### ISSUE TITLE
Broken Mira build

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#268]
KOKKOS_ENABLE_PROFILING defaults to 1, which breaks Mira builds.  It would be great to add an option to the generate_makefiles.bash to disable profiling, or we need to automatically disable profiling on systems that do not support dlsym.

**Comment by crtrott** [comment]
That options is called "disable_profiling": (put in your Makefile: KOKKOS_OPTIONS=disable_profiling").

**Comment by crtrott** [comment]
And if that doesn't work reopen the issue ;-)

**Comment by dsunder** [comment]
Thanks!

--Dan
