### ISSUE TITLE
CUDA: Race condition in parallel_scan

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2681]
There was a bug in the parallel_scan implementation where the correct inter-block fence `(__threadfence())` wasn't called. This would manifest as a wrong result of the scan.

**Comment by ndellingwood** [comment]
PRs #2666 and #2668

**Comment by crtrott** [comment]
@stanmoore1 found the reproducer which made it possible to find this thing ...

**Comment by ndellingwood** [comment]
Closing this issue as this is now in master
