### ISSUE TITLE
nvcc errors

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#269]
I am unable to get my kokkos code to compile with nvcc (cuda 7.5 with gcc 4.9.2).

I have attached a reproducer. It compiles with gcc (all versions I have tested so far) and intel 16.0.1 (failed with 16.0.0).

Fails with following error:
`error: no instance of function template "f" matches the argument list`

Curiously, this small example will fail with a runtime error, but my code does not, so I don't think the issues are related. 

[nvcc_err.zip](https://github.com/kokkos/kokkos/files/247936/nvcc_err.zip)

**Comment by hcedwar** [comment]
Will evaluate with clang and Cuda 8

**Comment by ndellingwood** [comment]
Passes with clang (serial and threads)

**Comment by dholladay00** [comment]
This leads me to believe that it is likely due to lack of support by Cuda 7.5. 

Are there known issues / lack of feature support associated with templates or variadic templates in Cuda 7.5?

It is possible that am I misusing them but being saved by forgiving compilers in the non-nvcc cases?

**Comment by dholladay00** [comment]
Just to provide an update, this error does not occur with cuda 8.

**Comment by hcedwar** [comment]
Issue and limitation appears to be understood
