### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#271]

**Comment by hcedwar** [comment]
[crtrott]
I had a bit of time to test it and starting to prepare bug reports. If I
make the lambda a __host__ __device__ lambda for Kokkos, the compiler
dies with internal errors on our unit test compilation. I'd like to
narrow it down a bit more to figure out a reproducer, or see whether
this is a usage error in Kokkos. I will keep you posted.

This is the error:
Error: Internal Compiler Error (codegen): "there was an error in
verifying the lgenfe output!"

**Comment by crtrott** [comment]
Ok this actually seems to be a regression for a simple __device__ lambda from Cuda 7.5 which is triggered when trying to generate a lambda inside a member function.
