### ISSUE TITLE
Kokkos environment variables are not respected when using Kokkos::initialize() with no arguments

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2719]
The check for environment variables occurs in lines https://github.com/kokkos/kokkos/blob/7df3e14cedd8d59eed1b790eeaed81c97d4446ff/core/src/impl/Kokkos_Core.cpp#L674-L826 of the `void initialize(int& narg, char* arg[])` routine. 

Variables are then set and passed to `Impl::initialize_internal(arguments)`.

However, if `Kokkos::initialize()` is called without any arguments, this results in the call https://github.com/kokkos/kokkos/blob/7df3e14cedd8d59eed1b790eeaed81c97d4446ff/core/src/Kokkos_Core.hpp#L126 which calls to `Impl::initialize_internal(arguments)` https://github.com/kokkos/kokkos/blob/7df3e14cedd8d59eed1b790eeaed81c97d4446ff/core/src/impl/Kokkos_Core.cpp#L839-L841 without any checking of arguments or environment variables, resulting in use of environment variables not being respected.

**Comment by ndellingwood** [comment]
Cross-referencing #2653

**Comment by crtrott** [comment]
There is a separate question: should `Kokkos::initialize(InitArguments)` respect the environment variables ...

**Comment by mhoemmen** [comment]
@crtrott wrote:
> There is a separate question: should `Kokkos::initialize(InitArguments)` respect the environment variables ...

YES PLEASE

**Comment by dalg24** [comment]
I think the answer is yes as long as we preserve the precedence of `InitArguments` over the environment variables.
