### ISSUE TITLE
How does parallel_reduce choose to use default vs. user-defined join() and init()?

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#272]
This question is just an attempt to satisfy my curiosity.  It's not a problem with Kokkos, nor is it mission critical, so if you don't feel like answering, please ignore.

When supplying a functor to parallel_reduce(), the user can choose to define join() and init() as members of the functor.  If join() and init() are not defined by the user, parallel_reduce() uses operator+ and zeroing as defaults.

My question is, how does parallel_reduce internally know to override the defaults if user-defined join() and init() are present?  Is it templating off the presence of join() and init() in the user-defined functor, as discussed [here](http://stackoverflow.com/questions/257288/is-it-possible-to-write-a-c-template-to-check-for-a-functions-existence) and [here](http://stackoverflow.com/questions/87372/check-if-a-class-has-a-member-function-of-a-given-signature)?

Also, does the way Kokkos addresses this issue rely on C++11?

**Comment by hcedwar** [comment]
Template meta-programming magic which we were using before C++11.

**Comment by crtrott** [comment]
Basically we discover whether there is a function pointer with the correct signature in the functor. If not we supply the join operation, if yes we use that. The current implementation does use C++11 (decltype), but I believe we had an even more convoluted way of doing it before.

**Comment by mcarilli** [comment]
Cool.  Thanks!
