### ISSUE TITLE
Are 2D Views padded for vector alignment on the CPU?

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#273]
I can implement my own padded pseudo-2D view as a 1D view, and access elements like
`mypaddedview( i + padded_pitch*j )` but I figured I'd ask first.
Thank you for your help,
Michael

**Comment by hcedwar** [comment]
Can be done at construction, assuming LayoutLeft:

    Kokkos::View<double**,Kokkos::LayoutLeft,Space> 
      a( Kokkos::view_alloc("MyLabel", Kokkos::AllowPadding) , N , M );

**Comment by mcarilli** [comment]
Thank you for your answer, but why only LayoutLeft?  I can't enforce that my 2D arrays are LayoutLeft, that would defeat the purpose of Kokkos.  Or were you just using LayoutLeft as an example?
Regards,
Michael

**Comment by hcedwar** [comment]
An example, LayoutLeft and LayoutRight both work.

**Comment by mcarilli** [comment]
Must I specify the layout, or can I let the defaults do so?  Also, it is the fast index which is padded, right?
Finally, does this extend to arrays of higher dimension, ie, if I specify AllowPadding for a 3D array, will it pad the fast index?

**Comment by hcedwar** [comment]
Can let the layout default.
LayoutLeft pads the first (left-most, fastest striding) dimension.
LayoutRight pads the subarrays defined by the second-thru-last dimensions.

**Comment by mcarilli** [comment]
ah i see.  This may be exactly what I need.  One more point of curiosity, if you'll indulge me:  For LayoutRight, why do you pad all of the subarrays defined by the second-through-last dimensions?
Isn't padding the fastest (in this case the rightmost) dimension sufficient?

**Comment by hcedwar** [comment]
Given the first dimension is the parallel work dimension the second-thru-last dimensions typically define a block of values upon which a unit of parallel work is performed.  So these values are kept contiguous and those blocks are cache-aligned.
Note AllowPadding is not guaranteed to introduce padding.  There is an evaluation during allocation of "is this dimension large enough to be worth padding."  Thus LayoutRight (N,3) arrays do not have padding for the second dimension, but LayoutLeft (N,3) arrays do have padding of the first dimension for reasonably sized N.

**Comment by mcarilli** [comment]
Well, my point is, I naively expect that padding only the fastest dimension should be enough to ensure that a single thread iterating along the fast dimension of its assigned data will see vector-aligned accesses.
e.g.
```c++
KOKKOS_LAMBDA ( int tid )
{
    for(int j = 0; j < nj; j++ )
    {
        #pragma simd
        for( int i = 0; i < ni; i++ )
            mypaddedview( tid, j, i ) = some work here...
    }
} 
```
If mypaddedview is LayoutRight and the i-dimension is padded, then accessing mypaddedview along an inner loop over i results in vector-aligned accesses for all repetitions over j, even if the j-dimension is not padded. 

I'm not trying to be a bother, I am just quite interested.
