### ISSUE TITLE
Redundant ifdef'ing away of Profiling

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2741]
Right now we ifdef away Profiling in two different ways

1) Preprocessor protection of _calls into_ Profiling
2) Preprocessed alternate implementations of Profiling

So

```c++
#ifdef KOKKOS_ENABLE_PROFILING
Kokkos::Profiling::beginDeepCopy(/**...
#endif
```

And

```c++
#ifdef KOKKOS_ENABLE_PROFILING
void beginDeepCopy(/** stuff */) {
  /** calls to tools */
}
#else
void beginDeepCopy(/** stuff){}
#endif
```

I don't really like having two different mechanisms to avoid the same bug, I'd prefer to pick one. My preference is to maintain callsite ifdef'ing and discard the empty implementations in Profiling, but that's a very mild preference.

**Comment by dalg24** [comment]
We will drop ifdef at callsite

**Comment by DavidPoliakoff** [comment]
Current thoughts on this have changed, in the future we will remove the ifdef'ing off of Profiling altogether. The comparisons to `nullptr` shouldn't cost us enough to be worth maintaining this code

**Comment by DavidPoliakoff** [comment]
Solve in #3115
