### ISSUE TITLE
Older clang and gcc nightly failures on kokkos-dev

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2744]
Since renaming of testing scripts to use the cmake build system, older clang and gcc nightly builds are failing with error messages like:

```
cd /home/ndellin/kokkos/testing/ClangTestAll/TestAll_2020-02-10_12.41.16/clang/4.0.1/Serial-release/core/src && /projects/sems/install/rhel6-x86_64/sems/compiler/clang/4.0.1/base/bin/clang++   -I/home/ndellin/kokkos/testing/ClangTestAll/TestAll_2020-02-10_12.41.16/clang/4.0.1/Serial-release/core/src -I/home/ndellin/kokkos/core/src -I/home/ndellin/kokkos/testing/ClangTestAll/TestAll_2020-02-10_12.41.16/clang/4.0.1/Serial-release  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o -c /home/ndellin/kokkos/core/src/impl/Kokkos_Stacktrace.cpp
/home/ndellin/kokkos/tpls/gtest/gtest/gtest-all.cc:1424:20: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
  typedef unsigned long long BiggestConvertible;  // NOLINT
                   ^  
```

For the above clang case, this is the cmake line called by `test_all_sandia`:
```
cmake -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel6-x86_64/sems/compiler/clang/4.0.1/base/bin/clang++ -DCMAKE_CXX_FLAGS=-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX= -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=RELEASE /home/ndellin/kokkos
```

These modules are loaded:
```
Loading module sems-env
Loading module sems-cmake/3.12.2
Loading module kokkos-env
Loading module kokkos-hwloc/1.10.1/base
Loading module sems-clang/4.0.1
```

Here is the `test_all_sandia` command for this case:

`<PATHTOKOKKOS/scripts/testing_scripts/test_all_sandia clang/4.0.1 --build-list="Serial,Pthreads_Serial"`

Affecting clang/3.7.1, clang/3.8.1, clang/4.0.1, gcc/4.8.4, gcc/4.9.3, gcc/5.3.0

@jeffmiles63 any guess as to the cause?

**Comment by masterleinad** [comment]
Could https://github.com/kokkos/kokkos/pull/2688/commits/e3bbeeffd7fcb944be1451700cea32a21858a334 be responsible?

**Comment by ndellingwood** [comment]
@masterleinad thanks for the link, it looks like these changes from that SHA could be responsible:
```
TARGET_COMPILE_DEFINITIONS(kokkos_gtest PUBLIC "-DGTEST_HAS_PTHREAD=0")
TARGET_INCLUDE_DIRECTORIES(kokkos_gtest PUBLIC ${GTEST_SOURCE_DIR})
#Gtest minimally requires C++11
TARGET_COMPILE_FEATURES(kokkos_gtest PUBLIC cxx_std_11)
```

**Comment by ndellingwood** [comment]
For reference the previous lines were:

```
KOKKOS_TARGET_COMPILE_DEFINITIONS(kokkos_gtest PUBLIC "-DGTEST_HAS_PTHREAD=0")
KOKKOS_TARGET_INCLUDE_DIRECTORIES(kokkos_gtest PUBLIC ${GTEST_SOURCE_DIR})
```

**Comment by jeffmiles63** [comment]
is it possible the c++ extensions option got dropped when we removed the   
target_link_libraries(
    ${NAME}
    PUBLIC kokkos
  )
from fake_tribits.cmake?

**Comment by ndellingwood** [comment]
@jjwilke @jeffmiles63 would either of you have time to take a look? I'm not comfortable touching the cmake build system.

The errors can be reproduced on kokkos-dev-2 as follows:

```bash
module load sems-env sems-cmake/3.12.2 sems-clang/3.8.1

export KOKKOS_PATH=${HOME}/kokkos

cmake -DCMAKE_CXX_COMPILER="`which clang++`" -DCMAKE_CXX_FLAGS="-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized"  -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH

make -j
```

**Comment by jeffmiles63** [comment]
I will take a look this afternoon

**Comment by masterleinad** [comment]
Restoring the previous (working) behavior and still making sure that `KOKKOS_ADD_EXECUTABLE` always links `Kokkos` in, you could try to have
```
IF (PARSE_TESTONLYLIBS)
  TARGET_LINK_LIBRARIES(${EXE_NAME} PRIVATE ${PARSE_TESTONLYLIBS})
ELSE()
  TARGET_LINK_LIBRARIES(${EXE_NAME} PRIVATE kokkos)     
ENDIF()
```
in that function and revert the changes to `KOKKOS_ADD_TEST_LIBRARY`.

**Comment by jjwilke** [comment]
That shouldn't make a difference, though, right? You're supposed to get `-std=c++11` because of `target_compile_features`.  Depending on something with `cxx_std_11` in `INTERFACE_COMPILE_FEATURES` shouldn't be any different from explicitly having `cxx_std_11` in your `COMPILE_FEATURES.

**Comment by jjwilke** [comment]
Fixed. We have two gtest libraries and `cxx_std_11` was only added to one. This only got triggered with `-Werrror`.

https://github.com/kokkos/kokkos/pull/2748

**Comment by jeffmiles63** [comment]
looks like `TARGET_COMPILE_FEATURES(kokkos_gtest PUBLIC cxx_std_11)` does not actually work with cmake 3.12.2 and clang 3.8.1

I've tried several different options, but the only thing that seems to work is adding 
`
target_link_libraries(
${NAME}
PUBLIC kokkos
)
`
back into fake_tribits.cmake

**Comment by jjwilke** [comment]
@jeffmiles63 Did you try on the PR branch? It's not `kokkos_gtest` that was the issue. It was `kokkosalgorithms_gtest`

**Comment by jeffmiles63** [comment]
I'll try that

**Comment by ndellingwood** [comment]
PR #2748 merged in with fix.
