### ISSUE TITLE
threads sleep and finalization.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#275]
I somehow need to use both OpenMP and Pthreads. What i did 
```
Kokkos::initialize(); // OpenMP becomes default
Kokkos::Threads::initialize(); // Pthreads is also activated

Kokkos::Threads::sleep(); // Pthreads sleeps now 

// do some OpenMP work.

Kokkos::Threads::wake(); // Pthreads awake

// do some task parallel work with Pthreads

Kokkos::Threads::sleep(); // Pthreads sleep

Kokkos::Threads::finalize(); // spinwait waits forever here
Kokkos::finalize();
```
A problem is that if finalization  sees all threads are sleeping, it waits forever.
```
Program received signal SIGINT, Interrupt.
Kokkos::Impl::spinwait (flag=@0x9e6ab0: 2, value=value@entry=2)
    at /home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/impl/Kokkos_spinwait.cpp:81
81	  while ( value == flag ) {
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.1.x86_64 libgcc-4.4.7-16.el6.x86_64 libgfortran-4.4.7-16.el6.x86_64 libgomp-4.4.7-16.el6.x86_64 libstdc++-4.4.7-16.el6.x86_64 libxml2-2.7.6-20.el6.x86_64 mpich-3.1-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  Kokkos::Impl::spinwait (flag=@0x9e6ab0: 2, value=value@entry=2)
    at /home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/impl/Kokkos_spinwait.cpp:81
#1  0x0000000000490c33 in Kokkos::Impl::ThreadsExec::fence ()
    at /home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Threads/Kokkos_ThreadsExec.cpp:322
#2  0x000000000049249a in Kokkos::Impl::ThreadsExec::finalize ()
```
gdb output is attached.

A question is that should I wake all threads first ? Or Kokkos finalization wake all threads if they are sleeping ? 

Another question is that I found OpenMP also has sleep and wake functions but not implemented. Can we have such functionalities ? I was a bit confused as OpenMP has an explicit parallel region.

**Comment by hcedwar** [comment]
Yes - wake the Threads back-end before finalizing.

**Comment by mhoemmen** [comment]
> Another question is that I found OpenMP also has sleep and wake functions but not implemented. Can we have such functionalities ? I was a bit confused as OpenMP has an explicit parallel region.

Right, but OpenMP implementations may maintain their own pool of worker threads that persist across parallel regions.  OpenMP gives us no way to shut down those threads or force them to sleep.
