### ISSUE TITLE
Document precedence of environment variables vs. command-line arguments vs. InitArguments in Kokkos::initialize

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#2756]
@mdmosby requested this for Kokkos' documentation.

See also #2719.  This currently is affecting Sierra.

**Comment by dalg24** [comment]
I updated the wiki earlier today.  What other place need update?

**Comment by mdmosby** [comment]
It is not clear from the documentation whether the environment or command line options/InitArguments takes precedence (unless I am missing something in scanning the documentation).

**Comment by dalg24** [comment]
Actually we check that if both the command-line argument (or member of `Kokkos::InitArguments`) and the environment variable are provided we throw an exception if both are not matching.

**Comment by mhoemmen** [comment]
@dalg24 Thanks for the info!  Would you happen to know about when that became true?

**Comment by masterleinad** [comment]
This was added in https://github.com/kokkos/kokkos/pull/1890.

**Comment by dalg24** [comment]
> This was added in #1890.

Which means it has been implemented this way from the very beginning ;)

**Comment by dalg24** [comment]
As for command-line arguments vs `InitArguments` you have to chose when you call `Kokkos::initialize()`.
