### ISSUE TITLE
Member to access label of view

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#276]
Simple question but I can't find it easily in documentation:
Suppose I have `View<int*>( "label", n ) myview;`
Is there a member to access "label"?

Regards,
Michael

**Comment by crtrott** [comment]
yes there is: myview.label();

**Comment by crtrott** [comment]
yes there is: myview.label();

**Comment by mcarilli** [comment]
good, thanks for quick reply

**Comment by mcarilli** [comment]
I discovered that when calling label() on a Subview, it returns the label of the parent View, which makes sense because I don't supply a label when constructing subviews.

Is it possible to assign a unique label to a Subview?

**Comment by hcedwar** [comment]
No - the label is associated with the allocation.

**Comment by mcarilli** [comment]
understood, thanks.

**Comment by crtrott** [comment]
That is not possible. The reason is that some of the metadata is actually shared between a subview and its parent. That part of the metadata lives as part of the allocation (i.e. it lives the 512 bytes or so before your actual data starts).
