### ISSUE TITLE
PGI/18.7.0 static_assert in Kokkos_TaskBase.hpp causing OpenMP_Serial compilation failure

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2768]
Kokkos fails to compile with pgi/18.7.0 with OpenMP and Serial execution spaces enabled with the following message:

```bash
cd /ascldap/users/ndellin/kokkos/testing/Blake-Testing/core/src && /home/projects/x86-64/pgi/2018/18.7.0/linux86-64/18.7/bin/pgc++   -I/ascldap/users/ndellin/kokkos/testing/Blake-Testing/core/src -I/ascldap/users/ndellin/kokkos/core/src -I/ascldap/users/ndellin/kokkos/testing/Blake-Testing  -fast -O3 -DNDEBUG   -mp --c++11 -A -o CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o -c /ascldap/users/ndellin/kokkos/core/src/impl/Kokkos_Core.cpp
"/ascldap/users/ndellin/kokkos/core/src/impl/Kokkos_TaskBase.hpp", line 225:
          error: static assertion failed with "Verifying expected
          sizeof(TaskBase)"
  static_assert(sizeof(TaskBase) == 48, "Verifying expected sizeof(TaskBase)");
```

**Reproducer Instructions**:

This was demonstrated on the Blake testbed with Skylake arch

```
module load pgi/18.7.0 cmake/3.12.3

<KOKKOS_PATH>/generate_makefile.bash \
    --arch=SKX \
    --compiler=pgc++ \
    --with-devices=OpenMP,Serial
```

**Comment by masterleinad** [comment]
I can compile the tests with `pgi/18.7` on `Summit`. So `Power9` seems to work with that configuration.

**Comment by dhollman** [comment]
Wait... why are we still using `generate_makefile.bash`?  Also, this should theoretically be in the part of the tasking code that I didn't change, not the new stuff, so I don't know what's going on here. I'll take a look.

**Comment by ndellingwood** [comment]
> why are we still using `generate_makefile.bash`

@dhollman the script is updated to take the same arguments as the old gnu-makefile based script and call cmake appropriately to generate the makefile. All the nightlies either use this or test_all_sandia (which calls generate_makefile.bash) so we still use it for convenience.

**Comment by dhollman** [comment]
Ah, okay. Sorry about the confusion. I'll take a look at this today

**Comment by dhollman** [comment]
This appears to be because this particular version of PGI implements `int16_t` as 4 bytes. There's really no reason we need to be asserting this anyway (AFAICT it was just being done for performance reasons, so that as many different task types fit in to one cache line as possible).

Once I fix this, though, there are other bugs, including an internal compiler error in `TestOffsetView.hpp`:

```
"/ascldap/users/dshollm/kokkos/source/containers/unit_tests/TestOffsetView.hpp"
          , line 361: internal error: assertion failed: lower_constant: bad
          kind (../src/lower_il.c, line 5118)

      ASSERT_NO_THROW(offset_view_type(&s, {0}, {0x7fffffffffffffffl}));
      ^
```

So my question is: was this compiler ever working? Do we need to still support it?

**Comment by ndellingwood** [comment]
> was this compiler ever working?

It was passing nightly tests prior to exchanging generate_makefile scripts to use the CMake build system, not sure what crept in between that time and reporting the bug to cause the new issues.



> Do we need to still support it?

@crtrott does this particular version of pgi need to be supported? I'll scan through the testbeds for any newer versions available.

**Comment by crtrott** [comment]
We can go to 19 if that works. Just ask the testbed team to get those installed.

**Comment by ndellingwood** [comment]
Just tested pgi/19.4 on kokkos-dev-2 to replace the 18.7 build (which has the errors David mentioned above). Seeing seg faults in some of the tests, will close this and open a new issue.
