### ISSUE TITLE
Building against Trilinos/Kokkos does not work

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#2779]
Use case: a project A uses both Trilinos and library B which uses Kokkos. In this case, if B uses standalone installation of Kokkos, A will get duplicated Kokkos headers from Trilinos and that installation, which may also be incompatible, as Trilinos and standalone Kokkos installation could be configured in a different way. A specific example of this use case is ExaWind project, where Nalu would use Trilinos and ArborX. This can also be a problem for Spack installations.

Prior to release 3.0, it was possible to manually create a `Kokkos::kokkos` target based on Trilinos installation using `kokkos.pc` and `KokkosConfig.cmake` files. See, for example, [here](https://github.com/arborx/ArborX/blob/acbb518f2bf7d93f47c63513d7b5742871b8e274/cmake/FindKokkos.cmake).

The new release made it much harder. Specifically, it used to be that `kokkos.pc` contained `Cflags` that had all "interesting" flags without fluff. For example, it had `-fopenmp`, CUDA specific flags, `--std`. In the new version, however, it only has `-I${includedir}` and nothing else. The only place now that contains the flags in the installation is `Kokkos_CXX_FLAGS`. Unfortunately, it also contains a bunch of other flags used for compiling Kokkos but not useful for linking against it (e.g., `-pedantic`, `-Wall`, `-O2`, `-g`, etc).

I would hope that we could find a way to allow external application to be built against Trilinos installation of Kokkos. It seems that if Kokkos could provide the flags required for linking against it in a separate variable, that could be sufficient.

In addition, it would be nice if it installed `KokkosConfigVersion.cmake` so that applications did not need to check the version using `kokkos.pc`. The patch to do that is pretty simple:
```diff
--- a/packages/kokkos/cmake/kokkos_install.cmake
+++ b/packages/kokkos/cmake/kokkos_install.cmake
@@ -1,3 +1,5 @@
+INCLUDE(CMakePackageConfigHelpers)
+
 IF (NOT KOKKOS_HAS_TRILINOS)
   INCLUDE(GNUInstallDirs)

@@ -5,7 +7,6 @@ IF (NOT KOKKOS_HAS_TRILINOS)
   GET_PROPERTY(KOKKOS_PROP_LIBS GLOBAL PROPERTY KOKKOS_LIBRARIES_NAMES)
   SET(KOKKOS_LIBRARIES ${KOKKOS_PROP_LIBS})

-  INCLUDE(CMakePackageConfigHelpers)
   CONFIGURE_PACKAGE_CONFIG_FILE(
     cmake/KokkosConfig.cmake.in
     "${Kokkos_BINARY_DIR}/KokkosConfig.cmake"
@@ -32,6 +33,13 @@ ELSE()
   CONFIGURE_FILE(cmake/KokkosConfigCommon.cmake.in ${Kokkos_BINARY_DIR}/KokkosConfigCommon.cmake @ONLY)
   file(READ ${Kokkos_BINARY_DIR}/KokkosConfigCommon.cmake KOKKOS_CONFIG_COMMON)
   file(APPEND "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/KokkosConfig_install.cmake" ${KOKKOS_CONFIG_COMMON})
+
+  WRITE_BASIC_PACKAGE_VERSION_FILE("${CMAKE_CURRENT_BINARY_DIR}/KokkosConfigVersion.cmake"
+      VERSION "${Kokkos_VERSION}"
+      COMPATIBILITY SameMajorVersion)
+
+  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/KokkosConfigVersion.cmake
+      DESTINATION "${${PROJECT_NAME}_INSTALL_LIB_DIR}/cmake/${PACKAGE_NAME}")
 ENDIF()

 # build and install pkgconfig file
```

**Comment by jjwilke** [comment]
There's already a `Kokkos::kokkos` target in `KokkosConfig.cmake`. You shouldn't need to build one anymore from a `kokkos.pc`.

**Comment by aprokop** [comment]
@jjwilke You sure about that in the Trilinos build? I don't see any in the Trilinos installation. For example, `KokkosTargets.cmake` is not getting installed. I see some files like `KokkosCoreTargets.cmake` and `KokkosAlgorithmsTargets.cmake`, but they also seem not have it.

**Comment by jjwilke** [comment]
Sorry, you're saying you want to construct a `Trilinos::Kokkos` target from the Trilinos install, not a `Kokkos::kokkos` target from the standalone Kokkos?

**Comment by aprokop** [comment]
I want to construct `Kokkos::kokkos` target from the Trilinos install.

**Comment by jjwilke** [comment]
You'll probably want to name it `Trilinos::kokkos` to avoid naming clashes with the standalone target `Kokkos::kokkos`. Supporting pkg-config is not so easy with modern CMake for a variety of reasons - so it's not really supported anymore. You can get all the same information (for now) from `Kokkos_{}` variables in the Trilinos-installed config files. That being said, Trilinos does install target files. It does it for the individual subpackages - so you could also use the installed `kokkoscore`, target, e.g. Look for `KokkosCoreConfig.cmake` and `KokkosCoreTargets.cmake`, e.g.

**Comment by aprokop** [comment]
In Trilinos, I do see (non-namespaced) `kokkoscore`, `kokkosalgorithms` and `kokkoscontainers` targets. But they don't look like valid targets:
```cmake
# Create imported target kokkoscore
add_library(kokkoscore SHARED IMPORTED)

set_target_properties(kokkoscore PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libdl.so"
)
```
Compare this to standalone target:
```cmake
# Create imported target Kokkos::kokkoscore
add_library(Kokkos::kokkoscore STATIC IMPORTED)

set_target_properties(Kokkos::kokkoscore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:>;\$<\$<COMPILE_LANGUAGE:CXX>:-expt-extended-lambda;-arch=sm_61>;\$<\$<COMPILE_LANGUAGE:CXX>:-Xcudafe;--diag_suppress=esa_on_defaulted_function_ignored>;\$<\$<COMPILE_LANGUAGE:CXX>:-Xcompiler;-fopenmp>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-fopenmp;Kokkos::CUDA;Kokkos::LIBDL"
)
```
None of the `INTERFACE_BLAH` properties are in the Trilinos. And I mentioned in the OP that it is unclear how to get them out of `Kokkos_CXX_FLAGS`.

And yes, of course I would prefer not dealing with `kokkos.pc`.

**Comment by jjwilke** [comment]
The variables are in the KokkosConfig.cmake installed by Trilinos:

````
SET(Kokkos_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../include")

## List of package library paths
SET(Kokkos_LIBRARY_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../lib")

## List of package libraries
SET(Kokkos_LIBRARIES "kokkosalgorithms;kokkoscontainers;kokkoscore")

## Specification of directories for TPL headers
SET(Kokkos_TPL_INCLUDE_DIRS "/usr/tce/packages/cuda/cuda-10.1.243/include")

## Specification of directories for TPL libraries
SET(Kokkos_TPL_LIBRARY_DIRS "")
````

That should hopefully give you what you need for now.  This nonsense will go way in the next few months (hopefully) when we start using real target-based CMake in Trilinos.

**Comment by aprokop** [comment]
Those are fine, but if I understand it right, you are suggesting manually parsing the flags from `Kokkos_CXX_FLAGS` and putting them into separate bins: one for compile features (`-std`), one for compile options (all CUDA flags, `-fopenmp`) and one for dropping (warning options, optimization options, etc). I was hoping that there could be avoid to do that, or an easy way, as this would essentially require replicating part of the `nvcc_wrapper` parsing inside CMake.

**Comment by jjwilke** [comment]
Yeah... this is making your life more difficult.  The `-std` shouldn't show up anymore? But, yes. We can make some small changes to the exported config to make your life easier by dumping what you want into a `Kokkos_COMPILE_OPTIONS` variable in the config. You're looking at a couple week delay, though, before this would make it into Trilinos devel or master.

**Comment by aprokop** [comment]
That would be great! The delay is not a big deal. If there's anything I can help with here, let me know.

**Comment by jjwilke** [comment]
Nah, it's a two-line fix in Kokkos. The delay is just the PR testing and promotion process for Trilinos. What variables do you need?

- [ ] Kokkos_COMPILE_OPTIONS

Anything else?

**Comment by aprokop** [comment]
I think also need something like `Kokkos_COMPILE_FEATURES`. Regarding libraries, I think I can put of the things together from `_LIBRARIES` and `_TPL_LIBRARIES`, but there is a question of how to put `-fopenmp` there too (it is only in `_FLAGS` now). So, the ideal case would be something like a proper `Kokkos_LINK_LIBRARIES`, too.

**Comment by jjwilke** [comment]
@aprokop Can I get some help testing this for your use case? There is now an open PR #2817 with the changes. It creates an exported target `Trilinos::kokkos` that (should) have everything you need.

To test this, you can check out the kokkos branch and use the "source override" feature of Trilinos. 
````
cmake -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos ...
````
Go to the top-level Trilinos source dir and symlink the kokkos branch to `kokkos`
````
trilinos_top_source_dir> ln -s $kokkos_branch_source_dir kokkos
````
Your Trilinos build is otherwise the same.

**Comment by masterleinad** [comment]
See https://github.com/trilinos/Trilinos/pull/7172#issuecomment-614263813

**Comment by crtrott** [comment]
Is there a way of just restarting one of the tests? It looks like the test failure was a system issue?
