### ISSUE TITLE
Question... temporary workspace wrapping with Kokkos view

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#278]
I have the following situation
```
KOKKOS_INELIN_FUNCTION
void doOtherThing(View a, View w) {
  // do other thing with a and w
}

KOKKOS_INLINE_FUNCTION
void doSomething(View a) {
  value_type work[128];
  // Can I wrap temporary stack buffer with a View ? 
  // Several APIs already assume input containers as Kokkos View 
  // and I would like to use such a function with local temporary stack.
  Kokkos::View<value_type,a::memory_space> w(work, 128);
  doOtherThing(a, w); 
}
```
I know that the current Kokkos View cannot be used inside of a functor nor device function. Can you allow inline decoration for Kokkos View when it is wrapping a buffer ?

**Comment by crtrott** [comment]
If you make the view unmanaged that should work.

**Comment by hcedwar** [comment]
Will even work with "managed" view since constructing with a pointer makes it runtime-unmanaged, which is slightly greater overhead than trait-unmanaged.

**Comment by kyungjoo-kim** [comment]
Oh.. I probably misunderstand the view constructor. In this example, I use memory space of other input containers. Do we have a better name for this space ? This wrapping is not necessary to be named like Cuda or HostSpace as this buffer is always accessible from functors.

**Comment by hcedwar** [comment]
If you assume the pointer is valid for the current execution space then you can use:
  Kokkos::Impl::ActiveExecutionMemorySpace

**Comment by kyungjoo-kim** [comment]
Oh..... that is a nice solution.
