### ISSUE TITLE
Thank you for Kokkos!

### ISSUE THREAD

**Issue by dmikushin** [kokkos/kokkos#2788]
Hi @crtrott,

I've been following your work since "early days", attended one of the first talks, I think it was GTC'2013. Kokkos is a major ground-break compared to what Labs were doing before you. Your work makes engineering software better in the whole world. I really admire your patience, and wish you and your colleagues a lot of inspiration!

**Comment by crtrott** [comment]
You are welcome :-)

**Comment by PhilMiller** [comment]
Gratitude is appreciated. I don't think we need to track this anymore, though, so closing.
