### ISSUE TITLE
Scratch memory and dynamic scheduling

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#279]
In my application, I have am making use of both team-wise scratch memory and dynamic scheduling. 

I recently discovered that when the number of teams exceeds the number of threads, I get a scratch memory allocation error sometimes (there is some undefined behavior somewhere). 

The errors do not occur if either the number of teams is < number of threads OR if I am not using dynamic scheduling. 

Is scratch memory and dynamic scheduling supposed to be incompatible?

reproducer of error attached.

[scratch_mem.zip](https://github.com/kokkos/kokkos/files/263657/scratch_mem.zip)

**Comment by crtrott** [comment]
No this is supposed to work. I will have a look.

**Comment by crtrott** [comment]
Just to let you know I replicated the issue, even after fixing some minor things in the reproducer (the mem_size should come from View<double*>::shmem_size(N), the member_type should come from TeamPolicy<dynamic_schedule>, and there are two using TeamPolicy statements). 

I am now trying to track down where this is coming from, and hope to get it fixed this week.

**Comment by crtrott** [comment]
Could you test if this fixes it for you?

**Comment by dholladay00** [comment]
With gcc 5.2.0 and the openmp backend, it works. However, with intel 16.0.1 and the openmp backend, the error remains. Could you see if things work on your end with intel compilers?

**Comment by dholladay00** [comment]
I have changed to intel 16.0.3 (from 16.0.1) and am no longer seeing those errors with dynamic scheduling with OpenMP! (I have only tested with OpenMP backend with gcc and intel compilers)
