### ISSUE TITLE
Change in Kokkos::UnorderedMap?

### ISSUE THREAD

**Issue by spdomin** [kokkos/kokkos#2794]
New build errors in Nalu under the Mac platform last night:

02/25/2020
PROCESS FAILED
NaluCFD/Nalu SHA1: 12e91f603c381fef17fdda414a72b7e7b90dde8c
Trilinos/develop SHA1: 04fb99e8c6aad84597014a791b449648c325d01e

[  1%] Building CXX object CMakeFiles/nalu.dir/src/FixPressureAtNodeAlgorithm.C.o
In file included from /Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/src/FixPressureAtNodeAlgorithm.C:12:
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Nalu/include/TpetraLinearSystem.h:225:38: error: no template named 'UnorderedMap' in namespace
      'Kokkos'; did you mean 'std::unordered_map'?
void copy_kokkos_unordered_map(const Kokkos::UnorderedMap<T1,T2>& src,
                                     ^~~~~~~~~~~~~~~~~~~~
                                     std::unordered_map

Any help would be appreciated.

**Comment by dalg24** [comment]
Did you make sure you included `Kokkos_UnorderedMap.hpp`?

**Comment by spdomin** [comment]
This is old code, however, I will make sure that this is the case and report back. Thanks.

**Comment by spdomin** [comment]
Looks like @alanw0 added a copy_kokkos_unordered_map() - a method that is no longer used...

At any rate, adding the header resolved the clang build issue and I am proceeding with simply removing the method.

I will close this once the code is pushed. Side question: is there a tool that checks for spurious member methods and member data?

**Comment by spdomin** [comment]
https://github.com/NaluCFD/Nalu/commit/261d8884e6dcc142647ed6a28ff3747540f7bdea

Thanks @dalg24

**Comment by alanw0** [comment]
If the function is no longer used then removing it is the best solution. It looks like I inexplicably removed the include for Kokkos_UnorderedMap.h in June of 2018. Why is it suddenly an issue now? I guess it doesn't matter now that the function is removed.

**Comment by dalg24** [comment]
> If the function is no longer used then removing it is the best solution. It looks like I inexplicably removed the include for Kokkos_UnorderedMap.h in June of 2018. Why is it suddenly an issue now? I guess it doesn't matter now that the function is removed.

Most likely transitive inclusion from one of your dependency.  Nothing changed on the Kokkos side.
