### ISSUE TITLE
Kokkos::CountAndFillBase uses Crs::size_type as data_type

### ISSUE THREAD

**Issue by PhilipFackler** [kokkos/kokkos#2811]
In both versions of `Kokkos::CountAndFillBase` (in Kokkos_Crs.hpp) define the alias `using data_type = CrsType::size_type;` in addition to `using size_type = CrsType::size_type;`. This seems like a typo/copy-paste error. Should they not use `CrsType::data_type` for `data_type`?

I saw this because of a compiler error where the two types in question are different. In the call operator for `Fill` there is an assignment of a value of type `CrsType::data_type *` (from `&m_crs.entries(j)`) to a variable of type `data_type *`.

**Comment by dalg24** [comment]
Thanks for reporting this.
