### ISSUE TITLE
ScatterView memory space is not user settable

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2826]
I'm trying to use a `ScatterView` with `force_uvm` in LAMMPS. I get a compile error 

```
../../lib/kokkos/core/src/Kokkos_View.hpp(2006): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void>::type *) [with DataType=F_FLOAT *[3], Properties=<Kokkos::LayoutRight, LMPHostType>, RT=LMP_FLOAT *[3], RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>]"
../../lib/kokkos/containers/src/Kokkos_ScatterView.hpp(697): here
            instantiation of "Kokkos::Experimental::ScatterView<DataType, Layout, ExecSpace, Op, 0, contribution>::ScatterView(const Kokkos::View<RT, RP...> &) [with DataType=F_FLOAT *[3], Op=0, ExecSpace=LMPHostType, Layout=Kokkos::LayoutRight, contribution=0, RT=LMP_FLOAT *[3], RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>]"
../../lib/kokkos/containers/src/Kokkos_ScatterView.hpp(1283): here
            instantiation of "Kokkos::Experimental::ScatterView<RT, Kokkos::ViewTraits<RT, RP...>::array_layout, Kokkos::ViewTraits<RT, RP...>::execution_space, Op, <expression>, <expression>> Kokkos::Experimental::create_scatter_view(const Kokkos::View<RT, RP...> &) [with Op=0, duplication=0, contribution=-1, RT=LMP_FLOAT *[3], RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>]"
../pair_kokkos.h(90): here
```
I tracked it down to a type-mismatch, where `ScatterView::internal_view` omitted the memory_space:

Internal View: `Kokkos::View<F_FLOAT *[3], Kokkos::LayoutRight, LMPHostType>`

Original View: `const Kokkos::View<LMP_FLOAT *[3], Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>`

If I hack the code like this then it compiles:

```patch
diff --git a/lib/kokkos/containers/src/Kokkos_ScatterView.hpp b/lib/kokkos/containers/src/Kokkos_ScatterView.hpp
index a8c05e3..1d83aed 100644
--- a/lib/kokkos/containers/src/Kokkos_ScatterView.hpp
+++ b/lib/kokkos/containers/src/Kokkos_ScatterView.hpp
@@ -681,7 +681,7 @@ class ScatterView<DataType
                    ,contribution>
 {
 public:
-  typedef Kokkos::View<DataType, Layout, ExecSpace> original_view_type;
+  typedef Kokkos::View<DataType, Layout, Kokkos::Device<ExecSpace, Kokkos::Cuda::memory_space> > original_view_type;
   typedef typename original_view_type::value_type original_value_type;
   typedef typename original_view_type::reference_type original_reference_type;
   friend class ScatterAccess<DataType, Op, ExecSpace, Layout, ScatterNonDuplicated, contribution, ScatterNonAtomic>;
```

**Comment by crtrott** [comment]
What are you actually trying to do? I.e. what is the ScatterView type you instantiate, what is the Type of the original view you pass to it?

**Comment by stanmoore1** [comment]
I'm just trying to compile LAMMPS with `force_uvm` so we can run problems larger than fit in GPU memory by automatically paging back and forth between GPU and CPU.

**Comment by crtrott** [comment]
wow that sounds like a horrible idea *haha* 

whats your build command?

**Comment by stanmoore1** [comment]
Here is the ScatterView type: https://github.com/lammps/lammps/blob/master/src/KOKKOS/pair_kokkos.h#L70. The ScatterView is wrapping the atom force array.

To build I'm setting `force_uvm` in `KOKKOS_CUDA_OPTIONS` in `Makefile.kokkos`, https://github.com/lammps/lammps/blob/master/lib/kokkos/Makefile.kokkos#L34. It builds fine if I don't use `force_uvm`.

**Comment by stanmoore1** [comment]
>wow that sounds like a horrible idea haha

Hahaha :)

**Comment by crtrott** [comment]
got it reproduced looking into it

**Comment by stanmoore1** [comment]
Great thanks.

**Comment by crtrott** [comment]
The problem is actually that you try to instantiate a ScatterView for the Host Execution Space and hand it a view of RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space> (i.e. Device<Serial,CudaUVMSpace> to a scatter view of Device<Serial,HostSpace>).

**Comment by crtrott** [comment]
At least as far as I can tell.

**Comment by stanmoore1** [comment]
Yeah I agree, but there is no way in Kokkos that I can see to set the memory space for a `ScatterView`. It isn't an option in the parameter list. I.e. I want a `ScatterView` with `Device<Serial,CudaUVMSpace>`, how do I get that?

**Comment by stanmoore1** [comment]
Maybe a better title for this issue would be "ScatterView memory layout is not user settable."

**Comment by stanmoore1** [comment]
I meant memory space, not memory layout. Edited the previous post.

**Comment by crtrott** [comment]
Yeah something like that.

**Comment by crtrott** [comment]
I think I got it. Basically it allows you to use a DeviceType as the argument the same as views. But you need to make sure that this all matches up with the original view.

**Comment by stanmoore1** [comment]
So are you saying in LAMMPS I need to set the `DeviceType` of the `ScatterView` as `Kokkos::Device<Serial,CudaUVMSpace>` instead of just `LMPHostType` = `Kokkos::Serial`?

**Comment by crtrott** [comment]
Yeah probably.

**Comment by stanmoore1** [comment]
OK I didn't think of that, thanks. I'll try it out.

**Comment by crtrott** [comment]
Though that doesn't work yet! I have the fix which makes that work but need to write some unit tests before issuing the PR.

**Comment by stanmoore1** [comment]
OK thanks for looking into this.

**Comment by crtrott** [comment]
PR issueed.

**Comment by crtrott** [comment]
Fixed.
