### ISSUE TITLE
question: hwloc compatibility with OpenMP

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#283]
Quite while ago, I realized that when I use OpneMP I should turn off hwloc. Is this still required ? Also with Pthreads tasking, hwloc is essential, right (this was required when it is first developed) ? 

Then a problem is when I use Pthreads tasking and OpenMP together, how can I set up hwloc ?

**Comment by ndellingwood** [comment]
Cannot use OpenMP and Pthreads together.
HWLOC and OpenMP can work together.
