### ISSUE TITLE
Excessive warnings after kokkos update

### ISSUE THREAD

**Issue by kvmatsuno** [kokkos/kokkos#2832]
We recently updated to the latest version of the Kokkos library used to compile our code, and now we receive multiple unused parameter warnings at compile time from Kokkos header files.  

We would like to limit the Kokkos compilation warnings and only have warnings associated with our code. With the previous version of Kokkos, we were able to mute these warnings by including the `Kokkos_INCLUDE_DIRS_RET` using the `SYSTEM` keyword in the CMakeLists.txt for the file (see sample below). With the updated Kokkos library, this `Kokkos_INCLUDE_DIRS_RET ` directory appears to be empty or unset by Kokkos. 

We have included below a sample code and corresponding cmake file that demonstrates the warning (the `KOKKOS_ROOT_DIR` environment variable must be set).

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.10)
project(HelloWorld)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(Kokkos_ENABLE_CXX11  ON CACHE BOOL "Enable C++11")
set(Kokkos_ENABLE_OPENMP ON CACHE BOOL "Enable OpenMP")
set(Kokkos_ENABLE_COMPILER_WARNINGS OFF CACHE BOOL "Disable compiler warnings")

add_subdirectory($ENV{KOKKOS_ROOT_DIR} ${CMAKE_CURRENT_BINARY_DIR}/kokkos)

set(COMPILER_WARNING_FLAGS -Wall -Wextra -pedantic)
add_executable(hello hello.cpp)
target_include_directories(hello SYSTEM PUBLIC ${Kokkos_INCLUDE_DIRS_RET})
target_link_libraries(hello kokkoscore kokkoscontainers)
target_compile_options(hello PRIVATE ${COMPILER_WARNING_FLAGS})
```

The sample code:
```c++
#include <cstdio>
#include "Kokkos_Core.hpp"

int main(int argc, char* argv[]) {
    (void) argc;
    (void) argv;
    printf("HelloWorld!\n");
    return 0;
}
```

**Comment by masterleinad** [comment]
See https://stackoverflow.com/questions/52135983/cmake-target-link-libraries-include-as-system-to-suppress-compiler-warnings for a workaround.

On the other hand, we are also looking into addressing `-Wextra` in #2796 and #2804.
