### ISSUE TITLE
arm/gcc7.2 nightly serial build error - Kokkos_LIFO.hpp:56:10: fatal error

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2846]
This error just began showing up in the nightlies on the mayer testbed (arm arch) 03/09/2020, potentially related to changes from #2655 

Mayer reproducer instructions:

```
Log into mayer

salloc -N 1
srun -N 1 --ntasks-per-node=1 -t 300 kokkos/scripts/testing_scripts/test_all_sandia gnu7/7.2.0 --build-list="OpenMP,Serial,Pthreads_Serial" --num=3 --skip-hwloc
```

generate_makefile line
```
module load cmake/3.12.2 gnu7/7.2.0

<KOKKOS_PATH>/generate_makefile.bash --with-serial --compiler=g++ --cxxflags="-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized" --arch=ARMv8-TX2
```

Error message:

```
18:21:23 /home/jenkins/mayer/workspace/Kokkos_develop_mayer_gcc_720/kokkos/core/src/impl/Kokkos_TaskQueue.hpp:61:10: fatal error: /home/jenkins/mayer/workspace/Kokkos_develop_mayer_gcc_720/kokkos/core/src/impl/Kokkos_Memory_Fence.hpp: Input/output error
18:21:23  #include <impl/Kokkos_Memory_Fence.hpp>
18:21:23           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:21:23 compilation terminated.
```

@crtrott @masterleinad

**Comment by crtrott** [comment]
This is likely not a code issue but a system issue (i.e. file system)

**Comment by ndellingwood** [comment]
Yeah, looks like the modules were updated yesterday. Put in PR #2847 to update testing scripts, will close this out if nightlies pass tonight.

**Comment by ndellingwood** [comment]
Mayer is still having issues (can't get on compute nodes manually or via Jenkins jobs), will report back once system issues are cleared up and there are new results.
