### ISSUE TITLE
Wide variance in OpenMP wall time

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#285]
Hello Kokkos Team,

I am testing code (consisting purely of parallel_for loops) on a node with two 10-core CPUs.  

The single-core serial runtime of my application is 7.13 seconds.
When I export OMP_NUM_THREADS=20 and run the application multiple times, sometimes it runs in 0.38 seconds.  7.13/0.38 = 18.7X, so I am achieving almost linear speedup across 20 cores, which is good.

However, often (more than half the time) the application takes 0.68 sec, or 0.58, or 0.5, or some other value that is greater than 0.38 seconds.  My only guess is that it has something to do with how threads are dynamically assigned to cores by openmp.  Naturally I'd like to ensure that it runs in 0.38 sec every time.  Do you have any thoughts?

Much appreciated,
Michael

**Comment by crtrott** [comment]
You need to apply binding. Assuming you don't do MPI this goes through the environment variable:
GOMP_CPU_AFFINITY=0-19 for a GNU compatible runtime (works with GCC and Intel for example). 
With Intel you could also use KMP_AFFINITY=compact or KMP_AFFINITY=scatter. The former would put threads on hyper threads in a dense fashion. So if you have hyper threading enabled you would only get a single socket, and you would need to increase number of OpenMP threads to 40.

**Comment by mcarilli** [comment]
That works perfectly, thanks.
