### ISSUE TITLE
Spack configuration for Cori

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2853]
We need to provide a packages.yaml containing the suggested variant list for Cori (both Haswell and MKL)

**Comment by PhilMiller** [comment]
Cori is slated for retirement next month:

> [Cori Retirement](https://docs.nersc.gov/systems/cori/#cori-retirement)
> 
> Cori had its first users in 2015, and since then, NERSC's longest running system has been a valuable resource for thousands of users and projects. With the complete Perlmutter system scheduled to be operational for the 2023 allocation year, NERSC plans to decommision Cori at the end of the 2022 allocation year on January 17, 2023.
