### ISSUE TITLE
Cannot choose multiple, specific devices

### ISSUE THREAD

**Issue by sswan** [kokkos/kokkos#2868]
When I'm running on a multi-gpu machine, I am able to run on ONE specific GPU by giving "--kokkos-device=INT". I cannot find documentation of how to run a multi-gpu run using specific GPUs. I also haven't been able to figure it out through trial-and-error.

My use-case is being on a 4 GPU machine and running many jobs - some are 1 GPU, some are 2, etc. When all the GPUs are full and one or more finish, I may have a 2 GPU job that I want to run but am not able to tell it to use the free devices 1 and 3.

If this currently isn't an option, can we make it something like "--kokkos-device=[1,3]"?

**Comment by sswan** [comment]
I found my answer - but an easier way of doing this would be nice.

```
mpiexec -n 1 a.out --kokkos-device 0 : -n 1 a.out --kokkos-device 2
```

**Comment by mhoemmen** [comment]
`--kokkos-num-devices` may help: https://github.com/kokkos/kokkos/wiki/Initialization
