### ISSUE TITLE
clang -Werror: Kokkos_FixedBufferMemoryPool.hpp:140:28: error: unused parameter 'alloc_size'

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#2869]
clang/3.8.1, clang/4.0.1 Serial and Pthread and clang/8 nightly builds are failing with `-Werror` enabled with this message:

```
/home/jenkins/slave/workspace/Kokkos_develop_kokkos-dev_clang_381/kokkos/core/src/impl/Kokkos_FixedBufferMemoryPool.hpp:140:28: error: unused parameter 'alloc_size' [-Werror,-Wunused-parameter]
```

Reproducer sample:
```
 #   Load modules:
        module load sems-env sems-cmake/3.12.2 kokkos-env kokkos-hwloc/1.10.1/base sems-clang/3.8.1

  #   Use generate_makefile line below to call cmake which generates makefile for this build:
        <KOKKOS_PATH>/generate_makefile.bash --with-devices=Serial --arch=Kepler35 --compiler=/projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.8.1/base/bin/clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="11" --ldflags=""  --kokkos-path=<KOKKOS_PATH> --no-examples --with-options=enable_large_mem_tests
```

**Comment by ndellingwood** [comment]
Updated title, apparently this is not specific to older clang compilers. Looks to occur following PR #2838 ; in the `allocate` routine where this is triggered there is a macro `KOKKOS_EXPECTS(alloc_size <= Size);` that is called but only defined when debugging is enabled; maybe the non-debug should pass args on to `KOKKOS_IMPL_SINK`?

**Comment by ndellingwood** [comment]
These macros all have potential to be problematic with `-Wunused-parameter` when the `#else` branch is hit:

https://github.com/kokkos/kokkos/blob/fe86da35221c637459f161cbb17a8604cdbe0563/core/src/impl/Kokkos_Error.hpp#L216-L222

**Comment by masterleinad** [comment]
> `` that is called but only acts on args when debugging is enabled; maybe the non-debug should pass args on to `KOKKOS_IMPL_SINK`?

We can just use
```
(void)alloc_size;
```
here. We were not seeing this one because we don't enable large memory tests in the CI.
