### ISSUE TITLE
build on musl libc fails due to missing execinfo.h used for stack tracing

### ISSUE THREAD

**Issue by junghans** [kokkos/kokkos#2873]
On system using musl libc the build fails with:
```
/usr/bin/x86_64-gentoo-linux-musl-g++ -Dkokkoscore_EXPORTS -Icore/src -I/var/tmp/portage/dev-cpp/kokkos-3.0.00/work/kokkos-3.0.00/core/src -I.  -DNDEBUG -O2 -pipe -march=native -fno-common -falign-functions=32:25:16 -fPIC   -fopenmp -MD -MT core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o -MF core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o.d -o core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o -c /var/tmp/portage/dev-cpp/kokkos-3.0.00/work/kokkos-3.0.00/core/src/impl/Kokkos_Stacktrace.cpp
/var/tmp/portage/dev-cpp/kokkos-3.0.00/work/kokkos-3.0.00/core/src/impl/Kokkos_Stacktrace.cpp:6:10: fatal error: execinfo.h: No such file or directory
    6 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
as musl doesn't have a `execinfo.h`.

See https://bugs.gentoo.org/712748

**Comment by crtrott** [comment]
Would you guys be willing to donate PR testing capability to test this? For now musl is not on our support list I guess ...

**Comment by crtrott** [comment]
Is there a way to detect that we are using MUSL? One could turn this off in Kokkos_Macros.hpp at lines 636.

**Comment by junghans** [comment]
@blueness should know...

**Comment by giordano** [comment]
> Is there a way to detect that we are using MUSL?

Not really: https://wiki.musl-libc.org/faq.html

**Comment by PhilMiller** [comment]
We can pretty easily be more direct about this now, using [`__has_include`](https://en.cppreference.com/w/cpp/preprocessor/include) from C++17.

**Comment by PhilMiller** [comment]
I'll add that check now. No guarantees or testing for the broader use of musl libc from me

**Comment by PhilMiller** [comment]
4.0 released with this.
