### ISSUE TITLE
Kokkos Profiling synchronization events

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2876]
Inspired by #2860 and #2862 , I wound up having to diagnose that through stack unwinding from calls to cudaStreamSynchronize.

This is an issue to discuss the introduction of a new callback to Kokkos Profiling, the Kokkos side likely looks something like

```c++
Kokkos::Profiling::syncEvent(/** insert smart set of arguments here */)
```

I'm pretty convinced that some version of this is a good idea. The base version

```c++
Kokkos::Profiling::syncEvent(const SpaceHandle& space, uint32_t deviceId)
```

Where deviceId is as described in #2824 , encoding SERIAL, CUDA, and perhaps eventually distinguishing amongst different instances of those execution spaces.

The next, more aggressive approach would be  

```c++
Kokkos::Profiling::syncEvent(const SpaceHandle& space, uint32_t deviceId, kokkos_sync_reason reason)
```

Where `kokkos_sync_reason` needs a little thought, I immediately can think of KOKKOS_USER_REQUEST, KOKKOS_INTERNAL_COPY_PRESYNC, KOKKOS_INTERNAL_COPY_POSTSYNC, and there's likely several more we would need to discuss.

Adding this third parameter is expensive, but potentially powerful, I worry that without it we'll have users saying "okay, so apparently I copied four times, but why?" If it comes down to it, I'm game to rewrite all of our fence calls to support this, I think it's important.

A third option that everybody will love as it brings in the preprocessor would be

```c++
Kokkos::Profiling::syncEvent(const SpaceHandle& space, uint32_t deviceId, kokkos_sync_reason reason, const char* sourceLocation)
```

And then some macro to extract source location so people can know exactly where their sync calls are coming from. I expect the Kokkos team to hate this, it's exposing Kokkos internals and allowing people to think in terms of implementation rather than intended semantics, but I keep failing to convince myself that it's a bad idea if it's possible.

Thoughts?

**Comment by crtrott** [comment]
The source location version needs a all the way through approach (from the user down) I am a bit wary about. What I would actually do is `Kokkos::Profiling::syncEvent(const SpaceHandle& space, uint32_t deviceId, const char* name)` and add overloads like: `Kokkos::fence("name",space);` We can generate names for the internal fences inside of deep copies, allocations, deallocations, reductions etc. based on the allocation or kernel names.

Like: "Kokkos::FenceReductionToScalar::KernelName" or "Kokkos::DeepCopyFence::AllocationA_AllocationB".

**Comment by DavidPoliakoff** [comment]
Christian and I were discussing this in another channel. I'm game for this kind of implementation. Three argument, with the "reason" enum replaced with a "name" string (`const char*`). Waiting on any feedback from tools folks before we implement

**Comment by daboehme** [comment]
Should "sync" really be a singular event or rather a begin/end style region? Do you want to know how long your sync takes?

Source location you can get through stack unwinding if needed, so I don't think that's really necessary.

**Comment by crtrott** [comment]
Good point about making a sync_begin/end hook ...

**Comment by DavidPoliakoff** [comment]
Yeah, I agree with the begin/end logic.

I'm a little less of a fan of the stack unwinding idea, stack unwinders break, but I think names remove the need for it in simple cases, and we can fix the stack unwinders in complicated cases.

But unless anybody else objects, it'll be a begin/end pair, good call David

**Comment by DavidPoliakoff** [comment]
Via Sameer Shende: string processing can be expensive. Do we want some sort of handle for the sync call, so that we don't have to do string lookups? This takes us a little closer to the enum-based idea we started with... perhaps we could use enums and the Ye Aulde Enum->String and String->Enum function paire based approach

**Comment by crtrott** [comment]
No but you need user provided names don't you? We could add a weird start string in the first 8 bytes which identifies it as a Kokkos internal one though?

**Comment by DavidPoliakoff** [comment]
Perhaps, if we want the handle implementation, we could have name _and_ handle. Users would use a name-based sync, whose handle would be "KOKKOS_SYNC_HANDLE_USER," while internally we would provide a name/handle pair?

For me to think this is a good idea, I'd want to know that the string processing is actually expensive enough to merit this. I'd tend to take Sameer's word on things like that, he has _mildly_ more experience than I do in tool development, but it would be worth exploring. Note that Sameer mentioned he's not opposed to more callbacks being added later (so long as existing interfaces don't change), one implementation might be to do the name-based approach and then add handles if that proves expensive

**Comment by khuck** [comment]
the string processing is only an issue if it happens frequently. :)

Source location would be better (i.e. less overhead) as an address, although this is depends on whether Kokkos has the address at its disposal, and/or whether the string is constructed once or each time this code region is encountered.  For comparison, the OpenACC performance API gives a string, but the OpenMP OMPT interface gives an address (when one is given).

In TAU, the Kokkos API has to demangle/create/hash-lookup a string regardless, so the point is kind of moot...  for example, see https://github.com/UO-OACISS/tau2/blob/220b4d0dca8ac9ee846cf3b58e677b1fbdbd2b2c/src/Profile/TauKokkos.cpp#L101-L112

**Comment by mhoemmen** [comment]
> Adding this third parameter is expensive, but potentially powerful, I worry that without it we'll have users saying "okay, so apparently I copied four times, but why?"

Commenting because I'm interested -- I am in favor of more info : - )

**Comment by jrmadsen** [comment]
My thoughts:

```cpp
Kokkos::Profiling::beginSyncEvent(const SpaceHandle& space, uint32_t deviceId, int ninfo, const char** info, int* id);
Kokkos::Profiling::endSyncEvent(const SpaceHandle& space, uint32_t deviceId, int id);
```
Statically construct `__FUNCTION__` and `__FILE__` and a kokkos specific descriptor into `info[0]`, `info[1]`, and `info[2]` respectively (or something along those lines). Then `info[3]` can be a user string, if provided.
Let the user assign a value to `int* id` so that at the `endSyncEvent`, no string processing would be required.

**Comment by crtrott** [comment]
yeah the id thing we did in the other callback functions too. Again the file descriptor and function pointer don't necessarily help, as long as we don't go to a macro based interface for most of Kokkos. Remember the vast majority of those tool calls are inside the Kokkos API, not introduced by users directly.

**Comment by jrmadsen** [comment]
> Again the file descriptor and function pointer don't necessarily help

Yea I get that, it just sounded like there was a desire to have this info. I think, at the very least, _because_ those calls mostly originate inside the Kokkos API, having that info might be useful for the user trying to find "where" the synchronizations are generated.

**Comment by crtrott** [comment]
But how do we get that info from the user call site? I mean if the user calls `Kokkos::fence();` how do we get the line info in? And having in the tool the info that you have called 1078 times a fence inside of `Kokkos_Core.cpp` is probably not helpful or? Is there a way to make `Kokkos::fence()` tell me where it was called?

**Comment by mhoemmen** [comment]
> Is there a way to make `Kokkos::fence()` tell me where it was called?

@jjellio 's tool can do that, but you need a stack trace library, and it will cost you.

**Comment by jjellio** [comment]
You don't really need backtraces.  We were able to pin down the location of the events in a coarse grain fashion. E.g., we were able to report that deep_copy was the culprit.

The weakness is that *inside* Kokkos we can't see what happens. Adding regions around sync points would let the Kokkos profiler report it, but doing so would be pretty high overhead. That is basically what my tool does. (It uses the Teuchos timers in place of what Kokkos would do)

A good question is why not adopt an LD_PRELOAD type solution for wrapping symbols rather than adding a profiling interface to Kokkos.  Wrapping symbols directly (and calling some type of KokkosP layer in the wrapped symbols).  It's much cleaner from a code maintenance perspective (your library no longer has pervasive profiling embedded).  It doesn't work with static, but who cares?  We wanted this functionality for sanity checking, then we stop using it.

Another concern is how to distinguish between different synchronization types. E.g., a true host side memory fence, a cuda device sync, a stream sync, _____

**Comment by jrmadsen** [comment]
Well my original thought was along the lines of something like this:

```cpp
  ViewCopy(const ViewTypeA& a_, const ViewTypeB& b_) : a(a_), b(b_) {

    FENCE_BEGIN_MACRO(...);    // relevant __FUNCTION__, __FILE__, __LINE__ valid here
    ExecSpace().fence();
    FENCE_END_MACRO(...);  //

    Kokkos::parallel_for(
        "Kokkos::ViewCopy-5D",
        policy_type({0, 0, 0, 0, 0}, {a.extent(0), a.extent(1), a.extent(2),
                                      a.extent(3), a.extent(4)}),
        *this);

    FENCE_BEGIN_MACRO(...);  // etc.
    ExecSpace().fence();
    FENCE_END_MACRO(...);  // etc.
  }
```

Although out of curiosity, I tried to see if there was a way to provide the `Kokkos::fence()` functionality you mentioned in the manner I described. __*Technically*__ would work without backtraces but it would __*definitely*__ break `ExecSpace().fence()` above. I got:

```console
creating context...
[beginSyncEvent: device0/foo/info.cpp:98] ...doing Kokkos::fence... [endSyncEvent]
creating context...
[beginSyncEvent: device0/bar/info.cpp:107/example] ...doing Kokkos::fence... [endSyncEvent]
[beginSyncEvent: device0/foo/info.cpp:98] ...doing Kokkos::fence... [endSyncEvent]
```

from:

```cpp
// regular fence call
void foo() { Kokkos::fence(); }

// fence call with label
void bar() { 
    Kokkos::fence("example"); 
    foo();
}

int main(int argc, char** argv) {
    foo();
    bar();
}
```

with:

```cpp
#include <cstdio>
#include <iostream>
#include <sstream>
#include <string>

// ignore this, for output
template <typename... Args>
std::string join(Args&&... args) { std::stringstream ss; (ss << ... << args); return ss.str(); }

namespace Kokkos
{

// original fence call
void fence() { std::cout << " ...doing Kokkos::fence... "; }

// dummy beginSync
void beginSyncEvent(uint32_t deviceId, int ninfo, const char** info, int* id)
{
    std::cout << join("[beginSyncEvent: device", deviceId, "/", info[0], "/", info[1],
                      ":", info[2], ((ninfo > 3) ? join("/", info[3]).c_str() : ""), "]");
    static int sync_counter = 0;
    *id                     = sync_counter++;
}

// dummy endSync
void endSyncEvent(uint32_t deviceId, int id) { std::cout << "[endSyncEvent]\n"; }

// a class to capture the context. use the function
// call operator to emulate original function call
class capture_context
{
public:
    capture_context(const char* func, const char* file, int line)
    : m_line(std::to_string(line))
    {
        puts("creating context...");
        m_info[0] = func;
        m_info[1] = file;
        m_info[2] = m_line.c_str();
        m_info[3] = nullptr;
    }

    void operator()()
    {
        int idx = 0;
        beginSyncEvent(0, 3, m_info, &idx);
        Kokkos::fence();
        endSyncEvent(0, idx);
    }

    void operator()(const char* user_msg)
    {
        m_info[3] = user_msg;
        int idx   = 0;
        beginSyncEvent(0, 4, m_info, &idx);
        Kokkos::fence();
        endSyncEvent(0, idx);
        m_info[3] = nullptr;
    }

private:
    std::string  m_line;
    const char** m_info = new const char*[4];
};

namespace
{

// static variable inside will be specialized to anonymous
// namespace, line number, and the first char of the function and file
template <int, char, char, typename... Args>
capture_context
get_context(const char* func, const char* file, int line)
{
    // create statically
    static capture_context _instance(func, file, line);
    // return temporary for function call operator
    return _instance;
}
}  // namespace
}  // namespace Kokkos

// remove the symbol for the Kokkos::fence() function
#undef fence

// replace with call that captures function, file, and line
#define fence                                                                            \
    get_context<__LINE__, __FUNCTION__[0], __FILE__[0]>(__FUNCTION__, __FILE__, __LINE__)
```

**Comment by DavidPoliakoff** [comment]
So, I feel that we're getting a little intricate here

```c++
#ifdef KOKKOS_PROFILING_INCLUDE_SOURCE_INFO
#define KOKKOS_NAME_CALLSITE(name) // some way to get Kokkos_Core.cpp:52 name
#else 
#define KOKKOS_NAME_CALLSITE(name) (name)
```

(Where KOKKOS_PROFILING_INCLUDE_SOURCE_INFO is a configure time option) And then the begin event is

```c++
kokkosp_begin_sync(SpaceHandle, uint32_t deviceId, const char* name, handle_type* handle)
kokkosp_end_sync(handle_type handle)
```
Then `ExecutionSpace::fence` can take a string, and any place in Kokkos I call fence I call it as

```c++
ExecutionSpace().fence(KOKKOS_NAME_CALLSITE(pre-copy-sync));
```

I like this implementation as it's fairly simple. Downside: we lose the ability to disaggregate information, there's no distinct info objects. Upside is simplicity, and the macro (HI DAISY) can be used anywhere, if we expand the Profiling interface we can just use it. Tools folks outside of Kokkos, feel free to comment on your preferences, and tomorrow I think we'll discuss this at the Kokkos meeting

**Comment by jrmadsen** [comment]
> So, I feel that we're getting a little intricate here

@DavidPoliakoff Oh haha yeah, I didn't mean to actually come across as proposing anything along the lines of what was above. That would break _a ton_ of stuff and would be a *horrible* idea. I just got side tracked by Christian's comment. I like what you have above.

**Comment by crtrott** [comment]
Having a Macro which takes a name and expands it with source info into a larger string is fine. Making `Kokkos::fence()` or `ExecutionSpace().fence()` a macro through something weird is not. So David I am not at all opposed to your solution, and if there is a standard C++ way of writing the Macro I have no issue with it unconditionally existing.

**Comment by DavidPoliakoff** [comment]
Hey guys, apparently I need to learn how the interface works. SpaceHandles refer to Memory Spaces, we sync on ExecutionSpaces. I'll delete the SpaceHandle from the suggested callbacks and put up a candidate PR.

**Comment by crtrott** [comment]
Space can refer to both. We can just add the ExecutionSpace variants too.

**Comment by ajpowelsnl** [comment]
@crtrott , @dalg24  -- should this issue be transferred to Kokkos Tools, assigned, or closed?

**Comment by PhilMiller** [comment]
This was done in #2891. The events are in use in our unit tests.
