### ISSUE TITLE
Add PGI support

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#289]
Jenkins nightly test configuration with PGI

**Comment by hcedwar** [comment]
Suspect that still have a compiler bug related to OpenMP.
Currently working for Serial back-end.

**Comment by hcedwar** [comment]
Is working with most recent PGI 17.1

**Comment by nmhamster** [comment]
Linking of one of the Kokkos tests causes a internal compiler error (see #642). Kokkos "supports" PGI from the perspective that the code now compiles and most tests seems to successfully run. We will report any individual issues as needed.

**Comment by nmhamster** [comment]
Kokkos build and test passes on X86-64 Haswell with OpenMP backend using PGI 17.3.0 compiler.
