### ISSUE TITLE
Add missing fences in overloads of create_mirror_view_and_copy()

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2906]
We will add the fences in a follow up PR.

_Originally posted by @dalg24 in https://github.com/kokkos/kokkos/pull/2901#issuecomment-603259475_

See also https://github.com/kokkos/kokkos/pull/2901#discussion_r396701923

**Comment by ndellingwood** [comment]
@dalg24 was this resolved by #2936 ?

**Comment by dalg24** [comment]
Nope it was resolved in #2911
