### ISSUE TITLE
DynRankView needs an is_dyn_rank_view meta-function

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#291]
DynRankView needs an is_dyn_rank_view meta-function for determining whether a template parameter is a DynRankView.  Something like this:

```
template< class > struct is_dyn_rank_view : public std::false_type {};

template< class D, class ... P >
struct is_dyn_rank_view< DynRankView<D,P...> > : public std::true_type {};
```

Alternatively you could also make is_view true for DynRankViews, but I'm assuming you don't want to do that.

**Comment by ndellingwood** [comment]
@etphipp 
Added to DynRankView in pull request #294 
Removed the matching code from Sacado in my local Trilinos branch, but I will wait to issue a pull request until this Kokkos change makes its way into Trilinos.
