### ISSUE TITLE
Improve sorting in Kokkos

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#2914]
Related to https://github.com/kokkos/kokkos/issues/645.

We noticed in https://github.com/arborx/ArborX/issues/145, https://github.com/arborx/ArborX/pull/147 and https://github.com/arborx/ArborX/pull/189 that using `Kokkos::BinSort` is much slower than using `thrust::sort_by_key` for the `CUDA` backend. We should consider importing that one as an alternative.

On a related note, `Kokkos::BinSort` doesn't take an execution space instance, yet.

Furthermore, for the `OpenMP` backend sorting is not parallelized but `std::sort` is called. It might be good to revisit  https://github.com/kokkos/kokkos/pull/1401 that reverted using `__gnu_parallel::sort` on the host.

**Comment by sslattery** [comment]
A true sort that template specializes to backend-specific implementations would be fantastic (i.e. Thrust for `Kokkos::Cuda`). We may want to consider splitting sorting/binning conceptually as well.

**Comment by aprokop** [comment]
Just wanted to mention that `Kokkos::BinSort` is almost unusable for arrays with multiple duplicated entries.

**Comment by masterleinad** [comment]
Fixed in #5071.

**Comment by aprokop** [comment]
> Fixed in #5071.

Not really. OpenMP for repeated indices is partially fixed by #5890 and #5892. `BinSort` on device for repeated indices still not fixed. `sort_by_key` is superseded by #6668.
