### ISSUE TITLE
Feature request: use cudaMemPrefetchAsync in DualView::sync for CudaUVMSpace?

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#2915]
[According to nvidia](https://devblogs.nvidia.com/maximizing-unified-memory-performance-cuda/), doing an explicit prefetch of a UVM view is nearly as fast as a cudaMemcpyAsync between host space and CudaSpace, and at least twice as fast as doing on-demand page transfers. DualView::sync is called everywhere that a prefetch would be needed, and sync knows the direction of the transfer. Is this something that could be added to DualView?

**Comment by crtrott** [comment]
Yeah, I was looking at this also in conjunction with doing the same for the initialize kernel after allocation.

**Comment by crtrott** [comment]
This is done in #2937
