### ISSUE TITLE
#2406 Broke LAMMPS build system

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#2916]
The change in #2406 seems to have broken the LAMMPS Make build system. OMPI_CXX can no longer be set in a Makefile. Also see https://github.com/kokkos/kokkos/issues/776 for more explanation.

**Comment by crtrott** [comment]
Hm how did we not notice this before ...

**Comment by stanmoore1** [comment]
We just recently merged Kokkos 3.0 into LAMMPS.

**Comment by crtrott** [comment]
I thought we had tested though, but probably with an older nvcc_wrapper ...
