### ISSUE TITLE
Scatter view does not use user execution space in whole call stack

### ISSUE THREAD

**Issue by jacobmerson** [kokkos/kokkos#2925]
If I compile Kokkos with both the Serial and OpenMP backends, and use the scatter view, Kokkos will use the OpenMP backed for parts of the computation. This can be seen specifically in the `ScatterValue` function where `Sum` is templated on the default execution space rather than the user specified execution space when creating the `ScatterView`

**Comment by crtrott** [comment]
One question: did this lead to an actual failure? I.e. is there a test missing? Or is it just awkward that the code will for example access an unmanaged CudaSpace View, which was constructed from a host ptr, inside an OpenMP region? In either case the execution space would never actually be used inside of ScatterValue, it technically will only pull the memory space off.

**Comment by jacobmerson** [comment]
This did not cause a failure, however it was a red herring while I was trying to debug some issues in my code.

**Comment by crtrott** [comment]
Ok :-) that is what I hoped (because I couldn't understand how it could have been a problem). But nevertheless this should be fixed as you did in your PR, thanks.
