### ISSUE TITLE
Building Kokkos as a shared object fails to link

### ISSUE THREAD

**Issue by makortel** [kokkos/kokkos#2958]
I tried to build Kokkos (3.0.00) as a shared object with
```
cmake .. -DBUILD_SHARED_LIBS=On -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=On
```
but then at the end of the build `nvcc` fails with
```
[100%] Linking CXX shared library libkokkoscontainers.so
nvcc fatal   : redefinition of argument 'relocatable-device-code'
```
Interestingly the `libkokkoscore.so` as the first shared object links fine.

I managed to work around by patching `nvcc_wrapper` to ignore additional `--relocatable-device-code` (and `-arch`)  arguments.

For what it's worth, I used GCC 8.4.0, CUDA 10.2, and CMake 3.10.2.

**Comment by crtrott** [comment]
this is actually not a bug but a limitation of relocatable device code. You can not refer to a an extern device symbol across shared library boundaries.

**Comment by makortel** [comment]
Thanks @crtrott. We have had troubles with CUDA towards that direction (when playing around with various options, ).

Nevertheless, my test setup described below appears to work (as in does not crash)
* Kokkos built as a shared object with relocatable device code
* an executable that initializes and finalizes the Kokkos runtime
* two shared objects that the executable loads with `dlopen()`, and instantiates objects of classes defined in those shared objects (with a factory pattern)
* both shared objects call `Kokkos::parallel_for()` with some dummy calculations in lambdas

Could this mean that I'm just not exercising something that does not work with shared object + relocatable decide code?

**Comment by makortel** [comment]
> Could this mean that I'm just not exercising something that does not work with shared object + relocatable decide code?

To answer myself, yes, it meant exactly that. Simple `parallel_for` worked fine, but trying e.g. thread teams lead to link failures because of https://github.com/kokkos/kokkos/issues/2958#issuecomment-619410893.
