### ISSUE TITLE
Kokkos UnitTest Serial unusual performance on ATS2 with mvapich2-gdr

### ISSUE THREAD

**Issue by jjellio** [kokkos/kokkos#2963]
This a question (for now).

I've been trying to get Trilinos working properly on ATS2 with MVAPICH2-GDR (rather than IBM Spectrum).  The build uses IBM's Clang 9.  This is currently done in the context of Trilinos (using Trilinos to build kokkos). For comparison's sake, I built with Clang+Spectrum to sanity check if IBM Clang was working (it is, Clang+Spectrum works fine).

This is a Cuda+Serial build (I believe Trilinos requires Serial enabled w/Cuda enabled)

Can anyone shed light on what this part of the Serial unit test is doing?
(`packages/kokkos/core/unit_test/KokkosCore_UnitTest_Serial.exe`)

The very first component of the Serial test is taking a significantly longer time than with Clang+Spectrum. My hypothesis is that memory access (or possibly allocations) are getting screwed up. I've done the test with and without launch blocking enabled, incase Mvapich is somehow sensitive to that (it doesn't seem to matter).

```
[==========] Running 132 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from TEST_CATEGORYDeathTest
[ RUN      ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment
view_layoutstride_right_to_layoutleft_assignment: srand(1587399334)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399371)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399408)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399445)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399482)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399520)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399557)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399594)
[       OK ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment (259908 ms)
[----------] 1 test from TEST_CATEGORYDeathTest (259909 ms total)
```

For comparison's sake, here is clang+spectrum:
```
[==========] Running 132 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from TEST_CATEGORYDeathTest
[ RUN      ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment
view_layoutstride_right_to_layoutleft_assignment: srand(1587399108)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399109)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399109)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399109)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399109)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399109)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399110)
view_layoutstride_right_to_layoutleft_assignment: srand(1587399110)
[       OK ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment (1677 ms)
[----------] 1 test from TEST_CATEGORYDeathTest (1677 ms total)
```

So, roughly 260s vs 1.6s. The kokkos unit tests are almost universally failing due to timeouts (when run via CTest w/Trilinos). 

For the above output, I manually ran the test (that is, I do not use any MPI launcher's, e.g., jsrun).

I also ran the binary with IBM's jsrun.  The Spectrum build has virtually identical performance. 
The main impact of jsrun is that it will append some `LD_PRELOAD` libraries that hook all kinds of things. The bottom line is that the direct launches above avoid the preloads.

In the case of the MVAPICH build, if I use jsrun, I see an assertion failure:
```
[==========] Running 132 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from TEST_CATEGORYDeathTest
[ RUN      ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment
view_layoutstride_right_to_layoutleft_assignment: srand(1587399977)
/g/g20/jjellio/rzansel/empire/Trilinos/packages/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:678: Failure
Death test: { dst = src; }
    Result: died but not with expected error.
  Expected: View assignment must have compatible layouts
Actual msg:
[  DEATH   ] [rank 0] Assertion failed in file src/mpid/ch3/channels/mrail/src/gen2/ibv_cuda_util.c at line 288: gdr_unmap_ret == 0
[  DEATH   ] 
[  FAILED  ] TEST_CATEGORYDeathTest.view_layoutstride_right_to_layoutleft_assignment (37403 ms)
[----------] 1 test from TEST_CATEGORYDeathTest (37403 ms total)
```

Anyone ideas on what could be going wrong are welcome.

**Comment by jjellio** [comment]
@crtrott Any ideas on this? 

I've worked with Kokkos directly, and LLNL and myself are building something similar to what EMPIRE's Trilinos configure will do. (Cuda+Serial w/UVM on)

I can reproduce the slowdown with Kokkos tags/2.9.00 (I and LLNL had issues w/Cmake or generate_makefile w/master, it appears to be screwing up Cuda linkage).

clang+spectrum is stupidly faster than clang+mvapich-gdr.  If I push through and build EMPIRE, it's unit tests run about 10x slower than a comparable spectrum build.

**Comment by DavidPoliakoff** [comment]
This feels like the place where I would want to use a sampling profiler and see whether we're spending ~90% of our time in MPI, or whether it's something else. Sorry, we're doing a tutorial this week, I'm hoping that we can give more info soon but at least I can't figure out how to debug this.

**Comment by jjellio** [comment]
No mpi here.  It's a pure Kokkos test. The fact it uses 'mpicxx' is just a side effect of building.

**Comment by crtrott** [comment]
These tests are death tests, i.e. gtest is spawning child processes, and checks whether the test dies (they check whether certain wrong usage asserts). So my guess is this has something to do with spawning child processes which then die via an assert, and maybe MPI doing some complicated clean up internally even though it was never initialized?

**Comment by jjellio** [comment]
In Kokkos 2.9, they aren't marked as death - is there any substantial difference between it being marked death vs not?

This is just one of many tests that are substantially slower.  Things like EMPIRE end up running about 3x slower (as well as beefy regression tests from them), serial-non-mpi tests can be anywhere from 3-10x slower.  I haven't put more effort into it (it's w/LLNL now) - just getting the software to build w/mvapich has been a royal hassle.

I picked Kokkos serial since it seems the least complex of the lot. It should be an issue w/mvapich2, since the real difference between clang+spectrum/clang+mvapich is a link-time change (their headers do inline different stuff, but since this isn't MPI, it shouldn't matter).

It's worth keeping this issue around.  We are using mvapich2 on another prototype machine that could end being production in a few years. I can email you more details if you want them.

**Comment by PhilMiller** [comment]
This issue is probably obsolete. @crtrott Any reason to keep this open, or subsequent details that emerged that are still relevant?

**Comment by crtrott** [comment]
Yeah closing issue, my guess is in the death test there is an issue with mvapich about a subprocess being started. Maybe the worker threads are to aggressively active and step all over each other?
