### ISSUE TITLE
Create kokkosp_parse_args and kokkosp_print_usage callbacks for profiling interface and kokkos-profiler command line option

### ISSUE THREAD

**Issue by jrmadsen** [kokkos/kokkos#2966]
So both @DavidPoliakoff and I are not fans of environment variables. They tend to be poorly documented and commonly cause issues when set and forgotten about. Here is the idea:

## Kokkos Command Line Option

Option specified in the form of: `--kokkos-profiler="<ARGS>"` taking one argument since allowing more than one is problematic to parsing. Then Kokkos takes the argument, space delimits into an array, and invokes `kokkosp_parse_args(...)` if provided.

## kokkosp_parse_args

The callback for parsing arguments. Couple options w.r.t. signature but ultimately, I think what should be passed to the function should be the `--kokkos-profiler` argument space delimited into an array and (personally) I would like to be able to get the executable name. Ideally, I think the best option would be to invoke `kokkosp_parse_args` such that from the tool perspective, it was as if it called directly in the code, e.g.

```console
./myexe --kokkosp-profiler="-c wall_clock --papi-events PAPI_LST_INST"
```

would look like this inside of `kokkosp_parse_args`:

```console
./myexe -c wall_clock --papi-events PAPI_LST_INST`
```

with, rather obviously, copies of the command line arguments so any modifications don't actually propagate to the app.

## kokkosp_print_usage

While it may seem this is unnecessary since `kokkosp_parse_args` could detect a `-h/--help` and print the usage, this actually serves a second purpose: if the tool __*requires*__ environment variables before the args are parsed or command line options are not supported, this could serve as a simple documentation of what the tool uses for configuration. Kokkos would simply look for a `-h` or `--help` in `--kokkos-profiler="<ARGS>"` and call it when dlopened regardless of whether `kokkosp_parse_args` is provided.

## Open questions

- Should `kokkosp_parse_args` be invoked before or after `kokkosp_init_library`?
  - Case for before: that is how it is traditionally done -- a tool parses command line arguments and then initializes
  - Case for after: most tools expect the init to be the first thing called so make it second might require migration and backwards compatibility issues requiring logic to determine if the kokkos version being used calls `kokkosp_parse_args`

**Comment by DavidPoliakoff** [comment]
Q: "Should we do this?"
A: "Yeah"

Q: "Before or after init"
A: "After"

Other people can comment if they feel differently about either. Thanks for putting the issue together
