### ISSUE TITLE
CPU core oversubscription warning on macOS with OpenMP backend

### ISSUE THREAD

**Issue by keichi** [kokkos/kokkos#2996]
I get the following warning when running a minimal Kokkos program with the OpenMP backend:

```
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: -1 cores per node.
                                    Detected: 1 MPI_ranks per node.
                                    Requested: 8 threads per process.
```

- Kokkos 3.1.00
- GCC 9.3.0
- macOS 10.15.4 (19E266)

```cpp
#include <Kokkos_Core.hpp>

int main(int argc, char* argv[])
{
    Kokkos::initialize(argc, argv);
    Kokkos::finalize();
    return 0;
}
```

**Comment by keichi** [comment]
It seems `Impl:: processors_per_node()` is hardcoded to return -1 on macOS for some reason.

https://github.com/kokkos/kokkos/blob/785d19f23ed4ba43354f9ecd7ef67cd5976ca4c8/core/src/impl/Kokkos_CPUDiscovery.cpp#L48-L50

**Comment by ndellingwood** [comment]
Cross reference https://github.com/kokkos/kokkos/pull/2477#issuecomment-582066345

**Comment by dalg24** [comment]
@keichi the fix is in `develop`

**Comment by keichi** [comment]
Thanks!
