### ISSUE TITLE
Build system on MAC/Debian

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#3]
The configure.sh script apparently doesn't work on MAC or Debian. The reason seems to be echo does not support -e option on those platforms. The configure script is anyway a bit misleading since its not a autotools script. It simply sets up a very simple top level Makefile. One idea would be to provide that top level Makefile directly and people could still change the defaults on the command line.

This is what it would look like:
Instead of:
sh ${KOKKOSPATH}/configure.sh --kokkos-path=${KOKKOSPATH} --prefix=${INSTALLPATH }--with-openmp --with-cuda
You do
make -f ${KOKKOSPATH}/Makefile KOKKOS_DEVICES=OpenMP,Cuda PREFIX=${INSTALLPATH} KOKKOS_PATH=${KOKKOSPATH}

This should work everywhere (fingers crossed).

**Comment by nmhamster** [comment]
This is why autotools was invented :), if you think this is bad, try getting these things to also run on Windows.

S



--
Si Hammond
Scalable Computer Architectures
Sandia National Laboratories, NM
[Sent remotely, please excuse typing errors]
________________________________

**Comment by crtrott** [comment]
I think I fixed this today. In the process I also renamed the configure.sh script because 
a) its NOT autotools stuff
b) it must be run with bash (and fails with sh on MAC)

The new command script is named generate_makefile.bash:

KOKKOS_PATH/generate_makefile.bash --kokkos-path=KOKKOS_PATH
make build-test
make test

**Comment by dsunder** [comment]
Build and test work but when I try to just build the library nothing happens.
