### ISSUE TITLE
CudaUVMSpace should track # allocations, due to CUDA limit on # UVM allocations

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#300]
There is a limit of 64k Cuda UVM allocations after which an "out of memory" error is generated from the cuda malloc function.  The Kokkos::CudaUVMSpace should track the number of allocations and report when this threshold is exceeded instead of simply "out of memory."

**Comment by etphipp** [comment]
Actually it is probably 2^16 = 65536

**Comment by etphipp** [comment]
Oh, I guess that is 64k when k=1024.  Sorry.
