### ISSUE TITLE
Add simple example for phalanx assembly DAG pattern

### ISSUE THREAD

**Issue by rppawlo** [kokkos/kokkos#302]
@hcedwar would like an example use case of phalanx dag assembly added to kokkos examples. This will be used to drive some studies into memory pool management for multiple worksets and temporary fields under AMT.

**Comment by ibaned** [comment]
@rppawlo is this still something we want to do? If so I think you and I could put this in place pretty quickly.

**Comment by rppawlo** [comment]
@ibaned I don't think we need it anymore. We have a good feel for the granularity of tasks in Phalanx and what Kokkos capability to use for them now.

**Comment by ibaned** [comment]
Okay, cool! feel free to comment here if something changes.
