### ISSUE TITLE
Make CXX_STANDARD conflict an error

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#3036]
Pretty small change, but based on user experience in Trilinos we suggest turning this CMake warning from Kokkos:
```
CMake Warning at packages/kokkos/cmake/kokkos_test_cxx_std.cmake:51 (MESSAGE):
  Specified both CMAKE_CXX_STANDARD=11 and KOKKOS_CXX_STANDARD=14, but they
  don't match
```
Into an error. Users clearly ignore CMake warnings, and Trilinos at least does not compile at all correctly when these conflict.

**Comment by jjwilke** [comment]
I can certainly make the change to an error. What sorts of errors are people getting, though? The warning really should have said "overwriting CMAKE_CXX_STANDARD". Curious that this doesn't work since Kokkos just overwrites and removes the conflict.

**Comment by crtrott** [comment]
We still ended up with both c++14 and c++11 flags on the command line

**Comment by jjwilke** [comment]
Is this still an issue?

**Comment by ibaned** [comment]
Not to me, we can close this until someone else comments

**Comment by PhilMiller** [comment]
With #5066, `Kokkos_CXX_STANDARD` as a setting is deprecated as of 3.7, and I'll go ahead and make setting it an error now. So, mismatch will become impossible.

**Comment by PhilMiller** [comment]
Actually that got done in #5293.
