### ISSUE TITLE
Add installation testing. 

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#3037]
This was implemented in #3034

**Comment by junghans** [comment]
You should also run some like:
```
DESTDIR=${PWD}/install cmake --install . && rm -rf ${PWD}/install/usr && rmdir ${PWD}/install
```
to make sure `DESTDIR` (for packaging) works correctly and nothing get installed outside of `CMAKE_INSTALL_PREFIX` (`/usr` in the above line).
