### ISSUE TITLE
Struct initialization on Device fails with ROCm backend

### ISSUE THREAD

**Issue by scothalverson** [kokkos/kokkos#3041]
I'm testing out the ROCm backend for AMD GPUs.  I'm getting a runtime error when creating a View of structs. 

Error:
`Kokkos::initialize() fyi: HIP enabled and initialized
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _ZN6Kokkos12Experimental4ImplL32hip_parallel_launch_local_memoryINS_4Impl11ParallelForINS3_16ViewValueFunctorINS0_3HIPE13SparseElementLb0EEENS_11RangePolicyIJS6_NS_9IndexTypeIlEEEEES6_EEEEvT_
Aborted (core dumped)`

This is running with ROCm 3.3.0

Reproducer:

```cpp
#include "Kokkos_Core.hpp"
struct SparseElement {
        KOKKOS_FUNCTION SparseElement() {x = 0; y = 0; v = 0.0;};
        size_t x;
        size_t y;
        double v;
};
typedef Kokkos::View<SparseElement*, Kokkos::HostSpace> SparseElementHost;
typedef Kokkos::View<SparseElement*> SparseElementDev;
int main(int argc, char** argv){
        Kokkos::initialize( argc, argv );{
                SparseElementHost A_h("A_h", 100);
                SparseElementDev A_d("A_d", 100);
        }
        Kokkos::finalize();
        return 0;
}
```

**Comment by masterleinad** [comment]
Hmmm... I cannot reproduce with commit 92e8323a02d091324716e81787dd0030c195bdce and hipcc with `HIP version: 3.3.20126-2dbba46b`
Your example compiles and runs fine for me. Which commit are you using? What does `hipcc --version` print for you?

**Comment by Rombur** [comment]
If I remember correctly, the missing metadata is a bug in `hipcc`. Try updating it to the latest version.

**Comment by scothalverson** [comment]
I apologize, this was my mistake.  I was adding in an incorrect flag to hipcc, nameley --amdgpu-target=gfx906.  After removing that, both the reproducer and the code I'm testing to run on AMD GPUs appears to work.

Probably not important at this point, but I'm definitely using 3.3.20126-2dbba46b:

```
hipcc --version
HIP version: 3.3.20126-2dbba46b
```
