### ISSUE TITLE
Launching 2D/3D Thread Teams

### ISSUE THREAD

**Issue by dingwentao** [kokkos/kokkos#3053]
We are DOE ECP EZ team and currently developing our Kokkos-based SZ lossy compressor for scientific data management. In general, we are porting our CUDA-based GPU code to Kokkos framework, however, we have been stuck in how to launch 2-D/3-D thread blocks. 

According to Kokkos wiki, the league rank is the index of thread block in CUDA, and the team rank is the index of thread in thread block. But we cannot find if Kokkos allows to use 2-D or 3-D index similar to CUDA. It only mentions -- - _Instead of mapping a 1-D range of indices to hardware resources, Kokkos' thread teams map a 2-D index range. The first index is the league rank, the index of the team. The second index is the team rank, the thread index within a team. In CUDA this is equivalent to launching a 1-D grid of 1-D blocks._ 

Is there anyone can confirm that Kokkos can or cannot use 2-D or 3-D index for league and team ranks? Thank you so much for your help!

**Comment by crtrott** [comment]
Hi,

it depends on what you are actually trying to do. Generally Kokkos is not meant to be a direct representation of CUDA. CUDA is a very hardware centric programming model, which is good if you write code for the hardware CUDA was developed for, but bad if you want performance portable code. And while there are ways of actually getting Kokkos to use 2D blocks trying to do this explicitly in order to do a 1-to-1 port of a CUDA kernel is generally not a good idea. 

Can you give some more info about the loop structure of the algorithm you are trying to port? That would be helpful to recommend the right mechanisms.

**Comment by dingwentao** [comment]
Thank you so much for your quick response!

Given a 2-D array, we're trying to calculate a value (per thread) for each data point based on its neighboring points' values. Below is the main code of our 2-D kernel in CUDA. We are able to port the 1-D kernel via replacing _blockDim.x_ by _team_member.team_size ()_,  _blockIdx.x_ by _team_member.league_rank ()_, and threadIdx.x by _team_member.team_rank ()_. However, we don't quite know how to create 2-D thread teams and map each thread to each data point in a 2-D array? Any suggestion?

    // get index for a 2-D thread
    int y = threadIdx.y;
    int x = threadIdx.x;

    // load data to shared memory
    if (x < B + 1 and y < B + 1) __s2df[y + 1][0] = 0, __s2df[0][x + 1] = 0;
    if (x == 0 and y == 0) __s2df[0][0] = 0;
    __syncthreads();

    int gi1 = blockIdx.y * blockDim.y + y;
    int gi0 = blockIdx.x * blockDim.x + x;
    if (gi0 >= dims_L16[DIM0] or gi1 >= dims_L16[DIM1]) return;
    size_t id = gi0 + gi1 * dims_L16[DIM0];  // low to high dim, inner to outer

    // main computation
    __s2df[y + 1][x + 1] = round(data[id] * ebs_L4[EBx2_r]);  // fp representation
    __syncthreads();
    // postquantization
    T    pred        = __s2df[y + 1][x] + __s2df[y][x + 1] - __s2df[y][x];
    T    posterror   = __s2df[y + 1][x + 1] - pred;
    bool quantizable = fabs(posterror) < dims_L16[RADIUS];
    Q    _code       = static_cast<Q>(posterror + dims_L16[RADIUS]);
    __syncthreads();
    data[id] = (1 - quantizable) * __s2df[y + 1][x + 1];
    code[id] = quantizable * _code;

**Comment by PhilMiller** [comment]
The general Kokkos answers to questions like this are to use either `MDRangePolicy` or `TeamPolicy` with a suitable application of hierarchical parallelism. Since this hasn't had any activity in over 2 years, I'm closing it.
