### ISSUE TITLE
Adding user or institution to Slack

### ISSUE THREAD

**Issue by ChristianLagares** [kokkos/kokkos#3056]
Dear all,

What would the appropriate procedure be to be included in the Slack Channel? I am actively using Kokkos and would greatly benefit from discussions. 

I tried reaching out over email, but I imagine with so much email traffic going on, it might have ended up lost. 

Best,
Christian

**Comment by masterleinad** [comment]
Do you have an e-mail address for us?

**Comment by ChristianLagares** [comment]
Sure thing! Thanks for the quick response!

christian.lagares@upr.edu
