### ISSUE TITLE
Kokkos Uint RNG Bounds

### ISSUE THREAD

**Issue by rfbird** [kokkos/kokkos#3068]
I think the notation for the bounds of some of the RNG stuff is wrong. 

At https://github.com/kokkos/kokkos/blob/785d19f23ed4ba43354f9ecd7ef67cd5976ca4c8/algorithms/src/Kokkos_Random.hpp#L149 

the bounds are stated as `(0,range]`

 Per the below test program, would this more accurately be `[0, range)`, per the following to my test program:

```
// Host
Kokkos::Random_XorShift64_Pool<> rp( seed );                         
    for (int i = 0; i < 20; i++)                                        
        {                                                                   
           Kokkos::Random_XorShift64<Kokkos::DefaultExecutionSpace> rg = rp.get_state();
           std::cout << rg.urand(10) << std::endl;                           
           rp.free_state(rg);                                                
        }  
```

Output:

```
7
8
**0**
3
6
5
3
9
4
8
1
9
1
3
7
3
9
3
8
3
```

**Comment by crtrott** [comment]
Oh yeah all the comments are the wrong way around. Should be `[0,Range)`
