### ISSUE TITLE
Allow naming of Views for initialization kernel

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3070]
@cielling is seeing a nontrivial amount of time being spent in View initialization, and asked in the Slack whether those kernels could be named by the name of the View being initialized, rather than just `Kokkos::View:initialization`

Personally I'm in favor of an environment variable/command line argument to allow that. I worry about the proliferation of such arguments, and have some desire to see it be a build time option, but this _should_ be fine, and we should definitely implement it in some form

**Comment by mhoemmen** [comment]
Is there a reason why naming initialization kernels with the View's name shouldn't be default behavior?

**Comment by crtrott** [comment]
Yeah I think we can just in general attach the name of the view

**Comment by crtrott** [comment]
`Kokkos::View::initialization[VIEWLABEL]` maybe?

**Comment by DavidPoliakoff** [comment]
Exactly my thought

**Comment by DavidPoliakoff** [comment]
Sorry, I read only Christian's comment in my email. @mhoemmen , good point, there isn't, we should do that. Christian, if we do that, your labeling scheme is a good one

**Comment by crtrott** [comment]
Also what I meant is: no option for this, we just do it.

**Comment by DavidPoliakoff** [comment]
@crtrott , I agree with that, unless somebody comes by the issue and makes a strong case otherwise.
