### ISSUE TITLE
cuda space instance allocates uvm memory

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#3075]
When I create Kokkos::Cuda(stream) instance, it uses uvm space by default as the code lives in Trilinos and uvm is always on at this moment. How can I control its memory space of the execution instance ? I simply do not want to see this warning. I also know how not to show the warning from a command line input but it would be better if I cant control the memory space associated with the instanciated execution space.
```
Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_LAUNCH_BLOCKING=1.
                                  The code must call Cuda().fence() after each kernel
                                  or will likely crash when accessing data on the host.
``` 

Also, how much overhead does instanciation have ? Is it a bad idea if I create instance wrapping a stream in a loop ?

**Comment by crtrott** [comment]
Uhm not sure what you are talking about. This is not a warning about a specific allocation, this is a warning (somewhat outdated on Power9 systems) telling you that by default i.e. when doing stuff like this: `Kokkos::View<double*>`  the system will allocate into UVM memory. The stream instance does NOT create an allocation in UVM per se. All the per-instance allocations (like buffers for reductions) are in CudaSpace.

**Comment by kyungjoo-kim** [comment]
This is when I compile the code in Trilinos where UVM is default. I also thought that cud space is default in kokkos but tpetra uses uvm as a default space. However, what I observed here is when I create the cuda instance with streams, I also see the same numer of warning message with the number of streams. The configuration also turns on relocatable device code. Does this allocate uvm when cuda instance is created ?

**Comment by kyungjoo-kim** [comment]
I looked at the code (Kokkos_Cuda_Instance.cpp) a bit more. The warning (line 494) pops up from the code initializing the instance. This is not about allocation but a general warning when the cuda instance is initialized. Then, do we need to repeat this warning for every cuda instance created ? This warning can be given when "kokko::initialize" only. 

Line 353. Why do we need device synchronization ? Assuming the cuda instances are created to wrap cuda streams, do we really need this device synchronization ? I think that this cause some overhead for a use case wrapping streams with kokkos exec instance. For instance,

```
for (i=0;i<Nstreams;++i) {
  const auto mystream = already_created_streams(i);
  // here we always encounter the device synchronization in this example code
  const auto exec_instance = Kokkos::Cuda(mystream);
  Kokkos::parallel_for(exec_instance, blah blah) ;
}
``` 
I can always create the exec instances when I create the stream before they are used. However, it would be better that the exec space instance is very light weight and does not call device sync unless it is really necessary.

**Comment by crtrott** [comment]
a) we shouldn't print this warning in subsequent instance creation
b) the warning about using UVM allocations without LAUNCH_BLOCKING is pretty relevant still. Like Trilinos will fail its test when you don't do it. 
c) creating a CUDA instance is NOT lightweight. There are allocations happening and all kinds of other stuff going on to start up all the internal runtime necessities. Your use case above is definitely not recommended. You should create instances and keep them around.

**Comment by kyungjoo-kim** [comment]
a) Thanks. 
b) Sounds good to me.
c) Not a big deal.

**Comment by kyungjoo-kim** [comment]
Another question. Do I also have heavy overhead if I use repeatedly default execution space instance "Kokkos::Cuda()" ?

**Comment by crtrott** [comment]
No
