### ISSUE TITLE
Wiki image links broken

### ISSUE THREAD

**Issue by wrwilliams** [kokkos/kokkos#3078]
It looks like quite a few image links in the Wiki are dead, notably for the execution/memory space example figures. Sample link: `https://github.com/kokkos/ProgrammingGuide/raw/figure-edits/figures/kokkos-node-doc.png`

**Comment by JoshuaSBrown** [comment]
This is still a problem. I noticed it today. I haven't seen a correctly displayed figure in the wiki since I started going through the wiki, but I'm still only a couple pages in.

**Comment by ndellingwood** [comment]
These should be fixed now, thanks for reporting

**Comment by wrwilliams** [comment]
Looks good to me.
