### ISSUE TITLE
Windows Compatibility Fixes

### ISSUE THREAD

**Issue by shie0041** [kokkos/kokkos#308]
[Shields_Changes.zip](https://github.com/kokkos/kokkos/files/286818/Shields_Changes.zip)

For Kokkos to compile under a Windows environment with Visual Studio 2015 Update 2 and Intel Compiler 16.0 Update 3, three changes to Kokkos files must be made.  Compiling with earlier versions of either VS or the Intel compiler is not possible due to lack of C++11 support.

The two files that need to be changed are Kokkos_Layout.hpp and Kokkos_MemoryPool.hpp.  The attached Zip has two versions of Kokkos_MemoryPool.hpp.  The one with the _Orig suffix was downloaded from GitHub yesterday. The other includes my changes to lines 151 and 570.

Without these changes, the following errors are reported in VS 2015:

`2>C:\GitHub\Trilinos\packages\kokkos\core\src\Kokkos_MemoryPool.hpp(151): error : function call must have a constant value in a constant expression
2>        LG_WORD_SIZE = Kokkos::Impl::integral_power_of_two( WORD_SIZE ),
2>                       ^
2>
2>C:\GitHub\Trilinos\packages\kokkos\core\src\Kokkos_MemoryPool.hpp(570): error : function call must have a constant value in a constant expression
2>        LG_MIN_BLOCK_SIZE  = Kokkos::Impl::integral_power_of_two( MIN_BLOCK_SIZE ),`

Unfortunately I didn't save the original version of Kokkos_Layout.hpp and so I have only included my changed version in the Zip file.  The change is very minor, though.  The original lines 205 to 207 have been commented out.  These read:

`static_assert( Impl::is_integral_power_of_two(ArgN0) &&
                 Impl::is_integral_power_of_two(ArgN1)
               , "LayoutTileLeft must be given power-of-two tile dimensions" );`

I have replaced this with

`static_assert(IsPowerOfTwo, "LayoutTileLeft must be given power-of-two tile dimensions" );`
A similar error as those reported for Kokkos_MemoryMap.hpp is reported if this change is not made.  It seems the Windows tools have a bit more restrictive definition about what constitutes a constant value at compile time.

Best regards,
Eric

**Comment by hcedwar** [comment]
Need a working pull request against the current development branch.
