### ISSUE TITLE
subview View layout determination

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#309]
impl/KokkosExp_ViewMapping.hpp:2749-2761 subview View layout determination logic is flawed.  To preserve the layout for a rank 2 View layout_left the first two subview arguments must be ranges.  To preserve the layout for a rank 2 View layout_right the last two subview arguments must be ranges.

**Comment by crtrott** [comment]
Ok I believe this actually works correct now. Not sure if there ever was a bug. Here is the testcode:

[main.txt](https://github.com/kokkos/kokkos/files/481317/main.txt)
