### ISSUE TITLE
Remove KOKKKOS_ENABLE_PROFILING Option

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#3095]
We will remove that option. The dependency on libdl will be explicitly managed, and if no libdl is available the dynamic loading of a profiling library will not be possible. The new explicit API to fill the tools hooks will always exist.

**Comment by crtrott** [comment]
We already have `Kokkos_ENABLE_LIBDL` as a public option. That one will determine whether the dynamic loading of a tool is possible via pointing to a shared library with the environement variable.

**Comment by DavidPoliakoff** [comment]
I'm in favor of it

**Comment by DavidPoliakoff** [comment]
Done in #3115
