### ISSUE TITLE
View type alias

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#3118]
In metaprogramming context, the difference between `Kokkos::View<int, void, void, void>` (declared as `Kokkos::View<int>`) and `Kokkos::View<int, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void, void>` (declared as `Kokkos::View<int, Kokkos::Device<Kokkos::DefaultExecutionSpace, Kokkos::DefaultExecutionSpace::memory_space>` on the host) is confusing and inconvenient because they are virtually the same type. I understand the flexibility of such template specialization but it seems the very goal can also be achieved by template aliasing. Are there any other reasons to make the distinction?

**Comment by crtrott** [comment]
I am not sure what you mean exactly. Do you have a proposed refinement which would make them all the same type which works in C++11?

**Comment by Char-Aznable** [comment]
Well,  there would be just one specialization of View that takes all the template arguments and the all other variants such as `View<int>` and `View<int,Layout>` are defined by template alias like
```c++
template < class T>
using View = View<T, DefaultLayout, DefaultDevice, DefaultTraits>;
template < class T, class Layout >
using View = View<T, Layout, DefaultDevice, DefaultTraits>;
```
This is my thought without going through the detail of the code
