### ISSUE TITLE
PGI compiler being passed the gcc -fopenmp flag

### ISSUE THREAD

**Issue by zackgalbreath** [kokkos/kokkos#3125]
We are running into the following error when attempting to build kokkos (953d7968e8fc5908af954f883e2e38d02c279cf2) on summit:

```
pgc++-Error-Unknown switch: -fopenmp
```

i.e. it's using the gcc flag, not the PGI one.

Here are the modules we're using:
```
module load pgi
module load spectrum-mpi
module load cuda
module load cmake
```

And we are the CMake configuration variables we're using:
```
-DCMAKE_BUILD_TYPE=Release
-DBUILD_TESTING=OFF
-DKokkos_ENABLE_CUDA=ON
-DKokkos_ENABLE_OPENMP=ON
-DKokkos_ENABLE_SERIAL=ON
-DKokkos_ARCH_VOLTA70=ON
-DKokkos_ARCH_POWER9=ON
-DKokkos_ENABLE_CUDA_LAMBDA=ON
-DKokkos_ENABLE_AGGRESSIVE_VECTORIZATION=ON
```

Please let us know if we're doing something wrong.

@ascheinb

**Comment by masterleinad** [comment]
No, it's not your fault. The current logic is https://github.com/kokkos/kokkos/blob/9cd19f110bcc0c31dfd6a0a5465461215d6f356d/cmake/kokkos_enable_devices.cmake#L46-L54
Since the compiler id is `NVIDIA` (I guess you are using `nvcc_wrapper`) we use `-Xcompiler -fopenmp` instead of `-Xcompiler KOKKOS_HOST_OPENMP_FLAG` with a `KOKKOS_HOST_OPENMP_FLAG` to be implemented.

**Comment by masterleinad** [comment]
@zackgalbreath Can you check if https://github.com/kokkos/kokkos/pull/3127 works for you?

**Comment by zackgalbreath** [comment]
> @zackgalbreath Can you check if #3127 works for you?

Thanks for the quick fix! I can confirm that this works for us on summit

**Comment by ascheinb** [comment]
@masterleinad @zackgalbreath I'm trying to compile with this fix using the `develop` branch since it was merged in. On Summit with PGI, getting this error running CMake:

```
-- Using --c++11;-A for C++11 standard as feature
CMake Error at cmake/kokkos_test_cxx_std.cmake:32 (IF):
  if given arguments:

    "NVIDIA" "STREQUAL" "NVIDIA" "AND" "NOT" "--c++11" "-A" "IN_LIST" "SUPPORTED_NVCC_FLAGS"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/kokkos_test_cxx_std.cmake:67 (kokkos_set_cxx_standard_feature)
  cmake/kokkos_tribits.cmake:201 (INCLUDE)
  CMakeLists.txt:161 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```

Any ideas?

**Comment by ascheinb** [comment]
I'm guessing `--c++11;-A` is causing some syntax to break

**Comment by masterleinad** [comment]
@ascheinb Can you check if you can compile successfully with `CUDA` support, `nvcc_wrapper` and `PGI` as host compiler when you comment the check https://github.com/kokkos/kokkos/blob/develop/cmake/kokkos_test_cxx_std.cmake#L32-L34?
It probably only makes sense to have this check for `gcc` and `clang`. Still, I am not quite sure if `-A` causes some other problems.

**Comment by ascheinb** [comment]
When I commented out the check, I got a ton of these sorts of errors:

`/usr/lib/gcc/ppc64le-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ppc64le-redhat-linux/bits/c++config.h(190): error: identifier "nullptr" is undefined`

as if it's not recognizing the c++11 flag...

**Comment by masterleinad** [comment]
Hmm... Do you know if you also had these problems with previous `Kokkos` releases?

The `-A` comes from `CMake` (https://github.com/Kitware/CMake/search?p=1&q=CMAKE_CXX11_STANDARD_COMPILE_OPTION&unscoped_q=CMAKE_CXX11_STANDARD_COMPILE_OPTION) to enforce ISO-C++-conforming code (https://www.pgroup.com/resources/docs/19.7/x86/pgi-ref-guide/index.htm#a-uc).

Can you give us the full compile line (`make VERBOSE=1`) for the failing compilation unit?

**Comment by masterleinad** [comment]
@ascheinb Can you have a look if #3239 works for you?

**Comment by ascheinb** [comment]
@masterleinad Yes, #3239 does work for me when I tried it on summit with PGI 19.10.
