### ISSUE TITLE
Reduce overhead of task memory pool in task scheduler.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#314]
For this moment, we need to estimate the number of tasks in task policy. I understand why this is necessary but practically this is quite inconvenient for application developer. As tasking is mostly suitable for irregular problems and we usually cannot set upper bound of tasks. Even if we cannot do this on GPUs, the feagure is required for host architectures.

**Comment by hcedwar** [comment]
Concern with performance overhead of iterative construction and destruction of TaskScheduler.  Is there a way to reduce this overhead by retaining the TaskScheduler and just resizing the empty memory before each use.

**Comment by dsunder** [comment]
@hcedwar does your current work on the memory pool address this?

**Comment by hcedwar** [comment]
Memory pool performance has been improved, including creating and destroying the memory pool.
Recommended practice is when you are unable to generate an estimate of upper bound then run a "count" algorithm first.  This could be the actual algorithm with a reduction of by how much the memory allocation failed.  Then use the count to size memory appropriately and run the algorithm.
