### ISSUE TITLE
optimize min/max atomics

### ISSUE THREAD

**Issue by jeffhammond** [kokkos/kokkos#3144]
min/max atomics should be specialized with an early exit since unlike arithmetic, it is often the case that no atomic operation besides load is required.

As best I can tell from https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_Atomic_Generic.hpp#L155, no such optimization exists in Kokkos.

This optimization was first recognized by Jim Cownie in RAJA and fixed by Tom Scogland a while ago:
- https://github.com/LLNL/RAJA/issues/447
- https://github.com/LLNL/RAJA/issues/448
- https://github.com/LLNL/RAJA/pull/470

I can implement this.  This issue has been created for tracking purposes.  Good-natured public humiliation is encouraged if this issue is not closed by a pull request from me by 30 July 2020.

**Comment by calewis** [comment]
@etphipp, has some interest in this.  So there are people that want faster min/max.

**Comment by jeffhammond** [comment]
FYI should be done in an hour if things go well. https://github.com/jeffhammond/kokkos/tree/issue-3144
