### ISSUE TITLE
Kokkos_BINARY_DIR unset in FetchContent context

### ISSUE THREAD

**Issue by david8dixon** [kokkos/kokkos#3153]
I see the following error at configuration time when using fetch content module to pull in kokkos as a dependency:

```
CMake Error: Could not open file for write in copy operation /KokkosConfig.cmake.tmp
CMake Error: : System Error: Read-only file system
CMake Error at /cmake/3.17.0/share/cmake-3.17/Modules/CMakePackageConfigHelpers.cmake:330 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  build/_deps/kokkos-src/cmake/kokkos_install.cmake:10 (CONFIGURE_PACKAGE_CONFIG_FILE)
  build/_deps/kokkos-src/CMakeLists.txt:262 (INCLUDE)
```

The issue is that `Kokkos_BINARY_DIR` is not set in this context. The quick fix is to pass `-D Kokkos_BINARY_DIR=./_deps/kokkos-build` when configuring my project, but by replacing `Kokkos_BINARY_DIR` with `PROJECT_BINARY_DIR` in `kokkos_install.cmake` seems like a possible permanent fix to this issue.

**Comment by crtrott** [comment]
@Jeremiah @masterleinad any thoughts?

**Comment by jjwilke** [comment]
This was already fixed here:

https://github.com/kokkos/kokkos/pull/3135

Is there any reason not to merge this PR?

**Comment by masterleinad** [comment]
@david8dixon Can you please check that this issue is resolved using `develop`?

**Comment by david8dixon** [comment]
It is thanks!
