### ISSUE TITLE
Autotuning tile sizes for MDRangePolicy

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3156]
When a user gives the auto keyword for tile size (or leaves it unspecified), we should have hooks into the Tuning system to get optimal values

**Comment by DavidPoliakoff** [comment]
Possible place to test this: https://github.com/kokkos/kokkos/issues/1710#issuecomment-417408682

**Comment by PhilMiller** [comment]
As noted, #3688 implemented this.
