### ISSUE TITLE
Memory leak when using CUDA stream

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#3167]
We currently have a memory leak when using CUDA stream [here](https://github.com/kokkos/kokkos/blob/master/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L814-L819). We cannot simply delete the object by the constructor because we pass it by copy everywhere. When we don't use a stream, we have a singleton that is correctly cleaned up in `Kokkos::finalize()`.

**Comment by crtrott** [comment]
Make it a shared pointer to the instance.
