### ISSUE TITLE
Reflect addition of vector::data() in the API reference on the wiki

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#3168]
Make sure you update the [Synopsys](https://github.com/kokkos/kokkos/wiki/Kokkos%3A%3Avector#synopsis) in the API reference accordingly

_Originally posted by @dalg24 in https://github.com/kokkos/kokkos/pull/3123_

**Comment by ndellingwood** [comment]
Looks like this has been updated:

```
  // returns pointer to the underlying array
  // [Host only]
  pointer data() const;
```

**Comment by dalg24** [comment]
Yep I assigned to him and he made me do it :)
