### ISSUE TITLE
Makefile.kokkos fails to detect CCE10 with OpenMP as device

### ISSUE THREAD

**Issue by tom91136** [kokkos/kokkos#3183]
Kokkos seems to misidentify newer clang based Cray compilers (CCE10.0.1) as clang compilers:

```
> CC  --version
Cray clang version 10.0.1 (caf30fcafd1021890a5ea5d98ca2f101977405d4)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/cray/pe/cce/10.0.1/cce-clang/aarch64/share/../bin
```
This causes the `-fopenmp` to not be added:
https://github.com/kokkos/kokkos/blob/953d7968e8fc5908af954f883e2e38d02c279cf2/Makefile.kokkos#L244

The behaviour is correct for the classic version but the clang based one defaults to openmp off so the compilation fails with: 

```
error: "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!" 
```

**Comment by PhilMiller** [comment]
This was generally addressed in #4105
