### ISSUE TITLE
RangePolicy has an implicitly deleted assignment operator

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#3192]
RangePolicy defines a move constructor, which causes the default assingment operator to be deleted. Is there a reason not to introduce explicitly defaulted assingment and move assignment operators?

**Comment by dalg24** [comment]
I can't really think of a good reason but maybe @dhollman or @crtrott can.
https://github.com/kokkos/kokkos/blob/e31cb2fe241c2099fa84902fd8524a313ed882ad/core/src/Kokkos_ExecPolicy.hpp#L124-L125


Also not sure why this guy is passed by value.
https://github.com/kokkos/kokkos/blob/e31cb2fe241c2099fa84902fd8524a313ed882ad/core/src/Kokkos_ExecPolicy.hpp#L127-L134

**Comment by dalg24** [comment]
This in fixed in develop.
