### ISSUE TITLE
List of desired Clang-Tidy checks

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3199]
Inspired by #3198 , I'd like to figure out which clang-tidy checks we want as a part of our CI. I'll edit this list as I read more

This list is just me going down the (very long) list here https://clang.llvm.org/extra/clang-tidy/checks/list.html

GOOD
- [ ] bugprone-argument-comment
- [ ] bugprone-assert-side-effect (consider listing KOKKOS_EXPECTS and KOKKOS_ENSURES as assert macros)
- [ ] bugprone-bool-pointer-implicit-conversion
- [ ] bugprone-branch-clone¶
- [ ] bugprone-copy-constructor-init¶
- [ ] bugprone-dangling-handle¶
- [ ] bugprone-exception-escape¶
- [ ] bugprone-forward-declaration-namespace¶
- [ ] bugprone-forwarding-reference-overload¶
- [ ] bugprone-inaccurate-erase¶
- [ ] bugprone-incorrect-roundings¶
- [ ] bugprone-infinite-loop¶
- [ ] bugprone-integer-division¶
- [ ] bugprone-macro-parentheses¶
- [ ] bugprone-macro-repeated-side-effects¶
- [ ] bugprone-misplaced-operator-in-strlen-in-alloc¶
- [ ] bugprone-misplaced-pointer-arithmetic-in-alloc¶
- [ ] bugprone-misplaced-widening-cast¶
- [ ] bugprone-move-forwarding-reference¶
- [ ] bugprone-multiple-statement-macro¶
- [ ] bugprone-not-null-terminated-result
- [ ] bugprone-parent-virtual-call¶
- [ ] bugprone-reserved-identifier¶
- [ ] bugprone-sizeof-container¶
- [ ] bugprone-sizeof-expression¶
- [ ] bugprone-string-constructor¶
- [ ] bugprone-string-integer-assignment¶
- [ ] bugprone-string-literal-with-embedded-nul¶
- [ ] bugprone-suspicious-enum-usage
- [ ] bugprone-suspicious-include¶
- [ ] bugprone-suspicious-memset-usage¶
- [ ] bugprone-suspicious-missing-comma¶
- [ ] bugprone-suspicious-semicolon¶
- [ ] bugprone-suspicious-string-compare
- [ ] bugprone-terminating-continue¶
- [ ] bugprone-throw-keyword-missing¶
- [ ] bugprone-too-small-loop-variable¶
- [ ] bugprone-undefined-memory-manipulation¶
- [ ] bugprone-undelegated-constructor¶
- [ ] bugprone-unhandled-self-assignment¶
- [ ] bugprone-unused-raii¶
- [ ] bugprone-unused-return-value¶
- [ ] bugprone-use-after-move¶
- [ ] bugprone-virtual-near-miss¶
- [ ] cert-dcl21-cpp¶
- [ ] cert-dcl58-cpp¶
- [ ] cert-err58-cpp¶
- [ ] cert-err60-cpp¶
- [ ] cert-flp30-c¶
- [ ] cert-mem57-cpp¶
- [ ] clang-analyzer-cplusplus.InnerPointer¶
- [ ] clang-analyzer-core.uninitialized.CapturedBlockVariable¶
- [ ] cppcoreguidelines-avoid-non-const-global-variables¶
- [ ] cppcoreguidelines-init-variables¶
- [ ] cppcoreguidelines-interfaces-global-init¶
- [ ] cppcoreguidelines-macro-usage¶
- [ ] cppcoreguidelines-narrowing-conversions¶
- [ ] cppcoreguidelines-pro-bounds-array-to-pointer-decay¶
- [ ] cppcoreguidelines-pro-bounds-constant-array-index
- [ ] cppcoreguidelines-pro-bounds-pointer-arithmetic
- [ ] cppcoreguidelines-pro-type-const-cast
- [ ] cppcoreguidelines-pro-type-cstyle-cast
- [ ] cppcoreguidelines-pro-type-member-init¶
- [ ] cppcoreguidelines-pro-type-static-cast-downcast¶
- [ ] cppcoreguidelines-slicing¶
- [ ] cppcoreguidelines-special-member-functions
- [ ] fuchsia-multiple-inheritance (this is just me giving a hot take)
- [ ] fuchsia-statically-constructed-objects (this is really interesting if it’s possible)
- [ ] fuchsia-trailing-return
- [ ] fuchsia-virtual-inheritance
- [ ] google-build-namespaces
- [ ] google-build-using-namespace (perhaps a bit aggressive, but it follows my typical pattern)
- [ ] google-explicit-constructor
- [ ] google-global-names-in-headers
- [ ] google-readability-avoid-underscore-in-googletest-name
- [ ] google-readability-casting
- [ ] google-readability-todo [spicy but I like it. If you’re going to have TODO’s in the code, have issues in the repo]
- [ ] google-upgrade-googletest-case
- [ ] hicpp-multiway-paths-covered
- [ ] hicpp-signed-bitwise
- [ ] misc-definitions-in-headers¶
- [ ] misc-misplaced-const
- [ ] misc-new-delete-overloads
- [ ] misc-no-recursion
- [ ] misc-redundant-expression
- [ ] misc-static-assert¶
- [ ] misc-throw-by-value-catch-by-reference
- [ ] misc-unconventional-assign-operator
- [ ] misc-unused-using-decls
- [ ] modernize-deprecated-headers (maybe a carveout for Profiling_C_Interface)
- [ ] modernize-loop-convert (worth a shot)
- [ ] modernize-make-shared
- [ ] modernize-pass-by-value
- [ ] modernize-raw-string-literal
- [ ] modernize-redundant-void-arg
- [ ] modernize-return-braced-init-list
- [ ] modernize-shrink-to-fit
- [ ] modernize-use-auto [possibly controversial]
- [ ] modernize-use-bool-literals
- [ ] modernize-use-default-member-init [also controversial]
- [ ] modernize-use-emplace
- [ ] modernize-use-equals-default
- [ ] modernize-use-equals-delete
- [ ] modernize-use-noexcept
- [ ] modernize-use-nullptr [ #3200]
- [ ] modernize-use-override
- [ ] modernize-use-transparent-functors
- [ ] modernize-use-using [#3198]
- [ ] openmp-exception-escape
- [ ] openmp-use-default-none
- [ ] performance-faster-string-find
- [ ] performance-for-range-copy
- [ ] performance-implicit-conversion-in-loop
- [ ] performance-inefficient-algorithm
- [ ] performance-inefficient-string-concatenation
- [ ] performance-inefficient-vector-operation
- [ ] performance-move-const-arg
- [ ] performance-move-constructor-init
- [ ] performance-no-automatic-move
- [ ] performance-noexcept-move-constructor
- [ ] performance-trivially-destructible
- [ ] performance-type-promotion-in-math-fn
- [ ] performance-unnecessary-copy-initialization
- [ ] performance-unnecessary-value-param
- [ ] readability-* [I’d want a good reason not to do this]

UNLIKELY to be present in our code
- [ ] bugprone-bad-signal-to-kill-thread
- [ ] bugprone-fold-init-type¶
- [ ] bugprone-no-escape¶
- [ ] bugprone-posix-return¶
- [ ] bugprone-signed-char-misuse¶
- [ ] bugprone-spuriously-wake-up-functions¶
- [ ] cert-dcl50-cpp¶
- [ ] cert-env33-c¶
- [ ] cert-err34-c¶
- [ ] cert-err52-cpp¶
- [ ] cert-oop57-cpp¶
- [ ] cert-oop58-cpp¶
- [ ] cppcoreguidelines-avoid-goto¶
- [ ] cppcoreguidelines-pro-type-vararg¶
- [ ] google-build-explicit-make-pair
- [ ] google-objc-* [not an ObjC project ]
- [ ] hicpp-no-assembler [Christian is the only one who would violate]
- [ ] linuxkernel-must-use-errs [we’re not the Linux kernel yet]
- [ ] llvm-* [we’re not LLVM yet]
- [ ] misc-non-copyable-objects
- [ ] misc-uniqueptr-reset-release [don’t think we use unique_ptrs]
- [ ] modernize-avoid-bind¶
- [ ] modernize-avoid-c-arrays
- [ ] modernize-deprecated-ios-base-aliases [we’re not using these I don’t think]
- [ ] modernize-replace-auto-ptr
- [ ] modernize-replace-disallow-copy-and-assign-macro
- [ ] mpi-* [I avoid making Hal happy. Also, we’re not an MPI project]
- [ ] objc-* [We’re not objective C]

Do we care?
- [ ] cert-msc50-cpp¶
- [ ] cert-msc51-cpp¶
- [ ] cppcoreguidelines-no-malloc
- [ ] cppcoreguidelines-pro-type-reinterpret-cast [C++ needs to either ban dlsym or live with this]
- [ ] cppcoreguidelines-pro-type-union-access [ Maybe if we exclude Profiling? But I think that’s the only place we have unions]
- [ ] darwin-*
- [ ] fuschia-default-argument*
- [ ] fuschia-overloaded-operator [ doesn’t work for us :/ ]
- [ ] google-default-arguments [ I like their reasoning, actually, but don’t think the group will ] 
- [ ] google-runtime-references [ this is a good practice that I violate regularly. Don’t know if others do too ]
- [ ] misc-non-private-member-variables-in-classes [ personally I see a lot of places this adds verbosity more than quality ]
- [ ] misc-unused-alias-decls [I just want to get rid of namespace aliases]
- [ ] misc-unused-parameters [we already use the diagnostic]
- [ ] modernize-use-trailing-return-type [I don’t like it]
- [ ] portability-simd-intrinsics [laughs in Dan Ibanez]
- [ ] portability-restrict-system-includes [ maybe if we allow dlfcn.h? ] 

???
- [ ] bugprone-dynamic-static-initializers¶
- [ ] bugprone-lambda-function-name¶
- [ ] bugprone-swapped-arguments¶
- [ ] cppcoreguidelines-owning-memory
- [ ] google-runtime-int
- [ ] google-runtime-operator

Not yet
- [ ] modernize-replace-random-shuffle [ C++14 ]
- [ ] modernize-make-unique [ C++14 ] 
- [ ] modernize-concat-nested-namespaces [C++17]
- [ ] modernize-unary-static-assert [C++17]
- [ ] modernize-use-nodiscard [C++17]
- [ ] modernize-use-uncaught-exceptions [C++17]

**Comment by DavidPoliakoff** [comment]
I've gone through the whole list. Feel free to tell me I'm wrong about a check

**Comment by ajpowelsnl** [comment]
@crtrott  and @dalg24 -- do we want to do anything more with the clang-tidy check info?  If not, can we close the issue?  If so, can we firm up what needs to be done to complete this task?

**Comment by dalg24** [comment]
I am leaning towards close it.

**Comment by ajpowelsnl** [comment]
No advocates for this work at this time - closing until / unless this work has a champion.
