### ISSUE TITLE
CMake fails with Nvidia compilers when the GPU architecture option is not supplied

### ISSUE THREAD

**Issue by scottbiersdorff** [kokkos/kokkos#3207]
With the following cmake command:

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=nvc++ -DKokkos_ENABLE_COMPILER_WARNINGS=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_OPENMPTARGET=ON -DCMAKE_CXX_STANDARD=17 kokkos

I get:

...
CMake Error at cmake/kokkos_arch.cmake:418 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  cmake/kokkos_tribits.cmake:202 (INCLUDE)
  CMakeLists.txt:166 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

I believe the code in kokkos_arch.cmake could be guarded to check whether the GPU architecture is set.

**Comment by DavidPoliakoff** [comment]
Also, hey Scott, long time no see!

**Comment by scottbiersdorff** [comment]
> Also, hey Scott, long time no see!

Hi David! I thought I saw you work around this project.
