### ISSUE TITLE
KOKKOS_INLINE_FUNCTION meaning "inline" and "host/device" leading to questionable code

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3209]
So I'm looking at the UniqueToken PR, specifically these lines https://github.com/kokkos/kokkos/pull/3051/files#diff-708288b9f98bd06071a58b68dd990429R732 , where we check for `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST` macro.

This feels really bad, we're polluting a Host execution space with GPU implementation details and preprocessor branches, I'm assuming to avoid compiler warnings. Is there some way for us to separate the host/device aspect from the inline aspect to avoid what seem to me to be kludges to avoid compiler warnings?

**Comment by crtrott** [comment]
This is actually a requirement from NVCC. NVCC does not make __host__ __device__ part of the function overload resolution system, i.e. you can't have a __host__ and a __device__ function with the same signature. Hence you need to ifdef inside the functions.
