### ISSUE TITLE
Fix tutorials to track new Kokkos::View

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#323]
I think one or more of the tutorials need a few changes to track the new Kokkos::View. 04_dualviews uses array_intrinsic_type, for example.

**Comment by ndellingwood** [comment]
@ambrad Thanks for pointing that out, I checked with Carter and the tutorials need to be added to the testing. Marking this as feature request. @hcedwar  @crtrott 

I'm guessing you fixed the issue, but for issue reference `array_intrinsic_type` should be replaced by `scalar_array_type`

I built the tutorials on my laptop (clang compiler) and on kokkos-dev with cuda and did not have other build errors.

**Comment by ambrad** [comment]
Great, thanks! Yes, I switched the types and also seemed to have to write Kokkos::Impl::Timer instead of Kokkos::Timer.

**Comment by ndellingwood** [comment]
Another note, the most recent tutorial with learning materials (slides, codes) is available at [](https://github.com/kokkos/kokkos-tutorials)

**Comment by ndellingwood** [comment]
@ambrad Was that in the same example (04_dualviews) where you had the issue with the timer? I wasn't able to replicate.

**Comment by ndellingwood** [comment]
I also had runtime errors when running the cuda build of that example that need fixing. 
```
[ndellin@kokkos-dev 04_dualviews]$ ./dual_view.cuda 
Device Time with Sync: 0.073874 without Sync: 0.003030 
Host   Time with Sync: 0.497851 without Sync: 0.495363 
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
```

**Comment by ambrad** [comment]
You are right about Timer; sorry for the false alarm.

**Comment by ndellingwood** [comment]
@ambrad 
Bug fixes for tutorials in pull request #328 (a fix for the DynRankView performance test also squashed in there). 
All tutorials now pass with Cuda 7.5.18. 
Makefile paths are updated to nvcc_wrapper (i.e. ../../etc./config/nvcc_wrapper   Cuda builds only)
Thanks @crtrott and @hcedwar !

**Comment by hcedwar** [comment]
Add these to the nightly build

**Comment by hcedwar** [comment]
Christian will get this into Kokkos develop branch nightly tests.
