### ISSUE TITLE
Can I allocate a View w/ both WithoutInitializing & AllowPadding?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#324]
Is it possible to allocate a View with both WithoutInitializing and AllowPadding?  I don't see a way to nest those allocation parameters.  Do they just nest, as they do with the string label?

#319 would fix this because I wouldn't need to pass in AllowPadding at run time; the compile-time memory trait would suffice.

**Comment by mhoemmen** [comment]
https://github.com/trilinos/Trilinos/issues/423 depends on this.

**Comment by hcedwar** [comment]
View<...> a( view_alloc( "label" , WithoutInitializing , AllowPadding ) , N0 , N1 , ... );

**Comment by mhoemmen** [comment]
Thanks @hcedwar ! But see #325.  Also, when I try this, I get the following static_assert:

...
.../Trilinos/packages/kokkos/core/src/KokkosExp_View.hpp: In instantiation of ‘Kokkos::Experimental::Impl::ViewCtorProp<typename Kokkos::Experimental::Impl::ViewCtorProp<void, P>::type ...> Kokkos::Experimental::view_alloc(const Args& ...) [with Args = {const char*, Kokkos::Experimental::Impl::WithoutInitializing_t, Kokkos::Experimental::Impl::AllowPadding_t}]’:
.../Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:146:79:   required from ‘typename Tpetra::MultiVector<ST, LO, GO, NT>::dual_view_type {anonymous}::allocDualView(size_t, size_t, bool) [with ST = double; LO = int; GO = long long int; NT = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>; typename Tpetra::MultiVector<ST, LO, GO, NT>::dual_view_type = Kokkos::DualView<double**, Kokkos::LayoutLeft, Kokkos::Serial, void>; size_t = long unsigned int]’
.../Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp:273:70:   required from ‘Tpetra::MultiVector<S, LO, GO, N, classic>::MultiVector(const Teuchos::RCP<const Tpetra::Map<LocalOrdinal, GlobalOrdinal, Node> >&, size_t, bool) [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = long long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>; bool classic = false; size_t = long unsigned int]’
.../Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_DOUBLE_INT_LONG_LONG_SERIAL.cpp:78:3:   required from here
.../Trilinos/packages/kokkos/core/src/KokkosExp_View.hpp:425:3: error: static assertion failed: Cannot give pointer-to-memory for view allocation
   static_assert( ! return_type::has_pointer

**Comment by mhoemmen** [comment]
Here is the line of code in question:
```
typename dual_view_type::t_dev d_view (Kokkos::Experimental::view_alloc (label, Kokkos::Experimental::WithoutInitializing, Kokkos::Experimental::AllowPadding), lclNumRows, numCols);
```

**Comment by mhoemmen** [comment]
I'm not sure whether this is a question or bug, so I removed the "question" label.

**Comment by mhoemmen** [comment]
The answer to my question is "yes," so I'm calling this bug closed.  Thanks all!

**Comment by crtrott** [comment]
Assigning to Fall, I don't want closed issues on backlog. Its kind of weird to have completion rate higher than 0% on backlog ....
