### ISSUE TITLE
KOKKOS_IMPL_FORCEINLINE_FUNCTION redefined

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos#3249]
In Kokkos_Macros.hpp, various backends define KOKKOS_IMPL_FORCEINLINE_FUNCTION, only to have it redefined if KOKKOS_FORCEINLINE_FUNCTION is not defined.

If it gets redefined to the exact same thing then there is no warning, but that logic isn't correct.  What should the logic be?

**Comment by calewis** [comment]
@nliber This is possibly my fault.  Can you point out exactly where it is warning? I moved the definitions of the `KOKKOS_X_FUNCTION` macros into the IMPL names so we could annotate them in certain cases, it's entirely possible I missed something on some path.

**Comment by calewis** [comment]
@dalg24 does this mean that we are missing a backend in the testing? From a quick scan of the jenkins file we appear to use `-Werror`

**Comment by nliber** [comment]
I was doing this on building the SYCL backend, but the pattern is everywhere.  Here are the error messages from that build:

> core/src/Kokkos_Macros.hpp:368:9: warning: 'KOKKOS_IMPL_FORCEINLINE_FUNCTION' macro redefined [-Wmacro-redefined]
> #define KOKKOS_IMPL_FORCEINLINE_FUNCTION inline __attribute__((always_inline))
>         ^
> core/src/Kokkos_Macros.hpp:302:9: note: previous definition is here
> #define KOKKOS_IMPL_FORCEINLINE_FUNCTION inline
>         ^
>

**Comment by dalg24** [comment]
> @dalg24 does this mean that we are missing a backend in the testing? From a quick scan of the jenkins file we appear to use `-Werror`

The SYCL backend has not been merged into `develop` yet but you can look at #3231

**Comment by calewis** [comment]
@nliber does #3250 address this for you?

**Comment by masterleinad** [comment]
For me, #3250 fixes the warning when building the `SYCL` backend.

**Comment by calewis** [comment]
Closing this then.
