### ISSUE TITLE
AppleClang+Openmp not correctly detected

### ISSUE THREAD

**Issue by Chrismarsh** [kokkos/kokkos#3256]
Building master with openmp enabled on macos fails, despite openmp being available.

```
$ cmake ../kokkos -DKokkos_ENABLE_OPENMP=On
-- Setting default Kokkos CXX standard to 11
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Using -std=gnu++11 for C++11 extensions as feature
-- Execution Spaces:
--     Device Parallel: NONE
--     Host Parallel: OPENMP
--       Host Serial: NONE
--
-- Architectures:
-- Found TPLLIBDL: /usr/lib/libdl.dylib
CMake Error at cmake/kokkos_corner_cases.cmake:44 (MESSAGE):
  AppleClang failed OpenMP check.  You have requested
  -DKokkos_ENABLE_OPENMP=ON, but the AppleClang compiler does not appear to
  have been built with OpenMP support
Call Stack (most recent call first):
  cmake/kokkos_tribits.cmake:186 (INCLUDE)
  CMakeLists.txt:156 (KOKKOS_SETUP_BUILD_ENVIRONMENT)


-- Configuring incomplete, errors occurred!
See also "/Users/chris/omptest/build/CMakeFiles/CMakeOutput.log".
```

Specifically this check fails to detect openmp (installed via homebrew)
https://github.com/kokkos/kokkos/blob/master/cmake/kokkos_corner_cases.cmake#L39

The problem is two-fold:
1) try_compile _may_ need to have the include dir passed (as per https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3916) (it is required in this case)
2) try_compile needs to have the library path passed to successfully link

This is a minimum working example:
```
project(test)
cmake_minimum_required(VERSION 3.17)
set(OMP_FLAG_AppleClang "-Xclang -fopenmp")  #Xpreprocessor works too

TRY_COMPILE(APPLECLANG_HAS_OMP
    ${CMAKE_BINARY_DIR}
    ${CMAKE_BINARY_DIR}/clang_omp.cpp
    CMAKE_FLAGS "-DCOMPILE_DEFINITIONS:STRING=${OMP_FLAG_AppleClang}"
     		"-DINCLUDE_DIRECTORIES:STRING=/usr/local/opt/libomp/include"
    LINK_LIBRARIES -lomp -L/usr/local/opt/libomp/lib
    OUTPUT_VARIABLE OUT
  )

message(STATUS ${APPLECLANG_HAS_OMP})
message(STATUS ${OUT})
if (NOT APPLECLANG_HAS_OMP)
    message(FATAL_ERROR "no omp")
endif()

```
This approach is essentially a slimmed down version of what is in FindOpenMP 
https://gitlab.kitware.com/cmake/cmake/-/blob/v3.18.1/Modules/FindOpenMP.cmake

On my machine, I can compile a OpenMP program from command line by only specifying  `-Xclang -fopenmp -lomp`, so it's not entirely clear to me why try_compile requires this.

However, it seems like a more robust approach is to use the CMake FindOpenMP module that deals with all these edge cases.

System details:
macos catalina 10.15.4
```
$ uname -a
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```
```
$ clang++ --version
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
brew list libomp
/usr/local/Cellar/libomp/10.0.0/include/ (3 files)
/usr/local/Cellar/libomp/10.0.0/lib/libomp.dylib
/usr/local/Cellar/libomp/10.0.0/lib/libomp.a
```

**Comment by calewis** [comment]
@Chrismarsh it might be easier just to use a non apple build of LLVM.  Apple clang doesn't make this easy.  From a brief glance at the file from `brew edit llvm` I believe the brew version is built with openmp by default (unless you are on Arm).

**Comment by calewis** [comment]
@dhollman, @crtrott, @jjwilke, are we officially supporting apple clang with the openmp backend?

**Comment by Chrismarsh** [comment]
@calewis

>(unless you are on Arm).

I am not

I don't think it will take too much effort to work around this (unless there is some deeper issue I'm not familiar with specific to kokkos).

I can make it successfully build with the following changes:

1) 

In `kokkos_corner_cases.cmake`, replace the try_compile directive with
```
 find_package(OpenMP)
  set(APPLECLANG_HAS_OMP ${OpenMP_FOUND})
```

2)

In `kokkos_tribits.cmake` in the function `FUNCTION(KOKKOS_SET_LIBRARY_PROPERTIES LIBRARY_NAME)`,
add (I added at line 247) the following

```
  IF (KOKKOS_ENABLE_OPENMP)
  TARGET_LINK_LIBRARIES(
        ${LIBRARY_NAME} PUBLIC OpenMP::OpenMP_CXX
      )

  ENDIF()
```

I'm not familiar with the internals of kokkos and perhaps enabling other options with require adding this to the executable function too. But the gist is there  -- the target `OpenMP::OpenMP_CXX` does the right thing on macos with limited effort. I would also note there is likely utility in using findOpenMP for other platforms with non-standard search paths.

**Comment by masterleinad** [comment]
@Chrismarsh Would you mind opening a pull request for this?

**Comment by calewis** [comment]
@Chrismarsh, you aren't the first person to request this, I just don't know that we are supporting apple clang.  That decision is above my pay grade.

**Comment by Chrismarsh** [comment]
@masterleinad yup no problem. I've done it in pull #3257. I took a quick look to see if there was a better place to insert the openmp target directives. It wasn't obvious if `kokkos_arch.cmake` was a better place or not. I've left it in `kokkos_tribits.cmake` and perhaps you can comment further.

**Comment by calewis** [comment]
> @calewis That's fair. For what it's worth, I'd really like it :) I enjoy dev work on macos, but I do my actual runs on proper linux HPC infrastructure.

@Chrismarsh if you want an LLVM/clang that supports openmp without any hassle while still doing all your development on mac, it's as easy as `brew install llvm`, which installs other useful tools like clang-tidy, clangd, and clang-format as well.  I guess I don't understand why do all the work to get libomp to work with apple clang when you could just get a vanilla clang that already works?

**Comment by Chrismarsh** [comment]
@calewis I'm not sure I have an entirely satisfactory answer! One reason is that users of software I develop tend to use AppleClang if they run on macos, so it's easier to support if I also do development around it.  I have a vague recollection that some of my tooling years back only worked with AppleClang (CLion maybe?), so that also entrenched my usage. In short, the AppleClang + brew omp has worked well without much issue for many years, and I haven't taken the opportunity cost to further explore using homebrew's llvm.

**Comment by crtrott** [comment]
Also commenting on the Issue in a sec: I think we want this to work (my understanding for the longest time was that AppleClang didn't support OpenMP). But if we can make this work we should. What the best approach is is apparently still an open question. We will discuss this on Wednesday in our Team meeting. @Chrismarsh thanks for the PR we will discuss this on our call, if you want to be involved I can get you an invite to that discussions, otherwise we can just take it from here and sort out how to resolve this properly.

**Comment by Chrismarsh** [comment]
@crtrott Thanks for the follow up. I'll reply here instead on the PR to keep the discussion more contained.

Thanks very much for the suggestion of an invite. I'm not sure I have much else to add though as I'm not familiar enough with the rest of the kokkos build system assumptions/reqs to add much to that discussion.

>my understanding for the longest time was that AppleClang didn't support OpenMP

[As I understand it](https://mac.r-project.org/openmp/), they don't enable compiler driver support (ie `-fopenmp`) and don't ship libomp. However, you can still use the Xclang/Xpreprocessor  frontend option to enable it, which can then be linked against a user-installed libomp. 

My high-level flyby recommendation would be to 

1) Gatekeep `Kokkos_ENABLE_OPENMP`  with `find_package(OpenMP)` on all platforms. 

Conditional on support being found and requested:
2) Add the CXX flags to include `${OpenMP_CXX_FLAGS}`
3) Add the link target `OpenMP::OpenMP_CXX` 

This will then correctly do the right thing everywhere. You'll be able to remove most/all the bespoke code to figure out the right omp invocation, etc. I'm just not 100% sure of all the places that needs to be done in the kokkos build system.

Lastly, you need to ensure a [minimum CMake version of 3.12](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/) to get a CMake version with a `FindOpenMP.cmake` that supports AppleClang. 

Let me know if there is anything else I can provide & thanks for looking into this.

**Comment by etphipp** [comment]
Has there been any progress on this?  I see related configure errors when I try to configure Kokkos with AppleClang when the OpenMP library is not -lomp.  In my case, I build a library that links to Kokkos and Matlab, so I need to use Matlab's OpenMP library, which is actually the Intel OpenMP library, and thus a different filename.  Currently I work around it by also adding the library path to -lomp to my EXE/SHARED linker flags.  So that means it is actually linking to two OpenMP libraries, but fortunately -lomp is the last one and is unused.  I assume that if Kokkos used find_package(OpenMP), the user would be able to specify the correct libraries and paths?

**Comment by Chrismarsh** [comment]
hi @calewis, Just looping back on this regarding any possible outcomes?

**Comment by calewis** [comment]
I haven't looked at this in a long time this is really up to @crtrott and the person responsible for making sure that openmp is properly detected.  If they want to maintain support for Apple Clang they can do so.

**Comment by masterleinad** [comment]
@Chrismarsh Does #4105 work for you?

**Comment by Chrismarsh** [comment]
@calewis ah, my apologies. 

@masterleinad I can absolutely test this! What would be the best way to test this out? I'm not familiar with mixing and matching trilinos sub-package versions.

**Comment by calewis** [comment]
@Chrismarsh no worries.  Good luck.

**Comment by masterleinad** [comment]
> @masterleinad I can absolutely test this! What would be the best way to test this out? I'm not familiar with mixing and matching trilinos sub-package versions.

It should be enough to just apply the changes in that pull request directly to the corresponding files in a recent `Trilinos` development version. I would not assume that there are any incompatible changes.
Note that we still debating if #4105 works for all configurations we care about but another user experience is definitely helpful.
