### ISSUE TITLE
Compiling is failed with C++14 enabled.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#3268]
Kokkkos team may already recorgnizes this compiler error from Victor Brunini. I just want to let you know that the following error comes with c++14. 

```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/kokkos/core/unit_test/incremental/Test11a_ParallelFor_TeamThreadRange.hpp:75:43: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705
                 for (int i = startDim1;
                              ~~~~~~~~~~   ^   
```

**Comment by masterleinad** [comment]
Interesting. Can you provide some more details on what compiler and versions you are using and how you configured `Kokkos`? 
What's the commit you are trying to compile?

**Comment by kyungjoo-kim** [comment]
This happens with compiling Trilinos current master branch with c++14. I did not try with the stand-alone kokkoks. I compiled this on V100 weaver testbed. I use ``module load devpack/20190814/openmpi/4.0.1/gcc/7.2.0/cuda/10.1.105``.

**Comment by masterleinad** [comment]
Would you have a small reproducer for this problem? So far, we are not aware of any issues with C++14 support in `Kokkos`.

**Comment by ndellingwood** [comment]
@kyungjoo-kim can you share your configuration with us?

Likely related to this https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83204, observed for example in https://github.com/trilinos/Trilinos/pull/7767#issuecomment-668180880 by Victor regarding similar issues in other packages.
I think Trilinos is testing c++14 support with gcc/8.3.0 per https://github.com/trilinos/Trilinos/pull/7353 but not gcc/7.

@masterleinad I added c++14 and c++17 nightly testing for newer gcc compilers but not gcc/7 nor gcc/7+cuda/10 combo, I'll test this now and add those tests to the nightlies, will put in a PR to resolve issues that show up, sorry for miss

**Comment by kyungjoo-kim** [comment]
@masterleinad @ndellingwood It looks like that the problem is already fixed in the kokkos but it is not merged into Trilinos. I see that the kokkos repo uses ``[=]`` while trilinos version uses ``[&]``. Closing this issue now.

**Comment by ndellingwood** [comment]
Add confirmation, I tested Kokkos develop with the devpack on weaver without build issues with this config:

```
../../generate_makefile.bash --kokkos-path=${HOME}/kokkos --compiler=${HOME}/kokkos/bin/nvcc_wrapper --with-cuda --with-cuda-options=enable_lambda --arch=Power9,Volta70 --cxxstandard=14
```

resulting in this cmake configure line:

```
cmake -DCMAKE_CXX_COMPILER=/ascldap/users/ndellin/kokkos/bin/nvcc_wrapper -DCMAKE_CXX_FLAGS= -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX= -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ARCH_POWER9=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_CUDA_LAMBDA=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE /ascldap/users/ndellin/kokkos
```
