### ISSUE TITLE
Edit ViewMapping so assigning Views with the same custom layout compiles when const casting

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#327]
Christian figured out a fix for this on our side, but I wanted to submit a ticket to get it edited in the main branch and have it tracked.  The following doesn't work:

View\<double\*, CustomLayout\> a("a",5);
View\<const double\*, CustomLayout\> b = a;

**Comment by crtrott** [comment]
I believe a simple change to the default ViewMapping should be sufficient (the one which simply assigns m_offset and m_handle).

**Comment by crtrott** [comment]
Pushed to develop branch.
