### ISSUE TITLE
Mature HBM Memory Support

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#330]
There  are some experimental capabilties in right now using the memkind library. We need to mature this and support the different KNL Modes.

**Comment by mhoemmen** [comment]
Would be nice if we had memory space instances and HBM and DDR had the same type.  That way, we would only have to compile kernels once for running in HBM or DDR.

**Comment by crtrott** [comment]
The low level management approach to HBM on KNL is a bit more in flux again. We might need to postpone this a bit further.

**Comment by crtrott** [comment]
A new version of Memkind seems to have resolved some of the issues we had.

**Comment by crtrott** [comment]
ou go to bowman and load the module memkind/20160811​

In the Makefile system you compile Kokkos with the option KOKKOS_USE_TPLS=experimental_memkind

Now the default memory space of OpenMP is Experimental::HBWSpace.
The HostMirror will be in HostSpace. You can also explicitly use the two obviously. Basically it should work like CudaSpace and HostSpace when you compile for GPUs, just that you can access both memory spaces within and outside of kernels. So if your current app works for Cuda then it will work also for this. 

For Trillions its probably a bit more tricky. You might want to add a new TPL to the Trillions build system for memkind. You need to link -lmemkind, and also set the include directory.  
On top of it we need to add the cmake defines for memkind to the Kokkos's came files. I know ow to do that so maybe I will just do it tomorrow. 

Pthreads does not set HBWSpace as the default right now when you enable it. But I can add that simple enough as well.

Because Memkind and the OS was updated since I implemented this it all works without additional environment variables.

**Comment by ajpowelsnl** [comment]
Obsolete -- no other platform needs this feature.
