### ISSUE TITLE
TeamPolicy with Kokkos::AUTO_t on GPUs

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos#331]
I am trying to determine team sizes using Kokkos::AUTO_t() as  

```c++
  const int leage_size = 100;
  typedef Kokkos::TeamPolicy<MyExecSpace> team_policy_t ;

  team_policy_t my_policy_t1 (leage_size, Kokkos::AUTO_t(), 1);
  team_policy_t my_policy_t2 (leage_size, Kokkos::AUTO_t(), 2);
  team_policy_t my_policy_t4 (leage_size, Kokkos::AUTO_t(), 4);
  team_policy_t my_policy_t8 (leage_size, Kokkos::AUTO_t(), 8);
  team_policy_t my_policy_t16 (leage_size, Kokkos::AUTO_t(), 16);
  team_policy_t my_policy_t32 (leage_size, Kokkos::AUTO_t(), 32);

  std::cout 
            << "my_policy_t1.teamsize():" << my_policy_t1.team_size()
            << "\nmy_policy_t2.teamsize():" << my_policy_t2.team_size()
            << "\nmy_policy_t4.teamsize():" << my_policy_t4.team_size()
            << "\nmy_policy_t8.teamsize():" << my_policy_t8.team_size()
            << "\nmy_policy_t16.teamsize():" << my_policy_t16.team_size()
            << "\nmy_policy_t32.teamsize():" << my_policy_t32.team_size()
            << std::endl;
```

1- It prints always -1 if the MyExecSpace is Kokkos::Cuda. But I get the correct team size if I print it in device (parallel region of functor). 
2- It seems to be setting team_size * vector_size = 128 on K80. team_size_max was returning 256 for such cases. Doesn't 128 threads on GPU usually under-utilize the SM's?

**Comment by crtrott** [comment]
Hi

the reason it return 1, is that it can only determine the actual team size, if you give it a functor. Furthermore we might change that in the future to allow auto-tuning, so the actual team_size might even change over time for the same functor. 

Also 128 does not underutilize the SM. 128x16 = 2048 the max number of threads per SM. AUTO will choose the smallest team size which maximizes occupancy considering the amount of registers used per thread and the amount of shared memory used per team. Going this way allows the maximum scheduling flexibility and thus typically results in better performance if the total number of teams is high enough. AUTO will also look at the total number of teams, if small I believe it increases team size.

**Comment by mndevec** [comment]
Thanks Christian!

**Comment by crtrott** [comment]
Btw: you can just do Kokkos::AUTO (or Kokkos::AUTO() for that matter). Its actually a macro which returns Kokkos::AUTO_t() and Kokkos::AUTO_t()() also returns Kokkos::AUTO_t() because the () operator is a static function returning that ....)

**Comment by mndevec** [comment]
By the way, I was using the team size to determine league size such as:
 overall_work / teamsize + 1
as 1 unit work is usually done by single team member. What is the correct way to set up the league size with Kokkos::AUTO_t?

**Comment by mndevec** [comment]
After we talked today, I am changing my functor's parallel regions. I am calling the parallel  region as below. 
```c++
Kokkos::parallel_for(  team_policy_t (num_overall_work / team_work_size + 1 , Kokkos::AUTO_t(), vector_size), tm);
```
And I am changing the parallel regions as 
```c++
  void operator()(const team_fill_member_t & teamMember) const {
    const nnz_lno_t teamsize = teamMember.team_size();
    const nnz_lno_t team_row_begin = teamMember.league_rank() * teamsize * team_work_size;
    const nnz_lno_t team_row_end = KOKKOSKERNELS_MACRO_MIN(team_row_begin + team_work_size, num_rows);
    for (nnz_lno_t row_index = team_row_begin + teamMember.team_rank(); row_index < team_row_end; i += teamsize){
   //each team member performs a row operation via threadvectorrange
  }
```
Therefore, because of the inner loop each thread works on the consecutive row indices. This makes sense for GPUs. 

My question is if that is the way to go for CPUs. Should I make my threads within same team work on the data that is as close as possible to improve locality, or should I try to spread their work as much as possible to avoid false sharing between them.

**Comment by crtrott** [comment]
First your row_begin shouldn't use teamsize (just league_rank * team_work_size). Then you shouldn't try to do your own scheduling but rather you nested parallel for:

You should do:
```C++
 void operator()(const team_fill_member_t & teamMember) const {
    const nnz_lno_t teamsize = teamMember.team_size();
    const nnz_lno_t team_row_begin = teamMember.league_rank() * team_work_size;
    const nnz_lno_t team_row_end = KOKKOSKERNELS_MACRO_MIN(team_row_begin + team_work_size, num_rows);
    Kokkos::parallel_for(Kokkos::TeamThreadRange(teamMember,team_row_begin,team_row_end), [&] (const nnz_lno_t& row_index) {
     //each team member performs a row operation via threadvectorrange
    }
  }
```

This will to the right type of splitting depending on the architecture.

**Comment by mndevec** [comment]
Okay, I totally forgot about the use of TeamThreadRange, thanks for the help!
