### ISSUE TITLE
pgfortran linking issue

### ISSUE THREAD

**Issue by ascheinb** [kokkos/kokkos#3325]
With the newest Kokkos release, the imported link flags from KokkosTargets.cmake include `-arch=` which is apparently not supported by pgfortran:

`pgfortran-Error-Unknown switch: -arch=sm_70`

(Not urgent)

**Comment by crtrott** [comment]
Is it ok if we only support this with CMake 3.18? CMake 3.18 can distinguish linker language and makes it non-attrocious to support it. Duplicated in #3355

**Comment by ascheinb** [comment]
Yes, that's fine with us!
