### ISSUE TITLE
Zero length reductions with kokkos view result argument fail for CUDA

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#3331]
There are multiple issues resulting from a short cut in the reduction code when the length of the reduction is zero.
The shortcut calls the initialization of the variable on the host inline which can go wrong for multiple reasons:

- You provided a device view as result argument.
- You are using a functor with init or final function which can't actually call its init or final function on the host
- You are using a custom reducer who's init function is not callable on the host. 

This would affect the CUDA, HIP and potentially OpenMPTarget backend.

**Comment by ndellingwood** [comment]
Addressed by #3364 as part of 3.2.1
