### ISSUE TITLE
Candidates for cherry-picking into 3.2.1

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#3334]
The aim of the issue is to compile a list of PRs to cherry-pick into the upcoming patch release:
* #3332
* #3313
* #3373

**Comment by ndellingwood** [comment]
In progress:

* #3364
* #3269

**Comment by crtrott** [comment]
#3383

**Comment by crtrott** [comment]
#3387

**Comment by crtrott** [comment]
#3384

**Comment by ndellingwood** [comment]
See PR #3406

**Comment by ndellingwood** [comment]
#3407

**Comment by ndellingwood** [comment]
For zero-length redux:
#3452 
#3470

**Comment by dalg24** [comment]
#3473

**Comment by ndellingwood** [comment]
#3543

**Comment by ndellingwood** [comment]
#3558

**Comment by ndellingwood** [comment]
PR #3570 includes round two of cherry-picks to release-candidate 3.2.1

**Comment by ndellingwood** [comment]
One more cherry-pick for issue #3428 (driver update was not sufficient)

#3580
