### ISSUE TITLE
Clang compiler error with named parallel_reduce, tags, and TeamPolicy.

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#335]
The following code compiles with gcc, intel, nvcc, but not clang (3.6 and 3.8):

struct Foo {

  struct MyTag {
  };

  void compute() {
    double totalEnergy = 0.0;
    Kokkos::parallel_reduce("name", Kokkos::TeamPolicy<MyTag>(100, Kokkos::AUTO), *this, totalEnergy);
  }

  KOKKOS_INLINE_FUNCTION void operator() (const MyTag&, const Kokkos::TeamPolicy<MyTag>::member_type& team, double& val) const {
    int index = team.league_rank();
    val += index;
  }

};

int main(int argc, char* argv[]) {

  Kokkos::initialize(argc, argv);

  Foo foo;
  foo.compute();

  Kokkos::finalize();

}

**Comment by crtrott** [comment]
This was incidentally fixed by the parallel_reduce implementation changes I worked on.
