### ISSUE TITLE
Adding `-arch=sm_XY` to kokkos link line creates trouble for apps that use f90 linker

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#3355]
I''m using the latest release, 3.2.00, and am having trouble linking kokkos to our application, due to the `-arch=..` flag. Our application has a F90 main entry, so we use a f90 linker. This causes the flag `-arch=sm_*` to be unrecognized.

The problem seems to stem from the following line:

```
IF(KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE OR KOKKOS_CXX_COMPILER_ID STREQUAL NVIDIA)
    GLOBAL_APPEND(KOKKOS_LINK_OPTIONS "${CUDA_ARCH_FLAG}=${FLAG}")
ENDIF()

```
I have a couple of questions on this:
1) if the user enabled cuda's rdc, then isn't the compiler always going to be nvidia? In which case, what's the point of checking the compiler id?
2) I understand why one would need that flag for rdc, but is it really needed always? Meaning, if I don't use rdc, do I really need the arch flag on my link line? I manually removed it from the `link.txt` for my f90 executable target, and it compiled and run. Maybe it was just a coincidence. But if not, then shouldn't kokkos add this flag only to the _private_ section (in cmake lingo) of the target's link properties?

Edit: [this](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-dlink-time-opt) seems to suggest this is needed for some link time optimization. Assuming that's the case (and point 2 above doesn't apply), is there a way to disable this optimization, and not get the flag in the link options?

**Comment by masterleinad** [comment]
The corresponding pull request is https://github.com/kokkos/kokkos/pull/3130. Basically, CUDA 11 wanted to have the architecture on the link line.

**Comment by bartgol** [comment]
So, adding the arch flag on the link line suppresses a CUDA11 warning? It makes it so that linking from f90 becomes a headache though. Without a way to prevent this flag from getting in the kokkos targets properties, I am bound to use a version that predates that PR, which is only going to work temporarily.

Did anyone report a similar issue before? Do you guys have any suggestion on how to deal with this? I am not 100% sure that putting this flag in the private section of the target properties would fix this; so as an alternative, would it be acceptable to add this link flag only if a certain cmake option was set (and we could make it ON by default)?

**Comment by masterleinad** [comment]
#3325 describes a similar issue.

**Comment by masterleinad** [comment]
Would you have a minimal reproducer?

**Comment by bartgol** [comment]
Sure:

CMakeLists.txt:
```
project(reproducer CXX Fortran)

add_subdirectory(${KOKKOS_PATH} ${CMAKE_CURRENT_BINARY_DIR}/kokkos)

add_executable(test main.f90)
target_link_libraries(test kokkos)
set_target_properties(test PROPERTIES LINKER_LANGUAGE Fortran)
```
where you need to set `KOKKOS_PATH` to kokkos src folder (I used the 3.2.00 release tag).

main.f90:
```
program test

  integer :: i

  i = 1 

  print*, "i: ", i

end program test
```
I used gcc 7.2, and cuda 10.1.105. Result:

```
...
[ 92%] Built target kokkoscontainers
[ 96%] Building Fortran object CMakeFiles/test.dir/main.o
[100%] Linking Fortran executable test
gfortran: error: unrecognized command line option ‘-arch=sm_70’
make[2]: *** [test] Error 1
make[1]: *** [CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by crtrott** [comment]
There is a larger issue here. We generally assume you use the same linker as we do for downstream apps. My guess is we need a full "do not propagate linker flags options" which means you are on your own to figure out how to do this correct (for example adding the correct link to the correct openmp runtime library we used or so).

**Comment by bartgol** [comment]
Well, I think some link flags/options can stay in the public section of the target property, but this one concerning compute capability seems like a good candidate to be in the private one.

More in general, (assuming I understand cmake machinery correctly) I think that if kokkos uses, say, libA but does not plan to (directly) expose it, then it seems appropriate to link it privately. If my app also uses libA, it is up to me to make sure I link it to my targets, and that the same library (or a "compatible" one) is used (to avoid link havoc). Kokkos can still store (and share) information about link deps in some cmake var, that downstream apps can inspect if they need.

**Comment by crtrott** [comment]
The problem is that just in general it is not clear that this is valid. It works for NVCC but I am not sure it works for Clang and I am pretty sure it doesn't work with the default settings for HIP and it doesn't work for OpenMPTarget (which needs to choose the correct internal device library which it does via the architecture flag).

**Comment by bartgol** [comment]
@crtrott ok, thanks for the explanation. 

Currently, I got  around it in our e3sm fork of kokkos, by adding a cmake option (as well as a generate_makefile one) that allows us to disable the propagation of the flag. Working on a fork is ok, though not the best option. Would kokkos consider a solution like that, meaning, adding a coniguration option to disable flag propagation? Or is this too much of a corner case?

Actually, re-reading your post, it might be that suppressing that link flag is plain wrong (at least in terms of portability). In which case I don't really know what the right thing to do is.

**Comment by jjwilke** [comment]
Sorry, I'm a bit late getting to this. I believe we can set the requirement that when the link language is C++, you MUST be using nvcc.  I can move these flags inside a generator expression so that they are conditionally omitted when the link language is something else.

**Comment by bartgol** [comment]
@jjwilke that seems like a fair solution. I've used gen expression for build flags before, but never thought of this for linker language. But if that's possible, it seems like the best solution.

**Comment by crtrott** [comment]
Is it ok if we only support this with CMake 3.18? CMake 3.18 can distinguish linker language and makes it non-atrocious to support this.

**Comment by bartgol** [comment]
Yes, this seems like a good compromise. Thanks!

**Comment by crtrott** [comment]
ok cool, the cmake in PR #3355 for the 3.13-3.17 case is just incomprehensible for most of us, not sure I can find a reviewer who will promise me he can maintain that :-D

**Comment by jjwilke** [comment]
Posting just so we don't forget the horror and wonder why we aren't supporting prior to CMake 3.18:

````cmake
  ELSEIF(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.13")
    #I can use link options
    #check for CXX linkage in a super complicated way
    SET(IS_STATIC $<STREQUAL:$<TARGET_PROPERTY:TYPE>,STATIC_LIBRARY>)
    #I can't query linker_language on static libraries (and it doesn't matter anyway)
    SET(LINK_TYPE $<${IS_STATIC}:CXX>$<$<NOT:${IS_STATIC}>:$<TARGET_PROPERTY:LINKER_LANGUAGE>>)
    TARGET_LINK_OPTIONS(
      ${LIBRARY_NAME} PUBLIC
      $<$<STREQUAL:${LINK_TYPE},CXX>:${KOKKOS_LINK_OPTIONS}>
````
