### ISSUE TITLE
Feature request for Kokkos to provide Kokkos::atomic_fetch_max and atomic_fetch_min

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#336]
We can use the Kokkos::Impl::atomic_fetch_oper(...) mechanism, but this is in the Impl namespace and having hard-coded max and min atomics seems like it would be useful to the community.

**Comment by ndellingwood** [comment]
Add necessary unit tests, along with other missing tests (e.g. binary operations); see #341 as well.

**Comment by hcedwar** [comment]
Note: no corresponding functionality in C++11 atomics

**Comment by crtrott** [comment]
Yeah, but that doesn't mean we shouldn't support it. I rather have us supporting this, than each team doing its own implementation.

**Comment by ndellingwood** [comment]
In develop branch
