### ISSUE TITLE
Make apply-clang-format not format my entire kokkos-root/.. directory accidently.

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#3365]
the apply-clang-format script unconditionally cds one level up and then runs. If I do source scripts/apply-clang-format in the root dir it will clang-format my entire parent directory! This happened now twice to me since I am in the habid of sourcing scripts instead of just running them. I want this fixed ...

**Comment by calewis** [comment]
@masterleinad instead of trying to find tracked files, you might just want to look into git-clang-format.  Aside from checking for the clang-format version does the script really do anything different than git-clang-format?

**Comment by masterleinad** [comment]
>  Aside from checking for the clang-format version does the script really do anything different than git-clang-format?

Yes: https://github.com/kokkos/kokkos/blob/03ded4e816da5927b946065b005ebfdf38e5a438/scripts/apply-clang-format#L31-L39

**Comment by masterleinad** [comment]
I mean no one prevents you from using git-clang-format locally but that would also not work if you are in a parent directory and try to get the formatting for Kokkos right. We can, of course, consider replacing https://github.com/kokkos/kokkos/blob/03ded4e816da5927b946065b005ebfdf38e5a438/scripts/apply-clang-format#L27-L29 with `git-clang-format`.
