### ISSUE TITLE
Negative vector lengths can lead to negative "max team sizes" in TeamPolicy's

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3371]
So I was looking at how we calculate the possible team sizes. It turns out that if a CUDA TeamPolicy has a negative vector length (which it will if it's specified auto) we'll happily divide the max team size (1024) by that value to get the max team size. 1024/-1 gets us a team size of -1024, which current hardware doesn't support.

I'm working around this in the Tuning I'm doing, but wanted to document it with an issue

**Comment by fnrizzi** [comment]
however, the team size seems to be -1 when using AUTO. Not sure this makes sense, so i willbring this up to the team.

**Comment by fnrizzi** [comment]
so it seems this is not a problem anymore
