### ISSUE TITLE
Failure in Kokkos_HIP_Parallel_Range.hpp

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#3386]
@masterleinad @dalg24 
I am seeing the following error when compiling Kokkos-Kernels:
```
/home/lberge/kk_lucbv_build/caraway/kokkos-install/include/HIP/Kokkos_HIP_Parallel_Range.hpp:348:23: error: no matching function for call to 'min'
      const dim3 grid(std::min(block.y, (nwork + block.y - 1) / block.y), 1, 1);

// then the compiler follows a bunch of includes until we reach the following

/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/algorithmfwd.h:383:5: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned int' \
vs. 'long')
    min(const _Tp&, const _Tp&);
    ^
/opt/rocm-3.5.0/llvm/lib/clang/11.0.0/include/../include/cuda_wrappers/algorithm:101:1: note: candidate template ignored: deduced conflicting types for parameter '__T' ('unsigned int' vs. 'long')
min(const __T &__a, const __T &__b) {
^
```
If I followed things well, `block` is of type `dim3` which is a HIP/CUDA struct that contains three `uint32_t` and `nwork` has type `index_type` which is defined as `using index_type     = typename Policy::index_type;` on line 159 in `Kokkos_HIP_Parallel_Range.hpp`.

Would it make sense to cast `nwork` to `uint32_t` to follow what `dim3` defines or do it the other way around and follow the user's choice defined in the range policy?
I like the `uint32_t` better because the user can set anything for `index_type`, in any case we need to cast to get consistent template deduction right?

Final info I think is useful, grepping for `min` in Kokkos_Cuda_Parallel.hpp (I quite dislike lines 1641 and 1642, inconsistent...):
```
$ grep -rn "min" core/src/Cuda/Kokkos_Cuda_Parallel.hpp
209:        std::min(requested_vector_length, vector_length_max());
497:        std::min(
551:          min((m_rp.m_upper[0] - m_rp.m_lower[0] + block.x - 1) / block.x,
553:          min((m_rp.m_upper[1] - m_rp.m_lower[1] + block.y - 1) / block.y,
565:          min((m_rp.m_upper[0] - m_rp.m_lower[0] + block.x - 1) / block.x,
567:          min((m_rp.m_upper[1] - m_rp.m_lower[1] + block.y - 1) / block.y,
569:          min((m_rp.m_upper[2] - m_rp.m_lower[2] + block.z - 1) / block.z,
582:          min(static_cast<index_type>(m_rp.m_tile_end[0] * m_rp.m_tile_end[1]),
584:          min((m_rp.m_upper[2] - m_rp.m_lower[2] + block.y - 1) / block.y,
586:          min((m_rp.m_upper[3] - m_rp.m_lower[3] + block.z - 1) / block.z,
598:          min(static_cast<index_type>(m_rp.m_tile_end[0] * m_rp.m_tile_end[1]),
600:          min(static_cast<index_type>(m_rp.m_tile_end[2] * m_rp.m_tile_end[3]),
602:          min((m_rp.m_upper[4] - m_rp.m_lower[4] + block.z - 1) / block.z,
614:          min(static_cast<index_type>(m_rp.m_tile_end[0] * m_rp.m_tile_end[1]),
616:          min(static_cast<index_type>(m_rp.m_tile_end[2] * m_rp.m_tile_end[3]),
618:          min(static_cast<index_type>(m_rp.m_tile_end[4] * m_rp.m_tile_end[5]),
997:  // Determine block size constrained by shared memory:
1042:      dim3 grid(std::min(int(block.y), int((nwork + block.y - 1) / block.y)), 1,
1291:  // Determine block size constrained by shared memory:
1345:      const dim3 grid(std::min(int(block.y), int(nwork)), 1, 1);
1641:          UseShflReduction ? std::min(m_league_size, size_type(1024 * 32))
1642:                           : std::min(int(m_league_size), m_team_size);
2096:  // Determine block size constrained by shared memory:
2131:          std::min(int(grid_max), int((nwork + block_size - 1) / block_size));
2387:  // Determine block size constrained by shared memory:
2422:          std::min(int(grid_max), int((nwork + block_size - 1) / block_size));
```

**Comment by dalg24** [comment]
> Final info I think is useful, grepping for min in Kokkos_Cuda_Parallel.hpp (I quite dislike lines 1641 and 1642, inconsistent...):

The HIP backend has the same issue
https://github.com/kokkos/kokkos/blob/593597c371eeb3485d01d1f8b34f5491fa80f9ea/core/src/HIP/Kokkos_HIP_Parallel_Team.hpp#L824-L829

**Comment by dalg24** [comment]
> Would it make sense to cast nwork to uint32_t to follow what dim3 defines or do it the other way around and follow the user's choice defined in the range policy?
I like the uint32_t better because the user can set anything for index_type, in any case we need to cast to get consistent template deduction right?

Casting to `uint_32_t` is fine by me.   Do you want to open a pull request?

**Comment by lucbv** [comment]
Yes, I can make a PR for that, should I cast consistently variables being compare in `std::min` when the output is used to construct a `dim3` or just the one that causes trouble?
Also I am not sure what the policy is regarding PR testing for Kokkos?

**Comment by masterleinad** [comment]
I am seeing
```
$ git grep "min" | grep "dim3"
core/src/Cuda/Kokkos_Cuda_Parallel.hpp:      dim3 grid(std::min(int(block.y), int((nwork + block.y - 1) / block.y)), 1,
core/src/Cuda/Kokkos_Cuda_Parallel.hpp:      const dim3 grid(std::min(int(block.y), int(nwork)), 1, 1);
core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp:      dim3 const grid(std::min(static_cast<index_type>(m_policy.m_tile_end[0] *
core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp:      const dim3 grid(std::min(int(block.y), int(nwork)), 1, 1);
core/src/HIP/Kokkos_HIP_Parallel_Range.hpp:      const dim3 grid(std::min(block.y, (nwork + block.y - 1) / block.y), 1, 1);
```
so most of the places explicitly cast to a common type already. If you have a look to make everything consistent, that would be appreciated of course.
It seems that we haven't covered this code path yet so if you could come up with a simple test case hitting it, that would also be good.

**Comment by lucbv** [comment]
@masterleinad, yes I think I will just uniformly cast these to `uint32_t` as it happens implicitly in the dim3 constructor.
I will also look into writing a small test to demonstrate the issue.

**Comment by kyungjoo-kim** [comment]
I have a similar issue and I just fixed it by using std::min<int>
