### ISSUE TITLE
parallel_reduce with multiple reducers appears not to support MDRangePolicy

### ISSUE THREAD

**Issue by PhilipFackler** [kokkos/kokkos#3394]
The following code does not compile.
```c++
using Range3d = Kokkos::MDRangePolicy<Kokkos::Rank<3>>;
double a{}, b{}, c{};
Kokkos::parallel_reduce(Range3d({0,0,0}, {m,n,p}),
        KOKKOS_LAMBDA (std::size_t i, std::size_t j, std::size_t k, auto& r) {
    //...
},
a, b, c);

```
Unless I am missing something, this use case is not supported, since `Kokkos::Impl::CombinedReductionFunctorWrapperImpl::operator()` takes just a single index parameter, but three indices are being passed to it.

( the `auto` is expected to be deduced as `Kokkos::Impl::CombinedReducerValueImpl<Kokkos::Impl::integer_sequence<long unsigned int, 0, 1, 2>, double, double, double>`)

**Comment by dhollman** [comment]
Yeah, this was left out of the initial feature implementation for simplicity for the moment, but I'm happy to add support for this. It would be a pretty small change—the main reason I left it out is that dealing with variadic arguments in the middle of a function signature in C++ is kind of a mess (but pretty straightforward if you know what you're doing, so I can just add this pretty easily).

**Comment by dhollman** [comment]
Also, you are missing something: the combined reducer interface passes you the reduction outputs as separate parameters. You should never be interacting with a `CombinedReducerValueImpl` directly.

**Comment by dhollman** [comment]
@PhilipFackler done, assuming it passes CI (and code review); see #3395. (Normally we don't do feature requests that quickly, but I was in the mood for something quick this afternoon).

**Comment by PhilipFackler** [comment]
Thanks for this.
