### ISSUE TITLE
reduction_identity has commented out default implementation

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#3396]
Why is the struct `reduction_identity` not default defined, i.e. why is this code commented?

Moreover, for initing `sum` the commented function returns `T()`, but `T{}` is maybe more appropriate. Example use case: immediately works on CUDA vector types.

```
    template<typename T>
    struct reduction_identity
    {
        kforceinline constexpr static T sum() { return T {}; }
        // ...
    };
```

**Comment by dalg24** [comment]
> Why is the struct reduction_identity not default defined, i.e. why is this code commented?

Would you elaborate why you think that is an issue?

**Comment by j8asic** [comment]
The commented code seems helpful. And it's more of a small annoyance than an issue, as many (user) types can be zero-initialized with curly braces to init the sum reduction.

**Comment by PhilMiller** [comment]
At least one reason not to define `reduction_identity` to return default-construction for arbitrary types is that it would mean that we would silently compile wrong code in which the default constructed value is not actually a reduction identity. It's a tradeoff between convenience for the easy cases, and correctness for cases that are more complicated. This would include cases where a developer forgets to define a correct identity, and also cases where they think they have, but have made a mistake (i.e. spelling error, mismatched the actual `value_type`, etc).
