### ISSUE TITLE
misspelled variable name in Kokkos_Atomic_Fetch + missing unit tests

### ISSUE THREAD

**Issue by jdsteve2** [kokkos/kokkos#340]
On [line 96](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp#L96) of Kokkos_Atomic_Fetch_Add.cpp, and on [line 76](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp#L76) of Kokkos_Atomic_Fetch_Sub.cpp, "assumed.i" should be "assume.i". Produces compile error, "assumed" undeclared.

**Comment by ndellingwood** [comment]
Missing unit tests, identify and add.
