### ISSUE TITLE
Cmake target_precompile_headers causes build failure

### ISSUE THREAD

**Issue by T-Captum** [kokkos/kokkos#3421]
We have tried to use cmakes `target_precompile_headers` together with kokkos. Using a simple pch.h that only contains \<iostream\> we get 
```
/usr/include/c++/8/bits/stringfwd.h:70:37: error: redefinition of default argument for ‘class _Traits’
/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:21:3: error: conflicting declaration ‘typedef struct __mbstate_t __mbstate_t’
/usr/include/x86_64-linux-gnu/bits/types/__locale_t.h:28:8: error: redefinition of ‘struct __locale_struct’
/usr/include/c++/8/bits/postypes.h:112:7: error: redefinition of ‘class std::fpos<_StateT>’
/usr/include/c++/8/bits/postypes.h:216:1: error: redefinition of ‘template<class _StateT> bool std::operator==(const std::fpos<_StateT>&, const std::fpos<_StateT>&)’
/usr/include/c++/8/bits/postypes.h:221:1: error: redefinition of ‘template<class _StateT> bool std::operator!=(const std::fpos<_StateT>&, const std::fpos<_StateT>&)’
/usr/include/c++/8/iosfwd:76:70: error: redefinition of default argument for ‘class _Traits’
```
and hundreds more lines of error code from the std library. We are not sure why. The actual command that causes these errors is
```

 [1/5] Building CXX object CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx.gch
FAILED: CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx.gch
/home/tim/dev/VoxelGrid/3rdParty/kokkos/bin/nvcc_wrapper   -I../src -isystem ../3rdParty/kokkos/include --relocatable-device-code=true -expt-extended-lambda -arch=sm_75 -Xcompiler -fopenmp -std=c++14 -Winvalid-pch -x c++-header -include /home/tim/dev/VoxelGrid/build/CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx -MD -MT CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx.gch -MF CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx.gch.d -o CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx.gch -c CMakeFiles/VoxelGridTest.dir/cmake_pch.hxx.cxx
```

We use g++-8 and nvcc 10.1 under Ubuntu 20 and are using Kokkos through the cmake find_package route.

**Comment by crtrott** [comment]
hm not sure what this is. But it doesn't look like a Kokkos issue per se. My guess is its an issue with nvcc/gcc8 exposed by target_precompile_headers.

**Comment by T-Captum** [comment]
I agree it doesn't seem like a Kokkos issue. However running 
```
cmake_minimum_required(VERSION 3.1)
set (CMAKE_CXX_STANDARD 14)

project(VoxelGrid LANGUAGES CXX)
file(GLOB srcfiles 
${PROJECT_SOURCE_DIR}/src/*.h   
${PROJECT_SOURCE_DIR}/src/*.cpp
)
add_executable(VoxelGridTest exe/main.cpp ${srcfiles})
target_include_directories(VoxelGridTest PUBLIC ${PROJECT_SOURCE_DIR}/src)

target_precompile_headers(VoxelGridTest PUBLIC ${PROJECT_SOURCE_DIR}/pchs/pch.h)
```
works, and adding 
```
find_package(Kokkos REQUIRED)
target_link_libraries(VoxelGridTest Kokkos::kokkos)

```
breaks it. We tried this on two different computers. Thanks a lot in advance.

**Comment by crtrott** [comment]
Aren't you using the launchrule thing? I.e. do you compile anything with nvcc without the kokkos dependency? In particular anything which includes iostream etc. the stuff which shows up in the error message above?

**Comment by T-Captum** [comment]
Yes we are using the launch rule thing. We specifically tried this with the usual kokkos build to see if this is a launch rule problem or a general problem. With the launch rule system we get the same error. At no other point in our little test setup are we compiling <iostream>. I am not sure which files actually get processed by nvcc with and without kokkos dependecy. What exactly do you mean by kokkos dependency?^^

**Comment by crtrott** [comment]
So if you don't have a Kokkos dependency (i.e. the target_link_libraries(... Kokkos::kokkos) you don't get nvcc as your compiler for any of the other cpp src files. Which means you are just compiling with GCC. Since my suspicion is that this is a NVCC/GCC issue with target_precompile_headers, you are just sidestepping the issue without Kokkos in it.

**Comment by crtrott** [comment]
Yeah so if you take this example:
some_header.h
```
#include<iostream>
```
main.cpp
```
#include<some_header.h>

int main(int argc, char* argv[]) {
  std::cout << "Hello " << argc << std::endl;
  return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.17)
project(Test LANGUAGES CXX)

file(GLOB srcfiles
${PROJECT_SOURCE_DIR}/*.h
)
add_executable(TestExe main.cpp ${srcfiles})
target_include_directories(TestExe PUBLIC ${PROJECT_SOURCE_DIR})
target_precompile_headers(TestExe PUBLIC ${PROJECT_SOURCE_DIR}/some_header.h)
```

It also fails if you do CMAKE_CXX_COMPILER=nvcc_wrapper.

**Comment by crtrott** [comment]
So it turns out that the issue seems to be "-include" which nvcc_wrapper doesn't know about. Can you try and just adding this change to nvcc_wrapper:
```
index bc21349..e9d5c9e 100755
--- a/bin/nvcc_wrapper
+++ b/bin/nvcc_wrapper
@@ -194,7 +194,7 @@ do
     cuda_args="$cuda_args $1"
     ;;
   #Handle known nvcc args that have an argument
-  -rdc|-maxrregcount|--default-stream|-Xnvlink|--fmad|-cudart|--cudart)
+  -rdc|-maxrregcount|--default-stream|-Xnvlink|--fmad|-cudart|--cudart|-include)
     cuda_args="$cuda_args $1 $2"
     shift
     ;;
```

**Comment by crtrott** [comment]
If that works we will jsut add it to nvcc_wrapper.

**Comment by T-Captum** [comment]
Thanks a lot. This will save so much compile time :D. Works well with no issues so far.

**Comment by crtrott** [comment]
ok cool, will add a PR.
