### ISSUE TITLE
Shmem allocation through TeamPolicy constructor

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#350]
Hello Kokkos Team,

According to the programming guide section 8.3, the maximum amount of available shared memory per block "is provided either through a function in the functor...or it can be specified as an argument to the constructor of the TeamPolicy."  I'd like to use the latter approach, but I can't find any examples in the PG showing how the amount of shared memory can be specified in the TeamPolicy constructor.  Simply adding an additional argument to the constructor, like this:
```cpp
TeamPolicy<>(numTeams, numThreads, vectorLength, shmemSize) 
```
fails, saying "no instance of constructor...matches the argument list."  What is the appropriate syntax?  I apologize if this is actually in the PG and I overlooked it.

Thank you for your help,
Michael

**Comment by mndevec** [comment]
There is a small example in below slides. 
https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/Kokkos-Overview-v2.pdf


```c++
TeamPolicy<>(leagues, teams, vectors).set_scratch_size(MemoryLevel,Kokkos::PerTeam(team_shmem),Kokkos::PerThread(thread_shmem))
```

**Comment by dholladay00** [comment]
I have used the following syntax:

```c++
TeamPolicy<> policy(numTeams, numThreads, vectorLength);
parallel_<for, reduce, scan> (policy.set_scratch_size(level, Kokkos::PerTeam(perTeamSize), Kokkos::PerThread(perThreadSize)) ...);
```

**Comment by mcarilli** [comment]
Excellent, that works.  Thanks very much.

**Comment by crtrott** [comment]
Updates for the programming guide are high on my to-do list, but so far were thrown out by higher priority issues.
