### ISSUE TITLE
data()==NULL after realloc with LayoutStride

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#351]
When running this example code:
```
#include <Kokkos_Core.hpp>

#include <cassert>

enum { SpatialDim = 3 };
enum { NNodes0 = 10 };
enum { NNodes1 = 20 };

static Kokkos::LayoutStride make_layout(int nnodes) {
  const int dimensions[] = {nnodes, SpatialDim};
  const int order[] = {1,0};
  const int rank = 2;
  return Kokkos::LayoutStride::order_dimensions(rank,order,dimensions);
}

int main(int argc, char** argv) {
  Kokkos::initialize(argc, argv);
#ifdef USE_STRIDE
  typedef Kokkos::View<double*[SpatialDim], Kokkos::LayoutStride> view_type;
#else
  typedef Kokkos::View<double*[SpatialDim]> view_type;
#endif
  view_type view;
#ifdef USE_STRIDE
  auto layout = make_layout(NNodes0);
  view = view_type("coords", layout);
#else
  view = view_type("coords", NNodes0);
#endif
#ifdef GOOD_REALLOC
  Kokkos::realloc(view, NNodes1, SpatialDim);
#else
  Kokkos::realloc(view, NNodes1);
#endif
  assert(view.size() == NNodes1 * SpatialDim);
  assert(view.dimension_0() == NNodes1);
  assert(view.dimension_1() == SpatialDim);
  assert(view.data() != nullptr);
  Kokkos::finalize();
}
```
With `USE_STRIDE` and without `GOOD_REALLOC`, the assertion `view.data() != nullptr` fails. The history here is my View used to have compile-time layout and `realloc` worked fine given only one dimension. After switching to `LayoutStride` I got segfaults due to this.

Either this shouldn't happen and there is a bug somewhere, or it is expected in which case I would prefer that some part of Kokkos threw a compile or runtime error on this example, so that its easier to track down the problem.

**Comment by hcedwar** [comment]
resize with a layout stride view should only accept layout object, not integer dimensions

**Comment by ibaned** [comment]
`realloc` with a layout object argument fails to compile. what is the difference between `resize` and `realloc` ?

**Comment by hcedwar** [comment]
Resize and realloc were implemented to support the LayoutLeft and LayoutRight.  Those functions were not previously intended to support LayoutStride.  The fact that LayoutStride can be passed in at all is a bug.  A new overload of resize and realloc that accepts a LayoutStride object is needed.  Thus this issue is both a bug report and, I assume, a feature request.

**Comment by ibaned** [comment]
Yes, thats correct, although the bug fix is all I'd need to consider it resolved, i.e. this usage ought to cause a compile or runtime error at the `realloc` call.

**Comment by crtrott** [comment]
OK here is how this works with LayoutStride:
instead of:
```C++
#else
  Kokkos::realloc(view, NNodes1);
#endif
```
do
```C++
#else
  Kokkos::realloc(view, make_layout(NNodes1));
#endif
```

The other version will now also compile time fail if the layout is not LayoutRight or LayoutLeft. Unit tests are put in place.

**Comment by ibaned** [comment]
thanks very much !
