### ISSUE TITLE
MDRange silently not accepting negative indices

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3524]
Reported in Slack, currently if you use an MDRange that goes from {-4,-4} to {4,4} only the positive indices run. We need some to make the index type signed, or at least warn people

**Comment by DavidPoliakoff** [comment]
Note: if you're seeing this error, and we haven't fixed this in your Kokkos branch, you can work around it by adding `Index_type<int>` to your MDRangePolicy definition:

```c++
MDRangePolicy<Rank<2>,IndexType<int>>({-1,-1},{2,2});
```

**Comment by crtrott** [comment]
Note this only affects CUDA and maybe HIP as far as I can tell.

**Comment by DavidPoliakoff** [comment]
Thanks @dalg24 for taking this one on!

**Comment by dalg24** [comment]
> Note: if you're seeing this error, and we haven't fixed this in your Kokkos branch, you can work around it by adding `IndexType<int>` to your MDRangePolicy definition:
> 
> ```c++
> MDRangePolicy<Rank<2>,IndexType<int>>({-1,-1},{2,2});
> ```

This is not a workaround.  This this the right way to deal with negative indices.
