### ISSUE TITLE
Does Kokkos still support Pthread in a Trilinos build?

### ISSUE THREAD

**Issue by kuberry** [kokkos/kokkos#3555]
While configuring Trilinos lately using CMake options that worked several months ago, I got the following message:

-- Architectures:
CMake Error at packages/kokkos/cmake/kokkos_tpls.cmake:28 (MESSAGE):
  Enabled TPL PTHREAD inside TriBITS build, but this can only be enabled in a
  standalone build

Relevant CMAKE flags include: 

-D TPL_ENABLE_Pthread:BOOL=ON
-D Kokkos_ENABLE_PTHREAD:BOOL=ON
and
-D Tpetra_INST_PTHREAD:BOOL=ON

Does Kokkos no longer support Pthreads in Trilinos builds? The logic in kokkos_tpls.cmake seems to indicate it does not.

**Comment by kuberry** [comment]
In lines 37-59 of kokkos_tpls.cmake, some of the TPLs such as CUDA do have 
KOKKOS_TPL_OPTION(CUDA    ${Kokkos_ENABLE_CUDA} TRIBITS CUDA)

but PTHREAD does not:
KOKKOS_TPL_OPTION(PTHREAD ${PTHREAD_DEFAULT})

Should this be: 
KOKKOS_TPL_OPTION(PTHREAD ${PTHREAD_DEFAULT} TRIBITS Pthread)
?

**Comment by masterleinad** [comment]
Looks reasonable. Does your suggestion work for you? If so, would you mind opening a pull request for fixing it?

**Comment by kuberry** [comment]
That suggestion does work for me. I noticed that the CUDA line I mentioned does not contain "TRIBITS CUDA" in the Kokkos standalone repo, just in Trilinos, so it would make most sense to patch it (add TRIBITS Pthread) in Trilinos.

**Comment by masterleinad** [comment]
> I noticed that the CUDA line I mentioned does not contain "TRIBITS CUDA" in the Kokkos standalone repo

That's not true. :slightly_smiling_face: https://github.com/kokkos/kokkos/blob/14fd074bfafb374c8a3459d3130ce7a2937c961d/cmake/kokkos_tpls.cmake#L39
The correct branch to look at is `develop` not `master`, `master` reflects the last release. Also, there should be no pull requests to `Kokkos` in `Trilinos` that are not mirrored here.
