### ISSUE TITLE
Add support for Intel Cascade Lake CPU to Kokkos build system

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#3590]
Can we add support for Intel Cascade Lake to Kokkos build system, i.e. `Kokkos_ARCH`.

**Comment by nmhamster** [comment]
@stanmoore1 - there is no change to enable Cascade Lake Xeon over Sky Lake Xeon for the compiler flags, level of features etc. Have you had a different experience? Basically if you compile for `Kokkos_ARCH=SKX` you should get the best performance.

**Comment by stanmoore1** [comment]
Understood, but it would still be nice to add this to `Kokkos_ARCH` since everything else is there.

**Comment by nmhamster** [comment]
OK, just letting you know that SKX will give you everything you need.

**Comment by stanmoore1** [comment]
Can use `Kokkos_ARCH=SKX`, closing #3590.
