### ISSUE TITLE
CUDA 8 has 64bit __shfl

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#361]
The Kokkos::shfl overloads should use the CUDA 8 intrinsic __shfl for 64bit types as well as 32bit types.  Will have to be protected with compiler version detection.
This is an undocumented feature,, wait for CUDA 8.5.

**Comment by hcedwar** [comment]
CUDA 8.5 never happened.  Perhaps CUDA 9

**Comment by srajama1** [comment]
Checking the status on this.

**Comment by ibaned** [comment]
It looks like CUDA 9's `__shfl_sync` and friends support `long long`. Working on adding this to Kokkos.
