### ISSUE TITLE
Running older SM kernels on newer archs results in Kokkos::abort

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#3612]
I know you're targeting specially compiled HPC platforms, but for consumer-harware cases the following restrictions are wrong, `Kokkos_Cuda_Instance.cpp, lines 368 to 377`:
```
    if (compiled_major != cudaProp.major || compiled_minor > cudaProp.minor) {
      std::stringstream ss;
      ss << "Kokkos::Cuda::initialize ERROR: running kernels compiled for "
            "compute capability "
         << compiled_major << "." << compiled_minor
         << " on device with compute capability " << cudaProp.major << "."
         << cudaProp.minor << " is not supported by CUDA!" << std::endl;
      std::string msg = ss.str();
      Kokkos::abort(msg.c_str());
    }
```

This should be warning at best, not `abort` if older kernels run on newer devices...
I assume the following test
https://github.com/kokkos/kokkos/blob/03ded4e816da5927b946065b005ebfdf38e5a438/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L368
for the abort case should be written as:
`
if ((compiled_major > cudaProp.major) || (compiled_major == cudaProp.major && compiled_minor > cudaProp.minor)) {
`

**Comment by crtrott** [comment]
No: according to CUDA you are not guaranteed that if you compile for example for 6.5 that it works on 6.0. We actually had runtime failures of code with running Kepler 37 on Kepler 35. From the CUDA Programming Guide:
```
In other words, a cubin object generated for compute capability X.y will only execute on devices of compute capability X.z where z≥y. 
```
https://docs.nvidia.com/cuda/cuda-c-programming-guide/#binary-compatibility

**Comment by j8asic** [comment]
This is also what I'm saying. And I'm trying to say the L368 "if" condition for this is buggy.

**Comment by dalg24** [comment]
@j8asic I am reading the documentation like Christian
```C++
// Binary compatibility is guaranteed from one minor revision to the next one
if (compiled_major != cudaProp.major // but not across major revisions
  || compiled_minor > cudaProp.minor) // nor from one minor revision to the previous one
```

The condition you suggest would allow binary code compiled for 3.5 to run on 6.0 which is not guaranteed to work according to the documentation.

**Comment by j8asic** [comment]
For the sake of discussion let's also add that Clang includes PTX and allows forward compability. Again, I suggest that abort case stays with the new proposed condition, but the current condition should yield a warning. One should argue: why the driver immediately does not abort if it is given older SM ptx? IMHO a library should not append restrictions stronger than its dependencies, and "not guaranteed" is a warning-material term.

**Comment by j8asic** [comment]
Sorry to bump this @dalg24 and @crtrott, but it does not make sense for you to append constraints that CUDA is not requiring.

This constraint blocks PTX compatibility.

**Comment by j8asic** [comment]
This constraint for cubin on PTX is blocking deployment of generalized software, and it is contradictory to "performance portable" definition.  At least when compiling with Clang. 

Proof from https://llvm.org/docs/CompileCudaWithLLVM.html :

> However, clang always includes PTX in its binaries, so e.g. a binary compiled with --cuda-gpu-arch=sm_30 would be forwards-compatible with e.g. sm_35 GPUs.

Therefore, according to the detection given in https://llvm.org/docs/CompileCudaWithLLVM.html#detecting-clang-vs-nvcc-from-code the "if" condition should be changed like in the primary post:

```
#if defined(__clang__) && defined(__CUDA__)
    // clang compiling CUDA code, allows forwards compatibility
    if ((compiled_major > cudaProp.major) ||
        (compiled_major == cudaProp.major && compiled_minor > cudaProp.minor)) {
#else
    if (compiled_major != cudaProp.major || compiled_minor > cudaProp.minor) {
#endif
```

Added this in the PR #5187
