### ISSUE TITLE
Update Qthreads back-end to revised interface

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#366]
Data parallel interface for revised parallel_reduce.
TaskPolicy interface, experimental and production

**Comment by hcedwar** [comment]
Data parallel is in develop branch: #364

**Comment by hcedwar** [comment]
Will need to enable nightly testing with baseline Qthreads.

**Comment by hcedwar** [comment]
This is an epic which needs smaller, incremental progress, issues.

**Comment by crtrott** [comment]
This is waiting for the rework of the threads backend infrastructure in Kokkos.
