### ISSUE TITLE
Kokkos Virtual Functions and Factory Patterns

### ISSUE THREAD

**Issue by ejm930** [kokkos/kokkos#3672]
Hi, I'm still a bit new to using Kokkos and C++ software design in general. I'm primarily using Kokkos in conjunction with Cabana and making use of AoSoAs for my code. I was reading through the wiki and I found that virtual functions don't play so nicely with GPU kernels. I'm considering making use of a factory method creational pattern for instantiating my simulations. So, am I free and clear to use virtual functions for methods like run() and init() so long as my derived classes doesn't use virtual functions inside the parallel dispatch section of my functor? Essentially, something like below: 

`virtual void compute() {
    parallel_for("Compute1", RangePolicy<TagPhase1>(0,N), *this);
    parallel_for("Compute2", RangePolicy<TagPhase2>(0,N), *this);
  }`
  
  The overloaded operator wouldn't contain any virtual functions, but would be wrapped inside something virtual.

**Comment by dalg24** [comment]
As long as your `operator()(Tag, Index)` are not virtual and do not call any virtual functions, I expect it should work.

**Comment by crtrott** [comment]
Yeah that should be fine. At the place of the instantation of the parallel_for all types are none and so you are good.

**Comment by ejm930** [comment]
Great, thanks for clearing that up. If for some reason something unusual happens I’ll open another issue.
