### ISSUE TITLE
Performance regression in DualView

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#3693]
I'm seeing a significant performance regression in `Kokkos::DualView` with LAMMPS due to a bunch of new `DtoH` data movement. I bisected the issue to #3326, and @crtrott found the label is being pulled down for every DualView `sync` and `modify` event. Can the label only be pulled down from GPU to CPU when profiling is enabled?

**Comment by crtrott** [comment]
We are trying to get a fix done today.

**Comment by stanmoore1** [comment]
Great, thanks!

**Comment by DavidPoliakoff** [comment]
@stanmoore1 , yikes, sorry about that. Just pushed #3695, we're pushing to merge it into everything, starting with the release

**Comment by stanmoore1** [comment]
I confirm that #3701 fixes the `DtoH` data movement issue, thanks!

**Comment by stanmoore1** [comment]
Now fixed, closing #3693.
