### ISSUE TITLE
Discrepancy in TeamThreadRange implementation between backends 

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#3702]
@crtrott 
The Cuda and HIP backend define the following overload: 
`TeamThreadRange(const Impl::HIPTeamMember& thread, iType1 begin, iType2 end)`
see `Kokkos_Cuda_Team.hpp:632` and `Kokkos_HIP_Team.hpp:615` while for the OpenMPTarget backend only:
`TeamThreadRange(const Impl::OpenMPTargetExecTeamMember& thread, iType begin, iType end)`
is defined see `Kokkos_OpenMPTarget_Parallel.hpp`.

This leads to some compiling errors when one does something like:
`TeamThreadRange(thread, 0, myEnd)`
since the compiler does not always assign the same type to `0` and `myEnd`.

I am fixing Kokkos Kernels so that we do not use the two types overload but it would be nice to have this consistent across backends.

**Comment by masterleinad** [comment]
Fixed by #3703.
