### ISSUE TITLE
Update Kokkos::Threads documentation (wake() no longer exists)

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#3709]
The Doxygen documentation of `Kokkos::Threads` mentions a ` wake` method:

https://github.com/kokkos/kokkos/blob/78538c8574777342f64c7da657f419778eaa2a10/core/src/Kokkos_Threads.hpp#L130

It looks like this no longer exists.  Would it be appropriate to update the Doxygen documentation accordingly?

**Comment by crtrott** [comment]
Technically we don't support Doxygen at all but yeah this should be removed.

**Comment by ajpowelsnl** [comment]
The relevant part of the comment in this file was deleted, and submitted for review in PR#4580.

**Comment by mhoemmen** [comment]
Thanks y'all! : - )

**Comment by mhoemmen** [comment]
Oops, I probably shouldn't have closed this; it's up to y'all.  Anyway, thanks for fixing this!
