### ISSUE TITLE
Trouble building tutorial example with Cuda

### ISSUE THREAD

**Issue by ralberd** [kokkos/kokkos#3728]
Hello,

I am trying to build the kokkos-tutorials examples on a GPU (Nvidia Quadro GV100), but am getting an error when I run the make command:

make -j KOKKOS_DEVICES=Cuda

It looks like it is not recognizing the nvcc compiler. A screenshot of the error message is attached.

Any idea what I'm doing wrong?

<img width="1257" alt="kokkos_cuda_build_error" src="https://user-images.githubusercontent.com/59070519/104667048-75699600-5692-11eb-8f2a-dd0f8be00daa.png">

**Comment by masterleinad** [comment]
How are you specifying your compiler? At the moment it still needs to be `nvcc_wrapper` or `clang++` like the error message says.

**Comment by dalg24** [comment]
Closing because inactive for a while.  Feel free to re-open if this is still an issue
