### ISSUE TITLE
Output order of test_atomic.cpp is confusing

### ISSUE THREAD

**Issue by ArchRobison** [kokkos/kokkos#373]
[This line](https://github.com/kokkos/kokkos/blob/9afaa87fa37f4bc90913d7b31a3c168883ceda55/core/perf_test/test_atomic.cpp#L434) of `test_atomic.cpp` seems to print results in one order, but times in a different order, which is confusing.  Would printing times in the same order as the results break anything?  I'm happy to contribute the trivial PR to fix this.

**Comment by hcedwar** [comment]
please do issue pull request
