### ISSUE TITLE
Kokkos compiler detection does not work for intel's icpx

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#3734]
The logic implemented in `cmake/kokkos_corner_cases.cmake` does not detect the intel compiler properly when the OpenMP backend is on. The issue mainly resides in the `CLANG_HAS_OMP` test.
Furthermore bypassing that test leads to problem at link time since Kokkos does not set `KOKKOS_CLANG_IS_INTEL` which results in `-fopenmp=libomp` being added to the compiler (and linker?) flags.

The problem should be easily fixed by parsing `icpx --version` to detect it correctly as a clang intel compiler.

**Comment by dalg24** [comment]
Pasting this for reference
https://github.com/kokkos/kokkos/blob/9d090c5e604cf2873c4add9fb0ac5d60c4fe4396/cmake/kokkos_corner_cases.cmake#L1-L23

Are you saying there is a defect in
https://github.com/kokkos/kokkos/blob/03ded4e816da5927b946065b005ebfdf38e5a438/cmake/kokkos_compiler_id.cmake#L66-L75
or are we just missing a `AND NOT KOKKOS_CLANG_IS_INTEL` in the code you referred to?

**Comment by lucbv** [comment]
I was using an outdated version, the current fix in develop (PR 3660) works just fine. Feel free to close this issue, sorry for the inconvenience
