### ISSUE TITLE
Negative start values in RangePolicy do not work with sequential Kokkos device?

### ISSUE THREAD

**Issue by BarrySmith** [kokkos/kokkos#3745]
Kokkos examples on-line have RangePolicy that start with a negative value.  But the example below running on the sequential Kokkos device does not appear to work when it starts with a negative value. The parallel_for() seems to be "skipped".

Am I misunderstanding something?

```
#include <Kokkos_Core.hpp>
#include <Kokkos_OffsetView.hpp>
#include <stdio.h>

int main(int argc,char **argv)
{
  Kokkos::InitArguments args;
  args.device_id  = -1;
  Kokkos::initialize(args);
 Kokkos::Experimental::OffsetView<double*, Kokkos::DefaultExecutionSpace::memory_space> X{"Label",{-2,2}};

 X(-2) = -2; X(-1) = -1; X(0) = 0; X(1) = 1;

 Kokkos::parallel_for(Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>(-1,2), KOKKOS_LAMBDA (const int &i)
    {
      printf("Inside kernel %d\n",i);
      X(i) = i+10;
    });
 printf("%g\n",X(-2));
 printf("%g\n",X(1));        
 return 0;
}
```

The parallel_for is never entered.
```
$ ./simpletest      
-2
1
```
  But change the Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>(-1,2), to Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>(0,2),

and the parallel _for is run
```
$ ./simpletest
Inside kernel 0
Inside kernel 1
-2
11
```

**Comment by BarrySmith** [comment]
Additional notes:

If I use Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>({-1},{2}), 

I get the very nice warning 

```
error: constant expression evaluates to -1 which cannot be narrowed to type
      'Kokkos::RangePolicy<Kokkos::Serial>::member_type' (aka 'unsigned long') [-Wc++11-narrowing]
```

I changed to Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace,int>(-1,2),  and it worked correctly.

It would be nice if this form also gave a nice error message and why is the default for Serial unsigned long ? 

Online documentation indicates the default is int64_t

**Comment by dalg24** [comment]
Hi Barry,
I think you found a bug in the documentation. The index type defaults to the execution space `size_type` which is `size_t` for `Serial`.
https://github.com/kokkos/kokkos/blob/f8fd210db4c10a3807676c5529f8b6945839ed75/core/src/impl/Kokkos_AnalyzePolicy.hpp#L280-L283
You can resolve it by using `Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace, Kokkos::IndexType<int>>`.

**Comment by janciesko** [comment]
Good catch. We should update the wiki to something like this:
| IndexType | `IndexType<T>` | Specify type to be used for traversing the iteration space. Defaults to the default type of the execution space. |
To the question, why it is a size_t and not a something else, because it is defined as such. Setting this to long long int would make your original code work. https://github.com/kokkos/kokkos/blob/f8fd210db4c10a3807676c5529f8b6945839ed75/core/src/Kokkos_HostSpace.hpp#L107

**Comment by janciesko** [comment]
@BarrySmith, I have updated the wiki. Thanks again for pointing this out. Supporting signed default types for RangePolicy is on our radar and subject to one of the upcoming Kokkos releases. If this resolved your issue for, please feel free to close.
