### ISSUE TITLE
KOKKOS_ARCH for Ampere 

### ISSUE THREAD

**Issue by DCaviedesV** [kokkos/kokkos#3750]
I noticed that the guidelines to set KOKKOS_ARCH at https://github.com/kokkos/kokkos/wiki/Compiling#table-43-architecture-variables does not show Nvidia Ampere architectures. I did, boldly set KOKKOS_ARCH = "Ampere80", which seems to have done the magic (I can see nvcc compiling for sm_80), and actually executed my code on an A100. 
Just wanted to ask if there is any reason that Ampere is not actually listed on the table (perhaps this is still experimental?). This could be easier to ask through Slack, but I have realised I require an invite from the workspace admin (who?).

**Comment by stanmoore1** [comment]
Yes `Ampere80` is supported, see:
https://github.com/kokkos/kokkos/blob/master/Makefile.kokkos#L13
https://github.com/kokkos/kokkos/blob/master/cmake/kokkos_arch.cmake#L62

Looks like the wiki needs to be updated.

**Comment by masterleinad** [comment]
I updated the Wiki.

**Comment by dalg24** [comment]
@DCaviedesV Please send an email to Christian (https://github.com/kokkos/kokkos/blob/1fb0c284d458c75370094921d9f202c287502325/core/src/Kokkos_Core.hpp#L39) about getting invited to Slack.
