### ISSUE TITLE
Is it possible to encapsulate a ScatterView within a functor?

### ISSUE THREAD

**Issue by XzzX** [kokkos/kokkos#3756]
Minimal example:
```
struct Func
{
    Func( view var_ )
    {
        var = var_;
        s_var = ScatterView(var);
    }

    ~Func()
    {
        contribute(var, s_var);
        //s_var.reset();
    }

    KOKKOS_INLINE_FUNCTION
    void operator()(const int idx) const
    {
        ...
    }

    view var;
    ScatterView s_var;
};
```
Observation: The accumulated results are too large. (OpenMP case)

I am guessing you duplicate the functor for every thread and `contribute` gets called more than once. Uncommenting the reset seemingly resolves the problem, however, I do not think this is the right solution. What is the correct way to handle a ScatterView inside of a functor?

**Comment by masterleinad** [comment]
Take a look at https://github.com/kokkos/kokkos/blob/master/containers/unit_tests/TestScatterView.hpp. In particular, `contribute` is called after the `parallel_for`.

**Comment by XzzX** [comment]
Thanks for the pointer. So, I cannot encapsulate the creation and contribution of a `ScatterView` in a functor (RAII like). If I want to do that I have to encapsulate the `ScatterView` and the `parallel_for` call in a function, right?

**Comment by masterleinad** [comment]
Yes, `contribute` is not a device function. You need to call it outside the parallel region.

**Comment by XzzX** [comment]
Ok, I understand. For thread local copies of the functor the destructor will be called within the parallel region. Thank you for the clarification. I will refactor my code.
