### ISSUE TITLE
Make GPU Auto-Detection Work With Kokkos Launch Compiler

### ISSUE THREAD

**Issue by lkersting** [kokkos/kokkos#3758]
The auto-detection of the NVIDIA GPU architecture currently only works when `CMAKE_CXX_COMPILER=nvcc_wrapper`.
Auto-detection would also be useful when compiling with gcc and the kokkos_launch_compiler instead of using nvcc_wrapper directly.

Is there a way to have the kokkos_lauch_compiler substitute nvcc_wrapper when CMake performs the `TRY_RUN` of cuda_compute_capability.cc (kokkos_arch.cmake line 474-480)?

**Comment by jrmadsen** [comment]
I ran a quick test to verify that it wasn’t a quick fix and, indeed, the `RULE_LAUNCH_COMPILE` is ignored during `try_run(...)`. There is no way to specify "use this compiler instead” so it looks like the options are (tentatively): 

- `enable_language(CUDA)` + compile/run a `compute_capability.cu` file
  - this should work just fine but may confuse some users who see the cuda compiler being enabled but never see it actually being used to build things
- use `ExternalProject_Add(...)` + execute_process
  - i'd like to avoid this but may be necessary if we can't go the enabling the cuda language route

**Comment by masterleinad** [comment]
Fixed in #3770.
