### ISSUE TITLE
Bump minimum supported CUDA compute capability to >=3.5

### ISSUE THREAD

**Issue by psanan** [kokkos/kokkos#3761]
I happened to be compiling on an ancient Quadro K600 (`KEPLER30`) GPU and couldn't build because `atomicMin()` and similar functions used in `core/src/impl/Kokkos_Atomic_MinMax.hpp` [aren't supported for 64-bit (`long long`) ints until compute capability 3.5.
](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicmin)

This should allow removal of the `KEPLER30` and `KEPLER32` architectures in the build system.

Also note that the tutorial slides here could be updated (and if I recall correctly, the video also says something about 3.0, but that'd be harder to change).
https://github.com/kokkos/kokkos-tutorials/blob/main/LectureSeries/KokkosTutorial_01_Introduction.pdf

**Comment by dalg24** [comment]
See #3780

**Comment by psanan** [comment]
Builds for me! Thanks a lot - this is obviously even better than dropping support for that compute capability.
