### ISSUE TITLE
Typos in wiki for API-Reference of parallel_for and parallel_reduce

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#3773]
https://github.com/PhilMiller/kokkos-wiki/compare/typos
Looks like some stuff was copied and pasted from lambda-using examples to functor examples, and some tag types were changed inconsistently

**Comment by masterleinad** [comment]
Just open a pull request. :slightly_smiling_face:

**Comment by PhilMiller** [comment]
It's in the wiki, not the main repo. Github seems not to facilitate that.
E.g. https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by masterleinad** [comment]
Fixed.
