### ISSUE TITLE
Intel compiler rejects explicit default move ctor

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#379]
I'm using the Intel C++ compiler version 17 to compile Kokkos for KNL, and get errors like:
```
.../packages/kokkos/core/src/Kokkos_TaskPolicy.hpp(323): error: invalid type for defaulted constructor
    TaskPolicy( TaskPolicy && rhs ) = default ;                                    
    ^
```
The same thing happens with version 16. I am just wondering if Kokkos developers have experience with Intel compilers and how to get around this, if possible. Any advice is appreciated !

The verbose compile command for this file was:
```
/opt/intel/compiler/2017.beta.intel/bin/icpc   -Dkokkoscore_EXPORTS -I/home/Xdibane/build/Trilinos -I/home/Xdibane/build/Trilinos/packages/kokkos/core/src -I/home/Xdibane/src/Trilinos/packages/kokkos/core/src  -O2 -g -fopenmp -std=c++11 -fPIC   -o CMakeFiles/kokkoscore.dir/impl/Kokkos_Serial_TaskPolicy.cpp.o -c /home/Xdibane/src/Trilinos/packages/kokkos/core/src/impl/Kokkos_Serial_TaskPolicy.cpp
```

**Comment by ambrad** [comment]
@ibaned, what is the output of
    $ icpc -v
In particular, what is the gcc compatibility? I suspect it might be < 4.7.2. If so, that is likely the cause of the problem you're having. Solve it by
    $ module purge
    $ module load intel/17.0 gcc/4.9.2
or something like that.

**Comment by ibaned** [comment]
Thanks @ambrad, I get:
```
icpc version 17.0.0 Beta (gcc version 4.4.7 compatibility)
```
This cluster is not managed by `module`, but gcc 5.3.0 was in my PATH. The cluster is also inaccessible at the moment, but I'll coordinate with their tech support now that I have a better idea what the issue is.

In terms of this Github issue, I was assuming that the Intel compiler had a fundamental limitation, but it seems this is just down to the configuration of this compiler, so I will close it for lack of relevance to Kokkos itself.

**Comment by nsccap** [comment]
Adding a concrete solution to this for the benefit of future people stumbling on this issue:

Add "-gxx-name=/path/to/local/g++" to CCFLAGS in MAKE/OPTIONS/Makefile.kokkos_omp
when compiling on a platform with old system g++ and new intel icpc.
