### ISSUE TITLE
Links to pull request in CHANGELOG.md are broken

### ISSUE THREAD

**Issue by arkantos493** [kokkos/kokkos#3794]
Links to specific pull requests in the current CHANGELOG.md are broken.

For example from the CHANGELOG entry 3.3.00:
```
- Added parallel_scan support with TeamThreadRange [\#3536](https://github.com/kokkos/kokkos/pull/#3536)
```
the generated link to the pull request [\#3536](https://github.com/kokkos/kokkos/pull/#3536) results in a 404 error.

However,  removing the ```#``` from the link fixes this issue: [\#3536](https://github.com/kokkos/kokkos/pull/3536).

(I could change the broken links if desired.)

**Comment by dalg24** [comment]
Sure we would accept such a pull request.  Thank you

**Comment by arkantos493** [comment]
See pull request [#3795](https://github.com/kokkos/kokkos/pull/3795).
