### ISSUE TITLE
arithmetic overflow potential

### ISSUE THREAD

**Issue by tonkapango** [kokkos/kokkos#3805]
In the file (./src/Cuda/Kokkos_Cuda_Instance.cpp) at line 567 of CudaInternal::scratch_flags function, there exists a integer overflow potential with size added to sizeScratchGrain

```
Cuda::size_type*CudaInternal::scratch_flags(const Cuda::size_type size) const {
  if (verify_is_initialized("scratch_flags") &&  
      m_scratchFlagsCount * sizeScratchGrain < size) {
          m_scratchFlagsCount = (size + sizeScratchGrain - 1) / sizeScratchGrain;

```

the check m_scratchFlagsCount * sizeScratchGrain less than size seems odd, given that m_scratchFlagsCount is set with new value.  but it would seem we could check for overflow by:

```
(size + sizeScratchGrain  - 1 ) > sizeScratchGrain // Not OF
```

**Comment by cz4rs** [comment]
Closing after #6159 and #6313 were merged.
