### ISSUE TITLE
Kokkos::subview(DualView) returns a broken DualView

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#3806]
``Kokkos::subview(dv, range1, range2)`` where dv is a DualView and range1 x range2 is noncontiguous wrt. dv's strides returns another DualView of the same layout, but the same strides as dv. These strides can't be compatible with the subview's extents and its type which says it's contiguous. I see 2 correct ways to handle this:

- Just error out. It's not possible to deep_copy a LayoutStride view across spaces, so it wouldn't be possible to (directly) sync a LayoutStride DualView anyway.
- (preferred) Return the correct LayoutStride DualView, and have the subview's sync recursively sync the parents. It already shares the ``modified_flags`` view with its parent, which sort of implies this should be happening already. If the top-level parent is noncontiguous (and can't be sync'd) then throw or just prevent a top-level noncontiguous DualView from being constructed in the first place.

This complete reproducer (for a build with Cuda enabled) makes a 10x10 LayoutLeft dualview, then takes a 5x5 subview. The subview is still LayoutLeft (prints the mangled type), but given that, the extents and strides are not compatible. Syncing it throws an exception "no available copy mechanism".

As a side note, subview(DualView) is able to construct the LayoutLeft d_view/h_view with the impossible stride, so there may be a missing sanity check for extents vs. strides in contiguous View constructors.
```
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
#include <typeinfo>

using ExecSpace = Kokkos::Cuda;
using MemSpace = Kokkos::CudaSpace;
using DeviceType = Kokkos::Device<ExecSpace, MemSpace>;

using DualViewType = Kokkos::DualView<float**, Kokkos::LayoutLeft, DeviceType>;

int main()
{
  Kokkos::initialize();
  {
    //Create a normal, contiguous DualView
    DualViewType contig("ContiguousLayoutLeft", 10, 10);
    //Grab the device side view and verify type - should be LayoutLeft
    auto contigDevice = contig.d_view;
    std::cout << "Device-side view type: " << typeid(contigDevice).name() << '\n';
    std::cout << "Contiguous view extents and strides: ";
    std::cout << contigDevice.extent(0) << 'x' << contigDevice.extent(1) << ", " << contigDevice.stride(0) << 'x' << contigDevice.stride(1) << '\n';
    //Create a noncontiguous subview. Should NOT be LayoutLeft,
    //since 5 = extent(0) != stride(1) = 10
    auto sub = Kokkos::subview(contig, Kokkos::make_pair(0, 5), Kokkos::make_pair(0, 5));
    std::cout << "Noncontiguous dual-view type: " << typeid(sub).name() << '\n';
    auto subDevice = sub.d_view;
    std::cout << "Noncontiguous device view type: " << typeid(subDevice).name() << '\n';
    std::cout << "Noncontiguous extents, strides: ";
    std::cout << subDevice.extent(0) << 'x' << subDevice.extent(1) << ", " << subDevice.stride(0) << 'x' << subDevice.stride(1) << '\n';
    std::cout << "Attempting to sync from host->device.\n";
    auto subHost = sub.h_view;
    subHost(1, 2) = 3.14f;
    sub.modify_host();
    std::cout << "Syncing noncontiguous from host to device.\n";
    sub.sync_device();
    std::cout << "Done.\n";
  }
  Kokkos::finalize();
  return 0;
}
```

Output:
```
Device-side view type: N6Kokkos4ViewIPPfJNS_10LayoutLeftENS_6DeviceINS_4CudaENS_9CudaSpaceEEEvEEE
Contiguous view extents and strides: 10x10, 1x10
Noncontiguous dual-view type: N6Kokkos8DualViewIPPfNS_10LayoutLeftENS_6DeviceINS_4CudaENS_9CudaSpaceEEENS_12MemoryTraitsILj0EEEEE
Noncontiguous device view type: N6Kokkos4ViewIPPfJNS_10LayoutLeftENS_6DeviceINS_4CudaENS_9CudaSpaceEEENS_12MemoryTraitsILj0EEEEEE
Noncontiguous extents, strides: 5x5, 1x10
Attempting to sync from host->device.
Syncing noncontiguous from host to device.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Kokkos::deep_copy with no available copy mechanism: ContiguousLayoutLeft_mirror to ContiguousLayoutLeft
Traceback functionality not available

Aborted (core dumped)
```

**Comment by kddevin** [comment]
@crtrott Any update on this issue?  It is needed for RequiredUVM removal in Trilinos.  Thanks!

**Comment by brian-kelley** [comment]
@kddevin After some discussion on slack, the way this will probably be resolved is:

- DualView::sync will just throw if ``this`` is a subviews (fine for us, since MultiVector keeps ``owningView_``)
- When Tpetra needs to do MPI with a noncontiguous view, we should be checking ``view.span_is_contiguous()`` at runtime rather than checking ``Layout != LayoutStride`` at compile time. Then there should be no more errors about deep_copy not being available. This would go in tpetra's temporaryViewUtils.hpp.

**Comment by Char-Aznable** [comment]
I also ran into similar problem. To me, this seems to show that Kokkos APIs related to deep_copy of view is broken, e.g. create_mirror_view_and_copy, when copying noncontiguous views across memory space. It basically forces all applications to do view contiguity check and work around deep_copy in a backend-dependent way: on host one do a the deep_copy anyway because it's a no op but on CUDA, the user has to be smart about what to expect from deep_copy. I understand that there's no easy way to do deep_copy of noncontiguous views across memory space but the all the users have to deal with this in probably the same way I can see: make a contiguous copy in the source space and then deep_copy from there, which then begs the question why Kokkos doesn't handle this internally?

**Comment by mhoemmen** [comment]
I recall talking with the Tpetra developers about this issue a couple years ago.  Everybody loves stashing away DualViews everywhere instead of carefully limiting their data access regions, alas.

**Comment by Char-Aznable** [comment]
@mhoemmen I don't think this problem is necessarily pertaining to only DualView but it comes up when you have a subview on the device and have to sync it to the host.

**Comment by brian-kelley** [comment]
@Char-Aznable I think it's actually reasonable that you can't deep-copy plain old Views when they're non-contiguous and not mutually accessible. It would hide from the user the fact that potentially hundreds of individual transfers are happening with a lot of overhead. DualView is a little different though, since a subview shares modify flags with its parent. Syncing a sub-DualView could be done by syncing the parent. Or if some more internal tracking was added, it could sync just the portions of the span that were actually changed.

However, at this point Tpetra (probably the main or only user of DualView subviews) is already doing something like this. So there's less demand to add that complexity to DualView.

**Comment by stanmoore1** [comment]
The SPARTA code also uses DualView subviews: https://github.com/sparta/sparta/blob/master/src/KOKKOS/update_kokkos.cpp#L294

**Comment by Char-Aznable** [comment]
@brian-kelley I understand the overhead associated with the syncing noncontiguous subview. However, the user should have to option to tolerate that. There are practical need to do such thing like many of us here and a couple other issues already posted. Talking about computational performance without the context or understanding where the bottleneck really is doesn't seems to me to be an argument for breaking an API.

**Comment by mhoemmen** [comment]
@Char-Aznable wrote:
> I don't think this problem is necessarily pertaining to only DualView but it comes up when you have a subview on the device and have to sync it to the host.

I think `deep_copy` and `DualView` are too low level of an interface for the problem that developers need to solve.  The problem that developers actually need to solve (not just think they need to solve) is to access

* a subset of the data;
* with a particular data layout;
* in a particular execution space;
* in a particular well-defined scope (e.g., during a kernel).

`DualView` is too low-level of an abstraction for that.

1. It hard-codes the existence of two allocations, thus preventing optimizations like allocation on demand.
2. It hard-codes the memory spaces on both sides, thus preventing features like spilling over to a slower but larger memory space as needed.
3. It hard-codes the layout, thus preventing features like automatic data reordering if needed.
4. It hard-codes shared ownership, thus breaking device-host sync'ing for subviews. 

It's not Kokkos' fault that DualView is too low level of an abstraction.  The fault is with users, who failed to build the abstractions that they needed.

**Comment by mhoemmen** [comment]
Users keep asking DualView to solve all their problems.  "Can DualView allocate lazily?"  "Can DualView change layouts?"  These are the wrong questions.  The right question is "What would an interface that can solve these problems look like?"

**Comment by mhoemmen** [comment]
It was pretty funny to see that something I added to Tpetra a while back, that might have been a start for solving these kinds of problems, was deleted.  I was hoping it would get replaced with something better.

**Comment by Char-Aznable** [comment]
@mhoemmen I appreciate what you said about "actually solving the problem with the right abstraction". But those are implementation details tangent to practical usage of the API. Layout and contiguity of the data isn't always the priority of consideration when solving actual problem. Content of the data and logic of organizing the code are far more important in most cases. Back to the topic, there are pretty straightforward way to deep_copy of noncontiguous data across memory space given some option to tolerate the overhead.

**Comment by mhoemmen** [comment]
> ...there are pretty straightforward way to `deep_copy` of noncontiguous data across memory space given some option to tolerate the overhead.

I don't disagree. 

> Back to the topic, ....

The original question started: "`Kokkos::subview(dv, range1, range2)` where `dv` is a `DualView` and `range1 x range2` is noncontiguous wrt. `dv`'s strides...."  People taking subviews of a `DualView` is a code smell.  Anyway, have fun y'all : - ) .
