### ISSUE TITLE
nvcc_wrapper and c++17

### ISSUE THREAD

**Issue by guangyechen** [kokkos/kokkos#3807]
I got an error message when compile Kokkos with c++17 standard:

build-power8]$ module list
Currently Loaded Modulefiles:
  1) gcc/7.4.0                 2) openmpi/4.0.2-gcc_7.4.0   3) cuda/11.0                 4) cmake/3.17.0

build-power8]$ cmake       -D CMAKE_BUILD_TYPE="Release"       -D CMAKE_CXX_COMPILER=$KOKKOS_SRC_DIR/bin/nvcc_wrapper       -D CMAKE_INSTALL_PREFIX=$KOKKOS_INSTALL_DIR       -D Kokkos_ENABLE_SERIAL=ON       -D Kokkos_ENABLE_OPENMP=ON       -D Kokkos_ENABLE_CUDA=ON       -D Kokkos_ENABLE_CUDA_LAMBDA=ON       -D Kokkos_ARCH_PASCAL60=ON -D Kokkos_ARCH_POWER8=ON -D Kokkos_CXX_STANDARD=17 .. ;
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /home/gchen/tools/kokkos/latest/kokkos-3.3.01//bin/nvcc_wrapper
-- Check for working CXX compiler: /home/gchen/tools/kokkos/latest/kokkos-3.3.01//bin/nvcc_wrapper - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Compiler Version: 11.0.194
-- Using -std=c++1z for C++17 standard as feature
CMake Error at cmake/kokkos_test_cxx_std.cmake:34 (MESSAGE):
  CMake wants to use -std=c++1z which is not supported by NVCC.**  Using a more
  recent host compiler or a more recent CMake version might help.
Call Stack (most recent call first):
  cmake/kokkos_test_cxx_std.cmake:76 (kokkos_set_cxx_standard_feature)
  cmake/kokkos_tribits.cmake:216 (INCLUDE)
  CMakeLists.txt:168 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

Any advice? Thanks.

**Comment by jrmadsen** [comment]
Have you tried using a newer host compiler, e.g. GCC 8? Also, you no longer have to do this: ` -DCMAKE_CXX_COMPILER=$KOKKOS_SRC_DIR/bin/nvcc_wrapper`, kokkos will handle forwarding to `nvcc_wrapper` when `-DKokkos_ENABLE_CUDA=ON`.

**Comment by guangyechen** [comment]
I just tried gcc/8.3.0 and it worked! Thanks!
