### ISSUE TITLE
Warnings in DynRankView

### ISSUE THREAD

**Issue by rppawlo** [kokkos/kokkos#381]
Getting lots of compiler warnings from the following line in DynRankView. Will submit a pull request soon.

```
/home/rppawlo/Trilinos/packages/kokkos/containers/src/Kokkos_DynRankView.hpp:229:22: 
warning: comparison between signed and unsigned integer expressions 
[-Wsign-compare]
      if ( drv.rank() > N )
                      ^
```

**Comment by rppawlo** [comment]
The pull request to fix this was accepted into kokkos development branch, but it is generating nightly test failures for the "warnings as errors" trilinos testing. Since the snapshot will overwrite this, would it be ok for me to apply this change to trilinos as well to get the tests passing again? When is the next merge from kokkos into Trilinos going to happen? If it is soon, then I can just wait.

**Comment by hcedwar** [comment]
Go ahead and apply to Trilinos - will be overwritten by the next snapshot.  Next snapshot has not been scheduled.
