### ISSUE TITLE
error when compiled using gcc-aarch64-none-elf

### ISSUE THREAD

**Issue by noisystreet** [kokkos/kokkos#3816]
error message:  
core/src/impl/Kokkos_HostBarrier.cpp:75:7: error: 'nanosleep' was not declared in this scope
core/src/impl/Kokkos_HostBarrier.cpp:77:7: error: 'sched_yield' was not declared in this scope
though time.h and sched.h are included.

**Comment by crtrott** [comment]
Is there more information regarding what operating system, gcc version etc. is it a docker image?

**Comment by masterleinad** [comment]
Fixed in #3825.
