### ISSUE TITLE
Memory leak in CUDA and HIP stream execution space instances

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#3817]
As discovered in #3767, the copy and move assignment operator for CUDA and HIP execution spaces when initialized with a stream leak memory since we don't clean up when assigning a new pointer to `m_space_instance`:

https://github.com/kokkos/kokkos/blob/9c6697546029ca3f5a34941c262d0c48e66ed596/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L852-L867

Fixed by #3796.

**Comment by dalg24** [comment]
Fixed by #3824
