### ISSUE TITLE
SYCL syntax for barriers

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#3837]
In SYCL 2020, [...] barriers will have to be rewritten as:
```
sycl::group_barrier(m_item.get_group());
```
because the member function has been removed.  Unfortunately, there are no fine-grained feature test macros in SYCL, so we'll just have to make the change when the compile breaks. :-(

Note: there is a second parameter to `group_barrier()` which takes a new `memory_scope` parameter and defaults to `work_group` (as opposed to `work_item`, `sub_group`, `device` or `system`).

Should we have a static member function to do this (so we only have to make the change in one place)?

_Originally posted by @nliber in https://github.com/kokkos/kokkos/pull/3815#discussion_r590546942_

**Comment by ajpowelsnl** [comment]
@masterleinad , @nliber -- what's the status of this issue?  Anything left to do?
