### ISSUE TITLE
Kokkos::subview with RandomAccess Memory Trait

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#385]
The following fails to compile with nvcc (works with gcc, also works if I switch the typedef):

Kokkos::View\<double**> view("name", 10, 3);
  for (int i=0; i < 3; ++i) {
    view(2,i) = i+1;
  }

  // typedef void MemoryTrait;
  typedef Kokkos::MemoryTraits\<Kokkos::RandomAccess> MemoryTrait;

  Kokkos::View\< const double**, MemoryTrait > constView = view;
 
  Kokkos::View\< const double*, Kokkos::LayoutStride, MemoryTrait >  constSubView;
  constSubView = Kokkos::subview(constView, 2, Kokkos::ALL());
  
  

Error is:

_error: no instance of constructor "Kokkos::Experimental::Impl::CudaTextureFetch<ValueType, AliasType>::CudaTextureFetch [with ValueType=const double, AliasType=int2]" matches the argument list
            argument types are: (const double *)
          detected during:
            instantiation of "void Kokkos::Experimental::Impl::ViewMapping<std::enable_if<<expression>, void>::type, SrcTraits, Args...>::assign(Kokkos::Experimental::Impl::ViewMapping<DstTraits, void> &, const Kokkos::Experimental::Impl::ViewMapping<SrcTraits, void> &, Args...) [with SrcTraits=Kokkos::Experimental::ViewTraits<const double **, Kokkos::MemoryTraits<2U>>, Args=<int, Kokkos::Experimental::Impl::ALL_t>, DstTraits=Kokkos::Experimental::ViewTraits<const double *, Kokkos::LayoutStride, Kokkos::MemoryTraits<2U>>" 
...._

Also, using auto is not really an option here, as we want to declare the type up front.

**Comment by hcedwar** [comment]
Will require update to Trilinos package when next integration occurs.
