### ISSUE TITLE
host_mirror_space is not HostSpace when memory_space is CudaUVMSpace

### ISSUE THREAD

**Issue by vqd8a** [kokkos/kokkos#3864]
Assuming I have a ```ViewType``` defined as ```Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::CudaUVMSpace>```. I realized that the ```ViewType::HostMirror``` also has its memory space as ```Kokkos::CudaUVMSpace```. Should it be ```Kokkos::HostSpace``` instead?

**Comment by vqd8a** [comment]
I just want to provide more details. When running ```Kokkos::sort()``` on a mirror view of ```Kokkos::CudaUVMSpace```, I observe that it is much slower (~15x) than running ```Kokkos::sort()``` on a host view for a 1D array of 2000 elements (I use Kokkos::OpenMP for both cases). Is this slow performance expected with ```Kokkos::CudaUVMSpace``` or is there a bug in ```Kokkos::sort``` with ```Kokkos::CudaUVMSpace```?

Reproducer:
```
#include <limits>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#include <Kokkos_Core.hpp>
#include <Kokkos_Random.hpp>
#include <Kokkos_Sort.hpp>

int main( int argc, char* argv[] )
{

  Kokkos::initialize( argc, argv );
  {
    using ViewType1     = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::HostSpace>;
    using ViewType2     = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::CudaUVMSpace>;

    using HostViewType2 = typename ViewType2::HostMirror;

    using execution_space1   = typename ViewType1::device_type::execution_space;
    using execution_space2   = typename ViewType2::device_type::execution_space;
    using memory_space2      = typename ViewType2::device_type::memory_space;
    using host_mirror_space2 = typename ViewType2::host_mirror_space;
    using hostview_execution_space2 = typename HostViewType2::device_type::execution_space;
    using hostview_memory_space2    = typename HostViewType2::device_type::memory_space;

    printf("DeviceView 2: exec_space %s, memory_space %s, host_mirror_space %s\n", typeid(execution_space2).name(), typeid(memory_space2).name(), typeid(host_mirror_space2).name());
    printf("Host mirror view 2: execution_space %s, memory_space %s\n", typeid(hostview_execution_space2).name(), typeid(hostview_memory_space2).name());

    int N=2000;

    uint64_t seed = Kokkos::Impl::clock_tic();
    Kokkos::Random_XorShift64_Pool<execution_space1> rand_pool(seed);
    Kokkos::Timer timer;

    ViewType1 A1 ( "A1", N );//HostSpace
    ViewType2 A2 ( "A2", N );//CudaUVMSpace
    
    HostViewType2 h_A2 = Kokkos::create_mirror_view( A2 );
    std::cout << "A2.data() " << A2.data() << ", h_A2.data() " << h_A2.data() << std::endl; 

    Kokkos::fill_random(A1,rand_pool,Kokkos::rand<Kokkos::Random_XorShift64<execution_space1>,double >::max());

    Kokkos::deep_copy( A2, A1 );
    Kokkos::deep_copy( h_A2, A2 );

    timer.reset();
    Kokkos::sort(A1); Kokkos::fence();
    double time_hostspace = timer.seconds();
    
    timer.reset();
    Kokkos::sort(h_A2); Kokkos::fence();
    double time_hostmirrorspace = timer.seconds();

    if (N<100) {
      for (int j=0; j<N; j++)
        printf( " Check results: A1(%d) = %lf, h_A2(%d) = %lf\n", j, A1(j), j, h_A2(j) );
    }

    printf( " Sort time on host space ( %lf s ), Sort time on host mirror space ( %lf s )\n", time_hostspace, time_hostmirrorspace);
  }

  Kokkos::finalize();

  return 0;
}
```
@crtrott @dalg24 @JulienLoiseau

**Comment by dalg24** [comment]
> Assuming I have a `ViewType` defined as `Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::CudaUVMSpace>`. I realized that the `ViewType::HostMirror` also has its memory space as `Kokkos::CudaUVMSpace`. Should it be `Kokkos::HostSpace` instead?

No.  This is expected because the view is already accessible from the host.

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/0e130610304d5f4471ddce954ca32de73fc63d31/algorithms/src/Kokkos_Sort.hpp#L521-L539

When you pass `A1`, `std::sort` is being used.  When you pass `A2`, we use `Kokkos::BinSort` on `Kokkos::Cuda`.

**Comment by dalg24** [comment]
In other words, I am not surprised that it was much slower considering how it is currently implemented but we could (and should) certainly improve it.

Adding a reference to #2914 to capture that there is more interest for it.

**Comment by vqd8a** [comment]
Thanks, @dalg24
