### ISSUE TITLE
Kokkos master clone tag

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#387]
When Kokkos is snapshotted into another project's repository the git sha1 from Kokkos can be lost by that project's snapshot procedure.
For traceability to which commit of the master was cloned add an in-code macro that is updated each time develop is promoted to master.  For example,
`KOKKOS_DATE` = 10000 * year + 100 * month + day

**Comment by dsunder** [comment]
We could use a client-side 'pre commit hook' to detect a merge between develop and master and populate a text file in top kokkos directory that describes the merge and the date.  However, client-side hooks are not copied when the repository is cloned, so any user doing said merge would need to copy the provided hook into their .git/hooks directory before starting the merge.

—Dan

**Comment by hcedwar** [comment]
1. develop -> master is always --no-ff merge
2. master_history.txt contains:
   - prepend SHA1 of develop that is being merged and the date

**Comment by hcedwar** [comment]
config/develop-master-promotion.txt

Detailed checklist on how to promote.
