### ISSUE TITLE
Kokkos::Vector::push_back throws uninitialized execution space error

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#3875]
This code throws `what():  Constructing View and initializing data with uninitialized execution space` error:
```c++
#include <iostream>
#include <Kokkos_Core.hpp>
#include <Kokkos_Vector.hpp>
#include <Kokkos_DualView.hpp>
#include <Kokkos_UnorderedMap.hpp>
#include <kokkosUtils.hpp>

using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using MemorySpace = ExecutionSpace::memory_space;
using Device = Kokkos::Device<ExecutionSpace, MemorySpace>;
using HostExecutionSpace = Kokkos::DefaultHostExecutionSpace;
using HostMemorySpace = HostExecutionSpace::memory_space;
using HostDevice = Kokkos::Device<HostExecutionSpace, HostMemorySpace>;

struct alignas(8) Key { int ids_[2]; };

using T = Kokkos::UnorderedMap<Key, void, Device>;
using THost = Kokkos::UnorderedMap<Key, void, HostDevice>;

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  Kokkos::vector<T, Device> v;
  v.push_back(T{10});
  v.push_back(T{5});

  } Kokkos::finalize();
}

```

**Comment by Char-Aznable** [comment]
I suspect the main problem is that `Kokkos::Bitset` and `Kokkos::vector` both lack a device default ctor. I tried patching this up by:
```c++
diff --git a/containers/src/Kokkos_Bitset.hpp b/containers/src/Kokkos_Bitset.hpp
index ea1d6dde..bc296eb4 100644
--- a/containers/src/Kokkos_Bitset.hpp
+++ b/containers/src/Kokkos_Bitset.hpp
@@ -92,9 +92,12 @@ class Bitset {
   enum { block_shift = Kokkos::Impl::integral_power_of_two(block_size) };
 
  public:
+
+  KOKKOS_FUNCTION Bitset() = default;
+
   /// constructor
   /// arg_size := number of bit in set
-  Bitset(unsigned arg_size = 0u)
+  Bitset(unsigned arg_size)
       : m_size(arg_size),
         m_last_block_mask(0u),
         m_blocks("Bitset", ((m_size + block_mask) >> block_shift)) {
diff --git a/containers/src/Kokkos_UnorderedMap.hpp b/containers/src/Kokkos_UnorderedMap.hpp
index a5858786..9e4b57a9 100644
--- a/containers/src/Kokkos_UnorderedMap.hpp
+++ b/containers/src/Kokkos_UnorderedMap.hpp
@@ -290,6 +290,9 @@ class UnorderedMap {
   using scalars_view = View<int[num_scalars], LayoutLeft, device_type>;
 
  public:
+
+  KOKKOS_FUNCTION UnorderedMap() = default;
+
   //! \name Public member functions
   //@{
 
@@ -299,7 +302,7 @@ class UnorderedMap {
   /// inserted into the map \param hash [in] Hasher function for \c Key
   /// instances.  The
   ///   default value usually suffices.
-  UnorderedMap(size_type capacity_hint = 0, hasher_type hasher = hasher_type(),
+  UnorderedMap(size_type capacity_hint, hasher_type hasher = hasher_type(),
                equal_to_type equal_to = equal_to_type())
       : m_bounded_insert(true),
         m_hasher(hasher),

```
However, this still runs into reference counting problem if I add code to change the UnorderedMap on the device and to sync it back to host:
```c++
int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  Kokkos::vector<T, Device> v;
  v.push_back(T{10});
  v.push_back(T{5});
  v.push_back(T{4});

  v.modify<HostDevice>();
  v.sync<Device>();

  Kokkos::parallel_for("setMap",
    Kokkos::RangePolicy<ExecutionSpace>(0, v.size()),
    KOKKOS_LAMBDA (const int i) {
    auto& m = v.view<Device>()(i);
    for(int j = 0; j < m.capacity(); ++j) {
      const Key k{j, j};
      const auto r = m.insert(k);
    }
  });

  Kokkos::fence();

  v.modify<Device>();
  v.sync<HostDevice>();

  } Kokkos::finalize();
}

```
which gives `Kokkos::Impl::SharedAllocationRecord failed decrement count` error.

@crtrott any chance we can fix all these so that one can use Kokkos::UnorderedMap inside a view? I have an application where I need to manage a large number of small sparse matrices each of which is an UnorderedMap so this seems the only way to implement it

**Comment by masterleinad** [comment]
The main problem here is that the code implicitly creates a View of Views which has a variety of problems, see https://github.com/kokkos/kokkos/wiki/View#623-can-i-make-a-view-of-views. This is hard to deal with in the general `vector` class but following the instructions in https://github.com/kokkos/kokkos/wiki/View#6233-i-really-want-a-view-of-views-what-do-i-do should make that work.

**Comment by Char-Aznable** [comment]
There are actually deeper problems. There are Kokkos APIs like `Kokkos::volatile_load` that makes implicit assumption about input type being device-side constructible and these APIs are used all over the place without type checking. Some kind of type checking is needed to ensure logical consistency with the usage of View

**Comment by ajpowelsnl** [comment]
Hi @Char-Aznable and @masterleinad -- is this issue still active?

**Comment by Char-Aznable** [comment]
I believe this is still active. The workaround on https://github.com/kokkos/kokkos/wiki/View#6233-i-really-want-a-view-of-views-what-do-i-do can be implemented as specialization of `Kokkos::Vector`. I can take a look at this when I have the time

**Comment by ajpowelsnl** [comment]
@crtrott , @dalg24 -- Should we discuss whether to allow a View of Views on Wed.?

**Comment by masterleinad** [comment]
`Kokkos::vector` is deprecated.
