### ISSUE TITLE
Documentation for kokkos/example/fenl missing?  

### ISSUE THREAD

**Issue by ArchRobison** [kokkos/kokkos#388]
I'm trying to figure out what the code in `example/fenl/` does and what the command line arguments to it do.  I can't find any documentation on it, except for the comment in `example/README` which says:

```
If you are looking for the FENL ("finite element
nonlinear" solve) example, it has moved into the LinAlg subpackage of Tpetra.
```

Perhaps the example should be deleted if it has moved?

**Comment by hcedwar** [comment]
Need to correct README
Need to add basic documentation

**Comment by dalabre** [comment]
@mhoemmen   As indicated by the kokkos/example/README file, this fenl problem (finite element linear solve) has been moved to the Tpetra/LinAlg subpackage ( trilinos/packages/tpetra/classic/LinAlg ). Is this effectively still a sparse matrix solve example? or other? Thanks.

**Comment by ibaned** [comment]
LinAlg is part of "classic" Tpetra which has been deleted from the Trilinos repository. These examples are still being built and tested, but the current Kokkos team members don't know much about them so we should get together and read through them and write documentation.
