### ISSUE TITLE
Team Size mismatch?

### ISSUE THREAD

**Issue by jtchilders** [kokkos/kokkos#3885]
I'm running on a 2x Skylake 8180M node and built kokkos using 
`cmake .. -DCMAKE_INSTALL_PREFIX=<..> -DKokkos_ENABLE_OPENMP=On -DKokkos_ARCH_SKX=On`

I have a code using a TeamPolicy built against this kokkos build.
With my node, I should be able to run 112 threads (confirmed in `/proc/cpuinfo` as well).
However, I can run up to a team size of 64. Between 65 - 112 I get this message: 
`Kokkos::abort: Requested Team Size is too large!Aborted`
At team size >= 113 I get an additional warning:
```
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 112 cores per node.
                                    Detected: 1 MPI_ranks per node.
                                    Requested: 113 threads per process.
```

Any ideas why Kokkos will not let me fill the node?

**Comment by masterleinad** [comment]
The number of team members is limited by 64 for the `Threads` and the `OpenMP` backend, see https://github.com/kokkos/kokkos/blob/1fb0c284d458c75370094921d9f202c287502325/core/src/impl/Kokkos_HostThreadTeam.hpp#L78.

**Comment by jtchilders** [comment]
Many HPCs these days have dual CPUs on a node, containing 10s of cores, each capable of 4 threads. This easily reaches above 64 in most modern systems. Why limit the team size with a hard setting? Perhaps I'm missing something?

**Comment by DavidPoliakoff** [comment]
@jtchilders : not sure, we'd need to get feedback from whoever did the OpenMP design. I'll try to get some eyes on this

**Comment by crtrott** [comment]
Teams are meant to synchronize fast. In general they should never exceed a single socket. Optimally threads in a team share the same L1 cache or at least the same L2 cache. Algorithms such as team broadcast etc. are generally not optimized for maximum scalability on CPUs but for lowest latency in low thread count regimes. Does that make sense? Whats the usecase where you would want to use significantly larger teams then say 4-16 on a cpu?

**Comment by jtchilders** [comment]
OK, Thanks @crtrott . 
I was trying to run a Kokkos app on a compute node that has 2 CPUs. It sounds like you think it is probably better to limit OpenMP apps to 1 CPU, so perhaps use 2 MPI ranks per node?
