### ISSUE TITLE
Restrict access to data for constant random access View

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#3894]
https://github.com/kokkos/kokkos/blob/1fb0c284d458c75370094921d9f202c287502325/containers/unit_tests/TestDynViewAPI.hpp#L1402-L1410

Non-blocking comment: won't this be a problem for, e.g., HIP also? Shouldn't the  method be SFINAE'd out if this isn't an allowed operation?

_Originally posted by @dhollman in https://github.com/kokkos/kokkos/pull/3838#discussion_r596403957_

**Comment by dalg24** [comment]
Why is this not an issue any more?

**Comment by masterleinad** [comment]
We decided to deal with it if the test ever fails with `HIP`.
