### ISSUE TITLE
Request: Kokkos helper for creating execution-space containing stream?

### ISSUE THREAD

**Issue by alanw0** [kokkos/kokkos#3895]
We would like to pass execution-space arguments to deep_copy etc., and on cuda we would like the execution space to contain a cuda-stream, but we prefer not to do the raw-cuda calls ourselves to setup and later delete the cuda-stream. (Because we would then have to also figure out how to do that for AMD/HIP and whatever else.)

We can discuss further if the terminology or motivation here isn't clear.

This is for Sierra/STK, where we are working to get more parallelism and/or asynchrony in our syncing of field-data to/from GPU devices.

**Comment by DavidPoliakoff** [comment]
Alan, just FYI that I've started an implementation sketch here (#3892 ). Once I get approval on the design, I'll extend that to all architectures. This won't make it in 3.4, but is highly likely to be in 3.5, if approved

**Comment by alanw0** [comment]
Great, thanks @DavidPoliakoff I hadn't seen that sketch. Thanks for putting some thought into this!

**Comment by DavidPoliakoff** [comment]
@alanw0 : so the "generic stream create/destroy" option wasn't too popular, I'm stubbing out something new at #3901. Basically, in that one you'll write something like

```c++
auto new_cuda_instances = my_cuda_instance.partition_instances(number_of_instances, Kokkos::FencesSyncSubInstances::no)
```

And you'll get back a collection of "number_of_instances" new Cuda instances, each with their own stream. I know that's a little clumsy for the GPU case you have in mind, but it's the kind of thing that might be generic to other backends (you could partition a thread pool and submit work to sub-pools independently). I think something like that should meet your needs, but feel free to either follow that PR, or have somebody else do so, if you want to keep tabs and make sure we don't fly off the rails

**Comment by alanw0** [comment]
Thanks @DavidPoliakoff , I think this looks reasonable. Tagging @ldh4 since he's working on this kind of thing in stk.

**Comment by masterleinad** [comment]
Added in #4096.
