### ISSUE TITLE
Check compiler version and print helpful message

### ISSUE THREAD

**Issue by kddevin** [kokkos/kokkos#39]
When we got compilation errors, Christian said it was due to our having an old compiler.  Unfortunately, cmake didn't tell us that.  Christian said, "I think Cmake doesn’t identify the compiler version internally. Though we could at least stop inside of Kokkos earlier. (I.e. Stop right away at the first compilation step with a compile time assert and a helpful message). Can you open an issue for that on the kokkos github page?"
Thanks.
Karen

**Comment by crtrott** [comment]
This should work now at least for GCC, Intel and PGI. It will fail early with a helpful error message.

**Comment by samaraseeri** [comment]
Dear Folks,

I need the an older version of kokkos if you please. Have tried to build it on a cray machine with gnu but getting the following error "g++: error: unrecognized command line option '-h'". It was ablt to build the old version.


Thanks

**Comment by jgfouca** [comment]
Looking at this now.

**Comment by crtrott** [comment]
This has nothing to do with the version of Kokkos. This is complaining about an argument to the compiler i.e. part of the CXX Flags. Kokkos never adds a -h.

**Comment by nmhamster** [comment]
We just need to have the version checks also pipe error as well. Do you want me to add that, it "should be easy" (trademark).

**Comment by samaraseeri** [comment]
Hi,

I'm trying to build Kokkos on a Cray machine and getting the above error. A
month ago Kokkos was able to build with gcc without the above error. That
is why I'm asking for the older version if possible.


Best

On Mon, Aug 10, 2015 at 9:43 PM, Si Hammond <notifications@github.com>
wrote:

> We just need to have the version checks also pipe error as well. Do you
> want me to add that, it "should be easy" (trademark).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129561357>.
>



-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by nmhamster** [comment]
Should have a patch any second.

-- 
Si Hammond

Scalable Computer Architectures
Sandia National Laboratories, NM, USA

**Comment by nmhamster** [comment]
Can you try out the pull request diff in pull request #62 please? (https://github.com/kokkos/kokkos/pull/62). I think this should fix the error you are seeing.

**Comment by samaraseeri** [comment]
Cannot clone. It fails with the following message

git clone git@github.com:kokkos/kokkos.git
Cloning into 'kokkos'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


On Mon, Aug 10, 2015 at 10:14 PM, Si Hammond <notifications@github.com>
wrote:

> Can you try out the pull request diff in pull request #62
> <https://github.com/kokkos/kokkos/pull/62> please? (#62
> <https://github.com/kokkos/kokkos/pull/62>). I think this should fix the
> error you are seeing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129570522>.
>



-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by crtrott** [comment]
Si I don't understand how your patch would address the "-h" argument not recognized? That argument seems to come from the application which gets compiled not from Kokkos.

**Comment by samaraseeri** [comment]
Cannot clone latest change. Can anyone help.

Best

$ git clone git@github.com:kokkos/kokkos.git
Cloning into 'kokkos'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of
known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

On Tue, Aug 11, 2015 at 12:34 AM, Christian Trott <notifications@github.com>
wrote:

> Si I don't understand how your patch would address the "-h" argument not
> recognized? That argument seems to come from the application which gets
> compiled not from Kokkos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129616301>.
>



-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by hcedwar** [comment]
@samaraseeri 
Apparently your github access (in general) is not configured properly.  I presume that you cannot clone from any github.com repository.  Go to the github.com main page and verify that you are setup correctly.

**Comment by samaraseeri** [comment]
Now getting:

git clone git@github.com:kokkos/kokkos.git
Cloning into 'kokkos'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


On Tue, Aug 11, 2015 at 1:19 AM, hcedwar <notifications@github.com> wrote:

> @samaraseeri <https://github.com/samaraseeri>
> Apparently your github access (in general) is not configured properly. I
> presume that you cannot clone from any github.com repository. Go to the
> github.com main page and verify that you are setup correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129632281>.
>



-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by nmhamster** [comment]
The -h comes from the Makefile seeing GNU as Cray doesn't it?



--
Si Hammond
Scalable Computer Architectures
Sandia National Laboratories, NM
[Sent remotely, please excuse typing errors]
________________________________

**Comment by samaraseeri** [comment]
When try to clone I get :

git clone git@github.com:kokkos/kokkos.git
Cloning into 'kokkos'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

On Tue, Aug 11, 2015 at 2:00 AM, Si Hammond <notifications@github.com>
wrote:

> The -h comes from the Makefile seeing GNU as Cray doesn't it?
>
>
>
> --
> Si Hammond
> Scalable Computer Architectures
> Sandia National Laboratories, NM
> [Sent remotely, please excuse typing errors]
> ________________________________
> From: Christian Trott <notifications@github.com>
> Sent: Monday, August 10, 2015 3:34:01 PM
> To: kokkos/kokkos
> Cc: Hammond, Simon David (-EXP)
> Subject: [EXTERNAL] Re: [kokkos] Check compiler version and print helpful
> message (#39)
>
>
> Si I don't understand how your patch would address the "-h" argument not
> recognized? That argument seems to come from the application which gets
> compiled not from Kokkos.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/kokkos/kokkos/issues/39#issuecomment-129616301>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129641438>.
>



-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by samaraseeri** [comment]
When try to clone I get :

git clone git@github.com:kokkos/kokkos.git
Cloning into 'kokkos'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Best

On Tue, Aug 11, 2015 at 2:04 AM, Samar Aseeri <samar.aseeri@kaust.edu.sa>
wrote:

> When try to clone I get :
>
> git clone git@github.com:kokkos/kokkos.git
> Cloning into 'kokkos'...
> ssh: connect to host github.com port 22: Connection timed out
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
> and the repository exists.
>
> On Tue, Aug 11, 2015 at 2:00 AM, Si Hammond <notifications@github.com>
> wrote:
>
>> The -h comes from the Makefile seeing GNU as Cray doesn't it?
>>
>>
>>
>> --
>> Si Hammond
>> Scalable Computer Architectures
>> Sandia National Laboratories, NM
>> [Sent remotely, please excuse typing errors]
>> ________________________________
>> From: Christian Trott <notifications@github.com>
>> Sent: Monday, August 10, 2015 3:34:01 PM
>> To: kokkos/kokkos
>> Cc: Hammond, Simon David (-EXP)
>> Subject: [EXTERNAL] Re: [kokkos] Check compiler version and print helpful
>> message (#39)
>>
>>
>> Si I don't understand how your patch would address the "-h" argument not
>> recognized? That argument seems to come from the application which gets
>> compiled not from Kokkos.
>>
>> -
>> Reply to this email directly or view it on GitHub<
>> https://github.com/kokkos/kokkos/issues/39#issuecomment-129616301>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129641438>.
>>
>
>
>
> --
> Samar Aseeri, PhD
> Computational Scientist
> KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
> *King Abdullah University of Science & Technology*
> Thuwal, Saudi Arabia
>
>
>


-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by crtrott** [comment]
Ah the -hstd=c++11 I overlooked that. Yes thats right. Samaraseeri: try cloning via the https route:
git clone https://github.com/kokkos/kokkos.git

**Comment by samaraseeri** [comment]
Yes, the build completed. Thanks for the help.


Best

On Tue, Aug 11, 2015 at 2:04 AM, Christian Trott <notifications@github.com>
wrote:

> Ah the -hstd=c++11 I overlooked that. Yes thats right. Samaraseeri: try
> cloning via the https route:
> git clone https://github.com/kokkos/kokkos.git
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kokkos/kokkos/issues/39#issuecomment-129642661>.
>



-- 
Samar Aseeri, PhD
Computational Scientist
KAUST Supercomputing Laboratory (KSL)  - Building 1 -Office: 0128
*King Abdullah University of Science & Technology*
Thuwal, Saudi Arabia

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by nmhamster** [comment]
I have/(had) a test case which caught the -hstd=c++11 here so regardless it is an issue :(.

**Comment by nmhamster** [comment]
@crtrott @hcedwar Can you merge pull request #62 into the develop when you have time please?

**Comment by crtrott** [comment]
I think this is addressed please reopen if not.
