### ISSUE TITLE
making KOKKOS tutorials with Cuda

### ISSUE THREAD

**Issue by pourmatin** [kokkos/kokkos#391]
Hello,
Apologies in advance for my rudimentary question! I'm trying to compile the provided KOKKOS tutorials with "KOKKOS_DEVICES=Cuda". However, I keep getting various compile errors, deperding on which c++ compiler I'm choosing for nvcc_wrapper!
For " host_compiler="g++" " (with gcc version 4.9.3) I get:

`login1.ls5(8)$ make KOKKOS_DEVICES=Cuda
nvcc_wrapper -I./ -I../../../core/src -I../../../containers/src -I../../../algorithms/src  --std=c++11 -mavx -arch=sm_35 -O3  -c simple_view.cpp
/opt/apps/gcc/4.9.3/include/c++/4.9.3/bits/alloc_traits.h(248): error: expected a ">"
          detected during instantiation of type "std::allocator_traits<_Alloc>::__has_construct<_Tp, _Args...>" 
(251): here

/opt/apps/gcc/4.9.3/include/c++/4.9.3/type_traits(130): error: not a class or struct name
          detected during:
            instantiation of class "std::__and_<_B1> [with _B1=<error-type>]" 
(1957): here
            instantiation of type "std::_Require<<error-type>>" 
/opt/apps/gcc/4.9.3/include/c++/4.9.3/bits/alloc_traits.h(251): here

/opt/apps/gcc/4.9.3/include/c++/4.9.3/type_traits(1957): error: class "std::__and_<<error-type>>" has no member "value"
          detected during instantiation of type "std::_Require<<error-type>>" 
/opt/apps/gcc/4.9.3/include/c++/4.9.3/bits/alloc_traits.h(251): here

/opt/apps/gcc/4.9.3/include/c++/4.9.3/type_traits(1957): error: class "std::enable_if<<error-constant>, void>" has no member "type"
          detected during instantiation of type "std::_Require<<error-type>>" 
/opt/apps/gcc/4.9.3/include/c++/4.9.3/bits/alloc_traits.h(251): here

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/ia32intrin.h(246): error: identifier "__builtin_ia32_readeflags_u64" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/ia32intrin.h(254): error: identifier "__builtin_ia32_writeeflags_u64" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(46): error: identifier "__builtin_ia32_aesdec128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(54): error: identifier "__builtin_ia32_aesdeclast128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(63): error: identifier "__builtin_ia32_aesenc128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(71): error: identifier "__builtin_ia32_aesenclast128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(79): error: identifier "__builtin_ia32_aesimc128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(89): error: identifier "__builtin_ia32_aeskeygenassist128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/wmmintrin.h(118): error: identifier "__builtin_ia32_pclmulqdq128" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(127): error: identifier "__builtin_ia32_addpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(133): error: identifier "__builtin_ia32_addps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(139): error: identifier "__builtin_ia32_addsubpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(145): error: identifier "__builtin_ia32_addsubps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(152): error: identifier "__builtin_ia32_andpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(158): error: identifier "__builtin_ia32_andps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(164): error: identifier "__builtin_ia32_andnpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(170): error: identifier "__builtin_ia32_andnps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(180): error: identifier "__builtin_ia32_blendpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(188): error: identifier "__builtin_ia32_blendps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(205): error: identifier "__builtin_ia32_blendvpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(213): error: identifier "__builtin_ia32_blendvps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(221): error: identifier "__builtin_ia32_divpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(227): error: identifier "__builtin_ia32_divps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(237): error: identifier "__builtin_ia32_dpps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(250): error: identifier "__builtin_ia32_haddpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(256): error: identifier "__builtin_ia32_haddps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(262): error: identifier "__builtin_ia32_hsubpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(268): error: identifier "__builtin_ia32_hsubps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(274): error: identifier "__builtin_ia32_maxpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(280): error: identifier "__builtin_ia32_maxps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(286): error: identifier "__builtin_ia32_minpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(292): error: identifier "__builtin_ia32_minps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(298): error: identifier "__builtin_ia32_mulpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(304): error: identifier "__builtin_ia32_mulps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(310): error: identifier "__builtin_ia32_orpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(316): error: identifier "__builtin_ia32_orps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(323): error: identifier "__builtin_ia32_shufpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(330): error: identifier "__builtin_ia32_shufps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(346): error: identifier "__builtin_ia32_subpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(352): error: identifier "__builtin_ia32_subps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(358): error: identifier "__builtin_ia32_xorpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(364): error: identifier "__builtin_ia32_xorps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(371): error: identifier "__builtin_ia32_cmppd" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(377): error: identifier "__builtin_ia32_cmpps" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(383): error: identifier "__builtin_ia32_cmppd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(390): error: identifier "__builtin_ia32_cmpps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(397): error: identifier "__builtin_ia32_cmpsd" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(403): error: identifier "__builtin_ia32_cmpss" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(434): error: identifier "__builtin_ia32_cvtdq2pd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(440): error: identifier "__builtin_ia32_cvtdq2ps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(446): error: identifier "__builtin_ia32_cvtpd2ps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(452): error: identifier "__builtin_ia32_cvtps2dq256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(458): error: identifier "__builtin_ia32_cvtps2pd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(464): error: identifier "__builtin_ia32_cvttpd2dq256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(470): error: identifier "__builtin_ia32_cvtpd2dq256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(476): error: identifier "__builtin_ia32_cvttps2dq256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(483): error: identifier "__builtin_ia32_vextractf128_pd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(489): error: identifier "__builtin_ia32_vextractf128_ps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(495): error: identifier "__builtin_ia32_vextractf128_si256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(574): error: identifier "__builtin_ia32_vzeroall" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(580): error: identifier "__builtin_ia32_vzeroupper" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(586): error: identifier "__builtin_ia32_vpermilvarpd" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(593): error: identifier "__builtin_ia32_vpermilvarpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(600): error: identifier "__builtin_ia32_vpermilvarps" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(607): error: identifier "__builtin_ia32_vpermilvarps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(615): error: identifier "__builtin_ia32_vpermilpd" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(621): error: identifier "__builtin_ia32_vpermilpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(627): error: identifier "__builtin_ia32_vpermilps" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(633): error: identifier "__builtin_ia32_vpermilps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(653): error: identifier "__builtin_ia32_vperm2f128_pd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(661): error: identifier "__builtin_ia32_vperm2f128_ps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(669): error: identifier "__builtin_ia32_vperm2f128_si256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(693): error: identifier "__builtin_ia32_vbroadcastss" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(699): error: identifier "__builtin_ia32_vbroadcastsd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(705): error: identifier "__builtin_ia32_vbroadcastss256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(711): error: identifier "__builtin_ia32_vbroadcastf128_pd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(717): error: identifier "__builtin_ia32_vbroadcastf128_ps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(724): error: identifier "__builtin_ia32_vinsertf128_pd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(732): error: identifier "__builtin_ia32_vinsertf128_ps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(740): error: identifier "__builtin_ia32_vinsertf128_si256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(856): error: identifier "__builtin_ia32_loadupd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(862): error: identifier "__builtin_ia32_storeupd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(868): error: identifier "__builtin_ia32_loadups256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(874): error: identifier "__builtin_ia32_storeups256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(892): error: identifier "__builtin_ia32_loaddqu256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(898): error: identifier "__builtin_ia32_storedqu256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(904): error: identifier "__builtin_ia32_maskloadpd" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(911): error: identifier "__builtin_ia32_maskstorepd" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(917): error: identifier "__builtin_ia32_maskloadpd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(924): error: identifier "__builtin_ia32_maskstorepd256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(930): error: identifier "__builtin_ia32_maskloadps" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(937): error: identifier "__builtin_ia32_maskstoreps" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(943): error: identifier "__builtin_ia32_maskloadps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(950): error: identifier "__builtin_ia32_maskstoreps256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(956): error: identifier "__builtin_ia32_movshdup256" is undefined

/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(962): error: identifier "__builtin_ia32_movsldup256" is undefined

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_000049c7_00000000-6_simple_view.cpp1.ii".
Compilation terminated.
make: *** [simple_view.o] Error 4`

and for " host_compiler="icc" " (with ICC version 16.0.1) I get:
`login1.ls5(16)$ make KOKKOS_DEVICES=Cuda
nvcc_wrapper -I./ -I../../../core/src -I../../../containers/src -I../../../algorithms/src  --std=c++11 -mavx -arch=sm_35 -O3  -c simple_view.cpp
nvcc warning : The -c++11 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /opt/apps/cuda/6.5/bin/..//include/cuda_runtime.h(59),
                 from simple_view.cpp(0):
/opt/apps/cuda/6.5/bin/..//include/host_config.h(72): error: #error directive: -- unsupported ICC configuration! Only ICC 14.0 on Linux x86_64 is supported!
  #error -- unsupported ICC configuration! Only ICC 14.0 on Linux x86_64 is supported!
   ^

In file included from /opt/apps/gcc/4.9.3/include/c++/4.9.3/type_traits(35),
                 from ../../../core/src/Kokkos_View.hpp(47),
                 from ../../../core/src/Kokkos_Parallel.hpp(52),
                 from ../../../core/src/Kokkos_Serial.hpp(52),
                 from ../../../core/src/Kokkos_Core.hpp(53),
                 from simple_view.cpp(56):
/opt/apps/gcc/4.9.3/include/c++/4.9.3/bits/c++0x_warning.h(32): error: #error directive: This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
  #error This file requires compiler and library support for the \
   ^
make: *** [simple_view.o] Error 2
`

My Cuda version is 6.5
Thank you for your help.
Hossein

**Comment by hcedwar** [comment]
We test with Cuda 6.5 + gcc 4.7.2

**Comment by hcedwar** [comment]
Cuda 6.5 does support gcc 4.9, independent of Kokkos
The error message from nvcc is telling you of the incompatibility
