### ISSUE TITLE
building kokkos under MSVC 2017

### ISSUE THREAD

**Issue by jbensabat** [kokkos/kokkos#3915]
hello 
I am trying to build trilinos using CMAKE GUI
when trying to build kokkos I get the following error 

C:\Software\trilinos\packages\kokkos\core\src\impl/Kokkos_ViewMapping.hpp(137): error C2955: 'Kokkos::Impl::ViewDimension0': use of class template requires template argument list
1>C:\Software\trilinos\packages\kokkos\core\src\impl/Kokkos_ViewMapping.hpp(122): note: see declaration of 'Kokkos::Impl::ViewDimension0'
1>C:\Software\trilinos\packages\kokkos\core\src\impl/Kokkos_ViewMapping.hpp(137): error C2039: 'value': is not a member of 'Kokkos::Impl::ViewDimension0<V,__formal>'
1>C:\Software\trilinos\packages\kokkos\core\src\impl/Kokkos_ViewMapping.hpp(137): error C2504: 'value': base class undefined
1>C:\Software\trilinos\packages\kokkos\core\src\impl/Kokkos_ViewMapping.hpp(137): error C2143: syntax error: missing ',' before '>'

something is mentioned in the source about MSVC 
is there any workaround ?
thanks
jac

**Comment by crtrott** [comment]
I am not sure that anyone fully support building Trilinos under Windows, but generaly with Kokkos I think we need MSVC 2019 anyway

**Comment by masterleinad** [comment]
We are testing MSVC 2019 in our CI so that should work at least with the Serial backend enabled.
Which Trilinos version are you using? Which backends do you enable? Can you try building `Kokkos` as standalone?

**Comment by jbensabat** [comment]
Hi I downloaded kokkos from github and was able to build although only the static libs
what is the difference between kokkos in Trilinos and this one ?
best
jac

**Comment by masterleinad** [comment]
Which `Kokkos` version or commit were you trying? `Kokkos` in the latest `Trilinos` release should be essentially the same as what we have in the `master` branch. Which `Trilinos` version were you trying?

**Comment by mhoemmen** [comment]
I'm not a Trilinos developer any more, but at least historically, people who downloaded Trilinos as a tarball tended to get an ancient release version of Trilinos, since Trilinos never actually bothered with the quarterly release schedule they promised <= 2009.  Maybe they have since fixed that.
