### ISSUE TITLE
Add support for clang 3.7 w/ openmp backend

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#393]
Clang 3.7 and above support openmp.  Please add support for building and testing with clang 3.7 or newer.

**Comment by crtrott** [comment]
Are you sure its full OpenMP 3.1 support?

**Comment by crtrott** [comment]
The website says OpenMP 3.1 is only in Clang 3.8

**Comment by gmackey** [comment]
I've compiled and used Kokkos with OpenMP and Clang 3.7 without any issues.  On the OpenMP website, they claim OpenMP 3.1 will be added with Clang 3.7 (http://openmp.org/wp/2015/08/clang-37-will-have-full-openmp-31-support/).  The release notes for Clang 3.7 says it has full OpenMP 3.1 support as well (http://llvm.org/releases/3.7.0/tools/clang/docs/ReleaseNotes.html#openmp-support).

**Comment by dsunder** [comment]
I've been using the macports clang-3.7 with OpenMP for over 6 months without any problems.

**Comment by crtrott** [comment]
Might be 3.8 actually.

**Comment by crtrott** [comment]
This works now (at least with 3.9.0). Note: the SEMS module was not build with the openmp runtime library. So it will fail to link executables.

**Comment by bathmatt** [comment]
@crtrott How does one enable the clang/openmp build?  I looked at the code and docs and tried the following.
-fopenmp=libomp -fopenmp-version=31 
without luck, if we can add this info to the ticket that would help other seraching

**Comment by crtrott** [comment]
You don't have to do anything. You just need a version of Clang installed which has OpenMP enabled and the LLVM OpenMP runtime installed as well. After that our GNU build at least does all the right things. If you want to do it through Trilinos you need to add: -fopenmp=libomp as you said (you don't need the version thingy). My guess would be that your clang install doesn't actually have the llvm openmp runtime installed (it is an optional thing at least all the way to LLVM/Clang3.9).

**Comment by bathmatt** [comment]
So, have you built w/ SEMS modules?

**Comment by crtrott** [comment]
Oh yeah I should have mentioned that: the SEMS modules did not install OpenMP support in LLVM ....

**Comment by gmackey** [comment]
Clang 3.7 supports OpenMP, but it requires a special build as Christian mentioned.  Clang 3.8 and above support OpenMP in the normal builds.  As far as I know, Clang expects the same flag as GCC to enable OpenMP (-fopenmp).  That's what's always worked for me.

**Comment by crtrott** [comment]
Greg, no this is not fully correct. Clang 3.8 and above support OpenMP by default, but they don't actually build the runtime for OpenMP by default. So a default build of Clang will not work for OpenMP without some complicated explicitly added include and link stuff in order to link against the intel OpenMP runtime and find the header files for OpenMP (not sure if it works with the GNU runtime). You can verify this with the sems-clang modules.

**Comment by bathmatt** [comment]
It does not appear that the SEMS tool has clang installed.

find $SEMS_CLANG_ROOT -name omp.h
dir-tmp (gcc) 4 $
