### ISSUE TITLE
Intel 17, 18, 19 compilation seemingly hangs in nightly tests

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#3936]
Following merge of PR #3832 nightly Intel builds of the develop branch began hanging  partway through compilation (or is so lengthy that builds time out after several hours) and failing to complete. 

This does not occur with the SHA of the previous merge commit 84ff7f1

Sample reproducer instruction (Serial backend)
```
# Load intel 17, 18 or 19 and cmake

cmake -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
```

**Comment by masterleinad** [comment]
@DavidPoliakoff Didn't you check compilation times for #3832, possibly with @dhollman?

**Comment by DavidPoliakoff** [comment]
@masterleinad I did, but nonetheless... Working through with Nic

**Comment by masterleinad** [comment]
Apparently, we are having a similar issue for `icpc (ICC) 19.1.1.217 20200306` with `Kokkos 3.4.00`.

**Comment by nmm0** [comment]
This seems to be a problem on `TestDefaultDeviceTypeResize.cpp`. Trying to narrow down what specifically is causing the problem. It's worth noting all the DeviceType tests take significantly longer than the other tests to compile.

**Comment by nmm0** [comment]
Update: the underlying cause appears to be the linearizing bases trick used as a workaround for MSVC EBO problems. PR #3924 fixes the problem for at least some configurations, still testing others
