### ISSUE TITLE
Question about view of kokkos 

### ISSUE THREAD

**Issue by yuanAIhan** [kokkos/kokkos#3938]
How can I understand the implementation of Kokkos's view from the source code? Now, some question for me. Please help me ?

**Comment by yuanAIhan** [comment]
using view_type = Kokkos::View<double *[10]>;
I want to know how to get the number of ten(10) in double *[10] ;

**Comment by masterleinad** [comment]
That would be
```
view_type::static_extent(1);
```

**Comment by yuanAIhan** [comment]
> That would be
> 
> ```
> view_type::static_extent(1);
> ```

yeah!Thanks! I need to learn it more!
