### ISSUE TITLE
Which files realize the memory allocation?

### ISSUE THREAD

**Issue by yuanAIhan** [kokkos/kokkos#3939]
I want to know which files realize the memory allocation?
What is the difference between kokkos's memory allocation and stl?

**Comment by crtrott** [comment]
Uhm that is a rather broad question. Memory allocations are implemented by all the different MemorySpace classes like CudaSpace, HostSpace, CudaUVMSpace etc. This has nothing to do with the stl really.,

**Comment by crtrott** [comment]
Oh and feel free to join the kokkosteam.slack.com for questions like this. That is where you usually get answers pretty fast.
