### ISSUE TITLE
Wiki MemorySpaceConcept refers to undefined symbol

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#3951]
https://github.com/kokkos/kokkos/wiki/Kokkos%3A%3AMemorySpaceConcept

> `execution_space`: the default `ExecutionSpace` to use when constructing objects in memory provided by an instance of `MSp`, or (potentially) when deep copying from or to such memory (see `deep_copy` documentation for details). 

The symbol `MSp` is not defined or mentioned anywhere else on the page.

**Comment by crtrott** [comment]
That just meant MemorySpace. I fixed it.
