### ISSUE TITLE
moving intermediate compilation/linking files to build directory with Makefile

### ISSUE THREAD

**Issue by haykh** [kokkos/kokkos#3952]
Hi, I was wondering if you could help with my issue. 

I'm building an app that uses `kokkos` as an external library. This is roughly what the project looks like as a tree-view:
```
 └──  extern/ 
 │  └────   catch2/ 
 │  └────   kokkos/ 
 │  └────   plog/ 
 │  └────   toml++/ 
 └──  lib/ 
 │  └────   ...
 │  └────   ... 
 │  ├────   ...
 │  └────   ...
 └──  app/ 
 │  └────   main.cpp  
 └──  tests/ 
 │  └────   test.cpp  
 └──  Makefile  
```

My `Makefile` looks something like this:

```
all: app
 
include ${KOKKOS_PATH}/Makefile.kokkos

app: $(BUILD_DIR)/$(TARGET)
$(BUILD_DIR)/$(TARGET): $(APP_OBJS) $(OBJS) $(KOKKOS_LINK_DEPENDS)
  $(CXX) $(APP_OBJS) $(OBJS) -o $@ $(LDFLAGS) $(KOKKOS_LDFLAGS) $(KOKKOS_LIBS)

$(BUILD_DIR)/%.cpp.o: %.cpp
  mkdir -p $(dir $@)
  $(CXX) $(CPPFLAGS) $(CXXFLAGS) $(KOKKOS_CXXFLAGS) -c $< -o $@
```
Basically it makes a temporary `build` directory (with `make app`), compiles all the `cpp` files there and then links them. All the variables are defined in advance. And since that depends on `kokkos` -- it also compiles and links that as a library. All works and is perfectly fine. 

The problem is rather aesthetic: `kokkos` creates a bunch of junk files (`.o`-s, `.tmp`-s, `.hpp`-s) in the root directory (instead of the `build`, obviously, as it doesn't know how to). 

The `Makefile.kokkos` pretty much looks like a black box, and I was wondering if there is a way to specify the prefix for these temporary objects and files. 

Thank you advance!

PS. Actually the same can be seen if you try make the `example/make_buildlink/` project from the source code.

**Comment by crtrott** [comment]
No there is no such configure option. Basically we support you calling make from wherever you want (i.e. a build directory) and it will put it all there, but that assumes you invoke make there. It would be quite a bit of work to fix that. What might be possible is for you to auto create a Makefile in your build dir and then include Makefile.kokkos there and build it, but I am not sure.

**Comment by haykh** [comment]
Fair comment! I ended up making a cmake-style makefile that compiles in the temporary disposable subdirectory. Closing the issue.
*don't ask me why I can't have used the `cmake` in the first place. :)
