### ISSUE TITLE
parallel_scan should create accum var not with copy initialization syntax

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#3954]
In parallel_scan (e.g., [here](https://github.com/kokkos/kokkos/blob/1fb0c284d458c75370094921d9f202c287502325/core/src/Cuda/Kokkos_Cuda_Team.hpp#L1011)), the accumulation variable is created like so:

```
value_type accum = 0;
```
This syntax is not ok if value_type ctor from 0 is explicit. E.g., for a SIMD type with ctor
```
// Fill all entries of SIMD vector with s.
MySimdType (const ScalarType& s) explicit;
```
the compiler would complain.

Is there any downside turning the accum var creation into something like the following?
```
value_type accum(0);
```

**Comment by masterleinad** [comment]
The particular source line you are pointing out has actually been replaced in `develop`, see https://github.com/kokkos/kokkos/blob/eee712802629267ca8c6109b57b17995fcff6988/core/src/Cuda/Kokkos_Cuda_Team.hpp#L1006-L1009. If there are other places, we should also treat them similarly by doing whatever would appropriate for a general reducer (in doubt call `Sum::init`).

**Comment by bartgol** [comment]
@masterleinad Ah, great. We've been using a version of kokkos based on 3.3.00. I guess as soon as this gets tagged with a suitable version, we can fast forward our kokkos version.

I haven't checked all places where this happened. I just remember having to drop the explicit from our SIMD class' ctor, due to this. Once we update our kokkos version, I'll try adding it back, and see what happens.

Btw, it seems to me that, if a reducer exposed the reduction identity, one could do
```
value_type accum(ReducerType::reduction_identity());
```
and save one default initialization of accum. Probably a O(epsilon) improvement though...
