### ISSUE TITLE
TaskPolicy - generate error when attempt to use uninitialized 

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#396]
A default constructed TaskPolicy is "null" and not usable.  Generate an error for attempts to use a null TaskPolicy.

**Comment by crtrott** [comment]
Mark as enhancement (since it is about catching an user error, rather than correct code not working).

**Comment by hcedwar** [comment]
The `host_spawn` function will abort if the `TaskScheduler` is not initialized.
