### ISSUE TITLE
Targeting multiple CUDA architectures

### ISSUE THREAD

**Issue by keichi** [kokkos/kokkos#3965]
Hi, I am planning to distribute a Kokkos-based Python extension module on PyPI. In plain CUDA code, I would add multiple `-gencode` flags when invoking nvcc, but the `-DKokkos_ARCH_*` flags seem exclusive. Is there a way to build for multiple CUDA architectures in Kokkos?

**Comment by ajpowelsnl** [comment]
This deliverable is part of our long term set of priorities.  Currently, we do not have the resources or the driver to take on this work immediately.

**Comment by keichi** [comment]
Thanks, @masterleinad @ajpowelsnl! I will find an alternative solution. Maybe I will build a separate shared library for each target as suggested in another issue. Closing this issue for now.
