### ISSUE TITLE
v3.4.00: KokkosContainers_UnitTest_OpenMP fails on ppcle64

### ISSUE THREAD

**Issue by junghans** [kokkos/kokkos#3976]
From https://koji.fedoraproject.org/koji/taskinfo?taskID=66826158, only ppc64le fails:
```
hypot(long double, long double)
relative difference exceeds tolerance [6.837208e-33 > 9.881313e-324]
value at 2.000000, 3.000000 which is 3.605551 was expected to be 3.605551
/builddir/build/BUILD/kokkos-3.4.00/core/unit_test/TestMathematicalFunctions.hpp:467: Failure
Value of: 0
Expected: errors
Which is: 1
[  FAILED  ] openmp.mathematical_functions_power_functions (19 ms)
```

Build log [here](https://github.com/kokkos/kokkos/files/6388405/build.log.txt)

**Comment by dalg24** [comment]
Configure with `-DKokkos_ENABLE_POWER8=ON`

https://github.com/kokkos/kokkos/blob/4b97a22ff7be7635116930bb97173058d6079202/core/unit_test/TestMathematicalFunctions.hpp#L604-L606

**Comment by junghans** [comment]
Will test. Is there anything I should enable for x86_64, aarch64 and s390x archs?

**Comment by dalg24** [comment]
> Is there anything I should enable for x86_64, aarch64 and s390x archs?

I wouldn't bother.

**Comment by junghans** [comment]
Worked!
