### ISSUE TITLE
Missing handler for unsupported standard flag in nvcc_wrapper 

### ISSUE THREAD

**Issue by keipertk** [kokkos/kokkos#3979]
nvcc_wrapper handles many unsupported c++ standard flags by falling back to -std=c++14. But there is no such logic for -std=gnu++0x / -std=c++0x - which are valid flags for GNU, but not supported by nvcc. 

Note that if one specifies -std=gnu++0x, it is converted to -std=c++0x by nvcc_wrapper. But neither are valid options for nvcc.

**Comment by masterleinad** [comment]
Since `Kokkos` only supports C++14 and later, we should only need to handle flags that correspond to C++14 and later. Where does `-std=gnu++0x` come from?

**Comment by keipertk** [comment]
`std=gnu++0x` was the working name for C++11, so out of scope for kokkos then. I was mistaken in thinking the flag enabled a future standard, but have since learned it referred specifically to C++11.
