### ISSUE TITLE
cudaMallocAsync

### ISSUE THREAD

**Issue by maxpkatz** [kokkos/kokkos#3981]
In lanl/parthenon#506 we saw an issue where the memory allocation pattern is relatively inefficient using cudaMalloc. This is a pattern where the internal suballocation scheme of [cudaMallocAsync](https://developer.nvidia.com/blog/enhancing-memory-allocation-with-new-cuda-11-2-features/) does substantially better (instead of ~40% of memory unused, it is more like ~1%). As a first cut, this could be exposed as an option in `cudaSpace` that just immediately synchronizes after called. It could also be a new memory space (e.g. `cudaAsyncSpace`) that in principle allows the user to actually asynchronously allocate the memory.

**Comment by crtrott** [comment]
Are there performance issues with using cudaMallocAsync / cudaDeviceSynchronize pairings? Did you compare that?

**Comment by maxpkatz** [comment]
My experience has been that the performance gain from allocating with cudaMallocAsync is often significant even if you effectively make it synchronous with an immediate device sync due to its internal pool allocator.

There is also the issue that we'd be blocking on any asynchronous kernel launches in progress that were being done at the same time as an allocation or free. I don't expect this is a common use case, cudaMalloc and cudaFree have been effectively synchronous for so long now that I can't imagine anyone intentionally coded around that behavior. But if that would break some workflow let me know.

**Comment by crtrott** [comment]
Currently all allocations and deallocations are semantically blocking in Kokkos and have to be. Largely that is because the async kernels don't do proper reference counting on allocations and it kinda would be bad to yank a view's allocation away while a kernel is still using it ...

**Comment by maxpkatz** [comment]
OK, that makes sense. So for now let's treat this only as an alternative way to achieve the memory pooling effect of an Umpire memory space and address the semantics of a truly asynchronous allocator at some later date.

**Comment by PhilMiller** [comment]
The code for this is implemented, but disabled in #4288. I think this issue could probably be closed. I was reminded to come look by #6344 reported by @romintomasetti

**Comment by masterleinad** [comment]
Added support in #4026.
