### ISSUE TITLE
DefaultExecutionSpace is a class or other?

### ISSUE THREAD

**Issue by yuanAIhan** [kokkos/kokkos#3989]
when I read the resource code,I find this about Kokkos::DefaultExecutionSpace in View. But I do not find what is DefaultExecutionSpace ? It is a class or a Macro definition ？

**Comment by dalg24** [comment]
It is an alias.
https://github.com/kokkos/kokkos/blob/4df09798f85f2318e9da3087f02b1eca5aaa5d34/core/src/Kokkos_Core_fwd.hpp#L120-L176

**Comment by dalg24** [comment]
Types can have attributes.  Also the annotation expands to nothing unless you are using Clang's static analyzer (it is meant for Kokkos' Clang-Tidy checks which can warn you at compile-time for instance if you capture `*this` in a lambda expression which would yield runtime memory access violation when running on GPUs)

**Comment by yuanAIhan** [comment]
> Types can have attributes. Also the annotation expands to nothing unless you are using Clang's static analyzer (it is meant for Kokkos' Clang-Tidy checks which can warn you at compile-time for instance if you capture `*this` in a lambda expression which would yield runtime memory access violation when running on GPUs)

Can I think the default of DefaultExecutionSpace is  cpu serial ? But In this code do not have any attributes. Is it defined in some other file ？A cmake file? 
![image](https://user-images.githubusercontent.com/80769611/116703828-4a1a7500-a9fd-11eb-95fc-13e591c02c15.png)

It use as this  -> 

```  using ExecutionSpace = typename std::conditional<
      !std::is_same<typename prop::execution_space, void>::value,
      typename prop::execution_space, Kokkos::DefaultExecutionSpace>::type; ```

  ``` using MemorySpace = typename std::conditional<
      !std::is_same<typename prop::memory_space, void>::value,
      typename prop::memory_space, typename ExecutionSpace::memory_space>::type; ```  in view  .

I don't know where its attributes are defined? Can you tell me? Because you can see from the code that it has an attribute such as memory_space?  Thanks！

**Comment by masterleinad** [comment]
> Can I think the default of DefaultExecutionSpace is cpu serial ? But In this code do not have any attributes. Is it defined in some other file ？A cmake file?

Just as @dalg24 said, `DefaultExecutionSpace` is an alias with the aliased execution space depending on the enabled backends. If no backends are explicitly enabled, this will be an alias for `Kokkos::Serial` which is defined in https://github.com/kokkos/kokkos/blob/4b97a22ff7be7635116930bb97173058d6079202/core/src/Kokkos_Serial.hpp#L88-L160
You can see that this class defines `memory_space` and other alias types. This holds similarly for the other execution spaces possibly aliased by `DefaultExecutionSpace`.

**Comment by yuanAIhan** [comment]
> > Can I think the default of DefaultExecutionSpace is cpu serial ? But In this code do not have any attributes. Is it defined in some other file ？A cmake file?
> 
> Just as @dalg24 said, `DefaultExecutionSpace` is an alias with the aliased execution space depending on the enabled backends. If no backends are explicitly enabled, this will be an alias for `Kokkos::Serial` which is defined in
> 
> https://github.com/kokkos/kokkos/blob/4b97a22ff7be7635116930bb97173058d6079202/core/src/Kokkos_Serial.hpp#L88-L160
> 
> 
> You can see that this class defines `memory_space` and other alias types. This holds similarly for the other execution spaces possibly aliased by `DefaultExecutionSpace`.

Thank you very much!
