### ISSUE TITLE
staticcrsgraph: create_staticcrsgraph failure in Tpetra with HIP

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#3990]
Tpetra fails to build due to a staticcsrgraph failure.
The underlying cause is that Tpetra currently uses the `Kokkos::Experimental::HIPHostPinnedSpace` while UVM removal is underway.
This means that views internally constructed using the execution_space as template parameter will run into issues as they use the default `Kokkos::Experimental::HIPSpace` which is incompatible.

**Comment by masterleinad** [comment]
You are running into the same issue with HIP as I am currently with SYCL. :slightly_smiling_face: 
I think we should just use the associated memory_space. I can open a pull request for that.

**Comment by brian-kelley** [comment]
@lucbv I ran into the same issue. I think your Kokkos change is fine, but i did a workaround in KokkosKernels by just avoiding the 'factory': https://github.com/kokkos/kokkos-kernels/pull/949.

**Comment by ajpowelsnl** [comment]
In develop
