### ISSUE TITLE
Can you tell me the default value of this traits

### ISSUE THREAD

**Issue by yuanAIhan** [kokkos/kokkos#3994]
some code in the Kokkos_viewMapping.hpp =>

**template <class Traits, class Enable = void>**
struct ViewDataHandle { 
  using value_type  = typename Traits::value_type;  
  using handle_type = typename Traits::value_type*;
  **using return_type = typename Traits::value_type&;**
  using track_type  = Kokkos::Impl::SharedAllocationTracker;
  KOKKOS_INLINE_FUNCTION
  static handle_type assign(value_type* arg_data_ptr,
                            track_type const& /*arg_tracker*/) {
    return handle_type(arg_data_ptr);
  } 
  KOKKOS_INLINE_FUNCTION
  static handle_type assign(handle_type const arg_data_ptr, size_t offset) {
    return handle_type(arg_data_ptr + offset); 
  }
};

The Traits have some default? If I use Kokkos like this(using view_type = Kokkos::View<double * [3]>;)
What is the default value of the Traits at this time ? Thanks!

**Comment by masterleinad** [comment]
Compiling
```
Kokkos::View<double*[3]>::traits dummy = "";
```
gives
```
error: conversion from ‘const char [1]’ to non-scalar type ‘Kokkos::View<double* [3]>::traits {aka Kokkos::ViewTraits<double* [3]>}’ requested
```

**Comment by DavidPoliakoff** [comment]
I think the question was about the value of the traits. @yuanAIhan, it might be good to say what you're trying to accomplish, it will help us answer your questions better.

The `value_type` is double, which tells you the others. What's going on here is that we're making a class that manipulates the data in the View (this is _never_ seen in user code). It looks at various template arguments of the View, and realizes "oh, this is a View<double* [3]>, so the type I return is a double, a pointer to that is a double*, and if I return that from a View indexing operation I should return a double&." If you let us know what you're trying to do we might have more informative answers, though
