### ISSUE TITLE
Compiler flags for a main.f90 file

### ISSUE THREAD

**Issue by pourmatin** [kokkos/kokkos#400]
Hello,

I'm trying to convert the .cu files of my code to .cpp, using Kokkos. The complication is my main function is in fortran (main.f90). So is it possible to do that without rewriting the main function in C++? and if so, in what way should I change the ${KOKKOS_LDFLAGS} for mpif90?

Thank you
Hossein

**Comment by crtrott** [comment]
Hi

you can have an initialize_kokkos.cpp which has two functions for initialize and finalize with an extern C function interface, and then call them through the usual mechanism you call external C functions in fortran at the begin and end of your main in the fortran file.

**Comment by pourmatin** [comment]
That is brilliant. 
Thank you

**Comment by mhoemmen** [comment]
Sounds like this is closed :-)
