### ISSUE TITLE
Kokkos not building with Visual Studio 2019

### ISSUE THREAD

**Issue by jrobcary** [kokkos/kokkos#4005]
This is a reboot of an issue that was reported in trilinos.  The current errors from the build log are when built within trilinos, so perhaps only the first two are really kokkos.  Creating this to have an issue number for creating the branch.
I think I have a fix for the first two.

`
grep ' error' nmake.txt | grep Kokkos | sort -u
D:\winsame\cary\vorpalall-dev1\trilinos\packages\kokkos-kernels\src\common\KokkosKernels_BitUtils.hpp(207): fatal error C1189: #error:  "Popcount function is not defined for this compiler. Please report this with the compiler you are using to KokkosKernels."
D:\winsame\cary\vorpalall-dev1\trilinos\packages\kokkos-kernels\src\common\KokkosKernels_IOUtils.hpp(428): error C2664: 'int _stat64i32(const char *,_stat64i32 *)': cannot convert argument 2 from 'stat *' to '_stat64i32 *'
D:\winsame\cary\vorpalall-dev1\trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(292): error C2668: 'Kokkos::atomic_compare_exchange_strong': ambiguous call to overloaded function
D:\winsame\cary\vorpalall-dev1\trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(303): error C2668: 'Kokkos::atomic_compare_exchange_strong': ambiguous call to overloaded function
D:\winsame\cary\vorpalall-dev1\trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(340): error C2668: 'Kokkos::atomic_compare_exchange_strong': ambiguous call to overloaded function
D:\winsame\cary\vorpalall-dev1\trilinos\packages\tpetra\core\src\Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp(396): error C2668: 'Kokkos::atomic_compare_exchange_strong': ambiguous call to overloaded function
D:\winsame\cary\vorpalall-dev1\trilinos\packages\xpetra\src\Utils\Xpetra_ETI_4arg.hpp(42): error C2065: 'Kokkos_Compat_KokkosSerialWrapperNode': undeclared identifier
D:\winsame\cary\vorpalall-dev1\trilinos\packages\xpetra\src\Utils\Xpetra_ETI_4arg.hpp(42): error C2923: 'Xpetra::CrsMatrixWrap': 'Kokkos_Compat_KokkosSerialWrapperNode' is not a valid template type argument for parameter 'Node'
`

**Comment by jrobcary** [comment]
Hmm.  Now I am confused.  Looks like KokkosKernels is not part of kokkos?

**Comment by masterleinad** [comment]
No, it's a separate repository: https://github.com/kokkos/kokkos-kernels

**Comment by jrobcary** [comment]
Okay.  Will close and open there.
