### ISSUE TITLE
Propose changed to Kokkos_Sparse_trsv.hpp to handle processes with zero rows

### ISSUE THREAD

**Issue by allaffa** [kokkos/kokkos#401]
@allaffa @jhux2 

I am currently working on a project at Sandia about multigrid preconditioners where some tasks have no matrix rows. I have encountered a situation where Kokkos throws an exception in the file "Kokkos_Sparse_trsv.hpp" around line 107 inside of the "trsv" function. I would like to propose a change of the condition to throw the exception, checking also that the number of rows be different from zero. 

See .txt file attached
[0007-Kokkos-added-check-on-rows-in-exception.txt](https://github.com/kokkos/kokkos/files/425900/0007-Kokkos-added-check-on-rows-in-exception.txt)

**Comment by crtrott** [comment]
Is this a thing with respect to the Kokkos Kernels package in Trilinos? That is not currently part of the core kokkos project so you are in the wrong place. Can you reopen the issue with Trilinos: github.com/trilinos/trilinos?

Thanks

**Comment by jhux2** [comment]
Dang, you're right.  I was the one who told Max to open the issue here.  We'll close this one and reopen w/ Trilinos.

**Comment by crtrott** [comment]
No problem. I am gonna check back with Mark whether he thinks this is ok so that we can merge it in. Remember to open against develop not master.
