### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by Fyz01** [kokkos/kokkos#4028]
Hello
when I'm trying to build kokkos, I get the following error

  In file included from /home/fangyz/kokkos/build/KokkosCore_Config_SetupBackend.hpp:47:0,
                 from /home/fangyz/kokkos/core/src/Kokkos_Macros.hpp:109,
                 from /home/fangyz/kokkos/core/src/Kokkos_Core_fwd.hpp:52,
                 from /home/fangyz/kokkos/core/src/Kokkos_Core.hpp:51,
                 from /home/fangyz/kokkos/core/src/impl/Kokkos_Core.cpp:45:
/home/fangyz/kokkos/core/src/setup/Kokkos_Setup_Cuda.hpp:54:2: error: #error "KOKKOS_ENABLE_CUDA defined but the compiler is not defining the __CUDACC__ macro as expected" #error

cmake information:
-- Setting default Kokkos CXX standard to 14
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Compiler Version: 10.1.243
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: Kokkos::OpenMP
--       Host Serial: NONE
-- Architectures:
--  VOLTA70
-- Kokkos Devices: OPENMP;CUDA, Kokkos Backends: OPENMP;CUDA
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fangyz/kokkos/build

should I change my cuda version?

**Comment by ndellingwood** [comment]
The cuda version should be fine, I'll post a sample configure line that installed kokkos (SHA 0d181ef3c9dba92cddbea29073246b215fda98bf) without issue using cuda/10.1.243, gcc/7.3.0, and cmake/3.19, hopefully this helps:

```bash
cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DCMAKE_INSTALL_PREFIX=${PWD}/install -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ENABLE_TESTS=OFF -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
```
where `KOKKOS_PATH` points to your kokkos source directory

**Comment by Fyz01** [comment]
> The cuda version should be fine, I'll post a sample configure line that allowed install of kokkos without issue (SHA [0d181ef](https://github.com/kokkos/kokkos/commit/0d181ef3c9dba92cddbea29073246b215fda98bf)) using cuda/10.1.243, gcc/7.3.0, and cmake/3.19, hopefully this helps:
> 
> ```shell
> cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DCMAKE_INSTALL_PREFIX=${PWD}/install -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ENABLE_TESTS=OFF -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
> 
> make install -j4
> ```
> 
> where `KOKKOS_PATH` points to your kokkos source directory

Thanks
I used your configure line and got the following error:
> CMake Error at CMakeLists.txt:94 (PROJECT):
>          The CMAKE_CXX_COMPILER:
>          ../bin/nvcc_wrapper
>          is not a full path and was not found in the PATH

before this, I used -DCMAKE_CXX_COMPILER=$PATH:/nvcc, PATH = /usr/local/cuda/bin, and didn't have this error，but make install still failed

I used cuda/10.1.243, gcc 7.5.0, and cmake/3.19.8

**Comment by Fyz01** [comment]
> The cuda version should be fine, I'll post a sample configure line that allowed install of kokkos without issue (SHA [0d181ef](https://github.com/kokkos/kokkos/commit/0d181ef3c9dba92cddbea29073246b215fda98bf)) using cuda/10.1.243, gcc/7.3.0, and cmake/3.19, hopefully this helps:
> 
> ```shell
> cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DCMAKE_INSTALL_PREFIX=${PWD}/install -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ENABLE_TESTS=OFF -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
> 
> make install -j4
> ```
> 
> where `KOKKOS_PATH` points to your kokkos source directory

Thanks
I used your configure line and got the following error:
> CMake Error at CMakeLists.txt:94 (PROJECT):
>          The CMAKE_CXX_COMPILER:
>          ../bin/nvcc_wrapper
>          is not a full path and was not found in the PATH

before this, I used -DCMAKE_CXX_COMPILER=$PATH:/nvcc, PATH = /usr/local/cuda/bin, and didn't have this error，but make install still failed

I used cuda/10.1.243, gcc 7.5.0, and cmake/3.19.8

**Comment by masterleinad** [comment]
If you use the latest release, the `master`, or `develop` branch you can just a host compiler as `CMAKE_CXX_COMPILER` or don't specify it at all.
Otherwise, you should `nvcc_wrapper` that is contained in this repository at `bin/nvcc_wrapper` (assuming that `nvcc` is in your `PATH`).

**Comment by Fyz01** [comment]
> If you use the latest release, the `master`, or `develop` branch you can just a host compiler as `CMAKE_CXX_COMPILER` or don't specify it at all.
> Otherwise, you should `nvcc_wrapper` that is contained in this repository at `bin/nvcc_wrapper` (assuming that `nvcc` is in your `PATH`). Make sure to provide a full path and not just a relative path.

use nvcc_wrapper works, Thanks for your help!
