### ISSUE TITLE
Enable atomics on Windows-LLVM so that TPetra can compile

### ISSUE THREAD

**Issue by jrobcary** [kokkos/kokkos#4029]
The problem shows up when compiling TPetra, where there is a call to atomic_assign, but no calls are available, as none of the ENABLE_*_ATOMICS get defined by Kokkos_Atomic.hpp, and even if they were, the atomics assume that long is 64 bits, while it is 32 bits on Windows.  On Windows one wants to use long long.

Will follow this with the needed PR.

**Comment by masterleinad** [comment]
Fixed in #3247.
