### ISSUE TITLE
error：‘Cuda‘ is not a member of ‘Kokkos’

### ISSUE THREAD

**Issue by Fyz01** [kokkos/kokkos#4035]
Hello
when i'm try to make simple_reduce.cpp in kokkos/example/tutorial/02_simple_reduce, I got the error:
> error：‘Cuda‘ is not a member of ‘Kokkos’

it comes from
> Kokkos::RangePolicy\<Kokkos::Cuda\> policy(0, n);

I have set the -DKokkos_ENABLE_CUDA=ON, and build the project successfully, why is this error occurring?

**Comment by masterleinad** [comment]
How are you building the examples? Did you specify `-DKokkos_ENABLE_EXAMPLES=ON` when building `Kokkos`?

**Comment by Fyz01** [comment]
> How are you building the examples? Did you specify `-DKokkos_ENABLE_EXAMPLES=ON` when building `Kokkos`?

> cmake
> -DCMAKE_CXX_COMPILER=nvcc_wrapper \
> -DCMAKE_INSTALL_PREFIX=../../kokkos-install \
> -DKokkos_ENABLE_OPENMP=ON \
> -DKokkos_ENABLE_CUDA=ON \
> -DKokkos_ENABLE_EXAMPLES=ON \
> -DKokkos_ARCH_VOLTA70=ON \
> -DKokkos_ENABLE_TESTS=OFF \
> -DCMAKE_VERBOSE_MAKEFILE=ON \
> -DCMAKE_CXX_EXTENSIONS=OFF \
> -DCMAKE_BUILD_TYPE=REALEASE \
> -DKokkos_ENABLE_LIBDL=OFF \
> ..

yes, still the same error..

**Comment by crtrott** [comment]
jup if you typed make in the tutorial directory that would have created files which screw the cmake build up.

**Comment by ajpowelsnl** [comment]
@Fyz01 Hello - have we resolved your issue, or would you like further help?

**Comment by Fyz01** [comment]
> @Fyz01 @crtrott Good morning -- Can we assist you further with your ticket? If not, may we close it today? Many thanks for any update you can provide. Best, AJP

Sorry for the late reply! The problem has been solved. Thanks very much for your help!
