### ISSUE TITLE
When the execution space of kokkos is designated as openmp. Compared with the execution space is the host. What advantages does it bring? 

### ISSUE THREAD

**Issue by yuanAIhan** [kokkos/kokkos#4048]
When the execution space of kokkos is designated as openmp. Compared with the execution space is the host. What advantages does it bring? 
Like this ->. using view_type = Kokkos::View<double * [3], Kokkos::OpenMP>;
Specify the execution space for openmp 。
                   using view_type = Kokkos::View<double * [3]>；
The default host is the execution space。
What is the difference between them in  View？ 
What are the advantages of specifying the execution space as openmp?

**Comment by masterleinad** [comment]
https://kokkosteam.slack.com/messages is better suited for these kinds of questions.

**Comment by crtrott** [comment]
but to give you a short answer: these are the same. There is no advantage and some downside to explicitly writing Kokkos::OpenMP there, better would be Kokkos::DefaultExecutionSpace and Kokkos::DefaultHostExecutionSpace if you want to be explicit. If you want to be fully explicit you can use the full types but define them in a header.

**Comment by ajpowelsnl** [comment]
@yuanAIhan - Good morning - Have we answered your question in great enough detail for you to move forward, or can we help you with anything else on this front?

**Comment by ajpowelsnl** [comment]
@yuanAIhan -- Hello - can we help you with anything further on this issue?  If so, please let us know at your earliest convenience.  If not, please let us know if we can close your ticket.  Many thanks!
