### ISSUE TITLE
Kokkos as library

### ISSUE THREAD

**Issue by pourmatin** [kokkos/kokkos#405]
Hello,

Kokkos README file has specific instructions on how how build Kokkos as a library. However, non of the provided examples or tutorials actually seem to be using libkokkos.a
Is it possible to actually use this library instead of including Makefile.kokkos in my own Makefiles? If so, how can I get around generating kokkos_config.h?

Thank you for your time
Hossein

**Comment by crtrott** [comment]
Hi

the KokkosCore_config.h will be generated as part of the library build and is gonna be located in the install directory of the library. The drawback of pre-installing Kokkos is that it will be one configuration, with one specific set of enabled backends etc. So if you want to rebuild your code with another backend you also need a different library install. But it should in principal work. 

Christian

**Comment by dholladay00** [comment]
There is a `generate_makefile.bash` script that generates a Makefile for building Kokkos as a library. You run that script which defines the correct macros, etc. based upon the options provided to the script. The Makefile will produce usable header files and `libkokkos.a`. Enabling the Cuda backend is a little bit more tricky as you need to use the provided nvcc_wrapper as the compiler.

I have some example scripts that show how to do this if you'd like, I can dig one up.

**Comment by crtrott** [comment]
Since no new post came I assume the question was answered and close it for now.
