### ISSUE TITLE
Makefile.kokkos causes unnecessary builds

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#4052]
For SPARTA, using the traditional Makefile build system (`gmake`), something in Kokkos seems to be messing up the build dependency workflow. If I build everything, then run the same `gmake` command, nothing should happen. However, a bunch of SPARTA files are rebuilt because it thinks these files "out of date":

```
   Prerequisite `KokkosCore_Config_SetupBackend.hpp' is newer than target `compute_distsurf_grid_kokkos.o'.
   Prerequisite `KokkosCore_Config_DeclareBackend.hpp' is newer than target `react_tce_kokkos.o'.
   Prerequisite `KokkosCore_Config_FwdBackend.hpp' is newer than target `react_tce_kokkos.o'.
```

These Kokkos files seem to be touched/updated every time `gmake` is run.

**Comment by crtrott** [comment]
This problem comes from having automatic dependency discovery. The KOKKOS_CPP_DEPENDS variable does not include those files and so it wouldn't trigger a rebuild. But the fix is easy, and we will do this.

**Comment by ajpowelsnl** [comment]
In develop currently, not yet merged into Release
