### ISSUE TITLE
-MD option in nvcc_wrapper

### ISSUE THREAD

**Issue by glesur** [kokkos/kokkos#4078]
It seems like nvcc_wrapper converts -MD flag into -M when calling nvcc, which makes dependencies printed to stdout instead of being sent to a .d file, as the -MD should be doing.

Is there any proper reason for this weird behaviour or is this a bug?

**Comment by masterleinad** [comment]
This might be an ordering issue in https://github.com/kokkos/kokkos/blob/e4831441fb213bd29485327b02cf1b54149a58a7/bin/nvcc_wrapper#L171-L198
Does it work properly if you move the `-I*|-L*|-l*|-g|--help|--version|-E|-M|-shared|-w)` option below the other ones?

**Comment by glesur** [comment]
To me, the problem is line 528:
`nvcc_depfile_command="$nvcc_command -M $depfile_target_arg $depfile_output_arg"`
when -MD or -MMD is passed in argument to nvcc_wrapper, `depfile_separate` is set to 1, and nvcc is then called with -M on l. 528 (not -MD or -MMD). I would have thought that -MD or -MMD should be given to nvcc, but maybe this piece of code dates back when nvcc only supported -M?

**Comment by crtrott** [comment]
Hm that piece of code comes from some folks who actually use dependency files. But yes this might be older.

**Comment by crtrott** [comment]
Yeah -MD was only introduced in CUDA 11 ...

**Comment by glesur** [comment]
right, so I'll stick to -M then to be compatible with cuda 10 (we're also using dep files). For future reference, nevertheless, I think -MD should be passed to nvcc when -MD is passed to nvcc_wrapper.

**Comment by ajpowelsnl** [comment]
@glesur - Good morning -- can we help you with this issue further at this time? Would you like for us to put the "future reference" item (i.e., " For future reference, nevertheless, I think -MD should be passed to nvcc when -MD is passed to nvcc_wrapper." ) in our backlog?  Many thanks for the suggestion : )

**Comment by glesur** [comment]
Yep, if -MD is now accepted by nvcc, I believe nvcc_wrapper should not transform it into -M, so it should be kept in mind for the future. I'm closing the comment, thanks!
