### ISSUE TITLE
Convert p-threads backend to std::thread 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#4081]
A successful conversion requires performance parity with the current Kokkos Threads backend measured with:
- [ ] the standard benchmark set of LAMMPS 
- [ ] the benchmark suite of Kokkos Core 
- [ ] the Kokkos version of the RajaPerf suite 
- [ ] Document benchmarks and comparisons results keeping track of which commits are used etc 

Note that the benchmarks themselves require no changes, since they currently build with the Kokkos Threads backend, and the conversion will not change the public interface of Kokkos itself.

**Comment by fnrizzi** [comment]
@PhilMiller's suggestion: 
For ease of development/comparison, I'd suggest we start with the following source-level indirection

* Rename `Kokkos::Threads` to `Kokkos::PosixThreads`
* Add `namespace Kokkos { using Threads = PosixThreads; }`
* Duplicate the `Kokkos::PosixThreads` implementation to our new `Kokkos::CppThreads` implementation

That way, we can easily change just the type alias (maybe even make it depend on a preprocessor macro) without touching anything else.

This is potentially slightly complicated by other coordinating classes that may go along with the specific pthreads implementation, which we'll need to adjust to use the literal name accordingly, and then reimplement for our new backend.

**Comment by crtrott** [comment]
Actually I literally meant dropping posix threads in favor of std::threads. I.e. make the Kokkos::Threads backend use std::thread and not having a backend which uses raw pthreads. But for development purposes you could start a new backend as a copy and then later we just rename and delete the old one?

**Comment by PhilMiller** [comment]
That's my intention, yeah.

**Comment by PhilMiller** [comment]
PR merged
