### ISSUE TITLE
algorithms: signature of function object argument 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#4090]
This issue is related to #4074.

**Going more concretely into the signature of function object** @crtrott @dalg24 @cz4rs @PhilMiller
```c++
template<class InputIt, class UnaryFunction> 
Kokkos::for_each(InputIt first, InputIt last, UnaryFunction f);
``` 
We want device runnable code, and `f` to be consistent with standard ,so its signature should be equivalent to:
```c++
void fun(const Type &a);
```
the type `Type` must be such that an object of type `InputIt` can be dereferenced and then implicitly converted to `Type`.
So for this to work , we want users for example to do: 
```c++
Kokkos::for_each(..., ..., KOKKOS_LAMBDA(double & operand) {
    operand++; 
  });

// or 

auto myLambda = KOKKOS_LAMBDA(double & operand) { operand++; }
Kokkos::for_each(..., ..., myLambda);
```
such that the functor is host or device runnable. 
Then, inside the for_each impl (or similarly for other algos), we construct a functor that takes the one passed in such that we can run a parallel for based on the iterators.

**Comment by crtrott** [comment]
Yeah this looks right.

**Comment by mhoemmen** [comment]
@fnrizzi Should "device runnable code" imply at least [`forward_iterator`](https://en.cppreference.com/w/cpp/iterator/forward_iterator)?

**Comment by crtrott** [comment]
We actually gonna need random_access_iterator. Forward_iterator only has ++ or, which means their is a non-fixed overhead to get the correct forward indexing for each thread?

**Comment by mhoemmen** [comment]
@crtrott Users would definitely want to use random access iterators for performance, but the only thing they would need for correctness is the multipass guarantee that forward iterators offer.

**Comment by fnrizzi** [comment]
> @fnrizzi Should "device runnable code" imply at least [`forward_iterator`](https://en.cppreference.com/w/cpp/iterator/forward_iterator)?

@mhoemmen  What I actually meant with that was that the functor `f` passed by the user should be runnable on device. However, we also want `f` to have a signature consistent with the one you would use in the standard.

**Comment by fnrizzi** [comment]
I think this is resolved.
