### ISSUE TITLE
CUDA/Kepler37: team size AUTO gives "requested too large team size"

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#4095]
See https://github.com/trilinos/Trilinos/issues/9272 for original issue appearing in Trilinos nightlies
Workaround in https://github.com/trilinos/Trilinos/pull/9278

Note: this is not a Trilinos blocker because of the workaround. If there's an easy fix that would be great, otherwise this issue could just serve to document what happened.

One specific functor causes this error when doing parallel_reduce with team size ``AUTO()``:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Impl::ParallelReduce< Cuda > requested too large team size.
Traceback functionality not available

Aborted
```
Using ``teampol.team_size_recommended(functor, ParallelReduceTag())`` instead works. If I print out the team size for AUTO where the exception is thrown, it's using 544, while team_size_recommended gives 512.

This happens on debug builds with bounds checking only, on Kepler K80 (e.g. RIDE/White rhel7F queue) with Kepler37 arch. But it happens with develop and 3.4.1, and with CUDA 9 and 10. It doesn't happen on Kepler35 architectures - I tried on kokkos-dev and ride's rhel7T queue.

RIDE reproducer instructions:
Get on node
```
bsub -Is -q rhel7F -W 3:00 bash
```
Modules
```
module load devpack/20190404/openmpi/4.0.1/gcc/7.2.0/cuda/10.1.105
module swap cmake/3.12.3 cmake/3.19.3
```
Clone Kokkos develop.

Replace example/build_cmake_in_tree/cmake_example.cpp with this: https://gist.github.com/brian-kelley/259f495732cbc33b0a643754c9f13ec4

Config
```
cmake \
        -DKokkos_ENABLE_CUDA=ON \
        -DKokkos_ARCH_POWER8=ON \
        -DKokkos_ARCH_KEPLER37=ON \
        -DCMAKE_BUILD_TYPE=Debug \
        -DKokkos_ENABLE_DEBUG=ON \
        -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
        ../kokkos/example/build_cmake_in_tree
```
Expected output (I added a line in Kokkos_Cuda_Parallel.hpp:2056 to print out ``m_team_size``).
```
Full functor type: 23SortIntoLongRowsFunctor
Recommended SortIntoLongRowsFunctor team size: 512
Launching with AUTO team size...
(attempted team size = 544)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Impl::ParallelReduce< Cuda > requested too large team size.
Traceback functionality not available

Aborted
```

**Comment by janciesko** [comment]
Thanks for reporting this Brian. Looks like an issue in block size deduction (cuda_deduce_block_size) for that platform you are mentioning. I'll take a look.
