### ISSUE TITLE
Which architecture optimization for cascade lake cpus?

### ISSUE THREAD

**Issue by remunds** [kokkos/kokkos#4124]
Hi,
I was just wondering which architecture-keyword is best for the Intel Xeon Platinum 9242 (cascade lake-ap) processors.
Also: would it be possible to add @stud.tu-darmstadt.de to the allowed domains for the slack-channel?

**Comment by stanmoore1** [comment]
Can just use Skylake (SKX), see https://github.com/kokkos/kokkos/issues/3590.

**Comment by remunds** [comment]
oh perfect, did not see this. Thank you :)
