### ISSUE TITLE
Kokkos::UnorderedMap::clear() doesn't zero out size()

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#4128]
Consider this:
```c++
#include <Kokkos_Core.hpp>
#include <Kokkos_UnorderedMap.hpp>
#include <iostream>

using HostExecutionSpace = Kokkos::DefaultHostExecutionSpace;

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  using MapHost = Kokkos::UnorderedMap<int,void,Kokkos::DefaultHostExecutionSpace>;

  MapHost mHost{10};
  mHost.insert(3);
  mHost.insert(4);

  std::cout << mHost.size() << " of " << mHost.capacity() << "\n";

  mHost.clear();

  std::cout << mHost.size() << " of " << mHost.capacity() << "\n";

  } Kokkos::finalize();
}

```
where both `std::cout` lines print "2 of 128", i.e., the `mHost.clear()` doesn't clear the number of inserted elements. This seems very counterintuitive because the `clear()` method looks like it's returning the map to an uninserted state as in the case of the equivalent of a STL container.

**Comment by nliber** [comment]
`UnorderedMap::m_size` is a cache of the size of the container (that is why is is marked `mutable`), which only gets updated when `size()` is called on a modified (indicated by the `m_scalars(modified_idx)` flag) map.   This flag is only set (under some conditions) in `insert` and `erase` methods.  clear() both clears out `m_scalars` (which effectively clears the `modified_idx` flag) and doesn't update the `m_size` value, hence the bug.
