### ISSUE TITLE
Memory allocation for PerTeam level 1 scratch with CUDA backend should take into account actual number of teams

### ISSUE THREAD

**Issue by arnodu** [kokkos/kokkos#4143]
PerTeam level 1 scratch in CUDA takes into account the maximum number of concurrent teams that can be scheduled by the hardware to determine the allocation size in global memory. The actual number of teams is not taken into account, even if it's smaller than what the hardware can schedule.

When using a small number of teams with a large PerTeam scratch buffer the memory footprint is excessive : 
With 1000 teams needing 255KB each i would expect an allocation no bigger than 255MB, but instead the memory-events kokkos-tool reports an allocation of 1.3GB on Tesla V100.

Could the actual number of teams to dispatch be taken into account to determine the size of the allocation in global memory?

**Comment by crtrott** [comment]
We will do this.

**Comment by PhilMiller** [comment]
Fix released in 3.6
