### ISSUE TITLE
Allow non-power-2 team sizes for team reductions and team scans.

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#4146]
As noticed in https://github.com/kokkos/kokkos/pull/3536#issuecomment-874458276, we currently don't allow non-power-2 team sizes for team reductions and team scans (at least for the `CUDA` backend) but we decided that this is useful to have.

**Comment by crtrott** [comment]
Do we want this?

SF F N A SA
1 10 2 0 0

**Comment by crtrott** [comment]
So we decided to want this :-)

**Comment by PhilMiller** [comment]
Fix was released in 3.6
