### ISSUE TITLE
Xeon Phi native and offload mode

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#416]
Hello Kokkos Team,

It appears that when building a Kokkos application for the Xeon Phi, ie, by selecting KOKKOS_ARCH = "KNC", the application builds for native-mode execution by default.

Is compiling for offload mode also available?

Regards,
Michael

**Comment by crtrott** [comment]
No it is not supported. We never bothered because DOE is not buying any offload Xeon Phi machines. KNL (the just newly released Xeon Phi) is mostly sold as self hosted (i.e. its only native mode). 

Christian

**Comment by mcarilli** [comment]
Understood, thanks.
