### ISSUE TITLE
Serial Backend Threadsafety

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#4171]
We need to make it threadsafe to use the Serial backend from multiple (non-kokkos controlled) threads. 

For example ThreadTeamScratch is problematic...

So we need a) use mutexes to protect use in singletons, and b)
allow creation of distinct Serial instances with partition_space().

**Comment by masterleinad** [comment]
Should have been fixed by https://github.com/kokkos/kokkos/pull/4053 already.
