### ISSUE TITLE
Parallel Reduce Bug With Large Team Sizes

### ISSUE THREAD

**Issue by JamieStumpORNL** [kokkos/kokkos#4177]
Parallel reduce was giving nonsense answers occasionally when using Kokkos::AUTO for the team size.
As it turns out, it also gives nonsense answers using a team size of 64 (I've tested on 1,2,4...,32,64).
So I believe Kokkos::AUTO would occasionally chose a size large enough which causes buggy code.
I am on a power9 architecture which uses a Volta70 gpu.

**Comment by crtrott** [comment]
Hi, do you have reproducer code? We need some code for that, since we do test this pretty thoroughly and don't have any failing combos I am aware of.

**Comment by ajpowelsnl** [comment]
Hello @JamieStumpORNL !  Would you please provide reproducer code for this error?  We will be happy to help, once we have that info.

**Comment by JamieStumpORNL** [comment]
What is the best way to send the code over? You can email me at stumpbc@ornl.gov

**Comment by masterleinad** [comment]
Ideally, you would have a small reproducer that you can just paste here.

**Comment by masterleinad** [comment]
Not enough info to be meaningful.
