### ISSUE TITLE
KokkosP event for View access

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#4184]
So, in several other threads we're discussing adding an event to Kokkos::View each time it is captured. I think this is a good idea, but it keeps getting held up on the MDSpan view refactor. What I'm proposing here is that _while_ we wait on the mdspan refactor, we add a KokkosP event (which we will say won't be permanent) for a View access. Once we have the mdspan refactor, we can throw that away, but I'd like to start experimenting with tooling for this. My thoughts are:

1) This event will be hidden behind a preprocessor branch, default-off. This is for advanced users only
2) This will directly invoke a kokkosp_callback from within the copy constructor

There's increasing interest in "how do I debug dataflow problems" and I'd like to start writing tools to answer those questions. My thought is that we put this up to a vote Wednesday

**Comment by ajpowelsnl** [comment]
@DavidPoliakoff Ok , I'll add to the list of items to vote on Wed.

**Comment by masterleinad** [comment]
How are you going to detect if `Kokkos::View` is captured? Do you mean that you want to detect copies?

Independently, I think it's reasonable to introduce such an event (as long as we test it somewhere).

**Comment by DavidPoliakoff** [comment]
@masterleinad : see @3493 , and @nmm0 has a more up-to-date version of that same concept (though his does something more interesting/powerful)

**Comment by ajpowelsnl** [comment]
@DavidPoliakoff , I am closing this issue; awaiting @nmm0 PR

**Comment by ajpowelsnl** [comment]
see @nmm0 draft design:  https://github.com/kokkos/kokkos/pull/4197
