### ISSUE TITLE
Segfaults in CI for OPENMPTARGET-Clang 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#4188]
While working on the std algorithms implementation, I came across a problem with reductions for OpenMPTarget.  
I created the following reproducer: 
```cpp
namespace Test {

template <class IndexType>
struct MyFunctor {
  using index_type = IndexType;

  KOKKOS_INLINE_FUNCTION
  void operator()(const index_type i, int& redValue) const {
    (void)i;
    redValue += 1;
  }

  KOKKOS_INLINE_FUNCTION
  MyFunctor() {}
};

template <class ViewType>
struct FillViewFunctor {
  ViewType m_view;

  FillViewFunctor(ViewType view) : m_view(view) {}

  KOKKOS_INLINE_FUNCTION
  void operator()(int i) const { m_view(i) = i; }
};

TEST(red_issue, is_ok) {
  using view_t = Kokkos::View<int[10]>;
  view_t myView("VIEW");

  FillViewFunctor<view_t> F(myView);
  Kokkos::parallel_for(myView.extent(0), F);

  using index_type   = int;
  using reducer_type = Kokkos::Sum<index_type, Kokkos::DefaultExecutionSpace>;
  int sum            = 0;
  reducer_type reducer(sum);
  Kokkos::parallel_reduce("LABEL", myView.extent(10), MyFunctor<index_type>(),
                          reducer);
}

TEST(red_issue, not_ok) {
  using view_t = Kokkos::View<int[10]>;
  view_t myView("VIEW");

  FillViewFunctor<view_t> F(myView);
  Kokkos::parallel_for(myView.extent(0), F);

  using index_type   = int;
  using reducer_type = Kokkos::Sum<index_type, Kokkos::DefaultExecutionSpace>;
  using result_view_type = typename reducer_type::result_view_type;
  result_view_type result("result_view");
  reducer_type reducer(result);
  Kokkos::parallel_reduce("LABEL", myView.extent(0), MyFunctor<index_type>(),
                          reducer);
}
}  // namespace Test
```

The `is_ok` test works fine, the `not_ok` test segfaults. 
See this: https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/5779/pipeline/42
Please note that I am only concerned with OpenMPtarget. 
It might very well be that this is not a bug and i am doing something wrong, but I am not sure what. 
Any help would be greatly appreciated!

**Comment by rgayatri23** [comment]
I was able to run this test case with llvm-12 installed on my machine (cori-gpu). 
I think if the llvm compiler in the CI is updated to the latest (llvm-13), the issue will be resolved.
I can raise a PR for that if needed.

**Comment by ajpowelsnl** [comment]
Hi @fnrizzi and @rgayatri23 -- is this issue still active?

**Comment by rgayatri23** [comment]
I tested this issue with llvm/14 which is what we are using for the CI testing and the issue has been resolved.

**Comment by masterleinad** [comment]
> I tested this issue with llvm/14 which is what we are using for the CI testing and the issue has been resolved.

Is it worth it to add it to the unit tests then?

**Comment by rgayatri23** [comment]
> > I tested this issue with llvm/14 which is what we are using for the CI testing and the issue has been resolved.
> 
> Is it worth it to add it to the unit tests then?

This seemed to be a specific bug with the llvm compiler. So I do not think it is testing anything Kokkos specific to be added as a unit test.
