### ISSUE TITLE
nvcc_wrapper -> $(NVCC_WRAPPER)

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#42]
Hi,

this is a minor thing, but it could be useful to define NVCC_WRAPPER in the top level Makefile.kokkos
NVCC_WRAPPER :=  $(KOKKOS_PATH)/config/nvcc_wrapper
for people not accustomed to trilinos build, they may not be aware of nvcc_wrapper.

I also think that nvcc_wrapper could be installed in $(PREFIX)/bin

In case it is useful, i did the modification in my repo.

Some examples are missing a Makefile; I added one so that they still build when KOKKOS_PATH points to the install location (where is the customized Makefile.kokkos) instead of top-level kokkos source path.

best regards,
Pierre.

**Comment by crtrott** [comment]
I did merge the changes into the develop branch.
