### ISSUE TITLE
algorithms: API with custom label, support for hierarchical parallelism 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#4202]
@cz4rs @crtrott @dalg24 

Related to #4075 #4076 #4082 #4083 #4084 
Two items to bring up and vote on.

# (1) User-provided label 
Do we want to support a custom label when calling algorithms? 
```cpp
namespace KE = Kokkos::Experimental;
KE::max_element("my_debug_label", KE:cbegin(view), KE::cend(view));
KE::max_element("my_label", view);
```
Vote on this. 

# (2) Nesting algorithms call in par_for
I think it would make sense (at some point) to support the following use case (or some similar to it): 
```cpp
namespace KE = Kokkos::Experimental;

template <class view_t, class member_t>
struct FunctorWithTeamLevelMaxElement {
  view_t m_view;
  //....

  KOKKOS_INLINE_FUNCTION
  void operator()(const member_t& tmember) const 
  {
    const auto pol = Kokkos::TeamThreadRange(tmember, m_view.extent(0));
    const auto myTeamId = tmember.league_rank();
    const auto myRow = Kokkos::subview(m_view, myTeamId, Kokkos::ALL());
    const auto result    = KE::max_element(pol, KE::cbegin(myRow), KE::cend(myRow));
    // do something with result
    //...
  }

  KOKKOS_INLINE_FUNCTION
  FunctorWithTeamLevelMaxElement(view_t viewIn) : m_view(viewIn){}
};

int main()
{
  ...
  Kokkos::View<double**> myView("something", 10, 1000); 
  const int leagueSize = myView.extent(0);
  using team_p_t = Kokkos::TeamPolicy<>;
  using member_t = team_p_t::member_type;
  team_p_t policy(leagueSize, Kokkos::AUTO());
  using F_t = FunctorWithTeamLevelMaxElement<decltype(myView), member_t>;
  Kokkos::parallel_for(policy, F_t(myTestedView, maxVals));
  ...
}
```
Vote on this: we want this? we do not want this (yet)
If yes, whether we should make it available right away, i.e. as soon as we announce support for std algos, 
or if we postpone this to later. For example, we can plan such that we first push out "simple" use cases (e.g. not allowing nesting algos within par_for), and then gradually support more complex ones, like the one above.

**Comment by crtrott** [comment]
Regarding 1): There are pro and cons. For algorithms which don't take a custom functor it may not make sense to have this, since its really the same algorithm. On the other hand people might still want to distinguish based on where they call it. The overhead of supporting this is also fairly small, since its at most a couple forwarding overloads (i.e. the overload without a string forwards to the one with the string after adding our default label for the algorithm like "Kokkos::alg::max_element"

Regarding 2): I definitely think we need to do this, and largely in the way you prototyped this. I think we should discuss when we get closer to the end of the current contract, and put that on the list of next things. We should discuss priorities though in the team.

**Comment by fnrizzi** [comment]
> Regarding 1): There are pro and cons. For algorithms which don't take a custom functor it may not make sense to have this, since its really the same algorithm. On the other hand people might still want to distinguish based on where they call it. The overhead of supporting this is also fairly small, since its at most a couple forwarding overloads (i.e. the overload without a string forwards to the one with the string after adding our default label for the algorithm like "Kokkos::alg::max_element"
> 
Yes exactly, and that is how it is implemented. Just wanted to make sure we all agree on this because you originally proposed this but as a "tenative" thing. So we'll move forward with it. 

> Regarding 2): I definitely think we need to do this, and largely in the way you prototyped this. I think we should discuss when we get closer to the end of the current contract, and put that on the list of next things. We should discuss priorities though in the team.
Indeed I verified that the prototyped code above works. Also, overall it is not too bad to support if we do something clever with the public API forwards args to the implementation. Ok, so we can discuss this during one of the meetings to see how high priority the team assigns to it. I agree that it is a "level-up" feature, but also think that if the team parfor is widely used, this usecase might be important.

**Comment by fnrizzi** [comment]
Discussion/vote on August 4th: 
- 1: all in favor
- 2: will pause on this for now, pick it up later
