### ISSUE TITLE
Deprecation proposal: Remove raw ptr parallel_reduce overload for array reductions 

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#4208]
When doing array reductions (which requires a proper functor with value_count and value_type definition, and is currently not supported for lambdas) one can either provide a raw ptr or a View as result argument. I propose we deprecate the raw ptr variant. 

One issue is that we don't properly define whether the raw ptr variant can be asynchronous. 

```c++
#include <Kokkos_Core.hpp>
#include <cmath>

struct F {
  int value_count;
  using value_type = int[];
  using ScalarType = int;
  KOKKOS_FUNCTION
  void operator()(int i, value_type v) const {
    v[0]+=i;
  }
  F() { value_count=1;}
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  {
    int N = argc > 1 ? atoi(argv[1]) : 100;
    int R = argc > 2 ? atoi(argv[2]) : 10;

    int r = 0;
    // Deprecate this call variant
    Kokkos::parallel_reduce(N, F(), &r);
    Kokkos::fence();
    printf("%i\n",r);

    r = 0;
    // One would now have to wrap into a view:
    Kokkos::parallel_reduce(N, F(), Kokkos::View<int*,Kokkos::HostSpace>(&r,1));
    Kokkos::fence();
    printf("%i\n",r);
  }
  Kokkos::finalize();
}
```

So before:
```c++
    Kokkos::parallel_reduce(N, F(), &r);
```

Replaced by (this already works):
```c++
    Kokkos::parallel_reduce(N, F(), Kokkos::View<ScalarType*,Kokkos::HostSpace>(&r,F().value_count));
```

**Comment by masterleinad** [comment]
Sounds reasonable to me. There is a clear path to adapt to the non-deprecated version by wrapping the pointer in an unmanaged View. For most of the implementations, we fence depending on the internal reduction pointer being host/device-accessible or not. It would certainly be good to document this better.
Of course, it would be good to evaluate first how painful the deprecation for users is. Does `Trilinos` use array reductions with raw pointers?

**Comment by DavidPoliakoff** [comment]
Unanimously decided to do this (or rather, nobody voiced opposition)
