### ISSUE TITLE
Support for ranges larger than INT_MAX in SYCL (and other backends)

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#4210]
For recent (nightly) `SYCL` compiler releases, I run into issues when using policies with ranges larger than `INT_MAX` in size.
For the `SYCL` backend we decided to use `size_type = int`, see https://github.com/kokkos/kokkos/blob/984093842b822871b6a8e2ac1f8b727d2c1af999/core/src/SYCL/Kokkos_SYCL_Instance.hpp#L57-L59 but then there are also compiler flags for the SYCL compiler that allow/disallow using more work items than INT_MAX can hold, see https://software.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/offload-compilation-options-openmp-options-and-parallel-processing-options/fsycl-id-queries-fit-in-int.html.

Particular tests that are problematic are contained in https://github.com/kokkos/kokkos/blob/develop/core/unit_test/TestView_64bit.hpp (but there are others). The GPU backends have `size_type = unsigned int` and the `HostSpace` has `size_type = size_t` allowing for somewhat larger ranges.
My question is what we want to promise supporting in the end. Clearly, there was some interest in ranges larger than `INT_MAX` looking at #1541, #1481, and #1452.

**Comment by crtrott** [comment]
Note that you technically should be able to override that by providing an IndexType to the Policy.

I.e. even on CUDA something like this should work:

```c++
int64_t N = int64_t(10)*1000*1000*1000;
int64_t result;
parallel_reduce(RangePolicy<IndexType<int64_t>>(0,N), 
  KOKKOS_LAMBDA(int64_t i, int64_t& lsum) { 
   lsum += i<int64_t(5)*1000*1000*1000?1:2;
  }, result);
printf("%li\n",result);
```
