### ISSUE TITLE
Nightly tests failure: openmp.scatterview in sems-intel/17.0.1 builds

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4220]
Splitting this off into it's own issue from #4136 for better tracking, failure began around July 8

Failure message:
```
21:07:52 39: [ RUN      ] openmp.scatterview
21:07:52 39/41 Test #39: KokkosContainers_UnitTest_OpenMP .............***Exception: Illegal  0.57 sec
```

That one crept in after the intel compiler desul fixes went in
```
module load sems-env sems-cmake/3.17.1 sems-intel/17.0.1
module swap sems-gcc/4.9.3 sems-gcc/6.4.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=OpenMP  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

_Originally posted by @ndellingwood in https://github.com/kokkos/kokkos/issues/4136#issuecomment-876579546_

**Comment by ajpowelsnl** [comment]
Thanks @ndellingwood !

**Comment by crtrott** [comment]
Looks like this only happens if you build for something older than HSW, I extracted the test into a stand alone thing and if I compile for at least HSW it passes. So probably the intel compiler issues a haswell and up instruction for one of the things.

**Comment by crtrott** [comment]
Using SNB fails and specifying nothing fails.

**Comment by crtrott** [comment]
HAHA, looks like if I comment out any 4 of these lines in the scatterview sum test:
```c++
    for (int j = 0; j < 10; ++j) {
      auto k = (i + j) % scatterSize;
      scatter_access(k, 0) += 4;
      ++scatter_access(k, 1);
      --scatter_access(k, 2);
      scatter_access(k, 3)++;
      scatter_access(k, 4)--;
      scatter_access(k, 5) -= 5;
      scatter_access_atomic(k, 6) += 2;
      scatter_access_atomic(k, 7)++;
      scatter_access_atomic(k, 8)--;
      --scatter_access_atomic(k, 9);
      ++scatter_access_atomic(k, 10);
      scatter_access(k, 11) -= 3;
}
```

I don't get the illegal instruction for the sum test. It doesn't even matter which of them. While I didn't do an exhaustive combinatorical test, I tried like 30 combos. As long as there are only 8 consecutive ops I don't get the illegal error;

based on that I did this which appears to fix the problem: 
```c++
    for (int j = 0; j < 10; ++j) {
      auto k = (i + j) % scatterSize;
      scatter_access(k, 0) += 4;
      ++scatter_access(k, 1);
      --scatter_access(k, 2);
      scatter_access(k, 3)++;
      scatter_access(k, 4)--;
      scatter_access(k, 5) -= 5;
#ifdef KOKKOS_COMPILER_INTEL
#if(KOKKOS_COMPILER_INTEL<1800)
    }
    for (int j = 0; j < 10; ++j) {
      auto k = (i + j) % scatterSize;
#endif
#endif
      scatter_access_atomic(k, 6) += 2;
      scatter_access_atomic(k, 7)++;
      scatter_access_atomic(k, 8)--;
      --scatter_access_atomic(k, 9);
      ++scatter_access_atomic(k, 10);
      scatter_access(k, 11) -= 3;
    }
```

I will insert that as a workaround. Since this only affects Intel 17 on pre Haswell platforms, apparently if you do more than 6ish atomics on unsigned int in a sequence I feel its fair to do this.

**Comment by crtrott** [comment]
My supicion is that the compiler optimizes the sequence of atomic adds into a AVX256 add in that case (these instructions are atomic on itself) instead of going through scalar atomics. That is only valid on Haswell and newer though.

**Comment by crtrott** [comment]
Looked with @nmhamster into this a bit more, dissection the assembly. It appears that the compiler tries to align the instructions in the bit code, and makes a mistake. Turns out that even just inserting an assembly nop fixes the problem:
```c++
    for (int j = 0; j < 10; ++j) {
      auto k = (i + j) % scatterSize;
      scatter_access(k, 0) += 4;
      ++scatter_access(k, 1);
      --scatter_access(k, 2);
      scatter_access(k, 3)++;
      scatter_access(k, 4)--;
      scatter_access(k, 5) -= 5;
// Workaround Intel 17 compiler bug if you have more than 8 atomic adds
// on unsigned int in direct sequence. It results in illegal instruction.
// Only affects pre Haswell archs. Looking at the assembly the compiler
// appears to insert cache line alignment for the instruction
// Inserting an assembly nop instruction changes the alignment and
// works round this.
#ifdef KOKKOS_COMPILER_INTEL
#if (KOKKOS_COMPILER_INTEL < 1800)
      asm volatile("nop\n");
#endif
#endif
      scatter_access_atomic(k, 6) += 2;
      scatter_access_atomic(k, 7)++;
      scatter_access_atomic(k, 8)--;
      --scatter_access_atomic(k, 9);
      ++scatter_access_atomic(k, 10);
      scatter_access(k, 11) -= 3;
    }
```

**Comment by ndellingwood** [comment]
* 09/02/2021 - This just showed up in then nightly sems-intel/17.0.1 nightly build again :(

https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1701_openmp_pthread_serial/83/console

**Comment by crtrott** [comment]
Yeah turns out it wasn't desul. Its just generally a bug with the compiler. So now after we turned desul off instead of adding this workaround its back (sometimes). It literally can change with any commit to Kokkos, since any commit can change the alignment of instructions and thus make the compiler insert buggy alignment.
