### ISSUE TITLE
Layout and Execution space compatibility bug.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#423]
When I simply type
`Kokkos::View<double**,Kokkos::Serial,Kokkos::LayoutLeft> a("a", 3,5)`

I have the following error.

/home/kyukim/Work/lib/trilinos/trunk/packages/kokkos/core/src/Kokkos_View.hpp:163:3: error: static assertion failed: Only one View Execution or Memory Space template argument
   static_assert( std::is_same< typename ViewTraits<void,Prop...>::execution_space , void >::value &&

**Comment by hcedwar** [comment]
You need proper ordering of template arguments:
`Kokkos::View<double**,Kokkos::LayoutLeft,Kokkos::Serial>`

**Comment by kyungjoo-kim** [comment]
Yes. Nathan just told me that order is important.
