### ISSUE TITLE
Hip backend compilation issues with debug plus boundscheck options enabled (rocm/4.2.0 compiler)

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4236]
I encountered compiler errors with rocm/4.2.0 on MI50 while trying to build Kokkos SHA c93ccb46856676872c7c7a7b9b2a0249ae4fb83a with the Hip backend and debug and boundschecking options enabling. The error does not occur when boundschecking is removed. I tested by enabling debugging and boundschecking, as well as adding extra cxx flags I saw in the jenkins file for the debug build and this occurs in both cases.

```
fatal error: error in backend: Error while trying to spill SGPR4_SGPR5 from class SReg_64: Cannot scavenge register without an emergency spill slot!
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

Is this a known issue? A possibly related llvm compiler bug report I came across during search is this https://bugs.llvm.org/show_bug.cgi?id=33031 but that has since been resolved (in 2017); I didn't see anything on the rocm github issue tracker from a brief search

Reproducer:
```
cmake -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_CXX_FLAGS="-g -Wno-unused-command-line-argument -DNDEBUG" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_HIP=ON -DKokkos_ARCH_VEGA906=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=DEBUG -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF
```

**Comment by crtrott** [comment]
@ndellingwood Can we check this with 4.3 on Caraway? We dropped support for 4.2 If it works now on develop close this.

**Comment by ajpowelsnl** [comment]
@ndellingwood -- does this now work with newer versions of rocm (i.e., 4.5 +)?

**Comment by ndellingwood** [comment]
@ajpowelsnl thanks for testing, I also reproduced with MI100 with rocm/4.5 as well

**Comment by Rombur** [comment]
I have a different error on Crusher with rocm 5.1.0 I get: `error: branch size exceeds simm16` That's it, not other message.

**Comment by ajpowelsnl** [comment]
@Rombur , @ndellingwood , @dalg24 -- Is this issue resolved?  If so, may I close it?  If not, should we test with more recent versions of rocm?

**Comment by Rombur** [comment]
It works on Crusher with ROCm 5.2. We need to try on different architectures

**Comment by ajpowelsnl** [comment]
rocm/4.2 no longer supported

**Comment by crtrott** [comment]
Ok closing since 5.2 is the minimum we support anyway
