### ISSUE TITLE
OpenMP TeamPolicy member broadcast not using correct volatile shared variable

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#424]
https://github.com/kokkos/kokkos/blob/master/core/src/OpenMP/Kokkos_OpenMPexec.hpp#L396
 should have volatile

**Comment by hcedwar** [comment]
OpenMP thread team broadcast is not using a shared variable - fix and add necessary memory fence.

**Comment by hcedwar** [comment]
Need to have unit test

**Comment by crtrott** [comment]
Fixed name of issue :-)
