### ISSUE TITLE
Rename CUDA_SAFE_CALL

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#4245]
Generally we complain about non namespaces stuff. But we actually had one really bad unnamespaced thing forever: CUDA_SAFE_CALL (and now HIP_SAFE_CALL). Which is in particular bad since its one of those things floating around in a number of codes. I think we need to rename this to KOKKOS_IMPL_CUDA_SAFE_CALL and KOKKOS_IMPL_HIP_SAFE_CALL, and deprecate the old ones.

**Comment by DavidPoliakoff** [comment]
Yeah, I'm in favor of this

**Comment by mhoemmen** [comment]
`CUDA_SAFE_CALL` comes from NVIDIA's demos ages past -- I agree that it's likely to cause collisions in code bases whose first encounter with CUDA is not through Kokkos.

**Comment by dalg24** [comment]
Did you mean the deprecation part?  I think we should just rename.

**Comment by crtrott** [comment]
I do mean deprecation, because I am not confident that this isn't used in Trilinos and what not.

**Comment by dalg24** [comment]
It is used in Sacado, KokkosKernels, and Ifpack2

**Comment by dalg24** [comment]
But what is our message to them.  Do we really want them to use a `KOKKOS_IMPL_` macro or are we telling them to define their own?

**Comment by crtrott** [comment]
Should we deprecate instead of just remove the old name?
->near unanimous consent, Damien had a weak preference for just removal

Do we want the new name imply this is publicly supported (i.e. use KOKKOS_CUDA_SAFE_CALL, instead of KOKKOS_IMPL_CUDA_SAFE_CALL):
SF F N A SA
0 0 4 8 1

So we gonna KOKKOS_IMPL_CUDA_SAFE_CALL

**Comment by crtrott** [comment]
We decided to make this an internal macro only (which it was always intended for). For example we may change the error message to say explicitly that this is an internal Kokkos runtime error, which may be misleading to users.

**Comment by masterleinad** [comment]
Resolved in #4249.

**Comment by PhilMiller** [comment]
Released in 3.5
