### ISSUE TITLE
Copy constructed HostSharedPtr produces wrong reference count

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#4251]
As reported by @crtrott code such as
```C++
struct F { Exec_t instance; }
F* foo(Exec_t e1, Exec_t e2) {
  F* f_dev = kokkos_malloc<UVM>(sizeof(F));
  F f_host{e1};
   parallel_for(1,KOKKOS_LAMBDA(int i) {
      new (f_dev) F(f_host);
   });
   f_dev.instance=e2;
   return f_dev;
}
```
behaves unintentional since `HostSharedPtr` objects copy constructed on the device don't do reference counting on the device but still on the host, i.e., the assignment in `f_dev.instance=e2` decreases the use count for `f_host` but the construction in `new (f_dev_ F(f_host)` did not increase it.
We decided that copy construction and copy assignment on the device set the control block to `nullptr` to avoid these issues.

**Comment by dalg24** [comment]
How is that assignment `f_dev.instance=e2;` not a memory access violation?

**Comment by dalg24** [comment]
OK I missed the UVM part.
