### ISSUE TITLE
Enhance create_mirror_view to support AllocateWithoutInitializing

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#4259]
We need a way to turn off initialization for `create_mirror_view`. The use case is constructing a large `DualView` that needs to be zero-initalized on device only. The init kernel runs fast on the GPU, but is super slow on the host CPU since it runs in serial, which hurts performance. So we want to only run the initialization on the device view, not on the host view.

**Comment by stanmoore1** [comment]
Once we have a version of `create_mirror_view` that supports `AllocateWithoutInitializing`, we can modify the `DualView` constructor code here to fix the issue I mentioned previously: https://github.com/kokkos/kokkos/blob/master/containers/src/Kokkos_DualView.hpp#L264.

**Comment by crtrott** [comment]
Turns out there is an overload for this: https://github.com/kokkos/kokkos/blob/e4831441fb213bd29485327b02cf1b54149a58a7/core/src/Kokkos_CopyViews.hpp#L3246-L3257

**Comment by crtrott** [comment]
but its weird because it takes the argument at the end. I think we should fix this still that it works like other stuff.

**Comment by stanmoore1** [comment]
That would be great thanks.

**Comment by stanmoore1** [comment]
@DavidPoliakoff can we add this to `DualView` here: https://github.com/kokkos/kokkos/blob/master/containers/src/Kokkos_DualView.hpp#L264?

**Comment by masterleinad** [comment]
Fixed in #4486.

**Comment by stanmoore1** [comment]
Thank you @masterleinad!

**Comment by PhilMiller** [comment]
Fix released in 3.6
