### ISSUE TITLE
Task-DAG capability API

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#426]
We had a lively discussion about the TaskPolicy API which a number of us found confusing in wording (i.e. how the different things are named) as well as in how it fits with the otherwise used understanding of the concepts of "Pattern" and "Policy".

This is how it basically looks now:

``` C++
TaskPolicy<ExecutionSpace> policy(exec_space,mem_space,…)

policy.host_spawn(Functor1,TaskHighPriority,TaskSingle,Dependency);
policy.host_spawn(Functor2,TaskLowPriority,TaskTeam,Dependency);
```

A number of complains were: 
- Policy is not a transient object any more
- The "Pattern" (host_spawn) is owned by the policy
- Arguments which say how to execute the functor are coming in as extra arguments not through the policy (Priority, Dependency, Single, Team)

After a bit of discussion the thought was that "TaskPolicy" is actually the scheduler, and that TaskSingle and TaskTeam are the actual policies. Hence the proposed alternative for the API:

``` C++
TaskScheduler<ExecutionSpace,…> scheduler(exec_space,mem_space,…);

scheduler.host_spawn(TaskSingle<ExecSpace>(HighPriority,Dependency), Functor1);
scheduler.host_spawn(TaskTeam<ExecSpace>(LowPriority,Dependency),Functor2);
```

One could even go one step further and make the scheduler an argument to the policies:

``` C++
TaskScheduler<ExecutionSpace,…> scheduler(exec_space,mem_space,…);

TaskSingle<ExecSpace> policy_single(scheduler,HighPriority,Dependency);
TaskTeam<ExecSpace> policy_team(scheduler,LowPriority,Dependency);

host_spawn(policy_single,Functor1)
host_spawn(policy_team,Functor2)
```

Note that this is still fully in line with the all the semantics and use cases possible of the first variant. It mostly just changes syntax a bit to be more in line with the rest of the philosophy of Kokkos. 

There is another thing here which is worth noting: By splitting scheduler and policy more cleanly you can more straight forward support situations where the scheduler spans more than one execution resource type. On Power with NVLINK and GPUs you for example could have a scheduler which allows in the same task graph to put tasks on both GPU and Power cores. A very good example for that would be communication tasks which certainly would want to run on the host. 

An argument for making the scheduler an argument given to the policy is that this allows certain checks to happen at policy construction. Also I can reuse that policy object then to launch many tasks (for example I have tasks which all depend on some communication to be finished, but are independent of each other).

**Comment by mhoemmen** [comment]
Forking off a bunch of tasks with a single common dependency seems like something people would want to do a lot.  It's like the opposite of MPI_Waitall.  I would like it if policies were independent of schedulers / queues / execution space instances.  If Kokkos had a separate API for launching many tasks with a common dependency, then the implementation of that API could reuse the policy instance, thus saving some overhead.

**Comment by hcedwar** [comment]
In prior documents we have called it a **task manager** because it manages both the scheduling of task execution and lifetime of task memory.

```
TaskManager<Space,...> manager(exec_space,mem_space, ... );
manager.host_spawn( TaskPolicy(TaskSingle,TaskLowPriority,dependence) , Functor );

manager.task_respawn( TaskPolicy(TaskLowPriority,dependence) , this ); // not allowed to change single vs. team
```

**Comment by crtrott** [comment]
I would make TaskSingle and TaskTeam the actual policies, they do indicate very different desired behavior and semantics. In one you got parallelism in the task in the other you don't. In that way its not really like a small modifier to what you do, but allows completely different algorithms.

**Comment by hcedwar** [comment]
Inclined toward the following API:

```
scheduler.task_spawn( TaskTeam , functor ); // or host_spawn, or TaskSingle
scheduler.task_spawn( TaskTeam( dependence , priority ) , functor );
scheduler.respawn( TaskRespawn( dependence , priority ) , this );
```

**Comment by crtrott** [comment]
I am still thinking making the scheduler an argument to the policy( TaskTeam, TaskRespawn) would be more inline with what we do in the rest of Kokkos with respect to our plans on having execution space instances. 

```
parallel_for( RangePolicy(space, 0, N), functor ); 
task_spawn( TaskTeam(scheduler, dependence, priority), functor);
```

The equivalent of having the operation being a member of the scheduler would be this:
```
space.parallel_for( RangePolicy(0,N), functor );
scheduler.task_spawn( TaskTeam( dependence, priority ), functor );
```

The first one really appeals to me since we would stay perfectly within the patterns we have established.

**Comment by hcedwar** [comment]
```
task_spawn( TaskTeam( scheduler , priority ) , functor );
task_spawn( TaskTeam( dependence , priority ) , functor );
```

The `task_spawn` is `host_spawn` when calling from a host control thread.
The `TaskTeam` can also be `TaskSingle`.
The `priority` defaults to `TaskPriority::Regular`, options are `High` or `Low` priority.

```
respawn( this , scheduler , priority );
respawn( this , dependence , priority );
```

Respawn is a different thing.  The original policy `{ Team | Single }` cannot be changed and a functor is not created.  Only the dependence and priority may be updated.

**Comment by crtrott** [comment]
Looks good to me now. I assume your second task_spawn example uses some kind of default scheduler, or does it deduct the scheduler from the dependence?
