### ISSUE TITLE
Subview bug with 0xN DualView

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#4262]
From a comment in Tpetra:

```
// mfh 14 Apr 2015: Work-around for bug in Kokkos::subview, where
// taking a subview of a 0 x N DualView incorrectly always results
// in a 0 x 0 DualView.

```

Can we check to see if that is still a problem?

**Comment by ajpowelsnl** [comment]
Hi @csiefer2 , @crtrott -- Do we have a path forward on this issue?  If so, what's the next step?  If not, shall we discuss it during tomorrow's meeting?
