### ISSUE TITLE
Allow using external gtest

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#4263]
As part of the discussion in #4230, we also considered dropping the bundled gtest version and allowing linking to an external one.

**Comment by ajpowelsnl** [comment]
Meeting discussion:

4230:

    use external version, pr is a step in the right direction (Damien)
    API breakage between versions -> need exact version (Nic Morales)
    no cmake fetch content, there are machines without access (Damien)
    we update, open issue for external gtest

**Comment by masterleinad** [comment]
Fixed in #4563.
