### ISSUE TITLE
Incorrect constexpr usage when GCC<10 and -frounding-math enabled

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#4267]
See https://github.com/trilinos/Trilinos/issues/9056

I think this is something we have to fix, and I think the right fix is to remove constexpr from those computations.

I think the resolution should be to remove the constexpr, possibly with a comment that constexpr can be re-added when we drop support for the GCC that fails this case.

**Comment by ajpowelsnl** [comment]
@DavidPoliakoff , @crtrott -- It sounds like we need to handle this before our next release ...

**Comment by crtrott** [comment]
There is no vote needed this just needs fixing.
