### ISSUE TITLE
gpucc CUDA compiler

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#427]
Hi!
Any chance of using the [gpucc](http://llvm.org/docs/CompileCudaWithLLVM.html), open-source CUDA compiler integrated in LLVM, in the future?
Best regards

**Comment by mhoemmen** [comment]
@j8asic Would you consider testing this yourself, by modifying the nvcc_wrapper script appropriately?

**Comment by j8asic** [comment]
Sure, I am going to try it.

**Comment by crtrott** [comment]
I am occasionally testing it and reporting bugs. We are pretty close to have it working, and are definitely trying to get there.

**Comment by crtrott** [comment]
We have an issue open for this: #455
