### ISSUE TITLE
Add simple profiling class that pushes region on constructor and pops on destructor

### ISSUE THREAD

**Issue by maxpkatz** [kokkos/kokkos#4275]
To take advantage of the profiling hooks a programmer might write today
```
Kokkos::profiling::pushRegion("region_name");
...
Kokkos::profiling::popRegion();
```

An alternative model might be a one-line construct, like
```
Kokkos::profiling::profiler p("region_name");
```
This would be a simple class whose constructor calls `pushRegion` and whose destructor calls `popRegion`. Aside from saving overhead on typing, a limitation with the first model is that it gets tricky in functions with multiple returns, since you'd have to call `popRegion` just before every return. With the pop-on-destruction method there is no additional effort required for this case, we will automatically get a pop when the object goes out of scope.

**Comment by dalg24** [comment]
Essentially, proposing a scope guard to profile a region.  That is fine by me, although I would suggest to pick some other name, such as `ScopedRegionProfiler` or alike.

**Comment by maxpkatz** [comment]
Sounds good. I volunteer myself to contribute this.

**Comment by ajpowelsnl** [comment]
Hi @maxpkatz - I'll add this to our items to discuss at tomorrow's meeting.  Should this issue be up for a vote?  Just out of curiosity, would this change represent an improvement upon existing capability, or is it substantially new?

**Comment by maxpkatz** [comment]
I would characterize it as the former, it's just a convenience layer on top of the real functionality provided by `Kokkos::profiling::{push,pop}Region()`.

**Comment by ajpowelsnl** [comment]
@maxpkatz - cool.  I'll put it on our list of items to discuss

**Comment by mhoemmen** [comment]
[Tpetra has one](https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/core/src/Tpetra_Details_Profiling.hpp) and a bunch of documentation y'all could borrow -- I didn't put that TimeMonitor bit in there, though (implementation hiding would be nicer).

**Comment by maxpkatz** [comment]
Thanks @mhoemmen that looks pretty similar to what I had in mind.

**Comment by mhoemmen** [comment]
@maxpkatz Hope it's helpful! : - )  Please do consider hiding the implementation in a .cpp file and including as few headers as possible in the header file.  Thanks!

**Comment by nliber** [comment]
Question:  should we give it a `popRegion` member function (and a `bool` to keep track of whether or not it is called).

What that allows is for `popRegion` to be guaranteed to be called if it goes out of scope, but allows someone to call it early.  (This is somewhat analogous to `std::lock_guard` vs `std::unique_lock`).  I wouldn't opt for any more functionality than that.

Note:  The Tpetra one is moveable and copyable, and it should not be.

**Comment by nliber** [comment]
I'm thinking something like:

.hpp:

```
class ProfilingRegion {
public:
    explicit ProfilingRegion(const std::string& name);
    ~ProfilingRegion();

    ProfilingRegion(const ProfilingRegion&) = delete;
    ProfilingRegion(ProfilingRegion&&) = delete;
    ProfilingRegion& operator=(const ProfilingRegion&) = delete;
    ProfilingRegion& operator=(ProfilingRegion&&) = delete;

    void popRegion();

private:
    bool m_active_region = true;
};

```
.cpp:

```
ProfilingRegion::ProfilingRegion(const std::string& kName) { Kokkos::Tools::pushRegion(kName); }

ProfilingRegion::popRegion() {
    if (m_active_region) {
        Kokkos::Tools::popRegion();
        m_active_region = false;
    } else {
        Kokkos::abort("Kokkos::ProfilingRegion::popRegion() called multiple times");
    }
}

ProfilingRegion::~ProfilingRegion() {
    if (m_active_region) {
        Kokkos::Tools::PopRegion();
    }
}
```

**Comment by maxpkatz** [comment]
@nliber I have no objection. But I am curious what the use case is you have in mind for needing to be able to pop early (since in that case it's not any less code than just doing the explicit push and pop)?

**Comment by nliber** [comment]
Yes, my argument is that it is a safer construct.  I would rather teach folks to always use `ProfilingRegion` because it is safer.  Okay, I will anyway, but this gets rid of one of the easy objections to doing so.

**Comment by mhoemmen** [comment]
@nliber wrote:
> The Tpetra one is copyable, and it should neither be copyable nor moveable.

Yes, please listen to Nevin on this one.  It did not occur to me at the time to prevent people from copying a scope guard.

SOME PEOPLE (**ahem**) (@csiefer2 knows some of them) will do even more unnatural things to your scope guard class, like passing it around by (the Trilinos equivalent of) `shared_ptr`, and assigning the result of `make_shared` to an existing pointer.  They then complain when the resulting regions overlap.  I'm not sure how to prevent that, other than something like this:

```c++
namespace Teuchos {
template<class T>
class RCP {
  static_assert( ! std::is_same_v<T, ProfilingRegion>, "NO, BAD PROGRAMMER" );
  // ... the rest of RCP, which Trilinos developers will use until the end of time
  // instead of std::shared_ptr, for no good technical or programmatic reason ...
};
}
```

**Comment by nliber** [comment]
After sleeping on it, I'm now leaning against adding a `.popRegion()` method.

Here is the problem case:

```
ProfilingRegion r1("r1");
// ...
ProfilingRegion r2("r2");
//. ...
r1.popRegion();  // silent error; this pops r2
```

It looks likes it should pop `r1`, but it really pops the last region pushed, which in the above example is `r2`.

While there is nothing we can do about folks who mix `pushRegion`/`popRegion` and `ProfilingRegion` in the same function, we should not make it easy to misuse for folks who just use either one or the other.

**Comment by mhoemmen** [comment]
@nliber Is there a way to `=delete` the unary `&` and `*` operators for `ProfilingRegion`, so that users can't pass it by pointer?  [In an experiment](https://godbolt.org/z/KW7d13bqa), I was able to forbid taking the address of a class, but not to forbid handling it by `shared_ptr`.

**Comment by nliber** [comment]
@mhoemmen in general there is no way to prevent that.

Fundamentally, anything that uses `new` (placement `new` or heap allocated `new`) under the covers is opting in to managing the lifetime so that it need not obey a scope.  There are a plethora of standard library types (let alone user defined types) which do that:  shared_ptr, unique_ptr, all the containers, the "sum" types (any/optional/variant), etc., so storing the guard in any of these things can lead to bugs.

I wish there was a better answer than telling people to only use guards as local variables.

The other problem with guards is that people forget the variable (since they never need to refer to it), and if you write `ProfilingRegion("foo");` it really won't do what you want it to do.  (Macros are the usual solution around this problem.)

**Comment by maxpkatz** [comment]
I think there is another reason to prefer macros here too, which is that if you do have multiple regions in the same function then it gets mildly annoying to have to explicitly name them all uniquely, so you can have a macro that automatically appends `__COUNTER__` to each invocation. So I was going to advocate adding such a macro if this is done.

**Comment by mhoemmen** [comment]
@maxpkatz One could use a scope guard class _and_ macros, and let users decide.  I've used the scope guard class `ProfilingRegion` a lot in practice.  It was nice to be able to pick my own names that summarize what the region is doing.  Perhaps some people don't want to be bothered, which is OK, but one could get automatic names without macros too.  [Here is an example.](https://godbolt.org/z/v8ahfYTGf)

```c++
#include <iostream>
#include <memory>
#include <string>
#include <string_view>

class ProfilingRegion {
private:
  class AutomaticNameTag {};
  static size_t counter;
  std::string stringLabel_;

public:
  static constexpr AutomaticNameTag autoName {};

  // Automatically named region
  ProfilingRegion(AutomaticNameTag /* tag */) :
    ProfilingRegion(std::string("Region ") + std::to_string(counter))
  {
      ++counter;
  }

  // Explicitly named region
  ProfilingRegion(const std::string_view stringLabel) : stringLabel_(stringLabel)
  {
      std::cout << "Start region \"" << stringLabel << "\"\n";
  }

  ~ProfilingRegion() {
      std::cout << "Stop region \"" << stringLabel_ << "\"\n";
  }
  // ... forbid copying and moving ...
};

size_t ProfilingRegion::counter = 0;

#define PROFILING_REGION ProfilingRegion __r(ProfilingRegion::autoName)

int main()
{
    { // Users can name regions explicitly.
        ProfilingRegion r("Named region");
    }
    { // Users can use either C++ code or the macro to create an automatically named region.
        ProfilingRegion r0(ProfilingRegion::autoName);
        for(int i = 0; i < 3; ++i) {
            PROFILING_REGION;
        }
    }
    return 0;
}
```

**Comment by mhoemmen** [comment]
@nliber wrote:
> ... in general there is no way to prevent that.

Alas : - (

**Comment by crtrott** [comment]
Voting on this:

We want the simple version:
```
RegionScopeGuard prof("Name");
```
unanimous consent

We want macros with (partially) autogenerated names?
The team  thinks this is not an accute problem and some folks think its bad to add Macros to the profiling interface.


So @maxpkatz if you just want to open a PR that would be fine, we can help finish it up.
