### ISSUE TITLE
Kokkos sorting algorithms

### ISSUE THREAD

**Issue by whart222** [kokkos/kokkos#4279]
Hi, all:

I'm working with the ExaFEL team using kokkos for their compute kernel, and we noted the sorting algorithm here:

  algorithms/src/Kokkos_Sort.hpp

Is this being actively maintained?  Is there interest in expanding this capability?

We need to perform a distributed sort of a list of lists, where each list in the list is independently sorted.  That seems similar to this kernel, but different enough that we'd need a different method.

**Comment by ajpowelsnl** [comment]
@whart222 -- Hello!  Many thanks for your question.  Do you attend our Kokkos Developer Meeting on Wednesdays at noon (Mountain time zone)? I can put it on our weekly list of items to discuss, in any case, but please feel free to attend.

**Comment by nliber** [comment]
Could you post a sample of what the data structure you want to sort would look like and how you envision what the call to a sort algorithm would look like?

**Comment by crtrott** [comment]
Yes this is maintained. The current sort is good at reasonable homogenous distributions, but falls over performance wise if you have non-homogenous distributions. We need both a set of different sorting methods, and interfaces for stuff like sorting within a Team (which would probably cover your use case, where you would assign a team to each sublist).

With actual user requests we can certainly try and put this higher on our priority list.

**Comment by ajpowelsnl** [comment]
> Could you post a sample of what the data structure you want to sort would look like and how you envision what the call to a sort algorithm would look like?

@whart222 -- Would you please provide us an example of the data structure you'd like new sorting capabilities for?

**Comment by whart222** [comment]
I'm going to close this issue.  I think the solution may not actually require sorting.  I'll schedule an offline discussion about this.
