### ISSUE TITLE
Scratch space for RangePolicy

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#428]
Example use case: complicated user-specified material model for which only runtime sizing of temporary work space is possible.

Discussed with @dsunder . Discussed at Kokkos Review.

**Comment by mhoemmen** [comment]
Is this starting to cross into task territory?

**Comment by mhoemmen** [comment]
Another use case: tiny dense LU factorizations, one per loop iteration.  Need workspace array proportional to each block's dimension.  Only need workspace for active loop iterations, not for total number of iterations.

**Comment by crtrott** [comment]
This would require thing a different member type, not sure how to do that in a sane way. Got to think about it.

**Comment by mhoemmen** [comment]
Could hash from loop index into scratch array, and atomically grab a chunk of scratch.  Might want to overprovision scratch chunks to reduce contention for tighter loops, though.

**Comment by hcedwar** [comment]
Blocker: complete execution instances #457 first

**Comment by hcedwar** [comment]
This may be doable by embedding the MemoryPool in the functor and allocating/deallocating.

**Comment by hcedwar** [comment]
@ambrad : Still need this?

One option is the now robust & scalable MemoryPool, which is in develop.  You can include a MemoryPool member in your functor and then `allocate` and `deallocate` with reasonable performance.

Another option is to pre-allocate workspace and use the new UniqueToken, which is experimental in develop.  The UniqueToken issues within any parallel operation including range policies a unique integer [0..P) where P is the maximum possible concurrency of the execution space.  The UniqueToken will tell you at construction the value of P to use for your pre-allocated workspace.

**Comment by ambrad** [comment]
UniqueToken will work; thanks. Probably will be useful for other things, too.

**Comment by mhoemmen** [comment]
We want it too! :-D  @hcedwar which option would you recommend, for the case where all threads would need about the same amount of storage?  Sounds like UniqueToken but just want to make sure.

**Comment by crtrott** [comment]
Unique token is most likely much faster than memory pool for this purpose (by about an order of magnitude maybe more than that). The reason is that you don't have to do a memory tracking thing under neath as you need to do a for a memory pool which can free and delete. On the other hand with a memory pool you don't need to know in advance how much memory each thread wants, you just need to know an overall total.

**Comment by mhoemmen** [comment]
For the new UniqueToken feature, see issue #818 and PR #921.

**Comment by mhoemmen** [comment]
For the new UniqueToken feature, see issue #818 and PR #921.

**Comment by ibaned** [comment]
It sounds like the answer was "use UniqueToken". Please comment if there is more to this.
