### ISSUE TITLE
Cuda heuristic change for blocksize breaking some Kokkos Kernels tests - cuda/10 builds

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4283]
A cross-reference to the kokkos-kernels issue: kokkos/kokkos-kernels#1089

**Comment by crtrott** [comment]
Its likely a kokkos kernels issue, since Kokkos never guaranteed a specific block size. This could for example be a missing team fence.

**Comment by ndellingwood** [comment]
Missing fences in the kokkos-kernels test were the culprit like Christian said, removing the "Bug" label and closing issue
