### ISSUE TITLE
Derive default_arch from the -DKokkos_ARCH_VOLTA70 setting

### ISSUE THREAD

**Issue by cponder** [kokkos/kokkos#4288]
Given that the ```cmake``` already supports these settings
```
Kokkos_ARCH_KEPLER30=ON
Kokkos_ARCH_KEPLER32=ON
Kokkos_ARCH_KEPLER35=ON
Kokkos_ARCH_KEPLER37=ON
Kokkos_ARCH_MAXWELL50=ON
Kokkos_ARCH_MAXWELL52=ON
Kokkos_ARCH_MAXWELL53=ON
Kokkos_ARCH_PASCAL60=ON
Kokkos_ARCH_PASCAL61=ON
Kokkos_ARCH_VOLTA70=ON
Kokkos_ARCH_VOLTA72=ON
Kokkos_ARCH_TURING75=ON
Kokkos_ARCH_AMPERE80=ON
Kokkos_ARCH_AMPERE86=ON
Kokkos_ARCH_VEGA906=ON
```
Can't these be made to set the ```default_arch``` variable for ```bin/nvcc_wrapper```, instead of us having to remember to make the corresponding changes in both places?
There's also this issue suggesting a variable to override the ```default_arch``` value
      https://github.com/kokkos/kokkos/issues/3667
this variable could be set in the ```cmake```.

**Comment by cponder** [comment]
One step in the right direction would be to change this line in ```bin/nvcc_wrapper```
```
     15     default_arch="sm_70"
```
to
```
     15     default_arch:-"sm_70"
```
so it will not override an outside setting of the ```default_arch``` variable.

**Comment by masterleinad** [comment]
> Can't these be made to set the `default_arch` variable for `bin/nvcc_wrapper`, instead of us having to remember to make the corresponding changes in both places?

What is your use case that requires using the default architecture flag? If the target links with `Kokkos` the correct flag should be used automatically. Do you have other source files that don't link with Kokkos and use raw Cuda?

**Comment by cponder** [comment]
The ```bin/nvcc_wrapper``` has this as a hard setting, right?
```
15     default_arch="sm_36"
```
So my use-case would be any system not running such a backlevel GPU.

**Comment by cponder** [comment]
So you mean, if I use an explicit ``` -DKokkos_ARCH_VOLTA70``` flag, then the ```default_arch``` doesn't get used?

**Comment by masterleinad** [comment]
> So you mean, if I use an explicit -DKokkos_ARCH_VOLTA70 flag, then the default_arch doesn't get used?

Yes, `Kokkos` should add the flag `-arch=sm_70` to the flags exported and used. This should override `default_arch` in `nvcc_wrapper`, see https://github.com/kokkos/kokkos/blob/e4831441fb213bd29485327b02cf1b54149a58a7/bin/nvcc_wrapper#L479-L482 and https://github.com/kokkos/kokkos/blob/e4831441fb213bd29485327b02cf1b54149a58a7/bin/nvcc_wrapper#L356-L368.

**Comment by cponder** [comment]
You mean I put this in my script?
```
export CMAKE_CXX_FLAGS="-arch=sm_70"
```

**Comment by masterleinad** [comment]
If you use `nvcc_wrapper` for compiling anything that doesn't link with `Kokkos`, yes. Everything that links with `Kokkos` (using `CMake`, i.e., `target_link_libraries(target Kokkos::kokkos)`) should have this flag automatically.

**Comment by cponder** [comment]
I'm not invoking the wrapper. I'm just building Kokkos using
```

```
I'm getting a lot of these errors
```
pgc++-Error-Switch -tp with unknown keyword core-avx2
-tp=px|bulldozer|piledriver|zen|zen2|sandybridge|haswell|knl|skylake|host|native
                    Select target processor
    px              Generic x86 Processor
    bulldozer       AMD Bulldozer processor
    piledriver      AMD Piledriver processor
    zen             AMD Zen architecture (Epyc, Ryzen)
    zen2            AMD Zen 2 architecture (Ryzen 2)
    sandybridge     Intel SandyBridge processor
    haswell         Intel Haswell processor
    knl             Intel Knights Landing processor
    skylake         Intel Skylake Xeon processor
    host            Link native version of HPC SDK cpu math library
    native          Alias for -tp host
core/src/CMakeFiles/kokkoscore.dir/build.make:94: recipe for target 'core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o' failed
make[2]: [core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o] Error 1 (ignored)

**Comment by cponder** [comment]
It looks like it's following the gnu/intel convention to specify the architecture.
Setting this turns them into warnings
```
-D CMAKE_CXX_FLAGS="-noswitcherror"
```
but that's not the same thing as setting it correctly.

**Comment by masterleinad** [comment]
Were the last two comments supposed to be for https://github.com/kokkos/kokkos/issues/4290?

**Comment by cponder** [comment]
Ok nevermind -- this problem had been that I was trying to build the Kokkos with ```bin/nvcc_wrapper```, which is a moot point. I'll go ahead and close this one.
