### ISSUE TITLE
Nightly test failure: serial.atomics on Power9, xl/16.1.1

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4289]
The following test is failing on Power9 arch with xl/16.1.1. @crtrott this is likely related to the desul update? I added some xl jobs to weaver which picked this up now that there is more testing bandwidth for these nightlies.

```
21:56:59 1: [ RUN      ] serial.atomics
21:56:59 1: Loop<N10TestAtomic11SuperScalarILi4EEE>( test = 1 FAILED : { 100, 200, 300, 400} != { 100, 100, 150, 200}
21:56:59 1: /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_xl_1611_serial/kokkos/core/unit_test/TestAtomics.hpp:560: Failure
21:56:59 1: Value of: (TestAtomic::Loop<TestAtomic::SuperScalar<4>, TEST_EXECSPACE>(100, 1))
21:56:59 1:   Actual: false
21:56:59 1: Expected: true
21:56:59 1: [  FAILED  ] serial.atomics (28 ms)
```

Reproducer
```
module load cmake/3.19.3 ibm/xl/16.1.1 gcc/7.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=Power9,Volta70 --compiler=xlC --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -qxflag=disable__cplusplusOverride" --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

**Comment by crtrott** [comment]
Looks like the Serial backend is missing a memory fence in its fence. I.e. the relaxed atomics we did (even for large atomics) truly did have relaxed semantics, but because the execution_space.fence() wasn't actually fencing memory ops the relaxed atomics in the kernel were not immediately visible outside.

**Comment by crtrott** [comment]
Should be fixed.

**Comment by ajpowelsnl** [comment]
@crtrott , @ndellingwood -- Is this bug now fixed?

**Comment by ndellingwood** [comment]
@ajpowelsnl the test is passing now, I'll add InDevelop while I'm here updating the issue
