### ISSUE TITLE
cmake detection flips from nvcc_wrapper/pgc++ to gcc

### ISSUE THREAD

**Issue by cponder** [kokkos/kokkos#4290]
I'm trying to build Kokkos  3.4.01 using these settings
```
-D CMAKE_CXX_COMPILER=$PWD/distro/bin/nvcc_wrapper
-D NVCC_WRAPPER_DEFAULT_COMPILER=pgc++
```
and notice that the compiler detection is looking at the native ```gcc``` instead of the ```nvcc_wrapper``` or ```pgc++``` compiler:
```
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is GNU 4.8.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /glade/work/cponder/Applications/Kokkos/3.4.01/PGI-21.7_CUDA-11.4/distro/bin/nvcc_wrapper - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```
I see that it's by-passing the ```bin/nvcc_wrapper```, but (this being CentOS 7) the default ```gcc``` compiler is (a) junk, and (b) not used in this compilation to begin with. And it's causing the breakage in the build:
```
-- Using -std=c++1y for C++14 standard as feature
CMake Error at cmake/kokkos_test_cxx_std.cmake:34 (MESSAGE):
  CMake wants to use -std=c++1y which is not supported by NVCC.  Using a more
  recent host compiler or a more recent CMake version might help.
Call Stack (most recent call first):
  cmake/kokkos_test_cxx_std.cmake:72 (kokkos_set_cxx_standard_feature)
  cmake/kokkos_tribits.cmake:231 (INCLUDE)
  CMakeLists.txt:170 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```
The failure doesn't happen on Ubuntu 20.04, where the native ```gcc``` is version 7.5.0 and gives a workable resolution:
```
-- Using -std=c++14 for C++14 standard as feature
```
The real problem, though is that if it's going to bypass the ```bin/nvcc_wrapper``` this way, it should fall-through to the ```NVCC_WRAPPER_DEFAULT_COMPILER``` not the system default compiler, right?

**Comment by masterleinad** [comment]
`NVCC_WRAPPER_DEFAULT_COMPILER` should be an environment variable, not a `CMake` variable.
Also, you should get the desired behavior by just setting 
```
-D CMAKE_CXX_COMPILER=pgc++
-D Kokkos_ENABLE_CUDA=ON
```
This will use `nvcc_wrapper` for all `Kokkos` files (and everything that links with `Kokkos`) and `pgc++` as host compiler.

**Comment by cponder** [comment]
Ok, I think I get it. The ```bin/nvcc_wrapper``` is for building an app with Kokkos, not for building the Kokkos itself.
I'll go ahead and close this then.

**Comment by masterleinad** [comment]
> Ok, I think I get it. The bin/nvcc_wrapper is for building an app with Kokkos, not for building the Kokkos itself.

That's not true. You can build `Kokkos` with `nvcc_wrapper` (and in fact that is happening under the hood whenever you request `CUDA` support and don't set `CMAKE_CXX_COMPILER` to something that can compile `CUDA` code).

**Comment by cponder** [comment]
I didn't think you could put raw CUDA code (chevron notation ```<<< >>>``` through any compiler except ```nvcc```.
So in those cases, the Kpkkos builder will switch over to using ```nvcc``` with the ```CMAKE_CXX_COMPILER``` being used as the ``` NVCC_WRAPPER_DEFAULT_COMPILER```?

**Comment by masterleinad** [comment]
> I didn't think you could put raw CUDA code (chevron notation <<< >>> through any compiler except nvcc.

`clang` should also support launching kernels using this syntax.

>  So in those cases, the Kokkos builder will switch over to using `nvcc` with the `CMAKE_CXX_COMPILER` being used as the ` NVCC_WRAPPER_DEFAULT_COMPILER`?

Yes.
