### ISSUE TITLE
Add name of view to "View bounds error"

### ISSUE THREAD

**Issue by stanmoore** [kokkos/kokkos#432]
"View bounds error" would be much more helpful if it included the name of the view.

**Comment by hcedwar** [comment]
May not currently be able to query label from a subview.

**Comment by crtrott** [comment]
Now it prints again name, indicies and dimensions.

**Comment by stanmoore1** [comment]
I tried this but I still don't get a name in the output, and should the "<" be a ">":
<pre>
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
  what():  View bounds error of view  ( 15616 < 0 )
Traceback functionality not available
</pre>

**Comment by stanmoore1** [comment]
I suppose the view isn't initialized so it doesn't have a name, that makes sense.
