### ISSUE TITLE
Would like a new domain on slack

### ISSUE THREAD

**Issue by aminiussi** [kokkos/kokkos#4336]
Hello,

I would like to create an account on the Kokkos slack, but my email domain does not appears on the account creation  page. 
It is indicated to contact the Kokkos administration but the page does not indicate how to contact that administrator.
Is it possible to add a domain and if yes how should I proceed ?

Thanks

**Comment by masterleinad** [comment]
What's your e-mail address?

**Comment by aminiussi** [comment]
alain.miniussi@oca.eu
