### ISSUE TITLE
view_alloc (label, ...) gets confused if label is a char* instead of an std::string

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#434]
If I use `view_alloc(label, ...)` with `label` a `const char*` instead of an `std::string`, I get build errors like this:

.../Trilinos/packages/kokkos/core/src/Kokkos_View.hpp:1272:7: error: static assertion failed: Constructing View to wrap user memory must supply matching pointer type

**Comment by crtrott** [comment]
Ah that is nasty ... 

I let Carter deal with it ;-)

**Comment by mhoemmen** [comment]
> Ah that is nasty ...

Not sure if you _can_ even fix this, if view_alloc has an option to take a pointer as its first argument. What do you do if you want a `View<char*, ...>`?

**Comment by mhoemmen** [comment]
Anyway, this is no big deal for me, so don't worry ;-)

**Comment by crtrott** [comment]
That View<char*> thing is why I thought this was nasty. I don't have a good idea right now how to distinguish, other than just categorically saying that view_alloc requires you to give a label as a std::string.

**Comment by hcedwar** [comment]
The label can be either an in-place string `"label"` or a std::string.  Passing a `char *` or other pointer is assumed to be a pointer to user supplied memory.
