### ISSUE TITLE
Provide tests for WithoutInitiailizing

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#4342]
Blocked by #4331.

https://github.com/kokkos/kokkos/pull/4337 adds a `WithoutInitializing` option to some more functions. This feature is difficult to test for correct behavior and basically requires support from `Kokkos Tools`.
Infrastructure for this is contained in #4331.

**Comment by ajpowelsnl** [comment]
@masterleinad -- Thanks for submitting this issue.  Is it easy to articulate why the feature is difficult to test for correctness?  If so, what are the reasons : )

If not, then I'll put it on our "items to discuss" list.

**Comment by masterleinad** [comment]
It's difficult because we need to check that an object is not initialized. The only reliable way for that is to monitor the kernels that were invoked.

**Comment by ajpowelsnl** [comment]
Morning @masterleinad and @DavidPoliakoff -- can you guys take a stab at this issue?   Please let me know if you have any questions, and have a great day!

**Comment by masterleinad** [comment]
@ajpowelsnl You have surely seen that neither #4331 nor #4337 has been merged yet.

**Comment by ajpowelsnl** [comment]
@masterleinad -- oh my.  And you would be correct on those points : )
Apologies, we just triaged the issues on Monday, and I was out on Friday.

**Comment by PhilMiller** [comment]
Fix released in 3.6
