### ISSUE TITLE
nvcc_wrapper doesn't handle "-Xptxas option" and mixed arch options correctly

### ISSUE THREAD

**Issue by pwang234** [kokkos/kokkos#4350]
The current nvcc_wrapper assumed "-Xptxas=options" (https://github.com/kokkos/kokkos/blob/master/bin/nvcc_wrapper#L225). But "-Xptxas options" is also accepted by nvcc. This would lead to error:

nvcc_wrapper -arch=sm_70 -Xptxas=-v vecAdd.cu // this works
nvcc_wrapper -arch=sm_70 -Xptxas -v vecAdd.cu // this breaks due to messed up cuda flags
gcc: error: g++: No such file or directory

Furthermore, nvcc works fine if "-arch=sm_70 -gencode arch=compute_70,code=sm_70" is passed as options. But nvcc_wrapper doesn't handle this mixed case correctly:

nvcc_wrapper -arch=sm_70 -gencode arch=compute_70,code=sm_70 vecAdd.cu 

g++: error: arch=compute_70: No such file or directory
g++: error: code=sm_70: No such file or directory

**Comment by ajpowelsnl** [comment]
Item for Wed. Dev. Meeting discussion
