### ISSUE TITLE
Disable allocating in UVMSpace by default warning

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#4357]
I'd like a way to specifically disable (or just remove) the warning:
```
Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_LAUNCH_BLOCKING=1.
                                  The code must call Cuda().fence() after each kernel
                                  or will likely crash when accessing data on the host.)warning"
```
For one thing it no longer seems to be true on Volta, you get a race condition but don't immediately crash anymore. My bigger issue with it is that the warning is only useful for application developers, but appears to application users which causes a few problems:

1. It confuses users into thinking they are doing something wrong even when we want them to be running without CUDA_LAUNCH_BLOCKING, and if they follow the suggestion to set CUDA_LAUNCH_BLOCKING=1 to silence the warning they get worse performance with no benefit.
2. If using many MPI ranks (or even worse many ranks with multiple streams per rank) it outputs a nRanks*nStreams times which makes it harder to find actual application warnings/errors.

I know there is the command line option/env var that disables all warnings from Kokkos, but I don't want to condition users to use that because there are other warnings that are useful to users to see (for example the OpenMP ones about thread binding settings & over-subscription) and that they could take action on.

@crtrott @DavidPoliakoff

**Comment by dalg24** [comment]
Pass `--kokkos-disable-warnings` to your executable.
If you are using `Kokkos::InitArguments` there is a `disable_warnings` member.

**Comment by vbrunini** [comment]
The last sentence of the issue is literally why I don't view that as a solution.

**Comment by ajpowelsnl** [comment]
@vbrunini , @dalg24 , @DavidPoliakoff -- Shall I I go into Kokkos and remove this error?

**Comment by ajpowelsnl** [comment]
Item for Wed. Dev. Meeting discussion

**Comment by crtrott** [comment]
We (Evan) will investigate who still needs this.

**Comment by ajpowelsnl** [comment]
Morning @e10harvey -- do you have an idea yet of which release you've got this work staged for?  3.6?  3.7?  In any case, could you provide a guesstimate for completion of this work?

**Comment by e10harvey** [comment]
> Morning @e10harvey -- do you have an idea yet of which release you've got this work staged for? 3.6? 3.7? In any case, could you provide a guesstimate for completion of this work? For now, I've stubbed in that it will be in Release 3.6, but we can always change that. I just want to get us in the habit of providing an estimate for when we'll deliver work we commit to.

Good morning. This will be for 3.6. I estimate having this done by 11/1.

**Comment by ajpowelsnl** [comment]
Morning @e10harvey -- Excellent work on this issue.  Would you like to discuss your proposed solution (and updates to the 3.5 release notes) in the Wed. Developer meeting, just to make sure that deleting the error does not ruffle anyone's feathers?  It sounds like this error is associated with Cuda 7.0 SDK, which is not something that we have supported recently.  Is there a good reason to support Cuda 7.0 SDK in Debug builds?  Presumably , our Kokkos releases track with a certain range of Cuda SDK versions.  Are we obliged to support versions outside of those ranges?
