### ISSUE TITLE
UnorderedMap::erase() is not thread safe

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#4363]
I'm not sure what the intended usage case is for erase() since there is no documentation for it. Consider this:
```c++
int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  using Map = Kokkos::UnorderedMap<int, int>;
  Map m(10);
  std::cout << "m insertable? " << Map::is_insertable_map << "\n";
  Kokkos::parallel_for(1, KOKKOS_LAMBDA(const int i) {
    m.insert(1, 1234);
  });

  Kokkos::DualView<int*> v("v", 10);
  Kokkos::deep_copy(v.d_view, -1);
  Kokkos::fence();

  const bool canErase = m.begin_erase();
  if(!canErase) { Kokkos::abort("Can't begin erase"); }
  std::cout << "m is erasable? " << m.erasable() << "\n";
  Kokkos::parallel_for(v.span(), KOKKOS_LAMBDA(const int i) {
    const auto r = m.find(1);
    v.d_view(i) = m.erase(1);
  });
  Kokkos::fence();
  m.end_erase();
  syncToHost(v);
  for(int i = 0; i < v.extent(0); ++i) {
    std::cout << v.h_view(i) << "\n";
  }
  
  } Kokkos::finalize();
}
```
My expectation is that one and only one thread should succeed with the `erase()`. But the code shows that multiple threads can succeed in the `erase()` call. Because `erase()` calls `find()`, this implies one thread can result in a successful `find()` after that element has been `erase()` by another thread.

**Comment by ajpowelsnl** [comment]
Item for Wed. Dev. Meeting discussion

**Comment by mhoemmen** [comment]
I was under the impression that UnorderedMap only permits erases during an "erase phase" that does not include inserts.  @dsunder would know more, assuming the design hasn't changed since then.

**Comment by Char-Aznable** [comment]
insert() is indeed blocked in a erase phase but `find()` and `value_at()` modification are still allowed, as the example demonstrated, which can run into racing condition with `erase()`. As far as I can tell from the code, the design of UnorderedMap value access is not linearizable with the concurrent I/O.

**Comment by ajpowelsnl** [comment]
@crtrott -- Please weigh in!

**Comment by Char-Aznable** [comment]
I think it might be possible to wrap the operations under `insert()`, `erase()` and `find()` into atomic functor so that one can use the generic atomic functions to make it possible to call `insert()`, `erase()` and `find()` concurrently

**Comment by crtrott** [comment]
@Char-Aznable to close this out: yeah you are right, the current design does not allow for safe value_at() and erase() intermixing. Or for that matter find(). But even if find() would be safe with respect to erase(), it doesn't help since by the time you received the return value of find() erase might already have invalidated that thing.

**Comment by Char-Aznable** [comment]
>But even if find() would be safe with respect to erase(), it doesn't help since by the time you received the return value of find() erase might already have invalidated that thing
I believe I have seen hash map algorithms that support async insert, erase and find so I think theoretically there might be a way to fix all of this. Would there be interest for a PR?

At least this should be documented.
