### ISSUE TITLE
Add Kokkos::Experimental::bhalf_t

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos#4372]
Base class `floating_point_wrapper` templated on `impl_type`.

Steps:

- [x] Refactor `half_t` support to use `floating_point_wrapper`.
- [x] Add `bhalf_t` support

**Comment by ajpowelsnl** [comment]
Hi @e10harvey - Has @crtrott been able to speak with you yet about how he would like to see this implemented?  If not, please book time with him to discuss, and let's get this party started!

**Comment by e10harvey** [comment]
@crtrott: Inheritance was not used to resolve this issue due to how C++ handles operator overloads in child classes (for example, assignment operators and non-member functions are not inherited from the parent class). Please take a look at #4543 and let me know if you have any feedback.

**Comment by crtrott** [comment]
Will look in more detail but alias is fine I think ...
