### ISSUE TITLE
Enable Profiling by default in Tribits build

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#438]
This is documenting that we want to enable Profiling by enabling the DLlib by default in a Trillions build. We already enable it by default in Makefile builds. This is done by marking DLlib as an tentatively enabled library.

**Comment by mhoemmen** [comment]
@crtrott Does profiling only work with dynamic shared libraries?  It's OK if not; we can just disable the profiling option in that case, with a suitable warning message.

Note that some customers insist upon static library builds of Trilinos.  I'm not pleased that they do; static libraries increase build times, and prevent me from having a function called if a package is linked in (see e.g., LinearSolverFactory's desired dependency injection).

**Comment by nmhamster** [comment]
@mhoemmen works for both build types.

**Comment by crtrott** [comment]
Yeah this works with static and dynamic links. The profiling tools themselves are linked in via explicit dynamic loads at runtime. The DLlib can be statically linked into the executable though.

**Comment by mhoemmen** [comment]
@crtrott @nmhamster good good, thanks :)
