### ISSUE TITLE
use external GoogleTest optionally

### ISSUE THREAD

**Issue by cz4rs** [kokkos/kokkos#4384]
Currently we use a fixed version of gtest (placed in `kokkos/tpls/gtest/gtest`). Add possibility to use external GoogleTest.

- [x] make tests work with the latest GoogleTest version (see #4230)
- [ ] ~add an option to provide gtest directory to use (`Kokkos_GTEST_DIR`?)~
  - try to find the gtest package with CMake, fallback to "our" version when not found
  - add a boolean option to disable searching and force the use of "our" version **or** use [CMake's builtin controls](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH.html#variable:CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH) for that (preferable)
- [ ] use this in at least one CI build

---
Part of [Version 3.6 - General Refactor](https://github.com/kokkos/internal-documents/blob/1d3e0a4411a6cb9f2b8a2cd63cfd09f53c87e99a/developer-notes/KokkosCore-Priorities.md#general-refactor-2).

**Comment by ajpowelsnl** [comment]
Hi @cz4rs -- would you like to discuss this item with the larger group?

**Comment by cz4rs** [comment]
> Hi @cz4rs -- would you like to discuss this item with the larger group?

Hi @ajpowelsnl, I have just added this to the agenda myself :)

**Comment by ajpowelsnl** [comment]
Good morning @cz4rs -- Did last Wednesday's discussion of this issue provide enough information to move this work forward, or would you like for me to add it to this week's list of items to discuss again?  Also, is there a PR yet that can be linked to this issue?  Many thanks for submitting this topic for discussion!

**Comment by ajpowelsnl** [comment]
@cz4rs  -- BTW, here's the guidance from the last Wed. Developer Meeting 👍 

  - Cezary: add external google test
  - Damien:
    - Looks good
    - Daniel: review please
    - Maintain a fall back option if GTEST not installed. In that case use the snapshot version that we provide
      - Nevin: Also specify to use internal (not to search) in case a non-working GTEST is found (for different reasons)
      - Daniel in favour
      - Add boolean to use external or internal ideally from cmake's GTEST find (FindGTest)

**Comment by cz4rs** [comment]
Fixed with #4563
