### ISSUE TITLE
AVX flags are showing up in PGI build

### ISSUE THREAD

**Issue by cponder** [kokkos/kokkos#4393]
I'm building Kokkos 3.4.01 using these settings
```
CMAKE_CXX_COMPILER=pgc++
CMAKE_CXX_EXTENSIONS=Off
Kokkos_ARCH_BDW=On
Kokkos_ARCH_VOLTA70=On
CUDA_TOOLKIT_ROOT_DIR=$PGI/cuda/$PGI_CUDA_LEVEL
Kokkos_ENABLE_CUDA=On
Kokkos_CUDA_DIR=$PGI/cuda/$PGI_CUDA_LEVEL
Kokkos_ENABLE_CUDA_LAMBDA=On
Kokkos_CUDA_LAMBDA=On
Kokkos_CUDA_UVM=On
Kokkos_ENABLE_HWLOC=On
Kokkos_HWLOC_DIR=$HWLOC
Kokkos_ENABLE_OPENMP=On
Kokkos_ENABLE_SERIAL=On
Kokkos_ENABLE_TESTS=On
CMAKE_CXX_FLAGS="-tp=host -mp -noswitcherror"
```
It looks like it builds ok, and all of the regression-tests pass.
I'm trying to build an app, though, and am seeing these flags show up in the build
```
-march=core-avx2 -mtune=core-avx2
```
which aren't valid with the PGI compiler. I know how to work around this (```-noswitcherror```) but am running into other breakages 
```
"/glade/u/apps/dav/opt/gnu/10.2.0-gpu/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/stdarg.h", line 40: error: identifier "__builtin_va_list" is undefined
  typedef __builtin_va_list __gnuc_va_list;
          ^

"/glade/u/apps/dav/opt/cuda/11.4.0/include/crt/sm_70_rt.hpp", line 94: error: identifier "__match32_any_sync" is undefined
    return __match32_any_sync(mask, value);
           ^
```
that look like it might be enabling some GCC-only components in the header-files.
Is there something else I need to set when I build Kokkos, or something I need to set when I build my app with Kokkos?

**Comment by cponder** [comment]
On a side-note, I know that I need to use this form
```
Kokkos_ENABLE_CUDA_LAMBDA=On
```
Before I figured that out, I was using this
```
Kokkos_CUDA_LAMBDA=On
```
Can I delete this, or does it need to stay in for some reason?

**Comment by masterleinad** [comment]
You should delete `Kokkos_CUDA_LAMBDA=On`.

**Comment by cponder** [comment]
Do I need to set this?
```
KOKKOS_COMPILER_PGI
```
All the other cases seem to start with ```Kokkos_``` rather than ```KOKKOS_```.

**Comment by masterleinad** [comment]
`PGI` should already optimize for the platform you're are compiling on, so likely you won't see a difference specifying a platform in the `CMake` configuration. Current `develop` uses `-tp=haswell`, though. You can set it yourself in `CMAKE_CXX_FLAGS` if you want.

No, you don't need `KOKKOS_COMPILER_PGI` either.

**Comment by masterleinad** [comment]
Apparently, `Kokkos` 3.4.01 sets a wrong flag for `Kokkos_ARCH_BDW=On` with `PGI` possibly due to using a newer `CMake` version that changes the compiler identification. I would just not set that `CMake` flag.

**Comment by masterleinad** [comment]
Out of curiosity: Do you see the same problem using a recent commit on `develop`? If so, we should fix it.
