### ISSUE TITLE
Is this a bug? "The installed Kokkos configuration does not support CXX extensions"

### ISSUE THREAD

**Issue by cponder** [kokkos/kokkos#4394]
I built Kokkos / develop and 3.4.01 with this setting
```
-D CMAKE_CXX_EXTENSIONS=On
```
This was reverted in the build/CMakeCache.txt file
```
//Kokkos turns off CXX extensions
CMAKE_CXX_EXTENSIONS:BOOL=OFF
```
and I get this message building my app:
```
The installed Kokkos configuration does not support CXX extensions.
Forcing -DCMAKE_CXX_EXTENSIONS=Off
```
Is this the way it's supposed to work?
I'm getting some header-file failures with an app I'm building, and want to know whether this is part of the problem.

**Comment by cponder** [comment]
Here's an example of the header-file problems:
```
"/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h", line 40: error: identifier "__builtin_va_list" is undefined
  typedef __builtin_va_list __gnuc_va_list;
          ^

"/gpfs/fs1/SHARE/Utils/CUDA/11.3.1.0_465.19.01/include/crt/sm_70_rt.hpp", line 94: error: identifier "__match32_any_sync" is undefined
    return __match32_any_sync(mask, value);
           ^
```
I'm hoping I just need to add an extra path somewhere, or set a compilation flag that would affect the ```#ifdef```'s.

**Comment by masterleinad** [comment]
We are using the standard flags for nvcc/nvcc_wrapper and the host compiler which means that standard extensions are not supported for `Cuda` builds using `nvcc_wrapper` (directly tr indirectly). You could see if you get the same error using `clang` instead of `nvcc`.

**Comment by masterleinad** [comment]
nvcc only supports `-std {c++03|c++11|c++14|c++17}`.
