### ISSUE TITLE
LayoutStride Scalar view has span 0

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#4401]
In some corner case of my application, I encounter something like
```c++
  Kokkos::View<int, Kokkos::LayoutStride> v("v"
    , Kokkos::LayoutStride());

```
which has a span of zero but I expect its span is 1. There seems to be no way of making a valid view out of it by different way of calling the ctor `Kokkos::LayoutStride` or by doing `Kokkos::View<int, Kokkos::LayoutStride> v("v")`. I know this is a weird corner case but there isn't any documentation on whether this should be allowed or not. Semantic wise, a scalar view of stride 1 makes perfect sense.

**Comment by mhoemmen** [comment]
Relevant: https://github.com/ORNL/cpp-proposals-pub/pull/157
