### ISSUE TITLE
How do I create a memory space instance?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#442]
I would like to use the new version of Kokkos::create_mirror_view that takes a memory space instance as its first argument, because this will let me create a "device mirror" (like a host mirror, but on device instead of on host).  See comment here: https://github.com/trilinos/Trilinos/issues/621

How do I safely and correctly create a memory space instance?  For example, CudaUVMSpace has an `int m_device` instance variable, but the default constructor doesn't set it.

**Comment by hcedwar** [comment]
Currently the default memory space instance is created by the default memory space constructor.  The internal m_device is currently unused and a place holder for planned multi-instance capability.

**Comment by mhoemmen** [comment]
> Currently the default memory space instance is created by the default memory space constructor.

Thanks @hcedwar !  Will this change at some point?  That is, is it safe for me to do this right now?

**Comment by hcedwar** [comment]
The default constructor will always produce the default memory space instance.  In the future a non-default constructor will have to be used to get a non-default memory space instances.

**Comment by mhoemmen** [comment]
Thanks!  It sounds like memory spaces have the same "view semantics" that View has.  That seems reasonable to me :-)
