### ISSUE TITLE
Nightly tests build failures with std algorithms: cuda/11.0+gcc/9.2 with c++17

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4423]
Some nightly tests began failing following merge of #4315 with support for C++ algorithms.
The cuda/11.0+gcc/9.2 with c++17 build fails to compile with errors of type:

```
21:21:39 nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
21:21:39 nvcc error   : 'cicc' core dumped
21:21:39 make[2]: *** [algorithms/unit_tests/CMakeFiles/KokkosAlgorithms_UnitTest.dir/TestStdAlgorithmsSearch_n.cpp.o] Error 139
```

**Reproducer (Cuda_Serial, kokkos-dev-2)**:
```
module load sems-env sems-cmake/3.17.1 cuda/11.0 sems-gcc/9.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Serial --arch=SNB,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17"--kokkos-path=$KOKKOS_PATH --with-options=disable_deprecated_code --with-cuda-options=enable_lambda  --no-examples
```

@cz4rs @fnrizzi are you able to take a look?

**Comment by ajpowelsnl** [comment]
Morning @fnrizzi and @ndellingwood -- Would you both be OK with my assigning this issue to you guys?

**Comment by ajpowelsnl** [comment]
@ndellingwood -- Can I put you on this issue , too?  It might be good to team, since the issues are surfacing in Nightly Builds...

**Comment by fnrizzi** [comment]
@ndellingwood fix is ready in this PR: https://github.com/kokkos/kokkos/pull/4488

**Comment by ndellingwood** [comment]
The build completed and the algorithms tests passed, thanks for the fix!
