### ISSUE TITLE
Nightly tests build failures with std algorithms: test failures with intel compilers and serial backend

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4424]
Some nightly tests began failing following merge of #4315 with support for C++ algorithms.
The intel/17.0.1, intel/18.0.5 jobs all have multiple unit test failures with the serial backed (passing with openmp, threads), e.g.

```
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] std_algorithms_mod_seq_ops_test.transform
[  FAILED  ] std_algorithms_mod_seq_ops_test.swap_ranges
[  FAILED  ] std_algorithms_replace_ops_test.replace_copy
[  FAILED  ] std_algorithms_replace_ops_test.replace_copy_if
```

**Sample reproducer** (intel/18.0.5):
```
module load sems-env sems-cmake/3.17.1 sems-intel/18.0.5
# Note: This job has gcc/6.4.0 on the path

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

@cz4rs @fnrizzi are you able to take a look?

**Comment by fnrizzi** [comment]
@ndellingwood yes, will look into it thanks !

**Comment by fnrizzi** [comment]
I started to try working on this but obviously none of my sandia stuff is working :( 
I will try as soon as things work again

**Comment by ajpowelsnl** [comment]
Hi @fnrizzi and @ndellingwood -- Would it be OK if I assigned this issue to both of you, as well?

**Comment by fnrizzi** [comment]
thanks! I think I fixed them. Using your reproducer, everything now passes on kokkos-dev-2.

**Comment by fnrizzi** [comment]
@ndellingwood can we close this issue ?

**Comment by ndellingwood** [comment]
@fnrizzi #4480 resolved the final failure, thanks for the fix, closing the issue
