### ISSUE TITLE
Document that over-allocation of HBM can result in hangs

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#443]
Modern OS allow over-allocation where virtual pages are only bound to physical pages upon first touch.  When physical pages are exhausted system hangs and deadlocks can occur.  Since we cannot catch this error in Kokkos, the programming guide needs to make specific mention of edge case.

**Comment by nmhamster** [comment]
This should not happen any more for KNL systems, it should fail the allocation. What options are you using for `numactl`?
