### ISSUE TITLE
Extend View api to mimic proposed array_ref API to specify extents

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#444]
The current View API only allows static dimensions from the right, extend the API to accept an optional Extents argument to allow intermixing of static and dynamic dimensions.  Extents takes a variadic list of integers, where 0 signifies that the dimension is dynamic.

This will facilitate transiting Fortran codes to C++/Kokkos by allowing codes to maintain the same array structures and indexing.

e.g.
View< Type, Extents< I, J, K, 0 >, Layout, Device, IndexType< integral >, Traits >

**Comment by ibaned** [comment]
This will also improve cases we have that use a `LayoutStride` to work around the current `DataType` restriction that all static dimensions must be on the right.

**Comment by mhoemmen** [comment]
Was the idea to imitate / use the mdspan proposal (not the one requiring a syntax change, but the back-up one) from the last C++ meeting?

**Comment by crtrott** [comment]
We are waiting on a firm decision on how this looks in mdspan. Only then should we add this alternative dimensionality definition mechanism. I don't want to introduce a second mechanism, which is not gonna be long term relevant.
