### ISSUE TITLE
Bogus device ID for profiling tool callbacks

### ISSUE THREAD

**Issue by khuck** [kokkos/kokkos#4455]
Occasionally, I get bogus device IDs in the profiling API.  These calls: `kokkosp_begin_parallel_for`, `kokkosp_begin_parallel_scan`,`kokkosp_begin_parallel_reduce`. give the device ID as a `uint32_t`.  It appears that sometimes a couple upper bits get set, and I get device IDs like: 16777216, 33554432, or 50331648.  Just those three values.  If I do the following, I can get the legit device id:
```
    // mask off the upper bits, they are sometimes set...
    uint32_t _devID = devID & 0x0000FFFF;
```
...unless the upper bits of the device ID are supposed to be telling me something?

**Comment by janciesko** [comment]
Has this been resolved? @khuck

**Comment by khuck** [comment]
@janciesko It hasn't been documented (I don't think), but I found the code that explains what the bit mask is.  It's resolved for my problem, but I don't know if the documentation has been done.

**Comment by janciesko** [comment]
I see, yes, there is bug. I'll issue a PR.

**Comment by janciesko** [comment]
https://github.com/kokkos/kokkos/pull/4694

**Comment by khuck** [comment]
will this require a change in interpreting the value?

**Comment by janciesko** [comment]
If your code relies on the buggy version, yes, if it relies on your temporary fix (masking the wrong bits out), then likely not.

**Comment by khuck** [comment]
this was working as of e5a8acce571b0deeb04b8eb53b7bb2aaa9ebbb87, but current develop is giving bogus device ID information.  Please see my comments on #4694.  thanks!

**Comment by janciesko** [comment]
@khuck  - with https://github.com/kokkos/kokkos/pull/4997 in develop, does this fix the issue?

**Comment by janciesko** [comment]
@khuck  - with https://github.com/kokkos/kokkos/pull/4997 in develop, does this fix the issue?

**Comment by khuck** [comment]
Yes, I wrote on the other PR where this was discussed (#4997 ?) that it is working now. I just double-checked on Crusher. Thanks!
