### ISSUE TITLE
Possible Issue with Makefile.kokkos with "Incorrect Standard Input"

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#446]
Am seeing some outputs that the arithmetic in Makefile.kokkos has an incorrect `standard input`. Haven't had time to check this out yet but am repeatedly seeing this on Linux systems running Broadwell and KNL. Will try to track down and report back.

**Comment by crtrott** [comment]
Is this the latest develop or master branch? I fixed one of those guys a few days ago.

**Comment by nmhamster** [comment]
We think it is in both but not confirmed yet.

**Comment by crtrott** [comment]
What is an example of output? I just ran a KNL build and didn't get any spurious output on Bowman.

**Comment by crtrott** [comment]
The commit which fixed the previous issue went in on Sep 20th 520af6b076ac3d

**Comment by nmhamster** [comment]
I *think* we pulled yesterday but I'll check with the people here.

**Comment by nmhamster** [comment]
We are using `master`.

**Comment by crtrott** [comment]
Oh master was updated yesterday late afternoon. So if you were using master from before 4pm mountain time yesterday you have the syntax error still in.

**Comment by nmhamster** [comment]
OK, that explains it. I will close issue since its fixed.

**Comment by crtrott** [comment]
Removing bug label and mark duplicate for book keeping purposes.
