### ISSUE TITLE
[Feature Request] task data parallel for knl tile mapping.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#447]
Current Kokkos task data parallel interface maps data parallelism within a task to hyper threads. This may not give us a benefit when we want to use BLAS calls. For such a case, it would be better to map data parallel part into a tile on knl (no evidence that this will work better yet).

**Comment by hcedwar** [comment]
Related to issue #426 requesting user configured task team size

**Comment by hcedwar** [comment]
Related to #255
