### ISSUE TITLE
KokkosCore_UnitTest_Cuda1 timing out in nightly tests with cuda/11.1+gcc/8.3.0

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4474]
The `KokkosCore_UnitTest_Cuda1` test began timing out in the `cuda.impl_shared_alloc` subtest in nightly Cuda builds with cuda/11.1+gcc/8.3.0 with c++14 and c++17

```
21:30:03 2: [ RUN      ] cuda.impl_shared_alloc
21:30:03  2/50 Test  #2: KokkosCore_UnitTest_Cuda1 ....................***Timeout 2000.14 sec
```

**Reproducer**:
```
module load sems-env sems-cmake/3.17.1 sems-cuda/11.1 sems-gcc/8.3.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,Pthread --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --with-cuda-options=enable_lambda  --no-examples --with-options=enable_large_mem_tests
```

I'll have to triage this tomorrow (Thur) to pinpoint the culprit change, but from a quick scan it looks like #4349 touched code in `SharedAllocationRecord` specializations to add fences after deep copy calls, could this be related?

**Comment by ajpowelsnl** [comment]
Morning @masterleinad and @ndellingwood - Can we close this issue, since PR #4478 would appear to resolve the problem?
