### ISSUE TITLE
[Improvement] FAD operator() in DynRankView.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#448]
DynRankView has a performance problem when it uses FAD as it FAD dimension is established on the base rank 8 view. This carries significant overhead in operator(). FAD specialization on DynRankView should be remedied. 

@ndellingwood , @etphipp   and I already discussed about this and  this issue is for tracking work progress.

**Comment by ajpowelsnl** [comment]
@kyungjoo-kim -- Is this still an issue for you?

**Comment by kyungjoo-kim** [comment]
I think that it is resolved.

**Comment by ndellingwood** [comment]
@ajpowelsnl at one point we had discussed creating a ViewMapping specialization to update the existing functionality in Sacado but this was moved to the backlog as other tasks were higher priority at the time and never made it out of the backlog. I'm guessing incorporation of mdspan will supercede this

**Comment by ajpowelsnl** [comment]
Morning @kyungjoo-kim , @ndellingwood  -- Many thanks for chiming in.  If necessary in the future, we'll re-open , and update this issue.
