### ISSUE TITLE
Can we have Kokkos::sort on non-integral types like Kokkos::pair?

### ISSUE THREAD

**Issue by hamidrezanorouzi** [kokkos/kokkos#4487]
Hi,
In a part of my application I have to sort millions of values (pairs). I am developing the code for two back-ends (OpenMP and cuda). I realized that the sort function in Kokkos, only works on integral types like int, etc. However, std::sort and thrust::sort give more flexibility and provide me with compareFunction , which allows me to perform custom sorting operations. I first came-up with this solution that I use thrust and std functions for my application (instead of using Kokkos'), which makes the code a bit ugly. However, std parallel algorithms are developed on TBB back-ends and when I use std::sort in my application, I see performance issues. My question: is there a way to sort Kokkos::pair values using Kokkos::sort? Can future release provide more general functions for performing sort operations? As you know, many parallel algorithms rely on sorting and in some cases this sorting is not as straightforward as sorting integral types. 

Thanks

**Comment by cwsmith** [comment]
+1 to this.  We have a similar use case.  In our code there is a View of a scalar type that are treated as tuples (e.g., two consecutive ints per 'item') that I'd like to sort using a custom comparison operator between a pair of tuples.  Instead of returning the view of sorted scalars I'd like to return a permutation array.  

From what I have seen so far in [ArborX](https://github.com/arborx/ArborX/blob/419e078861dc61500cf16359b12c874e5c304dec/src/details/ArborX_DetailsSortUtils.hpp#L75-L109) and Kokkos_sort.hpp, I need to call BinSort.  Assuming that is correct, I'm guessing I'll then need to implement something like [BinOp[1|3]D](https://github.com/kokkos/kokkos/blob/2879e23507bcb21adb739d6317b3430f665de4a6/algorithms/src/Kokkos_Sort.hpp#L395-L432) but didn't find an example that gave me confidence to proceed.

As mentioned in the OP, this is done for the Cuda backend using Thrust by defining a simple comparison operator.

**Comment by dalg24** [comment]
`Kokkos::sort` is currently supported on arithmetic types.
For reference, the (undocumented) type requirements are
* A specialization of `Kokkos::reduction_identity` matches `T` and provides `min()` and `max()` static member functions.
* Definitions of binary comparison operator less than and greater than that (sigh...) take objects of type possibly `volatile`- qualified `T` are available
* Binary `operator-` is defined

I agree that this would be a good thing to support sorting arrays of user-defined types with a comparison operator.  It is not a trivial ask though.  We will discuss that at the next developer meeting.  Feel free to upvote this issue and comment further if your use-case is not covered above.

**Comment by masterleinad** [comment]
Also, note that `ArborX` is using vendor libraries for `Cuda`, `HIP` and `SYCL`.

**Comment by PhilMiller** [comment]
EMPIRE would also appreciate a Kokkos routine to go from a comparator function and some input to a sorted permutation array. It might even be able to provide the relevant code - I can check if the implementation there is acceptable to generalize like that and they're OK with have it lifted out.

Just a thought on the design - should the comparator encapsulate any references it needs to the data it's actually going to compare? I'm thinking we may want essentially `template <class Comparator, class ViewType> void sorted_permutation(int length, Comparator c, ViewType out_permutation)`. Taking the output as an argument to allow avoided allocation, and templating over it to allow different memory spaces, etc.

**Comment by hamidrezanorouzi** [comment]
> `Kokkos::sort` is currently supported on arithmetic types. For reference, the (undocumented) type requirements are
> 
> * A specialization of `Kokkos::reduction_identity` matches `T` and provides `min()` and `max()` static member functions.
> * Definitions of binary comparison operator less than and greater than that (sigh...) take objects of type possibly `volatile`- qualified `T` are available
> * Binary `operator-` is defined
> 
> I agree that this would be a good thing to support sorting arrays of user-defined types with a comparison operator. It is not a trivial ask though. We will discuss that at the next developer meeting. Feel free to upvote this issue and comment further if your use-case is not covered above.

I have tried to overload the operator operator - for Kokkos::pair. However, I guess the return value should be int (unsigned int) and I had no idea how I correctly convert two integers (maybe by using a hasher) to one integer. 
The other requirements for a custom sort are not documented (like specializing Kokkos::reduction_identity), and I didn't know that I also need those.
Now suppose that I am using Kokkos::sort for developing a high level API. In this API the type of the values to be sorted is templated, and the user of the API should provide all the above requirements for that type. This is possible, but hard. 
With a custom comparator, the user of the API only requires to provide a function object (or similar mechanisms) for that specific type and use the API. 
I have not reviewed the underlaying algorithm of Kokkos::sort and I don't know about the implementation difficulties or performance penalties of this approach. But I think this would enhance Kokkos' API.

**Comment by PhilMiller** [comment]
Notes from EMPIRE's code - 
Good news: there's a CUDA compatible implementation of quicksort that's been in production use
Bad news: it's meant for sorting modest numbers of objects already binned by an integer key, so it runs sequentially, with outer parallelism over the bin (one thread per)

**Comment by crtrott** [comment]
We decided that we need to support stuff like this as part of a larger enhancement of sorting capabilities in Kokkos, that includes new underlying sort algorithms.

**Comment by PhilMiller** [comment]
@hamidrezanorouzi For my reference as I'm now starting work on Kokkos sorting enhancements in this vein, what are the elements of your pairs? Are they each themselves integers?

**Comment by hamidrezanorouzi** [comment]
> @hamidrezanorouzi For my reference as I'm now starting work on Kokkos sorting enhancements in this vein, what are the elements of your pairs? Are they each themselves integers?

It can be a pair of integers. But in more general form, it should have a compare functor (compareFunction), so the user provide a compare function to it.

**Comment by PhilMiller** [comment]
We're discussing adding a comparison based sort. The reason I asked is because I want to prioritize that against generalizing our implementations of integer sorting algorithms (e.g. RadixSort) that outperform the N*log(N) lower bound for comparison-based algorithms. I strongly suspect that use cases among Kokkos client applications are heavily weighted away from needing to pay the computational-complexity expense of general sorting.

**Comment by hamidrezanorouzi** [comment]
In many cases, sort is performed on pairs of int32 or int64. 
If you are going to leverage the performance gain of sorting pairs of integers and on the other side be general, you may want to provide two versions (overloads) of the function: one for pairs of integers (which is the more efficient version) and one with a compare function that enables, which extends the capabilities of the code with additional costs (if the client uses it).

**Comment by PhilMiller** [comment]
That was the general plan I had in mind.

**Comment by aprokop** [comment]
A slightly tangential but still related to this is the functionality of the segmented sort. Sometimes, you have a compressed graph storage, and you want to sort items just within the rows. Using pairs would be one way to achieve that, but providing a segmented sort would be ideal.

**Comment by masterleinad** [comment]
Fixed in #6253.
