### ISSUE TITLE
Regarding to experimental task DAG retiring.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#449]
Now we have a new task API on Serial, OpenMP and CUDA, outdated experimental APIs on P/Q threads should be updated. FYI: George wants his new NUMA scheduling with Qthreads.

**Comment by gmackey** [comment]
I am currently working on updating the Qthreads backend.

**Comment by gmackey** [comment]
The Qthreads backend has its own ticket: #366.
