### ISSUE TITLE
using namespace KokkosBatched.hpp causes build errors in application codes

### ISSUE THREAD

**Issue by jfike** [kokkos/kokkos#4497]
We are currently seeing build errors with the latest version of kokkos in Trilinos.  Specifically, `error: reference to 'Vector' is ambiguous` due to KokkosBatched::Vector.  I've also heard of at least one other application code with similar build errors.

I found three spots in kokkos-kernels with `using namespace KokkosBatched.hpp`.  Specifically, KokkosBlas3_trsm_impl, KokkosBlas3_trmm_impl, and KokkosBlas_trtri_impl.  I removed the `using namespace` lines and fixed the calls in those files.

This allowed our application code to build without any errors.

**Comment by masterleinad** [comment]
This sounds like a problem that should be fixed in `KokkosKernels` not in `Kokkos`. Would you mind migrating the issue over to https://github.com/kokkos/kokkos-kernels/issues?

**Comment by jfike** [comment]
Done. https://github.com/kokkos/kokkos-kernels/issues/1170
