### ISSUE TITLE
parallel_scan on the device with a TeamThreadRange

### ISSUE THREAD

**Issue by jeffamelang** [kokkos/kokkos#45]
It seems that parallel_scan doesn't work on the device with a TeamThreadRange.

**Comment by jeffamelang** [comment]
In case this issue looks suspiciously sparse, it's simply to make official a conversation that has already happened via email, and gives Christian a way of official checking a box when he fixes it.

**Comment by dholladay00** [comment]
I have recently attempted to use a parallel_scan pattern with an **integer range policy** and using a lambda (not function) on a Cuda device (with kokkos built as a library, not using Makefile.kokkos) and I get compile time errors.

Are parallel scans supported on Cuda with a lambda body?

I can give more details if necessary, but this seemed like something that would be supported, although to be fair, the kokkos tests don't pass on my system  #196  , so there are issues lurking about, but I have not been able to identify all of them as of yet.

**Comment by crtrott** [comment]
lambdas on Cuda are still considered experimental by NVIDIA. They come with a set of restrictions which do not allow us to implement scan unfortunately.

**Comment by dholladay00** [comment]
Okay, I can express the algorithm with a `parallel_for`, I just wanted to make sure this wasn't due to me improperly building of the library or some other issue on my end.

**Comment by crtrott** [comment]
No it is not. You could use a functor. That works with Cuda.

**Comment by mfdeakin-sandia** [comment]
In case you all are still gauging interest in this feature, my project also needs this feature for OpenMP and Cuda. It's not something we need frequently, but there are some parts that could use it.

**Comment by Char-Aznable** [comment]
I'm running into the same issue here. Is there any update on this thread?

**Comment by dholladay00** [comment]
Is there a document that contains a table of which patterns (`parallel_*`) are available with which policies (`TeamThread...`, `ThreadVector...`, etc.) for each backend (openmp, pthread, cuda, serial, ...)? 

If it doesn't exist, would it be possible to make such a thing?
