### ISSUE TITLE
OpenMP Target: execute_init_join in reduction

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#4500]
@dalg24 @rgayatri23 
Another issue with the OpenMP Target discovered while building Kokkos Kernels, here is the compiler error:

```c++
In file included from /gpfs/alpine/scratch/lberge/csc465/builds/ompt_cuda/kk_lucbv/src/impl/generated_specializations_cpp/spgemm_symbolic/Sparse_spgemm_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_OPENMPTARGET_MEMSPACE_OPENMPTARGETSPACE_MEMSPACE_OPENMPTARGETSPACE.cpp:48:
In file included from /ccs/proj/csc465/lberge/kokkoskernels_root/sources/kk_lucbv/src/sparse/impl/KokkosSparse_spgemm_symbolic_spec.hpp:49:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/Kokkos_Core.hpp:56:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/KokkosCore_Config_DeclareBackend.hpp:47:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/decl/Kokkos_Declare_OPENMPTARGET.hpp:49:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/Kokkos_OpenMPTarget.hpp:157:
/gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp:1005:31: error: no member named 'begin' in 'Kokkos::Impl::TeamPolicyInternal<Kokkos::Experimental::OpenMPTarget, Kokkos::Experimental::OpenMPTarget>'
    const auto begin      = p.begin();
```

currently to work around this build issue I replace the implementation of `execute_init_join` in kokkos/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp (line 254 and 1003) with:

```c++
  static void execute_init_join(const FunctorType& f, const PolicyType& p,
                                PointerType ptr, const bool ptr_on_device) {
    (void) f, p, ptr, ptr_on_device;
  }
```
but I'm sure that will make my kernel fail to run...

**Comment by rgayatri23** [comment]
Oh I see the issue. This is not supposed to work because the `execute_init_join` for `TeamPolicy` is a copy of the same routine from `RangePolicy` which means its missing a few variable names that are accessible in `RangePolicy`. I understand the issue. I will fix it.

**Comment by ajpowelsnl** [comment]
Thanks, @lucbv and @rgayatri23.  Rahul, may I assign this issue to you?

**Comment by rgayatri23** [comment]
> Thanks, @lucbv and @rgayatri23. Rahul, may I assign this issue to you?

Yes @ajpowelsnl . I have assigned it to myself.

**Comment by rgayatri23** [comment]
Addressing this issue in #4521 @lucbv can you check the updates.

**Comment by lucbv** [comment]
Closing this issue since PR #4512 has been merged.
