### ISSUE TITLE
stable (more permanent) access that allows access to host serial member

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#4501]
In my use cases, I have multiple functor-level functions taking the member argument. For serial and host execution case, it can also be used without kernel launch. To support this use case, I used to use the following syntax.
```
Impl::HostThreadTeamData* const data = Impl::serial_get_thread_team_data();
```

This interface is changed recently, and I do the following
```
auto & data = serail_execution_space().impl_internal_space_instance()->m_thread_team_data;
```

My request is to provide this serial team member interface as a non-impl interface (stable interface which is not going to be changed over time). Since the functor is already written with parallel range construct internally, without the serial member data I have to write the same function twice or I make a fake team member that can override with all kokkos nested parallel constructs. If Kokkos provides something equivalent that I can use on host without kernel, I appreciate for it.

**Comment by ajpowelsnl** [comment]
Morning @kyungjoo-kim - Many thanks for bringing the issue up.  I don't actually know the extent to which interfaces and implementation are de-coupled in Kokkos, but we'll figure out a way to address your issue.

**Comment by crtrott** [comment]
Uhm what are you doing with that thing? I am seriously considering removing it in favor of some other stuff in particular for the serial backend. So what is your use case.

**Comment by crtrott** [comment]
Oh and to make that clear: it is absolutely undefined behavior to get this thing EVER outside of a TeamPolicy launched parallel construct even ignoring the fact that its in IMPL.

**Comment by kyungjoo-kim** [comment]
I have a code something like
```
/// the interface has member, input, output. I do not allocate scratch memory internally 
/// the workspace buffer is used when this code is used with kokkos parallel launch.
template<typename MemberType>
KOKKOS_INLINE_FUNCTION void doThisForSomething(const MemberType &member, input, output, workspace) {
  kokkos_parallel_for(team_vector_range(member, m), [=](int i) {
  }
}

/// This code can be used in kokkos parallel for with or without team policy 
/// so far I achieve this when it is used without kokkos parallel launch
auto& data = Kokkos::Serial().impl_internal_space_instance()->m_thread_team_data;
auto member = Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>(data);

doThisForSomething(member, input, output, work);
```

Without having the serial member interface (in my use case, I always enable serial backend), I have to write two same codes with and without kokkos nested parallel for. This so far works fine and if possible I would like to get a more consistent interface exposure. With serial member has unit team/vector size, I don't think that it has undefined behaviors.

**Comment by crtrott** [comment]
Sorry this is clearly breaking through the abstraction and now how anyone should write code. I do have plans to make this all work better with C++17 where you will have a much more generic interface and combined with stuff like std::conditional can do what you are trying to do in a proper way. But we are not there yet. Note that Serial semantically doesn't guarantee to execute in the calling thread, and we will likely change that in the future.
