### ISSUE TITLE
Mathematical constants and functions in Kokkos

### ISSUE THREAD

**Issue by srikrrish** [kokkos/kokkos#4507]
Hi all,

What is the best way to use mathematical constants such as pi in a portable way alongside kokkos? Does Kokkos provide an interface for it and is it guaranteed to have in all future releases too? I am afraid to use things like M_PI from cmath because of portability. Similarly, for mathematical functions such as sin, cos, erf etc. currently I use std::cos, std::sin, std::erf from cmath (inside Kokkos loops also). Is this fine or is there a better way of doing it from Kokkos?   

Thanks

**Comment by dalg24** [comment]
Regarding the math constants, Kokkos does not currently provide anything but we would consider backporting the new C++20 facility https://eel.is/c++draft/numbers so you can write use something like `Kokkos::pi<FloatingPointType>::value`.
As far as the math functions are concerned, you can use `Kokkos::Experimental::{cos,sin,erf}`.  We added them in v3.4

**Comment by srikrrish** [comment]
Sounds good. Thanks for the info.

**Comment by ajpowelsnl** [comment]
Good for beginner -- assign on Wednesday

**Comment by dalg24** [comment]
This has been merged in the develop branch and will be part or release 3.6
You would do
```C++
constexpr auto pi = Kokkos::Experimental::pi_v<FloatingPoint>;
