### ISSUE TITLE
Multiple reductions for team-level loops

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#4510]
I'd like to be able to use multiple reductions for parallel_reduce calls on TeamThreadRange/TeamVectorRange/ThreadVectorRange levels.

**Comment by ajpowelsnl** [comment]
Morning @vbrunini -- Many thanks for the suggestion.  I'll bring it to the team to discuss in our Wed. meeting.

**Comment by ajpowelsnl** [comment]
Hi @nliber and @ldh4 -- what is the status of this issue?

**Comment by ldh4** [comment]
@ajpowelsnl We haven't gotten to this yet. We plan to start this once #4812 is code complete.
