### ISSUE TITLE
Check Kokkos::InitArguments::num_threads == 0 (with OpenMP enabled)

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#4512]
If you build with OpenMP, and do
```
  Kokkos::InitArguments init_args;
  init_args.num_threads = 0;
  Kokkos::initialize(init_args);
  Kokkos::parallel_for(Kokkos::RangePolicy<Kokkos::OpenMP>(0, 20),
      KOKKOS_LAMBDA(int i)
      {
        std::cout << "Hello from OpenMP, running with " << omp_get_num_threads() << " threads.\n";
      });
  Kokkos::finalize();
  return 0;
```
then Kokkos::initialize will silently accept the 0 thread number. OpenMP itself appears to clamp it to 1, but Kokkos allocates internal structures for scan based on 0, so ``parallel_scan`` will crash.

The above prints this 20 times:
```
Hello from OpenMP, running with 1 threads.
```

This isn't really a bug with Kokkos as num_threads obviously shouldn't be 0, but it would be nice for ``initialize()`` to validate the ``num_threads`` setting.

See https://github.com/kokkos/kokkos-kernels/issues/1168 for an issue that was affected by this - a bug in command-line argument parsing led to num_threads being 0, but in valgrind/gdb it behaved as if there was a bug much further along in the program (in a scan).

**Comment by brian-kelley** [comment]
Maybe this is a real bug after all - I looked into ``OpenMP::impl_initialize`` and it seems that num_threads == 0 is supposed to be handled gracefully:
```
315     } else if (thread_count == 0 &&
316                Impl::g_openmp_hardware_max_threads != process_num_threads) {
317       Impl::g_openmp_hardware_max_threads = process_num_threads;
318       omp_set_num_threads(Impl::g_openmp_hardware_max_threads);
```

And here's a complete reproducer for scan crashing:
```
#include "Kokkos_Core.hpp"

int main()
{
  Kokkos::InitArguments args;
  args.num_threads = 0;
  Kokkos::initialize(args);
  {
    Kokkos::View<int*, Kokkos::HostSpace> myView("myView", 10);
    //This scan segfaults
    Kokkos::parallel_scan(Kokkos::RangePolicy<Kokkos::OpenMP>(0, 10),
    KOKKOS_LAMBDA(int i, int& lsum, bool finalPass)
    {
      int val = myView(i);
      if(finalPass)
        myView(i) = lsum;
      lsum += val;
    });
  }
  Kokkos::finalize();
  return 0;
}
```
If you just leave num_threads to the default (-1), the scan succeeds.

**Comment by ajpowelsnl** [comment]
Morning @brian-kelley and @masterleinad -- Are we able to close this issue now that the fix has been merged?

**Comment by masterleinad** [comment]
I added the `InDevelop` label.
