### ISSUE TITLE
Feature request: allow list initialization of view

### ISSUE THREAD

**Issue by Char-Aznable** [kokkos/kokkos#4514]
Currently, it takes a lot of boilerplate to create even simple 1-d view. It would be very convenient for the user to be able to do something like: `View v("v", {1,83, 12, 6, 5});` or even just `View v({1,83, 12, 6, 5});` Free function like `auto v = makeView({1,83, 12, 6, 5});` would do too

**Comment by dalg24** [comment]
Although I agree it can be handy and I have written such code many times (never in production code but more as a unit testing facility), I don't think that this is a pattern we would want to encourage people to use.
In any case, adding a new `View` constructor is a no-go, a free function would have more chance to land.

Here is an example of code that does about what you are asking for
https://github.com/arborx/ArborX/blob/fccbfd2034efc6152df41fd0cbccb531c69b4057/examples/dbscan/dbscan.cpp#L137-L146

**Comment by Char-Aznable** [comment]
>I don't think that this is a pattern we would want to encourage people to use

Why? Most of the popular numeric libraries in the world have something like that. 

Free function would do the job too. Since many people are doing their own version of this, why not make a standard version of it?

**Comment by crtrott** [comment]
Yeah I think a three function is possible. Should get easier with mdspan in there then too.

**Comment by ajpowelsnl** [comment]
@dalg24 and @crtrott -- I will add to our list of items to discuss for the Wed. , Nov. 17th meeting.

**Comment by ajpowelsnl** [comment]
> Yeah I think a three function is possible. Should get easier with mdspan in there then too.

Free function?

**Comment by crtrott** [comment]
What one could write:
```c++
auto vals = {1,3,4};
view_t a(vals.begin(), vals.size());
auto a_d create_mirror_view(device_t(),a);
```

Or if you just want a temporary thing inside a kernel:
```c++
auto vals = {1,3,4};
view_t a(vals.begin(), vals.size());
```
Just leave the vals thing around. 

Vote of the team: "We should add a free function to construct a possibly device side view from an initializer list"
SF F N A SA
0 0 4 6 2

So there is a pretty strong consensus for not doing it. Mainly because the team doesn't feel that folks should write this in production code, since its generally a pretty inefficient thing to create small views, and furthermore the free function would do be fairly costly (needs to allocate, deep_copy and fence).

**Comment by Char-Aznable** [comment]
> Just leave the vals thing around

Unfortunately, this is not always practical. The resulting view needs ownership of the data.

> Mainly because the team doesn't feel that folks should write this in production code, since its generally a pretty inefficient thing to create small views, and furthermore the free function would do be fairly costly (needs to allocate, deep_copy and fence)

What's the baseline for "pretty inefficient"? How would you do it (with the ownership requirement)?

**Comment by Char-Aznable** [comment]
>furthermore the free function would do be fairly costly (needs to allocate, deep_copy and fence)

Also, it's not true that one necessarily needs deep_copy  and fence. The example referred by @dalg24 is not necessarily the only way to do it. There's a way to do it with just one kernel launch

**Comment by dalg24** [comment]
> The example referred by @dalg24 is not necessarily the only way to do it.

Not arguing with you on this.
Fell free to share snippets of code on this thread.

We are not willing to add the functionality at this time, but we may reconsider after the `View` refactor to use `mdspan`.
