### ISSUE TITLE
Slow deallocation of DynamicView

### ISSUE THREAD

**Issue by lifflander** [kokkos/kokkos#4517]
The de-allocation of DynamicView has slowed down significantly due to the recent refactor (https://github.com/kokkos/kokkos/pull/4129). 

It seems the issue might be that the deallocation is no longer performed in a parallel_for.

**Comment by DavidPoliakoff** [comment]
Could you link the refactoring in question, and give perf numbers?

**Comment by lifflander** [comment]
> Quick Summary: In kokkos 3.4 release, the ParticleContainer TestAppendSort runs in about 1.6 seconds. The 3.5 release takes 533 seconds. The actual test still runs in 1.6 seconds, with the rest of the time occurring at exit of the test during the destructor calls to the DynamicViews in teh ParticleContainer.

**Comment by ajpowelsnl** [comment]
Hi @lifflander -- many thanks for looking at this!

**Comment by crtrott** [comment]
See my post in the PR: this seems to be unlikely to be the culprit. Did you actually test that your proposed fix makes this thing run fast? And 150x? How is that supposed to be coming from parallel dealloc vs serial? How many threads are you running.
