### ISSUE TITLE
Rare bug in memory pool where allocation can finish on superblock in empty state

### ISSUE THREAD

**Issue by gmackey** [kokkos/kokkos#452]
In the memory pool, it is possible for an allocation to finish on a superblock in the empty state.  Allocations can only start on superblocks in the active state, but it is possible for the superblock to transition to full, then partially full, then empty before the allocation completes.  This is extremely unlikely and hasn't been encountered yet, but the issue needs to be addressed.

**Comment by crtrott** [comment]
Tonight there was a segmentation fault on openmp.task_fib on kokko-develop in addition to the always failing cuda.task_fib on Pascal.

**Comment by hcedwar** [comment]
The redesigned memory pool explicitly eliminates this situation.
