### ISSUE TITLE
Kokkos::sort with UVM now requires a fence before it

### ISSUE THREAD

**Issue by kddevin** [kokkos/kokkos#4526]
Before Kokkos' last upgrade in Trilinos, a call to Kokkos::sort with a UVM view after a device kernel did not require a fence.  
After the upgrade https://github.com/trilinos/Trilinos/pull/9836,  the same code needs a fence before Kokkos::sort.  

The new version of Kokkos has a different rule in try_std_sort for determining whether sorting can be done on the host.  That rule is likely making a different decision from the old version.  In the old version, the view had to be HostSpace; in the new version, it only needs to be HostAccessible.  Thus, a fence is now needed.  The fence should be before the call to std::sort in try_std_sort, rather than in the user's code.

**Comment by masterleinad** [comment]
Fixed in https://github.com/kokkos/kokkos/pull/4490.

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/d94cc8da9af13b32e318624fb41dc1ec60129aec/algorithms/src/Kokkos_Sort.hpp#L536

**Comment by kddevin** [comment]
Can the fix be patched into Trilinos?

**Comment by crtrott** [comment]
Yeah since we didn't release yet we are trying to snapshot it in now. #4528

**Comment by ajpowelsnl** [comment]
Morning All -- Can we now close this issue, since it was cherry-picked into Kokkos 3.5?

**Comment by kddevin** [comment]
Yes; the Zoltan2 jobs that were failing now complete.  Thanks.
