### ISSUE TITLE
Nightly Hip builds unit tests seg fault

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4527]
Nightly builds with the Hip backend have all unit tests seg faulting. Bisecting commits show this began after #4365 

**Reproducer** (MI100):
```
module load cmake/3.19.3 rocm/4.3.0

cmake -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_CXX_FLAGS="-O3 -Werror" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_HIP=ON -DKokkos_ARCH_VEGA908=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF $KOKKOS_PATH
```

**Comment by crtrott** [comment]
@Rombur @masterleinad Any ideas?

**Comment by crtrott** [comment]
Can you two check if you can reproduce?

**Comment by masterleinad** [comment]
I can't reproduce on `spock`.

**Comment by Rombur** [comment]
I can't reproduce either on `tulip`

**Comment by ajpowelsnl** [comment]
Hi @Rombur , @masterleinad -- Would you please confirm that you have enabled the large memory tests:

`-DKokkos_ENABLE_LARGE_MEM_TESTS=ON `

**Comment by Rombur** [comment]
Yes, I configured exactly the same way. I copy/paste it

**Comment by masterleinad** [comment]
> Yes, I configured exactly the same way. I copy/paste it

Me, too.

**Comment by ldh4** [comment]
I was getting some segfaults when running HIP unit-tests on Caraway last week, but after rebasing on top of the latest `Develop` branch just now, I am no longer getting the segfault.

**Comment by ajpowelsnl** [comment]
Morning -- Is it safe to close this issue?  Can we point to specific changes in the update that might have fixed the problem?

**Comment by masterleinad** [comment]
@ndellingwood Can you please check if this issue is fixed now?

**Comment by ndellingwood** [comment]
I think the changes from #4591 must have resolved this issue. Interestingly, I never observed this problem with any of our nightly tests on Power9. Closing.
