### ISSUE TITLE
Rework Scratch / Chunk Interface

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#453]
API Review resulted in preferring:

``` C++
TeamPolicy<>(N,T,ScratchRequest(Level,PerTeam,PerThread))
```

instead of setter functions. Preliminary compile time checks are looking good, but a little more needs to be done.

**Comment by crtrott** [comment]
On the other hand a couple proposals which are prototypes for C++ standard go with modifier functions. For example HPX and agency (from NVIDIA). It looks more like this:

```
for_each(par.on(executor).with(static_schedule()), Functor)
```

**Comment by hcedwar** [comment]
**Use variadic argument list!!**
