### ISSUE TITLE
Abstraction layer for load balancing

### ISSUE THREAD

**Issue by hamidrezanorouzi** [kokkos/kokkos#4530]
Hi, 
I don't know if the matter that I am going to explain here is one of the goals in Kokkos or it is a completely un-relevant feature. Here I explain all I have in my mind for a while that I still have not found a nice solution for it.
When we develop an application in the shared-memory fashion, we are limited to the resource of a single machine/device. This constraint, however, bring some features like high rate of memory access and data transfer. This is specially the case for GPUs where we can get the best performance from their massively-parallel architecture. The problem with these devices is the limited memory resources which in turn limit the simulation size. The obvious solution here would be going for a device with a larger memory (which is expensive and still has limitations) or going for multiple GPUs (which seems a reasonable approach).
There are a number of solutions for multiple GPU computations (for load balancing and data passing): some technologies like  NVlink (in case of nvidia GPUs) for direct transfer of data, or MPI for data transfer through host memory (in the same machine) or through a network (among discrete machines). I am thinkin about an abstraction layer with a unified API for such communications and data transfers, in which the best data transfer protocol is used based on the available hardware and communication paths between devices. Now these are the questions:
1) Is Kokkos projecting for such capabilities?
2) Is this really practical at least with limited features?
3) Is there any tool (rather than basic technologies like MPI) that can interact with Kokkos without any problem for load balancing and data transfer? 

Thanks

**Comment by crtrott** [comment]
Generally most of our apps to MPI and they usually burry MPI in their own communication layer. We also have a project which incorporates PGAS semantics (kokkos-remote-space) into Views. 

Then there are load balancing libraries inside of Trilinos which know how to interact with Kokkos too. 

Kokkos Core is not intended to deal with multi processor issues and does not currently support multiple GPUs.

**Comment by hamidrezanorouzi** [comment]
Thanks for the reply. I will give them a try to see how I can implement these tools alongside Kokkos.
