### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by Fyz01** [kokkos/kokkos#4534]
Hello，I have read some information about Kokkos. I have a question that Kokkos supports for heterogeneous computing? If it can, where it is reflected?

**Comment by masterleinad** [comment]
Kokkos runs on a variety of platforms and multiple backends can be used within the same program but one kernel cannot be split across multiple devices. You can find a good overview of Kokkos at https://kokkos.link/the-lectures. For specific reaching out on Slack (https://kokkosteam.slack.com) works best.
