### ISSUE TITLE
Set up Qthread nightly testing

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#454]
Using the baseline version of Qthreads set up nightly testing

**Comment by hcedwar** [comment]
Should have new version of Qthreads with capability in the main branch by mid-October.

**Comment by gmackey** [comment]
This ticket is linked to #366.  When the first subset of the updates to Qthreads is finished, the nightly testing for that subset will be turned on.  As more subsets of the Qthreads backend are implemented, they will be turned on in the nightly testing as well.

**Comment by ibaned** [comment]
Closing until we get stronger motivation behind Qthreads
