### ISSUE TITLE
Compilation slowdown with HIP backend

### ISSUE THREAD

**Issue by markdewing** [kokkos/kokkos#4546]
Compiling for the HIP backend went from a few minutes to 90 minutes.

Using git bisect shows commit fcccfd20be38eb6b7f96ff72a125edb92c7b593d is responsible.

Breaking into the compiler with gdb shows `AMDGPUPropagateAttributesLatePass` is where the time is being spent.   It happens with Rocm 4.5 and 4.3.

The project is here: https://github.com/cms-patatrack/pixeltrack-standalone
The files/functions involved:
- https://github.com/cms-patatrack/pixeltrack-standalone/blob/master/src/kokkos/test/kokkos/testEigenGPU.cc  The problem is with the kernelCircleFit function, which calls the Circle_fit function in
  - https://github.com/cms-patatrack/pixeltrack-standalone/blob/master/src/kokkos/plugin-PixelTriplets/kokkos/RiemannFit.h

Short reproducer instructions:
- modify ROCM_BASE, KOKKOS_DEVICE_PARALLEL in makefile (or on command line). 
- by default the makefile pulls in and builds a version of kokkos that does not show the issue (will be stored in 'external/kokkos').  Either modify the version that it downloads (look for the 'external_kokkos' target), or modify KOKKOS_BASE and KOKKOS_BUILD to point to another location.
- `make kokkos`

The compile time can be reduced for exploration. The test case in `testEigenGPU.cc` instantiates the test code for three values of a template parameter.  Leave only one value in `main` (e.g. `testFit<4>();`) and the compile time is about 15 minutes.

If necessary, I can reduce the code to a minimal test case or provide more detailed instructions. 

Ultimately it is likely an issue with the HIP compiler, but something in kokkos sets up the conditions for it to happen.

**Comment by ajpowelsnl** [comment]
Good morning @crtrott and @dalg24 - do we have a point of contact for HIP compiler issues?

**Comment by dalg24** [comment]
@Rombur and @arghdos

**Comment by crtrott** [comment]
So the thing is that the HIP compiler is bad in its default decisions, and AMD recommended an approach to fix that using LaunchBounds which are compile-time per-kernel properties. But that involved instantiatiating the kernel for multiple LaunchBounds, and thus compiling the kernel multiple times. We overlooked the repercussions here, while we generally used to be pretty conscious about not instantiating kernels multiple times in the CUDA backend. 

We are now investigating opt-in mechanisms for this optimization (which makes a big performance impact on a number of apps). We are looking at both global opt-in and per-kernel opt-in. The default will be not to compile multiple versions.

**Comment by arghdos** [comment]
I would suggest an additional direction to look into.

I don't think we have much, if any strong evidence that the various kernel launch mechanisms present in the CUDA backend make much of an impact on the HIP side.  Since there are three kernels (one for each launch mechanism), and each has two instantiations, we should also consider _testing_ whether there is any substantial performance impact when we just say, map all of the launch mechanisms onto Local, versus forcing an opt-in for the block-size overloads.

**Comment by crtrott** [comment]
@arghdos: isn't the launch mechanism thing a purely compile time decision and thus does not add additional compilation time?

**Comment by crtrott** [comment]
Oh and just to make clear we are adding this as a high priority issue for us to fix.

**Comment by arghdos** [comment]
Ok, you're right @crtrott, sorry -- I thought they all got instantiated, but it looks like it's all `constexpr` resulting in only one launcher type per kernel.

One thing I did notice was that we have roughly 28 different `View[Copy|Value|Fill]` kernels per-TU that absolutely do not need the overload, but I think we'll have to back out the overloads and opt-in as needed.

**Comment by Rombur** [comment]
@markdewing I cannot compile your code. Does https://github.com/kokkos/kokkos/pull/4644 fixes the problem?

**Comment by markdewing** [comment]
@Rombur Yes, this fixes the compile time problem.  From 161 minutes using the Kokkos develop branch to 6 minutes with the PR.

**Comment by Rombur** [comment]
@markdewing Great. Thank you for the help.

**Comment by crtrott** [comment]
@markdewing is this basically back to what we had with the code before we introduced that multi instantiation? Also do you see compile time differences between ROCM 4.3 and ROCM 4.5?

**Comment by PhilMiller** [comment]
Fix released in 3.6
