### ISSUE TITLE
Add Clang 4.0+ compilation of Cuda code

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#455]
Clang can now directly compile cuda. I have code lying around which kind of works for a lot of things, but it would need to be folded back into master. I don't expect it to work for everything right now, but start moving the code in the right direction will help us steer compiler development.

**Comment by hcedwar** [comment]
Must have nightly testing

**Comment by crtrott** [comment]
I just pushed a "clang-cuda" branch which with a single test removed passes all unit and performance tests of Kokkos (some examples don't compile due to lambda issues).

**Comment by crtrott** [comment]
Need to fix it to compile with nvcc again. Main issue is that nvcc doesn't like a __device__ function and a host function to exist at the same time, while clang is fine with that.

**Comment by crtrott** [comment]
Ok looks like I need to compile TestCuda_c.cpp with -O0 to get it to pass (which I did before). With -O1 or higher the arbitrary atomics and the team_scan fail.

**Comment by crtrott** [comment]
So I got the normal Cuda backend working again.

**Comment by crtrott** [comment]
Filed bug related to arbitrary atomics (in the reproducer O1 works but O2 fails).
https://llvm.org/bugs/show_bug.cgi?id=30564

**Comment by crtrott** [comment]
Ok the bug for arbitrary atomics was determined to be due to reliance on compiler behaviour. I got a new implementation which makes that go away, which I believe does not rely on specific compiler behaviour.

**Comment by crtrott** [comment]
So I got all tests passing now other than nested views. This is with clang commit b221f48436c383d7d8d522bc51faa1d58dd2278f
and llvm commit
f6a95d4da82ce484eb49ad15be61feb985cd52c5

But: I had to semi revert a commit which disallowed extern __shared__ which I think is actually required to use dynamically sized (i.e. user requested) shared memory. The diff is:
```
diff --git a/lib/Sema/SemaDeclAttr.cpp b/lib/Sema/SemaDeclAttr.cpp
index 21cace4..6b99c6c 100644
--- a/lib/Sema/SemaDeclAttr.cpp
+++ b/lib/Sema/SemaDeclAttr.cpp
@@ -3714,10 +3714,10 @@ static void handleSharedAttr(Sema &S, Decl *D, const AttributeList &Attr) {
                                                  Attr.getName()))
     return;
   auto *VD = cast<VarDecl>(D);
-  if (VD->hasExternalStorage()) {
-    S.Diag(Attr.getLoc(), diag::err_cuda_extern_shared) << VD;
-    return;
-  }
+  //if (VD->hasExternalStorage()) {
+  //  S.Diag(Attr.getLoc(), diag::err_cuda_extern_shared) << VD;
+  //  return;
+  //}
   D->addAttr(::new (S.Context) CUDASharedAttr(
       Attr.getRange(), S.Context, Attr.getAttributeSpellingListIndex()));
 }
```

A bug is filed against clang here: https://llvm.org/bugs/show_bug.cgi?id=30591

**Comment by crtrott** [comment]
C++17 [=,*this] capture works now with Clang for Cuda, and also with __host__ __device__
That means the following code runs correct:

```C++
#include<Kokkos_Core.hpp>

template<class ExecSpace>
struct Foo {
  int val;
  Foo(int val_):val(val_) {}
  int compute(int N) {
    int sum;
    Kokkos::parallel_reduce(Kokkos::RangePolicy<ExecSpace>(0,N), KOKKOS_CLASS_LAMBDA (const int&i, int& lsum) {
      lsum+= i*val;
    },sum);
    return sum;
  }
};

int main() {
  Kokkos::initialize();
  int N = 317;;
  Foo<Kokkos::Cuda> foo_c(3);
  int sum_c = foo_c.compute(N);
  Foo<Kokkos::Serial> foo_s(5);
  int sum_s = foo_s.compute(N);
  printf("Results: %i (%i) %i (%i)\n",sum_c,N*(N-1)/2*3,sum_s,N*(N-1)/2*5);
  Kokkos::finalize();
}
```

**Comment by crtrott** [comment]
Here is some benchmark data from the new synthetic bytes_and_flops benchmark in Kokkos running the 5 suggested configurations. Basically NVCC 8.0 performs the same as Clang. 

```
NKRUFTS: 100000 1024 1 1 1 256 6000 
Time: 0.013127s Bandwidth: 174.359592GiB/s GFlop/s: 15.601432
Time: 0.013113s Bandwidth: 174.545745GiB/s GFlop/s: 15.618089
NKRUFTS: 100000 256 32 1 1 256 6000 
Time: 0.038174s Bandwidth: 479.660158GiB/s GFlop/s: 42.919264
Time: 0.037378s Bandwidth: 489.874977GiB/s GFlop/s: 43.833271
NKRUFTS: 100000 1024 1 8 64 256 6000 
Time: 0.088629s Bandwidth: 25.824712GiB/s GFlop/s: 1199.282402
Time: 0.094073s Bandwidth: 24.330237GiB/s GFlop/s: 1129.879987
NKRUFTS: 20000 256 32 1 1 256 6000 
Time: 0.363819s Bandwidth: 10.065745GiB/s GFlop/s: 0.900668
Time: 0.364046s Bandwidth: 10.059469GiB/s GFlop/s: 0.900106
NKRUFTS: 20000 256 32 1 1 256 6000 
Time: 0.014709s Bandwidth: 248.970656GiB/s GFlop/s: 22.277517
Time: 0.014721s Bandwidth: 248.767704GiB/s GFlop/s: 22.259357
```

**Comment by crtrott** [comment]
Here are some miniMD numbers (I also added NVCC with LDG fallback [i.e. texture objects are disabled as in clang]):

System Size NVCC NVCC-LDG CLANG
LJ 30 45.2 45.0 44.3
LJ 60 53.7 52.7 51.5
EAM 30 19.1 18.8 20.0
EAM 60 22.4 22.2 23.9

Looks like clang again is on par with NVCC, slower in some cases but a good 5% faster in EAM.

**Comment by crtrott** [comment]
Just ran Trilinos with Cuda/NVCC and everything is fine except the expected failure due to some changes which Carter logged as needing accompanying changes in Trilinos.

**Comment by crtrott** [comment]
The extern issue was resolved, so current head clang works for us.

**Comment by crtrott** [comment]
Here is the bug report for the outstanding view of classes issue: https://llvm.org/bugs/show_bug.cgi?id=30593

**Comment by crtrott** [comment]
Also relocatable device code doesn't work: so no Tasks for us.
Bug Report: https://llvm.org/bugs/show_bug.cgi?id=26343

**Comment by crtrott** [comment]
The branch passed full test-suite (i.e. all the other compilers still get through their tests on the modified code).

**Comment by crtrott** [comment]
The branch is merged in. Working on removing some of the WORKAROUND stuff.

**Comment by crtrott** [comment]
Nightly testing is added to Apollo.
