### ISSUE TITLE
_GLIBCXX_NUM_CATEGORIES undefined

### ISSUE THREAD

**Issue by Adrian-Diaz** [kokkos/kokkos#4557]
Greetings,

Recently I was compiling Trilinos and ran into the following:

![image](https://user-images.githubusercontent.com/46537160/143792594-a75a2a2a-4d91-4606-9b7a-67d826801b7d.png)

Any ideas what could be causing that? Thanks in advance for any help rendered.

Adrian

**Comment by dalg24** [comment]
The error message suggests there is a configuration issue with the locale facility on your system.

**Comment by crtrott** [comment]
Yeah this is super unlikely to be a Kokkos issue. One possible issue could be mismatch between compiler and used header files. I.e. for some reason you compile with GCC 7 but the header files its using are coming from GCC 9 or so.

**Comment by Adrian-Diaz** [comment]
Looks like my compiler or libs must've been corrupted at some point. A reinstall fixed it. Thanks for the help!
