### ISSUE TITLE
Move OpenMP 4.5 OpenMPTarget backend into Develop

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#456]
We started developing a OpenMP 4.5 backend with IBM compilers which has a lot of things working. Moving that back into master and doing partial nightly testing will help us to keep track of it.

**Comment by hcedwar** [comment]
Must have nightly testing

**Comment by hcedwar** [comment]
Pending compiler updates

**Comment by hcedwar** [comment]
Still pending compiler updates...
