### ISSUE TITLE
Kokkos installation when added as a CMake subproject

### ISSUE THREAD

**Issue by jrmadsen** [kokkos/kokkos#4566]
So I have a project which builds Kokkos as a CMake subproject but I want to avoid installing the Kokkos headers, CMake config files, and the bin files. How do y'all feel about adding:

```cmake
option(Kokkos_DEVELOPER_INSTALL "When OFF, only install the kokkos runtime libraries" ON)
```

or, for finer grain control:

```cmake
option(Kokkos_INSTALL_HEADERS "Install header files" ON)
option(Kokkos_INSTALL_CONFIG "Install cmake configuration files" ON)
option(Kokkos_INSTALL_BIN "Install bin files (e.g. nvcc_wrapper, etc.)" ON)
```

Basically, the idea is that when these are all OFF, the only thing that would get installed are the runtime libraries. I just want to check before creating a PR.

**Comment by dalg24** [comment]
What is the issue with doing a standard install and copying after into the destination whatever might be relevant?
Can you refer to other projects that may offer such a granularity?

**Comment by nmm0** [comment]
@jrmadsen Would it be sufficient to add a flag `Kokkos_INSTALL` to prevent Kokkos from adding the install targets?

You could then install the components you need with your own install commands since all the targets should be accessible in your CMake.

**Comment by jrmadsen** [comment]
> What is the issue with doing a standard install and copying after into the destination whatever might be relevant?

@dalg24 Sorry for the delay. When Kokkos is a subproject in cmake, it becomes really wonky to do this, especially with CPack.

>  Can you refer to other projects that may offer such a granularity?

Pybind11 has a `PYBIND11_INSTALL` option, my tasking library [PTL](https://github.com/jrmadsen/PTL) and timemory have options to do this. Spack is a good example of where a project might want this... it allows one to have a "vendored" build that won't conflict in an environment.

> Would it be sufficient to add a flag Kokkos_INSTALL to prevent Kokkos from adding the install targets?

@nmm0 This might even be better because it allow one to RPATH to libraries which are hidden from standard LD_LIBRARY_PATH paths, e.g. an executable could set the RPATH to `$ORIGIN/../lib/<project-name/kokkos`.

**Comment by nmm0** [comment]
@jrmadsen Sounds good! I think that's the best path then. I think the installing from a different subdirectory issue only exists with cmake versions before 3.13, according to the 3.13 release notes install(TARGETS) should work without problems. I'm not sure about `export(TARGETS)`
