### ISSUE TITLE
Execution and Memory Space Instances - resource management abstraction and requirements

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#457]

**Comment by hcedwar** [comment]
DARMA needs the abstraction and API to be mappable onto other lightweight threading packages such as Charm++ CTH-threads, Qthreads, etc.

**Comment by hcedwar** [comment]
Interface needs to accommodate non-ownership / external ownership of the underlying threading resources.

**Comment by dsunder** [comment]
This is a template of what I think an Execution space should look like

`#ifndef KOKKOS_EXECUTION_SPACE_HPP
#define KOKKOS_EXECUTION_SPACE_HPP

#include <Kokkos_Macros.hpp>
#if defined( KOKKOS_ENABLE_EXECUTION_SPACE)

#include <...>

/*--------------------------------------------------------------------------*/

namespace Kokkos {

/// \class ExecutionSpace
class ExecutionSpace {
public:

  /// Tag this class as a kokkos execution space
  using execution_space = ExecutionSpace;

  using memory_space = ...;

  /// This execution space preferred device_type
  using device_type          = Kokkos::Device< execution_space, memory_space >;
  using array_layout         = ...;
  using size_type            = memory_space::size_type;
  using scratch_memory_space = ScratchMemorySpace< ExecutionSpace >;

  /// \brief Get a handle to the default execution space instance
  ExecutionSpace();

  /// \brief has the Execution space been initialized
  static bool is_initialized();

  /// \brief in the default instance running a parallel algorithm
  inline static bool in_parallel();

  /// \brief are any of the instances running a parallel algorithm
  template <typename... ExecutionSpaces>
  inline static bool in_parallel( ExecutionSpaces const&... instances );

  /// \brief Wait until all dispatched functors complete on the default instance
  static void fence() {}

  /// \brief Wait until all dispatched functors complete on the given instances
  template <typename... ExecutionSpaces>
  static void fence( ExecutionSpace const&... instances );

  /// \brief  Return the maximum amount of concurrency.
  static int concurrency();

  /// \brief Print configuration information to the given output stream.
  static void print_configuration( std::ostream & );

  /// \brief Print configuration information to the given output stream.
  static void print_verbose_configuration( std::ostream & );

  /// \brief Free any resources being consumed by the device.
  static void finalize();

  /// \brief Initialize the execution space
  ///
  /// Arguments can differ between backends
  template <typename... Args>
  static void initialize( Args &&... args);

  /// \brief Split the default instance into new instances
  ///
  /// All instances are created valid and the default instance
  /// may be updated as necessary to insure this
  ///
  /// When the last split instance is destroyed the default instance
  /// should be restored to its original state
  ///
  /// It is permissable for the result to return duplicated instances
  /// i.e. return an array of default instances
  ///
  /// Implementation and API determined by each ExecutionSpace
  template <typename... InstanceRequests>
  static Array<ExecutionSpace,N> split( InstanceRequests const&... requests );

  //----------------------------------------------------------------------------
  // Only on host execution spaces
  //---------------------------------------------------------------------------

  /// \brief the size of the default instance
  inline static int thread_pool_size();

  /// \brief the size of the given instance
  inline static int thread_pool_size( ExecutionSpace const& );

  /// \brief  The rank of the executing thread in its current instance
  ///
  /// Note: a thread can only belong to a single instance at any time
  KOKKOS_INLINE_FUNCTION static int thread_pool_rank();

  /// \brief Partition the default instance and call 'f' on each new 'master' thread
  ///
  /// Require num_partitions * partition_size <= thread_pool_size()
  /// Func is a functor with the following signiture
  ///
  ///   void( int partition_id, int num_partitions )
  template <typename F>
  static void partition_master( Func const& f
                              , int num_partitions = 0
                              , int partition_size = 0
                              );

  template <typename Request>
  static bool request_default_instance(Request const& request);

  static void release_default_instance();

  /// \brief class to coordinate work between 'master' threads
  ///
  /// SHOULD NOT be used within any parallel algorithm
  ///
  /// This lock must be compatiable with a scoped lock guard
  /// i.e. std::unique_lock<Lock>
  ///
  /// cannot be copied or moved
  /// has the following functions available
  ///
  /// Lock()
  /// ~Lock()
  ///
  /// void lock()
  /// void unlock()
  /// bool try_lock()
  class MasterLock;

  //----------------------------------------------------------------------------
  // On host execution spaces: will be deprecated
  //---------------------------------------------------------------------------

  /// \brief the maximun number of threads available
  KOKKOS_INLINE_FUNCTION
  static int max_hardware_threads();

  /// \brief the current thread's global id
  KOKKOS_INLINE_FUNCTION
  static int hardware_thread_id();

};

} // namespace Kokkos

/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/

namespace Kokkos {
namespace Impl {



template<>
struct MemorySpaceAccess
  < Kokkos::ExecutionSpace::memory_space
  , Kokkos::ExecutionSpace::scratch_memory_space
  >
{
  enum { assignable = ... };
  enum { accessible = ... };
  enum { deepcopy   = ... };
};

template<>
struct VerifyExecutionCanAccessMemorySpace
  < Kokkos::ExecutionSpace::memory_space
  , Kokkos::ExecutionSpace::scratch_memory_space
  >
{
  enum { value = ... };
  // inline static void verify( void ) { }
  // inline static void verify( const void * ) { }
};

} // namespace Impl
} // namespace Kokkos

/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/

#include <ExecutionSpace/...>

#endif /* #if defined( KOKKOS_ENABLE_EXECUTION_SPACE ) */
#endif /* #ifndef KOKKOS_EXECUTION_SPACE_HPP */
`
