### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by burhop** [kokkos/kokkos#4597]
New to using Kokkos and Trilinos so be gentle :-)  This is probably some newbie problem. Feel free to point me to the right place to asks these types of questions or how to get added to the Kokkos Slack forum if that is the right place.

I'm getting a link error from this simple example for KokkosBlas::scal

```C++
#include<Kokkos_Core.hpp>
#include<KokkosBlas1_scal.hpp>

int main(int argc, char* argv[]) {
   Kokkos::initialize();

   int N = atoi(argv[1]);

   Kokkos::View<double*> x("X",N);
   Kokkos::View<double*> y("Y",N);
   Kokkos::deep_copy(x,3.0);

   KokkosBlas::scal(y,1.5,x);

   double sum = 0.0;
   Kokkos::parallel_reduce("CheckValue", N, KOKKOS_LAMBDA (const int& i, double& lsum) {
     lsum += y(i);
   },sum);

   printf("Sum: %lf Expected: %lf Diff: %e\n",sum,1.0*N*4.5,sum-1.0*N*4.5);

   Kokkos::finalize();
}
```

**The Error is:**
```
/work/ext/trilinos/Trilinos-MPI-CUDA-DEBUG-INSTALL-mpi4/include/KokkosBlas1_scal.hpp:106: undefined reference to `KokkosBlas::Impl::Scal<Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaUVMSpace>, Kokkos::MemoryTraits<1u> >, double, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaUVMSpace>, Kokkos::MemoryTraits<1u> >, 1, false, true>::scal(Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaUVMSpace>, Kokkos::MemoryTraits<1u> > const&, double const&, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaUVMSpace>, Kokkos::MemoryTraits<1u> > const&)'
```

I'm guessing I don't have the right options when building the kokkos libraries and the right template instantiations are not there.  Here is what I have with the Cuda options being turned on (as far as I know).

```
cmake \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D CMAKE_INSTALL_PREFIX:FILEPATH=$TRILINOS_INSTALL \
  -D CMAKE_CXX_COMPILER=${MPI_PREFIX}/bin/mpicxx \
  -D CMAKE_C_COMPILER=${MPI_PREFIX}/bin/mpicc \
  -D CMAKE_Fortran_COMPILER=${MPI_PREFIX}/bin/mpif90 \
  -D CMAKE_EXE_LINKER_FLAGS="-lstdc++ -lm" \
  -D Trilinos_EXTRA_LINK_FLAGS="-lm -lstdc++" \
  -D MPI_CXX_LINK_FLAGS="-L${MPI_PREFIX}/lib -lm -lmpi -lmpi_cxx -lstdc++" \
  -D Trilinos_CXX11_FLAGS:STRING="-L${MPI_PREFIX}/lib -lm -lmpi -lmpi_cxx -std=c++11 -expt-extended-lambda -lineinfo" \
  -D CMAKE_CXX_FLAGS="-g" \
  -D LDFLAGS="-L${MPI_PREFIX}/lib -lm -lmpi -lmpi_cxx -lopen-rte -lopen-pal -lutil -lnsl -ldl" \
  -D Trilinos_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_LIBRARIES=/usr/local/lib/openmpi \
  -D TPL_ENABLE_CUDA=ON \
  -D KOKKOS_ARCH="Maxwell52" \
  -D KOKKOS_ENABLE_PARALLEL=ON \
  -D KOKKOS_ENABLE_Cuda=ON \
  -D KOKKOS_ENABLE_SERIAL=ON \
  -D Kokkos_ENABLE_Cuda_UVM=ON \
  -D KOKKOS_ENABLE_Cuda_Lambda:BOOL=ON \ 
  -D KOKKOS_ENABLE_CXX11=ON \
  -D Trilinos_ENABLE_KokkosExample=OFF \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_kokkosKernels:BOOL=ON \
  -D KokkosKernels_REQUIRE_DEVICES =CUDA \
  -D KokkosKernels_REQUIRE_OPTIONS=cuda_relocatable_device_code \
  -D KokkosKernels_ENABLE_TPL_BLAS:BOOL=ON \
  -D Kokkos_ENABLE_TESTS:BOOL=OFF \
  -D Kokkos_ENABLE_TSQR:BOOL=ON \
  -D TPL_ENABLE_MKL:BOOL=OFF \
  -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
  -D TPL_ENABLE_Pthread:BOOL=OFF \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_LIBRARY_DIRS:FILEPATH="/usr/lib/x86_64-linux-gnu/boost169" \
  -D Boost_INCLUDE_DIRS:FILEPATH="/usr/include/boost169" \
  -D DART_TESTING_TIMEOUT:STRING=600 \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_DEBUG:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=OFF \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Teuchos_ENABLE_EXAMPLES:BOOL=ON \
  -D Teuchos_ENABLE_TESTS:BOOL=OFF \
  -D TSQR_ENABLE_Fortran:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
```

I did check I'm picking up the kokkos libs and that I'm not getting a different one than I think.

**Comment by dalg24** [comment]
This is something that really should be reported on the KokkosKernels (or Trilinos) side and you probably want to include more information about how to build the snippet you posted and what the link line that gave the error looked like.

The header `<KokkosBlas1_scal.hpp>` belongs to KokkosKernels but I can see how the name is misleading.

**Comment by burhop** [comment]
I can do that.  BTW, do you know who owns the slack group?  My domain is siemens.com so I'm not automatically admitted and need an invite.

**Comment by ajpowelsnl** [comment]
Morning @brian-kelley and @lucbv - Would you please have a look at this bug, and see if you can help this user out?

**Comment by burhop** [comment]
I doubt this is a 'bug'.  Most likely an (ignorant use) 'question' .

**Comment by dalg24** [comment]
> BTW, do you know who owns the slack group? My domain is siemens.com so I'm not automatically admitted and need an invite.

Email me (`lebrungrandt <at> ornl <dot> gov`) or Christian (his address is in the copyright notice on all files of this repo)

**Comment by brian-kelley** [comment]
@burhop Did you install Trilinos and then build this example using it, or is this example inside Trilinos? Either way, try adding this option:
```
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
```
which is what we typically test with in Trilinos.

**Comment by mhoemmen** [comment]
@burhop btw, you'll want to be sure that all nontrivially constructed `Kokkos::View` instances are out of scope before `Kokkos::finalize` is called.

**Comment by ajpowelsnl** [comment]
> @burhop btw, you'll want to be sure that all nontrivially constructed `Kokkos::View` instances are out of scope before `Kokkos::finalize` is called.

Morning Mark -- For the benefit of people who are new to Kokkos, what exactly would a "non-trivially" constructed `Kokkos::View` be?

**Comment by mhoemmen** [comment]
@ajpowelsnl wrote:
> Morning Mark -- For the benefit of people who are new to Kokkos, what exactly would a "non-trivially" constructed Kokkos::View be?

Good morning! : - )  I should have written "not default constructed."

What I mean is, a `Kokkos::View`'s destructor will be called at the end of the scope.  If that scope includes a call to `Kokkos::finalize`, then the destructor will be called after `Kokkos::finalize` has been called.  "Doing Kokkos things" after `finalize` has been called is a Bad Idea.  (It's like calling general `MPI_*` functions after `MPI_Finalize` has been called.)

**Comment by burhop** [comment]
BTW, for any future googlers stumbling on this thread, after updating to the latest Trilinos (13.1 which included Kokkos), updating  cmake and updating C++ standard to C++14, the the linking problem went away.
