### ISSUE TITLE
Variants of create_mirror* routines taking execution space argument

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#4604]
The `create_mirror*` routines potentially allocate, initialize, and copy the contents of a `View` or similar container. They should have forms that take an execution space on which to do that work

**Comment by PhilMiller** [comment]
Not clear how to arrange the parameters for the overloads that don't currently take a (memory) `Space` parameter at all. Maybe I'll just omit those.

**Comment by crtrott** [comment]
Overload set:
```c++
// also all of them with WithoutInit
resize(view, ...);
resize(exec, view, ...);
realloc(view, ...);
realloc(exec, view, ...);
realloc(ConstrArgs, view, ...)
create_mirror[_view](view);
create_mirror[_view](device, view); // return View<DataType, Device>
create_mirror[_view]_and_copy(view);
create_mirror[_view]_and_copy(device, view); // return View<DataType, Device>
```

```c++
//Lets do this as asynchronous 
create_mirror_view(WithoutInit, view);
deep_copy(exec, copy, 0.);
```

**Comment by ajpowelsnl** [comment]
Morning Phil - May I add the "InDevelop" label for this issue?

**Comment by masterleinad** [comment]
The conclusion from the last meeting was that we don't need this. I don't think there it's necessary to do anything here.

**Comment by ajpowelsnl** [comment]
OK, thank you.  I'll update the notes.
