### ISSUE TITLE
Kokkos updates break configuration with Trilinos

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4609]
Following merge of #4341, builds of Trilinos with Kokkos' develop branch fail to configure with the following messages:

```
18:32:42 CMake Error at kokkos/cmake/kokkos_tribits.cmake:249 (SET_SOURCE_FILES_PROPERTIES):
18:32:42   SET_SOURCE_FILES_PROPERTIES called with incorrect number of arguments.
18:32:42 Call Stack (most recent call first):
18:32:42   kokkos/core/unit_test/CMakeLists.txt:724 (KOKKOS_ADD_TEST_EXECUTABLE)
18:32:42 
18:32:42 
18:32:42 CMake Error at kokkos/cmake/kokkos_tribits.cmake:249 (SET_SOURCE_FILES_PROPERTIES):
18:32:42   SET_SOURCE_FILES_PROPERTIES called with incorrect number of arguments.
18:32:42 Call Stack (most recent call first):
18:32:42   kokkos/core/unit_test/CMakeLists.txt:789 (KOKKOS_ADD_TEST_EXECUTABLE)
```

This can be reproduced by overriding the Kokkos package in Trilinos to instead use the develop branch https://github.com/kokkos/kokkos/wiki/Compiling#building-trilinos-with-kokkos-develop-branch, and enabling Kokkos and Kokkos' unit tests (any compiler and backend will reproduce)

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/pull/4610#issuecomment-992904654
