### ISSUE TITLE
Can force all floating point variable to double instead of float?

### ISSUE THREAD

**Issue by MJChku** [kokkos/kokkos#4624]
Can force all floating point variable to double instead of float?

**Comment by masterleinad** [comment]
No, it's not possible to change all floating operations in `Kokkos` to use `float` but most interfaces are templated on the number type anyway and you can, of course, use `float`. Is there a specific example that you care about the precision of floating operations in `Kokkos` for?

**Comment by MJChku** [comment]
Actually I want all double. I have a system that substitute floating point instructions in Kokkos binary library to arbitrary precision, however, in theory I require every floating point instruction to be double.

**Comment by crtrott** [comment]
No there is no way to enforce that in a code. I don't think our library itself has any floating point stuff with single precision compiled in, however. Thats an application thing downstream.
