### ISSUE TITLE
atomic_load and atomic_store

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#463]
The C++ standard uses `atomic_load` and `atomic_store` with sequential consistency to memory fence a load or store operation.
Implement `Kokkos::atomic_load` and `Kokkos::atomic_store`.
Replace `Kokkos::volatile_load` and `Kokkos::safe_load` functions with `Kokkos::atomic_load`.
Replace usage of write to volatile variable followed by a `Kokkos::memory_fence` with `Kokkos::atomic_store`.
The **enhanced-memory-primitives** branch has X86 assembly supporting these operations and introduced several `atomic_store` operations where they were missing.
Delete **enhanced-memory-primitives** once this enhancement is done.

**Comment by hcedwar** [comment]
C++17 atomic free function spec:
`
// 29.6.1, general operations on atomic types
bool atomic_is_lock_free(const volatile atomic-type *) noexcept;
bool atomic_is_lock_free(const atomic-type *) noexcept;
void atomic_init(volatile atomic-type *, T) noexcept;
void atomic_init(atomic-type *, T) noexcept;
void atomic_store(volatile atomic-type *, T) noexcept;
void atomic_store(atomic-type *, T) noexcept;
void atomic_store_explicit(volatile atomic-type *, T, memory_order) noexcept;
void atomic_store_explicit(atomic-type *, T, memory_order) noexcept;
T atomic_load(const volatile atomic-type *) noexcept;
T atomic_load(const atomic-type *) noexcept;
T atomic_load_explicit(const volatile atomic-type *, memory_order) noexcept;
T atomic_load_explicit(const atomic-type *, memory_order) noexcept;
T atomic_exchange(volatile atomic-type *, T) noexcept;
T atomic_exchange(atomic-type *, T) noexcept;
T atomic_exchange_explicit(volatile atomic-type *, T, memory_order) noexcept;
T atomic_exchange_explicit(atomic-type *, T, memory_order) noexcept;
bool atomic_compare_exchange_weak(volatile atomic-type *, T*, T) noexcept;
bool atomic_compare_exchange_weak(atomic-type *, T*, T) noexcept;
bool atomic_compare_exchange_strong(volatile atomic-type *, T*, T) noexcept;
bool atomic_compare_exchange_strong(atomic-type *, T*, T) noexcept;
bool atomic_compare_exchange_weak_explicit(volatile atomic-type *, T*, T,memory_order, memory_order) noexcept;
bool atomic_compare_exchange_weak_explicit(atomic-type *, T*, T,memory_order, memory_order) noexcept;
bool atomic_compare_exchange_strong_explicit(volatile atomic-type *, T*, T,memory_order, memory_order) noexcept;
bool atomic_compare_exchange_strong_explicit(atomic-type *, T*, T,memory_order, memory_order) noexcept;

// 29.6.3, arithmetic operations on atomic types
integral atomic_fetch_add(volatile atomic-integral *, integral ) noexcept;
integral atomic_fetch_add(atomic-integral *, integral ) noexcept;
integral atomic_fetch_add_explicit(volatile atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_add_explicit(atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_sub(volatile atomic-integral *, integral ) noexcept;
integral atomic_fetch_sub(atomic-integral *, integral ) noexcept;
integral atomic_fetch_sub_explicit(volatile atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_sub_explicit(atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_and(volatile atomic-integral *, integral ) noexcept;
integral atomic_fetch_and(atomic-integral *, integral ) noexcept;
integral atomic_fetch_and_explicit(volatile atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_and_explicit(atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_or(volatile atomic-integral *, integral ) noexcept;
integral atomic_fetch_or(atomic-integral *, integral ) noexcept;
integral atomic_fetch_or_explicit(volatile atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_or_explicit(atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_xor(volatile atomic-integral *, integral ) noexcept;
integral atomic_fetch_xor(atomic-integral *, integral ) noexcept;
integral atomic_fetch_xor_explicit(volatile atomic-integral *, integral , memory_order) noexcept;
integral atomic_fetch_xor_explicit(atomic-integral *, integral , memory_order) noexcept;
`

**Comment by crtrott** [comment]
Wait, does this still require atomic types?

**Comment by hcedwar** [comment]
C++17 standard will still requires atomic types - working the issue for next standard.
Need to move our atomic free functions into alignment with these free functions in preparation for (someday) replacement by C++20 standard.
Start with `atomic_load` and `atomic_store`, then incrementally revise others.

**Comment by hcedwar** [comment]
Alignment with standard will help with explanation, such as #782

**Comment by keitat** [comment]
I see something about Kokkos::atomic_compare_exchange in the latest source.  Is it working?

**Comment by ibaned** [comment]
@keitat I would say that any function in the current source (especially the public namespace) is working and has been well-tested. I don't think however that the full spirit of this issue is complete, as I don't think all of @dsunder's changes have made it in yet.

**Comment by dsunder** [comment]
Use atomic_ref
