### ISSUE TITLE
Allow C++1Z Flag for Class Lambda capture

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#465]
This is to allow [=,*this] capture with proposed c++17 (currently enabled via c++1z in most compilers). Will rename this to C++17 when this happens in compilers.

**Comment by crtrott** [comment]
This will probably come in with a merge from cuds-clang branch.

**Comment by hcedwar** [comment]
Use
`KOKKOS_LAMBDA` for non-member and static member functions
`KOKKOS_MEMBER_LAMBDA` or `KOKKOS_LAMBDA_MEMBER` for non-static member functions.

**Comment by crtrott** [comment]
I used KOKKOS_CLASS_LAMBDA, and personally think that is less confusing for C++ novices. Other opinions?

**Comment by crtrott** [comment]
Also I was wondering if we should just make it C++17 right away and simply use the correct c++1z flag underneath if the compiler doesn't have c++17 flag yet.

**Comment by hcedwar** [comment]
Other names to consider before finalizing...
`KOKKOS_LAMBDA_IN_CLASS`

**Comment by crtrott** [comment]
Need to add a unit test.

**Comment by dsunder** [comment]
I vote for KOKKOS_CLASS_LAMBDA.

**Comment by mhoemmen** [comment]
I vote for KOKKOS_CLASS_LAMBDA too.

**Comment by hcedwar** [comment]
Issue: there is no such thing as a "class lambda"
There are two distinct kinds of lambdas:

1. within the scope of a function that is not a class member, or a static member
2. within the scope of a non-static class member function

**Comment by crtrott** [comment]
There is also no such thing as a "member lambda" ;-)

**Comment by mhoemmen** [comment]
> Issue: there is no such thing as a "class lambda"

How about KOKKOS_INSTANCE_LAMBDA? or KOKKOS_THIS_LAMBDA?

**Comment by hcedwar** [comment]
`KOKKOS_LAMBDA`  when not capturing `*this`
`KOKKOS_LAMBDA_THIS` when capturing `*this`

**Comment by crtrott** [comment]
I am unsure about the THIS thing, most users are probably not aware that there is a "this" thingy in every class. How often does a normal developer use this-> ? I want a name that the less experienced C++ developer can easily associate with the use case for the macro.

**Comment by mhoemmen** [comment]
@crtrott wrote:
> How often does a normal developer use this-> ?

You need it when calling a base-class method in a template class inheriting from a templated class.  Otherwise, you don't need it :-)  Use of "this->" a lot smells of Perl or Python OOP.

**Comment by crtrott** [comment]
yeah I know Mark, but I don't know many people who do much with inheritance.

**Comment by hcedwar** [comment]
Thinking "outside the box" - don't even provide a `KOKKOS_LAMBDA`
`[=] KOKKOS_FUNCTION ( ...args... )`
`[=,*this] KOKKOS_FUNCTION ( ...args... )`

1. Is fewer macros.
2. Hides less of the standard - developers should be aware of standard features they are using.
3. Is more future proof with respect to options for named capture variables.

**Comment by mhoemmen** [comment]
@hcedwar can't complain about that.  On the other hand, users may not understand the subtlety of & capture...

**Comment by crtrott** [comment]
Yeah in principle I like it as well. The only problem I see is capture by reference, which will work fine in most situations on the CPU, will runtime crash on current GPUs, and run slow on future GPUs (with NVLINK capture by reference is legal, but access will be slow, and through indirection).

**Comment by hcedwar** [comment]
That is Kokkos-user education about how to properly use the standard language features for portability - just like educating them that `operator()` must have `KOKKOS_FUNCTION` and must be `const`.

**Comment by hcedwar** [comment]
This only works for CUDA 8, which officially supports proper `__host__ __device__` lambdas, before it was only `__device__` lambdas, which was a portability problem.
Now that CUDA 8 is released I suggest that for portable lambdas we **require** CUDA 8, then all is good.

**Comment by crtrott** [comment]
No it doesn't work. Because [=,*this] __host__ __device__ doesn't work ....

**Comment by crtrott** [comment]
On Cuda 8 we are for the most part still restricted to [=,*this] device, since non of the supported host compilers support [=,*this]

**Comment by hcedwar** [comment]
Cannot remove KOKKOS_LAMBDA in favor of `[=,*this] KOKKOS_FUNCTION` until CUDA 8 is the minimum version supported.

Another option: `KOKKOS_LAMBDA_THIS`
