### ISSUE TITLE
Error using custom reduction on an array

### ISSUE THREAD

**Issue by yencal** [kokkos/kokkos#4669]
Error using custom reduction on an array as specified in the [kokkos wiki](https://github.com/kokkos/kokkos/wiki/Custom-Reductions%3A-Built-In-Reducers-with-Custom-Scalar-Types). I have adapted the example for my application as shown below. Specifically I would like to point your attention to `typedef array_type<double,3> ValueType;` and the `RangePolicy`. The following code below works fine if built with OpenMP backend however when built with CUDA backend it throws the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaStreamSynchronize(m_stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered 
```
Now, if `typedef array_type<double,3> ValueType;` is changed to `typedef array_type<int,3> ValueType;` the code works fine for both OpenMP and CUDA backend. Also, if the `1D RangePolicy` (commented out below) is used instead of the `3D RangePolicy`, the code works fine for both OpenMP and CUDA backend. Please, what is going on here?

Machine info: Tesla V100 CUDA/11.0

```
namespace sample {  // namespace helps with name resolution in reduction identity 
   template< class ScalarType, int N >
   struct array_type {
     ScalarType the_array[N];
  
     KOKKOS_INLINE_FUNCTION   // Default constructor - Initialize to 0's
     array_type() {
       for (int i = 0; i < N; i++ ) { the_array[i] = 0; }
     }
     KOKKOS_INLINE_FUNCTION   // Copy Constructor
     array_type(const array_type & rhs) { 
        for (int i = 0; i < N; i++ ){
           the_array[i] = rhs.the_array[i];
        }
     }
     KOKKOS_INLINE_FUNCTION   // add operator
     array_type& operator += (const array_type& src) {
       for ( int i = 0; i < N; i++ ) {
          the_array[i]+=src.the_array[i];
       }
       return *this;
     } 
     KOKKOS_INLINE_FUNCTION   // volatile add operator 
     void operator += (const volatile array_type& src) volatile {
       for ( int i = 0; i < N; i++ ) {
         the_array[i]+=src.the_array[i];
       }
     }
   };
   typedef array_type<double,3> ValueType;  // used to simplify code below
}

namespace Kokkos { //reduction identity must be defined in Kokkos namespace
   template<>
   struct reduction_identity< sample::ValueType > {
      KOKKOS_FORCEINLINE_FUNCTION static sample::ValueType sum() {
         return sample::ValueType();
      }
   };
}

int main( int argc, char* argv[] )
{
  // int E = 1024;
  int E = 5;
  Kokkos::initialize( argc, argv );
  {
    sample::ValueType tr;         
    //Kokkos::parallel_reduce( E, KOKKOS_LAMBDA (const int& i, 
    //                                           sample::ValueType & upd) {
    Kokkos::parallel_reduce(
    Kokkos::MDRangePolicy<Kokkos::Rank<3,LOOP_ORDER,LOOP_ORDER>>({0,0,0}, {E,E,E}),
    KOKKOS_LAMBDA(const int k, const int j, const int i, sample::ValueType & upd) {
      for(int j = 0; j < 3; j++) {
        upd.the_array[j] += 1;
      }
    }, Kokkos::Sum<sample::ValueType>(tr) );

    for(int j = 0; j < 3; j++) {
      printf("tr.the_array[%d] = %d\n", j, int(tr.the_array[j]));
    }  
  }
  Kokkos::finalize();

  return 0;
}
```

**Comment by ajpowelsnl** [comment]
Hello @yencal -- I'm having a look at your issue.  Which version of Kokkos did you use?

**Comment by yencal** [comment]
Hi @ajpowelsnl, I used Kokkos v. 3.5.0.

**Comment by crtrott** [comment]
Can you provide more information about your build. Exact build commands, GCC version underneath, CUDA driver version? We can't reproduce this.

**Comment by yencal** [comment]
My apologies I was using Kokkos v. 3.2.01 after upgrading to v. 3.5.0 I no longer see this issue.

**Comment by ajpowelsnl** [comment]
> My apologies I was using Kokkos v. 3.2.01 after upgrading to v. 3.5.0 I no longer see this issue.

Great! Thank you for using Kokkos, and please do let us know if you have further questions.
