### ISSUE TITLE
Drop Cuda 6.5 support

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#467]
I would like to drop Cuda 6.5 support with the next master merge (which I believe should increase the minor version number of master). We gonna add official Cuda 8.0 support (has been working for a while) as well as Cuda compilation with Clang.

**Comment by crtrott** [comment]
Titan has Cuda 7.0 as default as far as I can tell.

**Comment by hcedwar** [comment]
1. Must verify Titan has 7.0
2. Definitely bump the minor version number

**Comment by crtrott** [comment]
It says so on their website: https://www.olcf.ornl.gov/kb_articles/software-cudatoolkit/ (click on the version tab)

**Comment by etphipp** [comment]
Actually Titan has both 7.0 and 7.5, and the default is 7.5:

etphipp@titan-ext2 ~ $ modulegrep cuda
cudatoolkit/7.0.28-1.0502.10280.4.1
cudatoolkit/7.5.18-1.0502.10743.2.1(default)

-Eric

**Comment by crtrott** [comment]
Ok then I gonna drop 6.5.
