### ISSUE TITLE
Add official Cuda 8.0 support

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#468]
Has been working for a while, but we need to add nightly testing on X86 and Power. 
I think we should use a gcc 5.x compiler (5.3 probably since that comes with SEMS) as the host side compiler.

**Comment by nmhamster** [comment]
We are likely to transition to 5.4 in POWER in the new stack but it's undergoing testing at the moment.

**Comment by crtrott** [comment]
Yeah sure thats no problem. I don't think we need to have the same versions on X86 and Power.

**Comment by crtrott** [comment]
Nightly Testing is set up on Apollo.

**Comment by hcedwar** [comment]
Need SEMS supported module for this.
Need on all of our GPU testbeds.

**Comment by nmhamster** [comment]
@hcedwar you will have the first production release of this on POWER8 shortly. SEMS are providing your support in the development environment. We are under evaluation on some other machines and expect to have this in a few weeks (we have other things in the queue for higher priority today unless this is super urgent).

**Comment by hcedwar** [comment]
CUDA 8 is not in the test_all_sandia

**Comment by jgfouca** [comment]
It will be soon.

**Comment by crtrott** [comment]
It is: COMPILERS=("cuda/8.0.44 $NVCC_MODULE_LIST $BUILD_LIST_CUDA_NVCC $KOKKOS_PATH/config/nvcc_wrapper $CUDA_WARNING_FLAGS"

It is not for kokkos-dev, but it is on Apollo and nightly tests have been running for a few days. You can check jenkins to see the output.
