### ISSUE TITLE
OpenMPTarget: TeamPolicy constructor requires >= 32 team size

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#4685]
Constructing a ``TeamPolicy<OpenMPTarget>`` throws if the given team size is less than 32 (at least, when building with Intel icpx). It would be nice if this check were in the actual kernel launch instead, because it's a common pattern in KokkosKernels to create a dummy policy to ask for the recommended/max team size:
```
//constructing this policy, but won't actually execute with it
TeamPolicy<exec_space> dummyPolicy(1, 1, vector_length);
int teamSize = dummyPolicy.team_size_recommended(myFunctor, Kokkos::ParallelForTag());
TeamPolicy<exec_space> actualPolicy(n, teamSize, vector_length);
...
```

Alternately, it would be neat to have a static version of TeamPolicy::team_size_recommended/team_size_max - then the dummy policies wouldn't be needed at all.

**Comment by ajpowelsnl** [comment]
As a work around, would you please try:
 
```C++
TeamPolicy<exec_space> dummyPolicy(1, AUTO, vector_length)
```

**Comment by ajpowelsnl** [comment]
Hi @rgayatri23 -- Is this still a problem?

**Comment by brian-kelley** [comment]
I replaced the team size with AUTO in all the dummy policies, and will do that from now on. I'm fine with that being the standard thing to write, so I'll just close this.
