### ISSUE TITLE
kokkos_launch_compiler removes escaped characters

### ISSUE THREAD

**Issue by Azrael3000** [kokkos/kokkos#4687]
I had the problem that I was passing an escaped character to the kokkos_launch_compiler which was then passed without the backslash to the `eval` function and caused an error in the linking stage.
In detail it was:
`kokkos_launch_compiler nvcc_wrapper c++ c++ [...] -Wl,-rpath,"\$ORIGIN:/other/path:" [...]`
which was converted to
`c++ [...] -Wl,-rpath,"$ORIGIN:/other/path:" [...]`

To avoid the issue I added
`target=$(sed 's/\$/\\\$/g' <<< "$@")`
and replaced all `$@` by `$target` in the following. While this worked for me a more general solution might be required for further escaped characters, for example:

```
target=$(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/`/\\`/g' -e 's/\$/\\\$/g' <<< "$@")
target=$(sed -e 's/\\\\!/\\!/g' <<< "$target") 
```

which correctly escapes ``\ " ` $ !`` as shown below:

```
$ cat test.sh 
target=$(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/`/\\`/g' -e 's/\$/\\\$/g' <<< "$@")
target=$(sed -e 's/\\\\!/\\!/g' <<< "$target")
echo $target
eval $target
$ ./test.sh "echo '\$foo \`a \"a \!a \\n'"
echo '\$foo \`a \"a \!a \\n'
\$foo \`a \"a \!a \\n
```

Since bash is not my strong point there might be more elegant solutions to this which is the reason I'm opening this issue. If not I'd be happy to provide you with a pull request.

Thanks,
Arno

**Comment by cz4rs** [comment]
Hello @Azrael3000, thanks for submitting the issue.

> (...) it was: `kokkos_launch_compiler nvcc_wrapper c++ c++ [...] -Wl,-rpath,"\$ORIGIN:/other/path:" [...]` which was converted to `c++ [...] -Wl,-rpath,"$ORIGIN:/other/path:" [...]`

Is that manual invocation or does this come from another script? (I wonder if using `"\\$ORIGIN:/other/path:"` is a legit workaround)

**Comment by Azrael3000** [comment]
Hi, I'm using cmake which produces the `\$ORIGIN` in the linker command, so I'm afraid it's not easily possible to change it.

**Comment by cz4rs** [comment]
@Azrael3000 can you take a look at https://github.com/kokkos/kokkos/pull/4703 and confirm that this works for you?

**Comment by Azrael3000** [comment]
Works for me. Thanks

**Comment by cz4rs** [comment]
Closing after #4703 was merged.
