### ISSUE TITLE
[Feature Request] Adding 1D tile layout.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#469]
From the discussion with Carter, Kokkos has 2D tile layout but it  does not have 1D tile layout. Could we have 1D tile layout in Kokkos  ?

**Comment by crtrott** [comment]
What is the motivation? And what is a 1D tile layout? Do you mean you want the first dimension of a multi dimensional array tiled?

**Comment by kyungjoo-kim** [comment]
I want to test how I can use vector intrinsics in Intrepid2. For instance, (C,P,D,D) with tile size 4 translates internally (c,P,D,D,i) where i = C%4, c = C/4. Then, maybe I can apply vector intrinsics directly on this layout and still put parallel for on C dimension.

**Comment by crtrott** [comment]
Ok so what you want is actually what we refer to as a SIMDLayout. This is a different beast than an actual TiledLayout. We actually have that implemented for another team.

**Comment by kyungjoo-kim** [comment]
How can I use the layout ? could you point out any example or test ?

**Comment by crtrott** [comment]
This is not in mainline Kokkos it is a custom Layout we wrote for another code team. We might think about moving it back though.

**Comment by ibaned** [comment]
This boils down to getting SIMD types added to the Kokkos Ecosystem.
