### ISSUE TITLE
Add OpenMPTarget to supported device variants in Spack

### ISSUE THREAD

**Issue by janciesko** [kokkos/kokkos#4700]
Add Spack support for OMPTarget.

**Comment by rgayatri23** [comment]
@ajpowelsnl . This is a goal for 3.7.

**Comment by ajpowelsnl** [comment]
Hi @janciesko  and @rgayatri23 -- How's work on this issue going?  Will it be ready for Kokkos 3.7 in a couple of weeks?

**Comment by masterleinad** [comment]
Fixed in https://github.com/spack/spack/pull/30724.
