### ISSUE TITLE
LayoutLeft to LayoutLeft subview for 3D and 4D views

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#473]
We would like to do the following:
```C++
Kokkos::View<double***,Kokkos::LayoutLeft> a("A",N*E,M,K);

Kokkos::View<double***,Kokkos::LayoutLeft> sub(a,
  Kokkos::pair<int,int>(n*E,(n+1)*E),Kokkos::ALL,Kokkos::ALL,Kokkos::ALL)
```
With sub being LayoutLeft again.

**Comment by crtrott** [comment]
This gets us in some really important kernel tests (as in 30% of the wall clock time of production runs)  about 40% time reduction on Kepler and 75% time reduction on Pascal Titan X.

**Comment by crtrott** [comment]
Ok I think I now know what is legal and what not in a generic sense:

From LayoutLeft of rank R_Src to LayoutLeft of rank R_Dest:
 1) The first R_Dest subview arguments are Ranges, the last R_Src-R_Dest are indices
 2) The first subview argument is a Range
 3) The next R_Dest-1 arguments are ALL
 4) The last range argument is a Range

I.e. this should be legal:

```C++
View<int******,LayoutLeft> a("A",N0,N1,N2,N3,N4,N5);
View<int****,LayoutLeft> b(a,pair<>(5,N0-5),ALL,ALL,pair(3,N3-8),1,3);
```

Why does this work: the new index calculation is:
```C++
sub_ptr[i0 + sub_stride*(i1 + sub_N1*(i2 + sub_N2*i3))]
```
the old one was
```C++
base_ptr[i0 + m_stride*(i1 + N1*(i2 + N2 * ( i3 + N3 *( i4 + N4*i5))))]
```
with i4 and i5 fixed this transforms to
```C++
base_ptr[i0 + m_stride*(i1 + N1*(i2 + N2*i3)) + m_stride * N1 * N2 * N3 * ( 1 + N4 * 3)]
```
and that makes 
```C++
sub_ptr = base_ptr + m_stride * N1 * N2 * N3 * ( 1 + N4 * 3)
```
if sub_N1 = N1 and sub_N2=N2 and sub_stride = m_stride.
We do not need sub_N3 to be equal N3.

LayoutRight is like LayoutLeft just in revers order.

**Comment by hcedwar** [comment]
special case of issue #205
