### ISSUE TITLE
Kokkos nvcc_wrapper does not handle -Werror correctly

### ISSUE THREAD

**Issue by Azrael3000** [kokkos/kokkos#4734]
As far as I'm aware the `nvcc_wrapper` needs to explicitly capture each compiler flag explicitly. One that I would like to use is `-Werror` in particular with the `cross-execution-space-call` option as this will throw an error when a `__host__ __device__` function calls a pure `__host__` function which can lead to hard to debug issues.

According to the NVIDIA documentation the following the syntax is [`-Werror` or `--Werror` followed by `kind`](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generic-tool-options-Werror)

Thus, I propose adding
```
  -Werror|--Werror)
    cuda_args="$cuda_args $1 $2"
    shift
    ;;  
```
to the `while` loop starting in line 125.

Thanks in advance for the consideration,
Arno

**Comment by dalg24** [comment]
Would you like to open a pull request for it?

**Comment by Azrael3000** [comment]
Sure, will do

**Comment by ajpowelsnl** [comment]
Morning @dalg24 and @crtrott -- May I close this issue?
