### ISSUE TITLE
KOKKOS_ARCH_KEPLER - revise for alignment with __CUDA_ARCH__

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#475]
Our nvcc_wrapper sets a single `-arch`.  We should use a host-side macro that aligns with `__CUDA_ARCH__` .

**Comment by crtrott** [comment]
So you want a KOKKOS_ARCH_NVIDIA = 350 or something like this? What do you then do with Intel or IBM? Do we leave those with KOKKOS_ARCH_HSW, KOKKOS_ARCH_SNB, KOKKOS_ARCH_POWER8? or do you want to make up a own number scheme? Alternatively do you want to treat NVIDIA different from the other vendors?

**Comment by hcedwar** [comment]
The Intel architectures have an E series number which may be usable.

**Comment by nmhamster** [comment]
I do not want to be using E-series for this since the number of combinations is potentially huge. We want to stick with base ISA and then some options for Intel and POWER. We will need to have this conversation offline since it relates to NDA material.

**Comment by hcedwar** [comment]
Also must reflect the target architecture if cross-compiling.

**Comment by hcedwar** [comment]
Another strategy: `KOKKOS_ARCH_{FEATURE}` macros.  For different architectures there are probably be sensible bundled FEATURE macros.

**Comment by dsunder** [comment]
KOKKOS_ARCH_{FEATURE} exist in master
