### ISSUE TITLE
building a shared library with nvcc_wrapper and LTO does not work

### ISSUE THREAD

**Issue by XzzX** [kokkos/kokkos#4757]
When `CMAKE_INTERPROCEDURAL_OPTIMIZATION` is activated in `CMake` and a shared library is linked against a `nvcc` version of `Kokkos` link time errors like `Error: symbol 'fatbinData' is already defined` occur.

MWE:
```
cmake_minimum_required(VERSION 3.4...3.18)
project(example LANGUAGES CXX CUDA)

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)

find_package(Kokkos REQUIRED)
add_library(bar SHARED example1.cpp example2.cpp)
target_link_libraries(bar PRIVATE Kokkos::kokkos)
```
Content of `example1.cpp` and `example2.cpp` seems to be irrelevant.

Due to the `cpp` file extension and a `gcc` host compiler `CMake` will emit `-flto -fno-fat-lto-objects` these are passed through the wrapper to and nvcc during compilation and cause the error. If one compiles a native CUDA program with `CMake` and lto no flags are emitted.

Tested with CUDA 11.2

This problem should always arise if you use `pybind11` together with `Kokkos` as `pybind11` enables LTO. Also `pykokkos-base` seems to have this problem and is working around it: https://github.com/kokkos/pykokkos-base/blob/main/cmake/Modules/KokkosPythonBuildOptions.cmake#L72-L80

**Comment by crtrott** [comment]
This is a limitation of the default way to build Kokkos. You could try to build Kokkos as native CUDA code. But that means you have to mark everything which depends on Kokkos as CUDA language files (which then obviously means you won't get LTO either).

**Comment by crtrott** [comment]
Here is an example:

https://github.com/kokkos/kokkos/tree/develop/example/build_cmake_installed_kk_as_language

Note this requires develop branch.

**Comment by ajpowelsnl** [comment]
Hello @XzzX -- Did the suggestion from @crtrott help resolve your issue , and answer your question?
