### ISSUE TITLE
Increasing kernel duration for KOKKOS compute kernels on GPUs

### ISSUE THREAD

**Issue by rutwik-n-jain** [kokkos/kokkos#4759]
I have been trying to get the Molecular Dynamics code LAMMPS, and specifically the REAXC benchmark from Coral-2’s source  to run on a supercomputer cluster (https://asc.llnl.gov/sites/asc/files/2020-09/CORAL2_Benchmark_Summary_LAMMPS.pdf). We want to profile metrics like power, performance and execution times on GPUs running the REAXC code. 
 
**Details:**
**LAMMPS binary:** lmp_kokkos_cuda_mpi 
**Target GPU:** Nvidia Volta V100
**GPU Profiler:** nvprof (Nvidia’s profiler)
**Run command:** 
mpiexec -np 1 -x CUDA_LAUNCH_BLOCKING --bind-to core nvprof  --print-gpu-trace --event-collection-mode continuous --system-profiling on --kernel-latency-timestamps on --csv --log-file  lammps_${UUID}_run${2}_node${3}_gpu${1}_${ts}.csv --device-buffer-size 128 --continuous-sampling-interval 1 -f ../src/lmp_kokkos_cuda_mpi -k on g 1 device ${1} -sf kk -pk kokkos neigh half neigh/qeq full newton on -v x 8 -v y 16 -v z 16 -in in.reaxc.hns -nocite
 
While doing so, we find that nvprof is not able to sample any useful metrics because each of the application kernels are very short in duration (of the order of few μs). To clarify, nvprof is logging data but the minimum granularity it supports (1ms) is not large enough to get any useful data and requires longer running kernels. We tried changing knobs for the input script in an attempt to increase kernel duration. The input parameters `(x,y,z)` for the MD simulation are the knobs available in the LAMMPS input script. However, they have an upper bound since KOKKOS throws a CUDA Malloc error if `x*y*z > 2048`. This triplet is already set to its maximum legal value and we still see kernels running for a few microseconds only. The run command is for `(x,y,z) = (8,16,16)` and 100 simulation timesteps.
 
I also wanted to understand what the underlying computation is for these extremely short kernels – they seem to be running some KOKKOS library functions such as ViewValueFunctor and ViewRemap – I was wondering how much computation these kernels could really achieve when running for only 7-10 microseconds. It would be great to connect to somebody who can help us understand what knobs there are to increase kernel duration and ensure that nvprof can sample useful data. I tried contacting LAMMPS support on this but they redirected me saying that this query is more appropriate for a KOKKOS forum. 
 
Thanks,
Rutwik

**Comment by stanmoore1** [comment]
@rutwik-n-jain How many atoms are you running? You can increase the number of atoms/GPU in LAMMPS, which will increase the kernel length, i.e. use something larger than `-v x 8 -v y 16 -v z 16`. @weinbe2 may have more insights on `nvprof`.

**Comment by stanmoore1** [comment]
Sorry missed the part about running out of memory, will take a look.

**Comment by crtrott** [comment]
A lot of these very short kernel are simply stuff like filling an array with 0s or copying an array / resizing an array etc. Since the number of particles in typical MD simulations is not huge, with most of the memory being in stuff like neighbor lists, the actual particle data arrays (like forces etc.) are fairly small. For example 1M atoms force array is only 24MB (1M * 3*8bytes). At 1TB/s GPU bandwidth doing a copy will only take ~50us. If you have 100k atoms it will take 5us and at 10k atoms it would take 0.5us assuming you don't have latency effects (which you do).

**Comment by stanmoore1** [comment]
I confirm that ~600k atoms is the max that will fit into 16GB of GPU memory on V100. There are many small kernels, but the largest kernels are multiple ms:

```
4.91907s  67.608ms           (1769 1 1)       (1 352 1)        92        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  _ZN6Kokkos4Impl36cuda_parallel_launch_constant_memoryINS0_11ParallelForIN9LAMMPS_NS16PairReaxFFKokkosINS_4CudaEEENS_11RangePolicyIJS5_NS3_26PairReaxFFComputeLJCoulombILi2ELi0EEEEEES5_EEEEvv [25045]

3.62416s  3.6388ms         (622592 1 1)       (1 128 1)        26       48B  1.0156KB         -           -           -           -  Tesla V100-SXM2         1         7  _ZN6Kokkos4Impl36cuda_parallel_launch_constant_memoryINS0_11ParallelForIN9LAMMPS_NS18FixQEqReaxFFKokkosINS_4CudaEEENS_10TeamPolicyIJS5_NS3_16TagSparseMatvec1EEEES5_EEEEvv [7736]
```

```
KOKKOS CUDA SPACE:
=================== 
MAX MEMORY ALLOCATED: 14649574.0 kB
MPI RANK WITH MAX MEMORY: 0
ALLOCATIONS AT TIME OF HIGH WATER MARK:
  16.3% qeq/kk:val
  16.3% qeq/kk:val
  14.3% neighlist:neighbors
  14.2% neighlist:neighbors
  8.1% qeq/kk:jlist
  8.1% qeq/kk:jlist
  2.0% reaxff/kk:hb_list
  1.5% reaxff/kk:Cdbo
  1.5% reaxff/kk:Cdbopi
  1.5% reaxff/kk:Cdbopi2
  0.5% reaxff/kk:BO
  0.5% reaxff/kk:BO_pi
  0.5% reaxff/kk:BO
```

```
BEGIN KOKKOS PROFILING REPORT:
TOTAL TIME: 39.0754 seconds
TOP-DOWN TIME TREE:
<average time> <percent of total time> <percent time in Kokkos> <percent MPI imbalance> <remainder> <kernels per second> <number of calls> <name> [type]
=================== 
|-> 8.30e+00 sec 21.2% 100.0% 0.0% ------ 2280 N9LAMMPS_NS18FixQEqReaxFFKokkosIN6Kokkos4CudaEEE/N9LAMMPS_NS16TagSparseMatvec2E [for]
|-> 6.11e+00 sec 15.6% 100.0% 0.0% ------ 90 N9LAMMPS_NS16PairReaxFFKokkosIN6Kokkos4CudaEEE/N9LAMMPS_NS26PairReaxFFComputeLJCoulombILi2ELi0EEE [for]
|-> 5.06e+00 sec 13.0% 100.0% 0.0% ------ 105 N9LAMMPS_NS16PairReaxFFKokkosIN6Kokkos4CudaEEE/N9LAMMPS_NS22PairReaxBuildListsHalfILi2EEE [for]
|-> 3.07e+00 sec 7.9% 100.0% 0.0% ------ 90 N9LAMMPS_NS16PairReaxFFKokkosIN6Kokkos4CudaEEE/N9LAMMPS_NS24PairReaxFFComputeTorsionILi2ELi0EEE [for]
|-> 2.04e+00 sec 5.2% 100.0% 0.0% ------ 101 N9LAMMPS_NS33FixQEqReaxFFKokkosComputeHFunctorIN6Kokkos4CudaELi1EEE [for]
|-> 1.56e+00 sec 4.0% 100.0% 0.0% ------ 90 N9LAMMPS_NS16PairReaxFFKokkosIN6Kokkos4CudaEEE/N9LAMMPS_NS24PairReaxFFComputeAngularILi2ELi0EEE [for]
|-> 1.41e+00 sec 3.6% 100.0% 0.0% ------ 7 N9LAMMPS_NS28NPairKokkosBuildFunctorGhostIN6Kokkos4CudaELi0EEE [for]
```

**Comment by stanmoore1** [comment]
Just FYI, AMD (@arghdos and others) made several optimizations to ReaxFF, see https://github.com/stanmoore1/lammps/tree/amd_hip_opt. I'm working on getting these released in public LAMMPS.
