### ISSUE TITLE
Is `eval` needed to execute compile command?

### ISSUE THREAD

**Issue by finkandreas** [kokkos/kokkos#4766]
Looking at the code of kokkos_launch_compiler: https://github.com/kokkos/kokkos/blob/2834f94af9b01debf67c1aaa3f0eb0c903d72c8d/bin/kokkos_launch_compiler#L88
The use of `eval` seems incorrect in this context, it should be rather a plain 
```
"$@"
```
We do not want to re-evaluate the arguments. I ran into a problem with the filename `P_<>_projectorTest.c`.
I am almost sure that filenames with a `$` will pose problems too because eval will try to re-evalute it as a variable expression. In my opinion we just want to perfectly forward the arguments, which is simply wrapping it with quotes.

Additionally to the problem of using eval, the arguments need also to be quoted, i.e. instead of `$@` it should be everywhere `"$@"`, otherwise files with whitespace will be problematic (`$@` is used several times, all of them must be quoted).

**Comment by dalg24** [comment]
@finkandreas would you please try the develop branch.  It looks like #4703 resolved the issue you are reporting.

**Comment by finkandreas** [comment]
@dalg24 Does not work either. What works is
```
"$@"
```
or alternatively if you would want to insist on a keyword
```
exec "$@"
```

**Comment by finkandreas** [comment]
done #4769

**Comment by ajpowelsnl** [comment]
Hi @dalg24 and @crtrott -- Can we close this issue?
