### ISSUE TITLE
Revise Public and Private Header Files in Kokkos 

### ISSUE THREAD

**Issue by ajpowelsnl** [kokkos/kokkos#4856]
This issue tracks revision of public vs. private headers in Kokkos.  Users can include public headers, but not private.  We are revising the public and private headers design because ... ??

**Comment by crtrott** [comment]
### Core:

- Kokkos_Core.hpp
- Kokkos_Core_fwd.hpp
- Kokkos_Macros.hpp
- Kokkos_Timer.hpp
- Kokkos_Half.hpp?
- Kokkos_Mathematicl....hpp?
- Kokkos_NumericTraits.hpp

### Algorithms
- Kokkos_Random.hpp
- Kokkos_Sort.hpp
- Kokkos_Algorithms.hpp

### Containers
- Kokkos_DualView.hpp
- Kokkos_DynamicView.hpp
- Kokkos_Functional.hpp
- Kokkos_ScatterView.hpp 
- Kokkos_UnorderedMap.hpp
- Kokkos_Bitset.hpp
- Kokkos_DynRankView.hpp
- Kokkos_ErrorReporter.hpp
- Kokkos_OffsetView.hpp
- Kokkos_StaticCrsGraph.hpp
- Kokkos_Vector.hpp

**Comment by ajpowelsnl** [comment]
@dalg24 - please have a look 👀

**Comment by ajpowelsnl** [comment]
@crtrott: a gentle reminder -- draft the idea you have in mind for this work, and test against @dalg24 estimate of the pitfalls of doing this reorganization.  More broadly, what are the pros, what are the cons?  Would this reorganization be an overall design "win?"

**Comment by crtrott** [comment]
Note: algorithms and container headers are not included via Kokkos_Core.hpp. Generally containers and algorithms depend on core not the other way around.
