### ISSUE TITLE
What headers should be public Kokkos headers - i.e. users can include them.

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#4857]
### Core:

- Kokkos_Core.hpp
- Kokkos_Core_fwd.hpp
- Kokkos_Macros.hpp
- Kokkos_Timer.hpp
- Kokkos_Half.hpp
- Kokkos_MathematicalFunctions.hpp
- Kokkos_MathematicalSpecialFunctions.hpp
- Kokkos_NumericTraits.hpp
- Kokkos_Functional.hpp
- Kokkos_DetectionIdiom.hpp
- Kokkos_Pair.hpp
- Kokkos_Complex.hpp
- Kokkos_Array.hpp

### Algorithms
- Kokkos_Random.hpp
- Kokkos_Sort.hpp
- Kokkos_Algorithms.hpp

### Containers
- Kokkos_DualView.hpp
- Kokkos_DynamicView.hpp
- Kokkos_Functional.hpp
- Kokkos_ScatterView.hpp 
- Kokkos_UnorderedMap.hpp
- Kokkos_Bitset.hpp
- Kokkos_DynRankView.hpp
- Kokkos_ErrorReporter.hpp
- Kokkos_OffsetView.hpp
- Kokkos_StaticCrsGraph.hpp
- Kokkos_Vector.hpp

**Comment by ajpowelsnl** [comment]
@crtrott -- Would it be OK to close / delete this issue?  It duplicates #4856.
