### ISSUE TITLE
Consistency between Trilinos/pacakges/kokkos and kokkos/kokkos

### ISSUE THREAD

**Issue by pbosler** [kokkos/kokkos#486]
Why are the libraries produced by kokkos/kokkos different than the libraries produced by Trilinos/packages/kokkos?  For example,
- Standalone kokkos: 
  `$ ls kokkos-openmp/lib/` returns
  `libkokkos.a`
- Trilinos kokkos:
  `$ls trilinos-kokkos-openmp/install/lib | grep -i kokkos` returns 
  `libkokkosalgorithms.a`
  `libkokkoscontainers.a`
  `libkokkoscore.a`
  `libkokkostsqr.a`
  `libteuchoskokkoscomm.a`
  `libteuchoskokkoscompat.a`

This difference makes it harder to migrate a project that began using standalone kokkos (for rapid development) to one that uses more Trilinos capabilities as it matures.

**Comment by crtrott** [comment]
Because its two different build systems. Also only the first three in Trilinos are actually coming from Kokkos itself.

**Comment by pbosler** [comment]
With CMake it's not that difficult to make the change; I was mainly curious if there was a specific reason for separating the three libraries that come from kokkos in one case and keeping them together in the other case.

**Comment by crtrott** [comment]
Yeah the reason is that within Trilinos Kokkos is a package with three sub packages : core, containers, algorithms. Libraries are generated on a per sub package thing in Trilinos.
