### ISSUE TITLE
HIP backend: LocalMemory launch mechanism should pass functor by value

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#4861]
I noticed that in the HIP backend, launches using the LocalMemory launch mechanism actually seem to take the functor/driver as a pointer to host-pinned, not by value like on Cuda:

Kokkos_HIP_KernelLaunch.hpp:
```
101 template <class DriverType>
102 __global__ static void hip_parallel_launch_local_memory(
103     const DriverType *driver) {
104   // FIXME_HIP driver() pass by copy
105   driver->operator()();
106 }
107 
108 template <class DriverType, unsigned int maxTperB, unsigned int minBperSM>
109 __global__ __launch_bounds__(
110     maxTperB,
111     minBperSM) static void hip_parallel_launch_local_memory(const DriverType
112                                                                 *driver) {
113   // FIXME_HIP driver() pass by copy
114   driver->operator()();
115 }
```

Is this something that can be resolved easily? I would imagine it would give a noticeable performance boost, since if I'm understanding right, launches have to cross PCIe at least 3 times (?)

- Host launches kernel and sends driver pointer to device
- Device reads the driver out of host pinned
- Driver comes back from host pinned

whereas if it were pass-by-value, it would just be "host launches with the full driver".

I tried to hack this change in, to see how performance changed, but I ran into a couple issues:
- The HIP specializations of some drivers have ``std::lock_guards`` so the drivers can't be copy-constructed (e.g. ``Impl::ParallelReduce`` has a lock ``m_shared_memory_lock``). This is different from Cuda, where the drivers don't acquire locks
- When I change the ``__global__ hip_parallel_launch_local_memory(...)`` function to take the driver by value, hipcc seems to think it's an ambiguous overload down below in ``get_kernel_func()``. This happens even if I give different names to the versions with and without the ``__launch_bounds__``.

**Comment by Rombur** [comment]
The reason it is done that way is that sometimes you would hit a compiler bug at runtime. I don't remember the details maybe @arghdos  does. We can change the code but we will need to tests with several apps to check that the bug has been fixed.

**Comment by arghdos** [comment]
I believe this should be fixed at this point (this was... way back in like ROCm 3.5 days), but I've never gone back to check it, but it used to cause the compiler to behave _terribly_ (think: T-Rex on a unicycle trying to hold a glass of water... spills everywhere :P)

I will note @brian-kelley, the current method absolutely does not have to cross PCIe 3x to get at the driver, though you'd be forgiven for thinking so.  This is because it's allocated with a ["magic flag"](https://github.com/kokkos/kokkos/blob/develop/core/src/HIP/Kokkos_HIP_Instance.cpp#L475) that instructs the GPU driver that the data can be cached in the L2.  So: the very first load may end up crossing the bus, but once it's in L2 it's very likely to _stay_ there given how often the `DriverType` is accessed.

I am interested in seeing what happens these days if we can actually get pass-by-value to work, but I don't anticipate it to be revolutionary -- it might be useful for small / strong-scaled kernels however.

**Comment by brian-kelley** [comment]
@Rombur @arghdos OK, thanks a lot for the information. So I understand this isn't quite the low-hanging performance fruit I thought it might be. I'll leave this issue up for now to document this.

**Comment by arghdos** [comment]
> Edit: actually, when you say that the driver can get cached on device, the first access is still like any other host-pinned access, right?

Correct -- so if you launched a single workgroup that did like "store some value into a member variable" it would probably be painful.

Do you remember why we have locks @Rombur? That's mildly concerning as well -- is it because the access to these `DriverTypes` isn't thread-safe?  If so, we can probably come up with an atomic version that should be.

**Comment by brian-kelley** [comment]
Hmm, what about for something like a `deep_copy` that fills a view with a constant? Even if there are enough elements to saturate the entire device, the PCIe latency is several times greater than the global latency. Plus each thread could have several global accesses in flight, whereas that first host-pinned read will block everything.

**Comment by arghdos** [comment]
Possibly, but then you have to eat the `memcpy` API latency :/.  I could see an async copy followed by a kernel launch on the same stream being useful here.  

The other option (which again is on my very long 'Kokkos todo list') is that on our GPUs, at least where LargeBAR is enabled in the BIOS, you can literally just `std::memcpy` it over, though that's usually only profitable for smaller sizes (say < 1KB)

**Comment by brian-kelley** [comment]
I don't mean the view-to-view deep_copy, I mean the overload that's more like a memset, ``deep_copy(myView, 123);``. This is implemented as a regular parallel_for. Just as an example of a common operation that might take a hit from this launch mechanism, even when there are enough items to saturate the device.

**Comment by Rombur** [comment]
> Do you remember why we have locks @Rombur? That's mildly concerning as well -- is it because the access to these DriverTypes isn't thread-safe? If so, we can probably come up with an atomic version that should be.

The lock is for the access of shared memory when multiple kernels are launched from different threads. There is no lock in CUDA but instead we create a memory pool. We did measure the performance of using locks and there was no slow down.

**Comment by ajpowelsnl** [comment]
Hi @Rombur -- is there an action item on this issue, or is it resolved?

**Comment by IanBogle** [comment]
I have done some work on figuring out the ambiguous overload error, and I think it's a problem in the ParallelScanHIPBase hierarchy (in https://github.com/kokkos/kokkos/blob/develop/core/src/HIP/Kokkos_HIP_Parallel_Range.hpp#L659). I've come up with a piece of code that produces the same compiler error from hipcc:
```
template<typename t>
void test_func(t c) {c.test();}

template<typename t>
auto returner(){
	return test_func<t>;
}

class base{
  public:
  	virtual void foo() = 0;
  	void impl_execute(){returner<base>()(*this);}
  	void test(){}
};

class derived2: public base{
  public:
  	int bar;
  	void foo(){bar=5;}
  	void execute(){base::impl_execute();}
  	void test(){}
};

int main(){
  derived2 d;
  d.execute();
}
```
This code is modeled on the class structure of the ParallelScanHIPBase Hierarchy, and there's some explicit casting that we suspect makes the KernelLaunch classes attempt to return a functor that takes an instance of an abstract base class, so the compiler can't deduce the type of the functor. It's much more obscured in the Kokkos HIP backend, but I do know that the DriverType passed to the function that throws the error is ParallelScanHIPBase, which is abstract.

**Comment by brian-kelley** [comment]
Closing because this got taken care of a long time ago, thanks @Rombur!
