### ISSUE TITLE
Fujitsu Compiler not handled in Makefile.kokkos

### ISSUE THREAD

**Issue by simon-schlepphorst** [kokkos/kokkos#4868]
Trying to compile the exercises from [kokkos-tutorials](https://github.com/kokkos/kokkos-tutorials) with the fujitsu compiler and Makefiles, I ran into the issue that the fujitsu compiler is, depending on the mode, either identified as gcc or clang. In both cases Makefile.kokkos sets incompatible flags.

So I started working on a patch #4867

- The man page and #4730 seem to suggest that Clang Mode is the way to go.

      Trad Mode
      This mode uses an enhanced compiler based on compilers for K computer and PRIMEHPC FX100 or earlier system.
      This mode is suitable for maintaining compatibility with the past Fujitsu compiler.
      Supported specifications are C++03/C++11/C++14/Part of C++17 and OpenMP 3.1/Part of OpenMP 4.5.
      Specify -Nnoclang option (default) if you use Trad Mode.

      Clang Mode
      This mode uses an enhanced compiler based on Clang/LLVM.
      This mode is suitable for compiling programs using the latest language specification and open source software.
      Supported specifications are C++03/C++11/C++14/C++17 and OpenMP 4.5/Part of OpenMP 5.0.
      Specify -Nclang option if you use Clang Mode

- `-Nclang` needs to be the first argument to work properly. I got away with setting `CXX = FCCgx -Nclang` in the local Makefile. Adding it later with `CXXFLAGS = -Nclang` conveniently circumvents the compiler checks and triggers my warning.

- I only tested the `OpenMP` and `compiler_warnings` logic.

- #3975 isn't an issue with Clang Mode.

How do you want to proceed?

**Comment by ajpowelsnl** [comment]
@simon-schlepphorst -- you will still need to compile with `-Nclang`
