### ISSUE TITLE
Segfaults for Threads+HWLOC on Linux

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#4878]
While looking into #4842, I discovered that tests segfault if HWLOC is used together with the `Threads` backend, at least on our `linux` CI, i.e. `.github/workflows/continuous-integration-workflow.yml` and I can reproduce that locally.

**Comment by ajpowelsnl** [comment]
Possibly integrate into Kokkos 3.6.1

**Comment by ajpowelsnl** [comment]
Hi @PhilMiller -- have you been able to look into this issue?

**Comment by masterleinad** [comment]
Fixed by #5109.

**Comment by masterleinad** [comment]
In 3.6.01.
