### ISSUE TITLE
UnorderedMap [] operator

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#488]
Why does the unordered map not have a [] interface?  It seems odd that, looking at the code 

v = uom.value_at(find(key))

vs the standard unordered map interface?  

Same question for insertion

**Comment by mhoemmen** [comment]
Kokkos::UnorderedMap inserts can fail if the map has no more space left.  operator[] is supposed to return a nonconst reference to the value changed.  This means that operator[] cannot return an error code.  std::map::operator[] has the freedom to throw if it cannot allocate more space.  However, Kokkos::UnorderedMap is not supposed to throw exceptions.  This means that operator[] does not make sense for Kokkos::UnorderedMap.

**Comment by mhoemmen** [comment]
@bathmatt , I'm talking with @gmackey about the possibility of reopening this, because @gmackey sees what you might actually want, and may also want that.  He will post more here.
