### ISSUE TITLE
CUDA LDG fetch never happens due to typo _CUDA_ARCH__

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#4892]
CUDA LDG fetching is never called because it is guarded by a typo:
https://github.com/kokkos/kokkos/blob/2834f94af9b01debf67c1aaa3f0eb0c903d72c8d/core/src/Cuda/Kokkos_Cuda_View.hpp#L142

`_CUDA_ARCH__` -> `__CUDA_ARCH__`

**Comment by PhilMiller** [comment]
Fix was also cherry-picked to 3.6.01, which was merged to `master` today
