### ISSUE TITLE
VTK-m failure with Kokkos(Cuda)

### ISSUE THREAD

**Issue by renderdude** [kokkos/kokkos#4903]
BenchmarkFilters in VTK-m fails with current HEAD on Summit compiled against Kokkos w/Cuda. The same versions run successfully on spock agains Kokkos/HIP.  It seems to manifest inside vtk-m as arrays of mismatched size. 

Kokkos commit  2834f94af (Jan 4, 2022) does not have this issue.

**Comment by renderdude** [comment]
Running against the current HEAD I get this:
<preamble>
...
-------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------------------------------------------------------
BenchGradientScalar/manual_time                                                                        23.9 ms         25.8 ms           29
BenchGradientVector/manual_time                                                                        48.6 ms         54.1 ms           14
BenchGradientVectorRow/manual_time                                                                     46.2 ms         51.8 ms           15
BenchGradientPoint/manual_time                                                                         1.01 ms         1.02 ms          691
BenchGradientDivergence/manual_time                                                                    8.79 ms         9.55 ms           79
BenchGradientVorticity/manual_time                                                                     24.4 ms         26.3 ms           29
BenchGradientQCriterion/manual_time                                                                    8.75 ms         9.50 ms           79
BenchGradientAll/manual_time                                                                           74.4 ms         83.3 ms            9
cudaStreamSynchronize(stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /ccs/home/mbolsta/ECP/kokkos_develop/core/src/Cuda/Kokkos_Cuda_Instance.cpp:162

**Comment by renderdude** [comment]
gcc 10.2, Cuda 11.4.2

**Comment by nicolemarsaglia** [comment]
What is your recipe for building kokkos with cuda and vtkm? I'm trying to get them to build on summit as well but I am not having success.

**Comment by renderdude** [comment]
Sure, this is the script that I use for Summit (it's more of a cut and paste thing then actually running it). Also, I found that it's in the RC-3.6.0 branch, so I'm trying a git bisect to find the bug, but it's a 2+ hour loop each good/bad selection:

use_gcc=true

if ${use_gcc}; then
  CUDA_VERSION=11.4.2
  COMPILER_VERSION=10.2.0
  module load cuda/${CUDA_VERSION} gcc/${COMPILER_VERSION} cmake git-lfs git
  CXX_COMPILER=/sw/summit/gcc/$COMPILER_VERSION/bin/g++
  C_COMPILER=/sw/summit/gcc/$COMPILER_VERSION/bin/gcc
else
  CUDA_VERSION=10.2.89
  COMPILER_VERSION=12.0.0
  module load cuda/${CUDA_VERSION} llvm/${COMPILER_VERSION} cmake git-lfs git
  CXX_COMPILER=`which clang++`
  C_COMPILER=`which clang`
fi

home_dir=$(pwd)
host=summit
use_master=true
checkout=false
cmake_build_type=Release
vtkm_version=vtk-m_bolstad
vtkm_src_dir=${home_dir}/ECP/${vtkm_version}

cd ${vtkm_src_dir}
vtkm_hash=`git log | head -1 | awk '{print $2}' | cut -c1-7`
cd ${home_dir}

if ${use_master}; then
  kokkos_src_dir=${home_dir}/ECP/kokkos
  build_dir=${home_dir}/scratch/${host}/kokkos_master/${vtkm_version}_${vtkm_hash}/${COMPILER_VERSION}/${cmake_build_type}
else
  kokkos_src_dir=${home_dir}/ECP/kokkos_develop
  build_dir=${home_dir}/scratch/${host}/kokkos_develop/${vtkm_version}_${vtkm_hash}/${COMPILER_VERSION}/${cmake_build_type}
fi

kokkos_build_dir=${build_dir}/build/kokkos
kokkos_install_dir=${build_dir}/install

benchmark_src_dir=${home_dir}/ECP/benchmark/
benchmark_build_dir=${build_dir}/build/benchmark
benchmark_install_dir=${build_dir}/install

vtkm_build_dir=${build_dir}/build/${vtkm_version}
vtkm_install_dir=${build_dir}/install

if ${checkout}; then
  cd ${home_dir}/ECP
  git clone https://github.com/google/benchmark.git
  git clone https://github.com/google/googletest.git benchmark/googletest
  git clone -b develop https://github.com/kokkos/kokkos.git ${kokkos_src_dir}
  git clone https://github.com/kokkos/kokkos.git ${kokkos_src_dir}
  cd ${home_dir}
fi

rm -rf ${benchmark_build_dir}
cmake -S ${benchmark_src_dir} -B ${benchmark_build_dir} \
  -DCMAKE_BUILD_TYPE=${cmake_build_type} \
  -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
  -DCMAKE_C_COMPILER=${C_COMPILER} \
  -DCMAKE_INSTALL_PREFIX=${benchmark_install_dir}
cmake --build ${benchmark_build_dir} -j10
cmake --install ${benchmark_build_dir}

rm -rf ${kokkos_build_dir}
cmake -S ${kokkos_src_dir} -B ${kokkos_build_dir} \
  -DCMAKE_BUILD_TYPE=${cmake_build_type} \
  -DKokkos_ARCH_POWER9=ON  \
  -DKokkos_ARCH_VOLTA70=ON \
  -DKokkos_ENABLE_EXAMPLES=ON \
  -DKokkos_ENABLE_TESTS=OFF \
  -DKokkos_ENABLE_CUDA=ON \
  -DKokkos_ENABLE_CUDA_CONSTEXPR=ON \
  -DKokkos_ENABLE_CUDA_LAMBDA=ON \
  -DKokkos_ENABLE_CUDA_LDG_INTRINSIC=ON \
  -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=OFF \
  -DKokkos_ENABLE_CUDA_UVM=ON \
  -DCMAKE_CXX_FLAGS=-fPIC \
  -DCMAKE_CXX_STANDARD=14 \
  -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
  -DCMAKE_C_COMPILER=${C_COMPILER} \
  -DKokkos_CUDA_DIR=$CUDA_DIR \
  -DCUDA_cuda_driver_LIBRARY=$CUDA_DIR/lib64/libcuda.so.1 \
  -DCMAKE_INSTALL_PREFIX=${kokkos_install_dir}
cmake --build ${kokkos_build_dir} -j10
cmake --install ${kokkos_build_dir}

rm -rf ${vtkm_build_dir}
cmake -S ${vtkm_src_dir} -B ${vtkm_build_dir} \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF\
  -DCMAKE_BUILD_TYPE=${cmake_build_type} \
  -DVTKm_NO_DEPRECATED_VIRTUAL=ON \
  -DVTKm_ENABLE_KOKKOS=ON \
  -DVTKm_ENABLE_RENDERING=ON \
  -DVTKm_ENABLE_TESTING=OFF \
  -DVTKm_ENABLE_BENCHMARKS=ON\
  -DVTKm_ENABLE_CUDA=ON \
  -DBUILD_SHARED_LIBS=OFF \
  -DVTKm_USE_DOUBLE_PRECISION=OFF \
  -DVTKm_ENABLE_TESTING=OFF \
  -DCMAKE_CXX_STANDARD=14 \
  -DCMAKE_PREFIX_PATH=${kokkos_install_dir} \
  -DCMAKE_INSTALL_PREFIX=${vtkm_install_dir} \
  -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
  -DCMAKE_C_COMPILER=${C_COMPILER} \
  -DKokkos_DIR=${kokkos_install_dir}/lib64/cmake/Kokkos \
  -Dbenchmark_DIR=${benchmark_install_dir}/lib64/cmake/benchmark

bsub -Is -W 2:00 -nnodes 1 -P CSC331 /bin/zsh
cmake --build ${vtkm_build_dir} -j10

**Comment by renderdude** [comment]
Here's where bisect stand at the moment:
git bisect start
# good: [2834f94af9b01debf67c1aaa3f0eb0c903d72c8d] Merge pull request #4643 from kokkos/PhilMiller-patch-1
git bisect good 2834f94af9b01debf67c1aaa3f0eb0c903d72c8d
# bad: [989ca926ea7bf82c5606d30828ade4ca63cfece5] Merge pull request #4866 from ndellingwood/rc-3.6.0-4852
git bisect bad 989ca926ea7bf82c5606d30828ade4ca63cfece5
# good: [2fc10503681d8968bf80c209b9e50839afabbd0d] Merge pull request #4312 from crtrott/fix-cpp20-warnings
git bisect good 2fc10503681d8968bf80c209b9e50839afabbd0d
# bad: [f47206f9c3959d37e1e9958ed90d50529e628995] Merge pull request #4511 from janciesko/local_deep_copy_use_TeamVectorRange
git bisect bad f47206f9c3959d37e1e9958ed90d50529e628995
# good: [58e05b159a39009cf925601297ba4ea52d402329] Merge pull request #4315 from NexGenAnalytics/standard-algorithms
git bisect good 58e05b159a39009cf925601297ba4ea52d402329
# bad: [7f14a46a62973b606847b0ca8008e74b52694964] Merge pull request #4509 from masterleinad/disable_fedora_icpc
git bisect bad 7f14a46a62973b606847b0ca8008e74b52694964

**Comment by renderdude** [comment]
After much bisecting, the commit that's tripping VTK-m (commit 626c806772ecbe938e202839a2d574b80aeeeef3) is the following:

733f23401fa43feaf922e69892e147fffc3134f2 is the first bad commit
commit 733f23401fa43feaf922e69892e147fffc3134f2
Author: Daniel Arndt <arndtd@ornl.gov>
Date:   Thu Sep 23 13:03:40 2021 -0400

    Don't fence in CUDA/HIP DeepCopy

 core/src/Cuda/Kokkos_CudaSpace.cpp |  9 +++------
 core/src/HIP/Kokkos_HIP_Space.cpp  | 10 ++--------
 core/src/Kokkos_CudaSpace.hpp      | 12 ------------
 core/src/Kokkos_HIP_Space.hpp      |  3 ---
 4 files changed, 5 insertions(+), 29 deletions(-)

**Comment by renderdude** [comment]
It looks like we may need to fence our deep_copy. Will update ticket if that fixes it.

**Comment by janciesko** [comment]
Great, thanks for looking into that. Let us know if fencing after the DC fixed the issue.

**Comment by Rombur** [comment]
Looking at the PR, the commit https://github.com/kokkos/kokkos/commit/733f23401fa43feaf922e69892e147fffc3134f2 will fail if the following commits are omitted. With the changes made in that commit, we need to add fences in Kokkos and that's only done in the following commits. However, it is possible that we forgot to fence something in Kokkos. 
@renderdude when you say that you are reverting the individual patches, are you modifying `develop`? If not you may get a false positive because like I said the commit cannot be considered alone. However, it would be a good idea to revert the change in `DeepCopyCuda` in `develop`. If that fixes the bug then that means that we forgot to fence something.

**Comment by renderdude** [comment]
I'm working on the RC-3.6.0 branch. However, I had made a mistake and was still on an older commit. I'm currently on HEAD for RC-3.6.0 (which crashes) and I reverted the change in DeepCopyCuda and am recompiling. It's just that Summit is slow and takes about an hour every time I rebuild VTK-m + Kokkos.

**Comment by renderdude** [comment]
Okey dokey. I reverted the change to DeepCopyCuda in RC-3.6.0 (commit 989ca926ea) and looped the benchmark 20 times and it passed all 20 without a crash. And for all sizes of wavelet-dims, [8,256] (pow of 2).

This is the change I made:
diff --git a/core/src/Cuda/Kokkos_CudaSpace.cpp b/core/src/Cuda/Kokkos_CudaSpace.cpp
index cc5c3b802..469bdb6fc 100644
--- a/core/src/Cuda/Kokkos_CudaSpace.cpp
+++ b/core/src/Cuda/Kokkos_CudaSpace.cpp
@@ -91,9 +91,10 @@ static std::atomic<int> num_uvm_allocations(0);
 }  // namespace

 void DeepCopyCuda(void *dst, const void *src, size_t n) {
-  cudaStream_t s = cuda_get_deep_copy_stream();
-  KOKKOS_IMPL_CUDA_SAFE_CALL(
-      cudaMemcpyAsync(dst, src, n, cudaMemcpyDefault, s));
+  KOKKOS_IMPL_CUDA_SAFE_CALL(cudaMemcpy(dst, src, n, cudaMemcpyDefault));
+//  cudaStream_t s = cuda_get_deep_copy_stream();
+//  KOKKOS_IMPL_CUDA_SAFE_CALL(
+//      cudaMemcpyAsync(dst, src, n, cudaMemcpyDefault, s));
 }

 void DeepCopyAsyncCuda(const Cuda &instance, void *dst, const void *src,

**Comment by ajpowelsnl** [comment]
Project:  https://gitlab.kitware.com/vtk/vtk-m

**Comment by ajpowelsnl** [comment]
Hi @renderdude -- can you confirm that this issue is now fixed in develop?
