### ISSUE TITLE
Constexpr operator[] for Kokkos::Array?

### ISSUE THREAD

**Issue by dutkalex** [kokkos/kokkos#4905]
Hi! I was wondering: why `Kokkos::Array`'s `operator[]` is not declared `constexpr`?
I'd like to be able to compute at compile time some coefficients and store them in a `Kokkos::Array`, and I end up having to write some ugly pieces of code in order to make this work (e.g. bypassing the API to access the C-array inside directly). I can't imagine a situation where having this operator available in a `constexpr` context could lead to trouble... Did I miss something?

**Comment by dalg24** [comment]
It looks like an oversight on our part.

**Comment by ajpowelsnl** [comment]
Discuss on Wed.

**Comment by nliber** [comment]
The whole `std::array` interface is `constexpr`; `Kokkos::Array` should be as well.  I think `.data()` is the only other function left that is not yet `constexpr`.

Note:  it may not just be an oversight.  I can't remember if C++17 language changes were required for the non-`const` versions of `operator[]` and `.data()` to be `constexpr`.

**Comment by dalg24** [comment]
This is fixed in the `develop` branch
