### ISSUE TITLE
DGX-2 (V100): maxBlocksPerMultiProcessor returns 0

### ISSUE THREAD

**Issue by jrouzaud** [kokkos/kokkos#4949]
Hello,

I am developing a simple code, it runs well on CPU (with OpenMP) but when trying with CUDA, it crashes due to an assert because block_size is set to 0.

I track (one of) the reason(s) within the Kokkos code.

cuda_max_active_block_per_sm : properties.maxBlocksPerMultiProcessor returns 0

I am using CUDA 11.5.1

Thank you very much,
Regards

**Comment by ajpowelsnl** [comment]
Hi @jrouzaud -- Many thanks for your question.  Would you please provide a simple, standalone reproducer for the error you're seeing?  Please include information about your compiler, Kokkos version, and any other details pertinent to your configuration and build steps.

**Comment by crtrott** [comment]
Hey, outside of a reproducer we think this is most likely a system setup issue. Feel free to reopen if you have more information.
