### ISSUE TITLE
Nightly failures of openmp.partition_master with gcc compilers (6.1.0, 6.4.0, 7.2.0, 8.3.0)

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4960]
Following merge to enable the partition master tests #4937  the openmp.partition_master test fails in nightly builds with gcc compilers:

```
18:25:29 1: [ RUN      ] openmp.partition_master
18:25:29 1: terminate called recursively
18:25:29 1: terminate called after throwing an instance of 'std::runtime_error'
18:25:29  1/48 Test  #1: KokkosCore_UnitTest_OpenMP ...................Subprocess aborted***Exception:  46.72 sec
18:25:29 [==========] Running 284 tests from 2 test suites.
```

**Reproducer** (gcc/6.4.0 case):
```
module load cmake/3.19.3 gcc/6.4.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=OpenMP --arch=Power9 --compiler=g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests
```

**Comment by Rombur** [comment]
It's because you need to set the variable `OMP_MAX_ACTIVE_LEVELS ` . See this [comment](https://github.com/kokkos/kokkos/pull/4937#discussion_r844416715).

**Comment by ndellingwood** [comment]
Once #4963 merges and I confirm the nightly tests resume pass I'll close the issue. Removing the Bug label

**Comment by ajpowelsnl** [comment]
Morning @ndellingwood -- can we put the `InDevelop` label on this issue now?

**Comment by ndellingwood** [comment]
@ajpowelsnl yes thanks for the follow up. The updates to testing script resolved the issue, I'll mark InDevelop and close
