### ISSUE TITLE
Structured bindings for Kokkos::Array ?

### ISSUE THREAD

**Issue by dutkalex** [kokkos/kokkos#4961]
Hi! I'm currently writing a piece of code that looks something like this...
```
KOKKOS_FUNCTION
Kokkos::Array<double,3> compute_heat_flux(Kokkos::Array<double,5> const& state) const {
    auto const& [rho, rho_u, rho_v, rho_w, rho_E] = state;
   ...
}
```
... and it seems like structured bindings does not work with `Kokkos::Array`s (`Kokkos::Array<double,5>` decomposes into 1 element and not 5 according to GCC). However, if I replace `Kokkos::Array<double,5>` by `std::array<double,5>`everything works perfectly fine. Is it just an oversight, or is it not allowed on purpose ?

**Comment by dalg24** [comment]
Because no one asked for it and some of us are stuck in C++14 world.
I can't think of any reason why we can't support it.

**Comment by dalg24** [comment]
Merged in `develop`.  Closing.  Feel free to re-open if there is any issue with it.
