### ISSUE TITLE
Limit configuration to a single CPU microarchitecture target

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#4964]
Per https://github.com/kokkos/kokkos/issues/4953 and meeting discussion today, we'd like the CMake configuration process to detect when the user has passed options for more than one target CPU microarchitecture, and error out. This is going to either fail to build, or silently pass the underlying compiler a series of options that will only ultimately support one of the requested targets, which would not honor the user's request.

**Comment by ajpowelsnl** [comment]
Discuss more when CRT and DLG return
