### ISSUE TITLE
Investigate possible race condition in kokkos::parallel_reduce

### ISSUE THREAD

**Issue by overfelt** [kokkos/kokkos#4970]
Background:  The Exawind wind turbine project has a construct where master element singleton classes are allocated on device and simple integer data such as number of nodes per element can either be accessed on device or returned to host, depending on 
the context.  This has worked for years but since advancing to Cuda 11 and gcc 8 we were seeing intermittent segmentation violations in the simple kokkos::parallel_reduce that is used to access the device pointer.

In trying to determine why the code sometimes failed with what appeared to be a NULL pointer dereference on device when printing the pointer showed it to be valid, we hit upon the cuda-memcheck with the  --tool racecheck option.  This seems to show a race condition in the kokkos::parallel_reduce call.  Unfortunately the racecheck option has a lot of false positives and this might be one of them.  

Eventually the code was rewritten to use a kokkos::view of length one to return an integer from device and we have had no problems with the new pattern.  But we still do not understand why the previous code sometimes failed.

To create a kokkos unit test that demonstrates the possible race condition, a bit of code was added to one of the kokkos unit tests. This was then compiled and installed with debugging turned on and executed with the command
`
cuda-memcheck  --tool racecheck --racecheck-report all --print-limit 10000 ./core/unit_test/KokkosCore_UnitTest_Cuda1  --gtest_filter=cuda.device_ptr_parallel_reduce_on_device
` 
Read-After-Write (RAW) race conditions in the parallel_reduce are the messages we are looking at and wondering if reducing on a single thread could be the root of the problem.    

git diff with the added unit test:
```
diff --git kokkos/core/unit_test/TestHostSharedPtrAccessOnDevice.hpp
index 1018025..7700c34 100644
--- a/packages/kokkos/core/unit_test/TestHostSharedPtrAccessOnDevice.hpp
+++ b/packages/kokkos/core/unit_test/TestHostSharedPtrAccessOnDevice.hpp
@@ -129,8 +129,37 @@ CheckSpecialMembersOnDevice<Ptr> check_special_members_on_device(Ptr p) {
   return {p};
 }

+template <class DevMemSpace>
+void test_device_ptr_parallel_reduce_on_device () {
+  using ExecSpace = typename DevMemSpace::execution_space;
+  using T = int;
+  T* device_ptr = static_cast<T*>(Kokkos::kokkos_malloc<DevMemSpace>(sizeof(T)));
+
+  Kokkos::fence();
+  Kokkos::parallel_for(
+      Kokkos::RangePolicy<ExecSpace>(0, 1),
+      KOKKOS_LAMBDA(int) { *device_ptr = 99;});
+  Kokkos::fence();
+
+  T host_val = 0;
+  Kokkos::parallel_reduce(
+    Kokkos::RangePolicy<ExecSpace>(0, 1),
+    KOKKOS_LAMBDA(int, T &t) {
+      t = *device_ptr;
+    },
+  host_val);
+  Kokkos::fence();
+
+  ASSERT_EQ(99, host_val);
+  Kokkos::kokkos_free<DevMemSpace>(device_ptr);
+}
 }  // namespace

+TEST(TEST_CATEGORY, device_ptr_parallel_reduce_on_device) {
+  using MemorySpace = TEST_EXECSPACE::memory_space;
+  test_device_ptr_parallel_reduce_on_device<MemorySpace>();
+}
+
 TEST(TEST_CATEGORY, host_shared_ptr_dereference_on_device) {
   using T = Data;

```

**Comment by PhilMiller** [comment]
I fixed most racecheck reports that I previously observed in `parallel_reduce` on CUDA in #4855 which is merged in `develop` but is not on 3.6. Assuming you tested against the last release 3.5 or the pending 3.6 release candidate branch, could you see if this still crops up?

Separately, do I understand correctly that the code was using a reduction of length 1 to essentially implement a single element `deep_copy` from device to host? I know we have a view-from-scalar broadcast overload, but this maybe suggests we should have an overload for the simple host-scalar-from-rank-0-view case, too.

**Comment by PhilMiller** [comment]
Also, see the description of #4931 for references to a couple other fixes that may yet be necessary to make the reduction code more fully sound.

**Comment by overfelt** [comment]
@PhilMiller , I was using the Trilinos master branch for my tests, Kokkos version 3.5 without your fixes.  I'll rerun my tests with 3.6.  

Yes, the parallel_reduce was just an easy way to copy a single scalar from device to host and was not a reduction since the loop was length 1.  But this is not a construct we use extensively. 

Thanks for your quick reply.

**Comment by PhilMiller** [comment]
Ah, to be clear, the fixes in question are not in 3.6 either, only develop, but they'd be easy to cherry pick. I finished them up after we'd started to stabilize 3.6, do we didn't add them to the branch. If it's valuable to you, we can consider them for a potential 3.6.1 patch release

**Comment by overfelt** [comment]
We have a work around, no need for a patch release.

**Comment by overfelt** [comment]
I re-ran my test case with the `develop` branch and instead of 2058 `racecheck` warnings there were absolutely none.  Good job.
