### ISSUE TITLE
Unable to compile Kokkos::SYCL backend for Intel Iris XeMAX 

### ISSUE THREAD

**Issue by kakwok** [kokkos/kokkos#4974]
I'm using Kokkos develop branch with dpcpp 2022.0.0
I configure cmake with:
```
cmake  -DCMAKE_CXX_COMPILER=dpcpp -DKokkos_ENABLE_SYCL=On -DKokkos_ARCH_INTEL_DG1=On -DKokkos_CXX_STANDARD=17  ../
```
But I get the following error during compilation:
```
[100%] Linking CXX executable p2r_kokkos
llvm-foreach: No such file or directory
dpcpp: error: gen compiler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/p2r_kokkos.dir/build.make:87: p2r_kokkos] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: CMakeFiles/p2r_kokkos.dir/all] Error 2
```
The same program compiles successfully for Intel Gen 9 GPU(Intel(R) UHD Graphics P630).

Without the `DKokkos_ARCH_INTEL_DG1` flag, the program compiles, but I have the following during run time: 

```
terminate called after throwing an instance of 'cl::sycl::compile_program_error'
  what():  The program was built for 1 devices
Build program log for 'Intel(R) Iris(R) Xe MAX Graphics [0x4905]':

error: double type is not supported on this platform
in file: propagate-tor-test_kokkos.cpp:483

in kernel: 'typeinfo name for cl::sycl::event Kokkos::Impl::ParallelFor<main::'lambda'(Kokkos::Impl::SYCLTeamMember const&), Kokkos::TeamPolicy<>, Kokkos::Experimental::SYCL>::sycl_direct_launch<Kokkos::Experimental::Impl::SYCLFunctionWrapper<main::'lambda'(Kokkos::Impl::SYCLTeamMember const&), Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<(cl::sycl::usm::alloc)0>, false> >(Kokkos::Impl::TeamPolicyInternal<Kokkos::Experimental::SYCL> const&, Kokkos::Experimental::Impl::SYCLFunctionWrapper<main::'lambda'(Kokkos::Impl::SYCLTeamMember const&), Kokkos::Experimental::Impl::SYCLInternal::USMObjectMem<(cl::sycl::usm::alloc)0>, false> const&, cl::sycl::event const&) const::'lambda'(cl::sycl::handler&)::operator()(cl::sycl::handler&) const::'lambda'(cl::sycl::nd_item<2>)'
error: backend compiler failed build.
```

**Comment by dalg24** [comment]
Did it actually configure?
Looking at https://github.com/kokkos/kokkos/blob/1b1cfbc3249b42e9f3d18f1ea90414434d5c1d52/cmake/kokkos_arch.cmake#L506-L533 it should not.  In any case, it is not legal to specify multiple architectures.

**Comment by masterleinad** [comment]
Have a look at https://community.intel.com/t5/Intel-DevCloud/Iris-Xe-MAX-node-is-missing-double-precision-support/m-p/1247876 for JIT compilation, i.e., only specifying `-DKokkos_ARCH_INTEL_GEN=ON`.

**Comment by masterleinad** [comment]
> Sorry for the typo, i used `KOKKOS_ARCH_INTEL_GEN9` for the GEN9 GPU, which worked, and `Kokkos_ARCH_INTEL_DG1` for the Iris-XeMAX, which does not work. I did not specify multiple architectures.

@kakwok Were you able to resolve your issues in the meantime following the suggestions in https://community.intel.com/t5/Intel-DevCloud/Iris-Xe-MAX-node-is-missing-double-precision-support/m-p/1247876?

**Comment by masterleinad** [comment]
This is an issue with the driver for particular hardware and nothing that `Kokkos` can fix.
