### ISSUE TITLE
Add Kokkos Library Compatibility Documentation

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos#4985]
Add a standing document to Kokkos documentation describing what Kokkos means by compatibility, modeled on the [C++ SD-8 Standard Library Compatibility](https://isocpp.org/std/standing-documents/sd-8-standard-library-compatibility) document.

**Comment by ajpowelsnl** [comment]
Morning @nliber -- How this going?  Will this be in by Kokkos 3.7 in a couple of weeks : )
