### ISSUE TITLE
segmentation fault on kokkos::initialize

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#4987]
```
#include <iostream>
using std::cout;
#include "Kokkos_Core.hpp"

int main(int argc,char *argv[]) {
  Kokkos::initialize(argc,argv);
  return 0;
}
```

Compiled and linked with the Kokkos installation that PETSc provides, Intel 19 compiler.

(Why can't I attach the kokkoscore config file? Is there a setting to allow .h files?)

[kokkos.zip](https://github.com/kokkos/kokkos/files/8584741/kokkos.zip)

**Comment by VictorEijkhout** [comment]
```
(gdb) where
#0  0x00002aaaaab0b415 in Kokkos::Impl::(anonymous namespace)::parse_command_line_arguments (
    narg=@0x7fffffff9110: 1, arg=0x7fffffff92a8, arguments=...)
    at /tmp/petsc-3.16/clx/clx/git.kokkos/core/src/impl/Kokkos_Core.cpp:640
#1  0x00007fffffff92a8 in ?? ()
#2  0x00002aaaaab09e88 in Kokkos::initialize (narg=@0x7fffffff9110: 1, arg=0x7fffffff92a8)
    at /tmp/petsc-3.16/clx/clx/git.kokkos/core/src/impl/Kokkos_Core.cpp:1064
#3  0x0000000000402336 in main (argc=1, argv=0x7fffffff92a8) at policy.cxx:19
```

**Comment by crtrott** [comment]
I can't really reproduce this, is there potentially a mismatch between the compiler used to install Kokkos and the compiler used to compile the executable?

**Comment by crtrott** [comment]
Probably I need the full petsc configure/install command and probably the exact petsc version. FYI the version of Kokkos which was installed there was not a release version (3.4.99 indicates that it was a develop version sometime after the fork of the 3.4.00 release candidate, but before the fork of the 3.5.00 release candidate).

**Comment by ajpowelsnl** [comment]
Hi @VictorEijkhout -- Are you still having runtime problems?

**Comment by VictorEijkhout** [comment]
Must have been a compiler or MPI mismatch. Closing.
