### ISSUE TITLE
Deprecate KOKKOS_CXX_STANDARD variable in CMake

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#4999]
`KOKKOS_CXX_STANDARD` is essentially a wrapper around `CMAKE_CXX_STANDARD`, with a literal string "c++" prepended. If users specify it, print a deprecation warning referring to the common CMake variable

**Comment by ndellingwood** [comment]
Cross-referencing #3432, at one point there was a reason to have `KOKKOS_CXX_STANDARD` for downstream apps (not sure if this was necessitated by TriBITS/Trilinos or with stand-alone Kokkos) but the reason may no longer hold

**Comment by PhilMiller** [comment]
Stop accepting `KOKKOS_CXX_STANDARD` as configuration input, still export it for downstream users

**Comment by PhilMiller** [comment]
Digging into the code, it internally gets set with the `c++` prefix stripped off.

**Comment by PhilMiller** [comment]
PR #5066

**Comment by PhilMiller** [comment]
Merged, closing
