### ISSUE TITLE
subview(X, ALL(), j) for 2-D LayoutRight View X: should it view a column?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#5]
I think it's actually viewing a row, which I find counterintuitive.  Should it view a column instead?  I'm only having this trouble for LayoutRight views.

**Comment by crtrott** [comment]
Uhm it views a column as far as I see. But it does not return layout right, but LayoutStride.

**Comment by mhoemmen** [comment]
Cool, just checking that this is what it's supposed to do :-)  I'll add a test for this to the TpetraKernels multivector test.  (The issue is that for our BLAS1 multivector kernels, the 1-D View version gives the right answer for LayoutLeft, but not for LayoutRight.  So, it's not an urgent issue, but if we ever want LayoutRight multivectors in Tpetra, we'll need to figure it out.)

**Comment by crtrott** [comment]
Ok there is/was a serious issue with LayoutStride. I think I fixed them and will push that in a minute. Sync to Trilinos will take a bit since I have to rebuild/run all of it.

**Comment by crtrott** [comment]
Ok after pushing to Kokkos and in the middle of the Trilinos test/push cycle my machine died a horrible death (i/o bus error). Actually its not quite dead, but it doesn't let me reboot from the commandline (bus error). So the push to Trilinos has to wait till tomorrow I guess.

**Comment by crtrott** [comment]
This thing is pushed and should be resolved. I close the issue, please reopen if you still have problems.

**Comment by mhoemmen** [comment]
Thanks Christian! :-D
