### ISSUE TITLE
UVM allocations in multi-GPU systems

### ISSUE THREAD

**Issue by sphamil** [kokkos/kokkos#50]
In dual-socket systems with multiple GPUs, Cuda managed memory allocations will default to pinned memory allocations on the host, leading to very poor performance in access from device.  This behavior can be overriden with environment variables CUDA_MANAGED_FORCE_DEVICE_ALLOC and CUDA_LAUNCH_BLOCKING.  Per email exchange with Christian Trott, Kokkos should be able to check whether such variables are set and issue an appropriate warning (or error).

**Comment by crtrott** [comment]
The check for now the variables is possible. I looked into actually setting them but the driver seems to read them before the process actually starts.

**Comment by crtrott** [comment]
This now spits out warnings when using force_uvm, without setting the environment variables.

**Comment by crtrott** [comment]
Pushed to master
