### ISSUE TITLE
Trilinos nightly Cuda build errors, stk: error: An extended __host__ __device__ lambda cannot capture variables with array type

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5007]
**Describe the bug**
Nightly cuda/10.1 builds of Trilinos' kokkos-promotion branch with kokkos and kokkos-kernels' develop branches results in compilation errors with unit tests in the stk package (stk_expreval subset):

```
[ 62%] Building CXX object packages/stk/stk_expreval/unit_tests/CMakeFiles/STKExprEval_stk_expreval_unit_tests.dir/UnitTestEvaluator.cpp.o
/ascldap/users/ndellin/trilinos/Trilinos-pristine/packages/stk/stk_expreval/unit_tests/UnitTestEvaluator.cpp(134): error: An extended __host__ __device__ lambda cannot capture variables with array type

/ascldap/users/ndellin/trilinos/Trilinos-pristine/packages/stk/stk_expreval/unit_tests/UnitTestEvaluator.cpp(134): error: An extended __host__ __device__ lambda cannot capture variables with array type

[ 62%] Building CXX object packages/krino/krino/krino_lib/CMakeFiles/krino_lib.dir/Akri_Compute_Surface_Distance.cpp.o
/ascldap/users/ndellin/trilinos/Trilinos-pristine/packages/stk/stk_expreval/unit_tests/UnitTestEvaluator.cpp(186): error: An extended __host__ __device__ lambda cannot capture variables with array type

/ascldap/users/ndellin/trilinos/Trilinos-pristine/packages/stk/stk_expreval/unit_tests/UnitTestEvaluator.cpp(186): error: An extended __host__ __device__ lambda cannot capture variables with array type

/ascldap/users/ndellin/trilinos/Trilinos-pristine/packages/stk/stk_expreval/unit_tests/UnitTestEvaluator.cpp(2583): warning: function "<unnamed>::Ngp_testRandom" was declared but never referenced

4 errors detected in the compilation of "/tmp/tmpxft_00027913_00000000-6_UnitTestEvaluator.cpp1.ii".
```

These errors do not occur with Trilinos' develop branch, indicating a change in Kokkos is triggering this. @dalg24 @masterleinad any guesses on what change might produce errors of the type I posted? Adding @ldh4 for potential input on the stk side

**Reproducer** (Weaver testbed):
```bash
# Repos
git clone -b kokkos-promotion https://github.com/trilinos/Trilinos.git
git clone -b develop kokkos
git clone -b develop kokkos-kernels
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Modules and env
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/weaver
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
module list
export OMPI_CXX=<path-to-your-kokkos-repo>/bin/nvcc_wrapper

# Configure
cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX=$PWD/install \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DTrilinos_ENABLE_Stokhos=ON \
 -DSTKExprEval_ENABLE_TESTS=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by ldh4** [comment]
There was a stk snapshot update to Trilinos a few days ago (5/6/2022) that may have introduced this failure.
And I see that there are array capturing into extended lambdas which shouldn't be happening.
I can look into this.

**Comment by ldh4** [comment]
@ndellingwood
Could you check what exact Cuda version the command `source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt` in your script loads?
It seems that starting from `cuda 10.1.168`, this compilation error will not produced, but I see that `weaver` also has `cuda/10.1.105`, which will produce this error. So I'm wondering if that's what it used to build.

**Comment by ndellingwood** [comment]
@ldh4 the cuda version is `cuda/10.1.105` that is used. Just to check, you're building with kokkos and kokkos-kernels' develop branches from the repo (not the Trilinos packages)? This is necessary to reproduce the error.

To provide additional info that may be helpful, the kokkos-promotion branch tested includes up to SHA 00f1cf4c24646bb27074123268d1b1908d778c5f of the develop branch from May 6 (there are two additional commits to sacado and stokhos tracked on the branch that are not backward compatible with Trilinos, #4902 has additional details though I think unnecessary to the stk issue)
I retested locally with rebase of Trilinos up to SHA 69249c127f2b0c2feca37029d62b7e52e40cf8d1 , but still see the same compilation errors in the configuration of the OP

**Comment by ndellingwood** [comment]
@ldh4 also, if you have access to weaver you can call `source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt` to reproduce the module environment (TRILINOS_DIR points to the Trilinos source directory). Thanks for working toward reproducing the error so quickly

**Comment by ndellingwood** [comment]
@ldh4 excellent, thanks for the update! I'll get the kokkos-promotion branch of Trilinos rebased with those changes and reenable the STK tests in the Cuda builds

**Comment by ndellingwood** [comment]
@ldh4 I reenabled the stk tests yesterday for the Cuda builds, the `STKExprEval_stk_expreval_unit_tests_MPI_1` test failed in testing with UVM disabled as the default memory space (that is `-DKokkos_ENABLE_CUDA_UVM=OFF`) and no launch blocking (`unset CUDA_LAUNCH_BLOCKING`).

I ran the testing with `--output-on-failure` but it did not generate any useful output for the reason of the tests failure. Based on the configuration, possibly a missing fence somewhere?

**Comment by ldh4** [comment]
@ndellingwood I was able to reproduce the failures, and I think I know where the problem is. I'll get it patched and request another STK snapshot update to be done asap.

**Comment by ndellingwood** [comment]
@ldh4 thanks for the update and fast response!

**Comment by ajpowelsnl** [comment]
Morning @ldh4  -- How this going? Will this be in by Kokkos 3.7 in a couple of weeks : )

**Comment by ldh4** [comment]
@ajpowelsnl I am currently waiting on a Trilinos PR to get merged in. It's still going through the auto-tester, but it should definitely be in by Kokkos 3.7.

**Comment by ldh4** [comment]
@ndellingwood STK just had another snapshot update into Trilinos. Can you try re-enabling STK in the CUDA build again and see if it is good this time?

**Comment by ndellingwood** [comment]
Thanks @ldh4 for the fix, closing the issue
