### ISSUE TITLE
Kokkos Tests are Not Run using Compiler Optimization

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#501]
Running some Kokkos tests across various platforms and I'm not seeing many of them issue even basic `-O3` style optimization requests. We probably should be testing `-O2` and `-O3` as a way of checking we do not have subtle bugs in our codes. Seems to be most users switch between these two options in production environments.

**Comment by nmhamster** [comment]
OK, its early in the morning and I am not full of caffeine yet. `-O3` is present but should we or could we test with `-O2` as well? I am conscious on some platforms like POWER we may want to test with `-O4` and `-O5` as well (XL and PGI).

**Comment by crtrott** [comment]
I think you can simply override the cxxflags with --cxxflags.

**Comment by crtrott** [comment]
So do we have an actual issue or not? Is your suggestion just to add more tests some of them using -O2?

**Comment by hcedwar** [comment]
Add a **small** number of configurations in integration and nightly.  Will have to monitor total resource consumption for testing.

**Comment by crtrott** [comment]
The mechanism is added, can put the jobs up in Jenkins now.
