### ISSUE TITLE
generate_makefile.bash: "make install" is broken

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#503]
There is an inconsistency with target "make install":

When defining target install, variable PREFIX appears twice.

Right now PREFIX value set by user on command line of generate_makefile.bash is not taken into account, overriden by the second occurence of PREFIX on make install target.

So "make install" installs kokkos in the build directory, instead of prefix passed through command line.

**Comment by crtrott** [comment]
Args. I screwed that up when improving our testing so that examples are build against an installed Kokkos in order to a) test compiling against an installed kokkos and b) improve compile times. 
I'll fix that again.

**Comment by crtrott** [comment]
Ok I think I got it. Note the library target hat to be renamed to "kokkoslib" and the one which is used for testing is actually "kokkoslib-test" and "install-test". The kokkoslib and install target will use the user provided prefix, the test targets will not. Does that sound good?

**Comment by crtrott** [comment]
Should be fixed now.
