### ISSUE TITLE
multi_scratch test with hwloc and pthreads seg-faults. 

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#504]

**Comment by nmhamster** [comment]
I think this may also be failing with OpenMP on POWER8 with PGI.

**Comment by crtrott** [comment]
Ok. It did pass with all compilers using OpenMP tonight on HSW and KNL, just the pthread-hwloc tests failed. My suspicion is that it will fail with Pthreads without hwloc as well if I crank up the number of threads. Without hwloc pthreads defaults to 4 thread testing, while OpenMP would use more.

**Comment by crtrott** [comment]
Can't replicate on my workstation ...

**Comment by crtrott** [comment]
Can't seem to replicate on kokkos-dev either (which was the machine which failed tonight ...)

**Comment by crtrott** [comment]
Ok not sure what is going on. If I do test_all_sandia gcc/4.8.4 the test fails with pthread and hwloc, if I do test_all_sandia gcc/4.8.4 --build-list=Threads it doesn't. And after building I can go into the build dircectories just run the tests and they fail/don't fail reliably ...

**Comment by crtrott** [comment]
On my workstation I can't replicate either way.

**Comment by jgfouca** [comment]
The only difference between your workstation and kokkos-dev is that you've sync'd the TPLs to local storage?

**Comment by crtrott** [comment]
No its slightly different OS, more memory, more cores, Haswell instead of Ivy Bridge.

**Comment by jgfouca** [comment]
Do you think this is a problem with NFS or test_all_sandia? If not, I'll ignore this ticket.

**Comment by crtrott** [comment]
No its not.

**Comment by crtrott** [comment]
Tracked it down to running this: 
./KokkosCore_UnitTest_Threads --gtest_filter=threads.team_lambda_shared_request:threads.multi_level_scratch

If I run all tests except team_lambda_shared_request, everything passes. So it looks like it might be a problem in that instead of others.

**Comment by crtrott** [comment]
Ok individually those two tests come back clean in valgrind, but segfault if they are executed one after the other ...

**Comment by nmhamster** [comment]
@crtrott sounds like you have some clean up which isn't performed properly.

**Comment by crtrott** [comment]
I believe there is something funky going on with the resize of the internal scratch array stuff. Because both tests use it but with different team sizes. If I reduce team_size to 2 for the second test it passes.

**Comment by crtrott** [comment]
Also if I run with mpirun -np -map-by socket:PE=8 it passes, with mpirun -np -map-by socket:PE=10 it fails (using team_size = 4 in either case).

**Comment by crtrott** [comment]
mpirun -np -map-by node:PE=16 passes mpirun -np -map-by node:PE=20 fails. And now when I run with that restriction on my machine (i.e. -map-by socket:PE=10) it also fails there. Not quite sure yet whats going on, on my machine with -map-by node:PE=20 it passes which should actually match what kokkos-dev runs.

**Comment by crtrott** [comment]
Got it :-)
