### ISSUE TITLE
Add GCC 6.x support

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#508]
This depends on issues: #445 and #298

**Comment by gmackey** [comment]
Issue #298 has been fixed and pushed to develop.  So, GCC 6.1.0 is working except in the case of being used with Intel 17.0.098 to compile for Knights Landing.

**Comment by crtrott** [comment]
that KNL thing seems also to work at least with GCC 6.2.0 (which is the only one I could test right now).
