### ISSUE TITLE
Is there a manual? Does the doxyfile work?

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#5083]
```
[eijkhout/Installation/kokkos 1005] cd kokkos/doc
[kokkos/kokkos/doc 1006] ls
Doxyfile                                design_notes_space_instances.md
Kokkos-Programming-Guide.md             develop_builds.md
SAND2017-10464-Kokkos-Task-DAG.pdf      hardware_identification/
TuningDesign.md                         index.doc
build_docs*                             kokkos-promotion.txt
[kokkos/kokkos/doc 1007] doxygen
error: @INCLUDE = ../../common/Doxyfile: not found!
Exiting...
[kokkos/kokkos/doc 1008] find .. -name common
[kokkos/kokkos/doc 1009]
```

**Comment by dalg24** [comment]
> Is there a manual

See the wiki https://github.com/kokkos/kokkos/wiki
There is a reference to it in the README https://github.com/kokkos/kokkos#learning-about-kokkos

> Does the doxyfile work?

No.  We do not rely on Doxygen for documentation.  Please refer to the API reference in the wiki instead https://github.com/kokkos/kokkos/wiki/API-Reference

**Comment by VictorEijkhout** [comment]
On , 2022Jun2, at 11:19, Damien L-G ***@***.******@***.***>> wrote:

No. We do not rely on Doxygen for documentation

Time to remove that from the repo?

Victor.

**Comment by dalg24** [comment]
@ndellingwood is `doc/Doxyfile` still used by Trilinos?

**Comment by ndellingwood** [comment]
@dalg24 Trilinos uses Doxygen though I'm not certain that particular file is needed, I'll check with someone on the Frameworks team to confirm what is required
