### ISSUE TITLE
documentation quibbles

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#5084]
https://github.com/kokkos/kokkos/wiki/Compiling

"adding the following to you your CMakeLists.txt:"

*cough*

"KOKKOS_ENABLE_PTHREADS"

```
\grep KokkosCore_config.h
/* #undef KOKKOS_ENABLE_THREADS */
```

*cough cough*

**Comment by dalg24** [comment]
Please use `-DKokkos_ENABLE_THREADS=ON`
We will update the doc

**Comment by VictorEijkhout** [comment]
No answer why pthreads & openmp are incompatible?

**Comment by dalg24** [comment]
We only allow one host parallel backend, just like we allow only one device backend.
The design decision predates my working on the project.
Do you have a use case for this?

**Comment by Rombur** [comment]
We don't want people to mix `pthreads` and `openmp` in the same code. The standards don't guarantee that you can do it and you can have bad performance because both model try to acquire the same resources.

**Comment by stanmoore1** [comment]
>Ok, so what keeps you from having both OpenMP & CUDA enabled? In fact that combination makes sense to me, since I could use the OMP threads to manage the multiple CUDA devices.

This is allowed: OMP is a host parallel backend, CUDA is a device backend, you can only have 1 of each.

**Comment by PhilMiller** [comment]
> Ok, so what keeps you from having both OpenMP & CUDA enabled? In fact that combination makes sense to me, since I could use the OMP threads to manage the multiple CUDA devices.

Note that you can't actually drive more than one CUDA device from a single process via Kokkos, at least by default.

You could manually create CUDA streams bound to each device, but the memory allocation would definitely all be on you, and I expect that the notionally global `Kokkos::fence()` doesn't know it needs to do something more involved than `cudaDeviceSynchronize()` to synchronize across all those devices

**Comment by VictorEijkhout** [comment]
On , 2022Jun3, at 13:03, Bruno Turcksin ***@***.******@***.***>> wrote:

We don't want people to mix pthreads and openmp in the same code.

How about two different codes being built against the same installation by me as the sysadmin?

Or are you assuming that everyone installs kokkos in their own private account?

Victor.

**Comment by dalg24** [comment]
If you want to provide Kokkos with OpenMP and C++ Threads, you will need to two different installs of Kokkos
