### ISSUE TITLE
Remove `Kokkos::Tools::InitArguments::tune_internals` data member

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5087]
The runtime option for tuning (introduced in #3459) is currently being parsed when initializing kokkos-tools but it really belongs to Kokkos core.  I suspect it was implemented this way out of convenience to circumvent the lack of support for "possibly unset option" in Core.
I propose we fix this whenever we require C++17

```diff
diff --git a/core/src/Kokkos_Core.hpp b/core/src/Kokkos_Core.hpp
index 232873d3f..18b6f43c2 100644
--- a/core/src/Kokkos_Core.hpp
+++ b/core/src/Kokkos_Core.hpp
@@ -88,7 +88,7 @@ struct InitArguments {
   int ndevices;
   int skip_device;
   bool disable_warnings;
-  bool tune_internals;
+  std::optional<bool> tune_internals;
   bool tool_help        = false;
   std::string tool_lib  = {};
   std::string tool_args = {};
diff --git a/core/src/impl/Kokkos_Profiling.hpp b/core/src/impl/Kokkos_Profiling.hpp
index 4a8527f5e..c1e9d1e37 100644
--- a/core/src/impl/Kokkos_Profiling.hpp
+++ b/core/src/impl/Kokkos_Profiling.hpp
@@ -66,10 +66,9 @@ struct InitArguments {
   // for this long-term
   static const std::string unset_string_option;
   enum PossiblyUnsetOption { unset, off, on };
-  PossiblyUnsetOption tune_internals = unset;
   PossiblyUnsetOption help           = unset;
   std::string lib                    = unset_string_option;
   std::string args                   = unset_string_option;
```

**Comment by dalg24** [comment]
Actually it just occurred to me that neither the command line argument`--kokkos-disable-warnings` nor the environment variable `KOKKOS_DISABLE_WARNINGS` can be used to disable deprecation warnings for using deprecated command line arguments (`--kokkos-ndevices` instead of `--kokkos-num-devices`).
More interestingly these warnings are printed regardless of what the configuration options `Kokkos_ENABLE_DEPRECATED_CODE_3` and `Kokkos_ENABLE_DEPRECATION_WARNINGS` are set to.

**Comment by ajpowelsnl** [comment]
@dalg24 , @ajpowelsnl , @crtrott -- Detail the need for this refactor.  Status quo recommended (vs. the proposed change).

**Comment by ajpowelsnl** [comment]
@dalg24 -- Are we able to close this issue now?
