### ISSUE TITLE
CMake project language duplicates cause issues

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#5092]
**Describe the bug**
I ran into a very subtle issue where the
CXX language was listed twice in the
CMake project command (which I think is
the normal use case) and this caused
CMAKE_CXX_OUTPUT_EXTENSION to somehow
come through as empty, meaning that
if you compiled foo.cpp, the compiled
object file would also be named foo.cpp
instead of the desired foo.cpp.o
This would in turn cause nasty compile
failures that were also a bit unpredictable.
Sometimes Kokkos would still link okay
but other times (after a rebuild for example)
the object file would be interpreted as
a source file.

**Please also include the following items to support reproducing the bug**
1. compilers (with versions) Apple Clang
2. Kokkos release or commit used (i.e., the sha1 number) ecbfc2f7d3902061d3e60ed7861845925ad8d48e
3. platform and backend: macOS, Serial backend only
4. cmake configure command: `-DCMAKE_INSTALL_PREFIX=/Users/daibane/src/capp-alegra-ng/flavor/skylake
/install/kokkos -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=17 -DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON -DKokkos_ENABLE_CUDA=OFF -DKokkos_ENABLE_CUDA_LAMBDA=OFF -DKokkos_ENABLE_OPENMP= -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_SKX=ON -DKokkos_ENABLE_TESTS=ON`
5. output from cmake command
    ```
    CMakeFiles/kokkosprinter-tool.dir/tools/printing-tool.cpp:1:1: error: source file is not valid UTF-8
    ```
7. code needed to reproduce the bug: nothing but Kokkos
8. command line needed to reproduce the bug: just compiling
7. please also attach the `KokkosCore_config.h` header file (generated during the build);
**Any additional info**
Please provide any additional context about the issue here.

I have fixed this in #5091

**Comment by dalg24** [comment]
The issue was specifically triggered for `-DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE -DKokkos_ENABLE_CUDA=OFF`
