### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#5101]
How do I prevent these:

```
n file included from /work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/Kokkos_Core.hpp(51),
                 from smooth.cxx(16):
/work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/Kokkos_Core_fwd.hpp(246): warning #2651: attribute does not apply to any entity
  using ActiveExecutionMemorySpace KOKKOS_DEPRECATED = Kokkos::HostSpace;
                                   ^

In file included from /work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/Kokkos_HostSpace.hpp(54),
                 from /work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/Kokkos_OpenMP.hpp(55),
                 from /work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/decl/Kokkos_Declare_OPENMP.hpp(49),
                 from /work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/KokkosCore_Config_DeclareBackend.hpp(47),
                 from /work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/Kokkos_Core.hpp(53),
                 from smooth.cxx(16):
/work2/00434/eijkhout/kokkos/installation-git-clx-intel/include/Kokkos_Concepts.hpp(371): warning #2651: attribute does not apply to any entity
    using host_memory_space KOKKOS_DEPRECATED = do_not_use_host_memory_space;
                            ^
```

**Comment by dalg24** [comment]
What Kokkos version?  What compiler?

**Comment by ndellingwood** [comment]
@dalg24 the intel/19 builds have `-DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF`. I'll update the jobs to get that turned on, sorry for the miss

**Comment by VictorEijkhout** [comment]
Intel 19 and a kokkos clone from last week. Give me a heads-up when I need to pull again? Making me a test branch is fine too.

**Comment by dalg24** [comment]
As a workaround you can configure with `-DCMAKE_CXX_COMPILER="-wd2651"` or build Kokkos with `-DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF`

**Comment by ndellingwood** [comment]
I confirmed @dalg24 's PR #5102 resolved the deprecation warnings with intel/19.0.5, tested with configuration
```
cmake -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_FLAGS="-Wall -Werror" -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_SNB=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=ON $KOKKOS_PATH
```

**Comment by dalg24** [comment]
> I confirmed @dalg24 's PR #5102 resolved the deprecation warnings when compiling with intel/19.0.5, tested with configuration
> 
> ```
> cmake -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_FLAGS="-Wall -Werror" -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_SNB=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=ON $KOKKOS_PATH
> ```

I suspect that for 19.0.5, `KOKKOS_COMPILER_INTEL` is `1900` so you wouldn't get the warning with the current `develop`

**Comment by ndellingwood** [comment]
> I suspect that for 19.0.5, `KOKKOS_COMPILER_INTEL` is `1900` so you wouldn't get the warning with the current `develop`

@dalg24 you're right, I just tested develop (SHA 69ceb6cc3eff9f189b3ba322c86a6ca291506633) with the same config above and it compiled without issue

**Comment by dalg24** [comment]
> What is the exact version number? **edit: compiler version**

@VictorEijkhout please confirm what compiler version you were using

**Comment by VictorEijkhout** [comment]
[staff cxx:245] icpc -v
icpc version 19.1.1.217 (gcc version 8.3.0 compatibility)

**Comment by dalg24** [comment]
This is fixed in `develop` and will be part of release 3.7

**Comment by dalg24** [comment]
For workarounds see https://github.com/kokkos/kokkos/issues/5101#issuecomment-1151442289
