### ISSUE TITLE
Should we make an `iterator` component at same level as `core`, `algorithms`, `containers`, etc?

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#5114]
We currently have a random access iterator and `begin/end` functions all living inside the `kokkos/algorithms`. 
Would it make sense to extract them out and separate them into a `kokkos/iterators`?
I am aware that we *currently* only have one kind of iterator and maybe we will only have that. But it would be nice (IMO) to clearly separate iterators from algorithms.

**Comment by dalg24** [comment]
Separating them? sure
Putting them on the same level as Core or Algorithm? no

**Comment by fnrizzi** [comment]
I was thinking of an "iterator" library

**Comment by fnrizzi** [comment]
Or maybe let me revise and say that maybe iterator should go into core ?

**Comment by dalg24** [comment]
I'd be open to moving it to Core

**Comment by ajpowelsnl** [comment]
SF F N A SA

Iterator in `Core` vs. in `Algorithms` ?

**Comment by ajpowelsnl** [comment]
Decision:  delay action in favor of research project on multidimensional iterators (in the context of MDSpan)

**Comment by mhoemmen** [comment]
+1 on delaying action -- moving an iterators library to core would amount to a long-term support contract, for a feature still very much in the research stage.

**Comment by fnrizzi** [comment]
closing this for now since it is delayed
