### ISSUE TITLE
What is a cuda architecture?

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#5124]
```
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /opt/apps/cuda/11.3/bin/nvcc
-- The CUDA compiler identification is NVIDIA 11.3.109
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/apps/cuda/11.3/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Error at cmake/kokkos_arch.cmake:650 (MESSAGE):
  CUDA enabled but no NVIDIA GPU architecture currently enabled and
  auto-detection failed.  Please give one -DKokkos_ARCH_{..}=ON' to enable an
  NVIDIA GPU architecture.
```

I'm assuming you want something like "70"?

**Comment by crtrott** [comment]
Hi

yeah its -DKokkos_ARCH_VOLTA70=ON. Generally you may wanna join our slack channel at https://kokkosteam.slack.com, questions like this are really well suited for the slack. 

Cheers

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/wiki/Compiling#architecture-keywords
`-DKokkos_ARCH_VOLTA70=ON`

**Comment by lucbv** [comment]
If you want to see all the arch available you can try this: cmake -LAH | grep "Kokkos_ARCH".
The architecture flags are actually names like Pascal, Volta or Ampere.

**Comment by VictorEijkhout** [comment]
On , 2022Jun17, at 11:50, Christian Trott ***@***.******@***.***>> wrote:

Generally you may wanna join our slack channel at https://kokkosteam.slack.com<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkokkosteam.slack.com%2F&data=05%7C01%7C%7C9e356f33d822489c899808da50817388%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637910814164093108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b%2BzgBETqlj%2Br1J%2Fkmxq4NLHatKuL8N%2Fujah9VA8Mf6U%3D&reserved=0>,

Sounds like a good idea except that you have only whitelisted @utexas edu, not @tacc.utexas.edu. Can you accommodate me there?

Victor.

**Comment by dalg24** [comment]
Done
