### ISSUE TITLE
IBM XL 13.1.3 Link error

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#513]
Looks like a compiler bug:

```
crtrott@white24:~/KokkosBuild/OpenMP/XL/13.1.3/core/unit_test$ xlc++ -L/home/crtrott/KokkosBuild/OpenMP/XL/13.1.3/core/unit_test -mcpu=power8 -mtune=power8 -qsmp=omp -lpthread  TestOpenMP_Other.o TestOpenMP_Reductions.o TestOpenMP_Atomics.o TestOpenMP_Team.o TestOpenMP_SubView_a.o TestOpenMP_SubView_b.o TestOpenMP_SubView_c01.o TestOpenMP_SubView_c02.o TestOpenMP_SubView_c03.o TestOpenMP_SubView_c04.o  TestOpenMP_SubView_c05.o  TestOpenMP_SubView_c06.o TestOpenMP_SubView_c07.o  TestOpenMP_SubView_c08.o  TestOpenMP_SubView_c09.o TestOpenMP_SubView_c10.o TestOpenMP_SubView_c11.o TestOpenMP_SubView_c12.o TestOpenMP_ViewAPI_a.o TestOpenMP_ViewAPI_b.o UnitTestMain.o gtest-all.o -lkokkos -ldl  -o KokkosCore_UnitTest_OpenMP
TestOpenMP_SubView_c03.o:(.data+0x250): multiple definition of `_ZNK6Kokkos4Impl11ParallelForINS_12Experimental4Impl16ViewValueFunctorINS_6OpenMPEiLb1EEENS_11RangePolicyIJS5_EEES5_E16execute_scheduleINS_6StaticEEENSt9enable_ifIXsr3std7is_sameIT_SB_EE5valueEvE4typeEv$$OL$$1RVLA88'
TestOpenMP_SubView_c01.o:(.data+0x240): first defined here
TestOpenMP_SubView_c06.o:(.data+0x250): multiple definition of `_ZNK6Kokkos4Impl11ParallelForINS_12Experimental4Impl16ViewValueFunctorINS_6OpenMPEiLb1EEENS_11RangePolicyIJS5_EEES5_E16execute_scheduleINS_6StaticEEENSt9enable_ifIXsr3std7is_sameIT_SB_EE5valueEvE4typeEv$$OL$$1RVL8113'
TestOpenMP_SubView_c04.o:(.data+0x240): first defined here
TestOpenMP_SubView_c09.o:(.data+0x260): multiple definition of `_ZNK6Kokkos4Impl11ParallelForINS_12Experimental4Impl16ViewValueFunctorINS_6OpenMPEiLb1EEENS_11RangePolicyIJS5_EEES5_E16execute_scheduleINS_6StaticEEENSt9enable_ifIXsr3std7is_sameIT_SB_EE5valueEvE4typeEv$$OL$$1RVL9554'
TestOpenMP_SubView_c07.o:(.data+0x250): first defined here
TestOpenMP_SubView_c12.o:(.data+0x260): multiple definition of `_ZNK6Kokkos4Impl11ParallelForINS_12Experimental4Impl16ViewValueFunctorINS_6OpenMPEiLb1EEENS_11RangePolicyIJS5_EEES5_E16execute_scheduleINS_6StaticEEENSt9enable_ifIXsr3std7is_sameIT_SB_EE5valueEvE4typeEv$$OL$$1RVL9721'
TestOpenMP_SubView_c10.o:(.data+0x250): first defined here

```

**Comment by nmhamster** [comment]
We are also seeing this with IBM XL 13.1.4 on the new system image. Still investigating.

**Comment by jjellio** [comment]
These are actually the same "class" of duplicate definitions I reported in Trilinos/trilinos#723. I saw a few more.

A possible fix may be how ETI definitions are declared (or definitions in general).

Tpetra's ETI are defined as
namespace Tpetra {
template class Foo<....>;
}

Looking at the assembly generated by XL, the symbols needed by the class are added into the namespace Tpetra (e.g., lots of Kokkos stuff).

Instead, writing the ETI def as
template class Tpetra::Foo<....>;

Seemed to work, in a small test (built two files that failed and manually linked them into the same lib file). I didn't get the ASM when I did that. My build has progressed for enough to say if that changes actually allows future things to link correctly. So this could be nonsense. 

I am still fiddling with this, it just takes a while.

**Comment by crtrott** [comment]
In Kokkos there is no ETI whatsoever, so there is nothing we can really do about it.

**Comment by crtrott** [comment]
Bascially what I wanted to say is that the multiple definitions are for things which are implicilty instantiated and should be marked as weak symbols and thus not prevent linking.

**Comment by jjellio** [comment]
The issue isn't ETI though, it is how XL labels symbols. In the former case, symbols are mangled such that they belong to "Tpetra", when I did it the other way, the symbol is given a different name so you miss the conflict.

**Comment by crtrott** [comment]
Sure but they shouldn't neceearily conflict in the first place since they are for implicitly instantiated template classes. Thus the symbols should be marked as weak symbols and not conflict at link time.

**Comment by crtrott** [comment]
Si did you forward to IBM?

**Comment by nmhamster** [comment]
@crtrott @jjellio this is under discussion with IBM. We have other areas we are working on as well, some of which are also similar compiler issues.

**Comment by crtrott** [comment]
I am going to put a workaround in for our testing. That won't fix stuff in Trilinos or whether though.

**Comment by crtrott** [comment]
Looks like this is fixed in 14.x beta. But it will be a while before the 14 line hits the public. 13.1.5 still has the issue.
