### ISSUE TITLE
Compiling a cuda code

### ISSUE THREAD

**Issue by VictorEijkhout** [kokkos/kokkos#5139]
Let me know what I'm missing.

```
Compiling: icpc -g -I/work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include -I/opt/apps/cuda/11.3/include  -std=c++17 -qopenmp  -O2 -g      -c enabled.cxx
In file included from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/KokkosCore_Config_SetupBackend.hpp(47),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/Kokkos_Macros.hpp(110),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/Kokkos_Core_fwd.hpp(52),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/Kokkos_Core.hpp(51),
                 from enabled.cxx(16):
/work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/setup/Kokkos_Setup_Cuda.hpp(54): error: #error directive: "KOKKOS_ENABLE_CUDA defined but the compiler is not defining the __CUDACC__ macro as expected"
  #error \
   ^

In file included from /opt/apps/cuda/11.3/include/builtin_types.h(56),
                 from /opt/apps/cuda/11.3/include/cuda_runtime.h(91),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/setup/Kokkos_Setup_Cuda.hpp(68),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/KokkosCore_Config_SetupBackend.hpp(47),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/Kokkos_Macros.hpp(110),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/Kokkos_Core_fwd.hpp(52),
                 from /work2/00434/eijkhout/kokkos/installation-git-frontera-intel-cuda/include/Kokkos_Core.hpp(51),
                 from enabled.cxx(16):
/opt/apps/cuda/11.3/include/device_types.h(66): warning #1292: unknown attribute "device_builtin"  enum __device_builtin__ cudaRoundMode
```

(83k more lines of errors and warnings omitted)

**Comment by dalg24** [comment]
Presumably user code misconfigured, using Intel (Classic) C++ compiler directly instead of `nvcc_wrapper` to compile while Kokkos that was found had CUDA enabled and was built with a different compiler (I can only guess `nvcc_wrapper`)

**Comment by dalg24** [comment]
Please use the template when you open such an issue, or (preferred) [join us on Slack](https://kokkosteam.slack.com) and ask your questions on the \#general channel.

**Comment by VictorEijkhout** [comment]
On , 2022Jun23, at 15:27, Damien L-G ***@***.******@***.***>> wrote:

 join us on Slack<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkokkosteam.slack.com%2F&data=05%7C01%7C%7C74cb2f0a2b184771c12908da5556c1cb%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637916128349958053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qjtZE69z6FlG0DCI0ZyITLXUri6QA8%2BPXzQqM1XB7Vc%3D&reserved=0>

I can’t. My email is not of a form that you approve of.

Victor.

**Comment by dalg24** [comment]
Send an email to crtrott(at)sandia.gov or lebrungrandt(at)ornl.gov from the email address you want to use and we will send you an invitation.
