### ISSUE TITLE
Instantiation of Kokkos::vector of Kokkos::Array fails to compile. 

### ISSUE THREAD

**Issue by overfelt** [kokkos/kokkos#5145]
This might be a feature and not a bug if Kokkos::vector is designed to work with scalar types only.

When compiling 
`   Kokkos::vector<Kokkos::Array<double,3>> vector_of_kokkos_array(1);`
I get the error
`  Kokkos_Array.hpp:322:34: note: 'Array' has been explicitly marked deleted here`

This is with Apple clang version 13.1.6, host only, Kokkos master branch, d19aab99.  

With std::array it does compile:
`  Kokkos::vector<std::array<double,3>> vector_of_std_array(1);`
as does views of arrays:
`  Kokkos::View<Kokkos::Array<double,3>*> view_of_kokkos_array("view_of_kokkos_array",1);`

For now this is host only code so std::array is fine, but might want to move this to device in the future.

**Comment by crtrott** [comment]
We may give this a shot again after moving to mdspan underneath View because there is a whole can of worms underneath this which is hard to fix.

**Comment by masterleinad** [comment]
`Kokkos::vector` is deprecated.
