### ISSUE TITLE
value_type deduction for parallel_reduce doesn't work with templated functors

### ISSUE THREAD

**Issue by ho37** [kokkos/kokkos#5156]
**Describe the bug**

If you don't specify the `value_type` in a functor, sometimes `parallel_reduce` will fail to compile.

**Please also include the following items to support reproducing the bug**
1. compilers: gcc 11.3.0, with Cuda 11.7
2. Kokkos release or commit used: d19aab998
3. platform and backend: lassen HPC at LLNL (powerpc 9, NVidia V100). Built Kokkos with Cuda+Threads+Serial backends.
4. cmake configure command: N/A
5. output from cmake command: N/A
6. code needed to reproduce the bug:
Minimum example code:

```
#include <Kokkos_Core.hpp>

template <class V>
struct MyFunctor
{
  //using value_type = typename V::value_type;
  V view;

  template<class I0>
  KOKKOS_FUNCTION void operator()(I0 i0 , typename V::value_type &res) const
  {
    res += view(i0);
  }
};

int main(int argc, char **argv) {
  Kokkos::initialize(argc, argv);
  {
    size_t Nx = 4;
    Kokkos::View<double *> myview("myview", Nx);

    MyFunctor<decltype(myview)> func = {myview};
    double res = 0;
    Kokkos::parallel_reduce("sum", myview.extent(0), func, res);
  }
  Kokkos::finalize();
}
```

7. please also attach the `KokkosCore_config.h` header file (generated during the build);

[KokkosCore_config.zip](https://github.com/kokkos/kokkos/files/9003743/KokkosCore_config.zip)

**Any additional info**

Changes which happen to compile successfully:
- uncommenting the `using value_type = typename V::value_type;` statement in `MyFunctor`
- Removing the `operator()` template parameter `I0` and forcing it to always be `int` (or any other integral type).

Changing the `operator()` signature to the following doesn't help:
```
template<class I0>
KOKKOS_FUNCTION std::enable_if_t<std::is_integral<I0>::value> operator()(I0 i0, typename V::value_type &res) const;
```

**Comment by masterleinad** [comment]
Fixed in #5976.
