### ISSUE TITLE
Better name for the InitArguments replacement

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos#5162]
P/R #5135 is deprecating `InitArguments` with a better replacement.  We need a different name for the new class.

The P/R currently uses `InitializationArguments`, the downside being the name is too close to `InitArguments`, so we need a better name to go with the better replacement.

The initial brainstorm has the name including one of the following in it:

```
Arguments
Settings
Configuration
RunTime

```
Ideally, the name should reflect its use instead of the mechanism (`InitArguments` tells what it does; a better name would tell what it is for).

Please brainstorm names, with a justification (a sentence or two is fine) as to why it is a good name.

**Comment by JBludau** [comment]
For the discussion we could compose the word from two categories and do 1st+2nd
1st
- Initialization
- Runtime
- Kokkos
- Commandline

2nd
- Arguments
- Configuration
- Parameters
- Preferences
- Settings
- Values

**Comment by JBludau** [comment]
I personally like RuntimeConfiguration as it is a very technical description and different enough from the current state to not confuse the users. But I see that users could think that this gives them the arguments they supplied in the commandline (But this holds for all combinations)

**Comment by ajpowelsnl** [comment]
It seems we're doing three things in initializaton: set, check and get.  Could you have prefixes on the order of, `set_*` , `check_*`, `get_*` for each initialization item?  Would it make sense to have three separate classes for setters, checkers and getters, to use for initialization, towards the goal of greater modularization?

**Comment by dalg24** [comment]
> given that we can reinitialize Kokkos.

I suppose you meant to write "cannot" ;)

**Comment by crtrott** [comment]
I don't like commandline at all, since its specific purpose is to replace command line arguments passed in via argc argv.

**Comment by crtrott** [comment]
It also doesn't need `Kokkos` in the name since its gonna be `Kokkos::Something` anyway.

**Comment by crtrott** [comment]
I like InitializationSettings and RuntimeSettings

**Comment by nliber** [comment]
@dalg24 how do you want us to bring this discussion to a conclusion?

So far, it looks like `InitializationSettings` is winning (in terms of number of people supporting it).

**Comment by dalg24** [comment]
`InitializationSettings` it is then
