### ISSUE TITLE
Move min and max routines to Kokkos namespace

### ISSUE THREAD

**Issue by ajpowelsnl** [kokkos/kokkos#5168]
In reviewing changes requested by the RAJAPerf Suite project, I discovered that Kokkos min and max routines were still in the `Experimental` namespace.   The min and max routines are Kokkos implementations of the corresponding standard algorithms. 

On the RAJAPerf Suite side, `REDUCE3_INT-Kokkos.cpp` contains the min and max functions in `Experimental`:

```
...
      m_vmin =
          Kokkos::Experimental::min(m_vmin, static_cast<Int_type>(min_value));
      m_vmax =
          Kokkos::Experimental::max(m_vmax, static_cast<Int_type>(max_value));
...
```

I will propose updates for the following files in a PR today:

- `core/src/Kokkos_MinMaxClamp.hpp`
- `core/src/HIP/Kokkos_HIP_Parallel_Team.hpp`
-  `core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp`
- `core/unit_test/TestMinMaxClamp.hpp`
- `algorithms/src/std_algorithms/impl/Kokkos_LexicographicalCompare.hpp`

**Comment by dalg24** [comment]
Not an oversight.  They are not classified as math functions but as algorithms in the standard library.
That said I don't really object to their promotion into the main Kokkos:: namespace.

**Comment by ajpowelsnl** [comment]
> Not an oversight. They are not classified as math functions but as algorithms in the standard library. That said I don't really object to their promotion into the main Kokkos:: namespace.



> Not an oversight. They are not classified as math functions but as algorithms in the standard library. That said I don't really object to their promotion into the main Kokkos:: namespace.



> Not an oversight. They are not classified as math functions but as algorithms in the standard library. That said I don't really object to their promotion into the main Kokkos:: namespace.

Just out of curiosity, why are not ma
