### ISSUE TITLE
Deprecate join(volatile)

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#5194]
Following #4077, client code declaring a reduction `join()` operation taking only `volatile` parameters is both a potential performance pitfall and an anachronism of an API requirement we carried for an obscure reason.

Should we deprecate the older method signature and plan to remove support for it, to push downstream code to fix the potential performance bug and clean up the debris?

**Comment by masterleinad** [comment]
I'm in favor.

**Comment by ajpowelsnl** [comment]
I'll put it on our list for Wednesday.

**Comment by PhilMiller** [comment]
Per meeting, deprecation notice will go ahead.

There's less certainty about how and when we're going to stop compiling code that would go through the `volatile`-qualified call path

**Comment by PhilMiller** [comment]
As noted in #5215, we do have a way of failing compilation for the case where we'd select a method taking `volatile`-qualified parameters, but doing so basically requires maintaining support for that code path for as long as we want to block it.

The way forward on this may be to leave the deprecation in place through the 4.x line, with a `static_assert(dependent_false<F>)` if deprecated code is disabled, and plan to remove it for 5.0

**Comment by ajpowelsnl** [comment]
> As noted in #5215, we do have a way of failing compilation for the case where we'd select a method taking `volatile`-qualified parameters, but doing so basically requires maintaining support for that code path for as long as we want to block it.
> 
> The way forward on this may be to leave the deprecation in place through the 4.x line, with a `static_assert(dependent_false<F>)` if deprecated code is disabled, and plan to remove it for 5.0

@PhilMiller - would you like further discussion of this topic in today's meeting?

**Comment by PhilMiller** [comment]
Sure, but it's probably the least urgent thing that'll be on the agenda. There's no real cost delay.

**Comment by PhilMiller** [comment]
Per meeting today, I will add the `static_assert(dependent_false<F>)` under the deprecation `#ifdef`

**Comment by ndellingwood** [comment]
@PhilMiller I'm marking this InDevelop via PR #5409

**Comment by PhilMiller** [comment]
4.0 released with this.
