### ISSUE TITLE
Trilinos nightly build failures, Tpetra undefined references to create_mirror_view_and_copy during linking, Serial builds, intel compilers

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5196]
**Describe the bug**
Following merges from 7/8/2022 Trilinos builds began failing at link stage in Tpetra with undefined references:
```
21:42:52 [ 55%] Building CXX object packages/tpetra/core/test/Behavior/CMakeFiles/TpetraCore_Behavior_On.dir/Behavior_On.cpp.o
21:42:52 [ 55%] Building CXX object packages/tpetra/core/test/Behavior/CMakeFiles/TpetraCore_Behavior_Default.dir/__/__/__/__/teuchos/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
21:42:52 [ 55%] Building CXX object packages/tpetra/core/test/Behavior/CMakeFiles/TpetraCore_Behavior_On.dir/__/__/__/__/teuchos/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
21:42:52 ../../src/libtpetra.so.13.5: undefined reference to `_ZN6Kokkos27create_mirror_view_and_copyINS_9HostSpaceEPPdJNS_10LayoutLeftENS_6DeviceINS_6SerialES1_EEEvEEDaRKT_RKNS_4ViewIT0_JDpT1_EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNSt9enable_ifIXsr3std7is_voidINS_10ViewTraitsISC_JSE_EE10specializeEEE5valueEvE4typeE'
21:42:52 ../../src/libtpetra.so.13.5: undefined reference to `_ZN6Kokkos27create_mirror_view_and_copyINS_9HostSpaceEPPiJNS_10LayoutLeftENS_6DeviceINS_6SerialES1_EEEvEEDaRKT_RKNS_4ViewIT0_JDpT1_EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNSt9enable_ifIXsr3std7is_voidINS_10ViewTraitsISC_JSE_EE10specializeEEE5valueEvE4typeE'
21:42:52 ../../src/libtpetra.so.13.5: undefined reference to `_ZN6Kokkos27create_mirror_view_and_copyINS_9HostSpaceEPiJS1_NS_12MemoryTraitsILj1EEEEvEEDaRKT_RKNS_4ViewIT0_JDpT1_EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNSt9enable_ifIXsr3std7is_voidINS_10ViewTraitsIS9_JSB_EE10specializeEEE5valueEvE4typeE'
21:42:52 ../../src/libtpetra.so.13.5: undefined reference to `_ZN6Kokkos27create_mirror_view_and_copyINS_9HostSpaceEPPNS_7complexIdEEJNS_10LayoutLeftENS_6DeviceINS_6SerialES1_EEEvEEDaRKT_RKNS_4ViewIT0_JDpT1_EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNSt9enable_ifIXsr3std7is_voidINS_10ViewTraitsISE_JSG_EE10specializeEEE5valueEvE4typeE'
21:42:52 ../../src/libtpetra.so.13.5: undefined reference to `_ZN6Kokkos27create_mirror_view_and_copyINS_9HostSpaceEPPxJNS_10LayoutLeftENS_6DeviceINS_6SerialES1_EEEvEEDaRKT_RKNS_4ViewIT0_JDpT1_EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNSt9enable_ifIXsr3std7is_voidINS_10ViewTraitsISC_JSE_EE10specializeEEE5valueEvE4typeE'
21:42:52 make[2]: *** [packages/tpetra/core/test/Behavior/CMakeFiles/TpetraCore_Behavior_Named.dir/build.make:140: packages/tpetra/core/test/Behavior/TpetraCore_Behavior_Named.exe] 
```

<details>
 <summary><b>Kokkos commits:</b></summary>

Git (git https://github.com/kokkos/kokkos.git)

    Provide ViewCtorProp overload for create_mirror_view_and_copy ([commit: ec9da94](https://github.com/kokkos/kokkos/commit/ec9da947b671a1a3990eb8ae4de6363417ca4985)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Add a test ([commit: 939b781](https://github.com/kokkos/kokkos/commit/939b7815d763359fe94f4c67d69e3948236bb791)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Fix warning ([commit: 6b7468b](https://github.com/kokkos/kokkos/commit/6b7468b35cc6a8785b930b799b700b180d146c1d)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Shift dummy arguments ([commit: 7f04137](https://github.com/kokkos/kokkos/commit/7f0413700faed6c0462e2a8eac9d31853e05164c)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    DynRankView implementation ([commit: 447f8ff](https://github.com/kokkos/kokkos/commit/447f8ff7556e59617e36af15ca49b51027575a48)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Small fixes ([commit: 84dc902](https://github.com/kokkos/kokkos/commit/84dc90203f43968d96b2216a529c1079975181ff)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Implement OffsetView ([commit: 521767a](https://github.com/kokkos/kokkos/commit/521767aa8f1e65f2954224ecaac433bef418f467)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Minor fix ([commit: 2cda2c1](https://github.com/kokkos/kokkos/commit/2cda2c1004bc5371ba294bb3038ae65b79259c15)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Implement DynamicView ([commit: 211ece8](https://github.com/kokkos/kokkos/commit/211ece819ac97c99341160aafb18e26fa196fc0d)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Fix deep_copy_to ([commit: 55e763e](https://github.com/kokkos/kokkos/commit/55e763e7be794a85ac40177f8ec3fbd851212317)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Use TEST_EXECSPACE in containers/TestWithoutInitializing.hpp ([commit: 6ce5a94](https://github.com/kokkos/kokkos/commit/6ce5a947d9dd1aa2fa762ae16620df405c231a4a)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Disable test for UVM; they fence to much ([commit: 527b92f](https://github.com/kokkos/kokkos/commit/527b92f448c050b017b6dd19b7da6266140f727c)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Restore containers/unit_tests/CMakeLists.txt ([commit: 0c970ba](https://github.com/kokkos/kokkos/commit/0c970bacdc587158e36e8fac9087481984f23d87)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Disable kokkosp.create_mirror_view_and_copy for OpenMPTarget ([commit: cb93153](https://github.com/kokkos/kokkos/commit/cb9315369e27e6e3cf9e12b3e3fedcada2a1a498)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Indentation ([commit: ed2fe37](https://github.com/kokkos/kokkos/commit/ed2fe3796ef478b32108ae12558de85f902dc7cb)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Disable kokkosp.create_mirror_view_and_copy for CUDA UVM ([commit: 375a21f](https://github.com/kokkos/kokkos/commit/375a21fa23f6f093bf292796448a18afdb2147b4)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Move min, max, clamp, minmax routines out of Experimental namespace ([commit: 233e4ee](https://github.com/kokkos/kokkos/commit/233e4ee43c7ff5c7ec4a86275ff1621664057985)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Fix clang formatting ([commit: 0bc4ddf](https://github.com/kokkos/kokkos/commit/0bc4ddf0c169c8eb14a3931b1e2dd59684c9efe7)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
    Add reimport of min/max etc to Experimental ([commit: c9e065a](https://github.com/kokkos/kokkos/commit/c9e065a4c91385a31f0a42a55530ea54582e7ee4)) ([detail](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel193199_Serial_Cplx/143/changes#detail))
</details>

**Please also include the following items to support reproducing the bug**
1. compilers intel/18, intel/19
2. Reproducer script (intel/19, Blake testbed)
```bash
# Clone repos
git clone -b kokkos-promotion git@github.com:trilinos/Trilinos.git
git clone -b develop git@github.com:kokkos/kokkos.git

# Create symbolic link to kokkos within Trilinos source directory for source override
cd Trilinos
ln -s ../kokkos kokkos
ln -s ../kokkos-kernels kokkos-kernels
cd -

# Create build directory
mkdir -p Build
cd Build

# Load and prep env
module load devpack/20190329/openmpi/4.0.1/intel/19.3.199
module swap cmake/3.12.3 cmake/3.19.3

export ARCH_CXX_FLAG="-xCORE-AVX512 -mkl"
export ARCH_C_FLAG="-xCORE-AVX512 -mkl"
export BLAS_LIBRARIES="-mkl;${MKLROOT}/lib/intel64/libmkl_intel_lp64.a;${MKLROOT}/lib/intel64/libmkl_intel_thread.a;${MKLROOT}/lib/intel64/libmkl_core.a"
export LAPACK_LIBRARIES=${BLAS_LIBRARIES}


# Top Level Configuration Options
TESTS=ON
EXAMPLES=ON
SHARED=ON

CUDA=OFF
OPENMP=OFF
PTHREAD=OFF
SERIAL=ON
COMPLEX=ON
ENABLE_SHYLU="ON"

# Configure
cmake \
-GNinja \
-DCMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
-DCMAKE_CXX_STANDARD="14" \
-D Trilinos_ENABLE_COMPLEX_DOUBLE=${COMPLEX} \
\
-D Kokkos_ARCH_SKX=ON \
-D CMAKE_CXX_FLAGS="-g" \
-D CMAKE_C_FLAGS="${ARCH_C_FLAG} -g" \
-D CMAKE_Fortran_FLAGS="${ARCH_C_FLAG} -g" \
-D CMAKE_EXE_LINKER_FLAGS="${ARCH_C_FLAG}" \
-D CMAKE_Fortran_COMPILER="mpif77" \
-D HAVE_CXX_PRAGMA_WEAK:BOOL=OFF \
-D CMAKE_AR:FILEPATH=/usr/bin/ar \
-D CMAKE_STRIP:FILEPATH=/usr/bin/strip \
-D CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_DEBUG:BOOL=OFF \
\
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D CMAKE_SKIP_RULE_DEPENDENCY=ON \
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D BUILD_SHARED_LIBS:BOOL=${SHARED} \
-D DART_TESTING_TIMEOUT:STRING=500 \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
\
-D Trilinos_ENABLE_OpenMP=${OPENMP} \
-D TPL_ENABLE_CUDA=${CUDA} \
-D TPL_ENABLE_MPI=ON \
  -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-bind-to;socket;-map-by;socket" \
-D TPL_ENABLE_BinUtils=OFF \
-D TPL_ENABLE_SuperLU=OFF \
  -D TPL_SuperLU_LIBRARIES:STRING="${SUPERLU_ROOT}/lib/libsuperlu.a" \
  -D TPL_SuperLU_INCLUDE_DIRS:STRING="${SUPERLU_ROOT}/include" \
-D TPL_ENABLE_BLAS=ON \
  -D TPL_BLAS_LIBRARIES:PATH="${BLAS_LIBRARIES}" \
-D TPL_ENABLE_LAPACK=ON \
  -D TPL_LAPACK_LIBRARIES:PATH="${LAPACK_LIBRARIES}" \
-D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_Netcdf=ON \
  -D Netcdf_INCLUDE_DIRS:PATH="${NETCDF_ROOT}/include" \
  -D Netcdf_LIBRARY_DIRS:PATH="${NETCDF_ROOT}/lib" \
  -D TPL_Netcdf_LIBRARIES:PATH="${NETCDF_ROOT}/lib/libnetcdf.a;${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;${ZLIB_ROOT}/lib/libz.a;${PNETCDF_ROOT}/lib/libpnetcdf.a" \
  -D TPL_Netcdf_PARALLEL:BOOL=ON \
-D TPL_ENABLE_HDF5=ON \
  -D HDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
  -D TPL_HDF5_LIBRARIES:PATH="${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;${ZLIB_ROOT}/lib/libz.a" \
-D TPL_ENABLE_Zlib=ON \
  -D Zlib_INCLUDE_DIRS:PATH="${ZLIB_ROOT}/include" \
  -D TPL_Zlib_LIBRARIES:PATH="${ZLIB_ROOT}/lib/libz.a" \
-D TPL_ENABLE_DLlib=ON \
\
-D Trilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=${SERIAL} \
  -D Kokkos_ENABLE_PTHREAD=${PTHREAD} \
  -D Kokkos_ENABLE_OPENMP=${OPENMP} \
  -D Kokkos_ENABLE_CUDA=${CUDA} \
  -D Kokkos_ENABLE_CUDA_LAMBDA=${CUDA} \
  -D Kokkos_ENABLE_TESTS:BOOL=${TESTS} \
-D Trilinos_ENABLE_KokkosKernels=ON \
  -D KokkosKernels_ENABLE_TESTS:BOOL=${TESTS} \
-D Trilinos_ENABLE_Sacado=ON \
  -D Sacado_ENABLE_UNINIT:BOOL=ON \
  -D Sacado_ENABLE_TESTS:BOOL=${TESTS} \
  -D Sacado_ENABLE_EXAMPLES:BOOL=${EXAMPLES} \
-D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_INST_SERIAL:BOOL=${SERIAL} \
  -D Tpetra_INST_OPENMP:BOOL=${OPENMP} \
  -D Tpetra_INST_PTHREAD:BOOL=${PTHREAD} \
  -D Tpetra_INST_CUDA:BOOL=${CUDA} \
  -D Tpetra_ENABLE_TESTS:BOOL=${TESTS} \
  -D Tpetra_ENABLE_EXAMPLES:BOOL=${EXAMPLES} \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

Most of the TPL stuff is boiler plate, blas and lapack should be the only tpls needed for the build.
The devpack referenced loads the following modules:

```
-bash-4.2$ module list
Currently Loaded Modulefiles:
  1) autoconf/2.69.0                                  16) java/oracle/1.8.0
  2) automake/1.15.0                                  17) openmpi/4.0.1/intel/19.3.199
  3) libtool/2.4.6                                    18) pnetcdf/1.9.0/openmpi/4.0.1/intel/19.3.199
  4) cmake/3.19.3                                     19) zlib/1.2.11
  5) make/4.2.1                                       20) hdf5/1.8.21/openmpi/4.0.1/intel/19.3.199
  6) m4/1.4.18                                        21) netcdf/4.6.1/openmpi/4.0.1/intel/19.3.199
  7) bison/3.0.4                                      22) metis/5.0.1/intel/19.3.199
  8) flex/2.6.4                                       23) parmetis/4.0.3/openmpi/4.0.1/intel/19.3.199
  9) git/2.9.4                                        24) cgns/20190329/openmpi/4.0.1/intel/19.3.199
 10) devtools/20170725                                25) superlu/4.3.0/intel/19.3.199
 11) binutils/2.30.0                                  26) superlu-dist/4.3.0/openmpi/4.0.1/intel/19.3.199
 12) gcc/7.2.0                                        27) boost/1.65.1/intel/19.3.199
 13) intel/compilers/19.3.199                         28) yamlcpp/0.5.3
 14) numa/2.0.11                                      29) devpack/20190329/openmpi/4.0.1/intel/19.3.199
```

**Comment by ajpowelsnl** [comment]
@masterleinad - would you please have a look?

**Comment by masterleinad** [comment]
Does this only fail with `Intel` compilers?

**Comment by ndellingwood** [comment]
@masterleinad it only failed with the intel compilers, though those are the only compilers I've tested with Serial-only enabled backend in case that is relevant. I can launch a build with gcc and Serial-only backend if that would be a helpful diagnostic

**Comment by ajpowelsnl** [comment]
> @masterleinad it only failed with the intel compilers, though those are the only compilers I've tested with Serial-only enabled backend in case that is relevant. I can launch a build with gcc and Serial-only backend if that would be a helpful diagnostic

@masterleinad and @crtrott have a fix in the PR queue.

**Comment by ndellingwood** [comment]
@dalg24 I saw you added the InDevelop label, what PR was merged to address this issue?

**Comment by masterleinad** [comment]
> @dalg24 I saw you added the InDevelop label, what PR was merged to address this issue?

https://github.com/kokkos/kokkos/pull/5207
