### ISSUE TITLE
MDRange execution policy

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#52]
Need a range execution policy for Cartesian product index space with layout parameter to specify locality in mapping dimensions to execution space.

**Comment by crtrott** [comment]
Nathan is working on this.

**Comment by ndellingwood** [comment]
Ensure has no negative impact on 1D range policy; then review for experimental status

**Comment by hcedwar** [comment]
Need to be able to set each tile dimension individually.  Each dimensions is either the whole extent or a power of two.

**Comment by hcedwar** [comment]
Introduce into Experimental namespace for Spring 2016.  Follow up with evaluation and hardening for Summer 2016.

**Comment by hcedwar** [comment]
Introducing as separate Kokkos::Experimental::MultiDimRangePolicy
To be merged into Kokkos::RangePolicy once performance issues have been resolved.
API style: Policy( {0,N0} , {0,N2} , Tiling(J0,J1) ); Tiling(...) is optional.

**Comment by hcedwar** [comment]
Investigating loop collapse as well as tiling.

**Comment by hcedwar** [comment]
This feature being integrated in Experimental and does not have any interference with the current RangePolicy.
Only have parallel_for working at the moment.
Integration with RangePolicy requires revisiting of RangePolicy options mechanisms.

**Comment by crtrott** [comment]
We pulled that just out of develop again right?

**Comment by ndellingwood** [comment]
No it is in develop, I pulled the op() stuff I added to DynRankView

**Comment by ndellingwood** [comment]
I think I misunderstood in first reply - we pulled out the changes that touched other parts of Kokkos and instead isolated the MDRangePolicy in its own experimental file with experimental namespace. Added the Experimental label instead to more adequately reflect this.

**Comment by crtrott** [comment]
Ah ok

**Comment by mhoemmen** [comment]
Can we call this inDevelop now, given the merge?

**Comment by ibaned** [comment]
probably. added the label, if I'm wrong please remove.

**Comment by hcedwar** [comment]
Move out of experimental namespace

**Comment by ndellingwood** [comment]
Final decisions/requests/changes regarding API also needed prior to the Sept milestone.

**Comment by hcedwar** [comment]
and alias back into Experimental namespace for backward compatibility
