### ISSUE TITLE
Consider changing the behavior of `Kokkos::is_initialized` and providing `Kokkos::is_finalized`?

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5208]
Currently `Kokkos::is_initialized` returns
* `false` before calling `Kokkos::initialize` or after calling `Kokkos::finalize`, and
* `true` in-between.

This is unfortunate since it is not legal to call `Kokkos::initialize` more than once, and it means there is no way for programs to figure out if they can safely do so.

We should consider
* changing `Kokkos::is_initialized` so that it returns `false` before calling `Kokkos::initialize`, and `true` after,
* adding `Kokkos::is_finalized` that would return `false` before calling `Kokkos::finalize`, and `true` after.

This would be a breaking change so we need to think carefully about it.

```C++
#include <Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  assert(!Kokkos::is_initialized());
  assert(!Kokkos::is_finalized());

  Kokkos::initialize(argc, argv);

  assert(Kokkos::is_initialized());
  assert(!Kokkos::is_finalized());

  Kokkos::finalize(argc, argv);

  assert(Kokkos::is_initialized());  // <- breaking change
  assert(Kokkos::is_finalized());
```

**Comment by masterleinad** [comment]
I would be in favor of at least adding `Kokkos::is_finalized`.

**Comment by JBludau** [comment]
having a way to query if finalize was called would probably help with the python issue of not being allowed to have libs in the same context that use an initialized kokkos. Still, this would require the python libs to add the `is_finalized` to their interface, and the users to be aware of the issue ...

**Comment by stanmoore1** [comment]
Also related: https://github.com/kokkos/kokkos/issues/4126

**Comment by stanmoore1** [comment]
I support this change--I had to add logic in LAMMPS to work around the lack of `Kokkos::is_finalized()`, see https://github.com/lammps/lammps/blob/develop/src/KOKKOS/kokkos.cpp#L337-L353, would be nice to simplify the user code.

**Comment by masterleinad** [comment]
I think we agree on introducing the functionality of `Kokkos::finalize`. We are most debating how `Kokkos::initialize` should behave.

**Comment by dalg24** [comment]
I am strongly in favor of Option 2 with naming the new facility `Kokkos::initialized` and `Kokkos::finalized` and marking `Kokkos::is_initialized` as deprecated.  I think it is easy to document and least surprising to users without adding any cognitive load (no new symbols, consistency with MPI, etc.)

**Comment by JBludau** [comment]
> I am strongly in favor of Option 2 with naming the new facility `Kokkos::initialized` and `Kokkos::finalized` and marking `Kokkos::is_initialized` as deprecated. I think it is easy to document and least surprising to users without adding any cognitive load (no new symbols, consistency with MPI, etc.)

if we do this, the names `Kokkos::initialize` and `Kokkos::initialized` are easy to mix up

**Comment by JBludau** [comment]
I kind of like option 4, as it clearly differentiates between the three states but keeps the interface of returning `bool` for easy `if`. I would favor `must_initialize()` though, as it conveys that it is not optional.

**Comment by nliber** [comment]
I'm fine with renaming it to `must_initialize`.

**Comment by crtrott** [comment]
Option 4 updated:
```
bool can_initialize();
bool is_initialized();
bool was_finalized();
```

**Comment by dalg24** [comment]
Team decision was option 1, pure addition of `is_finalized()` no change in behavior for `is_initialized`.
