### ISSUE TITLE
Custom Reduction Types in Nested Parallelism

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#521]
I posted this question to the Kokkos-Users mailing list back in April. I have a (nested) reduction:

```c++
double a = 0.0, b = 0.0;
parallel_reduce (TeamThreadRange(N), [&] (const int i, SumAndWeightedSum & isum)
{
  parallel_reduce (ThreadVectorRange(M), [&] (const int j, double & jsum)
  {
    jsum += y(j)
  }, value);
  isum.a += value
  isum.b += i*value;
}, (a,b));
```

@crtrott gave what the type `SumAndWeightedSum` in the above example would have to look like: 

```c++
struct SumAndWeightedSum {
  double sum;
  double weighted_sum;

  KOKKOS_INLINE_FUNCTION
  SumAndWeightedSum ():sum(0),weighted_sum(0) {}

  KOKKOS_INLINE_FUNCTION
  SumAndWeightedSum (double& sum_, int& i):sum(sum_),weighted_sum(sum_*i) {}

  KOKKOS_INLINE_FUNCTION
  void operator += (SumAndWeightedSum& val) {
    sum += val.sum;
    weighted_sum += val.weighted_sum;
  }

  KOKKOS_INLINE_FUNCTION
  void operator += (const volatile SumAndWeightedSum& val) volatile {
    sum += val.sum;
    weighted_sum += val.weighted_sum;
  }

KOKKOS_INLINE_FUNCTION
  void operator = (SumAndWeightedSum& val) {
    sum = val.sum;
    weighted_sum = val.weighted_sum;
  }

  KOKKOS_INLINE_FUNCTION
  void operator = (const volatile SumAndWeightedSum& val) volatile {
    sum = val.sum;
    weighted_sum = val.weighted_sum;
  }

};
```

There was some disagreement at the time about if that was correct or not. Given that a consensus was not reached *and* that changes have been made to reductions, **is the above still the way to go?**

Also, this question was originally posted through the Kokkos-Users mailing list, there was some discussion at the tech review about where to post questions, but I don't recall a consensus being reached.

**Is the preference to post questions on the email list or here on github?**

**Comment by crtrott** [comment]
The strong preference is to put questions on github. There is a new interface for custom reductions but I am not sure if it fits this particular use case. We need to check that.

**Comment by dholladay00** [comment]
If the new interface does not fit this use case, would the solution proposed above be the correct thing?

**Comment by dholladay00** [comment]
What is the status of the new interface for custom reductions?

**Comment by crtrott** [comment]
The new interface is in for global reduction but not for nested ones (with TeamThreadRange etc). I have to check whether the interface covers your usecase.

**Comment by dholladay00** [comment]
* What did you find out in terms of the new interface?
* If it does not cover my use case, is the above method the best way to go about it?

**Comment by crtrott** [comment]
Ok so I looked into this: and yes the new interface covers this, but actually what you are doing is a legitimate summation. So I think the way you go about doing this is actually completely correct. 

Just in case you wonder: here is the example code of how to do it via a custom reduction:

```C++
#include<Kokkos_Core.hpp>

template<class Scalar,class Space = Kokkos::HostSpace>
struct Sum {
public:
  //Required
  typedef Sum reducer_type;
  typedef Kokkos::pair<Scalar,Scalar> value_type;

  typedef Kokkos::View<value_type, Space, Kokkos::MemoryTraits<Kokkos::Unmanaged> > result_view_type;

private:
  result_view_type result;

public:
  Sum(value_type& result_):
    result(&result_) {}

  //Required
  KOKKOS_INLINE_FUNCTION
  void join(value_type& dest, const value_type& src)  const {
    dest.first += src.first;
    dest.second += src.second;
  }

  KOKKOS_INLINE_FUNCTION
  void join(volatile value_type& dest, const volatile value_type& src) const {
    dest.first += src.first;
    dest.second += src.second;
  }

  //Optional
  KOKKOS_INLINE_FUNCTION
  void init( value_type& val)  const {
    val = value_type(0,0);
  }

  result_view_type result_view() const {
    return result;
  }
};

int main() {
  Kokkos::initialize();

  int N = 1000;

  Kokkos::View<int*> a("A",N);

  Kokkos::parallel_for(N, KOKKOS_LAMBDA(const int& i) {
    a(i) = i;
  });

  int sum = 0;
  Kokkos::parallel_reduce(N, KOKKOS_LAMBDA(const int& i, int& lsum) {
    lsum += a(i);
  },sum);

  int weighted_sum = 0;
  Kokkos::parallel_reduce(N, KOKKOS_LAMBDA(const int& i, int& lsum) {
    lsum += i%2==0?a(i):0;
  },weighted_sum);

  Sum<int>::value_type hybrid_sum;
  Kokkos::parallel_reduce(N, KOKKOS_LAMBDA(const int& i, Sum<int>::value_type& lsum) {
    lsum.first += a(i);
    lsum.second += i%2==0?a(i):0;
  },Sum<int>(hybrid_sum));

  printf("%i | %i %i | %i %i | (%i %i)\n",N,sum,weighted_sum,hybrid_sum.first,hybrid_sum.second,N*(N-1)/2, N*(N-2)/4);

  Kokkos::finalize();
}

```

**Comment by dholladay00** [comment]
I have attempted and am coming upon **compilation errors**. Before I go digging further, I want to make sure that the fact that my use is slightly different than your example. Namely that this occurs within a parallel region and makes use of nested reductions (the inner-most reduction is of a standard scalar type (int, float, double etc.)). Below I show something very close to what I am attempting to implement.

Would the following be legal?

```c++
parallel_for (policy, KOKKOS_LAMBDA (const member_type & team)
{
  …
  Sum<int>::value_type hybid_sum;
  Kokkos::parallel_reduce (TeamThreadRange(team, N), [&] (const int& i, Sum<int>::value_type& lsum) {
    View<const int*, random_access> a(b(i)); // b is a view of views
    const int M = a.dimension(0);
    int inner_sum = 0;
    Kokkos::parallel_reduce (ThreadVectorRange(team, M), [&] (const int& j, int& jsum)
    {
      jsum += a(j);
    }, inner_sum);
    lsum.first += inner_sum;
    lsum.second += i*inner_sum;
  },Sum<int>(hybrid_sum));

  const int c = hybrid_sum.first/hybrid_sum.second;
});
```

I can provide specific errors if needed.

**Comment by dholladay00** [comment]
It seemed that for my use case, I would need to allocate the resultant view with team scratch memory. I tested out the following:

```c++
parallel_for (policy.set_scratch_size(…), KOKKOS_LAMBDA (const member_type & team)
{
  …
  Sum<int>::result_view_type res(team.team_scratch(0));
  Sum<int> hybid_sum(res);
  Kokkos::parallel_reduce (TeamThreadRange(team, N), [&] (const int& i, Sum<int>::value_type& lsum) {
    View<const int*, random_access> a(b(i)); // b is a view of views
    const int M = a.dimension(0);
    int inner_sum = 0;
    Kokkos::parallel_reduce (ThreadVectorRange(team, M), [&] (const int& j, int& jsum)
    {
      jsum += a(j);
    }, inner_sum);
    lsum.first += inner_sum;
    lsum.second += i*inner_sum;
  }, hybrid_sum);

  Sum<int>::value_type hs(res());
  const int c = hs.first/hs.second;
});
```

This also required adding a ctor: `Sum(result_view_type& result_) : result(result_) { }`. Now I am getting the error: 

```
error: no match for ‘operator+=’ (operand types are ‘Sum<int>’ and ‘Sum<int>’)
     result+=tmp;
```

Would this require adding a `+=` operator overload to the `Sum` struct, or is there more going on?

**Comment by dholladay00** [comment]
For this particular application, the following works on master branch (after help from @crtrott):

```c++
struct multiple_sums {
  real_t sum;
  real_t wsum;
  
  KOKKOS_INLINE_FUNCTION
  multiple_sums()
  : sum(0),
  wsum(0) 
  { }
  
  KOKKOS_INLINE_FUNCTION
  multiple_sums(real_t & sum_, int_t & i)
  : sum(sum_),
  wsum(i*sum_)
  { }

  KOKKOS_INLINE_FUNCTION
  multiple_sums(const multiple_sums & s)
  : sum(s.sum),
  wsum(s.wsum)
  { }
  
  KOKKOS_INLINE_FUNCTION
  multiple_sums(const volatile multiple_sums & s)
  : sum(s.sum),
  wsum(s.wsum)
  { }  
  
  KOKKOS_INLINE_FUNCTION
  void operator += (const multiple_sums & val)
  {
    sum += val.sum;
    wsum += val.wsum;
  }
  
  KOKKOS_INLINE_FUNCTION
  void operator += (const volatile multiple_sums & val) volatile
  {
    sum += val.sum;
    wsum += val.wsum;
  }

  KOKKOS_INLINE_FUNCTION
  void operator = (const multiple_sums & val)
  {
    sum = val.sum;
    wsum = val.wsum;
  }
  
  KOKKOS_INLINE_FUNCTION
  void operator = (const volatile multiple_sums & val) volatile
  {
    sum = val.sum;
    wsum = val.wsum;
  }  

  KOKKOS_INLINE_FUNCTION
  void operator = (const volatile multiple_sums & val)
  {
    sum = val.sum;
    wsum = val.wsum;
  }  

};
```

It seems to be connected to other open issues, but for my purposes, this can be closed.

**Comment by crtrott** [comment]
OK I close this particular issue. Especially since this is actually the correct way to do this, since you really do have a sum. So even going forward I would recommend this approach.

**Comment by dholladay00** [comment]
For the case of true sums of 2 numbers (no weighting involved), do you think you could implement the necessary overloads to allow a `Kokkos::pair` to be used as a reduction type?

**Comment by mhoemmen** [comment]
> For the case of true sums of 2 numbers (no weighting involved), do you think you could implement the necessary overloads to allow a Kokkos::pair to be used as a reduction type?

Kokkos::pair also needs to work for types for which operator+ is not defined.  Correctly defining Kokkos::pair::operator+ would thus require conditional compilation with a traits class to identify "types for which operator+ is defined."  We could use std::is_arithmetic, but that would only cover built-in types for which operator+ is defined.

**Comment by dholladay00** [comment]
It's not a big deal as I have something that already works. I use pairs of builtin types in several places. If it's something that is also common to other users, it could be worth doing. I use it mostly because I happen to want to return 2 numbers in a lot of places, perhaps a `Kokkos::Array` would be the more appropriate thing for me to use, but I am not sure.

**Comment by crtrott** [comment]
We could think about something like: arithmetic_pair or numeric_pair, which requires that all those operators are defined.
