### ISSUE TITLE
Trilinos nightly test failure, Stokhos_SacadoMPVectorUnitTest_MPI_1 (various subtests)

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5216]
Stokhos failure I may have missed (or may have been began after merge of changes to Kokkos on 7/8/2022):

```
00:44:30 	2319 - Stokhos_SacadoMPVectorUnitTest_MPI_1 (Failed)
...
23:43:46 111. DynamicStridedVector_Max_UnitTest ... 
23:43:46  Comparing u == v ... 
23:43:46  Error, relErr(u[1],v[1]) = relErr(0.1,0.25) = 0.15 <= tol = 3.5e-05: failed!
23:43:46  
23:43:46  Error, relErr(u[2],v[2]) = relErr(0.2,0.5) = 0.3 <= tol = 6e-05: failed!
23:43:46  
23:43:46  Error, relErr(u[3],v[3]) = relErr(0.3,0.75) = 0.45 <= tol = 8.5e-05: failed!
23:43:46  
23:43:46  Error, relErr(u[4],v[4]) = relErr(0.4,1) = 0.6 <= tol = 0.00011: failed!
23:43:46  
23:43:46  Error, relErr(u[5],v[5]) = relErr(0.5,1.25) = 0.75 <= tol = 0.000135: failed!
23:43:46  
23:43:46  Error, relErr(u[6],v[6]) = relErr(0.6,1.5) = 0.9 <= tol = 0.00016: failed!
23:43:46  
23:43:46  Error, relErr(u[7],v[7]) = relErr(0.7,1.75) = 1.05 <= tol = 0.000185: failed!
23:43:46  
23:43:46  u = [ 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ]
23:43:46  v = [ 0 0.25 0.5 0.75 1 1.25 1.5 1.75 ]
23:43:46  [FAILED]  (0.000566 sec) DynamicStridedVector_Max_UnitTest
23:43:46  Location: /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp:490
...
23:43:46 115. DynamicStridedVector_Max_left_const2_UnitTest ... 
23:43:46  Comparing u == v ... 
23:43:46  Error, u.size() = 1 == v.size() = 8 : failed!
23:43:46  [FAILED]  (0.000486 sec) DynamicStridedVector_Max_left_const2_UnitTest
23:43:46  Location: /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp:490
23:43:46  
23:43:46 116. DynamicStridedVector_Max_right_const2_UnitTest ... 
23:43:46  Comparing u == v ... 
23:43:46  Error, u.size() = 1 == v.size() = 8 : failed!
23:43:46  [FAILED]  (0.00048 sec) DynamicStridedVector_Max_right_const2_UnitTest
23:43:46  Location: /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp:490
23:43:46  
23:43:46 117. DynamicStridedVector_Max_resize_UnitTest ... 
23:43:46  Comparing u == v ... 
23:43:46  Error, relErr(u[1],v[1]) = relErr(0.1,0.25) = 0.15 <= tol = 3.5e-05: failed!
23:43:46  
23:43:46  Error, relErr(u[2],v[2]) = relErr(0.2,0.5) = 0.3 <= tol = 6e-05: failed!
23:43:46  
23:43:46  Error, relErr(u[3],v[3]) = relErr(0.3,0.75) = 0.45 <= tol = 8.5e-05: failed!
23:43:46  
23:43:46  Error, relErr(u[4],v[4]) = relErr(0.4,1) = 0.6 <= tol = 0.00011: failed!
23:43:46  
23:43:46  Error, relErr(u[5],v[5]) = relErr(0.5,1.25) = 0.75 <= tol = 0.000135: failed!
23:43:46  
23:43:46  Error, relErr(u[6],v[6]) = relErr(0.6,1.5) = 0.9 <= tol = 0.00016: failed!
23:43:46  
23:43:46  Error, relErr(u[7],v[7]) = relErr(0.7,1.75) = 1.05 <= tol = 0.000185: failed!
23:43:46  
23:43:46  u = [ 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ]
23:43:46  v = [ 0 0.25 0.5 0.75 1 1.25 1.5 1.75 ]
23:43:46  [FAILED]  (0.000567 sec) DynamicStridedVector_Max_resize_UnitTest
23:43:46  Location: /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA101_opt/Trilinos/packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp:490
```

_Originally posted by @ndellingwood in https://github.com/kokkos/kokkos/issues/5189#issuecomment-1180762625_

**Comment by ndellingwood** [comment]
List of commits from 7/8/2022 (of which one is culprit triggering the failure):

Git (git https://github.com/kokkos/kokkos.git)

    Provide ViewCtorProp overload for create_mirror_view_and_copy ([commit: ec9da94](https://github.com/kokkos/kokkos/commit/ec9da947b671a1a3990eb8ae4de6363417ca4985)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Add a test ([commit: 939b781](https://github.com/kokkos/kokkos/commit/939b7815d763359fe94f4c67d69e3948236bb791)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Fix warning ([commit: 6b7468b](https://github.com/kokkos/kokkos/commit/6b7468b35cc6a8785b930b799b700b180d146c1d)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Shift dummy arguments ([commit: 7f04137](https://github.com/kokkos/kokkos/commit/7f0413700faed6c0462e2a8eac9d31853e05164c)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    DynRankView implementation ([commit: 447f8ff](https://github.com/kokkos/kokkos/commit/447f8ff7556e59617e36af15ca49b51027575a48)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Small fixes ([commit: 84dc902](https://github.com/kokkos/kokkos/commit/84dc90203f43968d96b2216a529c1079975181ff)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Implement OffsetView ([commit: 521767a](https://github.com/kokkos/kokkos/commit/521767aa8f1e65f2954224ecaac433bef418f467)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Minor fix ([commit: 2cda2c1](https://github.com/kokkos/kokkos/commit/2cda2c1004bc5371ba294bb3038ae65b79259c15)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Implement DynamicView ([commit: 211ece8](https://github.com/kokkos/kokkos/commit/211ece819ac97c99341160aafb18e26fa196fc0d)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Fix deep_copy_to ([commit: 55e763e](https://github.com/kokkos/kokkos/commit/55e763e7be794a85ac40177f8ec3fbd851212317)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Use TEST_EXECSPACE in containers/TestWithoutInitializing.hpp ([commit: 6ce5a94](https://github.com/kokkos/kokkos/commit/6ce5a947d9dd1aa2fa762ae16620df405c231a4a)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Disable test for UVM; they fence to much ([commit: 527b92f](https://github.com/kokkos/kokkos/commit/527b92f448c050b017b6dd19b7da6266140f727c)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Restore containers/unit_tests/CMakeLists.txt ([commit: 0c970ba](https://github.com/kokkos/kokkos/commit/0c970bacdc587158e36e8fac9087481984f23d87)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Disable kokkosp.create_mirror_view_and_copy for OpenMPTarget ([commit: cb93153](https://github.com/kokkos/kokkos/commit/cb9315369e27e6e3cf9e12b3e3fedcada2a1a498)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Indentation ([commit: ed2fe37](https://github.com/kokkos/kokkos/commit/ed2fe3796ef478b32108ae12558de85f902dc7cb)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Disable kokkosp.create_mirror_view_and_copy for CUDA UVM ([commit: 375a21f](https://github.com/kokkos/kokkos/commit/375a21fa23f6f093bf292796448a18afdb2147b4)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Move min, max, clamp, minmax routines out of Experimental namespace ([commit: 233e4ee](https://github.com/kokkos/kokkos/commit/233e4ee43c7ff5c7ec4a86275ff1621664057985)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Fix clang formatting ([commit: 0bc4ddf](https://github.com/kokkos/kokkos/commit/0bc4ddf0c169c8eb14a3931b1e2dd59684c9efe7)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))
    Add reimport of min/max etc to Experimental ([commit: c9e065a](https://github.com/kokkos/kokkos/commit/c9e065a4c91385a31f0a42a55530ea54582e7ee4)) ([detail](https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_CUDA101_opt/577/changes#detail))


**Reproducer**:
```bash
# Repos
git clone -b kokkos-promotion https://github.com/trilinos/Trilinos.git
git clone -b develop kokkos
git clone -b develop kokkos-kernels
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Modules and env
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/weaver
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
module list
export OMPI_CXX=<path-to-your-kokkos-repo>/bin/nvcc_wrapper

# Configure
cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX=$PWD/install \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DTrilinos_ENABLE_Intrepid2=ON \
 -DIntrepid2_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_Panzer=ON \
 -DPanzer_ENABLE_TESTS=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by masterleinad** [comment]
It appears that the problem is that `Kokkos`' `max` function is a better match than `Sacado::MP::max` and the test intents to use the latter one.

**Comment by masterleinad** [comment]
Sounds similar to what @maartenarnst is observing in https://github.com/trilinos/Trilinos/issues/10740#issuecomment-1180885529.

**Comment by masterleinad** [comment]
An easy fix would be to just replace the unqualified operator names by `Sacado::MP` prefixed ones in the test but it's probably worth figuring out why ADL is not working as intended.

**Comment by masterleinad** [comment]
https://github.com/trilinos/Trilinos/pull/10779 should fix this.

**Comment by ndellingwood** [comment]
Thanks for the fix to Trilinos @masterleinad , it has merged to Trilinos develop branch and I confirm it resolved failures in our nightly testing of Trilinos with kokkos' develop branch
