### ISSUE TITLE
KokkosTargets.cmake is not created by make install

### ISSUE THREAD

**Issue by mayianm** [kokkos/kokkos#5231]
Hi all,
I am migrating a code from using raw makefiles inline to instead use CMake with Kokkos installed separately. Presently I am stuck on the `find_package (Kokkos REQUIRED)` step.

find_package does successfully find the install directory, but throws the error:
`CMake Error at external/kokkos/build/KokkosConfig.cmake:69 (INCLUDE):`
`  INCLUDE could not find requested file:`

`    /home/ian/Code/kfvm-kokkos/external/kokkos/build/KokkosTargets.cmake`
`Call Stack (most recent call first):`
`  CMakeLists.txt:11 (find_package)`

The paths referenced all make sense with where I tried installing Kokkos. From within the Kokkos root directory I did the installation as follows:
`mkdir build && cd build`

`cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=. -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_HWLOC=ON -DKokkos_ARCH_ZEN2=ON -DKokkos_ARCH_TURING75=ON`

`make -j`

`make install`

Neither the `cmake` nor the `make` calls throw any errors. After this the build directory does contain the KokkosConfig.cmake file that `find_package` found, but does not contain any KokkosTargets.cmake file. I did find that file inside lib/cmake/Kokkos, but naturally copying that up to the build directory just creates new errors.

If I manually change line 69 in KokkosConfig.cmake from `INCLUDE("${Kokkos_CMAKE_DIR}/KokkosTargets.cmake")` to `INCLUDE("${Kokkos_CMAKE_DIR}/lib/cmake/Kokkos/KokkosTargets.cmake")` I can successfully get through the cmake call in my code, but then failure happens at the make step instead. Also, manually fiddling with the config file seems ill-advised.

I'm not familiar with cmake beyond the surface level, so I'll attach everything that seems vaguely relevant. Github doesn't seem to like the .cmake or .h extensions, so I've renamed those to .txt instead.
[CMakeCache.txt](https://github.com/kokkos/kokkos/files/9128327/CMakeCache.txt)
[install_manifest.txt](https://github.com/kokkos/kokkos/files/9128328/install_manifest.txt)
[KokkosConfig.txt](https://github.com/kokkos/kokkos/files/9128330/KokkosConfig.txt) (Really .cmake)
[KokkosCore_config.txt](https://github.com/kokkos/kokkos/files/9128333/KokkosCore_config.txt) (Really .h)

Thank you all for your time and effort! I'd wager there is a simple fix, but I'm out of ideas at this point.

**Describe the bug**
Please provide a concise, clear description of the bug, as well as any available error logs.

**Please also include the following items to support reproducing the bug**
1. compilers (with versions)
2. Kokkos release or commit used (i.e., the sha1 number)
3. platform and backend
4. cmake configure command
5. output from cmake command
6. code needed to reproduce the bug
7. command line needed to reproduce the bug
7. please also attach the `KokkosCore_config.h` header file (generated during the build);
**Any additional info**
Please provide any additional context about the issue here.

**Comment by dalg24** [comment]
You are installing into the build directory ` -DCMAKE_INSTALL_PREFIX=.`
It is generally not a good idea.
You need to specify some other path.

**Comment by mayianm** [comment]
Thanks dalg24. I've just discovered that. I was trying to mock up what will happen on the cluster when I don't have the ability to touch /usr/local at all.

I'll close this and break things out into a few different directories.
