### ISSUE TITLE
Visual Studio 2019 + clang-cl : /clang:-fopenmp=libomp is passed to linker options

### ISSUE THREAD

**Issue by JoeOnTheSpot** [kokkos/kokkos#5236]
Flag /clang:-fopenmp=libomp is passed to both compile options and linker options on tag 3.6.01. 
This leads to a linker error "file not found".

**Comment by crtrott** [comment]
Is that only happening if enabling OpenMP or without it? We do not currently support OpenMP with MSVC because it doesn't support enough of the OpenMP standard, and I don't think even its clang variant ships a full openmp runtime or?

**Comment by JoeOnTheSpot** [comment]
Hello,

This only happens with OpenMP enabled.
To clarify, the issue arises with the Visual Studio generator + ClangCL toolkit, both from the command line and from within the IDE.

I have no issue building with Ninja + Clang on Windows however.

**Comment by crtrott** [comment]
Proper clang likely comes with a proper OpenMP runtime so it will work, while Microsofts clang version does not :-(, I can investigate more but my guess is we can't make OpenMP work with ClangCL

**Comment by JoeOnTheSpot** [comment]
That's ok, I think a word in the wiki would be sufficient :)

Thank you  for your help.

**Comment by sketch34** [comment]
> We do not currently support OpenMP with MSVC because it doesn't support enough of the OpenMP standard.

Maybe there could be a matrix of backends vs compiler support? I just spent a lot of time trying to get kokkos compiling with MSVC + OpenMP before finding this comment. The readme kind of implies that MSVC is a fully supported compiler ("primary") so I assumed Kokkos + MSVC would work without limitation.

https://github.com/kokkos/kokkos#primary-tested-compilers

_Note: I was trying with MSVC 19.32.31332.0_
