### ISSUE TITLE
String class container

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#524]
Any chance of getting a string container as a special part of view?  So many classes we use, use strings, because of this when we port it would be nice to have a string view.

Understand this is a fluffy feature request, but curious if others want/need this.

**Comment by mhoemmen** [comment]
Could you clarify how this differs from `Kokkos::View<char*>`?

**Comment by bathmatt** [comment]
the same way std::string is different than std::vector<char>

it is the functions that go along with it.

**Comment by bathmatt** [comment]
Oh, and I said it was a fluffy feature :)

**Comment by mhoemmen** [comment]
@bathmatt wrote:
> Oh, and I said it was a fluffy feature :)

Maybe not fluffy if you're writing a parallel database!  On the other hand, I don't think std::string semantics are quite right here.  (std::string is mutable, and implementations often do "copy on write," much like Matlab's matrices.)  What you likely want are the string-related utility functions (e.g., change case), but not std::string semantics.  Is that right?

**Comment by crtrott** [comment]
This is something we could add to containers or algorithms.

**Comment by crtrott** [comment]
Also one difference to std::string would be that it actually works on GPUs ...

**Comment by bathmatt** [comment]
What Christian said...

Really, what I want is to have things where we pass strings in now and they
get copied around as part of kokkos views.
It is a low priority, but thinking for error stuff mostly.  However, what
i've started doing is creating error handlers and passing back ints and
have things like errno functions in the old days of C

**Comment by crtrott** [comment]
Matt: for error handling we are actually gonna add something. I was planning to fix up a pull request this week and get it into the develop branch: #518 
We will make it an experimental feature initially and then want to solicit feedback on the functionality and the interface. For example I was considering whether we should have a default instance of the error handler around for strings which is always available (kind of a singleton concept).
