### ISSUE TITLE
equivalent of std::shared_ptr::unique() for Kokkos::View ?

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#525]
I'm trying to track the memory usage by instances of a class which contains a `Kokkos::View`. The idea is that in the destructor I would call this function to determine if the `Kokkos::View` destructor would deallocate its memory:
```
MyClass::~MyClass() {
  if (view.unique()) {
    global_memory_counter -= my_memory_use;
  }
}
```
Is there a good way to do this ?

**Comment by mhoemmen** [comment]
Would it be better if Kokkos tracked memory usage for you?  See e.g., #300.

**Comment by ibaned** [comment]
I'd be fine if Kokkos did the tracking for me, although I'd like to track only memory usage by my library separately from other libraries using Kokkos, and it would be great if I could track at an even finer granularity.

**Comment by mhoemmen** [comment]
@nmhamster, @crtrott -- does the Kokkos Profiling library track allocations and deallocations?  I think you could use or even modify that in order to call arbitrary functions of your choice on allocation or deallocation.

**Comment by hcedwar** [comment]
[Would `use_count()` suffice?](https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_View.hpp#L1261)

**Comment by ibaned** [comment]
@hcedwar I guess I didn't look very hard, yes `Kokkos::View::use_count()` will suffice. Thank you. I'll try to implement this with `use_count` and reopen this if that doesn't work.
