### ISSUE TITLE
strange behavior of CudaUVMSpace in develop branch

### ISSUE THREAD

**Issue by XzzX** [kokkos/kokkos#5252]
I am seeing a strange performance regression when changing from Kokkos `3.6.01` to the current `develop` branch.
Code:
 * Cuda 11.4 and run on A100
 * all memory is allocated in CudaUVMSpace
 * I am allocating a bunch of matrices and right hand sides
 * I am calling 5 times `cublasDgelsBatched` on exactly the same data allocated in CudaUVMSpace

Kokkos 3.6.01
![fast](https://user-images.githubusercontent.com/2733900/180416313-559a6633-0427-4d56-b1e4-3ed139e7c08a.png)
This is what I expected to happen.

Kokkos develop
![slow](https://user-images.githubusercontent.com/2733900/180416359-fb2df360-1f39-411a-9fc7-53737f2939bd.png)
All DtoH traffic is evictions?!? Of course, this version is much slower.

Everything is reproducible by changing between the two Kokkos versions. Is anything changed in the way how Kokkos handles UVM? The benchmark code is already a MWE of a larger code and can be found here: https://gitlab.mpcdf.mpg.de/seibl/batched_gels

**Comment by dalg24** [comment]
Do you mind trying 9beba321593b97645b0bda866a8e84c5cc9fc050 ?

**Comment by XzzX** [comment]
> Do you mind trying [9beba32](https://github.com/kokkos/kokkos/commit/9beba321593b97645b0bda866a8e84c5cc9fc050) ?

This commit is fine. Performance similar to `3.6.01`.

**Comment by dalg24** [comment]
What about 7ffb61a105ae513a66ad95a9e9c525411900b8d1

**Comment by crtrott** [comment]
Hm I wasn't able to reproduce it. How did you run it (also I disabled the MKL run)

**Comment by crtrott** [comment]
Even with MKL enabled I was not able to reproduce it. 

Develop:
```
 GPU activities:   58.91%  10.3518s         8  1.29398s  1.28917s  1.30694s  _ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_11ParallelForIZ12batched_gelsILb0EEvP13cublasContextiiEUliiE_NS_13MDRangePolicyIJNS_4CudaENS_4RankILj2ELNS_7IterateE0ELSA_0EEEEEES8_EEEEvT_
                   40.34%  7.08940s      1275  5.5603ms  1.5869ms  169.45ms  void geqrSolve_batch_kernel<double, double, int=32, int=8, bool=0>(int, int, int, int, double* const *, int, double* const *, int, int, int*)
                    0.67%  117.10ms        50  2.3421ms  3.1680us  4.4259ms  [CUDA memset]
                    0.09%  14.958ms      1275  11.731us  6.2080us  225.92us  void trsm_batch_left_upper_kernel<double>(cublasTrsmBatchParams<double>, double const * const *, double* const *, double const *, double)
                    0.00%  43.455us         1  43.455us  43.455us  43.455us  desul::_GLOBAL__N__50_tmpxft_00014bc7_00000000_7_Lock_Array_CUDA_cpp1_ii_4d2bf3a0::init_lock_arrays_cuda_kernel(void)
                    0.00%  14.912us        12  1.2420us  1.1200us  1.5360us  [CUDA memcpy HtoD]
                    0.00%  7.6800us         3  2.5600us  1.9840us  3.6480us  [CUDA memcpy DtoH]
                    0.00%  3.7440us         1  3.7440us  3.7440us  3.7440us  Kokkos::_GLOBAL__N__52_tmpxft_00014bb8_00000000_7_Kokkos_Cuda_Locks_cpp1_ii_915ea793::init_lock_array_kernel_atomic(void)
                    0.00%  3.0400us         1  3.0400us  3.0400us  3.0400us  Kokkos::Impl::_GLOBAL__N__55_tmpxft_00014bb1_00000000_7_Kokkos_Cuda_Instance_cpp1_ii_f3693ba3::query_cuda_kernel_arch(int*)
....
==85761== Unified Memory profiling result:
Device "Tesla V100-PCIE-16GB (0)"
   Count  Avg Size  Min Size  Max Size  Total Size  Total Time  Name
     991  68.197KB  4.0000KB  0.9961MB  66.00000MB  8.033700ms  Host To Device
    3632  99.260KB  4.0000KB  0.9961MB  352.0625MB  32.24445ms  Device To Host
   90004         -         -         -           -  10.410969s  Gpu page fault groups
```

3.6.1
```
 GPU activities:   59.83%  10.7406s         8  1.34258s  1.33360s  1.35586s  _ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_11ParallelForIZ12batched_gelsILb0EEvP13cublasContextiiEUliiE_NS_13MDRangePolicyIJNS_4CudaENS_4RankILj2ELNS_7IterateE0ELSA_0EEEEEES8_EEEEvT_
                   39.50%  7.09142s      1275  5.5619ms  1.5848ms  169.61ms  void geqrSolve_batch_kernel<double, double, int=32, int=8, bool=0>(int, int, int, int, double* const *, int, double* const *, int, int, int*)
                    0.59%  105.62ms        50  2.1123ms  3.2000us  4.0830ms  [CUDA memset]
                    0.08%  14.989ms      1275  11.756us  6.2400us  225.02us  void trsm_batch_left_upper_kernel<double>(cublasTrsmBatchParams<double>, double const * const *, double* const *, double const *, double)
                    0.00%  43.264us         1  43.264us  43.264us  43.264us  desul::_GLOBAL__N__50_tmpxft_00013f0f_00000000_7_Lock_Array_CUDA_cpp1_ii_4d2bf3a0::init_lock_arrays_cuda_kernel(void)
                    0.00%  14.656us        12  1.2210us  1.1200us  1.6000us  [CUDA memcpy HtoD]
                    0.00%  7.7440us         3  2.5810us  1.9840us  3.7120us  [CUDA memcpy DtoH]
                    0.00%  3.7120us         1  3.7120us  3.7120us  3.7120us  Kokkos::_GLOBAL__N__52_tmpxft_00013eff_00000000_7_Kokkos_Cuda_Locks_cpp1_ii_915ea793::init_lock_array_kernel_atomic(void)
                    0.00%  3.0400us         1  3.0400us  3.0400us  3.0400us  Kokkos::Impl::_GLOBAL__N__55_tmpxft_00013efe_00000000_7_Kokkos_Cuda_Instance_cpp1_ii_f3693ba3::query_cuda_kernel_arch(int*)
                    ....
==83584== Unified Memory profiling result:
Device "Tesla V100-PCIE-16GB (0)"
   Count  Avg Size  Min Size  Max Size  Total Size  Total Time  Name
     967  69.890KB  4.0000KB  0.9961MB  66.00000MB  7.980864ms  Host To Device
    3632  99.260KB  4.0000KB  0.9961MB  352.0625MB  32.24247ms  Device To Host
   90046         -         -         -           -  10.776118s  Gpu page fault groups
Total CPU Page faults: 232384
```

**Comment by crtrott** [comment]
However I do see an overall time difference with MKL in the picture: 
15min vs 11min which is not explained by anything I see in the nvprof output.

**Comment by XzzX** [comment]
> Hm I wasn't able to reproduce it. How did you run it (also I disabled the MKL run)

Did you change https://gitlab.mpcdf.mpg.de/seibl/batched_gels/-/blob/main/CMakeLists.txt#L15 to `develop`?

My cmake command is pretty simple: `cmake -S batched_gels -B batched-test -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ENABLE_CUDA_UVM=ON -DKokkos_ARCH_AMPERE80=ON`
I use Intel 2021.5.0.20211109 as a host compiler. Just tried it, I can still reproduce it.

Hmm, also my MKL runs are stable in terms of performance.

**Comment by XzzX** [comment]
> What about [7ffb61a](https://github.com/kokkos/kokkos/commit/7ffb61a105ae513a66ad95a9e9c525411900b8d1)

performance is fine

**Comment by XzzX** [comment]
Solution:  
In https://github.com/kokkos/kokkos/pull/5211 the default assignment of GPUs to MPI ranks changed. I did not do anything special, so all gets mapped to device 0. `--kokkos-map-device-id-by=mpi_rank` solves the problem. Unfortunately, I did not see that all 4 devices reported by nsight systems have the same id... So I thought everything is fine.

**Comment by PhilMiller** [comment]
Should we bring that lack of notice about over subscription to Nvidia's attention?

**Comment by crtrott** [comment]
I don't know its a long standing expected behavior after all
