### ISSUE TITLE
SYCL should not fallback to using the host if Kokkos is configured to use a GPU arch

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5254]
Discussion on https://github.com/kokkos/kokkos/pull/5251#discussion_r927640645 brought up that we should probably not fallback to using the host if the user explicitly specified a GPU architecture at configure time.
For reference, here is how we currently decide what `sycl::device` to use.
https://github.com/kokkos/kokkos/blob/0ef409bab190cdae9417bff34f7cf5c90048f227/core/src/SYCL/Kokkos_SYCL.cpp#L149-L166

**Comment by dalg24** [comment]
In the short term, I think the right thing to do he add an extra condition in the first branch.

Looking forward, Christian has suggested we should explore an opt-in configuration for backends to use whatever we can run on.  This requires more thinking because it would mean we would start targeting multiple architecture with Cuda/HIP which involves non-trivial refactoring.

**Comment by ajpowelsnl** [comment]
@masterleinad - do you have any thoughts about this?  BTW, it does not need to be in the release.

**Comment by masterleinad** [comment]
> @masterleinad - do you have any thoughts about this? BTW, it does not need to be in the release.

See #5624.
