### ISSUE TITLE
Add CTAD (deduction guides) to various types

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos#5257]

**Comment by nliber** [comment]
For `RangePolicy`, it looks like I can deduce the `ExecutionSpace` and the `IndexType`.

**Comment by crtrott** [comment]
I think we should not: similar to extents(5,5) not deducing int in the C++ standard. I think its too easy to make a mistake.

**Comment by nliber** [comment]
Implemented so far:

RangePolicy only deduces execution space
TeamPolicy only deduces execution space
MDRangePolicy deduces execution space and Rank

**Comment by nliber** [comment]
Adding deduction guides to our standard reducers (`Sum`, `Prod`, etc.) 

It is straightforward to deduce all the template parameters from the `View` constructor.

From the `value_type&` constructor, we cannot deduce the memory space.  We could assume it to be `DefaultExecutionSpace::memory_space`.  Is that useful or error-prone?

**Comment by nliber** [comment]
Open question here on deduction guides for `View`:

Besides the following constructors:

```c++
View(T*, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t) -> View<T********>
View(T*, size_t, size_t, size_t, size_t, size_t, size_t, size_t)  -> View<T*******>
View(T*, size_t, size_t, size_t, size_t, size_t, size_t) -> View<T******>
View(T*, size_t, size_t, size_t, size_t, size_t) -> View<T*****>
View(T*, size_t, size_t, size_t, size_t) -> View<T****>
View(T*, size_t, size_t, size_t) -> View<T***>
View(T*, size_t, size_t) -> View<T**>
View(T*, size_t) -> View<T*>
View(T*) -> View<T>

```
are there any other constructors we can deduce the `View` from?

**Comment by dalg24** [comment]
When an execution space is passed via view_alloc
```C++
View<DataType>(view_alloc("v, space), ...) -> View<DataType, decltype(space)>
View<DataType, Layout>(view_alloc("v, space), ...) -> View<DataType, Layout, decltype(space)>

**Comment by nliber** [comment]
@dalg24 `view_alloc("v", space)` doesn't contain the `DataType` needed by `View`, does it?

CTAD has to be `View(...) -> View<...>`; the left hand side cannot have a template argument list.

**Comment by dalg24** [comment]
No it does not.  You're right of course.

**Comment by ajpowelsnl** [comment]
Please summarize how to document deduction guides.

**Comment by mhoemmen** [comment]
@ajpowelsnl Hi!  Not sure how y'all want to do that, but cppreference does it this way:

https://en.cppreference.com/w/cpp/container/span/deduction_guides

**Comment by ajpowelsnl** [comment]
> @ajpowelsnl Hi! Not sure how y'all want to do that, but cppreference does it this way:
> 
> https://en.cppreference.com/w/cpp/container/span/deduction_guides

Hey @mhoemmen -- Many thanks for the info; we we just discussing the issue this morning in our documentation session -- a potential pitfall is that deduction guides (for reductions) require a memory space.

**Comment by nliber** [comment]
> **_Open question_** here on deduction guides for reducers:
> 
> Adding deduction guides to our standard reducers (`Sum`, `Prod`, etc.):
> 
> It is straightforward to deduce all the template parameters from the `View` constructors.
> 
> From the `value_type&` constructors, we cannot deduce the memory space (the information isn't there). We could assume it to be `DefaultExecutionSpace::memory_space`. Is that useful or error-prone? (Please don't just answer "yes" :-))

I don't think we can do this, as `DefaultExecutionSpace` is an incomplete type at this point, so we cannot get `DefaultExecutionSpace::memory_space` out of it.

**Comment by ajpowelsnl** [comment]
Hi @nliber - is there still work in progress on the CTAD Deduction Guide effort, or has all the relevant work been merged?  IN any case, many thanks for any update you can provide!

**Comment by ajpowelsnl** [comment]
Hi @nliber , @dalg24 - where are we on this issue?

**Comment by nliber** [comment]
This is now covered by P/Rs #5515, #5516, #5517 and #6117.

**Comment by ajpowelsnl** [comment]
> This is now covered by P/Rs #5515, #5516, #5517 and #6117.

Have all of these PR been merged?

**Comment by masterleinad** [comment]
> Have all of these PR been merged?

No

**Comment by ajpowelsnl** [comment]
@nliber - what's the status of this issue, and timeline for completion?

**Comment by ajpowelsnl** [comment]
Hi @nliber - what is the status of the remaining work on this issue?  Do we have a pathway and a timeline for completion?

**Comment by nliber** [comment]
All relevant PRs have been Merged.  Closing this out.
