### ISSUE TITLE
Deprecate Kokkos::Impl::VerifyExecutionCanAccessMemorySpace

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#527]
Replace usage of `Kokkos::Impl::VerifyExecutionCanAccessMemorySpace` with
`Kokkos::Impl::SpaceAccessibility` which has improved clarity and functionality in support of issue #290.

**Comment by crtrott** [comment]
YEAH 

I always found VerifyExecutionCanAccessMemorySpace confusing in particular because it actually took two memory spaces!!!
