### ISSUE TITLE
Long Link Times for Kokkos Tests in Trilinos on ARM64 w/ GCC 5.3.0

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#528]
Just seen this recently but will try to work through some of this a bit more on the platform.

`20   0  287552  12160   3712 S  99.7  0.0  17110:56 KokkosCore_Unit`

S.

**Comment by jjellio** [comment]
If binutils is built with gold, perhaps try using -fuse-ld=gold as a link argument to GCC (this works wonderfully only some projects)

**Comment by crtrott** [comment]
wow this is not nice, any idea where this is coming from considering that gcc 5 seems to be fine on both X86 and Power8?

**Comment by nmhamster** [comment]
@crtrott @jjellio I think we may have tracked this to a file system configuration issue. Hope to report back soon one way or another.

**Comment by nmhamster** [comment]
Closing, we *think* this may be a system issue. Will reopen if we see this again on modified system/alternative systems.
