### ISSUE TITLE
Minimum Compiler Version Update

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#5285]
After the 3.7 release, Kokkos is requiring C++17, which necessitates an upgrade in minimum compiler versions.
Furthermore, we are planning to move HIP out of Experimental in the release after 3.7 and start more stable support for ROCM versions. The question arises what that means for minimum versions Kokkos should support.

Here is the proposal we are working with right now, however we are considering lifting the version a bit higher than what we could get away with. The main reason to do so is avoiding known bugs, as well as making our burden for testing/support a bit easier.

| Compiler Line | Current Minimum | Initial Proposal | Considering | Decision | 
| --- | --- | --- | --- | --- | 
| GCC | 5.3 | 7.3 | **8.2** | 8.2 | 
| Clang | 4.0 | **8.0** | 11.1 | 8.0 | 
| Clang as CUDA compiler | 10.0 | **10.0** | 11.1 | 10.0 | 
| Intel `icpc` | 17.0 | 19.1 | **2019.5** (aka `icpc --version` 19.0.5) | 2019.5 | 
| CUDA `nvcc` | 9.2.88 | **11.0** | 11.x | 11.0 |
| Minimum CUDA for use with Clang as CUDA compiler | 10.0.1 | 10.0.1 | -- | 10.0.1 |
| ROCM | 4.5.0 | 5.2.0 | -- | 5.2.0 | 
| IntelLLVM (CPU) `icpx` | 2021.1.1 | 2021.1.1 | -- | 2021.1.1 |
| IntelLLVM (SYCL)| 2022.0.0 | 2022.2.0 | -- |  2022.2.0 |
| NVHPC `nvc++` | 22.3 | 22.3 | -- | 22.3 |
| MSVC | | | | 19.29 |
| IBM XL |  | | | Not supported |
| PGI | | | | now via NVC++ |

Couple notes: 
- Clang as CUDA compiler requires at least 10.x possibly 11.x we test 11.0 currently.
- NVC++ as CUDA compiler is not officially supported yet, we expect official support later this year
- The OpenMPTarget backend has separate requirements for newer compilers
- The upcoming OpenACC backend may have separate requirements for newer compilers

**Comment by PhilMiller** [comment]
For GCC, reasons to consider 8.x or 9.y:
- NVCC with reasonable input can easily generate code that results in ICE crashes of GCC versions up to 7.4, and 7.5 is unlikely to be installed on DOE systems in place of the current widespread 7.3
- There's also a noted correction for DRs regarding C++17 CTAD in GCC 8 per https://gcc.gnu.org/projects/cxx-status.html#cxx17
- 9.2 was also widely installed on DOE systems

**Comment by PhilMiller** [comment]
For Intel, the reason to consider 19.5 is that earlier 19.x releases exhibited a lot of bugs that caused compile-time failures on conformant C++17 code. 19.5 is widely installed on DOE systems (as 19.0.5)

**Comment by ajpowelsnl** [comment]
Do we have a clear understanding of what we lose / costs / bugs in adopting each of the `Considering` versions, vs. those in the `Initial Proposal`? Similarly, what are the benefits of adopting the versions in the `Considering` column?

**Comment by masterleinad** [comment]
For the C++17 pull request, we are currently using
- GCC 12.1.1
- clang 14.0.0
- clang 14.0.5
- GCC 11.2.0
- ICC 2021.6.0.20220226
- IntelLLVM 2022.1.0
- clang 11 + cuda 10.1
- GCC 8.4.0 + cuda 11.0.221
- GCC 9.4.0 + cuda 11.6.124
- NVHPC 22.3.0 + cuda 11.6.112
- GCC ? + cuda 11.7.0
- GCC 8.4.0
- hipcc 4.4.21401 (clang 13.0.0)

suggesting that we maybe shouldn't go below 8.4.0 since that is what we get with the cuda-11.0 container.

**Comment by masterleinad** [comment]
Also, what are we doing about `XL` and `PGI`?
Do we drop support for `PGI` to only support `NVHPC`?
Classic `XL` doesn't seem to have C++17 support at all (https://en.cppreference.com/w/cpp/compiler_support/17, https://www.ibm.com/docs/en/xl-c-and-cpp-aix/16.1?topic=new-clang-based-front-end) but `IBMClang` has (https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Compiler/IBMClang-CXX.cmake, https://www.ibm.com/products/open-xl-cpp-aix-compiler-power).

**Comment by PhilMiller** [comment]
Another point in favor of Intel 19(.0).5: https://github.com/trilinos/Trilinos/wiki/Pull-Request-Testing-Interface shows that it's already part of Trilinos's Dev2Master automated testing

**Comment by masterleinad** [comment]
- Ubuntu 18.04 LTS comes with `gcc-7.4.0`, `clang-6.0`
- Ubuntu 20.04 LTS comes with `gcc-9.3.0`, `clang-10.0`
- Ubuntu 22.04 LTS comes with `gcc-11.2.0`, `clang-14.0`

**Comment by masterleinad** [comment]
Problems in https://github.com/kokkos/kokkos/issues/3496 would also suggest to rather require cuda 11.2 than cuda 11.0.

**Comment by masterleinad** [comment]
In the `CMake` configuration, we check for compilers `GCC < 7`, `nvcc <11`, `ICC 18.0.0` apart from the checks for the current minimum compiler version in general and `nvcc <11.2` for constexpr support.
In code, we have checks for 
- `ICC < 18.0.0`, `ICC >= 2021`, 
- `clang < 8`, `clang >=13`, `clang < 13`, 
- `gcc==10.3.0`, `gcc >= 7.1.0`, `gcc < 5.3.0`, `gcc >= 9.1.0`, `gcc >= 6.1.0`, `gcc >=7.3.0`, `gcc >= 9.3.0`, `gcc < 6.1.0`, `gcc < 7.1.0`, `gcc >= 5.4.0`

We can remove most of these checks already with the initial new minimum compiler versions proposed.

**Comment by masterleinad** [comment]
`CentOS 8 Stream` has `gcc-8.5` and `clang-14.0`.

**Comment by masterleinad** [comment]
Summit has gcc `7.5.0` but `gcc-9.1.0` is the default, the oldest llvm release is `10.0.1` which is also the default.

**Comment by stanmoore1** [comment]
I think we need to support `cuda/11.0.3` on Summit since older CUDA versions are broken with SpectrumMPI CUDA-aware.

**Comment by stanmoore1** [comment]
i.e. `cuda/11.1` and above are broken for CUDA-aware MPI on Summit

**Comment by stanmoore1** [comment]
Correction, I just tried and`cuda/11.1` works for CUDA-aware MPI, but anything higher on Summit, e.g. `cuda/11.3.1` and above are broken. This is a known issue with OLCF, but no idea when it will be fixed.

**Comment by lucbv** [comment]
Should we rename the `CUDA` line to `nvcc`?
Also just for information, llvm is also requiring c++17 to build its projects and proposes the following [minimum requirements](https://discourse.llvm.org/t/rfc-increasing-the-gcc-and-clang-requirements-to-support-c-17-in-llvm/59983)

**Comment by masterleinad** [comment]
We should still discuss what to do with XL and PGI.

**Comment by mdmosby** [comment]
The Sierra apps are targeting Cuda 11.2 due to the cuda-aware spectrum-MPI issues.

For GCC, we are looking at 10+ due to costs associated with updating GCC across all of our supported platforms. We'd like to be able to look ahead to c++20 with more of the features supported (whether or not they are used). Most of our target platforms will be on RHEL8 by the end of CY22, which has GCC8 by default and I think TCE is targeting 10.X (maybe 11). Sierra is flexible on the rest (in many cases meeting or exceeding currently proposed minimums).

**Comment by lucbv** [comment]
@ndellingwood @e10harvey 
Adding you hear so that when the final decision is made we can update the compilers we use in Kokkos Kernels testing accordingly

**Comment by crtrott** [comment]
@mdmosby I updated the decisions we made above. We will likely update CUDA-NVCC to 11.2 when Summit either installs it or goes out of commission.

**Comment by ax3l** [comment]
Hi @crtrott, just want to let you know that WarpX uses 11.3 on Summit due to some compiler bugs in 11.0-11.2 for C++17 code.
The module they provide is non-standard but fully compatible with the system and we saw now issues over a year of production with it.

**Comment by crtrott** [comment]
Yeah we are aware, but 11.3 does not with spectrum mpi with gpu enabled right?

**Comment by crtrott** [comment]
Was just wondering if you got spectrum-mpi to work, or if uou guys simply use openmpi (which anyway would likely be my recommendation too)

**Comment by stanmoore1** [comment]
Last time I checked (in August), CUDA 11.3 was broken with SpectrumMPI on Summit.

**Comment by PhilMiller** [comment]
To memorialize a bit of more recent chatter that I instigated, in investigating #5933, I found that icpc 19.0.5 running with `-O3` besides needing the referenced workaround to not hang for several hours on `Test_MDRange_[bcd..].hpp` also takes over 20 minutes to compile `TestRangePolicyRequire.hpp`, while the rest of a build completes in under 3 minutes.

Both of these issues are resolved with icpc 19.1.2. So, I've proposed a late change to require that as the minimum instead. @ndellingwood agreed on the basis of future support work if/when bugs are identified that need to be investigated and fixes tested.

**Comment by stanmoore1** [comment]
@PhilMiller I think the wiki still needs to be updated: https://kokkos.github.io/kokkos-core-wiki/requirements.html#kokkos-4-x

**Comment by ajpowelsnl** [comment]
> @PhilMiller I think the wiki still needs to be updated: https://kokkos.github.io/kokkos-core-wiki/requirements.html#kokkos-4-x

@stanmoore1 -- is the main issue that we do not have a table for supported compilers for Kokkos-4.x?  In any case, if you summarize your needs, I'll get to it.

**Comment by stanmoore1** [comment]
@ajpowelsnl yes correct, we are going to point that page in the LAMMPS docs and need a table for 4.0. Thanks

**Comment by dalg24** [comment]
row 4 is missing a column :@
thx for reporting
