### ISSUE TITLE
Volatile and C++17/20/23

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#5306]
Q: So now C++23 is de-deprecating volatile bitwise compound assignment operations	[P2327R1](https://wg21.link/P2327R1). What do three variations on the volatile subject (pre-20/20/23) now mean for the end user of kokkos reductions etc.?

**Comment by dalg24** [comment]
This is a good question.
We already lifted the `volatile`-qualified functions requirement in `develop` (in #4931 and follow-up PRs)
We intend for all users to define the non-qualified versions.
It will be in the upcoming release 3.7

**Comment by j8asic** [comment]
Good to know, thanks. Going to test it.

**Comment by ajpowelsnl** [comment]
@j8asic -- have you had a chance yet to test reductions in the context of this change?

**Comment by j8asic** [comment]
Yes. All good

**Comment by ajpowelsnl** [comment]
Thank you!
