### ISSUE TITLE
Seg. fault on ppc64le with clang 15

### ISSUE THREAD

**Issue by scottbiersdorff** [kokkos/kokkos#5315]
This occurs with both version 3.6.01 and well as the master branch:

```
cmake .. -DCMAKE_CXX_COMPILER=clang++   -DCMAKE_INSTALL_PREFIX=`pwd`/../kokkos_install   -DKokkos_ENABLE_OPENMP=On   -DKokkos_ARCH_HSW=On -DKokkos_ENABLE_TESTS=On
make -j install
 OMP_PROC_BIND=TRUE OMP_NUM_THREADS=16 ./core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_color=no --gtest_filter=openmp.task_fib_single
...
Note: Google Test filter = openmp.task_fib_single
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from openmp
[ RUN      ] openmp.task_fib_single
Segmentation fault (core dumped)
```

**Comment by dalg24** [comment]
What about `develop`?

**Comment by crtrott** [comment]
Also any idea if it happens with clang 14 and earlier?

**Comment by ajpowelsnl** [comment]
TODO:
- replicate / reproduce on Power architectures (Vortex, Weaver w/ clang-13)
- Test earlier versions of clang (e.g., clang-13) & then w/ clang-15rc-1 (need to install)

**Comment by scottbiersdorff** [comment]
Yes, I can reproduce the seg. fault with the 'develop' branch. I don't have an older version of Clang available. Also, note that you may need to run it several times before hitting the race condition...

**Comment by PhilMiller** [comment]
See #2582 and #4206. This test has had intermittent failures for years, especially on architectures with weaker memory orderings than x86

**Comment by ajpowelsnl** [comment]
I now have a build of clang:

` ./clang++ --version
clang version 16.0.0 (https://github.com/llvm/llvm-project.git 42d48d09666279bdd05d70ff7c353466ae79711a)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
`

**Comment by ajpowelsnl** [comment]
I can reproduce the seg fault error w/ clang-16 on Power9 architecture.

**Kokkos `master` and `develop`:**
```
 %  OMP_PROC_BIND=TRUE OMP_NUM_THREADS=16 ./core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_color=yes --gtest_filter=openmp.task_fib_single
Note: Google Test filter = openmp.task_fib_single
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from openmp
[ RUN      ] openmp.task_fib_single
Segmentation fault (core dumped)
```
We will dig a bit deeper to figure out what's going on.

**Comment by ajpowelsnl** [comment]
> Do you see the same issue with the `develop` branch?

Yes

**Comment by dalg24** [comment]
@scottbiersdorff can you confirm that #5530 (already merged in the develop branch) resolves the issue you reported?

**Comment by scottbiersdorff** [comment]
I’m still getting occasional seg. faults with the current dev:

git log
commit d5fcc323490d8eb7dc931ddec45ffbf5c6c21a61 (HEAD -> develop, origin/develop)
Merge: bd9adc669 1a63570f2
Author: Christian Trott ***@***.***>
Date:   Fri Oct 7 09:27:31 2022 -0600

    Merge pull request #5528 from Rombur/trilinos_fix

    Export the flags in KOKKOS_AMDGPU_OPTIONS when using Trilinos

…

Running ‘core/unit_test/KokkosCore_UnitTest_OpenMP --gtest_color=no --gtest_filter=openmp.task_fib_single’ I get:

Thread 9 "KokkosCore_Unit" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x20133e5af930 (LWP 921544)]
0x0000000011162ea0 in Kokkos::Impl::SingleTaskQueue<Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased, Kokkos::MemoryPool<Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > >::pop_ready_task (this=<optimized out>)
    at /home/sbiersdorff/code_examples/kokkos_develop/core/src/../../tpls/desul/include/desul/atomics/Compare_Exchange_GCC.hpp:56
56        (void)__atomic_compare_exchange(dest,
(gdb) bt
#0  0x0000000011162ea0 in Kokkos::Impl::SingleTaskQueue<Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::Impl::TaskQueueTraitsLockBased, Kokkos::MemoryPool<Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace> > >::pop_ready_task (this=<optimized out>)
    at /home/sbiersdorff/code_examples/kokkos_develop/core/src/../../tpls/desul/include/desul/atomics/Compare_Exchange_GCC.hpp:56
#1  0x000000001114c2bc in .omp_outlined._debug__.156 (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, instance=<optimized out>,
    scheduler=..., queue=...) at /home/sbiersdorff/code_examples/kokkos_develop/core/src/OpenMP/Kokkos_OpenMP_Task.hpp:142
#2  .omp_outlined..157(void) const (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, instance=<optimized out>, scheduler=...,
    queue=...) at /home/sbiersdorff/code_examples/kokkos_develop/core/src/OpenMP/Kokkos_OpenMP_Task.hpp:116
#3  0x00002000001cf3f4 in __kmp_invoke_microtask () from /lib64/libomp.so
#4  0x000020000014fac4 in __kmp_invoke_task_func () from /lib64/libomp.so
#5  0x000020000014e49c in __kmp_launch_thread () from /lib64/libomp.so
#6  0x00002000001aa804 in __kmp_launch_worker(void*) () from /lib64/libomp.so
#7  0x00002000000987c8 in start_thread () from /lib64/power9/libpthread.so.0
#8  0x00002000006f01b8 in clone () from /lib64/power9/libc.so.6


  *   Scott

**Comment by ajpowelsnl** [comment]
I will take another crack at it, @scottbiersdorff.  Sorry about that.

**Comment by PhilMiller** [comment]
Removing InDevelop so that we don't think this is fixed and close-able at the next release.

**Comment by ajpowelsnl** [comment]
@crtrott , @scottbiersdorff - do we need to do additional work on this issue? Are we seeing the same seg faults with newer clang versions?
