### ISSUE TITLE
Trilinos compile question CUDA + MPI

### ISSUE THREAD

**Issue by Adrian-Diaz** [kokkos/kokkos#5320]
Greetings, I was trying to compile Trilinos with CUDA and OpenMPI using the following:

export OMPI_CXX=${trilinosdir}/packages/kokkos/bin/nvcc_wrapper

cmake -DCMAKE_BUILD_TYPE=RELEASE
-DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE
-DTPL_ENABLE_MPI=ON
-DCMAKE_CXX_STANDARD:STRING=17
-DTrilinos_ENABLE_Kokkos=ON
-DTPL_ENABLE_CUDA=ON
-DKokkos_ENABLE_CUDA_UVM=OFF
-DTrilinos_ENABLE_OpenMP=OFF
-DTrilinos_ENABLE_Amesos2=ON
-DTrilinos_ENABLE_Belos=ON
-DTrilinos_ENABLE_MueLu=ON
-DTrilinos_ENABLE_ROL=ON
-DTrilinos_ENABLE_Ifpack2=ON
-DTrilinos_ENABLE_Zoltan2=ON
-DMueLu_ENABLE_TESTS=OFF
-DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF
-DCMAKE_INSTALL_PREFIX=.
..

It seems to find the mpicxx wrappers in that case, then I get the following error in the cmake configure:

CMake Error at packages/kokkos/cmake/kokkos_test_cxx_std.cmake:132 (MESSAGE):
Invalid compiler for CUDA. The compiler must be nvcc_wrapper or Clang or
use kokkos_launch_compiler, but compiler ID was GNU
Call Stack (most recent call first):
packages/kokkos/cmake/kokkos_tribits.cmake:239 (INCLUDE)
packages/kokkos/CMakeLists.txt:198 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

I also tried directly setting the MPI_CXX_COMPILER build variable directly and in that case cmake seems to be pointing to the nvcc wrapper:

-- USE_XSDK_DEFAULTS='FALSE'
-- BUILD_SHARED_LIBS='FALSE'
-- CMAKE_BUILD_TYPE='RELEASE'
-- MPI_USE_COMPILER_WRAPPERS='ON'
-- MPI_C_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpicc'
-- Setting CMAKE_C_COMPILER=${MPI_C_COMPILER}
-- CMAKE_C_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpicc'
-- MPI_CXX_COMPILER='/scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/packages/kokkos/bin/nvcc_wrapper'
-- MPI_CXX_COMPILER='/scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/packages/kokkos/bin/nvcc_wrapper'
-- Setting CMAKE_CXX_COMPILER=${MPI_CXX_COMPILER}
-- CMAKE_CXX_COMPILER='/scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/packages/kokkos/bin/nvcc_wrapper'
-- MPI_Fortran_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpif90'
-- Setting CMAKE_Fortran_COMPILER=${MPI_Fortran_COMPILER}
-- CMAKE_Fortran_COMPILER='/projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpif90'
-- MPI_EXEC='/usr/bin/mpiexec'
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /projects/opt/centos8/x86_64/openmpi/3.1.6-gcc_9.3.0/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_C_COMPILER_ID='GNU'
-- CMAKE_C_COMPILER_VERSION='9.3.0'
-- The CXX compiler identification is GNU 9.3.0

but that leads to the same error at the end. Are there any other settings I need? Thanks for any help.

Sincerely,
Adrian Diaz

**Comment by ndellingwood** [comment]
@trilinos/kokkos

@Adrian-Diaz what version of Cuda are you compiling with? nvcc >= 11.0 is needed for c++17 support (unless you're using clang as cuda compiler, though I'm not certain of the status of Trilinos for this type of build).

Also, from the cmake error message, please confirm that you have some version of Cuda available at time of configuration to compile with (e.g. `module list` should show a cuda module if you are on a system with module support, `nvcc --version` should tell you the compiler version...)

For Cuda builds in general, please try adding the following cmake options to your configure line as well (not sure if they're set automagically by `TPL_ENABLE_CUDA=ON`):

```
-DKokkos_ENABLE_CUDA=ON
-DKokkos_ENABLE_CUDA_LAMBDA=ON
```

**Comment by ndellingwood** [comment]
@Adrian-Diaz I confirmed the configuration below completes for me on a system with cuda/11.1, gcc/9.2.0 and openmpi/4.0.5 with SHA trilinos/Trilinos@35b4d4d70f930fee3412063a904ea659b366d824.
The config is from your configuration (rearranged a bit) and I added the configure lines I mentioned above, and had to add some explicit path info for my blas+lapack install on the system I used.

```bash
export OMPI_CXX=$TRILINOS_DIR/packages/kokkos/bin/nvcc_wrapper

cmake \
 -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_STANDARD:STRING=17 \
 -DTPL_ENABLE_MPI=ON -DTPL_ENABLE_CUDA=ON \
 -DTPL_ENABLE_BLAS:BOOL=ON -DTPL_ENABLE_LAPACK:BOOL=ON  -DTPL_BLAS_LIBRARIES="/usr/lib64/libblas.so.3" -DTPL_LAPACK_LIBRARIES="/usr/lib64/liblapack.so.3" \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF -DTrilinos_ENABLE_TESTS=OFF -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE -DTrilinos_ENABLE_OpenMP=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
  -DKokkos_ARCH_VOLTA70=ON \
  -DKokkos_ENABLE_OPENMP=ON \
  -DKokkos_ENABLE_CUDA=ON \
  -DKokkos_ENABLE_CUDA_UVM=OFF \
  -DKokkos_ENABLE_CUDA_LAMBDA=ON \
 -DTrilinos_ENABLE_Amesos2=ON \
 -DTrilinos_ENABLE_Belos=ON \
 -DTrilinos_ENABLE_MueLu=ON \
  -DMueLu_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ROL=ON \
 -DTrilinos_ENABLE_Ifpack2=ON \
 -DTrilinos_ENABLE_Zoltan2=ON \
$TRILINOS_DIR
```

I specified the GPU arch in this case for illustration purpose (` -DKokkos_ARCH_VOLTA70=ON`); if you are on a compute node with the GPU present this should be autodetected, but if you are on a login node or run into issue for some reason then this should be specified.

Note you may run into runtime issues as there seem to be some issues with Cuda+OpenMP builds with Tpetra (at least exhibited with unit tests): https://github.com/trilinos/Trilinos/issues/10569

Hopefully this helps

**Comment by ndellingwood** [comment]
I ran into compilation errors with the configure above:
```

```

This hadn't occurred for me a couple weeks ago with an older sha of Trilinos (though different system and different toolchain). I'll open an issue in the Trilinos repo and cross-reference this issue[  6%] Building CXX object packages/teuchos/parser/src/CMakeFiles/teuchosparser.dir/Teuchos_make_lalr1_parser.cpp.o
cd /ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/teuchos/parser/src && /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.5/bin/mpicxx -DTEUCHOSPARSER_LIB_EXPORTS_MODE -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17 -I/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/teuchos/core/src -I/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/core/src -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/kokkos/core/src -I/ascldap/users/ndellin/Trilinos-dev/packages/kokkos/core/src -I/ascldap/users/ndellin/Trilinos-dev/Build/Cuda110Cpp17/packages/kokkos -pedantic -Wall -Wno-long-long -Wwrite-strings -Wshadow -Woverloaded-virtual    -Xcompiler -fopenmp -expt-extended-lambda -Wext-lambda-captures-this -arch=sm_70  -O3 -DNDEBUG -std=c++17 -o CMakeFiles/teuchosparser.dir/Teuchos_make_lalr1_parser.cpp.o -c /ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp
/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp(50): error: more than one instance of overloaded function "Teuchos::size" matches the argument list:
            function template "auto std::size(const _Container &)->decltype((<expression>))"
            function template "int Teuchos::size(const std::vector<T, std::allocator<T>> &)"
            argument types are: (const Teuchos::Grammar::Productions)

/ascldap/users/ndellin/Trilinos-dev/packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp(52): error: more than one instance of overloaded function "Teuchos::size" matches the argument list:
            function template "auto std::size(const _Container &)->decltype((<expression>))"
            function template "int Teuchos::size(const std::vector<T, std::allocator<T>> &)"
            argument types are: (const Teuchos::Grammar::RHS)
...

**Comment by Adrian-Diaz** [comment]
The system is showing Cuda 11.4 when I print the version for the module; also using gcc/9.3 and openmpi 3.1.6. I added -DKokkos_ENABLE_CUDA=ON and
-DKokkos_ENABLE_CUDA_LAMBDA=ON to cmake and got the following error instead:

CMake Error at packages/kokkos/cmake/kokkos_arch.cmake:626 (CONFIGURE_FILE):
  CONFIGURE_FILE Problem configuring file
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_tribits.cmake:240 (INCLUDE)
  packages/kokkos/CMakeLists.txt:198 (KOKKOS_SETUP_BUILD_ENVIRONMENT)


CMake Error at /scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/build/packages/kokkos/cmake/compile_tests/CUDAComputeCapabilityWorkdir/CMakeFiles/CMakeTmp/CMakeLists.txt:19 (add_executable):
  Cannot find source file:

    /scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/build/compile_tests/cuda_compute_capability.cu


CMake Error at /scratch/users/adiaz17/Fierro_GPU_test/Fierro/Trilinos/build/packages/kokkos/cmake/compile_tests/CUDAComputeCapabilityWorkdir/CMakeFiles/CMakeTmp/CMakeLists.txt:19 (add_executable):
  No SOURCES given to target: cmTC_5bbf6


CMake Error at packages/kokkos/cmake/kokkos_arch.cmake:632 (TRY_RUN):
  Failed to generate test project build system.
Call Stack (most recent call first):
  packages/kokkos/cmake/kokkos_tribits.cmake:240 (INCLUDE)
  packages/kokkos/CMakeLists.txt:198 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

**Comment by dalg24** [comment]
Please try applying the changes from #5321

**Comment by ndellingwood** [comment]
@Adrian-Diaz it might be that when you hopped on the compute node your env variables didn't carry over. Try defining OMPI_CXX again as from your OP (and check that $trilinosdir is defined as well)

`export OMPI_CXX=${trilinosdir}/packages/kokkos/bin/nvcc_wrapper`

**Comment by ndellingwood** [comment]
@Adrian-Diaz when you make it farther through compilation but if you run into issues like here https://github.com/kokkos/kokkos/issues/5320#issuecomment-1208901023, there is a PR open with Trilinos with a fix that I confirmed worked for my build https://github.com/trilinos/Trilinos/pull/10848

**Comment by Adrian-Diaz** [comment]
I blew up the build folder and started from scratch when I moved to the compute node.

**Comment by ajpowelsnl** [comment]
Morning @Adrian-Diaz -- did the Trilinos PR (#10848) resolve your issue?

**Comment by Adrian-Diaz** [comment]
I didn't seem to need the PR; I guess since I have CUDA on and OpenMP off. It compiles fine now using some of the configure script options from https://github.com/trilinos/Trilinos/issues/10843 for CUDA and Kokkos.
