### ISSUE TITLE
Compile fail with CMake, c++17, CUDA and OpenMP

### ISSUE THREAD

**Issue by aaronyicongfu** [kokkos/kokkos#5329]
Got the this (seemingly random) error
```
/usr/include/c++/9/bits/stl_pair.h(442): error: argument list for class template "std::pair" is missing
/usr/include/c++/9/bits/stl_pair.h(442): error: expected a ")"
/usr/include/c++/9/bits/stl_pair.h(442): error: template parameter "_T1" may not be redeclared in this scope
/usr/include/c++/9/bits/stl_pair.h(442): error: expected a ";"
```

when compile an empty `main.cpp` with Kokkos in-tree.

**Full details:**

The project folder has the following structure: 
```
.
├── CMakeLists.txt
├── kokkos
└── main.cpp
```

`CMakeLists.txt` is:
```
# Specify cmake version needed
cmake_minimum_required(VERSION 3.22 FATAL_ERROR)

# Set project name, language and c++ std
project(test LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Require OpenMP
find_package(OpenMP REQUIRED)

# Build kokkos in-place
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/kokkos)

# Build my target
add_executable(main main.cpp)
target_link_libraries(main OpenMP::OpenMP_CXX kokkos)
```

`main.cpp` is:
```
int main() {}
```

The command used to compile the project is:
`mkdir build && cd build && cmake .. -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON && make main -j 16`

Version of kokkos used is 3.6.01.

**Comment by masterleinad** [comment]
Do you also see this problem with the `develop` or `release-candidate-3.7.00` branch?

**Comment by aaronyicongfu** [comment]
@masterleinad Hi, yes, I got same error for both branches.

**Comment by masterleinad** [comment]
I could reproduce and this is independent of `Kokkos`:
```
$ nvcc -arch=sm_70 -ccbin /usr/bin/g++-8 -Xcompiler -std=c++17 -x cu /home/6da/reproducer/main.cpp -c -o CMakeFiles/main.dir/main.cpp.o

/usr/include/c++/8/bits/stl_pair.h(79): error: inline specifier allowed on function declarations only
/usr/include/c++/8/bits/stl_pair.h(442): error: argument list for class template "std::pair" is missing
/usr/include/c++/8/bits/stl_pair.h(442): error: expected a ")"
/usr/include/c++/8/bits/stl_pair.h(442): error: template parameter "_T1" may not be redeclared in this scope
/usr/include/c++/8/bits/stl_pair.h(442): error: expected a ";"
5 errors detected in the compilation of "/tmp/reproducer/main.cpp".
```

**Comment by aaronyicongfu** [comment]
🤔hmmm, so this could be a bug from nvcc then?

**Comment by masterleinad** [comment]
> thinkinghmmm, so this could be a bug from nvcc then?

Somehow, we don't pass `-std=c++17` to `nvcc` directly and that's the problem, also see https://forums.developer.nvidia.com/t/ubuntu-20-04-gcc-9-3-cuda-toolkit-11-3-not-a-supported-combination/193486/10.

**Comment by masterleinad** [comment]
```
# Specify cmake version needed
cmake_minimum_required(VERSION 3.20 FATAL_ERROR)

# Set project name, language and c++ std
project(test LANGUAGES CXX)
#set(CMAKE_CXX_STANDARD 17)
#set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Require OpenMP
find_package(OpenMP REQUIRED)

# Build kokkos in-place
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/kokkos)

# Build my target
add_executable(main main.cpp)
target_link_libraries(main kokkos)
target_link_libraries(main OpenMP::OpenMP_CXX)
```
seems to work, though, i.e., calling `taget_link_libraries` separately for the two targets.

**Comment by aaronyicongfu** [comment]
> ```
> # Specify cmake version needed
> cmake_minimum_required(VERSION 3.20 FATAL_ERROR)
> 
> # Set project name, language and c++ std
> project(test LANGUAGES CXX)
> #set(CMAKE_CXX_STANDARD 17)
> #set(CMAKE_CXX_STANDARD_REQUIRED ON)
> 
> # Require OpenMP
> find_package(OpenMP REQUIRED)
> 
> # Build kokkos in-place
> add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/kokkos)
> 
> # Build my target
> add_executable(main main.cpp)
> target_link_libraries(main kokkos)
> target_link_libraries(main OpenMP::OpenMP_CXX)
> ```
> 
> 
>      
>   
> 
> seems to work, though, i.e., calling `taget_link_libraries` separately for the two targets.

Yeah, I think somehow the order matters here, so
```
target_link_libraries(main kokkos OpenMP::OpenMP_CXX)
```
can compile, but
```
target_link_libraries(main OpenMP::OpenMP_CXX kokkos)
```
can't.

Anyway, I found a workaround for my application so not a problem on my end for now. Just to bring this up in case it could be useful to the community. Thanks again for your reply!

**Comment by ajpowelsnl** [comment]
@nmm0 - would you please have a look and see if you can identify the underlying problem?
