### ISSUE TITLE
failing Albany clang nightly build due to missing header

### ISSUE THREAD

**Issue by ikalash** [kokkos/kokkos#5359]
This is a duplicate of the following Trilinos issue: https://github.com/trilinos/Trilinos/issues/10868 .

The nightly clang CEE build for Albany is failing with an error about a missing Kokkos header:

[Albany/src/Albany_KokkosTypes.hpp:19](https://blob/master/Albany/src/Albany_KokkosTypes.hpp#L19):10: fatal error: 'Kokkos_StaticCrsGraph.hpp' file not found
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=37594

Curiously, it doesn't happen with any of the other builds, which use different compilers. Did this header get renamed / removed?

**Comment by masterleinad** [comment]
Please follow the template for a bug report (also note that not all of us can access Sandia internal pages/servers):
> **Describe the bug**
>Please provide a concise, clear description of the bug, as well as any available error logs.
**Please also include the following items to support reproducing the bug**
>1. compilers (with versions)
>2. Kokkos release or commit used (i.e., the sha1 number)
>3. platform and backend
>4. cmake configure command
>5. output from cmake command
>6. code needed to reproduce the bug
>7. command line needed to reproduce the bug
>7. please also attach the `KokkosCore_config.h` header file (generated during the build);
>**Any additional info**
Please provide any additional context about the issue here.

**Comment by dalg24** [comment]
Since when is it failing?
Only thing that comes to mind is #5345

**Comment by ajpowelsnl** [comment]
@ikalash - if you provide configure and build details, I can try to reproduce the failure.

**Comment by ikalash** [comment]
In looking at this in more detail, it appears since I originally opened this issue on the Trilinos github, it has evolved into a different error that I suspect is due to recent changes to the Trilinos build system.  Sorry about the spam issue.  I will close this issue, and open a separate one in Trilinos once I've triaged the problem a bit.
