### ISSUE TITLE
compiling on Mac, lots of errors out of kokkos_core.hpp

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#538]
Odd issue I'm getting lots of errors for the code

#include <Kokkos_Core.hpp>

Here is what I see

Clearly there must be a simple issue, but not sure how to move forward

cd /Users/mbetten/Trilinos/test-intrepid/build/src && /usr/local/bin/mpicxx    -I/Users/mbetten/Trilinos/test-intrepid/build/src -I/Users/mbetten/installs/refactor-for-panzer/clang-DEBUG/include -I/usr/local/include  -DPARALLEL_IO    -o CMakeFiles/miniPIC.exe.dir/main.cpp.o -c /Users/mbetten/Trilinos/test-intrepid/src/main.cpp
In file included from /Users/mbetten/Trilinos/test-intrepid/src/main.cpp:3:
In file included from /Users/mbetten/installs/refactor-for-panzer/clang-DEBUG/include/Kokkos_Core.hpp:50:
In file included from /Users/mbetten/installs/refactor-for-panzer/clang-DEBUG/include/Kokkos_Core_fwd.hpp:52:
/Users/mbetten/installs/refactor-for-panzer/clang-DEBUG/include/impl/Kokkos_Utilities.hpp:59:1: error: unknown type name 'constexpr'
constexpr
^
/Users/mbetten/installs/refactor-for-panzer/clang-DEBUG/include/impl/Kokkos_Utilities.hpp:58:1: error: 'inline' can only appear on functions
KOKKOS_INLINE_FUNCTION
^
/Users/mbetten/installs/refactor-for-panzer/clang-DEBUG/include/Kokkos_Macros.hpp:389:33: note: expanded from macro 'KOKKOS_INLINE_FUNCTION'
#define KOKKOS_INLINE_FUNCTION  inline

**Comment by bathmatt** [comment]
Whoops, comment type error in cmake file.. Sorry!!

**Comment by crtrott** [comment]
Whats the compiler?

**Comment by kddevin** [comment]
Hi @bathmatt.  What was the simple fix?  I am seeing the same compiler errors on my mac with Apple LLVM version 8.0.0 (clang-800.0.42.1)
I am including Kokkos indirectly from Tpetra_Multivector.hpp.

In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_Multivector.hpp:1:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_MultiVector_decl.hpp:54:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_DistObject.hpp:1:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_DistObject_decl.hpp:53:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_Map.hpp:1:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_Map_decl.hpp:49:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Tpetra_ConfigDefs.hpp:46:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Kokkos_DefaultNode.hpp:48:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:5:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/KokkosCompat_View.hpp:58:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Kokkos_Core.hpp:50:
In file included from /Users/kddevin/code/Trilinos/Obj_tpetra/include/Kokkos_Core_fwd.hpp:52:
/Users/kddevin/code/Trilinos/Obj_tpetra/include/impl/Kokkos_Utilities.hpp:59:1: error: unknown type name 'constexpr'
constexpr
^
/Users/kddevin/code/Trilinos/Obj_tpetra/include/impl/Kokkos_Utilities.hpp:58:1: error: 'inline' can only appear on functions
KOKKOS_INLINE_FUNCTION
^
/Users/kddevin/code/Trilinos/Obj_tpetra/include/Kokkos_Macros.hpp:400:33: note: expanded from macro 'KOKKOS_INLINE_FUNCTION'
#define KOKKOS_INLINE_FUNCTION  inline
                                ^

**Comment by kddevin** [comment]
@bathmatt Ah, never mind.  I wasn't getting the right compiler flags from Trilinos' Makefile.export.  Sorry for the noise.

**Comment by hcedwar** [comment]
Appears that you don't have c++11 enabled

Sent from my iPad

On Feb 7, 2017, at 3:48 PM, K Devine <notifications@github.com<mailto:notifications@github.com>> wrote:


@bathmatt<https://github.com/bathmatt> Ah, never mind. I wasn't getting the right compiler flags from Trilinos' Makefile.export. Sorry for the noise.

-
