### ISSUE TITLE
Behavior of calling tagged join

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#5380]
**Describe the bug**

Check what worked in 3.6, and possibly deprecate fallback to untagged `init()/join()`.

**Please also include the following items to support reproducing the bug**
1. compilers (with versions)
2. Kokkos release or commit used (i.e., the sha1 number)
3. platform and backend
4. cmake configure command
5. output from cmake command
6. code needed to reproduce the bug
7. command line needed to reproduce the bug
7. please also attach the `KokkosCore_config.h` header file (generated during the build);
**Any additional info**
Please provide any additional context about the issue here.

**Comment by crtrott** [comment]
We checked, and the behavior has been consistent for years, so there is no issue.
