### ISSUE TITLE
Unmanaged View should be Debug time checked if it becomes dangling

### ISSUE THREAD

**Issue by certik** [kokkos/kokkos#54]
After discussion with @crtrott, the unmanaged View should be checked in Debug build, so that instead of segfaulting or undefined behavior (if it becomes dangling) it should raise a nice exception. This shouldn't be difficult to implement.

Similar to the spirit of `Teuchos::RCP` and `Teuchos::Ptr`, where `Ptr` also raises a nice exception if it becomes dangling in Debug mode, but in Release mode it is as fast as a raw pointer.

**Comment by crtrott** [comment]
Pretty complicated goes to backlog for now.

**Comment by mhoemmen** [comment]
It's trickier to implement this than you might think.  For example, you have to distinguish between an unmanaged View created with a raw pointer, vs. an unmanaged View created from a managed View via assignment.  Even Teuchos::ArrayView debug tracking had issues with this before.

**Comment by certik** [comment]
I thought @bartlettroscoe fixed that for `ArrayView`. Either way, it's not a big deal if it is hard to implement, I thought it would be easy, but if it is not, then that's fine.

**Comment by bartlettroscoe** [comment]
> It's trickier to implement this than you might think. For example, you have to distinguish between an unmanaged View created with a raw pointer, vs. an unmanaged View created from a managed View via assignment. Even Teuchos::ArrayView debug tracking had issues with this before.

If you get a `Teuchos::ArrayView` from an owning `Teuchos::ArrayRcp` or `Teuchos::Array`, then it will catch dangling views.  If it is created from a raw pointer, it can't obviously.  Implementing the infrastructure for the debug-mode checking was not trivial (which is the whole point for the value of the Teuchos MM classes).

**Comment by certik** [comment]
I forgot that Kokkos is not using Teuchos MM, so it would indeed be non-trivial to implement Debug time checking for dangling pointers.

**Comment by mhoemmen** [comment]
The desired behavior is beyond scope of Kokkos as far as I can tell, so I'm closing this.  Please feel free to reopen if you need this.
