### ISSUE TITLE
Kokkos::abort and Kokkos_Core.hpp

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#5403]
Sometimes, the only utility we want to use is `Kokkos::abort`. It seems that right now this requires inclusion of `Kokkos_Core.hpp`, which brings a lot of things. Should there be a way to include a minimal header with just that functionality? I see that there is `Kokkos_Error.hpp` but it is inside `impl` so that's not for users.

**Comment by masterleinad** [comment]
We will define a header for `Kokkos::abort` and `KOKKOS_ASSERT` that can be included on its own.

**Comment by ajpowelsnl** [comment]
@nmm0 - is there anything else that we should discuss about this issue in the Wed. meeting?  I've added it to Kokkos Planning.

**Comment by fnrizzi** [comment]
closing since the corresponding PR was merged
