### ISSUE TITLE
Improve DynRankView debug check

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#541]
The `verify_dynrankview_rank( N , drv )` routine used during debugging (specifically when bounds check is enabled) currently checks that the rank of the parenthesis operator ( the 'N' value above ) is greater than or equal to the dynamic rank, and aborts otherwise. This check, rather than equality, was chosen to allow for extra zero arguments to be passed to the DynRankView, which was needed for Intrepid2 refactoring and generic functors for various tensor/contraction operations if I remember correctly. 

With FAD types that are not created through the Sacado factory this can result in a situation where the results of this check pass but would be expected to fail. 
@rppawlo @kyungjoo-kim @etphipp

**Comment by etphipp** [comment]
Would it be reasonable to check the extra indices are in fact zero?  I think that would catch the errors Roger was running into.

**Comment by ndellingwood** [comment]
I added checks like @etphipp, tested on my laptop. Will run more rigorous tests and after passing will issue a pull request.
