### ISSUE TITLE
Nightly build errors, intel/19.5: Kokkos_NestedSort.hpp(92): error #869: parameter "valueView" was never referenced

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5420]
**Describe the bug**
Following merges on 08/31/2022 the compilation errors with intel/19 began:
```
/home/jenkins/blake-new/workspace/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/kokkos/algorithms/unit_tests/../src/Kokkos_NestedSort.hpp(92): error #869: parameter "valueView" was never referenced
                                               const ValueViewType& valueView,
```

New commits that came in with the failing build:

Team- and thread-level sort, sort_by_key ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#1f946f9af1eaf4cee911ba6be339144bd9c948a1) / [githubweb](https://github.com/kokkos/kokkos/commit/1f946f9af1eaf4cee911ba6be339144bd9c948a1))
    Small updates to nested sort ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#91531a5e8b152d4c01b101a1156aae334ad3feaa) / [githubweb](https://github.com/kokkos/kokkos/commit/91531a5e8b152d4c01b101a1156aae334ad3feaa))
    Refactor nested-parallelism sort to need 1 impl only ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#a86eb7ff4e1e80aee08130e67880201546b2d55b) / [githubweb](https://github.com/kokkos/kokkos/commit/a86eb7ff4e1e80aee08130e67880201546b2d55b))
    sort_thread tests: Fix OOB access on idle threads ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#6ae55a9a537d30ced943a7d391b71388681d8e84) / [githubweb](https://github.com/kokkos/kokkos/commit/6ae55a9a537d30ced943a7d391b71388681d8e84))
    Use KOKKOS_FUNCTION in place of INLINE, FORCEINLINE ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#294b7f66e16491dc373a4c71ce27ead20f78e561) / [githubweb](https://github.com/kokkos/kokkos/commit/294b7f66e16491dc373a4c71ce27ead20f78e561))
    Move team/thread sort to Experimental::, new header ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#6ea1250e42c948d61f47eae72e6756034dbb0399) / [githubweb](https://github.com/kokkos/kokkos/commit/6ea1250e42c948d61f47eae72e6756034dbb0399))
    Fix Sort/NestedSort includes ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#745cfd8f743eb75b601fe7b2f073f9728380d3a1) / [githubweb](https://github.com/kokkos/kokkos/commit/745cfd8f743eb75b601fe7b2f073f9728380d3a1))
    Nested bitonic sort: small changes ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#cb2eaff49f5da70a9b4a4692acdd809833d623d6) / [githubweb](https://github.com/kokkos/kokkos/commit/cb2eaff49f5da70a9b4a4692acdd809833d623d6))
    Pass tag by value ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#9d67e0b542805c46723bb14ccafb9fadcb826818) / [githubweb](https://github.com/kokkos/kokkos/commit/9d67e0b542805c46723bb14ccafb9fadcb826818))
    NestedSort test cleanup ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#67bb790c5f95745041ea85e51353668fb86fe543) / [githubweb](https://github.com/kokkos/kokkos/commit/67bb790c5f95745041ea85e51353668fb86fe543))
    Nested sort test: add error messages ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#7994904096869c415bdf656062461dc80d7faa70) / [githubweb](https://github.com/kokkos/kokkos/commit/7994904096869c415bdf656062461dc80d7faa70))
    Move nested sort tests into a separate file ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#35faf0967b42ae8e1fe659b5ff67cc65499d354e) / [githubweb](https://github.com/kokkos/kokkos/commit/35faf0967b42ae8e1fe659b5ff67cc65499d354e))
    Move sort test includes, revert whitespace changes ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#0cc7917e12be513c259e5133d0d033e3d243a396) / [githubweb](https://github.com/kokkos/kokkos/commit/0cc7917e12be513c259e5133d0d033e3d243a396))
    Add is_device_v helper variable template ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#d1f61dce5530c1f9a8daee700397d7ca6560c55c) / [githubweb](https://github.com/kokkos/kokkos/commit/d1f61dce5530c1f9a8daee700397d7ca6560c55c))
    Define comparison operators == and != for all execution spaces ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#bb94f0eed88130cec0f42b4b09f914bfd27a3cd3) / [githubweb](https://github.com/kokkos/kokkos/commit/bb94f0eed88130cec0f42b4b09f914bfd27a3cd3))
    Take advantage of C++17 when checking that execution spaces meet requirements ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#2cb40e17ccdb232b31368eef3fc90fdfe8f9da19) / [githubweb](https://github.com/kokkos/kokkos/commit/2cb40e17ccdb232b31368eef3fc90fdfe8f9da19))
    Check that execution spaces meet the requirements of regular types ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#bcbc0861fd0ca6ace5399c92e3783f9bca87470a) / [githubweb](https://github.com/kokkos/kokkos/commit/bcbc0861fd0ca6ace5399c92e3783f9bca87470a))
    Provide equality comparison operators for HPX as well ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#c39b4a3da8835fc6187cb22479cbf3d6a0ca8084) / [githubweb](https://github.com/kokkos/kokkos/commit/c39b4a3da8835fc6187cb22479cbf3d6a0ca8084))
    #5385: Add fences to all non-exec-space sorting routines other than BinSort constructors ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#46892083557e76f995d42519e5caeefe2cf52ed0) / [githubweb](https://github.com/kokkos/kokkos/commit/46892083557e76f995d42519e5caeefe2cf52ed0))
    Introduce dependent_false_v<T> so obscure code and clarifying comments don't need to be repeated ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#4f8e0ea256eecd6a35e8207ea052ab938890dd9d) / [githubweb](https://github.com/kokkos/kokkos/commit/4f8e0ea256eecd6a35e8207ea052ab938890dd9d))
    #5194: Fail compilation if a volatile-qualified join() would be called ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#d7baa9f55b5c728282f0dad74cc964f6c8624ed6) / [githubweb](https://github.com/kokkos/kokkos/commit/d7baa9f55b5c728282f0dad74cc964f6c8624ed6))
    Add unit test that volatile-qualified join() is called when we expect it to be ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#4efb43fe68e19615e41fa238a2167f3c2e022b79) / [githubweb](https://github.com/kokkos/kokkos/commit/4efb43fe68e19615e41fa238a2167f3c2e022b79))
    Format ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#f08c241739c56944d2ebebe596b43901b3f79596) / [githubweb](https://github.com/kokkos/kokkos/commit/f08c241739c56944d2ebebe596b43901b3f79596))
    parallel_scan with View as result type (#5146) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/479/changes#6c54349dde8177a9623f24c875b99709e73941c8) / [githubweb](https://github.com/kokkos/kokkos/commit/6c54349dde8177a9623f24c875b99709e73941c8))

**Please also include the following items to support reproducing the bug**
**Reproducer**:
```bash
module load cmake/3.19.3 intel/compilers/19.5.281

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial --arch=SKX --compiler=icpc --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH  --no-examples   --with-options=enable_large_mem_tests --debug
```

**Comment by masterleinad** [comment]
Fixed in #5421 (`develop` only).
