### ISSUE TITLE
CHANGELOG: 4.0

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#5439]
This is the changelog for the upcoming Release 4.0

### Features:
- Allow value types without default constructor in `Kokkos::View` with `Kokkos::WithoutInitializing` https://github.com/kokkos/kokkos/pull/5307
- `parallel_scan` with `View` as result type. https://github.com/kokkos/kokkos/pull/5146
- Introduced `SharedSpace`, an alias for a `MemorySpace` that is accessible by every `ExecutionSpace`. The memory is moved and then accessed locally. https://github.com/kokkos/kokkos/pull/5289
- Introduced `SharedHostPinnedSpace`, an alias for a `MemorySpace` that is accessible by every `ExecutionSpace`. The memory is pinned to the host and accessed via zero-copy access. https://github.com/kokkos/kokkos/pull/5405
- Groundwork for `MDSpan` integration. https://github.com/kokkos/kokkos/pull/4973 and https://github.com/kokkos/kokkos/pull/5304
- Introduced MD version of hierarchical parallelism: `TeamThreadMDRange`, `ThreadVectorMDRange` and `TeamVectorMDRange`. https://github.com/kokkos/kokkos/pull/5238

#### CUDA:
- Allow CUDA PTX forward compatibility #3612 #5536 #5527
- Add support for NVIDIA Hopper GPU architecture #5538
- Don't rely on synchronization behavior of default stream in CUDA and HIP #5391
- Improve CUDA cache config settings #5706

#### HIP:
 - Move `HIP`, `HIPSpace`, `HIPHostPinnedSpace`, and `HIPManagedSpace` out of the `Experimental` namespace #5383
 - Don't rely on synchronization behavior of default stream in CUDA and HIP #5391 
 - Export AMD architecture flag when using Trilinos #5528
 - Fix linking error (see [OLCF issue](https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html#olcfdev-1167-kokkos-build-failures-with-prgenv-amd)) when using `amdclang`: https://github.com/kokkos/kokkos/pull/5539
 - Remove support for MI25 and added support for Navi 1030 #5522
 - Fix race condition when using `HSA_XNACK=1`  #5755 
 - Add parameter to force using GlobalMemory launch mechanism. This can be used when encountering compiler bugs with ROCm 5.3 and 5.4  #5796 

#### SYCL:
- Delegate choice of workgroup size for `parallel_reduce` with `RangePolicy` to the compiler. https://github.com/kokkos/kokkos/pull/5227
- SYCL `RangePolicy`: manually specify workgroup size through chunk size #4875 

#### OpenMPTarget:
- Select the right device #5492

#### OpenMP:
 - Add `partition_space` #5105

### General Enhancements
- Implement `OffsetView` constructor taking `pair`s and `ViewCtorProp` #5303 
- Promote math constants to `Kokkos::numbers` namespace #5434
- Add overloads of `hypot` math function that take 3 arguments #5341
- Add `fma` fused multiply-add math function #5428
- Views using `MemoryTraits::Atomic` don't need `volatile` overloads for the value type anymore. #5455
- Added `is_team_handle` trait https://github.com/kokkos/kokkos/pull/5375
- Refactor desul atomics to support compiling CUDA with NVC++ #5431 #5497 #5498
- Support finding `libquadmath` with native compiler support #5286 
- Add architecture flags for MSVC #5673
- SIMD backend for ARM NEON #5829

### Build System Changes 
- Let CMake determine OpenMP flags. https://github.com/kokkos/kokkos/pull/4105
- Update minimum compiler versions. https://github.com/kokkos/kokkos/pull/5323
- Makefile and CMake support for C++23 #5283 
- Do not add `-cuda` to the link line with NVHPC compiler when the CUDA backend is not actually enabled #5485 
- Only add `-latomic` in generated GNU makefiles when OpenMPTarget backend is enabled #5501 #5537 (3.7 patch release candidate)
- `Kokkos_ENABLE_CUDA_LAMBDA` now `ON` by default with NVCC #5580
- Fix enabling of relocatable device code when using CUDA as CMake language #5564
- Fix cmake configuration with CUDA 12 #5691

### Incompatibilities (i.e. breaking changes)
- ***Require C++17***  #5277
- Turn setting `Kokkos_CXX_STANDARD` into an error #5293 
- Remove all deprecations in Kokkos 3 #5297
- Remove `KOKKOS_COMPILER_CUDA_VERSION` #5430 
- Drop `reciprocal_overflow_threshold` numeric trait #5326
- Move `reduction_identity` out of `<Kokkos_NumericTraits.hpp>` into a new `<Kokkos_ReductionIdentity.hpp>` header #5450
- Reduction and scan routines will report an error if the `join()` operator they would use takes `volatile`-qualified parameters #5409
- `ENABLE_CUDA_UVM` is dropped in favor of using `SharedSpace` as `MemorySpace` explicitly #5608  
-  Remove Kokkos_ENABLE_CUDA_LDG_INTRINSIC option #5623
- Don't rely on synchronization behavior of default stream in CUDA and HIP - this potentially will break unintended implicit synchronization with other libraries such as MPI #5391 
- Make ExecutionSpace::concurrency() a non-static member function #5655 and related PRs

### Deprecations
- Guard against non-public header inclusion [\#5178](https://github.com/kokkos/kokkos/pull/5178)
- Raise deprecation warnings if non empty WorkTag class is used [\#5230](https://github.com/kokkos/kokkos/pull/5230)
- Deprecate `parallel_*` overloads taking the label as trailing argument [\#5141](https://github.com/kokkos/kokkos/pull/5141)
- Deprecate nested types in functional [\#5185](https://github.com/kokkos/kokkos/pull/5185)
- Deprecate `InitArguments` struct and replace it with `InitializationSettings` [\#5135](https://github.com/kokkos/kokkos/pull/5135)
- Deprecate `finalize_all()` [\#5134](https://github.com/kokkos/kokkos/pull/5134)
- Deprecate command line arguments (other than `--help`) that are not prefixed with `kokkos-*` [\#5120](https://github.com/kokkos/kokkos/pull/5120)
- Deprecate `--[kokkos-]numa` cmdline arg and `KOKKOS_NUMA` env var [\#5117](https://github.com/kokkos/kokkos/pull/5117)
- Deprecate `--[kokkos-]threads` command line argument in favor of `--[kokkos-]num-threads` [\#5111](https://github.com/kokkos/kokkos/pull/5111)
- Deprecate `Kokkos::is_reducer_type` [\#4957](https://github.com/kokkos/kokkos/pull/4957)
- Deprecate `OffsetView` constructors taking `index_list_type` [\#4810](https://github.com/kokkos/kokkos/pull/4810)
- Deprecate overloads of `Kokkos::sort` taking a parameter `bool always_use_kokkos_sort` [\#5382](https://github.com/kokkos/kokkos/issues/5382)
- Deprecate `CudaUVMSpace::available()` which always returned `true` [\#5614](https://github.com/kokkos/kokkos/pull/5614)
- Deprecate `volatile`-qualified members from `Kokkos::pair` and `Kokkos::complex` [\#5412](https://github.com/kokkos/kokkos/pull/5412)
- Deprecate `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` macros #5824 (oversight in 3.2)

### Bug Fixes
- Avoid allocating memory for `UniqueToken` https://github.com/kokkos/kokkos/pull/5300 
- Fix `pragma ivdep` in `Kokkos_OpenMP_Parallel.hpp` https://github.com/kokkos/kokkos/pull/5356 
- Fix configuring with Threads support when rerunning CMake #5486 
- Fix View assignment between `LayoutLeft` and `LayoutRight` with static extents #5535 (3.7 patch release candidate)
- Add `fence()` calls to sorting routine overloads that don't take an execution space parameter #5389
- `ClockTic` changed to 64 bit to fix overflow on Power #5577 (incl. in 3.7.01 patch release)
- Fix incorrect offset in CUDA and HIP `parallel_scan` for < 4 byte types #5555 (3.7 patch release candidate)
- Fix incorrect alignment behavior of scratch allocations in some corner cases (e.g. very small allocations) #5687 (3.7 patch release candidate)
- Add missing `ReductionIdentity<char>` specialization #5798
- Don't install standard algorithms headers multiple times #5670 
- Fix max scratch size calculation for level 0 scratch in CUDA and HIP $5718

**Comment by nmm0** [comment]
Would it make sense to have incompatibilities/breaking changes to the top?

**Comment by PhilMiller** [comment]
#5382 was also addressed in 3.7.00 in #5384, but was not listed in the changelog for that release. Should we modify that changelog to note it? Just stick it in the 3.7.01 changelog?

@ajpowelsnl I presume it will make it into the wiki's deprecation page regardless, since it's tagged with `KOKKOS_DEPRECATED_CODE_3` in the source
