### ISSUE TITLE
MPI processes sharing multiple GPUs

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#544]
Hello Kokkos Team,

I'm dealing with an issue I'm sure you've handled before:  our cluster nodes have 2 GPUs each, and we'd like to run multiple MPI ranks on each node, with several MPI ranks sharing each GPU.

I know one way to do this optimally for MPI+Cuda applications (outlined on Page 414 of [Professional Cuda C Programming](http://www.hds.bme.hu/~fhegedus/C++/Professional%20CUDA%20C%20Programming.pdf)):
Each MPI process picks a GPU based on its local rank, using cudaSetDevice.
Each MPI process uses hwloc to find and pin itself to a CPU near that GPU.
The book says this should be done before calling `MPI_Init`, because a Cuda-aware MPI implementation will create a device context during the call to `MPI_Init`, thus requiring a context switch if a new device is manually selected.  I'm not sure how harmful this is in practice; selecting the device before or after `MPI_Init` may not be a big deal.

I don't know what the usual best practice is with Kokkos.  Can I simply pass "--kokkos-ndevices=2" to `Kokkos::initialize(int& argc, char* argv[])` and expect Kokkos to take care of everything under the hood (ie, query the local MPI rank, pick a device, and pin the MPI process for optimal locality to that device)?
The Kokkos programming guide ("Initialization," page 23, first paragraph) states 
> If you use both MPI and Kokkos, your program should initialize Kokkos right after calling `MPI_Init`.  That way, if MPI sets of process binding masks, Kokkos will get that information and use it for best performance.

This implies that Kokkos itself does NOT attempt to establish process binding. 

Also, I have a general question unrelated to Kokkos:  CPU affinity can be set via A. hwloc calls in code or B. (distribution-dependent) arguments to mpirun.  If both A. and B. are used simultaneously, what happens if they conflict?  Which one "wins"?

Thanks very much for your help,
Michael

**Comment by hcedwar** [comment]
MPI+Cuda: Yes - just call MPI_Init before Kokkos::initialize and use the ndevices argument and all should be well.
Process binding: If you configure and build with hwloc then Kokkos will detect and honor the process binding set by MPI, otherwise Kokkos knows nothing about the process binding.  Note that MPI process binding sometimes requires a launch argument such as bind-to-socket.

**Comment by mcarilli** [comment]
Some final points to alleviate my confusion:  by  "configure and build with hwloc" do you mean that Kokkos must be built with hwloc, by invoking for example `make KOKKOS_DEVICES=Cuda KOKKOS_USE_TPLS=hwloc  HWLOC_PATH=/whatever/`? 

Also, if I configure and build with hwloc, and set the process binding via arguments to mpirun, by "detect and honor" do you mean that Kokkos within each process will automatically select the best-located GPU?

**Comment by crtrott** [comment]
Yes if you enable HWLOC that way, Kokkos will detect the process mask, setup the correct number of threads by default and bind them. Without it it doesn't. When using OpenMP you usually can use the standard OpenMP mechanism for binding (OMP_NUM_THREADS, GOMP_CPU_AFFINITY, KMP_AFFINITY etc.). 

We did not put in correct nearest GPU assignment as of now. If you use MPI and --kokkos-ndevices we simply detect the local rank (at least for MVapich and OpenMPI) and assign GPUs round robin.

Improving this is on our agenda.

**Comment by mcarilli** [comment]
Sounds good.  I will simply use --kokkos-ndevices for now and rely on future improvements.  My data transfers are small relative to the amount of work that must be done on the GPU, so nearest-GPU selection probably won't have a significant effect on my overall application.

Be advised:  As I said before, some of the [literature](https://www.open-mpi.org/community/lists/users/2011/12/17954.php) I have found indicates that it is beneficial to select a GPU BEFORE calling MPI_Init.  Again, I'm not sure how essential this is, and I haven't been able to find a thorough explanation.

**Comment by mcarilli** [comment]
I am having some trouble setting the GPU devices via the `Kokkos::initialize(int& argc, char* argv[])` interface.  I don't have access to the command line arguments at the point where I'm initializing Kokkos (my Kokkos routines are interfaced with a large Fortran application) so I'm synthesizing them as follows:
```c++
    std::stringstream ss;
    ss << "--kokkos-ndevices=" << nDevices;
    int length = ss.str().length();
    char args[length+1];
    for( int i = 0; i < length; i++ )
      args[i] = ss.str().c_str()[i];
    args[length] = '\0';
    char* argv[] = { args, NULL };
    int argc = 1;
    Kokkos::initialize( argc, argv );
```
Admittedly this is rather hacky, but it compiles, and creates "--kokkos-ndevices=whatever" in argv[0].  Based on my reading of `Kokkos::initialize` as it appears in Kokkos_Core.hpp, this should be adequate to set the number of devices.  However, it does not appear to work:  a multi-GPU profile reveals that when initialized this way, my Kokkos code runs on only one GPU, even when nDevices=2.

For now, I have switched to initialization-by-struct:
```c++
    Kokkos::InitArguments args;
    args.device_id = deviceThisRank;
    Kokkos::initialize( args );
```
When I set `deviceThisRank` uniquely for each MPI rank, the profiler now reveals that the Kokkos code for different ranks does run on different GPUs, as desired.  However, since `Kokkos::InitArguments` does not appear to contain an equivalent of `--kokkos-ndevices`, I now have to compute `deviceThisRank` manually (for example by querying the MPI rank and modding by the number of devices).

This is not a huge problem, I'm just wondering what I am doing wrong or misunderstanding about the `initialize(argc, argv)` version.

**Comment by jjramsey** [comment]
I noticed a link to a copy of "Professional CUDA C Programming", hosted at http://www.hds.bme.hu/, that I'm not sure is legit. It doesn't look like it's from any of the book's authors, nor do I see any other indication that Wiley has made it freely available.
