### ISSUE TITLE
Kokkos and `#include <windows.h>` 

### ISSUE THREAD

**Issue by JBludau** [kokkos/kokkos#5446]
The problem is that as soon as we want to use `min` and `max` as function names (e.g. in `Kokkos_NumericTraits.hpp`) we get compilation errors. But a user (or in my case a testcase) might want to include `windows.h`. This creates an interesting problem:

`min` and `max` are defined in `windows.h` as preproc macros. Thus, as soon as someone wants to include `windows.h` in code that also uses kokkos, he would have to define `NOMINMAX` before the include. This prevents `windows.h` from defining the macros. We are basically failing to export this constraint that we add by using the names `min` and `max`.
As failing to define `NOMINMAX` mixes macros with namespace stuff there are nasty compile errors happening far away from the point that needs the `NOMINMAX` fix. 

I can see the following ways we could tackle this (please comment if you know more):

- define `NOMINMAX` in Kokkos and document, that `Kokkos_Core.hpp` has to be included before any`windows.h` include
- just document that users have to do the `NOMINMAX` defines themselfs ...
- export `DNOMINMAX` in our compile commands
- make every call to `min` or `max` in kokkos not being translated by the macro by doing `(min)(x,y)`

**Comment by PhilMiller** [comment]
The last point you note, of fixing call sites, won't help the function declarations that we need to do.

One guard rail that we could absolutely put in place would be to say
```c++
#ifdef max
#error max is already defined as a macro; do you need to define NOMINMAX?
template<T blah>
T max (...) ...
```

If compilation ever reaches a point where the macro would screw it up, we can at least report the error sensibly

**Comment by PhilMiller** [comment]
On the first point, an include of Kokkos_Core.hpp or <algorithm> would have to precede pretty much any other header, because anything else might reach windows.h before we get the chance to guide it

**Comment by PhilMiller** [comment]
(can you tell this isn't the first Windows-supporting library code base I've worked on?)

**Comment by PhilMiller** [comment]
Maybe when we demand C++20 support, we can insist on getting Windows API bits from a module rather than a textual header inclusion. If we can tighten compiler requirements just for Windows, we could see about doing that sooner

**Comment by JBludau** [comment]
I guess exporting `DNOMINMAX` or just documenting and having the user deal with it might be the 'best' here ...

**Comment by PhilMiller** [comment]
If we don't export `NOMINMAX` ourselves, we could definitely put in the guard rail to report the error nicely

**Comment by JBludau** [comment]
I almost see having the guard rail as `non-negotiable` :-)

**Comment by msimberg** [comment]
> The last point you note, of fixing call sites, won't help the function declarations that we need to do.

I dislike `min`/`max` as macros as much as anyone, but just in case you weren't aware, you can  absolutely wrap the function names also in definitions/declarations and the macros won't be expanded, see https://godbolt.org/z/1oa8Y3o59.

**Comment by masterleinad** [comment]
Couldn't we also possibly use `#pragma push_macro("min")` to disable the macro and re-enable it at the end of the file with `#pragma pop_macro("min")`?

**Comment by msimberg** [comment]
> Wow. I had no idea that syntax was possible.
> 
> Out of curiosity, do you know of any other use case for writing a function name that way? I wouldn't even know what to search for to look it up

Unfortunately no. I suppose being allowed to put parentheses around most things combined with https://en.cppreference.com/w/cpp/preprocessor/replace#Function-like_macros ("each instance of the macro name followed by a `(`) is what helps here.

I only know about this because HPX has exactly that same problem: https://github.com/STEllAR-GROUP/hpx/blob/445dff84c2a9f90bf5c9ef43e9edfef504d77f1e/libs/core/util/include/hpx/util/max.hpp#L13.

**Comment by PhilMiller** [comment]
> Couldn't we also possibly use `#pragma push_macro("min")` to disable the macro and re-enable it at the end of the file with `#pragma pop_macro("min")`?

I imagined that would be a neat solution, but I didn't figure compilers actually supported that.

It makes protecting our definitions easy and self contained. Our internal uses can use the parentheses trick.

That just leaves the question of whether/how we communicate this to impacted users
