### ISSUE TITLE
Question on using nvcc_wrapper

### ISSUE THREAD

**Issue by mfdeakin-sandia** [kokkos/kokkos#545]
I'm having issues building a project with CUDA 8 which depends on Kokkos.

From the following error, the issue appears to be that a lambda is not an extended lambda:
/home/mdeakin/prefix/include/Cuda/Kokkos_CudaExec.hpp(284): error: The closure type for a lambda ("lambda [](int, int)->void") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is a 'extended lambda' and the flag --expt-extended-lambda is specified

I am using the following compilation command:

/home/mdeakin/HOMMEXX/cime/externals/trilinos/packages/kokkos/config/nvcc_wrapper --expt-extended-lambda -DHAVE_CONFIG_H -DINCLUDE_CMAKE_FCI -DSPMD -I/home/mdeakin/HOMMEXX/components/homme/build -I/home/mdeakin/HOMMEXX/components/homme/build/src/sweqx_flat -I/home/mdeakin/HOMMEXX/components/homme/utils/pio/pio -I/home/mdeakin/HOMMEXX/components/homme/build/utils/pio/pio -I/home/mdeakin/prefix/include -I/home/projects/pwr8-rhel72/netcdf/4.3.3.1/openmpi/1.10.2/gcc/5.3.0/cuda/8.0.21/include -I/home/projects/pwr8-rhel72/pnetcdf/1.6.1/openmpi/1.10.2/gcc/5.3.0/cuda/8.0.21/include -I/home/mdeakin/HOMMEXX/components/homme/build/utils/timing -I/home/mdeakin/HOMMEXX/components/homme/build/src/sweqx_flat/sweqx_flat_modules -I/home/mdeakin/HOMMEXX/components/homme/src -I/home/mdeakin/HOMMEXX/components/homme/src/share -I/home/mdeakin/HOMMEXX/components/homme/src/kokkos_kernels  -std=c++11 -O2 -g -fopenmp    -o CMakeFiles/sweqx_flat.dir/__/kokkos_kernels/recover_q.cpp.o -c /home/mdeakin/HOMMEXX/components/homme/src/kokkos_kernels/recover_q.cpp

Is this issue fixed in a more recent version of Kokkos? Or is there some other way for me to avoid this?

**Comment by mhoemmen** [comment]
Just curious -- are you using the KOKKOS_LAMBDA macro _in place of_ the capture specifier (e.g., [=])?

**Comment by mfdeakin-sandia** [comment]
Yes, we're using it as follows:
Kokkos::Experimental::md_parallel_for(
        RangePolicy({0, nets - 1}, {nlev, nete}, {1, 1}),
        KOKKOS_LAMBDA(int k, int ie) {...}

**Comment by mhoemmen** [comment]
Could be a multidimensional range policy thing.  Does KOKKOS_LAMBDA work for plain old Kokkos::parallel_for?

**Comment by mfdeakin-sandia** [comment]
I get the same error for the following test code:
Kokkos::parallel_for(10, KOKKOS_LAMBDA (const int i) {});

**Comment by crtrott** [comment]
Did you enable lambda support in Kokkos? I.e. did you install the library with the option: KOKKOS_CUDA_OPTIONS=enable_lambda?

Please paste your KokkosCore_config.h

**Comment by mfdeakin-sandia** [comment]
I didn't see that as an option in ccmake, but I can try it.
Here is the relevant portion of my KokkosCore_config.h

#if ! defined(KOKKOS_USE_CUDA_UVM)
/* #undef KOKKOS_USE_CUDA_UVM */
#endif // ! defined(KOKKOS_USE_CUDA_UVM)

/* #undef KOKKOS_HAVE_PTHREAD */
#define KOKKOS_HAVE_SERIAL
/* #undef KOKKOS_HAVE_QTHREAD */
/* #undef KOKKOS_HAVE_Winthread */
#define KOKKOS_HAVE_OPENMP
/* #undef KOKKOS_HAVE_HWLOC */
/* #undef KOKKOS_HAVE_DEBUG */
/* #undef KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK */
#define KOKKOS_HAVE_CXX11
/* #undef KOKKOS_HAVE_CUSPARSE */
#define KOKKOS_ENABLE_PROFILING_INTERNAL
#ifdef KOKKOS_ENABLE_PROFILING_INTERNAL
#define KOKKOS_ENABLE_PROFILING 1
#else
#define KOKKOS_ENABLE_PROFILING 0
#endif

**Comment by crtrott** [comment]
Ah ok, you are using CMake? The raw CMake support is still kind of experimental. Furthermore within Trilinos (via Tribits) we also didn't want to add the option, since those lambdas could be a fairly substantial problem. The details are a bit technical, but it comes down to the Lambda feature in Cuda still being considered experimental and some of the restrictions applying to lambdas are possibly not honored throughout the whole Trilinos code base. From your posting it looks like you simply want to install Kokkos somewhere? In that case you can use the GNU Makefile build system of Kokkos. 

Get yourself a build directory somewhere and run 
```
KOKKOS_PATH/generate_makefile.bash --help
```
That should list all the options you want. 

Christian

**Comment by mfdeakin-sandia** [comment]
Okay, then we might need to switch to using functors instead.
I had a few reasons to use the CMake interface, but one motivation was that another part of our project already uses most of Trilinos, so it makes sense to continue using it. If this wasn't a script to install Trilinos and Kokkos, I'd probably already be using the make system.

Thanks for the help!
Michael

**Comment by crtrott** [comment]
We are looking into an option which would allow us to enable Lambdas for everyone, but it requires an unreleased clang compiler (the current trunk of clang).

**Comment by mfdeakin-sandia** [comment]
Actually it looks like I'm having the same issue even after enabling cuda lambdas through the makefile system. The issue also persists when changing to use functors as well.
Here's my KokkosCore_config.h:
/* ---------------------------------------------
Makefile constructed configuration:
Fri Nov 18 12:11:37 MST 2016
----------------------------------------------*/
/* Execution Spaces */
#define KOKKOS_HAVE_OPENMP 1
#define KOKKOS_HAVE_SERIAL 1
#define KOKKOS_HAVE_CUDA 1
/* General Settings */
#define KOKKOS_HAVE_CXX11 1
/* Optimization Settings */
/* Cuda Settings */
#define KOKKOS_CUDA_USE_LAMBDA 1

And my test method with a parallel for functor:
void pfor_test() {
  struct functor {
    KOKKOS_INLINE_FUNCTION void operator() (const int i) const {}
  };
  Kokkos::parallel_for(10, functor());
}

**Comment by mfdeakin-sandia** [comment]
To clarify, the error is slightly different now:
/home/mdeakin/prefix/include/Cuda/Kokkos_CudaExec.hpp(284): error: A type defined inside a __host__ function  ("functor") cannot be used in the template argument type of a __global__ function template instantiation

**Comment by crtrott** [comment]
This is a limitation of Cuda. As the error message indicates a functor cannot be defined inside a function (i.e. in the scope of a local function). If you are interested in why, I can explain. So it should work if you do this:
```C++
struct functor {
  KOKKOS_INLINE_FUNCTION void operator() (const int i) const {}
};
void pfor_test() {
  Kokkos::parallel_for(10, functor());
}
```

Can you please post your error for the Lambda thing (code as well as compilation command line and KokkosCore_config.h). Because that should work (and does for us on all platforms as far as we can tell).

**Comment by mfdeakin-sandia** [comment]
I don't seem to be able to reproduce it anymore with Lambda anymore, so I must have been making a mistake. Thanks for your help and patience!
