### ISSUE TITLE
Examples for `print_configuration` need to be updated

### ISSUE THREAD

**Issue by psakievich** [kokkos/kokkos#5460]
**Describe the bug**
In prior versions of kokkos `print_configuration` was a static function for several execution spaces. Since the static property has been removed a few examples using this feature are out of date and should be updated.  Doing a Github search I found the following cases:

https://github.com/kokkos/kokkos/blob/b52f8c835f4df003954dad66d9761094f8baa66c/example/build_cmake_installed_kk_as_language/cmake_example.cpp
https://github.com/kokkos/kokkos/blob/4b97a22ff7be7635116930bb97173058d6079202/example/build_cmake_installed_different_compiler/foo.cpp
https://github.com/kokkos/kokkos/blob/1fb0c284d458c75370094921d9f202c287502325/example/build_cmake_installed/cmake_example.cpp

**Comment by masterleinad** [comment]
All of these have been fixed in the `develop` branch (and the release branch for 3.7).
