### ISSUE TITLE
Broken Albany build

### ISSUE THREAD

**Issue by ikalash** [kokkos/kokkos#5471]
**Describe the bug**
A bunch of Albany builds are failing with a call to ``Kokkos::Serial::print_configuration`` not being defined.  Did this routine go away?

**Please also include the following items to support reproducing the bug**
We are using the Kokkos in Trilinos develop.  The issue happens in various builds with various compilers.  The issue can be seen here on our CDash site: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=39411

The error looks as follows: 

```
[Albany/tests/unit/Albany_UnitTestMain.cpp:25](https://blob/master/Albany/tests/unit/Albany_UnitTestMain.cpp#L25):45: error: cannot call member function ‘void Kokkos::Serial::print_configuration(std::ostream&, bool) const’ without object
```

The error started within the past week while I was on foreign travel and unable to look a the CDash site / open the issue.

**Comment by ndellingwood** [comment]
This would be following merge of trilinos/Trilinos#10962 , the error can be resolved by replacing
`Kokkos::Serial::print_configuration`
with 
`Kokkos::Serial().print_configuration`

**Comment by ikalash** [comment]
@ndellingwood : thank you, I figured it was some simple fix like this.  I will try it and close this tomorrow provided the nightlies are clean.  Thanks!

**Comment by ikalash** [comment]
Hmmm, so actually it's not so simple.  It looks like we're calling the get_configuration routine through Phalanx: https://github.com/sandialabs/Albany/blob/master/tests/unit/Albany_UnitTestMain.cpp#L25 .  It must wrap print_configuration.  Seems a change to Phalanx may be required.  Tagging @rppawlo .

**Comment by ndellingwood** [comment]
I think I cleaned this up in all the spots in phalanx with trilinos/Trilinos#10962, 

```
s1067110:Trilinos ndellin$ git grep print_configuration packages/phalanx
packages/phalanx/example/FiniteElementAssembly/FiniteElementAssembly.cpp:    PHX::exec_space().print_configuration(std::cout);
packages/phalanx/example/FiniteElementAssembly_DeviceDag/FiniteElementAssembly_DeviceDag.cpp:    PHX::exec_space().print_configuration(std::cout);
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/FiniteElementAssembly_MixedFieldTypes.cpp:    PHX::exec_space().print_configuration(std::cout);
packages/phalanx/test/Utilities/Phalanx_UnitTestMain.cpp:    PHX::exec_space().print_configuration(out);
```

From the test line in Albany, it is calling print_configuration through the Phalanx `exec_space` type in `Phalanx_KokkosDeviceTypes.hpp`, which is an alias to an execution space type from a Phalanx `Device`
(i.e. `using exec_space = PHX::Device::execution_space;`) which aliases an execution space type.
@ikalash I think making the same type of change at https://github.com/sandialabs/Albany/blob/master/tests/unit/Albany_UnitTestMain.cpp#L25 should resolve the issue , that is replace that line by
`PHX::exec_space().print_configuration(out);`

**Comment by masterleinad** [comment]
In any case, was never intended to be `static`, see https://github.com/kokkos/kokkos/wiki/Kokkos::ExecutionSpaceConcept, but was implemented as such for some backends.

**Comment by dalg24** [comment]
Closing.  As pointed out above, `print_configuration()` is a non-static member function for execution spaces.
The [documentation](https://kokkos.org/kokkos-core-wiki/API/core/execution_spaces.html?highlight=print_configuration#synopsis) is up to date.
