### ISSUE TITLE
Deprecate `CudaUVMSpace::available()`

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5472]
Rational: not portable nor really useful.  Prefer facility introduced in #5289 instead

_Originally posted by @dalg24 in https://github.com/kokkos/kokkos/pull/5441#discussion_r975336647_

**Comment by JBludau** [comment]
I was thinking about proposing the deprecation in a separate pr together with some changes in examples/tutorials.

**Comment by dalg24** [comment]
Sounds good

**Comment by dalg24** [comment]
Done
