### ISSUE TITLE
NVHPC compiler issues an error when compiled with the serial backend on ppc64le

### ISSUE THREAD

**Issue by scottbiersdorff** [kokkos/kokkos#5483]
The NVHPC compiler will issue an error if the '-cuda' option is used on a system without a proper NVIDIA GPU:

cmake options are:

`-DCMAKE_CXX_COMPILER=nvc++ -DCMAKE_CXX_FLAGS="-fast -mp " -DCMAKE_VERBOSE_MAKEFILE=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_SERIAL=ON -DCMAKE_INSTALL_PREFIX=/tmp -DCMAKE_CXX_STANDARD=17    -DCMAKE_INSTALL_LIBDIR=lib64
...
[  6%] Linking CXX executable KokkosCore_TestCompileOnly
...
nvc++-Fatal-The `-cuda` option is available only on systems with NVIDIA GPUs with compute capability '>= cc60`

This occurs with the 3.7.00 release. I would recommend that the '-cuda' option only be applied when the CUDA backend is compiled.

**Comment by dalg24** [comment]
I was able to reproduce and see the `-cuda` on the link line.

**Comment by dalg24** [comment]
It is coming from here
https://github.com/kokkos/kokkos/blob/153a39e26779f5fe18ce0a09f09b4a2895ee85f3/cmake/kokkos_arch.cmake#L196

**Comment by dalg24** [comment]
Fix will be in release 4.0 and is a candidate for cherry-pick into the 3.7 first patch release (if we actually do a patch release)

**Comment by PhilMiller** [comment]
Fixed in 3.7.01 with #5569
