### ISSUE TITLE
deep_copy of Views with Atomic memory trait causes seg fault

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#552]
deep_copy between Views with the `Kokkos::Atomic` memory trait causes a seg fault at runtime. 

The occurs because in the ViewMapping's `data()` method, the `reference_type` is not an lvalue (see ViewDataHandle return_type at line 2281 of Kokkos_ViewMapping.hpp) and thus a call to its `data()` method returns `0` rather than a pointer to `m_handle`, which in turn causes the call to `deep_copy` between View's with atomic traits to seg fault. 

A View with Atomic trait created in either of these ways will have its data() method return 0: 
1. 'Directly' i.e.
```
  typedef Kokkos::View< T* , execution_space ,  Kokkos::MemoryTraits< Kokkos::Atomic > >  atomic_view_type ;
  atomic_view_type atv("atv",2) ;
```

2. Creating a View (no Atomic trait) first, then assigning it to the atomic View
```
  typedef Kokkos::View< T* , execution_space ,  Kokkos::MemoryTraits< Kokkos::Atomic > >  atomic_view_type ;
  typedef Kokkos::View< T* , execution_space > view_type ;
  view_type vt("vt",2);
  atomic_view_type avt = vt;
```

However, when calling `create_mirror_view` the resulting atomic View's `data()` method returns a non-zero value, for example
```
  typedef typename atomic_view_type::HostMirror host_atomic_view_type ;
  host_atomic_view_type h_result = Kokkos::create_mirror_view(atv);
```
returns a valid address.

**Comment by crtrott** [comment]
Ok so the question is why should map not return the ptr if I ask for it if the reference type is not an lvalue. I.e. what is the reason for it tor return 0 if the operator() of a view doesn't return an lvalue?

**Comment by crtrott** [comment]
@hcedwar need to wait for Carters input, I am not sure what moved him to do that.

**Comment by ndellingwood** [comment]
Yes; I posted under the assumption that `deep_copy` between View's with the Atomic trait should be valid, but was unsure why the behavior that is preventing that from working is there (and uncertain how to best follow through on the fix). Thanks for rephrasing more clearly and concisely.

**Comment by hcedwar** [comment]
If not an lvalue reference then can be a proxy type, for example a UQ aggregate data type, then a pointer is misleading since the underlying data does not reside within a contiguous span of memory.
Thus the conservative rule is when not an lvalue reference then don't allow address to be extracted.

**Comment by hcedwar** [comment]
Should catch this deep copy usage error prior to seg fault.

**Comment by crtrott** [comment]
Sure I get that. But there is a difference between asking for the base pointer of the view and doing &view(i). I believe .data() should always return something useful.

**Comment by etphipp** [comment]
Even for the UQ and AD data types, data() returns a valid pointer.  It is just the case that reference_type != pointer_type, which usually causes a compiler error when someone just grabs the pointer without paying attention to what they are doing.

**Comment by crtrott** [comment]
And basically what is the rule for deep_copy here? You can't deep_copy things which don't return lvalue? Or you can't deep-copy things which return an lvalue as long as nobody put in the explicit overload of deep_copy?

**Comment by crtrott** [comment]
Oh so you didn't mark UQ and AD as not being lvalues?

**Comment by etphipp** [comment]
It depends on the type.  For AD, reference_type is not an lvalue.  For UQ, it is (because the implementation is different).  In the AD case, reference_type is a temporary, but pointer_type is double* (assuming Fad<double>).  In both cases, I have a ViewMapping specialization, and therefore must implement my own overload of deep_copy().

**Comment by crtrott** [comment]
I see. For Atomic the return type is also a special handle, but data() would still be fully valid and I don't need a special mapping.

**Comment by etphipp** [comment]
Isn't that true for RandomRead memory trait as well?  Is it unsafe to use the pointer in these cases?  If it isn't, it seems to me that data() should return something valid.

**Comment by crtrott** [comment]
It is safe to use the pointer in that case.

**Comment by hcedwar** [comment]
Should not deep copy to/from a View with atomic trait.
For C++20 (assuming goes through) accessing non-atomic data while an atomic view exists will be illegal with "undefined behavior."
Best practice is to have non-atomic view, deep copy as needed, create atomic view, run functor, destroy atomic view, then deep copy as needed with original non-atomic view.

**Comment by crtrott** [comment]
Wait, I have to allocate and destroy atomic views all the time?

**Comment by hcedwar** [comment]
Should not be any allocation, just shallow-copy construction, prior to algorithm which needs to use via atomic operations.

**Comment by hcedwar** [comment]
Relax `data()` to return non-null for allocated data.  Add to comments and programming guide that interpretation and proper use of the underlying data depends upon layout, traits, etc.

**Comment by hcedwar** [comment]
Use case: to be able to reset values of an View<Atomic> on GPU from CPU.  Which does not violate concurrent atomic and non-atomic access.  Correctness requires trusting proper use, cannot be enforced.  Thus deep_copy needs to be supported with the requirement that a parallel kernel is not touching the view's data.
