### ISSUE TITLE
XL 13.1.4 incorrect C++11 flag

### ISSUE THREAD

**Issue by tomdeakin** [kokkos/kokkos#553]
If I setup Kokkos with the IBM XL 13.1.4 compiler as follows,
```CXX=xlc++ ../../generate_makefile.bash --prefix=$PWD/.. --with-openmp --arch=Power8```
it sets `--std=c++11` in `Makefile.kokkos`.

This causes any user code to fail to build with `warning: 1501-257 Option std=c++11 is not recognized.  Option will be ignored.`

The `xlc++ --help` page says the flag should be `-std=c++11`.

This is using Kokkos at the `2.02.01` tag.

**Comment by nmhamster** [comment]
I think you should do --compiler=xlc++ on the generate_makefike.sh

**Comment by tomdeakin** [comment]
Thanks, that now works OK. If I have `CXX=xlc++` set in my environment though, shouldn't the build work out I'm using xlc++ for me?

**Comment by nmhamster** [comment]
Why would we do that ;-)! It's a bug. Thanks for reporting it.

**Comment by crtrott** [comment]
Ok found the issue. The -qversion option spits out a different format, so our makefile doesn't identify the compiler correctly.
