### ISSUE TITLE
Cuda Parallel Scan has incorrect offset for types smaller than `size_type`

### ISSUE THREAD

**Issue by nmm0** [kokkos/kokkos#5545]
**Describe the bug**
https://github.com/kokkos/kokkos/blob/0fb8b8ab8bd01cfc7dd27da37f20deb0904afe30/core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp#L542-L544

This value is 0 if the size of `value_type` is < 4 bytes (`sizeof(size_type)`)

This is the underlying cause for https://github.com/kokkos/kokkos/issues/5513 and partially fixes the issue

**Comment by PhilMiller** [comment]
Maybe also tag for https://github.com/kokkos/kokkos/labels/Patch%20Release ?

**Comment by dalg24** [comment]
> This value is 0 if the size of `value_type` is < 4 bytes (`sizeof(size_type)`)

Do you mean the return value of `Analysis::value_size(m_functor)`?

**Comment by PhilMiller** [comment]
Released fix in 3.7.01 #5607
