### ISSUE TITLE
Interaction between "Execution Space Instances" and control threads

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#555]
Two use cases to discuss:
1. Support for AMT models "multiple control threads" (Darma, Uintah, L2 Milestone)
 * Static splitting of execution resources
 * Each control thread acts as a 'master/process thread'

2. Multiple _execution space instances_ accessible from a each control thread
 * Multiple GPU/streams 
 * GPU + Host backend
 * Dynamic subsetting execution spaces for functional parallelism

_Kokkos Instance_ at initialization acquires execution resources and memory resource (made into spaces by Kokkos)
Execution resources are uniquely owned
Memory resources can be shared across multiple Kokkos Instances

**Comment by hcedwar** [comment]
There is no abstraction of a _Kokkos Instance_
There are control threads, per-control thread default execution and memory spaces, and properly managing interactions between spaces associated with different control threads.

**Comment by hcedwar** [comment]
@dsunder - Can this be closed?
