### ISSUE TITLE
CHANGELOG 3.7.01

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#5551]
This is the changelog for the upcoming Release 3.7.01

### Bug Fixes

- Add fences to all sorting routines not taking an execution space instance argument https://github.com/kokkos/kokkos/pull/5547
- Fix repeated team_reduce without barrier #5552 
- Fix memory spaces in create_mirror_view overloads using view_alloc #5521
- Allow as_view_of_rank_n() to be overloaded for "special" scalar types #5553 #5591
- OpenMPTarget: adding implementation to set device id. #5557 
-  Fix 5315: use Kokkos::atomic_load to Correct Race Condition Giving Rise to Seg Fault'ing Error in OpenMP tests #5559 
-  cmake: define KOKKOS_ARCH_A64FX #5561 
-  Only link against libatomic in gnu-make OpenMPTarget build #5565 
-  Fix static extents assignment for LayoutLeft/LayoutRight assignment #5566 
- Do not add `-cuda` to the link line with NVHPC compiler when the CUDA backend is not actually enabled  #5569
- Export the flags in KOKKOS_AMDGPU_OPTIONS when using Trilinos #5571 
- Add support for detecting MPI local rank with MPICH and PMI #5570 #5582
- Remove listing of undefined TPL dependencies #5573
- `ClockTic` changed to 64 bit to fix overflow on Power #5592
- Fix incorrect offset in CUDA and HIP `parallel_scan` for < 4 byte types #5607

**Comment by ajpowelsnl** [comment]
TODO:

- Merge 5561 [DONE]
- Fix test 5559:
```
27/30 Test  #7: KokkosCore_UnitTest_LogicalSpaces ..............***Timeout 2000.07 sec
[==========] Running 6 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from defaultdevicetype_DeathTest
[ RUN      ] defaultdevicetype_DeathTest.access_forbidden
```
- Merge 5557 (caveat: clang++ failure)
- Add fix to issue #5475
  - FIX:  #5552 (already merged)
- Merge / cherry-pick #5485 
- Merge / cherry-pick #5528 
- Merge / cherry-pick #5535
- Merge / cherry-pick #5491 
- Merge / cherry-pick #5492
- Merge / cherry-pick #5525
- Merge / cherry-pick #5530 (caveat: is this really fixed?)
- Merge / cherry-pick #5537
- Merge / cherry-pick #5540
- Merge / cherry-pick #5555
