### ISSUE TITLE
HIP Parallel Scan and Reduce have incorrect offset for types smaller than size_type

### ISSUE THREAD

**Issue by nmm0** [kokkos/kokkos#5556]
Related: https://github.com/kokkos/kokkos/issues/5545

**Comment by masterleinad** [comment]
I'm just wondering how it was passing the tests after the respective changes were made to `Cuda` and we added tests.

**Comment by nmm0** [comment]
Using the test included in https://github.com/kokkos/kokkos/pull/5555, @masterleinad was able to get test failures for HIP scan but we are still trying to figure out why reduce seems to work correctly

**Comment by PhilMiller** [comment]
This has https://github.com/kokkos/kokkos/labels/InDevelop but it's not clear which PR provided the fix. Was it addressed by #5522?

**Comment by nmm0** [comment]
Fixed by https://github.com/kokkos/kokkos/pull/5555

**Comment by PhilMiller** [comment]
Ah, I was misled by the title of that PR only mentioning CUDA.
