### ISSUE TITLE
Makefile.kokkos Can Have Issues with Compiler Selection

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#556]
We have an potential issue with the compiler selection. The `ifeq ($(KOKKOS_INTERNAL_COMPILER_XL), 1)` can be an issue if the version outputs additional text (e.g. the XL Beta compiler). This should really be a greater than check rather than an equals.

**Comment by crtrott** [comment]
yeah I know I fixed that internally already.

**Comment by crtrott** [comment]
Duplicate of #553 so I close this again.
