### ISSUE TITLE
Are you supposed to be able to pass Kokkos::Device as the exeuction space template parameter of execution policies?

### ISSUE THREAD

**Issue by gmackey** [kokkos/kokkos#558]
In many places devices, execution spaces, and memory spaces can be used interchangeably.  However, I get a compile error if I try to pass a device type as the template parameter to either the RangePolicy or TeamPolicy.  Is this supposed to work?

**Comment by crtrott** [comment]
No its not, if you have a device you need to pass device::execution_space
