### ISSUE TITLE
Performance regression of Kokkos::subview (especially managed views) inside kernels

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#5581]
**Describe the bug**
There has been a performance regression involving ``Kokkos::subview`` inside of kernels, running on Serial. There are 2 dimensions to this:
- the strange part: it seems to be creeping up over multiple versions, instead of jumping up in one specific change
- subviewing managed vs. unmanaged views used to take the same amount of time, but it started to diverge around 3.6 release

This was originally noticed from a regression in a Trilinos performance test running on the CTS-1 clusters after the 3.7 update. This made a significant (~50%) slowdown in a nontrivial kernel. Replacing managed with unmanaged views gets back to the 3.6.1 speeds. But in both that test and this reproducer, the view's ``use_count()`` is not changing inside the kernel. So I'm not sure why managed makes a difference.

CTS-1 is the Broadwell machine used below.

```
Versions/SHAs
develop 9a8ea2f
3.7     61d7db5
3.6.1   d19aab9
3.6     b52f8c8
3.5     ae5fc64

g++ 9.1.0, Intel(R) Xeon(R) W-2155 (SKX)

develop: Normal: 1.85181 s.    Unmanaged: 1.17398 s.
3.7:     Normal: 1.26016 s.    Unmanaged: 0.93661 s.
3.6.1:   Normal: 1.38607 s.    Unmanaged: 0.91535 s.
3.6:     Normal: 1.16579 s.    Unmanaged: 1.14086 s.
3.5:     Normal: 0.928741 s.   Unmanaged: 0.93753 s.

icpc 19.1, Intel(R) Xeon(R) CPU E5-2695 v4 (BDW)

develop: Normal: 3.93745 s.    Unmanaged: 2.64626 s.
3.7:     Normal: 4.11707 s.    Unmanaged: 2.63066 s.
3.6.1:   Normal: 3.3886 s.     Unmanaged: 2.62778 s.
3.6:     Normal: 2.8558 s.     Unmanaged: 2.50448 s.
3.5:     Normal: 2.74807 s.    Unmanaged: 2.75499 s.
```

Reproducer (example/build_cmake_in_tree/cmake_example.cpp):
```
#include <Kokkos_Core.hpp>
int main()
{
  Kokkos::initialize();
  Kokkos::print_configuration(std::cout);
  {
    Kokkos::View<int*, Kokkos::DefaultExecutionSpace> v("V", 1000);
    Kokkos::Timer t;
    for(int rep = 0; rep < 100; rep++)
    {   
      Kokkos::parallel_for("Reproducer", Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>(0, 10000000),
          KOKKOS_LAMBDA(int i)
          {
          auto vsub = Kokkos::subview(v, i % 1000);
          vsub()++;
          });
    }   
    Kokkos::DefaultExecutionSpace().fence();
    double elapsed = t.seconds();
    std::cout << "Normal: " << elapsed << " s.    ";
    Kokkos::View<int*, Kokkos::DefaultExecutionSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> vu = v;
    t.reset();
    for(int rep = 0; rep < 100; rep++)
    {   
      Kokkos::parallel_for("Reproducer", Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>(0, 10000000),
          KOKKOS_LAMBDA(int i)
          {
          auto vusub = Kokkos::subview(vu, i % 1000);
          vusub()++;
          });
    }
    Kokkos::DefaultExecutionSpace().fence();
    elapsed = t.seconds();
    std::cout << "Unmanaged: " << elapsed << " s.\n";
  }
  Kokkos::finalize();
  return 0;
}
```

Configuring, g++ version:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_SKX=ON ../kokkos/example/build_cmake_in_tree
```
Configuring, Intel version:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=icpc -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_BDW=ON ../kokkos/example/build_cmake_in_tree
```

**Comment by brian-kelley** [comment]
@csiefer2

**Comment by dalg24** [comment]
@brian-kelley I can see you are on the host and that it likely does not change your timings but you might want to add fences before you stop your timer.

**Comment by brian-kelley** [comment]
@dalg24 I just added them. I was only running on Serial before (because the Trilinos regression appeared on a serial build), so those should still be valid. I didn't try this on other backends.

**Comment by brian-kelley** [comment]
Out of curiousity, here are the numbers for SKX on OpenMP, 8 threads. There is a much smaller change over time compared to Serial.
```
develop: Normal: 0.789081 s.    Unmanaged: 0.621484 s.
3.7:     Normal: 0.794798 s.    Unmanaged: 0.642438 s.
3.6.1:   Normal: 0.80062 s.     Unmanaged: 0.662359 s.
3.6:     Normal: 0.813639 s.    Unmanaged: 0.669795 s.
3.5:     Normal: 0.713756 s.    Unmanaged: 0.583025 s.
```

**Comment by brian-kelley** [comment]
On BDW/Intel compiler I saw it improve from:
```
Normal: 3.94619 s.    Unmanaged: 2.70187 s.
```
to:
```
Normal: 3.33296 s.    Unmanaged: 2.44337 s.
```

**Comment by masterleinad** [comment]
On another build I only see improvements switching back from `thread_local` to `__thread` completely.

**Comment by brian-kelley** [comment]
update - ifdef'ing out the runtime rank check in the View constructor made no difference.

**Comment by masterleinad** [comment]
```diff
diff --git a/core/src/impl/Kokkos_SharedAlloc.cpp b/core/src/impl/Kokkos_SharedAlloc.cpp
index db9ebd98e..33c9488da 100644
--- a/core/src/impl/Kokkos_SharedAlloc.cpp
+++ b/core/src/impl/Kokkos_SharedAlloc.cpp
@@ -47,7 +47,7 @@
 namespace Kokkos {
 namespace Impl {
 
-thread_local int SharedAllocationRecord<void, void>::t_tracking_enabled = 1;
+__thread int SharedAllocationRecord<void, void>::t_tracking_enabled = 1;
 
 #ifdef KOKKOS_ENABLE_DEBUG
 bool SharedAllocationRecord<void, void>::is_sane(
diff --git a/core/src/impl/Kokkos_SharedAlloc.hpp b/core/src/impl/Kokkos_SharedAlloc.hpp
index 3e84f2d71..903f190e1 100644
--- a/core/src/impl/Kokkos_SharedAlloc.hpp
+++ b/core/src/impl/Kokkos_SharedAlloc.hpp
@@ -141,7 +141,7 @@ class SharedAllocationRecord<void, void> {
       SharedAllocationHeader* arg_alloc_ptr, size_t arg_alloc_size,
       function_type arg_dealloc, const std::string& label);
  private:
-  static thread_local int t_tracking_enabled;
+  static __thread int t_tracking_enabled;
 
  public:
   virtual std::string get_label() const { return std::string("Unmanaged"); }
```

**Comment by PhilMiller** [comment]
WTH? What compiler doesn't treat `__thread` and `thread_local` equivalently? Is there some obvious difference in the output of `nm` or a disassembly?

**Comment by brian-kelley** [comment]
Sure enough, this revision does entirely fix the original regression in Tpetra.

**Comment by PhilMiller** [comment]
> WTH? What compiler doesn't treat `__thread` and `thread_local` equivalently? Is there some obvious difference in the output of `nm` or a disassembly?

A listing of relocations from `readelf` might also be informative - possibly it's using a different type, with different performance characteristics

**Comment by masterleinad** [comment]
For some reason, I also see 67b0ee8a527011f8663e0da05308aa140f234abd causing regressions here.

**Comment by crtrott** [comment]
Do we have an overview with which compilers the change from `thead_local` to `__thread` fixes the issue?

**Comment by crtrott** [comment]
We may wanna introduce a macro KOKKOS_IMPL_THREAD_LOCAL and add a big FIXME with explanation for which compilers this matters, and that we need to continue check whether newer compilers need this or not. We also may wanna file bug reports.

**Comment by brian-kelley** [comment]
@masterleinad Do you think your change can make it into the 4.0 release?
@crtrott I could help figure out how this affects performance on different compilers if needed. I only tested so far on Intel 19 where it made a major improvement. In the table I put in the issue, it eliminated the slowdown of managed views since version 3.5.

**Comment by nmm0** [comment]
> WTH? What compiler doesn't treat `__thread` and `thread_local` equivalently? Is there some obvious difference in the output of `nm` or a disassembly?

@PhilMiller Could this be why?: https://stackoverflow.com/questions/13106049/what-is-the-performance-penalty-of-c11-thread-local-variables-in-gcc-4-8 It looks like it can in some situations be translated into a function call.

**Comment by PhilMiller** [comment]
That seems pretty plausible. 

Here's an alternative patch I'm testing, to just make the variable entirely private to the one .cpp file:

```diff
diff --git a/core/src/impl/Kokkos_SharedAlloc.cpp b/core/src/impl/Kokkos_SharedAlloc.cpp
index 3db93e8fd..53ed1ae1b 100644
--- a/core/src/impl/Kokkos_SharedAlloc.cpp
+++ b/core/src/impl/Kokkos_SharedAlloc.cpp
@@ -51,7 +51,22 @@
 namespace Kokkos {
 namespace Impl {
 
-thread_local int SharedAllocationRecord<void, void>::t_tracking_enabled = 1;
+static thread_local int t_tracking_enabled = 1;
+
+#if defined(__EDG__) && !defined(KOKKOS_COMPILER_INTEL)
+#pragma push
+#pragma diag_suppress implicit_return_from_non_void_function
+#endif
+static KOKKOS_FUNCTION int SharedAllocationRecord<void, void>::tracking_enabled() {
+  KOKKOS_IF_ON_HOST(return t_tracking_enabled;)
+  KOKKOS_IF_ON_DEVICE(return 0;)
+}
+#if defined(__EDG__) && !defined(KOKKOS_COMPILER_INTEL)
+#pragma pop
+#endif
+
+static void SharedAllocationRecord<void, void>::tracking_disable() { t_tracking_enabled = 0; }
+static void SharedAllocationRecord<void, void>::tracking_enable() { t_tracking_enabled = 1; }
 
 #ifdef KOKKOS_ENABLE_DEBUG
 bool SharedAllocationRecord<void, void>::is_sane(
diff --git a/core/src/impl/Kokkos_SharedAlloc.hpp b/core/src/impl/Kokkos_SharedAlloc.hpp
index 02dcd1ec6..931aeff18 100644
--- a/core/src/impl/Kokkos_SharedAlloc.hpp
+++ b/core/src/impl/Kokkos_SharedAlloc.hpp
@@ -140,33 +140,21 @@ class SharedAllocationRecord<void, void> {
 #endif
       SharedAllocationHeader* arg_alloc_ptr, size_t arg_alloc_size,
       function_type arg_dealloc, const std::string& label);
- private:
-  static thread_local int t_tracking_enabled;
 
  public:
   virtual std::string get_label() const { return std::string("Unmanaged"); }
 
-#if defined(__EDG__) && !defined(KOKKOS_COMPILER_INTEL)
-#pragma push
-#pragma diag_suppress implicit_return_from_non_void_function
-#endif
-  static KOKKOS_FUNCTION int tracking_enabled() {
-    KOKKOS_IF_ON_HOST(return t_tracking_enabled;)
-    KOKKOS_IF_ON_DEVICE(return 0;)
-  }
-#if defined(__EDG__) && !defined(KOKKOS_COMPILER_INTEL)
-#pragma pop
-#endif
+  static KOKKOS_FUNCTION int tracking_enabled();
 
   /**\brief A host process thread claims and disables the
    *        shared allocation tracking flag.
    */
-  static void tracking_disable() { t_tracking_enabled = 0; }
+  static void tracking_disable();
 
   /**\brief A host process thread releases and enables the
    *        shared allocation tracking flag.
    */
-  static void tracking_enable() { t_tracking_enabled = 1; }
+  static void tracking_enable();
 
   virtual ~SharedAllocationRecord() = default;
```

**Comment by PhilMiller** [comment]
Ok, so on kokkos-dev-2 with my patch, and built like so:

> `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-march=native -DCMAKE_CXX_COMPILER=g++ -DKokkos_ENABLE_SERIAL=ON ~/repos/kokkos/example/build_cmake_in_tree`

I observe a 50% slowdown for managed views relative to `develop`, and parity for unmanaged views.

`develop`:
> `Normal: 1.36239 s.    Unmanaged: 1.0793 s.`

Patched:
> `Normal: 2.07042 s.    Unmanaged: 1.08063 s.`

So, let's not do *that*

**Comment by PhilMiller** [comment]
For reference on kokkos-dev-2, using `sems-gcc/10.1`, built as my previous comment, here are timings from recent releases:

3.7:
> `Normal: 1.35975 s.    Unmanaged: 1.0797 s`

3.6.01:
> `Normal: 1.07839 s.    Unmanaged: 1.07848 s.`

3.6.00:
> `Normal: 1.08041 s.    Unmanaged: 1.07952 s.`

3.5.00:
> `Normal: 1.07957 s.    Unmanaged: 1.07876 s.`

**Comment by masterleinad** [comment]
@PhilMiller Does replacing `thread_local` with `__thread` or making `t_tracking_enabled` `static inline` fix the regression for you completely?

**Comment by PhilMiller** [comment]
Yeah.

3.7 with `__thread int t_tracking_enabled;`:
> `Normal: 1.07934 s.    Unmanaged: 1.07805 s.`

**Comment by masterleinad** [comment]
> 3.7 with static inline int t_tracking_enabled = 1;
>
>    Normal: 1.07923 s. Unmanaged: 1.07989 s.

I meant `static inline thread_local int t_tracking_enabled = 1;`.

**Comment by PhilMiller** [comment]
I think I just mis-transcribed, rather than copying and pasting.

**Comment by masterleinad** [comment]
@brian-kelley Would you mind reevaluating this on your side with `develop`?

**Comment by brian-kelley** [comment]
@masterleinad This is really weird but whatever I try now, I cannot get either patch (``inline`` or ``__thread``) to show the improvement with Intel 19.1, with the Tpetra reproducer or the standalone reproducer above. In October I did find that ``__thread`` fixed the regression in Tpetra, but now I can't replicate that :disappointed:

**Comment by ajpowelsnl** [comment]
Hi @brian-kelley, @csiefer2 - is the slowdown still an issue?

**Comment by brian-kelley** [comment]
@ajpowelsnl It's definitely not an immediate issue, so I can close this. After I failed to replicate the fix in January, I put in a workaround for the Tpetra thing where we originally noticed this.
