### ISSUE TITLE
`OpenMP` performance regression in `3.7.0`

### ISSUE THREAD

**Issue by cz4rs** [kokkos/kokkos#5600]
**Describe the bug**
Reported via Slack:

> Using OMP_NUM_THREADS=64 on an AMD Threadripper 3970x this is about 3-4x slower using Kokkos 3.7 than Kokkos 3.6
> If I set OMP_NUM_THREADS=32 it is only about 2x slower on Kokkos 3.7

<details>
  <summary>Reproduction code</summary>
  
```cpp
#include <Kokkos_Core.hpp>
#include <list>

using Device = Kokkos::DefaultHostExecutionSpace;

void driver(){
    uint32_t n = 200000000;
    Kokkos::View<uint32_t*, Device> a("test", n);
    std::list<Kokkos::View<uint32_t*, Device>> sources;
    uint32_t t_iter = 10;
    Kokkos::fence();
    Kokkos::Timer t;
    double begin = t.seconds();
    uint32_t segments = 64;
    uint32_t width = n / segments;
    for(uint32_t i = 0; i < t_iter; i++){
        for(uint32_t j = 0; j < segments; j++){
            auto source = Kokkos::subview(a, std::make_pair(width*j, width*(j+1)));
            Kokkos::View<uint32_t*, Device> dest(Kokkos::ViewAllocateWithoutInitializing("dest"), width);
            Kokkos::deep_copy(dest, source);
            sources.push_back(dest);
        }
        Kokkos::fence();
    }
    double end = t.seconds();
    double d = end - begin;
    double avg = d / static_cast<double>(t_iter);
    double bandwidth = static_cast<double>(2*sizeof(uint32_t)*n) / avg;
    printf("uint32_t size: %li\n", sizeof(uint32_t));
    printf("Total time: %.2fs; Avg Time: %.2fs; Bandwidth: %.2fMB/s\n", d, avg, bandwidth / 1000000);
}

int main() {
    Kokkos::initialize();
    {
        driver();
    }
    Kokkos::finalize();
    return 0;
}
```
</details>

**Configuration**
```
../generate_makefile.bash --kokkos-path=/home/user/workspace/kokkos \
--prefix=/home/user/workspace/install/kokkos \
--with-cuda --arch=Ampere86 --compiler=/home/user/workspace/kokkos/bin/nvcc_wrapper \
--with-cuda-options=enable_lambda --with-openmp --with-serial
```
- Ubuntu 20.04 LTS
- `g++` 10.2
- AMD Ryzen Threadripper 3970x, with 256GB (8x32GB at 3200 MT/s) in a quad-channel configuration
- `OMP_PROC_BIND=spread` `OMP_PLACES=cores`

**Any additional info**
Introduced with https://github.com/kokkos/kokkos/pull/4664. Defining `KOKKOS_INTERNAL_DISABLE_NATIVE_OPENMP`) in `core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp` (which causes `OpenMP` backend to use previous, non-native implementation) 
fixes the slowdown.

**Comment by masterleinad** [comment]
Would you mind checking if https://github.com/kokkos/kokkos/pull/5601 helps?

**Comment by masterleinad** [comment]
It looks like using `__thread` instead of `thread_local` (or `inline` globals) doesn't really help here.

**Comment by cz4rs** [comment]
> It looks like using `__thread` instead of `thread_local` (or `inline` globals) doesn't really help here.

True, I have confirmation from Mike Gilbert as well (the original reporter) that it doesn't help.

**Comment by crtrott** [comment]
Can we do a compiler/arch sweep to see where this is a problem? I.e. test x86 Intel, AMD and some ARM with GCC, Intel and Clang, NVHPC?

**Comment by vlkale** [comment]
I had been experimenting this on Perlmutter with clang and nvhpc and will also be experimenting and Crusher with clang and amdclang++ next week.  

@crtrott Do you (or others) have any specific instances of platforms (compiler/arch) to try? 

I don't have access to any system with ARM right now, but I can try to obtain it if it helps for this Issue.

**Comment by rgayatri23** [comment]
I tested this on Perlmutter CPU nodes with gcc/10.3, gcc/11.2, nvhpc/22.9, clang/15. Perlmutter has [AMD EPYC CPU ](https://www.amd.com/en/products/cpu/amd-epyc-7763) with 128 cores. 
I was not able to reproduce the issue. Here are the results from gcc/10.3 which is the closest to the compiler version mention in the issue (gcc/10.2)

```
OMP_NUM_THREADS=32
kk/3.7.01 - Total time: 0.75s; Avg Time: 0.08s; Bandwidth: 21255.14MB/s
kk/4.0.0  -  Total time: 0.74s; Avg Time: 0.07s; Bandwidth: 21735.03MB/s

OMP_NUM_THREADS=64 
kk/3.7.01 - Total time: 1.20s; Avg Time: 0.12s; Bandwidth: 13309.80MB/s
kk/4.0.0  - Total time: 1.22s; Avg Time: 0.12s; Bandwidth: 13125.78MB/s  

OMP_NUM_THREADS=128 
kk/3.7.01 - Total time: 3.12s; Avg Time: 0.31s; Bandwidth: 5134.65MB/s
kk/4.0.0  - Total time: 2.89s; Avg Time: 0.29s; Bandwidth: 5528.59MB/s
```

**Comment by PhilMiller** [comment]
@rgayatri23 The point of reference from which a regression was seen is Kokkos 3.6

**Comment by rgayatri23** [comment]
Thanks @PhilMiller for pointing it out. I was able to reproduce the issue and raised a PR that can fix the issue. 
#5742

**Comment by cz4rs** [comment]
Closing after #5742 was merged.
