### ISSUE TITLE
Legion+Kokkos Interop fails on HIP backend

### ISSUE THREAD

**Issue by eddy16112** [kokkos/kokkos#5603]
**Describe the bug**
In the Legion+Kokkos Interop, we explicit uses the `Kokkos::CUDA/HIP/OpenMP::impl_finalize` to finalize each execution space in each thread, and then call `Kokkos::finalize` from the main thread to finalize kokkos. However, this mechanism breaks on HIP backend. It is because `Kokkos::finalize` also calls `Kokkos::HIP::impl_finalize` even though the HIP execution space has been finalized explicitly by Legion, then `constantMemHostStaging` is freed twice (https://github.com/kokkos/kokkos/blob/master/core/src/HIP/Kokkos_HIP_Instance.cpp#L431) and resulting in crushes.

**Comment by masterleinad** [comment]
Have a look at https://github.com/kokkos/kokkos/blob/develop/core/unit_test/TestLegionInitialization.cpp for the intended pattern to be used now.

**Comment by masterleinad** [comment]
Basically, use `Kokkos::Impl::post_finalize()` instead of `Kokkos::finalize()` if you finalize individual backends.

**Comment by eddy16112** [comment]
Thank you! Is `Kokkos::Impl::pre_finalize()` also needed?

**Comment by dalg24** [comment]
Yes

**Comment by eddy16112** [comment]
Looks like the pre/post_finalize is in the develop branch, I am wondering when it will be merged into the master branch?

**Comment by dalg24** [comment]
When 4.0 is released.  Note that in the future we will get rid of the `master` branch.  If you want something stable, prefer tagged releases, otherwise go for `develop`.
