### ISSUE TITLE
Kokkos hangs in develop with ROCm 5.3 and managed memory

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#5606]
I am opening an issue because this blocks the promotion. With ROCm 5.3, `hip_managed.view_allocation_error` segfaults on master. The same test segfaults on develop with `XNACK=0`. The `hip_managed` tests hangs on develop with `XNACK=1`. Everything works as expected with ROCm 5.2

**Comment by JBludau** [comment]
have we checked, if there is some updated requirement for the kernel and driver versions? Feels like stating the obvious

**Comment by Rombur** [comment]
I checked the release note there was nothing about it.

**Comment by Rombur** [comment]
I found the PR that causes the tests to hang: https://github.com/kokkos/kokkos/pull/5448 It's when we decided to pass the functors by value instead of copying them. I need to think about this more but right now, I don't think we have many choices. We either revert the patch or we have both path in the code and we choose one of them depending on the ROCm version.

**Comment by arghdos** [comment]
Interestingly, extracting one of the [hanging tests](https://github.com/kokkos/kokkos/blob/master/core/unit_test/TestViewSubview.hpp#L160) to a standalone test ... doesn't hang.
The hang itself is happening on _some_ lanes of e.g., a store to a managed view: https://github.com/kokkos/kokkos/blob/master/core/unit_test/TestViewSubview.hpp#L160

**Comment by arghdos** [comment]
The segfault w/ HSA_XNACK=0 was comparatively easy to track down, have that reproduced internally.

**Comment by arghdos** [comment]
> The segfault w/ HSA_XNACK=0 was comparatively easy to track down, have that reproduced internally.

Was fixed with https://github.com/ROCm-Developer-Tools/hipamd/commit/df82f201f26e297ae4c0f9e263ab85173a2690dd

**Comment by arghdos** [comment]
I've extracted the `hip_managed.view_subview_auto_1d_left` test out of GTEST and into a standalone code (giving reasonable facsimiles of of `ASSERT_EQ` and `TEST` and friends), and ... it _still_ doesn't hang.

It is starting to seem like GTEST is required... somehow.  No idea how, yet but working on reducing the test case as much as possible.

**Comment by arghdos** [comment]
Been chewing on this in the background.
One thing I noticed is that the whole `DriverType` pointer cycling scheme also went away in https://github.com/kokkos/kokkos/pull/5448.

This will change the performance of e.g., the `GlobalMemory` launcher, but it's not clear that it's related to this hang.

**Comment by ajpowelsnl** [comment]
TODO:
- Disable local launch for 5.3 and 5.4 & verify that it works;
  - WARN: use 5.2 if you want overlapping kernel launch; potentially a severe performance bug (effectively serial) in HIP;
  - WARN at configure time;

**Comment by Rombur** [comment]
> Disable local launch for 5.3 and 5.4 & verify that it works; 

It doesn't. I get the same bug when using constant memory launch

**Comment by Rombur** [comment]
#5796 introduces a workaround when hitting this bug

**Comment by PhilMiller** [comment]
Workaround merged to both `develop` and `release-candidate-4.0.0` - setting InDevelop and unsetting 'Blocks Promotion'
