### ISSUE TITLE
Implementability of logical spaces

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5609]
Logical spaces are our attempt to mock GPU to enable debugging from a host-only build.

As we rediscovered in #5544 (adding a `static_assert` to check that the view memory space is accessible from the execution space that does the initialization) we currently only have logical memory spaces.
Logical memory spaces are implemented as a strongly-typed wrapper around another space which changes accessibility and has its own separate allocation tracking facility.  We don't have logical execution spaces from which we can legally access logical memory spaces so we can't do much with them.

The goal of this issue is to determine whether it is possible to make them useful.  If so what are we missing?  Otherwise should we withdraw the whole thing?

Here are previous work on the subject that I was able to dig up with a quick search:
* Issue #783 first discussion of a debug facility that would be available from a serial build 
* PR #2229 reviving the original discussion and stating 
* PR #2307 prototype allocation in the debug space with separate tracking mechanism
* PR #2822 attempt to pass the meta information from the policy to the tools via `beginParallel{For,Reduce,Scan)`
* PR #2918 draft of the logical memory space that is currently in `develop`
* PR #3546 version finally merged into release 3.4

**Comment by dalg24** [comment]
This snippet of code
https://github.com/kokkos/kokkos/blob/3c842fb0a46df51dd6bcd012316a9171993e7a05/core/src/impl/Kokkos_ViewMapping.hpp#L4124-L4135
illustrates why I currently think it cannot work.  This is how we determine memory access violations in views.  In short, we cannot infer from the kernel in what context it is being called, that is we cannot distinguish a logical execution space from its underlying host execution space.

**Comment by masterleinad** [comment]
I could see that the class would be more usable with something like
```diff
diff --git a/core/src/Kokkos_LogicalSpaces.hpp b/core/src/Kokkos_LogicalSpaces.hpp
index 2f5aa2985..30d73c1e4 100644
--- a/core/src/Kokkos_LogicalSpaces.hpp
+++ b/core/src/Kokkos_LogicalSpaces.hpp
@@ -71,6 +71,14 @@ struct LogicalSpaceSharesAccess {
   struct no_shared_access {};
 };
 
+template <class BaseExecutionSpace, class MemorySpace>
+class LogicalExecutionSpace : public BaseExecutionSpace {
+ public:
+  using BaseExecutionSpace::BaseExecutionSpace;
+  using execution_space = LogicalExecutionSpace;
+  using memory_space    = MemorySpace;
+};
+
 /// \class LogicalMemorySpace
 /// \brief
 ///
@@ -102,10 +110,11 @@ class LogicalMemorySpace {
   /// useful for things like initializing a View (which happens in
   /// parallel using the View's default execution space).
 
-  using execution_space =
+  using execution_space = LogicalExecutionSpace<
       std::conditional_t<std::is_void<DefaultBaseExecutionSpace>::value,
                          typename BaseSpace::execution_space,
-                         DefaultBaseExecutionSpace>;
+                         DefaultBaseExecutionSpace>,
+      LogicalMemorySpace>;
 
   using device_type = Kokkos::Device<execution_space, memory_space>;
 
@@ -227,7 +236,7 @@ class SharedAllocationRecord<Kokkos::Experimental::LogicalMemorySpace<
                                                SharesAccessSemanticsWithBase>;
   using RecordBase = SharedAllocationRecord<void, void>;
 
-  SharedAllocationRecord(const SharedAllocationRecord&) = delete;
+  SharedAllocationRecord(const SharedAllocationRecord&)            = delete;
   SharedAllocationRecord& operator=(const SharedAllocationRecord&) = delete;
 
   static void deallocate(RecordBase* arg_rec) {
@@ -437,5 +446,34 @@ struct DeepCopy<Kokkos::Experimental::LogicalMemorySpace<
 };
 }  // namespace Impl
 
+namespace Tools {
+namespace Experimental {
+template <class BaseExecutionSpace, class MemorySpace>
+struct DeviceTypeTraits<Kokkos::Experimental::LogicalExecutionSpace<
+    BaseExecutionSpace, MemorySpace>> {
+  static constexpr DeviceType id = DeviceTypeTraits<BaseExecutionSpace>::id;
+  static int device_id(const Kokkos::Experimental::LogicalExecutionSpace<
+                       BaseExecutionSpace, MemorySpace>& exec) {
+    return DeviceTypeTraits<BaseExecutionSpace>::device_id(exec);
+  }
+};
+}  // namespace Experimental
+}  // namespace Tools
+
+namespace Impl {
+template <class BaseExecutionSpace, class MemorySpace, class FunctorType,
+          class... Traits>
+class ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>,
+                  Kokkos::Experimental::LogicalExecutionSpace<
+                      BaseExecutionSpace, MemorySpace>>
+    : public ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>,
+                         BaseExecutionSpace> {
+  using Base = ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>,
+                           BaseExecutionSpace>;
+
+ public:
+  using Base::Base;
+};
+}  // namespace Impl
 }  // namespace Kokkos
 #endif  // KOKKOS_LOGICALSPACES_HPP
```

**Comment by dalg24** [comment]
How does that help?  You still would not be able to access views

**Comment by masterleinad** [comment]
I was mostly looking into making #5544 work without modifying the test by making sure that the associated execution space can access the memory space. This doesn't solve the issue with testing view accessibility.

**Comment by PhilMiller** [comment]
Relative to Kokkos 3.6, I was using `LogicalMemorySpace` to test that some code does not access particular View instances except via `deep_copy`

https://github.com/DARMA-tasking/magistrate/blob/develop/tests/unit/test_kokkos_serialize_special.cc#L119

When I went to update the tests to 3.7 or 4.0, the referenced `static_assert` failed on line 130, just trying to construct the initial View instance in the logical space. Even without initialization, it still won't compile an inaccessible view without an associated execution space that could access it:

```c++
struct TestSpaceNamer {
  static constexpr const char* get_name() { return "TestSpace"; }
};

using fake_memory_space = Kokkos::Experimental::LogicalMemorySpace<
    Kokkos::HostSpace, Kokkos::DefaultHostExecutionSpace, TestSpaceNamer,
    Kokkos::Experimental::LogicalSpaceSharesAccess::no_shared_access>;

TEST(defaultdevicetypeKokkosViewContentsTest, test_logical_device_view_contents) {
  // Create an inaccessible View
  using LogicalViewType = Kokkos::View<int*, fake_memory_space>;
  auto lv = LogicalViewType(Kokkos::view_alloc("lv", Kokkos::WithoutInitializing), 1); // static_assert fails

  // Initialize a value
  Kokkos::deep_copy(lv, 3);
}
```

Why are we enforcing this in the allocation path, and not the initialization path?

For contrast, the unmanaged case compiles fine:

```c++
struct TestSpaceNamer {
  static constexpr const char* get_name() { return "TestSpace"; }
};

using fake_memory_space = Kokkos::Experimental::LogicalMemorySpace<
    Kokkos::HostSpace, Kokkos::DefaultHostExecutionSpace, TestSpaceNamer,
    Kokkos::Experimental::LogicalSpaceSharesAccess::no_shared_access>;

TEST(defaultdevicetypeKokkosViewContentsTest, test_logical_device_view_contents) {
  // Create an inaccessible View
  using LogicalViewType = Kokkos::View<int*, fake_memory_space>;
  int a;
  auto lv = LogicalViewType(&a, 1);

  // Initialize a value
  Kokkos::deep_copy(lv, 3);
}
```
But, for the code I'm trying to test, unmanaged views aren't supported, so that's no good.

**Comment by ajpowelsnl** [comment]
@dalg24, @masterleinad - is this still something we want to do?  Wasn't this discussed in the context of Kokkos Tools?  If so, then maybe @vlkale might weigh in to help us establish priority...?

**Comment by dalg24** [comment]
Hi @PhilMiller.  Sorry I had missed your reply.  I agree with your analysis and opened #6555 to fix this issue you reported above (in https://github.com/kokkos/kokkos/issues/5609#issuecomment-1490777893).

But that aside, I still think that the logical memory space is in practice not really useful because at the end of the day the data is still not accessible from within kernel code.

**Comment by PhilMiller** [comment]
See my comment on your PR for how logical space was useful. We wanted something that would only be accessible via `deep_copy`, and it gave us that. I think it would potentially be useful for testing other code that wants to ensure freedom from use of shared/UVM memory in whatever places.

**Comment by dalg24** [comment]
> I think it would potentially be useful for testing other code that wants to ensure freedom from use of shared/UVM memory in whatever places.

Please elaborate, I do not see how that would work.

**Comment by ajpowelsnl** [comment]
removed in #6557
