### ISSUE TITLE
Need to revisit detection of number of processors on Windows

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5631]
It would seem that we're not actually doing anything for the Windows case right now.
https://github.com/kokkos/kokkos/blob/c4df87cd35b162620c8e0f294dffa25980f35fa7/core/src/impl/Kokkos_CPUDiscovery.cpp#L51-L53
https://github.com/kokkos/kokkos/blob/c4df87cd35b162620c8e0f294dffa25980f35fa7/core/src/impl/Kokkos_CPUDiscovery.cpp#L82-L84

https://stackoverflow.com/questions/22767620/mingw-missing-sysconf-sc-nprocessors-onln
Has a suggestion for the rough equivalent to what the current code is doing.

_Originally posted by @PhilMiller in https://github.com/kokkos/kokkos/pull/5630#discussion_r1020524656_

**Comment by dalg24** [comment]
Is there a good reason not to just use `std::thread::hardware_concurrency()`?

**Comment by PhilMiller** [comment]
It if works, that sounds like it would be great. Ideally, it could be used to replace `processors_per_node` entirely

**Comment by mhoemmen** [comment]
> Is there a good reason not to just use `std::thread::hardware_concurrency()`?

Works pretty well for me with MSVC: https://godbolt.org/z/sEPa5GaTK

I haven't followed the latest MSVC, but I know they were doing a lot of work on their OpenMP implementation.  That might change how you would want to implement processor discovery.
