### ISSUE TITLE
Trilinos nightly test failures in MueLu: MueLu_UnitTestsTpetra_MPI_1 and MueLu_UnitTestsTpetra_MPI_4 unit tests

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5643]
Nightly Trilinos builds with MueLu enabled fail in the `MueLu_UnitTestsTpetra_MPI_1` and `MueLu_UnitTestsTpetra_MPI_4` tests with cuda/11.2 and gcc/8.3.0 on Power9+Volta70 arch in Cuda and OpenMP builds.

`MueLu_UnitTestsTpetra_MPI_1` output failure:
```
574. ParameterListInterpreter_std_complex0double0_int_longlong_Kokkos_Compat_KokkosOpenMPWrapperNode_BlockCrs_UnitTest ... WARNING: Using inefficient BlockCrs Multiply Placeholder
...
 Setup Smoother (MueLu::Ifpack2Smoother{type = RELAXATION})

 p=0: *** Caught standard std::exception of type 'std::runtime_error' :

  /ascldap/users/ndellin/trilinos/Trilinos/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp:977:

  Throw number = 401

  Throw test that evaluated to true: info > 0

  GETF2 or GETRI failed on = 1 diagonal blocks.
 [FAILED]  (0.0557 sec) ParameterListInterpreter_std_complex0double0_int_longlong_Kokkos_Compat_KokkosOpenMPWrapperNode_BlockCrs_UnitTest
 Location: /ascldap/users/ndellin/trilinos/Trilinos/packages/muelu/test/unit_tests/ParameterList/ParameterListInterpreter.cpp:105
```

The failing line in ifpack2 https://github.com/trilinos/Trilinos/blob/c7521148774a413445e5e31b02976742fe6d58ea/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp#L975-L977 occurs following calls to the `InvertDiagBlocks` kernel that fails following either the Tpetra GETF2 or GETRI routines called here 
https://github.com/trilinos/Trilinos/blob/c7521148774a413445e5e31b02976742fe6d58ea/packages/ifpack2/src/Ifpack2_Relaxation_def.hpp#L841-L854 
and defined here 
https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_BlockView.hpp

The tests above pass with the Trilinos develop branch, but fail when tested with kokkos and kokkos-kernels develop branches. Scanning through the Ifpack2 and Tpetra routines, it doesn't look like any kokkos-kernels routines are called so I'm filing under Kokkos for now

**Reproducer**:
```bash
# Repos
git clone -b kokkos-promotion https://github.com/trilinos/Trilinos.git
git clone -b develop https://github.com/kokkos/kokkos.git
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Configure
module load openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1 cmake/3.24.2 boost/1.70.0/gcc/8.3.1

cmake \
 -D CMAKE_CXX_COMPILER=`which mpicxx` \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER=`which mpicc` \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER=`which mpifort` \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 -D CMAKE_CXX_STANDARD=17 \
 -D BUILD_SHARED_LIBS=OFF \
\
 -D TPL_ENABLE_CUDA:STRING=OFF \
 -D TPL_ENABLE_MPI:STRING=ON \
 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \
 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \
 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \
\
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
\
-D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_Netcdf=OFF \
\
 -D Trilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
  -D Kokkos_ENABLE_OPENMP=ON \
  -D Kokkos_ENABLE_CUDA=OFF \
  -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
  -D Kokkos_ENABLE_CUDA_UVM=ON \
  -D Kokkos_ARCH_VOLTA70=ON \
  -D Kokkos_ARCH_POWER9=ON \
  -D Kokkos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_KokkosKernels=ON \
  -D KokkosKernels_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_ENABLE_CUDA=OFF \
  -D Tpetra_INST_SERIAL:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_INST_PTHREAD:BOOL=OFF \
  -D Tpetra_INST_CUDA:BOOL=OFF \
  -D Tpetra_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Sacado=ON \
  -D Sacado_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Belos=ON \
  -D Belos_ENABLE_TESTS=OFF \
\
 -D Trilinos_ENABLE_MueLu=ON \
  -D MueLu_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Zoltan2=ON \
  -D Zoltan2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Ifpack2=ON \
  -D Ifpack2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Intrepid2=ON \
  -D Intrepid2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_ShyLU_NodeTacho=OFF \
 -D Trilinos_ENABLE_Zoltan2Sphynx=OFF \
\
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
  -DKokkosKernels_ENABLE_SPARSE=ON \
  -DKokkosKernels_ENABLE_GRAPH=ON \
  -DKokkosKernels_ENABLE_BLAS=ON \
  -DKokkosKernels_ENABLE_BATCHED=ON \
$TRILINOS_DIR

```

**Comment by masterleinad** [comment]
What does the backtrace look like?

**Comment by ndellingwood** [comment]
I ran it through gdb but the test failure didn't kill the run for a backtrace, will have to go through more manual debugging

**Comment by PhilMiller** [comment]
Is this potentially related to https://github.com/trilinos/Trilinos/issues/11280 ?

**Comment by PhilMiller** [comment]
Failure hasn't been seen recently. Removing blocking label, but leaving open for tracking.

**Comment by ajpowelsnl** [comment]
@ndellingwood, @crtrott - Should this issue be a blocker?

**Comment by PhilMiller** [comment]
My comment and tag removal was a reflection of discussion of exactly that question in last week's meeting. It wasn't capricious.

**Comment by ajpowelsnl** [comment]
@ndellingwood -- How's this issue looking in the context of Trilinos Nightly Testing?  Are we closer to resolution?

**Comment by ndellingwood** [comment]
@ajpowelsnl I'm seeing the failure in builds with Hip but not the other backends; I don't think this is a blocker on the kokkos side, but I'll dig into this more

**Comment by ajpowelsnl** [comment]
@ndellingwood - how's this test been behaving?

**Comment by ndellingwood** [comment]
Hi @ajpowelsnl , had another failure this week with gcc/8.3.0 OpenMP testing on Power9
https://jenkins-son.sandia.gov/view/Kokkos/job/KokkosEco_Trilinos_Weaver_Gcc830_OpenMP_opt/142/

Let's keep this open for now

**Comment by ajpowelsnl** [comment]
hey @ndellingwood - any news / progress on this issue?

**Comment by ndellingwood** [comment]
These tests still randomly fail on occasion. Cross-referencing https://github.com/trilinos/Trilinos/issues/11209 , which should be preferred for tracking this (the value in this issue may be an additional configuration for testing)

**Comment by masterleinad** [comment]
Tracked in trilinos/Trilinos#11209.
