### ISSUE TITLE
Disabling macro KOKKOS_IMPL_WORKAROUND_ICE_IN_TRILINOS_WITH_OLD_INTEL_COMPILERS triggers internal compiler errors with intel compilers

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5651]
**Describe the bug**
Testing Kokkos develop branch with intel compilers after disabling the macro `KOKKOS_IMPL_WORKAROUND_ICE_IN_TRILINOS_WITH_OLD_INTEL_COMPILERS` (to workaround ICE in Trilinos packages with intel compilers) results in internal compiler errors when compiling Kokkos unit tests (in this case `TestSerial_LocalDeepCopy.cpp`).

This occurs when specifying non-SNB architectures (reproduced with SKX, BDW). From past experience with Trilinos builds, the ICE occurs when vectorization flags e.g. `-xCORE-AVX2` are on the compile line

This was reported by Trilinos/intrepid2 developers while investigating ways to resolve ICE in Intrepid2 builds without the macro

**TestSerial_LocalDeepCopy.cpp make -j1 VERBOSE=1 output**:
```
cd /ascldap/users/ndellin/kokkos/testing/Intel1905/core/unit_test && /projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-parallel-studio/professional.2019.5/gcc/8.3.0/base/r2foxm2/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc -DKOKKOS_DEPENDENCE -I/ascldap/users/ndellin/kokkos/tpls/gtest -I/ascldap/users/ndellin/kokkos/testing/Intel1905/core/unit_test -I/ascldap/users/ndellin/kokkos/core/unit_test -I/ascldap/users/ndellin/kokkos/core/unit_test/category_files -I/ascldap/users/ndellin/kokkos/testing/Intel1905 -I/ascldap/users/ndellin/kokkos/testing/Intel1905/core/src -I/ascldap/users/ndellin/kokkos/core/src -I/ascldap/users/ndellin/kokkos/core/src/../../tpls/desul/include -I/ascldap/users/ndellin/kokkos/testing/Intel1905/containers/src -I/ascldap/users/ndellin/kokkos/containers/src -I/ascldap/users/ndellin/kokkos/testing/Intel1905/algorithms/src -I/ascldap/users/ndellin/kokkos/algorithms/src -I/ascldap/users/ndellin/kokkos/testing/Intel1905/simd/src -I/ascldap/users/ndellin/kokkos/simd/src -O2 -g -DNDEBUG -xCORE-AVX2 -qopenmp -std=gnu++17 -MD -MT core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_LocalDeepCopy.cpp.o -MF CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_LocalDeepCopy.cpp.o.d -o CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_LocalDeepCopy.cpp.o -c /ascldap/users/ndellin/kokkos/testing/Intel1905/core/unit_test/serial/TestSerial_LocalDeepCopy.cpp
": internal error: 101003_1112

compilation aborted for /ascldap/users/ndellin/kokkos/testing/Intel1905/core/unit_test/serial/TestSerial_LocalDeepCopy.cpp (code 4)
make[2]: *** [core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_LocalDeepCopy.cpp.o] Error 4
make[2]: Leaving directory `/home/ndellin/kokkos/testing/Intel1905'
make[1]: *** [core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/all] Error 2
make[1]: Leaving directory `/home/ndellin/kokkos/testing/Intel1905'
make: *** [all] Error 2

```

This was tested with this diff to disable the macro (by only defining for unsupported pre-intel/19 compilers):
```diff
diff --git a/core/src/Kokkos_Macros.hpp b/core/src/Kokkos_Macros.hpp
index 7035113..2fb189b 100644
--- a/core/src/Kokkos_Macros.hpp
+++ b/core/src/Kokkos_Macros.hpp
@@ -219,7 +219,7 @@
 #endif
 
 // FIXME Workaround for ICE with intel <=21 in Trilinos
-#if (KOKKOS_COMPILER_INTEL <= 2100)
+#if (KOKKOS_COMPILER_INTEL <= 1800)
 #define KOKKOS_IMPL_WORKAROUND_ICE_IN_TRILINOS_WITH_OLD_INTEL_COMPILERS
 #endif
```

**Please also include the following items to support reproducing the bug**
**Reproduce** (kokkos-dev-2):
```bash
source /projects/sems/modulefiles/utils/sems-v2-modules-init.sh
module load sems-cmake/3.24.3 sems-intel/19.0.5

cmake -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_BDW=ON -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_STANDARD=17 -DKokkos_ENABLE_TESTS=ON $KOKKOS_PATH

```

* The internal compiler errors do not occur if the arch is not specified, for example removing the `-DKokkos_ARCH_BDW=ON` option from the cmake line

**Comment by ndellingwood** [comment]
The errors also occurred when I tested on a machine with SKX and Intel oneAPI 2021.5.0
```
bash-4.2$ icpc --version
icpc (ICC) 2021.5.0 20211109
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.
```

**Comment by ndellingwood** [comment]
Cross-referencing some past PRs and related issues

* PR introducing `KOKKOS_IMPL_WORKAROUND_ICE_IN_TRILINOS_WITH_OLD_INTEL_COMPILERS` for Serial backend: https://github.com/kokkos/kokkos/pull/4407
* Issue tracking discussion of workaround with the OpenMP backend: https://github.com/kokkos/kokkos/issues/5290
* PR with workaround to the above: https://github.com/kokkos/kokkos/pull/5305
* Trilinos related issue with BDW arch: https://github.com/trilinos/Trilinos/issues/10806

**Comment by masterleinad** [comment]
@ndellingwood Can you clarify the motivation for trying to remove the macro for compilers that we thought needed it? From the information in the pull request title, we would expect an ICE, right? 
Or is this just to keep track of trilinos/Trilinos#10806?

**Comment by ndellingwood** [comment]
@masterleinad correct, removing the macro we would expect to see ICE in Trilinos, but I had not encountered ICE with intel builds in Kokkos' unit tests directly (at least at the time of #4407)

At one point there was discussion and desire to remove the workaround (ideally part of 4.0), but if this is more of a "wish list" type item rather than a requirement or release blocker then this issue can either go into the backlog or be closed.

If we continue with the current workaround, then we will need to pull in the changes from PR #5305 to the develop branch for the 4.0 release in order for OpenMP testing with intel compilers to pass with Trilinos (those changes were only applied to the 3.7.00 release and workaround e.g. trilinos/Trilinos#10806)

Adding @dalg24 and @crtrott for clarification on the path forward for 4.0 (keeping the workaround and pulling in #5305 to develop v.s. addressing ICE in this issue and potentially more stuff masked by this existing case)

**Comment by ndellingwood** [comment]
Updated the OP to more clearly indicate the ICE in Kokkos unit tests occurred with `TestSerial_LocalDeepCopy.cpp`

**Comment by crtrott** [comment]
Just to make that clear, the intrepid failure did occur wihtout what Nathan was changing here, just by changing the OpenMP backend to how current develop is. Our unit tests are currently fine in develop, while if you copy develop into Trilinos it will crash intrepid. I.e. the thing you did here, by truning off that macro is NOT the same as my reproducer for intrepid, in which Kokkos unit tests were fine.

**Comment by ajpowelsnl** [comment]
@ndellingwood - are next steps for this issue clear, or should we discuss in today's meeting?

**Comment by ndellingwood** [comment]
> are next steps for this issue clear, or should we discuss in today's meeting?

@ajpowelsnl @crtrott Not at all clear to me on the path forward, here's my understanding of the issues:

* With #4407 and #5305 we added workarounds for intel compilers that prevents ICE for example with builds of Intrepid2; in order for Intrepid2 devs to reproduce the ICE and attempt to refactor code to no longer need this workaround, I suggested disabling the workaround (see the diff in OP)
* While Intrepid2 investigated the occurrences of ICE with intel/19 and disabling the workaround, the first occurrence of ICE that showed up was with calls to `Kokkos::deep_copy`; if those hadn't occurred, there would also be other locations within Intrepid2 with ICE; enabling Kokkos unit tests within Trilinos in that same build also demonstrated ICE in the Kokkos unit tests themselves
* When testing Kokkos standalone from the repo (not the snapshot into Trilinos) with the workaround disabled (for the Serial backend) I reproduced ICE with intel/19 and newer intel compilers, the first occurrence with the `TestSerial_LocalDeepCopy.cpp` unit tests

**Comment by ndellingwood** [comment]
I filed this issue with focus on the ICE that occurs within Kokkos' unit tests (independent of Trilinos or Intrepid2) with intel compilers and the serial backend when disabling the workaround of #4407 (the change in #5305 was only committed to 3.7.*).
If the plan is for the workaround of #4407 to remain then this issue can be closed
There currently are no occurrences of ICE with the OpenMP backend when building Kokkos unit tests with the develop branch.

**Comment by ndellingwood** [comment]
If I'm misunderstanding something, may be it is regarding what needs to be addressed in Intrepdi2; if the focus there is supposed to be a refactor (or something else) to drop the need for the #5305 workaround with the OpenMP backend, but we aren't concerned with #4407 and the Serial backend then I provided incorrect instructions for how to reproduce the ICE (the diff in the OP drops the workaround for both cases, which may have conflated problems)

**Comment by crtrott** [comment]
I think ther error you are seeing is actually coming from OpenMP, not Serial. If you turn OpenMP off it goes away actually.

**Comment by ajpowelsnl** [comment]
Hi @ndellingwood -- can you confirm that this fix fully addresses the ICE problem?

**Comment by ndellingwood** [comment]
@ajpowelsnl yes, the ICE problems with stand-alone Kokkos and unit tests were resolved; there are still issues with ICE in Trilinos and intel builds, but that is separate from the failures reported in this issue
