### ISSUE TITLE
Unmanaged view constructor doesn't check that num arguments matches rank

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#5654]
**Describe the bug**
I think this is probably a bug. If it's intentional behavior for some use case, feel free to close.

In this program:
```
#include <Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  Kokkos::DefaultExecutionSpace{}.print_configuration(std::cout);
  {
    int myArray[10];
    //All OK
    Kokkos::View<int, Kokkos::HostSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> myView0D(myArray, 10);
    Kokkos::View<int*, Kokkos::HostSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> myView1D(myArray, 10);
    Kokkos::View<int**, Kokkos::HostSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>> myView2D(myArray, 10);

    //Constructor for Kokkos View 'managed0D' has mismatched number of arguments. Number of arguments = 1 but dynamic rank = 0
    Kokkos::View<int, Kokkos::HostSpace> managed0D("managed0D", 10);

    //OK, one argument matches the rank, 1
    Kokkos::View<int*, Kokkos::HostSpace> managed1D("managed1D", 10);

    //Constructor for Kokkos View 'managed2D' has mismatched number of arguments. Number of arguments = 1 but dynamic rank = 2 
    Kokkos::View<int**, Kokkos::HostSpace> managed2D("managed2D", 10);
  }
  Kokkos::finalize();
  return 0;
}
```

Unmanaged views of dynamic ranks 0, 1 and 2 are constructed pointing to a C-style array, but in each case only one extent is passed. No compile or runtime errors are thrown by this.

But when passing only 1 extent to a managed view constructor, there is an runtime exception whenever the dynamic rank is not 1. **Should the Unmanaged constructor throw a similar exception**? (I actually just made a typo that would have been caught by this, forgetting to add a "*" to the view's data type)

**Comment by dalg24** [comment]
Looked a bit more into it and confirming this is a bug that needs fixing.
Related to #4618, #5188 and #5190.

**Comment by dalg24** [comment]
Unfortunately, just like for regular (managed) views, we can only diagnose this at runtime in the current implementation.
The fix is rather obvious
```diff
diff --git a/core/src/Kokkos_View.hpp b/core/src/Kokkos_View.hpp
index c3be55181..a29d3c23e 100644
--- a/core/src/Kokkos_View.hpp
+++ b/core/src/Kokkos_View.hpp
@@ -1494,6 +1494,20 @@ class View : public ViewTraits<DataType, Properties...> {
                      typename Impl::ViewCtorProp<P...>::pointer_type>::value,
         "Constructing View to wrap user memory must supply matching pointer "
         "type");
+
+    size_t i0 = arg_layout.dimension[0];
+    size_t i1 = arg_layout.dimension[1];
+    size_t i2 = arg_layout.dimension[2];
+    size_t i3 = arg_layout.dimension[3];
+    size_t i4 = arg_layout.dimension[4];
+    size_t i5 = arg_layout.dimension[5];
+    size_t i6 = arg_layout.dimension[6];
+    size_t i7 = arg_layout.dimension[7];
+
+    Impl::runtime_check_rank(
+        traits::rank, traits::rank_dynamic,
+        std::is_same<typename traits::specialize, void>::value, i0, i1, i2, i3,
+        i4, i5, i6, i7, "**UNMANAGED**");
   }

   // Simple dimension-only layout
```
but we will need to add test which probably means some sync up with #5190

**Comment by masterleinad** [comment]
I added a commit to #5190 addressing this.

**Comment by ajpowelsnl** [comment]
@masterleinad, @brian-kelley -- does #5190 resolve the problem?  If so, can we close?  If not, what's left to do on the issue?

**Comment by masterleinad** [comment]
Yes, #5190 will resolve this but it's not merged.

**Comment by ajpowelsnl** [comment]
> Yes, #5190 will resolve this but it's not merged.

Is it ready to be merged?  If so, I'll nudge ...

**Comment by masterleinad** [comment]
> Is it ready to be merged? If so, I'll nudge ...

https://github.com/kokkos/kokkos/pull/5190#pullrequestreview-1034554262

**Comment by ajpowelsnl** [comment]
@masterleinad - is this item still in progress?  What does #5190 need before merging?
