### ISSUE TITLE
Make `ExecutionSpace::concurrency()` a non-static member function

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#5655]
`ExecutionSpace::concurrency()` is currently declared as a static member function in all backends and this is an issue because the concurrency is really a property of an execution space instance, not from its type.

This is something we knew we would have to deal with for a while but we can't procrastinate much longer.
In particular, it is problematic as we add support for execution space instances to parallel host backends.
Apropos, #5105 attempts to work around that issue by providing `OpenMP::concurrency(OpenMP const& = OpenMP()) -> int`

The change from static to non-static member function is a breaking change but the fix on the user-side is rather trivial
```C++
int concurrency = Kokkos::DefaultExecutionSpace::concurrency();  // does not compile any more
// change to
int concurrency = Kokkos::DefaultExecutionSpace().concurrency();  // using default-constructed execution space
// or
int concurrency = execution_space.concurrency();  // calling member function on an instance
```

The intent of this issue is to announce our intent to make this change and to formulate a plan for the transition.

**Comment by PhilMiller** [comment]
4.0 would be a really nice timeframe to make such a change. We didn't deprecate to provide a warning or anything, but I think users would survive without too much grumbling if we did it ASAP

**Comment by dalg24** [comment]
Unfortunately I can't think of any way to emit warnings because we would not be able to "overload" on the static member function.
