### ISSUE TITLE
Initializing View on host, then updating on device.

### ISSUE THREAD

**Issue by JosefRuzicka** [kokkos/kokkos#5658]
Hello, I'm trying to initialize a 1D View of doubles by assigning each a value read from a .txt file. Since the values come in order in the file I wanted to serially execute this on the host. 
After the initialization is done I want to use the View in a parallel region executed on device.
Using CudaUVMSpace I get invalid memory access on the initialization, any ideas on how I could approach this?

CODE: 
```
Kokkos::initialize(argc, argv);
{
typedef Kokkos::Cuda ExecSpace;
typedef Kokkos::CudaUVMSpace MemSpace;
typedef Kokkos::View<double*, MemSpace> ViewVectorType;
ViewVectorType particles("particles", length*DIMENSIONS);

// Create view on host.                                                                                                                                  
ViewVectorType::HostMirror h_particles = Kokkos::create_mirror_view(particles);
LoadParticles(argc, argv, h_particles, length, 0);  // INVALID MEMORY ACCESS HERE
// Copy view to device.
Kokkos::deep_copy( particles, h_particles );
// Here would come a parallel region where the device would update the values on particles.
```
// NOTE: LoadParticles opens a file and assigns value read in a line to a "particle" of the view  (Works on CPU exec space serially and with openMP)

**Comment by JosefRuzicka** [comment]
> If the invalid memory access is in `LoadParticles`m it's difficult to help without seeing how that is implemented.

The code is as follows.
particles is a 1D View of 3D coordenates, so [x0, y0, z0, x1, y1, y2, ..., xn, yn, zn] where n is the number of particles.

This initialization is not meant to be in a parallel region.
```
void LoadParticles(const int& argc, char** argv, Kokkos::View<double*> particles, const int length, const int seedValue)
{
    bool found = false;
    for(int i = 1 ; i < argc - 1 ; ++i)
    {
        std::string tmp = argv[i];
        if(tmp == "-particles")
        {
            loadParticleFile(particles, length, argv[i+1]);
            found = true;
            break;
        }
    }
    if(!found)
    {
        printf("No file given. Initializing random particles\n");
        initializeParticles(particles, length,seedValue);
    }
}

void loadParticleFile(Kokkos::View<double*> particles, const int length, const std::string& path)
{
    FILE* file_buff;
    //Open file
    file_buff = fopen(path.c_str(), "r");
    if (file_buff == nullptr)
    {
        printf("Error al abrir archivo \n");
	exit(0);
    }
    else
    {
        double localX, localY, localZ;
        printf("Loading %s with length=%d\n", path.c_str(), length);
        for (int point = 0; point < length; point++)
        {
            fscanf(file_buff, "%le %le %le", &localX, &localY, &localZ);
            int base = point*DIMENSIONS;
            particles(base) = localX;
            particles(base+1) = localY;
            particles(base+2) = localZ;
        }
        fclose(file_buff);
    }
}
```

**Comment by dalg24** [comment]
`void loadParticleFile(Kokkos::View<double*> particles, ...)` here is your issue, the default memory space is presumably `CudaSpace` (can't really tell for sure w/o knowing how you configured Kokkos)

I am surprised that compiled at all (unless you enabled the (deprecated in 4.0) option `Kokkos_ENABLE_CUDA_UVM`.

**Comment by JosefRuzicka** [comment]
> `void loadParticleFile(Kokkos::View<double*> particles, ...)` here is your issue, the default memory space is presumably `CudaSpace` (can't really tell for sure w/o knowing how you configured Kokkos)
> 
> I am surprised that compiled at all (unless you enabled the (deprecated in 4.0) option `Kokkos_ENABLE_CUDA_UVM`.

Thank you for answering, but I'm unsure about what the solution to that may be. If pass the parameter as Kokkos::View<double*, Kokkos::HostSpace>, the view will then be incompatible with the device view when I get to deep copy.

**Comment by dalg24** [comment]
```C++
template <class HostAccessibleKokkosView>
void loadParticleFile(HostAccessibleKokkosView particles, const int length, const std::string& path)
{
  static_assert(Kokkos::is_view_v<HostAccessibleKokkosView> &&
      Kokkos::SpaceAccessibility<Kokkos::HostSpace, typename HostAccessibleKokkosView::memory_space>::accessible);
  ...
```
or
```C++
template <class... Properties>
void loadParticleFile(Kokkos::View<double*, Properties> particles, const int length, const std::string& path)
{
  static_assert(
      Kokkos::SpaceAccessibility<Kokkos::HostSpace, typename decltype(particles)::memory_space>::accessible);
  ...
```

**Comment by JosefRuzicka** [comment]
Thank you very much, I'll be looking into that, I haven't tried templates with Kokkos yet

**Comment by ajpowelsnl** [comment]
@JosefRuzicka - Please let us know if we can assist you further with this issue.  We can reopen if necessary.

**Comment by JosefRuzicka** [comment]
> @JosefRuzicka - Please let us know if we can assist you further with this issue. We can reopen if necessary.

Hello, I'm sorry, I was away for a few days. 
Thank you very much, if I have any issue I'll definitely come back for your help!
