### ISSUE TITLE
Architecture flags are incorrect for MSVC

### ISSUE THREAD

**Issue by torecalculation** [kokkos/kokkos#5663]
Hello

When building a Kokkos project with MSVC, architecture specific flags not passed correctly to the compiler.
For instance with -DKokkos_ARCH_HSW=ON, the flags `-march=core-avx2 -mtune=core-avx2` are passed.

This seems to be due to MSVC not being present in the compiler list in kokkos_arch.cmake.

```IF (KOKKOS_ARCH_HSW)
  SET(KOKKOS_ARCH_AVX2 ON)
  COMPILER_SPECIFIC_FLAGS(
    COMPILER_ID KOKKOS_CXX_HOST_COMPILER_ID
    Intel   -xCORE-AVX2
    NVHPC   -tp=haswell
    Cray    NO-VALUE-SPECIFIED
    DEFAULT -march=core-avx2 -mtune=core-avx2
  )
ENDIF()
```

**Comment by torecalculation** [comment]
This works well, thank you for your help.
Could this be possibly integrated in a future Kokkos release ?

**Comment by dalg24** [comment]
Will be in release 4.0
