### ISSUE TITLE
Error in generate_makefile.sh for Kokkos when Compiler is Empty String/Fails

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#568]
`generate_makefile.sh --compiler=which pgc++` will switch back to using `g++` if the `pgc++` is not in the `$PATH`.

This implies that an empty string does not force an error if `--compiler` option is specified. This should print an error and stop further execution. It could easily lead to a scenario where we inadvertently are not running the correct compiler.

**Comment by crtrott** [comment]
I'll do it.

**Comment by crtrott** [comment]
Fixed.
