### ISSUE TITLE
Problems in develop with ROCm 5.4

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#5690]
I have strange errors using ROCm 5.4 and develop. The test ` hip.mathspecialfunc_cbesselj1y1` sometimes fails with `Memory access fault by GPU node-4 (Agent handle: 0x67be760) on address 0x7ff7e9dca000. Reason: Unknown.`, sometimes it hangs, and rarely it passes. When the test passes another one fails. Everything works with master. I am going to do a bisect to find where the problem comes from.

**Comment by Rombur** [comment]
The faulty commit is c5f7108644555e8b0526b4fb2d46601dfbe5b8bc

**Comment by ajpowelsnl** [comment]
Should this issue be a blocker for Kokkos-4.0?

**Comment by romintomasetti** [comment]
We are also affected by this issue on ROCm 5.4 (VEGA906).

**Comment by ajpowelsnl** [comment]
> We are also affected by this issue on ROCm 5.4 (VEGA906).

@romintomasetti - Thank you for letting us know.  We're working to resolve the problem as quickly as possible.

**Comment by Rombur** [comment]
@romintomasetti We have talked to AMD and it's a compiler bug. Right now it's best usig ROCm 5.2. We have a fix for the problem but because the problem depends on the user kernel and the performance cost of the fix can be pretty large,  users will have to change the execution policy for the offending kernels. We won't apply the fix indiscriminately.

**Comment by Rombur** [comment]
#5796 introduces a workaround when hitting this bug

**Comment by fnrizzi** [comment]
@Rombur can we close this issue?

**Comment by maartenarnst** [comment]
Just an update :) I've tried with ROCm 6.0, and I found that the following tests now pass:
- `mathspecialfunc_cbesselj0y0`
- `mathspecialfunc_cbesselj1y1`
- `mathspecialfunc_cbesseli0k0`
- `mathspecialfunc_cbesseli1k1`

But the following two remaining tests still fail:
- `mathspecialfunc_cbesselh1stkind`
- `mathspecialfunc_cbesselh2ndkind`

The fix using the property tag doesn't seem to solve the issue for these two remaining tests.

Currently, the tests are disabled for certain hardcoded major/minor versions of ROCm. It may be necessary to add `6.0` for the two remaining failing tests. May be related to #6679.

**Comment by maartenarnst** [comment]
Just wanted to update this issue.

I've tried with ROCm 6.2, released a few days ago.

The two tests that failed with ROCm 6.0 still fail:
- `mathspecialfunc_cbesselh1stkind`
- `mathspecialfunc_cbesselh2ndkind`

Unfortunately, there is also a regression. Whereas these tests passed on ROCm 6.0, they fail again under ROCm 6.2:
 - `mathspecialfunc_cbesselj1y1 `
- `mathspecialfunc_cbesseli1k1 `

Our hardware is `zen3`/`amd_gfx906`. Our driver is the latest driver.

I think it would make sense to reopen this issue.

**Comment by Rombur** [comment]
> I think it would make sense to reopen this issue.

No, this issue is for ROCm 5.4 Please open a new issue.
