### ISSUE TITLE
Testing: Add testing for uvm and rdc

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#571]
We didn't test this nightly so something slipt through (Was caught by integration testing).

**Comment by ndellingwood** [comment]
Does this happen after the cuda uvm allocation test? If so something from pull request #526 may be the culprit.

**Comment by crtrott** [comment]
The bug I discovered is independent. And the commit after I merged 526 is clean (everything passes).

**Comment by crtrott** [comment]
The mechanisms are added. Need to set up the Jenkins jobs to actually run them.
