### ISSUE TITLE
rank() function for View and DynRankView

### ISSUE THREAD

**Issue by maartenarnst** [kokkos/kokkos#5717]
In Kokkos_View.hpp, there is around lines 644-648 a function `rank()` that is commented out and said "to be implemented".  This function mimics a function also called `rank()` from Kokkos_DynRankView.hpp.  It seems the idea of having the same function in both classes is to allow client code to work generically for `View` and `DynRankView`.  However, because the lines are commented out, this currently doesn't work.

If the lines in  Kokkos_View.hpp are uncommented, compilation errors occur, because, around line 345 in Kokkos_View.hpp, there is an `enum { rank = dimension::rank };`.  Thus, the compiler gets confused by the enum and the function having the same name.

Is having such a function `rank()` still under consideration?  And would there be a solution to the conflict with the enum?  Renaming the function `rank()` might be a solution, but it would likely require many changes in client code.

An example of a use case of such a function could be in Intrepid2.  In fact, Intrepid2 defines functors that are templated generally on a "viewType".  Ideally, these functors could then be instantiated for both View and DynRankView, which is often used in Intrepid2.  But, because some of the member functions of such functors in Intrepid2 call `rank()`, only instantiation for DynRankView is currently possible.  E.g. line 97 in `intrepid2/src/Cell/Intrepid2_CellToolsDefJacobian.hpp`, but there are several other instances where it would be beneficial to have `rank()` work for both `View` and `DynRankView`.

**Comment by dalg24** [comment]
For reference https://github.com/kokkos/kokkos/blob/d9d43bf62998854617e9224b074775aa1e6fa1ba/core/src/Kokkos_View.hpp#L644-L648

**Comment by dalg24** [comment]
> Is having such a function rank() still under consideration? 

Not actively, no.
We will bring it up at the developer meeting.  In the meantime feel free to upvote this if there is more interest in this feature.

Note that can be implemented on the user side as
```C++
template <class ViewLike>
auto rank(ViewLike const& v) {
  if constexpr (Kokkos::is_view_v<ViewLike>)
    return ViewLike::rank;
  else if constexpr (Kokkos::is_dyn_rank_view<ViewLike>)
    return v.rank();
  else
    static_assert(std::is_void_v<ViewLike>);
}

**Comment by crtrott** [comment]
Yeah we probably should fix this, unfortunately we did not take that into consideration during deprecation in 3.x :-(

**Comment by crtrott** [comment]
uhoh I have a nasty thought - not sure if this would fully work lol

```c++
template<int R>
struct RankImpl {
  constexpr int() const { return R; }
  constexpr int operator() () const { return R; }
}

template<...>
struct View {
...
   RankImpl rank;
...
};
```

**Comment by crtrott** [comment]
https://godbolt.org/z/xGxzr4cxd

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/d9d43bf62998854617e9224b074775aa1e6fa1ba/containers/src/Kokkos_DynRankView.hpp#L1301-L1306
and
https://github.com/kokkos/kokkos/blob/d9d43bf62998854617e9224b074775aa1e6fa1ba/core/src/Kokkos_View.hpp#L1677-L1684

**Comment by dalg24** [comment]
It turns out we already have a free function for it
https://github.com/kokkos/kokkos/blob/d9d43bf62998854617e9224b074775aa1e6fa1ba/core/src/Kokkos_View.hpp#L1677-L1684
and
https://github.com/kokkos/kokkos/blob/d9d43bf62998854617e9224b074775aa1e6fa1ba/containers/src/Kokkos_DynRankView.hpp#L1301-L1306

**Comment by maartenarnst** [comment]
Thanks @dalg24 and @crtrott!  

I've tried out Christian's idea in Kokkos.  

Around line 76 in Kokkos_View.hpp, I've added into the Kokkos::Impl namespace the following code:

```
template<unsigned R>
struct RankImpl {
  KOKKOS_INLINE_FUNCTION constexpr operator unsigned() const { return R; }  
  KOKKOS_INLINE_FUNCTION constexpr unsigned operator() () const { return R; }
};
```

And, around line 345, I've commented out `enum { rank = dimension::rank };` and replaced it with

```
static constexpr Impl::RankImpl<dimension::rank> rank = Impl::RankImpl<dimension::rank>();
```

I've compiled it in Kokkos develop in an openMP build and a Cuda build.  Everything compiles and all tests pass.

I've also tried it in our PDE code that uses Trilinos.  This also works, and we can now indeed call `rank()` on a view.

**Comment by crtrott** [comment]
We are considering doing this but aren't 100% convinced that it doesn't have bad side effects somewhere (one thing I know will break is `printf("%i\n",view_type::rank)` which did work before. 

As Damien said: `Kokkos::rank(view);` will work for DynRankView and normal View and is already in Kokkos. So that would be a way to do this without modifying Kokkos and or Trilinos.

**Comment by maartenarnst** [comment]
Thanks!  No problem to stay with the current code of course.

If you should have a chance to consider this further with the Kokkos team, that would be great.  Even just clarifying/confirming the Kokkos team's current recommended approach for this (e.g. the free function) may be helpful.

E.g., thinking of the Intrepid2 example, the calls to `rank()` currently restrict the use of the Intrepid2 functors to DynRankView, even though they are templated on a general `ViewType`.  We would like to use them more generally with View in our PDE code, and this might also be the case for other users.  To go to the Intrepid2 team to propose a change, knowing the Kokkos team's recommended approach would probably be helpful in a discussion to make progress.

Thanks in any case.

**Comment by crtrott** [comment]
Yeah free function is what we recommend for now.

**Comment by maartenarnst** [comment]
Thanks, @crtrott !  Thanks for the recommendation.  That's helpful indeed to proceed.  I'll close the issue.
