### ISSUE TITLE
`ccache` is not configured properly in CI

### ISSUE THREAD

**Issue by cz4rs** [kokkos/kokkos#5723]
**Describe the bug**
We try to use `ccache` to speed up builds in Kokkos CI, but the right option (`CMAKE_CXX_COMPILER_LAUNCHER`) is not provided at the configuration stage.
https://github.com/kokkos/kokkos/blob/f54c04c77250be0cf82f349d451859f4854e4d9e/.github/workflows/continuous-integration-workflow.yml#L109-L113
Statistics from [an actual build](https://github.com/kokkos/kokkos/actions/runs/3762406268/jobs/6395074913):
```
Summary:
  Hits:               0 /  432 (0.00 %)
    Direct:           0 /  432 (0.00 %)
    Preprocessed:     0 /  432 (0.00 %)
  Misses:           432
    Direct:         432
    Preprocessed:   432
  Uncacheable:      146
Primary storage:
  Hits:               0 /  864 (0.00 %)
  Misses:           864
  Cache size (GB): 0.11 / 0.25 (45.65 %)
```

**Comment by cz4rs** [comment]
Alright, this might be more complicated. From the same build, it seems that `CMake` is picking up `ccache` even without the configuration option present:
```
-- Check for working CXX compiler: /usr/lib/ccache/clang++ - skipped
```
but all `ubuntu:latest` based builds have 0 hits.

On the other hand, `fedora:latest` gets:
```
Cacheable calls:    447 /  580 (77.07%)
  Hits:              16 /  447 ( 3.58%)
    Direct:          15 /   16 (93.75%)
    Preprocessed:     1 /   16 ( 6.25%)
  Misses:           431 /  447 (96.42%)
Uncacheable calls:  133 /  580 (22.93%)
Local storage:
  Cache size (GB): 0.03 / 0.25 (12.73%)
```

**Comment by dalg24** [comment]
It comes from https://github.com/kokkos/ci-containers/blob/35cf1d5510272d37d256c4973ea0f1c3090f8b0d/ubuntu#L12-L14
which I don't like so much

**Comment by ajpowelsnl** [comment]
Do we have a plan and timeline for addressing this issue?

**Comment by cz4rs** [comment]
> Do we have a plan and timeline for addressing this issue?

I am planning to check if we can remove the problematic lines in ubuntu dockerfile (now that we pass the `CMAKE_CXX_COMPILER_LAUNCHER` to CMake):
https://github.com/kokkos/kokkos/blob/728e3d3b341dd775fcb7ccbe72d41228ab7e3a94/.github/workflows/continuous-integration-workflow.yml#L108
This has pretty low priority though, so I haven't given it a proper try yet.

**Comment by cz4rs** [comment]
Side note: it might be worth checking if we can drop following lines as well:
https://github.com/kokkos/kokkos/blob/728e3d3b341dd775fcb7ccbe72d41228ab7e3a94/.github/workflows/continuous-integration-workflow.yml#L51-L52
This is not related to `ccache`, just another clean-up for CI (seems to be working fine in benchmarks workflow).

**Comment by cz4rs** [comment]
TODO: check if the issue persists after https://github.com/kokkos/ci-containers/pull/33 was merged.

**Comment by cz4rs** [comment]
Cache is now created and restored correctly.
[Sample build from `develop`](https://github.com/kokkos/kokkos/actions/runs/4198496496/jobs/7282196199):

```
Cache restored successfully
Cache restored from key: kokkos-ubuntu:latest-clang++-Debug--refs/heads/develop-2b532d1f9e5306504c7c17326ce5216540427900
```

```
Summary:
  Hits:              55 /  439 (12.53 %)
    Direct:          49 /  439 (11.16 %)
    Preprocessed:     6 /  390 (1.54 %)
  Misses:           384
    Direct:         390
    Preprocessed:   384
Primary storage:
  Hits:             446 /  888 (50.23 %)
  Misses:           442
  Cache size (GB): 0.23 / 0.25 (90.55 %)
  Cleanups:          22
```

```
Cache Size: ~212 MB (222577590 B)
Cache saved successfully
Cache saved with key: kokkos-ubuntu:latest-clang++-Debug--refs/heads/develop-15989dd3a1edb72bbc178fc74d081502e32dd3d6
```

Possible improvements in the future:
- [adding more `restore-keys`](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)
- finetuning the configuration of `ccache` (max size, compression)
