### ISSUE TITLE
Missing KokkosTargets.cmake file

### ISSUE THREAD

**Issue by Yaraslaut** [kokkos/kokkos#5728]
**Describe the bug**
following cmake script will fail
```
include(FetchContent)
FetchContent_Declare(
  Kokkos
  GIT_REPOSITORY https://github.com/kokkos/kokkos.git
  GIT_TAG        5ad609661e570ba6aa7716a26a91cb67d559f8a2
)
FetchContent_MakeAvailable(Kokkos)
find_package(Kokkos PATHS "${FETCHCONTENT_BASE_DIR}/kokkos-build")
```
error itself

```
CMake Error at build/_deps/kokkos-build/KokkosConfig.cmake:42 (INCLUDE):
  INCLUDE could not find requested file:

    .../build/_deps/kokkos-build/KokkosTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)
```

**Comment by dalg24** [comment]
I think you misunderstood how CMake's FetchContent works.
```
.
├── CMakeLists.txt
└── example.cpp

1 directory, 2 files
```
```CMake
cmake_minimum_required(VERSION 3.16)
project(Example CXX)

include(FetchContent)
FetchContent_Declare(
  Kokkos
  GIT_REPOSITORY https://github.com/kokkos/kokkos.git
  GIT_TAG        5ad609661e570ba6aa7716a26a91cb67d559f8a2
)
FetchContent_MakeAvailable(Kokkos)
#find_package(Kokkos PATHS "${FETCHCONTENT_BASE_DIR}/kokkos-build")

add_executable(example example.cpp)
target_link_libraries(example Kokkos::kokkos)
```
```C++
#include <Kokkos_Core.hpp>

int main(int argc, char *argv[]) {
  Kokkos::initialize(argc, argv);
  Kokkos::finalize();
}
```

Then run
```
cmake -B build -DKokkos_ENABLE_THREADS=ON
cmake --build build
```

**Comment by dalg24** [comment]
You use either `FetchContent` or `find_package`.
See the documentation [here](https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#fetchcontent-and-find-package-integration)

**Comment by Yaraslaut** [comment]
> You use either `FetchContent` or `find_package`. See the documentation [here](https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#fetchcontent-and-find-package-integration)

Oh indeed, dumb me. Thanks for the prompt reply
I am closing this issue then, 
maybe it worth to add in documentation that it can be fetched directly withoud `find_package` command invocation

**Comment by dalg24** [comment]
> maybe it worth to add in documentation that it can be fetched directly withoud find_package command invocation

This is tricky.  If we do that, some will copy/paste without trying to understand the implications, and before you know the next bug report will be from someone trying to link against another library that also uses Kokkos.
In this kind of situations, I would rather defer to CMake's documentation and on the Kokkos side just make sure that we follow best practices.

**Comment by Yaraslaut** [comment]
> 

I see, makes sense
