### ISSUE TITLE
KNL performance test question

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#573]
This may be only loosely a Kokkos issue, but I have a code based on Kokkos which shows good OpenMP scaling on a KNC card but not on the KNL nodes of bowman and ellis. On the latter, scaling reverses at about 4 threads and 16 threads is as slow as serial. Scaling is linear up to 16 threads on KNC. I'm building Kokkos in Trilinos; is there a simple Kokkos performance test I can run to see if this is an issue with my code or with my build environment ?

**Comment by nmhamster** [comment]
Dan, have you looked at VTune profiles for the code?

**Comment by ibaned** [comment]
Is there a webpage with info on running vtune on these machines ? anyway I'll give it a try.

**Comment by crtrott** [comment]
Please post run command and environment.

**Comment by ibaned** [comment]
environment should be entirely defined by this `.bash_profile`:
```
module load boost/1.55.0/openmpi/1.10.4/intel/17.0.098
module load intel/compilers/17.0.098
module load openmpi/1.10.4/intel/17.0.098
module load zlib/1.2.8
module load git/2.8.2
module load cmake/3.5.2
```
run commands:
```
14:24:59:ellis-lsm1:~/build/omega_h$ salloc -n 1 -t 2:00:00 -p knl-delta
salloc: Granted job allocation 1032875
bash-4.2$ export OMP_NUM_THREADS=1
bash-4.2$ mpirun -n 1 ./src/perf_tests 
...
building a 42x42x42 box took 4.3104 seconds
....
bash-4.2$ export OMP_NUM_THREADS=4
bash-4.2$ mpirun -n 1 ./src/perf_tests 
...
building a 42x42x42 box took 2.77069 seconds
...
bash-4.2export OMP_NUM_THREADS=16
bash-4.2$ mpirun -n 1 ./src/perf_tests 
...
building a 42x42x42 box took 4.62896 seconds
```
working on figuring out vtune now.

**Comment by crtrott** [comment]
You are probably binding to a single core. Run with: mpirun -np 1 -bind-to socket and export first:
KMP_AFFINITY=compact (for using all hyper threads on a core)
KMP_AFFINITY=scatter (for using a single thread per core)

**Comment by ibaned** [comment]
@ctrott I just came to the same conclusion through trying to run vtune. You're absolutely right.

```
bash-4.2$ ./src/perf_tests 
...
building a 42x42x42 box took 0.337181 seconds
...
bash-4.2$ mpirun -n 1 ./src/perf_tests 
...
building a 42x42x42 box took 4.90091 seconds
...
bash-4.2$ mpirun -n 1 --bind-to socket ./src/perf_tests 
...
building a 42x42x42 box took 0.335005 seconds
```

Thank you both for the help !
