### ISSUE TITLE
`HPX::in_parallel` should return something useful

### ISSUE THREAD

**Issue by msimberg** [kokkos/kokkos#5744]
It currently always returns `false`. Reference for self: https://kokkos.github.io/kokkos-core-wiki/API/core/execution_spaces.html?highlight=in_parallel. I think this could be implemented by wrapping calls of user-defined callables in an RAII object that sets and unsets a thread-local `bool` which can be queried by `in_parallel`.

**Comment by ajpowelsnl** [comment]
Hi @msimberg -- would you be able to develop a PR for your implementation idea?  Many thanks for submitting this issue.

**Comment by msimberg** [comment]
@ajpowelsnl yeah, that's the plan, which is why I've assigned it to myself :wink: This issue is just a spinoff from this comment: https://github.com/kokkos/kokkos/pull/5628#discussion_r1065484512 that I didn't want to do in the same PR.

**Comment by ajpowelsnl** [comment]
@msimberg -- Any progress in your implementation?  Any update you could provide would be greatly appreciated!

**Comment by msimberg** [comment]
Yeah, almost everything, except for the execution space-specific behaviour. I was planning to still do that, but given the tentative decision in https://github.com/kokkos/kokkos/issues/6032#issuecomment-1662765779 I probably won't do that. Even if the decision is to deprecate `in_parallel` I might still upgrade the implementation to be able to do https://github.com/kokkos/kokkos/pull/6051 better for HPX. In any case, this can stay closed.
