### ISSUE TITLE
Have Kokkos gracefully handle multiple calls to init/finalize

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#5749]
In E3SM we have mutliple independent sub-packages that use Kokkos. The host model is not even aware of Kokkos, so it cannot handle init/finalize at the beginning/end of execution. Instead, each subcomponent tries to init/finalize Kokkos.

To avoid multiple init/finalize calls, in some subcomponent we added a bit of code, which checks if Kokkos is already init-ed; if it is, the component will skip initialization and will not call Kokkos::finalize. However, this _relies_ on the order of initialization and finalization to be Last-In-First-Out, as well as on the assumption that all component (and sub-component, tpls, ...) possibly using Kokkos are also performing this kind of check.

It would be nice if Kokkos could "kept track" of the number of init calls, and perform finalization only on the last call. Something like this

- first time `initialize` is called: actually _do_ initialize, and set `g_num_customer=1`.
- every following call to `initialize` simply increments `g_num_customers`. Probably also check that, if initialization settings are passed, they are compatible with the settings set by the first init call.
- when `finalize` is called, decrement `g_num_customers`, and only call the actual finalization function wheh the counter reaches 0.

This would allow apps which indirectly use Kokkos in multiple places to avoid headaches. Even if we add init/finalize routines in our main driver, we need to make sure all possible TPLs are not calling init/finalize without verifying the current status of Kokkos, and that might not be possible for all TPLs/submodules.

Is something along this line possible?

**Comment by stanmoore1** [comment]
Related issues: https://github.com/kokkos/kokkos/issues/4195, https://github.com/kokkos/kokkos/issues/4126, https://github.com/kokkos/kokkos/issues/5208

**Comment by bartgol** [comment]
> Related issues: #4195, #4126, #5208

Just to clarify after looking at the issues linked: I'm ok with not allowing init after finalize. That is, even in the scenario I'm envisioning, all calls to init will certainly happen _before_ the last call to finalize (and, most likely, they will _all_ happen before the _first_ call to finalize).

**Comment by bartgol** [comment]
Also, if this behavior does not violate any Kokkos assumption, I can certainly help putting up a tentative PR.

**Comment by ajpowelsnl** [comment]
> Also, if this behavior does not violate any Kokkos assumption, I can certainly help putting up a tentative PR.

@bartgol -- there are Booleans to help you manage initialization / finalization:  https://kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/initialize.html?highlight=is_initialized

**Comment by bartgol** [comment]
> > Also, if this behavior does not violate any Kokkos assumption, I can certainly help putting up a tentative PR.
> 
> @bartgol -- there are Booleans to help you manage initialization / finalization: [kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/initialize.html?highlight=is_initialized](https://kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/initialize.html?highlight=is_initialized)

Thanks, I'm aware of that. As I wrote above, we are indeed doing that. But we are also using TPLs thad we have no control over, and which may or may not do those checks. Furthermore, relying on those booleans requires that the order of init is reversed when it comes to finalization, since we'd likely do something like "if it was already inited when we call init, then someone else is handling it, so we don't finalize either".

It would be much easier to have kokkos keep a reference count, so that all subpackages can simply call init/finalize just as they would do in their own standalone builds, knowing that kokkos will handle multiple customers internally.

**Comment by masterleinad** [comment]
We decided to only allow calling `Kokkos::initialize` and `Kokkos::finalize` once to avoid confusion about some calls not having any effect (and arguments being ignored).
What I am doing in one project is to let the first package that wants to call `Kokkos::initialize` subscribe `Kokkos::finalize` to `std::atexit` and don't do anything if `Kokkos` was already initialized. Of course, this requires that none of the calls to  `initialize` pass crucial configuration options.

**Comment by dalg24** [comment]
> Also, if this behavior does not violate any Kokkos assumption, I can certainly help putting up a tentative PR.

No, this violates the Kokkos semantics.  Just like with MPI, you can initialize the Kokkos execution environment at most once.  This is a deliberate design choice.  Although we sympathize with the issue E3SM is currently facing and we recognize that it is likely not an isolated problem, we stand by that choice.  Allowing multiple calls to initialize and finalize is not just reference counting.  For instance what would we do with subsequent calls to `Kokkos::initialize` that resolve to a different configuration?
We had discussed it at length at the last release briefing (see [slides 27-36](https://github.com/kokkos/kokkos-tutorials/blob/main/Other/ReleaseBriefings/release-37.pdf)).  If you want to reach out to me on Slack I can sit with you and help find a solution on the E3SM side.  I understand it may require changes to individual components if they are not aware of each others, but in short they just can't unconditionally call `Kokkos::initialize` if they want to compose with other pieces of software that also use Kokkos.

**Comment by bartgol** [comment]
> Something like [dealii/dealii@`616f0b2`/source/base/kokkos.cc#L29-L38](https://github.com/dealii/dealii/blob/616f0b2deb0fe744f580b635f433f4b6cba39243/source/base/kokkos.cc#L29-L38).

Thanks! That's a good solution to the issue "the first subpkg to call Kokkos::init must be the last to call Kokkos::finalize".

@dalg24 Thanks for the clarification and for the pointer to the briefing. I will think a bit to find out what the best strategy is, to minimize the code disruption in all subpackages.

**Comment by crtrott** [comment]
Just to make clear: the deal.ii approach is NOT a general recommended approach by the Kokkos team. As stated before this issue is directly comparable to MPI, which has the same restrictions with respect to initialization and finalization - for much the same underlying technical reasons. And generally the recommendation is that a library documents as a requirement for a user to call MPI_Init / Kokkos::initialize before the first use of the library.

Note that for example Trilinos Teuchos::GlobalMPISession also implements this restriction. Its constructor will abort if MPI is already initialized. In its documentation it provides also the same justification, for not simply not calling initialize.

```
   It would not be reasonble to simply not not call MPI_Initialize() becuase
   this would ignore the input arguments that the user (you) should be
   expecting to be read.
```
