### ISSUE TITLE
Unified Host Thread Teams for TeamPolicy and TaskTeam

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#577]
The thread team implementation are independent and redundant between TeamPolicy and TaskTeam capabilities.  Merge these implementations by choosing the best components from each.
The Task-DAG capability must allow the team size to be selected when the TaskScheduler is constructed, following the TeamPolicy.

**Comment by hcedwar** [comment]
Current team collectives are not consistent:
```
  void team_broadcast( T & , source_rank ) const ; // in-place
  T team_reduce( T const & , JoinOp ) const ;         // return value
  T team_scan( T const & , T * global_value = 0 ) const ; // return value
```
Should they be made consistent using in-place?  This would also be consistent with the nested `parallel_reduce`
```
  void team_broadcast( T & , source_rank ) const ;
  void team_reduce( T & , JoinOp ) const ;
  void team_scan( T & , T * global_value = 0 ) const ;
```
This would also remove potential concerns with returning large `T` values.

**Comment by hcedwar** [comment]
Also need to address custom reductions for the `team_reduce` and `parallel_reduce( TeamThreadRange ...`
Related to issue #521

**Comment by hcedwar** [comment]
Done for Serial and OpenMP.  Pending for Threads and Qthreads.

**Comment by hcedwar** [comment]
Only applies to new StdThreads back-end, old pthreads back-end destined for removal so not updating.
See #255

**Comment by dsunder** [comment]
Reissue if still desired behavior
