### ISSUE TITLE
Trilinos compilation error (Tpetra) following removal of legacy atomic headers

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5815]
**Describe the bug**
Following removal of the legacy atomic headers compilations of Trilinos began failing in Tpetra:

```
In file included from <https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/ws/Trilinos/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp>:68,
                 from <https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/ws/Build/packages/tpetra/core/src/Tpetra_MultiVector_DOUBLE_INT_LONG_LONG_CUDA.cpp>:69:
<https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/ws/Trilinos/packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp>:61:10: fatal error: impl/Kokkos_Atomic_Generic.hpp: No such file or directory
 #include "impl/Kokkos_Atomic_Generic.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is the list of new commits since prior successful build:

Fix sycl.scratch_align test ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#e8c08e2c0cf37786a65574b030679cceb7658108))
    Improve comments in TestTeam.hpp ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#53cc29764415a73732e66a730501f01b3756cd2a))
    Purge logic around desul atomics being enabled at configuration time ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#05cb3f5114897d622c9adaba7e0a17432b8e113d))
    Purge macro guards for desul atomics being enabled or not ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#c3fe1d607b14f526a46c548ee6e1da17099dd554))
    Get rid of #ifdef KOKKOS_ENABLE_IMPL_DESUL_ATOMICS in unit tests ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#44140f7212e3fb3a2a4e2f21094ac0895c568721))
    Remove a whole bunch of Kokkos leagacy atomics headers ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#52953c824bac56ba6031c260901247f7259e9ef9))
    Update diff_files (might be worth revisiting logic) ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#7f5ea60095120aa02e1f348d09adfdd98511d8c6))
    Drop `KOKKOS_ENABLE_IMPL_DESUL_ATOMICS` macro define altogether ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#796e964880159e8660b975bde4dfc793dd58e19a))
    Fixup deleted wrong branch in HIP locks ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#d745c31735f983d8a40c0729c69f0f08a4467725))
    Move Kokkos::{Impl:: -> }::ALL_t definition and add using-declaration in Impl:: namespace for backward compatibility ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#7869915c0896fd5331115af3c413d0f0dc40dd15))
    Stay off Kokkos::Impl::ALL_t ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#5304a40801b2a083031a9efb5509332ac8fe0e2a))
    Guard using-declaration in Impl:: namespace with #ifdef KOKKOS_ENABLE_DEPRECATED_CODE_4 ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#e91f7e880916b4f217f32450f17ac966f835e4a4))
    Drop anonymous namespace around definitions of ALL, WithoutInitializing, and AllowPadding ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#4519e4ca891259d6e0a4d39b5838cadee4a78bca))
    Per review dropped superfluous const-qualifiers ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#05f6a9aab37d9d6b022a3ae2c2c21a5b25affd0d))
    Move all SYCL headers into SYCL directory ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#6d90db37bc5b0f18dee459ebdb1f833f044093c8))
    Fixup GH Actions compiler warnings (#5780) ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#236e892a2884f0b2b7431d5ff680f9af9de57746))
    Issue warnings when using Kokkos::Impl::ALL_t ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#ddefe61809380bc8205018a72ec5d16446e2f32d))
    Drop desul_* helper functions in tasking ([details](https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/116/changes#adb3141e8d99dcc6449d9b8bab143662d761265c))

This occurred in Cuda builds so far, will update if host builds fail as well

Adding @dalg24

**Comment by dalg24** [comment]
Bug is in Trilinos.  `"impl/Kokkos_Atomic_Generic.hpp"` is a private header.

**Comment by dalg24** [comment]
Great...
https://github.com/trilinos/Trilinos/blob/2e6c1fd693208061bebe91fc19d101f52512e3ba/packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp#L789-L812

**Comment by ndellingwood** [comment]
> Bug is in Trilinos. `"impl/Kokkos_Atomic_Generic.hpp"` is a private header.

Right, I'll drop the Bug label

**Comment by ajpowelsnl** [comment]
@PhilMiller , @dalg24 - Is this issue resolved?  If so, may we close?

**Comment by dalg24** [comment]
Yes resolved.
