### ISSUE TITLE
Issues when building miniFE on Apple M1

### ISSUE THREAD

**Issue by gonzalobg** [kokkos/kokkos#5835]
**Describe the bug**

When building MiniFE on Apple M1 there are two issues:
* Apple Clang does not support `-fopenmp` at all, the current workaround in `Makefile.kokkos` to use `-fopenmp=libomp` does not work anymore. No `-fopenmp` should be used with this compiler; the user could pick a non-Apple clang instead.
* Apple M1 is an Arm CPU but `Makefile.kokkos` tries to use `-mavx`.

**Please also include the following items to support reproducing the bug**
1. compilers (with versions): Apple Clang 14.0 for the -fopenmp issue; Clang 15.0 for the -mavx issue.
2. Kokkos release or commit used (i.e., the sha1 number): 5ad609661e570ba6aa7716a26a91cb67d559f8a2
3. platform and backend: Apple M1
4. cmake configure command: miniFE does not use CMake, it uses `Makefile.kokkos`
5. output from cmake command: see 4.
6. code needed to reproduce the bug: `git clone https://github.com/Mantevo/miniFE.git  && cd miniFE/kokkos/src && KOKKOS_PATH=XYZ make`
7. command line needed to reproduce the bug: see 6.
7. please also attach the `KokkosCore_config.h` header file (generated during the build);

**Comment by masterleinad** [comment]
Wouldn't this issue rather belong at https://github.com/Mantevo/miniFE/issues?

**Comment by dalg24** [comment]
@gonzalobg would you be willing/able to submit a patch to `Makefile.kokkos` that resolves the issue you are reporting?

**Comment by gonzalobg** [comment]
Being realistic I don't have the bandwidth to do this sorry :(

**Comment by ajpowelsnl** [comment]
Reopen issue if it becomes a priority.
