### ISSUE TITLE
cmake resets CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by oksanaguba** [kokkos/kokkos#5863]
We noticed this in e3sm, where after one successful build, the 2nd build would fail.

Reproduced with current master like this:

```
cmake -DKokkos_ENABLE_SERIAL=On -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=${HOME}/tmp/aaa ~/kokkos-repo
...
[ac.onguba@chrlogin1 tmp]$ grep PREFIX CMakeCache.txt 
CMAKE_INSTALL_PREFIX:PATH=/home/ac.onguba/tmp/aaa
//CMAKE_INSTALL_PREFIX during last run
_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX:INTERNAL=/home/ac.onguba/tmp/aaa

cmake -DKokkos_ENABLE_SERIAL=On -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=${HOME}/tmp/aaa ~/kokkos-repo
...
[ac.onguba@chrlogin1 tmp]$ grep PREFIX CMakeCache.txt 
CMAKE_INSTALL_PREFIX:PATH=/usr/local
//CMAKE_INSTALL_PREFIX during last run
_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX:INTERNAL=/usr/local
```

**Comment by dalg24** [comment]
Can't reproduce on the latest release (3.7.01) nor on develop.

**Comment by oksanaguba** [comment]
I forgot to add -- we also saw it on one of machines, but not on another (we tried 2, i think). Should i try to get environment?

**Comment by oksanaguba** [comment]
I probably should search for a commit that caused the issue on the machine with problematic env.

**Comment by dalg24** [comment]
Please investigate why this error only shows on that one machine and not on the other.

**Comment by crtrott** [comment]
Note: we do not anywhere in our cmake mess with CMAKE_INSTALL_PREFIX. So I doubt that trying to isolate a commit on our side which will introduce this behavior will be successful. More likely that this has something to do with your cmake version or otherwise with your system config.

**Comment by jgfouca** [comment]
Hi all,

I dug a bit on this and discovered some things.

I started with this config line:
```
cmake -DKokkos_ENABLE_SERIAL=On -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=$mydir ..
```

At the end of the first invocation, I had these correct values my cache:
```
CMAKE_INSTALL_PREFIX:PATH=$mydir
CMAKE_CXX_COMPILER:STRING=$absolute_path/icpc
```

In the second invocation, I see this during configuration:
```
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= icpc
```

And, in my cache prefix is now incorrect:
```
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_CXX_COMPILER:STRING=$absolute_path/icpc
```

So, the first invocation cached the absolute path to icpc. When I ran the same command again, again passing in only `icpc`, CMake interpreted that as a change to a cached variable so deleted the cache and re-ran itself. In that process, the CMAKE_PREFIX_INSTALL was lost.

I'm not sure if this is a problem with Kokkos or just the weirdness of CMake. If need be, we can work around this problem by passing the full path of icpc each time.

**Comment by dalg24** [comment]
Likely `-DKokkos_ENABLE_SERIAL=On` does not matter.
Do you see the same when you omit the CMAKE_CXX_COMPILER compiler option?  When you specify another compiler, say g++?
Please confirm whether you are configuring Kokkos by itself or within a larger project (via add_subdirectory or similar).
What CMake version are you using?

**Comment by crtrott** [comment]
I can't reproduce this. What is your cmake version? I tried 3.18 and 3.24

**Comment by jgfouca** [comment]
@dalg24 , the problem was originally observed as part of a larger project, but the reproducer I pasted above works (demonstrates the problem) with standalone Kokkos. You are correct that enable serial does not matter.

@crtrott , my cmake version is 3.24.2

If I omit the `-DCMAKE_CXX_COMPILER` option, CMake picks up cxx from my environment (CXX) which contains the absolute path, so everything works. Things also work if I use `-DCMAKE_CXX_COMPILER=$(which icpc)` because both the argument and the cache have the absolute path, so subsequent runs do not think the compiler has changed and the cache is not flushed.

**Comment by jgfouca** [comment]
Oh, for what it's worth, this is on the ANL machine chrysalis.

**Comment by jgfouca** [comment]
Another thing, to be clear, I am running the full cmake command twice:
```
% cmake  -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=$mydir ..
...
% cmake  -DCMAKE_CXX_COMPILER=icpc -DCMAKE_INSTALL_PREFIX=$mydir ..
...
CMAKE_INSTALL_PREFIX:PATH=/usr/local
```

**Comment by crtrott** [comment]
Do you actually need Kokkos to reproduce this? Or does a dummy cmake project behave the same way?

**Comment by dalg24** [comment]
For the record, James was able to reproduce with
```CMake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.12)
project(not_kokkos CXX)
add_executable(not_kokkos not_kokkos.cpp)
```
```C++
// not_kokkos.cpp
int main() {}
```
which demonstrates that this is not a Kokkos-specific issue.

**Comment by crtrott** [comment]
Sounds like this also showed up in a minimal non-kokkos cmake project - i.e. its not a kokkos issue.
