### ISSUE TITLE
Improve Kokkos::BinSort for repeated indices

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#5864]
Kokkos::BinSort is extremely slow for arrays with multiple repeated indices. This is coming from some buckets containing too many elements. As each bucket is being sorted by a single thread using bubble sort, this becomes very slow:
https://github.com/kokkos/kokkos/blob/5ad609661e570ba6aa7716a26a91cb67d559f8a2/algorithms/src/Kokkos_Sort.hpp#L438-L460

In general, in ArborX we typically use `BinSort` only for the host sorting, and delegate to Thrust/OneDPL for device sorts. I tried the following patch to improve the host sorting, and it seems to have fixed the issue.
```diff
--- a/algorithms/src/Kokkos_Sort.hpp
+++ b/algorithms/src/Kokkos_Sort.hpp
@@ -396,6 +396,26 @@ class BinSort {
   void operator()(const bin_sort_bins_tag& /*tag*/, const int i) const {
     auto bin_size = bin_count_const(i);
     if (bin_size <= 1) return;
+    constexpr bool use_std_sort =
+#if defined(KOKKOS_ENABLE_SERIAL) && defined(KOKKOS_ENABLE_OPENMP)
+        (std::is_same_v<exec_space, Kokkos::Serial> ||
+         std::is_same_v<exec_space, Kokkos::OpenMP>);
+#elif defined(KOKKOS_ENABLE_SERIAL)
+        std::is_same_v<exec_space, Kokkos::Serial>;
+#elif defined(KOKKOS_ENABLE_OPENMP)
+        std::is_same_v<exec_space, Kokkos::OpenMP>;
+#else
+        false;
+#endif
+    if (bin_size > 10 && use_std_sort) {
+      auto& bin_op_c   = bin_op;
+      auto& keys_rnd_c = keys_rnd;
+      std::sort(&sort_order(bin_offsets(i)),
+                &sort_order(bin_offsets(i) + bin_size),
+                [&bin_op_c, &keys_rnd_c](int i, int j) {
+                  return bin_op_c(keys_rnd_c, i, j);
+                });
+    } else {
       int upper_bound = bin_offsets(i) + bin_size;
       bool sorted     = false;
       while (!sorted) {
@@ -416,6 +436,7 @@ class BinSort {
         upper_bound--;
       }
     }
+  }
 };
 
 //----------------------------------------------------------------------------

```
In general, as long as the sort within a bin is improved in some way (through using external functions or writing your own), it resolves the issue.

**Comment by dalg24** [comment]
The logic in your patch belongs to `Kokkos::sort`.  If you ask for `BinSort` that's what you get.

**Comment by aprokop** [comment]
> The logic in your patch belongs to `Kokkos::sort`. If you ask for `BinSort` that's what you get.

No. `BinSort` is the sorting algorithm the works by using bins. I'm saying that the sorting within bins can be improved. It is different from using `std::sort` on the full array.

**Comment by dalg24** [comment]
I see.  Do you want to open a PR for it?

**Comment by aprokop** [comment]
> I see. Do you want to open a PR for it?

I'm not sure what the right way to do it. Using something like `std::sort` would improve the situation for host-based execution spaces. But it does not fix the problem for device-based. So, one would want to implement something else there. Maybe introsort.
