### ISSUE TITLE
CMake configuration of Kokkos 3.7.1 fails with CUDA 12.0

### ISSUE THREAD

**Issue by akohlmey** [kokkos/kokkos#5868]
**Describe the bug**
Running the command:
```
cmake -S . -B build  -D Kokkos_ENABLE_SERIAL=on -D Kokkos_ENABLE_CUDA=on -D Kokkos_ARCH_PASCAL90=on
```
stops with the error:
```
-- The project name is: Kokkos
nvcc fatal   : Value 'sm_35' is not defined for option 'gpu-architecture'
CMake Error at cmake/kokkos_compiler_id.cmake:12 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  cmake/kokkos_compiler_id.cmake:53 (kokkos_internal_have_compiler_nvcc)
  cmake/kokkos_tribits.cmake:215 (INCLUDE)
  CMakeLists.txt:189 (KOKKOS_SETUP_BUILD_ENVIRONMENT)
```

Changing bin/nvcc_wrapper as follows:
```
  diff --git a/bin/nvcc_wrapper b/bin/nvcc_wrapper
  index e1a208813..f8bf1c376 100755
  --- a/bin/nvcc_wrapper
  +++ b/bin/nvcc_wrapper
  @@ -12,8 +12,8 @@
   # or g++ as their back-end compiler.  The defaults can be overwritten
   # by using the usual arguments (e.g., -arch=sm_30 -ccbin icpc).
   
  -default_arch="sm_35"
  -#default_arch="sm_50"
  +#default_arch="sm_35"
  +default_arch="sm_60"
   
   #
   # The default C++ compiler.
```
Prevents the error and configuration completes.

**Please also include the following items to support reproducing the bug**
1. gcc 12.2, nvcc from CUDA 12.0.1 download
2. release-candidate-3.7.02 branch. It is fixed in develop.
3. Linux x86_64 with a GeForce GTX 1060 GPU.

**Any additional info**
We have noticed that with the copy of Kokkos bundled with LAMMPS (3.7.01) and fixed it there, but it seems appropriate to report that change upstream.

**Comment by dalg24** [comment]
Please try `-DKokkos_ARCH_PASCAL60=ON

**Comment by dalg24** [comment]
Also this is already cherry-picked into release candidate 3.7.2 (see #5693)

Essentially the arch you specified is wrong which triggers the auto detection attempt that has the `sm_35` flag that NVCC did not like.  If you fix the typo, you won't get the error.
