### ISSUE TITLE
Why I can't find this func: register_space_initializer()? 

### ISSUE THREAD

**Issue by mingygit** [kokkos/kokkos#5896]
When I see the "Kokkos_ExecSpaceManager.hpp", It say this: 
/* ExecSpaceManager - Responsible for initializing all the registered
 * backends. Backends are registered using the register_space_initializer()
 * function which should be called from a global context so that it is called
 * prior to initialize_spaces() which is called from Kokkos::initialize()
 */
Why I can't find this func: register_space_initializer()? Is it because it's an abstract name? Different names for different backends? If yes, can you give the corresponding function name of a specific backend? Thank you very much!

**Comment by masterleinad** [comment]
It should probably be `register_space_factory` instead of `register_space_initializer` and the former is called by `initialize_space_factory`.

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/948c6c69fc24879e507c8c86bee36490b4b11dbb/core/src/impl/Kokkos_ExecSpaceManager.hpp#L138-L142

The comment is out of date and was just copied from https://github.com/kokkos/kokkos/pull/5144/files#diff-6e58bf29b9c0c8cb173f1a4674af22eb89406f4f2f473e7138b36b357cfd1a7eL85-L89
A quick search through history before the refactor in #5144 shows that this function has never been committed into the code base.

**Comment by mingygit** [comment]
Thanks！

**Comment by PhilMiller** [comment]
Want to make a quick PR to fix the comment?
