### ISSUE TITLE
Subviews and Compile Time Dimension Question

### ISSUE THREAD

**Issue by tcfisher** [kokkos/kokkos#590]
I am trying to use subviews with compile time dimensions. I've seen solutions on other threads (#237) that don't seem to work in my case. I get the following error: 

> TPLs_src/Trilinos/packages/kokkos/core/src/KokkosExp_View.hpp: In instantiation of ?Kokkos::Experimental::View<DataType, Properties>::View(const Kokkos::Experimental::View<RT, RP ...>&, const Arg0&, Args ...) [with RT = double** [3][3]; RP = {Kokkos::Serial}; Arg0 = unsigned int; Args = {Kokkos::Experimental::Impl::ALL_t, Kokkos::Experimental::Impl::ALL_t, Kokkos::Experimental::Impl::ALL_t}; DataType = double* [3][3]; Properties = 
TPLs_src/Trilinos/packages/kokkos/core/src/KokkosExp_View.hpp:1166:7: error: static assertion failed: Subview construction requires compatible view and subview arguments

`Kokkos::View<double**[3][3]> a("a",10,16);`
`Kokkos::View<double*[3][3]> b(a,2,Kokkos::ALL(),Kokkos::ALL(),Kokkos::ALL());`

Is there something I'm doing incorrectly or is this not supported. In the case where there is only one compile time dimension, everything is fine. For example:
`Kokkos::View<double**[3]> a("a",10,16);`
`Kokkos::View<double*[3]> b(a,2,Kokkos::ALL(),Kokkos::ALL());`
compiles without issue.

**Comment by crtrott** [comment]
Which Kokkos version are you working with? This appears to work currently.

**Comment by crtrott** [comment]
I believe this was fixed in #473, which is part of Kokkos 2.02.00 (Oct 30).

**Comment by crtrott** [comment]
For the Kokos version check the CHANGELOG.md or config/master_history.txt

**Comment by tcfisher** [comment]
Oops. The version of Trilinos we are currently using is before that using 2.01.10. Sorry. I will let you know if I have problems with the updated version.

**Comment by crtrott** [comment]
no problem
