### ISSUE TITLE
CHANGELOG PATCH RELEASE: 4.0.1

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#5903]
This is the changelog for the upcoming Release 4.0.1

#### CUDA:

* Allow NVCC 12 to compile using C++20 flag [\#6020](https://github.com/kokkos/kokkos/pull/6020)
* Add CUDA Ada architecture support [\#6022](https://github.com/kokkos/kokkos/pull/6022)

#### HIP:

* Add support for AMDGPU target NAVI31 / RX 7900 XT(X): gfx1100 [\#6021](https://github.com/kokkos/kokkos/pull/6021)
* HIP: Fix warning from `std::memcpy` [\#6019](https://github.com/kokkos/kokkos/pull/6019)

#### SYCL:
* Fix `SYCLTeamMember` to take arguments for scratch sizes as `std::size_t` [\#5986](https://github.com/kokkos/kokkos/pull/5986)

### General Enhancements
* Fixup 4.0 change log [\#6023](https://github.com/kokkos/kokkos/pull/6023)

### Build System Changes 
* Cherry-pick TriBITS update from Trilinos [\#6037](https://github.com/kokkos/kokkos/pull/6037)
* CMake: update package compatibility mode when building within Trilinos [\#6013](https://github.com/kokkos/kokkos/pull/6013)

### Bug Fixes
* Fix an incorrectly returning size for SIMD uint64_t in AVX2 [\#6011](https://github.com/kokkos/kokkos/pull/6011)
* Desul atomics: wrong value for `desul::Impl::numeric_limits_max<uint64_t>` [\#6018](https://github.com/kokkos/kokkos/pull/6018)
* Fix warning in some user code when using std::memcpy [\#6000](https://github.com/kokkos/kokkos/pull/6000)

**Comment by ndellingwood** [comment]
For fast and easy snip of the issue directly to the CHANGELOG.md, please markdown format issue number and link as follows:
```
[\#N](https://github.com/kokkos/kokkos-kernels/pull/N)
```
(where "N" is the PR number)

**Comment by ajpowelsnl** [comment]
@crtrott, @dalg24, @Rombur -- does issue #5898 need to be fixed in this patch release?
