### ISSUE TITLE
Roadmap for using CombinedFunctorReducerType in ParallelReduce

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#5908]
Implementations:
- Serial: https://github.com/kokkos/kokkos/pull/5874
- Cuda: https://github.com/kokkos/kokkos/pull/5874
- Threads: https://github.com/kokkos/kokkos/pull/5894
- OpenMP: https://github.com/kokkos/kokkos/pull/5893
- HPX: https://github.com/kokkos/kokkos/pull/5895
- HIP: https://github.com/kokkos/kokkos/pull/5911
- SYCL: https://github.com/kokkos/kokkos/pull/5953
- OpenMPTarget: https://github.com/kokkos/kokkos/pull/5954
- OpenACC: https://github.com/kokkos/kokkos/pull/5949

Follow-ups:
-  Don't call the functor's destructor on the device for Serial and Cuda: https://github.com/kokkos/kokkos/pull/5910
- Fix reducer result check for Serial+HPX: #5971
- Use CombinedReducer in HostIterateTile: #5962
- Deduce `value_type` from return type in `paralle_reduce` and `parallel_scan`: #5976
- Cleanup: Remove `implements_new_reduce_interface` and wrappers. #5982
- Convert `ParallelScan`, too?  Already done in most backends. The remainder can be done together with the `generic_lambdas`.

**Comment by ajpowelsnl** [comment]
@masterleinad -- is all of the work associated with `parallel_reduce` wrapped up?  If so, can we close this issue?
