### ISSUE TITLE
release-candidate-4.0.0 - nvcc_wrapper add c files?

### ISSUE THREAD

**Issue by ARSanderson** [kokkos/kokkos#5914]
Could this addition be made to the nvcc_wrapper?

```diff
diff --git a/bin/nvcc_wrapper b/bin/nvcc_wrapper
index 2204514d1..af1dd6704 100755
--- a/bin/nvcc_wrapper
+++ b/bin/nvcc_wrapper
@@ -148,7 +148,7 @@ do
     remove_duplicate_link_files=1
     ;;
   #handle source files to be compiled as cuda files
-  *.cpp|*.cxx|*.cc|*.C|*.c++|*.cu)
+  *.cpp|*.cxx|*.cc|*.C|*.c++|*.cu|*.c)
     cpp_files="$cpp_files $1"
     ;;
```

**Comment by dalg24** [comment]
Are you able to open a PR (against the `develop` branch) with these changes?  If not, I can do it on your behalf.
As far as 4.0 is concerned it might be too late, but it can certainly make it into the 1st patch release.

**Comment by PhilMiller** [comment]
You changed the issue description pretty starkly from what was initially opened.

The change to the parameter type you originally noted may make sense.

Does the change to `nvcc_wrapper` somehow address that? If so, that makes me concerned that you've got C++ code in what looks like it should be a C file, and we'd just be convincing the compiler to treat it like C++. Otherwise, it makes sense that one might want to compile and link C/CUDA code using `nvcc_wrapper`.

**Comment by ARSanderson** [comment]
@dalg24 - I have a forked branch so was able to create a pull request as @PhilMiller just noted

@PhilMiller - I initially open the issue then found that it was due to a rebuild conflict. Once I started from scratch the issue was gone. At the same time I had nvcc_wrapper issue so rather open another just edited it.

**Comment by PhilMiller** [comment]
Ok, cool, thanks.

**Comment by dalg24** [comment]
Can you give a bit more context.  Are you dealing with external source code that uses the `.c` extension for C++ code??

**Comment by ARSanderson** [comment]
A colleague, when compiling a hybrid Cuda with Kokkos-Cuda version of our code base was running into issues. Semi-legacy code that we still compare against though we have moved to using only Kokkos.

**Comment by dalg24** [comment]
Do you own that semi-legacy code?  Is changing the source file extension an option?  I don't think I have ever heard of `.c` (lowercase c) used for C++, only C.

**Comment by dalg24** [comment]
Glad you figured it out.
