### ISSUE TITLE
Cannot enable KOKKOS_ENABLE_CUDA_ATOMICS 

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5920]
**Describe the bug**
Cannot enable KOKKOS_ENABLE_CUDA_ATOMICS even when set it as on using ccmake. When using 

I enable KOKKOS_ENABLE_CUDA_ATOMICS with ccmake, but in the example, it shows 

Cuda Atomics:
  KOKKOS_ENABLE_CUDA_ATOMICS: no

Device Execution Space:
  KOKKOS_ENABLE_CUDA: yes
Cuda Atomics:
  KOKKOS_ENABLE_CUDA_ATOMICS: no
Cuda Options:
  KOKKOS_ENABLE_CUDA_LAMBDA: yes
  KOKKOS_ENABLE_CUDA_LDG_INTRINSIC: yes
  KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE: no
  KOKKOS_ENABLE_CUDA_UVM: yes
  KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA: yes

Cuda Runtime Configuration:
macro  KOKKOS_ENABLE_CUDA      : defined
macro  CUDA_VERSION          = 12000 = version 12.0
Kokkos::Cuda[ 0 ] NVIDIA GeForce GTX 1650 capability 7.5, Total Global Memory: 3.815 G, Shared Memory per Block: 48 K : Selected

**Please also include the following items to support reproducing the bug**
1. compilers (with versions)
2. -- Setting default Kokkos CXX standard to 14
-- The project name is: Kokkos
-- Compiler Version: 12.0.140
-- kokkos_launch_compiler (/home/xiwang/Workspace/TDDA/contrib/kokkos-3.7.01/bin/kokkos_launch_compiler) is enabled...
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  TURING75
-- Using internal desul_atomics copy
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xiwang/Workspace/TDDA/build
3. Kokkos release or commit used (3.7.01)
4. platform and backend
5. cmake configure command
6. output from cmake command
7. code needed to reproduce the bug
8. command line needed to reproduce the bug
7. please also attach the `KokkosCore_config.h` header file (generated during the build);
**Any additional info**
Please provide any additional context about the issue here.

**Comment by masterleinad** [comment]
We are now using `desul` for atomics and have removed `Kokkos` own implementation for atomics. Is there a particular reason why you want `KOKKOS_ENABLE_CUDA_ATOMICS` to be defined?

**Comment by wangxi0706** [comment]
> We are now using `desul` for atomics and have removed `Kokkos` own implementation for atomics. Is there a particular reason why you want `KOKKOS_ENABLE_CUDA_ATOMICS` to be defined?

Thanks for your reply. I run the code "/kokkos-3.7.01/example/build_cmake_in_tree/cmake_example.cpp" using GPU, but the parallel_reduce return wrong results sometimes, I thought it is due to the absence of atomic function. Why would the result be wrong when using GPU?

  long count = 0;
  Kokkos::parallel_reduce(
      n, KOKKOS_LAMBDA(const long i, long& lcount) { lcount += (i % 2) == 0; },
      count);

**Comment by wangxi0706** [comment]
> We are now using `desul` for atomics and have removed `Kokkos` own implementation for atomics. Is there a particular reason why you want `KOKKOS_ENABLE_CUDA_ATOMICS` to be defined?

When I tried to enable Kokkos_ENABLE_DESUL_ATOMICS_EXTERNAL, it seems some files are absent. Will it influence the correctness of Kokkos parallel program?

Could not find a package configuration file provided by "desul" with any of
  the following names:

    desulConfig.cmake
    desul-config.cmake

  Add the installation prefix of "desul" to CMAKE_PREFIX_PATH or set
  "desul_DIR" to a directory containing one of the above files.  If "desul"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  contrib/kokkos-3.7.01/cmake/kokkos_tribits.cmake:247 (INCLUDE)
  contrib/kokkos-3.7.01/CMakeLists.txt:189 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

**Comment by masterleinad** [comment]
> Thanks for your reply. I run the code "/kokkos-3.7.01/example/build_cmake_in_tree/cmake_example.cpp" using GPU, but the parallel_reduce return wrong results sometimes, I thought it is due to the absence of atomic function. Why would the result be wrong when using GPU?

That would be concerning. What does your configuration look like (same question you are asked when opening an issue)?

**Comment by wangxi0706** [comment]
> > Thanks for your reply. I run the code "/kokkos-3.7.01/example/build_cmake_in_tree/cmake_example.cpp" using GPU, but the parallel_reduce return wrong results sometimes, I thought it is due to the absence of atomic function. Why would the result be wrong when using GPU?
> 
> That would be concerning. What does your configuration look like (same question you are asked when opening an issue)?


 
Configuration is like this:


#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
#error \
    "Do not include KokkosCore_config.h directly; include Kokkos_Macros.hpp instead."
#else
#define KOKKOS_CORE_CONFIG_H
#endif

// KOKKOS_VERSION % 100 is the patch level
// KOKKOS_VERSION / 100 % 100 is the minor version
// KOKKOS_VERSION / 10000 is the major version
#define KOKKOS_VERSION 30701

/* Execution Spaces */
#define KOKKOS_ENABLE_SERIAL
/* #undef KOKKOS_ENABLE_OPENMP */
/* #undef KOKKOS_ENABLE_OPENACC */
/* #undef KOKKOS_ENABLE_OPENMPTARGET */
/* #undef KOKKOS_ENABLE_THREADS */
#define KOKKOS_ENABLE_CUDA
/* #undef KOKKOS_ENABLE_HIP */
/* #undef KOKKOS_ENABLE_HPX */
/* #undef KOKKOS_ENABLE_MEMKIND */
/* #undef KOKKOS_ENABLE_LIBRT */
/* #undef KOKKOS_ENABLE_SYCL */

/* General Settings */
#define KOKKOS_ENABLE_CXX14
/* #undef KOKKOS_ENABLE_CXX17 */
/* #undef KOKKOS_ENABLE_CXX20 */

/* #undef KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE */
#define KOKKOS_ENABLE_CUDA_UVM
#define KOKKOS_ENABLE_CUDA_LAMBDA
/* #undef KOKKOS_ENABLE_CUDA_CONSTEXPR */
/* #undef KOKKOS_ENABLE_CUDA_LDG_INTRINSIC */
/* #undef KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC */
/* #undef KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS */
/* #undef KOKKOS_ENABLE_HPX_ASYNC_DISPATCH */
/* #undef KOKKOS_ENABLE_DEBUG */
/* #undef KOKKOS_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK */
/* #undef KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK */
/* #undef KOKKOS_ENABLE_PROFILING_LOAD_PRINT */
/* #undef KOKKOS_ENABLE_TUNING */
#define KOKKOS_ENABLE_DEPRECATED_CODE_3
#define KOKKOS_ENABLE_DEPRECATION_WARNINGS
/* #undef KOKKOS_ENABLE_LARGE_MEM_TESTS */
#define KOKKOS_ENABLE_COMPLEX_ALIGN
#define KOKKOS_ENABLE_IMPL_DESUL_ATOMICS
/* #undef KOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION */
/* #undef KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION */

/* TPL Settings */
/* #undef KOKKOS_ENABLE_HWLOC */
/* #undef KOKKOS_USE_LIBRT */
/* #undef KOKKOS_ENABLE_HBWSPACE */
#define KOKKOS_ENABLE_LIBDL
/* #undef KOKKOS_ENABLE_LIBQUADMATH */
/* #undef KOKKOS_IMPL_CUDA_CLANG_WORKAROUND */

#define KOKKOS_COMPILER_CUDA_VERSION 120

/* #undef KOKKOS_ARCH_SSE42 */
/* #undef KOKKOS_ARCH_ARMV80 */
/* #undef KOKKOS_ARCH_ARMV8_THUNDERX */
/* #undef KOKKOS_ARCH_ARMV81 */
/* #undef KOKKOS_ARCH_ARMV8_THUNDERX2 */
/* #undef KOKKOS_ARCH_A64FX */
/* #undef KOKKOS_ARCH_AMD_AVX2 */
/* #undef KOKKOS_ARCH_AVX */
/* #undef KOKKOS_ARCH_AVX2 */
/* #undef KOKKOS_ARCH_AVX512XEON */
/* #undef KOKKOS_ARCH_KNC */
/* #undef KOKKOS_ARCH_AVX512MIC */
/* #undef KOKKOS_ARCH_POWER7 */
/* #undef KOKKOS_ARCH_POWER8 */
/* #undef KOKKOS_ARCH_POWER9 */
/* #undef KOKKOS_ARCH_INTEL_GEN */
/* #undef KOKKOS_ARCH_INTEL_DG1 */
/* #undef KOKKOS_ARCH_INTEL_GEN9 */
/* #undef KOKKOS_ARCH_INTEL_GEN11 */
/* #undef KOKKOS_ARCH_INTEL_GEN12LP */
/* #undef KOKKOS_ARCH_INTEL_XEHP */
/* #undef KOKKOS_ARCH_INTEL_GPU */
/* #undef KOKKOS_ARCH_KEPLER */
/* #undef KOKKOS_ARCH_KEPLER30 */
/* #undef KOKKOS_ARCH_KEPLER32 */
/* #undef KOKKOS_ARCH_KEPLER35 */
/* #undef KOKKOS_ARCH_KEPLER37 */
/* #undef KOKKOS_ARCH_MAXWELL */
/* #undef KOKKOS_ARCH_MAXWELL50 */
/* #undef KOKKOS_ARCH_MAXWELL52 */
/* #undef KOKKOS_ARCH_MAXWELL53 */
/* #undef KOKKOS_ARCH_PASCAL */
/* #undef KOKKOS_ARCH_PASCAL60 */
/* #undef KOKKOS_ARCH_PASCAL61 */
/* #undef KOKKOS_ARCH_VOLTA */
/* #undef KOKKOS_ARCH_VOLTA70 */
/* #undef KOKKOS_ARCH_VOLTA72 */
#define KOKKOS_ARCH_TURING75
/* #undef KOKKOS_ARCH_AMPERE */
/* #undef KOKKOS_ARCH_AMPERE80 */
/* #undef KOKKOS_ARCH_AMPERE86 */
/* #undef KOKKOS_ARCH_AMD_ZEN */
/* #undef KOKKOS_ARCH_AMD_ZEN2 */
/* #undef KOKKOS_ARCH_AMD_ZEN3 */
/* #undef KOKKOS_ARCH_VEGA */
/* #undef KOKKOS_ARCH_VEGA900 */
/* #undef KOKKOS_ARCH_VEGA906 */
/* #undef KOKKOS_ARCH_VEGA908 */
/* #undef KOKKOS_ARCH_VEGA90A */

**Comment by wangxi0706** [comment]
> > Thanks for your reply. I run the code "/kokkos-3.7.01/example/build_cmake_in_tree/cmake_example.cpp" using GPU, but the parallel_reduce return wrong results sometimes, I thought it is due to the absence of atomic function. Why would the result be wrong when using GPU?
> 
> That would be concerning. What does your configuration look like (same question you are asked when opening an issue)?

With the reduce code like this:
  long count = 0;
  Kokkos::parallel_reduce(
      n, KOKKOS_LAMBDA(const long i, long &lcount) { lcount += (i % 2) == 0; },
      count);

The output is like this (parallel output is different from the serial output):

evice Execution Space:
  KOKKOS_ENABLE_CUDA: yes
Cuda Atomics:
  KOKKOS_ENABLE_CUDA_ATOMICS: no
Cuda Options:
  KOKKOS_ENABLE_CUDA_LAMBDA: yes
  KOKKOS_ENABLE_CUDA_LDG_INTRINSIC: yes
  KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE: no
  KOKKOS_ENABLE_CUDA_UVM: yes
  KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA: yes

Cuda Runtime Configuration:
macro  KOKKOS_ENABLE_CUDA      : defined
macro  CUDA_VERSION          = 12000 = version 12.0
Kokkos::Cuda[ 0 ] NVIDIA GeForce GTX 1650 capability 7.5, Total Global Memory: 3.815 G, Shared Memory per Block: 48 K : Selected

Number of even integers from 0 to 9999999999
  **Parallel: 705032704      0.006109**
**Sequential: 5000000000      2.383043**

**Comment by masterleinad** [comment]
Which `Kokkos` release/commit are you using?

**Comment by wangxi0706** [comment]
> KOKKOS_VERSION 30701

The lastest Kokkos v. 3.7.1

**Comment by wangxi0706** [comment]
> Which `Kokkos` release/commit are you using?

The lastest Kokkos v. 3.7.1

**Comment by wangxi0706** [comment]
> Which `Kokkos` release/commit are you using?

I just tested that kokkos-3.6.00 will yield the same problem.

macro  KOKKOS_ENABLE_CUDA      : defined
macro  CUDA_VERSION          = 12000 = version 12.0
Kokkos::Cuda[ 0 ] NVIDIA GeForce GTX 1650 capability 7.5, Total Global Memory: 3.815 G, Shared Memory per Block: 48 K : Selected
Number of even integers from 0 to 9999999998
  **Parallel: 705032704      0.006112
Sequential: 5000000000      3.378674**

**Comment by dalg24** [comment]
This is not a bug.
You are using the short form `Kokkos::parallel_reduce(N, ...` which is equivalent to `Kokkos::parallel_reduce(RangePolicy<>(0, N), ...`.  Since the index type is not specified as a template argument, it defaults to `Kokkos::DefaultExecutionSpace::size_type` which is `size_t` for the `Serial` backend and `unsigned int` for `Cuda`.
The upper bound you are using `9999999999` exceeds the maximum representable `unsigned int` which is `4294967295`, it wraps around and you get `N` equal to `1410065407`, meaning `705032704` is the right answer.

**Comment by wangxi0706** [comment]
> This is not a bug. You are using the short form `Kokkos::parallel_reduce(N, ...` which is equivalent to `Kokkos::parallel_reduce(RangePolicy<>(0, N), ...`. Since the index type is not specified as a template argument, it defaults to `Kokkos::DefaultExecutionSpace::size_type` which is `size_t` for the `Serial` backend and `unsigned int` for `Cuda`. The upper bound you are using `9999999999` exceeds the maximum representable `unsigned int` which is `4294967295`, it wraps around and you get `N` equal to `1410065407`, meaning `705032704` is the right answer.

Great! When I set RangePolicy<long>(0,N), the results seems good! Thanks very much !
