### ISSUE TITLE
Cannot Enable CUDA_RELOCATABLE_DEVICE as suggested in the tutorial.

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5922]
**Describe the bug**
In kokkos-tutorials/Intro-Full/Slides/KokkosTutorial_CMake.pdf, it is suggested that “-DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON
” when compiling with CUDA and CMake.

However, the following error emerges when doing this. Just like one previous issue. #5461 .

terminate called after throwing an instance of 'std::runtime_error'
  what():  Desul::Error: init_lock_arrays_cuda: post init kernel error(cudaErrorIllegalAddress): an illegal memory access was encountered

**Comment by dalg24** [comment]
Please confirm what GPU architecture you are running on, what version of Kokkos you used and how you configured.

**Comment by wangxi0706** [comment]
> Please confirm what GPU architecture you are running on, what version of Kokkos you used and how you configured.

Cuda Runtime Configuration:
macro KOKKOS_ENABLE_CUDA : defined
macro CUDA_VERSION = 12000 = version 12.0
Kokkos::Cuda[ 0 ] NVIDIA GeForce GTX 1650 capability 7.5, Total Global Memory: 3.815 G, Shared Memory per Block: 48 K : Selected


#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
#error \
    "Do not include KokkosCore_config.h directly; include Kokkos_Macros.hpp instead."
#else
#define KOKKOS_CORE_CONFIG_H
#endif

// KOKKOS_VERSION % 100 is the patch level
// KOKKOS_VERSION / 100 % 100 is the minor version
// KOKKOS_VERSION / 10000 is the major version
#cmakedefine KOKKOS_VERSION @KOKKOS_VERSION@

/* Execution Spaces */
#cmakedefine KOKKOS_ENABLE_SERIAL
#cmakedefine KOKKOS_ENABLE_OPENMP
#cmakedefine KOKKOS_ENABLE_OPENACC
#cmakedefine KOKKOS_ENABLE_OPENMPTARGET
#cmakedefine KOKKOS_ENABLE_THREADS
#cmakedefine KOKKOS_ENABLE_CUDA
#cmakedefine KOKKOS_ENABLE_HIP
#cmakedefine KOKKOS_ENABLE_HPX
#cmakedefine KOKKOS_ENABLE_MEMKIND
#cmakedefine KOKKOS_ENABLE_LIBRT
#cmakedefine KOKKOS_ENABLE_SYCL

/* General Settings */
#cmakedefine KOKKOS_ENABLE_CXX14
#cmakedefine KOKKOS_ENABLE_CXX17
#cmakedefine KOKKOS_ENABLE_CXX20

#cmakedefine KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE
#cmakedefine KOKKOS_ENABLE_CUDA_UVM
#cmakedefine KOKKOS_ENABLE_CUDA_LAMBDA
#cmakedefine KOKKOS_ENABLE_CUDA_CONSTEXPR
#cmakedefine KOKKOS_ENABLE_CUDA_LDG_INTRINSIC
#cmakedefine KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC
#cmakedefine KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE
#cmakedefine KOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS
#cmakedefine KOKKOS_ENABLE_HPX_ASYNC_DISPATCH
#cmakedefine KOKKOS_ENABLE_DEBUG
#cmakedefine KOKKOS_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK
#cmakedefine KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK
#cmakedefine KOKKOS_ENABLE_PROFILING_LOAD_PRINT
#cmakedefine KOKKOS_ENABLE_TUNING
#cmakedefine KOKKOS_ENABLE_DEPRECATED_CODE_3
#cmakedefine KOKKOS_ENABLE_DEPRECATION_WARNINGS
#cmakedefine KOKKOS_ENABLE_LARGE_MEM_TESTS
#cmakedefine KOKKOS_ENABLE_COMPLEX_ALIGN
#cmakedefine KOKKOS_ENABLE_IMPL_DESUL_ATOMICS
#cmakedefine KOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION  // deprecated
#cmakedefine KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION

/* TPL Settings */
#cmakedefine KOKKOS_ENABLE_HWLOC
#cmakedefine KOKKOS_USE_LIBRT
#cmakedefine KOKKOS_ENABLE_HBWSPACE
#cmakedefine KOKKOS_ENABLE_LIBDL
#cmakedefine KOKKOS_ENABLE_LIBQUADMATH
#cmakedefine KOKKOS_IMPL_CUDA_CLANG_WORKAROUND

#cmakedefine KOKKOS_COMPILER_CUDA_VERSION @KOKKOS_COMPILER_CUDA_VERSION@

#cmakedefine KOKKOS_ARCH_SSE42
#cmakedefine KOKKOS_ARCH_ARMV80
#cmakedefine KOKKOS_ARCH_ARMV8_THUNDERX
#cmakedefine KOKKOS_ARCH_ARMV81
#cmakedefine KOKKOS_ARCH_ARMV8_THUNDERX2
#cmakedefine KOKKOS_ARCH_A64FX
#cmakedefine KOKKOS_ARCH_AMD_AVX2
#cmakedefine KOKKOS_ARCH_AVX
#cmakedefine KOKKOS_ARCH_AVX2
#cmakedefine KOKKOS_ARCH_AVX512XEON
#cmakedefine KOKKOS_ARCH_KNC
#cmakedefine KOKKOS_ARCH_AVX512MIC
#cmakedefine KOKKOS_ARCH_POWER7
#cmakedefine KOKKOS_ARCH_POWER8
#cmakedefine KOKKOS_ARCH_POWER9
#cmakedefine KOKKOS_ARCH_INTEL_GEN
#cmakedefine KOKKOS_ARCH_INTEL_DG1
#cmakedefine KOKKOS_ARCH_INTEL_GEN9
#cmakedefine KOKKOS_ARCH_INTEL_GEN11
#cmakedefine KOKKOS_ARCH_INTEL_GEN12LP
#cmakedefine KOKKOS_ARCH_INTEL_XEHP
#cmakedefine KOKKOS_ARCH_INTEL_GPU
#cmakedefine KOKKOS_ARCH_KEPLER
#cmakedefine KOKKOS_ARCH_KEPLER30
#cmakedefine KOKKOS_ARCH_KEPLER32
#cmakedefine KOKKOS_ARCH_KEPLER35
#cmakedefine KOKKOS_ARCH_KEPLER37
#cmakedefine KOKKOS_ARCH_MAXWELL
#cmakedefine KOKKOS_ARCH_MAXWELL50
#cmakedefine KOKKOS_ARCH_MAXWELL52
#cmakedefine KOKKOS_ARCH_MAXWELL53
#cmakedefine KOKKOS_ARCH_PASCAL
#cmakedefine KOKKOS_ARCH_PASCAL60
#cmakedefine KOKKOS_ARCH_PASCAL61
#cmakedefine KOKKOS_ARCH_VOLTA
#cmakedefine KOKKOS_ARCH_VOLTA70
#cmakedefine KOKKOS_ARCH_VOLTA72
#cmakedefine KOKKOS_ARCH_TURING75
#cmakedefine KOKKOS_ARCH_AMPERE
#cmakedefine KOKKOS_ARCH_AMPERE80
#cmakedefine KOKKOS_ARCH_AMPERE86
#cmakedefine KOKKOS_ARCH_AMD_ZEN
#cmakedefine KOKKOS_ARCH_AMD_ZEN2
#cmakedefine KOKKOS_ARCH_AMD_ZEN3
#cmakedefine KOKKOS_ARCH_VEGA
#cmakedefine KOKKOS_ARCH_VEGA900
#cmakedefine KOKKOS_ARCH_VEGA906
#cmakedefine KOKKOS_ARCH_VEGA908
#cmakedefine KOKKOS_ARCH_VEGA90A

**Comment by ajpowelsnl** [comment]
@wangxi0706 -- would you please provide the (cmake) configure line you used?

**Comment by dalg24** [comment]
See https://github.com/kokkos/kokkos/issues/5461#issuecomment-1458684944
Can't reproduce.  All tests and examples are passing with RDC enabled.
