### ISSUE TITLE
Cannot join slack as suggested in the tutorial

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5928]
When I want to join the slack https://kokkosteam.slack.com as suggested in the tutorial, it is said that I was don’t have an account on this workspace. How can I joint?

**Comment by dalg24** [comment]
Send me or Christian an email.  You can find them there https://github.com/kokkos/kokkos/blob/569a60949aa5dc3e62c9830f16574d8ec3284ffe/LICENSE#L235-L236
