### ISSUE TITLE
How to tell if the default execution space is the same with the host space?

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5929]
It is said in the tutorial that "create_mirror_view allocates data only if the host process cannot access view’s data, otherwise hostView references the same data. create_mirror always allocates data."

How to compare the host space with the default execution space to determine if deep copy or not?

Thanks

**Comment by dalg24** [comment]
If you did create the mirror view you can compare pointers at runtime
```C++
auto mirror = Kokkos::create_mirror_view(origin);
if (mirror.data() != origin.data()) printf("allocation occurred\n");
```
but if you want to figure it out beforehand (even at compile time) you can do 
```C++
if constexpr(Kokkos::SpaceAccessibility<Kokkos::DefaultHostExecutionSpace, OriginView>::accessible)
  printf("no allocation will occur\n");
else
  printf("allocation will occur\n");
```

PS We generally use GitHub for development and reporting issues.  This sort of questions are more suited to our slack channel.  If you are not able to join, send an email to
https://github.com/kokkos/kokkos/blob/569a60949aa5dc3e62c9830f16574d8ec3284ffe/LICENSE#L235-L236
