### ISSUE TITLE
Wrong number of dimensions check (add check for constructor)

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#593]
Is there a way to force Kokkos::View to check (at least in debug mode) whether the number of runtime dimensions passed to the constructor matches the view's runtime rank? Also an analogous check for the operator ()?

The current behaviour appears to me to be really error prone: it took me 1 hour to debug a code that was just missing one '*' in the data type of the view.

Thanks!

**Comment by hcedwar** [comment]
If you `generate_makefile --debug` or using cmake `Kokkos_ENABLE_Debug_Bounds_Check`
then `operator()` will verify

1. that there is at least _rank_ indices
1. that indices beyond _rank_ are zero

**Comment by bartgol** [comment]
Sounds good!

If I use the Kokkos_ENABLE_Debug_Bounds_Check flag, will it be ignored in my RELEASE build? I'm trying to automatize the configuration of Kokkos...

Also, will these checks be done also for the constructor? If not, what happens to the extra/missing arguments? I'm assuming the missing ones are set to 0 and the extra ones are ignored...Although I'd really like them to be checked at construction time too, to avoid bugs.

**Comment by mhoemmen** [comment]
> If I use the Kokkos_ENABLE_Debug_Bounds_Check flag, will it be ignored in my RELEASE build?  I'm trying to automatize the configuration of Kokkos...

Debug bounds checking has a high run-time performance cost.  I would not recommend using it in a RELEASE build.  A good practice would be to offer two Kokkos builds: DEBUG and RELEASE.

**Comment by bartgol** [comment]
Sure, I just wanted to double check that in a release build, that option would be ignored, even if set. But that's no big deal, I can just have different configuration strings for debug and release.

Looking at the code though, I don't see an analogous check for the constructor. Am I missing it? I would love Kokkos to warn me (again, debug only is fine) if I forgot to pass a dimension, rather than setting it to 0...

**Comment by mhoemmen** [comment]
> Sure, I just wanted to double check that in a release build, that option would be ignored, even if set.

I don't think so.  I'm pretty sure that Kokkos respects your setting for this option, no matter what build (DEBUG or RELEASE) you choose.

**Comment by crtrott** [comment]
Ok just checked. The constructor does not care ... I think we need to rectify that.

**Comment by crtrott** [comment]
P.S. Originally all of them did care even in release mode and you would get a compile time error. But then some customers convinced us that it would be really useful for them to be able to give more arguments. Basically they want to do stuff like this in spirit:

```C++
template<class ViewType>
double norm(ViewType a) {
  double sum = 0;
  for (int i=0; i<view.dimension_0();i++)
  for (int j=0; j<view.dimension_0();j++)
  for (int k=0; k<view.dimension_0();k++)
    sum += a(i,j,k)*a(i,j,k);
}

void foo(View<double***> a, View<double**> b) {
     ...
     double total = norm(a) + norm(b);
     ...
}
```

I.e. they want to reuse functions for views of different dimensionality.

**Comment by crtrott** [comment]
OK I changed this into a request for enhancement, and modified the title to make clearer that we need to add check for constructor.

**Comment by bartgol** [comment]
Thanks everyone! The cmake bounds check flag helps a lot, and if the same feature is added in the constructor, then I believe it will be much easier to debug code.

Cheers.

**Comment by bartgol** [comment]
P.S:  would the following attempt to bring back the compile time check and maintain the dynamic rank feature be possible/reasonable?

I'm thinking of adding a template parameter to the views list, which (similarly to what is done with memory traits for memory management) specifies whether the view is dynamic or not; then inside the operator()/constructor, re-add a static check that, in spirit, does

static_assert (RankType==DynamicRank || sizeof...(Indices)==Rank,"Error! Rank mismatch (do you need dynamic rank views?).");

This parameter would default to StaticRank, and if one wants dynamic rank, would have to create a View specifying it. Something like
Kokkos::View<double*, Kokkos::DynamicRank[, ...]> a (...);

I think adapting to this would not be too big of a hassle for the customers who are using that feature (I'm guessing they would just need to change one/few typedefs), while at the same time would enforce better checks for "normal" users.

But I'm not sure whether this would conflict with other designs inside Kokkos and/or require too many modifications, with the risk of breaking code...

**Comment by crtrott** [comment]
This is actually not truly about dynamik rank. A Kokkos View always has a static rank. It can just accept more parameters in some of its functions than what the rank suggests it should do. Those parameters are simply unused in Release mode. In Debug mode it should be tested whether they are valid in the sense that they would work for a degenerated view (i.e. indices are 0 and dimensions are 1).

**Comment by crtrott** [comment]
Hi, there is another class for actual dynamic rank view called DynRankView (part of the containers sub package). There are pretty good reasons to keep the two classes separated. But pretty much the whole API is fully compatible. 

This issue you were running in is not for an actual dynamic rank view. It is meant for template libraries, which are templates on the ViewType but which could take views of different rank. But all instantiations still use static rank views (which have a number of benefits compared to DynRankView).

**Comment by ibaned** [comment]
We are doing this, but we opened two issues for it. Moving everything to #1286 .
