### ISSUE TITLE
Nightly build failures: Intel-19.0.5 builds timeout during compilation of Test{OpenMP,Serial}_MDRange_b.cpp, TestSerial_RangePolicyRequire.cpp

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5933]
**Describe the bug**
Nightly builds with intel/19.0.5 began to timeout during compilation of the Test*_MDRange_b.cpp test with OpenMP and Serial backends (presumably will occur with Threads as well)

This began after merge of the following commits:

Drop (unused) HBW lock array ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#b4655f90fa4b228c78f254871b0de5652ea16877) / [githubweb](https://github.com/kokkos/kokkos/commit/b4655f90fa4b228c78f254871b0de5652ea16877))
    Drop host lock array ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#63879dbbc631f537dbf5aab1787d77a62055f129) / [githubweb](https://github.com/kokkos/kokkos/commit/63879dbbc631f537dbf5aab1787d77a62055f129))
    Remove misplaced and commented host lock array code in OpenMPTarget backend ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#cba99e88d2c42512a3775efc49de9f33a4711cdd) / [githubweb](https://github.com/kokkos/kokkos/commit/cba99e88d2c42512a3775efc49de9f33a4711cdd))
    Convert HIP ParallelReduce ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#70a0af5f816187a2e91ed1aab2067d3a5ce332b9) / [githubweb](https://github.com/kokkos/kokkos/commit/70a0af5f816187a2e91ed1aab2067d3a5ce332b9))
    Convert HIP ParallelScan ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#4f871bea833a20597a3497297f8eb954e7d0f4ff) / [githubweb](https://github.com/kokkos/kokkos/commit/4f871bea833a20597a3497297f8eb954e7d0f4ff))
    algorithms: Remove workaround for Intel older than the required 19.0.5 ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#6a3b1d60f5eb947103812635ab92a979a92f61f2) / [githubweb](https://github.com/kokkos/kokkos/commit/6a3b1d60f5eb947103812635ab92a979a92f61f2))
    containers: Remove workaround for Intel older than the required 19.0.5 and GCC < 5 ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#54e4396dce03551829e149ad5f029b5c8eeaa65c) / [githubweb](https://github.com/kokkos/kokkos/commit/54e4396dce03551829e149ad5f029b5c8eeaa65c))
    Revert "Fix intel hang" ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#33e5ef694ef4cd11eae1f4dd931d5d56cd84c3e3) / [githubweb](https://github.com/kokkos/kokkos/commit/33e5ef694ef4cd11eae1f4dd931d5d56cd84c3e3))
    Use insertion sort for sort within a bin in BinSort (#5890) ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#12708a1e46406aa91d5eb328e216d6f9bb5727c4) / [githubweb](https://github.com/kokkos/kokkos/commit/12708a1e46406aa91d5eb328e216d6f9bb5727c4))
    New OpenACC backend implementation for  parallel_scan with  a range policy (#5876) ([details](https://jenkins-son.sandia.gov/view/Kokkos/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/627/changes#416d7b7439f6dca7bc4c1b2c4e48c6f8e46a9d1f) / [githubweb](https://github.com/kokkos/kokkos/commit/416d7b7439f6dca7bc4c1b2c4e48c6f8e46a9d1f))

Guessing this follows from updates in #5918 

**Reproducer**:
```

module load sems-intel/19.0.5 sems-cmake

cmake -DCMAKE_CXX_COMPILER=icpc -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH
```

**Comment by PhilMiller** [comment]
Ok, the difference seems to be `-O2` that I tested with vs `-O3`.

**Comment by PhilMiller** [comment]
And indeed, reverting my last commit in #5918 lets it complete without delay.

**Comment by dalg24** [comment]
@ndellingwood please confirm that this is resolved by #5935 and that we can close the issue.

**Comment by ndellingwood** [comment]
@dalg24 I'll update tomorrow to confirm this eve's nightlies pass

**Comment by ndellingwood** [comment]
@dalg24 intel/19 nightlies look good, we can close this :)

Thanks @PhilMiller for the fix and extra footwork checking build times, it makes a good case for moving the minimum supported version to intel/19.1
