### ISSUE TITLE
Assuming we use Threads as the backend, in the `simple_reduce_lambda.cpp` code, what is the process of `parallel_reduce` (using RangePolicy)? 

### ISSUE THREAD

**Issue by mingygit** [kokkos/kokkos#5937]
Assuming we use Threads as the backend, in the `simple_reduce_lambda.cpp` code, what is the process of `parallel_reduce` (using RangePolicy)? Assuming that the number of threads is not specified, that is, kokkos uses hwloc to determine the number of threads, and assuming that the main thread `s_threads_process` and the sub-threads are synchronized, what is the underlying implementation when calculating sum? Are the results calculated by each sub-thread, and finally the final sumn sum is calculated by `m_result_ptr` in ParallelReduce? Thanks!!!

**Comment by dalg24** [comment]
Each thread works on a consecutive chunk and the main thread reduces the partial results into the final value.
https://github.com/kokkos/kokkos/blob/e98766bcc6a24413836dff55779ef3319edcc025/core/src/Threads/Kokkos_Threads_Parallel_Range.hpp#L119-L290

**Comment by mingygit** [comment]
Where is the calculation result of the sub-thread stored? How does the main thread access and finally get the sum of the calculation results of all sub-threads?Can you help me clear up the confusion? thank you very much！！

**Comment by dalg24** [comment]
May I ask why these implementation details matter to you?

**Comment by mingygit** [comment]
I am a graduate student and am interested in high-performance computing, so I want to learn more about kokkos. Thanks !!!

**Comment by dalg24** [comment]
Look at the recording from the Kokkos lectures on YouTube.  Christian covers how work units are mapped to threads.
https://github.com/kokkos/kokkos-tutorials/wiki/Kokkos-Lecture-Series

You should also consider joining us on Slack for this sort of questions.
We generally use GitHub for development and to report issues.
