### ISSUE TITLE
Sync() in dual view, deep_copy(), and View in CudaUVMSpace, which one is the best?

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5938]
What is the performance of modify() and sync() of dual view? Does it just do the deep_copy() between device and hosts? Compared with view with CudaUVMSpace?

**Comment by masterleinad** [comment]
`modify` largely just sets flags and should be cheap. `sync` calls `deep_copy` if necessary even if `CudaUVMSpace` is used as memory space.

**Comment by wangxi0706** [comment]
> `modify` largely just sets flags and should be cheap. `sync` calls `deep_copy` if necessary even if `CudaUVMSpace` is used as memory space.

Will sync() always call deep_copy? Will sync() only copy part of the view rather than the whole view?

**Comment by masterleinad** [comment]
> Will sync() always call deep_copy? Will sync() only copy part of the view rather than the whole view?

It always calls `deep_copy` on the whole `View` if the data has been modified, see https://github.com/kokkos/kokkos/blob/5ad609661e570ba6aa7716a26a91cb67d559f8a2/containers/src/Kokkos_DualView.hpp#L549-L614.

**Comment by wangxi0706** [comment]
> 

Not very sure, if it always deep copy the whole view, it seems less efficient than Cuda UVM memory, is it?

**Comment by masterleinad** [comment]
> Not very sure, if it always deep copy the whole view, it seems less efficient than Cuda UVM memory, is it?

Ideally, you try to limit moving data between host and device as much as possible and the question then is if the difference in access overhead justifies the explicit data movement.

**Comment by wangxi0706** [comment]
> > Not very sure, if it always deep copy the whole view, it seems less efficient than Cuda UVM memory, is it?
> 
> Ideally, you try to limit moving data between host and device as much as possible and the question then is if the difference in access overhead justifies the explicit data movement.

Yes, there seems to be multiple ways of manipulating data on host and device, like using deep_copy with host view and device view, using dual view (kokkos::vector), or use CudaUVM space. What I want is to make the singe version of code universal for OpenMP on CPU and Cuda on Nvidia GPU, with good fit for the architecture. Is there any suggestion?

**Comment by masterleinad** [comment]
Use `Views` and create host or device mirrors as necessary. Also, these kinds of questions are better suited for our Slack channel (https://kokkosteam.slack.com).
