### ISSUE TITLE
Allow assignment of LayoutLeft to LayoutRight or vice versa for rank-0 Views

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#594]
This works for rank-1 Views, but not for rank-0 Views (where it equally would make sense to work).  This is not urgent for me, but it would be helpful (e.g., would reduce the need for some template parameters in my fix for https://github.com/trilinos/Trilinos/issues/957 ).  Thanks!

**Comment by mndevec** [comment]
What is the status of this issue? 
We will probably need this fix for the integration of KokkosKernels into Trilinos by August 20. 
Current ETI system in KokkosKernels casts all rank=0, rank=1 views to layoutleft, and integration is currently failing. Would this be an easy fix?
@crtrott 
@srajama1

**Comment by srajama1** [comment]
I didn't realize this. @hcedwar The urgency comes from a deliverable for ATDM deliverable to applications by August 20. Can we prioritize this ?

**Comment by hcedwar** [comment]
@mndevec 
I am adding a Kokkos unit test for this now, and it passes without modifications.  Can you show me a failing example?

**Comment by mndevec** [comment]
@hcedwar 
Replicating the error might be a bit difficult. It requires the snapshat of kokkoskernels develop branch into Trilinos, and the changes to Trilinos in https://github.com/mndevec/Trilinos/tree/kk_integration .

Let me run the tests again after kokkos commit, and I will let you know if the problem continues.

**Comment by mndevec** [comment]
@hcedwar 
Thank you for the fix. The compilation issues seem to be resolved.
