### ISSUE TITLE
How to integrate Views and Functors into Classes and Objects?

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5941]
Kokkos provides powerful Views to store data, and parallel patterns to implement functors. How we can wrap View as member variables and functors as member functions into the Class and Objects? The programming might be more straightforward with classes and objects.

**Comment by dalg24** [comment]
See
https://github.com/kokkos/kokkos/blob/3.7.01/example/tutorial/03_simple_view/simple_view.cpp
