### ISSUE TITLE
`team_sort` performs significantly worse than `sort`

### ISSUE THREAD

**Issue by matthew-mccall** [kokkos/kokkos#5951]
I have encountered a problem with the new `Kokkos::Experimental::sort_team` function that was introduced recently. In this example, the function is supposed to sort a list of integers in ascending order using the team-based algorithm. However, when I tested it on a dataset of over 10,000 integers, I found that it performed much worse than the traditional `Kokkos::sort` function. For instance, the `sort_team` function took an average of 0.04156 seconds to sort the list, while the `sort` function took only 0.00005 seconds. This discrepancy becomes more significant with increasing orders of magnitude of input size. I ran both functions multiple times on the same hardware and got consistent results. I would appreciate it if you could look into this issue and provide a fix or an explanation for this performance discrepancy.

### Sort Integers with Existing Sort
```cpp
Kokkos::ScopeGuard kokkos;

unsigned long NUMBER_OF_INTS = 10'000;

Kokkos::View<std::uint32_t*> b("b", NUMBER_OF_INTS);
Kokkos::parallel_for("Init", NUMBER_OF_INTS, KOKKOS_LAMBDA (const std::uint32_t i) {
   b(i) = NUMBER_OF_INTS - 1 - i;
});

Kokkos::sort(b);
```
### Sort Integers with `sort_team`
```cpp
Kokkos::ScopeGuard kokkos;

unsigned long NUMBER_OF_INTS =10'000;
    
Kokkos::View<std::uint32_t*> b("b", NUMBER_OF_INTS);
Kokkos::parallel_for("Init", NUMBER_OF_INTS, KOKKOS_LAMBDA (const std::uint32_t i) {
  b(i) = NUMBER_OF_INTS - 1 - i;
});

Kokkos::TeamPolicy<> policy(static_cast<int>(NUMBER_OF_INTS), Kokkos::AUTO());

Kokkos::parallel_for("Sort", policy, KOKKOS_LAMBDA (const Kokkos::TeamPolicy<>::member_type& team) {
  Kokkos::Experimental::sort_team(team, b);
});
```

## Tested Platforms
- RHEL
  - Compiler: `gcc (Spack GCC) 10.1.0`
  - CMake flags: `-DCMAKE_CXX_COMPILER=g++ 
  -DKokkos_ARCH_TURING75=ON 
  -DBUILD_SHARED_LIBS=ON 
  -DKokkos_ENABLE_DEBUG=on 
  -DKokkos_ENABLE_TESTS=off
  -DKokkos_ENABLE_CUDA=on 
  -DKokkos_ENABLE_CUDA_LAMBDA=on`
  - NVIDIA GTX 2060 Super (Turing)

#### Using `sort_team`
```
Regions:


-------------------------------------------------------------------------
Kernels:

- Sort
 (ParFor)   0.041507 1 0.041507 99.877228 99.524937
- Init
 (ParFor)   0.000039 1 0.000039 0.094087 0.093755
- Kokkos::View::initialization [b] via memset
 (ParFor)   0.000012 1 0.000012 0.028685 0.028584

-------------------------------------------------------------------------
Summary:

Total Execution Time (incl. Kokkos + non-Kokkos):                   0.04171 seconds
Total Time in Kokkos kernels:                                       0.04156 seconds
   -> Time outside Kokkos kernels:                                  0.00015 seconds
   -> Percentage in Kokkos kernels:                                   99.65 %
Total Calls to Kokkos Kernels:                                            3

-------------------------------------------------------------------------
```
#### Using `sort`
```
Regions:


-------------------------------------------------------------------------
Kernels:

- Init
 (ParFor)   0.000034 1 0.000034 72.081218 10.881226
- Kokkos::View::initialization [b] via memset
 (ParFor)   0.000013 1 0.000013 27.918782 4.214559

-------------------------------------------------------------------------
Summary:

Total Execution Time (incl. Kokkos + non-Kokkos):                   0.00031 seconds
Total Time in Kokkos kernels:                                       0.00005 seconds
   -> Time outside Kokkos kernels:                                  0.00026 seconds
   -> Percentage in Kokkos kernels:                                   15.10 %
Total Calls to Kokkos Kernels:                                            2

-------------------------------------------------------------------------
```

**Comment by dalg24** [comment]
Please put a region around what you want to time.
The CUDA `Kokkos::sort` is deferring to `thrust::sort` and it is not counted as a Kokkos kernel in the report you posted above.

**Comment by dalg24** [comment]
Also making 10000 teams that all are sorting the original array concurrently, likely causing all sorts of race conditions

**Comment by dalg24** [comment]
To be clear the teams are NOT collaborating to sort the underlying array.  You would use `Experimental::sort_team` to sort many independent small arrays.

**Comment by matthew-mccall** [comment]
Understood, thank you for clarifying.
