### ISSUE TITLE
Kokkos 4.0.00 compile failure

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5956]
I try to compile kokkos 4.0, my gcc version is 10.3.0, nvcc version is cuda 12.0, cmake version is 3.25.2. Cmake shows the error:

CMake Error at contrib/kokkos-3.7.01/cmake/kokkos_test_cxx_std.cmake:34 (MESSAGE):
  CMake wants to use -std=c++1z which is not supported by NVCC.  Using a more
  recent host compiler or a more recent CMake version might help.

**Comment by dalg24** [comment]
Xi Wang reported this to work properly on Slack with a fresh install, after reinstalling the `build-essential` package on his system.
