### ISSUE TITLE
Kokkos sort question

### ISSUE THREAD

**Issue by DomBrown** [kokkos/kokkos#5974]
Hello, sorry if there is an answer to this question somewhere else, but I'd like to know the best way to do something like a lexicographic sort using Kokkos.

The use case is that I have three 1D Views of int: x, y, z that I would like to sort first by x, then y, then z. Essentially this is an SoA structure representing (x, y, z) points. I assume I need to provide some sort of custom comparator and then generate and apply a permutation vector of some kind.

**Comment by aprokop** [comment]
My understanding is that Kokkos' sort does not support custom comparators. If you had two values, `x` and `y`, I would recommend casting to `long long` with shift and then sorting. But it would not work for 3 ints.

**Comment by PhilMiller** [comment]
Does https://github.com/kokkos/kokkos/pull/5507/ with a Key Functor that knows about all three key elements suit your need?

**Comment by DomBrown** [comment]
Just took a look at the unit test(s) in that PR. I think that could work for me, once I worked out how to write the correct key functor. The pattern of creating the sorter and then applying the permutation to a given view is definitely what I am looking for because I could create the sorter and then call apply_permutation to each view as needed.

**Comment by ajpowelsnl** [comment]
@DomBrown -- was the suggested approach a workable solution for you?  If so, may we close the issue?

**Comment by DomBrown** [comment]
Been away from the office for a while -- will get back to you once I get a chance to test

**Comment by ajpowelsnl** [comment]
@DomBrown - can with help with anything else on this issue?  If so, please let us know in the next couple of days.

**Comment by DomBrown** [comment]
I'm happy to close this one -- my use case has changed anyways.
