### ISSUE TITLE
Likely failure of reduce, scan for `value_type` smaller than `int` in Team policies

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#5975]
**Describe the bug**

The issue reported in #5641 likely applies to the various Team policies as well.

Try testing MDRange scan, too, if that's a thing.

Start of a fix in #5334

**Comment by PhilMiller** [comment]
As initially noted in that PR, the test case there doesn't produce the expected failure. I could use some help on that point.

**Comment by ajpowelsnl** [comment]
Thanks, @cz4rs !
