### ISSUE TITLE
Different behavior when using Kokkos::SharedSpace and Kokkos::CudaSpace for virtual functions.

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#5980]
I am wrapping derived class as shown in doc (https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Kokkos-and-Virtual-Functions.html?highlight=virtual+function). When I am using ShareSpace or CUDAUVM Space,

**Comment by wangxi0706** [comment]
When usinng  ShareSpace or CUDAUVM Space, Code and output is like this.
int main(int argc, char *argv[])
{
  Kokkos::initialize(argc, argv);
  Kokkos::DefaultExecutionSpace{}.print_configuration(std::cout);
  {
    Kokkos::View<Foo_1[1], Kokkos::SharedSpace> f_1("f_1");
    Kokkos::View<Foo_2[1], Kokkos::SharedSpace> f_2("f_1");
    int value_1, value_2;
    Kokkos::parallel_reduce(
        "CheckValues", 1,
        KOKKOS_LAMBDA(const int &, int &lsum) { Foo *pf_1=&f_1[0]; lsum = pf_1->value(); }, value_1);
    Kokkos::parallel_reduce(
        "CheckValues", 1,
        KOKKOS_LAMBDA(const int &, int &lsum) { Foo *pf_2=&f_2[0]; lsum = pf_2->value(); }, value_2);
    printf("Values: %i %i\n", value_1, value_2);
  }
  Kokkos::finalize();
}

And the output reads as follows:
Device Execution Space:
  KOKKOS_ENABLE_CUDA: yes
Cuda Atomics:
  KOKKOS_ENABLE_CUDA_ATOMICS: no
Cuda Options:
  KOKKOS_ENABLE_CUDA_LAMBDA: yes
  KOKKOS_ENABLE_CUDA_LDG_INTRINSIC: yes
  KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE: yes
  KOKKOS_ENABLE_CUDA_UVM: yes
  KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA: yes
Cuda Runtime Configuration:
macro  KOKKOS_ENABLE_CUDA      : defined
macro  CUDA_VERSION          = 12000 = version 12.0
Kokkos::Cuda[ 0 ] NVIDIA GeForce GTX 1650 capability 7.5, Total Global Memory: 3.815 G, Shared Memory per Block: 48 K : Selected
Values: 1 2

**Comment by wangxi0706** [comment]
When I use:

  Kokkos::View<Foo_1[1], Kokkos::CudaSpace> f_1("f_1");
    Kokkos::View<Foo_2[1], Kokkos::CudaSpace> f_2("f_1");

Here is the error 

Kokkos::View ERROR: attempt to access inaccessible memory space (label="f_1")
Backtrace:
                  [0x55a3b104bb7d]
                  [0x55a3b103e3a4]
                  [0x55a3b103e438]
                  [0x55a3b0fce6a2]
                  [0x55a3b0fd25c2]
                  [0x55a3b0fd11bd]
                  [0x55a3b0fcd23d]
__libc_start_main [0x7f48e9614c87]
                  [0x55a3b0fcc17a]
Aborted (core dumped)


And the same error occurs when I am trying to call the derived function on host when it lives in  ShareSpace or CUDAUVM Space.  I am quite confused about it. Why cannot parallel_for call the derived class on CudaSpace? Why cannot host call the derived class living on SharedSpce?

**Comment by ajpowelsnl** [comment]
Hi @wangxi0706 - have you tried `Kokkos::View<Foo_1[1], Kokkos::DefaultExecutionSpace> f_1("f_1");` instead of `Kokkos::View<Foo_1[1], Kokkos::SharedSpace> f_1("f_1");`?

**Comment by ajpowelsnl** [comment]
Hi @wangxi0706 -- do you need further help with this issue?

**Comment by ajpowelsnl** [comment]
Hi @wangxi0706 - closing issue under the assumption that you've been able to resolve the problem.  Please get in touch again, if that is not the case.
