### ISSUE TITLE
Issue with ScatterView with CUDA 

### ISSUE THREAD

**Issue by LonelyCat124** [kokkos/kokkos#5994]
I'm having an issue with a program that uses a ScatterView when I run it with CUDA (but seems to work find with Serial).

Apologies if this isn't the best place to ask a question, but the main page says to open an issue or use the Slack, but I don't have access to the Slack.

When I run the program on a CUDA GPU, the Max current output is always 0, though if i add `std::printf` statements inside the kernel, the values being updates are non-zero (though the value of `jx(cx+jng)` is always approximately 0 (e-310), but I'm not sure if thats just not a value which is readable as part of a ScatterView inside a Kernel).

If I run the program (same code except swapping to `using MemorySpace = Kokkos::HostSpace` and a Kokkos compiled without CUDA support), then the value of Max current is correct (~1e9).

Setup code:
```
using MemorySpace = Kokkos::CudaSpace;
using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using DeviceType = Kokkos::Device<Kokkos::DefaultExecutionSpace, MemorySpace>;
using HostType = Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>;

using field_type = Kokkos::View<double* , MemorySpace>;
using scatter_field_type = Kokkos::Experimental::ScatterView<double*>;

struct FDTD_field{
    struct field_struc field;
    field_type ex;
    field_type ey;
    field_type ez;
    field_type bx;
    field_type by;
    field_type bz;
    field_type jx;
    field_type jy;
    field_type jz;
    scatter_field_type scatter_jx;
    scatter_field_type scatter_jy;
    scatter_field_type scatter_jz;
    int nxglobal;
    int nx;
    int min_local_cell;
    int max_local_cell;
    int ng;
    int jng;
    double dx;
};
```

The `scatter_jx` value is initialised with:
```
    field.jx = field_type("jx", size_grid + 2*field.jng);
    field.jy = field_type("jy", size_grid + 2*field.jng);
    field.jz = field_type("jz", size_grid + 2*field.jng);

    field.scatter_jx = scatter_field_type(field.jx);
    field.scatter_jy = scatter_field_type(field.jy);
    field.scatter_jz = scatter_field_type(field.jz);
```

I access the ScatterView inside a kernel with:
```
        auto jx = scatter_jx.access();
        auto jy = scatter_jy.access();
        auto jz = scatter_jz.access();
        jx(cx+jng) += jxh;
        jy(cx+jng) += jyh;
        jz(cx+jng) += jzh;
```

The kernel is called by:
```
            push_particles.update_structs(field);
            Cabana::simd_parallel_for(simd_policy, push_particles, "push_particles");
            Kokkos::fence();

            field.scatter_jx.contribute_into(field.jx);
            field.scatter_jy.contribute_into(field.jy);
            field.scatter_jz.contribute_into(field.jz);
            field.scatter_jx.reset();
            field.scatter_jy.reset();
            field.scatter_jz.reset();
            {
                auto jx = Kokkos::create_mirror_view(field.jx);
                auto jy = Kokkos::create_mirror_view(field.jy);
                auto jz = Kokkos::create_mirror_view(field.jz);
                Kokkos::deep_copy(jx, field.jx);
                Kokkos::deep_copy(jy, field.jy);
                Kokkos::deep_copy(jz, field.jz);
                double max = 0.0;
                for(int i = 0; i < jx.size(); i++){
                    if(jx(i) > max) max = jx(i);
                    if(jy(i) > max) max = jy(i);
                    if(jz(i) > max) max = jz(i);
                }
                printf("Max current = %f\n", max);
            }
```

I'm using functors containing the code, where they are declared with this "field" struct as a member:
```
template < class WEIGHT, class CHARGE, class MASS, class PART_P_X, class PART_P_Y, class PART_P_Z, class CORE_PART_POSITION>
struct push_particles_functor{
    ....
    FDTD_field field;

        KOKKOS_INLINE_FUNCTION
     push_particles_functor( WEIGHT weight, CHARGE charge, MASS mass, PART_P_X part_p_x, PART_P_Y part_p_y, PART_P_Z part_p_z, CORE_PART_POSITION core_part_position, config_struct_type config, FDTD_field FIELD):
    _weight(weight), _charge(charge), _mass(mass), _part_p_x(part_p_x), _part_p_y(part_p_y), _part_p_z(part_p_z), _core_part_position(core_part_position), field(FIELD), _config(config){}

    KOKKOS_INLINE_FUNCTION
    void update_structs(FDTD_field FIELD){
        field = FIELD;
    }

    KOKKOS_INLINE_FUNCTION
    void operator()(const i, const a) const{ //This is cabana simd operator call format.
    .... code including scatterview accesses.
    }
};
```

I assumed the field (which is part of the constructor, and then in theory updated in `update_structs`) should be copied to the GPU correctly (since its just a structure) - is that causing my issues? Though if i never call update_structs it should use the original field structure (which is never actually modified in this code) and I have the same issue. I tried using `&FIELD` to pass by reference into the update_structs call but that didn't help either.

I can provide the full code/files that make up this program if there's nothing obvious here, just let me know.

Edit: ~~I have another program with the same Kokkos installation using scatterviews on CUDA correctly as far as I can tell, so I'm not sure what the difference is as this is based on the other code.~~

Edit2: My previous edit is wrong, I'm not sure I have scatterviews working at all the moment with CUDA so I'm not sure what is happening.

Edit3: I managed to build a mini program with scatterviews working as I expect - the construction of everything should be the same but without any other views etc. being used during the program.

**Comment by LonelyCat124** [comment]
Ok I think i worked it out, and its when I call the `scatter_x.reset();` with CUDA that the data is all deleted. For example:
```
int main( int argc, char* argv[] ){
    Kokkos::ScopeGuard scope_guard(argc, argv);
    {
        field_type x("x", 10000);
        scatter_field_type scatter_x(x);


        Kokkos::parallel_for("test", 10000,
                KOKKOS_LAMBDA (const int &i){
                    auto x = scatter_x.access();
                    x(1) += 1.0;
                });

        Kokkos::fence();
        scatter_x.contribute_into(x);
        Kokkos::fence();
        scatter_x.reset();
        auto host_x = Kokkos::create_mirror_view(x);
        host_x(100) = 100.0;
        Kokkos::deep_copy(host_x, x);
        Kokkos::fence();
        printf("%e %f\n", host_x(1), host_x(100));

    }

}
```

This test code works correctly if `scatter_x.reset();` is not present, but all the value are 0 if the reset is present. Is there an easy way to check in code if `scatter_x` is using atomic updates (and if so, don't call reset?). Or am I using this wrong?

**Comment by masterleinad** [comment]
You can set the Duplication and Contribution type manually via the 5th and 6th template parameter (see https://kokkos.github.io/kokkos-core-wiki/API/containers/ScatterView.html?highlight=scatterview) but there is currently no alias that you could query for it.

`reset_except` omits the reset on the View given if it matches the internally used View.

**Comment by LonelyCat124** [comment]
Ah, so if i did `scatter_x.reset_except(x)` it would probably work on both CUDA and Serial backends for the same code with the defaults? I can give that a try, thanks.

**Comment by ajpowelsnl** [comment]
@LonelyCat124 - Have we addressed your issue on `ScatterView`?  If so, may we close this issue?

**Comment by ajpowelsnl** [comment]
@LonelyCat124 - Please let us know if you need additional help with this issue, and we can reopen.
