### ISSUE TITLE
Provide a type_trait for an execution space to be host or device

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#6006]
While working on https://github.com/trilinos/Trilinos/pull/11708, I noticed that we don't have a good way to tell if a given execution space is running on the host or device but downstream code often wants to specialize for it. I would suggest basically copying what the pull request is proposing for Ifpack2 right now:
```C++
template<typename T> struct is_device_execution_space : std::false_type{};
template <> struct is_device_execution_space<Cuda> : std::true_type{};
template <> struct is_device_execution_space<HIP> : std::true_type{};
template <> struct is_device_execution_space<SYCL> : std::true_type{};
template <> struct is_device_execution_space<OpenACC> : std::true_type{};
template <> struct is_device_execution_space<OpenMPTarget> : std::true_type{};
```
asking if `DefaultExecutionSpace` is a device execution space (and thus if `Kokkos` has been configured with any device backend) would then look like
```
is_device_execution_space<DefaultExecutionSpace>::value
```
Somewhat related to the various `Trilinos` pull requests avoiding using `KOKKOS_ACTIVE_EXECUTION_MEMORY` in `Trilinos`, like https://github.com/trilinos/Trilinos/pull/11657 since we often know the type of the execution space in a kernel.

**Comment by crtrott** [comment]
I am not sure this is right. What if you compiled SYCL or OpenACC or OpenMPTarget for CPU execution? I think what the codes need to know is `is_accessible<HostSpace, execution_space>` or?

**Comment by crtrott** [comment]
Also what happens in cases where CUDA/HIP can access HostSpace because there is only one memory space? What do we want to happen then?

**Comment by crtrott** [comment]
Maybe another thing which could be what the codes want is this? `is_same_v<DefaultExecutionSpace, DefaultHostExecutionSpace>`

**Comment by masterleinad** [comment]
> I am not sure this is right. What if you compiled SYCL or OpenACC or OpenMPTarget for CPU execution? 

I would still call those `device execution spaces`. We don't really optimize for these backends targeting CPU execution.

> I think what the codes need to know is is_accessible<HostSpace, execution_space> or?

There are multiple use cases. In the pull request above, the question really is about choosing different policies for different backends and not so much about memory access. For this particular case, we don't provide a portable solution directly while we have `SpaceAccessibility` for memory access (that could potentially be used for the former one).

**Comment by ajpowelsnl** [comment]
Hi @masterleinad - what is the current status of this issue?  Something we want to do?

**Comment by masterleinad** [comment]
> Hi @masterleinad - what is the current status of this issue? Something we want to do?

Still not clear/no consensus.

**Comment by ajpowelsnl** [comment]
> > Hi @masterleinad - what is the current status of this issue? Something we want to do?
> 
> Still not clear/no consensus.

I'll put it as a yes / no thing for Wed.

**Comment by crtrott** [comment]
If we really want this then probably this is it:

```c++
template<class ExecSpace>
constexpr bool is_device_execution_space<ExecSpace> == !is_same_v<ExecSpace, Kokkos::Serial> && !is_same_v<ExecSpace, Kokkos::DefaultHostExecutionSpace>;
```

**Comment by crtrott** [comment]
We decided to not do anything until we have more than one customer asking for this.

**Comment by brian-kelley** [comment]
@crtrott I just saw @masterleinad linked to this issue. Tpetra and KokkosKernels can make use of this. In KokkosKernels we already have
```
constexpr bool KokkosKernels::Impl::kk_is_gpu_exec_space<execution_space>() {...}
```
which is about the same, except it's specialized per-backend. But it is always nice to shrink our internal utilities and replace them with the official thing from core 😄 

In the case of Tpetra, we are looking into adding this to the Node class directly, since some downstream packages have lots of copy-pasted logic for checking whether the backend is a 'device' or not.

**Comment by ajpowelsnl** [comment]
@brian-kelley , @crtrott - if no customer , no use case, can we close this issue?

**Comment by brian-kelley** [comment]
@ajpowelsnl I think so, KokkosKernels and Tpetra each have a version of this that works for them. The KokkosKernels one is internal-only, and the Tpetra one lives in the Node class.
