### ISSUE TITLE
Runtime issue when setting the language property of the source files

### ISSUE THREAD

**Issue by anagainaru** [kokkos/kokkos#6014]
**Describe the bug**
ADIOS2 needs to link to Kokkos in a way that requires to set the language property for the source files that use Kokkos.
I created a minimal shared library (myADIOS) that mimics ADIOS2 behavior here: https://github.com/anagainaru/ADIOS-Kokkos-bug

The repo has an example code (`kokkosHelloWorld.cpp`) that creates a view and populates it then calls a myADIOS function (implemented in `myADIOS/src/adiosKokkos.cpp`) that creates another view and populates it.

Running the example application with CUDA backend results in a Segmentation Fault when using the latest release and develop branch. The code runs successfully with the 3.7.0 release. 

**Please also include the following items to support reproducing the bug**
The runs were done on Summit with the following modules:
```
module load gcc/10.2
module load cuda/11.5
module load cmake/3.23
```

CUDA backend and Kokkos 4.0 or latest develop branch from yesterday.

Kokkos is built with:
```
    -D CMAKE_BUILD_TYPE=RelWithDebInfo
    -D CMAKE_CXX_COMPILER=/path/to/kokkos/bin/nvcc_wrapper
    -D Kokkos_ENABLE_CUDA=ON
    -D Kokkos_ENABLE_CUDA_LAMBDA=ON
    -D Kokkos_ARCH_VOLTA70=ON
    -D CMAKE_CXX_STANDARD=17
    -D CMAKE_CXX_EXTENSIONS=OFF
    -D BUILD_SHARED_LIBS=ON
```

**Any additional info**

To reproduce the bug, download the code from the repo: 
https://github.com/anagainaru/ADIOS-Kokkos-bug
```
$ bash build_example.sh
$ ./build/KokkosHello
Create View on memory space: Cuda
Create View inside ADIOS on memory space: Cuda
Segmentation fault (core dumped)
```

If these two lines:
```
    set_property(SOURCE src/adiosKokkos.cpp PROPERTY LANGUAGE CUDA)
    set_property(SOURCE src/adiosKokkos.cpp APPEND PROPERTY COMPILE_FLAGS "--extended-lambda")
```
are removed from the `myADIOS/CMakeLists.txt` the code runs correctly. 

I would like to understand why this is an issue (since it wasn't with Kokkos 3.7) and if we need to adapt on our side.

**Comment by Rombur** [comment]
> ADIOS2 needs to link to Kokkos in a way that requires to set the language property for the source files that use Kokkos.

Sounds like you want to use `Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON` (#4323). When using this option, you don't need to use `nvcc_wrapper`  but instead you tell CMake that files that uses Kokkos are CUDA files. 

I don't know why your code started to segfault but as far as I know we don't explicitly support using `nvcc_wrapper` and setting the language to CUDA. If you use `nvcc_wrapper`, you should set the language to C++.

**Comment by anagainaru** [comment]
I get the same error when I build Kokkos with `Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON`

The code that sets the language to CUDA is built with C++ not `nvcc_wrapper`:
```
cmake -DKokkos_ROOT=${Kokkos_ROOT} -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_INSTALL_PREFIX=${myADIOS_HOME}/install ..
```

The application that will link against `myADIOS` does not set the language to CUDA so it needs to use the `nvcc_wrapper`.

**Comment by crtrott** [comment]
Missing -fPIC on the Adios stub is the issue in the reproducer. Note you need it here on CMAKE_CUDA_FLAGS and what not. Also you potentially need it on the kokkos library?

**Comment by anagainaru** [comment]
Adding `-fPIC` solved the problem for the reproducer but not the initial ADIOS2 problem. You can consider this solved. We will work on a new reproducer that behaves closer to ADIOS2 and come back (if we don't figure it out on our own).

**Comment by PhilMiller** [comment]
It's maybe an aside for now, but it's probably preferable to use the CMake property `BUILD_SHARED_LIBS=ON` than to pass an explicit compiler argument of `-fpic`

**Comment by PhilMiller** [comment]
Actually, if PIC mismatches were the issue in the original ADIOS2 instance, doing things the CMake-y way may fix it, if the flag was otherwise being missed on some step.

**Comment by anagainaru** [comment]
Thanks @PhilMiller we're not doing that in ADIOS2 so I will try it
