### ISSUE TITLE
Enabling Cuda Compute Capability 3.7 within Trilinos

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos#602]
I am compiling Trilinos with
CUDA_NVCC_FLAGS:STRING=-DKOKKOS_HAVE_CUDA_ARCH=370;-gencode;arch=compute_37,code=sm_37

At the run time I keep getting the below warning: 

Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 3.5 on device with compute capability 3.7 , this will likely reduce potential performance.

What would be the correct way to set compute_37 within Trilinos configure?

**Comment by pkestene** [comment]
You need to make sure your CXX compiler is nvcc_wrapper (or set OMPI_CXX to
nvcc_wrapper if you're building openmpi wrapper), and then add
"-arch=sm_37" to your CMAKE_CXX_FLAGS
nvcc_wrapper will parse CMAKE_CXX_FLAGS and set the correct to the actual
nvcc compiler

**Comment by mndevec** [comment]
I was setting the OMPI_CXX, but I was missing CXX_FLAG option. 
Thank you very much @pkestene, the warning disappeared finally!
