### ISSUE TITLE
Add the option to set number of threads/blocks, suggestion

### ISSUE THREAD

**Issue by wangxi0706** [kokkos/kokkos#6025]
In documentation, there is a launch bounds :

LaunchBounds | LaunchBounds<MaxThreads, MinBlocks> | Specifies hints to to the compiler about CUDA/HIP launch bounds.

but it is just hints, when I set the bounds, the program does not follow at all. It is strongly suggested that the option of manually set the blocks and threads be added, and the underlying mechanism of setting blocks and threads should be clarified.

**Comment by crtrott** [comment]
Couple things: LaunchBounds is a requirement on the compiler on how to do register allocation. It is NOT a thing which says how many blocks/threads to use. We are considering allowing `chunk_size()` to influence the block size choice. But we do not guarantee anything, and we will not guarantee anything regarding how loops are mapped. This was always a choice on our side to preserve implementation freedom. Guaranteeing in detail how we schedule stuff will lead to non portable code in the long run.

**Comment by ajpowelsnl** [comment]
@wangxi0706 -- Have we answered your question?  If not, please let us know in the next few days.

**Comment by ajpowelsnl** [comment]
Hi @wangxi0706 - closing this issue, but please let us know if you have further questions!
