### ISSUE TITLE
Warning from Kokkos code using ALL_t

### ISSUE THREAD

**Issue by nmm0** [kokkos/kokkos#6027]
It should use `Kokkos::ALL_t` (qualified)

See https://github.com/kokkos/kokkos/pull/5807 and https://github.com/kokkos/kokkos/pull/5818

**Comment by dalg24** [comment]
How comes these warnings were not reported before.  Is there a gap in the CI?

**Comment by masterleinad** [comment]
> How comes these warnings were not reported before. Is there a gap in the CI?

We don't detect deprecation warnings in the CI because we oftentimes still want to test deprecated functions.

**Comment by nmm0** [comment]
> > How comes these warnings were not reported before. Is there a gap in the CI?
> 
> We don't detect deprecation warnings in the CI because we oftentimes still want to test deprecated functions.

We could have a build that just ensures Kokkos core isn't calling anything deprecated

**Comment by masterleinad** [comment]
Fixed in #6027.
