### ISSUE TITLE
Drop gcc 4.7 and intel 14 from tested compiler suite, end of 2017-January

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#603]

**Comment by nmhamster** [comment]
I think GCC 4.7.2 support is still required for IC support isn't it? We have not had a firm decision to retire that yet.

**Comment by hcedwar** [comment]
cite:  SART teleconference 01/10/17 at 10:50am; a historic moment!

**Comment by crtrott** [comment]
Yeah IC codes confirmed transition to GCC 4.9.3 with a firm kill date of 4.7 for end of January.

**Comment by hcedwar** [comment]
TODO: Assess how far back we could drop; perhaps gcc 4.8 ?

**Comment by crtrott** [comment]
Yeah I would go for Intel 15 and GCC 4.8.4 for now.

**Comment by nmhamster** [comment]
We had been told that the most likely jump would be 17.1 and GCC 4.9.3.

**Comment by crtrott** [comment]
Yeah thats what IC is doing. Not sure we should go there right away. Also its not clear that the capacity machines are upgrading right away. Looks like those are still on Intel 15.

**Comment by hcedwar** [comment]
Must be deferred. Reevaluate in April.

**Comment by mhoemmen** [comment]
If it helps -- one of the issues I've found with GCC 4.7.2 is that lambdas don't quite understand implicit capture.  If you capture explicitly, that seems to help.

**Comment by hcedwar** [comment]
Trilinos is moving to gcc 4.8.4 as the _floor_ version.  Time to move _floor_ to gcc 4.8.4 and Intel 15.  Drop earlier versions from nightly testing, officially supported lists, and testing scripts.  Replace gcc 4.7.2 with gcc 4.8.4 in Jenkins nightly testing.

**Comment by hcedwar** [comment]
@crtrott - LAMMPS ok with gcc 4.8.4 and Intel 15 as the floor version?

**Comment by hcedwar** [comment]
Verify Titan has CUDA 7.5, then drop CUDA 7.0 as well

**Comment by bjoo** [comment]
Finally I can help with something :)

Titan has CUDA-7.5.
Please see below…

Best, 
 B

bjoo@titan-ext5:~> module avail cudatoolkit

---------------------------- /opt/cray/modulefiles -----------------------------
cudatoolkit/7.0.28-1.0502.10280.4.1
cudatoolkit/7.5.18-1.0502.10743.2.1(default)
bjoo@titan-ext5:~> module load cudatoolkit
bjoo@titan-ext5:~> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
bjoo@titan-ext5:~> 


> On Sep 20, 2017, at 2:46 PM, hcedwar <notifications@github.com> wrote:
> 
> Verify Titan has CUDA 7.5, then drop CUDA 7.0 as well
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------
