### ISSUE TITLE
float support for SIMD types

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [kokkos/kokkos#6054]
Creating the issue based on @ibaned response in #5674 . Could you add FP32 support for SIMD types. 

I am working on porting the seismic modelling package SPECFEM towards Kokkos, and almost all users use the package in single precision mode. Currently, I am not able to define my compute intensive kernels such that it auto-vectorizes without sacrificing on GPU performance.

**Comment by ibaned** [comment]
@ldh4 @crtrott

**Comment by crtrott** [comment]
OK we can prioritize that, any specific architectures highest on your priority list?

**Comment by Rohit-Kakodkar** [comment]
Thanks! Yes, intel Broadwell architecture. Currently, we are testing the speed up we get when using SIMD support and Broadwell seems to be the most abundant CPU machine on our cluster.

**Comment by masterleinad** [comment]
Fixed in #6177.
