### ISSUE TITLE
Goal: Performance of a pure Serial build & back-end is near non-Kokkos

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#607]
Given a well-written on-node pure Serial (MPI-only) application we want the performance of a pure Serial build and back-end to have comparable performance.

What are sources of performance degradation?

**Comment by stanmoore1** [comment]
Another issue is that sometimes threading must use a `parallel_scan` for thread safety whereas in the serial code a regular `for loop` can be used. The `parallel_scan` increases the cost of the loop by a minimum of 2x. It would be helpful if all the `parallel_scans` were replaced with `parallel_for` loops when using a pure Serial build.

**Comment by stanmoore1** [comment]
In other words, for a pure Serial build, only make a single pass through the parallel_scan, instead of the normal 2+ passes.

**Comment by hcedwar** [comment]
This is how the Serial back-end currently works.  The parallel back-ends (OpenMP, Thread) currently do not detect single threaded so they make two passes regardless.

**Comment by stanmoore1** [comment]
@hcedwar That's great, I didn't know that, thanks

**Comment by hcedwar** [comment]
Could help if the parallel pattern interface has move arguments and contructors.

**Comment by hcedwar** [comment]
Possible strategy: use OpenMP atomics without enabling OpenMP in the build.
