### ISSUE TITLE
Trilinos nightly test failures (multple packages tests) in MPI+OpenMP builds on Power9

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6082]
**Describe the bug**
Multiple Trilinos unit tests are failing in Trilinos nightly tests with Kokkos' develop branch in MPI+OpenMP builds on Power9 with gcc/8.3.0. The failures do not occur with 4.0.0 nor 4.0.01.

I ran bisection to track down the change when failures began and determined the failures began with kokkos #5874 , testing against kokkos-kernels@develop and Trilinos@develop branches

Here is a list of failing unit tests, mostly in Tpetra:
```
TpetraCore_BlockCrsMatrix_MPI_4
TpetraCore_CrsGraph_UnitTests0_MPI_4
TpetraCore_Issue601_MPI_4
TpetraCore_CrsGraph_StaticImportExport_MPI_4
TpetraCore_CrsGraphTransposer_UnitTests_MPI_4
TpetraCore_FECrsGraph_UnitTests_MPI_4
TpetraCore_FECrsMatrix_UnitTests_MPI_4
TpetraCore_ImportExport2_UnitTests_Send_MPI_4
TpetraCore_ImportExport2_UnitTests_ISend_MPI_4
TpetraCore_MatrixMarket_Tpetra_CrsGraph_InOutTest_MPI_4
TpetraCore_FECrs_MatrixMatrix_UnitTests_MPI_4
TpetraCore_FEMAssembly_InsertGlobalIndicesFESPKokkos_MPI_4
Ifpack2_unit_tests_MPI_4
Ifpack2_AdditiveSchwarz_MPI_4
MueLu_GeneralBlockSmoothing_MPI_4
Zoltan2_XpetraTraits_MPI_4
Zoltan2_XpetraCrsGraphInput_MPI_4
PanzerDofMgr_Test_FE_Assembly_HEX_MPI_2
```

This is sample failure output from `TpetraCore_CrsGraph_UnitTests0_MPI_4`:
```
...
1. CrsGraph_int_longlong_Tpetra_KokkosCompat_KokkosOpenMPWrapperNode_EmptyGraphAlloc1_UnitTest ... [Passed] (0.000324 sec)
2. CrsGraph_int_longlong_Tpetra_KokkosCompat_KokkosOpenMPWrapperNode_ExcessAllocation_UnitTest ... [Passed] (0.000724 sec)
3. CrsGraph_int_longlong_Tpetra_KokkosCompat_KokkosOpenMPWrapperNode_BadConst_UnitTest ... [Passed] (0.000304 sec)
4. CrsGraph_int_longlong_Tpetra_KokkosCompat_KokkosOpenMPWrapperNode_insert_remove_LIDs_UnitTest ... [Passed] (0.000111 sec)
[weaver10:2112034:0:2112034] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x81)
[weaver10:2112033:0:2112033] Caught signal 11 (Segmentation fault: <unknown si_code> at address 0xfffffffffffffff0)
...
```

**Please also include the following items to support reproducing the bug**

**Reproducer** (Weaver testbed, rhel8 queue):
The script below enables the Tpetra unit tests and includes boiler-plate for various TPLs - only gcc/8.3.0, mpi and blas+lapack tpls are needed to reproduce the Tpetra failures
```bash
# Repos
git clone -b develop https://github.com/trilinos/Trilinos.git
git clone -b develop https://github.com/kokkos/kokkos.git
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Configure
module load openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1 metis/5.1.0/gcc/8.3.1  hdf5/1.10.7/gcc/8.3.1/openmpi/4.1.1 netcdf-fortran/4.5.4/gcc/8.3.1/openmpi/4.1.1 parallel-netcdf/1.12.2/gcc/8.3.1/openmpi/4.1.1 parmetis/4.0.3/gcc/8.3.1/openmpi/4.1.1 zlib/1.2.11/gcc/8.3.1 cmake/3.23.1 boost/1.70.0/gcc/8.3.1

export OMP_NUM_THREADS=8
# This is needed for the Kokkos openmp.partition_master test to pass
export OMP_MAX_ACTIVE_LEVELS=1

cmake \
 -D CMAKE_CXX_COMPILER=`which mpicxx` \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER=`which mpicc` \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER=`which mpifort` \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
 -D CMAKE_CXX_STANDARD=17 \
 -D BUILD_SHARED_LIBS=OFF \
\
 -D TPL_ENABLE_CUDA:STRING=OFF \
 -D TPL_ENABLE_MPI:STRING=ON \
 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \
 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \
 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \
\
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
\
-D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D Boost_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH="${BOOST_ROOT}/include" \
   -D BoostLib_LIBRARY_DIRS:PATH="${BOOST_ROOT}/lib" \
-D TPL_ENABLE_Netcdf=OFF \
-D TPL_ENABLE_HDF5=ON \
  -D HDF5_INCLUDE_DIRS:PATH="${HDF5_ROOT}/include" \
  -D TPL_HDF5_LIBRARIES:PATH="${HDF5_ROOT}/lib/libhdf5_hl.a;${HDF5_ROOT}/lib/libhdf5.a;${ZLIB_ROOT}/lib/libz.a" \
-D TPL_ENABLE_Zlib=ON \
  -D Zlib_INCLUDE_DIRS:PATH="${ZLIB_ROOT}/include" \
  -D TPL_Zlib_LIBRARIES:PATH="${ZLIB_ROOT}/lib/libz.a" \
\
 -D Trilinos_ENABLE_OpenMP=ON \
 -D Trilinos_ENABLE_COMPLEX=ON \
 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_EXAMPLES=OFF \
\
  -D Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
\
 -D Trilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
  -D Kokkos_ENABLE_OPENMP=ON \
  -D Kokkos_ENABLE_CUDA=OFF \
  -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
  -D Kokkos_ENABLE_CUDA_UVM=ON \
  -D Kokkos_ARCH_VOLTA70=ON \
  -D Kokkos_ARCH_POWER9=ON \
  -D Kokkos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_KokkosKernels=ON \
  -D KokkosKernels_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_ENABLE_CUDA=OFF \
  -D Tpetra_INST_SERIAL:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_INST_PTHREAD:BOOL=OFF \
  -D Tpetra_INST_CUDA:BOOL=OFF \
  -D Tpetra_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Sacado=ON \
  -D Sacado_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Belos=ON \
  -D Belos_ENABLE_TESTS=OFF \
\
 -D Trilinos_ENABLE_Stokhos=OFF \
  -D Stokhos_ENABLE_TESTS=OFF \
\
 -D Trilinos_ENABLE_Ifpack2=OFF \
  -D Ifpack2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Zoltan2=OFF \
  -D Zoltan2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_MueLu=OFF \
 -D Trilinos_ENABLE_Intrepid2=OFF \
  -D Intrepid2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Panzer=OFF \
  -D Panzer_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_ShyLU_NodeTacho=OFF \
 -D Trilinos_ENABLE_Zoltan2Sphynx=OFF \
 -D Trilinos_ENABLE_SEACAS=OFF \
\
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by ndellingwood** [comment]
I am reproducing the Tpetra test failures on non-Power9 systems (SKX, Blake testbed) with a newer version of gcc (version 11.2), just wanted to confirm the failures are not specific to Power9 nor the gcc version

**Reproducer** (Blake testbed, SKX arch, gcc/11.2):
```bash
module purge
module load gcc/11.2.0 openmpi/3.1.6/gcc/11.2.0 cmake/3.25.2 netlib-lapack/3.10.1/gcc/11.2.0

export BLAS_LIBRARIES="${BLAS_ROOT}/lib64/libblas.so"
export LAPACK_LIBRARIES="${LAPACK_ROOT}/lib64/liblapack.so"

cmake \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D Trilinos_ENABLE_OpenMP=ON \
 -D TPL_ENABLE_MPI=ON \
  -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-bind-to;socket;-map-by;socket" \
 -D TPL_ENABLE_BLAS=ON \
  -D TPL_BLAS_LIBRARIES:PATH="${BLAS_LIBRARIES}" \
 -D TPL_ENABLE_LAPACK=ON \
  -D TPL_LAPACK_LIBRARIES:PATH="${LAPACK_LIBRARIES}" \
  \
 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ENABLE_SERIAL=ON \
  -D Kokkos_ENABLE_OPENMP=ON \
 -D Trilinos_ENABLE_KokkosKernels=ON \
 -D Trilinos_ENABLE_Tpetra=ON \
  -D Tpetra_INST_SERIAL:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=ON \
  -D Tpetra_ENABLE_TESTS:BOOL=ON \
  -D Tpetra_ENABLE_EXAMPLES:BOOL=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by ndellingwood** [comment]
Running `TpetraCore_ImportExport2_UnitTests_Send_MPI_4` through the kernel-logger it appears the test is failing in this parallel_scan kernel: https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5893-L5969

**Comment by ndellingwood** [comment]
It's a bit slow going, so far what I've observed:

- `exportLIDs_h.data()` returns `0` see https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5786 

- `numPacketsPerLID_h.data()` returns `0` see https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5801

- The `parallel_reduce` that follows the above tries to access values from `exportLIDs_h` and `exportLIDs_h`, which is problematic https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5824
 
I'm assuming that changes in Kokkos affected an earlier portion of Tpetra code that allocates and sets `exportLIDs` and `numPacketsPerLID` (doesn't make sense that the behavior I listed above is as expected and previously worked, though I can also confirm if I get a build of Trilinos@develop up).
Will investigate https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_DistObject_def.hpp#L1550-L1556 next, which passes the suspect `exportLIDs` and `numPacketsPerLID` to `packAndPrepare`

**Comment by ndellingwood** [comment]
As I dig further, the point of failure (seg fault) with `TpetraCore_ImportExport2_UnitTests_Send_MPI_4` test is not consistent. Not confident my prior notes are useful, still investigating

**Comment by ndellingwood** [comment]
I have some progress that seems to correlate with changes from https://github.com/kokkos/kokkos/pull/5874 , though I don't have an explanation

In this Tpetra routine:
https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp#L345-L356

If I change the type from `size_t` to `int` used for reduction and as template for the `Kokkos::Max` reducer the test I've been using to investigate the failures `TpetraCore_ImportExport2_UnitTests_Send_MPI_4` passes reliably. 

@masterleinad or @dalg24 any thoughts or ideas on how use of size_t vs int may have an impact on results?

**Comment by ndellingwood** [comment]
Edited my previous comment, the change along with other debugging artifacts I accumulated along the way led to the subtest passing, unraveling some of that mess now

**Comment by ndellingwood** [comment]
I abandoned my previous debugging effort and started fresh, here are some updates:

* The test seg-faults in various spots, but if I comment out the parallel_scan at https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5893-L5969 then the test will reliably run until completion (with an expected correctness check failure of course due to removing the scan)

* I commented out the body of the lambda of the parallel_scan then reintroduced some components until the seg fault returned, at this line near the beginning https://github.com/trilinos/Trilinos/blob/cd2c0a141460b8c8ad028a6034e1333d137b3849/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp#L5898

* I dumped the contents of various data accessed within the lambda, e.g. exportLIDs_h, to file (tagged by rank), and compared between separate builds of Trilinos with kokkos@4.0.01 vs kokkos@develop and there does not seem to be a difference between the View and maps content-wise captured by the lambda

Not sure what to make of it yet, but finally honed in on a specific point in the code to look at

**Comment by masterleinad** [comment]
```diff
index 587f34e5cae..d0b73ca0f9b 100644
--- a/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
+++ b/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
@@ -5892,7 +5892,7 @@ namespace Tpetra {
     Details::disableWDVTracking();
     Kokkos::parallel_scan
       ("Tpetra::CrsGraph::packFillActiveNew: Pack exports",
-       inputRange, [=, &prefix]
+       inputRange, [&]
        (const LO i, size_t& exportsOffset, const bool final) {
          const size_t curOffset = exportsOffset;
          const LO lclRow = exportLIDs_h(i);
```
fixes the issue.

**Comment by masterleinad** [comment]
Capturing `rowMap` by copy is the problem.

**Comment by masterleinad** [comment]
Configuring `Trilinos` with `Teuchos_ENABLE_THREAD_SAFE=ON` also fixes it which confirms my suspicion that it's a RCP thread-safety issue and not really a `Kokkos` issue.

**Comment by ndellingwood** [comment]
@masterleinad thanks for chasing this down!
My interpretation of these updates is that use of `Teuchos_ENABLE_THREAD_SAFE=ON` is necessary to ensure thread-safety (i.e. avoid seg-faults) within some of the Tpetra::CrsGraph routines (and possibly elsewhere).
I'll suggest that this option be set within Tpetra when configured with a non-Serial host backend (e.g. here with OpenMP) as an option to handle this situation, unless you'd prefer I suggest something else

**Comment by masterleinad** [comment]
Yes, from my understanding the issue is that changes in #5874 created more copies of `RCP` variables inside an `OpenMP` parallel region and the `RCP` class is not thread-safe unless `Teuchos_ENABLE_THREAD_SAFE=ON` is set.
I think it's up to `Teuchos`/`Tpetra` maintainers to decide if setting this configuration flag (by default?) is the right option or if they rather want to make sure that no `RCP` variables are passed to `Kokkos` kernels.

We could still discuss if we also want to incorporate the `Kokkos` changes mentioned above but that seems somewhat orthogonal.

**Comment by ndellingwood** [comment]
@masterleinad that makes sense, thank you!

**Comment by ndellingwood** [comment]
Issue https://github.com/trilinos/Trilinos/issues/11921 filed with Trilinos
