### ISSUE TITLE
Kokkos::device_id not available

### ISSUE THREAD

**Issue by MarcelKoch** [kokkos/kokkos#6084]
The documentation describes the function `Kokkos::device_id` (see https://kokkos.github.io/kokkos-core-wiki/API/core/utilities/device_id.html) but it is not available when I include `Kokkos_Core.hpp`. Is there another way to query which device ID the default execution space uses?

**Please also include the following items to support reproducing the bug**
1. compilers (with versions): GCC 11.3.1
3. Kokkos release or commit used: both 4.0.0 and 3.7.01
4. platform and backend: Cuda
5. cmake configure command: `spack install kokkos+cuda+wrapper+cuda_constexpr+cuda_lambda+openmp cuda_arch=61 %gcc@11.3.1 ^kokkos-nvcc-wrapper@master`
7. please also attach the `KokkosCore_config.h` header file (generated during the build):
[KokkosCore_config.tar.gz](https://github.com/kokkos/kokkos/files/11341028/KokkosCore_config.tar.gz)

**Comment by dalg24** [comment]
I will amend the documentation.  This is being added in Kokkos 4.1.  You need to use the develop branch
