### ISSUE TITLE
[QUESTION] Architecture mismatch error

### ISSUE THREAD

**Issue by tbhaxor** [kokkos/kokkos#6092]
Which Kokkos_ARCH_ should I use for the **NVIDIA Tesla V100** cards. 

I am using it with athenapk and it is failing with error

```
==> Error: Spec 'cuda@11.4.0' matches no installed packages.
Kokkos::Cuda::initialize ERROR: likely mismatch of architecture
```

Currently I am using `-DKokkos_ARCH_VOLTA72=ON`, this caused error

**Comment by tbhaxor** [comment]
In the wikipedia it also mention VOLTA https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units

**Comment by masterleinad** [comment]
`Kokkos_ARCH_VOLTA70=ON`.

**Comment by masterleinad** [comment]
In general, the last two digits match the compute capability of the architecture to use.

**Comment by tbhaxor** [comment]
> `Kokkos_ARCH_VOLTA70=ON`.

And, how did you find it?

Where is this documented?

**Comment by stanmoore1** [comment]
See table here: https://en.wikipedia.org/wiki/CUDA

**Comment by stanmoore1** [comment]
Also see this link: https://github.com/kokkos/kokkos/wiki/Compiling

**Comment by masterleinad** [comment]
Also, note that the architecture is auto-detected when using `CMake` and configuring on a compute node.

**Comment by tbhaxor** [comment]
Yes, it does but not on HPC login nodes where we have only CPU and use slurm scripts to schedule jobs for GPU nodes.

**Comment by masterleinad** [comment]
Right, but you could also execute https://github.com/kokkos/kokkos/blob/develop/cmake/compile_tests/cuda_compute_capability.cc on a compute node (if configuring `Kokkos` in a job script is too difficult).

**Comment by tbhaxor** [comment]
Great @masterleinad this would solve issue.
