### ISSUE TITLE
Kokkos Make System can induce Errors on Cray Volta System

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#610]
Kokkos automatically manages parallelism when running `make` but this uses too many resources when running with the Cray compiler. Causes compile errors because `/tmp` is exhausted.

**Comment by crtrott** [comment]
Marking this as a compiler issue just to tease you ;-)

**Comment by crtrott** [comment]
Fix coming up.

**Comment by crtrott** [comment]
Here you go. I don't have it used yet inside of test_all_sandia though. And regarding compiler issue: maybe the Cray software stack should somehow manage to deal with this. I can compile this on my macbook air with -j.

**Comment by nmhamster** [comment]
Now it only runs a single compilation at once, so very slow. What we would like is to just have `make -j <n>` work if possible (for the user).

**Comment by crtrott** [comment]
Uhm no it shouldn't. I did test this, by default it does -j 32, and you can overwrite the value by --make-j=16 for example as a command line argument to generate_makefile.bash.
