### ISSUE TITLE
Builing with different compilers for Kokkos and application broken with OpenMP

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#6100]
#5978 showed that we silently broke supporting building Kokkos and downstream with different compilers if we are using `OpenMP` since we are now trying to find `OpenMP` via `CMake`. We should discuss if we want to try to fix this.

**Comment by masterleinad** [comment]
See https://github.com/kokkos/kokkos/pull/5978#discussion_r1154570289.

**Comment by crtrott** [comment]
Not sure we care for now. Let's see if someone complains.
