### ISSUE TITLE
How to use cuda-gdb to debug a kokkos kernel function (run on GPU) ?

### ISSUE THREAD

**Issue by 123wujiao** [kokkos/kokkos#6105]
hello, I want to use cuda-gdb to find the memory access mode of some code block, but now I cant't enter to kokkos code, For example, after I add a breakpoint, I cannot enter the breakpoint, why? how do it? thanks very much.

```
void PairTersoffKokkos<DeviceType>::tersoff_compute(const int &ii, EV_FLOAT& ev) const {

  // The f array is duplicated for OpenMP, atomic for CUDA, and neither for Serial
  

  const auto v_f = ScatterViewHelper<NeedDup_v<NEIGHFLAG,DeviceType>,decltype(dup_f),decltype(ndup_f)>::get(dup_f,ndup_f);
  const auto a_f = v_f.template access<AtomicDup_v<NEIGHFLAG,DeviceType>>();

  const int i = d_ilist[ii];
  if (i >= nlocal) return;
  const X_FLOAT xtmp = x(i,0);
  const X_FLOAT ytmp = x(i,1);
  const X_FLOAT ztmp = x(i,2);
  const int itype = d_map(type(i));  
  const tagint itag = tag(i);

  F_FLOAT fi[3], fj[3], fk[3];
```

**Comment by stanmoore1** [comment]
Did you compile with `-G` (best) or `-lineinfo` (might work)?

**Comment by ajpowelsnl** [comment]
@vlkale -- Can Kokkos Tools help with this?

**Comment by vlkale** [comment]
@ajpowelsnl Thanks for this question. I haven’t used CUDA-gdb on a Kokkos program to debug a Kokkos kernel on a GPU I imagine it wouldn’t tell or help much though. The reason would the same as the motivation for have having a Kokkos Tools connector for each vendor third-party profiler, e.g., VTune-connector, nvtx-connector. For example, one reason is the problem of function name demangling when using, e.g., nvprof on a Kokkos program using CUDA as its backend.Maybe interactive debugging for Kokkos is best accomplished by investing time to developing a kokkos-gdb that sits on top of each of its backends’ gdb. Given the third-party profiling tools support available in Kokkos Tools, I think this wouldn’t involve starting from scratch to do this, and some code could be reused.Right now, debugging and code analysis efforts for Kokkos Tools have focused non-interactive (non-gdb-style) debugging: primarily logging, static/symbolic analysis, and simply putting assertions in a Kokkos program. On May 8, 2023, at 2:07 PM, ajpowelsnl ***@***.***> wrote:﻿
@vlkale -- Can Kokkos Tools help with this?

**Comment by ajpowelsnl** [comment]
> Did you compile with `-G` (best) or `-lineinfo` (might work)?

Hi @123wujiao -- were you able to try @stanmoore1's suggestion, i.e., compiling w/ `-G` to get your debug symbols?  After that point, it may become straightforward to use `cuda-gdb` (https://developer.nvidia.com/cuda-gdb).  Either way, please give us a status update on your end.

**Comment by ajpowelsnl** [comment]
Hi @123wujiao -- were you able to do the debugging you needed ?  If not, please do let us know in a couple of days.

**Comment by ajpowelsnl** [comment]
Hi @123wujiao - we're assuming that you were able to resolve this issue, so we'll close it.  Please let us know if you're still needing help, and we'll re-open.
