### ISSUE TITLE
Construct Kokkos::Array from list initialization?

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#611]
Would it be possible to initialize a `Kokkos::Array` with an aggregate initialization?
In other words, I'd like to be able to do
```
Kokkos::Array<double, 3> p = { 1.0, 2.0, 3.0 };
```
and I wondered if there was any reason why this had not been implemented.

**Comment by hcedwar** [comment]
This would be a std::initializer_list constructor which is not (yet?) available through CUDA.  As such could only be supported within host-code.

**Comment by dalg24** [comment]
According to the [CUDA documentation](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#language-features) it is available from version 7.0.

**Comment by mhoemmen** [comment]
@dalg24 wrote:
> and I wondered if there was any reason why this had not been implemented.

Kokkos _is_ an open-source project; you could contribute an implementation via pull request :-)

I think this makes sense for 1-D Kokkos::View, but it could be confusing for multiple-dimension Views.  Would the nested lists have the same layout as the View, or would they follow a standard convention?  Either way could confuse someone.

**Comment by crtrott** [comment]
Mark this is for Kokkos::Array which is 1D and compile time length by definition.

**Comment by mhoemmen** [comment]
Sorry my bad :)

**Comment by dalg24** [comment]
Would you consider merging something like that?  Of course I realize that the specialized template would need to be changed as well.  I just want to make sure I am on track before I implement more.

**Comment by crtrott** [comment]
Yeah we surely can talk about how to make this something we can merge in. We generally are willing to accept pull requests. One of the requirements would be a unit test which works with all backends.

**Comment by dsunder** [comment]
The normal (non-proxy) Kokkos::Array is suppose to be an aggregate type like std::array.  We need to remove the constructors and destructor from the struct to assure this behavior.  

Most compilers are happier with the double brace syntax for initialize std::array, i.e. std::array<int,3> a = {{ 1, 2, 3 }};
Kokkos::Array will behave in the same way when we remove the constructors and destructor.

**Comment by dalg24** [comment]
@dsunder wouldn't `m_elem` need to be public for the struct to be considered as an aggregate?

**Comment by dalg24** [comment]
OK turns out this would do the trick:
```diff
diff --git a/core/src/Kokkos_Array.hpp b/core/src/Kokkos_Array.hpp
index 038eda8..47a55cd 100644
--- a/core/src/Kokkos_Array.hpp
+++ b/core/src/Kokkos_Array.hpp
@@ -59,7 +59,7 @@ template< class T      = void
         , class Proxy  = void
         >
 struct Array {
-private:
+public:
   T m_elem[N];
 public:
```
I checked how `std::array` is implemented on libstdc++ and they also have it public.  Would that be an acceptable change in Kokkos?

**Comment by hcedwar** [comment]
Best to combine that with changing the member variable name to something onerous, like
`m_internal_implementation_member_variable`

**Comment by dalg24** [comment]
Closing issue since PR #616 got merged into the `develop` branch.  Thanks.

**Comment by hcedwar** [comment]
Remains open until develop -> master promotion occurs.

**Comment by dalg24** [comment]
OK. Sorry about that.

**Comment by hcedwar** [comment]
Had to revert do to build errors:  https://github.com/kokkos/kokkos/pull/619

**Comment by dalg24** [comment]
Where can I see the error logs?

**Comment by hcedwar** [comment]
https://jenkins-son.sandia.gov/view/Kokkos/job/Kokkos_develop/

**Comment by dalg24** [comment]
Is it behind a firewall?  I cannot see the build.

**Comment by hcedwar** [comment]
email me and I will forward the jenkins reports

**Comment by dalg24** [comment]
That's weird.  I just tried with clang-3.9.1 and the test builds and passes.

**Comment by hcedwar** [comment]
-Wall ?

**Comment by crtrott** [comment]
Look in kokkos/config/test_all_sandia to see the warning and warning as errors flags we are using.

**Comment by dalg24** [comment]
OK I understand now, "-Wall" and "-Werror".

That's fine, I pushed another commit to use double braces in the initializations.

But for reference:
* On stackoverflow: [Is it wise to ignore gcc/clang's “-Wmissing-braces” warning?](http://stackoverflow.com/questions/13905200/is-it-wise-to-ignore-gcc-clangs-wmissing-braces-warning)
* Documentation for [aggregate initialization](http://en.cppreference.com/w/cpp/language/aggregate_initialization) on cppreference.com.
