### ISSUE TITLE
Nightly compilation failures with Hip,Serial backends enabled, rocm/5.2.0

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6115]
**Describe the bug**
Nightly builds with Hip,Serial backends enabled, rocm/5.2.0, fail to compile following the zero-memset reorg #6087; compilation error did not occur with Hip+OpenMP builds

```
22:16:47 /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/Kokkos_Serial.hpp:215:8: error: explicit specialization of undeclared template struct 'ZeroMemset'
22:16:47 struct ZeroMemset<
22:16:47        ^         ~
22:16:47 In file included from /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/unit_test/headers_self_contained/tstHeader.cpp:26:
22:16:47 In file included from /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/Kokkos_Serial.hpp:238:
22:16:47 In file included from /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp:20:
22:16:47 In file included from /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/Kokkos_Parallel.hpp:31:
22:16:47 In file included from /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/Kokkos_View.hpp:490:
22:16:47 In file included from /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:35:
22:16:47 /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/impl/Kokkos_ZeroMemset_fwd.hpp:23:42: error: template type parameter conflicts with previous template type parameter pack
22:16:47 template <typename ExecutionSpace, class ViewType>
22:16:47                                          ^
22:16:47 /home/jenkins/caraway-new/workspace/Kokkos_develop_carawaymi50_rocm520_hipserial/kokkos/core/src/Kokkos_Serial.hpp:214:30: note: previous template type parameter pack declared here
22:16:47 template <class DT, class... DP>
```

@tcclevenger are you able to investigate?

**Reproducer** (Caraway testbed, MI100 queue):
```bash
module load cmake/3.19.3 rocm/5.2.0

$KOKKOS_PATH/generate_makefile.bash --with-devices=Hip,Serial --arch=VEGA908 --compiler=hipcc --cxxflags="-O3 -Werror " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

**Comment by tcclevenger** [comment]
Yes, I'll find some time today.

**Comment by tcclevenger** [comment]
@ndellingwood I don't have access to a HIP machine (is that possible to get as a part of the Kokkos group?). Looking at the output there are a few confusing things to me:
1. After my PR, `Kokkos_Serial.hpp` no longer contains any reference to `ZeroMemset`. Part of the error references
```
Kokkos_Serial.hpp:214:30: note: previous template type parameter pack declared here
        template <class DT, class... DP>
```
That line 214 was the old template declaration for `ZeroMemset` before my PR.
2. The include trail it references should no longer be an issue since `Kokkos_Serial.hpp` no longer contains any reference to `ZeroMemset`
3. This may just be a misunderstanding of how CMake is working, but it references the file `core/src/Kokkos_Serial.hpp` but that file is actually in a subfolder `core/src/Serial/Kokkos_Serial.hpp`. Is it possible that the old `Kokkos_Serial.hpp` got copied to the wrong folder?

**Comment by tcclevenger** [comment]
@Rombur ahh thanks, that makes the error make sense.

**Comment by ndellingwood** [comment]
@Rombur thanks I didn't realize that. I updated the job to make sure it cleans up before checkout
@tcclevenger sorry for the distraction and thanks for taking a look so quickly. Re: HIP machine, you can request access to Caraway, I'll email a couple details

**Comment by dalg24** [comment]
Can we close this?

**Comment by ndellingwood** [comment]
Yeah, I'll clean up the labels and close
