### ISSUE TITLE
create_conf_view ??

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#613]
Hello,

I would like to create a copy of a view, which has a different mechanism from mirroring. I have a situation as follows.
```
teplate<typename view_type>
foo(view_type a) {
  view_type acopy("acopy", a.dimension(0), a.dimension(1), a.dimension(2));
  deep_copy(acopy, a);
  
  for_each {
    a(i,jk) = doSomething(copy(i,j,k));
  }
}
```

The problem is that input view can have different rank e.g., 1 and 2. The computing pattern can still remain same as kokkos treat the extra dimension is 1 and operator() also can handle that. In this case, deep_copy would not work as they have different ranks now. Otherwise I have to put switch case for all possible ranks. Mirroring does not work as mirroring will return the same view if the memory space is same. The suggested `create_conf_view` provides conforming view structure (however, strided layour should be changed into layour left or layout right according to its execution space. 
```
teplate<typename view_type>
foo(view_type a) {
  auto acopy = Kokkos::create_conf_view("acopy", a);
  deep_copy(acopy, a);
  
  for_each {
    a(i,jk) = doSomething(copy(i,j,k));
  }
}
```

Do we already have functions for this ?

**Comment by ibaned** [comment]
We are moving away from rank polymorphism. Unless this is mission-critical, we likely won't do it.
