### ISSUE TITLE
MaxLoc/MinLoc reductions stopped supporting non-integral for location

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#6134]
There are use cases such as finding the maximum value in a multi-dimensional array plus the index pair. Clearly we don't have a test for that, so we need to unbreak this (i.e. don't require location to be an integral) and test for it. This got broken here: https://github.com/kokkos/kokkos/pull/5698

**Comment by dalg24** [comment]
What are the constraints on the type?  Has non-constant public members `val` and `loc` to which we can assign <something>?

**Comment by crtrott** [comment]
no, the assert was contraining the type of loc

**Comment by crtrott** [comment]
updated the example.

**Comment by dalg24** [comment]
Closing as this is resolved in develop and the issue was introduced post 4.0
