### ISSUE TITLE
output from cmake command

### ISSUE THREAD

**Issue by yqiao18** [kokkos/kokkos#6139]
When I run make -j 24 command, I got the following output and error. How to fix it?
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3  -c exercise_1_begin.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_CPUDiscovery.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_Command_Line_Parsing.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_Core.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_Error.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_ExecPolicy.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_HostBarrier.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_HostSpace.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_HostSpace_deepcopy.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_HostThreadTeam.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_MemoryPool.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_MemorySpace.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_Profiling.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_Spinwait.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_Stacktrace.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/impl/Kokkos_hwloc.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/containers/src/impl/Kokkos_UnorderedMap_impl.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
g++ -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -std=c++17 -march=core-avx2 -mtune=core-avx2 -mrtm -fopenmp=libomp -I./ -I/Users/qiaoyunhan/Kokkos/kokkos/core/src -I/Users/qiaoyunhan/Kokkos/kokkos/containers/src -I/Users/qiaoyunhan/Kokkos/kokkos/algorithms/src -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/desul/include -I/Users/qiaoyunhan/Kokkos/kokkos/tpls/mdspan/include -O3 -c /Users/qiaoyunhan/Kokkos/kokkos/core/src/OpenMP/Kokkos_OpenMP_Task.cpp
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make: *** [Kokkos_CPUDiscovery.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [exercise_1_begin.o] Error 1
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: clang: error: error: unsupported argument 'libomp' to option 'fopenmp='
unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make: *** [Kokkos_Stacktrace.o] Error 1
make: *** [Kokkos_Error.o] Error 1
make: *** [Kokkos_Command_Line_Parsing.o] Error 1
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make: *** [Kokkos_MemorySpace.o] Error 1
make: *** [Kokkos_HostSpace_deepcopy.o] Error 1
make: *** [Kokkos_hwloc.o] Error 1
make: *** [Kokkos_SharedAlloc.o] Error 1
make: *** [Kokkos_HostBarrier.o] Error 1
make: *** [Kokkos_ExecPolicy.o] Error 1
make: *** [Kokkos_Spinwait.o] Error 1
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make: *** [Kokkos_Core.o] Error 1
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make: *** [Kokkos_MemoryPool.o] Error 1
make: *** [Kokkos_HostSpace.o] Error 1
make: *** [Kokkos_Profiling.o] Error 1
make: *** [Kokkos_UnorderedMap_impl.o] Error 1
make: *** [Kokkos_HostThreadTeam.o] Error 1
clang: error: unsupported argument 'libomp' to option 'fopenmp='
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make: *** [Kokkos_OpenMP_Task.o] Error 1
make: *** [Kokkos_OpenMP_Instance.o] Error 1

**Comment by masterleinad** [comment]
Which `CMake` options are you using to configure the project?

**Comment by yqiao18** [comment]
I am using GCC

**Comment by masterleinad** [comment]
> I am using GCC

It's hard to help with so little information.
Shot in the dark: Make sure you use the same compiler when configuring Kokkos and the project using it.

**Comment by yqiao18** [comment]
Thank you so much. I am a new guy to Kokkos. May I ask where can I see the compiler information when configuring the Kokkos?

**Comment by dalg24** [comment]
Yunhan, GitHub is used for development and to report bugs.  If you are a new user and would like some help to get started, I recommend you [join us on Slack](https://kokkosteam.slack.com/).

**Comment by yqiao18** [comment]
Thank you for your reminder. Do I need someone to invite me to join slack?

**Comment by dalg24** [comment]
If you are not able to sign in with your email address (chances are we already whitelisted your school/organization), then send an email to me or Christian.  You will find our contact info here https://github.com/kokkos/kokkos/blob/4197fa833d27679fecb8a22a3321582340417181/LICENSE#L234

**Comment by yqiao18** [comment]
Ok. Really appreciate it.

**Comment by yqiao18** [comment]
Damien, I already emailed u. Thank you!
