### ISSUE TITLE
Type alias `DeviceSpace` to name non-shared device memory

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos#6168]
We've always had `HostSpace`. We added `SharedSpace` and `SharedHostPinnedSpace` to spare applications conditional logic based on the enabled device backend to specify whichever of UVM or equivalent. We didn't add a simple `DeviceSpace` to go along with it, so applications still have to figure out what that is if they want to specify that.

One reason they may want this is a dependency on library code that still relies on UVM defaults for `Kokkos::View<T*>` without a specified space, but wanting to specifically allocate non-UVM memory in its own code.

**Comment by dalg24** [comment]
Please discuss whether the `DeviceSpace` alias should be defined if no device backend is enabled (only serial or host parallel backends)

**Comment by PhilMiller** [comment]
I believe it should, for the same reason we did so for `SharedSpace` - so that applications could use these aliases completely ubiquitously, without conditional compilation

**Comment by crtrott** [comment]
Note that if we do this it's gonna be an alias for `DefaultExecutionSpace::memory_space` and should be called `DefaultSpace` in my opinion. And I do think that the unfortunate CUDA UVM option would change this, because that is what the UVM thing is meant to do: change the meaning of the default space. 

And there is absolutely no guarantee that there ever is a non-shared device space. In fact most of the next gen GPUs won't have that.

**Comment by dalg24** [comment]
> I believe it should, for the same reason we did so for `SharedSpace` - so that applications could use these aliases completely ubiquitously, without conditional compilation

This is not what we did.  `Shared[HostPinned]Space` are not defined when OpenMPTarget or OpenACC is enabled.

**Comment by PhilMiller** [comment]
After further discussion, I've come around to the notion that since the option to allocate in CUDA UVM by default is deprecated and going away, it's somewhat pointless to permanently support a workaround for its presence in the meantime. 

The suggested workaround is along the lines of
```c++
#if KOKKOS_ENABLE_CUDA
// Avoid the possibility that KOKKOS_ENABLE_CUDA_UVM would yield CudaUVMSpace in the common case below
using MyDeviceMemorySpace = Kokkos::CudaSpace;
#else
using MyDeviceMemorySpace = Kokkos::DefaultExecutionSpace::memory_space;
#endif
```
