### ISSUE TITLE
Cuda casts half_t and bhalf_t NaNs to float incorrectly 

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos#6179]
With `T=half_t` or `T=bhalf_t`, it appears that Cuda is casting `quiet_NaN<T>::value` and `signaling_NaN<T>::value` to a representable floating point number. Note that Kokkos defines NaN  numeric traits for `half_t` and `bhalf_t`; these constants may not be defined elsewhere (e.g. in the Cuda SDK).

**Comment by masterleinad** [comment]
Fixed in #6543.
