### ISSUE TITLE
Slack workspace administrator: Slack channel access request

### ISSUE THREAD

**Issue by cander111** [kokkos/kokkos#6227]
Can you please help me reach the Slack workspace administrator for https://kokkosteam.slack.com?

I would like to request access to the slack channel but I do not have an email address with one of the pre-approved domains.

I have some technical questions related to using Kokkos thread teams with Kokkos Kernels.

Thanks.

**Comment by masterleinad** [comment]
Can you post an e-mail address you would like to use?

**Comment by cander111** [comment]
Thanks for the quick reply. Unfortunately, my organization does not allow me to post my email address in public spaces, is there a way to send a private message?

**Comment by masterleinad** [comment]
Write an e-mail to me(https://www.ornl.gov/staff-profile/daniel-arndt).

**Comment by cander111** [comment]
Thanks for your help!
