### ISSUE TITLE
Nightly testing of SIMD stuff at SNL

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#6232]
We need a SNL nightly testing of all SIMD variants.

**Comment by ndellingwood** [comment]
Is there any cmake option or simd-specific setting that needs to be set to enable the testing? Are the appropriate simd variants enabled based on the arch that is specified at configuration for the build?
I don't see an option under CMake Keywords on the wiki and didn't see any options pop up when grepping for "SIMD" in the cmake directory

**Comment by masterleinad** [comment]
> Are the appropriate simd variants enabled based on the arch that is specified at configuration for the build?

Yes.

**Comment by ndellingwood** [comment]
Status update:

* AVX512 testing (`Kokkos_ARCH_SKX=ON`) - has been in place for gcc/8-11, intel/19.0.5, intel/2021.4, clang/10
  * TODO: Increase coverage with clang
* AVX2 testing (`Kokkos_ARCH_BDW=ON`) - is lacking
  * Located a machine with dedicated compute nodes with BDW for nightly testing
  * TODO: Add new machine and tests to nightly tests
* NEON testing (?) - I have not identified a machine with ARM Cortex-A,B type arch
  * TODO: Set up compile-only testing for now

**Comment by ajpowelsnl** [comment]
Hi @ndellingwood - can you update us on this tomorrow?

**Comment by ndellingwood** [comment]
Status update 8/9/2023:

* AVX512 testing (`Kokkos_ARCH_SKX=ON`) coverage temporarily reduced; Blake is down for DST hardware and software upgrades for a few days. gcc/8 jobs temporarily moved to kokkos-dev-2
* AVX2 (`Kokkos_ARCH_BDW=ON`) nightly coverage added on kokkos-dev-2
* NEON : (`Kokkos_ARCH_ARMV8_THUNDERX2=ON`) machine identified for testing (mayer) with arm/20.1 compiler available, sys. admins are working on connection problems with arm compiler license server issues on compute nodes
