### ISSUE TITLE
Kokkos Serial build on Cray testbed segfaults

### ISSUE THREAD

**Issue by jjellio** [kokkos/kokkos#626]
Hi,

I've been trying to build a Trilinos build with Serial only, on a cray testbed and the resulting binaries (unit tests) all segfault before hitting main(). I've narrowed this down somewhat, by eliminating Trilinos.
I've been able to reproduce this for both HSW and SNB arches, and the Trilinos exhibited the same error for KNL.  My OpenMP only builds all seem OK.

The error seems to come before main(), so this may not be a kokkos issue.

WIth a fresh checkout of Kokkos master.

Modules:
```

Currently Loaded Modulefiles:
  1) modules/3.2.10.4                  6) ugni/6.0.12-2.1                  11) nodehealth/5.2.0-5.46            16) craype-network-aries             21) PrgEnv-intel/6.0.3
  2) alps/6.1.7-23.1                   7) gni-headers/5.0.7-3.1            12) system-config/2.2.18-3.39        17) craype/2.5.6                     22) cray-mpich/7.4.2
  3) nodestat/2.2-2.40                 8) dmapp/7.1.0-12.37                13) sysadm/2.2.2-3.39                18) cray-libsci/16.07.1              23) craype-haswell
  4) sdb/2.2.1-3.119                   9) xpmem/0.1-4.5                    14) Base-opts/2.1.3-2.16             19) pmi/5.0.10-1.0000.11050.0.0.ari  24) friendly-testing
  5) udreg/2.3.2-4.6                  10) llm/20.2.4-3.18                  15) intel/17.0.1                     20) atp/2.0.2                        25) cmake/3.5.2

```

```../generate_makefile.bash --with-openmp --with-options="disable_profiling" --arch=HSW --compiler=CC```

```
Starting program: /home/jjellio/build/kokkos/build/core/unit_test/KokkosCore_UnitTest_Serial 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x0000000000e12931 in __gthread_once (__func=0xe128d0 <std::locale::_S_initialize_once()>, __once=<optimized out>)
    at /tmp/peint/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/x86_64-suse-linux/bits/gthr-default.h:699
#2  std::locale::_S_initialize () at ../../../../../cray-gcc-6.1.0/libstdc++-v3/src/c++98/locale_init.cc:316
#3  0x0000000000e12983 in std::locale::locale (this=0x13d6f58 <__gnu_internal::buf_cout_sync+56>) at ../../../../../cray-gcc-6.1.0/libstdc++-v3/src/c++98/locale_init.cc:250
#4  0x0000000000e0f9b4 in basic_streambuf (this=<optimized out>) at /tmp/peint/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/streambuf:466
#5  stdio_sync_filebuf (__f=0x138d5e0 <_IO_2_1_stdout_>, this=<optimized out>) at /tmp/peint/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/ext/stdio_sync_filebuf.h:80
#6  std::ios_base::Init::Init (this=<optimized out>) at ../../../../../cray-gcc-6.1.0/libstdc++-v3/src/c++98/ios_init.cc:85
#7  0x0000000000420e4b in __sti__$E ()
#8  0x0000000000ec2407 in __libc_csu_init (argc=argc@entry=1, argv=argv@entry=0x7fffffff6ae8, envp=0x7fffffff6af8) at elf-init.c:88
#9  0x0000000000ec1ead in __libc_start_main (main=0xd7da80 <main>, argc=1, argv=0x7fffffff6ae8, init=0xec2390 <__libc_csu_init>, fini=0xec2420 <__libc_csu_fini>, rtld_fini=0x0, stack_end=0x7fffffff6ad8) at libc-start.c:244
#10 0x0000000000402807 in _start () at ../sysdeps/x86_64/start.S:122
```

**Comment by jjellio** [comment]
I tried building the Kokkos unit tests using the underlying Intel compiler directly. The binaries seem to run fine.  This appears to be an issue with conflicting libraries added by the craype wrapper.
@nmhamster

**Comment by jjellio** [comment]
Small update on this.  This is not a Kokkos issue, but it seems the Kokkos team should be aware of the issue.

From a sys-admin that is helping to diagnose the root cause:

> I think it comes down to the fact that the icpc link is dynamic, and the CC link is static.  When I link with icpc statically,
> 
> icpc -L/home/users/u3186/kokkos/build/core/unit_test -mavx  TestSerial_Other.o TestSerial_Reductions.o TestSerial_Atomics.o TestSerial_Team.o  TestSerial_SubView_a.o TestSerial_SubView_b.o  TestSerial_SubView_c01.o TestSerial_SubView_c02.o TestSerial_SubView_c03.o TestSerial_SubView_c04.o  TestSerial_SubView_c05.o  TestSerial_SubView_c06.o   TestSerial_SubView_c07.o  TestSerial_SubView_c08.o  TestSerial_SubView_c09.o TestSerial_SubView_c10.o TestSerial_SubView_c11.o TestSerial_SubView_c12.o TestSerial_ViewAPI_a.o TestSerial_ViewAPI_b.o UnitTestMain.o gtest-all.o  -lkokkos -ldl  -o KokkosCore_UnitTest_Serial -static -Wl,-as-needed,-lpthread,-no-as-needed
> 
> I get an executable that segfaults at runtime.  If I link with CC dynamically,
> 
> export CRAYPE_LINK_TYPE=dynamic
> CC -L/home/users/u3186/kokkos/build/core/unit_test -mavx -lpthread  TestSerial_Other.o TestSerial_Reductions.o TestSerial_Atomics.o TestSerial_Team.o  TestSerial_SubView_a.o TestSerial_SubView_b.o  TestSerial_SubView_c01.o TestSerial_SubView_c02.o TestSerial_SubView_c03.o TestSerial_SubView_c04.o  TestSerial_SubView_c05.o  TestSerial_SubView_c06.o   TestSerial_SubView_c07.o  TestSerial_SubView_c08.o  TestSerial_SubView_c09.o TestSerial_SubView_c10.o TestSerial_SubView_c11.o TestSerial_SubView_c12.o TestSerial_ViewAPI_a.o TestSerial_ViewAPI_b.o UnitTestMain.o gtest-all.o  -lkokkos -ldl  -o KokkosCore_UnitTest_Serial
> 
> **It works.  The static link, without the as-needed around libpthread, causes multiple definitions for functions that are defined in both libpthread and libc.  But with the -as-needed (which CC supplies when it links statically), there's some kind of miscommunication between libpthread and libc, and some global flag used by the thread initializer isn't properly set, and the initializer takes a wrong branch, and tries to call a function that hasn't been linked in (resulting in the branch to location 0).**

Currently, there is no fix for building a Serial only (Static) build on this machine. I'll update this issue as things progress.

**Comment by jjellio** [comment]
An analyst has help trace this down, and provided a small example

```
#include <iostream>
#include <pthread.h>
int main (int argc, char *argv[]) {
  pthread_key_t key;
  pthread_mutex_t mut;
  pthread_key_create(&key, NULL);
  pthread_mutex_init(&mut, NULL);
  pthread_mutex_lock(&mut);
  pthread_mutex_unlock(&mut);
  return 0;
}
```

> Compile with:
> icpc  test.cc  -static -Wl,-as-needed,-lpthread,-no-as-needed
> 
> And you will get the segfault.
> I'll file a Cray Bug on this, since CC uses static linking and the as-needed business.

This issue has been filed with Cray (Bug 848163).

**Comment by crtrott** [comment]
Thanks for tracking this down.

**Comment by jjellio** [comment]
Does anyone have a suggestion for a work around? I would like a Serial only build on Cray.

On option, would be to enable Serial, and compile with -qopenmp. If Trilinos/Kokkos code is properly written, this should have little effect.

I also tried icpc as the compiler, but linked with ld.gold (-B /path/to/ld.gold) that does not help.

**Comment by mhoemmen** [comment]
Some apps will build with OpenMP enabled, whether or not they use it, because they like the "one configuration to rule them all" approach.  Thus, I see it as acceptable to have OpenMP enabled, if that gets the build to work :)

**Comment by ibaned** [comment]
It sounds like this has been worked through as much as possible. Please reopen if further discussion is needed.
