### ISSUE TITLE
Question: StaticCrsGraph memory traits

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#627]
I cannot find much information about the StaticCrsGraph, but I might have a use for it. Would `Kokkos::StaticCrsGraph<const double, Kokkos::MemoryTraits<Kokkos::RandomAccess> >` create a texture object on the Cuda backend? 

```c++
Kokkos::StaticCrsGraph<const double, Kokkos::MemoryTraits<Kokkos::RandomAccess> > a;
Kokkos::StaticCrsGraph<double> a_non_const;

set_a(a_non_const);

a = a_non_const;

Kokkos::parallel_for(…
{
  // do stuff with a
  do_something(a);
});
```

**Comment by mhoemmen** [comment]
@dholladay00 Header file for Kokkos::StaticCrsGraph is kokkos/containers/src/Kokkos_StaticCrsGraph.hpp.  Even if the above code works, I would not recommend applying RandomAccess to the whole graph, unless you really plan on accessing random entries in the graph.

**Comment by dholladay00** [comment]
This data structure stores data read in from an input file. It really is constant data that is accessed randomly. Currently this data is stored in a `View<const double**, RandomAccess>` but that is a very inefficient method as it is actually a ragged (non-rectangular) 2d array. My other option (that I use elsewhere) is a `View< View<const double*, RandomAccess>* >`, but it is not clear how the texture objects would get created for the "inner" views. 

Maybe I should be asking this question: for constant data that is accessed randomly, but is a ragged 2D array, would using textures on the Cuda backend buy me performance?

**Comment by hcedwar** [comment]
The StaticCrsGraph is what you need.  If you could describe your access pattern in a little more detail we could probably define a small enhancement to support it.

**Comment by dholladay00** [comment]
These data structures are used in a number of different ways, there are several layers of indirection associated with each access. 

```c++
parallel_for (ThreadVectorRange(team, n_interacions), [&] (int interaction)
{
  const int global_interaction = offset_view_type(ii) + interaction; // ii is the team thread loop index
  const int local_level = level_list_view(global_interaction) - 1;
  const int local_level_prime = level_prime_list_view(global_interaction) - 1;
  const double ratio = a(local_level,ii)/a(local_level_prime,ii+1); // convert a from View<double**> to Crs
});
```

A lot of this is just hand rolled to deal with the mapping to the irregular structure. It is not something I have had time to change until now. Also, I have been in recent contact with @crtrott via email about visiting SNL to take a closer look at some of this.

**Comment by hcedwar** [comment]
`offset_view_type` is the StaticCrsGraph `row_map`
`level*list_view` is the StaticCrsGraph `entries` where `DataType` is `int[2]`
The two dimensional `a` array is like the values of a CRS matrix.  Access performance might be improved if `a` is `View<const double**,CudaSpace,RandomAccess>` and if the `local_level` and `local_level_prime` indices are fairly close to one another with the range of `interaction` indices.

**Comment by dholladay00** [comment]
So, it looks like I should change how those indices are stored:

```c++
// old way
View<int*> list(…);
View<int*> list_prime(…);
i = list(interaction);
i_prime = list_prime(interaction);

// new way
View<int*[2]> combined_list(…);
i = combined_list(interaction,0);
i_prime = combined_list(interaction,1);
```
I can definitely implement the above change.

However, I wanted to replace a `View<const double**, RandomAccess>` with a `StaticCrsGraph<const double, RandomAccess>` and just was curious if it gets the same speed benefits as a 2D view with `const` and `RandomAccess` traits.
