### ISSUE TITLE
Virtual inheritance and Cuda

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#628]
Code came up recently that was failing non-straightforwardly on the GPU. I traced the problem to two separate things, illustrated below in a reproducer. The reproducer as is works because it uses workarounds, but it shows in comments versions that break. It's best to run the program with cuda-memcheck because in this reduced setting, it can complete despite memory errors. In a larger program, the program will fail.

Do others think these are bugs; or is combination of memcpy-to-device, copy ctors, virtual inheritance, constant memory, etc., all conspiring to make correct but unfortunate behavior?

I tested with cuda/8.0.44 and 7.5.

Code:
```
#include <Kokkos_Core.hpp>

namespace impl {
struct ABase {
   const int base;
   ABase(int base) : base(base) {}
};

struct A : virtual public ABase {
   const int a;
   A(int a,int base) : ABase(base), a(a) {}
};
}

// There are a few separate bugs in what follows. 1 and 2 related; 3 is independent.
struct Wrapper {
   using A = impl::A;  // 1. Cuda can't handle using this to declare a. So don't use.
   typedef impl::A A1; // 2. Nor this. So don't use. Both compile, but
                       // then there's an address error at runtime.

   /*const*/ impl::A a; // 3. I speculate there is a bug in nvcc that
                        // makes copy ctor fail when this is const,
                        // leaving the vpointer point to the host. So
                        // don't make const.
   // const impl::A a;  // Memory error.
   // const A a;        // Memory error.
   // A a;              // Memory error.
   Wrapper(int a,int b) : a(a,b) {}
};

struct Kernel {
   Kernel ()
      : v_("v", 1000, 30), w(1,2)
   {}
   
   KOKKOS_INLINE_FUNCTION void operator() (const int i) const {
      int idx = w.a.base; // w.a.a would be fine, but w.a.base needs
                          // the vpointer. For w.a.base, the bug in 3
                          // was making the deref to .base invalid.
      v_(i,idx) = i;
   }

private:
   Kokkos::View<double**> v_;
   const Wrapper w;
};

int main () {
   Kokkos::initialize();
   Kernel k;
   Kokkos::parallel_for(1000, k);
   Kokkos::finalize();
}
```

**Comment by crtrott** [comment]
I believe that most of the issues are due to copy constructor calls which are not allowed since they call a virtual function if you don't explicitly invoke the base copy constructor. But We can investigate further. Generally if you use inheritance with any kind of virtual functions you must construct the object on the device in order to use the virtual function on the device (i.e. so that the function pointer is filled in correctly, and doesn't point to the a host function). But I guess you knew that.

**Comment by ambrad** [comment]
@crtrott, just for clarity, I want to point out that this example has nothing (at least on the surface) to do with virtual functions. Rather, the example is examining "virtual inheritance", i.e., as in for the diamond problem in multiple inheritance. The example uses only data members. However, it's true that a vpointer to the data in the virtually inherited class is very likely the problem. The question is whether it really should be a problem. A vpointer to data I think ought to be an offset (relative), not like a pointer to a function.

**Comment by hcedwar** [comment]
[http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#virtual-base-classes](From the CUDA programming guide)

E.2.10.4. Virtual Base Classes

It is not allowed to pass as an argument to a __global__ function an object of a class derived from virtual base classes.

**Comment by hcedwar** [comment]
When the closure is small Kokkos passes the closure by value to the global dispatch function.

**Comment by ambrad** [comment]
Great, thanks.
