### ISSUE TITLE
`Kokkos::complex` should have `constexpr` constructor as well

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#6281]
If I'm not mistaken, according to https://en.cppreference.com/w/cpp/numeric/complex/complex there are several constructors of `std::complex` that are declared `constexpr` already in the `c++14` standard.

Looking at
https://github.com/kokkos/kokkos/blob/7e6871f6a163d3ffff362ff4c64c3d4616d55f62/core/src/Kokkos_Complex.hpp#L109
it seems it is not the case for `Kokkos::complex`, and `constexpr` needs to be explicitly added.

Here is a small code to test `constexpr`-ness:
```c++
template<class Lambda, int=(Lambda{}(), 0)>
constexpr bool is_constexpr(Lambda) { return true; }
constexpr bool is_constexpr(...) { return false; }

if constexpr(is_constexpr([]{ std::complex{1.}; }))
        std::cout << "std::complex is constexpr" << std::endl;
    else
        std::cout << "unexpected !" << std::endl;

if constexpr(is_constexpr([]{ Kokkos::complex{1.}; }))
        std::cout << "Kokkos::complex is constexpr" << std::endl;
    else
        std::cout << "unexpected !" << std::endl;
```

This should show (at least for `g++ 11.3.0`):
```text
std::complex is constexpr
unexpected !
```

If you agree on the changes, I can open a PR.

**Comment by dalg24** [comment]
Agree that this is a defect.  The intent is that it can be used as a drop-in replacement for std::complex.

**Comment by JBludau** [comment]
I am for aligning with the std but am I missing something? https://godbolt.org/z/GEKGcz11r

**Comment by romintomasetti** [comment]
> I am for aligning with the std but am I missing something? https://godbolt.org/z/GEKGcz11r

I think the `is_constexpr` trick doesn't work if you don't enable `-std=c++20`. A simpler reproducer that works under `-std=c++17` might be:
```c++
int main(){
    static_assert(std::complex{1.} == std::complex{1.}); // OK
    static_assert(Kokkos::complex{1.}.real() == 1.); // error: non-constant condition for static assertion
}
```
