### ISSUE TITLE
Cuda 12 code compilation error with clang++-15 compiler

### ISSUE THREAD

**Issue by tbhaxor** [kokkos/kokkos#6286]
I am getting following error message, you can try any code with following cmake command

```
cmake -Bbuild -G Ninja  -DCMAKE_CXX_COMPILER=$(which clang++-15)
``` 

```
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/bits/shared_ptr_base.h:196:22: error: expected expression
/opt/cuda/include/crt/host_defines.h:83:33: note: expanded from macro '__noinline__'
        __attribute__((noinline))
                                ^
11 errors generated when compiling for sm_75.
ninja: build stopped: subcommand failed.
```

**Comment by masterleinad** [comment]
Please follow the `Bug report` template. Are you trying to compile `Kokkos` or some downstream code? If the latter, please provide a minimal example.
In any case, please provide the full failing compile line.

**Comment by tbhaxor** [comment]
My bad for not obeying the template pattern. 

It is clang version issue. I am installing clang11.1 now



```clang@10.0.1:11.1.0``` is supported
