### ISSUE TITLE
Create Kokkos Bill of Materials

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#632]
Create Kokkos::print_configuration which will dump all configuration and runtime parameters

**Comment by jjellio** [comment]
YES!  I want to add this type of functionality to Trilinos.  If you have work with Petsc, anytime something goes completely wrong, it prints a stack trace (if you compiled with their debug flag). It also shows the exact line used to ./configure the build. 

I want this information for performance tracking: Which TPLs (blas/lapack) were used and which version. The compiler used and its version. I think it will be extremely value when providing user support as well. (not related to Kokkos, just an FYI)

You may want to consider how Petsc has used this type of functionality in conjunction with bad things happening. E.g., if you reach a bad state, this info becomes part of the exception handler so the user has something useful to bring to a github issue.

**Comment by mhoemmen** [comment]
It's not hard for us to tie this into TEUCHOS_TEST_EXCEPTION* macros, or make it an MPI_Finalize or atexit hook.

**Comment by dsunder** [comment]
Output from Kokkos::print_configuration( out, false )

Compiler:
  KOKKOS_COMPILER_APPLECC: 6000
  KOKKOS_COMPILER_CLANG: 400
Architecture:
  KOKKOS_ENABLE_ISA_KNC: no
  KOKKOS_ENABLE_ISA_POWERPCLE: no
  KOKKOS_ENABLE_ISA_X86_64: no
Devices:
  KOKKOS_ENABLE_CUDA: no
  KOKKOS_ENABLE_OPENMP: yes
  KOKKOS_ENABLE_PTHREAD: no
  KOKKOS_ENABLE_STDTHREAD: no
  KOKKOS_ENABLE_WINTHREAD: no
  KOKKOS_ENABLE_QTHREADS: no
  KOKKOS_ENABLE_SERIAL: no
Default Device:
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_CUDA: no
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_OPENMP: yes
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_THREADS: no
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_QTHREADS: no
  KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_SERIAL: no
Atomics:
  KOKKOS_ENABLE_CUDA_ATOMICS: no
  KOKKOS_ENABLE_GNU_ATOMICS: yes
  KOKKOS_ENABLE_INTEL_ATOMICS: no
  KOKKOS_ENABLE_OPENMP_ATOMICS: no
  KOKKOS_ENABLE_WINDOWS_ATOMICS: no
Vectorization:
  KOKKOS_ENABLE_PRAGMA_IVDEP: no
  KOKKOS_ENABLE_PRAGMA_LOOPCOUNT: no
  KOKKOS_ENABLE_PRAGMA_SIMD: no
  KOKKOS_ENABLE_PRAGMA_UNROLL: no
  KOKKOS_ENABLE_PRAGMA_VECTOR: no
Memory:
  KOKKOS_ENABLE_HBWSPACE: no
  KOKKOS_ENABLE_INTEL_MM_ALLOC: no
  KOKKOS_ENABLE_POSIX_MEMALIGN: no
Options:
  KOKKOS_ENABLE_ASM: no
  KOKKOS_ENABLE_CXX1Z: no
  KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK: no
  KOKKOS_ENABLE_HWLOC: no
  KOKKOS_ENABLE_LIBRT: no
  KOKKOS_ENABLE_MPI: no
  KOKKOS_ENABLE_PROFILING: yes

Runtime Configuration:
Kokkos::OpenMP KOKKOS_ENABLE_OPENMP thread_pool_topology[ 1 x 2 x 1 ]
  thread omp_rank[0] kokkos_rank[0] hwloc_coord[0.0]
  thread omp_rank[1] kokkos_rank[1] hwloc_coord[0.0]
