### ISSUE TITLE
Add RISC-V support to the build system

### ISSUE THREAD

**Issue by diehlpk** [kokkos/kokkos#6323]
I played around testing Kokkos on RISC-V. Kokkos built on RISC-V using gcc out of the box. However, CMake needed some changes for the architecture to add correct compiler flags. 

Is there interest to support RISC-V? 

If so I am willing to prepare a pull request.

I assume I would need to add a new architecture flag for the RISC-V CPU or board.

**Comment by diehlpk** [comment]
Kokkos scales well on RISC V, I will post the preprint of our SC workshop paper soon.

**Comment by lucbv** [comment]
@diehlpk this sounds like a good idea but in general this has not happened because there is no hardware beyond development boards are at least there was not until recently?
I would be happy to have a discussion on the topic if you want.
I am guessing that you are sending your paper to the RISC-V for HPC workshop?

**Comment by diehlpk** [comment]
Yes, your guess it correct.

**Comment by ajpowelsnl** [comment]
> Kokkos scales well on RISC V, I will post the preprint of our SC workshop paper soon.

Many thanks for the suggestion, @diehlpk.  It would be great if you could develop a PR for this feature.

**Comment by diehlpk** [comment]
There might be soon a desktop machine available:

https://www.crowdsupply.com/milkv/milk-v-pioneer

However, our idea was to evaluate HPX and Kokkos on this new architecture.

**Comment by diehlpk** [comment]
@lucbv The paper got accepted, and here is the [preprint](https://arxiv.org/abs/2309.06530)

**Comment by diehlpk** [comment]
@ajpowelsnl I finished traveling and will now have time to work on the pull request.

**Comment by diehlpk** [comment]
It took a while but here is the promised [pull request ](https://github.com/kokkos/kokkos/pull/6771).

**Comment by diehlpk** [comment]
This can be closed since the pull request is merged.
