### ISSUE TITLE
Using an installed Kokkos in a target application using CMake

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#633]
Hello,

For people that already have an application using CMake, and want to use an installed Kokkos, I would like to suggest that Kokkos "make install" should install both Makefile.kokkos and a file kokkos.cmake
containing roughly the same information, but kokkos.cmake could then easily be included in the top-level CMakeLists.txt of the application.

A simple and small modification in core/src/Makefile is required
just add target "build-cmake-kokkos" which will output the required kokkos.cmake

Then on a system with several installed versions of kokkos, if using modulefiles and if modulefiles define env variable KOKKOS_PATH, one only need to put in the target application CMakeLists.txt:

  set(CMAKE_MODULE_PATH "$ENV{KOKKOS_PATH}" ${CMAKE_MODULE_PATH})
  include(kokkos)

I can provide a pull request if you think it can be useful (at least I do).

**Comment by crtrott** [comment]
Sure go ahead with a pull request.
