### ISSUE TITLE
Nightly GCC13 fails in TestStdAlgorithmsTeamAdjacentFind

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#6336]
@fnrizzi Can you take a look. The error message is [here](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos-nightly/detail/Kokkos-nightly/446/pipeline)

**Comment by fnrizzi** [comment]
oh another one!? yes looking now

**Comment by masterleinad** [comment]
Looks like you would it's sufficient to just copy the class members to local variables.
