### ISSUE TITLE
Cray and PGI: Kokkos_Parallel_Reduce

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#634]
Fix for issue reported by Cray (reported by @nmhamster)

In Kokkos_Parallel_Reduce.hpp
in `struct ParallelReduceReturnValue`
change:
  `typedef typename return_type::value_type value_type_array[];`
to:
  `typedef typename return_type::value_type *value_type_array;`

Need to assess impact of how this is used downstream to insure proper behavior.

**Comment by crtrott** [comment]
After looking into this we believe our usage is standard conform since the typedef is only used for function arguments. That said we are also reasonably confident that replacing it with a const pointer type should also work.
