### ISSUE TITLE
Proper swapping of views' data

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#6345]
To avoid often deep copies, while retaining global code readability the following idea is frequent in HPC:
1. read `A` and write updated results in `B`
2. swap `A` and `B` pointers, so algorithm can continue to work on `A` (while `B` is again treated as temp storage for something next)

The following options do not work in complex threading environments:
- `std::swap`
- `auto tmp = this->A; this->A = this->B; this->B = tmp;`
- swapping pointers using `assign_data`

What would be the proper way of swapping pointers to data of Views of same properties. Something like `swap_data`?

**Comment by masterleinad** [comment]
Can you clarify what is not working properly? Intuitively, I would expect `std::swap` and the manual assignments to work as expected (but no fences are invoked). `assign_data` always results in an unmanaged `View` which is likely not desired in this scenario.
Is the problem that copies increase the reference count so the copied from `View` continues to point to the same allocation when the copied `View` is swapped?

**Comment by ajpowelsnl** [comment]
@j8asic - are you still unsure how to proceed on this issue?  If so, we'll reopen.

**Comment by dalg24** [comment]
> To avoid often deep copies, while retaining global code readability the following idea is frequent in HPC:
> 
> 1. read `A` and write updated results in `B`
> 2. swap `A` and `B` pointers, so algorithm can continue to work on `A` (while `B` is again treated as temp storage for something next)

`std::swap` works.  See https://godbolt.org/z/bsan8KdEW
Feel free to reopen if you are still having issues.

**Comment by j8asic** [comment]
Thank you all for testing. The behaviour from my side is weird indeed, and cannot trace where does it come from. I will remember to reopen if I find the source.
