### ISSUE TITLE
Cuda team parallelism and scratch space cleanup

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#637]
In support of issues #477 and #577

Cuda back-end use of scratch and shared memory has become a patchwork that must be cleaned up.  In addition, to allow multiple teams to occupy a single thread block the thread block's shared memory must be partitioned among teams. The advent of Cuda shuffle capability since Kokkos' original design should also be considered.

Considerations for the use of Cuda shared memory:

- global reduce and scan inter-thread and inter-block scratch memory
- global reduce with static or dynamic reduction values
- team reduce and scan inter-thread scratch memory
- team shared scratch memory
- team thread private dynamically sized scratch memory
- non-failing fall-back to scratch global memory when requested shared scratch memory exceeds capacity of Cuda `__shared__` memory
- partitioning shared memory among multiple teams residing within a single block
- use of shared memory within separately compiled, relocatable Cuda functions such as tasks

**Comment by crtrott** [comment]
Wow February Milestone. This seems ambitious ....

**Comment by hcedwar** [comment]
Required to integrate task-teams with task-policy-teams, enhancement #320, without generating a nearly redundant back-end implementation.

**Comment by crtrott** [comment]
This thing let to a significant performance degradation in the Cuda ThreadVector parallel_reduce. I see an almost 2x hit on miniFE Matrix matvec due to commit cc9e146dff175805e2204d4dff9617882470b8b3

**Comment by hcedwar** [comment]
To be part of a comprehensive clean-up-and-migrate Cuda back-end to CUDA 9 effort.
