### ISSUE TITLE
Update `clang-format` version

### ISSUE THREAD

**Issue by cz4rs** [kokkos/kokkos#6381]
Follow-up to #6376, see https://github.com/kokkos/kokkos/issues/6376#issuecomment-1690544398.

It seems that he have agreed on using `constexpr West` in Kokkos. Update `clang-format` version used in CI and adjust `.clang-format` accordingly.

Relevant option: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#qualifierorder.

**Comment by cz4rs** [comment]
Note: we need to pick `clang-format` version, we are currently using `8.0.0`. `QualifierOrder` was introduced in 14.

**Comment by masterleinad** [comment]
Switching to clang-format 16 would change around 1000 lines. That's really not too bad in my opinion.
