### ISSUE TITLE
dynamic scheduling

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#639]
I'm using the dynamic scheduler and I want to know the best way to order my work.  I have about 400 units of work, each unit of work is a NxN matrix inversion (200-1000) elements.  If I order staticly I get a lot of idle processors.  If I order dynamically I also get a lot of idle processors.  It is even worse.  My thought was if I order all my big inversions up front I can back fill with small inversions. 

Is there any good ordering of work for scheduling?  I can go to atomics and a sorted list.\

Thoughts?

**Comment by crtrott** [comment]
Hm this is weird, dynamic scheduling should take care of this in a reasonable way. Which architecture are you on and how many threads are you running?

**Comment by hcedwar** [comment]
If the dynamic scheduler happens to start the biggest payload last then you'll get the idle threads.  Currently no (good) way to prioritize particular league ranks.  The sorted list with atomics is the simplest prioritizing mechanism.

**Comment by bathmatt** [comment]
openMP with 32 threads.  I'm trying the sorted list with atomics.  I think the overhead for that should be small since we are talking about inverting a couple 100x100 complex matrix.

**Comment by bathmatt** [comment]
That took it from 130s to 96 seconds, still a lot of wasted time according to v-tune.  I need to get a bit more hybrid parallelism which will be needed for the GPU.

**Comment by crtrott** [comment]
Can you produce a distribution of computational complexity? Maybe you simply can't fully load balance? 
Another approach might be to do a static ordering with worksets consisting of multiple inversions, but you build your worksets in a way that they are load balanced?

**Comment by bathmatt** [comment]
Got it down to 88s  Here is the issue.  We have work which is on the order 1000^3, and some that is 200^3, therefore 125x difference.  400 work items and 32 threads, therefore, each thread does roughly 15 things.  Therefore, if one is really slow near the end it can stall all the processes.  Right now all are finishing at the same time according to vtune.  I sort by work and use atomic so all the small ones are at the end and all backfill.

**Comment by bathmatt** [comment]
Also, Christian, I can get you the work load distribution if you would like.  it is easy to just print out.

**Comment by nmhamster** [comment]
@battmatt, have you also tried using a heuristic to balance the work and then issue with a static distribution (i.e. make a list of the work for everyone and then static hand it out?). If the heuristic is good (for balancing work) this should give you the fastest performance on the CPU platforms and Xeon Phi, if you can't get a good approximation that the dynamic is next best choice.

**Comment by bathmatt** [comment]
I can do that, but it seems hard :).  I have a good est of the work load (some variable to the 3rd power).  but how do I group things together cleanly to balance everything out?  Like I said, I use a fixed number of threads (all of them) and start from the slowest to the fastest blocks using atomic and an index counter assuming that the fast ones will all loadbal pretty good and the slow ones will be finished.  Like I said there is a factor of 100 difference between the slow and the fast one in compute time.
