### ISSUE TITLE
SYCL sycl.mathspecialfunc_cbesselj1y1 subtest failure with intel/2023.1.0 on Intel Ponte Vecchio

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6396]
**Describe the bug**
The `sycl.mathspecialfunc_cbesselj1y1` subtest failed for me with an initial test on a newer system (tested with kokkos@7e299b4e25c42528e105379c3aa9a318056545ba) on Intel Ponte Vecchio with the following output:

```
[ RUN      ] sycl.mathspecialfunc_cbesselj1y1
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:914: Failure
Expected equality of these values:
  h_ref_cby1(0)
    Which is: (-inf,0)
  h_cby1(0)
    Which is: (-inf,1233.15)
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:917: Failure
Expected: (Kokkos::abs(h_cby1(i) - h_ref_cby1(i))) <= (Kokkos::abs(h_ref_cby1(i)) * 1e-13), actual: 424.078 vs 1.47619e-13
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:917: Failure
Expected: (Kokkos::abs(h_cby1(i) - h_ref_cby1(i))) <= (Kokkos::abs(h_ref_cby1(i)) * 1e-13), actual: 424.078 vs 1.47619e-13
/home/ndellin/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:917: Failure
....
```

**Please also include the following items to support reproducing the bug**
**Reproducer**:
* Note that I disabled onedpl (the spack install on the system was a bit older and triggered compilation errors)
```bash
module load cmake intel-oneapi-compilers/2023.1.0

$KOKKOS_PATH/generate_makefile.bash --with-sycl --arch=INTEL_PVC --compiler=/projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/bin-llvm/clang++ --cxxflags="-fp-model=precise" --cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF

```

I'm testing on a newer system and I am relatively inexperienced with the Intel GPUs and SYCL backend, please let me know if this is self-inflicted user-configure error

Edit: updated reproducer instructions to current flag usage (-fp-model=precise)

**Comment by ndellingwood** [comment]
@dalg24 this was a fresh test on the new system without prior builds+testing for comparison, I listed #6369 as a reference SHA for reproducing and did not mean to imply it was a breaking commit

**Comment by dalg24** [comment]
Oh I see.  First thing that comes to mind is use precise floating point model.

**Comment by ndellingwood** [comment]
I tested a clean build using `-fp-model=precise` and still ran into the same failure

**Comment by ndellingwood** [comment]
A separate note, compilation time is pretty long, with `Kokkos_CoreUnitTest_SYCL1A` taking a pretty substantial amount of time to build (I don't have it itemized away from the remainder of the build).

From `time make -j12`:
```
real 121m17.114s
user 216m9.243s
sys 4m2.495s
```

**Comment by Rombur** [comment]
ROCm 5.5 and 5.6 throw a similar error in the Bessel function tests but not for the same functions. I wonder if the issue is in upstream LLVM. Which version of LLVM is Intel/2023.1.0 based on? ROCm 5.5 and 5.6 are based on LLVM 16.

**Comment by ndellingwood** [comment]
@Rombur thanks for the tip. I think intel/2023.1.0 is also based on llvm/16, based on looking in the lib/clang directory:
```
[ndellin@blake ~]$ ls /projects/x86-64-icelake-rocky8/compilers/intel-oneapi-compilers/2023.1.0/gcc/8.5.0/base/6g2jkiv/compiler/2023.1.0/linux/lib/clang/
16
```

**Comment by ndellingwood** [comment]
Also seeing this sub-test fail the past couple nights, though there was no change to Kokkos corresponding the first occurrence

```
03:25:41  5/45 Test  #5: Kokkos_CoreUnitTest_SYCL1B ....................***Failed  Error regular expression found in output. Regex=[  FAILED  ] 12.37 sec
...
03:25:41 [ RUN      ] sycl.mdrange_parallel_reduce_primitive_types
03:25:41 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestMDRangeReduce.hpp:44: Failure
03:25:41 Expected equality of these values:
03:25:41   land_MD
03:25:41     Which is: 0
03:25:41   1
03:25:41 [  FAILED  ] sycl.mdrange_parallel_reduce_primitive_types (7954 ms)

```

**Comment by ndellingwood** [comment]
The bessel test is still failing after merge of #6434:
```
03:33:13 [ RUN      ] sycl.mathspecialfunc_cbesselj1y1
03:33:13 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestMathematicalSpecialFunctions.hpp:914: Failure
03:33:13 Expected equality of these values:
03:33:13   h_ref_cby1(0)
03:33:13     Which is: (-inf,0)
03:33:13   h_cby1(0)
03:33:13     Which is: (-inf,1233.15)
```

Some refinement apparently needed to ensure the tests are skipped?

**Comment by masterleinad** [comment]
That's passing for me on the testbeds using the latest `develop` and `-fp-model=precise`.

**Comment by masterleinad** [comment]
@ndellingwood Please use `-fp-model=precise`.

**Comment by ndellingwood** [comment]
@masterleinad the nightly job is using that flag (the initial reproducer instructions are out of date, I'll update)

**Comment by masterleinad** [comment]
> @masterleinad the nightly job is using that flag (the initial reproducer instructions are out of date, I'll update)

OK. Since the rest of the checks are passing for you, let's just also disable this check even though it works on the testbeds.
