### ISSUE TITLE
question of first touch and performance

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#640]
I am building a dense matrix solver with a custom preconditioner  Now, with this preconditioner I formulate the foll dense matrix.  I have two routines.

preconditoin and apply.  Both do exactly the same instructions.

```  void apply(Vector x, Vector ax) {
    const int n=p.n;
    Kokkos::deep_copy(ax, 0.0);
    Kokkos::parallel_for(n, KOKKOS_LAMBDA(const int i) {
      for (int j=0; j<n; ++j) {
        ax(i) += m(i,j)*x(j);
      }
    });
  }```

Now, in both cases the data types are
```
  typedef Kokkos::View<Cmplx**> Matrix;
  typedef Kokkos::View<Cmplx*> Vector;
```

I call 400 of each of these and the runtimes are roughly 70% longer for the precondition then the apply.  Any idea on why this could be?  I'm assuming it's first touch?  Both are created the same way but the preconditoner is created second.  They take about 12G each matrix.  

Any ideas would be useful.  This is on my desktop with 2x16core sockets with HT turned on but only --kokkos-threads=32
Thanks
Matt

**Comment by crtrott** [comment]
does't make much sense to me, sorry. So the preconditioning is the exact same operation?

**Comment by bathmatt** [comment]
@crtrott yes, the only difference is the matrix and vectors which are created the same.

**Comment by mhoemmen** [comment]
First touch should use the parallel dimension for allocation, which should be rows of your dense preconditioner...
