### ISSUE TITLE
Tags for md_parallel_for

### ISSUE THREAD

**Issue by ipdemes** [kokkos/kokkos#643]
Dear Kokkos developers, would it be possible to add tags to the MD_Range policy? 
We need this for Albany.

**Comment by ndellingwood** [comment]
Hi @ipdemes ,
If this is urgent please pull from the link pasted at the bottom to the mdrange-extend-cuda branch from my Kokkos fork, it has a fix for tags with md_parallel for and I just updated it with the current (10 am 02/16/2017) develop branch of Kokkos. 

I will have some changes related to the MDRangePolicy pushed into Kokkos before the end of February. As a heads up, the feature is still in the experimental namespace and depending on performance results some of the upcoming changes may break the existing MDRangePolicy API. I will keep you informed and provide examples to help document the changes in this case. 


[https://github.com/ndellingwood/kokkos/tree/mdrange-extend-cuda](https://github.com/ndellingwood/kokkos/tree/mdrange-extend-cuda)

**Comment by ipdemes** [comment]
@ndellingwood , thank you for the info. We will use your branch then!

**Comment by ipdemes** [comment]
@ndellingwood : could you, please, point me to the example of using tags with MD_Range policy?

**Comment by ipdemes** [comment]
I am trying to do something like next, but keep getting an error (error file is attached):


struct Hydrostatic_Velocity_Tag{};
  struct Hydrostatic_Velocity_PRESCRIBED_1_1_Tag{};
  struct Hydrostatic_Velocity_PRESCRIBED_1_2_Tag{};

 ```
 using Hydrostatic_Velocity_Policy =
        Kokkos::Experimental::MDRangePolicy<
        Kokkos::Experimental::Rank<3, Kokkos::Experimental::Iterate::Left,
        Kokkos::Experimental::Iterate::Left >, Kokkos::IndexType<int> ,
        Hydrostatic_Velocity_Tag >;

 using Hydrostatic_Velocity_PRESCRIBED_1_1_Policy =
        Kokkos::Experimental::MDRangePolicy<
        Kokkos::Experimental::Rank<2, Kokkos::Experimental::Iterate::Left,
        Kokkos::Experimental::Iterate::Left >, Kokkos::IndexType<int>,
        Hydrostatic_Velocity_PRESCRIBED_1_1_Tag >;

  using Hydrostatic_Velocity_PRESCRIBED_1_2_Policy =
        Kokkos::Experimental::MDRangePolicy<
        Kokkos::Experimental::Rank<2, Kokkos::Experimental::Iterate::Left,
        Kokkos::Experimental::Iterate::Left >, Kokkos::IndexType<int>,
        Hydrostatic_Velocity_PRESCRIBED_1_2_Tag >;

  KOKKOS_INLINE_FUNCTION
  void operator() (const Hydrostatic_Velocity_Tag& tag, const int cell, const int node, const int level) const;

  KOKKOS_INLINE_FUNCTION
  void operator() (const Hydrostatic_Velocity_PRESCRIBED_1_1_Tag& tag, const int cell, const int node) const;

  KOKKOS_INLINE_FUNCTION
  void operator() (const Hydrostatic_Velocity_PRESCRIBED_1_2_Tag& tag, const int cell, const int node) const;

```

```
// Kokkos kernels
#ifdef ALBANY_KOKKOS_UNDER_DEVELOPMENT
template<typename EvalT, typename Traits>
KOKKOS_INLINE_FUNCTION
void Hydrostatic_Velocity<EvalT, Traits>::
operator() (const Hydrostatic_Velocity_Tag& tag, const int cell, const int node, const int level) const{
      for (int dim=0; dim < numDims; ++dim)
        Velocity(cell,node,level,dim) = Velx(cell,node,level,dim);
}

template<typename EvalT, typename Traits>
KOKKOS_INLINE_FUNCTION
void Hydrostatic_Velocity<EvalT, Traits>::
operator() (const Hydrostatic_Velocity_PRESCRIBED_1_1_Tag& tag, const int cell, const int node) const{
    const MeshScalarT lambda = sphere_coord(cell, node, 0);
    const MeshScalarT theta = sphere_coord(cell, node, 1);
    ScalarT lambdap = lambda - 2.0*PI*time/tau;

    ScalarT Ua = k*sin(lambdap)*sin(lambdap)*sin(2.0*theta)*cos(PI*time/tau)
               + (2.0*PI*earthRadius/tau)*cos(theta);

    ScalarT Va = k*sin(2.0*lambdap)*cos(theta)*cos(PI*time/tau);

    for (int level=0; level < numLevels; ++level) {
      ScalarT B = this->B(level);
      ScalarT p = pressure(cell,node,level);

      ScalarT taper = - exp( (p    - p0)/(B*ptop) )
                      + exp( (ptop - p )/(B*ptop) );

      ScalarT Ud = (omega0*earthRadius)/(B*ptop)
                   *cos(lambdap)*cos(theta)*cos(theta)*cos(2.0*PI*time/tau)*taper;

      Velocity(cell,node,level,0) = Ua + Ud;
      Velocity(cell,node,level,1) = Va;
    }
}

template<typename EvalT, typename Traits>
KOKKOS_INLINE_FUNCTION
void Hydrostatic_Velocity<EvalT, Traits>::
operator() (const Hydrostatic_Velocity_PRESCRIBED_1_2_Tag& tag, const int cell,
const int node) const{
  //FIXME: Pete, Tom - please fill in
    const MeshScalarT lambda = sphere_coord(cell, node, 0);
    const MeshScalarT theta = sphere_coord(cell, node, 1);
    for (int level=0; level < numLevels; ++level) {
      for (int dim=0; dim < numDims; ++dim) {
        Velocity(cell,node,level,dim) = 0.0; //FIXME  
      }
    }
}

```

```
switch (adv_type) {
    case UNKNOWN: //velocity is an unknown that we solve for (not prescribed)
    {
        Hydrostatic_Velocity_Policy range({0,0,0}, {(int)workset.numCells,
            (int)numNodes,(int)numLevels}, {256,0,0} );
        Kokkos::Experimental::md_parallel_for(range,*this);
        cudaCheckError();
      break;
    }

    case PRESCRIBED_1_1: //velocity is prescribed to that of 1-1 test
    {
       Hydrostatic_Velocity_PRESCRIBED_1_1_Policy range({0,0},
         {(int)workset.numCells, (int)numNodes}, {256,0} );
       Kokkos::Experimental::md_parallel_for(range,*this);
       cudaCheckError();
      break;
    }

    case PRESCRIBED_1_2: //velocity is prescribed to that of 1-2 test
    {
       Hydrostatic_Velocity_PRESCRIBED_1_2_Policy range({0,0},
         {(int)workset.numCells, (int)numNodes}, {256,0} );
       Kokkos::Experimental::md_parallel_for(range,*this);
       cudaCheckError();
      break;
    }
  }

```
[err.txt](https://github.com/kokkos/kokkos/files/788191/err.txt)

**Comment by ndellingwood** [comment]
Hi @ipdemes 
From the branch on my fork linked above, if you look in kokkos/core/unit_test/TestMDRange.hpp some of the unit tests use tags to test different functors with tagged operators. 
For example, starting at line 191 the first test in test_for2 (scoped by braces { } ) typedef's an md range policy with an InitTag (line 195) in the template arguments. This corresponds to the tagged operator in TestMDRange_2D (defined at line 80). Does this illustrate what you need for your use case?

**Comment by ipdemes** [comment]
@ndellingwood 
So your operator() in TestMDRange_2D functor doesn't get  tag as an argument, right? I guess this is an issue for us:
we have 1 functor with 3 overloaded by tag operator() in Albany. Please see not-MDRange implementation here: https://github.com/gahansen/Albany/blob/master/src/Aeras/evaluators/Aeras_VorticityLevels.hpp (line 75-85)

**Comment by ndellingwood** [comment]
@ipdemes 
Looking over your code snippets the syntax looks like it should be right, but from your err.txt it looks like this was compiled with the existing MDRangePolicy from the develop branch. Tags are not fixed in that branch, please try recompiling using my fork and the following branch hopefully this works. 
[](https://github.com/ndellingwood/kokkos/tree/mdrange-extend-cuda)

**Comment by ndellingwood** [comment]
Sorry, link did not send, trying again... 


[https://github.com/ndellingwood/kokkos/tree/mdrange-extend-cuda](https://github.com/ndellingwood/kokkos/tree/mdrange-extend-cuda)

**Comment by ndellingwood** [comment]
As a note for reference, the indicator from the error message that this was from develop branch and not my fork was this: 
`error: no match for call to ‘(const Kokkos::Experimental::Impl::MDForFunctor`

In my fork some of the code has been restructured/refactored and `MDForFunctor` no longer exists in my fork + branch.

**Comment by ipdemes** [comment]
@ndellingwood : oops, it seems like you are right: I have cloned from your repo, but forgot to checkout to the right branch. I am rebuilding Trilinos+Albany right now and let you know if this fixed an error.
Thanks!

**Comment by ndellingwood** [comment]
@ipdemes ah, I've forgetten that after cloning from other forks too! Let me know if the new branch fixes things.

**Comment by ipdemes** [comment]
P.S Adding dummy operator() fixed compile-time error, but this is not what I expect:

KOKKOS_INLINE_FUNCTION
void operator() (const int cell, const int node, const int level) const{}

**Comment by ndellingwood** [comment]
@ipdemes Thanks for the update. To clarify, when you say adding the the dummy operator fixed the compile time error but is not what you expected, do you did not expect to have to define the dummy operator, or that it gave results/behavior that you did not expect?

**Comment by ipdemes** [comment]
@ndellingwood adding this operator gave behavior that I didn't expect.
This is what I would expect from Kokkos, please correct me if I am wrong.

assume I have functor like:

```
template <typename ExecSpace >
struct TestMDRange_3D {

  using DataType     = int ;
  using ViewType     = typename Kokkos::View< DataType** ,  ExecSpace > ;
  using HostViewType = typename ViewType::HostMirror ;

  ViewType input_view ;

  TestMDRange_3D( const DataType N0, const DataType N1 ) : input_view("input_view", N0, N1) {}

  KOKKOS_INLINE_FUNCTION
  void operator()( const int i , const int j  ) const 
  {
    lsum += input_view(i,j)*2;
  }
  // tagged operators
  struct InitTag {};
  KOKKOS_INLINE_FUNCTION
  void operator()( const InitTag & , const int i , const int j, double &lsum ) const
  {
    input_view(i,j) = 1;
  }
};
```

and I would like to call the tagged operator, I would do something like next:

   ```
typedef typename Kokkos::Experimental::MDRangePolicy< ExecSpace, Rank<3>, Kokkos::IndexType<int> , InitTag > range_type;
      typedef typename range_type::tile_type tile_type;
      typedef typename range_type::point_type point_type;

      range_type range( point_type{{0,0,0}}, point_type{{N0,N1,10}}, tile_type{{3,3,0}} );
      TestMDRange_3D functor(N0,N1);

      md_parallel_for( range, functor );
```

In case of Albany this would produce a compile-time error like above because compiler would be looking for  and operator  void operator()(  const int i , const int j, double &lsum ) const inside of the functor (3 integers without tag)

**Comment by ndellingwood** [comment]
@ipdemes The general structure of the code above looks fine, though there is some inconsistency with the rank and number of arguments used in the different pasted snippets (e.g. rank 2 view and operator args in functor definition, but 3 arguments to begin/end/tile dims in range) - if that was intentional (not due to copy/paste from different pieces of code) is the behavior desired to pass in additional arguments to the begin/end/tile dim arguments of the md range policy (ignoring them if they exceed the rank)? 

If that is not the case, perhaps you can post .txt of the recent compiler error output (without dummy operator)? I experimented in one of the unit tests by adding different number of dim arguments, +/- tag, +/- redux value, but did not run into compiler issues. 

And from looking at the original code you posted, the using statement for `Hydrostatic_Velocity_Policy`has the tag properly included as a template parameter, so it is not clear to me why the compiler would be trying to call the operator with 3 int args rather than the tagged operator with 3 int args
```
using Hydrostatic_Velocity_Policy =
       Kokkos::Experimental::MDRangePolicy<
       Kokkos::Experimental::Rank<3, Kokkos::Experimental::Iterate::Left,
       Kokkos::Experimental::Iterate::Left >, Kokkos::IndexType<int> ,
       Hydrostatic_Velocity_Tag >;
```

I agree the compiler error is not expected (i.e. the un-tagged operator is looked for instead of the tagged operator from the code posted), looking more closely at the error output (without dummy operator) may help.

**Comment by ndellingwood** [comment]
@ipdemes 
Your code looks good; I made a mistake with tags when I refactored with some new tile macros and my unit test setup masked this. For now I have disabled the new macros on my fork/branch and will work on a fix (and better unit tests that properly check this), please pull from my fork and hopefully it will work properly for you. 
Thanks for testing and reporting this!

**Comment by ipdemes** [comment]
@ndellingwood 
Sorry for the late reply. I am working on Albany at my personal time so it took a little bit longer to check your fix out. Everything works with no issues now. Thanks a lot for the fix!

**Comment by ndellingwood** [comment]
@ipdemes Thanks for the update! Thanks again for pointing out the bug. Also, if you gather performance results I'd be interested you get a chance to share them and any feedback for improvements.

**Comment by ipdemes** [comment]
Thank you, @ndellingwood , we'll keep you updated.
