### ISSUE TITLE
Concurrently sort many (batched) arrays using Kokkos

### ISSUE THREAD

**Issue by tawiesn** [kokkos/kokkos#645]
I need to sort a large number of small arrays concurrently. For CUDA i can use
thrust::stable_sort_by_key as, e.g., described in the second answer [here](http://stackoverflow.com/questions/8298728/concurrently-sorting-many-arrays-with-cuda-thrust)
How can i do that with Kokkos? Something like thrust::stable_sort_by_key would be useful.

**Comment by ibaned** [comment]
@tawiesn a while back I found that Kokkos didn't quite have a general enough sorting interface and put together something of my own that either calls Thrust or an OpenMP parallel stable sort written by folks at Intel. What this thing does is to accept an array of keys and return a permutation array that can then be used to sort the many small arrays. There is a bit of complication because I allow keys to be composed of multiple entries.

https://github.com/ibaned/omega_h/blob/master/src/sort.cpp
https://github.com/ibaned/omega_h/tree/master/src/intel_sort

Anyway, maybe you can either adapt this code for your purposes or we can work to get a more production-quality version of it included in Kokkos.

**Comment by crtrott** [comment]
Yeah we do not have a sorting thing for sorting multiple small arrays concurrently. 
Though its something I would want. Maybe we can work on implementing something.

**Comment by tawiesn** [comment]
Thanks @ibaned for pointing me to these algorithms. The sorting part is only a minor step in my overall algorithm. So, i will first make sure that everything else is working. Maybe we can then coordinate our efforts to have some general sorting interface in Kokkos algorithms. I'll keep you informed about the progress.

**Comment by mhoemmen** [comment]
@tawiesn @ibaned If it helps, Tpetra has a (currently not parallel) `sort2` function, that sorts one array and applies the resulting permutation to an array of the same length.

Tpetra could use a thread-parallel "sort all the entries in every row of a sparse matrix."  My plan for now was just to do that on the host, with existing non-CUDA-ized functions.

**Comment by tawiesn** [comment]
@mhoemmen Thanks for the hint. I'll take a look at it. Currently i'm using a non-parallel sort version for my kernels in MueLu, too, playing around with the user interface.

**Comment by mhoemmen** [comment]
@tawiesn If you come up with a good interface, let me know :-)

**Comment by gmackey** [comment]
What I've done before is written a class that is templated on the ExecutionSpace.  The default version's constructor calls std::sort().  The specialization for Cuda calls thrust::sort().  You can use the thrust sorting algorithm and non-cuda sorting algorithm of your choice.  Here's code showing what I did to sort the data in a 1D View.

```
#include <algorithm>
#ifdef KOKKOS_HAVE_CUDA
#include <thrust/device_ptr.h>
#include <thrust/sort.h>
#endif

template <class ExecutionSpace>
struct SortView {
  template <typename ViewType>
  SortView(const ViewType& v, int begin, int end)
  {
    std::sort(v.data() + begin, v.data() + end);
  }
};

#ifdef KOKKOS_HAVE_CUDA
template<>
struct SortView<Kokkos::Cuda> {
  template <typename ViewType>
  SortView(const ViewType& v, int begin, int end)
  {
    typedef typename ViewType::value_type value_type;

    thrust::sort(thrust::device_ptr<value_type>(v.data() + begin),
                 thrust::device_ptr<value_type>(v.data() + end));
  }
};
```

**Comment by gmackey** [comment]
Oh, I forgot to mention the obvious.  You can now call this in a parallel loop like this.  Umm, I guess this would really sorting a view of views instead of just sorting a view.

```
Kokkos::parallel_for(num_views, KOKKOS_LAMBDA (const unsigned long i) {
  SortView<ExecutionSpace>(my_view[i], start[i], stop[i]);
});
```

**Comment by mhoemmen** [comment]
@gmackey Thanks!  Just curious -- how does thrust::sort work when called on device?  Does it work like a thread team collective, is it sequential, or does it launch a new kernel dynamically?

**Comment by tawiesn** [comment]
@gmackey: Thanks for the hint. That would be exactly what i want to do and i've already tried it and failed.
The thrust code is not compiling on my machine for some reason:

> /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/include/thrust/detail/type_traits/minimum_type.h(59): error: name followed by "::" must be a class or namespace name
> 
> /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/include/thrust/detail/type_traits/minimum_type.h(59): error: type name is not allowed
> 
> /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/include/thrust/detail/type_traits/minimum_type.h(60): error: name followed by "::" must be a class or namespace name
> 
> /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/include/thrust/detail/type_traits/minimum_type.h(60): error: not a class or struct name
> 
> /projects/sems/install/rhel6-x86_64/kokkos/compiler/cuda/7.5.18/include/thrust/detail/type_traits/minimum_type.h(60): error: class or struct definition is missing

These are the modules i've loaded on my machine

>  1) sems-env                                    
>  2) kokkos-env                                   
>  3) sems-cmake/3.5.2                        
>  4) sems-gcc/4.9.3                             
>  5) kokkos-cuda/7.5.18                           
>  6) kokkos-openmpi/1.8.7/cuda                   
>  7) kokkos-nvcc_wrapper/1                       
>  8) sems-python/2.7.9                           
>  9) sems-boost/1.58.0/base                      
>  10) sems-hdf5/1.8.12/parallel

Could you comment on which modules you are using (assuming you also use SEMS)?

Calling std::sort from within a parallel_for does not work on the device (which is not surprising):

> /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/base/include/c++/4.9.3/bits/stl_algo.h(1967): 
> error: calling a __host__ function("std::__introsort_loop<unsigned long *, long, __gnu_cxx::__ops::_Iter_less_iter> ") from a __device__ function("Kokkos::Impl::ParallelFor<MueLu::_NV_ANON_NAMESPACE::Stage1eVectorFunctor<KokkosSparse::CrsMatrix<double, int, Kokkos::Serial, void, unsigned long> , Kokkos::View<unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> , Kokkos::MemoryTraits<(unsigned int)0u>  > , Kokkos::View<unsigned long *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> , Kokkos::MemoryTraits<(unsigned int)0u>  > > , Kokkos::RangePolicy<Kokkos::Cuda > , Kokkos::Cuda> ::operator ()") is not allowed
> 

I probably would work somehow with thrust but i have the same question as @mhoemmen: i don't know whats really happening and what thrust would do in that case...
In between i'm tending to implement a small serial bubblesort which could be called from within my kokkos kernels...

**Comment by mhoemmen** [comment]
@tawiesn See the following (now closed) issue for sorting of short arrays:

https://github.com/trilinos/Trilinos/issues/887

**Comment by gmackey** [comment]
@mhoemmen Oh, you're right.  I combined code from two places for my example.  thrust::sort is a parallel sort.  It shouldn't be used inside a parallel loop.  One of the pieces of code used the templated class trick to sort a single array.  When I did the parallel loop around sorting I was using my own quicksort implementation.  Sorry for the confusion.

**Comment by gmackey** [comment]
@tawiesn I'm not going to answer your question, since if you look at my above post, thrust::sort is not what you want.  What I will do is a better temporary solution.  Here is an implementation of insertion sort you should be able to use for now.

```
/// \brief Sorts the elements in an array.
/// \param array The array to sort.
/// \param left The first entry to sort.
/// \param right One past the last entry to sort.
/// \param comp Compares two elements.
template <typename ArrayType, typename Comparator>
KOKKOS_FUNCTION
void
insertion_sort(ArrayType& array, int64_t left, int64_t right, Comparator comp)
{
  typedef typename property_traits<ArrayType>::value_type value_type;

  for (int64_t i = left + 1; i < right; ++i)
  {
    value_type value = array[i];
    int64_t j = i;

    if (comp(array[i], array[left]))
    {
      for ( ; j > left; --j) array[j] = array[j - 1];

      array[left] = value;
    }
    else
    {
      for ( ; comp(value, array[j - 1]); --j) array[j] = array[j - 1];

      array[j] = value;
    }
  }
}

/// \brief Sorts the elements in an array using '<' as the comparator.
/// \param array The array to sort.
/// \param left The first entry to sort.
/// \param right One past the last entry to sort.
template <typename ArrayType>
KOKKOS_INLINE_FUNCTION
void
insertion_sort(ArrayType& array, int64_t left, int64_t right)
{
  typedef typename property_traits<ArrayType>::value_type value_type;

  insertion_sort(array, left, right, less<value_type>());
}
```

**Comment by mhoemmen** [comment]
Tpetra already has all this code -- you just need to stick KOKKOS_FUNCTION in front of stuff (I wouldn't do KOKKOS_INLINE_FUNCTION since it probably wouldn't make sense to inline general sort) -- but thanks :D

**Comment by gmackey** [comment]
@tawiesn Forgot to mention that you can use this inside a parallel loop.  It will work on CPU and GPU.

**Comment by gmackey** [comment]
@mhoemmen Yeah, the only issue is adding KOKKOS_FUNCTION in front of the algorithm.  I agree with your statement about KOKKOS_INLINE_FUNCTION.  I only used it for the wrapper function in the code I listed.

**Comment by gmackey** [comment]
In general, would it be useful to have sorting algorithms in Kokkos?  How about other algorithms from the std algorithm header?  I've got a bunch of these implemented in MTGL (Multithreaded Graph Library) to make my life simpler there.  They are all written using Kokkos primitives, so they wouldn't be too hard to add into kokkos/algorithms.

**Comment by mhoemmen** [comment]
@gmackey Thanks! A team sort would be nice :-)  I've prototyped some sort functions for arrays of fixed lengths (2, 3, 4, 8) in Trilinos/packages/tpetra/core/src/Tpetra_Details_shortSort.hpp.  They use sort networks to get the minimum number of comparisons.  However, those are still single-thread versions; I don't have team versions yet.

**Comment by gmackey** [comment]
@mhoemmen What we really need is for NVIDIA to implement a CUDA-aware version of the std algorithm header!  :)

**Comment by tawiesn** [comment]
Thanks @gmackey. I've written a simple bubble sort that worked for me inside the kernel (both GPU+CPU) but i would switch to your more general code.
@gmackey, @mhoemmen: I think it would make sense to collect algorithms like that in a central place like Kokkos algorithms.

**Comment by crtrott** [comment]
That is exactly what Kokkos algorithms is intended for. I just didn't ever have time nor the incentive to populate it. If you have things like that putting it in there is the right thing to do in my mind, starting with something like a serial, and a per-team sort.

**Comment by gmackey** [comment]
@crtrott Sounds good.  As I get time, I will add things to Kokkos algorithms.

**Comment by brentmorgan1987** [comment]
Hi,

has anyone found a solution to this?  I'm trying to use Thrust::merge_by_key inside a Kokkos parallel_for loop and it's breaking/crashing.  Do I have to implement my own method Kokkos::merge_by_key()?  thanks,

**Comment by crtrott** [comment]
I am not aware of any framework which has this as a build in capability.

**Comment by ibaned** [comment]
For what it's worth, this is a capability that would come in very handy for mesh adaptation on GPUs. I coded my own (parallel_for over the arrays, local serial insertion sort for each array), but it is one of the more expensive kernels in the system. Just noting there is demand.

**Comment by keichi** [comment]
Our application also needs parallel partial sort of many arrays and we ended up implementing our own partial sort. I thought about using the block-wide radix sort provided by NVIDIA CUB, but I don't know how well CUB integrates with Kokkos.
https://nvlabs.github.io/cub/classcub_1_1_block_radix_sort.html

**Comment by ajpowelsnl** [comment]
assign to @brian-kelley

**Comment by ajpowelsnl** [comment]
Attempting to assign to @brian-kelley for Kokkos 3.6.

**Comment by PhilMiller** [comment]
4.0 released with this.

**Comment by dalg24** [comment]
Need to update the 4.0 changelog to reflect this and cherry pick into 4.0.01
