### ISSUE TITLE
Bitset: should it be default constructed ?

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#6467]
## Summary

This issue's purpose is to discuss whether or not `Kokkos::Bitset` should be:
- [:one:] Default constructed *by the compiler*, much like `Kokkos::View` is. It is therefore completely **default-initialized**.
- [:two:] Default constructed *with a defaulted zero size*, as it is the case now. All members of `Kokkos::Bitset` (like views) are initialized **to a zero size**.

### Context

In PR #6198, I made `Kokkos::Bitset` completely default constructed *by the compiler* (more or less along these lines):
 ```c++
 KOKKOS_DEFAULTED_FUNCTION
  Bitset() = default;

  /// constructor
  /// arg_size := number of bit in set
  explicit Bitset(unsigned arg_size) : Bitset(Kokkos::view_alloc(), arg_size) {}

  template <class... P>
  Bitset(const Impl::ViewCtorProp<P...>& arg_prop, unsigned arg_size)
```

but  @masterleinad  wanted to discuss this change in a seperate issue/PR. The current constructors of `Kokkos::Bitset` are:
```c++
  /// constructor
  /// arg_size := number of bit in set
  Bitset(unsigned arg_size = 0u) : Bitset(Kokkos::view_alloc(), arg_size) {}

  template <class... P>
  Bitset(const Impl::ViewCtorProp<P...>& arg_prop, unsigned arg_size)
```

### Proposition

Make `Kokkos::Bitset` default constructed.

### Possible backward compatibility issues

The only issue I see transitioning from situation :two: to :one: is that if someone wrote code like:
```c++
auto my_bitset = Kokkos::Bitset(); // for now, this is equivalent to writing Bitset(0)
ASSERT(my_bitset.is_allocated()); // for now this is OK
```
then using the defaulted compiler constructor would break the assertion. Not sure anyone wrote such a code though (except in `TestBitset.hpp` of course :wink:).

However, I think having the size defaulted to 0 is weird, because it then sets `Kokkos::Bitset::m_blocks` to a size 0, so I guess it goes through the whole `Kokkos::View` initialization mechanisms, which is quite unexpected for a default constructed device container... right?

If Kokkos team agrees on making the changes to situration :one: I can take care of the PR.

**Comment by ajpowelsnl** [comment]
Thanks, @romintomasetti.  I'll put it on the agenda for discussion.

**Comment by masterleinad** [comment]
@romintomasetti Do you have a particular use case in mind where this would make a difference?

**Comment by romintomasetti** [comment]
## Use cases

### Static variables

We think an interesting use case is related to what is discussed in #6447.

Basically, we'd like to have **static** variables (to be used with Google Test's `SetUpTestSuite` **static** method):
```c++
class ...
{
private:
    static Kokkos::View<...> my_view;
    static Kokkos::UnorderMap<...> my_map;
};
```

Similar uses cases would be Google's Benchmark tool, or in fact any production code that relies on static variables at some point.

### Default construction behavior

We think default constructing objects whose purpose is to "store" something should do nothing.

In this case `Bitset` stores *via* its `m_blocks` member. For now, `Kokkos::Bitset()` is trying to initialize this `View` member to a zero size, which I think is a pointless operation because I guess a zero-sized `Bitset` has no use.

The question might rather be: "Is there any use case that requires the default constructor of `Bitset` to set the size of `m_blocks` to zero?".

## Our opinion

In our opinion, it should be harmless to have `Kokkos` objects such as `View` or `Bitset` or `UnorderedMap` as static members of a class.

For now, only `View` would work, since as @dal24 mentioned in https://github.com/kokkos/kokkos/issues/6447#issuecomment-1719267073, default constructing a `View` is allowed before `Kokkos` initialization.

## Discussion

We don't see any reason not to allow other `Kokkos` objects to be default constructed before `Kokkos` is initialized.

### On the `Kokkos` semantics

`Kokkos` semantics on that subject could be:
> It is legal to default construct `Kokkos` objects like `View` or `Bitset` before initializing `Kokkos`.
>
> However, the use of such objects may be illegal **even after `Kokkos` has been initialized**.

### What about execution space classes like `Kokkos::Cuda` ?

(somewhat answer to #6447)

Thinking beyond objects like `View` or `Bitset`, we think it should be legal to allow any `Kokkos` execution space class like `Kokkos::Cuda` to be default constructed before `Kokkos` is initialized.

This statement tends to disagree with @dal24 in https://github.com/kokkos/kokkos/issues/6447#issuecomment-1719279711:
> Now to address your suggestion to change the behavior (we should probably move that discussion elsewhere, open another issue or whatnot) if the default constructor of an execution space does not yield a valid execution space that one can use once Kokkos is initialized, this would be a non starter because that would change the meaning of existing code.

We think default construction of `Kokkos::Cuda` before `Kokkos` is initialized should be made possible according to the proposed new semantic stated above and is *easy to implement*. Indeed, if `Kokkos` is initialized then fine, retrieve the singleton as it's done currently (and so the object can be used, it is *valid*). Otherwise, if `Kokkos` is not yet initialized, simply set the singleton to `nullptr` (and so the object cannot be used - even after `Kokkos` is initialized, it is *invalid*).

We think the current proposal *does not change the meaning of existing codes*, since existing codes should be conforming to the logic "first initialize `Kokkos`, then instantiate my space instance".


@maartenarnst

**Comment by romintomasetti** [comment]
@dalg24 Sorry, I wrote `@dal24` in the previous comment. I modified to comment to use `@dalg24`, but I don't know if this is sufficient to ping you. So I ping you now :ping_pong:

**Comment by dalg24** [comment]
> Bitset: should it be default constructed ?

Catching up slowly.  Only saw that issue after I opened #6524 so yes I agree, even more so because of the interaction with the UnorderedMap constructors.

Regarding the backward incompatibility
```diff
  UnorderedMap m;
- ASSERT_TRUE(m.is_allocated());
+ ASSERT_FALSE(m.is_allocated());
```
I think it is fine.

**Comment by dalg24** [comment]
The [documentation](https://kokkos.github.io/kokkos-core-wiki/API/containers/Unordered-Map.html#unorderedmap) does not mention default initialization (`UnorderedMap(uint32_t)` is the only constructor documented and it has no default argument) and technically `is_allocated` doc remains valid :)

> Return true if the internal views (keys, values, hashmap) are allocated
