### ISSUE TITLE
HIPInternal::concurrency inconsistent with Impl::HIPInternal::m_maxWavesPerCU 

### ISSUE THREAD

**Issue by maartenarnst** [kokkos/kokkos#6473]
**Describe the bug**

Kokkos overrides in `Kokkos_HIP.cpp` the maximum number of warps per CU:

- https://github.com/kokkos/kokkos/blob/41cf2e51cd8e63a614aa1b4a9564a35934b805d5/core/src/HIP/Kokkos_HIP.cpp#L70-L72

However, later in the code in `Kokkos_HIP_Instance.cpp`, the overridden value is not used when computing the concurrency:

- https://github.com/kokkos/kokkos/blob/41cf2e51cd8e63a614aa1b4a9564a35934b805d5/core/src/HIP/Kokkos_HIP_Instance.cpp#L78-L82

For instance, on our Radeon Pro VII, `m_deviceProp.maxThreadsPerMultiProcessor / WarpSize` is 40, whereas `Impl::HIPInternal::m_maxWavesPerCU` is set by Kokkos to 32.

It seems this issue can be straightforwardly fixed by doing in `Kokkos_HIP_Instance.cpp`:

```
int HIPInternal::concurrency() {
  static int const concurrency = m_maxWavesPerCU * Impl::HIPTraits::WarpSize * m_deviceProp.multiProcessorCount;
  return concurrency;
}
```

If you agree with such a change or you have another suggestion, I would be happy to make a PR. Thanks in advance!

**Comment by Rombur** [comment]
@maartenarnst Yes, please open a PR,

**Comment by maartenarnst** [comment]
Thanks, @Rombur. It's PR #6479.

**Comment by maartenarnst** [comment]
Closing as https://github.com/kokkos/kokkos/pull/6479 was merged.
