### ISSUE TITLE
Incorrect half_t and bhalf_t nan and infinity numeric trait values?

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos#6476]
CC: @lucbv

These values are currently set to:

### half_t
https://github.com/kokkos/kokkos/blob/31c060ab505983ea08ca554604c89982c5f674a9/core/src/impl/Kokkos_Half_NumericTraits.hpp#L158-L170

https://github.com/kokkos/kokkos/blob/31c060ab505983ea08ca554604c89982c5f674a9/core/src/impl/Kokkos_Half_NumericTraits.hpp#L64-L74

### bhalf_t
https://github.com/kokkos/kokkos/blob/31c060ab505983ea08ca554604c89982c5f674a9/core/src/impl/Kokkos_Half_NumericTraits.hpp#L302-L307

https://github.com/kokkos/kokkos/blob/31c060ab505983ea08ca554604c89982c5f674a9/core/src/impl/Kokkos_Half_NumericTraits.hpp#L261-L271

Note that casting from float's values for nan and infinity to half_t and bhalf_t may give different values than what is listed above.

Related to https://github.com/lucbv/kokkos-kernels/pull/2.

**Comment by ajpowelsnl** [comment]
@crtrott - would you please have a look at this?

**Comment by ajpowelsnl** [comment]
@e10harvey -- would you please provide a bit more context for this issue?  Would you please help us understand what's needed to address this issue?  Also, would you please clarify how the Kokkos-Kernels PR is related to this issue?

**Comment by crtrott** [comment]
This is probably just completely wrong. The bit patterns will NOT actually be the same after assigning to half_t/bhalf_t from the infinity/NAN stuff.

**Comment by e10harvey** [comment]
> This is probably just completely wrong. The bit patterns will NOT actually be the same after assigning to half_t/bhalf_t from the infinity/NAN stuff. See: https://godbolt.org/z/sM17Tc4Mf
> 
> Essentially `float a = 0x...` will create an integer from the bit pattern, and then do an int to float assignment. That does NOT preserve the bit pattern.

Agreed. 

> would you please provide a bit more context for this issue? Would you please help us understand what's needed to address this issue? Also, would you please clarify how the Kokkos-Kernels PR is related to this issue?

@ajpowelsnl: Certainly. Setting the bit pattern for nan/inf to a constant in https://github.com/kokkos/kokkos/pull/5778 is where this issues stems from. Prior to this change, we used the casted value of inf/nan, from float. As @crtrott points out, the constant in our limits is likely wrong. It shouldn't be difficult to test and fix this but I would need some time allocated to Kokkos to work on this.

**Comment by masterleinad** [comment]
Fixed in #6543.
