### ISSUE TITLE
How do I properly implement NUMA first touch on a View over a Custom Range or Dimension?

### ISSUE THREAD

**Issue by biergaizi** [kokkos/kokkos#6489]
According to the documentation:

> The first (leftmost) dimension of the View is the parallel dimension over which it is most efficient to do parallel array access if the default memory layout is used (e.g. if no specific memory layout is specified).

Issue #640 also says:

> First touch should use the parallel dimension for allocation, which should be rows of your dense preconditioner...

Thus, this indicates that Kokkos automatically performs NUMA first-touch initialization by default over the first dimension when a view is initialized. My question is how to achieve the same effect to ensure good performance on NUMA systems if teams access the view in a non-standard manner (e.g. because it's accessed via a custom subview, or the view has a custom memory layout, or because the view is unmanaged with externally-allocated memory).

My intuition is that, one can first allocate a view via `Kokkos::ViewAllocateWithoutInitializing`, then it can be zeroed via a `parallel_for()` kernel to manually perform a first-touch properly. Kokkos itself will try scheduling the teams launched by different `parallel_for()` invocations to stay within the same NUMA node.

Could you please confirm whether my interpretation is correct?

**Comment by mhoemmen** [comment]
@biergaizi wrote:
> one can first allocate a view via `Kokkos::ViewAllocateWithoutInitializing`, then it can be zeroed via a `parallel_for()` kernel to manually perform a first-touch properly.

That's the correct intuition.

> Kokkos itself will try scheduling the teams launched by different `parallel_for()` invocations to stay within the same NUMA node.

If you use the defaults, and your back-end is configured correctly (e.g., you're using the recommended OpenMP options, and MPI was launched in the right way), then your intuition is sound.

`Kokkos::parallel_for` uses its execution policy to decide how to divide up the index range among threads.  How it does that, and whether it always uses the same mapping from index to thread, depends on the execution policy and its schedule.  Please see [the Kokkos documentation](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/RangePolicy.html) for details.

**Comment by biergaizi** [comment]
Thanks for the answer!
