### ISSUE TITLE
HIP Managed Space device and system config

### ISSUE THREAD

**Issue by JosefRuzicka** [kokkos/kokkos#6507]
Hello, I have a code in Kokkos that I used to run in `CudaUVMSpace` without any issues, now Im trying to port it into an AMD machine with an `MI210 GPU` by changing my MemSpace to `HIPManagedSpace` but I get this warning:

```
Kokkos::HIP::allocation WARNING: The combination of device and system configuration
                                 does not support page migration between device and host.
                                 HIPManagedSpace might not work as expected.  
                                 Please refer to the ROCm documentation on unified/managed memory.
```
                                 
The program works properly, but performance dropped significantly and I'm not sure what the problem might be, or how I can fix that problem that the warning suggests. 
In my Makefile im specifying `KOKKOS_ARCH = VEGA90A`

The program is quite simple as the data structures are created on host, and then copied to device with 
```
  ViewParticleArrayType particles_view("particles_view", n);
  ViewParticleArrayType::HostMirror h_particles_view = Kokkos::create_mirror
  // init on host here
  // ...
  Kokkos::deep_copy(particles_view, h_particles_view);
  // Kokkos::parallel_for here (DROP IN PERFORMANCE OCCURS HERE)
```

Does this issue ring any bell?

**Comment by Rombur** [comment]
For `HIPManagedSpace` to work like `CUDAUVMSpace`, you need hardware that supports it (which you do) and you need `HSA_XNACK` to be enable. Try `export HSA_XNACK=1` before running the code. If you don't have `HSA_XNACK`, `HIPManagedSpace` behave like pinned host memory, i.e., the memory is never moved to the GPU.

**Comment by JosefRuzicka** [comment]
Thank you very much for your answer, I'm sorry I was unaware of this detail, however, when I run the program after `export HSA_XNACK=1`  it gets stuck executing the `Kokkos::initialize()`, I tried it on a simple program that only initializes and finalizes Kokkos as well. (All my tests finish execution properly with `HSA_XNACK=0`)
Is it possible you have any more insights on this matter?

**Comment by Rombur** [comment]
It could be that your kernel is too old or that it wasn't compiled to support page migration but I don't know how you check that.

**Comment by ajpowelsnl** [comment]
@JosefRuzicka - were you able to resolve your issue with the information we provided?

**Comment by JosefRuzicka** [comment]
Hello, Thanks again for your information, right now I'm in the process of checking if the Kernel was compiled to support page migration, which I would assume, because I'm not running these programs on my local machine but on a cluster, however it's the only one of the three requisites which I have not yet verified... I will provide an update as soon as possible.

**Comment by JosefRuzicka** [comment]
Hi again, the system administrators have confirmed to me that the OS (Kernel version 4.18.0-348.20.1.el8_5.x86_64) is compiled to support/allow page migration, we also know that the hardware supports it and `export HSA_XNACK=1` is active, so the three requirements are supposed to be met.

Do you think there might be some reason for Kokkos not to be detecting or respecting these settings?

**Comment by Rombur** [comment]
If you write the following code outside of Kokkos: https://github.com/kokkos/kokkos/blob/1a3ea28f6e97b4c9dd2c8ceed53ad58ed5f94dfe/core/src/HIP/Kokkos_HIP_Space.cpp#L48-L55
What do you get?

**Comment by JosefRuzicka** [comment]
Running that function returns a 0 for me

**Comment by Rombur** [comment]
> Running that function returns a 0 for me

Then it's not a Kokkos issue. Have you tried different ROCm versions?

**Comment by JosefRuzicka** [comment]
Hello, turns out there was something wrong in the installation of the machine I was using, it seemed like the --rocm-path handling was broken, so indeed, it wasn't a Kokkos issue. Thanks for your help!
