### ISSUE TITLE
Question: Check if 'identity element' in atomic overloads of augmented assignment operators

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#651]
This might not be the right thing to do, but in recent changes to my code, I build a matrix in which the matrix elements are computed atomically:

```c++
View<double**, Kokkos::MemoryTraits<Kokkos::Atomic> > A(A_non_atomic);
…
// new way
const int index_i = (condition) ? a : 0;
const int index_j = (condition) ? b : 0;
A(index_i, index_j) += (condition) ? value : 0;
// old way
if (condition)
  A(a, b) += value;
```

This used to be handled by an `if` as shown above , but I attempted to remove `if`s as per @crtrott's suggestion. However, numerical experiments have shown that something above is negatively affecting performance. If I had to guess, it would be increased contention on element `A(0,0)`.

Current workaround which showed significantly better performance:

```c++
View<double**, Kokkos::MemoryTraits<Kokkos::Atomic> > A(A_non_atomic);
…
// new way
const int index_i = (condition) ? a : min(a, A.extent(0) - 1);
const int index_j = (condition) ? b : min(b, A.extent(1) - 1);
A(index_i, index_j) += (condition) ? value : 0;
```

If someone has already worked out a solution for this that does not increase contention and does not require the `extent`s, I'd be very interested in hearing about it. Without knowing what's going on, my thought would be something like this: 

```c++
const_value_type plus_equal_identity_element = 0;

KOKKOS_INLINE_FUNCTION
const_value_type operator += (const_value_type& val) const {
  const_value_type tmp = (val == plus_equal_identity_element) ? plus_equal_identity_element : Kokkos::atomic_fetch_add(ptr,val);
  return tmp+val;
}
```

However, inserting that additional comparison on a very performance critical operator could make this potential fix a non-starter. 

Thoughts on how insane (if even possible) this is and/or other potential solutions?

The verbiage used here comes from: https://en.wikipedia.org/wiki/Augmented_assignment and https://en.wikipedia.org/wiki/Identity_element

**Comment by crtrott** [comment]
If you do atomics, the if condition doesn't hurt you anyway since the atomic operations will prevent vectorization etc. anyway. So not sure if this is something you should pursue.

**Comment by dholladay00** [comment]
The current workaround seems to work ok so I think I will leave it until I see reason to change it. It appears to not increase contention as much and also doesn't cause debug builds to throw view bounds errors.
