### ISSUE TITLE
Silent failure when reaching the maximum iteration count

### ISSUE THREAD

**Issue by petschge** [kokkos/kokkos#6517]
The following code works

```
#include <Kokkos_Vector.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);

  const  int64_t N = pow(2LL, 39LL) - pow(2LL, 8LL);
  double nu = 0;

  Kokkos::parallel_reduce("sample reduction",
    Kokkos::RangePolicy <Kokkos::IndexType<int64_t>> (0,N),
    KOKKOS_LAMBDA(const int64_t i, double & mynu_) { mynu_ += 1.0; },
    nu);
  Kokkos::fence();

  printf("N=%lu, nu=%g\n", N, nu);

  Kokkos::finalize();
  return 0;
}
```

and gives "N=549755813632, nu=5.49756e+11" as expected but changing the definition of N to
`const  int64_t N = pow(2LL, 39LL) - pow(2LL, 8LL) + 1;`
breaks things and results in "N=549755813633, nu=0" on GPU (it work on CPU / the OpenMP backend, but is of course much slower).

Kokkos config looks as follows:
```
#define KOKKOS_VERSION 40100
#define KOKKOS_VERSION_MAJOR 4
#define KOKKOS_VERSION_MINOR 1
#define KOKKOS_VERSION_PATCH 0
#define KOKKOS_ENABLE_SERIAL
#define KOKKOS_ENABLE_OPENMP
#define KOKKOS_ENABLE_CUDA
#define KOKKOS_ENABLE_CXX17
#define KOKKOS_ENABLE_CUDA_LAMBDA  // deprecated
#define KOKKOS_ENABLE_DEPRECATED_CODE_4
#define KOKKOS_ENABLE_DEPRECATION_WARNINGS
#define KOKKOS_ENABLE_COMPLEX_ALIGN
#define KOKKOS_ENABLE_LIBDL
#define KOKKOS_ARCH_TURING75
```

As discussed on slack, this is (probably) an issue of reaching the 2^31-1 iteration limit with a block_size of 256. It would be nice to get an explicit error message when reaching that limit instead of silent failure.

**Comment by Rombur** [comment]
We need to check but I believe that you get an error if you enable `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK`.

**Comment by fnrizzi** [comment]
`Kokkos_ENABLE_DEBUG_BOUNDS_CHECK` catches this , i opened https://github.com/kokkos/kokkos/pull/6578 to work on a more useful message

**Comment by ajpowelsnl** [comment]
@crtrott, @masterleinad - ok to close, since latest release?
