### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#653]
I get the following installation error when installing kokkos with cmake
```

CMake Error at algorithms/src/cmake_install.cmake:40 (file):
  file INSTALL cannot find
  "/home/lbertag/workdir/kokkos/kokkos-src/algorithms/src/EXPORT".
Call Stack (most recent call first):
  algorithms/cmake_install.cmake:37 (include)
  cmake_install.cmake:41 (include)
```

A quick look to algorithms/src/cmake_install.cmake shows the following

```
if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "KokkosAlgorithms")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE FILE FILES
    "/home/lbertag/workdir/kokkos/kokkos-src/algorithms/src/Kokkos_Random.hpp"
    "/home/lbertag/workdir/kokkos/kokkos-src/algorithms/src/Kokkos_Sort.hpp"
    "/home/lbertag/workdir/kokkos/kokkos-src/build/algorithms/src/KokkosAlgorithms_config.h"
    "/home/lbertag/workdir/kokkos/kokkos-src/algorithms/src/EXPORT"
    "/home/lbertag/workdir/kokkos/kokkos-src/algorithms/src/KokkosCMake"
    )
endif()
```

The last two files indeed do not exist. Is this a bug? Am I missing some configuration flags?

**Comment by bartgol** [comment]
I am not sure if this is a correct fix. However, removing the following lines from tribits.cmake fixed the problem for me:

 
     INSTALL(
       FILES  ${PARSE_HEADERS}
-      EXPORT ${PROJECT_NAME}
       DESTINATION include
       COMPONENT ${PACKAGE_NAME}
       )
 
       INSTALL(
       DIRECTORY  ${PARSE_HEADERS_INSTALL_SUBDIR}
-      EXPORT ${PROJECT_NAME}
       DESTINATION include
       COMPONENT ${PACKAGE_NAME}
       )

**Comment by hcedwar** [comment]
To install Kokkos most efficient to use the generate makefile and make.
