### ISSUE TITLE
Tribits macro assumes build directory is in top level source directory

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#654]
At line 511 of cmake/tribits.cmake you can see

`    ADD_SUBDIRECTORY(${CMAKE_BINARY_DIR}/../${SUBPACKAGE_DIR})`

This is assuming that the build directory is a subfolder of the kokkos top level source dir. If it's not the case, cmake does not find ${SUBPACKAGE_DIR} and errors out.

I would replace that line with

`    ADD_SUBDIRECTORY(${CMAKE_SOURCE_DIR}/${SUBPACKAGE_DIR})`

allowing the user to build the library wherever he wants.

Of course, unless I am missing some crucial detail about the tribits working flow...

**Comment by crtrott** [comment]
We can try this. the tribits.cmake is actually just a stubs for real tribits, so it only affects pure cmake builds.

**Comment by crtrott** [comment]
I assign Greg, who has been working on pure cmake related stuff.

**Comment by gmackey** [comment]
This issue will be fixed with the new cmake build.  The build directory can be wherever the user wants.
