### ISSUE TITLE
Kokkos RNG normal() function hangs for small seed value

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#655]
The Kokkos RNG normal() function hangs in its while loop if the RNG seed is a small integer (i.e. 0). It seems like the RNG warmup isn't working properly, or is this expected?

**Comment by crtrott** [comment]
It probably doesn't hang, but it doesn't converge. So we need to something better for warmup. Btw, is it just zero?

**Comment by stanmoore1** [comment]
Yeah, what happened is that our collaborator used the MPI rank as the seed, and for a single core, the seed becomes 0.

**Comment by stanmoore1** [comment]
So even a check on if the seed is valid (i.e. >0) could be helpful.

**Comment by mhoemmen** [comment]
@crtrott would it make sense just to "time out" of the loop if it does too many iterations (whatever we think "too many" should mean)?

**Comment by crtrott** [comment]
I'll fix it.

**Comment by stanmoore1** [comment]
Thanks!
