### ISSUE TITLE
Adding code-of-conduct in repo

### ISSUE THREAD

**Issue by mohitd404** [kokkos/kokkos#6550]
**Describe the bug**

code-of-conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure 
a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a 
wider range of perspectives.

**Issue type**

- [✅] Doc

@dalg24 @philmiller @masterleinad  if you were planning for this issue kindly assign to me! I would love to work on it ! Thank you !

**Comment by ajpowelsnl** [comment]
@mohitd404 - is there a need for a code of conduct?  We will reopen issue if a clear need is defined.

**Comment by crtrott** [comment]
There are some ongoing discussions regarding governance which will include official project specific code of conduct documentation in the next few months. For now the vast majority of contributors are actually already bound by the code of conduct at their institutions which happen to be largely DOE labs anyway.
