### ISSUE TITLE
Adding Contributors section in readme.md

### ISSUE THREAD

**Issue by mohitd404** [kokkos/kokkos#6551]
**Describe the bug**
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**

- [✅] Doc
Expected Output 
![3](https://github.com/kokkos/kokkos/assets/146939900/63b16011-ceaf-4ba3-b330-a49a92a5b819)

@dalg24 @hilMiller @masterleinad  if you were planning for this issue kindly assign to me! I would love to work on it ! Thank you !

**Comment by ajpowelsnl** [comment]
@mohitd404 - we have clear [guidelines](https://kokkos.github.io/kokkos-core-wiki/contributing.html#) for contributing to the project.  In the main, we are interested in contributions to Kokkos core source code and/or Kokkos Documentation.
