### ISSUE TITLE
Breaking change for empty runtime unmanaged views

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#6563]
This issue was introduced in #6536 and diagnosed in https://github.com/kokkos/kokkos/issues/6559#issuecomment-1787491503

Essentially we did not anticipate that the view constructor changes in #6536 broke runtime unmanaged views with `0` and `NULL` (implementation-dependent for the latter) as the pointer argument.
```C++
Kokkos::View<int*> v(nullptr, 0);  // ok
Kokkos::View<int*> v(0, 0);        // does not compile since #6536
Kokkos::View<int*> v(NULL, 0);     // also broken
```

**Comment by crtrott** [comment]
Probably need to roll back. mdspan allows all three too.

**Comment by masterleinad** [comment]
> Probably need to roll back. mdspan allows all three too.

I agree. I don't expect that we gain enough from that pull request to justify breaking code.
