### ISSUE TITLE
LAMMPS built with KOKKOS results in "Kokkos::Cuda::initialize ERROR: likely mismatch of architecture" error when trying to run a simulation on a GPU

### ISSUE THREAD

**Issue by superde1fin** [kokkos/kokkos#6565]
Dear KOKKOS developers,

I apologize in advance if this question has to be directed to LAMMPS team. If that is so, please let me know.

I am attempting to build LAMMPS with the KOKKOS package for my university gpu server.

Here is the complete procedure I am following:
1) Build Cuda-aware OpenMPI.

For this I am following this [tutorial](https://www.open-mpi.org/faq/?category=buildcuda). As it says in there two other dependencies are needed - gdrcopy and UCX. First problem arose with building UCX on the machine as it is running Rocky 8.7 with glibc version of 2.28. As it is mentioned on the [UCX page of known issues](https://github.com/openucx/ucx#known-issues) it may not build with such version, so I had to build newer glibc. After I did so UCX compiled without any errors.

2) Build LAMMPS with KOKKOS and MPI. 

To do so I was referring to this [tutorial provided by lammps](https://docs.lammps.org/Build_extras.html#kokkos) to figure out the flags needed for KOKKOS and [this one](https://docs.lammps.org/Build_basics.html) for the MPI tags. The GPUs located on the machine are mentioned in one of the screenshots I have attached and seem to be the NVIDIA A100 which I found to have the Ampere architecture as mentioned [here](https://developer.nvidia.com/blog/nvidia-ampere-architecture-in-depth/). The cpu info is also attached in one of the screenshots indicates that they are the Intel(R) Xeon(R) Platinum 8358. This GPU is not directly listed on the KOKKOS page, but I found it to just be a newer version of Ice Lake Xenon as mentioned [here](https://www.intel.com/content/www/us/en/products/sku/212282/intel-xeon-platinum-8358-processor-48m-cache-2-60-ghz/specifications.html). With all that said I have arrived at the following build command for LAMMPS:

cmake -D CMAKE_INSTALL_PREFIX=/home/vasilii/sub_root -D PKG_MANYBODY=yes -D KSPACE=yes -D BUILD_MPI=yes -D BUILD_OMP=yes -D LAMMPS_MACHINE=mpi -D PKG_KOKKOS=yes -D Kokkos_ARCH_ICX=yes -D Kokkos_ARCH_AMPERE86=yes -D Kokkos_ENABLE_CUDA=yes -D Kokkos_ENABLE_OPENMP=yes -D BUILD_LIB=yes -D BUILD_SHARED_LIBS=yes -D FFT=KISS ../cmake

Then using the command line switches described [here](https://docs.lammps.org/Run_options.html) I ran the following command:

mpirun -np 20 lmp_mpi -k on g 1 0 -sf kk -in frac_0_in.lammps

and it resulted in the following error:

"Kokkos::Cuda::initialize ERROR: likely mismatch of architecture" (screenshot also attached)

I have absolutely no idea why this might be happening... What bothers me is that all three devices that show up in lshw have an id of 0 and therefore KOKKOS is defaulting into the first one which I don't even recognize.

Could this be a potential issue? If so, I have noticed that the two GPUs are located on different pci buses, so how would I tell KOKKOS which exact GPU to llok at? Would it be done during compilation or during my "mpirun" command?

It is worth mentioning that I have tried building LAMMPS with the Kokkos_ARCH_AMPERE80=yes tag also which yielded the same results.

**Comment by dalg24** [comment]
Try omitting the Kokkos_ARCH_* argument and let Kokkos auto detect the
architecture of your GPU.

**Comment by dalg24** [comment]
We generally recommend asking these kind of questions on our Slack
workspace.

**Comment by superde1fin** [comment]
@dalg24 Trying your suggestion right now. Would you also please direct me on how to access the slack workspace?

**Comment by dalg24** [comment]
Look in the README at the root of the repository on GitHub

**Comment by ajpowelsnl** [comment]
Hi @superde1fin - a few questions:  1) were you able to find the info needed to sign up for Kokkos Slack? 2) assuming you were able to join Kokkos Slack, were you able to resolve your issue there?  3) if you weren't able to resolve your issue on Kokkos Slack, how can we help further?

**Comment by masterleinad** [comment]
See https://kokkosteam.slack.com/archives/CBC2FRMQ9/p1698868152066209.

**Comment by dalg24** [comment]
Reference to Slack discussion are useful but not sufficient.  Please add a quote.

**Comment by masterleinad** [comment]
> Reference to Slack discussion are useful but not sufficient. Please add a quote.

I meant to say that the discussion was moved to `Slack` since that's more appropriate then posting it here. Anyway, the last comment in the discussion was
> I believe I built and/or linked glibc incorrectly somehow. Turns out there was already a precompiled version of openmpi on our cluster, so when I used that everything worked. Sorry for wasting your time.
