### ISSUE TITLE
Problem using gnu_generate_makefile.sh when GNU make version is >= 4.3

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#6605]
**Describe the bug**
 
When trying to build kokkos using `gnu_generate_makefile.bash`, some generated unit test source files are ill-formed due to a change of behavior in GNU make version 4.3. E.g. when the following code gets expanded by Makefile
```make
# this works with make 4.2 but not with 4.3
$(shell echo "\#include <TestSort.hpp>" >> Test.cpp)
```
the slash gets printed in the output `Test.cpp`

One solution to fix the problem is mentioned e.g. here:
https://github.com/CEED/libCEED/blob/6dbc39456a768b0ea4055927c94c474873ea8bf6/common.mk#L34

just use this instead (it works for all version of make, I tested 4.2 and 4.3)
```make
HASH=\#
$(shell echo "$(HASH)include <TestSort.hpp>" >> Test.cpp)
```

**Please also include the following items to support reproducing the bug**

To reproduce, e.g.:
```shell 
mkdir _build
cd _build
../gnu_generate_makefile.bash --with_devices=OpenMP
make
g++ -I./ -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/core/src -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/containers/src -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/algorithms/src -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/tpls/desul/include -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/tpls/mdspan/include -std=c++17 -fopenmp -I./ -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/core/src -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/containers/src -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/algorithms/src -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/tpls/desul/include -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/tpls/mdspan/include -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/tpls/gtest -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/core/unit_test -I/data/pkestene/install/trilinos/kokkos/github/kokkos_test/core/unit_test/category_files -O3  -c TestOpenMP_Init.cpp
TestOpenMP_Init.cpp:1:1: error: stray ‘\’ in program
    1 | \#include <TestOpenMP_Category.hpp>
      | ^
TestOpenMP_Init.cpp:1:2: error: stray ‘#’ in program
    1 | \#include <TestOpenMP_Category.hpp>
      |  ^
TestOpenMP_Init.cpp:2:1: error: stray ‘\’ in program
    2 | \#include <TestInit.hpp>
      | ^
TestOpenMP_Init.cpp:2:2: error: stray ‘#’ in program
    2 | \#include <TestInit.hpp>
      |  ^
TestOpenMP_Init.cpp:1:3: error: ‘include’ does not name a type
    1 | \#include <TestOpenMP_Category.hpp>
      |   ^~~~~~~

```

1. compilers (with versions)
2. Kokkos release or commit used (i.e., the sha1 number)
3. platform and backend
4. cmake configure command
5. output from cmake command
6. code needed to reproduce the bug
7. command line needed to reproduce the bug
7. please also attach the `KokkosCore_config.h` header file (generated during the build);
**Any additional info**
Please provide any additional context about the issue here.

**Comment by pkestene** [comment]
a possible fix here : 
https://github.com/pkestene/kokkos/commit/4800522a03d15a5e0a2f1e88aa46aeb941460bec

**Comment by dalg24** [comment]
Would you open a PR with that fix?  (make sure you add a line ending after the definition of HASH L1508)
