### ISSUE TITLE
MDRangePolicy has no API to obtain the default tile size

### ISSUE THREAD

**Issue by biergaizi** [kokkos/kokkos#6609]
I have parallelized a loop with Kokkos that iterates across 3D space using an `MDRangePolicy` with rank 3, and I want to investigate the performance impact of different tile sizes. Unfortunately, according to the [documentation](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/MDRangePolicy.html), `MDRangePolicy` has no public API to query the default tile sizes, so the default decision by Kokkos is a mystery to users. I've tried to manually specify various tile sizes, none of the sizes I've guessed is as fast as the unknown one used picked by Kokkos, so knowing the values is of great practical significance.

MDRangePolicy should provide a public API to expose this runtime setting, similar to `chunk_size()` or `team_size_recommended()` in `TeamPolicy`.

**Comment by masterleinad** [comment]
Note that `m_tile` is public as of now (which we might change).

**Comment by biergaizi** [comment]
> Note that m_tile is public as of now (which we might change).

Interesting, thanks for the hint. I'll use `m_tile` for debugging purpose for now.

**Comment by biergaizi** [comment]
In case anyone's wondering, I've solved my original question that motivated the creation of this issue: understanding the default behaviors of Kokkos.

Right now under most situations, MDRangePolicy's default tiling has a size of 2, with the exception of the last dimension (or stride-1 dimension), which is used in full. Thus, a 100x100x100 index space would usually be tiled by default as 2x2x100. This is consistent with the common experience that 2D loop tiling in 3D space is faster than 3D loop tiling in 3D space since the last loop dimension is stride-1 streaming access.

Storing the array in a tiled format can reduce the 3D tiling overhead if its use is preferred. Right now Kokkos offers `LayoutTiled` but it only supports static tile sizes, not dynamic ones.

**Comment by ajpowelsnl** [comment]
@biergaizi - have we been able to answer your questions, and provide the help you need?

**Comment by biergaizi** [comment]
It solved *my personal* problem but I don't think it has solved this *Kokkos* problem. There's still no public API to obtain the default tile size, so this is at best a workaround and there's still no "legal" way to do it.

**Comment by crtrott** [comment]
Yeah, we actually probably need a max tile size as well. Possibly this needs to follow the TeamPolicy pattern of recommend and max team_size.
