### ISSUE TITLE
lambda and cuda

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#661]
Has something changed in kokkos with respect to lambda on cuda?  Does it work?  Do I need to do something special?

  Kokkos::parallel_for(size, KOKKOS_LAMBDA(const int i) {
    r(i) = rhs(i) - r(i);
    r_tilde(i) = r(i);
  });

fails to compile

/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include/Cuda/Kokkos_CudaExec.hpp(284): error: The closure type for a lambda ("lambda [](int)->void") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is a 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelFor<lambda [](int)->void, Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>, Kokkos::DefaultExecutionSpace>> 
(284): here
            instantiation of "Kokkos::Impl::CudaParallelLaunch<DriverType, false>::CudaParallelLaunch(const DriverType &, const dim3 &, const dim3 &, int, cudaStream_t) [with DriverType=Kokkos::Impl::ParallelFor<lambda [](int)->void, Kokkos::RangePolicy<Kokkos::DefaultExecutionSpace>, Kokkos::DefaultExecutionSpace>]" 
/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include/Cuda/Kokkos_Cuda_Parallel.hpp(526): here
            instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::execute() const [with FunctorType=lambda [](int)->void, Traits=<Kokkos::DefaultExecutionSpace>]" 
/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include/Kokkos_Parallel.hpp(221): here
            instantiation of "void Kokkos::parallel_for(size_t, const FunctorType &, const std::__cxx11::string &) [with FunctorType=lambda [](int)->void]" 
/home/mbetten/Trilinos/N-Body/src/CG_solve.hpp(98): here

**Comment by gmackey** [comment]
Did you pass the flag '--expt-extended-lambda' to nvcc_wrapper?  This flag is required to turn on lambdas for NVCC.  Also, what version of NVCC are you using?  Lambdas are only supported starting with 7.5.

**Comment by bathmatt** [comment]
Yes, I added it to nvcc
# Cuda (NVCC) only arguments
cuda_args="--expt-extended-lambda"

I also tried having it in the c++ flags. 

dir-src (cuda) 14 $ /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/bin/mpicxx    -I/home/mbetten/Trilinos/N-Body/src/. -I/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include -I/usr/local/cuda/include  -std=c++11 -O3 -DNDEBUG   -o CMakeFiles/ComplexMatrix.exe.dir/main.cpp.o -c /home/mbetten/Trilinos/N-Body/src/main.cpp --expt-extended-lambda


and I just updated from 8.0 something to the latest 8.0 version 

dir-cuda (cuda) 10 $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by gmackey** [comment]
The compile command you listed there appears to use a non-cuda compiler.  Are you sure you are using the cuda compiler?  Are you compiling using nvcc_wrapper instead of nvcc?  Kokkos requires nvcc_wrapper to compile.  If you are using an environment variable (such as CXX) to set the compiler, is it set to nvcc_wrapper and not nvcc?  On some machines using modules, I've seen CXX being set to something different.

**Comment by bathmatt** [comment]
I set OMPI_CXX
dir-~ (cuda) 2 $ echo $OMPI_CXX 
/home/mbetten/bin/nvcc_wrapper
dir-~ (cuda) 3 $

**Comment by bathmatt** [comment]
dir-~ (cuda) 3 $ mpicxx --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
dir-~ (cuda) 4 $

**Comment by gmackey** [comment]
What is the environment variable CXX set to?  Sometimes this is used instead of OMPI_CXX, and I've had to manually set it to nvcc_wrapper.

**Comment by bathmatt** [comment]
mpicxx is calling nvcc.  the comment above shows the version, Also, you wouldn't be getting cuda errors if nvcc was not being called.

dir-cuda (cuda) 9 $ echo $CXX
g++
dir-cuda (cuda) 10 $ which g++
/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/g++
dir-cuda (cuda) 11 $ 

dir-src (cuda) 15 $ /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/bin/mpicxx    -I/home/mbetten/Trilinos/N-Body/src/. -I/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include -I/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include -I/usr/local/cuda/include  -std=c++11 -O3 -DNDEBUG   -o CMakeFiles/ComplexMatrix.exe.dir/main.cpp.o -c /home/mbetten/Trilinos/N-Body/src/main.cpp -v
Using built-in specs.
COLLECT_GCC=g++
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base --disable-multilib
Thread model: posix
gcc version 5.3.0 (GCC) 
COLLECT_GCC_OPTIONS='-std=c++11' '-D' '__CUDA_ARCH__=350' '-E' '-D' 'CUDA_DOUBLE_MATH_FUNCTIONS' '-D' '__CUDACC__' '-D' '__NVCC__' '-D' '__CUDACC_EXTENDED_LAMBDA__' '-v' '-pthread' '-O3' '-I' '/home/mbetten/Trilinos/N-Body/src/.' '-I' '/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include' '-I' '/usr/local/cuda/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/include' '-I' '/usr/local/cuda/bin/../targets/x86_64-linux/include' '-D' '__CUDACC_VER__=80061' '-D' '__CUDACC_VER_BUILD__=61' '-D' '__CUDACC_VER_MINOR__=0' '-D' '__CUDACC_VER_MAJOR__=8' '-D' 'NDEBUG' '-include' 'cuda_runtime.h' '-m64' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/cc1plus -E -quiet -v -I /home/mbetten/Trilinos/N-Body/src/. -I /home/mbetten/installs/install-for-panzer/cuda-RELEASE/include -I /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include -I /projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include -I /projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include -I /usr/local/cuda/include -I /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/include -I /usr/local/cuda/bin/../targets/x86_64-linux/include -iprefix /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/ -D_GNU_SOURCE -D_REENTRANT -D __CUDA_ARCH__=350 -D CUDA_DOUBLE_MATH_FUNCTIONS -D __CUDACC__ -D __NVCC__ -D __CUDACC_EXTENDED_LAMBDA__ -D __CUDACC_VER__=80061 -D __CUDACC_VER_BUILD__=61 -D __CUDACC_VER_MINOR__=0 -D __CUDACC_VER_MAJOR__=8 -D NDEBUG -include cuda_runtime.h /home/mbetten/Trilinos/N-Body/src/main.cpp -m64 -mtune=generic -march=x86-64 -std=c++11 -O3
ignoring nonexistent directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../x86_64-unknown-linux-gnu/include"
ignoring duplicate directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0"
ignoring duplicate directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu"
ignoring duplicate directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward"
ignoring duplicate directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include"
ignoring duplicate directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed"
ignoring nonexistent directory "/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../x86_64-unknown-linux-gnu/include"
ignoring duplicate directory "/usr/local/cuda/bin/../targets/x86_64-linux/include"
ignoring duplicate directory "/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include"
ignoring duplicate directory "/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include"
ignoring duplicate directory "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/include"
ignoring duplicate directory "/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/mbetten/Trilinos/N-Body/src/.
 /home/mbetten/installs/install-for-panzer/cuda-RELEASE/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include
 /usr/local/cuda/include
 /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.4.7/openmpi/1.10.1/parallel/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.4.7/openmpi/1.10.1/parallel/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.4.7/base/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.4.7/base/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.4.7/base/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.4.7/base/include
 /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.4.7/openmpi/1.10.1/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/5.3.0/base/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/5.3.0/base/include
 /projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/5.3.0/base/include
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed
 /usr/local/include
 /net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/../../include
 /usr/include
End of search list.
COMPILER_PATH=/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/:/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../libexec/gcc/
LIBRARY_PATH=/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/:/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.4.7/openmpi/1.10.1/parallel/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.4.7/openmpi/1.10.1/parallel/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.4.7/base/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/4.4.7/base/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.4.7/base/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.4.7/base/lib/:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/lib/:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.4.7/openmpi/1.10.1/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/5.3.0/base/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/5.3.0/base/lib/:/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/5.3.0/base/lib/:/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-std=c++11' '-D' '__CUDA_ARCH__=350' '-E' '-D' 'CUDA_DOUBLE_MATH_FUNCTIONS' '-D' '__CUDACC__' '-D' '__NVCC__' '-D' '__CUDACC_EXTENDED_LAMBDA__' '-v' '-pthread' '-O3' '-I' '/home/mbetten/Trilinos/N-Body/src/.' '-I' '/home/mbetten/installs/install-for-panzer/cuda-RELEASE/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/5.3.0/openmpi/1.10.1/parallel/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/5.3.0/openmpi/1.10.1/parallel/include' '-I' '/usr/local/cuda/include' '-I' '/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/include' '-I' '/usr/local/cuda/bin/../targets/x86_64-linux/include' '-D' '__CUDACC_VER__=80061' '-D' '__CUDACC_VER_BUILD__=61' '-D' '__CUDACC_VER_MINOR__=0' '-D' '__CUDACC_VER_MAJOR__=8' '-D' 'NDEBUG' '-include' 'cuda_runtime.h' '-m64' '-shared-libgcc' '-mtune=generic' '-march=x86-64'

**Comment by gmackey** [comment]
Try 'export CXX=/home/mbetten/bin/nvcc_wrapper' and see if that affects anything.

**Comment by bathmatt** [comment]
same thing...

**Comment by gmackey** [comment]
Are you compiling using cmake and Trilinos?  If so, are the options Kokkos_ENABLE_CXX11_DISPATCH_LAMBDA and Kokkos_ENABLE_Cuda_Lambda turned on?

**Comment by bathmatt** [comment]
I'll try this, thanks!

**Comment by bathmatt** [comment]
I needed to add this
Kokkos_ENABLE_Cuda_Lambda
Thanks @gmackey !!
