### ISSUE TITLE
nvcc_wrappers and --expt-extended-lambda

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#662]
I tried to add a flag to nvcc_wrappers
cuda_args="--expt-extended-lambda"
since I want it for all my compiles.  However, if I do so, my trilinos configure fails.  

  /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/bin/mpicxx
  -o CMakeFiles/cmTC_03b07.dir/testCXXCompiler.cxx.o -c
  /home/mbetten/builds/panzer/cuda/debug/CMakeFiles/CMakeTmp/testCXXCompiler.cxx

  /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:133:29:
  error: template argument 1 is invalid

   #if defined(__cplusplus) && !defined(__CUDACC_RTC__)

Is there a universal way to do this for all cuda compiles that doesn't throw this error?  My issue is I want the same configure script for all builds since there is already 100s of options in it and I don't want to have to change it everywhere I go.

**Comment by bathmatt** [comment]
One needs to have the std=c++11 set to get around this error, the first time through this isn't set, 

we could 
cuda_c++11_args="--expt-extended-lambda"

then later in the wrapper we could
    cuda_args="$cuda_args $cuda_c++11_args"

That seems to work for configure and build.  

I can patch the file and send it along if it's thought worthwhile

**Comment by crtrott** [comment]
We discussed this today: this is more of an cmake issue and if one is not planning to use a single configure file for all backends the right way to do this is to specify the C++11 flag in cmake as "-std=c++11 --expt-extended-lambda".
