### ISSUE TITLE
Compile time constants

### ISSUE THREAD

**Issue by dutkalex** [kokkos/kokkos#6621]
Hi! 
I am writing a CFD solver and I would like to generate at compile time, with as much precision as possible, some floating point constants, store them in a `Kokkos::Array` and access them from inside of my parallel kernels. 
So far, the only way I found to make this work is to declare a `static constexpr Kokkos::Array<double, N> = quadrature_weights();` inside of my parallel code. This approach works fine on CPUs, but because these constants are computed using `long double`s and only casted into `double`s at the last moment to get the maximum possible precision, GPU builds warns that "long double is treated as double in device code", or simply fail. 
I was wondering if you had ideas about how to approach such problems in a portable way with Kokkos.
Thank you
Alex

**Comment by masterleinad** [comment]
As long as the constant you are using is of type `double` you should be fine, also see https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#const-variables for `Cuda`.

> GPU builds warns that "long double is treated as double in device code", or simply fail.

What do failures look like?

**Comment by dutkalex** [comment]
Compiling with gcc+nvcc works fine but I get that "long double is treated as double in device code" warning, while with clang I get the following error:
```
ptxas error   : File uses too much global constant data (0x25ea0 bytes, 0x10000 max)
clang-15: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 15.0.6 (https://github.com/llvm/llvm-project.git 088f33605d8a61ff519c580a71b1dd57d16a03f8)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /softs/local/llvm/15.0.6_gcc83/bin
clang-15: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/Hopps3D-21f42c.cu
clang-15: note: diagnostic msg: /tmp/Hopps3D-baac7b/Hopps3D-sm_80.cu
clang-15: note: diagnostic msg: /tmp/Hopps3D-21f42c.sh
clang-15: note: diagnostic msg: 

********************
```

**Comment by masterleinad** [comment]
Hmm... would you be able to provide a minimal reproducer?

**Comment by dutkalex** [comment]
I managed to reproduce the behavior with this code sample:
```cpp
#include <Kokkos_Core.hpp>

KOKKOS_FUNCTION
constexpr Kokkos::Array<double, 5000> compute_coefs(){
    Kokkos::Array<long double,5> x{ 1., 2., 3., 4., 5. };
    Kokkos::Array<double, 5000> y{};
    for (int i = 0; i < y.size(); ++i)
        y[i] = static_cast<double>(x[i%5]);
    return y;
}

int main()
{
    Kokkos::View<double*> result{ "", 50 };

    Kokkos::parallel_for(
        "Dummy",
        result.size(),
        KOKKOS_LAMBDA(int i){
            static constexpr auto magic_coefs = compute_coefs();
            result(i) = magic_coefs[i];
        }
    );

    auto host_copy = Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace{}, result);

    for (int i = 0; i < result.size(); ++i)
        std::cout << host_copy(i) << '\n';

    return 0;
}
```

It compiles with gcc 11.2 + nvcc 12.0 with the warning, and fails with clang 15.0.6 with the same kind of error message when compiling with the cuda backend + ampere80 architecture

**Comment by pkestene** [comment]
the clang error message is at first a bit surprising: 
looks like the generated assembly requires too much __constant__ memory (i.e. GPU device memory), eventhough the function is "constexpr" so only needed at compile time (on host).
It probably means clang did not manage to "constexpr" your function, at is evaluating it at runtime.

I guess nvcc managed to evaluate it at compile time.

Probably that you code should be best rewritten in cuda, and ask an Nvidia compiler expert ?

**Comment by dutkalex** [comment]
> Can't you move magic_coefs` definition outside of parallel_for ? it should be captured by lambda.

No, this does not work unfortunately and yield the following errors
NVCC: `error: identifier "main   ::magic_coefs" is undefined in device code`
Clang: `error: reference to __host__ variable 'magic_coefs' in __host__ __device__ function`

**Comment by dutkalex** [comment]
I did not remove the `static` when I tried on my machine and I think it's the reason why it did not work. However, I noticed that the `static` was often needed in order to actually get compile time evaluation of the coefficients, and that removing it induced a consequent performance degradation

**Comment by masterleinad** [comment]
> I don't have easy access to your clang version, but on my laptop moving variable outside parallel_for (and removing static) works (clang-17 + ampere86). Adding Kokkos::initialize and finalize, it builds and run ok.

That's also what I suggest. This is probably also the only way to take advantage of `long double` and get more consistent results when executing the code with a host backend and a device backend.

> However, I noticed that the static was often needed in order to actually get compile time evaluation of the coefficients, and that removing it induced a consequent performance degradation.

That really shouldn't be the case. Using a `constexpr` variable forces the compiler to evaluate the right-hand side at compile-time.

**Comment by ajpowelsnl** [comment]
@dutkalex - have we been able to answer all of your questions?

**Comment by dutkalex** [comment]
Yes your answers have been very helpful, thank you! 
I am currently in the process of refactoring my code accordingly, and the only reason why I did not close the issue myself is because I was waiting to make sure first that I could solve all the related issues in my code before (which I am now pretty confident I can since I am almost done)
