### ISSUE TITLE
`Kokkos::Graph`(`HIP`): declaration and definition in the same file leads to `multiple definition of`

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#6623]
**Describe the bug**

This happens since `Kokkos::Graph` was specialized for `HIP` in #6370.

Since member functions of `Kokkos::Impl::GraphImpl<Kokkos::HIP>` are both declared and defined in the same header file (without `inline` keyword), we get tons of `multiple definition of` when compiling our library:
```bash
multiple definition of `Kokkos::Impl::GraphImpl<Kokkos::HIP>::submit()`
...
multiple definition of `Kokkos::Impl::GraphImpl<Kokkos::HIP>::get_execution_space() const`
...
```

I think the problem can be solved by either defining the member functions inside the class (as done in `Kokkos_Cuda_Graph_Impl.hpp`) or by adding the `inline` keyword.

I can make a PR with whatever fix you prefer.

I'm tagging @Rombur @crtrott @masterleinad because they were involved in #6370.

**Comment by dalg24** [comment]
Let's add the `inline` specifier.
Go ahead and open a PR for it.

**Comment by romintomasetti** [comment]
Here you are: #6624.

**Comment by masterleinad** [comment]
> I guess this issue can be considered resolved because #6624 was merged.

but #6627 isn't.

**Comment by romintomasetti** [comment]
Oops, sorry !

**Comment by ajpowelsnl** [comment]
completed
