### ISSUE TITLE
Kokkos(profiling): `finalize` gets called in `Serial`/`OpenMP`/`Threads` finalize leading to premature profiling closure

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#6633]
## Describe the bug

When using `OpenMP` backend, creating a new space instance (*i.e.* different from the default one, *e.g.* with `Kokkos::Experimental::partition_space`) **prematurely ends the profiling session by calling `Kokkos::Profiling::finalize();` once the new space instance is destroyed** (*i.e.* potentially way before the end of the program).

I guess the same reasoning holds for `Serial` and `Threads` backends, for which `Kokkos::Profiling::finalize` is also present in their `finalize`.

For the record, I'm trying to use `Omnitrace` (https://github.com/AMDResearch/omnitrace) but it stops profiling my code once a new space instance gets destroyed, as described above.

## Proposed solution

I don't see any reason why these 3 backends should be responsible for finalizing the profiling, especially that `Kokkos::Profiling::finalize();` is already called in `pre_finalize_internal`.

If you agree @dalg24 @crtrott @masterleinad , maybe the way forward is to remove the call to `Kokkos::Profiling::finalize` from the `finalize` member function of these 3 backends.

## Please include the following for a minimal reproducer

The following code
```c++
#include <iostream>

#include "Kokkos_Core.hpp"

using execution_space = Kokkos::OpenMP;

void test()
{
    std::cout << "Entering my nice code that I want to profile." << std::endl;

    Kokkos::parallel_for(
        "my kernel before partitioning",
        Kokkos::RangePolicy<execution_space>(0, 1),
        KOKKOS_LAMBDA(const int /* osef */) {}
    );

    {
        const auto space = Kokkos::Experimental::partition_space(execution_space{}, 1)[0];

        Kokkos::parallel_for(
            "my kernel after partitioning, before new space instance gets destroyed",
            Kokkos::RangePolicy<execution_space>(0, 1),
            KOKKOS_LAMBDA(const int /* osef */) {}
        );
    }

    Kokkos::parallel_for(
        "my kernel after partitioning, after new space instance gets destroyed",
        Kokkos::RangePolicy<execution_space>(0, 1),
        KOKKOS_LAMBDA(const int /* osef */) {}
    );

    std::cout << "End of my nice code." << std::endl;
}

int main(int argc, char* argv[])
{
    std::cout << "Initializing Kokkos" << std::endl;
    Kokkos::initialize(argc, argv);
    std::cout << "Kokkos successfully initialized" << std::endl;

    test();

    std::cout << "Finalizing Kokkos" << std::endl;
    Kokkos::finalize();
    std::cout << "Kokkos successfully finalized" << std::endl;

    return EXIT_SUCCESS;
}
```
compiled for `OpenMP` leads to
```bash
116: Initializing Kokkos
116: Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
116:   In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
116:   For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
116:   For unit testing set OMP_PROC_BIND=false
116: 
116: KokkosP: Kernel Logger Library Initialized (sequence is 0, version: 20211015)
116: Kokkos successfully initialized
116: Entering my nice code that I want to profile.
116: KokkosP: Executing parallel-for kernel on device 16777217 with unique execution identifier 0
116: KokkosP:     my kernel before partitioning
116: KokkosP: Execution of kernel 0 is completed.
116: KokkosP: Executing parallel-for kernel on device 16777217 with unique execution identifier 1
116: KokkosP:     my kernel after partitioning, before new space instance gets destroyed
116: KokkosP: Execution of kernel 1 is completed.
116: KokkosP: Kokkos library finalization called.
116: End of my nice code.
116: Finalizing Kokkos
116: Kokkos successfully finalized
```
which clearly shows the problem: `Kokkos Tools` gets finalized when the scope ends (*i.e.* when `space` gets destroyed) and the third kernel is not logged.

**Comment by romintomasetti** [comment]
@maartenarnst will be interested.

**Comment by masterleinad** [comment]
I agree. `Kokkos::Profiling::finalize();` should only be called in `pre_finalize_internal()`.

**Comment by romintomasetti** [comment]
@masterleinad Here you are: #6635 :wink:
