### ISSUE TITLE
How to add a self-defined backend for this project

### ISSUE THREAD

**Issue by anyin233** [kokkos/kokkos#6637]
I'm now trying to develop a new backend for this project, is there are any document about how to create a custom backend for this project?  
Currently I have created headers and sources in `core/src` directory, and implemented some basic functions for `ExecutionSpace`.

**Comment by masterleinad** [comment]
You would try getting the tests in `core/unit_test/incremental` running one after the other, i.e., start with the executions space class, look at (host) atomics, add memory spaces, then proceed with parallel constructs.

**Comment by ajpowelsnl** [comment]
Is there anything else we can help with, @anyin233?  If not, may we close the issue?

**Comment by anyin233** [comment]
> Is there anything else we can help with, @anyin233? If not, may we close the issue?

Currently there is no problem.
