### ISSUE TITLE
Use of std::setprecision without including iomanip in TestStdAlgorithms[X]Scan.cpp

### ISSUE THREAD

**Issue by gregvw** [kokkos/kokkos#6644]
The following test files in `kokkos/algorithms/unit_tests` have calls to `std::setprecision`, but there is no `#include<iomanip>` in any of them or in `TestStdAlgorithmsCommon.hpp`, which they include.

    TestStdAlgorithmsExclusiveScan.cpp
    TestStdAlgorithmsInclusiveScan.cpp
    TestStdAlgorithmsTransformExclusiveScan.cpp
    TestStdAlgorithmsTransformInclusiveScan.cpp

**Comment by dalg24** [comment]
Would you be willing to open a PR (against develop) to fix this?

**Comment by fnrizzi** [comment]
https://github.com/kokkos/kokkos/pull/6645 fixes this
