### ISSUE TITLE
Question: performance in AMD MI210 vs NVIDIA A100 and V100

### ISSUE THREAD

**Issue by JosefRuzicka** [kokkos/kokkos#6657]
Hello I'm running a simulation that was originally programmed in OpenMP to offload particle position to the GPU and simulate their movement without taking into account their collitions, so all particles are independent and only take into account their last step.

I adapted the particles to be stored in Kokkos Views in CudaUVMSpace for the NVIDIA A100 and V100 GPUs and HIPManagedSpace for the MI210 GPU. The particles are updated in each step with a Kokkos parallel for.

The programs work fine, and the NVIDIA GPUs behave similarly between them, with the Kokkos version showing longer execution times than the  base OpenMP version. However, The opposite behavior occurs on the AMD MI210 GPU, with Kokkos taking less time to finish the simulation than the base OpenMP version.

Have you got any insight on how I could explain this difference in behaviour?

I'm adding a plot to visualize my results.

![BS-SOLCTRA-GPU (3)](https://github.com/kokkos/kokkos/assets/63564928/826d474a-cd3a-47de-b6ec-2d1b2f67aa62)

**Comment by crtrott** [comment]
Does the original OpenMP offload code also use managed memory? Or do you explicitly move memory via data clauses? Generally I would NOT expect any OpenMP offload code to be faster than native Kokkos CUDA code, unless something very different is going on - for example you use UVM in the Kokkos CUDA but you don't for the OpenMP code - Managed Memory (depending on your access patterns) can incur a very significant performance cost. However it could be that the OpenMP offload code on AMD uses also managed data and thus removes that relative penalty.

**Comment by JosefRuzicka** [comment]
The base OpenMP is not using Managed Memory, I only use Managed Memory in the Kokkos versions, so I guess that explains the difference in the execution durations I obtained with NVIDIA, however the OpenMP code is the same with AMD but the results are opposite to NVIDIA, unless it is somehow deciding to use Managed Memory implicitly, but I am using data clauses to move data.

**Comment by ajpowelsnl** [comment]
@JosefRuzicka - have we been able to answer your question / provide the needed help?  If so, may we close the issue?  If not, please just let us know how we can help further.

**Comment by JosefRuzicka** [comment]
Hi, Im going to program the simulations so that they use the same memory space, I have to study a bit more about whats going on because I thought I was not using Managed Memory with OpenMP since im using the pragma omp target data map clause, however the nvprof profiler writes some info about using Managed Memory, so please give me some time and I will get back to you when I have studied this a bit further, thank you!

**Comment by JosefRuzicka** [comment]
Hi! Sorry for taking such a long time. For the measurement I was making the memory space didn't seem to make a big difference, however! Back then I was using Kokkos 3.7 or something around that and now I updated to the latest version (4.3) and Kokkos is now outperforming OpenMP in my experiments so... I don't know what changed in the versions but that's solved now.

I suppose we can close the issue now. Thanks for your time and patience
