### ISSUE TITLE
Remove impl/Kokkos_Synchronic_*

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#666]
The synchronic functionality has been withdrawn from consideration for C++20.
Remove impl/Kokkos_Synchronic_*

FYI: Replacement proposal under development.  As of 3/4/17 not yet ready for experimentation:  https://github.com/ogiroux/semaphore

**Comment by crtrott** [comment]
Woohoo, this thing only brought pain anyway ....

**Comment by crtrott** [comment]
I am on this. This might make the PGI test clean.
