### ISSUE TITLE
initialize Kokkos::View of class 

### ISSUE THREAD

**Issue by liyujin1999** [kokkos/kokkos#6663]
Hello everyone, I am Kokkos beginner, have some questions to ask you, I am using Kokkos to do transplantation, the problem is described as follows:
	xedefect.h  Header file:
```
class XeDefect
	{
	
		public:
				class ReactionPair
				{
					public:              
						double a0, a1;
					
					KOKKOS_INLINE_FUNCTION
					ReactionPair(){}
					
					KOKKOS_INLINE_FUNCTION
					~ReactionPair(){}
				};
			int id;
			Kokkos::View<double*, Kokkos::CudaSpace> diffusionCoefficient;
			Kokkos::View<ReactionPair*, Kokkos::CudaSpace> reactionPairs;
		
		KOKKOS_INLINE_FUNCTION
		XeDefect(){}
		
		KOKKOS_INLINE_FUNCTION
		~XeDefect(){}
	}


int main()
	{
		
		//First I want to make sure that I can create the View variable of a custom class in the following way (is this line of code correct)?
		Kokkos::View<XeDefect*, Kokkos::CudaSpace> xedefects("xes", 10);
		
		
		//If the above line of code is okay, how do I assign a value to every variable in the list of xedefects? This includes sizing and assigning values to diffusionCoefficient and reactionPairs.

	}
```

**Comment by dalg24** [comment]
The current design makes a view of a class that contains a view which [generally something we discourage](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/View.html?highlight=view+views#can-i-make-a-view-of-views).

Does the number of diffusion coefficients  and reaction pairs vary for different Xe defects?
Do you know these numbers at compile time?

**Comment by liyujin1999** [comment]
Yes, the size of diffusion coefficients and reaction pairs in each instance of xedefects is different. I also have a set of host side data structures, and their sizes are specified based on the corresponding size of the host side data. I don't know how to allocate memory for diffusion coefficients and reaction pairs now.

**Comment by liyujin1999** [comment]
@dalg24 Can you give me some advice? Thanks in advance

**Comment by dalg24** [comment]
Let `n` be the number of Xe defects.
Allocate and zero-initialize `offsets` view of integers of size `n+1`  and fill with the reaction pair count per Xe defect (I assume that the number of coefficients and reaction pair per Xe defect is the same).  Then compute the exclusive prefix sum.  Let `m` be `offsets(n)` which the total number of reaction pairs and coefficients.
Allocate `m` reaction pairs and `m` coefficients.   For any Xe defect `i`, index into `offsets(i)` to `offsets(i+1)` to get the reaction pairs and coefficients.
```C++
Kokkos::View<int*> offsets("offsets", n+1);
Kokkos::parallel_for(n, KOKKOS_LAMBDA(int i) { offsets(i) = <NUMBER OF DIFFUSION COEFFS/REACTION PAIRS>; });
int m;
Kokkos::parallel_scan(n, KOKKOS_LAMBDA(int i, int& partial_sum, bool is_final_pass) {
    auto const offsets_i = offsets(i);
    if (is_final_pass)
      offsets(i) = partial_sum;
    partial_sum += offsets_i; }, m
);
Kokkos::View<double*> diffusion_coefficients("diffusion_coeffs", m);
Kokkos::View<ReactionPair*> reaction_pairs("reaction_pairs", m);
Kokkos::parallel_for(n, KOKKOS_LAMBDA(int i) {
  // process Xe defect "i"
  for (int j = offsets(i); j < offsets(i+1); ++j) {
    <COMPUTE THINGS>(diffusion_coefficients(j), reaction_pairs(j));
  }
});

**Comment by liyujin1999** [comment]
@dalg24 That's a good idea. I have another idea. Please help me check if it's correct.

```
auto h_tmp_xe = Kokkos::create_mirror_view(xedefects);
for(int i=0; i<xedefects.extent(0); i++;)
{
	h_tmp_xe(i).init(m, n);//The values of m and n are different every time
}
Kokkos::deep_copy(dm->xedefects, h_tmp_xe);

xedefect.cpp:
void init(int size1, int size2){
        reactionPairs = Kokkos::View<ReactionPair*, Kokkos::CudaSpace>("rps", size1);               
        diffusionCoefficient = Kokkos::View<double*, Kokkos::CudaSpace>("diff", size2);
}
```

Does this code properly allocate memory space on the device to either reactionPairs and diffusionCoefficient in each Xe defect?

In this way, I can normally access either reactionPairs or diffusionCoefficient,For example, my following code is normal:
```
//By default, parallel for is executed on the device
Kokkos::parallel_for(10,KOKKOS_LAMBDA(const int& i) {
	xedefects(0).diffusionCoefficient(i) = 5;//Normal assignment, no errors
});
```

**Comment by dalg24** [comment]
> my following code is normal

If you want to learn how to write code that runs portably across various architectures, you need to consider that "normal" might end up looking differently from what you have done before.

Also please keep in mind that this repository is intended for development and reporting bugs.

**Comment by ajpowelsnl** [comment]
@liyujin1999 - can we help you with anything else?  BTW, for future questions, feel free to join and submit to our [Kokkos Slack Channel (under Outreach tab)](https://kokkos.github.io/).
