### ISSUE TITLE
Implement sort_by_key

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#6668]
This is an issue to match the discussion at the Kokkos User Group meeting. The motivating slides are attached.

The hope would be that Kokkos would implement the `sort_by_key`, which would dispatch to Thrust/rocThrust/oneDPL.

ArborX currently implements some version of it [here](https://github.com/arborx/ArborX/blob/82d60e8f0b0281eaed5665d4236a486f95d18eb9/src/kokkos_ext/ArborX_DetailsKokkosExtSort.hpp), but it will need to be hardened to be included in Kokkos.

[20231212-kug23-lightning.pdf](https://github.com/kokkos/kokkos/files/13665384/20231212-kug23-lightning.pdf)

**Comment by aprokop** [comment]
`sort_by_key` is the most pressing kernel. Other segmented kernels are available in Thrust also supports other segmented kernels (see [here](https://thrust.github.io/doc/namespacethrust.html)): `{exclusive,inclusive}_scan_by_key`, `merge_by_key`, `reduce_by_key`, `set_{difference,intersection,symmetric_difference,union}_by_key`, `stable_sort_by_key`.

**Comment by masterleinad** [comment]
Current `sort` interfaces in `Kokkos` look like
```C++
template <class ExecutionSpace, class DataType, class... Properties>
void sort([[maybe_unused]] const ExecutionSpace& exec,
          const Kokkos::View<DataType, Properties...>& view);
template <class DataType, class... Properties>
void sort(const Kokkos::View<DataType, Properties...>& view);

template <class ExecutionSpace, class ComparatorType, class DataType,
          class... Properties>
void sort([[maybe_unused]] const ExecutionSpace& exec,
          const Kokkos::View<DataType, Properties...>& view,
          const ComparatorType& comparator);
template <class ComparatorType, class DataType, class... Properties>
void sort(const Kokkos::View<DataType, Properties...>& view,
          const ComparatorType& comparator);

template <class ExecutionSpace, class ViewType>
std::enable_if_t<Kokkos::is_execution_space<ExecutionSpace>::value> sort(
    const ExecutionSpace& exec, ViewType view, size_t const begin,
    size_t const end);
template <class ViewType>
void sort(ViewType view, size_t const begin, size_t const end);
```
and `ArborX` has
```C++
template <typename ExecutionSpace, typename Keys, typename Values>
void sortByKey(ExecutionSpace const &space, Keys &keys, Values &values);
```
where `thrust` has
```C++
sort_by_key 	( 	const thrust::detail::execution_policy_base< DerivedPolicy > &  	exec,
		RandomAccessIterator1  	keys_first,
		RandomAccessIterator1  	keys_last,
		RandomAccessIterator2  	values_first 
	)
void thrust::sort_by_key 	( 	RandomAccessIterator1  	keys_first,
		RandomAccessIterator1  	keys_last,
		RandomAccessIterator2  	values_first 
	) 	
__host__ __device__ void thrust::sort_by_key 	( 	const thrust::detail::execution_policy_base< DerivedPolicy > &  	exec,
		RandomAccessIterator1  	keys_first,
		RandomAccessIterator1  	keys_last,
		RandomAccessIterator2  	values_first,
		StrictWeakOrdering  	comp 
	) 	
void thrust::sort_by_key 	( 	RandomAccessIterator1  	keys_first,
		RandomAccessIterator1  	keys_last,
		RandomAccessIterator2  	values_first,
		StrictWeakOrdering  	comp 
	)
```
`oneDPL` has
```
sort_by_key(_ExecutionPolicy&& __exec, _RandomAccessIterator1 __keys_first, _RandomAccessIterator1 __keys_last,
            _RandomAccessIterator2 __values_first)
```

Given these observations, it looks like it makes sense to provide
```C++
template <class ExecutionSpace, class KeyType, class... KeyProperties, class ValueType, class... ValueProperties>
void sort_by_key(const ExecutionSpace& exec,
          const Kokkos::View<const KeyType, KeyProperties...>& keys, const Kokkos::View<ValueType, ValueProperties...>& values);

template <class ExecutionSpace, class ComparatorType, class KeyType,
          class... KeyProperties, class ValueType, class... ValueProperties>
void sort(const ExecutionSpace& exec,
          const Kokkos::View<const KeyType, KeyProperties...>& keys,
          const Kokkos::View<ValueType, ValueProperties...>& values)
          const ComparatorType& comparator);
```
I don't think it's too much to ask to create a default execution space instance if the user doesn't have one. Also, restricting the range can be achieved by taking subviews.

**Comment by aprokop** [comment]
> Given these observations, it looks like it makes sense to provide

May also want to have a variant with iterators.

**Comment by masterleinad** [comment]
> May also want to have a variant with iterators.

What benefit would that have over going through `Views`?

**Comment by aprokop** [comment]
> What benefit would that have over going through `Views`?

It's in addition to, not instead of. Following `std` algorithms, and make it possible to run within a kernel (of course, without delegation). Not a priority, but could be useful.

**Comment by stanmoore1** [comment]
We also use Kokkos sort in LAMMPS, see https://github.com/lammps/lammps/blob/develop/src/KOKKOS/atom_kokkos.cpp#L252-L274. We want to sort many views based on the same key, e.g. see https://github.com/lammps/lammps/blob/develop/src/KOKKOS/atom_vec_full_kokkos.cpp#L236-L265. Currently we have to use `BinSort` because other methods don't have `create_permute_vector`. So adding `sort_by_key` with vendor optimized routines would be really helpful in LAMMPS.

Here is another use of Kokkos sort in LAMMPS:

https://github.com/lammps/lammps/blob/develop/src/KOKKOS/atom_map_kokkos.cpp#L144-L267

It would also be nice if multiple views could be sorted at the same time with the same key to reduce kernel launch latency, i.e. in a batched mode, so we don't have code like this:
```
  Sorter.sort(LMPDeviceType(), d_tag);
  Sorter.sort(LMPDeviceType(), d_type);
  Sorter.sort(LMPDeviceType(), d_mask);
  Sorter.sort(LMPDeviceType(), d_image);
  Sorter.sort(LMPDeviceType(), d_x);
  Sorter.sort(LMPDeviceType(), d_v);
  Sorter.sort(LMPDeviceType(), d_q);
  Sorter.sort(LMPDeviceType(), d_molecule);
  Sorter.sort(LMPDeviceType(), d_num_bond);
  Sorter.sort(LMPDeviceType(), d_bond_type);
  Sorter.sort(LMPDeviceType(), d_bond_atom);
  Sorter.sort(LMPDeviceType(), d_nspecial);
  Sorter.sort(LMPDeviceType(), d_special);
  Sorter.sort(LMPDeviceType(), d_num_angle);
  Sorter.sort(LMPDeviceType(), d_angle_type);
  Sorter.sort(LMPDeviceType(), d_angle_atom1);
  Sorter.sort(LMPDeviceType(), d_angle_atom2);
  Sorter.sort(LMPDeviceType(), d_angle_atom3);
  Sorter.sort(LMPDeviceType(), d_num_dihedral);
  Sorter.sort(LMPDeviceType(), d_dihedral_type);
  Sorter.sort(LMPDeviceType(), d_dihedral_atom1);
  Sorter.sort(LMPDeviceType(), d_dihedral_atom2);
  Sorter.sort(LMPDeviceType(), d_dihedral_atom3);
  Sorter.sort(LMPDeviceType(), d_dihedral_atom4);
  Sorter.sort(LMPDeviceType(), d_num_improper);
  Sorter.sort(LMPDeviceType(), d_improper_type);
  Sorter.sort(LMPDeviceType(), d_improper_atom1);
  Sorter.sort(LMPDeviceType(), d_improper_atom2);
  Sorter.sort(LMPDeviceType(), d_improper_atom3);
  Sorter.sort(LMPDeviceType(), d_improper_atom4);
```

**Comment by masterleinad** [comment]
@stanmoore1 Do you need to the permutation vector or are you fine if you can just pass multiple Views to `sort_by_key`?

**Comment by stanmoore1** [comment]
We only need to sort multiple views by key without a lot of overhead, we don't need the actual permutation vector per se.

**Comment by stanmoore1** [comment]
One other thing that would be really useful for LAMMPS is the ability to sort on one key, then sort duplicate values on another criteria. I don't think that is currently possible with Kokkos sort?

**Comment by masterleinad** [comment]
> One other thing that would be really useful for LAMMPS is the ability to sort by key, then sort duplicate values on another criteria, i.e. an outer and inner sort. I don't think that is currently possible with Kokkos sort? This is like in Excel where you can sort by one column, then reorder duplicates by another column...

Not directly. You can sort, then scan to find bin boundaries and then run a bunch of sorts on all the bins identified.

I guess specifying a comparator in `sort_by_key` wouldn't be quite enough to achieve this in one call since you actually need the index? Is it feasible to have all the criteria you want to sort by combined in `keys`? If that's the case a custom comparator should do.

**Comment by aprokop** [comment]
> One other thing that would be really useful for LAMMPS is the ability to sort by key, then sort duplicate values on another criteria, i.e. an outer and inner sort.

I think this is called segmented sort.

**Comment by stanmoore1** [comment]
Can they keys be a struct with two values, one for inner and one for outer? They key for the outer sort is global atom id, stored in a 64 bit integer for large systems. Then I want to "inner" sort duplicate atoms (i.e. ghost atoms) by local atom id as well, which is a 32 bit integer. But if we try to commingle these into a single comparator, then I don't think we have enough precision for an exascale computation of billions to trillions of atoms. Maybe this would be a better discussion for Slack.

**Comment by aprokop** [comment]
We have a similar problem in ArborX. So far, we are bypassing it by using two 32-bit ints and converting them to a 64-bit for sorting. Not sure how long we'll be able to do that.

**Comment by masterleinad** [comment]
@stanmoore1 I was imagining something like
```C++
struct KeyValues {
  int32_t local_atomi_id;
  int64_t global_atom_id;
};
```
with a custom comparator like
```C++
[](const KeyValues& a, const KeyValues& b) {
  if (a.global_atom_id < b.global_atom_id)
    return true;
  if (b.global_atom_id < a.global_atom_id)
    return false;
  return a.local_atom_id < b.local_atom_id; 
}
```

**Comment by stanmoore1** [comment]
Yes that could work well. I thought you meant flattening like `key = global_atom_id*num_local_atom + local_atom_id`

**Comment by masterleinad** [comment]
OK. With further input, it seems doing the following would be sensible for `sort_by_key`
```C++
template <class ExecutionSpace, class KeyType, class... KeyProperties, class... Values>
void sort_by_key(const ExecutionSpace& exec,
          const Kokkos::View<const KeyType, KeyProperties...>& keys, const Values&... values);

template <class ExecutionSpace, class ComparatorType, class KeyType,
          class... KeyProperties, class... Values>
void sort_by_key(const ExecutionSpace& exec,
          const Kokkos::View<const KeyType, KeyProperties...>& keys,
          const ComparatorType& comparator,
          const Values&... values);
```

**Comment by stanmoore1** [comment]
@masterleinad will this support sorting multiple views (e.g. 30) in an efficient way without needing to recreate the permutation vector every time? Or maybe the vendor provided sort is so fast it doesn't matter as much? Batched mode with a single kernel launch would be nice too, though maybe beyond the scope of an initial implementation?

**Comment by stanmoore1** [comment]
Another pain point with `BinSort` is that it allocates memory and initializes views (equals another CUDA kernel launch) in the constructor, so using a local copy that goes out of scope every time it was called led to significant overhead. I hacked the code to avoid this but it isn't pretty: https://github.com/lammps/lammps/blob/develop/src/KOKKOS/atom_map_kokkos.cpp#L184-L196. It would be nice if there was some way to overallocate the internal buffer size for Kokkos sorting and only reallocate when exceeded.

**Comment by aprokop** [comment]
> @stanmoore1 I was imagining something like

I'm not sure about the performance of the custom operators. I think even for pod int types, using them is much slower than not. 

> will this support sorting multiple views (e.g. 30) in an efficient way without needing to recreate the permutation vector every time?

You don't need to recreate permutation vector, I think. You just do `permute = iota(n); sort_by_key(values1, permute);`, and then do `for i = 2...n; do apply_permutation(permute, values_i); done`.

**Comment by masterleinad** [comment]
We mostly wanted to discuss a suitable interface for a top-level `sort_by_key` first. I'm not sure if we need to allow some kind of cache. In the case that we would call one of the vendor-provided versions mentioned above, I would directly call their `sort_by_key` implementation if the number of Views to be sorted is small and allocate a permutation vector for a larger number of Views (by calling `sort`) so that the allocation cost would hopefully be amortized by being able to only sort once and then apply the permutation vector on all Views on one kernel call. I guess the fallback would for the moment still use `BinSort` resp. `std::sort`.

**Comment by stanmoore1** [comment]
>You don't need to recreate permutation vector, I think. You just do permute = iota(n); sort_by_key(values1, permute);, and then do for i = 2...n; do apply_permutation(permute, values_i); done.

I think you also need to inverse the permutation vector? I would expect Kokkos to take care of this, like in `BinSort`, ideally.

**Comment by aprokop** [comment]
> I think you also need to inverse the permutation vector?

You don't. This is the permutation vector you want. We do this in ArborX. You may want to looks at this code https://github.com/arborx/ArborX/blob/9253614aab442391a51c0fc7cb4ed6938ea36730/src/details/ArborX_DetailsDistributedTreeUtils.hpp#L99-L128 in ArborX that can do almost what you want (sort multiple views). It is easy to modify it to produce a permutation from the first view.

> I would expect Kokkos to take care of this, like in `BinSort`, ideally.

Not really imho. I would argue that Kokkos should not carry a hidden state just in case a user wants to use it. Instead, the interactions should be explicit.

**Comment by stanmoore1** [comment]
>Not really imho. I would argue that Kokkos should not carry a hidden state just in case a user wants to use it. Instead, the interactions should be explicit.

Well then we'll just have to agree to disagree :) I think the new code should at least carry over the same functionality of `BinSort` as the base case.

**Comment by aprokop** [comment]
I assigned it to myself. I'm going to implement a basic version in the next couple weeks.

**Comment by stanmoore1** [comment]
@aprokop I thought about this more and in some ways a simpler implementation (e.g. produce a permutation from the first view as you suggested) is advantageous because I can control the buffer allocation and tailor to my application. I had trouble with `Kokkos::BinSort` allocating memory too often. So I support getting https://github.com/kokkos/kokkos/pull/6801 merged ASAP.

**Comment by dalg24** [comment]
I will close as we merged Andrey's PR adding the `Experimental::sort_by_key` algorithm.  It will be in the upcoming 4.3 release.
Please open a new issue if you have feedback, for instance appetite for a variadic overload `Experimental::sort_by_key(exec, keys, values1, values2, ...)` or `stable_sort[_by_key]`.
