### ISSUE TITLE
Kokkos compiling with an manually added AMD (gpu) arch is failing (but should work)

### ISSUE THREAD

**Issue by jjellio** [kokkos/kokkos#6669]
**Describe the bug**

I'm trying to stand up a build for the recently added MI300 architecture, but I need to use a slightly different variant of the arch flag (gfx940 rather than gfx942). The build goes fine, if I use the existing `AMD_GFX942` arch, e.g.,
https://github.com/kokkos/kokkos/blob/62855dcf1845cc87c19a981db0067c93b5254bb3/cmake/kokkos_arch.cmake#L98

I edited `kokkos_arch.cmake` and added my own AMD_GFX940 (replicating the lines for `GFX942`).

Any chance someone could give me a tip on how to patch Kokkos so I could natively use gfx940? As is, a few of us are just configuring for Mi250x or 942, then doing find/replace on our build files to twiddle offload-arch to 940 rather than 942.

```
[1/3870] Building CXX object packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/HIP/Kokkos_HIP.cpp.o
FAILED: packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/HIP/Kokkos_HIP.cpp.o 
/opt/cray/pe/craype/2.7.23/bin/CC -DKOKKOS_DEPENDENCE -I/tmp/jjellio/build/amd-5.7.1_prgenv-amd_rocm-5.7.1_mpich-8.1.27_pure-amd_hip_amd-inlall-NOfunc-gfx940_serial_atdm_complex_opt-g_cxx17_libonly_static_rdc/trilinos -I/tmp/jjellio/build/amd-5.7.1_prgenv-amd_rocm-5.7.1_mpich-8.1.27_pure-amd_hip_amd-inlall-NOfunc-gfx940_serial_atdm_complex_opt-g_cxx17_libonly_static_rdc/trilinos/packages/kokkos/core/src -I/g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src -I/tmp/jjellio/build/amd-5.7.1_prgenv-amd_rocm-5.7.1_mpich-8.1.27_pure-amd_hip_amd-inlall-NOfunc-gfx940_serial_atdm_complex_opt-g_cxx17_libonly_static_rdc/trilinos/packages/kokkos -I/g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src/../../tpls/desul/include -x hip -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -g -march=znver3 -mtune=znver3 -fgpu-rdc -xhip --rocm-path=/opt/rocm-5.7.1 --offload-arch=gfx940  -O3 -DNDEBUG -std=c++17 -march=znver3 -mtune=znver3 -fgpu-rdc -xhip --rocm-path=/opt/rocm-5.7.1 --offload-arch=gfx940 -MD -MT packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/HIP/Kokkos_HIP.cpp.o -MF packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/HIP/Kokkos_HIP.cpp.o.d -o packages/kokkos/core/src/CMakeFiles/kokkoscore.dir/HIP/Kokkos_HIP.cpp.o -c /g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP.cpp
clang++: warning: argument unused during compilation: '-L/opt/rocm-5.7.1/lib' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/opt/rocm-5.7.1/lib64' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/opt/rocm-5.7.1/llvm/lib' [-Wunused-command-line-argument]
/g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP.cpp:59:36: error: no member named 'WarpSize' in 'Kokkos::Impl::HIPTraits'; did you mean 'warpSize'?
      hipProp.maxThreadsPerBlock / Impl::HIPTraits::WarpSize;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
                                   warpSize
/opt/rocm-5.7.1/include/hip/amd_detail/amd_warp_functions.h:86:22: note: 'warpSize' declared here
static constexpr int warpSize = __AMDGCN_WAVEFRONT_SIZE;
                     ^
/g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP.cpp:60:7: error: no member named 'WarpSize' in 'Kokkos::Impl::HIPTraits'; did you mean 'warpSize'?
  if (Impl::HIPTraits::WarpSize < Impl::HIPInternal::m_maxWarpCount) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~
      warpSize
/opt/rocm-5.7.1/include/hip/amd_detail/amd_warp_functions.h:86:22: note: 'warpSize' declared here
static constexpr int warpSize = __AMDGCN_WAVEFRONT_SIZE;
                     ^
/g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP.cpp:61:41: error: no member named 'WarpSize' in 'Kokkos::Impl::HIPTraits'; did you mean 'warpSize'?
    Impl::HIPInternal::m_maxWarpCount = Impl::HIPTraits::WarpSize;
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
                                        warpSize
/opt/rocm-5.7.1/include/hip/amd_detail/amd_warp_functions.h:86:22: note: 'warpSize' declared here
static constexpr int warpSize = __AMDGCN_WAVEFRONT_SIZE;
                     ^
/g/g20/jjellio/src/github/Trilinos/packages/kokkos/core/src/HIP/Kokkos_HIP.cpp:76:44: error: no member named 'WarpSize' in 'Kokkos::Impl::HIPTraits'; did you mean 'warpSize'?
      Impl::HIPInternal::m_maxWavesPerCU * Impl::HIPTraits::WarpSize;
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
                                           warpSize
/opt/rocm-5.7.1/include/hip/amd_detail/amd_warp_functions.h:86:22: note: 'warpSize' declared here
static constexpr int warpSize = __AMDGCN_WAVEFRONT_SIZE;
                     ^
4 errors generated when compiling for gfx940.
```

**Please include the following for a minimal reproducer**
The reproducer is
Edit:
https://github.com/kokkos/kokkos/blob/62855dcf1845cc87c19a981db0067c93b5254bb3/cmake/kokkos_arch.cmake#L98

Change to:
```
LIST(APPEND SUPPORTED_AMD_GPUS       MI300 MI300)
LIST(APPEND SUPPORTED_AMD_ARCHS      AMD_GFX942 AMD_GFX940)
LIST(APPEND CORRESPONDING_AMD_FLAGS  gfx942 gfx940)
```

Then configure and build w/that.  I could be useful to have this arch in Kokkos, but it also seems reasonable to expect folks to patch for 940.

**Comment by rbberger** [comment]
Did you try https://github.com/kokkos/kokkos/pull/6671?

**Comment by dalg24** [comment]
I have seen a similar error before.  It means the AMD GPU arch is not recognized.
https://github.com/kokkos/kokkos/blob/cedbf56f64e3cb1e6f11e934c01bff7b1c09964b/core/src/HIP/Kokkos_HIP_Instance.hpp#L32-L41

@Rombur how comes we don't error at configure time?  What about compile time? I expect we'd catch something like that with CUDA.  https://github.com/kokkos/kokkos/blob/cedbf56f64e3cb1e6f11e934c01bff7b1c09964b/core/src/impl/Kokkos_NvidiaGpuArchitectures.hpp#L52-L55

**Comment by Rombur** [comment]
> how comes we don't error at configure time? 

Because @jjellio modified the build system to add gfx940 as a supported architecture.

**Comment by jjellio** [comment]
I didn't see the PR  #6671 - but it looks like it should work.

In both cases this is an intermediate arch flag before `gfx942`. It should poof / not hang around.  I've not heard any word on using `gfx941`, but 940 is currently being hammered by teams.  If Richard Berger's PR is sufficient - would it be okay to merge it into Develop with some type of marking so that is never gets put in a release and instead is culled in maybe 6 months?

**Comment by jjellio** [comment]
Oh, and feel free to shoot me an email jjellio / sandia.gov and I can elaborate on where this is coming from.

**Comment by dalg24** [comment]
@jjellio see https://github.com/kokkos/kokkos/issues/6669#issuecomment-1855142675

We will add support shortly. Some more changes were needed to the source code. We will also improve the compile-time diagnostic (for our friends using generated makefiles).
