### ISSUE TITLE
CMake build: _OPENMP macro undefined

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#667]
The cmake build of Kokkos does not check that the compiler supports OpenMP, as it is instead done in Trilinos. The lookup via FIND_PACKAGE in trilinos, is then followed by the setup of the proper flags, including _OPENMP, which Kokkos uses to turn on the compilation of OpenMP code. In case the user enables OpenMP in kokkos via Kokkos_ENABLE_OpenMP but the macro _OPENMP is not defined, the compiler issues the error

error: #error "You enabled Kokkos OpenMP support without enabling OpenMP in the compiler!"

I copiedy and pasted the cmake snippet that finds OpenMP from trilinos (in cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake), and that fixed the problem (_OPENMP was correctly defined).

There is always the possiblity that I misunderstood something about the cmake build of kokkos. From where I stand, though, I think it is necessary to add a snipped of cmake code (that search for OpenMP support in the compiler, and sets the proper compiler flags) to the main CMakeLists.txt.

**Comment by gmackey** [comment]
@bartgol Are you trying to build a project using Kokkos with CMake but not using Trilinos?

The current CMake files included with Kokkos are really designed only to work with Trilinos.  To try to support non-Trilinos pure CMake builds, the cmake/tribits.cmake file was added.  However, this still weds a pure CMake build to exactly what Trilinos requires.  I am in the process of writing a pure CMake build file for Kokkos that makes things much, much better (no Tribits and no requirements by Trilinos) for building a project with CMake that uses Kokkos.

@bartgol You issued another ticket recently #654 that also deals with the Kokkos CMake build.

If both of these issues are related to trying to use CMake to build a project without using Kokkos, please wait a short time, and that will be added to kokkos.

**Comment by bartgol** [comment]
@gmackey 

Yes, I am building kokkos without trilinos. I figured that the tribits.cmake file was a workaround, to have the package building correctly without relying on the whole trilinos' tribits system.

I found some workaround/fixes for the (several) issues I posted here. Of course, I understand it will take some time for you guys to make the build system work correctly. I just thought I gave you a heads up, in case some issue was not yet known to you guys.

P.S: I opened a few issues related to CMake. I figured it was cleaner to have a single issue per each problem, rather than listing all of them in a single one. I hope this was ok. Thank you for the quick reply!

**Comment by crtrott** [comment]
Hi

yeah openening multiple issues is fine. We can have a master issue to link to them. It gives us a couple of things to check for that it actually works what Greg is building. As of right now CMake is not an officially supported build system (tribits is). But as you heard we are actively working on changing that and hope to have something in next few weeks which will work for everybody.

**Comment by pkestene** [comment]
For what it's worth, if you have an existing cmake-based application, and
try to use Kokkos inside, you can also simply add to your top-level
CMakeLists.txt

# set path to file kokkos.cmake (which is generated in a regular kokkos
build, along makefile.kokkos)
set(CMAKE_MODULE_PATH "$ENV{KOKKOS_PATH}" ${CMAKE_MODULE_PATH})
include(kokkos)
set(CMAKE_CXX_FLAGS  "${KOKKOS_CPPFLAGS} ${KOKKOS_CXXFLAGS}
${CMAKE_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS  "${KOKKOS_LDFLAGS} ${CMAKE_EXE_LINKER_FLAGS}")

assuming you have already built and installed kokkos to KOKKOS_PATH, where
is located kokkos.cmake containing custom variables KOKKOS_CPPFLAGS, ...

That said, it would be great to have a proper tribits integration i think.

**Comment by gmackey** [comment]
@pkestene Thanks for adding the cmake support for using an already installed Kokkos library!  :)  What I'm working on is the ability to build Kokkos as part of your project using CMake.  These are two different usage scenarios supported for building Kokkos using makefiles which are now going to be supported using pure CMake as well.

**Comment by gmackey** [comment]
@bartgol The new pure cmake build version I'm working on addresses this issue.  It finds the openmp library and enables it if the user requests it.  In general, all of the flags required to compile the kokkos library will be transitively added to targets that link against the library.

**Comment by gmackey** [comment]
@bartgol I have a decently tested version of the new CMake build process for building Kokkos as part of another CMake project checked into my fork of Kokkos at https://github.com/gmackey/kokkos.git.  It's in the branch 'cmake'.  There's an example of how to build in example/cmake_build/.  When you get a chance, would you mind testing it out?

**Comment by bartgol** [comment]
@gmackey Thanks! I will try it out later this week (I hope).

**Comment by bartgol** [comment]
@gmackey Sorry for the almost 2 months delay. I finally downloaded the branch. I have two issues (one with fix):

- cmake complains at line 5 of cmake/kokkos.cmake, since CMAKE_MINIMUM_REQUIRED_VERSION is not yet defined. It is defined by cmake_minimum_required a few lines below. However, putting that line at the beginning of the file does not work, since cmake_minimum_required must be in a CMakeLists.txt file. I fixed it by putting the command in the main CMakeLists.txt right before INCLUDE(cmake/kokkos.cmake).

- when trying to install I get "no rule to make target install". I set CMAKE_INSTALL_PREFIX as usual in my config script, which used to be enough with master. Perhaps removing the include for tribits.cmake removed also the lines that setup the install target?

**Comment by dsunder** [comment]
@bartgol is this still an issue for you?

**Comment by ibaned** [comment]
Closing for lack of response

**Comment by NikBomb** [comment]
Hi, today I encountered the same issue as described by @bartgol , building from Trilinos master Branch.
