### ISSUE TITLE
Cmake build: wrong include install directory

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#668]
In the files core/src/CMakeLists.txt and container/src/CMakeLists.txt, the following variable is set:

SET(TRILINOS_INCDIR ${CMAKE_INSTALL_PREFIX}/${${PROJECT_NAME}_INSTALL_INCLUDE_DIR})

Besides mentioning trilinos (which does not belong here, since it's a standalone kokkos package), this is also buggy: the variable ${PROJECT_NAME}_INSTALL_INCLUDE_DIR is never set, which causes most of the files to be installed not in install-dir/include/ but directly in install-dir/. The only exceptions are the files in the HEADERS_PUBLIC variable, which are correctly installed by the TRIBITS_ADD_LIBRARY function. This not only generates a "less structures" installation folder, but also causes some issues, since an application using Kokkos most likely uses kokkos-install-dir/include as a directory where to find kokkos headers, hence missing all headers that are directly put in kokkos-install-dir (or in its subdirectories other than include).

A possible fix (I checked, and it works) would be to replace the above cmake line with

SET(KOKKOS_INCDIR ${CMAKE_INSTALL_PREFIX}/include)

Note: I wrote KOKKOS instead of TRILINOS since there's not trilinos involved here, and I hard-coded 'include' as the name of the subdirectory, since this is already done by TRIBITS_ADD_LIBRARY anyways...

**Comment by gmackey** [comment]
This issue is fixed in the new pure CMake version.

**Comment by ibaned** [comment]
We think this is fixed. Please reopen if not.
