### ISSUE TITLE
Nightly Trilinos failures with Cuda build: undefined reference to cuStreamGetCtx', cuCtxPushCurrent_v2', cuCtxGetDevice'

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6693]
**Describe the bug**

Nightly Cuda builds of Trilinos fail to link with the following undefined references:
```
03:28:52 kokkos/core/src/libkokkoscore.a(Kokkos_Cuda_Instance.cpp.o): In function `Kokkos::Impl::CudaInternal::initialize(CUstream_st*, bool)':
03:28:52 tmpxft_00006e53_00000000-6_Kokkos_Cuda_Instance.cudafe1.cpp:(.text+0x2da2): undefined reference to `cuStreamGetCtx'
03:28:52 tmpxft_00006e53_00000000-6_Kokkos_Cuda_Instance.cudafe1.cpp:(.text+0x2dc4): undefined reference to `cuCtxPushCurrent_v2'
03:28:52 tmpxft_00006e53_00000000-6_Kokkos_Cuda_Instance.cudafe1.cpp:(.text+0x2de5): undefined reference to `cuCtxGetDevice'
03:28:52 collect2: error: ld returned 1 exit status
```

This seems to follow from the updates from #6361 , @masterleinad can you help advise?

**Please include the following for a minimal reproducer**

Reproducer:
```bash
# Repos
git clone -b develop https://github.com/trilinos/Trilinos.git
TRILINOS_DIR=$PWD/Trilinos
git clone -b develop https://github.com/kokkos/kokkos.git
KOKKOS_DIR=$PWD/kokkos
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
KOKKOSKERNELS_DIR=$PWD/kokkos-kernels

# Env and configure Trilinos
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/kokkos-dev-2
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh kokkos-dev-2-cuda-opt
# Local modules
module use /home/projects/x86-64/modulefiles/local
export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="17" \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
 -DKokkos_ENABLE_CUDA=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
$TRILINOS_DIR
```

The above is a snip from the nightly build, but this should be reproducible with just cuda/11.4.2 and cmake >= 3.23.1 (and dropping the `-DTrilinos_CONFIGURE_OPTIONS_FILE=...` option from the cmake line)

**Comment by masterleinad** [comment]
Looks like we need to explicitly link with the driver library, also see https://stackoverflow.com/questions/66273536/undefined-reference-to-cuctxgetcurrent-while-getting-cuda-context-for-optix.

**Comment by masterleinad** [comment]
On the other hand, we already have
```
$ git grep -n "cuda_driver"
cmake/Modules/CudaToolkit.cmake:143:- ``CUDA::cuda_driver``
cmake/Modules/CudaToolkit.cmake:144:- ``CUDA::cuda_driver``
cmake/Modules/CudaToolkit.cmake:803:  _CUDAToolkit_find_and_add_import_lib(cuda_driver ALT cuda)
cmake/Modules/CudaToolkit.cmake:865:  _CUDAToolkit_find_and_add_import_lib(nvrtc DEPS cuda_driver)
cmake/Modules/FindTPLCUDA.cmake:24:IF (TARGET CUDA::cuda_driver)
cmake/Modules/FindTPLCUDA.cmake:26:  KOKKOS_EXPORT_IMPORTED_TPL(CUDA::cuda_driver)
cmake/Modules/FindTPLCUDA.cmake:40:    LINK_LIBRARIES CUDA::cuda_driver CUDA::cudart
```
so I would expect that we are already linking against the driver library. Is `Trilinos` pulling in the `Cuda` libraries differently?

**Comment by ndellingwood** [comment]
> Is `Trilinos` pulling in the `Cuda` libraries differently?

I'm not sure what/how this may be handled in TriBITs or if there is some mismatch or missing interaction? 
Here is the link to the FindTPLCUDA cmake file, https://github.com/trilinos/Trilinos/blob/develop/cmake/tribits/core/std_tpls/FindTPLCUDA.cmake , which calls `find_package(CUDAToolkit REQUIRED)` and then some extra processing in the `tribits_extpkg_create_imported_all_libs_target_and_config_file` function

**Comment by masterleinad** [comment]
@ndellingwood Can you try
```diff
diff --git a/cmake/tribits/core/std_tpls/FindTPLCUDA.cmake b/cmake/tribits/core/std_tpls/FindTPLCUDA.cmake
index a8b1ab8b1ca..614a74674ea 100644
--- a/cmake/tribits/core/std_tpls/FindTPLCUDA.cmake
+++ b/cmake/tribits/core/std_tpls/FindTPLCUDA.cmake
@@ -56,5 +56,5 @@
 find_package(CUDAToolkit REQUIRED)  # Will abort if not found!
 tribits_extpkg_create_imported_all_libs_target_and_config_file( CUDA
   INNER_FIND_PACKAGE_NAME  CUDAToolkit
-  IMPORTED_TARGETS_FOR_ALL_LIBS  CUDA::cufft  CUDA::cublas  CUDA::cudart )
+  IMPORTED_TARGETS_FOR_ALL_LIBS  CUDA::cufft  CUDA::cublas  CUDA::cudart CUDA::cuda_driver)
 # Above, we could add more dependencies if we need
```

**Comment by ndellingwood** [comment]
@masterleinad that change resolved the linker errors

**Comment by ndellingwood** [comment]
Adding @bartlettroscoe to the loop regarding potential TriBITS change

@bartlettroscoe we encountered some linker errors in Cuda builds of Trilinos that are resolved by Daniel's change above to the `FindTPLCUDA.cmake` in TriBITS by adding the `CUDA::cuda_driver` target, https://github.com/kokkos/kokkos/issues/6693#issuecomment-1875917803 .
Is there a planned snapshot of TriBITS to Trilinos in the near term? If not, may we move forward with two separate PRs with the change, one to Trilinos, the other to the TriBITS repo?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe we encountered some linker errors in Cuda builds of Trilinos that are resolved by Daniel's change above to the `FindTPLCUDA.cmake` in TriBITS by adding the `CUDA::cuda_driver` target, [#6693 (comment)](https://github.com/kokkos/kokkos/issues/6693#issuecomment-1875917803) . Is there a planned snapshot of TriBITS to Trilinos in the near term? If not, may we move forward with two separate PRs with the change, one to Trilinos, the other to the TriBITS repo?

@ndellingwood, make whatever change is needed in the Trilinos copy and I will make sure it gets pull back into the TriBITS repo so it will be there for the next snapshot of TriBITS to Trilinos.

**Comment by ndellingwood** [comment]
PR https://github.com/trilinos/Trilinos/pull/12643 is up with the suggested change

**Comment by ndellingwood** [comment]
PR https://github.com/trilinos/Trilinos/pull/12643 is merged, I'll close this issue after a round of nightlies confirms the link error is resolved

**Comment by ndellingwood** [comment]
Nightlies Cuda builds looking good, thanks for the help @masterleinad @bartlettroscoe
