### ISSUE TITLE
Check whether reduction_identity is used in team reduce

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#6694]
Its not quite clear to me why the point_t default constructor is changed, considering that there is a `reduction_identity` overload. Maybe the team reduce does not use reduction identity??

_Originally posted by @crtrott in https://github.com/kokkos/kokkos/issues/5334#issuecomment-1875789682_

**Comment by masterleinad** [comment]
Our reduction interface only uses `reduction_identity` for the built-in reducers. If we don't provide a reducer (and the functor doesn't implement `join`), the reduction uses `operator+=` for `join` and uses the default constructor for `init`. Hence, the behavior seems to be inline with this behavior.
We could still discuss if we would wan to use `Kokkos::Sum`(using `reduction_identity`) if no reducer was provided.

**Comment by dalg24** [comment]
It is used as `test_sum` does both reductions w/o a reducer and with `Kokkos::Sum`.
https://github.com/kokkos/kokkos/blob/f485cfa53cb2d25cab98e7a1d41a116027ec2363/core/unit_test/TestReducers.hpp#L403-L498

Thanks Daniel for the explanation.
