### ISSUE TITLE
Nightly unit test failure, OpenMP backend, gcc/8.3.0: openmp.reducers_int Kokkos::abort: Requested Team Size is too large!

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6699]
**Describe the bug**

Nightly tests with gcc/8.3.0 and the OpenMP backend failed in the `openmp.reducers_int` subtest (both debug and rel builds):
```
[ RUN      ] openmp.reducers_int
Kokkos::abort: Requested Team Size is too large!
Backtrace:
[0x1103d1c4] 
[0x1100e268] 
[0x105de050] 
[0x105df410] 
[0x105d1f9c] 
[0x1100c30c] 
[0x10ff9370] 
[0x10ff9830] 
[0x10ffa148] 
[0x10ffce34] 
[0x10ffd4d0] 
[0x10012508] 
[0x200002599f5c] 
[0x20000259a0f4] __libc_start_main
```

Test failure began after merge of the following changes:

**Changes**

    Fixup test math functions ulp should double -> int ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta/488/changes#71729af719b2eb20b512efad05ae609e74e1dd7a) / [githubweb](https://github.com/kokkos/kokkos/commit/71729af719b2eb20b512efad05ae609e74e1dd7a))
    #5333: CUDA: Use scratch space appropriate to small reduction elements in Team reductions (#5334) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta/488/changes#02b46c09c75697da5a1e4bfed5429a56c1bfb7ef) / [githubweb](https://github.com/kokkos/kokkos/commit/02b46c09c75697da5a1e4bfed5429a56c1bfb7ef))
    Cuda: Allocate using the correct device (#6392) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta/488/changes#4078a0d8a022ab1ad2291554b2820916fa3bc361) / [githubweb](https://github.com/kokkos/kokkos/commit/4078a0d8a022ab1ad2291554b2820916fa3bc361))
    Let `Profiling::ProfilingSection(std::string)` constructor be explicit and nodiscard (#6690) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_openmp_cuda1122_gcc830_volta/488/changes#f485cfa53cb2d25cab98e7a1d41a116027ec2363) / [githubweb](https://github.com/kokkos/kokkos/commit/f485cfa53cb2d25cab98e7a1d41a116027ec2363))

**Please include the following for a minimal reproducer**
**Reproducer** (weaver rhel8 queue):
```bash
source /projects/ppc64le-pwr9-rhel8/legacy-env.sh
module load cuda/11.2.2/gcc/8.3.1 cmake/3.23.1

${KOKKOS_PATH}/generate_makefile.bash --with-cuda --with-openmp --compiler=${KOKKOS_PATH}/bin/nvcc_wrapper --arch=Volta70,Power9 --with-cuda-options=enable_lambda --kokkos-path=${KOKKOS_PATH} ${DEBUG} --cxxflags=${CXXFLAGS} --cxxstandard=17

make -j16

```

**Comment by masterleinad** [comment]
I guess #5334 is the culprit.

**Comment by masterleinad** [comment]
Probably, we need to choose a smaller team size in https://github.com/kokkos/kokkos/blob/9f5e38e976f1c9003d5895803e5d5ce03015dbbb/core/unit_test/TestReducers.hpp#L388C10-L388C10. Possibly take the minimum with `team_size_max`.

**Comment by ndellingwood** [comment]
Tonight's test passed after merge of these changes:

Add `ATOMICS_BYPASS` configuration option to disable atomics (#6692) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1200_gcc1130_volta-cpp20/26/changes#27286c32d7e0c157d1a4d7f00f9441979ed8eabe) / [githubweb](https://github.com/kokkos/kokkos/commit/27286c32d7e0c157d1a4d7f00f9441979ed8eabe))
    Check matching static extents in View constructor (#5190) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1200_gcc1130_volta-cpp20/26/changes#0e4a158a7585f2a93b93d4121788016fe0dba4c9) / [githubweb](https://github.com/kokkos/kokkos/commit/0e4a158a7585f2a93b93d4121788016fe0dba4c9))
    Remove Kokkos::[b]half_t volatile overloads (#6579) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_weaver_cuda_serial_cuda1200_gcc1130_volta-cpp20/26/changes#96d530a24034467db26070081b62a0a23c60530e) / [githubweb](https://github.com/kokkos/kokkos/commit/96d530a24034467db26070081b62a0a23c60530e))

The test had been failing consistently, will wait for another round of testing to confirm the pass was not spurious (unless there was a drive-by fix in one of the commits listed above)

**Comment by dalg24** [comment]
Uggg.  No I did not expect any of these would have anything to do with that issue...

**Comment by crtrott** [comment]
Yeah and also the original PRs shouldn't have caused the issue. The only way how OpenMP fails TeamSize check is if you ask for more than occupancy isn't it?

**Comment by ndellingwood** [comment]
@dalg24 @crtrott I posted the update on the wrong issue, sorry about the false alarm (the cuda/12 with c++20 build is now passing)

**Comment by ndellingwood** [comment]
@masterleinad I tried testing a modification to use (I believe) team_size_max, but still encountered the same abort failure in `openmp.reducers_int`

I tested this change, where I used the existing team_size as a guess to pass to the dummy TeamPolicy in order to get a team_size_max estimate:
```diff
diff --git a/core/unit_test/TestReducers.hpp b/core/unit_test/TestReducers.hpp
index f710c40d3..434908ab9 100644
--- a/core/unit_test/TestReducers.hpp
+++ b/core/unit_test/TestReducers.hpp
@@ -385,6 +385,7 @@ struct TestReducers {
     Kokkos::deep_copy(sum_scalar, sum_view);
     ASSERT_EQ(sum_scalar, Scalar{0}) << "N: " << N;
 
+#if 0
     auto team_size = std::min(128, TEST_EXECSPACE().concurrency());
     Kokkos::parallel_for(
         Kokkos::TeamPolicy<ExecSpace>(10, team_size),
@@ -396,6 +397,24 @@ struct TestReducers {
                                   reducer_scalar);
           sum_view() = local_scalar;
         });
+#else
+    auto team_size_guess = std::min(128, TEST_EXECSPACE().concurrency());
+
+    auto lambda =
+        KOKKOS_LAMBDA(member_type team_member) {
+          Scalar local_scalar;
+          Kokkos::Sum<Scalar, typename ExecSpace::memory_space> reducer_scalar(
+              local_scalar);
+          Kokkos::parallel_reduce(Kokkos::TeamThreadRange(team_member, N), f,
+                                  reducer_scalar);
+          sum_view() = local_scalar;
+        };
+
+    const int team_size_max = Kokkos::TeamPolicy<ExecSpace>(10, team_size_guess).team_size_max(lambda, Kokkos::ParallelForTag());
+    auto team_size = std::min(team_size_max, team_size_guess);
+
+    Kokkos::parallel_for(Kokkos::TeamPolicy<ExecSpace>(10, team_size), lambda);
+#endif
     Kokkos::deep_copy(sum_scalar, sum_view);
     ASSERT_EQ(sum_scalar, reference_sum) << "N: " << N;
   }
```

Did I make a mistake in the diff above? If not, do you have a suggestion for next steps I can try?

**Comment by tcclevenger** [comment]
Added a PR. Comments were correct, needed a smaller team size. @ndellingwood The issue with your code above is that when you ask for max team size
```
Kokkos::TeamPolicy<ExecSpace>(10, team_size_guess).team_size_max(lambda, Kokkos::ParallelForTag());
```
`team_size_guess` was too large, so we were still getting the error when creating the team policy to get the max size.
