### ISSUE TITLE
Nightly test failure, intel/19: TestArray.cpp(71): error: static assertion failed static_assert(test_array_ctad());

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6702]
**Describe the bug**

Nightly builds with intel/19 are failing to compile the TestArray.cpp test with all host backends:
```
[ 12%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreTestCompileOnly.dir/TestCreateMirror.cpp.o
/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/unit_test/TestArray.cpp(71): error: static assertion failed
  static_assert(test_array_ctad());
```

This error follows merge of the following changes, likely #6373:

**Changes**

    GitHub CI: Test with AddressSanitizer (#6676) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/905/changes#654a51f60cef8900868f55a93661cee80f451cd9) / [githubweb](https://github.com/kokkos/kokkos/commit/654a51f60cef8900868f55a93661cee80f451cd9))
    Kokkos::Array deduction guide (#6373) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/905/changes#efc0c365c0b61c63a47712656788d2d30ab16d4b) / [githubweb](https://github.com/kokkos/kokkos/commit/efc0c365c0b61c63a47712656788d2d30ab16d4b))
    Add CI for MSVC+Cuda (#6661) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/905/changes#06de563f9958c58a6f292d742d8f658d67600d7c) / [githubweb](https://github.com/kokkos/kokkos/commit/06de563f9958c58a6f292d742d8f658d67600d7c))
    SYCL: Address deprecations after oneAPI 2023.2.0 (#6577) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/905/changes#9f5e38e976f1c9003d5895803e5d5ce03015dbbb) / [githubweb](https://github.com/kokkos/kokkos/commit/9f5e38e976f1c9003d5895803e5d5ce03015dbbb))

**Please include the following for a minimal reproducer**

**Reproducer**:
```bash
module load sems-cmake sems-intel/19.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

**Comment by dalg24** [comment]
Guard the unit test against the Intel compiler version

**Comment by dalg24** [comment]
Closing as it is not in a release.  The issue was reported immediately and fixed timely.
