### ISSUE TITLE
Can't properly detect kokkos windows/msvc installation in project

### ISSUE THREAD

**Issue by lsoulierCExA** [kokkos/kokkos#6718]
**Describe the bug**

Cannot configure a project to use kokkos with windows/msvc (see #6717).
> CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

**Please include the following for a minimal reproducer**

1. cl 19.34.31937
2. Kokkos v.4.2.0
3. windows, x64, openMP
4. CMake configure command: default + setting openMP on and making a subdirectory build for cmake output
5. Output from CMake configure command:
> CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

also OpenMP_CXX_flags are not inherited from kokkos installation

> Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindOpenMP.cmake:544 (find_package_handle_standard_args)
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  <MYPATH>/kokkos/install/lib/cmake/Kokkos/KokkosConfig.cmake:39 (FIND_DEPENDENCY)
  CMakeLists.txt:14 (find_package)

The issue can be tracked down to this:
- CMake FindOpenMP module detects only the default msvc openmp version which is too old.

**Comment by lsoulierCExA** [comment]
Here is my CMakeLists.txt, modified from tutorial (in order to try to have a more straightforward kokkos detection)
```cmake
cmake_minimum_required(VERSION 3.16)
project(KokkosTutorial01)

add_executable(01_Exercise exercise_1_begin.cpp)

if(NOT CMAKE_BUILD_TYPE)
  set(default_build_type "RelWithDebInfo")
  message(STATUS "Setting build type to '${default_build_type}' as none was specified.")
  set(CMAKE_BUILD_TYPE "${default_build_type}" CACHE STRING
    "Choose the type of build, options are: Debug, Release, RelWithDebInfo and MinSizeRel."
    FORCE)
endif()

find_package(Kokkos CONFIG)
if(Kokkos_FOUND)
  message(STATUS "Found Kokkos: ${Kokkos_DIR} (version \"${Kokkos_VERSION}\")")
endif()

target_link_libraries(01_Exercise Kokkos::kokkos)
```

**Comment by crtrott** [comment]
Hey,

Are you trying to use a different OpenMP implementation, or just MSVCs? I think we need to a configure time error to not allow OpenMP with MSVC. Last I checked they don't support enough OpenMP for Kokkos to work. The threads backend should work fine though.

**Comment by lsoulierCExA** [comment]
Hi,

I'm trying to use MSVC version with /openmp:llvm.<br>
With this flag I can build and install kokkos (through a workaround, see #6717).

I don't know if the "llvm" version has enough features though, yet the cmake error does not seem related to missing features.

**Comment by crtrott** [comment]
Hi,

I just looked it up. While that /openmp:llvm does use the LLVM runtime, it does not support all the OpenMP features we would need in the compiler itself. I.e. the pragmas are not what LLVM would support. You only get OpenMP 2 with a few 3.x features. We actually need OpenMP 4 as a baseline.

https://learn.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-170

So all in all I think this won't work. If there is a real driver, we likely could make the CPU backend work but we haven't done this. 

Cheers
Christia

**Comment by lsoulierCExA** [comment]
Hi,

Bad news...
Is it the same issue with /openmp:experimental (I think I couldn't compile at all with that, but I'm not sure).

Though most (all) HPC services are on Linux, They are lots of people that work with windows locally and I think they would appreciate to prototype on their machine before pushing a code to a HPC machine.

Thanks for having looked into the issue.

**Comment by dalg24** [comment]
You can use the C++ Threads backend for that  `-DKokkos_ENABLE_THREADS=ON`

**Comment by lsoulierCExA** [comment]
@ajpowelsnl Yes, thanks. I'm not done yet but I could proceed with the first exercises, but only with threads (OpenMP is definitively a no go with msvc and I don't have other GPU backend available now, thus limiting the interest of some examples). If I find some time, I may try also through msys2 packages (trilinos, openmp).
