### ISSUE TITLE
Inaccurate CMake error message for C++26

### ISSUE THREAD

**Issue by simon-schlepphorst** [kokkos/kokkos#6727]
Trying to configure Kokkos with `CMAKE_CXX_STANDARD=26` results in this inaccurate error message:

```
CMake Error at thirdparty/kokkos/kokkos/cmake/kokkos_test_cxx_std.cmake:78 (MESSAGE):
  Kokkos requires C++17 or newer but requested 26!
```
CMake logic in the current develop branch only supports hard coded C++[17,20,23]:
https://github.com/kokkos/kokkos/blob/179d2e67fd42eeb894cf9b5e976104a13de990c2/cmake/kokkos_test_cxx_std.cmake#L65-L79

Easiest fix would be to come up with a better wording for the error message.

If you are fine with e.g. `Kokkos requires C++17 to 23 but requested 26!`, I am happy to send in a patch.

**Comment by dalg24** [comment]
I'd go for a
```cmake
 ELSEIF(KOKKOS_CXX_STANDARD STREQUAL "26") 
   kokkos_set_cxx_standard_feature(26) 
   SET(KOKKOS_CXX_INTERMEDIATE_STANDARD "2C") 
   SET(KOKKOS_ENABLE_CXX26 ON)
```

**Comment by simon-schlepphorst** [comment]
Here you go: #6733

Hope your tests will tell if I missed anything.
