### ISSUE TITLE
Compilation flags seemingly passed twice to Trilinos

### ISSUE THREAD

**Issue by maartenarnst** [kokkos/kokkos#6736]
**Describe the bug**

It appears that when Kokkos is built as part of Trilinos, it passes compilation flags twice to Trilinos.

- https://github.com/kokkos/kokkos/blob/71a9bcae52543bd065522bf3e41b5bfa467d8015/CMakeLists.txt#L295-L301

It may be behind an issue I am seeing. 

In fact, I'm trying to compile Trilinos with the Cray compiler on the European computer LUMI, which is similar to Frontier. Here, the linking doesn't work, and the reason appears to be that in passing these flags twice, Kokkos is setting "-x hip" as part of the `CMAKE_CXX_FLAGS`. It seems CMake then passes these flags to the linker too. And the issue is then that when it's called to link, the Cray compiler doesn't react well to `-x hip`.

- https://github.com/kokkos/kokkos/blob/71a9bcae52543bd065522bf3e41b5bfa467d8015/cmake/kokkos_arch.cmake#L225 

It appears a straightforward fix would be to remove `${KOKKOSCORE_CXX_FLAGS}` from the two lines that set the `CMAKE_CXX_FLAGS` in the snippet above. The flags would then still be passed to Trilinos through the `set(KOKKOS_ALL_COMPILE_OPTIONS $<$<COMPILE_LANGUAGE:CXX> ...`.  

The duplication seems to come from PR 
- #2779.

If you agree with the suggestion to remove the `${KOKKOSCORE_CXX_FLAGS}` from the two lines that set the `CMAKE_CXX_FLAGS` or you have another suggestion, I'll be happy to make a PR.

Also tagging
- https://github.com/kokkos/kokkos/issues/5921
- @romintomasetti

**Comment by masterleinad** [comment]
Fixed in #6742.
