### ISSUE TITLE
error LNK2038 when compiling tutorials

### ISSUE THREAD

**Issue by lsoulierCExA** [kokkos/kokkos#6755]
Kokkos is build with msvc with only threads on, in Release build type.
tutorials are also compiled on msvc in Release build type.

I've got the link error:
> error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in exercise_1_begin.obj

1. cl 19.34.31937
2. Kokkos v.4.2.0
3. windows, x64
4. meaningless
5. meaningless
6. The exercice cmakelist file is:
```cmake
cmake_minimum_required(VERSION 3.16)
project(KokkosTutorial01)

add_executable(01_Exercise exercise_1_begin.cpp)

if(NOT CMAKE_BUILD_TYPE)
  set(default_build_type "Release")
  message(STATUS "Setting build type to '${default_build_type}' as none was specified.")
  set(CMAKE_BUILD_TYPE "${default_build_type}" CACHE STRING
    "Choose the type of build, options are: Debug, Release, RelWithDebInfo and MinSizeRel."
    FORCE)
endif()

find_package(Kokkos CONFIG)
if(Kokkos_FOUND)
  message(STATUS "Found Kokkos: ${Kokkos_DIR} (version \"${Kokkos_VERSION}\")")
endif()

target_link_libraries(01_Exercise Kokkos::kokkos)
```
8. ```cmake --build .``` from the cmake build directory triggers the linker error

Note that if Kokkos is build in debug while the example is in release, the example compiles though, there seem to be no performance difference with or without kokkos loops.

this issue is related to #6717 and #6718

**Comment by dalg24** [comment]
According to https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2038 the issue comes from mixing together debug and release builds in the same executable.
Try to match the build type from what you used with Kokkos.

Also if you are trying to build the tutorial https://github.com/kokkos/kokkos-tutorials/tree/main/Exercises/01/Begin and you don't point to an external Kokkos build, it will install download and install Kokkos for you and you won't tun into such issues.

**Comment by lsoulierCExA** [comment]
Yes I know and it's what I find strange because it's the mixed configuration that works instead of the consistent one.

What bothers me is that I don't see what /Mxy options are set (x being D or T and y being d or nothing) for kokkos and for the exercice.

Yet I will follow you're suggestion to automatically fetch and build Kokkos with the example to see if there is any difference.

**Comment by lsoulierCExA** [comment]
I tried to use kokkos from the tutorials but failed.<br>
Previously, I removed my original kokkos install and start again with a fresh clone of the tutorials.<br>
If I don't change anything (except locating the build tree to some ```build``` directory), I can build and run the tests but it seems (from cmake warnings) that I only got a serial backend (running the exercice with or without kokkos loops does not change anything).

As soon as I try to change something from cmake-gui (switching to Release, and/or enabling threads (and disabling serial as suggested in cmake messages)), cmake configuration fails, not able to find ```KokkosTarget.cmake```.

**Comment by dalg24** [comment]
> it seems (from cmake warnings) that I only got a serial backend

Yes, if you need to explicitly enable backends.  For instance if you want the C++ Threads backend you'd use `-DKokkos_ENABLE_THREADS=ON` just like when you build Kokkos itself.

**Comment by ajpowelsnl** [comment]
@lsoulierCExA - did configuring with `-DKokkos_ENABLE_THREADS=ON` resolve the problem?

**Comment by lsoulierCExA** [comment]
Sorry I forgot to report back to this issue. It was not a backend issue but more probably an unclean cmake cache and/or an issue with the environment variable used to point to my kokkos installation directory.
With the support of dalg24, I made a fresh step by step configuration/build/install and the error disappeared.
My bad.
