### ISSUE TITLE
Nightly test failure, Intel/19.0.5: Kokkos_ViewMapping.hpp(3053): error: no instance of constructor "ZeroMemset" matches the argument list

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#6775]
**Describe the bug**
Nightly intel/19.0.5 builds fail to compile (serial, openmp, threads backends) with output:
```
/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(3053): error: no instance of constructor "ZeroMemset" matches the argument list
            argument types are: (Kokkos::HostSpace::execution_space, Kokkos::View<int *, Kokkos::HostSpace::memory_space, Kokkos::MemoryTraits<1U>>, int)
            space,
            ^
/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_CopyViews.hpp(1338): note: this candidate was rejected because mismatch in count of arguments
  struct ZeroMemset {
         ^
/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_CopyViews.hpp(1339): note: this candidate was rejected because arguments do not match
    ZeroMemset(const ExecutionSpace& exec_space, const ViewType& dst,
    ^
/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_CopyViews.hpp(1344): note: this candidate was rejected because mismatch in count of arguments
    ZeroMemset(const ViewType& dst, typename ViewType::const_value_type& value) {
    ^
          detected during:
            instantiation of "std::enable_if_t<<expression>, void> Kokkos::Impl::ViewValueFunctor<DeviceType, ValueType, true>::construct_shared_allocation() [with DeviceType=Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, ValueType=int, Dummy=int]" at line 3442
            instantiation of "Kokkos::Impl::SharedAllocationRecord<void, void> *Kokkos::Impl::ViewMapping<Traits, std::enable_if_t<<expression>, void>>::allocate_shared(const Kokkos::Impl::ViewCtorProp<P...> &, const Traits::array_layout &, bool) [with Traits=Kokkos::ViewTraits<int *, Kokkos::DefaultExecutionSpace>, P=<std::__cxx11::string, Kokkos::HostSpace::memory_space, Kokkos::HostSpace::execution_space>]" at line 1465 of
                      "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_View.hpp"
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::Impl::ViewCtorProp<P...> &, const std::enable_if_t<<expression>, Kokkos::ViewTraits<DataType, Properties...>::array_layout> &) [with DataType=int *, Properties=<Kokkos::DefaultExecutionSpace>, P=<std::__cxx11::string>]" at line 1580 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_View.hpp"
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Label &, std::enable_if_t<Kokkos::Impl::is_view_label<Label>::value, const size_t={unsigned long}>, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}) [with DataType=int *, Properties=<Kokkos::DefaultExecutionSpace>, Label=char [12]]" at line 91 of
                      "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/unit_test/TestCreateMirror.cpp"
```

This began following merge of these commits
**Changes**:
Drop CudaInternal::cuda_get_last_error_wrapper() ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#b3d8643e83c4b0f4ebd9f1ccc6bb380b0b8f6090) / [githubweb](https://github.com/kokkos/kokkos/commit/b3d8643e83c4b0f4ebd9f1ccc6bb380b0b8f6090))
    Avoid calling wrapper functions with singleton in some classes ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#a082f820d557cdd4921cd893ba0c54d0fe7a211b) / [githubweb](https://github.com/kokkos/kokkos/commit/a082f820d557cdd4921cd893ba0c54d0fe7a211b))
    Avoid calling wrapper functions with singleton in Kokkos_Cuda_Task.cpp ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#7439ec9d41099cb53e184f769ead2d202b9b7399) / [githubweb](https://github.com/kokkos/kokkos/commit/7439ec9d41099cb53e184f769ead2d202b9b7399))
    Deprecate `in_parallel` (#6032) (#6582) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#71b246d674600c7f83bc553f3ce5fe7dd6216d2b) / [githubweb](https://github.com/kokkos/kokkos/commit/71b246d674600c7f83bc553f3ce5fe7dd6216d2b))
    Remove redundant calls in rangepolicy constructors (#6765) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#bbb895a347f4c511a9fc85193ca554f105e99739) / [githubweb](https://github.com/kokkos/kokkos/commit/bbb895a347f4c511a9fc85193ca554f105e99739))
    OpenMPTarget on Intel GPUs update (#6735) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#408e8be5b943cd21092a7294a0fb9b8ecefb648e) / [githubweb](https://github.com/kokkos/kokkos/commit/408e8be5b943cd21092a7294a0fb9b8ecefb648e))
    Get rid of print statements in parallel algorithms unit tests ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#7d5fff958313c8d7bceec4cef8736b8c8ffd189f) / [githubweb](https://github.com/kokkos/kokkos/commit/7d5fff958313c8d7bceec4cef8736b8c8ffd189f))
    Drop 2-arguments `ZeroMemset` constructor overloads (#6764) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/932/changes#af806fb5de470944631ded4a62492d90bde3a6c8) / [githubweb](https://github.com/kokkos/kokkos/commit/af806fb5de470944631ded4a62492d90bde3a6c8))

Based on error message, this is apparently following PR #6764

**Please include the following for a minimal reproducer**

**Reproducer**:
```bash
module load sems-cmake sems-intel/19.0.5

$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --no-examples   --with-options=enable_large_mem_tests
```

**Comment by dalg24** [comment]
I am about to merge #6769 that will change this interface.  Let's see how that plays with that issue.  It might be an issue with CTAD.

**Comment by ndellingwood** [comment]
> I am about to merge #6769 that will change this interface. Let's see how that plays with that issue. It might be an issue with CTAD.

@dalg24 no luck, a later nightly job with intel/19.0.5 (debug build) showed the same compilation errors after merge of #6769 . I think your guess about CTAD-related issues sounds on the right track, iirc there have been other occurrences with intel/19.0.5 and gcc/8.* having some shortcomings handling CTAD stuff that should work

**Comment by dalg24** [comment]
I would guard the specifying template arguments for those compiler that give us issues.

**Comment by ndellingwood** [comment]
Nightlies back to passing after merge of #6807, closing
