### ISSUE TITLE
what is wrong with this?Makefile.kokkos: CUDA is enabled but the compiler is neither NVCC nor Clang (got version string nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Thu_Nov_18_09:45:30_PST_2021 Cuda compilation tools, release 11.5, V11.5.119 Build cuda_11.5.r11.5/compiler.30672275_0) .  Stop.

### ISSUE THREAD

**Issue by 5ch0** [kokkos/kokkos#6776]
![384e47a89d15928c50ebc57f4f27a37](https://github.com/kokkos/kokkos/assets/158433114/24c941e8-8b70-4d2d-9ba3-08ad9189e337)
![bb29aec5f1f6659363560361538c604](https://github.com/kokkos/kokkos/assets/158433114/b3932208-4e4a-4b87-8ad2-e2b66370e848)

It appears:
/home/zrj/kokkos-4.1.00/Makefile.kokkos:965: *** Makefile.kokkos: CUDA is enabled but the compiler is neither NVCC nor Clang (got version string nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Thu_Nov_18_09:45:30_PST_2021 Cuda compilation tools, release 11.5, V11.5.119 Build cuda_11.5.r11.5/compiler.30672275_0) .  Stop.

![e41170edbb0d8da727d8b57522f2be6](https://github.com/kokkos/kokkos/assets/158433114/a9a258f7-5691-4abd-8c6d-1314cfb7627f)

**Comment by dalg24** [comment]
Did you try installing `bc`?

**Comment by 5ch0** [comment]
I tried to reinstall Kokkos. But it can not make .why?
![Uploading 11a3c108dc2de20d07351d34805ccd2.jpg…]()

**Comment by 5ch0** [comment]
I tried to reinstall Kokkos. But it can not make .why?
![11a3c108dc2de20d07351d34805ccd2](https://github.com/kokkos/kokkos/assets/158433114/ea1b67f8-f279-4968-880f-c3e4436e2a8f)

**Comment by 5ch0** [comment]
I tried to reinstall Kokkos. But it can not make .why?
![b8e3d5a238299445158e1bf0cb92ad9](https://github.com/kokkos/kokkos/assets/158433114/e9d45ce9-9773-4c6d-83b9-d6256949d902)
![11a3c108dc2de20d07351d34805ccd2](https://github.com/kokkos/kokkos/assets/158433114/cd8a2969-b3a3-4d98-8c63-78040fc794a3)

**Comment by 5ch0** [comment]
I tried to reinstall the Kokkos.But it can not make.why?
![b8e3d5a238299445158e1bf0cb92ad9](https://github.com/kokkos/kokkos/assets/158433114/19fd4200-ffb3-4c8b-a96c-e51ff00c90a7)
![ba1994cdd3927d67b69c24ff9bde8a7](https://github.com/kokkos/kokkos/assets/158433114/53d346df-c972-4afa-bf6b-45e0e149eb0b)

**Comment by 5ch0** [comment]
Oh, I solved this problem by updating cuda to 11.8
It could be a version incompatibility issue.
Thank you for your answer.

**Comment by 5ch0** [comment]
> Did you try installing `bc`?

What is bc？
