### ISSUE TITLE
Kokkos parallel reduce error on cuda

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#678]
I wrote a simple lambda express 

`    Cmplx sum(0.0);
    Kokkos::parallel_reduce(size, KOKKOS_LAMBDA (const int j, Cmplx& local_sum) {
      for (int i=0;i<size;++i)
        local_sum += prec2(j,i);
    }, sum);
`

and it does, although prec3 is a kokkos view and everything else should be local.  I run it under cuda-gdb with mem check on I get a lane illegal address.  I'm at a loss at this point. ideas?

Program received signal CUDA_EXCEPTION_1, Lane Illegal Address.
[Switching focus to CUDA kernel 1, grid 1322, block (12,0,0), thread (0,0,0), device 0, sm 0, warp 0, lane 0]
0x0000000000f8f9a0 in _ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_14ParallelReduceINS0_18CudaFunctorAdapterIZN13MatrixBuilder20buildPreconditioner2ER12ParticleTreeEUnvhdl2_MS4_FvS6_ENS4_20buildPreconditioner2E1_viRNS_7complexIdEEEiKPS4_NS_11RangePolicyIJNS_4CudaEEEESA_vEESH_NS_11InvalidTypeESG_EEEEvT_<<<(21,1,1),(1,256,1)>>> ()
(cuda-gdb) where
#0  0x0000000000f8f9a0 in _ZN6Kokkos4Impl33cuda_parallel_launch_local_memoryINS0_14ParallelReduceINS0_18CudaFunctorAdapterIZN13MatrixBuilder20buildPreconditioner2ER12ParticleTreeEUnvhdl2_MS4_FvS6_ENS4_20buildPreconditioner2E1_viRNS_7complexIdEEEiKPS4_NS_11RangePolicyIJNS_4CudaEEEESA_vEESH_NS_11InvalidTypeESG_EEEEvT_<<<(21,1,1),(1,256,1)>>> ()
(cuda-gdb) quit

**Comment by crtrott** [comment]
Do you have a standalone example?

**Comment by crtrott** [comment]
I tried this:

```c++
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  typedef Kokkos::complex<double> Cmplx;
  int size = 1024;
  {
  Kokkos::View<Cmplx**> prec2("A",size,size);
  Cmplx sum(0.0);
  Kokkos::parallel_reduce(size, KOKKOS_LAMBDA (const int j, Cmplx& local_sum) { 
    for (int i=0;i<size;++i) local_sum += prec2(j,i); 
  }, sum);
  printf("%lf %lf\n",sum.real(),sum.imag());
  }
  Kokkos::finalize();
}
```

And it works both on master and develop.

**Comment by bathmatt** [comment]
I don't have a stand alone example anymore.  I think it is related to local
memory and the issue #679 which I'm still seeing problems.  I'm working on
a stand alone example for that one

**Comment by dsunder** [comment]
@hcedwar is your current memory pool work relevant to this issue?

**Comment by hcedwar** [comment]
@bathmatt : Has this issue been resolved in the recent few updates?
