### ISSUE TITLE
 Makefile.kokkos: CUDA is enabled but the compiler is neither NVCC nor Clang (got version string nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0) .  Stop.

### ISSUE THREAD

**Issue by 5ch0** [kokkos/kokkos#6781]
My last problem wasn't solved.
It can find nvcc compiler when installing.
![1](https://github.com/kokkos/kokkos/assets/158433114/7673ce23-d9f2-4953-81d6-016a80aa42df)
![2](https://github.com/kokkos/kokkos/assets/158433114/29a34869-4bcd-4ad9-865d-6ec075d83ba3)

But when I run the code, I can't find nvcc
![3](https://github.com/kokkos/kokkos/assets/158433114/2bc33007-4bbf-48eb-9c3b-2c84d364f2c2)

Follow is makefile:
![4](https://github.com/kokkos/kokkos/assets/158433114/21337d4a-1110-4e31-b7cd-3bd1aedcc132)

I am just contact Kokkos novice, hope to get the big guys help, thank you！

**Comment by masterleinad** [comment]
If you are using Makefiles, you have to make sure the compiler is `nvcc_wrapper` for `Cuda` and also have to specify the architecture which means swapping `OpenMP` for `Cuda` and `Volta70` for `Ada89` if that's your GPUs architecture.

In the tutorials, you can build `Kokkos` inline using `CMake` as well and have the architecture detected for you. All you would need to do is to configure with `-DKokkos_ENABLE_CUDA=ON`.

Separately, the first exercise is not meant to run with `Cuda`. You will run into some more problems as explained in the lecture notes and video lectures at https://github.com/kokkos/kokkos-tutorials/wiki/Kokkos-Lecture-Series.
