### ISSUE TITLE
Issue using team scratch on cuda, when mem is reused

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#679]
I've got a chunk of code where I am creating a matrix and I initialize it to 0, howevre, when I check the initialization I get NaN after the first set of teams have gone through.  I have no idea why this would be happening.  It only happens on a GPU, and not a CPU, 

`

      
      DoubleMatrix AhA(team_member.team_scratch(1), cnt, cnt);
      Kokkos::View<double*> work(team_member.team_scratch(1), cnt);
      Kokkos::parallel_for(Kokkos::TeamThreadRange(team_member, cnt), [&] (const int &i) {
        Kokkos::parallel_for(Kokkos::ThreadVectorRange(team_member, cnt), [&] (const int &j) {
          AhA(i,j) = 0.0;});
        });

      team_member.team_barrier();

      double s1=0;
      Kokkos::parallel_reduce(Kokkos::TeamThreadRange(team_member, cnt), [&] (const int &i, double &local_sum) {
        Kokkos::parallel_reduce(Kokkos::ThreadVectorRange(team_member, cnt), [&] (const int &j, double &vlocal_sum) {
          vlocal_sum += AhA(i,j);
        }, local_sum);},s1);
      if ( team_rank == 0 )
        printf("Local sum %d %lf\n", indx, s1);

`

On CPU I get 0 for all my sums, however, if I run this on cuda I get a lot of 0's and a lot more NaN

Local sum 50 0.000000
Local sum 2 0.000000
Local sum 28  0.000000
....
.Local sum 109  -nan

How can this be the case? I just set things to zero.

**Comment by crtrott** [comment]
Is this vs Kokkos Develop or Master?

**Comment by bathmatt** [comment]
trilinos develop.

**Comment by crtrott** [comment]
Oh my fix for the scratch_space level 1 for Cuda didn't make it yet to Trilinos if this is really important for you I can do an integration next week ...

**Comment by bathmatt** [comment]
OK, I'll tyr to apply a patch then.

**Comment by bathmatt** [comment]
@crtrott what is the checksum for the patch I'd need to apply?

**Comment by bathmatt** [comment]
@crtrott 
I applied patch 0001-Core-Fixing-level-1-scratch-space-for-Cuda.patchFrom 53a9cefb1f45797710419444f8661c806b7059f1 Mon Sep 17 00:00:00 2001
From: crtrott <crtrott@sandia.gov>
Date: Tue, 7 Mar 2017 17:05:11 -0700
Subject: [PATCH] Core: Fixing level 1 scratch space for Cuda

and I'm still getting the issue in this bug report.  I applied it to Trilinos/Develop.
Any ideas?

**Comment by crtrott** [comment]
No sorry. no idea.

**Comment by bathmatt** [comment]
I copied the latest version of kokkos over to my trilinos install and it appears to work now, closing.
