### ISSUE TITLE
[Bug] Parallel for on Cuda not calling team_size_recommended

### ISSUE THREAD

**Issue by maartenarnst** [kokkos/kokkos#6814]
**Describe the bug**

If the user doesn't provide the team size, the specialisation of `ParallelFor` on `Cuda` sets it as follows:

- https://github.com/kokkos/kokkos/blob/391f2d12f2d3e5f896d497a11d0752aa47be7277/core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp#L545-L552

This is quite similar but not exactly the same as what `team_size_recommended` does:

- https://github.com/kokkos/kokkos/blob/391f2d12f2d3e5f896d497a11d0752aa47be7277/core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp#L142-L148

It may also be worth noting that the documentation suggests that `ParalelFor` will call `team_size_recommended` (which it doesn't in this case).

- https://kokkos.org/kokkos-core-wiki/API/core/parallel-dispatch/ParallelForTag.html?highlight=team_size_recommended

And it may also be worth noting that on HIP, the behavior is more what would be expected:
- https://github.com/kokkos/kokkos/blob/e0dc0128e04f18c2bbbaefceef3616e7ddcfa3c4/core/src/HIP/Kokkos_HIP_Parallel_Team.hpp#L510-L520

It is not immediately clear why the constructor of `ParallelFor` doesn't call `team_size_recommended`, i.e. why there is duplication.  And it is not immediately clear why there are the differences, i.e. the sizes of the double that are added. 

Joint observations with @romintomasetti.

**Comment by crtrott** [comment]
I think the extra stuff is actually missing in the first code place ...

**Comment by romintomasetti** [comment]
@crtrott So you mean that internally, `ParallelFor` constructor should use `team_size_recommended`, and that the "formula" implemented in `team_size_recommended` is the correct one?

**Comment by crtrott** [comment]
Some of that scratch is in case you do a nested `parallel_reduce`.

**Comment by tcclevenger** [comment]
PR https://github.com/kokkos/kokkos/pull/6891. Made the change for both `ParallelFor` and `ParallelReduce`. Thanks for finding this @maartenarnst and @romintomasetti.

**Comment by tcclevenger** [comment]
https://github.com/kokkos/kokkos/pull/6891 resolved this issue. Closing.
