### ISSUE TITLE
Stream benchmark fails using the CUDA backend - Nvidia Quadro P5000 GPU ( pascal 6.1 )

### ISSUE THREAD

**Issue by ahadji05** [kokkos/kokkos#6827]
Hi,
I recently cloned Kokkos to experiment with the stream benchmark ( `https://github.com/kokkos/kokkos/tree/master/benchmarks/stream` ) on my machine. I am facing errors when trying to run the benchmark using the CUDA backend. Initially, I managed to run using the OpenMP backend but the CUDA still fails after several attempts.

Operating System:          Linux RedHat 8.5.0 
CPU:                               Intel Xeon Gold 6136
GPU:                               Nvidia Quadro P5000 ( pascal 6.1 )
Compiler (1st attempt ):  icpx Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0
Compiler (2nd attempt):  g++ (GCC) 9.2.1
CMake                         :  3.25.2

Cmake command:
`cmake .. -DKokkos_ROOT=/home/hadjigax/kokkosInstallationCUDA/lib64/cmake/Kokkos -DCMAKE_CXX_COMPILER=icpx`
or,
`cmake .. -DKokkos_ROOT=/home/hadjigax/kokkosInstallationCUDA/lib64/cmake/Kokkos -DCMAKE_CXX_COMPILER=g++ `

and the CMake output is:
```
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is IntelLLVM 2021.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/gcc-toolset-9/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2021.3.0/linux/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Enabled Kokkos devices: CUDA;SERIAL
CMake Warning at /home/hadjigax/kokkosInstallationCUDA/lib64/cmake/Kokkos/KokkosConfigCommon.cmake:59 (MESSAGE):
  The installed Kokkos configuration does not support CXX extensions.
  Forcing -DCMAKE_CXX_EXTENSIONS=Off
Call Stack (most recent call first):
  /home/hadjigax/kokkosInstallationCUDA/lib64/cmake/Kokkos/KokkosConfig.cmake:56 (INCLUDE)
  CMakeLists.txt:7 (find_package)


-- kokkos_launch_compiler is enabled globally. C++ compiler commands with -DKOKKOS_DEPENDENCE will be redirected to the appropriate compiler for Kokkos
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hadjigax/Desktop/KokkosApps/stream/buildCUDA

```

And when I compile everything looks good:
```
[ 50%] Building CXX object CMakeFiles/myTarget.dir/main.cpp.o
[100%] Linking CXX executable myTarget
[100%] Built target myTarget

```

But when I run I get this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos failed to allocate memory for label "Kokkos::InternalScratchSpace".  Allocation using MemorySpace named "Cuda" failed with the following error:  Allocation of size 64.12 K failed because of an unknown error.  (The allocation mechanism was cudaMalloc().  The Cuda allocation returned the error code "cudaErrorNotSupported".)

```

If I use nvidia's `compute-sanitizer` to launch the executable, the output is quite big so I will not throw it all here, however, I see that at some point there is this comment:
```
========= COMPUTE-SANITIZER
========= Program hit cudaErrorNotSupported (error 801) due to "operation not supported" on CUDA API call to cudaMallocAsync.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x44a116]
=========                in /lib64/libcuda.so.1
=========     Host Frame:cudaMallocAsync [0x6ed32]

```

I hope my description is sufficient to point out the issue I am facing!
Any help would be greatly appreciated!

**Comment by masterleinad** [comment]
It seems that your setup just doesn't support `cudaMallocAsync`. What is your `Cuda` driver version and your toolkit version?
As a workaround, you could avoid using that function by configuring `Kokkos` with `Kokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF`

**Comment by ahadji05** [comment]
Perfect, it worked after reinstalling Kokkos using the recommended flag.

Thanks a bunch!

**Comment by ajpowelsnl** [comment]
@ahadji05 - let us know if we can help with anything else!
