### ISSUE TITLE
Broken Things Need Fixing

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#685]
* ~~Apollo: Warning Issue with Clang3.9 Probably fixed now.~~
* ~~KokkosDev / Cuda7.0: cuda.team_vector() MisalignedAddress (Cuda 7.5 and 8.0 passed)~~
* ~~Bowman / GCC 6.2 (hwloc): sort.unsigned hangs: I believe this is team scan (Greg)~~
* Bowman / Intel17.0.098 (hwloc) threads.triple_nested_parallelism: wrong answer (Dan)
* ~~Shepard PGI 17.1: License Issue (Si)~~
* Sullivan: issue with building on compute node (Si)
* ~~White Cuda Kepler RDC: cuda.team_scan: misaligned address~~
* White Cuda Pascal RDC: cuda.task_fib: unspecified launch error if I change the test to take one level less it passes (Greg)
* Kokkos-Develop openmp.task_fib: segmentation fault (intermittend)
* ~~White OpenMP GCC 5.4: team_scan on OpenMP (Nathan)~~

**Comment by ndellingwood** [comment]
The OpenMP GCC 5.4 error is strange. Looking more closely at the reported error message output

`01:15:02 ScanTeamFunctor[1.1 of 10.2] answer(3) != scan_first(2) or scan_second(3)`

This output occurs in the ScanTeamFunctor when `answer != result || answer != result2` but from the output it shows `answer = 3` and `result2 = 3` - unclear why the if statement is entered (triggering the output and setting `error = 1` which leads to the `ASSERT_EQ` failure in the `team_scan` unit test)

**Comment by crtrott** [comment]
Yeah but result1 is 2 right? Basically result and result2 should be equal and they are not. So their is a race condition happening which should not occur. What this most likely means is that operations don't block the way they are supposed to be considering that they are probably sharing the same scratch space. There shouldn't be a barrier necessary from the user perspective, race conditions on internal stuff must be handled by Kokkos.

**Comment by ndellingwood** [comment]
@crtrott Right, I didn't look at that carefully enough. Thanks for clarifying.

**Comment by crtrott** [comment]
Ok I think I got the misaligned address thing sorted out. Running tests right now. #686

**Comment by crtrott** [comment]
Dan thinks he might have found the root cause: basically barriers can overtake each other if a thread is delayed enough. That needs fixing ...

**Comment by nmhamster** [comment]
@crtrott PGI License issue is fixed, problem now is that the link fails due to missing symbols. This is reported to PGI as a bug and will be fixed in a future release .. or .. we can remove `Synchronic`.

**Comment by crtrott** [comment]
Thats already fixed (by removing synchronic), PGI passed on Jenkins since Friday.

**Comment by crtrott** [comment]
Still not fixed on KNL ...

**Comment by crtrott** [comment]
triple nested parallelism test still intermittent failure on KNL

**Comment by crtrott** [comment]
Btw. the triple nested parallelism thing has also intermittent failures on master ...

**Comment by hcedwar** [comment]
No need to retain this "project" issue, most all nested issues have been closed and remaining identified bugs have their own issue.
