### ISSUE TITLE
Consider aborting instead of throwing an exception in view out-of-bound accesses

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#6851]
(Discussion started by Stan on Slack)

Throwing an exception makes things awkward when using multiple MPI ranks.
There does not seem to be a good reason to throw form the host side.
The code that does the out-of-bound check is there
https://github.com/kokkos/kokkos/blob/04a5334c699cb9b87293d27bc73090b3b7c13019/core/src/impl/Kokkos_ViewMapping.hpp#L4016-L4023

We should just call abort instead of throwing.

**Comment by stanmoore1** [comment]
Thank you @dalg24!
