### ISSUE TITLE
nvcc_wrapper does not treat '--disable-warnings' properly

### ISSUE THREAD

**Issue by NamjaeChoi** [kokkos/kokkos#6874]
If `--disable-warnings` is passed to `nvcc_wrapper`, it cannot process the option properly and eventually throws an error during compilation:

`cc1plus: error: unknown pass warnings specified in '-fdisable'`

It can be reproduced by compiling an arbitrary source file with the option.

**Comment by masterleinad** [comment]
We just don't treat this variable in `nvcc_wrapper`.

**Comment by NamjaeChoi** [comment]
OK.

**Comment by dalg24** [comment]
> We just don't treat this variable in `nvcc_wrapper`.

Any good reason why we couldn't/shouldn't add support for it?  https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#disable-warnings-w

**Comment by crtrott** [comment]
Yeah we can just add it.

**Comment by ajpowelsnl** [comment]
@rgayatri23 - is this issue complete?  If so, please close.  If not, what's left to do?  Please remember to update the documentation , also 😄
