### ISSUE TITLE
Allocate L2 scratchpad on-demand

### ISSUE THREAD

**Issue by cartoonist** [kokkos/kokkos#6885]
I could not join Slack to ask my question, so I'm creating an issue. I hope it is fine.

I am implementing an algorithm that allocate a fixed-size small (1K) 1D array on the first-level scratch space and another bigger one (32M) on the second-level *per team*. On CUDA, the arrays on L1 are allocated on per-block shared memory and the L2 array on global memory if I'm not mistaken. The algorithm is designed such that teams use L1 array with much higher probability and rarely use L2 arrays. Since all teams should allocate their L2 arrays, it limits the number of (active) teams depending on available global memory. I am looking for a way to allocate them on-demand so that I can tune the grid size with smaller blocks (which leads to more concurrent blocks).

What is the conventional way in Kokkos programming model to request memory from L2 on demand such that it is shared among threads in a team? What if each thread in a team call `get_shmem` irregularly if needed more space? Would it work as expected here considering that total allocated memory on L2 is less than what is required for all active teams?

Side question: is it safe to assume that per-block shared memory in CUDA is equivalent to per-team shared memory in Kokkos?

By the way, is it possible to add `@uni-bielefeld.de` domain to Slack? That would be fantastic! Thanks!

**Comment by ajpowelsnl** [comment]
Hello @cartoonist - many thanks for your question.  Sign up for Kokkos Slack here:  https://kokkosteam.slack.com/.

**Comment by dalg24** [comment]
See how to contact us to get an invitation if not able to join in the [FAQ](https://kokkos.org/kokkos-core-wiki/faq.html)
We are currently using the free version of Slack and we maxed out the number of domain we can add to the whitelist :/

**Comment by dalg24** [comment]
You don't get to control cache levels in C++ nor in CUDA, it is not a Kokkos limitation.  You allocate memory in global device memory by using Kokkos level-1 scratch pads and you play with the access pattern in your code.

> Side question: is it safe to assume that per-block shared memory in CUDA is equivalent to per-team shared memory in Kokkos?

Yes

**Comment by dalg24** [comment]
Christian pointed out to me that I had misread what you were asking and that you were just calling L1/L2 what we call level 0 and 1 of scratch pad in Kokkos.  Your understanding of what we do in CUDA is right.
And no you cannot do it "on demand", you need to ask for the same thing for all teams/all threads.

**Comment by cartoonist** [comment]
Referring to level-0 and level-1 scratch pads as L1/L2 were indeed misleading. Sorry. And thanks for your answers!
