### ISSUE TITLE
adjacent_difference should not allow running with source being the same as destination

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#6890]
Right now, it is possible to run
```c++
Kokkos::Experimental::adjacent_difference(space, view, view);
```
According to the [standard](https://eel.is/c++draft/numeric.ops#adjacent.difference-8), it should not be possible.
```
For the overloads with an ExecutionPolicy, the ranges [first, last)
and [result, result + (last - first)) shall not overlap.
```

Affects all Kokkos versions I tried.

**Comment by masterleinad** [comment]
Does this still generate the correct result? Is it a problem if the `Kokkos` implementation is more flexible than `std::adjacent_difference`?

**Comment by aprokop** [comment]
> Does this still generate the correct result? Is it a problem if the `Kokkos` implementation is more flexible than `std::adjacent_difference`?

No, it does not generate correct result. It would be impossible to do that without duplicating the view, which it does not do.

**Comment by fnrizzi** [comment]
on https://en.cppreference.com/w/cpp/algorithm/adjacent_difference
am i missing it or the precondition is not stated ?

**Comment by aprokop** [comment]
@fnrizzi yes, i didn't see it there when I submitted the issue. I only found it in the other reference.

**Comment by dalg24** [comment]
> on https://en.cppreference.com/w/cpp/algorithm/adjacent_difference am i missing it or the precondition is not stated ?

It does say
> If `op` invalidates any iterator (including any of the end iterators) or modify any elements of the ranges involved, the behavior is undefined.

> Update: I guess they just did not copy the text from the standard. It's in [it](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf).

Look at Andrey waving the Bible.  The current draft has the same paragraph as in cppreference but it also has this remark  https://eel.is/c++draft/adjacent.difference#8 that clearly spell out what the precondition involves.

**Comment by fnrizzi** [comment]
Yes right, I was just surprised the other part of the condition was missing

**Comment by fnrizzi** [comment]
I think what you highlight refers to what requirements "op" should have and so what it should do or not doto its arguments. How the result of op is used is a different thing IMO.

**Comment by fnrizzi** [comment]
In any case, why would it be written so explicitly in working draft but so cryptically in the user documentation?

**Comment by jbigot** [comment]
In any case, it is the responsibility of the user to ensure the preconditions. Here the standard makes no provision for the implementation of `adjacent_difference` to throw an exception, or signal an error in any way. The only thing that could be "fixed" is that the documentation could state the precondition more clearly.

In order to be a good citizen, Kokkos can try to check the precondition at runtime in certain simple cases and in debug mode ( Cf. @yasahi-hpc PR ), but this is just a nicety and goes beyond what the standard mandates.

**Comment by aprokop** [comment]
> In any case, it is the responsibility of the user to ensure the preconditions.

Sure. I do think it falls under the same concept as checking array bounds: a helpful utility to detect errors at early stage.

**Comment by jbigot** [comment]
> Sure. I do think it falls under the same concept as checking array bounds: a helpful utility to detect errors at early stage.

Definitely
