### ISSUE TITLE
Is there have any performance way to get values from a large Cuda View?

### ISSUE THREAD

**Issue by Gxinhu** [kokkos/kokkos#6900]
Greetings!

I desire to retrieve values by a specified index from a vast Cuda View. At present, I employ the `deep_copy` function to duplicate the entire view from CudaSpace to HostSpace, and subsequently perform operations on the HostSpace (I have included the code below). However, I have observed that this approach incurs significant slowness when working with a large View. For instance, it takes approximately 2 seconds to retrieve the `Kokkos::subview(vars,0,0,0,Kokkos::ALL)` from a view with dimensions `vars(double****,256,256,256,4)`. Thus, I am seeking an expedited method to obtain the desired values.

```cpp
void IOUtil::print_vel(const lbm_kokkos::DataArray4D &vars,
                       const std::string &name, size_t iter) {
    auto vars_host = Kokkos::create_mirror_view(vars);
    Kokkos::deep_copy(vars_host, vars);

    int x = -1;
    int y = -1;
    int z = -1;
    for (const auto &watch_point : watch_points_) {
        for (const auto &[key, value] : watch_point) {
            x = value[0];
            y = value[1];
            z = value[2];
            Precision u = 0;
            Precision v = 0;
            Precision w = 0;
            u = vars_host(x, y, z, kU);
            v = vars_host(x, y, z, kV);
            w = vars_host(x, y, z, kV);
            logger_->info("{}_{}: U {}, V {} W {}", name, key, u, v, w);
            save_vel(u, logs_dir_ / ("U" + name + key + ".dat"), iter);
            save_vel(v, logs_dir_ / ("V" + name + key + ".dat"), iter);
            save_vel(w, logs_dir_ / ("W" + name + key + ".dat"), iter);
        }
    }
};
```

**Comment by masterleinad** [comment]
Are you doing
```
Kokkos::View<double****, DeviceMemorySpace> vars;
auto subview_vars = Kokkos::subview(vars, 0, 0, 0, Kokkos::ALL);
auto host_subview_vars = Kokkos::create_mirror_view_and_copy(subiew_vars);
```
already? I wouldn't expect that to take that long.

**Comment by Gxinhu** [comment]
> auto host_subview_vars = Kokkos::create_mirror_view_and_copy(subiew_vars);

I apologize for the confusion caused by my typos. The code with the full deep copy took 2 seconds, not the subview.

> auto subview_vars = Kokkos::subview(vars, 0, 0, 0, Kokkos::ALL);
> auto host_subview_vars = Kokkos::create_mirror_view_and_copy(subiew_vars);

I'm also trying to deep copy just the subview using the following code, but it encounters a runtime error. The error message is: "terminate called after throwing an instance of 'std::runtime_error': Error: Kokkos::deep_copy with no available copy mechanism: vars to vars".

```cpp
void IOUtil::print_vel(const lbm_kokkos::DataArray4D &vars,
                       const std::string &name, size_t iter) {
  auto vars_host = Kokkos::create_mirror_view(vars);
  int x          = -1;
  int y          = -1;
  int z          = -1;
  for (const auto &watch_point : watch_points_) {
    for (const auto &[key, value] : watch_point) {
      x                      = value[0];
      y                      = value[1];
      z                      = value[2];
      Precision u            = 0;
      Precision v            = 0;
      Precision w            = 0;
      auto subview_vars      = Kokkos::subview(vars, x, y, z, Kokkos::ALL);
      auto host_subview_vars = Kokkos::create_mirror_view_and_copy(
          Kokkos::DefaultHostExecutionSpace(), subview_vars);
      u = host_subview_vars(kU);
      v = host_subview_vars(kV);
      w = host_subview_vars(kV);
      logger_->info("{}_{}: U {}, V {} W {}", name, key, u, v, w);
      save_vel(u, logs_dir_ / ("U" + name + key + ".dat"), iter);
      save_vel(v, logs_dir_ / ("V" + name + key + ".dat"), iter);
      save_vel(w, logs_dir_ / ("W" + name + key + ".dat"), iter);
    }
  }
};

```

**Comment by Gxinhu** [comment]
> You can do
> 
> ```c++
> Kokkos::View<double****> vars("vars", 256,256,256,4);
> auto subview_vars = Kokkos::subview(vars, 0, 0, 0, Kokkos::ALL);
> Kokkos::View<double*> tmp("tmp", 4);
> Kokkos::deep_copy(tmp, subview_vars);
> auto host_subview_vars = Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace{}, tmp);
> ```

Thank you for your guidance. I followed your instructions, but I noticed that the process still takes 2 seconds. Therefore, I created a small demo to evaluate the copy time, as shown below. Upon investigation, I realized that the method I previously used to calculate the duration was incorrect; it merely involved printing the duration.

Interestingly, altering the `print_iter` parameter also affected the printed duration time. To accurately assess the copy time, I employed the Kokkos tool simple-kernel-timer. Surprisingly, the actual copy time turned out to be much faster. It appears that the issue lies with the printing.

P.S. When I was using the simple-kernel-timer profiler, the printed duration time is correct.
```cpp
#include <chrono>
#include <iostream>

#include "kokkos/Kokkos_Core.hpp"
KOKKOS_INLINE_FUNCTION
void index2coord(size_t index, int &i, int &j, int &k, size_t Nx, size_t Ny,
                 size_t Nz) {
  size_t ny_nz = Ny * Nz;
  i            = index / ny_nz;
  j            = (index - i * ny_nz) / Nz;
  k            = index - j * Nz - i * ny_nz;
}
class VarsTest {
 public:
  VarsTest(Kokkos::View<double ****> vars) : vars_(std::move(vars)){};
  static void apply(const Kokkos::View<double ****> &vars) {
    VarsTest functor(vars);
    Kokkos::parallel_for(256 * 256 * 256, functor);
  }

  KOKKOS_INLINE_FUNCTION
  void operator()(const int &index) const {
    int i = -1;
    int j = -1;
    int k = -1;
    index2coord(index, i, j, k, 256, 256, 256);
    vars_(i, j, k, 0) = i * 0.25 + j * 3.9 * k;
    vars_(i, j, k, 1) = i * 0.25 + j * 3.9 * k;
    vars_(i, j, k, 2) = i * 0.25 + j * 3.9 * k;
    vars_(i, j, k, 3) = i * 0.25 + j * 3.9 * k;
  }

 private:
  Kokkos::View<double ****> vars_;
};
void print_vel(const Kokkos::View<double ****> &vars) {
  auto subview_vars = Kokkos::subview(vars, 128, 128, 128, Kokkos::ALL);
  Kokkos::View<double *> tmp("tmp", 4);
  Kokkos::deep_copy(tmp, subview_vars);
  auto host_subview_vars =
      Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace{}, tmp);
}
int main(int argc, char *argv[]) {
  Kokkos::initialize(argc, argv);
  int print_iter = 100;
  int max_iters  = 2000;
  Kokkos::Timer timer;
  {
    Kokkos::View<double ****> vars("vars", 256, 256, 256, 4);
    print_vel(vars);
    for (int iter = 0; iter < max_iters; ++iter) {
      VarsTest::apply(vars);

      if (iter % 100 == 0) {
        std::cout << iter << "\n";
      }
      if (iter % print_iter == 0) {
        timer.reset();
        print_vel(vars);
        std::cout << "Duration is : " << timer.seconds() << "\n";
      }
    }
  }
  Kokkos::finalize();
  return 0;
}

```

**Comment by ajpowelsnl** [comment]
@Gxinhu - can we help you with anything else?

**Comment by Gxinhu** [comment]
> @Gxinhu - can we help you with anything else?

Thank you. My problem solved.
