### ISSUE TITLE
How to run kokkos code into NVIDIA GPUs

### ISSUE THREAD

**Issue by arayannmsra76** [kokkos/kokkos#6901]
Hello; I am a Bsc student and working on Kokkos Project first time. I am writing a code into Kokkos but i was not able to run code on HPC NVIDIA GPU and i am able to make Slurm.sh file also. I am using on Two 64-bit 18-core [Intel Xeon Gold 6140](https://ark.intel.com/products/120485/Intel-Xeon-Gold-6140-Processor-24_75M-Cache-2_30-GHz) processors (36 cores per node) 1.5TB of RAM per node 8 [NVIDIA Tesla V100](https://images.nvidia.com/content/technologies/volta/pdf/tesla-volta-v100-datasheet-letter-fnl-web.pdf) GPUs per node with 32GB of HBM2 VRAM each (5120 CUDA cores per card, 640 Tensor cores per card). please help me how i can run kokkos code into the NVIDIA GPUs. Is there any command line module to install to run.

Another problem; i have a CUDA code and i convert into Kokkos to run into multiple GPUs and CPUs, how i can run into different GPUs. Is there any command line. Right now i am using gcc11 compilers. 

Another issues on my HPC is cmke CMake confguration, and output CMake configure command. 

1. Compilers (with versions)
2. Kokkos release or commit used (i.e., the sha1 number)
3. Platform, architecture and backend
4. CMake configure command
5. Output from CMake configure command
6. Minimum, complete code needed to reproduce the bug
7. Command line needed to reproduce the bug
8. `KokkosCore_config.h` header file (generated during the build)
9. Please provide any additional relevant error logs

**Comment by masterleinad** [comment]
Please join slack at https://kokkosteam.slack.com for this kind of help request. Let us know if you have trouble joining.

**Comment by arayannmsra76** [comment]
I have an issue on joining slack; I did not have email which have .gov, please help me how to connect on slack

**Comment by masterleinad** [comment]
What's your e-mail address?

**Comment by arayannmsra76** [comment]
My email is arayannmsra76@gmail.com
