### ISSUE TITLE
sort to accept DynamicView and [begin,end) indices

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#691]
I need to sort DynamicViews.  To do so I need to create a subview of a dynamic view.
Here is my routine

Can we add at least subviews with slightly smaller lengths for dynamic view?
```

  int max_elems = MapContainer::getElementMap()->getNodeNumElements();
  int min_elems = 0, num_elems = max_elems-min_elems+1;
  BinOp binner(num_elems, min_elems, max_elems);

  Kokkos::pair<size_t, size_t> reduced_size(0,size());
  KeyViewType local_ielement = Kokkos::subview(element_, reduced_size);

  Kokkos::BinSort<KeyViewType , BinOp > Sorter(local_ielement,binner,false);
  Sorter.create_permute_vector();
  Sorter.sort< KeyViewType >(local_ielement);

  Sorter.sort(Kokkos::subview(x_, reduced_size));
  Sorter.sort(Kokkos::subview(x_ref_, reduced_size));
  Sorter.sort(Kokkos::subview(v_, reduced_size));
  Sorter.sort(Kokkos::subview(v_ref_, reduced_size));
```

**Comment by crtrott** [comment]
Would it be sufficient to provide only a subview function outside of parallel kernels? 
Also: as a minimum requirement subviews would not be growable themselves, and shrinking the original view while a subview exist is undefined behavior.

**Comment by bathmatt** [comment]
Thats fine for buy use case

**Comment by hcedwar** [comment]
@bathmatt : how urgent?
This appears to be two enhancements: 

- subview  of DynamicView and 
- sort algorithm to accept subview of DynamicView

To create a subview it would have to be aligned with the DynamicView chunking - it cannot be arbitrary.

**Comment by bathmatt** [comment]
Pretty urgent. couple weeks...

**Comment by hcedwar** [comment]
Follow up conversation with @bathmatt 
Root requirement is to sort a subrange of a DynamicView.
The subview discussion is only due to the current sort functions' interface only working on a full View so that a subview must currently be created to sort a subrange.
The root requirement can be satisfied at lower effort with sort functions that accept a DynamicView and [begin,end) range indices.

**Comment by hcedwar** [comment]
@bathmatt 
A unit test applying ```Kokkos::sort``` to a ```Kokkos::Experimental::DynamicView``` is now in the develop branch.
https://github.com/kokkos/kokkos/blob/develop/algorithms/unit_tests/TestSort.hpp#L206
Please have a look as to whether the capability is sufficient for your use case.
