### ISSUE TITLE
Bug when compiling with CUDA backend

### ISSUE THREAD

**Issue by nvarini12** [kokkos/kokkos#6911]
Dear community, I am experiencing a bug when I enable kokkos with cuda backend
```
/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(407): error: identifier "__short2bfloat16_rn" is undefined

/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(409): error: identifier "__ushort2bfloat16_rn" is undefined

/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(411): error: identifier "__int2bfloat16_rn" is undefined

/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(413): error: identifier "__uint2bfloat16_rn" is undefined

/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(415): error: identifier "__ll2bfloat16_rn" is undefined

/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(417): error: identifier "__ull2bfloat16_rn" is undefined
```
If necessary, I can provide a reproducer.

**Comment by dalg24** [comment]
What version of Kokkos are you using?  How did you configure Kokkos?  What is the CUDA version.

Also that error looks like it occurred **after** Kokkos has been successfully installed which might very well be that the code downstream is not properly setup to build against Kokkos.

Please consider joining us on Slack for this kind of questions.

**Comment by nvarini12** [comment]
I'm using Kokkos v4.2.01.
I'm using gnu-11.3.0 and cuda-11.8.0.
I've enabled Kokkos_ARCH_AMPERE80 Kokkos_ENABLE_CUDA Kokkos_ENABLE_CUDA_CONSTEXPR Kokkos_ENABLE_CUDA_LAMBDA

I've tried to sign in on slack with my work email, nicola.varini@epfl.ch but I get the error: nicola.varini@epfl.ch doesn’t have an account on this workspace.

**Comment by dalg24** [comment]
Am I guessing right that you get this error downstream, that is in some other code that is using Kokkos?

You need to "sign up".   You will be able to "sign in" once you have created an account.

**Comment by nvarini12** [comment]
@dalg24 I managed to successfully login into slack; if you prefer we can keep discussing there.
The code I want to compile is fairly simple. 
```
#include <cuda_bf16.h>
#include <Kokkos_Core.hpp>
#include "flcl-cxx.hpp"
#include <stdio.h>

extern "C" void spmv_(flcl_ndarray_t *nd_array_x, flcl_ndarray_t *nd_array_y, 
                      flcl_ndarray_t *nd_array_val, flcl_ndarray_t *nd_array_row,
                      flcl_ndarray_t *nd_array_col){
  using flcl::view_from_ndarray;
  auto x = view_from_ndarray<double *>(*nd_array_x);
  auto y = view_from_ndarray<double *>(*nd_array_y);
  auto vals = view_from_ndarray<double *>(*nd_array_val);
  auto rows = view_from_ndarray<int *>(*nd_array_row);
  auto cols = view_from_ndarray<int *>(*nd_array_col);
  Kokkos::parallel_for("testy", y.extent(0), KOKKOS_LAMBDA(const size_t idy){
      for(int idx=rows(idy); idx<rows(idy+1); idx++)
        y(idy) = y(idy) + vals(idx)*x(cols(idx));
  });
}
```
And is compiled as following:
```
/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//bin/nvcc_wrapper -I/leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install//include --extended-lambda -I/leonardo/prod/opt/compilers/cuda/11.8/none/targets/x86_64-linux/include/ -cpp   -c -o spmv.o spmv.cc
```

You can find a reproducer here:
https://drive.google.com/file/d/17jqLJaMyWSuAe6XSVeXzXnGsM_R2DXCy/view?usp=sharing

**Comment by dalg24** [comment]
Why did you include `<cuda_bf16.h>` (in the snippet above that is your `spmv.cc`)?

The main issue is you attempted to write your own makefile
```
KOKKOS_ROOT = /leonardo_work/FUSIO_HLST_4/nvarini/hpc-stack/kokkos-install/
FC = gfortran
CXX = $(KOKKOS_ROOT)/bin/nvcc_wrapper
CXXFLAGS = -I$(KOKKOS_ROOT)/include --extended-lambda -I/leonardo/prod/opt/compilers/cuda/11.8/none/targets/x86_64-linux/include/ -cpp
HDF5_ROOT = ${HDF5_HOME}
FCFLAGS = -I$(HDF5_ROOT)/include -std=f2008
LDFLAGS = -L$(HDF5_ROOT)/lib -lhdf5 -lhdf5_fortran
FCFLAGS += -I$(KOKKOS_ROOT)/include
LDFLAGS += -L$(KOKKOS_ROOT)/lib64 -lm -fopenmp  -lc -lflcl -lkokkoscore  -lstdc++ -ldl -lgfortran

%.o:%.F90
        $(FC) $(FCFLAGS) -c -o $@ $<

%.o:%.cxx
        $(CXX) $(CXXFLAGS) -c -o $@ $<

miniapp: miniapp.o spmv.o
        $(CXX) -o  $@ miniapp.o spmv.o $(LDFLAGS)

clean:
        rm -rf miniapp *.o *.mod
```
Specifying the include path to Kokkos and a few extra flags is not sufficient.

Consider using CMake and please refer to the examples herehttps://github.com/kokkos/kokkos/tree/e0dc0128e04f18c2bbbaefceef3616e7ddcfa3c4/example/build_cmake_installed  and in the fortran-interop repository https://github.com/kokkos/kokkos-fortran-interop/tree/d38378923d3362ee581bcae80140fb8c1c8e58fb/examples

Considering that this is not an issue in Kokkos Core but really an issue in your code, it would be more appropriate to close this and continue the conversation on Slack.

**Comment by nvarini12** [comment]
Ok, I'll try to use CMake and see if that fix the issue.
I added ```<cuda_bf16.h>``` since make complained about certain types of errors 
```error: identifier "__short2bfloat16_rn" is undefined```
___short2bfloat16_rn is defined in cuda_bf16.h

**Comment by nvarini12** [comment]
Contiuing the discussion on slack

**Comment by jkhansell** [comment]
I'm having the same problem. Can I join the slack conversation?

**Comment by dalg24** [comment]
https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1712150388641909

**Comment by jkhansell** [comment]
Hi, I'm from outside the insitutions available in the sign up page. How can I sign up?

**Comment by masterleinad** [comment]
> Hi, I'm from another institution apart from the insitutions available in the sign up page. How can I sign up?

What's your e-mail address?

**Comment by jkhansell** [comment]
jovillalobos@cenat.ac.cr

**Comment by ajpowelsnl** [comment]
@masterleinad , @nvarini12 , @jkhansell -- I had the same problem, and was able to correct by making sure the architecture was correctly set everywhere (i.e., in `CXX_FLAGS`, in `nvcc_wrapper`, etc.).  I don't think it's a CMake or Makefile issue, as  such, but rather an architecture mismatch.

**Comment by masterleinad** [comment]
> @masterleinad , @nvarini12 , @jkhansell -- I had the same problem, and was able to correct by making sure the architecture was correctly set everywhere (i.e., in `CXX_FLAGS`, in `nvcc_wrapper`, etc.). I don't think it's a CMake or Makefile issue, as such, but rather an architecture mismatch.

That would mean that it is a build system issue since `Kokkos` (should) propagate the correct architecture flags.
