### ISSUE TITLE
Kokkos update for CUDA lambda implementation?

### ISSUE THREAD

**Issue by DaPiePiece** [kokkos/kokkos#6913]
Hello, I'm running into a new IntelliSense issue with VScode that started happening over the weekend. Opening up my kokkos code this monday (01/03/2024), IntelliSense started giving this error: 

``function "lambda []()->auto" cannot be called with the given argument list
argument types are: (<error-type>)
object type is: lambda []()->auto``

For the following code:

```c++
Kokkos::parallel_for("Initialisation", nCell, KOKKOS_LAMBDA (int i) {
   q0(i, 0) = 1;
});
```

With q0 being a two dimensional View with one runtime and one compile time dimension. This happens only when setting up IntelliSense with CUDA, for which the compiler replaces KOKKOS_LAMBDA with [=] \_\_host\_\_ \_\_device\_\_. Replacing the KOKKOS_LAMBDA macro with a simple C++ lambda [=] removes the IntelliSense issue, and surprisingly, correctly compiles afterwards with make. It is important to note that this is purely an IntelliSense issue, as the code still compiles with the KOKKOS_LAMBDA macro. Unfortunately I rely on IntelliSense a lot, so I cannot simply ignore it or use a different IDE.

Has there been an update that removes the need to use the \_\_device\_\_ tag in lambdas when compiling for CUDA? 

- CMake Version 3.22.1
- CUDA Version 11.5
- clang-17 and clang++-17 compiler with CUDA workaround
- Kokkos version 4.2.1
- c++17 standard
- CUDA sm86 architecture
- CUDAToolkit version 11.5.119

**Comment by dalg24** [comment]
> Has there been an update that removes the need to use the __device__ tag in lambdas when compiling for CUDA?

No there was not.  The annotation is still needed.  It sounds more like an update in your IDE settings. 

Here is a link to the CUDA toolkit documentation for the version you are using https://docs.nvidia.com/cuda/archive/11.5.1/cuda-c-programming-guide/#extended-lambda

Feel free to join us on Slack and ask on there if anyone else is using a similar IDE and might be able to help.

**Comment by DaPiePiece** [comment]
I see! I would love to join Slack but my institution isn't part of the list. How do I go about requesting access to the Slack?

**Comment by dalg24** [comment]
See the entry about how to join slack in the FAQ https://kokkos.org/kokkos-core-wiki/faq.html
It has instruction on how to contact me or Christian to get an invitation.

**Comment by DaPiePiece** [comment]
Sent an email to Christian. Closing the issue. Thanks.

**Comment by dalg24** [comment]
> Sent an email to Christian. Closing the issue. Thanks.

He is off today so try me if this is time sensitive.
