### ISSUE TITLE
Implementing Kokkos for Cross-Platform Efficiency

### ISSUE THREAD

**Issue by khoinguyyyen** [kokkos/kokkos#6915]
Purpose:
   - additional implementation to support a single CPU, multithreaded CPU, GPU
   - will not need to change code for different types of computers
   
  **opened issue to track upcoming work

**Comment by dalg24** [comment]
What is this about?  Did you open this issue in order to track progress on some upcoming work?

**Comment by khoinguyyyen** [comment]
> What is this about? Did you open this issue in order to track progress on some upcoming work?

yes

**Comment by crtrott** [comment]
Can you elaborate what the goal of this work is?
