### ISSUE TITLE
Static member data and cuda

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#692]
I've got a static member and nvcc is giving an odd error, is this not allowed?

```
struct ParticleTypes{
  ParticleTypes(bool read_defaults=false);
  static Kokkos::View<ParticleType*> types;
```

and later I try the following
```
  KOKKOS_INLINE_FUNCTION ParticleType operator [](int i) const {return types(i);}
```

and when I compile it complains about the line above as

/home/mbetten/Trilinos/mini-PIC/src/PIC/ParticleTypes.hpp(37): warning: address of a host member "PIC::ParticleTypes::types" cannot be directly taken in a device function

**Comment by mhoemmen** [comment]
@bathmatt -- any particular reason why`types` is `static`?

**Comment by crtrott** [comment]
static members are host variables only. You can't have device side static members. That means if you try to access types you access a host variable. It might actually work with NVLINK 2.0 on Sierra, but it doesn't work on our current platform as far as I can tell.

**Comment by bathmatt** [comment]
I want a singlton basically, a single instance which every class can access and add to.  What is the best way to do this?

I chose a static data type, typically a RCP would be used, but that also doesn't work, then I have the everyone gets a copy, but this doesn't work with resizing and obsoleting views.

**Comment by mhoemmen** [comment]
@bathmatt You could lift management of singleton status out of the class itself (make the class just a regular old instance-y thing) and into your application.

**Comment by bathmatt** [comment]
@mhoemmen I'm not sure how to do this sort of thing.  

The issue is that kokkos invalidates views when they grow, so you either need a RCP to the view or some other thingy.  But with RCP you can't access that view from device.  So, I had everyone point to a static.  That doesn't work as well, so it sounds like I'm stuck refreshing my local copy from a RCP and managing this in all my classes.

**Comment by crtrott** [comment]
If you really really want to do this you can allocate a pointer to your view with Kokkos::kokkos_malloc and pass that pointer around (kind of like a view of views). But now every data access is going through to pointer dereferences (like a  view of view, or pointer of pointers).

**Comment by mhoemmen** [comment]
> so it sounds like I'm stuck refreshing my local copy from a RCP and managing this in all my classes.

that's kinda what I meant, sorry ;-)
