### ISSUE TITLE
Move `layout_iterate_type_selector` into `Impl` namespace

### ISSUE THREAD

**Issue by masterleinad** [kokkos/kokkos#6923]
Follow up we should move the `layout_iterate_type_selector` into `Impl` namespace. There is no reason it should be public. Note this thing is used in stuff like ViewCopy to figure out the type of the `MDRangePolicy`.

_Originally posted by @crtrott in https://github.com/kokkos/kokkos/pull/6907#pullrequestreview-1984244986_

**Comment by jbadwaik** [comment]
I'll be interested to work on it.

**Comment by dalg24** [comment]
We need to mark it as deprecated and defer to the trait class that definition that we move into `Impl::`.

**Comment by nliber** [comment]
Any reason this issue is still open?
