### ISSUE TITLE
Performance regression, serial backend on Sapphire Rapids

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#6928]
**Describe the bug**

After the Kokkos 4.3.0 release was merged into Trilinos, we noticed a couple of performance regressions in Tpetra benchmarks on amber (CTS-2). One is FE assembly, and the other is distributed sparse matrix-sparse matrix multiply. I haven't measured down to individual kernels but the slowdown is roughly 1.8x in FE assembly and 1.1x in MM multiply.

I ran a bisect and found 27286c3 to be the first commit with the slowdown for both benchmarks. Building that version with
``-DKokkos_ENABLE_ATOMICS_BYPASS=ON`` gets the old behavior back and fixes the regressions.

Is this something that is fixable? If so, and a specific reproducer is needed, is a Trilinos based reproducer ok or should I reduce one of these examples down to pure Kokkos?

**Please include the following for a minimal reproducer**

1. Compiler: Intel 2021.3.0.20210609
2. Kokkos version with issue: 27286c3. First release with this commit is 4.3.0.
3. CTS-2 Sapphire Rapids (Xeon 8480+)

KokkosCore_config.h from building that specific commit, without the atomics bypass enabled:
```
// KOKKOS_VERSION % 100 is the patch level
// KOKKOS_VERSION / 100 % 100 is the minor version
// KOKKOS_VERSION / 10000 is the major version
#define KOKKOS_VERSION 40299
#define KOKKOS_VERSION_MAJOR 4
#define KOKKOS_VERSION_MINOR 2
#define KOKKOS_VERSION_PATCH 99

/* Execution Spaces */
#define KOKKOS_ENABLE_SERIAL
/* #undef KOKKOS_ENABLE_OPENMP */
/* #undef KOKKOS_ENABLE_OPENACC */
/* #undef KOKKOS_ENABLE_OPENMPTARGET */
/* #undef KOKKOS_ENABLE_THREADS */
/* #undef KOKKOS_ENABLE_CUDA */
/* #undef KOKKOS_ENABLE_HIP */
/* #undef KOKKOS_ENABLE_HPX */
/* #undef KOKKOS_ENABLE_MEMKIND */
/* #undef KOKKOS_ENABLE_LIBRT */
/* #undef KOKKOS_ENABLE_SYCL */
/* #undef KOKKOS_IMPL_SYCL_DEVICE_GLOBAL_SUPPORTED */

/* General Settings */
#define KOKKOS_ENABLE_CXX17
/* #undef KOKKOS_ENABLE_CXX20 */
/* #undef KOKKOS_ENABLE_CXX23 */

/* #undef KOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_CUDA_UVM */
/* #undef KOKKOS_ENABLE_CUDA_LAMBDA */
/* #undef KOKKOS_ENABLE_CUDA_CONSTEXPR */
#define KOKKOS_ENABLE_IMPL_CUDA_MALLOC_ASYNC
/* #undef KOKKOS_ENABLE_HIP_RELOCATABLE_DEVICE_CODE */
/* #undef KOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS */
/* #undef KOKKOS_ENABLE_IMPL_HPX_ASYNC_DISPATCH */
/* #undef KOKKOS_ENABLE_DEBUG */
/* #undef KOKKOS_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK */
/* #undef KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK */
/* #undef KOKKOS_ENABLE_TUNING */
#define KOKKOS_ENABLE_DEPRECATED_CODE_4
#define KOKKOS_ENABLE_DEPRECATION_WARNINGS
/* #undef KOKKOS_ENABLE_LARGE_MEM_TESTS */
/* #undef KOKKOS_ENABLE_COMPLEX_ALIGN */
/* #undef KOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION */
/* #undef KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION */
/* #undef KOKKOS_ENABLE_IMPL_MDSPAN */
/* #undef KOKKOS_ENABLE_ATOMICS_BYPASS */

/* TPL Settings */
/* #undef KOKKOS_ENABLE_HWLOC */
/* #undef KOKKOS_USE_LIBRT */
/* #undef KOKKOS_ENABLE_HBWSPACE */
#define KOKKOS_ENABLE_LIBDL
/* #undef KOKKOS_ENABLE_LIBQUADMATH */
/* #undef KOKKOS_ENABLE_ONEDPL */

...
#define KOKKOS_ARCH_AVX512XEON
```

**Comment by brian-kelley** [comment]
@csiefer2

**Comment by dalg24** [comment]
Are you using atomics?

**Comment by brian-kelley** [comment]
@dalg24 Yes, at least in one of the sub-timers of the FE assembly there are some atomic_adds on double. The other sub-timer that slowed down a lot doesn't have atomics we put there, but I suspect it's heavy on view reference count increments/decrements.

**Comment by brian-kelley** [comment]
Never mind, I see you said that in the PR

**Comment by dalg24** [comment]
Since #6692 you have to explicitly say it at configuration time (by passing `-DKokkos_ENABLE_ATOMICS_BYPASS=ON`) if you really want to disable atomics.  We had to choose between performance and correctness.

**Comment by stanmoore1** [comment]
This is news to me too, glad I saw this issue, now I need to go put that flag in LAMMPS...

**Comment by dalg24** [comment]
If and only if you do **Serial only** build (that is you don't enable any other backend) AND you **measured** you get a performance regression AND you are sure that your end-user program will be correct with that setting.

**Comment by stanmoore1** [comment]
> If and only if you do **Serial only** build (that is you don't enable any other backend) AND you **measured** you get a performance regression AND you are sure that your end-user program will be correct with that setting.

Atomics are so slow on CPUs, I don't see how this couldn't lead to a perf regression for the Serial Backend, but I will measure...

**Comment by crtrott** [comment]
Note its here in the CHANGELOG: https://github.com/kokkos/kokkos/blob/master/CHANGELOG.md#build-system-changes

**Comment by crtrott** [comment]
And we are planning to cover that in the release briefing.

**Comment by brian-kelley** [comment]
@dalg24 If you do disable atomics, will ``partition_space(Kokkos::Serial)`` then trigger a static_assert or an exception?

**Comment by dalg24** [comment]
> @dalg24 If you do disable atomics, will `partition_space(Kokkos::Serial, ...)` then trigger a static_assert or an exception?

No it will not.

**Comment by brian-kelley** [comment]
@dalg24 That might be a nice thing to add (make it basically impossible to shoot yourself in the foot with the atomics bypass option)
