### ISSUE TITLE
Creating a view with a non-default constructor

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#694]
Can one create a view with the non-default constructor?

**Comment by mhoemmen** [comment]
@bathmatt could you clarify?

**Comment by bathmatt** [comment]
I guess I want to 
Kokkos::View<MyType*> view("v",100, (args ... ) )
and it will call MyType(args....)
and not copy.  

This is partly because I have my copy constructor disabled

**Comment by crtrott** [comment]
Args Matt ... you come up with the funniest things. You can do this today manually (and even more flexible in some sens) by creating an unitialized view, and then launch a kernel where you placement new allocate the individual objects.

**Comment by crtrott** [comment]
If you need an example I can write one for you.

**Comment by bathmatt** [comment]
If you can point to an example that would be great.

and Args is what I scream when I can't figure something out.

**Comment by crtrott** [comment]
You will still need a default constructor (not much we can do about it without tons of internal code I fear) but otherwise this here should work for you:

```c++
#include<Kokkos_Core.hpp>

struct SomeClass {
  double a;
  int b;
  int c;
  KOKKOS_INLINE_FUNCTION
  SomeClass() {printf("Huch Default\n");}

  KOKKOS_INLINE_FUNCTION
  SomeClass(double a_, int b_, int c_):a(a_),b(b_),c(c_) {}

  KOKKOS_INLINE_FUNCTION
  SomeClass(const SomeClass& rhs) = delete;
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  int N = 100000;
  {
    // This view needs to go out of scope before Kokkos::finalize, since deconstruction goes through a parallel loop
    Kokkos::View<SomeClass*> a(Kokkos::ViewAllocateWithoutInitializing("A"),N);

    Kokkos::parallel_for(N, KOKKOS_LAMBDA (const int& i) {
      new (&a(i)) SomeClass(1.0*i*(N-i),i,N-i);
    });

    Kokkos::parallel_for(100, KOKKOS_LAMBDA (const int& i) {
      printf("%i: %i %i %lf\n",i,a(i).b,a(i).c,a(i).a);
    });
  }
  Kokkos::finalize();
}
```

Not this scheme even works if SomeClass is derived and the base class has a virtual function. The virtual function would now be callable on the device.

**Comment by bathmatt** [comment]
Thanks @crtrott this gets around another issue I've been having...  Thanks!
