### ISSUE TITLE
Auto vectorization with use of `parallel_for`

### ISSUE THREAD

**Issue by yencal** [kokkos/kokkos#6953]
Greetings,
Does Kokkos `parallel_for` allow compiler auto-vectorization? For a simple daxpy example, I see orders of magnitude difference between the CPP code and the Kokkos version. I think the issue might be that the compiler does not auto-vectorize Kokkos parallel_for. Below are the code samples.

Original CPP Code:
```
void daxpy(const double a, const double* const x, double* y)
{
  for (size_t i = 0; i < length; i++) {
    y[i] += a * x[i];
  }
}
```

Kokkos version:
```
void daxpy(const double a, const double* const x, double* y)
{
  Kokkos::parallel_for(
    Kokkos::RangePolicy<> (0, length),
    KOKKOS_LAMBDA(const int i){
    y[i] += a * x[i];
  });
}
```
Note that I use the same compiler flags for both codes:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -Ofast -march=native")
```
And I am using M3 MacBook.

Kokkos configure flags:
```
    -D CMAKE_BUILD_TYPE=Release
    -D CMAKE_INSTALL_PREFIX="${KOKKOS_INSTALL_DIR}"
    -D CMAKE_CXX_STANDARD=17
    -D Kokkos_ENABLE_SERIAL=ON
    -D Kokkos_ARCH_NATIVE=ON
    -D Kokkos_ENABLE_TESTS=OFF
    -D BUILD_TESTING=OFF
```

Thanks

**Comment by masterleinad** [comment]
> Does Kokkos parallel_for allow compiler auto-vectorization?

`Kokkos` doesn't prevent the compiler from auto-vectorization. The implementation is https://github.com/kokkos/kokkos/blob/486cc745cb9a287f3915061455105a3ee588c616/core/src/Serial/Kokkos_Serial_Parallel_Range.hpp#L33-L38. So it's a question of how well the compiler can see through the additional indirections. Note that we have experimental SIMD-type support as well.

**Comment by yencal** [comment]
Ok, got it. Thanks

**Comment by science-enthusiast** [comment]
Hi @yencal, Could you tell us which compiler you used on your MacBook?

In #8652 We have observed that GCC with `-O3` consistently leads to auto-vectorization for RangePolicy.
