### ISSUE TITLE
Are Apple Silicon GPU supported?

### ISSUE THREAD

**Issue by Aldric-L** [kokkos/kokkos#6956]
Hi! I'm a new user of Kokkos (please forgive me if this issue is duplicated), and I wonder if Kokkos can take full advantage of built-in GPU cores of Apple Silicon chips. I don't find any mention of Apple chips on this page (https://kokkos.org/kokkos-core-wiki/keywords.html#gpu-architectures), and my tests using a very basic installation do not show any GPU usage. 

Hence, can you please tell me if Apple GPU are supported and where I can find documentation to make Kokkos work with them?
Thanks.

**Comment by masterleinad** [comment]
> Hence, can you please tell me if Apple GPU are supported and where I can find documentation to make Kokkos work with them?

No, Apple GPUs are not supported yet.

**Comment by Aldric-L** [comment]
That's a pity! Thanks anyway for your answer.
