### ISSUE TITLE
Add Tutorial for Matrix Operations Handling

### ISSUE THREAD

**Issue by khoinguyyyen** [kokkos/kokkos#6963]
Adding tutorial involving matrix multiplication
 - This example demonstrates handling memory spaces and utilizing parallel computation for a matrix-matrix multiplication operation
 - Includes Makefile and CMakeLists.txt

**Comment by ajpowelsnl** [comment]
Hi @khoinguyyyen -- In the [kokkos-tutorials](https://github.com/kokkos/kokkos-tutorials), there are at least a couple of examples that might be instructive for your purposes:   `SpGEMM` and `TeamGEMM` (both in `Exercises/kokkoskernels`).  The `Intro-KokkkosKernels` slides provide an overview of BLAS capabilities.  @lucbv can help with more in-depth questions you might have.

**Comment by lucbv** [comment]
Some information would be helpful, it's not clear that this is for sparse matrices, could be dense as well in which case GEMM would be the kernel used. We already have unit-tests and performance tests for this but if something in the tutorial is needed we can also update that. Note that we are not supporting Makefile in any shape or form in Kokkos Kernels...

**Comment by dalg24** [comment]
@khoinguyyyen please advise on what this work is about

**Comment by ajpowelsnl** [comment]
No response to questions.  Closing, because proposed change is not materially different than the information in Tutorial 3.
