### ISSUE TITLE
clamp(v, lo, hi) changed slightly in C++20.  Should we change as well?

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos#6966]
In C++17, `clamp(v, lo, hi)` uses `operator<` to do the comparison.

In C++20 and beyond, `clamp(v, lo, hi)` uses `std::less{}` to do the comparison.  I'm not sure why it changed (I cannot find the LWG issue), but I suspect this has something to do with clamping pointers.

Should we change, and if so, should that change be dependent on the C++ version?

My answer to the above is yes and no.

**Comment by crtrott** [comment]
`std::less` won't work on the device so we would need a `Kokkos::less` ...

**Comment by masterleinad** [comment]
> @nliber , @masterleinad - is this an item for Wednesday discussion?

It's probably good to discuss the direction with some more people.

**Comment by nliber** [comment]
After discussing it on 2024-07-03, we believe that `operator<` is sufficient for our architectures.  Closing the issue for now.
