### ISSUE TITLE
Add --small option to snapshot script

### ISSUE THREAD

**Issue by gmackey** [kokkos/kokkos#697]
It would be useful to have an option for the snapshot script to only copy over the minimum necessary files to include Kokkos in a project.  This would exclude things like tests that aren't needed.  This option with be --small.

**Comment by crtrott** [comment]
Just removing Feature Request label: the somewhat fuzzy distinction between an enhancement and feature request is that the latter is a significant amount of work (e.g. a week or longer of solid work) while an enhancement is something which can be added in a few hours.

**Comment by gmackey** [comment]
The fix is in my CMake branch and will be pulled in with it.

**Comment by hcedwar** [comment]
Need intuitive name for option; e.g., ``--library-only``
