### ISSUE TITLE
layout() function broken for Views with padding -- path forward

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#6974]
We have an issue because the LayoutLeft and LayoutRight class itself (not the mapping) has no place to store stride. As a consequence the following code is wrong:

```c++
Kokkos::View<int**,Kokkos::LayoutLeft> a("A",N,M);
Kokkos::View<int**,Kokkos::LayoutLeft> a_sub =
  Kokkos::subview(a, Kokkos::pair{3,5},Kokkos::ALL());

Kokkos::View<int**,Kokkos::LayoutLeft> b_sub(a.sub.data(), a_sub.layout());
//b_sub.stride(1) != a_sub.stride(1);
```

Suggested path forward:

- restrict `layout()` to `Kokkos::LayoutLeft/Right/Stride` and deprecate
  - error out when calling `layout()` where `stride!=extent`
- introduce `View::mapping()` -> return mdspan mappings
- introduce `View(data_handle, mdspan_mapping_type map)`

**Comment by masterleinad** [comment]
It's actually not stride(1) but stride(2) that fails: https://godbolt.org/z/14q5o136r

**Comment by crtrott** [comment]
Because the code should have used `a_sub.layout()` corrected.

**Comment by crtrott** [comment]
Also accessing stride(2) on a rank-2 view is kinda UB lol
