### ISSUE TITLE
`View`: `HostMirror` and `host_mirror_type` aliases seem redundant (which one do we kill?)

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#6996]
### Summary

The alias `host_mirror_type` defined in https://github.com/kokkos/kokkos/blob/e4cc6862c6ba7cd14d7a274660015a62efb62605/core/src/Kokkos_View.hpp#L657-L660 seems redundant with `HostMirror` https://github.com/kokkos/kokkos/blob/e4cc6862c6ba7cd14d7a274660015a62efb62605/core/src/Kokkos_View.hpp#L650-L655

The main difference is that one is using the `host_mirror_space`, the other creates a `Kokkos::Device`.

Which alias should we deprecate ?

### Investigations

The alias `host_mirror_type` is used 2 times in `Kokkos` and 9 times in `Trilinos`. It is not mentioned in the documentation, but `HostMirror` is (https://kokkos.org/kokkos-core-wiki/API/core/view/view.html#_CPPv410HostMirror).

### Suggestion

Deprecate `host_mirror_type`, see who complains.

**Comment by dalg24** [comment]
`HostMirror` is the only one mentioned in the doc and it is all over our teaching material so it is clear if we cannot rid of it.
We could attempt to deprecate the `host_mirror_type ` member as you suggest.  I don't think too strongly about it.

**Comment by dalg24** [comment]
No consensus to deprecate `host_mirror_type`.  Need to investigate reconciling the definitions.
It was pointed out that `host_mirror_type` is probably a better name going forward but that it will be hard to change/get rid of `HostMirror`.
