### ISSUE TITLE
Question: best way to handle `exit` in a portable way

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#700]
I currently have:

```c++
  // ensure root is bracketed in specified domain
  if (!(f1*f2 < 0.)) {
    printf("Non-bracketed for index %i \n", func.team_.league_rank());
    exit(1);
  }
```

Which fails on cuda backend due to `exit(1)`. 

My first thought was to put some if guards around, something like `#ifndef KOKKOS_ENABLE_CUDA … #else … asm("trap;") #endif`. I think what I really want is to query the execution space that the kernel is running in and base which function is called from the execution space being used. Is that possible?

**Comment by crtrott** [comment]
```c++
Kokkos::abort("Message");
```

**Comment by dholladay00** [comment]
Yes! That worked.

As far as I'm concerned, this issue can be closed.

**Comment by mhoemmen** [comment]
@dholladay00 You could set an `atexit` hook if you want to call Kokkos::finalize automatically.
