### ISSUE TITLE
RangePolicy construction fails if input bound types are not convertible to the policy's IndexType

### ISSUE THREAD

**Issue by ldh4** [kokkos/kokkos#7005]
Reported from https://github.com/ECP-copa/Cabana/pull/753#issuecomment-2103376470.
 
Changes made in #6754 expects `RangePolicy`'s input bound types to be convertible to the `RangePolicy`'s `IndexType`.

However, the conversion safety check in `RangePolicy` actually requires a full roundtrip convertibility:
https://github.com/kokkos/kokkos/blob/506da184f0aa8af9fbbca5bccd8c500b81865af5/core/src/Kokkos_ExecPolicy.hpp#L271-L272
and fails if only one way conversion is available.

Few options to mitigate this include:
- Adding constraints to the `RangePolicy` constructors (more conditions in `enable_if`)
- Making roundtrip convertibility a mandate (with a `static_assert`)
- Skipping the value preserving/narrowing check if only convertible one way (output a warning message about skipping the check)

**Comment by crtrott** [comment]
Probable example: 

```c++
Kokkos::View<int, Kokkos::MemoryTraits<Kokkos::Atomic>> counter("Counter");
Kokkos::RangePolicy<>(0, counter());
```

**Comment by crtrott** [comment]
We conclude that it's fine that the above doesn't work and the requiremed round trip InputT -> IndexType -> InputT works (at least as explicit conversion).

**Comment by crtrott** [comment]
Could do better error message.
