### ISSUE TITLE
Get wrong results for compiler checks in Makefile on OS X.

### ISSUE THREAD

**Issue by gmackey** [kokkos/kokkos#706]
The shell calls to check the compilers and a couple of other shell calls get wrong results on OS X.  This is because of leading white space some of the shell commands generate on OS X.  The fix is to add the strip command to the offending commands.

**Comment by gmackey** [comment]
The fix is in my CMake branch and will be pulled in with it.

**Comment by crtrott** [comment]
I thought we fixed that on develop by adding the strip thing.
