### ISSUE TITLE
Use of Kokkos::ALL() on CUDA backend with use of Impl namespace

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#707]
I am receiving the following compile error: 
`error: identifier "Kokkos::_NV_ANON_NAMESPACE::ALL" is undefined in device code`

Error is mostly in this context:
`kokkos/core/src/Kokkos_View.hpp(1260): error: identifier "Kokkos::_NV_ANON_NAMESPACE::ALL" is undefined in device code`

I am using @gmackey's cmake branch. I'm guessing/hoping I am doing something silly.

**Comment by dholladay00** [comment]
I found that using `Kokkos::Impl::ALL_t()` made the error go away. 

Before I had been using `ALL` or `Kokkos::ALL()`, both of which produced the same compile error.

**Comment by crtrott** [comment]
Can i venture to guess that this is inside of a CUDA device (or host/device) lambda? I bet you are running into one of the limitations of device lambdas. Not sure what we can do about it other than telling you to use the workaround you already found.

**Comment by dholladay00** [comment]
You are correct.

Are there plans for a version of `Kokkos::ALL()` that works w/in device lambdas?

**Comment by crtrott** [comment]
We weren't aware of the issue (most of our stuff is still heavily functor based, since you still can't effectively use lambdas in member functions). So I don't know. We'll probably work with NVIDIA to make the current thing work in a future CUDA release. For now I would recommend to simply use the workaround you already found.

**Comment by dholladay00** [comment]
Will do. 

You can close the issue as far as I'm concerned, though it might be useful to note this as a CUDA feature request.

**Comment by Char-Aznable** [comment]
I have a similar issue with this code:
```c++
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>
#include<iostream>

using namespace std;

template < class ... VP, class SI > KOKKOS_INLINE_FUNCTION
constexpr decltype(auto) sv(const Kokkos::View<VP...>& v, const int i, SI&& si) {
  return Kokkos::subview(v, i, std::forward<SI>(si));
} 


int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {

  Kokkos::DualView<int*[3],Kokkos::DefaultExecutionSpace> v("v",10000);

  Kokkos::parallel_for(v.extent(0), KOKKOS_LAMBDA (const int i) {
    /* auto vsub = Kokkos::subview(v.d_view, i, Kokkos::ALL()); */ // this works
    auto vsub = sv(v.d_view, i, Kokkos::ALL()); // replace with Kokkos::Impl::ALL_t{} works
    for(int j = 0; j < v.d_view.extent(1); ++j) { vsub(j) = i + j; }
  });

  Kokkos::fence();

  v.modify_device();
  v.sync_host();

  for(int i = 0; i < v.extent(0); ++i) {
    for(int j = 0; j < v.extent(1); ++j) {
      cout << v.h_view(i,j) << " ";
    }
    cout << "\n";
  }

  } Kokkos::finalize();

}

```
The weird thing is that it works fine if  `subview()` is used directly inside the kernel instead of wrapped by a function.

**Comment by Char-Aznable** [comment]
Looks like it was the function argument instantiation `SI&&` that triggers the error regardless of what is used in the `subview()` call. e.g., this would gives the same error:
```
template < class ... VP, class SI > KOKKOS_INLINE_FUNCTION
constexpr decltype(auto) sv(const Kokkos::View<VP...>& v, const int i, SI&& si) {
  return Kokkos::subview(v, i, Kokkos::ALL());
} 

```
while 
```
template < class ... VP, class SI > KOKKOS_INLINE_FUNCTION
constexpr decltype(auto) sv(const Kokkos::View<VP...>& v, const int i, SI si) {
  return Kokkos::subview(v, i, si);
} 

```
this works
