### ISSUE TITLE
Can't config with Xyce

### ISSUE THREAD

**Issue by jsmith173** [kokkos/kokkos#7073]
I've compiled Trilinos 15.1 with Kokkos. Trilinos is compiled. When I'm trying to compile Xyce with Trilinos 15.1 I've got the following error messages:

---
  The link interface of target "Kokkos::kokkossimd" contains:
  
  DLlib::all_libs
  
  but the target was not found.  Possible reasons include:
  
  * There is a typo in the target name.
  * A find_package call is missing for an IMPORTED target.
  * An ALIAS target is missing.
---

There are some similar error messages also.

I think the problem is similar to #6902 but I don't know how to fix it for myself.

OS: MSYS2 (Cygwin) on Windows11
Cygwin: latest version

**Comment by masterleinad** [comment]
https://github.com/kokkos/kokkos/pull/3066 disabled `DL` support for `Windows` platforms by default already in a standalone `Kokkos` build. You need to make sure that your `Trilinos` configuration disables it as well.

**Comment by ajpowelsnl** [comment]
@jsmith173 -- did the suggestion to disable `DL`solve the problem?  If not, let us know how we can help further.

**Comment by jsmith173** [comment]
Thanks it is solved the problem
