### ISSUE TITLE
Performance Code Refactor

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#709]
This is a collection of performance points for the code refactor for different things

**Comment by crtrott** [comment]
Benchmark bytes_and_flops:

| Setting | Comment | NewStatic | OldStatic | NewDynamic | OldDynamic |
| --- | --- | --- | --- | --- | --- | 
| 2 100000 1024 1 1 1 1 1 1 | Bandwidth TeamSize 1 | 243.1 | 229.9 | 226.9 | 216.7 |
| 2 100000 1024 1 1 1 1 4 1 | Bandwidth TeamSize 4 | 201.6 | 206.7 | 188.9 | 196.7 |
| 2 100000 1024 1 1 1 1 4 1 | Bandwidth TeamSize 8 | 169.9 | 172.4 | 160.0 | 166.3 |
| 2 100000 1024 1 1 1 1 16 1 | Bandwidth TeamSize 16 | 109.8 | 108.3 | 98.8 | 105.7 |
| 2 1000000 128 1 1 1 1 1 1 | TeamOverhead TeamSize 1 | 238.1 | 228.7 | 212.5 | 213.1 |
| 2 1000000 128 1 1 1 1 4 1 | TeamOverhead TeamSize 4 | 131.8 | 136.6 | 117.3 | 132.6 |

**Comment by hcedwar** [comment]
```export KMP_AFFINITY=compact```
```export OMP_NUM_THREADS=256```
```numactl --membind=1 bytes_and_flops ...```

**Comment by hcedwar** [comment]
Revised dynamic scheduling for teams now steals chunks of work the same way as before:
https://github.com/kokkos/kokkos/commit/d03444270eefc2195924156c62f17b2841f513d0

**Comment by crtrott** [comment]
After adding the additional load and store fence in spin wait and the changes carter made the team-size 4 test for dynamic scheduling is now good (130 for both) but the team-size 1 test went down to 193 vs 210 with the master branch ....

**Comment by crtrott** [comment]
| Setting | Comment | NewStatic | OldStatic | NewDynamic | OldDynamic |
| --- | --- | --- | --- | --- | --- | 
| 2 100000 1024 1 1 1 1 1 1 | Bandwidth TeamSize 1 | 231 | 229 | 172 | 220 |
| 2 100000 1024 1 1 1 1 4 1 | Bandwidth TeamSize 4 | 202 | 206 | 164 | 194 |
| 2 100000 1024 1 1 1 1 8 1 | Bandwidth TeamSize 8 | 170 | 171 | 151 | 163 |
| 2 100000 1024 1 1 1 1 16 1 | Bandwidth TeamSize 16 | 112 | 106 | 106 | 103 |
| 2 1000000 128 1 1 1 1 1 1 | TeamOverhead TeamSize 1 | 229 | 229 | 194 | 216 |
| 2 1000000 128 1 1 1 1 4 1 | TeamOverhead TeamSize 4 | 130 | 134 | 130 | 130 |
