### ISSUE TITLE
Question: View of a POD struct

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#710]
I would like to have a view of a struct:

```c++
struct inputs {
  double a;
  double b;
  double c;
};
…
std::vector<inputs> a;
// I believe this eliminates copy of 'a' on host backends
View<inputs*, unmanaged, HostSpace> b(a.data(), a.size());
View<inputs*, unmanaged> c = create_mirror_view(DefaultExecutionSpace(), b);
deep_copy(c, b);
```

The deep_copy fails on the CUDA backend with:

```
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Invalid permissions (2)
```

Do I need to add certain constructors to make this work, or is this not supported on the CUDA backend?

**Comment by mhoemmen** [comment]
It doesn't make sense for the mirror View to be unmanaged in this case.  It's allocating a CUDA device buffer.  Who's going to free it?

**Comment by mhoemmen** [comment]
Try this:
```
View<inputs*>::HostMirror b (a.data (), a.size ()); // run-time unmanaged
View<inputs*> c = create_mirror_view (b);
deep_copy (c, b);
```

**Comment by dholladay00** [comment]
That worked! Thanks for the quick response. 

Follow up question, in the case that `DefaultExecutionSpace == HostSpace`, will the managed view delete all of the `vector`'s data when it goes out of scope? 

This issue is pretty easy to fix as I already have a place where I define things differently when `KOKKOS_ENABLE_CUDA` is defined. I just need to know.

**Comment by mhoemmen** [comment]
> ... in the case that DefaultExecutionSpace == HostSpace, will the managed view delete all of the vector's data when it goes out of scope?

Kokkos::View won't free an std::vector's data.  More specifically, if you create a Kokkos::View with a row pointer and dimension(s), the View will not free the pointer.  It's an unmanaged View.

**Comment by mhoemmen** [comment]
> This issue is pretty easy to fix as I already have a place where I define things differently when KOKKOS_ENABLE_CUDA is defined. I just need to know.

I'm pretty sure that the code I posted will work fine, with or without CUDA.  Be sure to try it, though :-)

**Comment by dholladay00** [comment]
Yep, that appears to work for both host (OpenMP) and device (CUDA) backends.

**Comment by mhoemmen** [comment]
To summarize for readers:

  1. Always assume that create_mirror_view creates a View whose type is managed.
  2. You can create "run-time unmanaged" Views, with the same type as managed Views, by passing in a pointer and dimension(s).
  3. This means that you can call create_mirror_view on a "run-time unmanaged" View.  The result may be a managed View, but always has the type of an unmanaged View.
