### ISSUE TITLE
deterministic task scheduling in Kokkos for CPUs

### ISSUE THREAD

**Issue by kadircs** [kokkos/kokkos#7100]
I am working on an MPI+Kokkos application. I am observing high time variation across different runs on a distributed-memory CPU system. The computational tasks are tiny. I need to find out the reason behind this high variation in run times. Is it possible to run Kokkos in a deterministic mode so that tasks are scheduled in the same way across different runs?

**Comment by masterleinad** [comment]
You should get static scheduling in host backends by default. Dynamic scheduling is only used when you specify the `Kokkos::Schedule<Kokkos::Dynamic>` property for the respective policy. Do you need more than that?

**Comment by ajpowelsnl** [comment]
@kadircs - were we able to answer your question, or would you like additional help with your issue?   For very small computational tasks on your system, it is possible that the observed variation in runtime is explained by (MPI) communication patterns.

**Comment by kadircs** [comment]
Thanks for your help!
