### ISSUE TITLE
RangePolicy constructors may accidentally implicitly convert optional last parameter to ChunkSize

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos#7142]
In Release 4.3, we removed the templated variadic constructors for `RangePolicy` in favor of taking `ChunkSize` as a final parameter, as that was the only use of the variadic constructors.

Because the original `RangePolicy` constructors were templated, that last parameter had to be `ChunkSize` and not just convertible to `ChunkSize`.  Now that it is a non-templated constructor, the constructors that take `ChunkSize` take anything implicitly convertible to `ChunkSize` in that position.  Specifically, because `ChunkSize` is _implicitly_ constructible from an `int`, just providing an `int` in that position will now compile where it wouldn't before, which is not the intention.

**Comment by dalg24** [comment]
I would like us to investigate declaring `ChunkSize` constructor from an integer `explicit` as a possible resolution.

**Comment by nliber** [comment]
Although that is a breaking change (see [https://godbolt.org/z/4bxEvMqv3](https://godbolt.org/z/4bxEvMqv3)), I concur.
