### ISSUE TITLE
cost of creating dynrankviews

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#715]
So,
I've got a kernel where I need small DynRankView for use within intrepid2.  I have a stack var which I use to initialize the dynrankview

```
  Kokkos::parallel_for (particles.size(), KOKKOS_LAMBDA(const int i)  {
    double values_mem[node_card_];
    Kokkos::DynRankView<double, Kokkos::MemoryUnmanaged> values(values_mem, node_card_);

    mi.getBasisValuesAtPoint(node_basis_, particles.element(i), particles.x(i), values);
    double factor = particles.weight(i)*types_[particles.type(i)].q;
    for (int icard=0;icard<node_card_; ++icard) {
      charge(particles.element(i), icard) += factor*values(icard);
    }
  });
```

Two questions, first will this work most places?  node_card_ is like 4 or 8.  Second, what is the cost of doing this?  Is this performant?  The function called is small, like loop of 32.

**Comment by bathmatt** [comment]
@kyungjoo-kim thought you might be interested in this.

**Comment by ndellingwood** [comment]
Hi @bathmatt  Wrapping the 1d array with an unmanaged DynRankView should work fine. As far as performance, the DynRankView will be more costly than a View with compile-time rank (more members to initialize giving a bit more overhead, more expensive parenthesis operator when accessing data). 
From the code snip posted it looks like this is for use with Intrepid2 where DynRankViews are required, which would make a more performant static rank View not an option in this case.

**Comment by kyungjoo-kim** [comment]
This is the case that you use serial interface. I do not know how many particles are computed per thread and whether it is necessary to explore more parallelism. If the # of particles to compute is considerably larger than the # threads (on GPUs), then this should be fine. 

However, if the # of particles to compute per thread is small, you may need to expand for team parallelism. Here we should provide Intrepid2 team basis interface(not yet available). The second for loop is team parallel loop (it might need to use atomic update if charges are overlapped between threads. Even for this team interface, it can only expand occupancy rate 4-8 times.

**Comment by bathmatt** [comment]
There are 1e6ish particles per GPU so single level is good enough.
