### ISSUE TITLE
Execution space constructors should be explicit

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#7152]
Background: We ran into disconcerting implicit conversions in #7151, `int` implicitly converting to `OpenMP`.

We should consider adding the `explicit` specifier to execution spaces constructors.

These are the backends that allow implicit conversions:
https://github.com/kokkos/kokkos/blob/bc7e02a16c779be323dd3f7673332d0ffd61b63c/core/src/Serial/Kokkos_Serial.hpp#L119
https://github.com/kokkos/kokkos/blob/bc7e02a16c779be323dd3f7673332d0ffd61b63c/core/src/OpenMP/Kokkos_OpenMP.hpp#L70
https://github.com/kokkos/kokkos/blob/bc7e02a16c779be323dd3f7673332d0ffd61b63c/core/src/HPX/Kokkos_HPX.hpp#L171-L180
https://github.com/kokkos/kokkos/blob/bc7e02a16c779be323dd3f7673332d0ffd61b63c/core/src/Cuda/Kokkos_Cuda.hpp#L169-L172
https://github.com/kokkos/kokkos/blob/bc7e02a16c779be323dd3f7673332d0ffd61b63c/core/src/HIP/Kokkos_HIP.hpp#L51-L53

**Comment by nliber** [comment]
I'm in favor of fixing this now.

However, I think we should split up the constructors (since some of them are both single argument and multi argument due to defaulting parameters) so that the single argument constructors are `explicit` while the multi argument constructors are implicit.

**Comment by tcclevenger** [comment]
Work in progress on this. Just putting some notes here. 

The serial impl does not allow explicit conversion since `NewInstance` is only explicitly constructible. 
https://github.com/kokkos/kokkos/blob/7d0e3e8184779c6f6b0d3ad7eac0341dbf273a2c/core/src/Serial/Kokkos_Serial.hpp#L79-L81
https://github.com/kokkos/kokkos/blob/bc7e02a16c779be323dd3f7673332d0ffd61b63c/core/src/Serial/Kokkos_Serial.hpp#L119

**Comment by masterleinad** [comment]
> The serial impl does not allow explicit conversion since `NewInstance` is only explicitly constructible.

You could still do
```
Kokkos::RangePolicy<Kokkos::Serial>policy (NewInstance{}, begin, end);
```
instead of
```
Kokkos::RangePolicy<Kokkos::Serial> policy(Kokkos::Serial{NewInstance{}}, begin, end);
```

**Comment by tcclevenger** [comment]
Ahh yes, I see.

**Comment by tcclevenger** [comment]
Completed by https://github.com/kokkos/kokkos/pull/7156
