### ISSUE TITLE
Simplify makefiles by guarding compilation with appropriate KOKKOS_ENABLE_### macros

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#716]
Remove conditional logic in Makefiles by protecting files with appropriate KOKKOS_ENABLE_### macros.  Also prevent linker from warning about empty archive.  Only Kokkos_Macros.hpp should be included before the #if defined test.

eg. (Kokkos_Foo.cpp)

#include <Kokkos_Macros.hpp>
#if defined( KOKKOS_ENABLE_FOO )
...
#else 
int g_KOKKOS_FOO_PREVENT_EMPTY_LINK_ERROR ;
#endif //if defined(KOKKOS_ENABLE_FOO)

**Comment by gmackey** [comment]
@dsunder I've already got updates to suppress the linker errors in my cmake branch.  It does it from the makefile side by conditional includes.  Why is it better to not have the conditional files but compile almost empty ones?  You then obviously have a few extra files in the compile that aren't even needed.  I would argue excluding them based on conditionals in the Makefile is better.

**Comment by hcedwar** [comment]
Better to define a noop function than global variable.
```void KOKKOS_FOO_NOOP_TO_AVOID_EMPTY_OBJECT_FILE() {}```

**Comment by hcedwar** [comment]
Which strategy has better maintainability?  make and cmake file logic or macro logic?
How does the macro strategy with extra compiles of trivial files impact compile times?

**Comment by dsunder** [comment]
I think that adding the protection to the files is valuable regardless of what the build system does.  The build system is free to exclude the files and it doesn't cost us anything, but if the build includes extra files it will still work without warnings.

**Comment by hcedwar** [comment]
This strategy has lower maintenance burden.

**Comment by ibaned** [comment]
This is all the way in master by now, we missed it.
