### ISSUE TITLE
Kokkos will compile for 32bit target?

### ISSUE THREAD

**Issue by jsmith173** [kokkos/kokkos#7161]
Question:
I'm compiling Trilinos 15.1 with Kokkos. Trilinos is compiled on 64 bit target. Can I try to compile for 32 bit target? Is it supported?

**Comment by masterleinad** [comment]
Yes, you can compile Kokkos for 32-bit. We have CI for that, see https://github.com/kokkos/kokkos/blob/develop/.github/workflows/continuous-integration-workflow-32bit.yml.
