### ISSUE TITLE
document how to indent

### ISSUE THREAD

**Issue by tjhei** [kokkos/kokkos#7177]
Would it be possible to better document how one is supposed to indent/format the code before contributing? I looked in the following places before discovering ./scripts/apply-clang-format:
- CMake generated make target
- project README
- top of .clang-format file
- https://github.com/kokkos/kokkos/blob/dbb0abb677554ed8339cef41825424fe94cbaae3/CONTRIBUTING.md 

It is also somewhat difficult to acquire clang-format-8: homebrew and debian/ubuntu packages do not contain such an old version.

**Comment by tjhei** [comment]
related to #7150

**Comment by dalg24** [comment]
Regarding availability of clang-format-8, as you noticed, we are planning to upgrade to more recent version.

We need to improve.  I like all the suggestions above except the README.  (I find the reference to contributing sufficient.)
We would also want to update https://github.com/kokkos/kokkos-core-wiki/blob/e87218bd67d6bcdbe547defffdf7d9bd1f2f31d6/docs/source/testing-and-issue-tracking/Testing-Processes.md?plain=1#L26-L27

**Comment by dalg24** [comment]
Feel free to comment/reopen if there is appetite for a cmake generated target.
