### ISSUE TITLE
Add University of Michigan to allowed domains for Slack channel

### ISSUE THREAD

**Issue by omsai** [kokkos/kokkos#7184]
Hello! I was wondering if you could invite me to the Kokkos to the Slack channel which does not yet recognize umich.edu addresses? @Rombur is giving training today at Argonne and advised opening a GitHub issue. First part of my e-mail is pnanda. Thank you so much!

**Comment by dalg24** [comment]
See https://kokkos.org/kokkos-core-wiki/faq.html

> **How do I join the Kokkos slack channel?**
> You can find the slack channel at [kokkosteam.slack.com](https://kokkosteam.slack.com/). Register a new account with your email. We reached the limit of whitelisted organizations, but every member of the Kokkos Slack workspace can invite more people. If no one you know is in the Slack workspace you can contact the Kokkos maintainers (their emails are in the LICENSE file).
