### ISSUE TITLE
Cuda+Pascal: feature .relaxed requires sm_70 or higher

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos#7187]
**Describe the bug**

When compiling programs with parallel_reduce for OpenMP + Cuda, with Pascal61 architecture, ptxas throws out errors like
```
ptxas: Feature '.relaxed' requires .target sm_70 or higher
```

A bisect points to #7089 as the first commit where this happens.

1. CUDA 12.5 with GCC 11.4.1 as host compiler
2. Replicates with today's develop branch, but b84125ed6 is the earliest commit where it happens
3. Architectures: SKX and Pascal61

Full reproducer: replace contents of example/build_cmake_in_tree/cmake_example.cpp with
```
#include <Kokkos_Core.hpp>
int main() {
  Kokkos::initialize();
  {
    double result;
    Kokkos::parallel_reduce(
        Kokkos::RangePolicy<>(0, 100),
        KOKKOS_LAMBDA(int i, double& lsum)
        {
          lsum += i*i - 1;
        }, result);
    printf("%f\n", result);
  }
  Kokkos::finalize();
  return 0;
}
```
Then configure with this and build.
```
cmake \
-DKokkos_ENABLE_CUDA=ON \
-DKokkos_ENABLE_OPENMP=ON \
-DKokkos_ARCH_SKX=ON \
-DKokkos_ARCH_PASCAL61=ON \
../kokkos/example/build_cmake_in_tree
```
Should see
```
ptxas /tmp/tmpxft_003a502d_00000000-6_cmake_example.ptx, line 273;
error   : Feature '.relaxed' requires .target sm_70 or higher
```

**Comment by dalg24** [comment]
Thanks for reporting Brian
