### ISSUE TITLE
Kokkos like assert

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#721]
Is there any function in kokkos that does an assert like call inside of a parallel_for?  I know that it isn't really a good thing to do, but thinking
```
Kokkos::delayed_assert(bool, maybe_string="") {
   set_fail_flag(true);
}
```
Then in the parallel for you could
```
set_fail_flag(false);
real_parallel_code()
if (set_fail_flag ) assert(false);
```
Obvious this isn't complete and we need d_view h_view and stuff like that.  but this feature would be super useful.

**Comment by mhoemmen** [comment]
I think @PGXavier had something like this -- a way to do deferred error reporting and error info collection in thread-parallel kernels.

**Comment by bathmatt** [comment]
As a feature request, can we take some version of this and move it into kokkos?  The issue if I make my own version and I use lambda expressions I have to check those by hand everytime.  Ideally it would be good to have one in the parallel_for code,

**Comment by crtrott** [comment]
We actually merged that into Kokkos (in the containers subpackage):

```c++
#include<Kokkos_Core.hpp>
#include<Kokkos_ErrorReporter.hpp>

struct error_string {
  char str[256];
  KOKKOS_INLINE_FUNCTION
  error_string() {};
  KOKKOS_INLINE_FUNCTION
  error_string(const char s[]) { int i= 0; while(s[i]!=0 && i<255) {str[i]=s[i]; i++;} str[i] = 0;}
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
  typedef Kokkos::Experimental::ErrorReporter<error_string, Kokkos::DefaultExecutionSpace> reporter_type;
  reporter_type errors(20);


  Kokkos::parallel_for(100, KOKKOS_LAMBDA(const int& i) {
   if(i%3==0)
     errors.add_report(i, error_string("OhNo"));
  });

  printf("Number of errors: %i\n",errors.getNumReportAttempts());
  if(errors.getNumReports() > 0) {
    Kokkos::View<int*, reporter_type::execution_space >::HostMirror reporter_ids;
    Kokkos::View<reporter_type::report_type*, reporter_type::execution_space >::HostMirror reports;
    errors.getReports(reporter_ids,reports);
    for(int i=0; i<errors.getNumReports(); i++) {
      printf("Report %i by %i is %s\n",i,reporter_ids(i),reports(i).str);
    }
  }
  }
  Kokkos::finalize();
}
```

This gives output (compiled for Cuda):
```
Number of errors: 34
Report 0 by 66 is OhNo
Report 1 by 96 is OhNo
Report 2 by 0 is OhNo
Report 3 by 33 is OhNo
Report 4 by 81 is OhNo
Report 5 by 99 is OhNo
Report 6 by 3 is OhNo
Report 7 by 48 is OhNo
Report 8 by 69 is OhNo
Report 9 by 18 is OhNo
Report 10 by 51 is OhNo
Report 11 by 84 is OhNo
Report 12 by 6 is OhNo
Report 13 by 36 is OhNo
Report 14 by 87 is OhNo
Report 15 by 21 is OhNo
Report 16 by 39 is OhNo
Report 17 by 72 is OhNo
Report 18 by 9 is OhNo
Report 19 by 54 is OhNo
```

**Comment by bathmatt** [comment]
This isn't quite what I'm looking for becuase it is added every parallel_for.  What I'm thinking is something that automatically checks for an error when done with a parallel_for which is in kokkos.  Basically a delayed assert.  I know I can set an error code and check it after every parallel_for but that litters the code quite a bit.

**Comment by ibaned** [comment]
For what its worth, CUDA does implement a version of plain old `assert()`, so you can just use that inside `parallel_for` loops.
