### ISSUE TITLE
Default Execution Space Always Uses CUDA Instead of Selecting Between CUDA or OpenMP Based on Command Line Argument

### ISSUE THREAD

**Issue by hiteshnagar2611** [kokkos/kokkos#7212]
I'm currently working on a project using Kokkos, and I've encountered an issue with the default execution space selection in the code. The code always defaults to using CUDA as the execution space, even when OpenMP is selected via a command line argument. 

### Reproduction Steps:
1. Compile the code with both CUDA and OpenMP enabled.
2. Run the program with `./program OpenMP` as the argument.
3. Observe that the output indicates CUDA is being used as the execution space instead of OpenMP.

### Expected Behavior:
The program should select the execution space based on the command line argument passed. Specifically:
- If the argument is `CUDA`, the program should use the CUDA execution space.
- If the argument is `OpenMP`, the program should use the OpenMP execution space.

### Actual Behavior:
The program always uses the CUDA execution space regardless of the command line argument provided.

### Code Snippet:
Here’s the relevant section of the code:

```cpp
bool useCuda = false;
bool usingCuda = false;

Kokkos::initialize(argc, argv);
{
    std::cout << "Default execution space: " << Kokkos::DefaultExecutionSpace::name() << std::endl;

    if (argc > 1 && std::strcmp(argv[1], "CUDA") == 0) {
        useCuda = true;
    }

    #ifdef KOKKOS_ENABLE_CUDA
    if (useCuda) {
        usingCuda = true;
        std::cout << "Using CUDA backend" << std::endl;
    }
    #endif

    #ifdef KOKKOS_ENABLE_OPENMP
    if (!useCuda) {
        std::cout << "Using OpenMP backend" << std::endl;
    }
    #endif
}
Kokkos::finalize();
```

### Environment:
- Kokkos version: 4.3.01
- CUDA version: 12.3

### Suggested Fix:
To fix this issue, the code should explicitly set the default execution space based on the command line argument. For example, using the Kokkos `initialize` function with the `execution_space` parameter might be necessary.

### Additional Information:
This issue can significantly affect performance on systems where both CUDA and OpenMP are available, as users may want to test on both backends. Any guidance or suggestions on how to implement the correct execution space selection based on user input would be appreciated.

**Comment by masterleinad** [comment]
C++ doesn't allow changing types at runtime. Therefore, the `Kokkos::DefaultExecutionSpace` alias is determined by the Kokkos configuration. In your setup, `Kokkos::DefaultHostExecutionSpace` would be `OpenMP`.
Also, note that you can always provide an explicit execution space or memory space in `Kokkos` interfaces.

If you want to use a particular execution space based on a runtime choice, you will have to do something like
```C++

template <typename ExecutionSpace>
void run()
{
  ...
}

int main()
{
  bool useCuda = ...;

#ifdef KOKKOS_ENABLE_CUDA
  if(useCuda)
  {
    run<Kokkos::Cuda>();  
  }
  else
#endif
  {
    run<Kokos::DefaultHostExecutionSpace>(); 
  }
}
```
which means that you have to instantiate the code both with `Kokkos::Cuda` and `Kokkos::DefaultHostExecutionSpace` (`Kokkos::OpenMP`).
