### ISSUE TITLE
dynamic_view resize_parallel deadlocks.

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#722]
So, 
I've got a dynamic view and under gcc/opt/openmp it is deadlocking with this snippet of code
```
    long which_dead = Kokkos::atomic_fetch_add(&num_dead_(0),1);
     printf("which dead %d capacity %d\n", which_dead, dead_capacity_());
   do {
      if ( which_dead == dead_capacity_()) {
        dead_list_.resize_parallel(dead_capacity_()+1024);
        dead_capacity_() += 1024;
      }
 // << print statement here fixes code
    }while (which_dead > dead_capacity_()); // spin lock if we need more space, it will get increased above
```

Is there a better way to do this?  I am only calling the resize with one thread which the one which hits the limit.  The rest should spin.  My guess is that dead_capacity_ is not getting updated in optimized code. 

The above code should work correct?

As one can see the list gets updated by this output.
```
which dead 0 capacity 0
which dead 1 capacity 0
which dead 2 capacity 0
which dead 3 capacity 0
which dead 4 capacity 1024
which dead 5 capacity 1024
which dead 6 capacity 1024
```

If I add a print statement inside the do/while loop it finishes.

**Comment by hcedwar** [comment]
try putting ``Kokkos::memory_fence();``` between the ```resize_parallel``` and ```dead_capacity_``` update.

**Comment by bathmatt** [comment]
Thanks, I Christian mentinoed that on Friday on the phone, it resolved the issue.  Sorry, I thought I closed it..  Will now.
