### ISSUE TITLE
HIP backend: Bessel function tests failing

### ISSUE THREAD

**Issue by maartenarnst** [kokkos/kokkos#7220]
**Describe the bug**

Some of the Bessel function tests in `core/unit_test/TestMathematicalSpecialFunctions.hpp` are failing on `HIP`.

This has been a known failure for a while, which has been tracked in 
- https://github.com/kokkos/kokkos/issues/5690

Currently the "workaround" is that in `core/unit_test/TestMathematicalSpecialFunctions.hpp`, some of the Bessel function tests are disabled depending on preprocessor conditions.

The issue and the preprocessor conditionals mentioned above are specific to the ROCm 5 series.

However, when we compile `Kokkos` and run the tests on ROCm 6, we still see Bessel function tests fail. Notably, on ROCm 6.2, there has been a regression, and more tests are failing than before.

Because the issue mentioned above was specific to ROCm 5 and is closed, @Rombur asked us to open a new issue (this one :)).

Two questions may be:
- Should we draw the attention of AMD developers to this issue of the failing Bessel functions to try to resolve it?
- Should we update the preprocessor conditionals in `core/unit_test/TestMathematicalSpecialFunctions.hpp` to disable tests too on ROCm 6. If yes, I can make a PR. 

Thanks in advance!

Related to:
- https://github.com/kokkos/kokkos/issues/5690
- https://github.com/kokkos/kokkos/issues/5637

Also tagging @romintomasetti.

**Comment by Rombur** [comment]
> Should we draw the attention of AMD developers to this issue of the failing Bessel functions to try to resolve it?

We reported the issue to AMD a while ago. 

> Should we update the preprocessor conditionals in core/unit_test/TestMathematicalSpecialFunctions.hpp to disable tests too on ROCm 6. If yes, I can make a PR.

The CI is clean for us when using ROCm 6.0 and 6.1. We run nightly tests with ROCm 6.0 on Frontier and nightly tests with ROCm 6.1 on our own hardware. What's your GPU?

**Comment by maartenarnst** [comment]
OK. That's interesting to hear that the CI is clean on your side. 

We run our tests on a Radeon Pro VII (`amd_gfx906`), and that's the architecture that we see the failures on. 

We have access to MI250X on LUMI. I'll try there, and I'll report back.

**Comment by maartenarnst** [comment]
I have just compiled `Kokkos` and ran the tests on MI250X on Lumi with a ROCm 6.2 stack. The tests pass there indeed. 

So it appears that the failure we still see with the Bessel functions is an issue with our older Radeon VII pro GPU. Support for this GPU is deprecated on ROCm 6. On my side, it is OK to close this issue.
