### ISSUE TITLE
kokkos bin sort bug w/ enable debug bounds check on

### ISSUE THREAD

**Issue by vasylivy** [kokkos/kokkos#7221]
Hi,

Reporting a bug in kokkos bin sort w/ serial host + Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON. See  /kokkos/algorithms/src/sorting/Kokkos_BinSortPublicAPI.hpp. When on host w/ more than 10 elements in the last bin, the std::sort path will be called as follows

`std::sort(&sort_order[lower_bound], &sort_order[upper_bound])`

Instead, directly compute the upper bound ptr by appropriately offseting the lower bound ptr so that the access op is not used. Otherwise it'll throw when on host w/ more than 10 elements in the last bin. Note that Kokkos::sort is used in tpetra import so this gets hit frequently and currently prevents enabling the bounds check.

Thanks,

Yaro

**Comment by masterleinad** [comment]
Would you be able to provide a full reproducer? I am seeing
```C++
    auto bin_size = bin_count_const(i);
    [....]
    int lower_bound = bin_offsets(i);
    int upper_bound = lower_bound + bin_size;
    // Switching to std::sort for more than 10 elements has been found
    // reasonable experimentally.
    if (use_std_sort && bin_size > 10) {
      KOKKOS_IF_ON_HOST(
          (std::sort(&sort_order(lower_bound), &sort_order(upper_bound),
                     [this](int p, int q) { return bin_op(keys_rnd, p, q); });))
    } else {
      [...]
    }
```
which looks OK at first sight, see https://github.com/kokkos/kokkos/blob/4c9cb7f3017a2f733b99f8a5495fe361a838daac/algorithms/src/sorting/Kokkos_BinSortPublicAPI.hpp#L381-L393.

**Comment by MalachiTimothyPhillips** [comment]
> Would you be able to provide a full reproducer? I am seeing
> 
> ```c++
>     auto bin_size = bin_count_const(i);
>     [....]
>     int lower_bound = bin_offsets(i);
>     int upper_bound = lower_bound + bin_size;
>     // Switching to std::sort for more than 10 elements has been found
>     // reasonable experimentally.
>     if (use_std_sort && bin_size > 10) {
>       KOKKOS_IF_ON_HOST(
>           (std::sort(&sort_order(lower_bound), &sort_order(upper_bound),
>                      [this](int p, int q) { return bin_op(keys_rnd, p, q); });))
>     } else {
>       [...]
>     }
> ```
> 
> which looks OK at first sight, see
> 
> https://github.com/kokkos/kokkos/blob/4c9cb7f3017a2f733b99f8a5495fe361a838daac/algorithms/src/sorting/Kokkos_BinSortPublicAPI.hpp#L381-L393
> .

Correct me if I'm wrong, but can't the `&sort_order(upper_bound)` invoke UB? Wouldn't it be safer to use `&sort_order(lower_bound) + (upper_bound - lower_bound)`?

**Comment by masterleinad** [comment]
Ah, yes, I see what you mean. We will fix it. Thanks for reporting!

**Comment by aprokop** [comment]
Can't we simply do `std::sort(sort_order.data() + lower_bound, sort_order.data() + upper_bound, ...)`?

**Comment by vasylivy** [comment]
Two other things I noticed when reviewing, 1) there is a global fence in the sort(...) call not sure why and 2) I think bin_count_atomic view should be allocated w/o initialization. There's already an appropriate deep copy later.

**Comment by vasylivy** [comment]
Whoops maybe its being used before that deep copy so nvm

**Comment by masterleinad** [comment]
> Can't we simply do `std::sort(sort_order.data() + lower_bound, sort_order.data() + upper_bound, ...)`?

Yes. Do you want to fix?
