### ISSUE TITLE
seriously?

### ISSUE THREAD

**Issue by alexmyczko** [kokkos/kokkos#7232]
**Describe the bug**

although source tarballs can have anything, it has been standard to unpack into a directory
by default. unfortunately i have downloaded the kokkos-4.4.00.tar.gz and not 4.4.00.tar.gz first...

**Please include the following for a minimal reproducer**

being silly i did not first inspect the tarball but just unpacked it, and BAM
i have thousands of files in that directory where i unpacked. thank you!

i will not read what will happen with this issue in a time after now, but i wanted to thank
you for creating kokkos-4.4.00.tar.gz which does not unpack into a subdirectory-4.4.00/ like
the latter tarball. (warming up your special place in hell for you, please consider not doing this in the future anymore)

**Comment by dalg24** [comment]
Release artifacts were updated with a `kokkos-4.4.00/` prefix prepended to paths in the archives.
