### ISSUE TITLE
unit test failure on KNL / Bowman testbed

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#724]
Compiler:
KOKKOS_COMPILER_GNU: 620
Architecture:
KOKKOS_ENABLE_ISA_KNC: no
KOKKOS_ENABLE_ISA_POWERPCLE: no
KOKKOS_ENABLE_ISA_X86_64: yes
Devices:
KOKKOS_ENABLE_CUDA: no
KOKKOS_ENABLE_OPENMP: yes
KOKKOS_ENABLE_PTHREAD: no
KOKKOS_ENABLE_STDTHREAD: no
KOKKOS_ENABLE_WINTHREAD: no
KOKKOS_ENABLE_QTHREADS: no
KOKKOS_ENABLE_SERIAL: yes
Default Device:
KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_CUDA: no
KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_OPENMP: yes
KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_THREADS: no
KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_QTHREADS: no
KOKKOS_ENABLE_DEFAULT_DEVICE_TYPE_SERIAL: no
Atomics:
KOKKOS_ENABLE_CUDA_ATOMICS: no
KOKKOS_ENABLE_GNU_ATOMICS: yes
KOKKOS_ENABLE_INTEL_ATOMICS: no
KOKKOS_ENABLE_OPENMP_ATOMICS: no
KOKKOS_ENABLE_WINDOWS_ATOMICS: no
Vectorization:
KOKKOS_ENABLE_PRAGMA_IVDEP: no
KOKKOS_ENABLE_PRAGMA_LOOPCOUNT: no
KOKKOS_ENABLE_PRAGMA_SIMD: no
KOKKOS_ENABLE_PRAGMA_UNROLL: no
KOKKOS_ENABLE_PRAGMA_VECTOR: no
Memory:
KOKKOS_ENABLE_HBWSPACE: no
KOKKOS_ENABLE_INTEL_MM_ALLOC: no
KOKKOS_ENABLE_POSIX_MEMALIGN: no
Options:
KOKKOS_ENABLE_ASM: yes
KOKKOS_ENABLE_CXX1Z: no
KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK: no
KOKKOS_ENABLE_HWLOC: yes
KOKKOS_ENABLE_LIBRT: no
KOKKOS_ENABLE_MPI: no
KOKKOS_ENABLE_PROFILING: yes

Runtime Configuration:
Kokkos::OpenMP KOKKOS_ENABLE_OPENMP hwloc[1x68x4] hwloc_binding_enabled thread_pool_topology[ 1 x 68 x 2 ]

[ RUN ] openmp.triple_nested_parallelism
/home/jenkins/workspace/Kokkos_SLURM_inner_test/core/unit_test/TestReduce.hpp:542: Failure
Value of: result
Actual: 1.73015e+07
Expected: solution
Which is: 1.67772e+07
[ FAILED ] openmp.triple_nested_parallelism (92 ms)

**Comment by crtrott** [comment]
This bug has been there for a bit (see #685). It is a non-deterministic failure, me and Dan have already spend about 20 hours on trying to fix it. It is present in master, but after some changes now more prevalent on develop (i.e. the rate with which this test fails is increased). Not so sure that this thing is the best "first assignment" in Kokkos land ...

**Comment by dsunder** [comment]
I just checked with my new threadpool backend and I can get it to fail there too.  I suspect that we are missing a barrier somewhere in the nested parallelism code.  I can almost always reproduce by oversubscribing the machine with multiple processes (i.e. launch background processes which compete with the unit test for hardware resources).  It can fail without hwloc, but happens more frequently with hwloc enabled since the we then bind the threads which prevents the OS from load balancing.

**Comment by crtrott** [comment]
In current develop there was a true bug in there which makes it always fail. Basically if the number of active threads changes (shrinks) between two successive reductions, the final summation on the second one will get some results of the prior one, because only active threads actually initialized their values.

**Comment by crtrott** [comment]
So I pushed a thing. But it is not clear whether this only fixed the deterministic bug or whether everything is now ok.

**Comment by crtrott** [comment]
It only fixed the deterministic failure, it didn't fix the non-deterministic one.

**Comment by hcedwar** [comment]
This test occasionally failed with the Threads back-end as well.

**Comment by hcedwar** [comment]
@dsunder quickly repeated prior runs that manifested the bug, and the bug did not manifest. Assume this non-deterministic bug has been resolved until new evidence otherwise.

**Comment by hcedwar** [comment]
On 2017-06-23 the `threads.triple_nested_parallelism` nightly test on KNL failed with the same error.

**Comment by ibaned** [comment]
Well darn

**Comment by hcedwar** [comment]
Failure analysis:
```
[ RUN      ] threads.triple_nested_parallelism
/home/jenkins/workspace/Kokkos_SLURM_inner_test@2/core/unit_test/TestTeamVector.hpp:841: Failure
Value of: result
  Actual: 1.62529e+07
Expected: solution
Which is: 1.67772e+07
```

- The difference is equal to this test dropping reduction contributions from the execution of two teams.  
- The league_size = nrows / chunk_size = 8192 / 128 = 64, the number of _virtual_ teams
- Each team contributes: chunk_size * ncols = 128 * 2048 = 262144
- The error is: 16777216 - 16252928 = 2 * chunk_size * ncols
- The KNL test has team_size = 32 or 16, given 256 threads this is 8 or 16 _actual_ teams each of which spans 8 or 4 cores
- Each _actual_ team performs 8 or 4 _virtual_ team iterations
- Thus a whole _actual_ team contribution was not dropped, only two iterations
- However, the prior "fixes" would only have addressed dropping an entire _actual_ team contribution

**Comment by hcedwar** [comment]
This test has not failed on KNL since the previous commit, which has been 3days x 6configurations.  Assume fixed until the non-deterministic failure occurs again; which will generate additional diagnostic output.

**Comment by hcedwar** [comment]
Test has not failed for OpenMP back-end on KNL.
Test failed for Threads back-end on KNL on 2017-06-27.
Output from extra diagnostic:
[ RUN      ] threads.triple_nested_parallelism
  TestTripleNestedReduce failed solution(16777216) != result(16711680), nrows(8192) ncols(2048) league_size(64) team_size(32)
/home/jenkins/workspace/Kokkos_SLURM_inner_test@2/core/unit_test/TestTeamVector.hpp:853: Failure
Value of: result
  Actual: 1.67117e+07
Expected: solution
Which is: 1.67772e+07
[  FAILED  ] threads.triple_nested_parallelism (79 ms)

**Comment by hcedwar** [comment]
The error is equal to having dropped reduction contributions from 32 rows (previous failure corresponded to 256 rows).  Given 8192 rows / 256 total threads this is the reduction contribution from a single thread.
Team size of 32 corresponds to 8 _actual_ teams iterating 8 times to fulfill the league size of 64.  Each iteration of an _actual_ team processes 128 rows in the [test](https://github.com/kokkos/kokkos/blob/develop/core/unit_test/TestTeamVector.hpp#L824).  Thus the dropped reduction contribution is a partial team.
Hypothesis: more likely that a single thread's entire contribution was dropped as opposed to team's partial contribution or multiple threads' partial contribution.

**Comment by hcedwar** [comment]
This probable error source should have prevented by the insertion of a [memory fence](https://github.com/kokkos/kokkos/blob/develop/core/src/Threads/Kokkos_ThreadsExec.hpp#L289).
Assumption: oversubscription of cores plus unpinned threads due to running this unit test through the Jenkins on KNL is triggering an underlying problem with the KNL runtime/memory system itself.
Given that non-unit testing usage of the KNL 

- exercises the OpenMP back-end which no longer manifests this non-deterministic failure even with unit testing, 
- does not oversubscribe cores, and 
- does not leave threads unpinned 

then this test's non-deterministic failure, while troublesome, has not been known to impact actual usage of Kokkos.
