### ISSUE TITLE
Question: reduction for update and sum

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#727]
I have an array in which I want to apply an operation to an array and sum up the updated values:

```c++
// sequential version
View<double*> x;
double multiplier = 1.5;
double sum = 0.0;
for (int i = 0; i < x.extent(0); ++i) {
  x(i) *= multiplier;
  sum += x(i);
}
```

It's not transparent what is going on during a `parallel_reduce`. If I replaced the `for` loop above with a `parallel_reduce`, can I be confident that the reduction will update the `View` correctly, or could it apply the `*=` multiple times?

My assumption is yes, b/c you warn against this in the `parallel_scan` and I assume you would give a similar warning for the reduction.

The bigger concern: even if this works today, is the plan to ensure that something like this will work in the future?

**Comment by crtrott** [comment]
Yes parallel_reduce is guaranteed to be a single pass. Parallel_scan can't so we explicitly state that. 
And also: I have tons and tons of code which relies on parallel_reduce being a single pass.

**Comment by crtrott** [comment]
Here is the fixed version:
```c++
// sequential version
View<double*> x;
double multiplier = 1.5;
double sum = 0.0;
parallel_reduce(x.extent(0), KOKKOS_LAMBDA(const int& i,double& lsum) {
  x(i) *= multiplier;
  lsum += x(i);
},sum);
```

**Comment by dholladay00** [comment]
That's what I needed to hear!

This can be closed.
