### ISSUE TITLE
MirrorViewType and deep_copy in case of const data type

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#728]
I'm not sure if this is a bug/enhancement issue or if I'm using mirror views in the wrong way.

I have a view on the HostSpace created from a pointer, and I want to create the corresponding execution space view with

`auto exec_view =  create_mirror_view(exec_space, host_view);`

where host_view has **const** data type, and exec_space is an instance of the execution space. From what I understand looking at MirrorViewType, if HostSpace==ExecutionSpace, the execution space view is of the same type of the input view (hence, with a const data type), otherwise it will have a non-const data type (and obviously different memory space). In the former case, create_mirror_view simply returns the src view, while in the latter it creates a new view (with non const data type).

Now, the problem arises when calling deep_copy. This method checks at compile time that the destination view has non const data type. This is a problem, since if HostSpace==ExecSpace, then the destination view created above will have const data type. Ideally, I would not want this to be a problem, since deep_copy should be a no-op in case the stored pointers are the same (which they are in this case). Is this really a problem or it is a desired behavior?

Notice that this issue does not show up when calling deep_copy with mirror views "the other way around", that is, when creating a HostMirror from an execution space view, since the HostMirror view is always created with non_const_data_type, so the static assert inside deep_copy always passes.

I am afraid that there is no way to avoid the check inside deep_copy, since deep_copy has no way to check (at compile time) that the two views store the same pointer (to const), and therefore, since it's a no-op, ignore the fact that the destination view has non-const data type. In other words, deep_copy has no knowledge of how the two views were created, so it cannot know that one view is meant to be a mirror of the other.

Perhaps a solution could be to add a deep_copy method to the MirrorViewType struct. The general implementation would simply call Kokkos::deep_copy, while the specialization for the case where Space is the same as the input view MemorySpace would simply do nothing.

But perhaps I'm simply not understanding correctly the mirror views...

**Comment by hcedwar** [comment]
@bartgol : I'm afraid your specific example is a use-error.

The premise for `create_mirror_view` is that it is OK to simply return the same `View` if everything is compatible.  The premise for `create_mirror` is that a `View` with separately allocated memory is required.

The `View` created by `create_mirror` should have non-const data type, but the data type of the created `View` is simply copied from the input `View`.  This is a bug so I created #1005 to fix this.
