### ISSUE TITLE
Building with pybind11 can't properly intilize Kokkos::Impl::g_openmp_hardware_max_threads

### ISSUE THREAD

**Issue by Sauron-1** [kokkos/kokkos#7283]
**Describe the bug**

When building Python module using pybind11 and linking to Kokkos with OpenMP backend, the variable `Kokkos::Impl::g_openmp_hardware_max_threads` is always `1`, which breaks `ScatterView`.

**Please include the following for a minimal reproducer**

- Platform: Ubuntu 22.04 on Intel 9700k
- Compiler: clang++ 17.0.6
- Kokkos version: 4.4.0 and commit a068d826dd79e8994c7b43a3b72577e0ea704b8f
- pybind11 version: 2.12.0dev1
- CMake configure command: `CXX=clang++ cmake .. -DKokkos_ENABLE_OPENMP=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON` (`BUILD_SHARED_LIBS=OFF` results in linkage error)

C++ file (`pytest.cpp`)
```cpp
#include <Kokkos_Core.hpp>
#include <pybind11/pybind11.h>
#include <omp.h>

void initialize() {
    printf("Value of g_openmp_hardware_max_threads before initialize is %d\n", Kokkos::Impl::g_openmp_hardware_max_threads);
    Kokkos::initialize();
    printf("Value of g_openmp_hardware_max_threads after initialize is %d, while omp_current_max_threads is %d\n",
        Kokkos::Impl::g_openmp_hardware_max_threads,
        omp_get_max_threads()
    );
}

void finalize() {
    printf("Finalizing\n");
    Kokkos::finalize();
}

PYBIND11_MODULE(pytest, m) {
    m.def("initialize", &initialize);
    m.def("finalize", &finalize);
}
```
CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.10)
project(pytest)

add_subdirectory(kokkos)
find_package(pybind11 REQUIRED)

pybind11_add_module(pytest pytest.cpp)
target_link_libraries(pytest PUBLIC Kokkos::kokkos)
```

test.py
```python
import pytest

pytest.initialize()
pytest.finalize()
```

Output of `python3 test.py`:
```
Value of g_openmp_hardware_max_threads before initialize is 1
Value of g_openmp_hardware_max_threads after initialize is 1, while omp_current_max_threads is 8
Finalizing
```

If add a print line in this function: https://github.com/kokkos/kokkos/blob/08ceff92bcf3a828844480bc1e6137eb74028517/core/src/OpenMP/Kokkos_OpenMP_Instance.cpp#L161
the printed value of `Kokkos::Impl::g_openmp_hardware_max_threads` is correct (equal to `omp_get_max_threads`).

Also, changing the declaration of this variable from `inline` to `extern` in the header file and defining it in `core/src/OpenMP/Kokkos_OpenMP_Instance.cpp` fix the issue.

**Comment by dalg24** [comment]
We probably should just get rid of that global variable.
