### ISSUE TITLE
Nightly test failure: sycl_graph.diamond, sycl_graph.end_of_submit_control_flow failures with Sycl backend, PVC arch, intel/oneapi/2023.1.0

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7302]
**Describe the bug**

A nightly Sycl job on PVC arch failed in the `sycl_graph.end_of_submit_control_flow` unit test

```
03:36:30 [ RUN      ] sycl_graph.diamond
03:36:30 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestGraph.hpp:454: Failure
03:36:30 Expected equality of these values:
03:36:30   data_host(index_A())
03:36:30     Which is: 84
03:36:30   value_A
03:36:30     Which is: 42
03:36:30 [  FAILED  ] sycl_graph.diamond (0 ms)
03:36:30 [ RUN      ] sycl_graph.end_of_submit_control_flow
03:36:30 /home/jenkins/blake-new/workspace/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/kokkos/core/unit_test/TestGraph.hpp:540: Failure
03:36:30 Expected equality of these values:
03:36:30   data_host(index_E())
03:36:30     Which is: 257676512
03:36:30   value_B + value_E
03:36:30     Which is: 523
03:36:30 [  FAILED  ] sycl_graph.end_of_submit_control_flow (0 ms)
```

The failure began following merge of these commits

**Changes**
    Fix implicit copy assignment operator for AVX2 mask being deleted ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#8daac7ce8bf849495cc7606fc5bec49585737e1f) / [githubweb](https://github.com/kokkos/kokkos/commit/8daac7ce8bf849495cc7606fc5bec49585737e1f))
    Update clang-format-check to fix it ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#307e13ca51e2c73bac938506a23c91373497847a) / [githubweb](https://github.com/kokkos/kokkos/commit/307e13ca51e2c73bac938506a23c91373497847a))
    Add range-based for loop support for `Array<T, N>` (#7293) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#383ecf6a9017c2379bd803d02af48479fe41fe8f) / [githubweb](https://github.com/kokkos/kokkos/commit/383ecf6a9017c2379bd803d02af48479fe41fe8f))
    [desul atomics] Add bitwise shift operations to AtomicRef ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#89c9890d10fca6ceca29d793f1c6f5330ea5e9ed) / [githubweb](https://github.com/kokkos/kokkos/commit/89c9890d10fca6ceca29d793f1c6f5330ea5e9ed))
    Update cmake and make configurations for Clacc/LLVM compiler (#7198) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#12fd21fd0cbae108a85093a566a977267c444832) / [githubweb](https://github.com/kokkos/kokkos/commit/12fd21fd0cbae108a85093a566a977267c444832))
    Fix nvc++ warning set_but_not_used in Array tests ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#beeb273c6d3bf97b273935d318938d5199824754) / [githubweb](https://github.com/kokkos/kokkos/commit/beeb273c6d3bf97b273935d318938d5199824754))
    graph(fix): defaulted graph submit control flow (#7271) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_sycl_pv_oneapi_2023_1_0/381/changes#5e7b4b2d97480a43ed2174ba599b4b7a705a3b81) / [githubweb](https://github.com/kokkos/kokkos/commit/5e7b4b2d97480a43ed2174ba599b4b7a705a3b81))

**Please include the following for a minimal reproducer**

**Reproducer configuration** (e.g. blake PV queue):
```bash
source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh
module purge
module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

cmake -DCMAKE_CXX_COMPILER=icpx -DCMAKE_CXX_FLAGS="-fp-model=precise" -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_PVC=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF $KOKKOS_PATH

make -j16

export ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu
ctest -R Kokkos_CoreUnitTest_SYCL1A -V

```

**Comment by dalg24** [comment]
CC @romintomasetti @masterleinad

**Comment by masterleinad** [comment]
Can't reproduce on the testbeds
```
[==========] Running 11 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from sycl_graph_DeathTest
[ RUN      ] sycl_graph_DeathTest.can_instantiate_only_once

[WARNING] /home/darndt/kokkos/tpls/gtest/gtest/gtest-all.cc:9326:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 3 threads. See https://github.com/google/googletest/blob/master/docs/advanced.md#death-tests-and-threads for more explanation and suggested solutions, especially if this is the last message you see before your test times out.

[WARNING] /home/darndt/kokkos/tpls/gtest/gtest/gtest-all.cc:9326:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 3 threads. See https://github.com/google/googletest/blob/master/docs/advanced.md#death-tests-and-threads for more explanation and suggested solutions, especially if this is the last message you see before your test times out.
[       OK ] sycl_graph_DeathTest.can_instantiate_only_once (42 ms)
[----------] 1 test from sycl_graph_DeathTest (42 ms total)

[----------] 10 tests from sycl_graph
[ RUN      ] sycl_graph.submit_once
[       OK ] sycl_graph.submit_once (0 ms)
[ RUN      ] sycl_graph.submit_once_rvalue
[       OK ] sycl_graph.submit_once_rvalue (0 ms)
[ RUN      ] sycl_graph.instantiate_and_submit_once
[       OK ] sycl_graph.instantiate_and_submit_once (0 ms)
[ RUN      ] sycl_graph.submit_onto_another_execution_space_instance
[       OK ] sycl_graph.submit_onto_another_execution_space_instance (0 ms)
[ RUN      ] sycl_graph.submit_six
[       OK ] sycl_graph.submit_six (0 ms)
[ RUN      ] sycl_graph.when_all_cycle
[       OK ] sycl_graph.when_all_cycle (0 ms)
[ RUN      ] sycl_graph.zero_work_reduce
[       OK ] sycl_graph.zero_work_reduce (0 ms)
[ RUN      ] sycl_graph.empty_graph
[       OK ] sycl_graph.empty_graph (0 ms)
[ RUN      ] sycl_graph.diamond
[       OK ] sycl_graph.diamond (0 ms)
[ RUN      ] sycl_graph.end_of_submit_control_flow
[       OK ] sycl_graph.end_of_submit_control_flow (0 ms)
[----------] 10 tests from sycl_graph (3 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 2 test suites ran. (46 ms total)
[  PASSED  ] 11 tests.
```

**Comment by ndellingwood** [comment]
This is still failing reliably in our nightlies

**Comment by masterleinad** [comment]
> This is still failing reliably in our nightlies

Let me try to reproduce on the Franken cluster.

**Comment by ndellingwood** [comment]
Making a note here this fail also occurred testing with a Trilinos build with gcc/8.5.0 and the OpenMP backend

**Comment by tcclevenger** [comment]
Taking a look at this now.

**Comment by ndellingwood** [comment]
Here's a link to CDash with the OpenMP failure https://trilinos-cdash.sandia.gov/test/64243044

```
[ RUN      ] openmp_graph.diamond
Kokkos::abort: Instance has no resource allocated to it
Backtrace:
[0x1375a03] 
[0x13642f5] 
[0x6504a1] 
[0x6505a9] 
[0x64303b] 
[0x13631ba] 
[0x13570e8] 
[0x13573ca] 
[0x135794d] 
[0x1359d92] 
[0x135a1fc] 
[0x47e190] 
[0x7f3699c1ad85] __libc_start_main
[0x4a54be] 
```

That build used the sems-gcc/8.5.0 compiler and was built in release mode, no arch specified

**Comment by masterleinad** [comment]
This tests creates 4 execution space instances so we need at least 4 threads available.

**Comment by masterleinad** [comment]
We might just want to check `concurrency` of the default execution space instance and disable the test if that's less than four.

**Comment by ndellingwood** [comment]
@tcclevenger yeah, blake (and the OHPC) will be down for the next week or so, they are in the process of moving facilities to a new location. You might be able to reproduce with an OpenMP build on a machine with sems compilers using sems-gcc/8.5.0 (or possibly a container with gcc/8.5.0 installed)

**Comment by dalg24** [comment]
> This tests creates 4 execution space instances so we need at least 4 threads available.

Why?
It is legal even if there was only a single omp num thread at startup.

**Comment by dalg24** [comment]
Sounds more like the `create_OpenMP_instances()` has a bug

**Comment by masterleinad** [comment]
> It is legal even if there was only a single omp num thread at startup.

The semantics that are implemented for OpenMP are "split the number threads in the original execution space instance up" and the `OpenMP` backend requires at least 1 thread assigned.

**Comment by masterleinad** [comment]
The original issue wasn't solved.

**Comment by tcclevenger** [comment]
@ndellingwood Apologies this got lost for me, but I'm back to working on it. With the setup above I'm encountering a build error
```
In file included from /home/tccleve/Kokkos/build-blake/algorithms/unit_tests/sycl/TestSort.cpp:2:
In file included from /home/tccleve/Kokkos/kokkos/algorithms/unit_tests/TestSort.hpp:24:
In file included from /home/tccleve/Kokkos/kokkos/algorithms/unit_tests/../src/Kokkos_Sort.hpp:25:
In file included from /home/tccleve/Kokkos/kokkos/algorithms/unit_tests/../src/sorting/Kokkos_SortPublicAPI.hpp:20:
In file included from /home/tccleve/Kokkos/kokkos/algorithms/unit_tests/../src/sorting/./impl/Kokkos_SortImpl.hpp:72:
In file included from /projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/execution:65:
In file included from /projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/glue_execution_defs.h:55:
In file included from /projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h:21:
In file included from /projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/../parallel_backend.h:19:
In file included from /projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h:40:
/projects/x86-64-icelake-rocky8/tpls/intel-oneapi-dpl/2022.1.0/oneapi/2023.1.0/base/6mz4j72/dpl/2022.1.0/linux/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h:65:21: error: constex       pr variable '__mask' must be initialized by a constant expression
    constexpr _UInt __mask = (__is_ascending) ? 1 << ::std::numeric_limits<_Int>::digits : ~_UInt(0) >> 1;

```
This is obviously not the runtime error you are getting. @masterleinad Have you encountered this error before? Am I missing some env variable? cmake option? I'll keep testing stuff on my end to try and get this running so I can replicate.

**Comment by masterleinad** [comment]
Looks like some incompatibility between `oneDPL` and `icpx`. I don't remember seeing that error.
For the sake of this pull request, you could just disable `oneDPL` via `Kokkos_ENABLE_ONEDPL=OFF`, of course.

**Comment by ndellingwood** [comment]
@tcclevenger I'll try a manual build as well. The nightly job was hung in the queue the last few days, so no reports came through about any new failures introduced

**Comment by ndellingwood** [comment]
@tcclevenger like @masterleinad mentioned adding `-DKokkos_ENABLE_ONEDPL=OFF` is necessary - I accidentally cut this off in the reproducer snip when I cleaned up the source code path (replacing local path with `$KOKKOS_PATH`), sorry for the mishap

**Comment by tcclevenger** [comment]
I'm also seeing tests pass on blake
```
[ RUN      ] sycl_graph.empty_graph_default_host_exec
[       OK ] sycl_graph.empty_graph_default_host_exec (0 ms)
[ RUN      ] sycl_graph.diamond
[       OK ] sycl_graph.diamond (0 ms)
[ RUN      ] sycl_graph.end_of_submit_control_flow
[       OK ] sycl_graph.end_of_submit_control_flow (1 ms)
```

**Comment by ndellingwood** [comment]
@tcclevenger no, the job hung in the queue again. I opened an issue with admins to look into the Jenkins connectivity issues
To confirm, were you passing tests with `intel-oneapi-compilers/2023.1.0`?

**Comment by tcclevenger** [comment]
Here is my env
```
[tccleve@blake15 Kokkos]$ module list

Currently Loaded Modules:
  1) cmake/3.27.4                      3) intel-oneapi-dpl/2022.1.0
  2) intel-oneapi-compilers/2023.1.0   4) git/2.41.0

[tccleve@blake15 Kokkos]$ export ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu
```

**Comment by ndellingwood** [comment]
@tcclevenger the Jenkins issues on Blake are resolved and last night's job passed 👍 
Some incidental change in the past week resolved the issue
