### ISSUE TITLE
graph(`SYCL`): specialization of `Kokkos::Impl::Graph` is not tested in jenkins CI

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos#7326]
The specialization of `Kokkos::Impl::Graph` for `Kokkos::SYCL` is never tested for now.

This is the piece of code that guard it:
https://github.com/kokkos/kokkos/blob/fd8d327ad964bde55b94f9f7c0fb60e7c54c8b03/core/src/Kokkos_Graph.hpp#L187-L189

In the current [scripts/docker/Dockerfile.sycl](https://github.com/kokkos/kokkos/blob/54b739089e5f9b5dab5efaf60f2d40d9530e46f3/scripts/docker/Dockerfile.sycl), the toolchain is just too old and does not support the `SYCL` graph extension.

This can be verified by looking in `sycl/sycl.hpp` and check if `SYCL_EXT_ONEAPI_GRAPH` gets defined.

This issue was spotted while working on #6904.

**Comment by romintomasetti** [comment]
@dalg24 @masterleinad This issue does not need to be tackle today, but we should keep that in mind. We could also have a CI job that runs on the GitHub runners with a basic `SYCL` that is CPU-only, but recent enough to support `SYCL_EXT_ONEAPI_GRAPH`.

**Comment by masterleinad** [comment]
This gets tested but not in our current jenkins CI setup. I adjusted the title of the pull request accordingly.

**Comment by masterleinad** [comment]
If/when we get access to a machine with Intel GPUs (possibly at https://systems.nic.uoregon.edu/internal-wiki/index.php?title=Main_Page) or are willing to stand-up another CI test we should test with a recent compiler version.

**Comment by romintomasetti** [comment]
> This gets tested but not in our current jenkins CI setup (but in nightly jobs at Sandia). I adjusted the title of the pull request accordingly.

OK, but we've got just no control over it, nor any proof that it's running (not to mention no information on the software stack and hardware)...

**Comment by masterleinad** [comment]
> no control over it, nor any proof that it's running (not to mention no information on the software stack and hardware)...

https://github.com/kokkos/kokkos/issues/7302 has errors and lists
> module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

and
> -DKokkos_ARCH_INTEL_PVC=ON 

and we know that an Intel® Data Center GPU Max 1100 is used. I agree that not getting automated reports is suboptimal.

**Comment by masterleinad** [comment]
Fixed in #7420.
