### ISSUE TITLE
Nightly Test Failures, intel/oneapi/2023.1.0, Sycl Backend, PVC arch; Kokkos, KokkosKernels and Trilinos/Tpetra package tests

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7363]
**Describe the bug**

Nightly Trilinos builds with intel/2023.1.0 and Sycl for PVC have several failing Tpetra tests with a common error message, for example:

`TpetraCore_gemv`
```
...
19:59:45  p=0: *** Caught standard std::exception of type 'sycl::_V1::exception' :
19:59:45  
19:59:45   Native API failed. Native API returns: -46 (PI_ERROR_INVALID_KERNEL_NAME)
19:59:45  [FAILED]  (0.129 sec) Blas_double_Gemv_UnitTest
19:59:45  Location: /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI_2023_1_Sycl_PVC_MKL-Tpetra/Trilinos/packages/tpetra/core/test/Blas/gemv.cpp:299
```

The testing machine used for this nightly job recently came back online, a couple basic checks (e.g. sycl-ls) confirm the GPU is visible

@masterleinad were there recent changes to Sycl that require a different configuration option in some cases, or some other type of change that could trigger these failures?

**Please include the following for a minimal reproducer**
**Reproducer notes** (blake PV queue):
```bash

# Environment
source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh
module purge
module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git intel-oneapi-mkl/2023.1.0 intel-oneapi-tbb/2021.9.0
module list

# Configure Trilinos
cmake \
  -D CMAKE_CXX_COMPILER="`which icpx`" \
  -D CMAKE_C_COMPILER="`which icx`" \
  -D CMAKE_Fortran_COMPILER="`which ifx`" \
  -D CMAKE_CXX_FLAGS="-fp-model=precise -Wno-deprecated-declarations" \
  -D CMAKE_INSTALL_PREFIX="${TRILINOS_INSTALL_DIR}" \
  -D BUILD_SHARED_LIBS=ON \
  -DTPL_ENABLE_MPI=OFF \
  -DTPL_ENABLE_BLAS:BOOL=ON \
    -D BLAS_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
    -D BLAS_LIBRARY_NAMES="mkl_rt" \
  -DTPL_ENABLE_LAPACK:BOOL=ON \
    -D LAPACK_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
    -D LAPACK_LIBRARY_NAMES="mkl_rt" \
  -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_MUST_FIND_ALL_TPL_LIBS=TRUE \
  -DTrilinos_ENABLE_OpenMP=OFF \
  -DTrilinos_ENABLE_Kokkos=ON \
  -D Kokkos_ARCH_INTEL_PVC=ON \
  -D Kokkos_ENABLE_SYCL=ON \
   -D Kokkos_ENABLE_IMPL_MDSPAN=ON \
   -D Kokkos_ENABLE_TESTS=OFF \
   -D Kokkos_ENABLE_ONEDPL=OFF \
  -DTrilinos_ENABLE_KokkosKernels=ON \
   -D KokkosKernels_ENABLE_TESTS=OFF \
  -DTrilinos_ENABLE_Tpetra=ON \
   -D Tpetra_ENABLE_TESTS=ON \
   -D Tpetra_INST_SYCL=ON \
   -D Tpetra_INST_SERIAL=ON \
\
  -DTPL_ENABLE_Matio=OFF \
\
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR

make -j16

export ZES_ENABLE_SYSMAN=1
export ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu

ctest --output-on-failure
```

**Comment by masterleinad** [comment]
> @masterleinad were there recent changes to Sycl that require a different configuration option in some cases, or some other type of change that could trigger these failures?

We only switched to `rdc=off` by default.

**Comment by masterleinad** [comment]
I am seeing
```
1/5 Test #43: TpetraCore_Bug10008 ...........................Subprocess aborted***Exception:   1.41 sec
test 82
    Start 82: TpetraCore_ImportExport2_UnitTests_Send

82: Test command: /home/darndt/trilinos/build/packages/tpetra/core/test/ImportExport2/TpetraCore_ImportExport2_UnitTests.exe "--distributor-send-type=Send" "--globally-reduce-test-result" "--output-show-proc-rank" "--output-to-root-rank-only=-1"
82: Working Directory: /home/darndt/trilinos/build/packages/tpetra/core/test/ImportExport2
82: Test timeout computed to be: 1500
82: Teuchos::GlobalMPISession::GlobalMPISession(): started serial run
82: p=0 | 
82: p=0 | ***
82: p=0 | *** Unit test suite ...
82: p=0 | ***
82: p=0 | 
82: p=0 | 
82: p=0 | Sorting tests by group name then by the order they were added ... (time = 6e-06)
82: p=0 | 
82: p=0 | Running unit tests ...
82: p=0 | 
82: p=0 | 0. CrsGraphImportExport_int_longlong_doImport_UnitTest ... [Passed] (1.2e-05 sec)
82: p=0 | 1. CrsMatrixImportExport_int_longlong_double_doImport_UnitTest ... [Passed] (5.6e-05 sec)
82: terminate called after throwing an instance of 'std::runtime_error'
82:   what():  There was a synchronous SYCL error:
82: Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)
```
and similar errors for the other failing tests (but I don't know if they were pre-existing)
```
	 43 - TpetraCore_Bug10008 (Subprocess aborted)
	 82 - TpetraCore_ImportExport2_UnitTests_Send (Subprocess aborted)
	 83 - TpetraCore_ImportExport2_UnitTests_ISend (Subprocess aborted)
	 84 - TpetraCore_ImportExport2_UnitTests_Alltoall (Subprocess aborted)
	 85 - TpetraCore_AsyncTransfer_UnitTests (Subprocess aborted)
```

**Comment by masterleinad** [comment]
It seems the failing tests are all failing in `lowCommunicationMakeColMapAndReindex`.

**Comment by ndellingwood** [comment]
@masterleinad I'm seeing this type of test failure `C++ exception with description "No kernel found with the specified name -46 (PI_ERROR_INVALID_KERNEL_NAME)" thrown in the test body.` on all the nightly Sycl jobs running on PVC as well (kokkos core and kernels), I'm launching a couple manual builds to reproduce and checking with the release to check if this is a system issue (the testbed was recently moved to new location and brought back online, maybe something is awry)

**Comment by ndellingwood** [comment]
@masterleinad I reproduced the issue with kokkos@develop, but the tests pass with kokkos@4.4.01. I will try enabling rdc with the kokkos@develop build to see if the test resume passing

**Comment by ndellingwood** [comment]
I tested with `Kokkos_ENABLE_IMPL_SYCL_RELOCATABLE_DEVICE_CODE=ON` and the tests (kokkos unit tests) still fail, so the new failures seem to be unrelated to rdc

**Comment by ndellingwood** [comment]
For reference for the kokkos unit tests:

**Test failures**:
```
The following tests FAILED:
	  1 - Kokkos_CoreUnitTest_Serial1 (Failed)
	  3 - Kokkos_CoreUnitTest_SYCL1A (Subprocess aborted)
	  4 - Kokkos_CoreUnitTest_SYCL1B (Subprocess aborted)
	  5 - Kokkos_CoreUnitTest_SYCL2A (Failed)
	  6 - Kokkos_CoreUnitTest_SYCL2B (Failed)
	  7 - Kokkos_CoreUnitTest_SYCL2C (Failed)
	  8 - Kokkos_CoreUnitTest_SYCL2D (Failed)
	  9 - Kokkos_CoreUnitTest_SYCL3 (Failed)
	 10 - Kokkos_CoreUnitTest_SYCLInterOpInit (Failed)
	 11 - Kokkos_CoreUnitTest_SYCLInterOpInit_Context (Failed)
	 12 - Kokkos_CoreUnitTest_SYCLInterOpStreams (Failed)
	 13 - Kokkos_CoreUnitTest_SYCLInterOpStreamsMultiGPU (Failed)
	 14 - Kokkos_CoreUnitTest_Default (Failed)
	 15 - Kokkos_CoreUnitTest_LegionInitialization (Failed)
	 21 - Kokkos_CoreUnitTest_KokkosP (Failed)
	 29 - Kokkos_IncrementalTest_SYCL (Failed)
	 34 - Kokkos_ContainersUnitTest_SYCL (Failed)
	 35 - Kokkos_UnitTest_Sort (Failed)
	 36 - Kokkos_UnitTest_Random (Failed)
	 37 - Kokkos_AlgorithmsUnitTest_StdSet_A (Failed)
	 38 - Kokkos_AlgorithmsUnitTest_StdSet_B (Failed)
	 39 - Kokkos_AlgorithmsUnitTest_StdSet_C (Failed)
	 40 - Kokkos_AlgorithmsUnitTest_StdSet_D (Failed)
	 41 - Kokkos_AlgorithmsUnitTest_StdSet_E (Failed)
	 42 - Kokkos_AlgorithmsUnitTest_StdSet_Team_A (Failed)
	 43 - Kokkos_AlgorithmsUnitTest_StdSet_Team_B (Failed)
	 44 - Kokkos_AlgorithmsUnitTest_StdSet_Team_C (Failed)
	 45 - Kokkos_AlgorithmsUnitTest_StdSet_Team_D (Failed)
	 46 - Kokkos_AlgorithmsUnitTest_StdSet_Team_E (Failed)
	 47 - Kokkos_AlgorithmsUnitTest_StdSet_Team_F (Failed)
	 48 - Kokkos_AlgorithmsUnitTest_StdSet_Team_G (Failed)
	 49 - Kokkos_AlgorithmsUnitTest_StdSet_Team_H (Failed)
	 50 - Kokkos_AlgorithmsUnitTest_StdSet_Team_I (Failed)
	 51 - Kokkos_AlgorithmsUnitTest_StdSet_Team_L (Failed)
	 52 - Kokkos_AlgorithmsUnitTest_StdSet_Team_M (Failed)
	 53 - Kokkos_AlgorithmsUnitTest_StdSet_Team_P (Failed)
	 54 - Kokkos_AlgorithmsUnitTest_StdSet_Team_Q (Failed)
	 55 - Kokkos_UnitTest_SIMD (Failed)
```

**Common failure output**:
```
C++ exception with description "Native API failed. Native API returns: -46 (PI_ERROR_INVALID_KERNEL_NAME)" thrown in the test body.
```

**Reproducer** (blake PV queue):
```bash
source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh
module purge
module load cmake intel-oneapi-compilers/2023.1.0 intel-oneapi-dpl/2022.1.0 git

cmake -DCMAKE_CXX_COMPILER=icpx -DCMAKE_CXX_FLAGS="-fp-model=precise" -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_PVC=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_ONEDPL=OFF -DKokkos_ENABLE_IMPL_SYCL_RELOCATABLE_DEVICE_CODE=ON -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF

make -j16

export ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu
ctest
```

**Comment by masterleinad** [comment]
So it looks like a toolchain issue. Can you compile and run any pure SYCL code?

**Comment by ndellingwood** [comment]
> We should get a bisect going then.

Yes, I'll post the sha once I finish the bisection

**Comment by ndellingwood** [comment]
A partial update
I started the bisect on merge commits
good: dac55f54f03f93e9a3bbfe19597d7aa0ced8f146
bad: af8df138190527f4a99b632da0a58faec188e8ba

Now looking at rebase+squashed PRs between those commits

**Comment by dalg24** [comment]
Does the compile line has the `-fno-rtti` flag?!  I did guard so it is not used when the SYCL backend is enabled...

**Comment by ndellingwood** [comment]
@dalg24 I'll have to rebuild to confirm, but I am testing some PRs between the shas above that may be more likely culprits (currently building 2e5c565a8fa1487f683c36b6a9e23eff8a255e15).
The shas above are associated with consecutive merge commits (via `git log --merges`) that I used to start the bisection and avoid intermediate WIP commits. Some merges (maybe squash+rebase) do not list with `git log --merges`, I am testing those between the good/bad sha

**Comment by ndellingwood** [comment]
Sha https://github.com/kokkos/kokkos/commit/2e5c565a8fa1487f683c36b6a9e23eff8a255e15 (#5993) failed (so https://github.com/kokkos/kokkos/commit/af8df138190527f4a99b632da0a58faec188e8ba is unrelated)

**Comment by dalg24** [comment]
Makes more sense :)

**Comment by ndellingwood** [comment]
> Makes more sense :)

Yeah, sorry for causing some alarm, I should have been more clear in the message about the relevance (i.e. consecutive merge commits from `git log --merges`) to why I posted that pair of good-bad shas

**Comment by masterleinad** [comment]
Does the setting of `Kokkos_ENABLE_IMPL_SYCL_RELOCATABLE_DEVICE_CODE`  matter or does it fail with both `ON` and `OFF`?

**Comment by ndellingwood** [comment]
@masterleinad if I test with explicitly setting `-DKokkos_ENABLE_IMPL_SYCL_RELOCATABLE_DEVICE_CODE=OFF` the tests fail (as posted); with this setting I did get a CMake warning (I think expected):
```
CMake Warning:
  Manually-specified variables were not used by the project:

    Kokkos_ENABLE_IMPL_SYCL_RELOCATABLE_DEVICE_CODE
```

Looking at the CMakeCache.txt, it looks like I should use `Kokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE` , let me know if I'm misunderstanding
```
...
//No help, variable specified on the command line.
Kokkos_ENABLE_IMPL_SYCL_RELOCATABLE_DEVICE_CODE:UNINITIALIZED=OFF
...
//Whether to enable relocatable device code (RDC) for SYCL
Kokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE:BOOL=OFF
```

I'm testing with `-DKokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE=ON` , as well as with the sha b5509ab14f760769446ab0710dca88483eebce22 (merge prior to https://github.com/kokkos/kokkos/pull/5993) to complete the bisection. These builds take awhile though (it is nice when testing the builds without rdc, so much faster :)

**Comment by masterleinad** [comment]
> Looking at the CMakeCache.txt, it looks like I should use `Kokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE` , let me know if I'm misunderstanding

Yes, that's what I meant. We had the `IMPL` version in one pull request and replaced it in the next one.

**Comment by ndellingwood** [comment]
Finished the bisection, the failures began with #5993 (sha b5509ab14f760769446ab0710dca88483eebce22 tests passed)

Testing with `-DKokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE=ON` still in progress

**Comment by masterleinad** [comment]
Can you make sure that the link line contains `-fsycl`?

**Comment by ndellingwood** [comment]
Tests with `-DKokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE=ON` passed

In the jobs with rdc off, `-fsycl` is on the compilation and link lines

**Comment by masterleinad** [comment]
> Tests with `-DKokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE=ON` passed

At least a workaround for now. Might be related to older compiler versions? I will try older versions as well on my side.

**Comment by masterleinad** [comment]
Ah, we get
```
icpx: warning: linked binaries do not contain expected 'spir64-unknown-unknown' target; found targets: 'spir64_gen-unknown-unknown' [-Wsycl-target]
```

**Comment by masterleinad** [comment]
I can see the failure with
- 2023.1.0
- 2023.2.0
- 2024.0.0

and it works with 
- 2024.1.0
- 2024.2.0
- 2025.0.0

**Comment by ndellingwood** [comment]
Thanks @masterleinad ! Nightlies look much better, only #7302 is now present
