### ISSUE TITLE
Develop performance-regression/acceptance tests

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#737]
Major features need to have performance tests.  Tests need to be broken down into stages to help isolate diffs.

**Comment by hcedwar** [comment]
Tier 1:  Parallel For with Range Policy, Static Scheduling
Tier 2: Parallel Reduce and Scan with Range Policy, Static Scheduling
Tier 3: Parallel For with Team Policy, Static Scheduling
Tier 4: Parallel Reduce with Team Policy, Static Scheduling
Tier 5:  Parallel For with Range Policy, Dynamic Scheduling
Tier 6: Parallel Reduce and Scan with Range Policy, Dynamic Scheduling
Tier 7: Parallel For with Team Policy, Dynamic Scheduling
Tier 8: Parallel Reduce with Team Policy, Dynamic Scheduling

**Comment by ndellingwood** [comment]
PR in with performance tests and sample script to run tests organized by Tier's from Apr 19 comment above.
