### ISSUE TITLE
`SequentialHostInit` does not compile in a `DualView`

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#7373]
**Describe the bug**

`SequentialHostInit` does not compile in a `DualView`:

`k_view.resize(Kokkos::view_alloc(Kokkos::SequentialHostInit),n);`

```
../../lib/kokkos/core/src/View/Kokkos_ViewAlloc.hpp(321): error: static assertion failed
static_assert(SpaceAccessibility<HostSpace, MemSpace>::accessible);
```

It seems like the Device view inside the DualView should ignore the `SequentialHostInit` property so it can compile.

**Comment by dalg24** [comment]
Essentially in the presence of that `SequentialHostInit` view allocation property we would have to mandate that the resize happens on the host with then mirroring to the device, making sure that we do not instantiate a device view construction with it.

The description mentions `resize()` but we would also want to consider the DualView constructors as well as `realloc()` as appropriate.

**Comment by masterleinad** [comment]
Places that use `ViewCtorProp`:
- `Bitset` constructor 
- `DualView` `realloc`
- `DualView` `resize`
- `DualView` constructor
- `DynRankView` `realloc`
- `DynRankView` `realloc`
- `DynRankView` `create_mirror[_view][_and_copy]`
- `DynRankView` constructor
- `DynamicView` constructor
- `DynamicView` `create_mirror[_view][_and_copy]`
- `OffsetView` constructor
- `OffsetView` `create_mirror[_view][_and_copy]`
- `ScatterView` constructor
- `ScatterView` resize
- `ScatterView` realloc
- `UnorderedMap` constructor
- `View` `realloc`
- `View` `resize`
- `View` `create_mirror[_view][_and_copy]`
- `View` constructor

The `DualView` constructor only uses the properties for the device View, and only applies the Withoutinitialzing property for the host View if given. We could consider forwarding more attributes.
`resize` and `realloc` are problematic as reported here.
All the other occurrences apply only to the given memory space and therefore seem to be fine.

**Comment by masterleinad** [comment]
I'm having a hard time reproducing
```C++
TEST(TEST_CATEGORY, dualview_sequential_host_init) {
  DualViewType dv(Kokkos::view_alloc("myView", Kokkos::SequentialHostInit), 100);
  dv.resize(Kokkos::view_alloc(Kokkos::SequentialHostInit),200);
  ASSERT_EQ(dv.d_view.size(), 200);
  ASSERT_EQ(dv.h_view.size(), 200);
    dv.realloc(Kokkos::view_alloc(Kokkos::SequentialHostInit),300);
      ASSERT_EQ(dv.d_view.size(), 300);
  ASSERT_EQ(dv.h_view.size(), 300);
}
```
seems to be fine

**Comment by dalg24** [comment]
Presumably you tried in your laptop. There is a runtime if guarding a device view construction and a static assert that will fail. On my cell otherwise would paste links to code

**Comment by stanmoore1** [comment]
@masterleinad what backend? Need to use CUDA or another GPU backend.

**Comment by masterleinad** [comment]
```
[ RUN      ] cuda.dualview_sequential_host_init
[       OK ] cuda.dualview_sequential_host_init (0 ms)
```

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/5635f200a6f15a8d51e4ed42cfed7bbd9afd9012/containers/src/Kokkos_DualView.hpp#L1072-L1078
Please try to trigger the "resize on device".
I indeed cannot find a static assertion that the view is host but clearly that is required.

**Comment by dalg24** [comment]
Actually here is the static assert I would have expected that would fail
https://github.com/kokkos/kokkos/blob/5635f200a6f15a8d51e4ed42cfed7bbd9afd9012/core/src/View/Kokkos_ViewAlloc.hpp#L206

**Comment by masterleinad** [comment]
I can reproduce with
```C++
TEST(TEST_CATEGORY, dualview_sequential_host_init) {
  Kokkos::DualView<double*> dv(Kokkos::view_alloc("myView", Kokkos::SequentialHostInit), 100);
  dv.resize(Kokkos::view_alloc(Kokkos::SequentialHostInit),200);
  ASSERT_EQ(dv.d_view.size(), 200);
  ASSERT_EQ(dv.h_view.size(), 200);
    dv.realloc(Kokkos::view_alloc(Kokkos::SequentialHostInit),300);
      ASSERT_EQ(dv.d_view.size(), 300);
  ASSERT_EQ(dv.h_view.size(), 300);
}
```

**Comment by masterleinad** [comment]
The unit test tried using `SharedSpace`.

**Comment by masterleinad** [comment]
@stanmoore1 Can you describe the use case some more? If we need/want `SequentialHostInit` on the host wouldn't we run into issues in the device view anyway?

**Comment by stanmoore1** [comment]
Like @dalg24 said: "in the presence of that SequentialHostInit view allocation property we would have to mandate that the resize happens on the host with then mirroring to the device, making sure that we do not instantiate a device view construction with it."
