### ISSUE TITLE
`hipMemsetAsync` error in scalar deep-copy into host-allocated unmanaged view on MI300A

### ISSUE THREAD

**Issue by cwpearson** [kokkos/kokkos#7377]
On MI300A with `DKokkos_ENABLE_IMPL_HIP_UNIFIED_MEMORY=ON`, it is permitted to do a host allocation (e.g. `calloc`), wrap it in an unmanaged `Kokkos::SharedSpace` view, and run a GPU parallel-for that modifies it.

However, if you `deep_copy` a scalar into that view, Kokkos ultimately tries to use `hipMemsetAsync`, which in rocm <= 6.2.0 comes back with the following error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  hipMemsetAsync( dst.data(), 0, dst.size() * sizeof(typename View<T, P...>::value_type), exec_space.hip_stream()) error( hipErrorInvalidValue): invalid argument /usr/WS1/shavano/spack-environments/ATS4CCE_GPU/2.5.2/spack/opt/spack/linux-rhel8-zen3/cce-18.0.0b-magic/kokkos-4.4.00-fwvvrmm/include/HIP/Kokkos_HIP_ZeroMemset.hpp:31
```

I think probably `hipMemsetAsync` is wrongly erroring out when it sees we're trying to operate on a host pointer, even though the GPU can access this data. I've reported this to AMD.

In the mean time, we can probably work around this by using a parallel_for rather than hipMemsetAsync in this specific situation.

```c++
#include <Kokkos_Core.hpp>
#include <Kokkos_OffsetView.hpp>

#include <iostream>

int main(void) {

    static_assert(std::is_same_v<Kokkos::HIPManagedSpace, Kokkos::SharedSpace>, "");

    Kokkos::initialize(); {

    double *ptr = (double*)calloc(1, 10 * sizeof(double));
    Kokkos::fence();

    Kokkos::View<double*, Kokkos::SharedSpace, Kokkos::MemoryUnmanaged> v(ptr, 10);
    Kokkos::fence();

    std::cerr << "parallel_for...\n";
    Kokkos::parallel_for(
         Kokkos::RangePolicy<Kokkos::HIP>(0, 10),
         KOKKOS_LAMBDA(int i) {v[i] = 1.0;}
    );
    Kokkos::fence();

    std::cerr << "deep_copy...\n";
    Kokkos::deep_copy(v, 0.0); // ERROR HERE
    std::cerr << "fence...\n";
    Kokkos::fence();
    std::cerr << "success\n";
    }Kokkos::finalize();
}
```

**Comment by dalg24** [comment]
Do we want to keep this open now that we have a workaround in place?
