### ISSUE TITLE
ThreadVectorRange Customized Reduction Bug

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos#739]
I am following the example in TestTeamVector.hpp for implementing a min reduction for ThreadVectorRange. 

I followed this example, and wrote a customized reduction for thread vector range. Below is my code: 
```c++

      nnz_lno_t max_num_results_in_row = 1000000;
      Kokkos::parallel_reduce(
          Kokkos::ThreadVectorRange(teamMember, left_work),
          [&] (nnz_lno_t i, nnz_lno_t & valueToUpdate) {
        std::cout << "valueToUpdate:" << valueToUpdate << std::endl;
        if (valueToUpdate > 10){
          valueToUpdate = 10;
        }
      },
        [&] (nnz_lno_t& val, const nnz_lno_t& src)
        {
        std::cout << "val:" << val << " src:" << src << std::endl;
        if (val > src){
          val = src;
        }},
      max_num_results_in_row);
```

I am running it on CPU with single thread, and it is printing:
valueToUpdate:0
val:1000000 src:0
valueToUpdate:0
val:0 src:0
valueToUpdate:0
val:0 src:0
valueToUpdate:0

Basically, join operator takes the initial value that I set for reduction. However, this appears to be a problem within the lambda function body.

**Comment by crtrott** [comment]
Initialization value is not treated correctly. This seems to work with OpenMP on develop, but is still broken with CUDA.

**Comment by crtrott** [comment]
For Cuda this actually worked on Master ...

**Comment by crtrott** [comment]
I think this works now across the board using reducers. The join-lambda interface is gone though. See #802
