### ISSUE TITLE
how can I create a view of pointers ? 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#744]
I need an array of pointers
```
typedef double* ptr_type;
View<ptr_type*> a(10);
a(0) = my_data_ptr; // kokkos consider this rank 2 array and this incurs error. 
```

Wha should I do ? Do I need to create a wrapper ? 
```
struct ptr_wrapper {
  double *ptr;
  
  ptr_wrapper(const double *ptr) : ptr(ptr) {}
  operator double*() const {
    return ptr; 
  }
}; 
```

Do we have a better solution for this  ?

**Comment by crtrott** [comment]
Nope ...

**Comment by kyungjoo-kim** [comment]
thanks.

**Comment by ibaned** [comment]
In the MemoryPool test, a `Kokkos::View<uintptr_t*>` is used to store pointers, with casting back and forth between `uintptr_t` and `void*`.
