### ISSUE TITLE
Kokkos_Serial_Task Compilation Errors on Windows

### ISSUE THREAD

**Issue by bkolade** [kokkos/kokkos#748]
I am trying to build Trillions 12.10.1 (downloaded from the Trilinos.org website) on Windows using MS Visual Studio IDE. I am getting compilation errors of the types:
1)	“more than one instance of overloaded function … matches the argument list” on functions  Kokkos::atomic_increment and Kokkos::atomic_decrement
2)	“no instance of function template … matches the argument list” on functions Kokkos::volatile_store, Kokkos::atomic_fetch_add, and Kokkos::volatile_store. 
I believe the offending headers are impl/Kokkos_TaskQueue_impl.hpp and Kokkos_MemoryPool.hpp.

I built the MS Visual Studio project files using CMake 3.80 and I am using the Intel C++ 17 and the compiler. The project compiles fine when I remove Kokkos_Serial_Task.cpp from the project list. I am new to Trilinos. I assume that removing this file from the project list may generate “unresolved external symbols” down the line. Any advice on how to proceed?

Thanks,

**Comment by crtrott** [comment]
Hi

this is related to our general lack of windows support. We need to get a handle on it but it didn't get high enough in our priority list. In particular our atomics need work.

**Comment by hcedwar** [comment]
Windows / MS Visual Studio is not a supported platform.  We would be glad to accept your pull request to address Windows / MS Visual Studia portability to the develop branch.
