### ISSUE TITLE
Nightly test failure, icpc builds on SKX, simd.device_math_ops subprocess abort

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#7481]
**Describe the bug**

Nightly builds with icpc (from intel-oneapi-compilers/2023.2.0) on SKX are failing the `simd.device_math_ops` subtest:

```
17:45:25 [ RUN      ] simd.device_math_ops
17:45:25 SIMD unit test equality condition failed on device
17:45:25 Backtrace:
17:45:25 [0x6a6d20] 
17:45:25 [0x669ba2] 
17:45:25 [0x5cdfc7] 
17:45:25 [0x5ca592] 
17:45:25 [0x53cf67] 
17:45:25 [0x7fe714944493] __kmp_invoke_microtask
17:45:25 [0x7fe7148b2533] 
17:45:25 [0x7fe7148b37b8] __kmp_fork_call
17:45:25 [0x7fe71486ad23] __kmpc_fork_call
17:45:25 [0x53c98f] 
17:45:25 [0x40959f] 
17:45:25 [0x65ba8a] 
17:45:25 [0x60e994] 
17:45:25 [0x60dbeb] 
17:45:25 [0x60cf63] 
17:45:25 [0x60afca] 
17:45:25 [0x5fe65e] 
17:45:25 [0x40753f] 
17:45:25 [0x7fe713b27d85] __libc_start_main
17:45:25 [0x40740e] 
```

This followed after merge of these commits

**Changes**

    Enable compound assignments ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#3c77b3ebd51b7b7af8e687a56068a98f96ba56de) / [githubweb](https://github.com/kokkos/kokkos/commit/3c77b3ebd51b7b7af8e687a56068a98f96ba56de))
    Add compound shifts ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#5b0e305533ea01221f2f29e30ecbe6dab7b2108e) / [githubweb](https://github.com/kokkos/kokkos/commit/5b0e305533ea01221f2f29e30ecbe6dab7b2108e))
    Added ctors that accepts a pointer to src mem ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#3b0f1967dbe4bd707fe8d73da057b064f8d14a76) / [githubweb](https://github.com/kokkos/kokkos/commit/3b0f1967dbe4bd707fe8d73da057b064f8d14a76))
    Expanded simd reduction operation ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#874675126b7d05d2bb8f064d4a79c7154a9efd68) / [githubweb](https://github.com/kokkos/kokkos/commit/874675126b7d05d2bb8f064d4a79c7154a9efd68))
    Added hmin, hmax and reduce (sum) in AVX512 ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#293f6f07791046016745bfa7f89b395246d96d78) / [githubweb](https://github.com/kokkos/kokkos/commit/293f6f07791046016745bfa7f89b395246d96d78))
    Rebased and added reduce functions to newly added simd types ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#959bf66dd483da08fbf434620e15b0ea11c6f68e) / [githubweb](https://github.com/kokkos/kokkos/commit/959bf66dd483da08fbf434620e15b0ea11c6f68e))
    Added KOKKOS_ENABLE_DEPRECATED_CODE guards ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#63d191e4f2d8d06130708b853bb228b88d0d6903) / [githubweb](https://github.com/kokkos/kokkos/commit/63d191e4f2d8d06130708b853bb228b88d0d6903))
    Refactored simd reductions; removed signed shift left tests ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#4f3871ce2809b654974c462a47612ede78bead79) / [githubweb](https://github.com/kokkos/kokkos/commit/4f3871ce2809b654974c462a47612ede78bead79))
    Fix error outputs from MSVC build ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#6c7b30e067a71a5ebd8811d9cfc228d34322b973) / [githubweb](https://github.com/kokkos/kokkos/commit/6c7b30e067a71a5ebd8811d9cfc228d34322b973))
    Modified to use identity element based on input mask ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#d111add6c5ada0c6f32901ddcc44ded9be1cc432) / [githubweb](https://github.com/kokkos/kokkos/commit/d111add6c5ada0c6f32901ddcc44ded9be1cc432))
    Removed unused functions ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#495f39bfbe547f6c306f48faefa295891480be49) / [githubweb](https://github.com/kokkos/kokkos/commit/495f39bfbe547f6c306f48faefa295891480be49))
    Update CEA weekly tests configuration (#7475) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#c14c94be1426396b394fbb9651a23e80acbb34d5) / [githubweb](https://github.com/kokkos/kokkos/commit/c14c94be1426396b394fbb9651a23e80acbb34d5))
    atomic_compare_exchange: compare fcn name typo (#7467) ([details](https://jenkins-son.sandia.gov/job/Kokkos_develop_blake_intel_2023_2_0-icpc_openmp_serial_cpp17/136/changes#e6e5c4598d16d756db62225ab7f937ee833bd660) / [githubweb](https://github.com/kokkos/kokkos/commit/e6e5c4598d16d756db62225ab7f937ee833bd660))

@ldh4 @crtrott 

**Please include the following for a minimal reproducer**

**Reproducer notes** (blake all or H100 queue):
```bash
source /projects/x86-64-icelake-rocky8/spack-config/blake-setup-user-module-env.sh
module purge
module load intel-oneapi-compilers/2023.2.0 intel-oneapi-dpl/2022.2.0 intel-oneapi-tbb/2021.10.0 cmake git

$KOKKOS_PATH/generate_makefile.bash --with-openmp --with-serial --compiler=icpc --cxxstandard=17 --cxxflags="-Wall" --arch=SKX
```

**Comment by ldh4** [comment]
I think this may be resolved by https://github.com/kokkos/kokkos/pull/7484.
