### ISSUE TITLE
Question: make errors building Kokkos in older Trilinos using gcc 12.3

### ISSUE THREAD

**Issue by ikalash** [kokkos/kokkos#7494]
This is not a bug report, but rather a question.

I am trying to build an older version of Trilinos on perlmutter using gcc 12.3.  The version is from Oct. 2018 (af3613cc1feb749f73056b849b2ad20ddbe7589f).  When I make Trilinos, I get errors that look like:
```
/global/homes/i/ikalash/MOR_Albany/Trilinos/build/KokkosCore_config.h:5:1: error: stray ‘\’ in program
    5 | \#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
      | ^
/global/homes/i/ikalash/MOR_Albany/Trilinos/build/KokkosCore_config.h:5:2: error: stray ‘#’ in program
    5 | \#if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
      |  ^
```
(full error log attached).  I am guessing that the issue is that the older Kokkos is not compatible with the more modern compiler/C++ standard.  Do you have any insight into whether that is what would cause this sort of error?  I tried also with gcc 10.3.0 and got the same error.

[make_out.txt](https://github.com/user-attachments/files/17563887/make_out.txt)

**Comment by ikalash** [comment]
I tried building Trilinos with the same compiler on a different machine and did not get this same error, so it must be related to the Perlmutter environment.  Any input on what could be causing this sort of behavior would be helpful so that I can try to figure out a workaround.

**Comment by masterleinad** [comment]
The question is how you get the extra `\` in `\#if`. https://github.com/trilinos/Trilinos/blob/af3613cc1feb749f73056b849b2ad20ddbe7589f/packages/kokkos/core/cmake/KokkosCore_config.h.in looks good to me but it's not clear to me if `KokkosCore_config.h` was created from that file in the 2.7.0 release (supposedly `TriBITS` would have done that).
If the file was created using the `Makefile` build system (which seems likely given the line numbers you posted), https://github.com/kokkos/kokkos/issues/6605 might have fix it.

In either case, there is no guarantee that that old version works fine with new compilers.

**Comment by ikalash** [comment]
@masterleinad : thanks for the reply.  Right, I was wondering how the extra \ came in there too.  I saw that the file was generated in the build dir by the build system.  I made sure to clear by build directory just in case but then the problem appeared again.  Maybe @bartlettroscoe has an idea, as a TriBits expert?

I looked at the other issue, and it appears a PR was merged in, no?  I am indeed using make > 4.3 on Perlmutter but not on the other machine where I built successfully with the same compiler.  This makes me think the issue is not the compiler version but, rather, the make version.

**Comment by masterleinad** [comment]
> I looked at the other issue, and it appears a PR was merged in, no? I am indeed using make > 4.3 on Perlmutter but not on the other machine where I built successfully with the same compiler. This makes me think the issue is not the compiler version but, rather, the make version.

Yes, I would assume it's the `make` version. The relevant pull request fixing it is likely rather https://github.com/kokkos/kokkos/pull/2972 (Kokkos 3.2.00). Since you are using Kokkos 2.7.00, that fix is not present.

**Comment by ikalash** [comment]
Ah yes, you are right, my version will not have the fix.  I will apply it later today to see if the issue can be resolved.

**Comment by ikalash** [comment]
So the patch fixed this issue - thank you!  Now i get a build error from kokkos-kernels:

```
[ 16%] Built target kokkosalgorithms
packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/build.make:8787: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:4830: packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/all] Error 2
```
Do you know what this could be caused by?  I don't know the Kokkos/Trilinos build system well enough to spot the issue.  I guess build.make gets generated on the fly.  Line 8787 of the build.make file looks like:
```
ackages/kokkos-kernels/src/libkokkoskernels.so.12.13: /opt/cray/pe/libsci/23.12.5/GNU/12.3/x86_64/lib/libsci_gnu.so\ \ \ \ \ \ \ -D\ TPL_LAPACK_LIBRARIES:FILEPATH$(EQUALS)/opt/cray/pe/libsci/23.12.5/GNU/12.3/x86_64/lib/libsci_gnu.so
```

**Comment by bartlettroscoe** [comment]
> Maybe @bartlettroscoe has an idea, as a TriBits expert?

Being that https://github.com/kokkos/kokkos/pull/2972 seems to be related to the Makefile build system feature of Kokkos, it does not seem that TriBITS is related?  Is this project using raw Makefiles instead of CMake?

**Comment by ikalash** [comment]
I was able to get the issue resolved by fiddling with the environment.  Thank you everyone for your help!
