### ISSUE TITLE
Question: Fat binaries for machines with mixed KNL and Xeon nodes

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#750]
I'm not sure about other compilers, but intel enables fat binaries to target KNLs and Xeon CPUs with the flag `-axMIC-AVX512` according [slide 27 here](https://www.alcf.anl.gov/files/Intel%20Compiler%20Optimization%20and%20Building%20for%20KNL.pdf).

Am I able to specify multiple `KOKKOS_HOST_ARCH` options or otherwise override the architecture flags to use the one above?

Or am I running on old info and this is no longer needed?

**Comment by crtrott** [comment]
Uhm technically we might be able to do this, so far there is no explicit support. One of the main issues may be our explicit usage of assembly.

**Comment by crtrott** [comment]
Let me add: right now we don't support this, and I also don't think that there are frequent production use cases for this. In the case of you actually wanting to do something like a full Trinity study, you can just set up an MPI config file which uses different executables on different node types.

**Comment by dholladay00** [comment]
Ah ok. I'll look into it. 

Would applications that depend on mine need to create 2 executables, one that links against the KNL version and another that links against the Xeon version?

**Comment by crtrott** [comment]
Yeah probably. I am not sure if you could generate two different libraries (one for KNL and one for Xeon) and link against both simultaneously from the same application. That might actually be possible.
