### ISSUE TITLE
Can i tell Kokkos::parallel_reduce whether to use the Cuda device or the host to run threads?

### ISSUE THREAD

**Issue by tawiesn** [kokkos/kokkos#751]
I have Tpetra enabled with both Cuda and Serial Node enabled  and write unit tests for it. By default all unit tests run for each enabled node type (e.g., Cuda and Serial). The corresponding Kokkos::Views live either on the Cuda device or on the host.

However, if i try to run a parallel kernel (e.g., through Kokkos::parallel_reduce), the cuda test works fine, but the Serial test crashes with 
> Assertion `Kokkos::View ERROR: attempt to access inaccessible memory space` failed.

This makes, sense: the Kokkos::View lives definitely on the host, but it seems, that Kokkos::parallel_reduce again tries to create threads on the device from where i cannot access the View.

I only call Kokkos::initialize once in the very beginning of the unit test executable (but not within each unit test). Is there a way that i can tell Kokkos::parallel_reduce the device type to use? Or can we only run unit tests for the "default" device which in my case would be cuda (or whatever is configured as default device). I think it is not that easy to call Kokkos::initialize() and finalize() within each unit test.

**Comment by dholladay00** [comment]
I believe you can specify the execution space in your range policy.

**Comment by tawiesn** [comment]
@dholladay00 Thanks, that solved the problem.
