### ISSUE TITLE
cuda 11.0 and 11.2 link failure with cmake >= 3.17 and glibc 2.34 

### ISSUE THREAD

**Issue by nmm0** [kokkos/kokkos#7512]
cuda 11.0 and 11.2 are not compatible with glibc 2.34 librt stubs, which seem to be linked in to the CMake  bundled CUDAToolkit.cmake. Since we switch to our own bundled CUDAToolkit (that I guess has a workaround for this issue and doesn't bring in librt) for cmake version < 3.17 , this works fine with cmake 3.16

e.g.
```
[  4%] Linking CXX executable Kokkos_CoreUnitTest_DeviceAndThreads
cd /____/code/kokkos/cmake-build-cuda11_0-debug/core/unit_test && /local-projects/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-11.4.1/cmake-3.30.2-dj6l4ur5mwiaqjvldxwrqzp5g6sirnmd/bin/cmake -E cmake_link_script CMakeFiles/Kokkos_CoreUnitTest_DeviceAndThreads.dir/link.txt --verbose=1
/____/code/kokkos/bin/nvcc_wrapper -g -DKOKKOS_DEPENDENCE -arch=sm_70 CMakeFiles/Kokkos_CoreUnitTest_DeviceAndThreads.dir/UnitTest_DeviceAndThreads.cpp.o -o Kokkos_CoreUnitTest_DeviceAndThreads  ../src/libkokkoscore.a /local-projects/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-11.4.1/cuda-11.0.2-skqtv3hsp2mnkreco5i7htua5yvnnao2/targets/x86_64-linux/lib/stubs/libcuda.so /local-projects/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-11.4.1/cuda-11.0.2-skqtv3hsp2mnkreco5i7htua5yvnnao2/lib64/libcudart.so /usr/lib64/librt.a -ldl
nvlink fatal   : Could not open input file '/usr/lib64/librt.a'
```

With librt being the stub (since it is bundled in glibc 2.34 and above):

```
$ cat /usr/lib64/librt.a
!<arch>
```

**Comment by nmm0** [comment]
Our current decision is that cuda < 11.4 is not officially supported on these systems anyway, so we will not support it. A workaround would be to use an older version of cmake (3.16 or earlier).

**Comment by crtrott** [comment]
Generally RedHat9 for example is only supported starting at CUDA 11.8
