### ISSUE TITLE
Command line processing of --threads argument prevents users from having any commandline arguments starting with --threads

### ISSUE THREAD

**Issue by jjellio** [kokkos/kokkos#760]
Kokkos takes ownership of all command line arguments starting with '--threads' (--numa, device, ndevice as well).  This prevents users from having any command line arguments starting with these strings, e.g., --threads_for_me, --threadsA, etc...

The logic at line 251 only checks that the argument starts with the specified string, not that the string starts with AND ends with '=' (line 253)
https://github.com/kokkos/kokkos/blob/36b92f437de3945b54e67ed8ce015746ae985a34/core/src/impl/Kokkos_Core.cpp#L251

**Comment by ibaned** [comment]
It looks like you're suggesting moving the conditional on line 253 to line 251, which seems perfectly reasonable to me, at least for the `--threads` variant. Unless someone else on the team objects, we can probably do this.

**Comment by ibaned** [comment]
I've implemented this more generally in PR #800. If that is accepted this will be fixed in the `develop` branch.
