### ISSUE TITLE
QUESTION - lambda and local member data

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#762]
I understand that *this gets copied in a lambda expression.  My question is if I had a class like this would the lambda expression copy the RCP multiple times and cause a race condition?/?  Or just once?  specifically on GPU

```
class foo{
 RCP<View> vp;
 View v;

  void my_func () [
     v = *vp;
     parallel_for(100, KOKKOS_LAMBDA (int i) {v(i)=0;});
  }
};
```

**Comment by ibaned** [comment]
1. Capturing `this` in a lambda can be problematic, especially with CUDA, so try to avoid capturing `this`. An easy way to avoid it is to create local variables:
```cpp
void my_func() {
  auto local_v = v;
  parallel_for(100, KOKKOS_LAMBDA(int i) { local_v(i) = 0; });
}
```
2. Having an `RCP<View>` seems very redundant to me. `Kokkos::View` already had RCP semantics, so I can't think of any reason why you'd want to wrap it in an `RCP`. This also answers your question about the race condition: the proper usage to treat `Kokkos::View` as an `RCP`, and it has special code in it to handle RCP semantics properly when it gets copied onto a GPU or CPU thread.

**Comment by bathmatt** [comment]
I thought that *this got captured, not this.  The local_v has no real effect in that case, correct??

The answer to #2 is 
Because I resize my view elsewhere which invalidates the have saved.  So I need a local copy of it...

**Comment by ibaned** [comment]
By default, `this` gets captured, not `*this`. There is support via `KOKKOS_CLASS_LAMBDA` and CUDA 8.0 to capture `*this`. @crtrott explains it better than me in his answer to #695, please take a look at that discussion as well.

**Comment by ibaned** [comment]
> The local_v has no real effect in that case, correct??

The `local_v` has the important effect that only `local_v` gets copied, as opposed to `this->v` (essentially `this`) which will segfault on GPUs, and even if you use `KOKKOS_CLASS_LAMBDA`, you'll copy all of `(*this)` including that `RCP<View>`, which is anything from a compile error to a race condition on GPUs (this was your original concern, which is valid).

`this` or `*this` are only copied if a member variable is used in the lambda.

**Comment by bathmatt** [comment]
OK, Thanks.  
so next question, when I call a functor does *this get copied only once :)

**Comment by ibaned** [comment]
If its a functor, then the meaning of `*this` in that context is the functor object itself. I think the copy does only happen once, but it may be a copy onto the GPU, which I think is still problematic for `Teuchos::RCP`, which cannot execute on the GPU (including constructor/destructor calls). Basically, I'd make sure that the `RCP` never gets copied to the GPU.

**Comment by bathmatt** [comment]
I'm thinking that it should never get used, but copied should be fine if it is a once only, and not like once per league.  I would like to create operators in my class and then call them parallel_for(100,*this)

**Comment by ibaned** [comment]
Yea, I would expect that to produce at least a compile warning on CUDA, saying you're calling a `__host__` function (`RCP` constructor or destructor) from your kernel. Although it is not a race condition, it is likely to crash with CUDA, even if it compiles. This is a guess, you can try it and confirm.

This issue of `View` invalidation on resize seems annoying... have you confirmed that this invalidation actually happens ? I'm not familiar enough with `View` internals to know if this is the case.

Some options:
1. Create local variables and only use those in a lambda
2. Create a separate functor class with only CUDA-compatible members and use that
3. Replace `RCP` with `View*`. This requires some external object to "own" the real one. Error-prone.
4. Get rid of `RCP` if invalidation doesn't happen ?

**Comment by ibaned** [comment]
I just asked @crtrott , the invalidation is real. I guess you do have to work around it somehow.

**Comment by bathmatt** [comment]
Thanks..
