### ISSUE TITLE
QUESTION - Use non-default execution space with lambdas

### ISSUE THREAD

**Issue by tawiesn** [kokkos/kokkos#763]
It is my understanding that
```
Kokkos::parallel_for("example", nnzEstimate, KOKKOS_LAMBDA(const LO j) {
      valsAux(j) = zero;
    });
```
runs on the default node. I want to run the parallel for on a specific execution_space.

Trying

```
typedef Kokkos::RangePolicy<local_ordinal_type, execution_space> range_type;
Kokkos::parallel_for("example", range_type(0,nnzEstimate), KOKKOS_LAMBDA(const LO j) {
      valsAux(j) = zero;
    });
```
leads to the compiler error

` error: calling a __device__ function("operator()") from a __host__ function("exec") is not allowed
`
which makes sense looking at the definition of KOKKOS_LAMBDA which is [=]__device__ in my case (i've set KOKKOS_ENABLE_CUDA_LAMBDA=1 and i'm using cuda 7.5.18).

Using a functor instead of lambdas works just fine.

Is there another way to use lambdas on a specific execution space (rather using functors?)

**Comment by ibaned** [comment]
I think you either have to switch to `[=] __host__ __device__`, or limit yourself to only run on the default execution space. Others can correct me if I'm wrong here.

**Comment by jhux2** [comment]
@jhux2

**Comment by tawiesn** [comment]
@ibaned: I think that is what KOKKOS_LAMBDA does if you are using Cuda 8.0.
I tried it by hand and it didn't compile. Gave me error messages like

> error: The closure type for a lambda ("lambda [](int)->void") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function

I think for now it's the easiest for me to use functors only.

**Comment by ibaned** [comment]
I think proper `__host__ __device__` support only exists with CUDA 8.0, so if you want to support CUDA 7.5 then `__device__` lambdas are needed, which by definition cannot execute on the host, so if you want to compile a single templated library that can run kernels on either the host execution space or the GPU, with CUDA 7.5, you probably need to stick to functors.

In my own project I drop the ability to use multiple execution spaces in one binary, and use device lambdas.

**Comment by tawiesn** [comment]
@ibaned Thanks for your answer. Fully makes sense.

I think in our case we do not want to drop the abiltiy to use multiple execution spaces. One reason is that it makes testing easier. Furthermore, it is somewhat hard to communicate that problem to the final end user (like "you can compile in support for any combination of Scalars, LO, GO, but for the Node type you are stuck to only one"). It may significantly reduce external support requests if we allow users to have more than one Node type enabled.

**Comment by jhux2** [comment]
@ibaned We also can't make that decision at the linear solver level, it's really a Trilinos-wide decision.

**Comment by tawiesn** [comment]
See also https://github.com/trilinos/Trilinos/issues/1278

**Comment by crtrott** [comment]
There is one more problem with LAMBDAS and that is creating them inside of class member functions. To really do that in combination with compilation for multiple execution spaces we gonna need CUDA 9 and C++17 support ...

**Comment by tawiesn** [comment]
@ctrott Thanks for clarification.

**Comment by ctrott** [comment]
@crtrott & @tawiesn redirecting to correct persons. Interesting thread, thanks.

**Comment by tawiesn** [comment]
Thanks. For now we use functors and try lambdas later again. Thanks for all responses
