### ISSUE TITLE
(develop branch) Issue with custom reduction type

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#772]
I have a type that I use for nested reduction. Latest pull form develop produced error:
```
kokkos/core/src/impl/Kokkos_Reducer.hpp(71): error: no instance of constructor "multiple_sums::multiple_sums" matches the argument list
            argument types are: (int)
    void init( value_type & dest ) noexcept { dest = value_type(0); }
```

From discussion with @crtrott, allow `init` to initialize `dest` with `value_type`'s default constructor rather than `0` when type is not arithmetic. Maybe something like:

```c++
void init( value_type & dest ) noexcept { dest = value_type(); }
```

**Comment by mhoemmen** [comment]
@dholladay00 That code should work for any value_type with a default constructor, right?  It should zero-initialize built-in arithmetic types too.

**Comment by dholladay00** [comment]
In `core/src/impl/Kokkos_Reduce.hpp`, around line 71, there is an init. My custom type is not arithmetic, but the reducer tries to initialize with `0`. Do I just need to implement a specialization for when `std::is_arithmetic< value_type >::value` is `false`?

For a first pass, I was just going to remove the 0 from that line and see if that worked.

**Comment by mhoemmen** [comment]
@dholladay00 I think your code works regardless of whether value_type is an arithmetic type.  That suggests we should just replace `value_type(0)` with `value_type()`.

**Comment by dholladay00** [comment]
Yes, that is what @crtrott suggested, but he wasn't sure that would work for all cases. @dsunder suggested `value_type{}` for the replacement but also wasn't convinced that the fix would be that simple for the general case.
