### ISSUE TITLE
[question] flush L2 cache on GPUs ?

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#779]
Right now I do, 
```
LLC_CAPACITY = 64*56*4*1024*1024; // 64 SM 56 core per SM 4 MB L2 cache per core
View<double*> buf("buf", LLC_CAPACITY/sizeof(double));
deep_copy(but, 1);
parallel_reduce(0, LLC_CAPACITY/sizeof(double)), sumFunctor, sumValue);
printf_to_null("%f", sumValue);
```

Is this a right thing to do ? I do this on host but I am not sure if this works on GPUs. If so, is there a way that Kokkos can provide this architecture L2 cache size ? When I compile kokkos, I give --arch argument. Kokkos may be able to provide some architecture cache size. Right now I need that information for performance benchmark but I will also need it for cache blocking algorithms.

**Comment by crtrott** [comment]
The SMs don't have an L2. There is a a total of 4MB L2 cache shared by all 56 SMs. Each SM has 64 32bit cores which share a common 32kB L1. On top of it you should have an occupancy of at least 25%. That means your L2 is shared amount 56*512=28672 active threads at a minimum. At that point you will have a grand total of 18 double values per thread capacity in L2.

I am not sure that we can query this stuff reliably.

**Comment by kyungjoo-kim** [comment]
Thanks.
