### ISSUE TITLE
Improve Kokkos CUDA debug experience

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#781]
In LAMMPS we avoid using UVM for performance reasons. However, for Kokkos CUDA this leads to some hard to find bugs when there are missing data transfer directives between the two memory spaces (i.e. `sync` and `modify` between `host` and `device`). Not sure if it would be possible, but it would be helpful to have more diagnostics to help find missing or misplaced `sync` and `modify` when there is more than one memory space. See PR #780 for an idea.

**Comment by ibaned** [comment]
Although I agree, we probably need a concrete list of items here.
I'll start with the one mentioned:
 - [ ] have an option to detect concurrent modification of DualView

**Comment by stanmoore1** [comment]
What would help me the most is a way to detect when (and why) using two separate memory spaces will give different behavior than a single memory space.

**Comment by stanmoore1** [comment]
Or a way to emulate two separate memory spaces using the Serial backend, since it is so much easier to debug than on a GPU.

**Comment by ibaned** [comment]
I tried to articulate what @stanmoore1 and I discussed earlier as #783 , which is another sub-item in this meta-issue:
 - [ ] Debug Device space (#783)

**Comment by stanmoore1** [comment]
Or better yet, determine the memory space data dependencies automatically like DARMA does and do the sync/modify automatically for me, haha ;)

**Comment by ibaned** [comment]
> Or better yet, determine the memory space data dependencies automatically like DARMA does and do the sync/modify automatically for me, haha ;)

I think thats basically what UVM tries to do, and would have all the same performance issues :)

**Comment by stanmoore1** [comment]
> I think thats basically what UVM tries to do, and would have all the same performance issues :)
Fair enough ...

**Comment by ibaned** [comment]
Closing this as it is basically equivalent to #783
