### ISSUE TITLE
Need a list of atomic operations and examples

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#782]
Kokkos provides a number of atomic operations.  However, its documents do not cover all atomics and their example.   In particular, I am interested in an atomics that fetch the information of a(i) and update if necessary.  Is there any example?
  
a(i) = (a(i) > b )  ?  a(i) ? b;

**Comment by crtrott** [comment]
There is no such atomic operation. There is a compare and swap though.

**Comment by keitat** [comment]
Is it kokkos::atomic_compare_exchange() ?  Is there any examples of the usage?

**Comment by hcedwar** [comment]
Subsumed into #463
