### ISSUE TITLE
"Debug" version of CUDA MemorySpace

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#783]
@stanmoore1 and I discussed the possibly of implementing the following:

A new `MemorySpace` (`DebugDeviceSpace` ?) that is enabled at least when Kokkos debug mode is on, which has traits that indicate it is *not* accessible from HostSpace, but has copy methods to HostSpace which are the usual host `memcpy`. Possibly a corresponding execution space (`DebugExecSpace` ?) which uses the debug `MemorySpace`.

The idea would be that users can compile Kokkos with just the Serial and Debug spaces, and use those as their "Host" and "Device" spaces. If they have bugs associated with incorrectly copying / synchronizing between Host and CUDA space, these bugs could be replicated using the Debug space, and could be tracked down in a CPU environment, which is much more friendly for debugging than a real GPU.

There should be a way for DualView to use the Host and Debug spaces as well.

**Comment by mhoemmen** [comment]
It used to be the case that `Kokkos::create_mirror_view` (or at least `Kokkos::DualView`) would actually create a separate allocation for the mirror View.  It was still accessible from host, but at least it was different memory; that would catch some errors.  Not sure if this is still the case.

**Comment by ibaned** [comment]
It seems to no longer be the case (which is actually very good from a memory usage standpoint). We're looking for an option to turn that back on and more, for debugging purposes only. I certainly appreciate all the optimizations that have been done for the Host==Device case and we should keep them, just maybe make them optional.

**Comment by crtrott** [comment]
You can do this on KNL by compiling with the memkind library and use the HBW space.

**Comment by stanmoore1** [comment]
This would sidestep issue #870.

**Comment by hcedwar** [comment]
The `Kokkos::create_mirror` function allocates memory for the new view no matter what.
The `Kokkos::create_mirror_view` function only allocates memory if the input view is not accessible from host code.
One option is to call, via your own macros, `create_mirror` for debug builds and `create_mirror_view` for release builds.
Another option is to introduce a Kokkos macro (e.g., `KOKKOS_ENABLE_FORCE_MIRROR_ALLOCATION`) that forces `create_mirror_view` to simply forward to `create_mirror`.

@stanmoore1  Preference?  do it yourself or requests a Kokkos feature for this?

**Comment by stanmoore1** [comment]
> Preference? do it yourself or requests a Kokkos feature for this?

If this will be helpful to other developers using Kokkos, then I think it makes more sense to be a Kokkos feature rather than doing it myself.

**Comment by ibaned** [comment]
> Another option is to introduce a Kokkos macro (e.g., `KOKKOS_ENABLE_FORCE_MIRROR_ALLOCATION`) that forces `create_mirror_view` to simply forward to `create_mirror`.

Okay, I just implemented this and tested it, and its not enough. The problem is that `DualView::sync()` and `DualView::modify()` decide which space they're being told about using a template parameter execution space, and checking the memory space of that to each of its views. So, without an actual new memory space / execution space type, `DualView` has no way of distinguishing between the two for debug purposes. There are several alternative designs for `DualView` that I think would have been better, like `modify_host()`/`modify_device()`, or `modify(HOST)`/`modify(DEVICE)` with runtime values... too late now, `DualView` is designed and used everywhere.

I guess to really get this working we would need a whole new execution space and memory space just for debugging, unfortunately.

**Comment by ibaned** [comment]
There is a new staff member picking up this work again, with what seems like a viable approach. A separate memory space type will be used, and "execution space" detection will be based on kokkos-tools hooks and kernel names. OS-level memory poisoning (page access control) will be used to catch illegal accesses. This seems promising.

**Comment by DavidPoliakoff** [comment]
Hey @ibaned , I just sent you an email (I'm the new staff member), and I have a prototype. People should feel free to ping me (I'm the only Poliakoff in directory I think), this looks really promising

**Comment by DavidPoliakoff** [comment]
Hey folks, I've moved the discussion of this to a Draft PR here https://github.com/kokkos/kokkos/pull/2229 , with the Kokkos Tool it's based off located here https://github.com/kokkos/kokkos-tools/pull/63
