### ISSUE TITLE
1 failed unit test on POWER8+GPU

### ISSUE THREAD

**Issue by robbwu** [kokkos/kokkos#794]
Hi there,

I was trying to test Kokkos on a POWER8 computer. I'm using the primary tested compiler GCC5.4.0 and CUDA/8.0.54. I followed the README to make the unittests and one of them failed:

```
[ RUN      ] threads.team_scratch_request
/ccs/home/pwu11/kokkos/core/unit_test/TestTeam.hpp:662: Failure
Value of: 0
Expected: error_count
Which is: 332
/ccs/home/pwu11/kokkos/core/unit_test/TestTeam.hpp:662: Failure
Value of: 0
Expected: error_count
Which is: 528
[  FAILED  ] threads.team_scratch_request (9 ms)
```

Please let me know what else I can provide. 

Thanks!
pwu

**Comment by crtrott** [comment]
Can you give some more details? For example: what Kokkos version did you use (master, develop, potentially which SHA). What was your configuration (post the KokkosCore_config.h in your UnitTest build directory). What GPU did you try to run on if you compiled for CUDA. 

Thanks

**Comment by crtrott** [comment]
Hi, just wanted to ask again if you can provide that additional information. 

Thanks

**Comment by robbwu** [comment]
Hi Christian,

Sorry for the late reply.

I am using the commit 36b92f437de3945b54e67ed8ce015746ae985a34

The KokkosCore_config.h is included here:

```
/* ---------------------------------------------
Makefile constructed configuration:
Wed May 17 16:19:58 EDT 2017
----------------------------------------------*/
/* Execution Spaces */
#define KOKKOS_HAVE_CUDA 1
#define KOKKOS_HAVE_OPENMP 1
#ifndef __CUDA_ARCH__
#define KOKKOS_USE_ISA_POWERPCLE
#endif
/* General Settings */
#define KOKKOS_HAVE_CXX11 1
/* Optimization Settings */
/* Cuda Settings */
#define KOKKOS_ARCH_POWER8 1
```

The result of the make test is attached. 
[make_test.txt](https://github.com/kokkos/kokkos/files/1009042/make_test.txt)

The GPU is P100.

Best
Panruo

**Comment by crtrott** [comment]
You need to compile for Pascal GPUs: KOKKOS_ARCH=Power8,Pascal60 when running CUDA (Looks like you only did Power8). We actually just put something in to catch this: #813.

Also in your initial posts it looks like you were running the threads backend and not openmp. The threads backend is still not fully supported on Power8 as noted in the readme.

Cheers
Christian

**Comment by hcedwar** [comment]
@robbwu Resolved?
