### ISSUE TITLE
Allow null Future in task spawn dependences

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#795]
Requested by @kyungjoo-kim : allow null Kokkos::Future in task spawn dependence

```c++
               if (f_tgt.is_null()) {
                 auto f = Kokkos::task_spawn
                   (Kokkos::TaskSingle(_sched, Kokkos::TaskPriority::High),
                    TaskFunctor_UpdateSupernodes(_sched, _pool, _info,
_sid, i));
                 _info.supernodes_future(tgt) = f;
               } else {
                 auto f = Kokkos::task_spawn
                   (Kokkos::TaskSingle(f_tgt, Kokkos::TaskPriority::High),
                    TaskFunctor_UpdateSupernodes(_sched, _pool, _info,
_sid, i));
                 _info.supernodes_future(tgt) = f;
               }
```

This code create a chain of futures that append data to a block. The
very first one depends on an empty future and it triggers an error
"Kokkos spawn given null Future".

This makes me duplicate the same code twice to check null future. I
think that if dependent future is null, it just needs to be ignored
instead of error.

**Comment by hcedwar** [comment]
@kyungjoo-kim 
Allow:
```
  Kokkos::task_spawn( Kokkos::TaskSingle( sched , future , priority ), functor );
```
The scheduler argument is necessary in case the future is null.  A non-null future must reference a task previously spawned with the same scheduler.

**Comment by kyungjoo-kim** [comment]
Thank you. This may make the api more verbose. 

Just a thought: 

 another possible suggestion is for a scheduler to produce a null future as a const object and the scheduler ignores the future whenever it comes in. Or possibly I can produce a task with no-op. 

I don't know which way is more elegant.
