### ISSUE TITLE
Move cmake_minimum_required command to top cmake file

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#797]
The current standalone cmake build fails with the following error

> 
CMake Error at cmake/kokkos.cmake:5 (if):
  if given arguments:

    "VERSION_LESS" "3.1"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:8 (INCLUDE)

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.
>

**Comment by netskink** [comment]
Thanks for the note about the parameter must be 'VERSION number.number'
