### ISSUE TITLE
static_assert >=64 bit reduction values on Pascal

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#799]
This is a continuation of #225, in which a `static_assert` was added to check that reduction value types were at least `sizeof(int)`. The Alexa shock hydro team and I have now confirmed several times that 64 bit values are needed on Pascal, and `int` values cause incorrect behavior. This issue is to increase the `static_assert` to 64 bits. It may not be possible to detect at the preprocessor level if the code will ever be run on Pascal, so maybe requiring 64 bits all the time is the way to go.

**Comment by crtrott** [comment]
This might be a red herring. We may only need to align certain internal buffers correct, and or this is yet another instance of the infamous permanent divergence bug.

**Comment by ibaned** [comment]
If you can point to the relevant buffers, I can check whether aligning them also fixes the bug.

**Comment by ibaned** [comment]
It appears they may have actually been due to running code on Pascal (compute capability 6.x) that was compiled for compute capability 3.5. We can close this issue and open a different one, to instead add an abort at `Kokkos::initialize` that will stop users from making this mistake, because clearly it breaks the code. I had no idea that pre-5.0 compiled code would not run correctly on post-5.0 hardware, and we can help others who likely did not know this. Thanks @crtrott for explaining things.
