### ISSUE TITLE
CMake build unit test and install

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#808]

**Comment by dsunder** [comment]
We need to have a discussion about how to support testing.  Right now the Makefiles are up-to-date, the CMakeLists.txt files (use by Tribits) are missing newer tests, and the stand alone cmake does not have rules to build any of the tests.

**Comment by ibaned** [comment]
#816 addressed the blocking portion of this. Maybe this issue will be restricted to just what was in #816, and and will be closed in the next promotion, and another issue should be opened for any remaining concerns like long-term syncing of tests etc.
