### ISSUE TITLE
Getting thread_id in parallel_for

### ISSUE THREAD

**Issue by keitat** [kokkos/kokkos#818]
I am just bringing back the old discussions.
Is it possible to introduce Kokkos::get_thread_id() or conditional_wait inside parallel_for?  I desperately need this to implement parallel tensor decomposition code.

**Comment by hcedwar** [comment]
Dan can tell you about thread-unique "token" functionality that will soon be in the develop branch.  I believe this is what you will need portable way.  What is the functionality you had in mind for conditional_wait?

**Comment by keitat** [comment]
Conditional wait should work like condition variables.  kokkos::cond_wait( Kokkos::View<...> val,  (value that unlock the wait) );  I know this is low-level, but it will help my tensor decomposition code.

**Comment by crtrott** [comment]
You can't do that because the hardware doesn't allow that. You could do it inside a team with some restrictions for one thread waiting on another but even that is tricky. If you really really need to write that you would need to specialize for certain backends, with some (including Cuda, OpernMPTarget and the AMD backend) not working at all.

**Comment by keitat** [comment]
Thanks!  In this case, I can just live with get_tid() to handle my case.

**Comment by keitat** [comment]
In my program, I statically allocate buffer and class per thread before going to parallel_for.  get_thread_id() is used to locate these.

**Comment by crtrott** [comment]
That we can give you and we have it almost available ...

**Comment by hcedwar** [comment]
The "token" functionality @dsunder has in the works is designed to portably underpin what you are doing for "thread private" buffers.  There is also a new, robust memory pool capability in the develop branch which might suffice as well.

**Comment by keitat** [comment]
I saw memory_pool in Kokkos::experimental .   Is there any example program with parallel_for?

**Comment by hcedwar** [comment]
The develop branch has it in Kokkos::MemoryPool.  There are some unit tests and a performance test.
https://github.com/kokkos/kokkos/blob/develop/core/perf_test/test_mempool.cpp

**Comment by crtrott** [comment]
Just as a performance comparison:
For per-thread scratch 
Using scratch level 0 (shared memory on GPU) you can do about 300 Billion allocations per s
Using scratch level 1 (pre allocated scratch in HBM) you can do about 150 Billion allocations per s

This is possible since it is a team-collective operation. So allocating per team scratch takes about the same time and thus gets you down to ~1B allocations per s.

This is on a K40 on a P100 the rates are about 4x higher. 
The memory pool is more like 10s of millions allocs per s.

**Comment by dsunder** [comment]
```c++
/// \brief class to acquire a unique tokens base on the required amount of concurrency
///
/// The value acquired by a thread will be unique to that thread until it is released
/// This object should behave like a ref-counted object, so that when the last
/// instance is destroy resources are free if needed
template <typename ExecutionSpace, UniqueTokenScope = UniqueTokenScope::Instance >
class UniqueToken
{
public:
  using execution_space = ExecutionSpace;
  using size_type       = typename execution_space::size_type;

  /// \brief create object size for concurrency on the given instance
  ///
  /// This object should not be shared between instances
  UniqueToken( execution_space const& = execution_space() );

  /// \brief upper bound for values, i.e. 0 <= value < size()
  KOKKOS_INLINE_FUNCTION
  size_type size();

  /// \brief acquire a unique value such that 0 <= value < size()
  KOKKOS_INLINE_FUNCTION
  size_type acquire();

  /// \brief release an acquired value 
  KOKKOS_INLINE_FUNCTION
  void release( size_type );
};
```

**Comment by crtrott** [comment]
You mind if I implement that for CUDA? Also should we add a `team_acquire` and `team_release`, i.e. a collective overload if every thread in a team calls it at the same time?

**Comment by crtrott** [comment]
Also there is no reason that this needs size_type. Int should be sufficient. In the end we hopefully won't have more than 2billion concurrent threads on a shared memory machine with a single Kokkos instance for a while ....

**Comment by dsunder** [comment]
Give me 30 minutes and I'll add a pull request that only adds the UniqueToken behavior to OpenMP, Threads, and Serial.  You can then implement it for Cuda.

**Comment by crtrott** [comment]
The team_acquire is too much hassle with respect to mixing team_acquire and acquire

**Comment by hcedwar** [comment]
For CUDA use the [impl/Kokkos_ConcurrentBitset.hpp](https://github.com/kokkos/kokkos/blob/develop/core/src/impl/Kokkos_ConcurrentBitset.hpp) - don't duplicate functionality.
If you find performance issues then improve the bitset.  Note how the memory pool generates a hint for acquiring a bit: https://github.com/kokkos/kokkos/blob/develop/core/src/Kokkos_MemoryPool.hpp#L468

**Comment by mhoemmen** [comment]
@dsunder wrote:
> In the end we hopefully won't have more than 2billion concurrent threads on a shared memory machine with a single Kokkos instance for a while ....

Never speak too soon ;-)

**Comment by dsunder** [comment]
- [ ]  Add UniqueToken to Cuda

**Comment by hcedwar** [comment]
Ready with all back-ends using the bitset
