### ISSUE TITLE
task_depend test failing, CUDA 8.0 + Pascal + RDC

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#829]
Illegal memory access in `task_depend` test:
```
1:44:41 [ RUN      ] cuda.task_depend
01:44:41 unknown file: Failure
01:44:41 C++ exception with description "cudaGetLastError() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/workspace/Kokkos_develop_white_cuda_8044_gcc_540_pascal_rdc/kokkos/core/src/Cuda/Kokkos_Cuda_Task.cpp:164
01:44:41 Traceback functionality not available
01:44:41 " thrown in the test body.
01:44:41 [  FAILED  ] cuda.task_depend (20 ms)
```
Seems to be the root of most failures from the White tests last night:

https://jenkins-son.sandia.gov/view/Kokkos/job/Kokkos_develop_white_cuda_8044_gcc_540_pascal_rdc/153/console

**Comment by hcedwar** [comment]
Another TBD issue to resolve with task-dag on pascal.
see: https://github.com/kokkos/kokkos/blob/develop/core/unit_test/TestTaskScheduler.hpp#L351
@ibaned for now stub it out for pascal as above.

**Comment by ibaned** [comment]
@hcedwar got it, will do.

**Comment by ibaned** [comment]
PR #836 stubs this out. running tests on it...

**Comment by ibaned** [comment]
#836 was merged, this no longer blocks promotion.

**Comment by hcedwar** [comment]
Being worked in combination with #758
