### ISSUE TITLE
Append tag name to parallel construct name for Profiling

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#842]
carry-over kokkos/kokkos-tools#14

@stanmoore1

**Comment by ibaned** [comment]
Not sure how feasible this is yet, but conceptually it makes sense

**Comment by crtrott** [comment]
Its something we could do. Need to check how much launch latency it adds. But basically we use already typeid(functor).name() as default label, and we can simply append it with typeid(policy_type::tag_type).name() or so.

**Comment by stanmoore1** [comment]
If the launch latency is high, then could you only enable it when profiling is also enabled?

**Comment by ibaned** [comment]
@stanmoore1  I think thats already the case for the existing code that queries the label, anything we add inside that `#ifdef` block would similarly be protected.

**Comment by nmhamster** [comment]
The issue here is that we want to have profiling be enabled by default. We may end up with some functions for profiling disabled if they affect performance but the premise is "always available profiling". We can talk offline as to why this is important.

**Comment by ibaned** [comment]
I created PR #846, which I think will do what you want. I guess we could do some kind of performance testing with LAMMPS to see how it affects latency ?

**Comment by crtrott** [comment]
I think it should be ok. That said, all pull requests are on hold until:
(i) integration is done
(ii) Dan (Sunderlands) stuff is in.

**Comment by ibaned** [comment]
The changes are in develop

**Comment by stanmoore1** [comment]
@ibaned thanks!

**Comment by stanmoore1** [comment]
Just wanted to say thanks again for this enhancement, it makes profiling my code a lot easier
