### ISSUE TITLE
Add deep_copy Profiling hook

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#843]
When using CUDA, `deep_copy` is a major source of performance degradation. Therefore I think it makes sense to add a profiling hook that is called by `deep_copy`. So far my guess is that the interface should look like `kokkosp_allocate_data`, but with each argument repeated twice (except maybe the allocation `size`).

@stanmoore1

**Comment by crtrott** [comment]
Yeah. That was on our unofficial to-do list. If you want to give a shot feel free.

**Comment by ibaned** [comment]
#865 addresses this.
