### ISSUE TITLE
How to disable profiling interface

### ISSUE THREAD

**Issue by ramanan** [kokkos/kokkos#848]
Is there a way to disable the profiling interface? I am trying to avoid the following warning in our automated builds:

Kokkos_Profiling_Interface.cpp:(.text+0x209): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

so that we can catch the real warnings. It seems that disabling the profiling interface would make them go away. Any other suggestions?

**Comment by ibaned** [comment]
Are you compiling Kokkos as part of Trilinos or using Makefiles?

**Comment by ibaned** [comment]
In Trilinos (TriBITS) the CMake flag to disable it is:
```
-DKokkos_ENABLE_Profiling:BOOL=OFF
```

If possible, try to compile things as shared libraries, that will also get rid of the warning:
```
-DBUILD_SHARED_LIBS:BOOL=ON
```

**Comment by ramanan** [comment]
I am building Kokkos stand alone (not Tribits).

**Comment by ibaned** [comment]
In that case you can pass this flag to `generate_makefile.bash`:
```
--with-options="disable_profiling"
```
I notice that it is not documented, so I will add it to the help output for `generate_makefile.bash`.

**Comment by stanmoore1** [comment]
You can also use dynamic linking and that warning will go away.

**Comment by ramanan** [comment]
On the development systems, I use shared libraries. On the Cray systems, I am using static linking. I will use the build option mentioned above. Thanks for the help.

**Comment by ibaned** [comment]
It looks like @dsunder documented the `disable_profiling` option in b04a4c0, so I'll close this. Please reopen if that option doesn't work.
