### ISSUE TITLE
Segfault when hardware threads / core > 1

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#850]
I have a hand-rolled matrix-vector multiply using Kokkos: 

```c++
parallel_for (TeamThreadRange(team, Y.extent(0)), [&] (const int_t row)
{
  // (A*X)_row
  real_t ax_i = 0.0;
  Kokkos::parallel_reduce (ThreadVectorRange(team, A.extent(1)),
    [&] (const int_t& col, real_t& inner_sum)
  {
    inner_sum += A(row, col)*X(col);
  }, ax_i);
  // Y := beta*Y + alpha*A*X
  Kokkos::single(PerThread(team), [&] ()
  {
    Y(row) = beta*Y(row) + alpha*ax_i;
  });
});
```

When I compile for and run on KNL, I am getting segfaults within the parallel reduce. I am new to KNL, are there any newbie mistakes that would lead to segfaults (running in quad cache mode). 

Note: Segfaults do not always happen, sometimes a different part of the code throws an error and an early exit occurs. When segfaults *do occur*, according to gdb, they appear to occur in the parallel reduce. 

Any ideas as to why the above code would be causing the segfault?
This appears to work correctly on OpenMP (with non-phi hardware) and CUDA backends. 

Info:
* Most recent master branch
* gcc 5.4.0 (same failures with 6.3.0)
* currently I set num_threads = npus (obtained from hwloc), I hear that's not always best for phi.
* `Kokkos::AUTO` gives 4 threads per team.

**Comment by dholladay00** [comment]
Errors are non-deterministic and I am able to occasionally get a view bounds error on debug builds.

One of the issues could be my use of hwloc related to issue #377. 

```c++
mt = 1;
    
hwloc_topology_t sTopology;

if (hwloc_topology_init(&sTopology) == 0 &&
    hwloc_topology_load(sTopology) == 0)
{
  mt = hwloc_get_nbobjs_by_type(sTopology, HWLOC_OBJ_PU);
  nnuma = hwloc_get_nbobjs_by_type(sTopology, HWLOC_OBJ_NODE);
  hwloc_topology_destroy(sTopology);
}

#pragma omp parallel
{
  nt = omp_get_num_threads();
}

if (nt != mt)
  omp_set_num_threads(mt);
```

Notice that I set the number of threads to `mt`, which is obtained from `hwloc_get_nobjs_by_type(topology, HWLOC_OBJ_PU);`, which might be the wrong thing for KNL. Could this setting be clashing with the auto team policy on KNL which wants 4 threads per team?

**Comment by dholladay00** [comment]
This appears to happen on other CPUs as well. I get non-deterministic issues as well (with gcc 5.4.0) on mult-core intel CPUs as well. 

Sometimes I get view bounds errors, other times I do not.

I'm curious if this has something to do with using sequential mkl lapack calls at the team level, but within a `single (PerTeam …`.

**Comment by dholladay00** [comment]
After looking at it more, I think this would be better resolved offline.

**Comment by dsunder** [comment]
@dholladay00 I know that you've closed this, but you don't want to set the number of threads to the number of pus on node; you need to use the process binding.  Consider using the following

```c++
hwloc_topology_t topology;
hwloc_topology_init( &topology );
hwloc_topology_load( topology );

hwloc_cpuset_t process = hwloc_bitmap_alloc();
hwloc_get_cpubind( topology, process, HWLOC_CPUBIND_PROCESS );

int mt = hwloc_bitmap_weight( process );
```

**Comment by dholladay00** [comment]
@dsunder I sent you an email.

If it turns out to be an actual issue with Kokkos, we can update this issue. 

For now, handling offline is preferable.
