### ISSUE TITLE
Question: Index Reference in () Operator

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#854]
What is the difference between `parallel_for (policy, KOKKOS_LAMBDA (const int& i) {…});` and `parallel_for (policy, KOKKOS_LAMBDA (const int i) {…});`?
* Is there a performance benefit to either or is there a preferred choice?
  * Is it completely arbitrary and/or subjective?
* Does it matter in the case of nested parallelism, i.e. `parallel_for (TeamThreadRange(team), [&] (const int& i) {…});`?
* Does it matter for (performance) portability?
  * For a specific backend (thread private or CUDA idiosyncrasies)?

**Comment by crtrott** [comment]
generally the compiler may actually end up doing the same thing. (const int& i) makes it more explicit, and thus its easier for the compiler to do it. And here is one of the little not-quite perfected design corners: for TeamThreadRange (const member_type&), (const member_type) and (member_type) should always work, (member_type&) depends on the backend (i.e. do we inline construct the thing or not).

**Comment by crtrott** [comment]
Short answer: (const T&) is the recommended way.

**Comment by dholladay00** [comment]
So for team/thread and thread/vector `parallel_<for,reduce,scan>`, can I do the normal `operator ()` overloads in a functor?

```c++
functor f();
parallel_for(TeamThreadRange(team), f);
sum_functor g();
double result = 0.0;
parallel_scan(TeamThreadRange(team), g, result);
```

**Comment by crtrott** [comment]
Should work.

**Comment by dholladay00** [comment]
Good to know. 

That resolves the issue in my book. I am ok with closing it, though it could be useful to add the "question" label to it.
