### ISSUE TITLE
Subview construction in body of reduction on a ThreadVectorRange prevents vectorization

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#864]
I am finding that constructing a subview in the loop body yields:

```
remark #15333: loop was not vectorized: exception handling for a call prevents vectorization
```

Is this the expected behavior? 

I can provide more details as necessary.

**Comment by dholladay00** [comment]
As per email conversation with @crtrott, this is expected.

Possibly see about ways around including special treatment of compile-time dimensions.

**Comment by ibaned** [comment]
Closing. Please reopen if it needs to be discussed further.

**Comment by dholladay00** [comment]
FYI #1116 might provide an elegant solution to the problem.

**Comment by hcedwar** [comment]
Could be, see the [commit message](https://github.com/kokkos/kokkos/pull/1116/commits/04c99d68449e5b55762fb86995eab664fdda7158)

**Comment by dholladay00** [comment]
I believe it will for my use cases, I just wanted to document it for the record to tie this issue to that PR.
