### ISSUE TITLE
Enable 32-bit pointers

### ISSUE THREAD

**Issue by andeplane** [kokkos/kokkos#866]
I was wondering why KOKKOS requires 64 bits pointer types. I wanted to compile a KOKKOS-accelerated program with emscripten (to web assembly which supports PThreads), but it failed since pointers are 32 bits. 

Why does KOKKOS require 64 bit pointers?

**Comment by ibaned** [comment]
> I wanted to compile a KOKKOS-accelerated program with emscripten (to web assembly which supports PThreads)

You are a brave person...

All I can say is:
1. We simply have a strong policy of making it clear what is supported and tested versus what isn't, and 32-bit addresses fall into the unsupported category for financial reasons. It is likely that there are a few bits of code that won't work with 32-bit pointers, but I don't know of any myself. @crtrott and @hcedwar are out of the office but they might know. You could try removing the `static_assert` that checks for pointers to be 64 bits. If you're lucky and use a small subset of Kokkos functionality, maybe it will run?
2. Our use of `pthreads` is coming to an end soon, so this adventure you've set out on may only get harder, not easier (unless emscripten and web assembly support C++11 `std::thread`, which is what we're moving towards).

**Comment by ibaned** [comment]
Some quick Googling suggests that `std::thread` may actually work with emscripten, so there is still hope.

**Comment by andeplane** [comment]
Haha I didn't expect it to work :P And thanks for letting me know that PThread support is going away. I'll try to remove the static_assert!

**Comment by hcedwar** [comment]
We know for sure that it will not work with 32bit pointers, thus the static assert to let you know up front rather than mysterious errors.  For HPC, our target application space, there has been no demand for 32bit pointers.  As @ibaned said, without demand from our target users there is no resource-incentive to support it.

**Comment by andeplane** [comment]
Luckily Emscripten now support 64 bit pointers, so will give this a go! I have created this https://andeplane.github.io/atomify/ to run LAMMPS in the browser (works quite nicely on single thread), and the ambition is to have multi threading support using KOKKOS. Wish me luck!

**Comment by andeplane** [comment]
I suppose this may not be super interesting for most people, but I have it working with threads in Webassembly now, with decent speedup. What a fun world this is.

**Comment by dalg24** [comment]
So you know, there is experimental support for 32-bit
https://github.com/kokkos/kokkos/blob/0a5890148b5168793bdb8d01dd978885fef65ba5/CMakeLists.txt#L131-L133
with currently one CI build in place
https://github.com/kokkos/kokkos/blob/0a5890148b5168793bdb8d01dd978885fef65ba5/.github/workflows/continuous-integration-linux.yml#L84-L90

**Comment by andeplane** [comment]
Oh, that is interesting also! I do not need it as 64 bit worked fine now as Emscripten added support for it.

**Comment by andeplane** [comment]
Wohoo, added it here now: https://editor.lammps.org. Works remarkably well in the browser.
