### ISSUE TITLE
f9d3767 broke array reductions on CUDA

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#867]

**Comment by ibaned** [comment]
This is actually a really subtle issue:
```cpp
enum : bool { IsArray = Impl::is_array< typename FunctorType::value_type >::value };
static_assert( IsArray == Impl::is_array< typename FunctorType::value_type >::value, "enums aren't equal" );
```
The `static_assert` above fails! (and this is only seen in OpenMP or CUDA builds...). It is also preceded by many warnings about comparing two different enums.

It seems like typed `enum` values have some serious pitfalls, we're likely better off using

```cpp
static constexpr bool IsArray = ...;
```

**Comment by dsunder** [comment]
static constexpr integral have major portability problems until c++17.

Can you try 

```c++
static_assert( static_cast<bool>(IsArray) == static_cast<bool>(Impl::is_array< typename FunctorType::value_type >::value)
  , "enums aren't equal" );
```

**Comment by ibaned** [comment]
well:
1. The whole point is to get values that are actually typed as `bool` so we get out of these GCC 7 warnings. Always having to `static_cast<bool>` would make me sad.

2. There are *lots* of uses of `static constexpr` in Kokkos already, and I've never seen a compiler complain about it:
```
[daibane@kokkos-dev kokkos]$ grep -rn "static constexpr" *
containers/src/Kokkos_DynRankView.hpp:1062:  static constexpr size_t required_allocation_size(
core/src/KokkosExp_MDRangePolicy.hpp:73:  static constexpr Iterate value = Iterate::Left;
core/src/KokkosExp_MDRangePolicy.hpp:75:  static constexpr Iterate value = Iterate::Right;
core/src/KokkosExp_MDRangePolicy.hpp:84:  static constexpr Iterate value = Iterate::Left;
core/src/KokkosExp_MDRangePolicy.hpp:86:  static constexpr Iterate value = Iterate::Right;
core/src/KokkosExp_MDRangePolicy.hpp:104:  static constexpr int rank = N;
core/src/KokkosExp_MDRangePolicy.hpp:105:  static constexpr Iterate outer_direction = OuterDir;
core/src/KokkosExp_MDRangePolicy.hpp:106:  static constexpr Iterate inner_direction = InnerDir;
core/src/KokkosExp_MDRangePolicy.hpp:129:  static constexpr int rank = iteration_pattern::rank;
core/src/KokkosExp_MDRangePolicy.hpp:131:  static constexpr int outer_direction = static_cast<int> (
core/src/KokkosExp_MDRangePolicy.hpp:136:  static constexpr int inner_direction = static_cast<int> (
core/src/KokkosExp_MDRangePolicy.hpp:143:  static constexpr int Right = static_cast<int>( Iterate::Right );
core/src/KokkosExp_MDRangePolicy.hpp:144:  static constexpr int Left  = static_cast<int>( Iterate::Left );
core/src/Cuda/KokkosExp_Cuda_IterateTile.hpp:382:  static constexpr index_type max_blocks = 65535;
core/src/Cuda/KokkosExp_Cuda_IterateTile.hpp:483:  static constexpr index_type max_blocks = 65535;
core/src/Cuda/KokkosExp_Cuda_IterateTile.hpp:584:  static constexpr index_type max_blocks = 65535;
core/src/Cuda/KokkosExp_Cuda_IterateTile.hpp:720:  static constexpr index_type max_blocks = 65535;
core/src/Cuda/KokkosExp_Cuda_IterateTile.hpp:857:  static constexpr index_type max_blocks = 65535;
core/src/Cuda/KokkosExp_Cuda_IterateTile.hpp:1026:  static constexpr index_type max_blocks = 65535;
core/src/Cuda/Kokkos_Cuda_Parallel.hpp:1109:  KOKKOS_INLINE_FUNCTION static constexpr
core/src/Kokkos_Array.hpp:80:  KOKKOS_INLINE_FUNCTION static constexpr size_type size() { return N ; }
core/src/Kokkos_Array.hpp:81:  KOKKOS_INLINE_FUNCTION static constexpr bool      empty(){ return false ; }
core/src/Kokkos_Array.hpp:133:  KOKKOS_INLINE_FUNCTION static constexpr size_type size()  { return 0 ; }
core/src/Kokkos_Array.hpp:134:  KOKKOS_INLINE_FUNCTION static constexpr bool      empty() { return true ; }
core/src/Kokkos_OpenMP.hpp:203:  static constexpr const char* name() noexcept { return "OpenMP"; }
core/src/impl/Kokkos_ViewMapping.hpp:1234:    static constexpr size_t stride( size_t const N )
core/src/impl/Kokkos_ViewMapping.hpp:1713:    static constexpr size_t stride( size_t const N )
core/src/impl/Kokkos_ViewMapping.hpp:2103:  static constexpr size_type Max( size_type lhs , size_type rhs )
core/src/impl/Kokkos_ViewMapping.hpp:2755:  static constexpr size_t memory_span( typename Traits::array_layout const & arg_layout )
core/src/impl/Kokkos_ViewCtor.hpp:131:  static constexpr type value = type();
core/src/impl/Kokkos_HostThreadTeam.hpp:235:  static constexpr int align_to_int64( int n )
core/src/impl/Kokkos_SharedAlloc.hpp:61:  static constexpr unsigned maximum_label_length = ( 1u << 7 /* 128 */ ) - sizeof(Record*);
core/src/impl/Kokkos_SharedAlloc.hpp:135:  static constexpr unsigned maximum_label_length = SharedAllocationHeader::maximum_label_length ;
core/src/impl/Kokkos_Utilities.hpp:88:  static constexpr std::size_t size() noexcept { return sizeof...(Ints); }
core/src/impl/Kokkos_Utilities.hpp:175:  static constexpr T value = h0;
core/src/impl/Kokkos_Utilities.hpp:182:  static constexpr T value = h1;
core/src/impl/Kokkos_Utilities.hpp:189:  static constexpr T value = h2;
core/src/impl/Kokkos_Utilities.hpp:196:  static constexpr T value = h3;
core/src/impl/Kokkos_Utilities.hpp:203:  static constexpr T value = h4;
core/src/impl/Kokkos_Utilities.hpp:210:  static constexpr T value = h5;
core/src/impl/Kokkos_Utilities.hpp:217:  static constexpr T value = h6;
core/src/impl/Kokkos_Utilities.hpp:224:  static constexpr T value = h7;
core/src/impl/Kokkos_Utilities.hpp:356:  static constexpr T value = Result::value ;
core/src/impl/Kokkos_Utilities.hpp:369:  static constexpr value_type value  = helper::value ;
core/src/impl/Kokkos_Utilities.hpp:396:  static constexpr T value = Result::value ;
core/src/impl/Kokkos_Utilities.hpp:409:  static constexpr value_type value  = helper::value ;
core/src/impl/Kokkos_ConcurrentBitset.hpp:82:  KOKKOS_INLINE_FUNCTION static constexpr
core/src/impl/Kokkos_ConcurrentBitset.hpp:92:  KOKKOS_INLINE_FUNCTION static constexpr
core/src/impl/Kokkos_FunctorAnalysis.hpp:249:  KOKKOS_INLINE_FUNCTION static constexpr
core/src/impl/Kokkos_FunctorAnalysis.hpp:254:  KOKKOS_INLINE_FUNCTION static constexpr
core/src/impl/Kokkos_FunctorAnalysis.hpp:264:  KOKKOS_FORCEINLINE_FUNCTION static constexpr
core/src/impl/Kokkos_FunctorAnalysis.hpp:268:  KOKKOS_FORCEINLINE_FUNCTION static constexpr
core/src/impl/Kokkos_FunctorAnalysis.hpp:275:  KOKKOS_FORCEINLINE_FUNCTION static constexpr
core/src/impl/Kokkos_FunctorAnalysis.hpp:280:  KOKKOS_FORCEINLINE_FUNCTION static constexpr
core/src/Kokkos_HBWSpace.hpp:150:  static constexpr const char* name();
core/src/Kokkos_HBWSpace.hpp:155:  static constexpr const char* m_name = "HBW";
core/src/Kokkos_HostSpace.hpp:156:  static constexpr const char* name() { return m_name; }
core/src/Kokkos_HostSpace.hpp:160:  static constexpr const char* m_name = "Host";
core/src/Kokkos_View.hpp:1354:  static constexpr size_t required_allocation_size(
core/src/Kokkos_CudaSpace.hpp:93:  static constexpr const char* name() { return m_name; }
core/src/Kokkos_CudaSpace.hpp:104:  static constexpr const char* m_name = "Cuda";
core/src/Kokkos_CudaSpace.hpp:189:  static constexpr const char* name() { return m_name; }
core/src/Kokkos_CudaSpace.hpp:196:  static constexpr const char* m_name = "CudaUVM";
core/src/Kokkos_CudaSpace.hpp:237:  static constexpr const char* name() { return m_name; }
core/src/Kokkos_CudaSpace.hpp:241:  static constexpr const char* m_name = "CudaHostPinned";
```

**Comment by ibaned** [comment]
not all of these are integral members, but some of them definitely are.

**Comment by ibaned** [comment]
This one in particular seems pretty central:
https://github.com/kokkos/kokkos/blob/1dcc3509b58c9a20bc04d690ccce762e24a883df/core/src/impl/Kokkos_SharedAlloc.hpp#L61

**Comment by dsunder** [comment]
Technically, it is not valid to compare different enum types to each other.  To compare enum types requires converting to an integral type first.  Before c++11 this conversion to an integral happened implicitly but the standard now states the following (summarized)

```c++
enum : int { A };
enum : int { B };
enum class EnumC : int { C };

bool test;
test = A == 0;                    // valid: implicit conversion of A to int
test = A == B;                    // error: no implicit conversion rule
test = static_cast<int>(A) == B;  // valid: implicit conversion of B to int
test = C == 0;                    // error: not implicit conversion rule
test = static_cast<int>(C) == 0;  //valid


```

**Comment by ibaned** [comment]
Thats fine, the `static_assert` above is for illustration/debugging only. The real problem is that I would then go and use `IsArray` in place of `Impl::is_array< typename FunctorType::value_type >::value`, as an argument to `Impl::is_c` or `Impl::enable_if`, and it would have the wrong value.

So if we're already depending on `static constexpr` to work (since at least d2a4e50 in May 2015), why not use those instead of `enum`s that always have to cast to use safely?

**Comment by dsunder** [comment]
```c++
static constexpr int name = value;
```

Causes problems with some compilers because it sometimes creates an symbol with linkage which interacts badly with nvcc.  Things tend to work ok until it falls over when it tries to use it in another context (normally when it is passed as a function argument instead of a template parameter).  We have be transitioning to typed enums since they are more portable and do not generate symbols.

**Comment by ibaned** [comment]
> normally when it is passed as a function argument instead of a template parameter

I think this is the key to what goes wrong, basically storage is only created if the address of the member is taken, and in Kokkos there is a habit of declaring arguments as having type `const T&` instead of just `T`, and since a reference is a pointer, that invites the compiler to take the address of a `static constexpr` variable and create storage for it.

So the pitfall with `static constexpr` is "don't take its address, even implicitly".

That seems less bad than the pitfalls with even typed enums:
1. Can't compare two enums of the same type without casting (what if I make a casting mistake like signed->unsigned and its negative?)
2. `enum : bool` gets the wrong value if assigned from some other kind of enum
If anything, they seem less type safe and less convenient.


As for the current bug, changing `Kokkos::Impl::integral_constant::value` and `IsArray` to `static constexpr` fixes it. I'll see if I can fix it by carefully typing all the enums, but even if it works I don't think its the best solution.

**Comment by dsunder** [comment]
I agree the enum edge cases are ugly, but I wonder how hard it would be to ensure that we never take the address of a ```static constexpr```

**Comment by ibaned** [comment]
@dsunder wrote:
> wonder how hard it would be to ensure that we never take the address of a `static constexpr`
The basic rule of thumb would be: pass integral values around by value, not by reference.

@ibaned wrote:
> I'll see if I can fix it by carefully typing all the enums
As an update to this, making `Kokkos::Impl::integral_constant::value` a typed enum:
```cpp
enum : T { value = v };
```
didn't help the compile error we're seeing (IsArray still doesn't behave correctly).
Note the recommended implementation of `std::integral_constant` is with `static constexpr` ([link](http://en.cppreference.com/w/cpp/types/integral_constant#Example)).

The failure case for `static constexpr` is a link error with the name of the symbol clearly denoted, whereas the failure case for typed enums seems to be mysteriously changing values all the classes of errors associated with integer casting. In this case it resulted in a compile error, but its possible for it to go undetected and just choose the wrong template instantiation that still runs but is no what we expect.

I'll come back to this after a meeting, but right now I don't see a way to both avoid `static constexpr` and silence GCC 7 warnings about enums in boolean context.

**Comment by hcedwar** [comment]
Actually better off using enum : int_type { ... }; everywhere due to some underdefined behavior in C++11 for static constexpr that will be corrected in C++17.

Sent from my iPad

On Jun 6, 2017, at 10:13 AM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:


This one in particular seems pretty central:
https://github.com/kokkos/kokkos/blob/1dcc3509b58c9a20bc04d690ccce762e24a883df/core/src/impl/Kokkos_SharedAlloc.hpp#L61

-

**Comment by ibaned** [comment]
Okay, there was some confusion about where and why this fails. Near as I can tell, it seems to be a CUDA compiler issue only that requires a static cast:
```cpp
enum : bool { IsArray = static_cast<bool>(Impl::is_array< typename FunctorType::value_type >::value) };
```

The fix is in develop now...
I rest my case, typed enums are error-prone and the rules for using them safely are non-obvious. However, I'm outvoted here.
