### ISSUE TITLE
Why is Pthreads default?

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#868]
In Makefile.kokkos `KOKKOS_DEVICES`, why is the `Pthreads` backend the default and not `OpenMP`?

**Comment by crtrott** [comment]
Because the default clang compiler on Mac doesn't have OpenMP. So Pthreads will work practically everywhere OpenMP will not work on many DOE peoples laptops.

**Comment by mhoemmen** [comment]
@crtrott btw this is not true of the CMake build system; Serial is still the default.  I'm happy with that but not sure if that's what you meant to happen.

**Comment by nmhamster** [comment]
@crtrott @mhoemmen - perhaps we should have OpenMP by default unless on Mac OS X and then its pthreads?

**Comment by mhoemmen** [comment]
@nmhamster Let's ask Rich Drake and Paul Wolfenbarger.  The only issue there is that users might not enable OpenMP in their build, but might use an OpenMP-enabled BLAS or other TPL.  Then the threads would fight :(
