### ISSUE TITLE
Windows: snprintf

### ISSUE THREAD

**Issue by danturner** [kokkos/kokkos#87]
snprintf isn’t supported by windows Visual Studio < 2015. There is a workaround that I’ve hacked into my local version: http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010. We could also just require Visual Studio 15 for windows users, but I haven’t tested this.

**Comment by crtrott** [comment]
I believe this is fixed on develop

**Comment by crtrott** [comment]
Pushed to master
