### ISSUE TITLE
Extra -arch=xxx argument in KOKKOS_LDFLAGS

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#872]
After updating Kokkos today, I am getting a linking error when trying to link my application that uses Cuda through Kokkos:

 ```
/home/etphipp/project/tensors/TTB_cpp/kokkos/install/opt_gnu49_cuda/bin/nvcc_wrapper   -g -lineinfo -isystem /home/software/boost/1.60.0/include --std=c++11 -expt-extended-lambda -mavx -arch=sm_35 -Xcompiler -fopenmp -I./ -I/home/etphipp/project/tensors/TTB_cpp/kokkos/build/opt_gcc49_cuda/../../install/opt_gnu49_cuda/include -I/home/etphipp/project/tensors/TTB_cpp/kokkos/build/opt_gcc49_cuda/../../install/opt_gnu49_cuda/include -I/home/etphipp/project/tensors/TTB_cpp/kokkos/build/opt_gcc49_cuda/../../install/opt_gnu49_cuda/include -I/usr/local/software/hwloc/current/include -I/usr/local/cuda/include -O3 -DNDEBUG   CMakeFiles/cpals.dir/driver/Genten_Driver_CpAls.cpp.o  -o bin/cpals -rdynamic lib/libgenten.a lib/libgenten_mathlibs.a -L/home/software/boost/1.60.0/lib -lboost_iostreams -lz -llapack -lblas -L/home/etphipp/project/tensors/TTB_cpp/kokkos/build/opt_gcc49_cuda/../../install/opt_gnu49_cuda/lib -L/usr/local/software/hwloc/current/lib -mavx -arch=sm_35 -L/usr/local/cuda/lib64 -fopenmp -lkokkos -ldl -lhwloc -lcudart -lcuda -lcublas -lcusolver 
nvcc fatal   : redefinition of argument 'gpu-architecture'
```

You can see that -arch=sm_35 is supplied twice.  I use KOKKOS_CXXFLAGS as my CXXFLAGS and KOKKOS_LDFLAGS as my LDFLAGS.  Previously -arch was not added to KOKKOS_LDFLAGS, but it is now, causing the error.  If I strip -arch from KOKKOS_LDFLAGS first, it works.

So why was -arch added to KOKKOS_LDFLAGS?

**Comment by etphipp** [comment]
You might ask why I am passing CXXFLAGS to the link step.  I don't do that.  CMake does that.  I just set CMAKE_CXXFLAGS (to KOKKOS_CXXFLAGS).

**Comment by ibaned** [comment]
@etphipp could you specify which of the (now 3) Kokkos build systems you're using?
1. Kokkos as a Trilinos package (TriBITS)
2. Kokkos as a sub-package of a "pure" CMake project ("CMake")
3. `Makefile.kokkos` (Makefile)

**Comment by etphipp** [comment]
I build Kokkos using option 3 (Makefile).  The application is a pure CMake project, which currently pulls in Kokkos settings by greping Makefile.kokkos (because before Kokkos didn't support a non-Tribits CMake build, I guess it does now).

**Comment by ibaned** [comment]
Maybe you can try switching to option 2? @bjoo, @bartgol, and @dholladay00 developed it.

I think you've already identified your current problem, which is that `KOKKOS_CXXFLAGS` from the Makefile.kokkos system is not meant to be combined with `KOKKOS_LDFLAGS` and send both to the linker, which CMake does for some reason.

**Comment by ibaned** [comment]
Another option is to use some of the CMake string functions to remove from `LDFLAGS` anything that is already in `CXXFLAGS`

**Comment by etphipp** [comment]
I plan to move to option 2 at some point.  How robust is it?  Are there any examples?

I am currently working around the issue in exactly the way you suggest, by stripping -arch from LDFLAGS.  But to be honest, I think this is a bug that should be fixed on the Kokkos side.

As a general rule, you supply CXXFLAGS to the linker so that shared libraries will be linked correctly.  So it is very common to supply both CXXFLAGS and LDFLAGS on the link step.  I would expect that if you leave it as is, more people will run into this issue.

**Comment by crtrott** [comment]
Yeah the reason we added it LDFLAGS is that for relocatable device codes it needs to be added to the link step and KOKKOS_CXXFLAGS is not intended to be added to the link step. This is short coming of CMake. I mean how do you add flags to the compilation step which can not be added to the link step?? For example if you don't use the same thing for linking and for compiling?

**Comment by crtrott** [comment]
We actually had situations where you can't add the CXXFLAGS to the linker.

**Comment by ibaned** [comment]
> I plan to move to option 2 at some point. How robust is it? Are there any examples?

I honestly don't know much about it, thats why I mentioned its developers hoping they can comment.

> I would expect that if you leave it as is, more people will run into this issue.

That really only happens if you try to mix `Makefile.kokkos` with CMake, which until now we didn't think anyone was doing and its really not recommended.

**Comment by etphipp** [comment]
I'm doing it that way because until very recently, that was the only way you could pull Kokkos into a non-Tribits CMake build!

**Comment by dholladay00** [comment]
Small example located in `example/cmake_build` 

Also, prior to this method, I used the external_project machinery of cmake which worked but not well particularly with compile/link flags.

**Comment by etphipp** [comment]
If you believe this is the correct behavior, that's good with me!

**Comment by dholladay00** [comment]
There are not very many people using standalone cmake. Essentially we made changes until it worked for our purposes, so there could definitely be issues with it. I am certainly not a cmake expert. If you see something that is wrong or not cmake-y, feel free to change and submit a PR. 

I only ask that if changes are made to cmake, the example `example/cmake_build` should be update as necessary.
