### ISSUE TITLE
Kokkos mangles stack traces

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#876]
One of the things that makes programming with Kokkos difficult is that it seems impossible to get a helpful strack trace when there is an issue inside a parallel region. The stack trace from `gdb` doesn't point to file and line numbers in the user's code inside the parallel_for, but instead references file and line numbers from `Kokkos_Parallel.hpp` etc. This is even true when using the `Serial` backend. Is there any way to improve this issue?

**Comment by nmhamster** [comment]
@stanmoore1 - what compiler combination are you using?

**Comment by stanmoore1** [comment]
I take back what I said, I did a simple check and this does work with the `Serial` and `OpenMP` backends if I use `gdb` and with the `CUDA` backend if I use `cuda-gdb` (I thought in the past it didn't).

However, the real case I am debugging now with `cuda-gdb` gives a useless single frame stack trace in `Kokkos_Cuda_abort.hpp`. Not sure what the difference is.

<pre>
#0  0x000000001c9f0d30 in _ZN6Kokkos4Impl36cuda_parallel_launch_constant_memoryINS0_11ParallelForIZN9LAMMPS_NS14NPairSSAKokkosINS_4CudaEE5buildEPNS3_9NeighListEEUnvdl1_MS6_FvS8_ENS6_5buildE1_NS3_21NPairSSAKokkosExecuteIS5_EENS_11RangePolicyIJS5_EEES5_EEEEvv<<<(1,1,1),(1,256,1)>>> ()
    at /home/stamoor/lammps_USER-DPD/src/Obj_kokkos_cuda_openmpi_db/../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_abort.hpp:75
</pre>

**Comment by stanmoore1** [comment]
Closing #876.
