### ISSUE TITLE
Provide Makefile.kokkos logic in TriBITS

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#878]
This is a mirror of trilinos/Trilinos#1400.

**Comment by kruger** [comment]
After phone call with Dan* and Roscoe, agreement was reached on how to remove as much duplicated logic from ```KOKKOS_PATH/kokkos.cmake``` and ```Makefile.kokkos``` as possible.

By beefing up the cmake generation in ```KOKKOS_PATH/core/src/Makefile```., the cmake system can do a ```make -f KOKKOS_PATH/core/src/Makefile build-cmake-kokkos``` and use the generated cmake file.  The config header file will also be generated by the ```Makefile.kokkos``` file.   

Miscellaneous issues:

* Need to ensure that cmake can bypass this makefile invocation.
* There are currently two ```kokkos.cmake``` files.  This is adding to the confusion and needs to be sorted out.
* There is the installed cmake file and that used for building.  The installed should be ```kokkos_config.cmake``` and serves a different purpose from the build version (which has a bunch of internal variables).  The current version can serve as something to distinguish public and private well. 
* With better integration with TriBITS, it might be useful to move private variables to public if needed.  It should be easy to do so.

**Comment by crtrott** [comment]
Question: does this mean CMAKE will be required to be available? Or do we just pre generate a file with cmake which we then commit to the repository and include in our Makefile build? My concern is that we actually use Kokkos based apps in CoDesign settings where CMake is not necessarily available.

**Comment by hcedwar** [comment]
This may be addressed in PR #1106

**Comment by crtrott** [comment]
Merged into develop ...

**Comment by crtrott** [comment]
Also I upgraded this to a feature request. Spend already close to 40 hours on it on top of the stuff Scott did. And Ross had to do quite a bit of stuff as well. Turns out this was not just some small enhancement, but a complete rewrite of the cmake and tribits build system support.

**Comment by mhoemmen** [comment]
@rrdrake @prwolfe (two folks who know how much time build systems can eat up ;-) )

**Comment by crtrott** [comment]
Btw. it might be worthwhile to figure out if this impacts Sierra somehow.

**Comment by crtrott** [comment]
Still need installation testing. In particular the following matrix:

| | App Make | App CMake |
| --- | --- | --- |
| Install Make | | |
| Install CMake | | |
| Install Tribits | | |

I.e. whether it works to install Kokkos with any build system, and then you can build with CMake or Make against that installation.

**Comment by crtrott** [comment]
Still need installation testing. In particular the following matrix:

| | App Make | App CMake |
| --- | --- | --- |
| Install Make | | |
| Install CMake | | |
| Install Tribits | | |

I.e. whether it works to install Kokkos with any build system, and then you can build with CMake or Make against that installation.

**Comment by kruger** [comment]
@crtrott  I've just pushed a commit for a bug fix to issue-878 on Tech-X/kokkos.git (https://github.com/Tech-XCorp/kokkos/commit/6a079d87d4779ee4203e9c88263ed83c86e205a9)

If you want me to push it somewhere else, please let me know.

**Comment by crtrott** [comment]
I will cherry pick this into develop.
