### ISSUE TITLE
Link Error with Kokkos v2.03.05 and OpenMP

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#879]
I just updated to LAMMPS to use Kokkos master v2.03.05 and I'm getting a link error internal to Kokkos when using OpenMP, see below. Kokkos CUDA still builds and runs fine, and OpenMP worked fine before updating. Any ideas?

<pre>
/lammps/src/Obj_kokkos_omp/libkokkos.a(Kokkos_OpenMP_Exec.o): In function `Kokkos::OpenMP::is_initialized()':
/lammps/src/Obj_kokkos_omp/../../lib/kokkos/core/src/OpenMP/Kokkos_OpenMP_Exec.cpp:236: multiple definition of `Kokkos::OpenMP::is_initialized()'
/lammps/src/Obj_kokkos_omp/libkokkos.a(Kokkos_OpenMPexec.o):/lammps/src/Obj_kokkos_omp/../../lib/kokkos/core/src/OpenMP/Kokkos_OpenMPexec.cpp:234: first defined here
/lammps/src/Obj_kokkos_omp/libkokkos.a(Kokkos_OpenMP_Exec.o): In function `Kokkos::OpenMP::initialize(unsigned int, unsigned int, unsigned int)':
</pre>

**Comment by hcedwar** [comment]
Looks like you updated without cleaning out the old install first.
The referenced source file was renamed.

**Comment by stanmoore1** [comment]
Ah yes, I forgot `make-clean`. Thanks!
