### ISSUE TITLE
Windows: atomic_fetch_sub()

### ISSUE THREAD

**Issue by danturner** [kokkos/kokkos#88]
There’s no implementation of atomic_fetch_sub() in Kokkos_Atomic_Windows.hpp.

**Comment by danturner** [comment]
Here's the implementation that I used in my local repo: 

 template < typename T >
  KOKKOS_INLINE_FUNCTION
	  T atomic_fetch_sub(volatile T * const dest,
	  typename Kokkos::Impl::enable_if< sizeof(T) == sizeof(long), const T >::type val)
  {
	  union { long i; T t; } assume, oldval, newval;

	  oldval.t = *dest;

	  do {
		  assume.i = oldval.i;
		  newval.t = assume.t - val;
		  oldval.i = _InterlockedCompareExchange((long*)dest, newval.i, assume.i);
	  } while (assume.i != oldval.i);

	  return oldval.t;
  }

**Comment by crtrott** [comment]
Pushed to master
