### ISSUE TITLE
Launch PThreads from worker thread

### ISSUE THREAD

**Issue by andeplane** [kokkos/kokkos#886]
Hi,

I'm working on an application where the heavy work is run on a worker thread. I wanted to accelerate parts of the heavy work with KOKKOS, but this doesn't work. I get an error
`std::runtime_error: ThreadsExec::start FAILED : Called by a worker thread, can only be called by the master process.`

which is pretty self explanatory. I'm using PThreads since this is running on macOS (even iOS). So my question is:
1) why is this necessary?
2) is there any way to get around this?
3) will this be different when you switch from PThreads to std::thread?

Thanks!

**Comment by hcedwar** [comment]
I need more context in order to answer.  What is the call-stack?  Are you trying to initialize Kokkos again from within a parallel kernel?  or something else?

**Comment by andeplane** [comment]
Allright! 

Well, I have created a tool that runs the molecular dynamics package LAMMPS (lammps.sandia.gov) and visualizes the current state after each timestep. Molecular dynamics is a physics simulator that based on forces between a set of atoms, moves the atoms around according to Newton's laws. 

So basically, I have a main thread (GUI) and a worker thread (so far no KOKKOS). The worker thread is in full control of LAMMPS and whatever LAMMPS is doing. After each computed timestep, the two threads are synchronized so atomic positions can be uploaded to GPU and visualized.

The worker thread has then the responsibility of everything LAMMPS does. Inside LAMMPS, KOKKOS is initialized and used. The two threads I have are QThreads (I'm using the Qt library). 

I'm not initializing KOKKOS form a parallel kernel, but just my regular worker thread. 

Not sure if this explains enough though? What triggers this message?

**Comment by hcedwar** [comment]
We call a thread that calls Kokkos initialize and subsequent parallel_* operations a "master" thread.
A master thread should only call Kokkos initialize/finalize once - this is a global operation just like you are only allowed to call MPI initialize/finalize once.
I suspect (since you haven't told me) your synchronization mechanism is to exit the qthreads, do the synchronization work, and then re-start the whole thing.  This is re-initializing, which is not permitted.

**Comment by hcedwar** [comment]
BTW: you should never mix threading models.  So if you are mixing qthreads and OpenMP in the same app you are asking for problems.

**Comment by andeplane** [comment]
My worker thread pauses while synchronization happens on main thread and continues after that is done. KOKKOS is not initialized more than once (and I get this error before any of my synchronization between threads happens). 

QThreads is a must in my application (and works well with OpenMP btw). QThreads are built using PThreads so they are the same threading model I guess?

So in my case, my worker thread is the Kokkos master thread. I'll see if I can dig more into the details.

Thanks!

**Comment by dsunder** [comment]
The current Threads backend has an assumption that the thread which calls "main" is the master thread for Kokkos, when the new Thread backend goes in this assumption will be removed.  You could try using the OpenMP backend.  If you only make OpenMP calls from your worker thread it will most likely work.  If you try this please make sure you set the following environment variables at a minimum.
```
OMP_PLACES=threads
OMP_PROC_BIND=spread,close
OMP_WAIT_POLICY=PASSIVE
OMP_DYNAMIC=true
```

**Comment by andeplane** [comment]
I see! OpenMP works, but the reason why I want PThreads (or std::thread) is that I want to run the application multithreaded on iOS with native clang which doesn't support OpenMP :) 

Thanks!

**Comment by hcedwar** [comment]
Heads up - we do not test (and thus cannot support) Kokkos on iOS.  You can try it, it might work, but absolutely no promises...

**Comment by andeplane** [comment]
Yeah I expect zero support on this ;)

Thanks :)
