### ISSUE TITLE
Way to disable Kokkos::Cuda::initialize warning?

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#889]
`Kokkos::Cuda::initialize` prints the following warning to stderr on each MPI process:
```
Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 3.5 on device with compute capability 3.7 , this will likely reduce potential performance.
```
Is there a way to disable such warnings?  They are useful on a small number of processes, but not very nice on many MPI processes.  Thanks!

**Comment by ibaned** [comment]
I don't think there is an I agree. This is part of a bigger general issue that any warnings printed by Kokkos are printed on all MPI ranks. Kokkos continues to avoid depending on MPI but there are already some ugly hacks that read MPI info from environment variables.

I'll see if I can bring up the overall issue of warnings on all ranks at today's Kokkos meeting.

**Comment by stanmoore1** [comment]
Yeah these types of warnings are really annoying when you are running on several hundred thousand MPI ranks or more. In the version of Kokkos bundled with LAMMPS I have commented out warnings like this if necessary.

**Comment by etphipp** [comment]
Maybe add option to initialize() so that it doesn't print out any warnings, no matter what?

**Comment by ibaned** [comment]
@dsunder is introducing options to print Kokkos warnings on MPI rank 0 only. This will be in develop within the next few days.

**Comment by ibaned** [comment]
Things for @dsunder  to do:
 - [ ] make the default option "print on MPI rank 0 only"
 - [ ] make sure all things printed by Kokkos are handled by this new system

**Comment by crtrott** [comment]
Btw. this particular warning is actually something which I am thinking of making a hard error. There is an issue with running code which is not compiled for Pascal on Pascal GPUs for example. And there could be more issues like that going forward.

**Comment by ibaned** [comment]
We did make it a hard error to run (< 5.0) code on (>= 5.0) hardware in #804. Still, it took us a while to catch that issue, so maybe requiring equality in all cases would be good.
