### ISSUE TITLE
Windows: sys/mman.h

### ISSUE THREAD

**Issue by danturner** [kokkos/kokkos#89]
sys/mman.h doesn’t exist on windows. This one might be kind of tricky. I used a google code version of mman as a workaround: https://code.google.com/p/mman-win32/ . I’m not sure what a more permanent solution would look like.

**Comment by crtrott** [comment]
I believe we have guards already but they are not uniformly used and in particular missing for an include in base allocator. The other usage is in guest. Maybe we can hack up our copy of it??

**Comment by crtrott** [comment]
I think we got this fixed on develop

**Comment by crtrott** [comment]
Pushed to master
