### ISSUE TITLE
Make Experimental a terminal namespace

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#892]
Promoting experimental features is difficult and often requires changing codes to use the entire scope specification to detect the appropriate implementation.  Making Experimental the terminal namespace would simplify many of these difficulties.

```c++
Kokkos::Experimental
Kokkos::Impl::Experimental
```

**Comment by crtrott** [comment]
Uhm what do you mean?

**Comment by hcedwar** [comment]
All new uses of `Experimental` namespace should be
```c++
Kokkos::Experimental
Kokkos::Impl::Experimental
```
and don't use `Kokkos::Experimental::Impl` anymore.

**Comment by crtrott** [comment]
Ah that makes sense ...
