### ISSUE TITLE
Question: MPI interop

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#895]
I currently use libquo (https://github.com/lanl/libquo) to work with an application that runs best with MPI everywhere.

Currently we switch to using 1 MPI rank per node and allow OpenMP to use the entire machine. Based on a conversation with @dsunder, it sounded like a **better** solution would be to switch to 1 MPI rank per NUMA domain (no first touch issues).

Is that a widely agreed upon?

**Comment by nmhamster** [comment]
@dholladay00 - I would agree with @dsunder. In general our approach to obtaining the best performance in our codes has followed the advice of _not_ allowing MPI ranks to spawn more than one NUMA domain (although you may have an argument for multiple ranks _per_ NUMA domain if the algorithms do not thread easily). This has the benefit on ensuring you do not go across slower inter-NUMA-domain buses which will help to reduce latency and improve bandwidth.

**Comment by dholladay00** [comment]
Is this also reasonable for many-core architectures like KNL, or do they need to be treated differently?

**Comment by mhoemmen** [comment]
Current experience with MPI + OpenMP, whether or not one uses Kokkos, is that the number of processes and threads are tuning parameters and one must experiment with them.  Best settings depend on the application.  I don't think it's Kokkos' job to tell users how to do that.

**Comment by nmhamster** [comment]
I agree with @mhoemmen, milage will vary considerably based on application use cases and the level of threading added to your code. Experimentation is the only way to answer that. My experience has been that a "balanced" number of MPI ranks and threads seems to give the best overall performance on KNL systems with between 4 and 16 ranks and 4 to 64 OpenMP threads per rank giving good performance depending on the use cases, for some codes pure MPI is the best. If your question refers to NUMA on KNL (in the SNC modes) then you try to avoid having the OpenMP ranks associated with a thread execute over multiple NUMA domains -- i.e. try to ensure the OpenMP affinity settings/environment variables group the threads within a single NUMA domain where possible. I hope that helps!

**Comment by dholladay00** [comment]
I find this very helpful!

Thanks!
