### ISSUE TITLE
Improve Atomics Performance on KNL/Broadwell where PREFETCHW/RFO is Available

### ISSUE THREAD

**Issue by nmhamster** [kokkos/kokkos#898]
Initial research studies show there may be improved atomics performance on machines with RFO/`PREFETCHW` instructions available assuming atomics have low contention rates. Want to investigate adding this to Kokkos atomic operations to improve performance.

**Comment by crtrott** [comment]
Did someone do any performance analysis (i.e. when does it help when does it hurt?) In the end most of the use cases are probably low contention so I guess its a good change overall with little downside. But we should document this somewhere.
