### ISSUE TITLE
Provide tuple and tie

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#900]
If we don't already, it may be worth considering providing `Kokkos::tuple` and `Kokkos::tie`. The motivation for this is the Trilinos MiniTensor package, which currently uses `boost::tie` to return arguments from some `KOKKOS_INLINE_FUNCTION` calls.

**Comment by hcedwar** [comment]
Tuple is some heavyweight template machinery, consider the cost/benefit.
Does boost::tie actually work in Cuda code?

**Comment by ibaned** [comment]
> Does boost::tie actually work in Cuda code?

I suspect not, which is why I'd like MiniTensor to move away from it so it can be safely used in CUDA code.

> Tuple is some heavyweight template machinery

Thats unfortunate... I was hoping it would be somewhat straightforward...
