### ISSUE TITLE
Separate clang-cuda nightly testing

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#915]
The nightly testing of officially unsupported configuration clang-cuda always fails on Jenkins' _Kokkos_apollo_ nightly test and shows red on the Jenkins dashboard.  The clang-cuda test suite should be separate clearly identified item on the Jenkins dashboard.

**Comment by crtrott** [comment]
I am closing this issue, because this was not due to some clang weirdness but because a static was added in a place where a static should not be and nvcc just ignores it. Also Clang 4.0 now works for everything and I promote it to officially supported ....
