### ISSUE TITLE
Qthread taskpolicy initialization bug.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#92]
There are a couple of typos in Qthread task policy constructor. I fixed and submit a pull request and somehow this commit is appended to my previous pull request (team barrier) which is not resolved yet. If some one can make a quick fix for this, I appreciate for it. 

core/src/Qthread/Kokkos_Qthread_TaskPolicy.hpp
@@ -490,7 +490,7 @@ class TaskPolicy< Kokkos::Qthread >
   KOKKOS_INLINE_FUNCTION
   TaskPolicy( const TaskPolicy & rhs )
     : m_default_dependence_capacity( rhs.m_default_dependence_capacity )
-    , m_team_size( m_team_size )
+    , m_team_size( rhs.m_team_size )
     , m_active_count_root(0)
     , m_active_count( rhs.m_active_count )
     {}
 @@ -499,7 +499,7 @@ class TaskPolicy< Kokkos::Qthread >
   TaskPolicy( const TaskPolicy & rhs
             , const unsigned arg_default_dependence_capacity )
     : m_default_dependence_capacity( arg_default_dependence_capacity )
-    , m_team_size( m_team_size )
+    , m_team_size( rhs.m_team_size )
     , m_active_count_root(0)
     , m_active_count( rhs.m_active_count )
     {}

**Comment by crtrott** [comment]
Pushed to master
