### ISSUE TITLE
Efficient data transfer between multiple GPUs

### ISSUE THREAD

**Issue by HBTUM** [kokkos/kokkos#920]
I am fairly new to the Kokkos package and am currently trying to figure out an efficient way to transfer data between multiple GPUs.
As far is I have gathered from the documentation and previously asked questions every GPU I want to use has to be accessed from a separate MPI process. This arises the question on how to transfer data from one GPU to another. My knowledge of Kokkos leads to the suggestion that I have to Copy from GPU_0 to Host_0 to Host_1 to GPU_1. This seems rather inefficient when everything happens on one Node and the GPUs are connected via PCIe. Is there already something available which is comparable to CUDA's "cudaMemcpyPeer()" ?
If not is there a routine which already handles the GPU->Host->Host->GPU copy process?

**Comment by mhoemmen** [comment]
There are different ways to do this.  If you choose to use MPI, and if your MPI is GPU-aware, then you can give CUDA device pointers as input or output buffers to `MPI_*` functions (e.g., `MPI_Send`, `MPI_Recv`, `MPI_Allreduce`), and it will just work.  This has nothing to do with Kokkos.  As long as each MPI process can access a GPU, this will work.  (It could even be possible for multiple MPI processes to share a single GPU.)

I'll let other folks comment on Kokkos-based ways to do this.

**Comment by ibaned** [comment]
I think the Kokkos team has made an explicit decision to not currently support multiple GPUs from the same Kokkos-enabled process, and so there are no pure-Kokkos mechanisms to do this.

Either @mhoemmen 's suggestion or the GPU-(deep_copy)->Host-(MPI)->Host-(deep_copy)->GPU method are the ways I'm aware of.

**Comment by mhoemmen** [comment]
btw, on modern GPU nodes with the right MPI, the MPI-based approach should not actually copy any of the data to host.  It should go straight from one GPU to the other GPU.  Of course, host has to issue the CUDA copy kernels, but the actual data being copied shouldn't ever need to touch host memory.

**Comment by ibaned** [comment]
@mhoemmen can you elaborate on what "the right MPI" is? how far along is support for this in OpenMPI and MPICH? This is a pretty important consumer of time in an application I work on.

**Comment by crtrott** [comment]
OpenMPI since 1.8 MVAPICH since 1.7 or so. MPICH does not currently support this. On the other hand if you buy a GPU machine than you should just also get a compatible MPI installed.

**Comment by HBTUM** [comment]
Thank you for your answers. The solution with a Cuda aware OpenMPI compilation allowed for a direct transfer from GPU to GPU.
