### ISSUE TITLE
Qthread initialization missing options

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#93]
The Qthreads backend only has an initialization option for the total number of threads but not for the ones which set the default team_size. We need those options.

**Comment by nmhamster** [comment]
Can you not map this into the shepherds that Qthreads create? Aren't these a similar idea? At some point I think you could find out how many of these you were running. I think HWLOC does all the magic with some fixes from George Stelle and Dylan Stark to do with affinity.

**Comment by crtrott** [comment]
Not gonna happen soon: Qthreads is considered experimental for now.

**Comment by hcedwar** [comment]
Qthreads back-end is being overhauled.  This issue is out-of-date.
