### ISSUE TITLE
TestViewCtorPropEmbeddedDim uses DynRankView

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#930]
`DynRankView` is not part of `kokkos/core`, so it shouldn't be used in `kokkos/core/unit_test`. The file `kokkos/core/unit_test/TestViewCtorPropEmbeddedDim.hpp` should either be modified to only use `kokkos/core` types or it should be moved to `kokkos/containers/unit_tests`.

In particular, the Trilinos (TriBITS) build fails with:
```
/home/daibane/src/Trilinos/kokkos/core/unit_test/TestViewCtorPropEmbeddedDim.hpp:49:34: fatal error: Kokkos_DynRankView.hpp: No such file or directory
compilation terminated.
kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial.dir/build.make:230: recipe for target 'kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial.dir/serial/TestSerial_Other.cpp.o' failed
```

**Comment by ndellingwood** [comment]
@ibaned thanks for diagnosing, will get a fix in shortly.
