### ISSUE TITLE
Flag to force separate address space in dual view, even on CPU?

### ISSUE THREAD

**Issue by tcfisher** [kokkos/kokkos#933]
I am wondering if there is a build flag available in Kokkos to force a host and dual view to have separate address spaces on architectures that don't have separate host and device memories? If not, will you please consider this a feature request?

This would be useful for debugging synchronization of views for the gpu without having to actually use the gpu architecture.

**Comment by ibaned** [comment]
There isn't right now, but you're not the first one to ask.

This request is basically the same as #783 originally proposed by @stanmoore1.

We now have at least two users asking for this, so it will likely be implemented soon.

**Comment by ibaned** [comment]
See discussion in #783, I think we'll need to introduce new execution and / or memory spaces to really get this to work...

**Comment by ibaned** [comment]
This is really a duplicate of #783, which based on attempts still seems pretty hard. I'll close this one and efforts can continue in #783.
