### ISSUE TITLE
Rendezvous performance regression

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#936]
Moving the rendezvous step variable into the rendezvous buffer introduced performance regression
Exposed by `./policy_performance.host 1000 1 1 100000 1 1 1 1 2 100`

**Comment by ndellingwood** [comment]
@hcedwar @dsunder 
Running the same case as above on KNL (with 1/10 less iterations to reduce runtime) demonstrated performance improvement of develop branch to master branch of 9% when comparing min times after ten runs. 
There was more flux in the develop branch results, for example:
develop ranges: min = 2.087922   max = 2.255668
master  ranges: min = 2.292342    max = 2.362365

**Comment by ndellingwood** [comment]
@dsunder @hcedwar 
That same test (code 100 i.e. parallel_for with team_policy but no nested parallelism) appears to run well on KNL only with the conditions in the first comment - all other tests seem to show performance regression.

`hwloc-bind core:0-63 ./policy_performance.host 1000 1 1 50000 1 1 1 1 1 100`
about 2% regression

`./policy_performance.host 1000 1 32 25000 1 1 5 1 1 100`
~23% regression

`./policy_performance.host 1000 1 32 25000 1 1 4 1 2 100`
~ 14% regression

`./policy_performance.host 1000 1 32 25000 1 1 5 1 2 100`
~ 14% regression 

`./policy_performance.host 1000 1 32 25000 1 1 8 1 2 100`
~ 14% regression

**Comment by ndellingwood** [comment]
hwloc-bind core:0-63 used in all the tests report above (didn't grab it when copy/pasting)

**Comment by hcedwar** [comment]
for reference https://github.com/kokkos/kokkos/commit/c7d95558317c8c8f0780efa1572b81f0c70695b7

**Comment by hcedwar** [comment]
The team rendezvous implementation will be restored to match the master branch where each member of the team maintains its own team rendezvous step.

**Comment by hcedwar** [comment]
Team collective performance has been restored.  Global collective performance used in the parallel_scan and TeamPolicy parallel dispatch performance is still problematic.

**Comment by ndellingwood** [comment]
@hcedwar 
Some performance results with PR #971 (compared to master branch)
Improvements on KNL (possibly a bit more tuning?)

On Power
./policy_performance.host 1000 1 32 25000 1 1 5 1 1 100
improvement: 54%

./policy_performance.host 1000 1 32 25000 1 1 4 1 2 100
Improvement: 59%

./policy_performance.host 1000 1 32 25000 1 1 5 1 2 100
Improvement: 51%

./policy_performance.host 1000 1 32 25000 1 1 8 1 2 100
Improvement: 60%


On KNL:
./policy_performance.host 1000 1 32 25000 1 1 5 1 1 100
Regression: 2.8% previously 23%

./policy_performance.host 1000 1 32 25000 1 1 4 1 2 100
Regression: 7% previously 14%

./policy_performance.host 1000 1 32 25000 1 1 5 1 2 100
Regression: 6% previously 14%

./policy_performance.host 1000 1 32 25000 1 1 8 1 2 100
Regression: 3% previously 14%

**Comment by ndellingwood** [comment]
@hcedwar @crtrott Merged #971; as discussed the performance tests of concern on Power will be tracked in a separate issue; integration testing should be ready to resume.

**Comment by nmhamster** [comment]
@dsunder @hcedwar @crtrott @ndellingwood - please see PR #935 for POWER8 assembly yields.

**Comment by hcedwar** [comment]
follow on #985
