### ISSUE TITLE
Tasking bug 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#94]
I have the following work scenario.

        for (int i=0;i<ntasks;++i) {
          future_type f = policy.create(simple_task_type(a,b,i), max_task_dependence);
          policy.spawn(f);
        }
        Kokkos::Experimental::wait( policy );

Since task is created and its handle is kept in the task queue, this should be okay (I think). However, this returns the following error.

Kokkos::Impl::TaskManager<Kokkos::Threads>::assign ERROR deleting task(0x1d55e30) m_ref_count(0) , m_wait(0x0)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Impl::TaskManager<Kokkos::Threads>::assign ERROR deleting
Traceback functionality not available

At this moment, Kokkos unit tests do not filter this.

**Comment by crtrott** [comment]
Is this still an open issue?

**Comment by kyungjoo-kim** [comment]
Yes, it seems so. The example simply creates a list of tasks without dependence. Somehow this still returns the same error. All my other examples have some dependence among tasks and I don't think that we test this simple cases.

**Comment by hcedwar** [comment]
I created a unit test for this yesterday and will fix upon my return nest week.

**Comment by kyungjoo-kim** [comment]
So, you already reproduced the same error. If not, I can provide my test code (it is already in the shylu directory for my own testing).

**Comment by hcedwar** [comment]
In master
