### ISSUE TITLE
Respawn when memory pool allocation fails (not available memory)

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#940]
@hcedwar 
I would like to respawn until it gets available memory. Current respawn API requires dependence.

```
respawn(self, dependence, priority)
```

How can I respawn this like periodic pooling

**Comment by hcedwar** [comment]
Do you mean respawn when memory pool allocation might be available; e.g., the dependence is that some other task has deallocated memory?

**Comment by kyungjoo-kim** [comment]
I mean respawn when memory is not available. I am going to use tight bound of memory pool and sometimes it is possible that memorypool cannot allocate. However, I know some memory will be released and available while executing tasks and I want to put this task back and check memory again with respawning. Since this task already satisfy the dependence, dependence would not be changed.

**Comment by kyungjoo-kim** [comment]
I tested respawn with an empty future. It seems to be working but I am also concerned about whether this is an expensive way to do spin lock. Any better suggestion ?

**Comment by mhoemmen** [comment]
@kyungjoo-kim I'm not sure if it's even possible to implement a spin lock this way.  I remember wanting to use Kokkos tasks for MPI polling (since MPI doesn't promise to make asynchronous progress on nonblocking operations), but Christian said it wouldn't work.

**Comment by hcedwar** [comment]
@kyungjoo-kim Did you try`respawn( this , scheduler , priority )` ?

**Comment by kyungjoo-kim** [comment]
this is not exactly polling and I do not have a control when this respawned task is executed.

my work scenario is 
- I have a memory pool 
- tasks need workspace and workspace is allocated via memory pool
- the workspace size required in each task is irregular and the memory pool capacity tightly estimated
- a large number of thrads demand more workspace simultaneously.

so, there is a dynamic situation that a task want to allocate space but it may not available due to several reasons. anyway, it indicates that there are tasks to be processed and this thread is used for such computation. 

my intention is to make the code robust (not about performance, but I am pretty sure this does not hurt performance either as long as I can make all processors busy).

i am not sure if this example is analogous to mpi polling. maybe you can use "low" priority when the polling task is respawned so that it is not executed too often.

**Comment by hcedwar** [comment]
Yes - "low" priority where everything else is "high" or "regular"

**Comment by kyungjoo-kim** [comment]
no. ``respawn( this , scheduler , priority )`` is not working.

**Comment by hcedwar** [comment]
The above respawn should work, this is a bug.  @kyungjoo-kim : Aside from that, are you asking for a respawn dependence that is satisfied by any other task being deallocated?

**Comment by kyungjoo-kim** [comment]
uuummmm.... I think that I do something really stupid.... yes I did. the respawn without dependence is to reuse my code again as it includes some repeated pattern. i do this respawn instead of putting the same code block duplicated.

**Comment by kyungjoo-kim** [comment]
future array with stride ??? 

when I construct a block of futures with other meta information, for instance
```
struct block {
  int nrows, ncols;
  future_type future;
};

view<block*> A("blocks", 10);

// after tasking spawning and future is recorded here and I need to respawn this with dependence
// currently 
future_type *dep;  pool.alloc(dev, 10);
for (int i=0;i<10;++i) dep[i] = A(i).future;

respawn(this, when_all(dev,10), priority);

// can I do this with stride ? 
long offset = &A(0).future - &A(0), stride = sizeof(block);
respawn(this, when_all(A.data() + offset, stride, 10), priority);

// I think when the futures are already available, I do not need to pack them to pass dependence.


```

**Comment by hcedwar** [comment]
Bug fix for `respawn( this , scheduler , priority );` on task-dag branch.
