### ISSUE TITLE
Question: Best Portable way to get min, max, eps

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#942]
What's the best way to get something similar to `std::numeric_limits` min, max, eps. It appears that some of that work is done in `core/source/Kokkos_NumericTraits.hpp`.

If no best practice exists, consider:
* Placing the specializations w/in something like `Kokkos::numeric_limits<T>` (I think) would allow for the specializations to be removed from `reduction_identity`.

I might be able to help.

**Comment by mhoemmen** [comment]
What about Kokkos::ArithTraits, that used to be in Tpetra and is now in kokkos-kernels?

**Comment by mhoemmen** [comment]
@dholladay00 Also check out Kokkos::Details::InnerProductSpaceTraits, in the same place.  (We should probably promote that out of Kokkos::Details into a different namespace at some point.)  Its documentation explains why it exists and what it does.

**Comment by mhoemmen** [comment]
@dholladay00 wrote:
> When I add kokkos-kernels into my project, that looks like the way to do it.

kokkos-kernels gets snapshotted into Trilinos, just like Kokkos.  You don't have to do anything special to get kokkos-kernels, unless you want the bleeding-edge version.  Snapshots happen every few weeks.

> Side Question: Is there a timeline for kokkos-kernels dense linear algebra?

I'm not in charge of kokkos-kernels.

**Comment by dholladay00** [comment]
Yeah, I was originally not planning on incorporating kokkos-kernels into my project until the linear algebra features I need are in (thread team level gemm, gemv, getrs, and getrf). 

If I need to use a max/min, I'll probably just use the corresponding `reduction_identity::min/max` that gives me the value I need. I thought it worth pointing out that similar functionality to `numeric_limits` could be had w/o much additional code and numeric traits did not seem an unreasonable location for such a feature.

**Comment by mhoemmen** [comment]
@dholladay00 Best thing would be to talk to @kyungjoo-kim about team-level dense linear algebra in kokkos-kernels.



> I thought it worth pointing out that similar functionality to numeric_limits could be had w/o much additional code and numeric traits did not seem an unreasonable location for such a feature.

I didn't actually know there was such a thing as `Kokkos::numeric_traits`.  Perhaps we should merge these two classes, insofar as that makes sense?

**Comment by ibaned** [comment]
there is no `Kokkos::numeric_traits`, but there is the file `core/src/Kokkos_NumericTraits.hpp` that defines `Kokkos::reduction_identity<T>` to assist `Kokkos::parallel_reduce` and its associated functors.

**Comment by dholladay00** [comment]
Indeed, no `Kokkos::numeric_traits`. However, `reduction_identity` already contains portable implementations for getting the min/max (albeit in an obfuscated interface).

If this is desired functionality, one could move the specializations currently contained in `reduction_identity` into something like `numeric_limits` and let `reduction_identity` utilize those traits, then `reduction_identity` wouldn't need any of the specializations. You could get portable `std::numeric_limits`-like functionality for not many more lines of code (if functionality is desired). 

If functionality is not desired, then might not be worth it, but again, the costs don't appear to be large, at least for `min` and `max`.

I could also imagine having a smaller capability (than ArithTraits) w/in Kokkos core and letting `ArithTraits` wrap `Kokkos::numeric_traits` where functionality is the same. 

But I'm not a Kokkos dev so what I say is merely a suggestion.

**Comment by dholladay00** [comment]
@kyungjoo-kim, is it possible to get a timeline on Kokkos-Kernels? I have particular interest in team-level dense linear algebra. 

It's not critical at the moment, but it would be useful to have an estimate on when that capability will be available. We can discuss offline further if need be.

**Comment by mhoemmen** [comment]
@dholladay00 Could you please open a new issue regarding kokkos-kernels' timeline for team-level  dense linear algebra?  That would help the team track things better.  Thanks!

**Comment by dholladay00** [comment]
Sure, it is kokkos-kernels issue [39](https://github.com/kokkos/kokkos-kernels/issues/39).

**Comment by mhoemmen** [comment]
Thanks! :D
