### ISSUE TITLE
nvcc_wrapper no input files

### ISSUE THREAD

**Issue by tomdeakin** [kokkos/kokkos#945]
I've been having an issue with the `nvcc_wrapper`. The issue is there is no whitespace between the ending comma `,` of the `-Xcompiler` flag and the source file. This results in `nvcc` complaining there is no input file.
After setting `dry_run=1` in the wrapper, I get for example:
```
nvcc -ccbin g++ -arch=sm_35 -O3 -DUSE_KOKKOS -I./ -I/nfs/modules/kokkos/2.03.05-gcc54-kepler35/include -I/nfs/modules/kokkos/2.03.05-gcc54-kepler35/include -I/nfs/modules/kokkos/2.03.05-gcc54-kepler35/include --std=c++11 -c -o obj/data_c.o -Xcompiler -fopenmp,src/data_c.c
```

Adding a space on line 211 of `nvcc_wrapper` possibly fixes this, however the compiler (GCC 5.4) then can't find the `cstdint` header.
`xcompiler_args="$xcompiler_args, $1"`

**Comment by tomdeakin** [comment]
I configured Kokkos 2.03.05 as ```../generate_makefile.bash --make-j=4 --arch=Kepler35 --with-openmp --compiler=`which g++` --with-options=aggressive_vectorization --with-cuda-options=enable_lambda```
Using GCC 5.4.0 and CUDA 7.5.18.

**Comment by crtrott** [comment]
Is it possible your issue is that you try to compile a .c file? nvcc_wrapper has an explicit list of what it considers to be a source file, and that does not include .c (since we expected only c++ files, which considering that --std=c++11 is set seems to be the case for you as well).

**Comment by tomdeakin** [comment]
Thanks @crtrott - it seems to work OK if I use a C++ extension for the files. I don't know why this code uses `.c` as the files actually contain C++ ...!!!
