### ISSUE TITLE
CMake: split kokkos.cmake into compiler, architecture and kokkos specific files

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#947]
In order to leverage our cmake logic for setting compiler and architectures specific flags inside of Trilinos, we would like to split the kokkos.cmake into three files:
* Compiler Detection: figure out type and version of compiler
* Architecture Settings: set the correct architecture flags based on user option for architecture and the detected compiler
* Kokkos specific options.

**Comment by hcedwar** [comment]
This may no longer be desired given PR #1106

**Comment by ibaned** [comment]
Assuming not desired, reopen otherwise.
