### ISSUE TITLE
Move ArithTraits to Kokkos core?

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#956]
As a follow-on to #942, this issue opens discussion on three questions:

1. whether `Kokkos::ArithTraits` is functionality that belongs more in the `kokkos` repository than the `kokkos-kernels` one.

1. whether `Kokkos::ArithTraits` should then be combined with `Kokkos::reduction_identity`

1. whether the result should be named in a way that is more consistent with the C++ standard library (as hinted at by @dholladay00), for example `Kokkos::numeric_limits` or `Kokkos::numeric_traits`. Likewise for the names of the functions.

**Comment by mhoemmen** [comment]
ArithTraits was written to be mostly backwards compatible with Teuchos::ScalarTraits.  If you decide to move this to Kokkos, it would be good to have a narrower interface, I think.
