### ISSUE TITLE
ROCm: Environment variables needed to be set for running

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#960]
This is stuff needing setting right now: 
```
export CPATH=/usr/include/libcxxabi
export HCC_OPT_FLUSH=0
```

**Comment by chipfreitag** [comment]
Neither variable is required in the most recent ROCm/HCC release.  Here is the version info:
chipf@paryzen3:/tmp/k1053$ uname -a
Linux paryzen3 4.11.0-kfd-compute-rocm-rel-1.6-127 #1 SMP Wed Aug 2 13:47:23 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chipfreitag** [comment]
Tested again with current -148 ROCm environment and associated compiler.  Neither variable required.
Closing issue.

**Comment by crtrott** [comment]
Can I simply do 'sudo apt update rocm' to update the rocm stack from teh currently installed 1.6.77 to 1.6.148?

**Comment by chipfreitag** [comment]
No.
Including my notes from out of band emails for completeness:
The procedure is found at https://github.com/RadeonOpenCompute/ROCm, but here’s the Cliff notes version that works very well for me:
 
First uninstall:
sudo apt-get autoremove rocm
sudo apt-get purge libhsakmt
sudo apt-get purge radeon-firmware
sudo apt-get purge $(dpkg -l | grep 'kfd\|rocm' | grep linux | grep -v libc | awk '{print $2}')
 
Some of those steps may not actually do anything. 
 
sudo reboot
 
Set up for the new repo:
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
 
(this will be a no-op if you’ve already done it)
 
and install the latest rocm:
sudo apt-get update
sudo apt-get install rocm
 
DO NOT use apt-get upgrade.  If you do, you’ll be rewarded with reinstalling from scratch.
 
Then 
sudo reboot
