### ISSUE TITLE
RangePolicy Question

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#968]
Say I'm using both CUDA and OpenMP backends and CUDA is the default execution space. If I have an implicit range policy like this:

`Kokkos::parallel_for(n,functor);`

will this always run in the default CUDA execution space? If so, is the only way to get it to run with the non-default OpenMP execution space this?

`Kokkos::parallel_for(Kokkos::RangePolicy<OpenMP>(0,n),functor);`

**Comment by mhoemmen** [comment]
@stanmoore1 wrote:
> ... will this always run in the default CUDA execution space?

Yes.

> If so, is the only way to get it to run with the non-default OpenMP execution space this?

Yes.  Also, labeling your parallel loops makes Kokkos profiling library output more readable:
```
parallel_for ("my awesome loop", RangePolicy<OpenMP> (0, n), functor);
```

**Comment by stanmoore1** [comment]
Even if the functor is templated on DeviceType?

**Comment by stanmoore1** [comment]
I'm trying to figure out if this code is valid or not: https://github.com/lammps/lammps/blob/master/src/KOKKOS/atom_vec_atomic_kokkos.cpp#L855. I think @crtrott wrote it, and it seems to work fine.

**Comment by hcedwar** [comment]
That looks problematic

**Comment by crtrott** [comment]
This works because the functor has an internal typedef which specifies the execution space. That was how users were supposed to define where to execute something 4 years ago, before we went to lambdas. That said in the future we would prefer the specification over the policy.

**Comment by stanmoore1** [comment]
@crtrott got it, that make sense. Thanks!
