### ISSUE TITLE
Task dependence upon successfull allocation from arbitrary memory pool

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#974]
@kyungjoo-kim Your memory-constrained task-dag algorithm has a dependence on the successful allocation of memory from a memory pool.  Brainstorming possibilities:

1. `Future<void*> f = scheduler.when_allocate( pool , size );` returns a future that is ready when the allocation from `pool` of `size` bytes succeeds.  If the allocation immediately succeeds then the future is immediately complete.

1. `Future<void> f = scheduler.when_available( pool , size );` returns a future that is ready when allocation from `pool` of `size` bytes could succeed.

**Comment by hcedwar** [comment]
For the `when_allocate` version: 

1. when the future reference count goes to zero then the associated memory is deallocated.

1. require an explicit call to `scheduler.deallocate(f)`

**Comment by hcedwar** [comment]
Further design brainstorming:
```c++
  Future<PoolAlloc> f = scheduler.when_allocate( pool , size ); 
    // f is ready when allocation is successful

    // at a future time when f is ready
    // a one-time (atomic) transfer of ownership for allocated memory
    // first call to get returns memory allocated from pool.allocate(size);
  void * ptr = f.get();
  assert( 0 == f.get() ); // all subsequent calls return 0
```

**Comment by dhollman** [comment]
@crtrott I'd like to start by making this less of an issue to begin with by making failed memory allocations boost-block on waiting tasks, and only fail if that doesn't free up enough memory.

**Comment by crtrott** [comment]
Sure :-)
