### ISSUE TITLE
Tagged shared memory requests for multi-operator functor

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#98]
A functor with multiple `TeamPolicy` operators differentiated by tags
`void operator()( const TagA & , const TeamPolicy<...>::member_type & ) const ;`
should have a per-operator shared memory size request that is also differentiated by the corresponding tag.

**Comment by crtrott** [comment]
Subsume that in the lambda shared memory request for now: 
#81

**Comment by crtrott** [comment]
Yeah I think we can close this with the resolution of #81. I don't think the additional complexity in the code base is worth it.
